### ISSUE TITLE
Pack liquidsoap wtih snap package

### ISSUE THREAD

**Issue by skhalymon** [savonet/liquidsoap#1003]
**Is your feature request related to a problem? Please describe.**
Currently dependencies that ships with liquidsoap deb package could conflict with already installed dependencies. Many of issues are related to some dependencies problem. This make bad end user experience. 

**Describe the solution you'd like**
We can pack whole liquidsoap into **snap**. It become kind a standard in Linux world for packaging this kind of apps. All related dependencies would be only inside the package and wont interconnect with rest of the system. It's good isolation practice. The only thing that I didn't find some example to package some OCaml apps into snap, but think it shouldn't be a problem.

**Describe alternatives you've considered**
The docker could be as option as well, but it's less useful from user perspective than snap package.

Flatpack as an alternative standard from RedHat

**Additional context**
Guide to create snap package.
https://snapcraft.io/docs/creating-a-snap

**Comment by smimram** [comment]
Unstaling, we should really do this some day.
