### ISSUE TITLE
Ubuntu packages need updating

### ISSUE THREAD

**Issue by whatthefork** [savonet/liquidsoap#1030]
The Ubuntu packages are sorely out of date, the liquidsoap version for the packages is 1.1.x. Can someone please update those, and also provide packages for Ubuntu 18.04?

**Comment by Infernion** [comment]
Have tried install 1.4 version from apt repository? Here is instruction https://github.com/savonet/liquidsoap/blob/master/doc/content/install.md

You need first add apt repository and then install from it

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20D63CCDDD0F62C2
sudo apt update
sudo apt install liquidsoap-1.4
```

**Comment by smimram** [comment]
Yes, this is the best we can offer here, for official packages, please report directly to Ubuntu: https://launchpad.net/ubuntu/+source/liquidsoap/+bugs

**Comment by whatthefork** [comment]
Thanks for the info, much appreciated!

**Comment by paddatrapper** [comment]
18.04 is a stable release, so will not see a major version bump. Ubuntu 20.04 will have a more up to date version if you wish to stay on LTS and Ubuntu repos. Ubuntu 19.04 also has an updated version

**Comment by smimram** [comment]
Based on the answers, I guess we can close this now.
