### ISSUE TITLE
Usage of gTTS (gtts-cli) in liquidsoap

### ISSUE THREAD

**Issue by count00zero** [savonet/liquidsoap#1034]
Dear Team,

do you think it would be possible to write a specific protocols.liq which would be able to enable / facilitate the usage of gtts via gtts-cli (https://github.com/pndurette/gTTS)  for liquidsoap.

Or maybe my question should be: can anyone of you try it or do it?

That would help a lot, because I am very dissatisfied with the voices available on linux (and the usage of sapi via wine is also not doable for me)

thanks in advance and BR,
count

**Comment by count00zero** [comment]
Hey there,

solved it myself; created the following in my protocols.liq
```

#register the gtts-cli protocol using gtts-cli
register(name="gttscli protocol settings","protocol.gttscli",())
register(name="gttscli path","protocol.gttscli.path","/usr/local/bin/gtts-cli")
 
def gttscli_protocol(~rlog,~maxtime,arg) =
  binary = get(default="gttscli","protocol.gttscli.path")
  [process_uri(extname="mp3","#{binary} -o $(output) #{string.quote(arg)}")]
end
 
add_protocol(static=true,"gttscli",gttscli_protocol,
             doc="Generate speech synthesis using gtts-cli. Result may be mono.",
             syntax="gttscli:Text to read")
 
register(name="SayG protocol settings","protocol.sayg",())
register(name="Sox path","protocol.sayg.sox_path","sox")
 
def sayg_protocol(~rlog,~maxtime,arg) =
  sox = get(default="sox","protocol.sayg.sox_path")
  [process_uri(extname="mp3",uri="gttscli:#{arg}","#{sox} $(input) -c 2 $(output)")]
end
 
add_protocol(static=true,"sayg",sayg_protocol,
             doc="Generate speech synthesis using gtts-cli and sox. Result is always stereo.",
             syntax="sayg:Text to read")
```

Afterwards I address that in my radio.liq by using: `radio = sayg_metadata(radio)`

cheers :)

**Comment by count00zero** [comment]
Additional info: to get sox working on mp3 I had to: `sudo apt-get install libsox-fmt-all sox libchromaprint-dev`

**Comment by count00zero** [comment]
another addition ;-)
in my utils.liq i added:

```
def sayg_metadata
  p = 'sayg:$(if $(artist),"It was $(artist)$(if $(title),\\", $(title)\\").")'
  fun (s,~pattern=p) ->
    append(s,fun (m) -> request.queue(queue=[request.create(pattern % m)],
                                      interactive=false))
end
```

**Comment by smimram** [comment]
Great! Reopening so that we don't forget about adding something like this in the standard library.
