### ISSUE TITLE
fdkaac problem

### ISSUE THREAD

**Issue by BenHippynet** [savonet/liquidsoap#1039]
Hi,
I was wondering if anybody could offer any advice. Liquidsoap v1.4.0. fdkaac v0.6.3 running on Ubuntu 18.04.3.
I'm trying to set up a transcoder and in the .liq script I'm using the line:

`%fdkaac(channels=2, samplerate=44100, bitrate=48, afterburner=false, aot="mpeg2_he_aac_v2", transmux="adts", sbr_mode=false),`

But I'm getting the error:

```
2019/11/20 05:29:31 >>> LOG START
2019/11/20 05:29:31 [main:3] Liquidsoap 1.4.0
2019/11/20 05:29:31 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.1 menhirLib=20190924 dtools=0.4.1 duppy=0.8.0 cry=0.6.4 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 mad=0.4.5 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.3.1 ffmpeg=0.4.1 samplerate=0.1.4 taglib=0.3.6 camomile=1.0.2
2019/11/20 05:29:31 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/11/20 05:29:31 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/11/20 05:29:31 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/11/20 05:29:31 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/11/20 05:29:31 [sandbox:3] Sandboxing disabled
2019/11/20 05:29:31 [video.converter:3] Couldn't find preferred video converter: gavl.
2019/11/20 05:29:31 [audio.converter:3] Using samplerate converter: ffmpeg.
2019/11/20 05:29:31 [clock.wallclock_main:2] Error when starting output /mearnsfm: Invalid configuration!
2019/11/20 05:29:31 [clock.wallclock_main:3] Raised by primitive operation at file "fdkaac.ml", line 208, characters 4-19
2019/11/20 05:29:31 [clock.wallclock_main:3] Called from file "list.ml", line 110, characters 12-15
2019/11/20 05:29:31 [clock.wallclock_main:3] Called from file "encoder/fdkaac_encoder.ml", line 99, characters 4-49
2019/11/20 05:29:31 [clock.wallclock_main:3] Called from file "encoder/fdkaac_encoder.ml", line 103, characters 14-32
2019/11/20 05:29:31 [clock.wallclock_main:3] Called from file "outputs/icecast2.ml", line 511, characters 12-46
2019/11/20 05:29:31 [clock.wallclock_main:3] Called from file "tools/start_stop.ml", line 99, characters 6-16
2019/11/20 05:29:31 [clock.wallclock_main:3] Called from file "clock.ml", line 237, characters 19-37
2019/11/20 05:29:31 [/starpointmp3:3] Connecting mount /starpointmp3 for source@stream2.hippynet.co.uk...
2019/11/20 05:29:31 [/starpointmp3:3] Connection setup was successful.
```

If I remove aot="mpeg2_he_aac_v2" liquidsoap will start and connect but no audio is passed. I've seen similar lines in examples, but can anybody offer any advice why it doesn't work in this case?

Thanks everybody!

**Comment by autonarcosis** [comment]
You are requesting mpeg2 meant for mpeg4 encapsulation.  mpeg2 is for ts and ps streams, not icecast.  As a side note; Afterburner is recommended to always be enabled. HE AAC V2 is SBR, so disabling it you might as well use AAC.  And the recommended sampling rate is 48khz at the bit rate you are streaming at.  Use this and it should work;

`afterburner=true, samplerate=48000, bitrate=48, aot="mpeg4_he_aac_v2", transmux="adts"`

**Comment by toots** [comment]
Hi! Closing this as I believe @autonarcosis did provide the response. Let us know if that doesn't work for you.

**Comment by BenHippynet** [comment]
Hi,

sorry for the late reply, I've only just had a chance to get back to this and didn't want to leave it without saying thanks. That solution worked great. Thanks @autonarcosis 

Ben
