### ISSUE TITLE
Floating point exception 

### ISSUE THREAD

**Issue by SergeDeMaseneer** [savonet/liquidsoap#1040]
I am getting an floating point exception on all commands so i suspect a faulty installation. I am using Debian Buster (10.1) which comes with version 1.3.3-2 but instead i find a map /usr/local/lib/liquidsoap/1.2.1. I must say that this Debian install is an update from a previous version (not a clean install) so i suspect some wrong files on the computer. 
My question is: how can i remove everything concerning liquidsoap so that i can reinstall a working version? I tried to uninstall with apt remove liquidsoap but when i reinstalled it still found a lot of "things" from the previous install.
Thanks in advance

Serge

**Comment by SergeDeMaseneer** [comment]
Just purged liquidsoap an manualy deleted everything pointing to the new and old version i found on my system. After reïnstalling liquidsoap it threw once more the floating point exception....

**Comment by smimram** [comment]
My guess would be Ladspa or frei0r plugins, can you try to remove those from your system?

**Comment by SergeDeMaseneer** [comment]
Sorry that it took me so long to get back since i was busy with some urgent matters. 
Pakket 'liquidsoap-plugin-ladspa' is niet geïnstalleerd.
Pakket 'liquidsoap-plugin-frei0r' is niet geïnstalleerd.
Dutch  for "not installed". So those plugins can not be the culprits.
So back to squaire one....

**Comment by smimram** [comment]
Ok, let's try something else then could you please run your script under gdb to get a stacktrace. If you've never done it it's easy: install the `gdb` package and then run
```
% gdb --args liquidsoap yourscript.liq
> r
(...process crash...)
> bt
```
and paste here the output.

**Comment by SergeDeMaseneer** [comment]
i'll do that on monday since currently i'm on a businesstrip in Germany.

**Comment by SergeDeMaseneer** [comment]
actualy it didn't do anything, before liquidsoap was processing anything the error occured. But this did the trick for my Debian buster:
[sudo] apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20D63CCDDD0F62C2
[sudo] echo deb http://deb.liquidsoap.info/debian stable main >> /etc/apt/sources.list.d/liquidsoap.list
[sudo] apt update
[sudo] apt install liquidsoap-master

it replaced the existing liquidsoap with another (Liquidsoap 1.5.0) version and everything works.

**Comment by smimram** [comment]
Good to hear. I'm closing this bug report, please reopen if the bug shows up again.

**Comment by SergeDeMaseneer** [comment]
I apreciated all the help very much. Thank you all!!!!
I consider this case closed
