### ISSUE TITLE
How to dynamically manage a playlist

### ISSUE THREAD

**Issue by tristan-nel** [savonet/liquidsoap#1043]
I'm finding the documentation a little confusing.

I'm developing a React Native app which will play an audio stream administrated by another React Native App. The media player in the Listener app already successfully plays a simple Liquidsoap-to-Icecast2 stream.

The administrator app will have a library of songs that you can insert into a list, and the Liquidsoap server should play through the songs in that list in order.
The list is tracked real-time in Google Cloud Firestore.
The songs/order can be modified at any time using the administrator app.
The currently playing song must complete, and then the Liquidsoap server should continue to the next song in the list.
The song files are stored in Google Cloud Storage.

Should I be using `playlist`, or `request`, and which method specifically is most appropriate for my use-case?

I have been attempting to simply create a `playlist(URI, reload=150)` where URI is a playlist.m3u file on Google Cloud Storage - but when I replace the playlist.m3u file, the stream does not reflect the changes, and simply keeps playing the old playlist.

I would appreciate any assistance

**Comment by Euguar** [comment]
Hi, tristan-nel.

You may to use `reload_mode="watch"` simple parameter. It will be reload the playlist’s file whenever it is changed.
E.g: `playlist(reload_mode="watch")`

Or use this combination of parameters: `reload="150"` with `reload_mode="seconds"`. It will be reload the playlist’s file every 150 seconds.
E.g: `playlist(reload_mode="seconds", reload=150)`

See documentation mindfully: [https://www.liquidsoap.info/doc-1.4.0/reference.html#playlist](https://www.liquidsoap.info/doc-1.4.0/reference.html#playlist)

Good luck!

**Comment by tristan-nel** [comment]
@Euguar after some further research, it seems what I need is `request.equeue`.

How can I make an HTTP POST (JSON) to an endpoint to push a track to the request queue?
What I currently have is not working, I just get the following output in the console:

> At line 15, char 2-41:
Warning 3: This expression should have type unit.
No output defined, nothing to do.

Here is the script:

```
# Log dir
set("log.file.path","./radio.log")

# Settings
set("server.telnet", true)
set("server.telnet.port", 1234)
set("server.telnet.bind_addr", "0.0.0.0")
set("harbor.bind_addr", "0.0.0.0")

# Functions
def addrequest(~protocol, ~data, ~headers, uri) =
  arr = of_json(default=[("key","value")], data)
  track = arr["track"];
  log("adding request track '#{track}'")
  server.execute("request.push #{track}")
  # not skipping current song for now
  http_response(
    protocol=protocol,
    code=200,
    headers=[("Content-Type","application/json; charset=utf-8")],
    data='{"status":"success", "track": "#{track}", "action": "#{action}"}'
  )
end

# Allow posting of request
harbor.http.register(port=8040, method="POST", "/request", addrequest())

# Security
security = single("./default.wav")

# Auto DJ
music = nrj(
  playlist(
    mode="normal",
    "http://REMOTE_URL/music.m3u"
  )
)

# Jingles
jingles = playlist(
  "http://REMOTE_URL/jingles.m3u"
)

# Start building the feed with music
radio = random([music])

# Add the security, requests and smart crossfade
radio = fallback(
  track_sensitive=false,
  [
    crossfade(
      fallback([request.queue(id="request"), radio])
    ),
    security
  ]
)

# Now add some jingles
# One jingle every 7 songs
radio = random(weights=[1,7], [jingles, radio])

# Make safe
# radio = mksafe(radio)

# Add a skip command to the music stream
server.register(
  usage="skip",
  description="Skip the current song",
  "skip",
  fun(_) -> begin source.skip(radio) "Done!" end
)

# Talk over stream using microphone mount.
mic = input.harbor(
  "mic",
  port=8080,
  password="hackme",
  #buffer=1.0
  buffer=0.0
)
radio = smooth_add(
  #delay=0.8,
  delay=0.0, 
  p=0.15, 
  normal=radio, 
  special=mic
)

# Stream
output.icecast(
  %vorbis,
  host = "localhost",
  port = 8000,
  password = "hackme",
  mount = "miradio.ogg",
  radio
)
```

@toots maybe you could give me some guidance? The script runs fine without the `addrequest` function, but this is functionality I would like to have. Alternatively, should I look into using `request.dynamic` to fetch the next track URL from Google Cloud Firestore using an external script?

**Comment by smimram** [comment]
If you are not accustomed to Liquidsoap, the most simple is to go for `request.dynamic` and fetch next song from an url.

Alternatively, you could use `request.queue.pushable` and register an http endpoint with `harbor.http.register` which would call the push function on requests.

**Comment by tristan-nel** [comment]
So I ended up using request.dynamic, and using a python script to request what the next song in the user-managed playlist will be from Firebase:

In the liquidsoap server:

```python
# Functions
def get_request() =
  uri = list.hd(default="", get_process_lines("python3 request.py"))
  request.create(uri, persistent=true)
end

# Requests
requests = request.dynamic(
  id="requests",
  conservative=false,
  get_request
)
```

In the python script:

```python
# ... get the next song info from Firebase
URL = next_song[const.URL]
new_now_playing = now_playing + 1
channel_ref.set({const.NOW_PLAYING : new_now_playing}, merge=True)
print(URL)
```

**Comment by smimram** [comment]
Great, good luck with your project!

**Comment by quydox** [comment]
> ```python
> request.dynamic
> ```

Hello, can you tell me how to use requests in this script?

When I want to play new song from url, how can I do?

**Comment by carrzkiss** [comment]
Hello, [tristan-nel](https://github.com/tristan-nel).

I am working on a project that gets the playlist from a database and loads it into Liquidsoap.
I've looked at what you provided here, but I don't know how to use it.
Could you come in and provide some insight on its use and how to make it work?

Thank You.
Wayne
