### ISSUE TITLE
Documentation: Request Sources example not working

### ISSUE THREAD

**Issue by ricardojorgerm** [savonet/liquidsoap#1048]
In the request_sources.md, the following line in the example:
```
result =
    list.hd(
      get_process_lines("my_script my_params")) 
```

Generates the error:
```
this value has type
    (default:_)->_
  but it should be a subtype of
    string
```
Which according to @smimram is due to the fact that one

> should always provide a default argument to the list.hd function which specifies the value which is returned when the list is empty 

In general, the documentation seems to be lacking an explanation on its notation, which makes it difficult to understand if some argument is mandatory or optional, especially for new users (I then understood: the usage of "?" marks the optional arguments). Additionally, the documentation for `request.create` fails to make clear what `indicators` and `persistent ` options are.

**Comment by smimram** [comment]
Thanks for this bug report, this is really helpful to improve the documentation. I have updated the `list.hd`, leaving this open to think about fixing other points.
