### ISSUE TITLE
Passing through an ingest source without re-encoding

### ISSUE THREAD

**Issue by kleinadam** [savonet/liquidsoap#1053]
Hi all, 

Is there a way to pass through an input.http source without re-encoding? It makes no sense due to performance to transcode a MP3 128 kbps input stream if output should be MP3 128 kbps as well. 

Regards,
Adam

**Comment by smimram** [comment]
Unfortunately not, and there is no short term plan to support that. We know that users would like to have that but we cannot, the reason being that many operators such as crossfading, or sound normalization would not work with encoded data, and it would be very hard to implement correctly... Sorry!

**Comment by kleinadam** [comment]
Thanks for answer Smimram!
