### ISSUE TITLE
Image functions

### ISSUE THREAD

**Issue by MaddyCrowle** [savonet/liquidsoap#1055]
Is it possible to have an functions to work with images in the future? Why am I asking. I am working with cover art audio tag and its most frequent usage is displaying on website, or audio software, or an hand-devices (like smartphones), so image doesn't need to be very big, but have good quality. But most of images in cover art tags are too big. In purpose of saving traffic and keeping high displaying performance it would be right to resize it to a smaller one before send to an user. I can do it with other programming language, but, as I mentioned [here](https://github.com/savonet/liquidsoap/issues/960), it would be better to keep all tools in one box.

**Comment by smimram** [comment]
In principle, yes, but it would rather be on demand, i.e., you should tell us what you need so that we know with what to start. Also, we currently don't have a notion of image in Liquidsoap (we have videos, but you don't want to do the modifications everytime), but it would not be too hard to add I guess.

**Comment by MaddyCrowle** [comment]
For example I parsed cover art tag and have data like: width: 1920px, height: 1080px, and contents of image itself. I need to get the same image **but** with width: 500px, height: 300px and set proportions if needed (keep proportions or not). Function that would generate new image contents according to setted up parameters and contents of original image. Even to save image as a file not necessary, because final goal is to have image described in json.

**Comment by smimram** [comment]
In this case, I'd suggest converting everything to strings even though this is not very clean. You'd need records, which we don't have for now in Liquidsoap for now. BTW you are aware that `file.cover` was [added to Liquidsoap](https://github.com/savonet/liquidsoap/pull/987) to get cover-art, right?

**Comment by MaddyCrowle** [comment]
> You'd need records, which we don't have for now in Liquidsoap for now

Well, maybe one day in the future.

> BTW you are aware that `file.cover` was [added to Liquidsoap](https://github.com/savonet/liquidsoap/pull/987) to get cover-art, right?

Yea, but is it compatible with flac/ogg cover art tag? Any syntax usage?

**Comment by smimram** [comment]
Actually, this was easy to add, see #1058.

**Comment by MaddyCrowle** [comment]
So I can use `file.cover` to parse cover art tag from metadata, right? Is it [that](https://github.com/savonet/liquidsoap/issues/959#issuecomment-547843748) syntax?

**Comment by smimram** [comment]
Yes, `file.cover("myfile.ogg")` should return the contents of the cover image.

**Comment by MaddyCrowle** [comment]
do I need to rebuild liquidsoap from git repo to have this feature?

**Comment by smimram** [comment]
Yes, I just merged the support for covers in the master. Please rebuild.

**Comment by MaddyCrowle** [comment]
`git pull` says `Already up-to-date`
Deleted my repo, `git clone https://github.com/savonet/liquidsoap-full.git liquidsoap` again, then rebuilt.
wrote following code in my script:
```
def currently_playing_metadata(m) =
coverfile = "#{home_dir}/now/cover.jpg"
nocover = "#{home_dir}/now/nocover.txt"

mf = list.assoc(default="", "filename", m)
    cover = file.cover(mf)
    if cover != "" then
        ignore (file.write(data=cover, coverfile))
    else
        ignore (file.write(data="nocover", nocover))
    end
end
```

Always "nocover". Input audio is ogg. Are you sure it supports flac/ogg?

**Comment by smimram** [comment]
I have just updated liquidsoap-full. However, I rarely do so: you should use `make update` to update all the submodules in liquidsoap-full.

**Comment by MaddyCrowle** [comment]
Unfortunately can't make it works. Even have no idea why... I built liquidsoap-full from the scratch. I can parse metadata and cover manually via new binary functions, but that part with file.cover() doesn't work for me. Input: audio ogg, cover art tag is base64 encoded binary data.

**Comment by smimram** [comment]
Could you send a sample ogg file so that I can try (I fear that there are multiple conventions for storing coverart).

**Comment by MaddyCrowle** [comment]
Sure, [here it is](https://github.com/MaddyCrowle/filesamples/blob/master/04.%20Better%20Be%20Alone.ogg)

**Comment by smimram** [comment]
Thanks, this is not the format I had seen for metadata, stay tuned.

**Comment by smimram** [comment]
This should be fixed by 8771449b0d1c3b2f74879531d7040f985c9bccf4. Please reopen if not.

**Comment by MaddyCrowle** [comment]
still `nocover`, `mf` is the correct path to audio file, `cover` is empty. Was the fix added to liquidsoap-full or somewhere else?

**Comment by MaddyCrowle** [comment]
I did `make update`, rebuilt it and now it works as expected. You did the great job, thanks a lot! Actually I think no need to develop any other image functions here according to the topic, `file.cover` should be enough.

**Comment by smimram** [comment]
Great to hear, happy new year too!
