### ISSUE TITLE
Arrays in OCaml / Liquidsoap

### ISSUE THREAD

**Issue by MaddyCrowle** [savonet/liquidsoap#1056]
Is it possible to create an array with mixed type of data?
Because, for example:
```
blabla = [
        ("a", 1),
        ("b", "123")
    ] 
```
cause error:

```
At line 70, char 8-20:
Error 5: this value has type
  _ * string
but it should be a subtype of the type of the value at line 69, char 8-16
  _ * int
```

**Comment by smimram** [comment]
No, what would be its type?
- `[1, 2] ` is a list of integers
- `["a", "b"]` is a list of strings
- etc.
- your `blabla` is a list of ???

Remember that we check types before running the program!

That being said, if you explain what you are trying to do, we might have ideas about how to do this.

**Comment by MaddyCrowle** [comment]
I need something like `struct` in C, or classes, but classes is too huge data structure here I think. Main target - is to be able to build a nested arrays:

```
item1 -> "value",
item2 -> "value",
item3 -> children -> item1 -> "value",
                                 item2 -> "value"
item3 -> "value"
```

**Comment by toots** [comment]
Hi! I'm afraid that this is a limitation of the current language design. We've been discussing adding support for hashes for a while but it's not there.

The closest you can do for now is tuples. They work like this:
```ruby
x = (1, "abc", [1,2], "def")

let (y,t,u,v) = x
# y = 1, t = "abc", etc..
```

**Comment by smimram** [comment]
We now have support for records, which should be the solution. For instance,
```
song = { filename = "song.mp3", duration = 257., bpm = 132. }
```
see [the doc](https://www.liquidsoap.info/doc-dev/language.html#records).
