### ISSUE TITLE
Error 4: Undefined variable rewrite_metadata

### ISSUE THREAD

**Issue by snblitz** [savonet/liquidsoap#1062]
**Describe the bug**
I inherited an system with liquidsoap 1.3.3.  I have no idea how it was built.
I made a copy of the setup and built liquidsoap 1.4.0 following the Opam path.
When I run liquidsoap against a config I get
Error 4: Undefined variable rewrite_metadata

The identical config works fine on the other machine with the older liquidsoap setup.

**To Reproduce**
See Describe the Bug

**Expected behavior**
Version 1.3.3 and 1.4.0 will work equally well with the same config.

**Version details**
 - OS: debian
 - Version 10

**Install method**
opam
opam depext taglib mad lame vorbis cry samplerate liquidsoap alsa
opam install taglib mad lame vorbis cry samplerate liquidsoap alsa

perhaps a module is missing?

**Comment by Infernion** [comment]
You could comment the unused variable and you're script would work

**Comment by smimram** [comment]
`rewrite_metadata` was removed in 1.4.0 (and deprecated before), see commit 0023c80901949512da8b415ca638d30813a50974. You can add the following at the beginning of your file to get it back:
```
def rewrite_metadata(l,~insert_missing=true,~update=true,~strip=false, s)
  def map(m)
    def apply(x)
      label = fst(x)
      value = snd(x)
      (label,value % m)
    end
    list.map(apply,l)
  end
  map_metadata(map,insert_missing=insert_missing,update=update,strip=strip,s)
end
```
