### ISSUE TITLE
Video streaming questions

### ISSUE THREAD

**Issue by MaddyCrowle** [savonet/liquidsoap#1063]
I have few questions about video streaming using Liquidsoap:

**1.** Theora, i have the following code:

```
%ogg(
        %theora(
            quality=63
        ), 
        %vorbis(

        )
    ),
```

**a:** I can't setup quality more than 63, it means output video always will be more worse quality than original, right?
**b:** if i try to setup width/height, even from [example ](https://www.liquidsoap.info/doc-dev/encoding_formats.html) width=640, height=480, streaming fails with error `[clock.main:2] Source Ultra_Video_Streaming failed while streaming: Theora.Invalid_data!`. If I don't setup width/height streaming goes fine but always 320 x 240. What do I do wrong here?
**c:** is it possible to have input video in webm/avi/mpeg and output in ogg/webm/avi?

**2.** What is the best way to stream video with HD quality using Liquidsoap (good video quality, high resolution)?

**Comment by smimram** [comment]
a. Not sure
b. Concerning video size, you should use something like
```
set("video.width", 640)
set("video.height", 480)
```
c. Yes Liquidsoap can decode/encode from/to most formats

2. I would say ffmpeg, see in particular #1038 for latest improvement which should be merged soon (people have reportedly streamed in 1080p live on youtube using this).

**Comment by autonarcosis** [comment]
Theora is a lossy compression. There will always be some sort of degradation of the original video.  In my experience Theora is best with standard definition frame sizes (anything below 720p).  The Quality setting is a VBR setting and the higher the number the better the quality, but higher bitrate.  I believe the defaults are quality=25 and 320x240 for framesize if not set.
If you are looking for HD framesizes I would suggest x264. But also expect high bitrates of 3Mbps+  for decent quality.

**Comment by MaddyCrowle** [comment]
I'm trying to build Liquidsoap from liquidsoap-full repo with ffmpeg library, but the error has appeared:

```
File "converters/audio/ffmpeg_audio_converter.ml", line 23, characters 20-37:
23 | module Swresample = FFmpeg.Swresample
                         ^^^^^^^^^^^^^^^^^
Error: Unbound module FFmpeg.Swresample
```
Could you point me how to fix it? ffmpeg and all dependences are installed, including swresample lib.

**Comment by toots** [comment]
Hi there! We have full support for internal `%ffmpeg` encoding for video now in the current `master`. Would you be interested to give it a try? We should be able to do pretty much anything that you can do with ffmpeg, including with the encoding params.

**Comment by MaddyCrowle** [comment]
@toots sure, would be glad!

**Comment by smimram** [comment]
I am closing this for now since it has been inactive for some time and would moreover be better suited for [discussions](https://github.com/savonet/liquidsoap/discussions).
