### ISSUE TITLE
Can't build liquidsoap-full

### ISSUE THREAD

**Issue by MaddyCrowle** [savonet/liquidsoap#1064]
I'm trying to build Liquidsoap from liquidsoap-full repo, but the error has appeared:

```
File "converters/audio/ffmpeg_audio_converter.ml", line 23, characters 20-37:
23 | module Swresample = FFmpeg.Swresample
                         ^^^^^^^^^^^^^^^^^
Error: Unbound module FFmpeg.Swresample
```

**Comment by smimram** [comment]
You need to install libswresample-dev and rebuild ffmpeg and Liquidsoap (or disable ffmpeg in PACKAGES). See also #816.

**Comment by MaddyCrowle** [comment]
I've managed to resolve previous issue, but could you point me please, what means next:
```
avutil_stubs.c:18:10: fatal error: pixel_format_stubs.h: No such file or directory
 #include "pixel_format_stubs.h"
```

**Comment by MaddyCrowle** [comment]
I've managed to resolve it. Linker couldn't find headers of few ffmpeg libs to include, i've checked, it searches them in path `/usr/include/ffmpeg`, but what if i've built ffmpeg in custom path? I've just copied these headers from custom path to `/usr/include/ffmpeg`, is there any more gentle way to point linker to these headers?

**Comment by smimram** [comment]
I guess the standard way to do this is something like
```
export CFLAGS="-I /dir/for/header/files"
```

**Comment by MaddyCrowle** [comment]
Ok, I think I am on the final stage of issues) could you help me please complete this task? I really would like to build dev version with ffmpeg myself, but I'm not very good in it. Now I have these errors (in the end of Liquidsoap building, right after `OCAMLOPT -o liquidsoap`):
```
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_init':
avdevice_stubs.c:(.text+0x20): undefined reference to `avdevice_register_all'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_audio_i                                                              nput_formats':
avdevice_stubs.c:(.text+0x1b4): undefined reference to `av_input_audio_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_video_i                                                              nput_formats':
avdevice_stubs.c:(.text+0x1f5): undefined reference to `av_input_video_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_audio_o                                                              utput_formats':
avdevice_stubs.c:(.text+0x364): undefined reference to `av_output_audio_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_video_o                                                              utput_formats':
avdevice_stubs.c:(.text+0x3a5): undefined reference to `av_output_video_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_app_to_dev_                                                              control_message':
avdevice_stubs.c:(.text+0x587): undefined reference to `avdevice_app_to_dev_control_message'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
```
I know it means linker didn't find definitions of these displayed functions, But I've manually checked include headers, they have definitions of requiring functions. I also copied libs (both static and shared) from built ffmpeg path to /usr/local/lib and checked `LD_LIBRARY_PATH` and `PATH`, everything seems fine... I'm stuck(

**Comment by smimram** [comment]
I guess
```
export LDFLAGS = "-L/path/to/library
```

**Comment by MaddyCrowle** [comment]
unfortunately, it didn't help
```
make clean
export CFLAGS="-I /dir/for/header/files"
export LDFLAGS = "-L/path/to/library"
./configure
make
```
The same errors.

**Comment by MaddyCrowle** [comment]
[here](https://github.com/MaddyCrowle/filesamples/tree/master/libavdevice) is the `libavdevice` headers

**Comment by toots** [comment]
Hi there! Have you tried with the latest `ocaml-ffmpeg`? Happy to fix the problem if it still occurs there..

**Comment by MaddyCrowle** [comment]
@toots not yet, gonna try it soon, I'll report result here. Thanks!

**Comment by MaddyCrowle** [comment]
@toots Well, I tried. `git fetch`, `make clean`, `make init`, `cp PACKAGES.minimal PACKAGES`, uncommented ffmpeg, `./bootstrap`, `./configure`, `make` and... the same error:

```
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_init':
avdevice_stubs.c:(.text+0x20): undefined reference to `avdevice_register_all'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_audio_i                                                              nput_formats':
avdevice_stubs.c:(.text+0x1b4): undefined reference to `av_input_audio_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_video_i                                                              nput_formats':
avdevice_stubs.c:(.text+0x1f5): undefined reference to `av_input_video_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_audio_o                                                              utput_formats':
avdevice_stubs.c:(.text+0x364): undefined reference to `av_output_audio_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_get_video_o                                                              utput_formats':
avdevice_stubs.c:(.text+0x3a5): undefined reference to `av_output_video_device_next'
/liquidsoap/ocaml-ffmpeg/src/libffmpeg_stubs.a(avdevice_stubs.o): In function `ocaml_avdevice_app_to_dev_                                                              control_message':
avdevice_stubs.c:(.text+0x587): undefined reference to `avdevice_app_to_dev_control_message'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
```
Maybe the problem is really in my compiled ffmpeg lib, but I'm not good enough to find out how to fix it. Could you please point to me what exactly steps do I need to do? Do I need `opam upgrade`, `opam install ffmpeg` and use opam version of ffmpeg? And how to point to liquidsoap builder opam ffmpeg lib?

**Comment by toots** [comment]
Hi! It looks to me that you're either missing some libraries or that they are outdated. Also, from what I can see you are compiling the old version of `ocaml-ffmeg`. Here's a quick step-by-step to install the latest version of `liquidsoap`
```sh
# Run the following as root or via sudo:
sed -e 's#main#main contrib non-free#' -i /etc/apt/sources.list
apt-get update
apt-get install -y --no-install-recommends aspcud autoconf automake build-essential \
  ca-certificates curl debhelper devscripts fakeroot git openssh-client unzip gnupg \
  dirmngr apt-transport-https

# Run as regular user:

# If you haven't configured opam yet:
opam init -y --disable-sandboxing --compiler=4.10.0
opam install -y depext

# Now the main stuff:
git clone https://github.com/savonet/liquidsoap-full.git
cd liquidsoap-full
make init && make update
cat PACKAGES.default | grep '^ocaml' | cut -d'-' -f 2 | while read package; do 
  cd ocaml-$package && opam pin add -y --no-action . && cd ..; \
done && cd liquidsoap && opam pin add --no-action .
```
From there, you should be ready to roll via `opam` only. No configure, no hassle. Here's an example to install `liquidsoap` with `ffmpeg` and its external dependencies:
```sh
opam depext -i liquidsoap ffmpeg <other dependencies>
```

**Comment by MaddyCrowle** [comment]
All was successful, all has been installed, except ffmpeg:

```
#=== ERROR while compiling ffmpeg-avcodec.0.5.0 ===============================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(git+file:///opt/liquidsoap/liquidsoap-full/ocaml-ffmpeg#master#5275e466)
# path        ~/.opam/4.08.1/.opam-switch/build/ffmpeg-avcodec.0.5.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avcodec -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/ffmpeg-avcodec-30694-7d21e4.env
# output-file ~/.opam/log/ffmpeg-avcodec-30694-7d21e4.out
### output ###
# avcodec_stubs.c:1046:3: error: unknown type name ‘AVCodecParameters’; use ‘struct’ keyword to refer to the type
# [...]
#    struct
# In file included from avcodec_stubs.c:14:
# avcodec_stubs.h:9:32: warning: initialization of ‘int *’ from incompatible pointer type ‘struct AVCodecParameters *’ [-Wincompatible-pointer-types]
#  #define CodecParameters_val(v) (*(struct AVCodecParameters**)Data_custom_val(v))
#                                 ^
# avcodec_stubs.c:1046:29: note: in expansion of macro ‘CodecParameters_val’
#    AVCodecParameters * dst = CodecParameters_val(ans);
#                              ^~~~~~~~~~~~~~~~~~~
# avcodec_stubs.c:1048:6: error: request for member ‘codec_id’ in something not a structure or union
#    dst->codec_id = SubtitleCodecID_val(_codec_id);
#       ^~



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ffmpeg-avcodec 0.5.0
└─

```

My OS is CentOS 7, it seems media things much easier to install on Ubuntu...

**Comment by MaddyCrowle** [comment]
I tried the same on fresh installed Ubuntu - the same error...

**Comment by toots** [comment]
@MaddyCrowle it looks like a case of outdated `ffmpeg`. Could you send me the full log you get via `opam install -v ffmpeg` so I can see if perhaps we can fix it within our own binding. Otherwise, you'd have to find a more recent version of ffmpeg.

**Comment by MaddyCrowle** [comment]
@toots sure, here is the full log file.

[ffmpeg-avcodec-install-log.zip](https://github.com/savonet/liquidsoap/files/4406336/ffmpeg-avcodec-install-log.zip)

**Comment by MaddyCrowle** [comment]
@toots Can I install ffmpeg from [here](ffmpeg.org)? If so, how can I link this lib to liquidsoap?

**Comment by toots** [comment]
It looks like your version of ffmpeg is too old indeed. You can try to:
* recompile by hand for a recent version (this can be difficult), or
* find an updated package for your distribution, or
* use a more recent distribution
The latest `master` branch for the binding should now have minimal versions checked at build time.

**Comment by MaddyCrowle** [comment]
I recompiled ffmpeg and now I have the latest version:

```
ffmpeg version N-97329-g5633f9a Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration:
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 78.102 / 58. 78.102
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.101 /  7. 77.101
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
```
Next do `opam depext -i liquidsoap ffmpeg` and have this error:
```
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ffmpeg-avcodec 0.5.0
+-
- No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed
before retrying:
    libavcodec-dev
```
But I have it: `libavcodec-dev is already the newest version (7:2.8.15-0ubuntu0.16.04.1).`

What do I do wrong?

**Comment by MaddyCrowle** [comment]
The full error listing:
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ffmpeg-avcodec failed at "/home/fortescue/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avcodec -j 1 @install".

#=== ERROR while compiling ffmpeg-avcodec.0.5.0 ===============================#
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.10.0 | pinned(git+file:///home/fortescue/projects/liquidsoap/liquidsoap-full/ocaml-ffmpeg#master#eb1506f9)
# path        ~/.opam/4.10.0/.opam-switch/build/ffmpeg-avcodec.0.5.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avcodec -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/ffmpeg-avcodec-15751-548b09.env
# output-file ~/.opam/log/ffmpeg-avcodec-15751-548b09.out
### output ###
# [...]
# (cd _build/default && /home/fortescue/.opam/4.10.0/bin/ocamlc.opt -w -40 -g -bin-annot -I avcodec/.avcodec.objs/byte -I /home/fortescue/.opam/4.10.0/lib/ffmpeg-avutil -I /home/fortescue/.opam/4.10.0/lib/ocaml/threads -no-alias-deps -open Avcodec__ -o avcodec/.avcodec.objs/byte/avcodec.cmi -c -intf avcodec/avcodec.mli)
# File "avcodec/avcodec.mli", line 178, characters 12-26:
# 178 |   type id = Codec_id.video
#                   ^^^^^^^^^^^^^^
# Error: Unbound type constructor Codec_id.video
#   ocamlmklib avcodec/dllavcodec_stubs.so,avcodec/libavcodec_stubs.a (exit 2)
# (cd _build/default && /home/fortescue/.opam/4.10.0/bin/ocamlmklib.opt -g -o avcodec/avcodec_stubs avcodec/avcodec_stubs.o -L/usr/local/lib -lavcodec -pthread -lm -lz -lva -lswresample -lm -lavutil -pthread -lva-drm -lva -lva-x11 -lva -lvdpau -lX11 -lm -lva -lXv -lX11 -lXext)
# Unknown option -pthread
# Unknown option -pthread
# /usr/bin/ld: /usr/local/lib/libavcodec.a(allcodecs.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
# /usr/local/lib/libavcodec.a: error adding symbols: Bad value
# collect2: error: ld returned 1 exit status
```
During the `opam depext -i liquidsoap ffmpeg` installation it also asks me if I want to install few `-dev` packages, including `libavcodec-dev`, I agreed and then the error appeared.
According to [ffmpeg documentation](https://launchpad.net/ubuntu/+source/ffmpeg), the `libavcodec-dev` is already included in package:

> ffmpeg package in Ubuntu
> ffmpeg: Tools for transcoding, streaming and playing of multimedia files
> ffmpeg-dbgsym: debug symbols for ffmpeg
> ffmpeg-doc: Documentation of the FFmpeg multimedia framework
> **libavcodec-dev**: FFmpeg library with de/encoders for audio/video codecs - development files

But after compilation ffmpeg there is no libavcodec-dev package in the system. How to point liquidsoap on these development files?

**Comment by toots** [comment]
Congratulations on installing ffmpeg! If you've done this step manually, there is no need to run `opam depext`, you can directly install the packages via `opam install <packages>`

**Comment by toots** [comment]
Now, it also looks like the compilation fails because it wasn't able to find your newly installed `ffmpeg`. Let's look at the following:
1. Where are the library files installed? Usually, for a locally built library, they would be at: `/usr/local/include/libavcodec` and etc.
2. If they are there, you might also have the `pkg-config` files used to detect the library files located at: `/usr/local/lib/pkgconfig/libavcodec.pc`
3. Then, what is the output of: `pkg-config --libs libavcodec` ?
4. Can you, again, send the `opam install --verbose ffmpeg-avcodec` logs?

The binding will look for the output of the command in #3, using the files from #2. If this does not work, it will defer to the compiler (usually `gcc` or `clang`) and hope that it finds the default path to the files, which may or may not be the path listed in #1. Eventually, the verbose logs should tell you a bit more about what's going on.

So, first step: run pkg-config command. It it does not work, locate the library files. If they are in an unusual path but still have the `pkgconfig` files, you can set the `PKG_CONFIG_PATH` environment variable to point `pkg-config` to those files (see: `man pkg-config` for more details about this variable).

If they are no `pkgconfig` files, you can use `CFLAGS="-I/path/to/include/directory"` to point the compiler to the proper `.h` headers and `LDFLAGS="-L/path/to/library/directory"` to point the linker to the proper `.so` library files.

**Comment by MaddyCrowle** [comment]
1. There are files in `/usr/local/include/libavcodec`
```
ac3_parser.h   avcodec.h  avfft.h       codec_id.h  dirac.h       dxva2.h  mediacodec.h  qsv.h    vdpau.h    videotoolbox.h   xvmc.h
adts_parser.h  avdct.h    codec_desc.h  d3d11va.h   dv_profile.h  jni.h    packet.h      vaapi.h  version.h  vorbis_parser.h
```
2. Yes, `/usr/local/lib/pkgconfig/` contains `libavcodec.pc`
3. The output is: `-L/usr/local/lib -lavcodec -pthread -lm -lz -lva -lswresample -lm -lavutil -pthread -lva-drm -lva -lva-x11 -lva -lvdpau -lX11 -lm -lva -lXv -lX11 -lXext`
4. [Here is the log file generated with -v](https://github.com/savonet/liquidsoap/files/4473574/ffmpeg-avcodec-install-log.zip)

**Comment by MaddyCrowle** [comment]
`/usr/local/lib/pkgconfig/libavcodec.pc` contains:
```
prefix=/usr/local
exec_prefix=${prefix}
libdir=/usr/local/lib
includedir=/usr/local/include

Name: libavcodec
Description: FFmpeg codec library
Version: 58.78.102
Requires: libswresample >= 3.6.100, libavutil >= 56.42.102
Requires.private: 
Conflicts:
Libs: -L${libdir}  -lavcodec -pthread -lm -lz -lva
Libs.private: 
Cflags: -I${includedir}
```

**Comment by MaddyCrowle** [comment]
Also, I installed ffmpeg via root, and work with opam via another user.
