### ISSUE TITLE
 Underrun! Trying to recover..

### ISSUE THREAD

**Issue by veyselolgun** [savonet/liquidsoap#1065]
Hello i am Veysel,
Firstly thank you for your program

I searched a lot about this error but i could not fix it, can you help me please ?
in the command line:
```
2019/12/20 15:52:30 [alsa_out(default):2] Underrun!
2019/12/20 15:52:30 [alsa_out(default):2] Trying to recover..
2019/12/20 15:52:31 [alsa_out(default):2] Underrun!
2019/12/20 15:52:31 [alsa_out(default):2] Trying to recover..
2019/12/20 15:52:31 [alsa_out(default):2] Underrun!
2019/12/20 15:52:31 [alsa_out(default):2] Trying to recover..
2019/12/20 15:52:31 [alsa_out(default):2] Underrun!
```
This is `/etc/liquidsoap/stream.liq` file contents:
```
#!/usr/bin/liquidsoap -v
set("frame.audio.size",4096)
radio = input.alsa(device="liq.input")
radio = filter(freq=1.,q=1.,mode="low",wetness=0.8,radio)
radio = mic_filter(radio)
nosound = blank()
stream = fallback(track_sensitive=false, [strip_blank(threshold=-60.,max_blank=3.,radio), nosound])
stream = amplify(1.,override="replay_gain", stream)

output.icecast(%vorbis(quality=1),
         host="127.0.0.1",
          port=8000, password="", genre="livestream",
           description="Live Stream from .......", mount="/stream",
            name="OGG-STREAM", user="source",
             url="..............", stream)

stream2 = input.http(max=90.,"http://............")
stream2 = amplify(3.0,stream2)
output.alsa(fallible=true, stream2)
```

**Comment by smimram** [comment]
You should bufferize the mic input (`radio`). Could you try to add
```
radio = buffer.adaptative(radio)
```
?

**Comment by veyselolgun** [comment]
Thank you, problem was solved via another developer. After COVID-19 i will add how it was solved here

**Comment by dannycorder** [comment]
This resulted in some very weird effects for me - slowing down and speeding up of the sound, quite noticeable.

> You should bufferize the mic input (`radio`). Could you try to add
> 
> ```
> radio = buffer.adaptative(radio)
> ```
> 
> ?

**Comment by smimram** [comment]
This is the point of `buffer.adaptative`, but it usually this goes unnoticed since the mismatch between speeds should be very small...

**Comment by dannycorder** [comment]
Yes, so I gather.  I was definitely using the wrong device definition as...

output.alsa(input.alsa()) was an underrun disaster zone

Whereas:

input.alsa(device="plughw:1,0") has worked like a charm with no underrun messages.

Appreciate this may be obvious to most users but just including it here in case others at the beginner level find it useful!

**Comment by veyselolgun** [comment]
> Yes, so I gather. I was definitely using the wrong device definition as...
> 
> output.alsa(input.alsa()) was an underrun disaster zone
> 
> Whereas:
> 
> input.alsa(device="plughw:1,0") has worked like a charm with no underrun messages.
> 
> Appreciate this may be obvious to most users but just including it here in case others at the beginner level find it useful!

Thank you for sharing. It has worked with no underrun error

**Comment by toots** [comment]
Happy to hear that! I just checked and the operators are using `"default"` for the default device. I'm not sure if there's anything more we could do here. Alsa can be finicky sometimes so even it `"default"` is supposed to be the "best" choice, it might not always be but we cannot know anything about that in advance.. I'll close, please re-open if needed!

**Comment by veyselolgun** [comment]
Actually i was late to say that it worked, but i feel need to give information even if i am late. Thank you for all. You can close it
