### ISSUE TITLE
Read a audio file once per hour

### ISSUE THREAD

**Issue by Ficreet** [savonet/liquidsoap#1067]
Hello,

I would like to make sure that every hour a file is read by liquidsoap, but that this file is only read once.
I have tried many methods but each time I have the same problem, either the file is not read, or it is read continuously until the end of the designated time.

If my information is unclear ask me and I'll rephrase it.
I enclose below the code I have
Thank you in advance!

```
tophs = once(single(default_duration=10.0, "/var/media/th.mp3"))

radio = switch([
	({ 0m - 3m }, tophs),
	({ true }, radio)
	])
```

**Comment by smimram** [comment]
Interesting question.

You can define, the function
```
def predicate.activates(~init=false, p)
  last = ref(not init)
  fun () -> begin
    cur = p()
    ans = (not !last) and cur
    last := cur
    ans
  end
end
```
which will detect when a predicate _becomes_ true. You should then be able to do something like
```
tophs = single(default_duration=10.0, "/var/media/th.mp3")

radio = switch([
	(predicate.activates({ 0m - 3m }), tophs),
	({ true }, radio)
	])
```

**Comment by Ficreet** [comment]
Sorry I'm late.

What does this function do, because in spite of the documentation I don't understand

Thank you in advance!

**Comment by smimram** [comment]
`predicate.activates(p)` is true when the predicate `p` *becomes* true, it won't be true again unless `p` becomes false before. Therefore `predicate.activates({0m - 3m})` will become true once within the 3 first minutes of the hour.

**Comment by smimram** [comment]
This was answered some time ago, I'm closing. Please reopen if there are further questions.
