### ISSUE TITLE
Liquidsoap does not play next song when jingle is played

### ISSUE THREAD

**Issue by bjarn** [savonet/liquidsoap#1074]
Hello,

First things first. I am currently using the following crossfade function in my liquidsoap configuration:
`radio = crossfade(fade_out=0.01, fade_in=0.01, default=(fun(a,b)->add(normalize=false,([b, a]))), conservative=true,  radio)`

My playlist entries all have the variables `liq_cross_duration` and `liq_cue_in` set. These are being generated by a python script which scans the songs.
`annotate:title="1000 Nights",artist="Frenship",duration="240.",song_id="efa1e16473d9dc4f202fb01bc8365cac",media_id="706",liq_cross_duration="9.80",liq_cue_in="0.",playlist_id="3":/var/azuracast/stations/xxx/media/xxx/165 - Frenship - 1000 Nights.mp3`

Now, my issue is. I play a jingle ever 2 songs. This jingle starts when the previous song is ending, the liq_cross_duration value. However, there are chances that there are jingles which are barely 1 or 2 seconds. When these are being played, the previous song is still fading out, but the jingle ended. 

What happens now is that there will be silence on the stream. I have been trying to figure out a way to force the next song to play after the jingle ended, even though the previous song is still fading out.

Is this possible? 

Thanks a lot!

**Comment by dbeiner** [comment]
Hi,

I guess we need the same result ?

Check my post : https://github.com/savonet/liquidsoap/issues/1086

**Comment by dbeiner** [comment]
Hi !

Nobody ?

Thank you !

**Comment by bjarn** [comment]
Hi @dbeiner, this doens't seem like the same issue.

Not sure if @toots is able to assist me on this one.

An example timeline of what I mean.

The red line is the entire timeline. 

The yellow line is the current playing track. At the first orange stripe, it starts fading out + starts the jingle (green line). However, the fade out takes longer than the duration of the jingle. So at the second orange stripe it ends the jingle and the next song (blue line) starts when the entire fade out has ended. So there's a quiet empty space between the end of the jingle and the start of the next song.

The desired effect is to start the next song when the jingle ends.

Thanks!

![Leeg](https://user-images.githubusercontent.com/14638441/75912815-13c18400-5e52-11ea-9b20-f5d23862f866.png)

**Comment by toots** [comment]
Hi! Have you tried to create a custom transition function when jjngles are being played? You should be able to:
* Add a metadata on the jingle track via your `annotate` URI, typically `type="jingle"`.
* Define a custom `cross()` transition function that checks for `type` in the ending and beginning track and returns a transition with no fade on the track that is a jingle.

Hope that helps! Feel free to come discuss it in our slack channel!

**Comment by toots** [comment]
This was closed in the too commits above.
