### ISSUE TITLE
crossfade smart=true inconsistencies

### ISSUE THREAD

**Issue by mooseh** [savonet/liquidsoap#1080]
**Describe the bug**
We have 3 servers all on completely the same os, hardware, network, running the same liq and pulling a playlist form the same location, we are using crossfade with smart enabled on a playlist

**To Reproduce**
run 3 replica liquidsoap instances on 3 machines (the same machine might work)
make sure the playlist is using crossfade(smart=true...

**Expected behavior**
the analysis of an identical will be wrong for absolutely no reason

**Version details**
 - OS: Debian Stretch (9)
 - Version 1.4.0 | 1.4.1

**Install method**
opam

**Some More information**
here is a log from all 3 servers
```
1580207046.121105 [tracks:3] Prepared "/opt/songs/80s/Daryl Hall  John Oates - You Make My Dreams.mp3" (RID 3).
1580207046.176269 [cross_8541:3] Analysis: -45.182854dB / -24.488184dB (4.98s / 4.98s)

1580207047.642619 [cross_8541:3] Analysis: -127.459195dB / -24.459510dB (4.99s / 5.01s)
1580207047.643371 [crossfade:3] new >= old + margin, old <= medium and new <= high.

1580207046.172648 [tracks:3] Prepared "/opt/songs/80s/Daryl Hall  John Oates - You Make My Dreams.mp3" (RID 3).
1580207046.219681 [cross_8541:3] Analysis: -45.182854dB / -24.488184dB (4.98s / 4.98s)
```
as you can see the middle one's analysis is way off here is the sync stats how server 02 made a wrong analysis putting the others out of sync with 02
![image](https://user-images.githubusercontent.com/17574472/73261425-f569c800-41c3-11ea-8142-929f47f80c94.png)

turning off smart resolved our sync issues.

**Comment by toots** [comment]
Hi, thanks for the report!

Could you describe the inconsistencies as you see them more in details? Smart crossfade decides the next transition based on the analysis of the ending track and beginning track, thus if the ending tracks are different, the analysis will result in potentially a different transition.

From what I can see from your logs, the beginning track seems to always be the same with a consistent DB analysis but the ending track might be different. Is that correct?

If you wish to have exactly the same transition for each new track then, indeed, turning `smart` to `false` would be recommended.

**Comment by mooseh** [comment]
Hey toots

so basically smart crossfade is infrequently detecting wrong levels on files, to go further into detail about the scenario above we have 3 soaps running they have been started using parallel curl to make sure they all start at exactly the same time therefore we have 3 streams all in "near sync".

the logs above are the transition into "/opt/songs/80s/Daryl Hall  John Oates - You Make My Dreams.mp3" from "/opt/songs/80s/Steve Winwood - Higher Love - Single Version.mp3"

all 3 servers are running perfectly in time of each-other until this transition happened
the log shows that for some reason server-02 detected -127.459195dB on the previous file so it performed a crossfade where as the other 2 servers detected -45.182854dB so they did not perform a crossfade throwing the servers out of sync even though the files are identical.

we also tested this to a central nginx server with the same result for good measure.

we have swapped to smart=false and have been de-sync free for 2 days solid

**Comment by toots** [comment]
Thanks for these details and detailed report. I will try to see what I can do about it. I am curious: how is that synchronization important for your project?

**Comment by mooseh** [comment]
We are using 3 liquidsoap instances, which are all started using a parrallel curl request so they start within ms of each other then we have icecast infronf of them serving content, should the primary soap fall over the transition is almost seamless as long as they are synchronized.

**Comment by toots** [comment]
Ok I see. This is pretty intense level of synchronization for us! But, let's see what we can do. 

Assuming all machines start with the same liquidsoap binary, same script, we have to find out the possible source of randomness/concurrency that can break this symmetry.. 

Do you have logs of instance 2 above (or similar situation) between the last correct transition and the first wrong one? I'm wondering if we could see a difference, for instance when fetching the next track/preparing it?
