### ISSUE TITLE
Liquidsoap fails to start when I create mount points with OPUS

### ISSUE THREAD

**Issue by ivellios1988** [savonet/liquidsoap#1081]
I have a serious issue with Liquidsoap since I updated my installation of Centova Cast on Tuesday. Liquidsoap doesn't get up when I create some mount points with streams in OPUS.

When I create mount points with MP3 or AAC then everything works fine. Creating a mount point with OPUS makes my instance of Liquidsoap dead like a dodo...

This is what I have in my log:
```
2020/01/29 13:48:18 [ogg.muxer:3] output_autodj: Could not find any opus encoder.
2020/01/29 13:48:18 [clock.wallclock_main:2] Error when starting output output_autodj: Not_found!
```
And here's the complete log:

https://pastebin.com/tfD9fXgB

I'm running Centova Cast on a VPS with CentOS 7. Opus libraries and opus-tools are installed and up to date, and there were no issues with OPUS at all until I updated Centova Cast. It looks like their update utility upgraded Liquidsoap to the newest version they have and for some reason, it's unable to find an OPUS encoder.

I tried contacting Centova's support development, however, they say that support for OPUS was removed from Liquidsoap as of version 1.3.7.

**Comment by smimram** [comment]
On our side opus support was never removed (it is still supported) and I don't remember of any problem related to it. I did not test that recently, but our daily build are compiled with opus support without any problem. So, the problem lies in the way Liquidsoap is compiled on Centova, over which we have no control...

**Comment by ivellios1988** [comment]
Turns out that, probably, Opam is a culprit here. Here's what I received from Centova's support: "To clarify, we specifically mentioned that this was removed from their repository. By that, we meant the Opam repository, which is what Centova Cast uses to download and install Liquidsoap on your server."

So, it looks like I need to try to build Liquidsoap on my server on my own. Huge 'thanks' to Opam for giving people a lot of trouble.

**Comment by smimram** [comment]
We are also maintaining the opam packages, and did *not* remove opus support in there: https://github.com/savonet/liquidsoap/blob/master/liquidsoap.opam#L93

This support is optional though: this means that you need to install opus with opam in order for it to be activated in Liquidsoap (but this did not change since ages).

**Comment by ivellios1988** [comment]
Eventually it turned out that, when updating Centova Cast installations, on some systems Opam installer failed tom 'communicate' with opus-devel. Let me post a solution provided by CC support department, for anyone who experienced an issue similar to mine (though commands can be executed only at one's risk):

yum -y install opus-devel #(if you're using a debian distribution, use apt-get instead of yum)
su -s /bin/bash ccuser
eval $(opam env)
opam install -y opus
exit
cp -a /usr/local/centovacast/.opam/4.07.1/bin/liquidsoap /usr/local/centovacast/liquidsoap/bin/

IMPORTANT: Bare in mind that this is an advanced procedure, that may break your installation if performed incorrectly. It may also not work at all in you specific environment, and you may end up with a broken build.

**Comment by smimram** [comment]
Glad you solved your problem, we can close this bug now I guess.
