### ISSUE TITLE
How to disable crossfade for specific playlist ?

### ISSUE THREAD

**Issue by dbeiner** [savonet/liquidsoap#1086]
Hi community !

I would like to know if it's possible to disable crossfade for specific playlist ?

So, I've a playlist with jingles and I want the next playlist (music) doesn't crossfade before the end of the jingle.

Thank you and have a good day !

David

**Comment by dbeiner** [comment]
Up ?

**Comment by toots** [comment]
Hi! The way to go is to use the smart mode of `crossfade` and decide on a specific transition depending on some metadata specific to the source.

The base doc is here: https://www.liquidsoap.info/doc-1.4.1/crossfade.html this gives you an example of a custom transition function. 

In your case, you might want to do two things:
* Inject a metadata specific to the jingle source, something like:
```ruby
jingles = <some source>

# Inject metadata
def add_stype_metadata(m) =
  [("stype","jingles")]
end
jingles = map_metadata(add_stype_metadata, jingles)
```

* Then, you can use that metadata in the transition:
```ruby
def crossfade (~start_next=5.,~fade_in=3.,
               ~fade_out=3., ~width=2.,
               ~conservative=false,s)
  high   = -20.
  medium = -32.
  margin = 4.
  fade.out = fade.out(type="sin",duration=fade_out)
  fade.in  = fade.in(type="sin",duration=fade_in)
  add = fun (a,b) -> add(normalize=false,[b,a])
  log = log(label="crossfade")

  def transition(a,b,ma,mb,sa,sb)
  # No transition if ending source is jingles:
  if list.assoc(default="", "stype", ma) == "jingles" then
     sequence([a,b])
    else
    # Crossfade!
    add(fade.out(sa),fade.in(sb))
  end

  cross(width=width, duration=start_next, 
        conservative=conservative,
        transition,s)
end
```

I haven't tested this code, but I hope it helps getting where you want to be!
