### ISSUE TITLE
libFDK fail

### ISSUE THREAD

**Issue by giabi** [savonet/liquidsoap#1088]
we had a problem with our stream, it had a fail with this message: 

[stderr:3] liquidsoap: libFDK/src/fixpoint_math.cpp:439: FIXP_DBL invSqrtNorm2(FIXP_DBL, INT*): Assertion `val > (FIXP_DBL)( ( (0.0) >= 0) ? ((( (double)(0.0) * (((INT64(1)<<(32-1)))) + 0.5 ) >= (double)(((signed)0x7FFFFFFF)) ) ? (INT)(((signed)0x7FFFFFFF)) : (INT)( (double)(0.0) * (double)(((INT64(1)<<(32-1)))) + 0.5)) : ((( (double)(0.0) * (((INT64(1)<<(32-1)))) - 0.5) <= (double)(((signed)0x80000000)) ) ? (INT)(((signed)0x80000000)) : (INT)( (double)(0.0) * (double)(((INT64(1)<<(32-1)))) - 0.5)) )' failed.

Liquidsoap version 1.4.4 running on Ubuntu 18.04

**Comment by toots** [comment]
Hi,
This could be a bug in libfdk. How did you install the fdk-aac library?

**Comment by giabi** [comment]
Hi Toots,

I've installed liquidsoap and fdkaac with Opam, libfdk-aac-dev version 0.1.5-1 from ubuntu repository.

**Comment by toots** [comment]
Hi @giabi! I have `fdk-aac` `2.0.1` here. Now that I'm thinking about it, we had to do some emergency work when the version was bumped from `0.1.5` to `2.0.0` I believe so it's likely that these two version are not compatible. I'd suggest to try to update your `fdk-aac`. 

It looks like, however, that all version of ubuntu are pretty outdated: https://packages.ubuntu.com/search?keywords=libfdk-aac You might want to remove all deb packages and install it by hand from https://github.com/mstorsjo/fdk-aac

I'm gonna close this ticket but, please, feel free to reopen if you still see the issue with the latest version of `fdk-aac`. Thanks!
