### ISSUE TITLE
Problem handling video without audio muxed on mp4 container

### ISSUE THREAD

**Issue by jlopex** [savonet/liquidsoap#1090]
**Describe the bug**
I tried to create a rtmp stream from two isolated mp4 files, one that only contains video and another that only contains audio, then mux video and audio and stream it through Liquidsoap+gstreamer.

**To Reproduce**
First create two sample input files from FFmpeg, one with only video and another with only audio.

```
ffmpeg -f lavfi -i testsrc=duration=10:size=1280x720:rate=30 -an video.mp4
ffmpeg -f lavfi -i sine=frequency=1000:duration=10 -vn -ac 2 audio.mp4
```

Then use those files on with Liquidsoap.

```
#!/usr/bin/liquidsoap -v
set("log.stdout",true)
set("log.level",10)
set("frame.video.width",720)
set("frame.video.height",576)
set("frame.video.samplerate",25)
set("gstreamer.add_borders", true)
video = drop_audio(single("video.mp4"))
audio = single("audio.mp4")
source = mux_video(mode="none", video=video, audio)
output.gstreamer.audio_video(
  video_pipeline="videoconvert ! x264enc pass=qual quantizer=20 tune=zerolatency ! video/x-h264,profile=baseline ! queue ! muxer.",
  audio_pipeline="audioconvert ! voaacenc bitrate=128000 ! queue ! muxer.",
  pipeline="mpegtsmux name=muxer ! tcpserversink recover-policy=keyframe sync-method=latest-keyframe",
  mksafe(source))
```

**Expected behavior**
Be able to stream the content in a loop, unfortunately Liquidsoap does not consider a valid content and refuses to stream.

I was able to stream successfully if video file contains audio and video muxed, but not when it does only contain video.

A small portion of the logs I obtain:

 ```
2020/02/09 13:47:07 [decoder:4] Decoder "FFMPEG" failed on "video.mp4": FFmpeg.Avutils.Error(Stream not found)!
2020/02/09 13:47:07 [decoder:4] Trying method "FLAC" for "video.mp4"...
2020/02/09 13:47:07 [decoder.flac:4] Invalid file extension for "video.mp4"!
2020/02/09 13:47:07 [decoder:4] Trying method "AAC" for "video.mp4"...
2020/02/09 13:47:07 [decoder.aac:4] Libfaad recognizes "video.mp4" as AAC (44100Hz,2 channels).
2020/02/09 13:47:07 [decoder:4] Trying method "MP4" for "video.mp4"...
2020/02/09 13:47:07 [decoder:4] Decoder "MP4" failed on "video.mp4": Faad.Failed!
2020/02/09 13:47:07 [decoder:4] Trying method "OGG" for "video.mp4"...
2020/02/09 13:47:07 [decoder.ogg:4] Invalid file extension for "video.mp4"!
2020/02/09 13:47:07 [decoder:4] Trying method "MAD" for "video.mp4"...
2020/02/09 13:47:07 [decoder:4] Trying method "GSTREAMER" for "video.mp4"...
2020/02/09 13:47:07 [decoder.gstreamer:5] [fakesink0] State change: NULL -> READY
2020/02/09 13:47:07 [decoder.gstreamer:5] [audioresample0] State change: NULL -> READY
2020/02/09 13:47:07 [decoder.gstreamer:5] [audioconvert0] State change: NULL -> READY
2020/02/09 13:47:07 [decoder.gstreamer:5] [typefind] State change: NULL -> READY
2020/02/09 13:47:07 [decoder.gstreamer:5] [decodebin0] State change: NULL -> READY
2020/02/09 13:47:07 [decoder.gstreamer:5] [filesrc0] State change: NULL -> READY
2020/02/09 13:47:07 [decoder.gstreamer:5] [pipeline0] State change: NULL -> READY (pending: PAUSED)
2020/02/09 13:47:07 [decoder.gstreamer:5] [audioresample0] State change: READY -> PAUSED
2020/02/09 13:47:07 [decoder.gstreamer:5] [audioconvert0] State change: READY -> PAUSED
2020/02/09 13:47:07 [decoder.gstreamer:5] [typefind] State change: READY -> PAUSED
2020/02/09 13:47:07 [decoder.gstreamer:5] [filesrc0] State change: READY -> PAUSED
2020/02/09 13:47:08 [decoder:4] Decoder "GSTREAMER" failed on "video.mp4": Gstreamer.Failed!
```

**Version details**
- Ubuntu
- Liquidsoap 1.5.0+git@f19569c9)

**Install method**
Installing latest Liquidsoap distribution's packages for Debian/Ubuntu deb repository.

`[sudo] apt-get install liquidsoap-master`

**Comment by smimram** [comment]
With the latest latest git it seems to work: ffmpeg can now be used to decode the video! (by latest I mean from a few minutes ago)

Moreover, there is work with automatic channel conversion by @toots which should also avoid you the need for `drop_audio` in the future.

**Comment by jlopex** [comment]
Hey @smimram thanks for this super quick update. Can I use deb snapshots?

**Comment by smimram** [comment]
I guess so they are rebuilt at each commit.

**Comment by toots** [comment]
Hey! Yeah, the latest deb should work. Also, with the recent changes, I'd suggest using the `%ffmpeg` encoder instead of gstreamer. For sending, it looks like this:
```
output.url(url="rtsp://<HOST>:<PORT>/<PATH>",
  %ffmpeg(format="rtsp", video_codec=libx264", audio_codec="aac"), source)
```

**Comment by jlopex** [comment]
Yes! @toots @smimram I was able to make it work, I'm founding some quirks that I think are related with video/audio desynchronising and looping stream gets "frozen" randomly. but this is a different problem so far! I'll try to make the FFmpeg approach too! :)

Do you want me to close the issue?

**Comment by toots** [comment]
Glad to hear! Let's close the issue indeed. Feel free to reopen or submit a new one if needed.
