### ISSUE TITLE
Using special chars in name parameter of harbor.shoutcast results in charset issues

### ISSUE THREAD

**Issue by naitsirch** [savonet/liquidsoap#1092]
**Describe the bug**
If we are using special chars or umlauts in the server name that is passed to harbor.shoutcast, Shoutcast 1 produces a false result.

**To Reproduce**
This is the relevant part of the liquidsoap script:
```
output.shoutcast(
    ...
    name="ÜÖSlave MeÜÄ"
)
```
In the script we use utf8 as charset.

On the shoutcast web interface it is displayed like this:
![grafik](https://user-images.githubusercontent.com/1118790/74526243-40edd700-4f23-11ea-9b3d-0409af6de5f2.png)

When we access the Shoutcasts admin stats XML, the server title looks like this:
`&#xC3;&#x9C;&#xC3;&#x96;Slave Me&#xC3;&#x9C;&#xC3;`

**Expected behavior**
The correct encoding should be used.

**Version details**
 - OS: Debian 10.3
 - Version: 1.3.7

**Comment by autonarcosis** [comment]
In the output.shoutcast() did you set encoding="UTF-8" ?

**Comment by naitsirch** [comment]
In the documentation it is said 
> encoding (of type string, which defaults to "ISO-8859-1"): Encoding used to send metadata.

I'd expect that this would chang the encoding used for the title metadata, too. But the metadata in the music files is still encoded with ISO-8859-1.

Would it work to save the content of the name parameter in the script ISO-8859-1 encoded?

**Comment by toots** [comment]
Hi! I guess we never thought of re-encoding the name parameter.. I'm gonna add this to the current `master` branch. Any chance you could test it there?

**Comment by naitsirch** [comment]
It's a pity but I have no capabilities to build from source to test `master`.

But from your change I suspect that liquidsoap assumes the script to be encoded as UTF-8, right? Could that be documented anywhere?

**Comment by toots** [comment]
Just added it. If you can't switch to the latest `master` you might still be able to fix your issue. What you need is to pass `name=...` with the correct encoding. A simple way to do it is to generate a base64-encoded string that contains the `name` value using the right character encoding. Then, in liquidsoap you can do:
```ruby
  name=base64.decode("<encoded value>")
```
That should do it!
