### ISSUE TITLE
How to skip current title when playlist is reloaded

### ISSUE THREAD

**Issue by naitsirch** [savonet/liquidsoap#1093]
We are using a playlist with reload mode "watch". The default behaviour when the playlist file changes is that the current song is played to the end.
What we would like to achieve is that when the playlist file changes we want the first track of the new playlist to be played immediately. So there should either be only a short crossfade or a hard cut.

Is that possible?

My idea is to use `fallback.skip` for example like this:

```
myPlaylist = mksafe(normalize(playlist(reload_mode="watch","/home/user/playlist.lst")))
fallback.skip(myPlaylist, myPlaylist)
```

Would this work?

**Comment by smimram** [comment]
I have just added the `on_reload` option to the playlist operator (see e690a2fec60b9b4ca11a4acbb1893b0d3f7ea799): you can pass a function which will be called when the playlist is reloaded. You should be able to use this easily in order to skip just after the playlist has been reloaded.

**Comment by naitsirch** [comment]
This sounds great! This is exactly what we need :-) Thank you

**Comment by davidtrattnig** [comment]
@smimram the `on_reload` parameter seems gone in the current 1.4.3 release.

Are there any alternative ways to do it now?
