### ISSUE TITLE
Stream metadata can't display japanese characters

### ISSUE THREAD

**Issue by Allavaz** [savonet/liquidsoap#1094]
**Describe the bug**
Japanese characters are not displayed at all in the stream metadata. Instead I get stuff like this:
![chrome_clhXDyWXmg](https://user-images.githubusercontent.com/8140592/74566277-e750d100-4f51-11ea-9928-2c4c906b3abd.png)
If it's any help here's a piece of the logs:
`2020/02/14 17:32:07 [decoder:3] Method "MAD" accepted "/home/david/Desktop/Anri/Circuit of Rainbow/05. \229\164\177\230\129\139\227\130\178\227\131\188\227\131\160\227\129\140\231\181\130\227\130\139\227\129\190\227\129\167.mp3".
`

**To Reproduce**
Play a song with japanese characters in its metadata. I imagine it happens too with any non-english characters but can't confirm.

**Expected behavior**
Japanese characters should display properly. I have no problem if it doesn't display them in the logs but I'd like them to show in the stream metadata. For example, this station displays them just fine:
![image](https://user-images.githubusercontent.com/8140592/74566139-904afc00-4f51-11ea-8c5d-75fca0a1f9aa.png)

**Version details**
 - OS: Ubuntu 19.10
 - Version: 1.4.1

**Install method**
Installed via OPAM with these commands:
```
opam depext taglib mad lame vorbis cry samplerate liquidsoap flac opus
opam install taglib mad lame vorbis cry samplerate liquidsoap flac opus
```

**Comment by autonarcosis** [comment]
In our output.icecast() do you have encoding = "UTF-8" and in icecast.xml your <mount> directive should have  the charset as well.

<mount type="normal">
		<mount-name>/yourmountpoint</mount-name>
		<charset>UTF-8</charset>
	</mount>

**Comment by Allavaz** [comment]
![image](https://user-images.githubusercontent.com/8140592/74596390-72ab8e80-5046-11ea-985c-329529abffb8.png)
thank you so much, it's working fine now!

**Comment by toots** [comment]
Happy to hear it's fixed!
