### ISSUE TITLE
Suppress Liquidsoap inserting metadata automatically 

### ISSUE THREAD

**Issue by gammaw** [savonet/liquidsoap#1096]
We have a Shoutcast input harbor in our Liquidsoap configuration and we realized that every time a client connects (we use Butt as a client), Liquidsoap will insert metadata (song and title) automatically. The metadata seems to be the last one from the previous Butt session. This behavior may have to do with the fact that Butt fails to insert metadata upon connection. 

Is there a way to suppress this behavior? 

Our problem is that although we insert custom metadata manually (upon a new client connecting) using `insert_metadata` (inside the Liquidsoap configuration) but this one is overwritten by Liquidsoap a couple of seconds later. 

FYI: Our Liquidsoap instance runs inside Azuracast and we use a custom form of their configuration. It seems to me that the metadata insertion is not triggered by Azuracast.

**Comment by toots** [comment]
Do you know if the metadata is coming from the client or from us? Our switches and fallback can be configured to replay the last metadata seen in a source when switching (this is a good behavior for playlists typically), could that be the issue?

If needed, you can suppress metadata programmatically using `map_metadata` or `drop_metadata` (which is based on `map_metadata`).

**Comment by gammaw** [comment]
@toots thanks. Yes, I think it's the replay. It's indeed useful for most cases but not for our live source. I can't switch it off for the live source, the `replay_metadata = false` doesn't seem to take effect. I can see in the documentation that sometimes `false` is default sometimes `true`. 

This is the rough structure of our config: 

```
live = audio_to_stereo(input.harbor(...))
live = fallback(id="radio_live_fallback", track_sensitive=false, [live, blank(duration=2.)])
radio = switch(track_sensitive=false, [({!live_enabled}, live), ({1w and 6h-6h59m}, once(playlist_best_tracks)),...])
```

I only want to switch off metadata replay for `live` and not for the playlists (e.g., `playlist_best_tracks`). Any idea?

**Comment by gammaw** [comment]
@toots now that the client we use for live sources (called Butt) released a new version with optimised metadata handling we hope to be able to fix our issue. Did you have a chance to look into my last question?

**Comment by toots** [comment]
Hi! Wouldn't it work be setting `replay_metadata` to false on `"radio_live_fallback"` and `true` on the next one?

**Comment by gammaw** [comment]
@toots I tried that, I guess, and as I remember it the setting you apply for `radio` will be used for `live` too. (We're using Liquidsoap 1.4.2.). I'll try again to confirm it.

**Comment by Diman779** [comment]
Метаданные можно настроить для hls aac ?

**Comment by Diman779** [comment]
Can metadata be configured for hls aac?
