### ISSUE TITLE
Fast fallback requests and race-conditions with multiple fallback sources

### ISSUE THREAD

**Issue by davidtrattnig** [savonet/liquidsoap#1098]
I have multiple fallbacks (`timeslot`, `show` and `station`), when should get triggered in this order, when my main source doesn't have any audio playing:

`output_source = fallback(id="fallback", track_sensitive=false, [stripped_stream, timeslot_fallback, show_fallback, mksafe(station_fallback)])`

Behind every fallback is some Python logic, which evaluates the fallback track to play.

Now the issue is, as soon a fallback is requested it:

1. Sends the request multiple times per second, although the first request didn't even get a reply from Python yet.

2. It switches to the next fallback type quite quickly, sometimes resulting in the fallback with less priority gets a result even before the higher priority fallback has finished (e.g. "`show`" results before "`timeslot`").

How to increase some timeout-value for Liquidsoap requesting fallbacks? In other words: decreasing the frequency of fallback requests being sent?

**Comment by toots** [comment]
Hi @davidtrattnig !

I'm not sure that I understand everything that is going on here. What do you mean that there's some python logic behind every fallback?

**Comment by davidtrattnig** [comment]
Thanks for looking into this @toots!

Each of:
* `timeslot_fallback`
* `show_fallback`
* `station_fallback`

calls

```
timeslot_fallback = fallback_create(skip=true, "timeslot_fallback", create_timeslot_fallback)
station_fallback  = fallback_create(skip=true, "station_fallback", create_station_fallback)
show_fallback     = fallback_create(skip=true, "show_fallback", create_show_fallback)
```

which triggers a call of 

def create_station_fallback() =
  result = get_process_lines('#{list.assoc("install_dir", ini)}/guru.py --get-next-file-for station --quiet')
  log("next song for STATION fallback is: #{result}")
  create_dynamic_playlist(result)
end

def create_show_fallback() =
  result = get_process_lines('#{list.assoc("install_dir", ini)}/guru.py --get-next-file-for show --quiet')
  log("next song for SHOW fallback is: #{result}")
  create_dynamic_playlist(result)
end

def create_timeslot_fallback() =
  result = get_process_lines('#{list.assoc("install_dir", ini)}/guru.py --get-next-file-for timeslot --quiet')
  log("next song for TIMESLOT fallback is: #{result}")
  create_dynamic_playlist(result)
end

The last functions call a python script, which returns the files to play via the command line.

I'm currently thinking about to move this fallback logic completley to Python, because for the first fallback options it's prectable, when they should be triggered in advance. I'll be only leaving the "Station Fallback" in LQS, which ensures that there is always something played (`mksafe(..)`).

**Comment by davidtrattnig** [comment]
Additionally, there is following issue: 

1. Assume that the `station_fallback` is triggered
2. The Python script is called to retrieve a file to play
3. Liquidsoap doesn't play that file. Instead it requests the Python script again for another file.
4. Now, only the second file is played.

(Liquidsoap 1.1.1)
