### ISSUE TITLE
%ffmpeg crashes on track change

### ISSUE THREAD

**Issue by autonarcosis** [savonet/liquidsoap#1100]
@toots 

Using the new %ffmpeg, it crashes on track change.

Here is the configuration I am using;

`output.url(%ffmpeg(format="mpegts",%audio(codec="aac",b="64k"),%video(codec="libx264",b="512k",g=150,preset="veryfast")),fallible=true, url="udp://127.0.0.1:5000",mksafe(videoplaylist))
`
Logfile is;
`2020/02/28 11:34:16 [clock.main:2] Source output(dot)url failed while streaming: FFmpeg.Avutils.Error(Invalid argument)!
2020/02/28 11:34:16 [clock.main:3] Raised at file "avutil/avutil.ml", line 69, characters 51-77
2020/02/28 11:34:16 [clock.main:3] Called from file "encoder/ffmpeg_encoder.ml", line 243, characters 4-28
2020/02/28 11:34:16 [clock.main:3] Called from file "encoder/ffmpeg_encoder.ml", line 243, characters 4-28
2020/02/28 11:34:16 [clock.main:3] Called from file "outputs/output.ml", line 258, characters 24-44
2020/02/28 11:34:16 [clock.main:3] Called from file "outputs/output.ml", line 186, characters 40-56
2020/02/28 11:34:16 [clock.main:3] Called from file "clock.ml", line 288, characters 14-22
`

Some more notes;

The Shaka Packager connects to the UDP stream then converts it to MPEG-DASH segments for playback via browser or VLC.  I believe this is the Packager out put around the time of the track change (quite sure of it).

`[0228/113347:WARNING:representation.cc(362)] Representation (id=0,codec='mp4a.40.2',frequency=44100,language='') Found a gap of size 207 > kRoundingErrorGrace (5). The new segment starts at 2161780 but the previous segment ends at 2161573.
[0228/113347:WARNING:es_parser_h26x.cc(320)] [MPEG-2 TS] PID 257 dts 0 less than or equal to previous dts 2563200
[0228/113353:WARNING:representation.cc(372)] Representation (id=0,codec='mp4a.40.2',frequency=44100,language='') Segments should not be overlapping. The new segment starts at 5110 but the previous segment ends at 2577491.
[0228/113353:WARNING:representation.cc(372)] Representation (id=1,codec='avc1.64001e',width=640,height=480) Segments should not be overlapping. The new segment starts at 7200 but the previous segment ends at 2570490.
`
The audio gap size error is consistent throughout the entire stream, hovering around in the 200-210.

There also appears to be no way to enter x264-params using this method.

I did experience audio de-sync during second test using VLC as the client. Inconclusive as VLC does massive amounts of https lookups using MPEG-DASH. Restarting the VLC stream seemed to get it back on track but seemed to drop out fairly quickly.  This didn't appear to happen using Shaka Player via browser but need to do more testing.

**Comment by toots** [comment]
This is fixed, thanks for reporting. You will need to update to the latest `ocaml-ffmpeg` as well.

**Comment by toots** [comment]
Also just pushed another fix to allow ffmpeg encoder params of the form `foo-bar`. This encoder works now here:
```
encoder = %ffmpeg(
  format="mpegts",
  %audio(codec="aac",b="64k"),
  %video(codec="libx264",preset="veryfast",
         profile="baseline",level=3.,sc_threshold=0,
         "x264-params"="scenecut=0:open_gop=0:min-keyint=150:keyint=150",
         minrate="512k",maxrate="640k",bufsize="1280k",b="512k")
)
```
