### ISSUE TITLE
vumeter output

### ISSUE THREAD

**Issue by hakao32** [savonet/liquidsoap#1101]
Can we change only the output file of vumeter? 
I just want logs to default but only vumeter so I can monitorize them in seperate files

**Comment by smimram** [comment]
As you can see in #1103, (more precisely [here](https://github.com/savonet/liquidsoap/pull/1103/files#diff-4c93d105e15507773cd903a3adee2fc7)), the vumeter can easily be implemented directly in Liquidsoap. From this implementation, it should not be hard to change the output: basically, you need to replace the `print` by a `file.write`.

**Comment by hakao32** [comment]
Is it possible to change that code without recompile? I am using 1.1.1 installaed by apt-get install liquidsoap.

**Comment by smimram** [comment]
Yes, I don't think that we are using anything really new here. The only thing maybe is `thread.run.recurrent` which used to be named `add_timeout`.

**Comment by hakao32** [comment]
There is no libs/visualization.liq in 1.1.1. There is only src/visualization/vumeter.ml.

**Comment by smimram** [comment]
Yes, but you can copy the following function directly in your code:
```
# VU meter: display the audio volume (RMS in dB).
# @category Visualization
# @param ~rms_min Minimal volume.
# @param ~rms_max Maximal volume.
# @param ~scroll Update the display in the same line.
# @param ~window Duration in seconds of volume computation.
def vumeter(~rms_min=-25., ~rms_max=-5., ~window=0.5, ~scroll=false, s)
  screen_width = 80
  bar_width = screen_width
  let (f,s) = rms(duration=window, s)
  def display()
    v = dB_of_lin(f())
    x = (v - rms_min) / (rms_max - rms_min)
    x = if x < 0. then 0. else x end
    x = if x > 1. then 1. else x end
    n = int_of_float(x * float_of_int(bar_width))
    bar = ref("")
    if not scroll then bar := "\r" end
    for (1, n, fun (_) -> bar := !bar ^ "=")
    for (1, bar_width - n, fun (_) -> bar := !bar ^ ".")
    bar := !bar ^ " " ^ string_of(v)
    if scroll then bar := !bar ^ "\n" end
    print(newline=false, !bar)
  end
  thread.run.recurrent(fast=true, {display (); window})
  s
end
```
(it does not have to be in the library).

**Comment by hakao32** [comment]
I got what you mean right now. sorry.

**Comment by hakao32** [comment]
I am getting 
File "/usr/lib/liquidsoap/1.1.1/visualization.liq", line 10, char 14 before "=": Parse error!

the line :
let (f,s) = rms(duration=window, s)

**Comment by smimram** [comment]
Change it to
```
fs = rms(duration=window, s)
f = fst(fs)
s = snd(fs)
```
(we added a new syntax to simplify this).

**Comment by hakao32** [comment]
I made 
fs = rms(s) because there is no parameter "duration" for rms func.

I am getting 
At /usr/lib/liquidsoap/1.1.1/visualization.liq, line 21, char 9:
  the variable for used here has not been previously defined.

The line :
for (1, n, fun (_) -> bar := !bar ^ "=")

**Comment by smimram** [comment]
You also need to define the `for` function from https://github.com/savonet/liquidsoap/blob/master/libs/utils.liq#L646 :
```
def rec for(first, last, f)
  if first <= last then
    f(first)
    for(first+1, last, f)
  end
end
```

**Comment by hakao32** [comment]
I defined for in utils.liq as you did. But now I am getting:

At /usr/lib/liquidsoap/1.1.1/utils.liq, line 768, char 12: the variable for
  used here has not been previously defined.

there is also "for" in "def for" thats why I think

**Comment by hakao32** [comment]
# VU meter: display the audio volume (RMS in dB).
# @category Visualization
# @param ~rms_min Minimal volume.
# @param ~rms_max Maximal volume.
# @param ~scroll Update the display in the same line.
# @param ~window Duration in seconds of volume computation.
def vumeter1(~rms_min=-25., ~rms_max=-5., ~window=0.5, ~scroll=false, s)
  fs = rms(s)
  f = fst(fs)
  s = snd(fs)
  def display()
    v = dB_of_lin(f())
    system ("echo #{v} > <file/to/write>")
    1.
  end
  add_timeout(fast=true, 1., display)
  s
end

this is how I solve the problem. I just get rms value.
I used system echo because there is no file.write in 1.1.1

**Comment by smimram** [comment]
Glad to hear that you found a solution!
