### ISSUE TITLE
Switch operator will break the playlist rotation

### ISSUE THREAD

**Issue by pavlos2** [savonet/liquidsoap#1105]
Hi liquidsoap users,

May I ask your help to find what is wrong with the following code:
```
Joyful = rotate(weights=[1,1,1,1,1], [playlist_1, playlist_2, playlist_3, playlist_4, playlist_5])
radio = switch(track_sensitive=true, [
({ (1w or 5w) and 23m }, Joyful ),
({true}, radio)])
```
It will run `playlist_1`, `playlist_2`, and `playlist_3`, and then switches back to the safe playlist. Hereunder is the Liquidsoap Log:
```
....
2020/03/09 02:22:55 [lang:3] AzuraCast Feedback Response: OK
2020/03/09 02:23:17 [playlist_default:3] Prepared "/var/azuracast/stations/testing_azuracast/media/Solos/03_solo.mp3" (RID 16).
2020/03/09 02:23:17 [playlist_5:3] Prepared "/var/azuracast/stations/testing_azuracast/media/5/5.mp3" (RID 12).
2020/03/09 02:23:17 [playlist_4:3] Prepared "/var/azuracast/stations/testing_azuracast/media/4/4.mp3" (RID 9).
2020/03/09 02:23:17 [playlist_3:3] Prepared "/var/azuracast/stations/testing_azuracast/media/3/3.mp3" (RID 8).
2020/03/09 02:23:17 [playlist_2:3] Prepared "/var/azuracast/stations/testing_azuracast/media/2/2.mp3" (RID 6).
2020/03/09 02:23:17 [playlist_1:3] Prepared "/var/azuracast/stations/testing_azuracast/media/1/1.mp3" (RID 3).
2020/03/09 02:23:17 [switch_7704:3] Switch to rotate_7702 with forgetful transition.
2020/03/09 02:23:17 [rotate_7702:3] Switch to stereo_playlist_1.
2020/03/09 02:23:17 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/1/1.mp3".
2020/03/09 02:23:17 [cross_7706:3] Analysis: -59.960583dB / -191.222375dB (2.99s / 3.01s)
2020/03/09 02:23:17 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/09 02:23:17 [lang:3] AzuraCast Feedback Response: OK
2020/03/09 02:23:36 [playlist_1:3] Prepared "/var/azuracast/stations/testing_azuracast/media/1/1.mp3" (RID 17).
2020/03/09 02:23:36 [rotate_7702:3] Switch to stereo_playlist_2 with forgetful transition.
2020/03/09 02:23:36 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/2/2.mp3".
2020/03/09 02:23:36 [cross_7706:3] Analysis: -28.626502dB / -198.465953dB (2.97s / 2.99s)
2020/03/09 02:23:36 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/09 02:23:36 [lang:3] AzuraCast Feedback Response: OK
2020/03/09 02:23:55 [playlist_2:3] Prepared "/var/azuracast/stations/testing_azuracast/media/2/2.mp3" (RID 18).
2020/03/09 02:23:55 [rotate_7702:3] Switch to stereo_playlist_3 with forgetful transition.
2020/03/09 02:23:55 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/3/3.mp3".
2020/03/09 02:23:55 [cross_7706:3] Analysis: -25.033657dB / -194.947891dB (2.99s / 3.01s)
2020/03/09 02:23:55 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/09 02:23:55 [lang:3] AzuraCast Feedback Response: OK
2020/03/09 02:24:14 [playlist_3:3] Prepared "/var/azuracast/stations/testing_azuracast/media/3/3.mp3" (RID 19).
2020/03/09 02:24:14 [rotate_7702:3] Switch to stereo_playlist_4 with forgetful transition.
2020/03/09 02:24:14 [switch_7704:3] Switch to testing_azuracast_safe_fallback with forgetful transition.
2020/03/09 02:24:14 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/Solos/09_solo.mp3".
2020/03/09 02:24:14 [cross_7706:3] Analysis: -146.707276dB / -97.591383dB (2.99s / 3.01s)
2020/03/09 02:24:14 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/03/09 02:24:14 [lang:3] AzuraCast Feedback Response: OK
....
```
**Version details**
OS: Ubuntu 18.04

**Install method**
From AzuraCast in Docker.

Thanks in advance!

Regards,
Pavlos

**Comment by pavlos2** [comment]
Can someone help, please!

**Comment by pavlos2** [comment]
I keep testing the code, still the output result is not the expected one. This time rotated only the two first playlists, sometimes it can rotate up to three first playlists, then switches to the safe one. 

...
**2020/03/13 12:24:08 [rotate_7745:3] Switch to cue_playlist_3 with forgetful transition.
2020/03/13 12:24:08 [switch_7747:3] Switch to testing_azuracast_safe_fallback with forgetful transition.**
...


**Liquidsoap Log**

[lang:3] AzuraCast Feedback Response: OK
2020/03/13 12:23:24 [playlist_default:3] Prepared "/var/azuracast/stations/testing_azuracast/media/Solos/06_solo.mp3" (RID 38).
2020/03/13 12:23:24 [playlist_5:3] Prepared "/var/azuracast/stations/testing_azuracast/media/5/5.mp3" (RID 32).
2020/03/13 12:23:24 [playlist_4:3] Prepared "/var/azuracast/stations/testing_azuracast/media/4/4.mp3" (RID 31).
2020/03/13 12:23:24 [playlist_3:3] Prepared "/var/azuracast/stations/testing_azuracast/media/3/3.mp3" (RID 28).
2020/03/13 12:23:24 [playlist_2:3] Prepared "/var/azuracast/stations/testing_azuracast/media/2/2.mp3" (RID 30).
2020/03/13 12:23:24 [playlist_1:3] Prepared "/var/azuracast/stations/testing_azuracast/media/1/1.mp3" (RID 29).
2020/03/13 12:23:24 [switch_7747:3] Switch to rotate_7745 with forgetful transition.
2020/03/13 12:23:24 [rotate_7745:3] Switch to cue_playlist_1.
2020/03/13 12:23:24 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/1/1.mp3".
2020/03/13 12:23:24 [lang:3] AzuraCast Feedback Response: OK
2020/03/13 12:23:46 [playlist_1:3] Prepared "/var/azuracast/stations/testing_azuracast/media/1/1.mp3" (RID 39).
2020/03/13 12:23:46 [rotate_7745:3] Switch to cue_playlist_2 with forgetful transition.
2020/03/13 12:23:46 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/2/2.mp3".
2020/03/13 12:23:46 [lang:3] AzuraCast Feedback Response: OK
2020/03/13 12:24:08 [playlist_2:3] Prepared "/var/azuracast/stations/testing_azuracast/media/2/2.mp3" (RID 40).
**2020/03/13 12:24:08 [rotate_7745:3] Switch to cue_playlist_3 with forgetful transition.
2020/03/13 12:24:08 [switch_7747:3] Switch to testing_azuracast_safe_fallback with forgetful transition.**
2020/03/13 12:24:08 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/Solos/07_solo.mp3".
2020/03/13 12:24:08 [lang:3] AzuraCast Feedback Response: OK
2020/03/13 12:24:32 [playlist_default:3] Prepared "/var/azuracast/stations/testing_azuracast/media/Solos/07_solo.mp3" (RID 41).
2020/03/13 12:24:32 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/Solos/02_solo.mp3".
2020/03/13 12:24:32 [lang:3] AzuraCast Feedback Response: OK
2020/03/13 12:24:54 [playlist_default:3] Prepared "/var/azuracast/stations/testing_azuracast/media/Solos/02_solo.mp3" (RID 42).
2020/03/13 12:24:54 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/testing_azuracast/media/Solos/09_solo.mp3".
2020/03/13 12:24:54 [lang:3] AzuraCast Feedback Response: OK



******

**Liquidsoap Configuration**

-# WARNING! This file is automatically generated by AzuraCast.
-# Do not update it directly!

set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/testing_azuracast/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "Europe/Athens")

playlist_2 = playlist(id="playlist_2",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/testing_azuracast/playlists/playlist_2.m3u")
playlist_2 = audio_to_stereo(id="stereo_playlist_2", playlist_2)
playlist_2 = cue_cut(id="cue_playlist_2", playlist_2)

playlist_3 = playlist(id="playlist_3",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/testing_azuracast/playlists/playlist_3.m3u")
playlist_3 = audio_to_stereo(id="stereo_playlist_3", playlist_3)
playlist_3 = cue_cut(id="cue_playlist_3", playlist_3)

playlist_1 = playlist(id="playlist_1",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/testing_azuracast/playlists/playlist_1.m3u")
playlist_1 = audio_to_stereo(id="stereo_playlist_1", playlist_1)
playlist_1 = cue_cut(id="cue_playlist_1", playlist_1)

playlist_4 = playlist(id="playlist_4",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/testing_azuracast/playlists/playlist_4.m3u")
playlist_4 = audio_to_stereo(id="stereo_playlist_4", playlist_4)
playlist_4 = cue_cut(id="cue_playlist_4", playlist_4)

playlist_5 = playlist(id="playlist_5",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/testing_azuracast/playlists/playlist_5.m3u")
playlist_5 = audio_to_stereo(id="stereo_playlist_5", playlist_5)
playlist_5 = cue_cut(id="cue_playlist_5", playlist_5)

playlist_default = playlist(id="playlist_default",mode="randomize",reload_mode="watch",conservative=true,default_duration=10.,length=20.,"/var/azuracast/stations/testing_azuracast/playlists/playlist_default.m3u")
playlist_default = audio_to_stereo(id="stereo_playlist_default", playlist_default)
playlist_default = cue_cut(id="cue_playlist_default", playlist_default)

-# Standard Playlists
radio = random(id="testing_azuracast_standard_playlists", weights=[3], [playlist_default])

requests = request.queue(id="testing_azuracast_requests")
requests = audio_to_stereo(id="testing_azuracast_stereo_requests", requests)
requests = cue_cut(id="testing_azuracast_cue_requests", requests)
radio = fallback(id="testing_azuracast_requests_fallback", track_sensitive = true, [requests, radio])

add_skip_command(radio)

radio = fallback(id="testing_azuracast_safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

-# Custom Configuration (Specified in Station Profile)
Joyful = rotate(weights=[1,1,1,1,1], [playlist_1, playlist_2, playlist_3, playlist_4, playlist_5])
radio = switch(track_sensitive=true, [
({ (1w or 5w) and 23m }, Joyful ),
({true}, radio)])

-# DJ Authentication
live_enabled = ref false
last_authenticated_dj = ref ""
live_dj = ref ""

def dj_auth(auth_user,auth_pw) =
    user = ref ""
    password = ref ""
  
    if (auth_user == "source" or auth_user == "") and (string.match(pattern="(:|,)+", auth_pw)) then
        auth_string = string.split(separator="(:|,)", auth_pw)
        
        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := auth_user
        password := auth_pw
    end
    
    log("Authenticating DJ: #{!user}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="^string.quote(!user)^" --form dj-password="^string.quote(!password)^" --form api_auth="^string.quote("3751822b9d03dc7d502986f69327e3a40a8b0e1b6f6fedcea5bfe53be9da366172bf3f13949bb43a605c0c21fb67c524eeac")^""), default="")
    log("AzuraCast DJ Auth Response: #{ret}")
    
    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end
    
    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")
    
    live_enabled := true
    live_dj := dj
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("3751822b9d03dc7d502986f69327e3a40a8b0e1b6f6fedcea5bfe53be9da366172bf3f13949bb43a605c0c21fb67c524eeac")^""), default="")
    log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() = 
    dj = !live_dj
    
    log("DJ Source disconnected! Current live DJ: #{dj}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("3751822b9d03dc7d502986f69327e3a40a8b0e1b6f6fedcea5bfe53be9da366172bf3f13949bb43a605c0c21fb67c524eeac")^""), default="")
    log("AzuraCast Live Disconnected Response: #{ret}")
    
    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
end 

-# A Pre-DJ source of radio that can be broadcast if needed
radio_without_live = radio
ignore(radio_without_live)

-# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id = "testing_azuracast_input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5., max = 10.))
ignore(output.dummy(live, fallible=true))

radio = fallback(id="testing_azuracast_live_fallback", track_sensitive=false, [live, radio])

-# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

-# Apply amplification metadata (if supplied)
radio = amplify(override="liq_amplify", 1., radio)

-# Send metadata changes back to AzuraCast
def metadata_updated(m) =
    if (m["song_id"] != "") then
        ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^string.quote(m["song_id"])^" --form media="^string.quote(m["media_id"])^" --form playlist="^string.quote(m["playlist_id"])^" --form api_auth="^string.quote("3751822b9d03dc7d502986f69327e3a40a8b0e1b6f6fedcea5bfe53be9da366172bf3f13949bb43a605c0c21fb67c524eeac")^""), default="")
        log("AzuraCast Feedback Response: #{ret}")
    end
end

radio = on_metadata(metadata_updated,radio)

-# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="testing_azuracast_local_1", host = "127.0.0.1", port = 8000, password = "Nee9EE6f", mount = "/radio.mp3", name = "Testing AzuraCast", description = "", genre = "", public = false, encoding = "UTF-8", radio)

-# Remote Relays

**Comment by toots** [comment]
It look like your condition for playlist rotation is only `true` at minute 23 and none else:
```
({ (1w or 5w) and 23m }, Joyful ),
```
That's essentially saying "First or 5th day of the week at minute 23 of any hour"

**Comment by pavlos2** [comment]
Hi Toots, thanks a lot for the reply. Indeed, I would expect on the 1st or 5th day of the week, at minute 23, to start rotating ALL playlists in sequence. What am I missing here? Do you mean the condition for playlist rotation is **true** only during the 23rd minute (00:23:00 - 00:23:59) regardless of the total duration of all playlists in the rotation condition?

**Comment by pavlos2** [comment]
ok, got it. I have to define time interval, I thought rotation would start at minute x and will run all the playlists in the rotation condition. What's the syntax for "Switch to Playlist A at x min, then Switch to the Safe Playlist at the end of Playlist A"

Regards,
Pavlos

**Comment by toots** [comment]
Cool, happy to hear you fixed it!
