### ISSUE TITLE
Version 1.5.0 doesn't show sources in telnet - no option to manually reload

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1106]
I've been running and testing version 1.5.0 and have noticed that when logging into telnet, the playlists sources are not displayed like they were in version 1.4.0. 
You can see this in the screenshot below

![Screen Shot 2020-03-10 at 8 34 01 pm](https://user-images.githubusercontent.com/46059094/76305664-474c5480-6311-11ea-9090-15d76e8a0663.png)

Previously in version 1.4.0, they were all listed with the option to reload them (as you can see in the screenshot below)
![Screen Shot 2020-03-10 at 8 50 51 pm](https://user-images.githubusercontent.com/46059094/76305722-6ba83100-6311-11ea-86d1-0bd4ab670fab.png)

I'm guessing it may have something to do with the new playlist operators being based on playlist.reloadable ... and playlist.reloadable doesn't display in telnet by default.

**Comment by smimram** [comment]
Thanks for letting us know, I have restored those commands!

**Comment by oranjebloom** [comment]
I've reinstalled version 1.5.0 and tested but those commands are still not appearing for me.

**Comment by smimram** [comment]
Do you see [these changes](https://github.com/savonet/liquidsoap/commit/4a646f464c6c86c4dc2f92edc6bee9f92866e130) in your installed version of `playlist.liq`?

**Comment by oranjebloom** [comment]
Yeah i see this in ... /home/amdin/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/git/783fffd9/libs

![Screen Shot 2020-03-11 at 8 31 16 pm](https://user-images.githubusercontent.com/46059094/76407595-51388b00-63d7-11ea-85fb-c032b8c0a4d4.png)

**Comment by oranjebloom** [comment]
My installation looks like this in opam list
![Screen Shot 2020-03-11 at 8 53 47 pm](https://user-images.githubusercontent.com/46059094/76409698-75e23200-63da-11ea-8d9d-69751b15149a.png)

**Comment by oranjebloom** [comment]
Hi Samuel, Can you confirm that the commands appear in telnet for you?

**Comment by smimram** [comment]
Yes, my test script is
```
set("server.telnet", true)
s = playlist(id="pl", "~/Music")
out(s)
```
and the telnet output is
```
$ telnet localhost 1234
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
help
Available commands:
| exit
| help [<command>]
| list
| pl.reload
| pl.skip
| pl.uri [<uri>]
...
```

**Comment by oranjebloom** [comment]
Okay, must be my installation then. Thanks
