### ISSUE TITLE
Make setting SSL certificate requirement clear in documentation for harbor.https.register

### ISSUE THREAD

**Issue by tristan-nel** [savonet/liquidsoap#1109]
It is currently not shown in the documentation that this is necessary, and for those not versed in SSL, they might not understand why their endpoint isn't working.

**Comment by vrx** [comment]
hi, can you elaborate on that ?  
i might have this problem.
more precisely i get this error : 
[input(dot)harbor(dot)ssl_7588:5] Not ready: need more buffering (0/88200)

**Comment by toots** [comment]
Hi @tristan-nel. What exactly would you like to add to the documentation? Feel free to send a PR too if you have a second!

**Comment by smimram** [comment]
Closing for the lack of answer, feel free to reopen.
