### ISSUE TITLE
Calculation of video samples per frame is causing output.external confusion

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1111]
In #1110 I mentioned the following an issue with setting video framerate
I've looked into this a bit further and have found some empirical evidence during my testing
In these tests I am using an output.external pipe in to ffmpeg

With the standard settings
```
set("frame.video.samplerate",25)
set("frame.audio.samplerate",44100)
```
Results in the frame setup
```
2020/03/16 02:58:43 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2020/03/16 02:58:43 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/03/16 02:58:43 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/03/16 02:58:43 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
```
FFMPEG detects input FPS at 25, and outputs at 25

Next when i use
```
set("frame.video.samplerate",30)
set("frame.audio.samplerate",44100)
```
I get 
```
2020/03/16 03:02:40 [frame:3] Using 44100Hz audio, 30Hz video, 44100Hz master.
2020/03/16 03:02:40 [frame:3] Frame size must be a multiple of 1470 ticks = 1470 audio samples = 1 video samples.
2020/03/16 03:02:40 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/03/16 03:02:40 [frame:3] Frames last 0.07s = 2940 audio samples = 2 video samples = 2940 ticks.
```
And FFMPEG detects input FPS at 30, but outputs at 15 - even when I am forcing fps with `-r 30` and a `fps=fps=30` filter

Next and now a strange FPS
```
set("frame.video.samplerate",26)
set("frame.audio.samplerate",44100)
```
results in
```
2020/03/16 03:15:20 [frame:3] Using 44100Hz audio, 26Hz video, 573300Hz master.
2020/03/16 03:15:20 [frame:3] Frame size must be a multiple of 286650 ticks = 22050 audio samples = 13 video samples.
2020/03/16 03:15:20 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 22932 ticks.
2020/03/16 03:15:20 [frame:3] Frames last 0.50s = 22050 audio samples = 13 video samples = 286650 ticks.
```
And FFMPEG detects input FPS at 26, but outputs at 2 fps

It seems to me that the desired output FPS is being affected by the decision of the number of video samples inside each frame
Such that the final output FPS becomes  `Target FPS / Samples per frame`
25/1 = 25 (expected)`
30/2 = 15
26/13 = 2

I have verified this holds for many other choices of framerate

Further more I have just resolved the problem with 44100Hz audio @ 30fps video by using
`set("frame.duration",0.03)`  which forces a single video sample per frame

**Comment by toots** [comment]
Thanks for reporting this. I think that it is time to revisit how we deal with streams with multiple content types.
