### ISSUE TITLE
Issues with playing dynamic audio files using the LS OPAM version (didn't have this issue with LS deb version)

### ISSUE THREAD

**Issue by jzvi12** [savonet/liquidsoap#1114]
I have an issue with the following 3 playlists with daily news, each one has only one mp3 file in it:

```
%include "/home/ubuntu/.opam/default/lib/liquidsoap/share/liquidsoap/1.4.1/libs/utils.liq"
%include "/home/ubuntu/.opam/default/lib/liquidsoap/share/liquidsoap/1.4.1/libs/fades.liq"
%include "/home/ubuntu/.opam/default/lib/liquidsoap/share/liquidsoap/1.4.1/libs/shoutcast.liq"
...
am_news = playlist(mode="normal",reload=45,reload_mode="rounds","/path/to/dir/am_news.txt")
pm1_news = playlist(mode="normal",reload=45,reload_mode="rounds","/path/to/dir/pm1_news.txt")
pm2_news = playlist(mode="normal",reload=45,reload_mode="rounds","/path/to/dir/pm2_news.txt")
```
I use an external (bash) script to download these mp3 files every day (M-F) before
they are scheduled, and the script OVERWRITES the existing mp3 file using the same file name. 

In my case, I configured the SWITCH operator to schedule and play these mp3 playlists at specific time (3x a day). But ever since I upgraded from 'LS deb' version to the 'LS OPAM' version, the SWITCH operator only works once after I restart LS. I mean when I restart LS, it works fine at the scheduled time but only one round (once), then nothing plays the next day and son on... 

```
s = fallback(track_sensitive = false, [switch([
({(1w or 2w or 3w or 4w or 5w) and 09h-09h50}, once(am_news)),
({(1w or 2w or 3w or 4w or 5w) and 15h-15h50}, once(pm1_news)),
({(1w or 2w or 3w or 4w or 5w) and 18h-18h50}, once(pm2_news))]),
timed_promotions, play_station_id,s])
```

Similar to: [https://savonet-users.narkive.com/Z626DVjV/problems-with-playing-dynamic-audio-files](url)

**Comment by jzvi12** [comment]
From @toots 

> Ok. Sam has added something recently in the latest master that I believe will solve your issue.
> 
> Instead of using once, you should use predicate.activates Here's how:
> 
> 1. Remove `once` in your script
> 
> 2. Add the following code at the top:
> ```
> def predicate.activates(~init=false, p)
>   last = ref(not init)
>   fun () -> begin
>     cur = p()
>     ans = (not !last) and cur
>     last := cur
>     ans
>   end
> end
> ```
> 
> 3. Replace your switch conditions as follows:
> ```
> s = fallback(track_sensitive = false, [
>   switch([
>     (predicate.activates({(1w or 2w or 3w or 4w or 5w) and 09h-09h50}), am_news),
>     (predicate.activates({(1w or 2w or 3w or 4w or 5w) and 15h-15h50}), pm1_news),
>     (predicate.activates({(1w or 2w or 3w or 4w or 5w) and 18h-18h50}), pm2_news)
>   ]),
>   timed_promotions, play_station_id,s
> ])
> ```

Applied the above changes suggested by @toots. My LS is currently up and running. Will monitor the behavior and report back.

**Comment by jzvi12** [comment]
code seems to work fine but there was a bug with the rotate operator. See https://github.com/savonet/liquidsoap/pull/1129

Once new build is out, will test code again, confirm is working, then close ticket.

**Comment by toots** [comment]
Any update on this one? We've got another `1.4.3` pre-release pending with another fix on `rotate` :-) Mind trying it?
