### ISSUE TITLE
Unexpected behaviour when inserting metadata in 1.4.1

### ISSUE THREAD

**Issue by th3hamm0r** [savonet/liquidsoap#1115]
**Describe the bug**
We have a script that works with 1.1.1 and 1.3.7, but does not with 1.4.1 (actually we wanted to upgrade from 1.1.1 to 1.4.1, but now stopped at 1.3.7).
Basically we are processing and storing the metadata of a stream (`map_metadata`, `on_metadata`), then we drop it (`drop_metadata`), then we insert it later with our own logic (`insert_metadata`), which will trigger `output.file` to reopen on every insertion.

**To Reproduce**

    # INSERT SOURCE WITH METADATA (preferably not generated by liquidsoap, to avoid further inference)
    source = audio_to_stereo(input.http("http://...", buffer=5., max=20.))

    _log = log(label="metadata test")

    current_track_number = ref 0

    def update_upstream_metadata(m) =
        _log("update_upstream_metadata - tracknumber: #{string_of(!current_track_number)}, upstream meta data: #{string_of(m)}")
        new_meta = [("tracknumber", string_of(!current_track_number)), ("track_start", string_of(gettimeofday()))]
        current_track_number := !current_track_number + 1
        new_meta
    end

    source = map_metadata(update_upstream_metadata, source)

    last_metadata = ref []

    def on_metadata_handler(m)
        _log("on_metadata_handler - metadata: #{string_of(m)}")
        last_metadata := m
    end

    source = on_metadata(on_metadata_handler, source)

    source = drop_metadata(source)

    insert_pair = insert_metadata(source)

    insert_metadata_function = ref fst(insert_pair)
    source = snd(insert_pair)

    execution_id = ref 0

    def execute_insert_metadata()
        _log("execute_insert_metadata - metadata: #{string_of(!last_metadata)}")
        new_metadata = list.append([("comment", string_of(!execution_id))], !last_metadata)

        execution_id := !execution_id + 1

        f = !insert_metadata_function
        f(new_metadata)

        5.0
    end

    add_timeout(5.0, execute_insert_metadata)

    file_source = output.file(
        %vorbis,
        "/tmp/%Y-%m-%d-%H:%M:%S-$(tracknumber)-$(comment).ogg",
        fallible=true,
        reopen_on_metadata=true,
        reopen_delay=0.01,
        on_start={_log("on_start")},
        on_stop={_log("on_stop")},
        on_close=fun(filename) -> _log("on_close #{filename}"),
        source
    )

**Expected behavior**

If we call `insert_metadata_function` the metadata should get inserted into the source AFTER `drop_metadata`. So the `output.file` will restart with a new file everytime we call this function.
Starting with 1.4.x the metadata gets inserted BEFORE `map_metadata`. But this will be dropped again by `drop_metadata` and so `output.file` will never reopen the file, because no metadata change will get to the output. Only one large file will be produced.

The above script should log something like:

    on_start...
    update_upstream_metadata - tracknumber: 0...
    on_metadata_handler..."tracknumber","0"...
    ... after 5s ...
    execute_insert_metadata..."tracknumber","0"...
    on_close...
    ... after 5s ...
    execute_insert_metadata..."tracknumber","0"...
    on_close...
    ... NEW METADATA ...
    update_upstream_metadata - tracknumber: 1...
    on_metadata_handler..."tracknumber","1"...
    ...
    execute_insert_metadata..."tracknumber","1"...
    on_close...
    ...

But with 1.4.1 it looks like:

    on_start...
    update_upstream_metadata - tracknumber: 0...
    on_metadata_handler..."tracknumber","0"...
    ... after 5s ...
    execute_insert_metadata..."tracknumber","0"...
    update_upstream_metadata - tracknumber: 1...
    on_metadata_handler..."tracknumber","1"...
    ... after 5s ...
    execute_insert_metadata..."tracknumber","1"...
    update_upstream_metadata - tracknumber: 2...
    on_metadata_handler..."tracknumber","2"...
    ...

**Version details**
 - OS: Ubuntu 16.04
 - Version: 1.4.1

**Install method**
`opam`

**Comment by toots** [comment]
Hi. Thanks for the report. I can definitely reproduce and will try to fix ASAP, this would be a great one to add to the upcoming `1.4.2` release.
