### ISSUE TITLE
ACC+ does not work after update from Debian 8 (Liquidsoap 1.1.1) to Debian 10 (Liquidsoap 1.3.3)

### ISSUE THREAD

**Issue by kleinadam** [savonet/liquidsoap#1116]
On Debian 8 the installation and usage of Liquidsoap was easy: 
deb ftp://ftp.deb-multimedia.org jessie main non-free
apt-get install deb-multimedia-keyring
apt-get install liquidsoap-plugin-lame libaacplus-ocaml-dynlink liquidsoap
ready !

After upgrading to Debian 10, the multimedia repository provides Liquidsoap 1.3.3 but the since years established config for AAC+ does not work any more. No one of the 3 acc-outputs below works, liquidsoap gives "parse error" on that line, second character. 

output.icecast(
%aacplus(channels=2, samplerate=44100, bitrate=48),
#%aac(channels=2, samplerate=44100, bitrate=128, adts=true),
#%fdkaac(channels=2, samplerate=44100, aot="mpeg2_he_aac_v2", transmux="adts", sbr_mode=false, bitrate=48),
name="RADIO",
...
...
Any idea how to fix or easily install and adapt to Debian 10? 

Thank you in advance. 

Regards from Bavaria/Germany, stay healthy!

Adam

**Comment by toots** [comment]
Hi @kleinadam. Thanks for the report. I hope y'all stay healthy over there as well.

Your problem most likely comes from a difference in the version of the OCaml compiler that was used to compile liquidsoap `1.3.3` and the `libaacplus-ocaml-dynlink` package.

I'd suggest to recompile `libaacplus-ocaml-dynlink` with the latest compiler from the distribution. Using standard debian packaging tools _should_ make that fairly easy.

However, if you're going down the path of recompiling stuff, I'd suggest to simply look at recompiling liquidsoap using `opam`. `opam` is a fairly simple tool to use once you are used to it and it would also provide the latest released version, which is the one for which we're currently fixing bugs.

**Comment by kleinadam** [comment]
Dear toots,

thanks for reply. 

It works further fine with MP3, means:
%mp3.cbr(samplerate=44100, internal_quality=9, bitrate=128, stereo=true),
but not with any acc-encoder. 

The installation described on the page for debian (install liquidsoap-master) does not work as well. 

Is there no way to get an pre-complied binary for amd64, as ffmpeg is able to provide it for users? 

I just want to use liquidsoap for transconding livestreams, no other stuff. 

Thank you!

**Comment by toots** [comment]
Hi,

I just released a new version of `ocaml-fdkaac` (`0.3.2`) this version should support both `libfdk-aac` `0.1.6` and `2.0.x`. Dynlink support, however, had to be dropped as it hasn't proven very reliable. I'd recommend to install via `opam`, which should carry this version shortly: https://github.com/ocaml/opam-repository/pull/16087
