### ISSUE TITLE
Windows Binaries crashing / not starting

### ISSUE THREAD

**Issue by whyronimus** [savonet/liquidsoap#1120]
Hello,

I just downloaded Windows binaries (both 32 and 64bit). The binaries do not start, first thing which is popping up is windows bit defender stating my computer had been protected, which normally would indicate malware attack. After manually authorizing the liquidsoap.exe, it still does not start - for a flash of a second you se a CLI window or similar appearing and disappearing, but after this, nothing happens. Is there anything I am doing wrong?

System ist Windows 10, on latest updates (KB4541335). I tried with Versions 1.4.0 and 1.3.7 of liquidsoap. Glad for any help.

**Comment by ignaciovenezia** [comment]
What script are you running? If your script has any issues the CLI will flash like that when opening the binary.
Same will happen if you open the .exe without any arguments of any kind.

**Comment by whyronimus** [comment]
Hello, I clicked on liquidsoap.exe. What parameters/arguments should I pass? If you have a link to a documentation, I'd be grateful.

**Comment by ignaciovenezia** [comment]
Sure, here's a link to the docs: https://www.liquidsoap.info/doc-1.4.1/

**Comment by toots** [comment]
Hi @whyronimus! Thanks for your interest! Liquidsoap is a command-line utility. To use it, you will need to open a terminal/console and execute it with a script. Some like:
```
liquidsoap.exe path\to\script.liq
```
I'll be closing this ticket but feel free to come chat with us on slack if you need more info!
