### ISSUE TITLE
Scheduled playlist

### ISSUE THREAD

**Issue by Ceel0** [savonet/liquidsoap#1121]
Hello there,

I'm new with Liquidsoap. I just installed a webradio with LiquidSoap and Icecast, all is working perfectly, thank you for your software.

My LiquidSoap's config file is simple :
```
output.icecast(%vorbis,
host = "localhost", port = 8000,
password = "pass", mount = "mountpoint",
url="url",
name="name",
genre="Music",
description="description",
public=true,
fallible=true,
mksafe(playlist(mode="randomize","/path")))
```

I'm trying to schedule my playlists, for example :
- playlist1 on monday between 1AM and 7AM
- playlist2 between 7AM en 1PM
- playlist3 on tuesday, etc.

People are talking about Airtime on internet, is it the only option ? If so, how can i install and use it ?
If not, can is just configure ma config file?

Thank you in advance,

Ceelo

**Comment by smimram** [comment]
You should use `switch` to switch between playlists. A source of the form
```
switch([ ({0h-7h}, night), ({7h-24h}, day) ])
```
will play the playlist `night` from 0 to 7h and `day` otherwise. See for instance here: https://www.liquidsoap.info/doc-1.4.1/complete_case.html

**Comment by Ceel0** [comment]
Hello Samuel,

Thank you for your answer.

Can we scheduled playlist regarding the day of the week?

BR,

Ceelo

**Comment by smimram** [comment]
yes, you've got some examples here: https://www.liquidsoap.info/doc-1.4.1/language.html#time-intervals

The predicate for monday between 1 and 7 am is for instance `{1w and 1h-7h}`

**Comment by Ceel0** [comment]
Thank you very much Samuel, i will test it.

BR,

**Comment by Ceel0** [comment]
Hello Smimram,

How are you ? I hope you're well.

I'm trying to configure my liquidsoap file... :)

Could you please help me with 1 example :
- For example, if i want to play the playlist "TOTO" on monday between 1:00AM and 2:00AM
- And what is the syntax with my file (below) to integrate the switch configuration ?
output.icecast(%vorbis,
host = "localhost", port = 8000,
password = "pass", mount = "mountpoint",
url="url",
name="name",
genre="Music",
description="description",
public=true,
fallible=true,
mksafe(playlist(mode="randomize","/path")))

Thank you very much in advance,

Ceelo

**Comment by Ceel0** [comment]
Hello,

I'm trying with this configuration for example :

#!/usr/bin/liquidsoap

output.icecast(%vorbis,
host = "localhost", port = 8000,
password = "pass", mount = "mountpoint",
url="url",
name="name",
genre="Music",
description="description",
public=true,
fallible=true,
playlist1=playlist(mode='random', "/path/playlist1")
playlist2=playlist(mode='random', "/path/playlist2")
    default=fallback([
        switch([
            ({ (1w or 2w or 3w or 4w or 5w or 6w or 7w) and 0h-10h}, playlist1),
            ({ (1w or 2w or 3w or 4w or 5w or 6w or 7w) and 10h-23h59}, playlist2),
            ])
            ])
default=mksafe(default)

When i'm trying to restart liquidsoap i get this error : 
Stopping liquidsoap channels: no script found in /etc/liquidsoap
Starting liquidsoap channels: radio.liq Line 13, char 28 before "=": Parse error!
OK

Please, could you help me ?

BR,

Ceelo
