### ISSUE TITLE
Replaygain extraction works in version 1.5.0, but fails in version 1.4.1

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1125]
I have installed both version 1.4.1 and 1.5.0 via opam on a Debian 9 setup.
I find that replaygain extraction works flawlessly on the git version. However, in version 1.4.1 I get ...
`[extract.replaygain:4] Replaygain extraction failed:`

Have any changes occurred that may prevent replaygain from working properly on versions 1.4.1? If so, can this functionality be reinstated to this version?

**Comment by smimram** [comment]
The main script for replaygain extraction is `extract-replaygain` which seeming does not have changed much: https://github.com/savonet/liquidsoap/compare/1.4.1...master#diff-19ebacb43328e2fff10d008e2125b5b3

What happens when you run `extract-replaygain somefile.mp3`? (you should get a dB as output)

**Comment by oranjebloom** [comment]
I ran this and got no output

`/home/amdin/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/1.4.1/bin/extract-replaygain /ssr/uploads/voxinterlude1.mp3`

... although I have seen dB outputs in the past. When I spoke to Romain about it on slack, he said 

"Ha, yes, there was a change introduced in 1.5 on the script that might explain why it works now. Good to known thank, I'll keep it in mind for a possible bugfix."

**Comment by oranjebloom** [comment]
So I ran further tests, this time with version 1.3.7 ... which works btw. In version 1.3.7, a manual test of extract-replaygain on an mp3 file shows the following dB output ...

`$ sudo ~/.opam/4.07.1/lib/liquidsoap/lib/liquidsoap/1.3.7/extract-replaygain /ssr/uploads/test.mp3
[sudo]` 
`-0.30 dB`

When I do the same thing in version 1.4.1, I get nothing

`$ sudo ~/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/1.4.1/bin/extract-replaygain /ssr/uploads/test.mp3`

Does this have anything to do with the fact that the path to the extract-replaygain script changed after version 1.3.7?

**Comment by toots** [comment]
Unfortunately, there was a minor change in the script that made it work:
```diff
diff --git a/scripts/extract-replaygain b/scripts/extract-replaygain
index a0779b70..a8eaacb8 100755
--- a/scripts/extract-replaygain
+++ b/scripts/extract-replaygain
@@ -1,17 +1,18 @@
 #!/bin/sh
+
 set -e

-FFMPEG=`which ffmpeg`
+FFMPEG=`which ffmpeg || echo ""`

 if test -z "$FFMPEG"; then
-       echo "ffmpeg must be installed"
-       exit 1
+  echo "ffmpeg must be installed"
+  exit 1
 fi

-SED=`which gsed`
+SED=`which gsed || echo ""`

 if test -z "$SED"; then
-  SED=`which sed`
+  SED=`which sed || echo ""`
 fi

 if test -z "$SED"; then
@@ -20,4 +21,3 @@ if test -z "$SED"; then
 fi

 $FFMPEG -i "$1" -vn -filter replaygain -f null /dev/null 2>&1 | $SED -n -r 's/.* track_gain = ([-+]?[0-9]+\.[0-9]+ dB).*/\1/p'
-
```

I'm gonna have a `1.4.2` branch started..

**Comment by toots** [comment]
Actually, it's already started..

**Comment by toots** [comment]
I'm gonna close this since the fix is already in `master`. However, keep an 👁 open for an up-coming `1.4.2` bugfix release with the fix in it..
