### ISSUE TITLE
Liquidsoap hanging during shutdown (dup)

### ISSUE THREAD

**Issue by AxisNL** [savonet/liquidsoap#1126]
Issue https://github.com/savonet/liquidsoap/issues/843 was closed with 'can't reproduce', then another user reproduced it. However, I cannot open that ticket again. I feel bad about opening a new ticket, but know no other way to get it opened.

Our helpdesk employee has to log into our servers and manually kill -9 hanging liquidsoap processes for the past months :(

**Comment by smimram** [comment]
I have reopened #843 and am closing this one in order to keep history.
