### ISSUE TITLE
Muxing with a fallible 'main' source 

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1128]
https://github.com/savonet/liquidsoap/blob/53bd2f169c0cff683d8331a2b23defe7f1e972ed/src/conversions/mux.ml#L34

This is a little annoying if we want to mux video with a live audio source like `input.harbor()`

Consider the following fallback flow 
```
fallback(
    track_sensitive=false,
    [live_video, live_audio+mux, rotate([local_video, local_audio+mux])])
```

For the moment I think I could hack that kind of flow together with more manual triggering of a `switch` operator

**Comment by toots** [comment]
Thanks for the report. I'll see what I can do but I believe that it's important to keep the simple cases simple.. You case seems a little more advanced.

For now, I would suggest, indeed, to use a `switch` triggered by a reference to a boolean that you can flip whenever someone connects to the harbor..

**Comment by toots** [comment]
Fixed in latest `master`!
