### ISSUE TITLE
Allow cross() to accept sources with video

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1132]
Currently cross only accepts `source(audio='#a+1, video=0, midi=0)`
It would be great if it could accept sources with video to apply some crossfades or other transitions

Edit: One final thing, with the `fade.initial` `fade.final`, they do accept sources with video, does this mean they fade both the audio volume and video to black?
Because that would be the default kind of transition for cross with video

**Comment by smimram** [comment]
@toots after a quick look at the code for cross I don't see anything which really requires preventing video in cross, do you?
