### ISSUE TITLE
Standard audio/flac mime type is not supported

### ISSUE THREAD

**Issue by mutantmonkey** [savonet/liquidsoap#1143]
**Describe the bug**
When creating a request for a FLAC file (e.g. https://www.example.com/music.flac), Liquidsoap does not support the audio/flac MIME type:
```
2020/04/07 00:33:08 [procol.external:3] No known file extension for mime: audio/flac
2020/04/07 00:33:08 [decoder:3] Unable to decode "/tmp/liq-process3712a3.osb" as {audio=1+;video=0;midi=0}!
```

**To Reproduce**
Configure a web server to return the MIME type audio/flac for FLAC files. For nginx, this can be done by editing /etc/nginx/mime.types and adding the following line:
```
audio/flac flac;
```

Upload a FLAC file to your web server and note the URL. Then use the following script, replacing the URL as appropriate:
```
def my_request() =
    request.create('https://www.example.com/music.flac')
end
demo = mksafe(request.dynamic(my_request))
output.pulseaudio(demo)
```

**Expected behavior**
The audio/flac MIME type should be handled the same way as audio/x-flac.

**Version details**
 - OS: Debian
 - Version 1.4.1

**Install method**
Installed from source on Debian Bullseye

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/download.html)

**Comment by smimram** [comment]
I just commited a fix, you can use `audio/x-flac` as mime for flac in the meantime.
