### ISSUE TITLE
Include opam library requirements for codecs, inputs, outputs, etc

### ISSUE THREAD

**Issue by tristan-nel** [savonet/liquidsoap#1145]
I've noticed a cycle of trying to implement a codec, input, or output, liquidsoap complaining about it, and then having to either ask on Slack or searching old issues for which opam lib will allow me to proceed.

Could the liquidsoap docs be updated to include which opam lib enables which feature? Maybe a script sample?

For example for using AAC in LS:

_Requires the faad lib in OPAM_
```bash
opam install depext
opam depext faad
opam install faad
```

Consider also listing the minimum OCaml version for this lib and liquidsoap to work together

**Comment by toots** [comment]
There is a page here: https://www.liquidsoap.info/doc-1.4.1/build.html but it's not visible enough. I'll look at making it better.

**Comment by tristan-nel** [comment]
Found this listing as well after a bit of further reading
https://www.liquidsoap.info/modules.html
But more visibility is always helpful
