### ISSUE TITLE
Using `single` fails with MIME type error in log

### ISSUE THREAD

**Issue by makeworld-the-better-one** [savonet/liquidsoap#1157]
Here's part of my script that causes the issue:
```
single("https://podcast-a.akamaihd.net/mp3/hourlynews.mp3")
```
Here's the relevant part of the log output:
```
2020/04/13 15:33:05 [procol.external:3] Failed to fetch mime-type for https://podcast-a.akamaihd.net/mp3/hourlynews.mp3.
2020/04/13 15:33:05 [procol.external:3] No known file extension for mime: 
2020/04/13 15:33:06 [decoder:3] Method "FFMPEG" accepted "/tmp/liq-processabf80a.osb".
2020/04/13 15:33:06 [procol.external:3] Failed to fetch mime-type for https://podcast-a.akamaihd.net/mp3/hourlynews.mp3.
2020/04/13 15:33:06 [procol.external:3] No known file extension for mime: 
2020/04/13 15:33:07 [decoder:3] Method "FFMPEG" accepted "/tmp/liq-process0acc56.osb".
```
It seems like it thinks there is a blank or empty MIME type for the file. The server does return a `Content-Type: audio/mpeg` header though.

**Version details**
 - OS: Debian Buster (stable)
 - Version: 1.4.1

**Install method**
Installed from Debian testing (bullseye).

**Comment by toots** [comment]
Thanks for reporting this. This should be fixed in `1.4.2` now, would you be able to test it there? All you should have to do is:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
git checkout 1.4.2
opam install -y .
```
`1.4.2` is a bugfix release so it should be a drop-in replacement for `1.4.1`, no need to change your scripts and etc.

**Comment by makeworld-the-better-one** [comment]
That's great news! However, when I do the final install step, even though opam told me `1.4.2` was installed, running `liquidsoap --version` says `1.4.1`. This happens even after uninstalling liquidsoap through opam, and then installing it from the git repo only, so maybe it's just that version-printing part of the code that wasn't updated?

Anyway, using `single` now doesn't cause any errors, and I was able to get the file to play.

**Comment by toots** [comment]
Great! The version is a glitch, fixing now, thanks for reporting.
