### ISSUE TITLE
Playlist prefix not triggering protocol [master]

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1162]
`playlist(prefix="replay_gain:", ...)` is not triggering the replay_gain protocol
`playlist(prefix="fake_protocol:", ...)` is not logging of an 'unknown protocol' warning

This was definitely working previously, as I was using a custom replay_gain script to return LUFS values. I have not yet identified which commit has caused this issue

**Comment by toots** [comment]
Thanks for reporting. That should be fixed now! Can you confirm?
