### ISSUE TITLE
playlist behaviour with subfolders ?

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1163]
I've been experiencing a bug (or a feature?) with playlist subfolders
Given a playlist:
`playlist(mode="radomize", reload=1, reload_mode="rounds", "/playlist_dir")`

The root playlist is randomized, then subfolders.
Once entering into a subfolder, the entire subfolder contents plays out before returning to the root, or a sibling subfolder.

Is this behaviour desired? In my case it is not as I use subfolders or organise artists/albums not for implicit sequencing.
I believe this only effects the `reload_mode="rounds"` implementation. I have not noticed it in my larger folder that is set to `reload_mode="seconds"`

**Comment by MaPePeR** [comment]
Not sure if this is related to this or a separate issue, but with `1.4.1-415-g94c080d6` the playback using folders just stops at some point for me, even though everything should be looping just fine. I now created a playlist from my folder using `find -type f folder/ > playlist.m3u` and this has not stopped randomly, yet.

**Comment by toots** [comment]
Hi! What version of liquidsoap are you using? Reading the current playlist code, files are first listed, included all sub-folders, and then randomized so this should not happen.

**Comment by dhannyz** [comment]
I too read over the code for this, and couldn't make sense of it.
Perhaps its was some very unlikely RNG runs for the times I did test it

Closing for now

**Comment by toots** [comment]
I'm reopening this since we just had a similar report in the slack channel.

**Comment by toots** [comment]
> huh I've just noticed something really strange with one of my instances on 1.5.x
> 
> I make it read a folder with the default playing mode, it works fine for a while, random and etc, but then after a while it starts acting strange and playing songs in the same subfolder until it has played all of them, in a very specific pattern, then goes to the next
> 
> and so on

**Comment by smimram** [comment]
I read the code again and don't see how this could happen... :(
