### ISSUE TITLE
Problem with documentation on https://www.liquidsoap.info/doc-1.4.1/hls_output.html

### ISSUE THREAD

**Issue by luisogandob** [savonet/liquidsoap#1164]
**Describe the bug**
The exampled included in documentation is not working to me, cause i think there is no way to get the codec "libfdk_aac" using %ffmpeg cause ocaml-ffmpeg uses the function avcodec_find_encoder_by_name and that function cannot return libfdk-acc cause it shares same codec id of acc.

Trying to use the %ffmpeg as the example on documentation will always lead you to a: 
Fatal error: exception FFmpeg.Avutils.Error(Encoder not found)

I think srt2hls team knows that too cause they change the [live.liq](https://github.com/mbugeia/srt2hls/blob/master/radio/live.liq) file to use custom %audio encoder.

**To Reproduce**
1. Build FFMpeg with libfdk-acc enabled
2. Verify encoder is available running: # ffmpeg -encoders 
3. Try to use %ffmpeg with codec="libfdk_aac"

**Version details**
 - OS: Centos
 - Version: 7

**Install method**
Installed via Opam with a custom build FFMPEG

**Comment by dhannyz** [comment]
@luisogandob you may need to make sure you compile ffmpeg and all supporting libraries with static libs instead of shared ones

**Comment by luisogandob** [comment]
> @luisogandob you may need to make sure you compile ffmpeg and all supporting libraries with static libs instead of shared ones.
> I have been using fdkaac and h264_nvenc without issues

I did. 

![image](https://user-images.githubusercontent.com/10240251/79402915-500cf780-7f5b-11ea-860a-15fe9a8e990e.png)

After that i did a test using the example of https://www.ffmpeg.org/ffmpeg-codecs.html.
`ffmpeg -i input.wav -codec:a libfdk_aac -vbr 3 output.m4a`

I even list the encoders available using...
`ffmpeg -encoders`

**Comment by luisogandob** [comment]
> @luisogandob you may need to make sure you compile ffmpeg and all supporting libraries with static libs instead of shared ones.
> I have been using fdkaac and h264_nvenc without issues

Are you using %ffmpeg as the example?
```
aac_lofi = %ffmpeg(format="mpegts",
                   codec="libfdk_aac",
                   channels=2,
                   ar=44100,
                   b="32k",
                   afterburner=1,
                   profile="aac_he_v2")
```

**Comment by dhannyz** [comment]
you may need to add --enable-static --disable-shared
![image](https://user-images.githubusercontent.com/25068340/79403990-c1888c80-7fd3-11ea-869e-6df8241c39a8.png)

**Comment by dhannyz** [comment]
Perhaps im using a more recent build, as the arguments to %ffmpeg have changed
```
encoder = %ffmpeg(
    %video(codec="h264_nvenc", b="3500k", preset="llhq", rc="cbr_ld_hq", coder="cabac", g=30, r=30, bf=2),
    %audio(codec="libfdk_aac", b="128k"),
    format="flv"
)
```

**Comment by luisogandob** [comment]
> you may need to add --enable-static --disable-shared
> ![image](https://user-images.githubusercontent.com/25068340/79403990-c1888c80-7fd3-11ea-869e-6df8241c39a8.png)

Let me try adding those parameters.

**Comment by luisogandob** [comment]
> you may need to add --enable-static --disable-shared
> ![image](https://user-images.githubusercontent.com/25068340/79403990-c1888c80-7fd3-11ea-869e-6df8241c39a8.png)

New build, same result...

![image](https://user-images.githubusercontent.com/10240251/79405719-2d7edc80-7f63-11ea-913e-0fffda327426.png)

![image](https://user-images.githubusercontent.com/10240251/79405769-4be4d800-7f63-11ea-802c-d45c29108f11.png)

**Comment by dhannyz** [comment]
Hmm, try also building libfdk_aac itself with static libs
```
cd ~/ffmpeg_sources && \
git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
cd fdk-aac && \
autoreconf -fiv && \
./configure --prefix="$HOME/ffmpeg_build" --disable-shared && \
make -j 4 && \
make install
```

**Comment by luisogandob** [comment]
I track the error and that it's comming from ocaml-ffmpeg which use AVCodec to search the codec by name, AVCodec use a function that iterates trough the codecs by their Codec ID. Problem resides in that FDK-ACC use the same Codec ID than ACC in FFMPEG (i verified that in libavcodec/libfdk-accenc.c) and that's why AVCodec cannot found the codec named libfdk_acc.

![image](https://user-images.githubusercontent.com/10240251/79406314-bf3b1980-7f64-11ea-9c03-97e27e5782c0.png)

**Comment by luisogandob** [comment]
> Hmm, try also building libfdk_aac itself with static libs
> 
> ```
> cd ~/ffmpeg_sources && \
> git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
> cd fdk-aac && \
> autoreconf -fiv && \
> ./configure --prefix="$HOME/ffmpeg_build" --disable-shared && \
> make -j 4 && \
> make install
> ```
> 
> Try rebuilding the ocaml-ffmpeg after too

I did that, i even submit a PR to ocaml-ffmpeg to fix a c99 standard issues.

**Comment by toots** [comment]
@luisogandob You should be using the syntax that @dhannyz has outlined indeed. The doc for liquidsoap `1.4.1` is for the old syntax/old binding. We are actively developing this part of the software currently so things gets broken and change. The dev doc seems up-to date to me, though: https://www.liquidsoap.info/doc-dev/hls_output.html
```
aac_lofi = %ffmpeg(format="mpegts",
                   %audio(
                     codec="libfdk_aac",
                     channels=2,
                     ar=44100,
                     b="32k",
                     afterburner=1,
                     profile="aac_he_v2"
                   ))
```
and etc.

**Comment by toots** [comment]
Hi! I'm gonna close this one. We changed the documentation to use the builtin `aac` codec. Please feel free to join our slack channel if you have more questions!

**Comment by sonyarianto** [comment]
> @luisogandob You should be using the syntax that @dhannyz has outlined indeed. The doc for liquidsoap `1.4.1` is for the old syntax/old binding. We are actively developing this part of the software currently so things gets broken and change. The dev doc seems up-to date to me, though: https://www.liquidsoap.info/doc-dev/hls_output.html
> 
> ```
> aac_lofi = %ffmpeg(format="mpegts",
>                    %audio(
>                      codec="libfdk_aac",
>                      channels=2,
>                      ar=44100,
>                      b="32k",
>                      afterburner=1,
>                      profile="aac_he_v2"
>                    ))
> ```
> 
> and etc.

Hi @toots btw I tried this on v1.4.4 via Opam it says "Syntax error" pointing to %audio line.
