### ISSUE TITLE
LS Crash - Assertion failure error message (psymodel.c)

### ISSUE THREAD

**Issue by alexhorner** [savonet/liquidsoap#1166]
**Describe the bug**
Today an issue was experienced during handover between DJs on our station. LS crashed completely with the following error:

liquidsoap: psymodel.c:576: calc_energy: Assertion `el >= 0' failed.

**To Reproduce**
We do not know how to reproduce this bug. We have never had it occur before and it occured in a live environment, and has only happened once, not again since LS started again, meaning several DJs have done handover without issue.

**Expected behavior**
Any handover between DJs (disconnect and connect) should not cause an LS crash

**Version details**
 - OS: Ubuntu 18.04.4 in Docker (AzuraCast)
 - Version: 1.4.1

**Install method**
Running in Docker, with a standard AzuraCast installation

**Comment by toots** [comment]
Hi,

This is pretty annoying indeed. The message looks like an error for one of our underlying libraries. From memory, it looks like an error from `lame`.

I'm not sue that there's much we can do about it.  This shouldn't crash the whole program though I'm afraid, we also cannot do much. I would recommend trying a different library. Typically, ffmpeg is a good drop-in replacement for `mp3` encoding.

Another approach could be to make sure that `lame` (or perhaps `mad`) are kept to the latest released version, in hope that the bug has been fixed there with the latest version.

**Comment by smimram** [comment]
Indeed: https://github.com/gypified/libmp3lame/blob/master/libmp3lame/psymodel.c#L576
