### ISSUE TITLE
Crossfade with chop just stops

### ISSUE THREAD

**Issue by MaPePeR** [savonet/liquidsoap#1170]
**Describe the bug**
I'm experiencing the problem, that playback just stops after some time. Adding a `chop` made the problem appear very soon and i could reduce my example to 

```
output.alsa(crossfade(chop(playlist("musik.m3u"))), fallible=true)
```
which results in 
```
[alsa_out(default):3] Source failed (no more tracks) stopping output...
```
after a very short time. I also added `duration=20.` to the chop, so it would be more natural for crossfading, but the problem persists.

**Expected behavior**
I expected there to be crossfading inbetween the track and the playback not to stop at some point.
Not sure if this really reproduces my original problem or if this is just a side effect of chop+crossfade, though. It looks very similar from the log, though.

**Version details**
 - OS: Arch Linux on ARM
 - Version: `1.4.1-415-g94c080d6`

**Install method**
Installing via opam from source.

**Comment by MaPePeR** [comment]
After removing all `crossfade`s from my script it has run fine for more than 12 hours, when it previously stopped "randomly" after around 1-3 hours. So i suspect that `crossfade` is really the culprit for my original problem.

**Comment by toots** [comment]
Thanks, I'll try to reproduce asap.

**Comment by toots** [comment]
Well, that was quick:
```
2020/04/25 10:06:35 [cross_17113:3] Analysis: -14.698624dB / -15.396416dB (4.96s / 4.96s)
2020/04/25 10:06:35 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/04/25 10:06:40 [ao:3] Source failed (no more tracks) stopping output...
```

**Comment by toots** [comment]
Thanks for the report! Bug is fixed. It looks like it didn't apply to `1.4.1` and was present in a release version. Good news!
