### ISSUE TITLE
Help in setting up more reliable solution for the Covid19 situation

### ISSUE THREAD

**Issue by mbrouillet** [savonet/liquidsoap#1173]
Hello !

This is not really an issue, but a request for help. I am trying to help people in their effort to keep activities ongoing during Covid19 lockdown.

Could anyone take a look at my post on the Mixxx forum and shine some Liquidsoap advice on this. 

[https://www.mixxx.org/forums/viewtopic.php?f=1&t=13350&p=44270#p44270](https://www.mixxx.org/forums/viewtopic.php?f=1&t=13350&p=44270#p44270)

I'm in Paris, if anyone would prefer a phone-call. My first challenge would be to have all sound through one channel (that seems feasible). If you see any road down to adding video when that is needed (yoga classes…) and downgrading to audio otherwise…

Thank you !
Marcel.

**Comment by toots** [comment]
Hi @mbrouillet. Looks like a tricky situation. Liquidsoap is not really particularly geared toward low-latency live stream. Software like zoom or hangout (webRTC) are better suited for that purpose. It's a very difference ballpark there..

My best recommendation would be find a software like that that works for you and can output a single mixed signal to liquidsoap or icecast as the final stream.

**Comment by gdhgdhgdh** [comment]
Hi @mbrouillet - I've been working on a system to let remote DJ's play back to back sets, which is using liquidsoap to send output to an existing RTMP service like Twitch/Mixer. It achieves perfectly sync'd audio for two DJs so it might be of interest. Have a look at https://faraway.dj/
