### ISSUE TITLE
Cannot assign an interactive variable to `video.add_image`

### ISSUE THREAD

**Issue by gdhgdhgdh** [savonet/liquidsoap#1176]
**Describe the bug**
I would like to move an image based on the value of a telnet variable - the use-case is showing where the crossfader of two DJs playing 'back to back' is currently set to.

**To Reproduce**
```
xfader = int_of_float(interactive.float("xfader", 640.))
mixvid = video.add_image(width=32,height=128,x=xfader,y=488,file="/host/knob.png",mixvid)

At line 19, char 22-55:
Error 5: this value has type
  () -> _
but it should be a subtype of
  float

```

**Version details**
 - OS: savonet/liquidsoap-full Docker Hub image
 - Version 1.4.0

**Comment by smimram** [comment]
This should be fixed by 23c3c4d34f334d361377e9e564c74a96b0994f53.
