### ISSUE TITLE
Can't build : duppy 0.8.1 not found in opam

### ISSUE THREAD

**Issue by martinkirch** [savonet/liquidsoap#1187]
I'm currently trying to build Liquidsoap (on the `master` branch). I'm installing depencencies via `opam`, but it seems the latest `duppy`, required by Liquidsoap, has not been released yet. Here is the `./configure` final error :

```
...
checking for ocaml duppy module >= 0.8.1... configure: error: requires version >= 0.8.1 found 0.8.0.
```

I'm not sure it's an issue for `duppy` or for `Liquidsoap` ?

**Comment by smimram** [comment]
duppy 0.8.1 is available on opam. Could you try doing an `opam update`?

**Comment by martinkirch** [comment]
I had just installed so it says `no changes from https://opam.ocaml.org`...
Also 0.8.0 is still shown as latest on https://opam.ocaml.org/packages/duppy/ ?

**Comment by smimram** [comment]
Sorry, my bad. You should checkout `ocaml-duppy` and do `opam pin add .` in the git directory in order to install the git version (which is currenly 0.8.1).

**Comment by Shizmob** [comment]
For reference, to build Liquidsoap master, as of yesterday you'll also need the following pins:
```
ocaml-mm
ocaml-ogg
ocaml-vorbis
ocaml-srt
ocaml-ffmpeg
ocaml-ffmpeg-av
```

**Comment by martinkirch** [comment]
Got it, thanks !
