### ISSUE TITLE
Liquidsoap Not Terminating Script Listening on Telnet Port

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#1192]
We're investigating an issue on the AzuraCast issues section (azuracast/azuracast#2724). Essentially, in the specific circumstance where Liquidsoap is instructed to play a remote URL and is then terminated in the middle of doing so, a shell script is left running that is actively listening to the telnet port. This process gets disconnected from the parent and just stays open, so when our process manager Supervisord attempts to spin up a new Liquidsoap instance, it fails to acquire the telnet port and exits instead.

Here's the `netstat -tulpn` output once the parent Liquidsoap process is closed:

```
tcp        0      0 0.0.0.0:8014            0.0.0.0:*               LISTEN      1000       5003/sh
```

and here's the `lsof` of that specific shell process (PID 5003) itself:

```
azuracast@9ceb328b0cc0:/$ lsof -p 5003
COMMAND  PID      USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
sh      5003 azuracast  cwd    DIR    8,1     4096  400637 /var/azuracast/stations/second_test_radio/config
sh      5003 azuracast  rtd    DIR  0,118     4096  958930 /
sh      5003 azuracast  txt    REG  0,118   129816 1080228 /usr/bin/dash
sh      5003 azuracast  mem    REG    8,1          1080228 /usr/bin/dash (path dev=0,118)
sh      5003 azuracast  mem    REG    8,1          3726326 /usr/lib/x86_64-linux-gnu/libc-2.31.so (path dev=0,118)
sh      5003 azuracast  mem    REG    8,1          3726290 /usr/lib/x86_64-linux-gnu/ld-2.31.so (path dev=0,118)
sh      5003 azuracast    0r  FIFO   0,12      0t0  823635 pipe
sh      5003 azuracast    1w  FIFO   0,12      0t0  823634 pipe
sh      5003 azuracast    2w  FIFO   0,12      0t0  823636 pipe
sh      5003 azuracast    3r  FIFO   0,12      0t0  823228 pipe
sh      5003 azuracast    4w  FIFO   0,12      0t0  823228 pipe
sh      5003 azuracast    5r  FIFO   0,12      0t0  823229 pipe
sh      5003 azuracast    6w  FIFO   0,12      0t0  823229 pipe
sh      5003 azuracast    7r  FIFO   0,12      0t0  823230 pipe
sh      5003 azuracast    8w  FIFO   0,12      0t0  823230 pipe
sh      5003 azuracast    9r  FIFO   0,12      0t0  823231 pipe
sh      5003 azuracast   10w  FIFO   0,12      0t0  823231 pipe
sh      5003 azuracast   11u  IPv4 823232      0t0     TCP *:8014 (LISTEN)
sh      5003 azuracast   12r  FIFO   0,12      0t0  823608 pipe
sh      5003 azuracast   13w  FIFO   0,12      0t0  823608 pipe
sh      5003 azuracast   14r  FIFO   0,12      0t0  823609 pipe
sh      5003 azuracast   15w  FIFO   0,12      0t0  823609 pipe
sh      5003 azuracast   16r  FIFO   0,12      0t0  823633 pipe
sh      5003 azuracast   17r  FIFO   0,12      0t0  823610 pipe
sh      5003 azuracast   18w  FIFO   0,12      0t0  823610 pipe
sh      5003 azuracast   19u  sock    0,9      0t0  823611 protocol: TCP
sh      5003 azuracast   20w  FIFO   0,12      0t0  823633 pipe
sh      5003 azuracast   21r   REG  0,118  1103504 1762720 /usr/local/share/icecast/web/error.mp3
```

Happy to provide any further diagnostic information to pin down what's causing this issue.

As a secondary question...we've been operating under the assumption that the only way to instruct Liquidsoap to reload the entire `.liq` configuration file is to completely terminate the process and spin it back up anew. If there's some trick to this that would avoid that issue entirely (i.e. similar to the `USR1` interrupt for individual playlists, but for the entire configuration), by all means we'd love to know!

**Comment by toots** [comment]
It would look like you've been bitten but an issue I reported a long time ago: https://github.com/ocaml/ocaml/issues/5256

I thought that we had fixed it on our end but it would appear that we didn't...

I've just pushed a fix to `master` and a `1.4.2-cloexec` branch with the fix backported to `1.4.2`. Could that work for y'all?
