### ISSUE TITLE
"We must catchup * seconds!"

### ISSUE THREAD

**Issue by dyon-b** [savonet/liquidsoap#1200]
Hello Github,

I've had issues with my harbor inputs disconnecting at random times and then falling back for 1-2 seconds, But a hour ago it just got really bad with the music speeding up and cutting off.

![image0 33](https://user-images.githubusercontent.com/40901726/81476923-fa9fcf80-9214-11ea-9fe2-a53d00cfd94c.jpeg)
Sorry for the bad picture.

I'm running 8 harbour inputs on a proxmox VM with 24 cores running at 20-30%.
I'll gladly provide extra info or logs, Thank you in advance.

**Comment by toots** [comment]
It looks like your server was being late. Did you check that there wasn't anything else consuming CPU resources? Typically a `cron` job..

**Comment by smimram** [comment]
No answer for a long time closing, feel free to reopen.
