### ISSUE TITLE
M3U8

### ISSUE THREAD

**Issue by stardevelop** [savonet/liquidsoap#1206]
I try to stream a M3U8 Playlist (HLS) from a remote URL and I get this error:

[decoder:3] Unable to decode stream of type "application/vnd.apple.mpegurl"!

**Comment by toots** [comment]
Hi! HLS input, which needs a special workflow. Currently, the best on `master` is to use `input.ffmpeg`. However, `master` is fastly moving right now, if you're looking for production-ready stuff, you should stick to `1.4.2`, in which case I believe gstreamer is probably your best bet.

**Comment by toots** [comment]
I'm gonna close this issue. Feel free to come discuss further on our slack channel!
