### ISSUE TITLE
Stream only new files in directory

### ISSUE THREAD

**Issue by ole-luk0e** [savonet/liquidsoap#1207]
Hello!
I'm making online translation of radio broadcasts. SDR program saves audio in folder and Liquidsoap streams it to Icecast. How can I manage Liquidsoap to stream only new files in folder?
My plan is:
1. Use inotify to monitor folder and create playlist:
```
#!/bin/bash
inotifywait -e close_write --format '%f' -m "/my/folder" | \
(
while read NEWFILE
do
echo $NEWFILE >> playlist.txt
done
)

```
2.  Liquidsoap plays playlist
```
radio = mksafe(normalize(playlist(loop=false,mode='normal',reload=0,reload_mode="watch", "playlist.txt")))
output.icecast(%vorbis,
host = "localhost", port = 8000,
password = "***", mount = "radio-basic.ogg", radio)
```
3. Liquidsoap removes recently played track from playlist.
Question is how to remove track from playlist after it have been played.
Maybe there is more elegant solution for my case without using over apps, such as inotify?
Thanx!

**Comment by toots** [comment]
Hi,
That could work. The `playlist` operator also has a `check_next` callback that you might be able to use for that purpose.

Ultimately, you could also re-implement your own `playlist` with the specs that you want. Our own version is defined in liq code already, here: https://github.com/savonet/liquidsoap/blob/master/libs/playlist.liq

I'll close this now. Feel free to come discuss it further in our slack channel!
