### ISSUE TITLE
liquidsoap process deadlocks at 100% cpu. Similar in description to issue #485 

### ISSUE THREAD

**Issue by dbrownidau** [savonet/liquidsoap#1209]
**Describe the bug**
Two liquidsoap threads spool at 100% CPU indefinitely and become unresponsive.
`straces` shows the main thread `rt_sigtimedwait([INT TERM],` indefinitely - the other (child) thread is attempting to read something.
`perf stat` shows 51.30% of (2.104GHz * 3.65s * 2cores) cycles as backend-stalled.

**To Reproduce**
Cannot reliably reproduce. Occurs randomly. I have a coredump if you want it (600MB).

**Version details**
 - Hypervisor: QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u5)
 - Kernel: 4.15.0-99-generic, 
 - OS: Ubuntu 18.04.2
 - The OCaml toplevel, version 4.05.0
 - Liquidsoap 1.4.2

**Install method**
Built by AzuraCast.
Issue still occurred when using LiquidSoap natively (why I migrated to AzuraCast)

**Logs**
```
2020/05/20 16:04:46 [decoder:3] Method "FLAC" accepted "/var/azuracast/stations/file.flac".
2020/05/20 16:05:35 [X_next_song:3] Prepared "/var/azuracast/stations/file.flac" (RID 7).
2020/05/20 16:05:35 [cross_7709:3] Analysis: -143.686790dB / -13.815549dB (3.00s / 3.00s)
2020/05/20 16:05:35 [crossfade:3] No transition: using default.
2020/05/20 16:05:35 [decoder:3] Method "FLAC" accepted "/var/azuracast/stations/file2.flac".
2020/05/20 16:05:36 [lang:3] AzuraCast Feedback Response: OK
2020/05/20 16:05:38 [lang:3] AzuraCast Feedback Response: OK
2020/05/20 17:28:01 [main:3] Shutdown started!
2020/05/20 17:28:01 [main:3] Waiting for main threads to terminate...
2020/05/20 17:28:11 >>> LOG START
2020/05/20 17:28:11 [main:3] Liquidsoap 1.4.2
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/12037038/82416579-9b1bac80-9abd-11ea-922a-02404cf38f32.png)

![image](https://user-images.githubusercontent.com/12037038/82416616-a969c880-9abd-11ea-90e6-bdabf12562c9.png)

PID3999:
![PID3999](https://user-images.githubusercontent.com/12037038/82416811-06fe1500-9abe-11ea-9d37-4476e752068c.png)

PID4021:
![PID4021](https://user-images.githubusercontent.com/12037038/82416838-0d8c8c80-9abe-11ea-844f-0b60a41f8354.png)

**Comment by toots** [comment]
Hi, thanks for the report. The coredump would help indeed. The lops seem to show a restart, was that the case?

**Comment by dbrownidau** [comment]
Hello, Yes - the restart was triggered by operator. I have just sent you an email regarding the coredump material.

**Comment by dbrownidau** [comment]
```
SHA1 (1209-1.tar.gz) = 151d1607e4b6b2085889b6004f5c82e055bb5dd9
```

```
2020/05/26 06:07:57 [decoder:3] Method "FLAC" accepted "file1.flac".
2020/05/26 06:08:31 [X_next_song:3] Prepared "file1.flac" (RID 1).
2020/05/26 06:08:31 [cross_7709:3] Analysis: -15.810517dB / -13.860294dB (2.96s / 2.96s)
2020/05/26 06:08:31 [crossfade:3] No transition: using default.
2020/05/26 06:08:31 [decoder:3] Method "MAD" accepted "file2.mp3".
2020/05/26 06:08:31 [lang:3] AzuraCast Feedback Response: OK
2020/05/26 06:08:34 [lang:3] AzuraCast Feedback Response: OK
2020/05/27 01:59:06 [main:3] Shutdown started!
2020/05/27 01:59:06 [main:3] Waiting for main threads to terminate...
2020/05/27 01:59:16 >>> LOG START
2020/05/27 01:59:16 [main:3] Liquidsoap 1.4.2
```

**Comment by dbrownidau** [comment]
@toots has kindly provided some insight to the core dumps, sadly the issue remains unclear.

In my setup, I have seen a dramatic decrease in crash frequency after switching the file system from NFS to an SSD block-device.

The issue *appears* to be common to FLAC files, but this remains anecdotal.

**Comment by toots** [comment]
Hi! Have you been able to test with the latest AzuraCast? We've pushed a couple of fixes there, including one that was causing a CPU spike..

**Comment by toots** [comment]
Reporter say issue hasn't been happening since updating `ocaml-flac`. Closing for now, let's re-open if it happens again.
