### ISSUE TITLE
Add configure option for where pervasive libraries are installed

### ISSUE THREAD

**Issue by paddatrapper** [savonet/liquidsoap#1211]
**Is your feature request related to a problem? Please describe.**
Debian maintains a single Liquidsoap install at a time, installed to `/usr/ocaml/liquidsoap`. Pervasive scripts are installed to `/usr/ocaml/liquidsoap/<version>/`. The package now includes a symlink for the pervasive scripts, but it would be nice not to have to update this on every release.

**Describe the solution you'd like**
A `configure` flag to specify the location for pervasive scripts.

**Describe alternatives you've considered**
It could also search a set of pre-defined directories

**Comment by toots** [comment]
Thanks for the report. This is a good idea! Just pushed a commit adding this to `master`!

**Comment by paddatrapper** [comment]
Thanks!
