### ISSUE TITLE
string.quote does not escape backticks 

### ISSUE THREAD

**Issue by naitsirch** [savonet/liquidsoap#1215]
**Describe the bug**
The `string.quote` (in earlier versions it is just `quote`) should escape shell metacharacters. But it does not escape backticks "\`" which are used in shells to execute subcommands.

**To Reproduce**
str = "foo\`echo 1 > /tmp/foo\`"
str = string.quote(str)
get_process_lines("php my-script.php #{str}")

**Expected behavior**
The php script should get the plain string "foo\`echo 1 > /tmp/foo\`" as argument. But instead it only gets "foo" and `echo 1 > /tmp/foo` is executed as command. This could be seen as a security vulnerability.
Especially in regard to the authorization function shown [here](https://www.liquidsoap.info/doc-1.4.2/harbor.html).

**Version details**
 - OS: Debian
 - Version e.g. `1.3.7` (but as far as I see, there were no changes in earlier versions)

**Install method**
distribution package

**Comment by toots** [comment]
Thanks for this report. Gonna look into it asap.

**Comment by naitsirch** [comment]
Some further investigation into this topic show that there is much more to consider. Here are a few resources that may help:

- https://unix.stackexchange.com/a/270979/208546
- https://gist.github.com/Zenexer/40d02da5e07f151adeaeeaa11af9ab36 (this is especially for PHP, but may be interesting for you, too)
- https://fireshellsecurity.team/restricted-linux-shell-escaping-techniques/

**Comment by toots** [comment]
Hi, I agree with you. The escape game is a loosing battle, it's much better to provide place holders for program arguments. I'll look into it ASAP. Or, else, feel free to send us a PR!

**Comment by dtcooper** [comment]
I observe the dollar sign is not escape as well,

`get_process_output('echo ' ^ string.quote('$HOME'))` should produce the string `$HOME`, however is produces the string `/home/user`

**Comment by dtcooper** [comment]
In case anyone else stumbles on this, as a stop-gap, I'm putting my variables in the `env` argument to `get_process_output`, ie `get_process_output(env=[('VAR', '$HOME')], 'echo "$VAR"')`.

**Comment by dtcooper** [comment]
Consequently, my approach above _does_ sidestep this bug,

For example, per above,

```
str = 'foo`echo 1 > /tmp/foo`'
get_process_lines(env=[('STR', str)], 'echo php my-script.php "$STR"')
```

Works as expected.

**Comment by toots** [comment]
Thanks for these details. This issue is on my radar.

**Comment by toots** [comment]
This will be fixed with the upcoming `1.4.4` bugfix release.

**Comment by dtcooper** [comment]
@toots if you haven't started this already, check out Python's implementation. I think _a lot_ could be made easier if we just use single quotes instead of doubel.

https://github.com/python/cpython/blob/3689c25a/Lib/shlex.py#L323-L334

It basically does the following.

1. If every character in the string is not in the (PCRE) regex class `\w@%+=:,./-`, then it can be used literally. (This step can be skipped
2. "[Wraps the string in] single quotes, and put[s] single quotes into double quotes." For example, "the string `$'b` is then quoted as `'$'"'"'b'`."

**Comment by dtcooper** [comment]
A reference Liquidsoap implementation might look something like the following,

```ruby
# Adapted from CPython's shlex module
def string.quote(s)
    if string.match(pattern='[^\\w@%+=:,./-]', s) then
        "'" ^ string.replace(pattern="'", fun(_) -> "'\"'\"'", s) ^ "'"
    else
        s
    end
end
```

**Comment by toots** [comment]
Fixed, thanks so much for all these details.

One important note re: the severity of this bug: shell calls are wrapped into the sandbox by default. While it is important that we also escape strings, the sandbox should also prevent unintended use of the shell execution API. Same goes for requests.

**Comment by dtcooper** [comment]
@toots wouldn't this escape all arguments in the string `cmd` together as one string enclosed in single quotes? I'll test this out in the next build, and admittedly I'm not great at reading OCaml, but I'm correct here I'm not sure this will work. Thanks!

**Comment by toots** [comment]
![giphy](https://user-images.githubusercontent.com/871060/101294985-5f89cb00-37e0-11eb-8b05-14aec892a158.gif)

**Comment by dtcooper** [comment]
Woops. Edited my comment. 😛
Not sure I'm 100% correct

**Comment by toots** [comment]
Nah, your comment if 100% correct, I definitely rushed this one. Hold on..

**Comment by toots** [comment]
Ok, after further analysis, here are a couple of things to consider:
* OCaml actually has its own API for escaping shell strings, namely `Filename.quote`. It does things a little different, for instance `$'b` is quoted as: `'$'\\''b'`
* I tried to write a proper parser to split shell arguments and it's, frankly, bug prone and also reinvents the wheel
* More generally, I should have first considered what is the security model here: attacker? attack vector? etc.

I would like to consider that, by default, a liquidsoap is written by a given user with full, unlimited control. Shell command, etc. In other words, the script writer shouldn't be considered as an attacker.

Adding the possibility for a third user to execute shell commands via a liquidsoap script is something the script writer decides and should be responsible for and, in this case, the third party could, indeed, be considered an attacker.

Further, we already have a catch-all mechanism in place via the sandbox. Likewise, if the script is run inside a docker container, the user will have limited access to the underlying system. The sandbox was initially added to protect request resolution which, contrary to the main liquidsoap script, can potentially lead to system calls not directly written by the script writer, for instance if someone hacks a callback script responsible for returning the next track to fetch.

However, we want to facilitate any kind of usage so, for instance, if the script writer wants to open up to a third party, there should be an easy way to prevent attacks. For this reason, I have just pushed a new operator, `process.quote`, which re-exports OCaml's `Filename.quote` as a liquidsoap operator. This way, you should be able to do:
```
# process.run is liquidsoap 2.x equivalent of run_process
process.run("echo #{process.quote(\"$HOME\")}")
```
which, I believe, should provide what the script writer could need to protect their shell calls.

**Comment by dtcooper** [comment]
Last nit: take it or leave it, should `string.quote()` be left in tact with the old functionality?
