### ISSUE TITLE
Add usage examples to the API reference

### ISSUE THREAD

**Issue by naitsirch** [savonet/liquidsoap#1221]
It would be extremely helpful for newcomers if the [API reference](https://www.liquidsoap.info/doc-1.4.2/reference.html) would contain examples how to use the functions.

For newcomers (like me) the descriptions of the functions are often hard to understand. I spent several hours to understand the parameter descriptions (e.g. `(pattern : string, ((string) -> string), string) ->
string`). In fact I still only understand the simple ones. I am coming from PHP background where such nomenclatures are not used. I can imagine that people without programming knowledge will have even harder times to understand that.

Examples would help a lot.

For example it took me a while to understand how to use _string.replace_. Although it is such a simple function. I had to google it and found somebody who has used this function in a code snippet in the mailinglist.

It would be great if the reference could look like this:
> string.replace
> 
> Replace substrings in a string. Will replace all substrings matched in the pattern by the string returned by the replace function.
> 
> Type:
> (pattern : string, ((string) -> string), string) -> string
>
> Arguments:
>     pattern (of type string)
>     (unlabeled) (of type (string) -> string)
>     (unlabeled) (of type string)
>
> **Examples:**
>      str = "Hello world" 
>      str = string.replace(pattern="world", (fun(_) -> "Frank"), str) 
>      print(str) # would print "Hello Frank"

What do you think?

**Comment by mcfiredrill** [comment]
I tried to make one before, but wasn't sure exactly what the best format for inline examples would be.
https://github.com/savonet/liquidsoap/pull/206

**Comment by naitsirch** [comment]
I'd prefer to add an extra parameter to `add_builtin`, where an array of examples can be passed.

I am sure, examples in the doc would be a huge advantage for newcomers. And will reduce questions in the mailing list or the bug tracker ;-)

**Comment by smimram** [comment]
I like this idea, reopening.

**Comment by mcfiredrill** [comment]
> I'd prefer to add an extra parameter to add_builtin, where an array of examples can be passed.

Is this feasible ?
What's the easiest way to get started?

**Comment by rrolla** [comment]
A bit related https://github.com/savonet/liquidsoap/discussions/2102

**Comment by smimram** [comment]
I have just added an `examples` parameter which takes a list of examples to `add_builtin` in #2227.
