### ISSUE TITLE
Crossfade: Howto??

### ISSUE THREAD

**Issue by saschaende** [savonet/liquidsoap#1224]
Help me, i find no solution for hours now :enttäuscht:
I am always getting "Error 4: Undefined variable fade.in" with this - just want to have a simple crossfade:

#!/usr/bin/liquidsoap
def crossfade(~start_next,~fade_in,~fade_out,s)
  s = fade.in(duration=fade_in,s)
  s = fade.out(duration=fade_out,s)
  fader = fun (a,b) -> add(normalize=false,[b,a])
  cross(duration=start_next,fader,s)
end
set("init.allow_root",true)
myplaylist = playlist("/etc/ices2/playlist.pls")
security = single("/etc/ices2/music/summer-ambient-piano--by-rafael-krux-from-filmmusic-io.ogg")
radio = myplaylist
radio = fallback(track_sensitive = false, [radio, security])
radio = crossfade(start_next=1.,fade_out=1.,fade_in=1.,radio)
output.icecast(%vorbis,host = "localhost", port = 8000, password = "xxx", mount = "/filmmusic",radio)

**Comment by mylselgan** [comment]
Hi,
I too have issue with crossfade after updating to latest version.
Previously i used `radio = crossfade(start_next=5.,fade_in=0.,fade_out=5.,s)`

Please give me a solution too. My requirement is very simple.

I need the currently playing song to fade for five seconds at the end and the next song should start when the previous song starts fade.

Ex. I have two 3:00 minuets songs
When the first song reach 2:55 it should start fade and the next song should continue without initial fade.

**Comment by saschaende** [comment]
@mylselgan Yes, i need the same simple thing.

**Comment by saschaende** [comment]
I got it to run. Follow my guide:
https://www.sascha-ende.de/development/general/886-icecast2-on-ubuntu-20-04-with-nginx-certbot-ssl-and-liquidsoap/

**Comment by toots** [comment]
Glad you got it to run. For the record, we diagnosed some issue with the location of the default `.liq` libraries.

**Comment by KevanGP** [comment]
I hate to re-open this issue but I can't get it to work either. I'm using basic non-smart-crossfade for now, but I want the fades based on volume not time. I know my script says smart=true, but putting in manual times seems to override that. Without the manual times entered, smart-crossfading works sometimes but not always.



faded = crossfade(radio,smart=true,fade_out=0.50,fade_in=0.01)
