### ISSUE TITLE
Error while compiling via opam

### ISSUE THREAD

**Issue by xorinzor** [savonet/liquidsoap#1225]
I'm trying to install liquidsoap via opam. This works fine on Debian 9, but gives problems on Debian 10. The only difference being the `opam` package being version 1.2 on debian 9, and version 2.0 on debian 10.

This is the error I get:
![error](https://user-images.githubusercontent.com/4212335/83902758-46369200-a75d-11ea-85a2-0c215ab62087.png)

And these are the packages I'm installing:
```
opam install -y alsa ao bjack camlimages cry dssi faad ffmpeg flac frei0r gavl gd graphics gstreamer ladspa lame lo mad magic ogg opus portaudio pulseaudio samplerate shine soundtouch ssl taglib theora vorbis xmlplaylist yojson liquidsoap
```

What's going wrong?

EDIT: also just noticed it's compiling liquidsoap 1.3.7, shouldn't opam be installing 1.4.2 (latest) ? I don't have a version number defined anywhere.

**Comment by toots** [comment]
Yeah it looks like you need to update `opam` to version `2` as explained in our install notes here: https://www.liquidsoap.info/doc-1.4.2/install.html#install-using-opam

I'll close this ticket, please re-open or submit a new one if needed. Thks and good luck!

**Comment by toots** [comment]
Sorry I forgot to add: if `opam` 2 is not an option, you might want to adjust the version of OCaml that you are using. It looks like this errors might come from a compiler that is either too old or to recent. I haven't compiled `1.3.7` in a while, wish I could be more specific :-)
