### ISSUE TITLE
Azuracast stop working since the last liquidsoap 1.4.2 update

### ISSUE THREAD

**Issue by arusi01** [savonet/liquidsoap#1226]
Azuracast stop working since the last update
AzuraCast • v0.10.2, #f44261b (2020-05-30 1:36) • Docker • PHP 7.4

when I hit the next song button I get this error

Telnet failure: Connection refused (111)

and Shoutcast Streams Status has Available Streams: 0

Liquidsoap Log -> Fatal error: out of memory

You can try to recreate the error by adding 14 lists with the "Interrupt other songs to play at scheduled time" and "Only play one track at scheduled time." both checked and scheduled three times per day each.

**Comment by arusi01** [comment]
[AzuraCast.Liquidsoap.configuration.txt](https://github.com/savonet/liquidsoap/files/4739044/AzuraCast.Liquidsoap.configuration.txt)

**Comment by arusi01** [comment]
[liquidsoaplog.txt](https://github.com/savonet/liquidsoap/files/4739045/liquidsoaplog.txt)

**Comment by arusi01** [comment]
![001](https://user-images.githubusercontent.com/51458416/83931073-1e512980-a771-11ea-96f0-9aa7ba695300.jpg)

![002](https://user-images.githubusercontent.com/51458416/83931078-23ae7400-a771-11ea-9204-331c8b69a649.jpg)

![003](https://user-images.githubusercontent.com/51458416/83931081-27da9180-a771-11ea-8fa7-2421070cb6b7.jpg)

![004](https://user-images.githubusercontent.com/51458416/83931088-2d37dc00-a771-11ea-9661-4e625d13ab3a.jpg)

**Comment by arusi01** [comment]
https://github.com/AzuraCast/AzuraCast/issues/2811

**Comment by stimpy23** [comment]
Not sure, but I think, I have the same problem:
https://github.com/savonet/liquidsoap/issues/1256

**Comment by toots** [comment]
Thanks for this report. It does indeed look like #1256 out the outskirt. What version did you upgrade from?

**Comment by toots** [comment]
We believe this was closed with #1272. Please reopen if needed.

**Comment by arusi01** [comment]
Thanks!
