### ISSUE TITLE
Failed to stream ogg

### ISSUE THREAD

**Issue by elopio** [savonet/liquidsoap#1228]
I'm trying to forward an ogg stream, but it seems to fail to identify it properly. 

The source is currently streaming in https://a.stream.mayfirst.org/coaatv.ogg, but probably it won't be live when you read this.

This is my script:
```
radio = input.https(
  "https://a.stream.mayfirst.org/coaatv.ogg",
  buffer=10.0, max=20.0)

output.icecast(%vorbis,
  host = "[redacted]", port = [redacted],
  password = "[redacted]", mount = "[redacted]",
  user = "[redacted]",
  radio, fallible=true)
```

Then the log prints:
`2020/06/06 15:50:26 [decoder:3] Unable to decode stream of type "video/webm"!`

It's weird that it says "video/webm", isn't it?

So I've added `force_mime="video/ogg"` to the input.

Then the log prints:
```
Ogg.Out_of_sync
2020/06/06 15:54:26 [decoder:3] Method "OGG" accepted "video/ogg".
2020/06/06 15:54:26 [https_9156:3] Decoding...
2020/06/06 15:54:26 [https_9156:2] Feeding stopped: Ogg.Out_of_sync
```

**To Reproduce**
Run an ogg stream. I'm not sure if this applies to all ogg streams, I've only tried this one.

**Expected behavior**
The ogg stream is forwarded to my radio.

**Version details**
 - OS: Ubuntu Focal.
 - Version 1.4.2 

**Install method**
I've downloaded the latest deb from https://packages.debian.org/sid/liquidsoap

**Comment by toots** [comment]
It's interesting. We'd have to inspect the HTTP response from that source when it is live again. Specifically its `Content-Type` header.

**Comment by mustafejen** [comment]
I guess the video stream is webm (viceo codec vp9 or vp9, audio codec vorbis or opus).
In case I remember things right, video/ogg is video codec theora with audio codec vorbis.
My guess is that somebody has encapsulated the webm stream in the wrong container.

It should be possible to decode the webm stream with input.gstreamer.audio_video or input.ffmpeg.

In case you only want the sound forwarded to your icecast server maybe you need to use drop_video after input-gstreamer.audio_video (or input.ffmpeg).

**Comment by toots** [comment]
`video/ogg` could be anything the ogg container supports that includes video which, in practice, is only theora I believe.

`webm` is another encapsulating format, which is different than `ogg` and contains different codecs than `ogg`. Its file or url extension is usually `.webm` and its mime-type, passed via the `Content-Type` HTTP header, is usually `video/webm` or `audio/webm`.

While it should be technically possible to have a url ending with `.ogg` using a webm `Content-Type` and returning a webm-encapsulated stream, I would consider that bogus and would expect many decoders to potentially have issues with it

Regarding `liquidsoap`, in `1.4.2`, the gstreamer decoder should be able to encode it if you have the right plugins installed by setting the following:
```
set("decoder.mime_types.gstreamer",["video/webm", "audio/webm"])
```
Please note, however that this hasn't been throughly tested. The usual way to use the decoder in situations like this is via file download using `playlist` or `single`. However, to come back full circle, I would expect this to have issue b/c of the `.ogg` file extension. If you wanted to, though, you could add the `.ogg` file extension to the gstreamer file decoder this way:
```
set("decoder.file_extensions.gstreamer",["ogg", "wma","wmv","avi","mp4","3gp","webm","mkv"])
```

Hope this helps!

**Comment by toots** [comment]
Any update on this one?

**Comment by elopio** [comment]
Well, the stream is no longer running. It's likely that it will open again some time soon, so I'll be keeping an eye on it and give it a try. I haven't been able to reproduce it with any other streams, so I'm not sure what else to do to help.
