### ISSUE TITLE
Metadata update may have failed, station stops and restart

### ISSUE THREAD

**Issue by hecgua** [savonet/liquidsoap#1238]
I have been having this issue for months. I reported this issue in the Azuracast Github but no one could help me. They told me to come here and report this issue. 

Could you please help me? Thanks in advance.

**Describe the bug**
Stream crashes and restart at least once a day.

**To Reproduce**
Station is playing music as usually and suddenly crashes

**Expected behavior**
Not to stop and restart

**Version details**
Ubuntu 16.04 
Azuracast  0.10.2
Liquidsoap 1.4.2

**Install method**
Azuracast Docker

**Liquidsoap Error Log**
...
2020/06/08 23:14:22 [lang:3] AzuraCast Feedback Response: OK
2020/06/08 23:14:22 [radio_name_2:3] Metadata update may have failed with error: 400, Bad Request (HTTP/1.0)
2020/06/08 23:14:22 [radio_name_1:3] Metadata update may have failed with error: 400, Bad Request (HTTP/1.0)
2020/06/08 23:14:22 [clock.wallclock_main:2] We must catchup 58.64 seconds!
2020/06/08 23:14:22 [radio_name_1:2] Error while sending data: could not write data to host: Broken pipe in write()!
2020/06/08 23:14:22 [radio_name_1:3] Closing connection...
2020/06/08 23:14:22 [radio_name_1:3] Will try to reconnect in 3.00 seconds.
2020/06/08 23:14:22 [radio_name_2:2] Error while sending data: could not write data to host: Broken pipe in write()!
2020/06/08 23:14:22 [radio_name_2:3] Closing connection...
2020/06/08 23:14:22 [radio_name_2:3] Will try to reconnect in 3.00 seconds.
2020/06/08 23:14:23 [clock.wallclock_main:2] We must catchup 8.28 seconds (we've been late for 100 rounds)!
2020/06/08 23:14:26 [radio_name_1:3] Connecting mount /listen for source@127.0.0.1...
2020/06/08 23:14:26 [radio_name_1:3] Connection setup was successful.
2020/06/08 23:14:26 [radio_name_2:3] Connecting mount /mobile for source@127.0.0.1...
2020/06/08 23:14:26 [radio_name_2:3] Connection setup was successful.
...
2020/06/08 23:16:53 [lang:3] AzuraCast Feedback Response: OK

**Comment by toots** [comment]
Hi, it looks like a blocking HTTP call. Without more details on your script, the general advice is that that call should be done via an asynchronous call so as to not block the main streaming thread. The operator for that is `add_timeout`: https://www.liquidsoap.info/doc-1.4.2/reference.html#add_timeout

I'm gonna close this now as I believe this is an issue with the AzuraCast script. I hope that you can get support from there.
