### ISSUE TITLE
liquidsoap 1.5.x hangs with crossfade

### ISSUE THREAD

**Issue by xogium** [savonet/liquidsoap#1247]
**Describe the bug**
As soon as you use crossfading, (I haven't been able to determine if smart=true is required) in any script, liquidsoap will hang, even with a simple --check. Nothing is printed to the terminal.
**To Reproduce**
This script is enough, no matter if you run liquidsoap or liquidsoap --check:

```
source = mksafe(crossfade(smart=true,sine()))
output.file(%mp3(bitrate=320),"test.mp3",source)
```

**Expected behavior**
Liquidsoap should start streaming or at least print text to the terminal.

**Version details**
 - OS: ArchLinux
 - Version 1.5.0+git@493557d1

**Install method**
Installed via opam.

**Comment by xogium** [comment]
I did some stracing, and it seems that liquidsoap is acting up, and trying these, over and over:


```
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_BLOCK, [VTALRM], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
```

I have no idea what it is trying to do, but it appears to fail or at least be stuck. Adding -ff to the strace gives these 3 logs:

[main thread](http://ix.io/2pfU),
[second thread](http://ix.io/2pfX) and
[third thread](http://ix.io/2pfZ). Hope this helps.

**Comment by smimram** [comment]
Interesting one. The `cross` function uses `Lang.iter_sources` (the one causing problems so far is [the one in `set_clock`](https://github.com/savonet/liquidsoap/blob/master/src/operators/cross.ml#L146)), which apparently has to go through all Liquidsoap values and takes quite some time. It looks like it is just slow, not non-terminating: if I remove some functions from pervasives, I can get it to run after some time.
