### ISSUE TITLE
How use input.udp ?

### ISSUE THREAD

**Issue by bnp322** [savonet/liquidsoap#1258]
Hi,
If possible, how use input.udp for my udp stream...  (more details :) )

Now I'm get and send stream through ffmpeg:

ffmpeg -i "udp://@224.1.1.5:1234?fifo_size=1000000&overrun_nonfatal=1" \
..............................
-c:a libvorbis -ar 48k -b:a 384k \
-map i:0x303 \
-f ogg -content_type application/ogg \
icecast://source:xxx@127.0.0.1:8888/input1 \
-c:a libvorbis -ar 48k -b:a 384k \
-map i:0x301 \
-f ogg -content_type application/ogg \
icecast://source:xxx@127.0.0.1:8888/input2

And then:
input1 = nrj(audio_to_stereo((input.harbor(id="1111",port=8888,password="xxx","input1"))))

**Comment by toots** [comment]
Hi!

The udp inputs and outputs are pretty crude. It's mostly an operator for liquidsoap communication only, I'm not sure that it'll work outside of that..

Closing this question now, feel free to follow-up on the slack channel!
