### ISSUE TITLE
Add support for video canvas content type

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#1261]
- Content is layers of images with offset position
- Used for all operators that add elements to the video stream
- One operator converts a `source(audio=none,video=yuv420p,midi=none)` to a layered source where the first layer is the origin source
- One operator converts a layered source back to a source of type `source(audio=none,video=yuv420p,midi=none)`
- Eventually, convert all video manipulation operators to this data type

**Comment by smimram** [comment]
Should be fixed by #2207.
