### ISSUE TITLE
input.external.rawaudio channels=1 errors with "Incompatible number of channels" 

### ISSUE THREAD

**Issue by wyozi** [savonet/liquidsoap#1277]
**Describe the bug**

I'm trying to get mono PCM data from a command `speech = input.external.rawaudio(channels=1, "tail -F /music/test")`, but I'm getting `Incompatible number of channels, please use a conversion operator.`

Even if I try to convert the result into stereo, it will still give the same error (`audio_to_stereo(mksafe(speech))`).

Is there something I'm missing here?

**Version details**
version: 1.5.0
buildnumber: 659

installed from the debian repo

**Comment by toots** [comment]
Hi! We've rewritten this whole layer recently, would you mind trying with a more recent buid? The debian packages in the repository are outdated but you can grab one by going to the actions section. For instance here: https://github.com/savonet/liquidsoap/actions/runs/156872465. Please note that the `master` branch is under heavy rework right now. However, if you feel adventurous, we are super happy to help people and get early feedback.

I'll close this for now, feel free to reopen later or else come chat in our slack channel!
