### ISSUE TITLE
"rotate" operator doesn't respect "weights" at first round

### ISSUE THREAD

**Issue by matteo-daddi** [savonet/liquidsoap#1279]
**Describe the bug**
I'm using liquidsoap 1.4.2, it seems that the "rotate" operator, at first round, uses always a weight equal to 1 at least for the first source. In subsequent rounds the correct weights are used.

**To Reproduce**
```
#In a real use case "songs" and "ads" are playlists, I've used "sine" in order to let others easily test the script.
#To detect a "track switch" pay attention to duration of the two harmonic tones or at log's timestamps

songs = sine(duration=5.)
ads = sine(duration=5.,880.)
test = rotate(track_sensitive=true,weights=[2,1],[songs,ads])

output.alsa(test,fallible=true)
```
```
2020/07/01 17:29:39 >>> LOG START
2020/07/01 17:29:39 [main:3] Liquidsoap 1.4.2
2020/07/01 17:29:39 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.3 sedlex=2.2 menhirLib=20200619 dtools=0.4.2 duppy=0.8.0 cry=0.6.5 mm=0.5.0 ogg=0.5.2 vorbis=0.7.1 mad=0.4.5 dynlink=[distributed with Ocaml] lame=0.3.3 alsa=0.2.3 samplerate=0.1.4 taglib=0.3.6 camomile=1.0.2
2020/07/01 17:29:39 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2020/07/01 17:29:39 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2020/07/01 17:29:39 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2020/07/01 17:29:39 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2020/07/01 17:29:39 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2020/07/01 17:29:40 [sandbox:3] Sandboxing disabled
2020/07/01 17:29:40 [video.converter:3] Couldn't find preferred video converter: gavl.
2020/07/01 17:29:40 [audio.converter:3] Using samplerate converter: libsamplerate.
2020/07/01 17:29:40 [clock.wallclock_alsa:3] Streaming loop starts, synchronized by active sources.
2020/07/01 17:29:40 [rotate_7393:3] Switch to sine_7387.
2020/07/01 17:29:40 [alsa_out(default):3] Using ALSA 1.1.8.
2020/07/01 17:29:40 [alsa_out(default):3] Samplefreq=44100Hz, Bufsize=32768B, Frame=4B, Periods=74
2020/07/01 17:29:44 [rotate_7393:3] Switch to sine_7391 with forgetful transition.
2020/07/01 17:29:49 [rotate_7393:3] Switch to sine_7387 with forgetful transition.
2020/07/01 17:29:59 [rotate_7393:3] Switch to sine_7391 with forgetful transition.
2020/07/01 17:30:04 [rotate_7393:3] Switch to sine_7387 with forgetful transition.
2020/07/01 17:30:14 [rotate_7393:3] Switch to sine_7391 with forgetful transition.
2020/07/01 17:30:16 [main:3] Shutdown started!
2020/07/01 17:30:16 [main:3] Waiting for main threads to terminate...
2020/07/01 17:30:16 [clock.wallclock_alsa:3] Streaming loop stopped.
2020/07/01 17:30:16 [main:3] Threads terminated.
2020/07/01 17:30:16 [threads:3] Shutting down scheduler...
2020/07/01 17:30:16 [threads:3] Scheduler shut down.
2020/07/01 17:30:16 [threads:3] Waiting for queue threads to terminate...
2020/07/01 17:30:16 [threads:3] Queues shut down
2020/07/01 17:30:16 [main:3] Cleaning downloaded files...
2020/07/01 17:30:16 [main:3] Freeing memory...
2020/07/01 17:30:16 >>> LOG END
```
**Expected behavior**
weights are always respected (at every round, including the first, you should hear 10 seconds of a 440 HZ tone and 5 second of a 880 Hz tone).

**Version details**
 - OS: raspbian
 - Version liquidsoap 1.4.2

**Install method**
opam

**Comment by toots** [comment]
Thank you so much for this great bug report. I was able to fix the issue right away. The fix has been pushed to the `v1.4.3-pre-release` branch and will come out with the next bugfix release. Meanwhile, you can grab the code from that branch, `opam pin` it or grab one of the build that should be updated shortly at: https://github.com/savonet/liquidsoap/releases/tag/v1.4.3-pre-release

**Comment by smimram** [comment]
It seems that your example is working correctly in the current git version (where `rotate` was heavily rewritten).

**Comment by matteo-daddi** [comment]
Yes, it seems so. Thank you and thanks to all the developers 😉 , great community!

I haven't added any feedback to the github issue because it has been closed and I didn't know if replying with something causes a unwanted reopen of the issue.


________________________________
Da: Samuel Mimram <notifications@github.com>
Inviato: mercoledì 8 luglio 2020 11:33
A: savonet/liquidsoap <liquidsoap@noreply.github.com>
Cc: matteo-daddi <mad88@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [savonet/liquidsoap] "rotate" operator doesn't respect "weights" at first round (#1279)


It seems that your example is working correctly in the current git version (where rotate was heavily rewritten).
