### ISSUE TITLE
Invalid URL and invalid M3U file in Windows examples?

### ISSUE THREAD

**Issue by alexhorner** [savonet/liquidsoap#1289]
### Invalid HTTP stream url
_http://flows.liquidsoap.fm/radio/01dbfc6d2f3e50d6ba243e68c1ca469b44babd1f/mp3/128k_

found in

 _https://github.com/savonet/liquidsoap/blob/cda1bdb967d501915987fff84c80eeea83b27746/.github/win32/test.liq_

This link provided as the HTTP input source in the Windows examples. This link does not go anwhere anymore and therefore does not work with LS

### Invalid M3U file
_https://github.com/savonet/liquidsoap/blob/cda1bdb967d501915987fff84c80eeea83b27746/.github/win32/test.m3u_

In addition, an m3u file is also provided, which is identical to the .liq file and this is clearly not correct as this is not the format for a .m3u file

**Comment by toots** [comment]
Thanks for posting that. This URL is not functional anymore, unfortunately. I'll fix our test scripts.
