### ISSUE TITLE
New feature: weak active sources

### ISSUE THREAD

**Issue by dbaelde** [savonet/liquidsoap#130]
On the mailing list, okay_awright reported a problem were he tried to shut down some sources but (surprisingly to him) the sources stayed alive because of an active strip_blank using them. This is indeed surprising and unwanted. Some sort of weak active source, that shuts itself down when no "strong" active source remains, could be useful here.

For reference: http://www.mail-archive.com/savonet-users@lists.sourceforge.net/msg08895.html

**Comment by smimram** [comment]
I don't think that this has come up again, and the notion of active source was removed. Let's close this for now unless someone needs this again.
