### ISSUE TITLE
Problems with https.get

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1300]
I tried the following
```
s = https.get("https://raw.githubusercontent.com/savonet/liquidsoap/master/CHANGES.md")
print("Here are the latest changes in Liquidsoap:\n" ^ s)
```
but I only see the first two lines of the file (presumably because the third one is blank).

Also, I tried an url shortener
```
s = https.get("https://git.io/JJ0Kk")
print("Here are the latest changes in Liquidsoap:\n" ^ s)
```
and this results in
```
Error while processing request: SSL connection() error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```
Thanks @toots :)

**Comment by toots** [comment]
Woof the `http` request body reader was a crazy mess! Fixed it and added optional `http_version` with default `1.0` version. Quick tests with `1.1` have shown that the code isn't ready for it yet.

Please, let's try to submit one ticket per issue when possible.. Re-opening another one for the second issue now. Also adding some improvement tickets for `http` internal client..
