### ISSUE TITLE
Naming of raw channels

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1301]
Currently, the type for raw audio is indicated by `pcm`. I think that it would be more clear if the raw channels were all indicated by the same thing for audio / video / midi. I would name this `raw` or maybe `internal`. This would avoid requiring the user to know what pcm means or to have to gess that the type for raw video is `yuv420`. I don't think that we are going to support multiple internal data representations, will we?

**Comment by toots** [comment]
I'm not sure what I think about this. What about supporting `rgba` format? Or video canvas to replace our expensive video add operators? Wouldn't each format be another flavor of our "internal" format?

One solution could be to make them parameters of an internal liquidsoap data type, something like `liquidsoap.internal(pcm)`, etc. but what would be the benefit?

It seems to me that naming should be about giving user information about what is going on and being specific. With generic content type, users are gonna have to consider what kind of content is flowing through their stream so naming them as they are seems like it would make understanding what's going on under the hood easier?

**Comment by smimram** [comment]
I think that `raw` or `internal` should refer to the default internal implementation, but this does not prevent other implementations from existing.
