### ISSUE TITLE
Issues with string representation of values with methods

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#1303]
String representation are used for both value printing and string interpolation. With value methods, however, they need to be treated differently. Here's an example:

```
# x = "foo";;
x : string = "foo"
# def x.bla() = "gni" end;;
x.bla : () -> string = {"gni"}
# x;;
- : string.{bla : (() -> string)} = "foo".{bla = {"gni"}}
# y = "a#{x}b";;
y : string = "a\"foo\".{bla = {\"gni\"}}b"
# y = "a" ^ x ^ "b";;
y : string = "afoob"
```

**Comment by smimram** [comment]
The following should work:
```
y = "a#{string(x)}b"
```
A possible way to fix this would be to systematically remove methods when interpolating. What do you think?

**Comment by toots** [comment]
Looks great and methods still show up in `interactive` mode. Thks!
