### ISSUE TITLE
replay_gain stops normalising tracks during transitions

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1318]
I have attached a minimal script so that you can reproduce this issue.

I'm running version 1.4.2 installed via opam on Debian 10. I use replay_gain (and have installed the ffmpeg binary) to normalise tracks. 

I use a custom transition, with a 10 second fade out, in a switch. 

If you run the minimal script that I have provided, you should notice that when source2 (in the schedule) transitions back to source1 (which is the default playlist), the volume suddenly shoots up just before the transition ends. It's as though replay_gain is not able to normalise the track all the way to the end of the transition. It does not seem to happen when transitioning from source 1 (default playlist) to source 2.

[test.liq.txt](https://github.com/savonet/liquidsoap/files/5044759/test.liq.txt)

**Comment by oranjebloom** [comment]
Hey, were you guys able to reproduce this with the attached script?

**Comment by toots** [comment]
Hi @oranjebloom, sorry it took me so long to get back to you.

I would recommend to put the amplify as early as possible. `replay_gain` adjustments are done per-track and the transitions can create artificial track boundaries which will indeed mess with these.

I would suggest to add one `amplify` directly on each of `source1` and `source2` right after their creation:
```
source1 = pl("path/to/source1")
source1 = amplify(1.,override="replay_gain", source1)

source2 = pl("path/to/source2)
source2 = amplify(1.,override="replay_gain", source2)
```

**Comment by oranjebloom** [comment]
Hi @toots thanks for the reply. Ahh, that makes sense. Are those `amplify` additions to each source in addition to the one at the bottom of the script `radio = amplify(1.,override="replay_gain",radio)` or should I remove that one?

**Comment by oranjebloom** [comment]
Ah, nevermind the last question. I applied `amplify` to all sources and tested it without  `radio = amplify(1.,override="replay_gain",radio)` at the bottom of the script and it solved the problem. I think we can probably close this issue, but just give me another day or two ... I'll write back again to confirm the result.

**Comment by toots** [comment]
Great, happy to hear!

**Comment by oranjebloom** [comment]
Nearly there. No problems with adding` amplify` to sources that use the `playlist` operator, but I'm needing a little bit of advice for using `amplify` with `playlist.reloadable`.

when I added `amplify`, like below, to the source called vptxt (below) the script broke.

```
vptxt         = playlist.reloadable("/ssr/ssr1/voxpop1/voxpop1.txt")
vptxt         = amplify(1.,override="replay_gain",vptxt)
vpt           = snd(vptxt)
vptreload     = fst(vptxt)
```

So, instead of this, I did the following...

```
vptxt         = playlist.reloadable("/ssr/ssr1/voxpop1/voxpop1.txt")
vpt           = snd(vptxt)
vptreload     = fst(vptxt)
vpt         = amplify(1.,override="replay_gain",vpt)
```

The script now runs, but weather the source named vpt is being normalised, I'm not sure. Will have to test further. Does this usage look okay to you?

**Comment by oranjebloom** [comment]
Okay, I can confirm that it works. I think we can close this. Thanks again @toots

**Comment by toots** [comment]
Great!
