### ISSUE TITLE
Cannot attach methods to variables inside function

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#1321]
The following code:
```
def new_reporter(name)
  r = name
  def r.report(m)
    print(json_of([("source", r),("metadata",m)]))
  end
  r
end
```
Is typed as:
```
Line 3, char 2:
Warning 4: Unused variable r.report
new_reporter : ('a) -> 'a = <fun>
```
Shouldn't the `report` method be added to the type?

**Comment by smimram** [comment]
I don't understand, when I try your example I get
```
new_reporter : ('a) -> 'a.{report : (('a) -> unit)}
```
as expected... Can you provide more information on how to reproduce?

**Comment by toots** [comment]
That's right. I must have been testing with the wrong version.
