### ISSUE TITLE
Amplify seems not to honour "override" parameter

### ISSUE THREAD

**Issue by matteo-daddi** [savonet/liquidsoap#1323]
**Describe the bug**
It seems that "amplify" respect the "override" parameters only if its value is set to "liq_amplify" wich is the default value (making that parameter useless!).

**To Reproduce**

```
#I've used "sine" in order to let others easily test the script.
#I've created a sequence of 4 sine waves like this:
#1) "HEAD" (song) - 440 Hz, amplitude = 1, no METADATA, duration = 5 [s]
#2) "KO" (songLow_customAmplifyMData) - 440 Hz, amplitude = 0.1, METADATA=("customTAG", "10.0"), duration = 5 [s]
#3) "OK" (songLow_stdAmplifyMData) - 440 Hz, amplitude = 0.1, METADATA=("liq_amplify", "10.0"), duration = 5 [s]
#4) "TAIL" (tail) - 880 Hz, amplitude = 1, no METADATA, duration = inf [s]

song = sine(duration=5.)
songLow_customAmplifyMData = sine(duration=5.,amplitude=0.1)
songLow_stdAmplifyMData = sine(duration=5.,amplitude=0.1)
tail = sine(duration=0.,880.)


def addCustomAplifyOverrideMData(m)

  print("Adding custom MDATA\n")

  [("customTAG", "10.0")]

end

def addStdAplifyOverrideMData(m)

  print("Adding std MDATA\n")

  [("liq_amplify", "10.0")]

end


songLow_customAmplifyMData = map_metadata(addCustomAplifyOverrideMData, songLow_customAmplifyMData)
songLow_stdAmplifyMData = map_metadata(addStdAplifyOverrideMData, songLow_stdAmplifyMData)

songLow_customAmplifyMData = amplify(override="customTAG",1.,songLow_customAmplifyMData)
songLow_stdAmplifyMData = amplify(override="liq_amplify",1.,songLow_stdAmplifyMData)

test = sequence([song,songLow_customAmplifyMData,songLow_stdAmplifyMData,tail])

output.alsa(test,fallible=true)
```

**Expected behavior**
You should hear 15 seconds of a 440 Hz tone at constant volume level and then a 880 Hz tone should start endlessly.
BUT, due to the supposed BUG, You'll probably hear 5 seconds of a 440 Hz tone, then 5 seconds of almost silence (w.r.t. previous sound), then 5 seconds of a 440 Hz tone (same volume level as the first one) and then a 880 Hz tone should start endlessly.

**Version details**
 - OS: Ubuntu server 18.04
 - Liquidsoap 1.4.3+git@9086335c

**Install method**
OPAM

**Comment by toots** [comment]
Thanks for the report! It was fixed for `1.4.4` in cb39637 and was already fixed in the current `master`. We hope to release `1.4.4` by the end of the year.
