### ISSUE TITLE
Nested Clocks - Following #1149

### ISSUE THREAD

**Issue by pavlos2** [savonet/liquidsoap#1326]
Hi,
This is a continuation of #1149, the following code will give the fatal error 'a source cannot belong to two clocks'

```
Joyful = rotate(weights=[1,1,1, ....], [playlist_01_inj, playlist_03_of, playlist_06_sm, ...])
Joyful2 = rotate(weights=[1,1,1, ...], [playlist_01_inj2, playlist_03_of2, playlist_06_sm2, ...])
Joyful3 = rotate(weights=[1,1,1, ...], [playlist_01_inj3, playlist_03_of3, playlist_06_sm3, ...])

tracks_played = ref 0

def count_tracks(_, _, _, _, old, new) =
  tracks_played := !tracks_played + 1
  sequence([old, new])
end

Joyful = cross(count_tracks, Joyful)
Joyful2 = cross(count_tracks, Joyful2)
Joyful3 = cross(count_tracks, Joyful3)

def reset_tracks_played() =
  if 50m-59m then
    tracks_played := 0
  end
  # Repeat every 5 min
  5. * 60.
end

add_timeout(0., reset_tracks_played)

radio = switch(track_sensitive=true, [
({ 1w and 0m - 5m and !tracks_played < 3 }, Joyful ),
({ 2w and 0m - 5m and !tracks_played < 3 }, Joyful2 ),
({ 3w and 0m - 5m and !tracks_played < 3 }, Joyful3 ),
({true}, radio)])
```

Romain suggests:  

> Hi! The problem that you are having is that crossfade needs full control over its child sources because it accelerates them to compute transitions. However, these same sources are also present at top-level via radio. You should re-organize your script so that you do not use the same sources in the crossfade and in radio.

By now I did not manage to address the issue, the provided online text on Nested Clocks does not help much on this particular matter. Can someone help?

**Comment by pavlos2** [comment]
Hi Romain,

This issue remains unresolved, I am still expecting your support, can you please help?

Regards,
Pavlos

**Comment by toots** [comment]
The `Joyful` sources cannot be both inside a `crossfade` (where they can potentially be accelerated to calculate a crossfade transition) and outside in the `switch`. You should create separate sources for each use case. Hope this helps!
