### ISSUE TITLE
Best way to enable replay_gain globally?

### ISSUE THREAD

**Issue by codeofdusk** [savonet/liquidsoap#1336]
The Liquidsoap docs [provide several seemingly contradictory ways](https://www.liquidsoap.info/doc-dev/replay_gain.html) to enable replay_gain support. What steps should I take to always adjust track levels based on replay_gain metadata? Should I be using `ffmpeg` to do this? `replay_gain:` protocol? `enable_replaygain_metadata()` function (or does that just make the protocol work?)

**Comment by codeofdusk** [comment]
Any updates on this?

Cc @toots @smimram.

**Comment by toots** [comment]
Hi! I just pushed some edits on the replay gain doc, let me know if that clarifies it. It should be live here in a short while: https://www.liquidsoap.info/doc-dev/replay_gain.html

**Comment by toots** [comment]
This will be part of the `1.4.4` release. Thanks for reporting!
