### ISSUE TITLE
How to run a script on a track change.

### ISSUE THREAD

**Issue by MattMski** [savonet/liquidsoap#1339]
Hello, I've created a PHP script that creates a JSON file that my radio website relies off of for song information and other things.

I tried to implement it on `on_track` but it is always behind one song.

How would I implement something like this correctly

Got something like this and it is still lagging behind

```
jsonurl = "php -q /directory/shoutcast_json.php"
# This function updates the JSON file
def updatejson()
    # PHP JSON Update
	#ignore(get_process_output(jsonurl))
	ignore(get_process_lines(jsonurl))
end
#radio = on_track(updatejson,radio)
def nowplaying(m)
	updatejson()
end
radio = on_track(nowplaying,radio)
```

**Comment by rrolla** [comment]
I have something like this:
```

def apply_metadata(m)
  tunePath = m['filename']
  songId = m['songId']

  curlcmdUtils = "curl --insecure -sS 'http://localhost:8080/api/nowplaying?&songId=#{songId}&path='"
  cmdUtils = "#{curlcmdUtils}#{url.encode(tunePath)}"
  system(cmdUtils)
end

s = on_metadata(apply_metadata, s)
```

**Comment by MattMski** [comment]
I tried that but same problem. Pretty much there is a problem that it is getting the previous song instead of the current song. Not sure if the PHP script is being executed wrong or my PHP script is coded wrong.

**Comment by MattMski** [comment]
Fixed it by using exporting Liquidsoap meta to json instead of relying off of reading shoutcast xml json
