### ISSUE TITLE
Add support for using Raspberry Pi as an FM transmitter (was LS-649)

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#134]
Reviving old bug report, so that I don't forget about it when I have really nothing to do someday.

Some code has been released to turn a raspberry pi into a low-power FM transmitter:
- https://github.com/Emerica/pifm
- http://www.icrobotics.co.uk/wiki/index.php/Turning_the_Raspberry_Pi_Into_an_FM_Transmitter

which needs very very few hardware modifications (actually only adding a piece of wire!...). It would be really cool if we could support this in Liquidsoap!
Moreover, since the technique seems to be very general, we could think of adapting it to other hardware (I'd love to insert a wire in the right VGA port of my laptop and have an FM transmitter...)

Actually, this is the magic of internet, the code for the VGA FM transmitter can be [found here](http://bk.gnarf.org/creativity/vgasig/).

**Comment by davidtrattnig** [comment]
Pretty sweet :-) Would love to try this myself at some point.

**Comment by smimram** [comment]
It should be relatively easy to achieve nowadays, without any further code from our part.

The lastest code for transmitting FM seems to be https://github.com/markondej/fm_transmitter, so that I am basing myself on this. You should be able to hear some sound with something like this:
```
s = sine() # replace with your favorite playlist
fmenc = %external(channels=2, samplerate=44100, header=true, restart_on_crash=true, proces="./fm_transmitter -f 100.6 -")
output.file(fmenc, s)
```
It would be nice if you could report any success/problem with this approach!

**Comment by rmens** [comment]
The example provided by @smimram doesn't seem to work. Literately copied it into a `.liq` file:

```root@pi:~# /root/.opam/default/bin/liquidsoap /root/test.liq
At /root/test.liq, line 3, char 19:
output.file(fmenc, s)

Error 5: this value has type
  source(_) (inferred at /root/test.liq, line 1, char 4-10)
but it should be a subtype of
  {string}
```
This is with version:
```
root@pi:~# /root/.opam/default/bin/liquidsoap --version
Liquidsoap 2.1.1
Copyright (c) 2003-2022 Savonet team
```

Can any one reproduce this?

**Comment by smimram** [comment]
I wrote this quickly, thinking that noone would ever read ;) Here is a better try:
```
s = sine() # replace with your favorite playlist
output.external(%wav(channels=2, samplerate=44100), "./fm_transmitter -f 100.6 -", s)
```
I still did not fully test (don't have a raspberry at hand), but at least the script runs. Please keep us posted of your experiments!
