### ISSUE TITLE
Icecast metadata that contains '=' is truncated by input.harbor

### ISSUE THREAD

**Issue by knyar** [savonet/liquidsoap#1340]
**Describe the bug**

If Icecast metadata transmitted by the broadcasting source to the `input.harbor` endpoint of Liqudsoap contains an equal sign (`=`), any content before the `=` gets truncated.

**To Reproduce**

1. Configure a `input.harbor` endpoint, e.g. `input.harbor('test_input", port=8888, password='test', id='test', metadata_charset="CP1251", replay_metadata=true)`
2. Run a simple script that sends an HTTP request with a song name that contains `=`:
```python
#!/usr/bin/env python3
import urllib.parse, urllib.request
url = 'http://localhost:8888/admin/metadata?'
getvars = dict(mode='updinfo', mount='/test', song='Test 1 = Test2')
req = urllib.request.Request(url + urllib.parse.urlencode(getvars), headers={'Authorization': 'Basic c291cmNlOnRlc3Q='})
with urllib.request.urlopen(req) as r: print(r.getcode())
```
3. Examine Liquidsoap log file and see the song name truncated:
```
2020/08/30 19:55:16 [test_input:3] New metadata chunk ? -- > Test 2.
```

**Expected behavior**

Expected behaviour is not to truncate the metadata - i.e. the example above should have had a log line like this:
```
2020/08/30 19:55:16 [test_input:3] New metadata chunk ? -- > Test 1 = Test2.
```

**Version details**
 - OS: Linux (`debian:buster-slim` Docker container)
 - Version `Liquidsoap 1.5.0+git@50de0f0f`

**Install method**
Debian package from deb.liquidsoap.info.

**Comment by toots** [comment]
Thanks for this detailed report! Too bad we didn't ship the fix in `1.4.3`.. It's in `master` now, tho!
