### ISSUE TITLE
Undefined variable ffmpeg.filter.alimiter

### ISSUE THREAD

**Issue by pedro-nonfree** [savonet/liquidsoap#1342]
I'm in liquidsoap version 1.4.2 (installed from opam in Debian 10 buster stable) and in a file I have the line `limiter = ffmpeg.filter.alimiter(limit = 0.9)` it complains this way `Error 4: Undefined variable ffmpeg.filter.alimiter`. But I have installed opam's ffmpeg `opam install ffmpeg`

I solved similar issues with ladspa such as, the problem of `compressor = ladspa.sc4(rms_peak = 0.5)` was that I was missing `opam install ladspa`.

If you search about this problem on the internet, it gets 0 results. Looks like nobody is using it? I would like to.

**Comment by toots** [comment]
Hi! The ffmpeg filters are only available when using the current `master` branch. For `lasdpa` plugins, they need to be installed separately. 

Feel free to follow-up in our slack channel if you need more details.
