### ISSUE TITLE
Unexpected channel configuration change when using input.http with aac

### ISSUE THREAD

**Issue by ChronosX88** [savonet/liquidsoap#1344]
**Describe the bug**
Liquidsoap doesn't decode correctly AAC stream from input.http.
I'm getting the following logs:
```
2020/09/11 18:01:40 [decoder:3] Method "AAC" accepted "audio/aac".
2020/09/11 18:01:40 [http_14876:3] Decoding...
2020/09/11 18:01:40 [http_14876:2] Feeding stopped: Faad error: Unexpected channel configuration change
```

**To Reproduce**
```
#!/usr/bin/liquidsoap
set("log.stdout",true)

set("scheduler.fast_queues",1)

# Start building the feed with music
url = "http://mgps.fmstream.ru:8010/megapolis-48.aac"
radio = mksafe(input.http(url))

# Stream it out
output.icecast(%opus(bitrate=320),
  host = "xxx", port = 8000, name="xxx", description="",
  password = "xxx", mount = "xxx", public=true,
  radio)

```

**Expected behavior**
The input stream will correctly decoded and relayed to icecast output.

**Version details**
 - OS: Ubuntu 20.04
 - Version: `1.4.1`

**Install method**
Ubuntu APT

**Comment by toots** [comment]
Hi! That seems like an error at the underlying library level. This kind of error can also happen if the data gets corrupted.

Have you tried to download the stream and play it with a regular media player? More generally, are you able to listen to the stream with another source client?

**Comment by ChronosX88** [comment]
> Hi! That seems like an error at the underlying library level. This kind of error can also happen if the data gets corrupted.
> 
> Have you tried to download the stream and play it with a regular media player? More generally, are you able to listen to the stream with another source client?

@toots Yep, the stream works correctly in a regular media player and in builtin browser player.
