### ISSUE TITLE
ARM64 Ubuntu & Debian builds

### ISSUE THREAD

**Issue by fourofspades** [savonet/liquidsoap#1347]
It would be convenient if there was a ARM64 variant of the Ubuntu and Debian builds available here.

https://github.com/savonet/liquidsoap/actions/runs/250631174

Currently in opam hell, trying to get things built .. :-(

**Comment by fourofspades** [comment]
Happy to test them out of someone can configure a build job.

**Comment by toots** [comment]
I'll look at it, shouldn't be too hard to do!

**Comment by toots** [comment]
Done! We now generate debian packages and docker images for `arm64`!
