### ISSUE TITLE
Unsupported format %fmpeg on master branch with debian 10.5

### ISSUE THREAD

**Issue by TheRealMattLear** [savonet/liquidsoap#1350]
Hi,

I'm struggling to get LS working with %ffmpeg() on the master branch and hoping i can get some assistance, i've been tryingto get this working for a few days now with no avail.

New installation of Debian 10.5. First of all, there are a number of dependency issues after pinning liquidsoap master branch (2.0.0) which i resolved by using the master branches of those dependencies. Install as follows:
```
# Prerequisites
apt-get install -y build-essential unzip m4 bubblewrap automake autoconf;

# Install Opam
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)

# Change to a user rather than root
su matt;
cd ~/;

opam init --bare -a -y;
opam switch create 4.08.0;
opam depext taglib mad lame cry samplerate liquidsoap ffmpeg;

git clone https://github.com/savonet/ocaml-mad mad
git clone https://github.com/savonet/ocaml-duppy duppy
git clone https://github.com/savonet/ocaml-mm mm
git clone https://github.com/savonet/ocaml-samplerate samplerate
git clone https://github.com/savonet/liquidsoap.git liquidsoap

opam pin -n duppy ./duppy
opam pin -n mm ./mm
opam pin -n mad ./mad
opam pin -n samplerate ./samplerate
opam pin -n liquidsoap ./liquidsoap

opam install taglib mad lame cry samplerate liquidsoap ffmpeg;
eval $(opam env)
```

start.liq
```
encoder = %ffmpeg(video_codec="libx264",format="flv")
output.url(fallible=true, url="rtmp://my-server:1935/stream/key", encoder, s = buffer(fallible=true, buffer=5., max=10., single("./sample.mp4")))
```

It results in the following error (note the assumingly typo of fmpeg instead of ffmpeg also?):
```
$ ./.opam/4.08.0/bin/liquidsoap ./start.liq
At line 1, char 10-53:
Error 12: Unsupported format: %fmpeg(format="flv",video_codec="libx264").
You must be missing an optional dependency.
```

**Comment by TheRealMattLear** [comment]
Hi, can anybody assist with this?

**Comment by toots** [comment]
Hi! We have released all dependencies on `opam` for `2.0` now, except for `ffmpeg`. All you should have to do is pin the latest `ocaml-ffmpeg` and `liquidsoap` and `opam` should be able to figure out the rest of the dependencies!

**Comment by TheRealMattLear** [comment]
> Hi! We have released all dependencies on `opam` for `2.0` now, except for `ffmpeg`. All you should have to do is pin the latest `ocaml-ffmpeg` and `liquidsoap` and `opam` should be able to figure out the rest of the dependencies!

Should we still be using 4.08.0 switch?

**Comment by TheRealMattLear** [comment]
Having difficulty on Debian 10.3; have tried with opam init

```
opam init --bare -a -y
opam switch create 4.08.0;
eval $(opam env);

git clone https://github.com/savonet/ocaml-ffmpeg ffmpeg;
opam pin -n ffmpeg ./ffmpeg;

git clone https://github.com/savonet/liquidsoap.git liquidsoap;
opam pin -n liquidsoap ./liquidsoap;

opam depext -i liquidsoap ffmpeg;
```

Error:
```
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
[ERROR] No solution for liquidsoap & ffmpeg: The following dependencies couldn't be met:
          - ffmpeg → ffmpeg-avutil
              unknown package


Command failed: opam list --readonly --external  --resolve=liquidsoap,ffmpeg returned 20
```

**Comment by toots** [comment]
Hi! There seems to be some weird dependencies issues these days. I'll try to reproduce and get back to you asap.

**Comment by toots** [comment]
Ok, this one looks easy actually. You need to pin all `ffmpeg` packages, not just the top-level `ffmpeg`. Here's a fix:
```
git clone https://github.com/savonet/ocaml-ffmpeg ffmpeg
cd ffmpeg  && opam pin -n . && cd ..
```

**Comment by TheRealMattLear** [comment]
Resolved!

**Comment by toots** [comment]
I think that this one can be closed now..
