### ISSUE TITLE
crossfade ignores fade_out if equals duration

### ISSUE THREAD

**Issue by RM-FM** [savonet/liquidsoap#1351]
- Ubuntu 20.04 
- 1.4.3
- installed using amd64 deb package

We are struggeling with this issue since 1.4.0 and it is still a problem with 1.4.3 obvisouly...

In case fade_out matches duration (which is a common use case in my opinion) the fade out will not happen. It just cuts hard. As soon as the fade_out param gets reduced to 2.9 everything sounds smooth.

Test setup (pls find script below):
- single file
- cue_cut (in: 0.5, out: 10)
- crossfade (dur: 3.0, fadein: 1.0, fadeout: 3.0)
- icecast output

One of the things I spotted for in the log is that there seems to be not enough time left to execute the 3.0s fade:
`2020/09/17 14:18:19 [cross_9474_before:4] Fading out with 2.94s remaining..`

Test script:
```
set("log.level",4)
set("frame.duration",0.01)

def append_cue(m) =
  [("liq_cue_out","10"),("liq_cue_in","0.5")]
end

src = single("/var/liquidsoap/test.mp3")
src = map_metadata(append_cue, src)
src = cue_cut(src)
src = crossfade(duration=3.0, fade_in=1.0, fade_out=3.0, src)

output.icecast(%mp3(bitrate=320),
		host = "example.com", port = 80,
		password = "example", mount = "example.mp3",
		name="Test LS 1.4.3",
		encoding="ISO-8859-1",
		fallible=true,
		src)
```

**Comment by toots** [comment]
Thanks for the report. I'll look at it in the coming days.

**Comment by toots** [comment]
Thanks for the report. This is fixed in the latest `master` now. I'll consider the changes for a potential future bugfix release. However, since the changes are liquidsoap-only, you should be able to drop them into your script. Just add the new version of `fade.out` at the very top of it:
```ruby
def fade.out(~id="fade.out",~duration=3.,
             ~override_duration="liq_fade_out",
             ~override_type="liq_fade_type",
             ~type="lin",s) =
  log = log(label=source.id(s),level=4)
  fn = ref(fun () -> 1.)
  type = ref(type)
  duration = ref(duration)
  start_time = ref(-1.)
  started = ref(false)

  def start_fade(d,_) =
    log("Fading out with #{d}s remaining..")
    start_time := source.time(s)
    duration = if d < !duration then d else !duration end
    fn := mkfade(start=1.,stop=0.,type=!type,duration=duration,s)
    started := true
  end

  def apply() =
    fn = !fn
    fn()
  end

  def stop_fade(_) =
    if !started then
      fn := fun () -> 1.
      started := false
    end
  end

  def update_fade(m) =
    if m[override_duration] != "" then
      duration := float_of_string(default=!duration,m[override_duration])
      log("New fade duration: #{!duration}")
    end

    if m[override_type] != "" then
      type := m[override_type]
      log("New fade type: #{!type}")
    end
  end

  s = on_metadata(update_fade,s)
  delay = fun () -> !duration
  s = on_track(stop_fade,s)
  s = on_end(delay=delay,start_fade,s)
  fade.scale(id=id,apply,s)
end
```

**Comment by RM-FM** [comment]
Thanks a lot @toots! I have implemented the fix as an include script and will carefully listen to the fades now :-)
