### ISSUE TITLE
input.http stops due to Assertion failed

### ISSUE THREAD

**Issue by elopio** [savonet/liquidsoap#1352]
**Describe the bug**
During the retransmission of an input.http to icecast, the stream stops after a few minutes.
The log prints:
2020/09/19 05:25:35 [http_21211:2] Feeding stopped: File "stream/generator.ml", line 82, characters 4-10: Assertion failed

**To Reproduce**
This is the script we are using:
https://gitlab.com/jaquerespeis/err-liquidsoap/-/blob/6098175472a1e67c38466fea42389977ad4084c0/scripts/stream-http.liq

The stream is:
http://live-mp3-128.kexp.org:8000/

**Expected behavior**
The stream should not stop.

**Version details**
 - OS: Debian sid
 - Version: 2.0.0+git@e4790af7

**Install method**
Installed from source after a lot of pain.

**Comment by toots** [comment]
Thanks for the report, I'll look at it asap. 

Question: do you need the latest sources? Although we love to receive reports and fix issues there, it is not considered stable for production at the moment. Have you considered using the latest stable release `1.4.3`?

**Comment by elopio** [comment]
Yes, I've switched to the latest in debian unstable for now, and it works. So no rush on this from my side.
And now I have everything ready to test master. If that helps in the future, just let me know.

**Comment by toots** [comment]
Hi! Thanks for the report. It seems to be working with the latest `master`. Any chance you could try it as well?

**Comment by toots** [comment]
Any update on this issue?

**Comment by elopio** [comment]
Hey. I grabbed the ubuntu focal deb from the most recent github actions. Running the same script with the same surce fails with:

```
At line 327, char 2-9:
Error 5: this value has type
  unit (inferred at /usr/share/liquidsoap/git/ac160608/libs/gstreamer.liq, line 110 char 0 - line 136 char 3)
but it should be a subtype of
  (id : _, fallible : _, start : _, on_start : _, on_stop : _, _) -> _
```
