### ISSUE TITLE
input.harbor authentication failing after update to 1.4.3

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#1353]
We're getting a report in from users that after our recent upgrade to the stable tagged 1.4.3 release version, DJ authentication via `input.harbor` is failing, even though our authentication script is correctly returning "true" (which should be converted via `bool_of_string`).

Here is the relevant portion of our auto-generated Liquidsoap code:

```
# DJ Authentication
live_enabled = ref false
last_authenticated_dj = ref ""
live_dj = ref ""

def dj_auth(auth_user,auth_pw) =
    user = ref ""
    password = ref ""
  
    if (auth_user == "source" or auth_user == "") and (string.match(pattern="(:|,)+", auth_pw)) then
        auth_string = string.split(separator="(:|,)", auth_pw)
        
        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := auth_user
        password := auth_pw
    end
    
    log("Authenticating DJ: #{!user}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="^string.quote(!user)^" --form dj-password="^string.quote(!password)^" --form api_auth="^string.quote("(apikey)")^""), default="")
    log("AzuraCast DJ Auth Response: #{ret}")
    
    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end
    
    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")
    
    live_enabled := true
    live_dj := dj
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("(apikey)")^""), default="")
    log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() = 
    dj = !live_dj
    
    log("DJ Source disconnected! Current live DJ: #{dj}")
    
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="^string.quote(dj)^" --form api_auth="^string.quote("(apikey)")^""), default="")
    log("AzuraCast Live Disconnected Response: #{ret}")
    
    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
end 

# A Pre-DJ source of radio that can be broadcast if needed
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = audio_to_stereo(input.harbor("/", id = "azuratest_radio_input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5.00, max = 10.00))
```

For reference, see AzuraCast/AzuraCast#3184

**Comment by SlvrEagle23** [comment]
Further comments from our users suggest this is happening specifically when users connect via SHOUTcast DJ clients and not Icecast ones.

We were already on a pinned version of 1.4.3, so we only went up maybe 5 or 6 commits when we switched to the official release version, so I'm reverting to see if that fixes the issue.

**Comment by toots** [comment]
Thanks for the report. You might want to try to revert this commit: 55b5e41fb7f8b7b87e7ab2b98f0f414fe4f4d9a3

**Comment by SlvrEagle23** [comment]
@toots We reverted to `3075878` and users are reporting that fixed the issue.

**Comment by toots** [comment]
Ok. Any chance we could try to narrow it down? I'll try to reproduce locally but, meanwhile, if y'all could test specifically commit 55b5e41 that would be awesome.

**Comment by TheRealMattLear** [comment]
@toots we're having the same problem, i can confirm that 55b5e41 did not resolve the issue but 3075878 does.

**Comment by toots** [comment]
@TheRealMattLear You mean that you reverted to 3075878fc99d4e41f2daf5403c4e2f7539960e1b and it's working from that commit?

**Comment by toots** [comment]
Hey there! Let's revive this, it seems like something we need to address sooner rather than later. I'd like to try to isolate the commit that created the issue. We know that it should be somewhere between https://github.com/savonet/liquidsoap/commit/3075878fc99d4e41f2daf5403c4e2f7539960e1b and https://github.com/savonet/liquidsoap/commit/55b5e41fb7f8b7b87e7ab2b98f0f414fe4f4d9a3. Any chance one of y'all with the issue would have a minute to a quick bisection test? Happy to provide details on how to do it...

**Comment by TheRealMattLear** [comment]
> @TheRealMattLear You mean that you reverted to [3075878](https://github.com/savonet/liquidsoap/commit/3075878fc99d4e41f2daf5403c4e2f7539960e1b) and it's working from that commit?

That is correct 

> Happy to provide details on how to do it...

Yeah absolutely, please let me know what to do and i'll run it for you shortly.

**Comment by toots** [comment]
Funny I actually have never used that functionality as well. Here's how it's supposed to work according to [the doc](https://git-scm.com/docs/git-bisect):
```
% cd /path/to/liquidsoap/git
% git checkout 3075878
% git bisect start
% git bisect bad 55b5e41
% git good
Bisecting: 14 revisions left to test after this (roughly 4 steps)
[98c6110718252f9759335b02816d62c2755efacc] Add on_cue_{in,out} to cue_cut

.. Try this commit, if it's good:
% git good

.. Otherwise:
% git bad
```
And keep repeating until you find the culprit!

**Comment by toots** [comment]
Hi there! I'm planning a `1.4.4` bugfix release. Let's make sure this one is fixed by then!

**Comment by SlvrEagle23** [comment]
@reans @pascalla Tagging you two on this since this is in Liquidsoap's next milestone and you had reported it over on our AzuraCast issues section. Hopefully we can get the fix into 1.4.4 so we can switch back to using the stable branch.

**Comment by toots** [comment]
Great, ty! What would really help is to find the one commit that introduced the issue. I'll have a look myself as well.

**Comment by Vaalyn** [comment]
@toots I have been testing around with different commit versions and found that it is working in commit 9a3e7f84bc98dc42ca0f8b0743e1e8c50d293dc9 and not in the commit 55b5e41fb7f8b7b87e7ab2b98f0f414fe4f4d9a3 so this is the commit resposible for breaking this functionality as far as I can see.

In `` the log gives me:

```
2020/12/13 05:55:57 [lang:3] Authenticating DJ: vaalyn
```
and in `` it shows:

```

**Comment by toots** [comment]
Well, that was a pretty dump bug, sorry it took so long to fix and thanks for all the effort. It'll come out with `1.4.4` soon. Would y'all mind testing this version? Thanks!

**Comment by Vaalyn** [comment]
@toots I can confirm that the fix is working.

I've recompiled our LS in AzuraCast with this commit and tested connecting via Mixxx and it is working.

**Comment by toots** [comment]
Super happy to hear that, thanks for confirming!
