### ISSUE TITLE
Provide encoder/source ip address to auth argument during harbor source authentication/connection

### ISSUE THREAD

**Issue by TheRealMattLear** [savonet/liquidsoap#1364]
We'd like to obtain the ip address of the source connection in order to:
a) Provide source connection ip information to our backend system
b) Restrict authentication based on ip address

To achieve this, i'd imagine the ip address could be passed as an additional argument to input.harbor(auth)

**Comment by toots** [comment]
Thanks for this report! Putting it on the list for `2.0`, track the progress here: https://github.com/savonet/liquidsoap/projects/2

**Comment by TraceOrdin** [comment]
This would be great! Excited for 2.0 :) Currently the only way I know of to get the ip address is to telnet in on the back end once someone is successfully connected and run the .status command in the Liquidsoap telnet server and then parse out the 'connected from' text.

Haven't found a way to get the IP during auth though, which would really help for tying this in to something like Fail2ban to lock out IP addresses of random people trying to hack in without correct credentials. Recently been getting around 20 unauthorized attempts a day on an unadvertised server (people probably finding it while IP scanning) and most of them are trying a userid of 'source'.

**Comment by toots** [comment]
Just pushed changes adding support for `address` in the auth function as well as a `connected_client` method that returns the (nullable) address of a connected client!

**Comment by TheRealMattLear** [comment]
Great work, thank you!

**Comment by TraceOrdin** [comment]
Amazing!! thanks a lot! :heart:

**Comment by toots** [comment]
Hi! Heads up, we just switched to passing a record for the `auth` function here: https://github.com/savonet/liquidsoap/issues/1580. This will break existing scripts but will allow for adding more arguments if needed without breaking existing scripts again..
