### ISSUE TITLE
1.4.3 fails to compile - alsa_in expected type bytes

### ISSUE THREAD

**Issue by paddatrapper** [savonet/liquidsoap#1371]
**Describe the bug**
While building the new release for Debian, I ran into the following build failure:

```
OCAMLOPT -c sources/alsa_in.ml
File "sources/alsa_in.ml", line 101, characters 42-46:
101 |                     let r = Pcm.readi pcm sbuf 0 len in
                                                ^^^^
Error: This expression has type string but an expression was expected of type
         bytes
make[4]: *** [../Makefile.rules:125: sources/alsa_in.cmx] Error 2
```

**Version details**
 - OS: Debian Sid
 - Version: 1.4.3

**Install method**
Source

**Comment by toots** [comment]
Hi! This should have been fixed recently. If you do `opam update` you should see:
```
% opam info liquidsoap.1.4.3
(...)
conflicts:    "alsa" {< "0.2.1" | >= "0.3.0"}
```

**Comment by paddatrapper** [comment]
Ok. What does that translate as to as a required alsa version? Am I right in understanding that alsa versions 0.3.0 and higher are not supported?

**Comment by paddatrapper** [comment]
Also I am packaging for Debian using the tar balls uploaded to github, so no `opam` commands are involved

**Comment by toots** [comment]
Ha I hear you. Alsa `0.2.x` should be working with `1.4.3`. Since I believe `liquidsoap` is the only real user of this binding, I wouldn't bother updating its package until liquidsoap `2.0` is out.

**Comment by toots** [comment]
Ha I see that it's already out in Debian. Hmmm, that's annoying. Can you downgrade a package?

**Comment by paddatrapper** [comment]
Not really... I guess I could upload a 3.0.0~really0.2 version, but will chat to the team and see what the consensus is

**Comment by toots** [comment]
I'll see if I can come up with a patch to make 1.4.3 work with that version.

**Comment by paddatrapper** [comment]
That would be great!

**Comment by toots** [comment]
This one should do it: https://github.com/savonet/liquidsoap/commit/5d7f810694caaf181e8fe97c14b836ca86e47cd5

**Comment by paddatrapper** [comment]
Yup that worked! Thanks a lot
