### ISSUE TITLE
1.3.7 dj disconnect for 1/ seconds .. listen autodj and then comeback music dj again

### ISSUE THREAD

**Issue by ajeje989** [savonet/liquidsoap#1375]
hi i have a bug with this version ..

I have sonicpanel (similar to centova cast) streaming audio panel.

It often happens to me that when the DJ is online for a second you hear the music of the autodj and after 1/2 seconds the live DJ music returns.

What can it depend on?

from the logs I see this

[dummy: 3] Source failed (no more tracks) stopping output ...

Please help me

**Comment by ajeje989** [comment]
set("log.file.path","/home/sc_raffa/log/autodj.log")
set("log.unix_timestamps",true)
set("init.allow_root",true)
set("server.telnet.port", 5989)
set("log.level",3)
set("server.telnet", true)
set("harbor.timeout", 30.0)
set("harbor.reverse_dns", false)

playreg = request.equeue(id="playreg")
playreg = audio_to_stereo(playreg)

%include "functions"
plist = "/home/sc_raffa/playlist/playlist"

stop_f = ref (fun () -> ())
def stop_dump() = f = !stop_f f () end

def live_disconnected() = djdone = get_process_output("echo '' > /home/sc_raffa/autodj/livedj") stop_dump() end
def live_connected(header) = djrec = get_process_output("") end

auth = harbor_auth("sc_raffa")
live = audio_to_stereo(input.harbor(icy=true,"/",port=4880,auth=auth,buffer=25.,max=60.,on_connect=live_connected(),on_disconnect=live_disconnected))
ignore(output.dummy(live, fallible=true))

# Playlist
tracks = audio_to_stereo(playlist(mode="randomize", plist, reload_mode="watch"))


jlist = "/home/sc_raffa/playlist/jingles"
jingles = audio_to_stereo(playlist(mode="normal", jlist, reload_mode="watch"))
tracks = rotate(weights = [1,2],[jingles,tracks])


radio = fallback(track_sensitive=false,transitions=[to_req, to_file],[playreg,tracks])

radio = fallback(track_sensitive=false,transitions=[to_live, to_file],[live,radio])
radio = my_safe(radio)

def idnew(m) =
  setnow = get_process_output("php /usr/local/sonicpanel/clients/scr/getfile.php sc_raffa #{quote(m[\"filename\"])}")
  title = m["title"]
  if "#{title}" == "" then
  [("title", get_process_output("basename #{quote(m[\"filename\"])} .mp3"))]
  else
  title = m["title"]
  [("title","#{title}")]
  end
end

radio = map_metadata(idnew, radio)

radio = server.insert_metadata(id="meta", radio)

voice = request.queue(id="voice")
voice = audio_to_stereo(voice)
voice = amplify(3.,override="replay_gain",voice)
radio = smooth_add(normal=radio,p=0.05,special=voice)

jinglelive = request.queue(id="jinglelive")
jinglelive = audio_to_stereo(jinglelive)
radio = smooth_add(normal=radio,p=0.15,special=jinglelive)

add_skip_command(command="skip", radio)

output.shoutcast(%mp3(bitrate=128),name="Radio La Spada nel Cuore",url="https://xat.com/Radio_la_Spada_Nel_Cuore_Forever",host="127.0.0.1",port = 9406,password = "pass",fallible=true,radio)


def start_sch(s) = ret = get_process_lines("cat /home/sc_raffa/sch") list.iter(fun(x) -> begin foo = server.execute("playreg.push #{x}") end,ret) end
server.register(namespace="schedule","start",fun (s) ->  begin start_sch(s) "Done!" end)

def start_dump(file_name) = s = output.file(%mp3(bitrate=320),fallible=true,reopen_on_metadata=false,"/home/sc_raffa/records/#{file_name}",live) stop_f := fun () -> source.shutdown(s) end
server.register(namespace="dump","start",fun (s) ->  begin start_dump(s) "Done!" end)
server.register(namespace="dump","stop",fun (s) -> begin stop_dump() "Done!" end)

this is my setting .. why have disconnect random from dj ( many not have problem with internet )

**Comment by toots** [comment]
Hi! Thanks for the report. Could you add some logs showing what's happening around when the problem happens? Thanks!

**Comment by ajeje989** [comment]
what log u need ?

I have many users who may have a slow internet line .. isn't there a way to help them not to fall from the direct without starting autodj immediately?

example if a DJ does not immediately send the song on the air autodj starts .. you cannot insert a mute of at least 3/4 seconds ... If after 3/4 seconds the audio is not recognized then ok autodj starts but not immediately.

**Comment by toots** [comment]
So you want to insert some silence or maybe a jingle when a DJ disconnects?

**Comment by ajeje989** [comment]
I don't want the DJ to disconnect immediately if he doesn't find audio in the DJ program he is broadcasting

At the moment the DJ if it is live and does not play a song immediately starts in the audio stream of the autodj. I would like there to be a few seconds before autodj starts.

Also I would like djs with slow lines not to lose the live stream .. maybe increasing this Error while reading from client: Timed out after waiting for 30.00 sec

**Comment by ajeje989** [comment]
I improved the situation by setting a buffer to 25 .. there is a bit of delay but it doesn't matter.

can't you do anything else?

**Comment by toots** [comment]
I'm still trying to understand. When you say that the DJ does not play a song immediately, does that mean that they're sending silence (blank) or that their connection is too slow?

**Comment by ajeje989** [comment]
No .. I would like to

1) If there is a way to optimize the streaming for slow connections that do not fall from the live.

At the moment the djs happens to fall from the live broadcast, the autodj starts, 2 seconds pass and the live dj returns

Is this normal?


2) When the live DJ does not insert any audio stream, autodj starts immediately and his live broadcast restarts as soon as he inserts an audio stream.

I would like that if the DJ does not immediately play the song that the autodj does not start immediately but 3 4 seconds pass.

**Comment by toots** [comment]
From what I can understand, you are mostly dealing with DJ connections that are too slow. I think your only tool is indeed increasing the buffer. However, if the sender's connection cannot send fast enough to send real-time data, there isn't much that you can do, the stream is bound to break at some point.

> When the live DJ does not insert any audio stream, autodj starts immediately

Sorry, I don't understand what this means.

**Comment by ajeje989** [comment]
If the dj on the air does not put music in the stream, do you immediately hear the music of the autodj? it's normal?

It is not possible to insert seconds before the autodj music starts if the DJ on air does not play music

sorry my bad english.

**Comment by ajeje989** [comment]
look here

1603137563.934490 [input (dot) harbor_6476: 3] New metadata chunk? - Michele Morrone - Michele Morrone - Feel It (from 365 days movie).
1603137762.324242 [fallback_6485: 3] Switch to fallback_6483 with forgetful transition.
1603137762.367986 [dummy: 3] Source failed (no more tracks) stopping output ...
1603137763.356089 [input (dot) harbor_6476: 3] New metadata chunk? - JINGOL POETRY.
1603137777.204330 [fallback_6485: 3] Switch to audio_to_stereo_6477 with transition.
1603137777.244498 [map_metadata_6495: 3] Inserting missing metadata.
1603137810.146724 [input (dot) harbor_6476: 3] New metadata chunk? - ROBERTA TANTILLO BEFORE YOU GO.
1603137885.384037 [input (dot) harbor_6476: 3] New metadata chunk? - LanaDelReyVEVO - Lana Del Rey - Let Me Love You Like A Woman (Audio).
1603138063.844253 [fallback_6485: 3] Switch to fallback_6483 with forgetful transition.
1603138063.886189 [dummy: 3] Source failed (no more tracks) stopping output ...
1603138083.883962 [input (dot) harbor_6476: 3] New metadata chunk? - JINGOLCACCOLNLM.
1603138099.124337 [fallback_6485: 3] Switch to audio_to_stereo_6477 with transition.
1603138099.164503 [map_metadata_6495: 3] Inserting missing metadata.
1603138146.875208 [input (dot) harbor_6476: 3] New metadata chunk? - Leon Faun - Leon Faun - OH CACCHIO (prod. Duffy).
1603138276.964248 [fallback_6485: 3] Switch to fallback_6483 with forgetful transition.
1603138277.008708 [dummy: 3] Source failed (no more tracks) stopping output ...
1603138292.364370 [fallback_6485: 3] Switch to audio_to_stereo_6477 with transition.
1603138292.404470 [map_metadata_6495: 3] Inserting missing metadata.
1603138338.865156 [input (dot) harbor_6476: 3] New metadata chunk? - iamAURORAVEVO - AURORA - Running With The Wolves.
1603138348.141273 [input (dot) harbor_6476: 2] Feeding stopped: Mad.End_of_stream.
1603138348.148572 [threads: 3] Thread "harbor source feeding" terminated (1 remaining).
1603138348.753978 [decoder: 3] Method "MAD" accepted "audio / mpeg".
1603138348.759924 [threads: 3] Created thread "harbor source feeding" (2 total).
1603138348.760012 [input (dot) harbor_6476: 3] Decoding ...
1603138353.204260 [map_metadata_6495: 3] Inserting missing metadata.
1603138362.124243 [dummy: 3] Source failed (no more tracks) stopping output ...
1603138362.124272 [fallback_6485: 3] Switch to fallback_6483 with forgetful transition.
1603138392.513550 [input (dot) harbor_6476: 2] Feeding stopped: Mad.End_of_stream.
1603138392.520345 [threads: 3] Thread "harbor source feeding" terminated (1 remaining).


it is not a internet bad because don't have have log timeout error 30 seconds .. I think it is the famous problem that if you do not play the song immediately, autodj starts ..


what can I do ?
