### ISSUE TITLE
Continuous Mp3

### ISSUE THREAD

**Issue by veyselolgun** [savonet/liquidsoap#1392]
Hello, i am trying to play an audio in my local file when there is no stream.
Here is the script;
```
#!/usr/bin/liquidsoap -v
set("log.level",4)
stream = input.http("http://127.0.0.1:8000/stream",logfile="/tmp/buffer.log")

playlist = playlist("/home/pi/Music/")
myplaylist = mksafe(fallback([stream,playlist]))

output.ao(myplaylist)
```
My mp3 file immediately increasing. Here is the scenario;

I have a stream file and i upload this stream to drive without stopping (mp3 size continuously increasing) and then i am dowloading this stream to my local from drive(My local file size continuously increasing). And then i play this mp3 file via liquidsoap everything is okay untill now. But after 2 or 3 minutes mp3 going back to start. I mean it is not go forwarding, it is starting to replay.  I do not know it is about liquidsoap maybe another problem occour but i care your advices
I hope that i could explain my problem

**Comment by toots** [comment]
Hi! I'm not sure if a growing mp3 file can be used easily. We rely on the underlying file system to open and read files. If the file grows after it's been opened by us, there's no guarantee that this would be reflected on the file that's opened in the application. I don't think it's a limitation of liquidsoap but, rather, of the file system/system/posix implementation.. Somewhere there..

If you need an on-going mp3 data stream, I'd recommend to split it into multiple files instead.

**Comment by veyselolgun** [comment]
Thank you for recommendation, i will take care your advice.
