### ISSUE TITLE
Write back on server when callback occurs

### ISSUE THREAD

**Issue by LucaSoldi** [savonet/liquidsoap#1399]
Hi all, I love liquidsoap. :)
I'm using it through ssh socket,  and it works without any problem. 

My target is to control it all through socket and socat. I would use it not only to send command but to receive notifications too, for example now I want the server says something when on_metadata functions occurs, so I can tell to my socket client that liquidsoap start playing new file. 

I registered without any problem new server funtions, but what I want now is that liquidsoap wirte something on the socket so client can read it and get in sync. 
I see the commands server.write 

```
server.write "string to write" then
  log("string done writting!")
  "Done!"
end
```

Is it good for my purpose? Can you give me some example how to use it? 

Thanks in advance

**Comment by toots** [comment]
Hi! That's an interesting feature request! Yes, you should be able to do it. Any server interaction needs to start with a command do the first step would be to register a "subscribe to new metadata update" command.

Then you could do things like:
```
c = server.condition()

# Warning: syntax for `ref` has changed in `2.0.0`
metadata = ref ""

def cmd(_) =
  def rec f() =
    server.write !metadata then
      server.wait c then
        f()
      end
    end
  end

  f ()
end

server.register(...)

# Outside of the command:
def metadata_callback(m) =
  metadata := "#{m}"
  server.signal(c)
end

# With 2.0.0: s.on_medatadata(metadata_callback)
s = on_metadata(metadata_callback, s)
```

**Comment by toots** [comment]
I'm closing this since I believe that covers what you needed. Please re-open if needed or come chat on the slack. We would love to see your final server command!
