### ISSUE TITLE
Type error on 2.0.0 - Gstreamer / hls

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1401]
**Describe the bug**
A clear and concise description of what the bug is. Add some script and log extract so we can see what is happening. Don't forget to add some context although not necessarily your whole script..

Running script give the following error

```
At line 327, char 2-9:
Error 5: this value has type
  unit (inferred at /home/ubuntu/.opam/default/lib/liquidsoap/share/liquidsoap/git/ac160608/libs/gstreamer.liq, line 110 char 0 - line 136 char 3)
but it should be a subtype of
  (id : _, fallible : _, start : _, on_start : _, on_stop : _, _) -> _

```

**To Reproduce**
A minimal script to reproduce the issue is the most efficient way to have your bug addressed and fixed very quickly!

```
url = "http://localhost:8000/mount"

source = input.http(buffer=10.,max=15.,url)

aac_hifi = %ffmpeg(format="mpegts",
                    %audio(
                     codec="aac",
                     channels=2,
                     ar=48000,
                     b="96k")
)

streams_info = [("aac_hifi",(220000,"mp4a.40.2","ts"))]

streams = [("aac_hifi", aac_hifi)]

def segment_name(~position,~extname,stream_name) =
  timestamp = int_of_float(gettimeofday())
  duration = 2
  "#{stream_name}_#{duration}_#{timestamp}_#{position}.#{extname}"
end

output.file.hls(playlist="live.m3u8",
#                encode_metadata=true,
                segment_duration=2.0,
                segments=5,
                segments_overhead=5,
                segment_name=segment_name,
                streams_info=streams_info,
                persist=true,
                persist_at="/tmp/state.config",
                "/tmp/hls",
                streams,
                mksafe(source))

```

**Expected behavior**
Script to run

**Version details**
 - OS: [e.g. Debian, OSX] - Ubuntu 20.04
 - Version [e.g. `1.3.4`] - 2.0.0

**Install method**
Did you install via `opam`? Using your distribution's packages? From source?

opam - pinned to liquidosoap / ffmpeg / gstreamer from git

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

Also if I activate ``` encode_metadata=true ``` I get a repetitive ffmpeg frame size not set and not HLS stream. -- this happens on ``` 1.4.3 ``` - which will run the script .

Many thanks for all your hard work.

**Comment by toots** [comment]
Thanks for the report. This is fixed now!

**Comment by Russsgithub** [comment]
Thank you.
