### ISSUE TITLE
Liqudisoap 2.0.0 / Soundtouch version not available

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1405]
**Describe the bug**
Liqudisoap 2.0.0 requires ocaml-soundtouch 0.1.9, but it doesn't exist in liquidsoap-full git rep.

Just flagging - no rush.

**To Reproduce**
It won't install .

**Expected behavior**
Clean install

**Version details**
 - OS: [e.g. Debian, OSX] - any
 - Version [e.g. `1.3.4`] - 2.0.0

**Install method**
Did you install via `opam`? Using your distribution's packages? From source?
Opam

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by toots** [comment]
That's true. I'll push a release soon. Meanwhile, you can use a pinned version. Thanks for reporting!

**Comment by Russsgithub** [comment]
Thanks for the reply, there doesn't seem to be a version 0.1.9 to pin. ocaml-soundtouch only has one branch (master) at version 0.1.8.

**Comment by toots** [comment]
It's coming: https://github.com/ocaml/opam-repository/pull/17751 !

**Comment by Russsgithub** [comment]
thanks
