### ISSUE TITLE
Liquidsoap 1.4.3 hangs at shutdown sometimes / related to Ocaml-Lo

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1409]
**Describe the bug**
9 times out of ten when I shutdown liquidsoap I get this error
```
2020/11/18 16:48:34 [threads:3] Waiting for queue threads to terminate...
Thread 1 killed on uncaught exception LO.Server.Stopped
Raised by primitive operation at file "LO.ml" (inlined), line 83, characters 2-51
Raised by primitive operation at file "lang/builtins_lo.ml", line 71, characters 13-21
Called from file "thread.ml", line 39, characters 8-14
```
and the system hangs.

**To Reproduce**
```
def meta(source, m) =
  def call() =
    playing(m)
    data = "#{!m_playing}"
    system('oscsend localhost 7777 "/metadata" ss "title" "#{data}"')
    -1.
  end
  add_timeout(fast=true,0.,call)
end

mr = insert_metadata(radio)
imeta = fst(mr)
radio = snd(mr)

def on_meta(m) =
  value = snd(m)
  print("Insert metadata title = #{value}")
  imeta([("title",value)])
end

osc.on_string_pair("/metadata",on_meta)
```
playing(m) sets ref m_playing

**Expected behavior**
System not to hang

**Version details**
 - OS: [e.g. Debian, OSX] - Ubuntu 20.04
 - Version [e.g. `1.3.4`] - 1.4.3

**Install method**
Did you install via `opam`? Using your distribution's packages? From source?

Opam

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by Russsgithub** [comment]
This happens less if i increase the amount of queues. To be honest I dont really understand the queues, so increased bot fast and non-blocking by two each.

The above still happens, but a lot less.
Possibly when shutdown is called while a message is still going through the port ?

**Comment by toots** [comment]
Hey! I pushed a PR here that might fix the bug: https://github.com/savonet/liquidsoap/pull/1508. There should be builds with debian packages coming up with the CI run shortly at: https://github.com/savonet/liquidsoap/actions/runs/587441380.

Would you mind trying the fix and confirming that it works? Thanks!

**Comment by Russsgithub** [comment]
Hello,

I can confirm that I'm no longer getting Lo errors on forced shutdown.

Thanks.

**Comment by toots** [comment]
Awesome thanks for testing!
