### ISSUE TITLE
Stream image not shown in quickstart docs

### ISSUE THREAD

**Issue by elopio** [savonet/liquidsoap#1415]
**Describe the bug**
In the quickstart page of the documentation, sources section, the image of the stream is not shown.

**To Reproduce**
Go to https://www.liquidsoap.info/doc-1.4.3/quick_start.html

**Expected behavior**
The image is shown.

![path18](https://user-images.githubusercontent.com/617831/100487316-87d14580-30cd-11eb-98d6-806208c9fac7.png)

**Comment by toots** [comment]
Should be fixed now, thanks for reporting.
