### ISSUE TITLE
Could not get a valid media file of kind {audio=2;video=1;midi=0}

### ISSUE THREAD

**Issue by xorinzor** [savonet/liquidsoap#142]
I am trying to run the following code:

````
set("video.converter.preferred", "ffmpeg")
set("frame.video.width", 1280)
set("frame.video.height",720)
set("frame.video.samplerate",30)

s = single("trailer_1080p.ogg")

output.file(%ogg(%vorbis, %theora(quality=25,width=1280,height=720)), "test.ogv", s)
````
but this produces the error:
````
Could not get a valid media file of kind {audio=2;video=1;midi=0}
````
even though the video has stereo sound and a video source (it's a trailer from the big buck bunny), why is this happening?

**Comment by xorinzor** [comment]
So I'm running liquidsoap 1.1.1 now and this issue is still happening; tried different media files, still incorrectly detects it.

Is there some way of just forcing liquidsoap to accept it? it's clearly a bug and kind of annoying that it's preventing it from running the script even though it's correct.

Tried some way of working around the issue, but no matter what I try, or what combination of audio=x and video=x, it won't accept the file.

**Comment by xorinzor** [comment]
Running "liquidsoap -r <filename>" results in:

![screenshot 1](https://cloud.githubusercontent.com/assets/4212335/11764639/f7d10e22-a137-11e5-9365-bf7e0e039c4a.png)

telling there's no audio and no video, which is clearly wrong too; any ideas?

**Comment by xorinzor** [comment]
recompiling the plugin from source rather then installing using apt-get fixed it.

**Comment by georgerappel** [comment]
I got it to work with an ogg sound file by removing the line `channels=1` from the configuration
