### ISSUE TITLE
FFMPEG: AAC HLS Metadata Output?

### ISSUE THREAD

**Issue by xemles** [savonet/liquidsoap#1424]
Hello,
I've been trying to output to HLS, it works properly using [https://www.liquidsoap.info/doc-dev/hls_output.html](https://www.liquidsoap.info/doc-dev/hls_output.html)

However, I'd also like to send the metadata, and I've tried multiple options and still cannot figure it out:

I've checked [this page](https://www.liquidsoap.info/doc-dev/encoding_formats.html) which tells that we can use all the ffmpeg "generic options", and I still cannot figure it out.
Here is what i've tried

```
aac_lofi = 
  %ffmpeg(
    format="m4v",
    %audio(
      channels=2,
      samplerate=44100,
      codec="libfdk_aac",
      b="32k",
      afterburner=1
    ),
    metadata="title=test"
  )
```
```
aac_lofi = 
  %ffmpeg(
    format="m4v",
    %audio(
      channels=2,
      samplerate=44100,
      codec="libfdk_aac",
      b="32k",
      afterburner=1,
      metadata="title=test"
      )
    )
```

I've also tried `metadata.title=""` but no success.
I always end up with an error, but the closest I've been is the two first there because the error message I get is:
`Error 9: Failure: Unrecognized options: metadata="title=test"`

If anybody got an idea, I'd love to know it!

**Comment by xemles** [comment]
Forgot to say that even though it shows `format="m4v"`, I also tried with `adts`. I was trying to see if I managed to send them with others.

**Comment by xemles** [comment]
Alright so I need to send apetags with `-write_apetag 1` but I still don't know where

**Comment by xemles** [comment]
Welp, guess i'm never gonna have an answer

**Comment by toots** [comment]
This is linked to https://github.com/savonet/liquidsoap/issues/916

**Comment by toots** [comment]
This is fixed nows!
