### ISSUE TITLE
output.icecast not working when there is ipv6 only

### ISSUE THREAD

**Issue by pedro-nonfree** [savonet/liquidsoap#1425]
**Describe the bug**

liquidsoap script that points to icecast through `output.icecast` is not working when it is only reachable through ipv6

**To Reproduce**

it is easily reproduceable in localhost

in `/etc/icecast/icecast.xml` put `<bind-address>::1</bind-address>` 

so

```
[02:12:26] $ ss -tupanl | grep 8000
tcp     LISTEN   0        5                  [::1]:8000              [::]:*          
```

prooved that ping resolves correctly to ipv6 in localhost

```
[02:18:54] $ ping localhost
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.032 ms
64 bytes from localhost (::1): icmp_seq=2 ttl=64 time=0.032 ms
```

and this is the script to reproduce it ( [here more details](https://gitlab.com/pedrolab/ipv6-only-hackathon-radio/-/issues/1) and [more details](https://gitlab.com/pedrolab/ipv6-only-hackathon-radio) )

```
# get input from another icecast mountpoint
signal = input.http(max=20., 'http://localhost:8000/playlist.mp3')
# ensure more loudness (normalization and compression)
signal = nrj(signal)

output.icecast(%mp3(bitrate=256),
     description = 'hack4glarus radio',
     password = 'hackme', mount = 'main.mp3',
     mksafe(signal))
```

**Expected behavior**

expected behavior is to see an icecast mountpoint working with name *main.mp3*, but that does not happen. In the log, there are also errors such as

```
2020/12/06 02:13:50 [main(dot)mp3:2] Connection failed: could not connect to host: Connection refused in connect()
2020/12/06 02:13:50 [main(dot)mp3:3] Will try again in 3.00 sec.
```

**Version details**
 - OS: Debian stable
 - Version tried with default debian stable liquidsoap `1.3.3-2` and opam build `1.4.2`

**Install method**
Did you install via `opam`? Using your distribution's packages? From source?

deb package and opam build

**Comment by gilou** [comment]
Hi,
Indeed, this is broken, if I do say `output.icecast(host='stream.wolface.net')` which is announced in v4 and v6, it chooses IPv4 (which shouldn't happen, as Linux should try IPv6 by default or configuration), then if I switch to an IPv6 address in host parameter, it tries to resolve it, and gets: `Connection failed: Not_found`

This is a bug.

**Comment by gilou** [comment]
as far as I know, this is still relevant, I have to test if it's any better using 2.0

**Comment by gilou** [comment]
This is still an issue in 2.0.2.
Using an explicit IPv6, this happens, as if it was trying to resolve it… great.
```
2022/01/18 23:29:49 [ice:3] Connecting mount test for source@2001:41d0:d:2147::106...                              
2022/01/18 23:29:49 [ice:2] Connection failed: Not_found                                                               
2022/01/18 23:29:49 [ice:3] Will try again in 3.00 sec.
```
If the name is ipv4/ipv6 resolvable it ignores the IPv6, which is … not what is supposed to happen.

I can provide an IPv6 reachable client/server if it helps.

**Comment by gilou** [comment]
input.http works, however, so this might not be fully because of ocaml support :P
This works, e.g.:
`liquidsoap "output(input.http('https://[2001:41d0:d:2147::106]/secousse'))"`

and using stream.wolface.net, it seems like it's accurately choosing IPv6 over IPv4.

**Comment by gilou** [comment]
and I'm also guessing, this might be an issue to follow on ocaml-cry, will investigate a bit…

**Comment by toots** [comment]
`input.http` uses `ffmpeg` 🙂

**Comment by toots** [comment]
Let's close this one and focus on savonet/ocaml-cry#5
