### ISSUE TITLE
Lastfm Submission failed: unknown error: unrecognized response code

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1427]
I upgraded from version 1.4.2 to 1.4.3 via opam on Debian Buster and discovered that Last.fm submissions no longer appear to work.

In the logs, I keep seeing the message below for all attempted track submissions.

`[audioscrobbler:3] Lastfm Submission failed: unknown error: unrecognized response code`

The settings in the liq script are as below.

```
#LAST.FM SCROBBLING#
def lastfm.submit(~user,~password,~source="broadcast",~length=false,m) =
audioscrobbler.submit(user=user,password=password,
source=source,length=length,
host="post.audioscrobbler.com",port=80,m)
end

radio = on_metadata(lastfm.submit(user="*******",password="*******"), radio)
```

**Comment by oranjebloom** [comment]
I've added a minimal script to help you reproduce this issue in version 1.4.3

[test.liq.txt](https://github.com/savonet/liquidsoap/files/5781193/test.liq.txt)

**Comment by Groschi** [comment]
Yup. Same thing happens to me.

**Comment by oranjebloom** [comment]
Glad I'm not the only one. Most likely a bug then. If we're lucky, they might get to it before version 1.4.4 is out.

**Comment by toots** [comment]
This is most likely an issue with [savonet/ocaml-lastfm](https://github.com/savonet/ocaml-lastfm). What version of the module are you using?

**Comment by toots** [comment]
The test script works for me on both `1.4.4` and `main` with `lastfm` version `0.3.0`

**Comment by oranjebloom** [comment]
You're version of lastfm is older than the one I have. I am running 0.3.2 in Liquidsoap version 1.4.2 (which works).
I hadn't tested 1.4.4 before now ... but lastfm 0.3.3 works there, which is good. 
However, in version 2.0 the following line breaks the script... has there been a change to `on_metadata` or some of the other syntax in that line?
 
`#radio = on_metadata(lastfm.submit(user="*********",password="******"), radio)`

**Comment by toots** [comment]
Sorry I was wrong, I'm on `0.3.3` as well.

On `main`, you need to do:
```
radio.on_metadata(lastfm.submit(user="*********",password="******"))
```
This is working as well for me.

**Comment by oranjebloom** [comment]
Hi @toots, I recompiled my install on `main` the line below for last.fm submissions breaks the script. Has there been a recent change (to this line or last.fm code)?
`
radio.on_metadata(lastfm.submit(user="*********",password="******"))`

**Comment by toots** [comment]
> Hi @toots, I recompiled my install on `main`, and the line below for last.fm submissions breaks the script. Has there been a recent change (to this line or last.fm code)?
> ` radio.on_metadata(lastfm.submit(user="*********",password="******"))`
> 
> the script works fine when all of the following is commented out
> 
> ```
> #LAST.FM SCROBBLING#
> def lastfm.submit(~user,~password,~source="broadcast",~length=false,m) =
> audioscrobbler.submit(user=user,password=password,
> source=source,length=length,
> host="post.audioscrobbler.com",port=80,m)
> end
> 
> radio.on_metadata(lastfm.submit(user="*************",password="**********"))
> ```

It was changed to use the new `libcurl` implementation but then reverted yesterday. Maybe try the latest `main` again?

**Comment by oranjebloom** [comment]
@toots I've followed your recommendation and reinstalling the latest `main`, but this hasn't fixed the last.fm problem above.

I can confirm that the script will work without the last.fm code chunk above, but it fails when it is enabled. It worked fine prior to the recent libcurl changes. Do you have a working instance of the last.fm code currently running on `main`?

Just so you know, I've successfully installed and run `main` in the past using the installation method on Debian buster below.

```
opam init
eval `opam config env`
opam install depext
opam depext taglib mad lame cry ssl samplerate magic lastfm inotify liquidsoap
opam install taglib mad lame cry ssl samplerate magic lastfm inotify liquidsoap
```

then, I installed and pinned `main` ...

```
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add liquidsoap .
```
