### ISSUE TITLE
Can you describe the Map-Metadata DOC page a bit better?

### ISSUE THREAD

**Issue by ttodua** [savonet/liquidsoap#1430]
At https://www.liquidsoap.info/doc-1.4.2/metadata.html , in ` Map metadata` section, this function is shown:

```
# Apply map_metadata to s using append_title
s = map_metadata(append_title, s)
```
However, it is not mentioned, what is `s`?

**Comment by rrolla** [comment]
s is an audio source: https://www.liquidsoap.info/doc-1.4.3/reference.html#map_metadata

**Comment by ttodua** [comment]
should it be `playlist` or `radio` variable?
i.e.
```
myPlaylist = playlist(id="...)
...
radio = random(....)
```
can i pass any of them?

**Comment by davidtrattnig** [comment]
@ttodua yes, you can pass `playlist` or `radio`, if the latter is e.g. holding a stream.

**Comment by ttodua** [comment]
thanks for answer!
