### ISSUE TITLE
Liquidsoap not sending "correct" metadata through output.icecast

### ISSUE THREAD

**Issue by davehayes** [savonet/liquidsoap#1435]
**Describe the bug**

Metadata is apparently not being sent correctly through icecast. No android player I have found yet can receive the stream I am sending and extract any metadata out of it. Trying all the players possible might take quite a long time, but my count is at 20. 

In fact, the only player I've seen receiving metadata is a desktop VLC (Windows, Mac, and FreeBSD), but apparently what it is displaying is considered the station name and somehow artist/title metadata is being sent as the station name? Please see [this issue](https://code.videolan.org/videolan/vlc-android/-/issues/1573). I am attempting to convince one or more of the developers involved to help figure this out. 

**To Reproduce**

Anyone who is testing or debugging on the issue may connect to [the liquidsoap stream](http://205.147.26.14:8001/JetCafeStudios.ogg) in question to see the behavior in question. Do not be fooled into using https:// as that schema will not work, it's http: (or icyx: inside of VLC). There is some detail on what is being sent in the VLC issue above.

The liquidsoap script I am using below couples with a stream socket and external software tells liquidsoap what to queue to play. 

```
set("server.socket", true)
set("server.socket.path", "/streaming/liquidserver")
set("server.socket.permissions",0o660);

## Start with silence
defaultsource = blank(duration=15.0)
serverqueue = request.queue(id="mainreq")

## Replay gain
serverqueue= amplify(1., override="REPLAYGAIN_TRACK_GAIN", serverqueue)

## Play anything on the request queue
content = fallback([ serverqueue, defaultsource ])

## Crossfade
crossplay = smart_crossfade(content, conservative=true, width=4.)

## And out
output.icecast(
  %vorbis(channels=2, quality=0.3),
  protocol="http",
  fallible=true,
  icy_metadata="true",
  id="JetCafe Studios",
  description="Private music stream for use of authorized personnel",
  genre="varies",
  host="127.0.0.1",
  mount="JetCafeStudios.ogg",
  password="hackme",
  port=8500,
  crossplay,
)
```
 
**Expected behavior**

Liquidsoap should send "correct" metadata to Icecast, so it can send "correct" metadata to players.

BIG RED CAVEAT: I don't know what "correct" metadata should be. There's no apparent documentation anywhere for this. Before you tell me to google it, remember that google returns different search results for different people out of the billions of links out there, so if you have a pointer to some documentation I'd love to see it. 

**Version details**
 - OS: FreeBSD
 - Version 1.3.7

I did some cursory examination of liquidsoap source and the ocaml-cry source (which is apparently used). No mention of the "New Icy-Title=Rhythm Jets  - Christmas Song" idea appears to be in the source even at 1.4.X.

**Install method**
Through opam on FreeBSD and a lot of pain. I'm getting intimately familiar with FreeBSD's issues.

**Comment by toots** [comment]
Hi,

There are two things here:
* On the source end, metadata is sent via a `GET` request to the server. You can double check that by going to the icecast server and checking that it displays the current metadata on its webpage.
* On the listener side, metadata are sent in-band via a ad-hoc protocol developed for shoutcast long time ago. It is briefly described here: https://cast.readme.io/docs/icy

In order to debug that, we should check on each step. First, are you able to confirm that your icecast server does or does not display metadata from liquidsoap?

**Comment by davehayes** [comment]
Ok confirmed I can see the metadata on the webpage of the icecast server. 

Next, thank you for the page of documentation. Looking through the vlc log I have, I can see that most of it is being observed but not all. Here's a snippet from a log file (this is just what VLC logs):

```
GET /JetCafeStudios.ogg HTTP/1.1
Host: 205.147.26.14:8001
Accept: */*
Accept-Language: en_US
User-Agent: VLC/3.0.11 LibVLC/3.0.11
Range: bytes=0-
...
http debug: incoming response:
HTTP/1.0 200 OK
Server: Icecast 2.4.4
Connection: Close
Date: Wed, 09 Dec 2020 08:16:15 GMT
Content-Type: application/ogg
Cache-Control: no-cache, no-store
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Pragma: no-cache
Access-Control-Allow-Origin: *
ice-audio-info: channels=2;quality=0.3;samplerate=44100
icy-description:Private music stream for use of authorized personnel
icy-genre:varies
icy-name:JetCafeStudios.ogg
icy-pub:1
```

As you can see, almost all of those headers listen in the document you posted are there. The only thing missing is `icy-url` but as you can see the first GET doesn't include `Icy-Metadata: 1`. 

Further down however, to confuse the issue even more, there is this:

```
http debug: http: server='205.147.26.14' port=8001 file='/JetCafeStudios.ogg'
main debug: net: connecting to 205.147.26.14 port 8001
main debug: connection succeeded (socket = 29)
http debug: sending request:
GET /JetCafeStudios.ogg HTTP/1.0
Host: 205.147.26.14:8001
User-Agent: VLC/3.0.11 LibVLC/3.0.11
Icy-MetaData: 1

http debug: HTTP answer code 200
http debug: Server: Icecast 2.4.4
http debug: Content-Type: application/ogg
http debug: Meta-Info: ice-audio-info: channels=2;quality=0.3;samplerate=44100
http debug: Meta-Info: icy-description: Private music stream for use of authorized personnel
http debug: Icy-Genre: varies
http debug: Icy-Name: JetCafeStudios.ogg
http debug: Meta-Info: icy-pub: 1
http debug: auto re-connect enabled
main debug: using access module "http"
```
This also does not contain `icy-url` and it mis-sends `icy-pub` which I have off in icecast.  So continuing after some more (the entire log file is on the VLC issue page):

```
main debug: processing request item: The Neville Brothers - Fallin' Rain, node: Playlist, skip: 0
main debug: resyncing on The Neville Brothers - Fallin' Rain
main debug: The Neville Brothers - Fallin' Rain is at 0
main debug: starting playback of new item
main debug: resyncing on The Neville Brothers - Fallin' Rain
main debug: The Neville Brothers - Fallin' Rain is at 0
main debug: creating new input thread
main debug: Creating an input for 'The Neville Brothers - Fallin' Rain'
qt debug: IM: Deleting the input
main debug: requesting art for new input thread
main debug: using timeshift granularity of 50 MiB
main debug: using default timeshift path
main debug: `http://205.147.26.14:8001/JetCafeStudios.ogg' gives access `http' demux `any' path `205.147.26.14:8001/JetCafeStudios.ogg'
main debug: looking for meta fetcher module matching "any": 1 candidates
main debug: creating demux: access='http' demux='any' location='205.147.26.14:8001/JetCafeStudios.ogg' file='(null)'
lua debug: Trying Lua scripts in /home/dave/.local/share/vlc/lua/meta/fetcher
main debug: looking for access_demux module matching "http": 14 candidates
lua debug: Trying Lua scripts in /usr/local/lib/vlc/lua/meta/fetcher
main debug: no access_demux modules matched
lua debug: Trying Lua scripts in /usr/local/share/vlc/lua/meta/fetcher
main debug: creating access: http://205.147.26.14:8001/JetCafeStudios.ogg
main debug: no meta fetcher modules matched
```

So there is some metadata somewhere. I have no idea how it got "request item" there.  There would appear to be an lua script somewhere but goodness knows where that is. 

I hope this helps. If you find any player that can see the metadata of this stream other than VLC, I'd love to see it. I'm going to try a few soon.

**Comment by davehayes** [comment]
Ok so more data. I installed (https://www.musicpd.org/)[MusicPlayer] which is comparatively simpler of a player. After writing a quick program to connect to it's socket, I was able to get it to display the metadata of this stream. So I got curious as to exactly what was being sent, and loaded up wireshark to watch the network packets. I captured this dump during the stream:

```
0070   6f 72 62 69 73 35 00 00 00 58 69 70 68 2e 4f 72   orbis5...Xiph.Or
0080   67 20 6c 69 62 56 6f 72 62 69 73 20 49 20 32 30   g libVorbis I 20
0090   31 38 30 33 31 36 20 28 4e 6f 77 20 31 30 30 25   180316 (Now 100%
00a0   20 66 65 77 65 72 20 73 68 65 6c 6c 73 29 02 00    fewer shells)..
00b0   00 00 29 00 00 00 74 69 74 6c 65 3d 50 61 74 20   ..)...title=Pat 
00c0   4d 65 74 68 65 6e 79 20 2d 20 46 69 6e 64 69 6e   Metheny - Findin
00d0   67 20 61 6e 64 20 42 65 6c 69 65 76 69 6e 67 14   g and Believing.
00e0   00 00 00 73 65 72 76 65 72 3d 49 63 65 63 61 73   ...server=Icecas
00f0   74 20 32 2e 34 2e 34 01 05 76 6f 72 62 69 73 25   t 2.4.4..vorbis%
0100   42 43 56 01 00 40 00 00 24 73 18 2a 46 a5 73 16   BCV..@..$s.*F.s.
```

This is indeed sending metadata first of all. However, it sends "title=" in the stream. This already does not match the document you posted, I believe that is expecting "StreamTitle". 

Next, I looked at the start of the stream. The `Icy-Metadata` header is in fact being sent by the client:

```
    GET /JetCafeStudios.ogg HTTP/1.1\r\n
    Host: 205.147.26.14:8001\r\n
    User-Agent: Music Player Daemon 0.21.26\r\n
    Accept: */*\r\n
    Icy-Metadata: 1\r\n
    \r\n
```

but the response is this:

```
HTTP/1.0 200 OK
Server: Icecast 2.4.4
Connection: Close
Date: Wed, 16 Dec 2020 20:30:35 GMT
Content-Type: application/ogg
Cache-Control: no-cache, no-store
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Pragma: no-cache
Access-Control-Allow-Origin: *
ice-audio-info: channels=2;quality=0.3;samplerate=44100
icy-description:Private music stream for use of authorized personnel
icy-genre:varies
icy-name:JetCafeStudios.ogg
icy-pub:1
```

In the VLC issue, they mention that they are expecting these headers:

```
libvlc stream: Icy-Name: Smooth Jazz CD101.9 New York
libvlc stream: Icy-MetaInt: 16000
libvlc stream: ICY metaint=16000
libvlc stream: New Icy-Title=Rhythm Jets  - Christmas Song 
```

I checked my icecast stream configuration and I do have the requested configuration items set:

```
<mount type="JetCafeStudios.ogg">
      <stream-name>JetCafe Studios</stream-name>
      <mp3-metadata-interval>16000</mp3-metadata-interval> 
      <relay-shoutcast-metadata>1</relay-shoutcast-metadata>
</mount>
```

but maybe those don't apply because liquidsoap is sending them?

**Comment by toots** [comment]
Hi! Streams using the ogg container use a different method for sending metadata. Because the ogg container has native support for metadata, they are sent using it. The ICY method is a ad-hoc method that is used only for format that do not natively support metadata, such as mp3 and aac.

As you have already shown, these metadata are indeed present in the stream. So, this might be a client bug w.r.t ogg metadata passed in icecast streams. You could try to play the dump you did with different media players and see which ones do report those metadata.

**Comment by davehayes** [comment]
https://trac.videolan.org/vlc/ticket/21057

This is indeed a VLC specific bug and not a liquidsoap one. However, for googlers who reach this issue, is there an option to use the native ogg metadata vs the icy-specifc ones? Failing that, would your recommendation be to use an AAC stream and icy-metadata?
