### ISSUE TITLE
Is it possible to chain conditionals

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1440]
I've been trying to do something like this

```
if x == true and y == false or z == true then
  print("condition met")
end
```
I've also tried
```
if (x == true and y == false) or z == true then
  print("condition met")
end
```
but neither seem to give the desired results

Any advice would be helpful.

Thanks

**Comment by gilou** [comment]
Hi, if they are actual booleans, you don't need the equal signs, and here, it works…

```
x = true
y = false
z = true

if (x and not y) or z then
  print("condition met")
end
```
This works as expected to me?

**Comment by Russsgithub** [comment]
Thanks for the response  Gilles, I'll rewrite my variables and give it ago.

**Comment by smimram** [comment]
Looks like gilou answered this, feel free to reopen if it's not the case.
