### ISSUE TITLE
is it possible not to wait for the end of playback to reload the playlist?

### ISSUE THREAD

**Issue by Sebasti3n** [savonet/liquidsoap#1441]
Script :
```
# Musique (list  music)
playlistok = playlist(mode="normal",reload=1,reload_mode="watch","dance.pls")
```
the normal reload mode waits for the end of the current title. Is it possible to cut a title and reload the playlist without waiting?

**Comment by gilou** [comment]
Have you tried the conservative parameter ? (I'm not sure it does that, but if something does, that would be it…)

Otherwise I'd say you'll need to have a sort of container handling that situation…
