### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by paddatrapper** [savonet/liquidsoap#1444]
**Is your feature request related to a problem? Please describe.**
It is difficult to assess the impact of a version bump in dependencies when any version could break functionality. For example, liquidsoap 1.4 caused https://github.com/LibreTime/libretime/issues/1136

**Describe the solution you'd like**
Semantic versioning provides implied meaning to each part of the version MAJOR.MINOR.BUG. Releases that break existing interfaces get a MAJOR version bump, while new features get a MINOR version bump. Bug fixes bump the BUG number. Using semantic versioning would give people a fast way to determine if a release is safe to deploy for testing or if more investigation is required. More information can be found here - https://semver.org/

**Comment by toots** [comment]
Hi. Sorry about the issues that you encountered. As explained in my comment here: https://github.com/LibreTime/libretime/issues/1136#issuecomment-749019118 we do indeed focus on not introducing non-breaking changes during a release lifecycle, e.g. `1.4.x`. We also take care of properly documenting any change that are introduced in each release, wether `New`, `Changed` or `Fixed`.

Semver seems to have evolved in the last years were most people consider carret versioning to be standard, i.e. `1.4.x` is considered safe to upgrade and breaking changes can happen in `1.5.x`. We use the major number for tracking our own major paradigm changes. For instance, liquidsoap 2, which we are currently working, will come with a total change of paradigm.

Lastly, I recommend to consult any changelog before updating and to test your script before updating to a new version in production.

Thanks for your interest in liquidsoap! I don't know if you have seen it but we're holding an online workshop on Jan. 17th: http://www.liquidsoap.info/liquidshop/ Feel free to attend so we can discuss these matters further..
