### ISSUE TITLE
Request leak from playlist(watch) when downloading a file to watched folder

### ISSUE THREAD

**Issue by martinkirch** [savonet/liquidsoap#1451]
I'm using `playlist(reload_mode="watch"` to play files from a folder. When downloading a file in that folder (while liquidsoap is running) log gets filled with messages like
```
[request:2] There are currently 300 RIDs, possible request leak! Please check that you don't have a loop on empty/unavailable requests, or creating requests without destroying them. Decreasing request.grace_time can also help
```

**To Reproduce**
Copy this script
```
source = playlist(reload_mode="watch", mode="normal", "tmp/")
output.prefered(mksafe(source))
```
 * put just one file in `tmp/` subfolder
 * start `liquidsoap script.liq`
 * download another file in `tmp/`

**Version details**
 - Liquidsoap 1.4.3 built with opam
 - Fedora33 (also happened under Ubuntu)

**Comment by martinkirch** [comment]
If that can help : after switching to `reload=60` (it will do the job for now) I'm still observing a leak from a folder where there's a mono file. The log repeats :
```
...
2020/12/29 22:24:25 [request:2] There are currently 300 RIDs, possible request leak! Please check that you don't have a loop on empty/unavailable requests, or creating requests without destroying them. Decreasing request.grace_time can also help.
2020/12/29 22:24:25 [decoder.mad:3] File "....mp3" has an incompatible number of channels.
2020/12/29 22:24:25 [decoder:3] Unable to decode "....mp3" as {audio=2;video=0;midi=0}!
...
```

the test script in my first post still have the issue with a stereo file.

**Comment by gilou** [comment]
Yeah, that's because of how it watches things… It'd be nice to have something working on liq there, but what I do in the end is separate partial  files  and uploads from actual liq stream playlist sources…

**Comment by toots** [comment]
Yeah, I believe that currently we will keep trying to resolve the file if there's a single file that's not valid. I don't think that this is something that we want to address for `1.4.4`. I'd recommend for now to make sure that your playlist has at least one valid file. Also, you should use `audio_to_stereo` to make sure that liquidsoap implicitly converts audio channels, which should make your file work here.

These two issues will be addressed in `2.0.0`

**Comment by martinkirch** [comment]
So it's 2 different issues; indeed the second one is avoided by `audio_to_stereo`.

But the first one still happens if there's already one valid file in `tmp/` and I download an album while playling. It looks like inotify over-notifying... so I checked out v1.4.3, grepped `inotify`, removed [this line](https://github.com/savonet/liquidsoap/blob/master/src/tools/file_watcher_inotify.ml#L54), compiled... and it's fixed !

Or, not really: disabling `Inotify.S_Modify` would break `reload_mode="watch"` if the playlist is a file. Maybe `Inotify.S_Modify` could be excluded if the playlist is a folder ?

**Comment by toots** [comment]
Hey! Yeah, it looks like `IN_MODIFY` is defined for files: 
> IN_MODIFY (+)
>  File was modified (e.g., write(2), truncate(2)).

Thanks for investigating, I'll push a fix right away!
