### ISSUE TITLE
Using with gstreamer to stream to nginx, liquidsoap fill up memory and crash.

### ISSUE THREAD

**Issue by lonerunner** [savonet/liquidsoap#1456]
Hi so as i say in title i am trying to use liquidsoap with gstreamer to stream dynamic playlist to rtmp server with nginx. Maybe this sound confusing, sorry english is not my native language. 

Anyway everything works fine except after a while liquidsoap fill up all memory and swap of the server and crash without anything posted in log file.

The server have 16GB ram so it takes about 20hrs for liquidsoap to reach 30gb in size and crash. 

I am using this as an example to stream.

```
#!/usr/bin/liquidsoap
set("frame.video.width", 1280)
set("frame.video.height", 720)
set("frame.video.samplerate", 25)
set("gstreamer.add_borders", true)

s = playlist.safe(mode="normal",reload=1,reload_mode="watch","/opt/playlist.m3u")

s = fallback([s, blank()])

s = video.add_image(
       width=150,height=58,
       x=10,y=10,
       file="/opt/logo.png",
       s)

  output.gstreamer.audio_video(
  video_pipeline=
    "videoconvert ! x264enc bitrate=2000 ! video/x-h264,profile=baseline ! queue ! mux.",
  audio_pipeline=
    "audioconvert ! voaacenc bitrate=128000 ! queue ! mux.",
  pipeline=
    "flvmux name=mux ! rtmpsink location=\"rtmp://192.168.1.1:1935/live/stream live=1\"",
  s)
```

Any ideas how is this happening and if i can somehow find a way to clean up memory usage after a while without having to restart the liquidsoap and stream? I guess even if i had 60gb ram on server, liquidsoap will fill that and crash eventually. Is this an old buffered videos in the file size?

**Comment by gilou** [comment]
This looks like a bug, I can't reproduce it though, but maybe you can check if it's really liq that's filling up the memory? Maybe valgrind could help spotting the issue also, but it might not be too easy to use in that setup…

**Comment by lonerunner** [comment]
I can provide any log if necessary but in liquid logs nothing is shown. It could be liquidsoap or gstreamer or even debian that have bug? I was looking at the `top` command and definitely liquidsoap service take over whole ram and crash. I will look at the walgrind and see what i can do with it.

If it's worth something:
`liquidsoap 1.3.3`
`debian 10 buster`
`gstreamer 1.14.4-2`
strangely it say `gstreamer libav version 1.15.0.1`

**Comment by lonerunner** [comment]
Ok so i tested this with multiple VPS instances, Debian 9, Debian 10, Ubuntu 20.04. And each of them have different version installation of both gstreamer and liquidsoap, i also used opam to install and i had quite some issues to set it up on one of testing VPS.

And on every installation liquidsoap fill up memory and crash.

I tried valgrind but for me this is something i don't understand at all about memory leaks.

When using to stream only single file instead of playlist with liquidsoap it acts the same.

I tried to use gstreamer directly with this command:

`
gst-launch-1.0 multifilesrc location="/opt/videos/Over.The.Moon.2020.mp4" ! \
    qtdemux name=demux \
    demux.video_0 ! queue ! \
    decodebin ! videoconvert ! x264enc bitrate=1000 tune=zerolatency ! video/x-h264 ! h264parse ! \
    video/x-h264 ! queue ! flvmux name=mux ! \
    rtmpsink location="rtmp://10.1.1.1:1935/live/stream live=1" \
    demux.audio_0 ! queue ! decodebin ! audioconvert ! audioresample ! \
    audio/x-raw,rate=48000 ! \
    voaacenc bitrate=96000 ! audio/mpeg ! aacparse ! audio/mpeg, mpegversion=4 ! mux.
`

And i did take on purpose a large file like movie so no memory increase with gstreamer.

Then i used the same large movie file to stream over liquidsoap and the whole time during the movie, liquidsoap didn't have any memory increase.

So the memory increase is happening when i try to stream multiple files and it's increasing memory when switching between videos.

So if i take 10 short mtv video spots, each time when new video is loaded, liquidsoap take up more memory.

**Comment by toots** [comment]
Hi! sorry to hear about all that. Gstreamer support is being progressively deprecated in favor of out `ffmpeg` internal support. Also, video support will come in full force with the new stable release.

We're very close to having a first `alpha` of the current `main` branch. Perhaps you would like to be an early tester? We would definitely follow-up and help fix any issue.
