### ISSUE TITLE
Adding methods to an integer is not properly parsed

### ISSUE THREAD

**Issue by dbaelde** [savonet/liquidsoap#1460]
**Describe the bug**
The expression `3.{a="bla"}` from the tutorial is not parsed correctly: `3.` is parsed as a float.

**Version details**
 - OS: Ubuntu
 - Version : latest git

**Comment by smimram** [comment]
Note that if we add a space then the expression is lexed correctly:
```
# 3.{a="bla"} ;;
At line 1, char 0-2:
Warning 3: This expression should have type unit.
- : {a : string} = {a = "bla"}
# 3 .{a="bla"} ;;
- : int.{a : string} = 3.{a = "bla"}
```
We could add some pre-processing to handle this case (this is difficult to properly correct because it would require some lookahead in the lexer, and I don't feel going there just for this...)

**Comment by smimram** [comment]
I vaguely remember fixing this in fbf4d71171fb4e8ade8d4293232bf440d708c68d:
```
# 3.{a="bla"};;
- : int.{a : string} = 3.{a = "bla"}
```
