### ISSUE TITLE
HELP NEEDED

### ISSUE THREAD

**Issue by MayhemRadio** [savonet/liquidsoap#1464]
Hello! I am trying to write a source.skip command for my station. Right now the issue is that the auto dj will be playing a song, then a live source will take over, but as soon as the live source disconnects, the song the auto dj was playing, starts where it left off. This is a big issue because it doesn't sound clean. I would like it to play something from my imaging playlist, then transition back into the playlists. I am very new to this sort of stuff and have been trying to do as much research as possible. Could anyone help a boy out? 

This is what I have to so far from the research I've done....

```
needs_reload = ref false

def transition(old,new) =
  if source.id(old) == "playlist_pop,playlist_rap_hip_hop,playlist_rock_and_roll,playlist_imaging,playlist_electronic,playlist_alternative_" then
    needs_reload := true
    source.skip(old)
  end

  sequence([old,new])
end

radio = crossfade(smart=true, duration=3.,fade_out=2.,fade_in=2.,radio)

radio = fallback(id="mayhemradio_safe_fallback", track_sensitive = false, [radio, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])
```

I would like it to target the playist_imaging when the source needs to be skipped

**Comment by dtcooper** [comment]
Have you tried calling `source.skip(...)` in your transition function, I've got a (somewhat complex) [example here](https://github.com/dtcooper/crazyarms/blob/80ee52f4/app/app/services/templates/services/harbor.liq#L424-L431) (using jinja2 so ignore the `{% ... %}` and `{{ ... }}`)

**Comment by martinkirch** [comment]
Hello,
I had the same issue, and solved it with this transition operator
```
def crossfade_3s(a,b)
    faded = add(normalize=false, [
        fade.in(duration=3., type="exp", b),
        amplify(mkfade(duration=3., start=1., stop=0., type="exp", a) ,a)
    ])
    add_timeout(10., { source.skip(a) ; -1.})
    faded
end

radio = fallback([live_source, music_source],
  transitions=[crossfade_3s, crossfade_3s],
  track_sensitive=false)
```

I'm using `amplify(mkfade(...` instead of `fade.out`, because `fade.out` triggers itself by detecting the end of track : usually the transition happens during a track, so it wouldn't fade at all.

I don't know why, but calling only `source.skip(a) ` before returning doesn't work :  hence the `add_timeout`, which triggers `source.skip(a)` after the fade.

**Comment by smimram** [comment]
Solutions have been provided, closing the issue, feel free to reopen if more is needed.
