### ISSUE TITLE
Metadata not sending on output.icecast live stream

### ISSUE THREAD

**Issue by imperialpixel** [savonet/liquidsoap#1469]
I have the following as my liquidsoap script to stream live audio input. The audio streams just fine, but the metadata never ever works... unless I'm streaming am mp3 file or whatever that has the tags already defined.  I'm not sure what I could be missing here to make manually setting the meta data work. Tons of internet searches have left me with no resort but to reach out to directly.

```
liquidsoap '
	
	set("frame.audio.size",'$HARDWARE_AUDIO_FRAME_SIZE'); 
	
	stream_master_source = output.icecast(
		%mp3(bitrate=192,samplerate=44100),
		host="'$TESTING_HOST'",
		port='$TESTING_PORT',
		user="'$TESTING_USER'",
		password="'$TESTING_PASSWORD'",
		mount="'$TESTING_MOUNT'",
		icy_metadata="true",
		id="metadata testing (id)",
		description="metadata testing (description)",
		genre="metadata testing (genre)",
		input.alsa(bufferize = true),
	)
	stream_master_source

'
```

Using the script above, when I check the server's mount overview as I am connected and hearing audio, the meta data that is listed doesn't reflect what I'm trying to send in the script (it instead shows whatever the previously streamed metadata was). 

Thoughts?

Thanks in advance.

**Comment by toots** [comment]
Hi! Alsa input gets its data from soundcard, which is pure audio with no metadata so I would not expect any to be sent to the icecast server with such source?

**Comment by imperialpixel** [comment]
Hi there toots, thanks for the reply.

1. But what then becomes of parameters like _description_ and _genre_ in in _output.icecast_ if audio from alsa somehow disregards metadata transmits? Or...
2. Maybe I'm confusing _description_ and _genre_ as being metadata when in fact they aren't. Am I?
3. Is it possible to just send a metadata update request to the server using liquidsoap? If so, how is that done?


Many thanks,


-- M

**Comment by toots** [comment]
Hi!

Yes, `genre` and `description` are _static_ info, set when connecting and never updated..

To update metadata on the fly, you have several options:
* Insert metadata at the source level using `insert_metadata`: https://www.liquidsoap.info/doc-1.4.3/reference.html#insert_metadata
* Send metadata directly to the icecast server using `icy.update_metadata`. This only works for formats using the ICY metadata protocol, i.e. `mp3` and `aac`. It works for `vorbis` but that's a one off, I don't think it'll work for other `ogg` contained formats.

**Comment by imperialpixel** [comment]
Hi Toots, 

It's now many months later, we keep circling back and bashing our heads against the wall to this, but we can't figure it out. 

Please, is there any way at all that you can give us some kind of basic example of "insert_metadata" usage? We can't find any examples online of just a basic metadata update in action to help us understand the documentation.

On the source level using "insert_metadata"...
If I wanted to change the meta of a stream ("main_broadcast_stream" - an mp3 encoded live stream, hence the need to update meta) to: 

    Artist "Lee Scratch Perry", 
    Song "Disco Devil" 
    
How exactly would you do that?

HUGE Thanks!
