### ISSUE TITLE
on_blank script 

### ISSUE THREAD

**Issue by CharlesOnAir** [savonet/liquidsoap#1473]
Hello,

I would like to run a Python script when triggering the rescue file.

Here is my code

But the script is not taken into account

def handler()
                    system("../var/www/html/secoursfiles/TestSecours.py")
                end
                
                stream = fallback(track_sensitive=false, [ strip_blank(max_blank=5.,flux) , security ])

                stream = on_blank(handler,stream)

**Comment by toots** [comment]
Duplicate of #1474
