### ISSUE TITLE
Running on Raspbian via supervisor : "Fatal error: exception Not_found"

### ISSUE THREAD

**Issue by YoannQueret** [savonet/liquidsoap#1479]
Hi

I try to run liquidsoap (package liquidsoap v1.3.3-2) via supervisor on a raspberry4 with raspbian 10.7.

```
[program:liq-test]
command=/usr/bin/liquidsoap /home/pi/test.liq
directory=/home/pi/
autostart=true
autorestart=true
priority=10
user=pi
group=pi
redirect_stderr=true
stdout_logfile=/var/log/supervisor/test.log
```

If i run manually the command /usr/bin/liquidsoap /home/pi/test.liq everything work fine.
If i run the same via supervisor i have "Fatal error: exception Not_found" output in log file.

I tried to run a simple liquidsoap --version and I got the same error in the logs when running via supervisor.

Do you have any idea where to look? The error message is really not explicit
Maybe I need to specify things in the environment?

I don't have this problem with liquidsoap 1.4.3 installed via opam.

In advance, thank you for your contributions, it will surely help me.

Yoann

**Comment by toots** [comment]
Hi! Does the supervisor restrict access to system resources like environment variables or file system?

Also, it might be worth noting that `1.3.3` is pretty old at this point. Latest release is `1.4.3` with `1.4.4` coming up hopefully soon.

**Comment by smimram** [comment]
Old version and no answer, closing the issue, feel free to reopen!

**Comment by hme12** [comment]
I installed liquidsoap using opam and it is version 2.0.2.
I had the same problem. I found out that the variable
$HOME must be set to the directory where the .opam
directory lies.

In my case it is /home/pi/.opam.
So I set HOME=/home/pi.

regards

Herbert
