### ISSUE TITLE
Logrotate issue, nothing is logged after logrotate is done

### ISSUE THREAD

**Issue by alvassin** [savonet/liquidsoap#148]
I discovered that after logrotate performs its work - liquidsoap does not write any logs any more (log files exists, but with 0 bytes).

After i run my liq script, it creates logfile with 0600 mode with correct user.
After logrotate work is done, permissons are same, file owner is same too. 

What can be a problem? (I am using git source build, running on debian wheezy)

**Comment by Matzeee** [comment]
@toots 

I just noticed the same.
It only works by adding `copytruncate` to my `/etc/logrotate.d/liquidsoap.conf`
For quick testing:
```
/var/log/liquidsoap/test-liquidsoap.log {
create 0644 liquidsoap liquidsoap
rotate 1
size 1k
copytruncate
}
```

Changing permissions from `0600` to `0644` before starting liquidsoap does not stop it from logging.

`/var/liquidsoap/test.liq`
```
log.file := true
log.file.path := "/var/log/liquidsoap/test-liquidsoap.log"

settings.log.level := 4

settings.frame.audio.samplerate := 48000

sine = sine(440.)

mp3_low  = %mp3.vbr(stereo_mode='joint_stereo', samplerate=16000, internal_quality=6, id3v2=true, quality=7)


opus_logging = %opus(samplerate=48000, channels=2,
                #vbr="unconstrained", bitrate="auto",
                vbr="constrained", bitrate=64,
                complexity = 10,
                dtx = true)

output.file(
        mp3_low,
        {time.string("/var/fm-loggings/test/%Y-%m-%d_%H-%M-%S-test.mp3")},
        sine,
        reopen_when={0m}, fallible=true)


output.file(
        opus_logging,
        {time.string("/var/fm-loggings/test/%Y-%m-%d_%H-%M-%S-test.opus")},
        sine,
        reopen_when={0m}, fallible=true)

```
```
 liquidsoap --version
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
Liquidsoap 2.2.1
```

**Comment by vitoyucepi** [comment]
Hi @Matzeee,
Would you mind starting a new discussion or an issue?
