### ISSUE TITLE
unable to decode stream of type "application/vnd.apple.mpegurl"!

### ISSUE THREAD

**Issue by jonahzheng** [savonet/liquidsoap#1485]
code
url = "https://www.aa.com/master.m3u8"
mksafe(input.https(url))

unable to decode stream of type "application/vnd.apple.mpegurl"!

**Comment by toots** [comment]
Hi! HLS input is not currently supported for `input.http`. This operator is mostly intended for icecast streams and could probably be renamed. With `1.4.3` (or the coming `1.4.4`, I'd suggest to use `input.external.ffmpeg` as the native `input.hls` is not stable enough.
