### ISSUE TITLE
Needhelp: How to reconnect after 10 seconds (output.icecast)

### ISSUE THREAD

**Issue by coldfire99** [savonet/liquidsoap#1486]
Hello,

I have a problem with the host dropping streams.
The default for a liquidsoap reconnect retry seems to be 600 seconds.
How can I change this default to e.g. 10 seconds?
```
output.icecast(%mp3(samplerate=44100, bitrate=256, internal_quality=0),fallible=true,on_error=fun(_)->600.,
  host = "aaaa.bbbbb.cccc", port = 8080,
  password = "zzzzzzzz", mount = "yyyyyyyyy", liveradio)
```
Here is the log:
```
2021/01/30 22:39:03 [yyyyyyyyyy:2] Error while sending data: could not write data to host: connection timeout!
2021/01/30 22:39:03 [yyyyyyyyyy:3] Closing connection...
2021/01/30 22:39:03 [yyyyyyyyyy:3] Will try to reconnect in 600.00 seconds.
```
How can I change this  reconnect timer to e.g. 10 seconds?

Br

Chris

**Comment by martinkirch** [comment]
Hello,
I think it comes from `on_error=fun(_)->600.` ; try changing `600.` to `10.` ; or remove it entirely, the default is to retry 3 seconds later.

**Comment by coldfire99** [comment]
Hi, thanks a lot for this hint. I will test this.

**Comment by smimram** [comment]
I think that the correct answer was given by @martinkirch, closing. Feel free to reopen if you have more issues.
