### ISSUE TITLE
HLS Ouput with Metadata?

### ISSUE THREAD

**Issue by chrecht** [savonet/liquidsoap#1487]
Hello,

maybe it's a silly question.. but has liquidsoap Metadata injection for AAC HTTP Livestreaming Output ?
If so, how ? I've tried to find a workaround by using on_file_change and using ffmpeg to add id3 tag but this breaks my Transport Stream :/ 

Thank you for you help,
 Christian

**Comment by dhannyz** [comment]
I've been asking this question, or a related one for a while.
I would love to know how to do this, or to have this feature added to liquidsoap.
Really would be a bit of a game-changer

**Comment by toots** [comment]
I'd love to consider adding it but do y'all know the specs/how it's supposed to be done?

**Comment by dfarrowUnity** [comment]
This would be an amazing feature. The documents are here: https://www.w3.org/TR/media-timed-events/  and https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/Introduction/Introduction.html

**Comment by toots** [comment]
This is fixed now! Will come out with `rolling-release-v2.2.x`!
