### ISSUE TITLE
Can't interact via socket or telnet

### ISSUE THREAD

**Issue by ononos** [savonet/liquidsoap#149]
I can't interact with server. As I know "help" must return list of commands or "var.get volume" from my liq file must return value. I was try telnet and socat. Commit c4c19d5f.
My .liq file:

<pre>
set("log.stdout",true)
set("log.level",4)
set("server.telnet",true)
set("server.telnet.port",  2424)

set("server.socket",true)
set("server.socket.path", "/home/userhere/Work/radio/liquidsoap")

radio =  mksafe(input.http("http://gyusyabu.ddo.jp:8000/"))

v = interactive.float("volume", 1.)
radio = amplify(v, radio)

output.icecast(
    %mp3(
        bitrate = 192, samplerate = 44100),
    host = "localhost", port = 7777,
    password = "passwordf", mount = "/radio",
    description = "Test stream", radio)
</pre>

Stdout output: when first connect:

<pre>
2014/01/25 03:05:06 [server:3] New client unix socket "".
Thread 2 killed on uncaught exception Invalid_argument("equal: abstract value")
Called from file "list.ml", line 175, characters 17-20
Called from file "thread.ml", line 39, characters 8-14
</pre>

**Comment by dbaelde** [comment]
Any news on this? It seemed serious, so I mark it as RC: I'd like to at least understand what I could observe, i.e. the funny "na\xxx\xxx" unix client socket name.

**Comment by toots** [comment]
Hi,

Unfortunately, this issue is so old that I don't think we'll ever be able to reproduce/fix it in the current codebase. Closing now, feel free to submit or reopen if it still applies to the latest code.
