### ISSUE TITLE
Compatibility Issues with RocketStreamingAudioServer.

### ISSUE THREAD

**Issue by fourofspades** [savonet/liquidsoap#1498]
**Describe the bug**
Getting frequent disconnects and reconnects when talking to a RocketStreamingAudioServer.  This didn't occur with IceCast.

**To Reproduce**
```
#!/usr/bin/liquidsoap
myradio=mksafe(normalize(playlist("/music/FLACplaylist.m3u",mode="randomize",reload=1,reload_mode="rounds")))
set("init.allow_root",true)

#OUTPUT HIGH BITRATE
output.icecast(%fdkaac(channels=2, samplerate=44100, bitrate=192, afterburner=false, aot="mpeg4_aac_lc", transmux="adts", sbr_mode=false),
host="127.0.0.1",
port=8000,
password="password",
description="Desc",
url="http://myurl/high",
public=false,
genre="Rock",
mount="high",
myradio )

#OUTPUT LOW BITRATE
output.icecast(%fdkaac(channels=2, samplerate=44100, bitrate=64, afterburner=false, aot="mpeg4_aac_lc", transmux="adts", sbr_mode=false),
host="127.0.0.1",
port=8000,
password="password",
description="Desc",
url="http://myurl/low",
public=false,
genre="Rock",
mount="low",
myradio )

```
**Expected behavior**
not drop out.

**Version details**
Synology DSM/Docker
LiquidSoap and RSAS running in same container (occurs in separate containers also)

**Log**

`
2021/02/17 22:46:55 [FLACplaylist(dot)m3u:3] Prepared "/music/./Tom Petty - Runnin' Down A Dream.flac" (RID 0).
2021/02/17 22:47:25 [low:3] Metadata update may have failed with error: Cry__Cry_common.Timeout
2021/02/17 22:47:25 [high:3] Metadata update may have failed with error: 404, Not Found (HTTP/1.0)
2021/02/17 22:47:25 [clock.wallclock_main:2] We must catchup 29.99 seconds!
2021/02/17 22:47:25 [high:2] Error while sending data: could not write data to host: Broken pipe in write()!
2021/02/17 22:47:25 [high:3] Closing connection...
2021/02/17 22:47:25 [high:3] Will try to reconnect in 3.00 seconds.
2021/02/17 22:47:25 [low:2] Error while sending data: could not write data to host: Broken pipe in write()!
2021/02/17 22:47:25 [low:3] Closing connection...
2021/02/17 22:47:25 [low:3] Will try to reconnect in 3.00 seconds.
2021/02/17 22:47:29 [low:3] Connecting mount low for source@127.0.0.1...
2021/02/17 22:47:29 [low:3] Connection setup was successful.
2021/02/17 22:47:29 [high:3] Connecting mount high for source@127.0.0.1...
2021/02/17 22:47:29 [high:3] Connection setup was successful.
2021/02/17 22:51:27 [decoder:3] Method "FLAC" accepted "/music/./Deep Purple - Speed King  (1995 Remaster).flac".

`

**Comment by toots** [comment]
Hi! Is that an icecast-compatible implementation? What version of liquidsoap are you using? Thks!

**Comment by fourofspades** [comment]
Liquidsoap 1.43 with rocketaudio sever 1.7 and icecast compatible implementation.
