### ISSUE TITLE
Typing of audio effects

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1505]
The current type of `amplify` is (roughly)

```
({float}, source(audio='a, video='b, midi='c)) -> source(audio='a, video='b, midi='c)
```

Since it only operates on raw data, shouldn't we have

```
({float}, source(audio=pcm('a), video='b, midi='c)) -> source(audio=pcm('a), video='b, midi='c)
```

instead?

If this is the case, we should start reviewing the type for most audio and video effects similarly.

Edit: acutally, I think that the above type is imprecise since it makes thinks look like we can generate encoded video, so that we should further constrain `'b` and `'c` to be internal types

**Comment by smimram** [comment]
PS: it seems that this script validates my theory:
```
s = playlist(loop=false, "~/Music")
s = amplify(3., s)
output.file(fallible=true, %ffmpeg(format="mp3", %audio.copy), "/tmp/out.mp3", s)
```
results in a crash:
```
2021/02/21 19:28:02 [clock.main:2] Source /tmp/out(dot)mp3 failed while streaming: Frame_content.Invalid!
```

**Comment by toots** [comment]
I switched to `audio_pcm`. As for video and midi, I believe they are passed untouched so the type is indeed correct. However, this is part of the greater conversation that I would like to have regarding type specifications.
