### ISSUE TITLE
Source live(dot)m3u8 failed while streaming: File "stream/frame.ml", line 549, characters 2-8: Assertion failed!

### ISSUE THREAD

**Issue by jonahzheng** [savonet/liquidsoap#1509]
**Describe the bug**
liquidsoap /opt/liquidsoap/rum.liq --daemon

After a few days of operation, liquidsoap will suddenly and abnormally shut down.

**To Reproduce**
2021/02/21 02:01:55 [https_9394:3] New metadata chunk: ? -- ?.
2021/02/21 02:01:57 [mksafe:3] Switch to safe_blank with forgetful transition.
2021/02/21 02:01:57 [https_9394:3] New metadata chunk: ? -- ?.
2021/02/21 02:01:59 [mksafe:3] Switch to https_9394 with transition.
2021/02/21 02:02:00 [https_9394:3] New metadata chunk: ? -- ?.
2021/02/21 02:02:02 [https_9394:3] New metadata chunk: ? -- ?.
2021/02/21 02:02:04 [https_9394:3] New metadata chunk: ? -- ?.
2021/02/21 02:02:06 [https_9394:3] New metadata chunk: ? -- ?.
2021/02/21 02:02:07 [clock.wallclock_main:2] Source live(dot)m3u8 failed while streaming: File "stream/frame.ml", line 549, characters 2-8: Assertion failed!
2021/02/21 02:02:07 [clock.wallclock_main:3] Raised at file "stream/frame.ml", line 549, characters 2-35
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "stream/frame.ml", line 568, characters 4-28
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "source.ml", line 537, characters 12-36
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "operators/sequence.ml", line 78, characters 8-14
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "source.ml", line 531, characters 10-24
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "operators/switch.ml", line 220, characters 14-19
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "source.ml", line 531, characters 10-24
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 178, characters 10-20
2021/02/21 02:02:07 [clock.wallclock_main:3] Called from file "clock.ml", line 168, characters 14-22
2021/02/21 02:02:07 [clock.wallclock_main:3] Streaming loop stopped.
2021/02/21 02:02:07 [main:3] Shutdown started!
2021/02/21 02:02:07 [main:3] Waiting for main threads to terminate...
2021/02/21 02:02:07 [https_9394:2] Feeding stopped: source stopped
2021/02/21 02:02:07 [main:3] Threads terminated.
2021/02/21 02:02:07 [threads:3] Shutting down scheduler...
2021/02/21 02:02:07 [threads:3] Scheduler shut down.
2021/02/21 02:02:07 [threads:3] Waiting for queue threads to terminate...
2021/02/21 02:02:07 [threads:3] Queues shut down
2021/02/21 02:02:07 [main:3] Cleaning downloaded files...
2021/02/21 02:02:07 [main:3] Freeing memory...

**Expected behavior**

**Version details**
 - ubuntu 20
 - Version 1.4.3

**Comment by toots** [comment]
Thanks for the report. This one looks tricky. I'll see what I can do. The whole buffering layer was completely rewritten in the current `master` branch so we might decide to leave this and focus on making sure it does not happen in liquidsoap `2.0`

**Comment by jonahzheng** [comment]
@toots thank you. the latest abnormally shut down on two week ago. I look forward to liquidsoap 2.0 release.

a few days before I wrote a bash script to monitor the process

> #! /bin/sh
proc_name="liquidsoap /opt/liquidsoap/rum.liq --daemon 
num=$(ps -ef | grep $proc_name | grep -v "grep" | grep -v "sh" |wc -l)
if [ $num -eq 0 ]
then 
    liquidsoap /opt/liquidsoap/rum.liq --daemon
fi

**Comment by smimram** [comment]
This bug is fairly old and 2.0 has ben out for some time now. Out of curiosity, can you confirm that this is fixed in 2.0?
