### ISSUE TITLE
How to read logs form External Input?

### ISSUE THREAD

**Issue by cdgraff** [savonet/liquidsoap#1510]
I need your help to guide me in the right direction

I have this code:
```
rxfm = "rx_fm -f #{public_dial} -d serial=#{device_id} -M fm -s 250000 -w 500000 -o 1 -g 0 -E deemp -E adc -E agc -"
live = input.external.rawaudio(restart_on_error=true,restart=true,channels=1,samplerate=250000,buffer=1.,max=5.,rxfm)
live = mksafe(live)
```

Some time by time, SDR Input fail with that error:
```
2021/02/23 21:45:17 [input.external.rawaudio_9301:4] cb transfer status: 1, canceling...
2021/02/23 21:45:18 [input.external.rawaudio_9301:4] readStream read failed: -1
dongle_thread_fn terminated
2021/02/23 21:45:18 [input.external.rawaudio_9301:4] End of track.
2021/02/23 21:45:18 [input.external.rawaudio_9301:4] Buffer emptied, buffering needed.
2021/02/23 21:45:18 [input.external.rawaudio_9301:5] Not ready: need more buffering (0/44100).
```

Commonly this error:
`dongle_thread_fn terminated`

Means that USB dongle was disconnected, and the only way to re-register is booting the device, for that reason I'm searching a way to identify that **input.external.rawaudio** was down and call the external script that will do the DEVICE Reboot.

I saw into [DEV](https://www.liquidsoap.info/doc-dev/reference.html#input.external.rawaudio) documentation that exist "METHODS", but into [1.4.3 docs](https://www.liquidsoap.info/doc-1.4.3/reference.html#input.external.rawaudio) I don't see them, that is new feature coming into the next release?

Thanks in advance!
Alejandro

**Comment by toots** [comment]
Ok, I see your issue now! 

Indeed, methods have only been introduced with the latest `master`. For the last release (`1.4.3` at the moment), I would recommend using `output.dummy`:

```ruby
live = input.external.rawaudio(...)

def on_shutdown() =
# Add your actions here
end

output.dummy(on_shutdown=on_shutdown, fallible=true, live)

# Rest of your script goes here
```

**Comment by cdgraff** [comment]
Thanks! @toots just I got an error using `on_shutdown`, look is not available into` ouput.dummy`

But I change for `on_stop` and works perfect! 

thanks for take the time to suggest this method!
