### ISSUE TITLE
Function trigger when new track start playing

### ISSUE THREAD

**Issue by quydox** [savonet/liquidsoap#1512]
Dear team,

I am looking for a function trigger when a new track start playing.

I do research and see `on_metadata`, `on_track` can do, but It does early before new track start playing (about 5-10 secs)

How can I trigger exactly the time new track start playing?

Thank you very much!

**Comment by smimram** [comment]
`on_track` is triggered exactly when Liquidsoap detects the track. However, there are various buffers when transmitting streams to clients which explains the lag. There is currently now way to synchronize precisely with the listener.

**Comment by quydox** [comment]
> `on_track` is triggered exactly when Liquidsoap detects the track. However, there are various buffers when transmitting streams to clients which explains the lag. There is currently now way to synchronize precisely with the listener.

Thanks for your reply.

How can I change this time buffer?

**Comment by smimram** [comment]
You cannot, this is done by the client, over who you don't have any control.
