### ISSUE TITLE
static playlist with annotate protocol not delivering custom vars after upgrade to LS4

### ISSUE THREAD

**Issue by unosonic** [savonet/liquidsoap#1515]
**Describe the bug**

after upgrading from LS 1.4.2. to Liquidsoap 1.4.4, the annotate protocol used in a static playlist doesn't work as before, eg. custom variables defined with annotate are no longer available in the metadata.
however, it works in single requests, eg. in request queue.

**To Reproduce**
create playlist test.m3u:

annotate:my_var1="aaa",my_var2="aaaa":/files/test1.mp3
annotate:my_var1="bbb",my_var2="bbbb":/files/test2.mp3
annotate:my_var1="ccc",my_var2="cccc":/files/test3.mp3

reload playlist, eg with telnet localhost 1234
test(dot)m3u.reload

request metadata, mystream defined in liq-script:

mystream.metadata 
...
this should show my_var1 and my_var2 among others, but doesn't.

**Expected behavior**

custom vars should appear in metadata when using annotate protocol in static playlists.

**Version details**
 - OS: debian 10
 - Version Liquidsoap 1.4.4 managed by opam

**Install method**
opam

**Comment by toots** [comment]
Thanks for the report, I'll look a it very shortly.

**Comment by toots** [comment]
I can confirm the regression. I'll push a fix today.

**Comment by toots** [comment]
Fixed, release updated.

**Comment by unosonic** [comment]
please excuse the maybe stupid question, not very used to opam: how do I update my installation with the fixed version? opam clean & reinstall liquidsoap?

**Comment by toots** [comment]
Yes, once this PR is merged: https://github.com/ocaml/opam-repository/pull/18247

**Comment by unosonic** [comment]
reinstall successful, works again as expected.
thanks Romain!
