### ISSUE TITLE
video.crop functionality

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1518]
When setting up video sources, they are all created in liquidsoap's internal video resolution irrespective of desired size.
For example, square album art in a 16:9 video.
Currently aspect ratio of the image is preserved, but fit to a 16:9 base with transparent sides. This can make further sizing and positioning tricky. It currently also causes a bug with transparency and video fading.

**Comment by smimram** [comment]
This should be fixed by #2207 which adds `video.crop` which puts the video in the upper-left corner.
