### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by scresante** [savonet/liquidsoap#1529]
**Describe the bug**
The build instructions at https://github.com/savonet/liquidsoap/blob/main/doc/content/build.html are missing

Without instructions on how to build the project, I'm not sure what are the prerequisites for compiling on Ubuntu.

**To Reproduce**
Visit https://github.com/savonet/liquidsoap/blob/main/doc/content/build.html

**Expected behavior**
See the build instructions.

**Comment by toots** [comment]
Hi,

The build instructions are here: https://www.liquidsoap.info/doc-1.4.4/install.html#latest-development-version

How did you get to this link?
