### ISSUE TITLE
Problems with check_next in version 2.0.0

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1530]
I have been testing Liquidsoap main / version 2.0.0. It's great! I have a question about changes / usage in this version.

The attached minimal script below works in version 1.4.4, but fails in version 2.0.0. 
It simply prevents the repetition of tracks within a specific time period by using check_next.

Could you tell me what has changed in version 2.0.0 which is causing this section of code to break?
If I can get this working in version 2.0.0, it would be good to share this as an example script on liquidsoap.info. I think others might find it useful too.

[2.0.0minimal.liq.txt](https://github.com/savonet/liquidsoap/files/6105339/2.0.0minimal.liq.txt)

**Comment by toots** [comment]
Hi! Thanks for testing and reporting. The playlist operator was entirely switched to a scripted operator with `2.0`, which could explain the change in behavior. Would you be able to attach some logs, preferably with `set("log.level", 4)`

**Comment by oranjebloom** [comment]
I'm actually unable to start the script at all. The same minimal script starts and runs fine in 1.4.4, but it won't start in 2.0. I have other scripts that work in 2.0, so I suspect a syntax error somewhere within this code. Doing journalctl -xe showed ```
Apr 07 10:52:32 systrum.net liquidsoap[357]: At /home/db/liquidsoap-daemon/script/2.0.0min.liq, line 13, char 15:
Apr 07 10:52:32 systrum.net liquidsoap[357]: Error 3: Syntax error!
```

**Comment by smimram** [comment]
This might be because we don't have all the metadata by default in `check_next` anymore: you have to call `request.read_metadata`. I will try to change this when a `check_next` function is defined.

**Comment by smimram** [comment]
Ok I have changed this, could you test and tell if this was the cause of the problem?

**Comment by oranjebloom** [comment]
Hi @smimram ... thanks for tinkering with the playlist.liq. Unfortunately, I'm still getting the same result. No joy.

**Comment by oranjebloom** [comment]
@smimram have you been able to replicate my problem at your end?

**Comment by oranjebloom** [comment]
Hi @smimram you suggested that I might need to employ `request.read_metadata` but can we be sure the the issue lies with `check_next`? I tested the changes you applied to the playlist.liq but it didn't help. I'd like to pin point what exactly is causing the script to break in version2 before rewriting sections of the script. @toots you requested logs but I can't get the script to start. Did my paste of the info from `journalctl -xe` help to diagnose where the issue in the code might reside?

**Comment by toots** [comment]
Here's a fixed version of your minimal script. Does that help?
[2.0.0minimal.liq.txt](https://github.com/savonet/liquidsoap/files/6311853/2.0.0minimal.liq.txt)

**Comment by oranjebloom** [comment]
hi @toots, yes, that fixed it. I've tested it and it works in v2.0. Thanks a lot!

**Comment by smimram** [comment]
For info, I have just introduced `playlog` operator, which can be used to record when a song was last played. For instance, you can reject all songs played less than an hour ago with
```
l = playlog()
def check(r)
  m = request.metadata(r)
  if l.last(m) < 3600. then
    log.info("Rejecting #{m['filename']} (played #{l.last(m)}s ago).")
    false
  else
    l.add(m)
    true
  end
end
s = playlist(check_next=check, "playlist")
output(s)
```

**Comment by oranjebloom** [comment]
Awesome! I've been hoping that something like this would eventually come! I'll have a play with it and see how it goes in my script.

I have a further question related to this ... is there scope to use this with an additional parameter? 
For instance , could the one definition be edited
1. to reject songs played less than an hour ago (or any other time set in the definition)
AND
2. to reject songs from a specific source

I'm currently looking for ways to do this within my script.

**Comment by oranjebloom** [comment]
@smimram I would like to know whether the playlog operator could be applied for the following purpose described below, and if not whether there is any other method currently available in Liquidsoap to do what I need. At this point, I get the feeling that I need to develop my own code to do what I am trying to achieve. 

Basically I have what we might call a master source and its tracks are changed or updated  every week. 

In addition to this master source, there are other sources managed by other contributors at our station, so it is possible that sometimes these people might add tracks to their source playlists that already exist in the master source playlist that I mentioned earlier.

My question is whether the playlog operator could be used so that the tracks that are contained in the master source playlist can only be played by that master source … and not in any of the other source playlists. Could playlog suppress the playing of a specific track unless it is listed in the master source directory or a text file? 

 Of course when those tracks are removed from the master source or changed for new tracks, then the other sources would be able to play those tracks.
