### ISSUE TITLE
HTTPS output to icecast failing

### ISSUE THREAD

**Issue by konalt** [savonet/liquidsoap#1532]
**Describe the bug**
I can't use liquidsoap as a source. It gives me "SSL: connection refused - error=20"

**To Reproduce**
```
set("log.stdout",true)
set("log.file",false)

s = amplify(0.1,playlist("playlist.m3u", mode = "random"))

output.icecast(%mp3,
	 mount = "radio",
	 protocol = "https", mksafe(s))
```

**Expected behavior**
I am able to stream to icecast (localhost:8000)

**Version details**
 - OS: Windows 10
 - Version: 1.4.3

**Install method**
Release page

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by toots** [comment]
I would suggest to look at your ssl certificate for the localhost. Is it self-signed? SSL on localhost is tricky, it's usually reserved for legitimate public domains. Any reason you want to use SSL for the localhost?

**Comment by horseyhorsey** [comment]
Similar issue here, not sure if there is another way?

I have an accessible Icecast server running with Let's Encrypt but when I run LiquidSoap:

 ```
Certificate[1] subject=/C=US/O=Let's Encrypt/CN=R3
Certificate[1] issuer =/C=US/O=Internet Security Research Group/CN=ISRG Root X1
SSL: rejecting connection - error=20
```

```
output.icecast(
fallible=true, %mp3, mount="radio.mp3",
host="radio.domainurl.com", port=8443, password = "****", protocol="https")
```

**Comment by toots** [comment]
Hi @horseyhorsey ! Have you checked that the server making the requests has the correct SSL certificates setup? You could for instance make a call with `curl` to one of the icecast static https hosted pages from that server and see if that works. If it does then most likely something is wrong on liquidsoap's side.

**Comment by toots** [comment]
If we trust the documentation for error 20 [here](https://articles.assembla.com/en/articles/1623119-certificate-verification-error-20-unable-to-get-local-user-certificate), this could be because your server does not have let's encrypt's root certificate in its local database of trusted root certificates.

**Comment by horseyhorsey** [comment]
Thanks for the quick response. I did forget to mention that this is a windows server and you could be right that it's not locally installed as this was a manual let's encrypt cert. That should be easy enough to test though.

I went to use Nginx to try as a proxy, but found that with IIS I installed you can just add URL Rewrite reverse rule proxy.

![image](https://user-images.githubusercontent.com/5377332/129854489-b126b50b-eb02-4cbc-b245-07f7b55368e0.png)

**Comment by horseyhorsey** [comment]
> Hi @horseyhorsey ! Have you checked that the server making the requests has the correct SSL certificates setup? You could for instance make a call with `curl` to one of the icecast static https hosted pages from that server and see if that works. If it does then most likely something is wrong on liquidsoap's side.

I've come back to tackle this now as the Reverse Proxy is too slow, it can take up to 20-30 seconds to connect to the stream.

I can `CURL` the static pages in and outside of the server over a public domain (not localhost) but `LS` rejects connection.

**Comment by toots** [comment]
Thanks for these details. I'm gonna try to build an example binary so we can try to isolate the problem using the underlying library, `ocaml-cry`.
