### ISSUE TITLE
Liquidsoap crashing intermittently when copying files from S3 bucket using AWS CLI (Windows and Linux)

### ISSUE THREAD

**Issue by sirherbertlemon** [savonet/liquidsoap#1533]
**Describe the bug**
I'm running into issues with my audio broadcasting solution using Liquidsoap. In my current setup I'm dynamically generating mp3 files and an m3u file and uploading them to an S3 bucket, where I have a Windows server with Liquidsoap pointing to that m3u playlist to send to Icecast for broadcasting. This works fine a majority of the time, but it will sporadically crash multiple times in a 24 hour period. I wanted to see if it was something unique to Liquidsoap running in Windows, so I tested the same setup on a Linux environment and it crashed there as well, albeit less frequently (about once every 24 hours). I suspect that it may have something to do with Liquidsoap using the AWS CLI to copy files from my S3 bucket. Perhaps it is not gracefully handling a failed copy attempt?

**To Reproduce**
Here is my script:
```
set("log.file",true)
set("log.file.append",true)
set("log.file.path","<syslogdir>/<script>.log")

set("request.grace_time",30.)

harPlaylist = mksafe(delay(2.,playlist(reload_mode="rounds",reload=1, mode="normal","s3://my-s3-bucket/Playlist.m3u")))

output.icecast(%mp3(bitrate=32, samplerate=22050, stereo=false),
     host = "localhost", port = 8000,
	 fallible=true,
     password = "hackme", mount = "har",
	 harPlaylist)
```
`Playlist.m3u` contains a list of S3 URLs to mp3 files on the same bucket.

**Version details**
WINDOWS 
-OS: Windows Server 2016
-Liquidsoap Version: 1.4.4
-AWS CLI Version: 2.1.19 Python/3.7.9

LINUX
-OS: Centos 7
-Liquidsoap Version: 1.4.4
-AWS CLI Version: 2.1.29 Python/3.8.8 

**Install method**
Windows was installed using the packaged Windows distribution version 1.4.4.

Linux was installed using OPAM.

**Log Files**
[windows-liquisoap-20210311-1.log](https://github.com/savonet/liquidsoap/files/6129867/windows-liquisoap-20210311-1.log)

[linux-liquidsoap.log](https://github.com/savonet/liquidsoap/files/6129876/linux-liquidsoap.log)

**Comment by sirherbertlemon** [comment]
This still appears to be an issue in 1.4.4

**Comment by toots** [comment]
Have you been able to test with `2.0.0`?

**Comment by toots** [comment]
Also, you might want to check this report: https://github.com/savonet/liquidsoap/issues/1647
