### ISSUE TITLE
input.ffmpeg to read mp3

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1536]
I tried
```
s = input.ffmpeg(format="mp3", "test.mp3")
output(s)
```
and it seems that there is a synchronisation issue: the whole file is played very quick, as in "fast-forward". Was this expected?

**Comment by toots** [comment]
Yes, this is a live input, much like `input.http` would consume a whole static file if used this way.

Should be think of renaming these operators to make it more clear?

**Comment by smimram** [comment]
Maybe `input.http.ffmpeg` would be better then?

**Comment by toots** [comment]
It can read any stream that `ffmpeg` can read, not just `http`. I'm actually planning on using it to have a functional `input.hls` c.f. #1537 

Maybe `input.live.{icecast, ffmpeg, hls}` etc?
