### ISSUE TITLE
cannot change sink in pulseaudio

### ISSUE THREAD

**Issue by anarcat** [savonet/liquidsoap#154]
it would be quite useful if we could select the sink we want to use in pulseaudio. this could allow, for example, full RTP streams (with SDP/SAP announcements, something I couldn't figure out how to do with VLC), see #109 for that.

**Comment by smimram** [comment]
Can't you specify it in the `device` parameter?

**Comment by smimram** [comment]
You should be able to specify the device. Please reopen if it is not the case.
