### ISSUE TITLE
Add documentation for LADSPA and LV2 plugins on the web

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1555]
Hi @toots, I am not sure I understand how the website is built any more. It would be nice if we could install traditional LADSPA and LV2 packages when building the doc, so that they appear on the website. They won't pollute really much since they are in the extra section now.

**Comment by toots** [comment]
Do you have debian packages that we can install for that?

**Comment by smimram** [comment]
I would start with
```
amb-plugins caps cmt csladspa fomp calf-ladspa swh-plugins tap-plugins lsp-plugins-ladspa lsp-plugins-lv2 zam-plugins dpf-plugins swh-lv2 abgate
```
