### ISSUE TITLE
How to get BPM?

### ISSUE THREAD

**Issue by xorinzor** [savonet/liquidsoap#1565]
When I try to get the BPM and store it in a variable using this code
```
bpm_a = 0
source_a = bpm(every=30., (fun(_) -> bpm_a), source_a)
```
It says
```
Error 5: this value has type
  (...) -> int
but it should be a subtype of
  (...) -> unit
```
But from what I can find in the documentation, I can't set a variable to "unit" (which would made sense since it's pretty ambiguous).
What would be the correct way of doing this?

**Comment by rrolla** [comment]
maybe can help https://github.com/savonet/liquidsoap/issues/467 :)

**Comment by xorinzor** [comment]
Thanks, I did see that, but rather then using a separate function, I'd like to use a small anonymous function to keep the code more readable (need to get the BPM for 2 tracks).

It's also a matter of trying to understand the script language and how I should write it :)

**Comment by smimram** [comment]
You can store the bpm in a reference as follows (non-tested code but you should get the idea):
```
bpm_a = ref(0.)
source_a = bpm(every=30., (fun(b) -> bpm_a := b), source_a)
```
The reference `bpm_a` should then regularly be updated and you can get the bpm with `!bpm_a`.

For future reference, I have just improved the interface to something more sensible: 1401b4af4629ffe6db1373321463e6c1bb036b68.

**Comment by xorinzor** [comment]
Is the `bpm` calculated when it's called?

When I use it like this:
```
bpm_a = ref(0.)
bpm_b = ref(0.)
source_a = bpm(every=10., (fun(bpm) -> bpm_a := bpm), source_a)
source_b = bpm(every=10., (fun(bpm) -> bpm_b := bpm), source_b)

log("BPM track A: #{string_of(!bpm_a)}")
log("BPM track B: #{string_of(!bpm_b)}")
```

the log always returns:
```
2021/04/12 15:57:07 [autodj_cross:3] BPM track A: 0.
2021/04/12 15:57:07 [autodj_cross:3] BPM track B: 0.
```

**Comment by smimram** [comment]
In your example, the bpm is updated every 10 seconds (and the first time it has to wait for 10 seconds, so that your `log` always display the initial value for the variables).

**Comment by xorinzor** [comment]
Gotcha, I figured it would update instantly, and then every x amount of seconds (which is why I just gave it a higher value).
Is there a way of executing it once? If not I'll just use one of my other ideas :)

**Comment by smimram** [comment]
The thing is that the operator has to be fed with some audio before being able to compute the bpm...

I don't think there is an easy way of executing it once currently (if you really need this we can think of something based on `switch` I think, but it is not going to be easy)

**Comment by xorinzor** [comment]
Ah, that makes sense.
No worries! My application will pre-process each track before ever adding it in liquidsoap anyway, so I can just store the BPM in a metatag and fetch it that way.

Thanks for the help!
