### ISSUE TITLE
Custom transition: how to get current and next track?

### ISSUE THREAD

**Issue by xorinzor** [savonet/liquidsoap#1566]
I'd like to write my own transition method. `cross` provides the arguments of source A and source B (ie: current and next track).
But digging into the source code I haven't been able to discover a way of getting these values without using `cross`.

How can I get the current track, and next track that will be played when the current track is finished?
Additionally, is there a way to get the filepath of said track?

**Comment by smimram** [comment]
In `cross`, you specify a transition function which will look like this:
```
def transition(va, vb, ma, mb, a, b)
  ...
end
s = cross(transition, s)
```
The arguments `ma` and `mb` are the metadata of the old track and the new track, and are of interest to you they should contain the usual metadata plus internal metdata such as the file name for the old and new track. The `a` and `b` are the old track and new track and you return how to combine them, the most simple way would be to simply add them:
```
def transition(va, vb, ma, mb, a, b)
  add(normalize=false, [a, b])
end
```

I hope this helps.

**Comment by xorinzor** [comment]
Thank you for the explanation, I was indeed using `cross` in my own function, but am running into issues which made me think I wasn't supposed to use `cross` this way.

These are the relevant files with the code that I am using:
https://github.com/xorinzor/Shoutz0r-player/blob/2.0/main.liq
https://github.com/xorinzor/Shoutz0r-player/blob/2.0/lib/autodj.liq
https://github.com/xorinzor/Shoutz0r-player/blob/2.0/lib/smooth_stretch.liq

This is the output I'm getting:
```
2021/04/12 15:57:07 [queue_list:3] Prepared "/home/liquidsoap/app/tracks/120bpm.mp3" (RID 3).
2021/04/12 15:57:07 [cross_33255:3] Analysis: -28.664440dB / -28.893253dB (7.88s / 7.88s)
2021/04/12 15:57:07 [autodj_cross:3] Getting BPM from track <source> and <source>
2021/04/12 15:57:07 [autodj_cross:3] BPM track A: 0.
2021/04/12 15:57:07 [autodj_cross:3] BPM track B: 0.
2021/04/12 15:57:07 [autodj_cross:3] BPM difference is within range. Using smart-mix logic
2021/04/12 15:57:07 [clock.main:2] Source test_output failed while streaming: Clock_conflict: At position: unknown position, a source cannot belong to two clocks (cross_33255[], resample_33447[])!
2021/04/12 15:57:07 [clock.main:3] Streaming loop stopped.
```

Now, there are 3 issues going on here:
1. I can't seem to get the filename from the source object (this one isn't really a huge problem, but would really help out).
2. The BPM always stays at zero, I'm guessing because the BPM hasn't been calculated yet at the time the `log` is called?
3. I am not yet familiar with how the clocks work. I understand the basic concept of them, but have no idea what is expected from me with this error.

**Comment by xorinzor** [comment]
Most likely found the issue in my transition. After another comparison it would seem the fade methods re-combine the sources using `add` and return that. Instead of applying a fade on the source and returning that.

After applying that to my method the clock conflict no longer occurs. Will close this issue for now, and will re-open if I need any additional help.
