### ISSUE TITLE
Allow adding blank audio for image decoders.

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1568]
Currently the script
```
v = single("image.jpg")
output.graphics(v)
```
is not working. It took me quite some time to figure out that it is because we try to decode the image with audio. We should allow adding blank audio to images.

The variant
```
v = (single("image.jpg"):source(audio=none))
output.graphics(v)
```
is working but I guess that no one will be able to find this.

**Comment by toots** [comment]
What's the type for `output.graphics`? The decoder's intended type should be driven by the output's declared type.

**Comment by smimram** [comment]
The type of `output.graphics` is
```
(source(audio='a, video=yuva420p('b), midi='c)) -> active_source(audio='a, video=yuva420p('b), midi='c)
```
We allow audio in order not to have to use `drop_audio` which is quite convenient. Because of this `audio` is undetermined and becomes the default value (stereo).

**Comment by toots** [comment]
I'm not sure if I feel the same way. Firstly, now that we have support for encoded content, how do we plan on dealing with sources that expects `mp3` data for the audio?

A very Vulcan answer is that the only logical answer is to be strict about the type that each operator processes, in particular output, I believe.. 😉

![giphy](https://user-images.githubusercontent.com/871060/114648380-4d46fe80-9ca4-11eb-9251-8b7cb6fd4cb1.gif)

**Comment by smimram** [comment]
My idea was rather to allow any `internal` content for audio and midi for images...

**Comment by toots** [comment]
This is possible and I believe that there is a constraint for it. I'm still in favor of strict typing and better logging. The way decoders accept/refuse files based on the source content choices that we make is already confusing (see https://github.com/savonet/liquidsoap/issues/1559), I'd rather make it as explicit as possible, report it clearly to the user and give them the right tools to adjust.
