### ISSUE TITLE
Delay the creation of encoders

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1569]
Rigth now the encoders are created at parsing time which is not nice:
- this is not nice
- we cannot have variables in encoders, which prevents writing some useful functions
- we have to hardcode some default values (e.g. samplerate, channels, etc.) because configuration is not evaluated at this time.

The rationale for this was that we need some of the information in there in order to determine typing. However, we don't need *all* the information (for instance, we need the number of audio and video channels, but not the samplerate or advanced ffmpeg settings). I suggest that we turn it into a formal structure of the language, where we only require to the required parameters to be constants (e.g. number of channels) and evaluate the rest and create the encoder at runtime, like any other value.

@toots What do you think?

**Comment by toots** [comment]
I fully agree, this would be an amazing improvement. Also, it could allow to separate the encoders from the lexer/parser, which chould allow the extraction of the language into its own library/module.

**Comment by smimram** [comment]
Fixed in #1858.
