### ISSUE TITLE
SRT support - Unable to locate package libsrt-gnutls-dev

### ISSUE THREAD

**Issue by AliceRossa** [savonet/liquidsoap#1571]
**Describe the bug**
I can't install opam-srt on Debian

**To Reproduce**
`opam depext -y srt`
`Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
The following system packages are needed:
libgnutls28-dev
libsrt-gnutls-dev
The following command needs to be run through "sudo":
    apt-get install -qq -yy libgnutls28-dev libsrt-gnutls-dev`
`E: Unable to locate package libsrt-gnutls-dev
OS package installation failed`

`sudo apt-get install -qq -yy libgnutls28-dev libsrt-gnutls-dev`
`.E: Unable to locate package libsrt-gnutls-dev`

`liquidsoap 'output.dummy(input.srt())'`
`At line 1, char 13-23:
Error 4: Undefined variable input.srt`

**Version details**
 - OS: Debian GNU/Linux 10 (buster)
 - Version: Liquidsoap 1.4.4

**Install method**
opam

How can I install and use SRT?

**Comment by toots** [comment]
Hi! Debian changed the packaging naming scheme to add the specific SSL implementation and we don't really have any way of supporting both. Have you tried to manually install `libsrt-dev` ?

**Comment by toots** [comment]
Yeah I can confirm the issue. I'm afraid you will have to use testing or unstable or ubuntu to take advantage of `srt`.
