### ISSUE TITLE
"Stretch" causes: Invalid_argument "Bigarray.sub: bad sub-array"

### ISSUE THREAD

**Issue by xorinzor** [savonet/liquidsoap#1572]
Trying to build my own custom transition, but it's causing some issues that I'm not entirely sure how to pinpoint.

Right now when the transition method gets called it throws this error:
```
[decoder:2] Decoding "/home/liquidsoap/app/tracks/130bpm.mp3" ended: Ffmpeg_decoder.End_of_file.
[cross_33249:3] Analysis: -28.606703dB / -nandB (14.88s / 0.00s)
[autodj_cross:3] Getting BPM from track <source> and <source>
[autodj_cross:3] BPM track A: 120.
[autodj_cross:3] BPM track B: 110.
[autodj_cross:3] BPM difference is within range. Using smart-mix logic
[smooth_stretch:3] calling start_stretch
[smooth_stretch:3] Start stretching
[smooth_stretch:3] applying stretch
[clock.main:2] Source test_output failed while streaming: (Invalid_argument "Bigarray.sub: bad sub-array")!
[clock.main:3] Streaming loop stopped.
```

From debugging a bit, I feel like that my transition function might not be actually returning a source. But I have no idea why.
If in `autodj.liq` at line 76 I comment out my transition function, and just use `add([source_a,source_b])` no issues occur.

My understanding of liquidsoap right now is that any methods of a source are being called over and over again, yet the `log()` output doesn't support this idea.

Pretty stuck on this one at the moment.
Relevant files are attached, all the other files (in their current state of writing) can be found at https://github.com/xorinzor/Shoutz0r-player/tree/75d9793aaae6f018def3a737aeb7fca45a8ac711

[smooth_stretch.liq.txt](https://github.com/savonet/liquidsoap/files/6312825/smooth_stretch.liq.txt)
[autodj.liq.txt](https://github.com/savonet/liquidsoap/files/6312826/autodj.liq.txt)

**Comment by xorinzor** [comment]
After some additional debugging, this seems to come from `stretch`.

Even when removing my own transition and just using something basic like:

```
#Create our unfallible source
silent_source = single("/home/liquidsoap/app/test.mp3")

#Requester input
playlist_source = playlist(
			"/home/liquidsoap/app/playlist.txt",
			id="queue_list",
			mode="randomize",
			reload_mode="seconds",
			reload=0,
			timeout=5.,
			loop=true)

playlist_source = stretch(
        ratio=1.1,
        playlist_source)

# Add the fallback silent unfallible-source and smart crossfade
live = fallback(track_sensitive=false, [playlist_source, silent_source])
```

The issue will still occur.

**Comment by toots** [comment]
Thanks, that's super helpful!
