### ISSUE TITLE
Arguments for harbor auth function.

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1580]
The change in 6e8f895d080c09b1eee40d02ad1349df74f3449e adds the IP of the user to the authentication function. Because of this, all scripts will have to rewrite their auth functions in order to add the `address` argument. This is ok for 2.0 but not very future-proof: we might want to add the connection time or so in the future... Maybe a better style, would be to pass a record for the user as unique argument, ie switch from
```
def auth(~address, login, pass)
  login == "admin" and pass == ""
end
```
to
```
def auth(user)
  user.login == "admin" and user.password == ""
end
```
so that we can add more fields without impact on existing scripts?

**Comment by toots** [comment]
Great idea!!
