### ISSUE TITLE
Merge http and https functions

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1591]
Do we really need both `http.get` and `https.get`?

It would seem more natural to me to have only `http.get` which would call internally the https version if the url begins with `https://`...

**Comment by toots** [comment]
This is addressed by https://github.com/savonet/liquidsoap/pull/1574 but I would like to at least confirm that it won't make a windows build impossible before merging.

**Comment by martinkirch** [comment]
Could it also happen to `input.http` ?

**Comment by toots** [comment]
Yes, planning on doing it. The idea would be to fully rewrite `input.http` using `libcurl`.

**Comment by toots** [comment]
Yes, planning on doing it. The idea would be to fully rewrite `input.http` using `libcurl`.
