### ISSUE TITLE
telnet's list is empty

### ISSUE THREAD

**Issue by martinkirch** [savonet/liquidsoap#1592]
Using a build from the `main` branch, when connecting to the telnet server I noticed that
 - outputs' commands are not listed by `help`
 - `list` returns an empty string

**Comment by martinkirch** [comment]
Adding a motivating example: this breaks Showergel's freshly-created [/live view](https://arcane-retreat-54560.herokuapp.com/index.html#/) - which looks even better [in real life](https://github.com/martinkirch/showergel/issues/18#issuecomment-825181762)

**Comment by smimram** [comment]
Concerning output commands, I think that they were removed in ce7fe64484633dcc91a7476ac589cd063e7a6c29. Do you really need those? If yes, which of them? Another approach would be to register the commands from Liq (see for instance `add_skip_command` in the standard library).

**Comment by smimram** [comment]
And apparently we don't call `Server.register` anymore since ce7fe64484633dcc91a7476ac589cd063e7a6c29.

@toots can you motivate those two changes?

**Comment by toots** [comment]
They should have been moved to the `deprecated` library, let me check.

**Comment by toots** [comment]
Yeah clearly I missed some commands..

**Comment by martinkirch** [comment]
I'm currently using three output commands
 - `{output_name}.metadata`, as a fallback when `request.on_air` yields no result (when it does, I use `request.metadata {RID}`). I added this after discovering that some sources do not have an RID (`input.http`, at least).
 - `{output_name}.skip`
 - `{output_name}.remaining` - displaying it was much welcomed in the studio. Despite its lack of precision at the beginning of tracks, it really eases transitions between shows (we're not much sticking to clock time).

It seems those have no equivalent ... yet ?

**Comment by toots** [comment]
There must be a better way to do this. This works for now but I want to revisit it soon.

**Comment by martinkirch** [comment]
Two other issues arose with 6d92915:
1. `list` contains plenty duplicates
2. object names in `list` do not match names given by `help` ; for example `list` contains `alsa : output.alsa` but `help` contains  `output.alsa_30101.skip` (should be `alsa.skip` to match v1 behavior)

**Comment by smimram** [comment]
I have just removed duplicates and enforced consistency of outputs' commands names. Can you tell us if you see more problems?

**Comment by oranjebloom** [comment]
This may be a different issue, but for me, in `main` when I type `help` in telnet, playlist sources are not listed, so reloading a playlist manually is not possible.

**Comment by smimram** [comment]
> This may be a different issue, but for me, in `main` when I type `help` in telnet, playlist sources are not listed, so reloading a playlist manually is not possible. Is this an effect of the changes you mentioned earlier in this thread?

It seems to me that they are listed: with
```
s = playlist(id="xxx", "~/Music")
```
I get in `help`
```
| xxx.reload
| xxx.skip
| xxx.uri [<uri>]
```
Don't you?

**Comment by oranjebloom** [comment]
ah, I see. I didn't realise that we need to use ids in `main` to get these to appear. I tried it and it works as it should.

**Comment by jonathanstowe** [comment]
Hi,
sorry to jump in someone else's issue but this seems to be as good a place as any.

Is there a description of the changes to the server interface between say 1.4.4 and 2.0.0 (if any?)   I'd like to keep the https://github.com/jonathanstowe/Audio-Liquidsoap working with 2.0.0 but last time I tested with HEAD it didn't work.

Obviously if the server.(telnet|socket) interface is being deprecated I'll need to make a new thing.

**Comment by jonathanstowe** [comment]
> Is there a description of the changes to the server interface between say 1.4.4 and 2.0.0 (if any?) I'd like to keep the https://github.com/jonathanstowe/Audio-Liquidsoap working with 2.0.0 but last time I tested with HEAD it didn't work.

Actually I've mostly worked it out for myself,  I'll do up a migration cheat sheet when I've got all these tests working.

**Comment by smimram** [comment]
> > Is there a description of the changes to the server interface between say 1.4.4 and 2.0.0 (if any?) I'd like to keep the https://github.com/jonathanstowe/Audio-Liquidsoap working with 2.0.0 but last time I tested with HEAD it didn't work.
> 
> Actually I've mostly worked it out for myself, I'll do up a migration cheat sheet when I've got all these tests working.

This would be great. For info, I have started [this boilerplate webpage](https://github.com/savonet/liquidsoap/blob/main/doc/content/migrating.md)

**Comment by smimram** [comment]
I think the issue has been solved here, feel free to reopen if not.
