### ISSUE TITLE
Linking with ffmpeg-avdevice

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1597]
The example
```
s = (input.ffmpeg(format="v4l2", "/dev/video0"):source(audio=none))
output.video(s)
```
requires that Liquidsoap is linked with ffmpeg-avdevice (otherwise `v4l2` is not found as an input format).

**Comment by toots** [comment]
Fixed now!

**Comment by smimram** [comment]
I can see `ffmpeg-avdevice` in `Makefile.defs` but my v4l test is stil not working:
```
Could not find ffmpeg input format with that name
```
It seems that the `linkall` is not working.
