### ISSUE TITLE
Failure in FFmpeg video converter

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1599]
The script
```
output.video((single("test1.png"):source(audio=none)))
```
crashes with
```
Error when starting graphics: "Assert_failure converters/video/ffmpeg_video_converter.ml:155:12"!
```
where the image `test1.png` is

![test1](https://user-images.githubusercontent.com/2012073/116554290-4dc5d300-a8fb-11eb-8747-9fdb114e2fb3.png)

NB: the file

![test2](https://user-images.githubusercontent.com/2012073/116557970-41437980-a8ff-11eb-8cb0-b8fb1ccb9311.png)

does not exhibit the problem, so my guess is that the problem is due to the fact that first file has a vertical offset.

**Comment by toots** [comment]
Hate to be petty but didn't you write the ffmpeg converter? I have no idea why this assert if there.. 😅

**Comment by smimram** [comment]
Argh, I'll try having a discussion with my old self then...
