### ISSUE TITLE
Synchronization issue with input.ffmpeg

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1604]
Trying `input.ffmpeg` on `testsrc` with
```
s = (input.ffmpeg(buffer=0.1, format="lavfi", "testsrc=size=1280x720:rate=25"):source(audio=none))
output.video(s)
```
The timing is clearly wrong, seconds go faster than they should:
![out](https://user-images.githubusercontent.com/2012073/116610120-723ea100-a935-11eb-9ed3-0c9fbea72e81.gif)

**Comment by toots** [comment]
This example does not work if I try to encode to a file:
```
s = (input.ffmpeg(buffer=0.1, format="lavfi", "testsrc=size=1280x720:rate=25"):source(audio=none))
e = %ffmpeg(format="mp4",%video(codec="libx264"))
output.file(e, "/tmp/bla.mp4", s, fallible=true)
```
Does it work for you?

**Comment by toots** [comment]
My bad it works just `mplayer` was having trouble with the file it seems.

**Comment by toots** [comment]
I think this is due to the fact that, like most `input` operators, `input.ffmpeg` expects a source that controls its own time:
```ocaml
    method private feed (should_stop, has_stopped) =
      try
        let decoder = self#get_decoder in
        let buffer = Decoder.mk_buffer ~ctype:self#ctype generator in
        while true do
          if should_stop () then failwith "stop";
          decoder buffer
        done
      with e -> ...
```
However, I haven't been able to confirm. I'd be nice to be able to have a dual behavior where one can set the source to follow its attached clock instead.

**Comment by toots** [comment]
Yeah, that's definitely what's going on. If you set `buffer=50.` and stop the process shortly after it is done buffering, you will have the appropriate timing..

https://user-images.githubusercontent.com/871060/116652418-c1db9780-a94a-11eb-86b7-30fbedad6222.mp4

**Comment by smimram** [comment]
Unfortunately, this does not seems to be fixed. The script
```
log.level.set(5)
s = video.testsrc.ffmpeg()
output.video(s)
```
is very very slow (for some reason even the startup logs take time to be displayed)...

**Comment by toots** [comment]
This should be fixed now. Can you confirm?

**Comment by smimram** [comment]
This is much better thanks! However the image flickers every few seconds and I see messages like this:
```
2021/05/09 21:37:21 [input.ffmpeg:5] Not ready: need more buffering (3528/22050).
```
Could this be avoided?

**Comment by toots** [comment]
Have you tried increasing the buffer? It looks like you're having a typical clock issue, what's the actual output and what's the clock situation?

**Comment by smimram** [comment]
Same sitatuation if I increase the buffer, it simply takes more time to show up. What kind of info could I provide you with?

**Comment by toots** [comment]
Is the output having its own clock? Is that clock also driving the input?

**Comment by smimram** [comment]
My test is the following one:
```
s = video.testsrc.ffmpeg()
output.graphics(fallible=true, s)
```
If I use a cpu clock I get the exact same result (periodic buffering):
```
s = video.testsrc.ffmpeg()
clock(sync="cpu", output.graphics(fallible=true, s))
```
If I use an unsynced clock, the script is very slow (as it was before your previous commit) plus I get buffering:
```
s = video.testsrc.ffmpeg()
clock(sync="none", output.graphics(fallible=true, s))
```

**Comment by smimram** [comment]
Another thing: I happened to try
```
output.video(input.v4l2())
```
I remember that it was working quite well earlier. Now `input.v4l2` is feed much slower than realtime (when I set `buffer=1.` it takes much longer than 1 sec to fill in the buffer + I need to rebuffer quite often...)

**Comment by smimram** [comment]
Incidentally, I just tried
```
s = input.ffmpeg(format="lavfi", "sine=frequency=440")
output(s)
```
and we hear very frequent jumps in the audio.
