### ISSUE TITLE
Add ffmpeg.filter.audio_video.output

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1612]
It would be *very* convenient to have a function `ffmpeg.filter.audio_video.output` whose type would rouhgly be
```
(?id : string, ?buffer : float, ?fps : int?, ffmpeg.filter.graph, ffmpeg.filter.audio, ffmpeg.filter.video) ->
source(audio=ffmpeg.audio.raw('a), video=ffmpeg.video.raw('b), midi=none)
```
It is currently difficult to write filter which process both audio or video, or simply process video while leaving audio untouched (I know we can mux but we'd rather avoid that).

Edit: muxing audio is not even a reasonable option: filters are buffered and this induces a lag beteween audio and video...

PS: my current test
```
def myfilter(s) =
  def mkfilter(graph) =
    s = drop_audio(s)
    s = ffmpeg.raw.encode.video(%ffmpeg(%video.raw), s)
    s = ffmpeg.filter.video.input(graph, s)
    s = ffmpeg.filter.hflip(graph, s)
    s = ffmpeg.filter.curves(preset=10, graph, s)
    ffmpeg.filter.video.output(graph, s)
  end
  o = ffmpeg.raw.decode.video(ffmpeg.filter.create(mkfilter))
  mux_audio(audio=drop_video(s), o)
end
s = single("lf.mp4")
s = myfilter(s)
output.audio_video(s)
```

**Comment by dhannyz** [comment]
Another problem I have encountered, crucial for any audio reactive visuals

**Comment by toots** [comment]
We have support for `PTS` through buffer processing, which should allow for synchronous parallel filter processing of audio and video. I'd like to confirm if this will work, then we can simply script this operator.

Here: https://github.com/savonet/liquidsoap/blob/main/src/io/ffmpeg_filter_io.ml#L112
We set the input frame PTS
Here: https://github.com/savonet/liquidsoap/blob/main/src/io/ffmpeg_filter_io.ml#L180
We pass the filter's output PTS back to liq
Finally, the generator (our internal buffers) have extensive support to keep synchronous audio/video data (up to a frame) that is throughly tested here: https://github.com/savonet/liquidsoap/blob/main/src/test/generator_test.ml

It would be nice to confirm if this can or cannot work first.

**Comment by toots** [comment]
Here's an example with audio and video filtering. I can confirm the lag between audio and video and will investigate further:
```ruby
s = single("/tmp/cut.mp4")

def myfilter(s) =
  def mkfilter(graph) =
    v = drop_audio(s)
    v = ffmpeg.filter.video.input(graph, v)
    v = ffmpeg.filter.hflip(graph, v)
    v = ffmpeg.filter.curves(preset=10, graph, v)

    a = drop_video(s)
    a = ffmpeg.filter.audio.input(graph, a)
    a = ffmpeg.filter.flanger(graph, delay=10., a)

    a = ffmpeg.filter.audio.output(graph, a)
    v = ffmpeg.filter.video.output(graph, v)

    mux_audio(audio=a, v)
  end

  ffmpeg.filter.create(mkfilter)
end

s = myfilter(s)
s = ffmpeg.raw.decode.audio_video(s)
```
Note that the use of `single` infers the raw format for the ffmpeg decoder, avoiding one round of data copy via `ffmpeg.raw.encode`.

**Comment by toots** [comment]
Update: sync issues happen even without any filtering at all, just straight I/O

**Comment by toots** [comment]
Update: the sync issue seems to come from the raw inline decoder. This works well:
```
s = single("/tmp/bla.mp4")

def myfilter(s) =
  def mkfilter(graph) =
    v = drop_audio(s)
    v = ffmpeg.filter.video.input(graph, v)
    v = ffmpeg.filter.hflip(graph, v)

    a = drop_video(s)
    a = ffmpeg.filter.audio.input(graph, a)
    a = ffmpeg.filter.flanger(graph, a)

    a = ffmpeg.filter.audio.output(graph, a)
    v = ffmpeg.filter.video.output(graph, v)

    mux_audio(audio=a, v)
  end

  ffmpeg.filter.create(mkfilter)
end

s = myfilter(s)

e = %ffmpeg(format="matroska",%audio.raw(codec="aac"),%video.raw(codec="libx264"))
output.file(e, "/tmp/bla.mkv", s, fallible=true)
```

**Comment by toots** [comment]
I just merged the PR fixing sync issues with the ffmpeg inline decoder!

**Comment by toots** [comment]
I believe this can be closed now.
