### ISSUE TITLE
output.file.hls usage

### ISSUE THREAD

**Issue by mrdevis** [savonet/liquidsoap#1623]
Hi all,
I have an issue using output.file.hls.
I use the example from your docs (https://www.liquidsoap.info/doc-1.4.4/hls_output.html). 
For some reason I keep getting this error::
```
Error 12: Unsupported format: %fmpeg(format="mpegts",ar=44100,codec="aac",b="32k",channels=2).
You must be missing an optional dependency.
```

--> note the single "f" after the % sign

testing like this,  a wav as input::
```
	# make source
	liveOut = playlist.once(reload_mode="watch", "/AUDIOS/play_one.pls")
	liveOut = fallback(track_sensitive=false, [liveOut, single("/AUDIOS/09-Mercato_Loud-161124_1346-glued.wav")] )
```

defining the protocol here ::
```
    aac_hifi = %ffmpeg(format="mpegts",
       codec="aac",
       channels=2,
       ar=44100,
       b="192k")
```

Segment names and streams are defined as per your example.

then outputting like this::
```
	output.file.hls(
					playlist="live.m3u8",
					segment_duration=3.0,
					segments=5,
					segments_overhead=5,
					segment_name=segment_name,
					streams_info=streams_info,
					persist=true,
					persist_at="/var/local/srs/www/live",
                    "/var/local/srs/www/live/livestream",
                    streams,
                    liveOut
		)
```

My install is local, github version 2.0.0 per opam
FFmpeg  is fresh from home, and so is srt (github)

Is is unclear to me where to look in the docs, as %ffmpeg is not documented (yet?). strace the script didn't reveal anything meaningfull either. Unsure if I should convert the audio before passing it to ffmpeg, as it seems to receive an encoder/bitrate argument...

Anz help with this greatly appreciated!
Tx, Jeroen

**Comment by smimram** [comment]
Small note: the `%fmpeg` (with one `f`) was only a typo in the error message (corrected in 97b926b63ab9b5a4d967d83840490c9dc1ec0242) and is not related to the cause of the bug.

**Comment by smimram** [comment]
As the error message suggests: did you build OCaml's FFmpeg libraries?

You can do so with something like
```
opam install ffmpeg ffmpeg-avcodec ffmpeg-avfilter ffmpeg-swresample ffmpeg-av ffmpeg-avdevice ffmpeg-avutil ffmpeg-swscale
```
which should trigger the re-compilation of liquidsoap with support for it.

**Comment by mrdevis** [comment]
Hoped something like that, f-wise :)

Didn't compiled them with ocaml, but from scratch. Are they to be recompiled for liquidsoap especially? 
my effort alas unsuccessful::
`opam install ffmpeg ffmpeg-avcodec ffmpeg-avfilter ffmpeg-swresample ffmpeg-av ffmpeg-avdevice ffmpeg-avutil ffmpeg-swscale
[ERROR] No package named ffmpeg-avcodec found.
[ERROR] No package named ffmpeg-avfilter found.
[ERROR] No package named ffmpeg-swresample found.
[ERROR] No package named ffmpeg-av found.
[ERROR] No package named ffmpeg-avdevice found.
[ERROR] No package named ffmpeg-avutil found.
[ERROR] No package named ffmpeg-swscale found.
`
Probably installed them (as per the directive of ffmpeg) in the wrong place (~)
I'll check that

**Comment by mrdevis** [comment]
>  did you build OCaml's FFmpeg libraries?
Ah I see, the naming confused me... Unclear why they do not want to be installed though

**Comment by mrdevis** [comment]
Would I need another repo for that?

**Comment by mrdevis** [comment]
There seems to be a problem installing the
        ocaml-ffmpegs  libraries.
    unsure if I did it all right, but what I
        did was:: 
      
    clone the github repository, and build in
        the repository with dune::
    $ dune build
    which seemed to work alright.
      
    Then, trying to figure out how to install
        the build libraries I guessed::
     $dune install
    which seemed to install the libs at the
        right places::
    >>>>
        Installing /home/jeroen/.opam/4.08.0/lib/stublibs/dllav_stubs.so
        Installing /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/META
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.a
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.cma
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.cmi
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.cmt
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.cmti
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.cmx
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.cmxa
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.ml
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec.mli
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec__.cmi
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec__.cmt
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec__.cmx
        Installing
        /home/jeroen/.opam/4.08.0/lib/ffmpeg-avcodec/avcodec__.ml
        etc
        <<<<
    however I keep getting the same message as
        mentioned before::
    $ Error 12: Unsupported format: %fmpeg(fo
      
    So, I am a bit clueless at the moment...
    Any pointers someone?
    Thanks, Jeroen
      
    
      
    
      
    
      
    On 5/7/21 7:17 PM, Samuel Mimram wrote:
    
    
      
      As the error message suggests: did you build OCaml's FFmpeg
        libraries?
      You can do so with something like
      opam install ffmpeg ffmpeg-avcodec ffmpeg-avfilter ffmpeg-swresample ffmpeg-av ffmpeg-avdevice ffmpeg-avutil ffmpeg-swscale

      which should trigger the re-compilation of liquidsoap with
        support for it.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/savonet/liquidsoap/issues/1623#issuecomment-834633607",
"url": "https://github.com/savonet/liquidsoap/issues/1623#issuecomment-834633607",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mrdevis** [comment]
Hi Samuel, and thanks for getting back.

> As the error message suggests: did you build OCaml's FFmpeg
        libraries?
      You can do so with something like
      opam install ffmpeg ffmpeg-avcodec ffmpeg-avfilter ffmpeg-swresample ffmpeg-av ffmpeg-avdevice ffmpeg-avutil ffmpeg-swscale

Maybe you missed the messages I wrote above my last one mentioning that an opam install does not work for some reasons beyond me. I am getting this::
[ERROR] No package named ffmpeg-avfilter found. 
[ERROR] No package named ffmpeg-swresample found. 
[ERROR] No package named ffmpeg-av found. 
etcetera 

That's why I tried to build them from scratch with dune, alas without success.

**Comment by mrdevis** [comment]
Hi, yes that was the only install that worked. But after the installation the same problem still existed::

```Error 12: Unsupported format: %fmpeg(format="mpegts",ar=44100,codec="aac",b="32k",channels=2).
You must be missing an optional dependency.
```
Is there any way to debug this?

**Comment by smimram** [comment]
Can you give me the first few lines of a typical log. For instance:
```
$ ./liquidsoap 'output.dummy(blank())'
2021/05/10 15:31:02 >>> LOG START
2021/05/10 15:31:01 [main:3] Liquidsoap 2.0.0+git@d42c7ecb
2021/05/10 15:31:01 [main:3] Using: graphics=5.1.1 bytes=[distributed with OCaml 4.02 or above] pcre=7.4.6 sedlex=2.2 menhirLib=20210419 curl=0.9.1 dtools=f844f4e duppy=2f80167 cry=0.6.5 mm=0.7.1 xmlplaylist=0.1.5 lastfm=0.3.3 ogg=90081bf ogg.decoder=90081bf vorbis=0bd2883 vorbis.decoder=0bd2883 opus=cb70651 opus.decoder=cb70651 speex=a97c80b speex.decoder=a97c80b mad=0.5.0 flac=f80c37d flac.ogg=f80c37d flac.decoder=f80c37d dynlink=[distributed with Ocaml] lame=fcf5830 shine=0.2.1 gstreamer=0.3.1 frei0r=0.1.2 fdkaac=0.3.2 theora=9db7f0e theora.decoder=9db7f0e ffmpeg-avutil=d4cffe5 ffmpeg-avcodec=d4cffe5 ffmpeg-avdevice=d4cffe5 ffmpeg-av=d4cffe5 ffmpeg-avfilter=d4cffe5 ffmpeg-swresample=d4cffe5 ffmpeg-swscale=d4cffe5 bjack=0.1.6 alsa=0.3.0 ao=0.2.3 samplerate=0.1.5 taglib=0.3.6 ssl=0.5.9 magic=0.7.3 camomile=1.0.2 inotify=2.3 yojson=1.7.0 faad=2703482 soundtouch=0.1.9 portaudio=0.2.2 pulseaudio=aacc476 ladspa=0.2.0 dssi=0.1.3 lilv=0.1.0 tsdl=v0.9.8 tsdl_ttf=0 camlimages=4.2.6 cohttp-lwt-unix=4.0.0 prometheus-app=1.0 srt.constants=fecde52 srt.types=fecde52 srt.stubs=fecde52 srt.stubs.locked=fecde52 srt=fecde52 lo=8f70448 gd=1.0a5
```
We first need to check whether you have ffmpeg on your side (here you can see `ffmpeg-avutil=d4cffe5 ffmpeg-avcodec=d4cffe5 ffmpeg-avdevice=d4cffe5 ffmpeg-av=d4cffe5 ffmpeg-avfilter=d4cffe5 ffmpeg-swresample=d4cffe5 ffmpeg-swscale=d4cffe5`).

**Comment by smimram** [comment]
The error message could also be improved :)

**Comment by toots** [comment]
Actually:
```
% liquidsoap '%fmpeg(format="mpegts",ar=44100,codec="aac",b="32k",channels=2)'
At line 1, char 0:
Error 3: Syntax error!
```
So, your assumption might have been the appropriate one @smimram

**Comment by toots** [comment]
It is syntactically correct actually b/c we accept generic options in `%ffmpeg`. I would most likely error at runtime.

**Comment by mrdevis** [comment]
btw toots, when I give that instruction, I get something else::
`%ffmpeg(format="mpegts",codec="aac",channels=2,ar=44100,b="32k")`
`At line 1, char 0-64:
Error 12: Unsupported format: %fmpeg(format="mpegts",ar=44100,codec="aac",b="32k",channels=2).
You must be missing an optional dependency.
`

**Comment by mrdevis** [comment]
pinning it did the trick, all the libs are installed. Just one more issue, using this input::
`	# make source
	liveOut = playlist.once(reload_mode="watch", "/AUDIOS/play_one.pls")
	liveOut = fallback(track_sensitive=false, [liveOut, single("/AUDIOS/09-Mercato_Loud-161124_1346-glued.wav")] )`

patching it to this output::
`output.file.hls(
					playlist="live.m3u8",
					segment_duration=3.0,
					segments=5,
					segments_overhead=5,
					segment_name=segment_name,
					streams_info=streams_info,
					persist=true,
					persist_at="/var/local/srs/www/live",
                    "/var/local/srs/www/live/livestream",
                    streams,
                    liveOut
		)
`
gives me this error ::

`At line 59, char 18-30:
Error 5: this value has type
  [_ * (_ * _ * _)] (inferred at line 38 char 16 - line 40 char 51)
but it should be a subtype of
  [_ * (_ * _ * _ * _)]
`
??

**Comment by toots** [comment]
Are you looking at the latest doc: https://www.liquidsoap.info/doc-dev/hls_output.html ?

**Comment by mrdevis** [comment]
yep

**Comment by toots** [comment]
What's the definition of `streams_info`? It's not included in the doc anymore and you don't need for most cases, we know how to generate it from most `%ffmpeg` encoding formats.

**Comment by mrdevis** [comment]
Ok, it seems I used the example from '1.4.4' with a 'dev' install. It is working now. Quite some changes between the both! Sorry for messing up. Closing the using. Thanks for the pointers!!
