### ISSUE TITLE
rotation and short tracks

### ISSUE THREAD

**Issue by luigiScarso** [savonet/liquidsoap#1625]
I have a rotation
`rotate(weights=[1,2,1,1],[n1, s, n2, n3])` where `n1`,`n2`,`n3` are playlists where the tracks are  1 minutes to 4 minutes long , and
and `s` are "short" tracks (about 15 seconds). 
What I see in the log is `n1`, `s` ,`n2` , `s`, `n3`, `n1`,...     while I expect to see  `n1`, `s` , `s`, `n2` ,`n3`, `n1`.... ; 
`rotate(weights=[1,1,1,1,1],[n1, s, s,n2, n3])` works as expected, i.e. I see `n1`, `s` , `s`, `n2` ,`n3`, `n1`.... 
Am I missing some parameters for the  short tracks ?
I am using liquidsoap 1.4.2

**Comment by smimram** [comment]
Looks like you have been hit by #1484 which should be fixed in latest versions of Liquidsoap. Any chance you could try a more recent version than 1.4.2? (at least 1.4.4)

**Comment by luigiScarso** [comment]
yes, a first test seems to be ok: with exactly the same config now I see
n1, s , s, n2 ,n3, n1.... ;

**Comment by smimram** [comment]
Great, let's close the issue then. Feel free to reopen, if you encounter the bug again.
