### ISSUE TITLE
Add a configuration option to suppress telnet messages in liquidsoap logs

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1630]
As per the discussion with @smimram in Slack I'd like to request a configuration option to suppress telnet messages in liquidsoap logs. This would provide the option to prevent telnet messages flooding logs, especially for users who have mechanisms that connect to telnet at regular intervals (for instance, to retrieve metadata).

**Comment by smimram** [comment]
You can use something like
```
set("server.log.level", 5)
```

**Comment by oranjebloom** [comment]
Thanks! This will only take effect from 2.0 on wards, right?

**Comment by smimram** [comment]
Yes, only for 2.0, unless it gets backported for next bugfix release if there is one...
