### ISSUE TITLE
Stream duration

### ISSUE THREAD

**Issue by negezor** [savonet/liquidsoap#1632]
How can you get track duration? There is a `source.remaining()` method, but there is no expected `source.duration()`. I understand that this will not be available for all threads, but it would be cool to add it.

**Version details**
 - OS: Debian 10
 - Version: latest (v2)

**Comment by smimram** [comment]
I am not sure I understand: the doc of `source.remaining` says that it is and _estimation of remaining time in the current track_. Can't you call it at the beginning of a track to get its duration?

**Comment by negezor** [comment]
The value may not be accurate. I will send values after `source.on_metadata()`. Are there any alternatives for accuracy?

**Comment by smimram** [comment]
The value is not accurate anyway, it is only an estimation. If you really need the duration of the current track, the proper way is to enable the duration resolver [as explained here](https://www.liquidsoap.info/doc-dev/settings.html#decoders-and-order-used-to-decode-files-metadata.) with
```
set("request.metadata_decoders.duration", true)
```
which will export a `duration` metadata, but can take some time to compute.

**Comment by negezor** [comment]
Thanks, this is what I need.
