### ISSUE TITLE
FFMPEG %video.copy does not work in 1.4.4?

### ISSUE THREAD

**Issue by CassianoDev** [savonet/liquidsoap#1633]
I'm trying to copy a playlist's codec and exit via icecast:

```
#!/usr/local/bin/liquidsoap
set("init.allow_root",true)

playlist_swing = playlist(id="playlist_swing",mode="normal","/home/cassiano/Documentos/guligulinho/stations/testando/config/playlst.pls")





output.icecast(fallible=true,%ffmpeg(format="mpegts",%audio.copy, %video.copy),id="local_1", host = "127.0.0.1", port = 8000, password = "hackme", mount = "/radio.ts", name = "Testando", description = "Testando", genre = "Tudo",icy_metadata = "true", format = "video/mpegts", url = "tvsorte.com.br", public = true, encoding = "UTF-8",  playlist_swing)
```

But I always get syntax error:
<pre><b>At line 10, char 53</b>:
<font color="#CD0000"><b>Error</b></font> 3: Syntax error!</pre>

In the alpha version it works well, but I want to use it for stability!
Is there another way to copy the codec? 
I want to transmit without mux

**Comment by smimram** [comment]
You need to close the string with `"` at the end of 4th line, just after `playlst.pl`.

**Comment by CassianoDev** [comment]
> You need to close the string with `"` at the end of 4th line, just after `playlst.pl`.

It was at the time of posting!
The Error is independent of that...

**Comment by smimram** [comment]
Could you post the actual script you are using then? Your error is located on line 10, but there are only 6 lines in the script you gave...

**Comment by CassianoDev** [comment]
> Could you post the actual script you are using then? Your error is located on line 10, but there are only 6 lines in the script you gave...

it's because there space blanks!
Updated!
The error happens in the character "%"...
As if liquidsoap does not recognize '%' it as an FFMPEG parameter (%audio.copy or %video.copy), but if we put audio = "libmp3" is work!
But I don't want to recode, I want to copy the codecs!

LiquidSoap 2.0 works ok but it's unstable, but liquidsoap from what I saw '% video.copy' has been around since last year, do I want to understand if something is missing or am I missing parameters?

**Comment by toots** [comment]
Hi! This is part of the new features of the new major release, unfortunately. Is 2.0 unstable for you? We'd love to work with you on fixing it if so, we're aiming at doing a beta release soon.

I'm gonna close this ticket since it can't be fixed. Feel free to follow-up here or open a new ticket with your issues with 2.0.
