### ISSUE TITLE
amplify function with dB parameter

### ISSUE THREAD

**Issue by YoannQueret** [savonet/liquidsoap#1637]
Hi all,

Is it possible to use the "amplify" function with a dB parameter for a simple input.http input (as for a playlist files entry) ?

In the same idea, is it possible to retrieve the audio level in dB and send it to an external script or APÏ or ..?

I have been researching and testing for some time, without success.

Thk for your trick

**Comment by YoannQueret** [comment]
oh ! It's so simple that I'm almost ashamed of it. I will hide :-)
Thk Samuel

**Comment by smimram** [comment]
No problem, I know that it's sometimes complicated to find things in the doc :)
