### ISSUE TITLE
RTMP input type

### ISSUE THREAD

**Issue by rhummelmose** [savonet/liquidsoap#1640]
**Is your feature request related to a problem? Please describe.**
I cannot easily pick up the signal from my RTMP server and use it in Liquidsoap.

**Describe the solution you'd like**
I would like to be able to pick up the live signal from my RTMP server and use it in Liquidsoap.

**Describe alternatives you've considered**
Using ffmpeg.

**Comment by rhummelmose** [comment]
CC: @toots

**Comment by toots** [comment]
Putting this in `2.0` project/milestone for now to see if we can have a work-around using `input.ffmpeg` Native RTMP input is planned for `2.0.1`

**Comment by dhannyz** [comment]
I have had success with input.ffmpeg for rtmp and have been using it for live video feeds in liquidsoap for over a year

**Comment by toots** [comment]
@dhannyz Mind sharing your setup?

**Comment by dhannyz** [comment]
```
live_video = input.ffmpeg(
    fallible=true,
    buffer=5.,
    log_overfull=false,
    format="live_flv",
    int_args=[("listen",1)],
    "rtmp://IP:PORT/ENDPOINT"
)```
The live_flv format is a little more flexible for surviving timestamp discontinuities.
Stream keys are ignored, but if you're bouncing from a trusted nginx-rtmp relay that's fine.
I'm looking forward to native rtmp support ;)

**Comment by smimram** [comment]
Thanks for sharing! I just added `input.rtmp` following your suggestion :)

**Comment by toots** [comment]
I think that this can be closed tho we still need to integrate @smimram's native RTMP module at some point in the future.
