### ISSUE TITLE
Resampling http.input depletes buffer

### ISSUE THREAD

**Issue by m4rcu5** [savonet/liquidsoap#1642]
**Describe the bug**

On `v2.0.0-alpha1`, when resampling is applied, the `input.http` buffer is slowly depleted and will require buffering at regular intervals. I can confirm this with up and down-sampling. When no resampling is needed in the chain, the issue is not present.
Testing the same chain on `v1.4.4` works with up or down-sampling applied. 

The resampler used is `libsamplerate`.

**To Reproduce**
```
set("frame.audio.channels", 2)
set("frame.audio.samplerate", 48000)

# any 44.1khz stream will do
stream = input.http(id="http", "http://ice6.somafm.com/groovesalad-256-mp3")

# resample to any other samplerate. adjust frame.audio.samplerate as well
format = %wav(stereo=true, channels=2, samplerate=48000, samplesize=16)

# we do not care about the output
output.file(append=true, fallible=true, format, "/dev/null", stream)

# for < v1.4.4
add_timeout(0., fun() -> begin print("Buffer: " ^ string_of(server.execute("http.buffer_length"))); 0.5 end)

# for > v2.0.0
thread.run.recurrent(delay=0., fun() -> begin print("Buffer: " ^ string_of(stream.buffer_length())); 0.5 end)
```

Watch the output for around 30 minutes and you will see the input buffer level get lower when resampling on `v2.0.0-alpha1`. Or stay about the same when the format's samplerate is `44100` or running `v1.4.4`.

**Expected behavior**
I would expect the resampler to behave the same on `v1.4.4` and `v2.0.0-alpha1`, leaving the input buffer at the same level while resampling the output.

**Version details**
 - OS: Debian Buster (docker)
 - Version `1.4.4` & `v2.0.0-alpha1`

**Install method**
Installed via `opam`, pinning on the git tag.

**Comment by toots** [comment]
Hi! Thanks for the report. We're working on a couple of enhancements on this operator that should help with your issue. I'll get back to you very shortly.

**Comment by toots** [comment]
Hi! The `input.http` operator has been re-implemented and enhanced, would you be able to test it using the `2.0.0-beta1` release or the latest `main`?

**Comment by toots** [comment]
It looks like this is fixed now. The implementation has been completely changed to use `ffmpeg` instead. Feel free to reopen if needed.

**Comment by pitsch** [comment]
ffmeg compared to sox for example uses rather low quality resampling algos. its not audiophile oriented, for those coming from foobar etc.  it might sound esotheric to some, but is a central issue in digital audio chains to avoid mulitple lossy resamplings and choose the sometimes cpu intensive quantisation method wisely. 

https://transcoding.wordpress.com/2011/11/16/careful-with-audio-resampling-using-ffmpeg/
https://mlr.mlr-org.com/articles/tutorial/resample.html

**Comment by pitsch** [comment]
how to tweak the default settings to get the best possible quality, if the needed CPU budget is available?
secret rabbit code aka libsamplerate has quite a range of "qualities". 
https://src.infinitewave.ca/?Top=SecretRabbitCode018&Bot=SRC_ZOH&Spec=0100
![grafik](https://github.com/savonet/liquidsoap/assets/3827235/c3c6e8e7-69d5-4ea4-85ab-0746157b2fbc)

measurement method:
http://www.mega-nerd.com/libsndfile/tools/
