### ISSUE TITLE
output.harbor.hls absolute path for init segment

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1643]
https://github.com/savonet/liquidsoap/blob/main/src/outputs/hls_output.ml#L590
This is causing the absolute path to be written to the playlist file, it needs to be relative.

More like this https://github.com/savonet/liquidsoap/blob/main/src/outputs/hls_output.ml#L596-L597

**Comment by toots** [comment]
Fixed, thanks for reporting!
