### ISSUE TITLE
Empty directory cause playlist to do infinite reload

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#1649]
**Describe the bug**
I try to load empty path with `playlist(mode = 'randomize', reload = 1, reload_mode = 'rounds', '/music/test')` then liquidsoap will try to load this path in loop.
Logs with empty path `/tmp`:
```
liquidsoap_1  | 2021/05/25 16:23:03 [tmp:3] Loading playlist...
liquidsoap_1  | 2021/05/25 16:23:03 [tmp:3] Playlist is a directory.
liquidsoap_1  | 2021/05/25 16:23:03 [tmp:3] Successfully loaded a playlist of 0 tracks.
liquidsoap_1  | 2021/05/25 16:23:03 [tmp:3] Loading playlist...
liquidsoap_1  | 2021/05/25 16:23:03 [tmp:3] Playlist is a directory.
liquidsoap_1  | 2021/05/25 16:23:03 [tmp:3] Successfully loaded a playlist of 0 tracks.
```
This also happens if path `/music/test` is absent.
Logs with not existed path `/music/test`:
```
liquidsoap_1  | 2021/05/25 16:20:45 [test:3] Loading playlist...
liquidsoap_1  | 2021/05/25 16:20:45 [request:3] Nonexistent file or ill-formed URI "/music/test"!
liquidsoap_1  | 2021/05/25 16:20:45 [test:2] Failed when resolving playlist URI "/music/test"!
liquidsoap_1  | 2021/05/25 16:20:45 [test:3] Successfully loaded a playlist of 0 tracks.
liquidsoap_1  | 2021/05/25 16:20:45 [test:3] Loading playlist...
liquidsoap_1  | 2021/05/25 16:20:45 [request:3] Nonexistent file or ill-formed URI "/music/test"!
liquidsoap_1  | 2021/05/25 16:20:45 [test:2] Failed when resolving playlist URI "/music/test"!
liquidsoap_1  | 2021/05/25 16:20:45 [test:3] Successfully loaded a playlist of 0 tracks.
```

**To Reproduce**
```
Testmusic = playlist(mode = 'randomize', reload = 1, reload_mode = 'rounds', '/music/test')
securityTrack = single("/var/liquidsoap/example.ogg")
radio = fallback(track_sensitive=false, [Testmusic, securityTrack])

output.icecast(
  host = 'icecast',
  port = 8000,
  password = 'hackme',
  mount = 'test',
  %vorbis,
  radio
)
```

**Expected behavior**
Liquidsoap will not try to instantly reload playlist if directory is empty or not exists.

**Version details**
 - OS: `Ubuntu 20.04`
 - Version: `1.4.4`

**Install method**
From github realeased `.deb` file. In container https://gitlab.com/vito-containers/liquidsoap/-/blob/master/containers/1.4/Dockerfile.

**Common issues**
`N/A`

**Additional context**
I can reproduce this behavior in `opam` based installation in `Debian 10` with version `1.4.3`.

I created workaround for this case.
```
def loadPlaylist(path)
  if file.exists(path) then
    nrj(playlist(mode = 'randomize', reload = 1, reload_mode = 'rounds', path))
  else
    log('#{path} is not exists')
    fail()
  end
end
```
Also if `reload = 2` then everything seems ok, but I haven't tested this in production.
If I use `reload_mode = 'watch'` with non-existed directory then it will cause error.

**Comment by smimram** [comment]
I just added a delay of 1 second to retry on an empty or non-existent playlist.
