### ISSUE TITLE
where correct use playlist.once or once

### ISSUE THREAD

**Issue by Den68** [savonet/liquidsoap#165]
The problem is that the commands playlist.once or once, Follow the important only once after the start, as it should be? From the documentation is not very clear. Play wanted to organize the structure of one fallbak saver before various compositions.

Samles not working:

splaylist = fallback(track_sensitive = false,transitions=[trans1,trans1],[
		fallback(track_sensitive = true,[
			once(jplaylist3),
			strip_blank(id="blogspeech",threshold=-35.,min_noise=2.,max_blank=15.,vplaylist),
			strip_blank(id="blogattach",threshold=-25.,min_noise=2.,max_blank=5.,aplaylist)
		]),
		mplaylist
	    ])

**Comment by dbaelde** [comment]
I'll close due to old age (sorry for not responding earlier) and because there's no clearly identified problem: the mailing list would have been a better place for help. For the record, once() plays only one track of its source, and playlist.once() plays a full playlist, but only once.
