### ISSUE TITLE
Buffering with input.http

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1650]
The script
```
log.level.set(5)
s = input.http("https://icecast.radiofrance.fr/fip-hifi.aac?id=liq")
output(s)
```
is buffering every ~2 sec, whereas I can listen to the url without any problem with an external player (it's not a bandwidth problem).

Maybe is it related to #1642?

**Comment by toots** [comment]
This is closed with the recent revert. Let's keep an eye on it when we try to switch the implementation again.
