### ISSUE TITLE
Rotate playlist: 1 turns into 2, sometimes 1

### ISSUE THREAD

**Issue by Hyperjase74** [savonet/liquidsoap#1651]
I have this code inside my Liquidsoap config (please note; I'm using this inside **Azuracast**, but prefer the controlability of the config file).  Version of Liquidsoap is 1.4.4 on Ubuntu 20.04 LTS. 

`radio = switch([(predicate.activates({ 0m-5m }), playlist_showstart), ({ true }, rotate(weights=[2,1,2], [playlist_music,playlist_jingles,playlist_ads]))])`

Now specifically the rotate part of this command;
`rotate(weights=[2,1,2], [playlist_music,playlist_jingles,playlist_ads])`

It's fairly simple - two songs, one jingle, then two ads - but I'm finding the one jingle can become two - they are quite short tracks, but sometimes it will play one, sometimes it will play two.

Is this associated to issue #1625 & #1484

Also; is it possible to change this so it would be song; jingle; ad; jingle [then loop]? I did try this and it didn't like it.

**Comment by oranjebloom** [comment]
I can confirm that this happens for me too (with very short jingle-type tracks), 1 play becomes two sometimes.
However, my rotate config is a little different. Nevertheless, same issue. in my case, it is the samples that get played twice. These are usually only about 5 to 10 seconds long.

```
ostrackloop = rotate([
  fresh,general,
  fresh,general,
  fresh,general,
  fresh,general,
  fresh,general,
  fresh,general,
  samples,archived
])
```

**Comment by Hyperjase74** [comment]
In my case it will be two different jingles so couldn’t be the sample issue, it’s slightly frustrating as to what’s causing it.

**Comment by oranjebloom** [comment]
My jingles are named samples... and I have 25 of them. It happens as you described. Sometimes it will only play one, sometimes it will play two in a row.

**Comment by Hyperjase74** [comment]
@oranjebloom yes, my mistunderstaning I see now you have specifically named samples - the one thing I've noticed it is the shorter tracks that are played twice, like it's expecting a minimum length of time before continuing.

**Comment by oranjebloom** [comment]
yep, my thoughts exactly.

**Comment by MrChrisCool** [comment]
Same here, seems not working as espected...
Play a Jingle then only music...


My config :

# Normalisation
enable_replaygain_metadata()
# Music
music = playlist("/usr/local/var/zik/playlists/youpi.m3u")
music = amplify(1.,override="replay_gain",music)
# Some jingles
jingles = playlist("/usr/local/var/zik/playlists/jingles.m3u")
jingles = amplify(1.,override="replay_gain",jingles)
# Some liners
liners = playlist("/usr/local/var/zik/playlists/liners.m3u")
liners = amplify(1.,override="replay_gain",liners)
# If something goes wrong, we'll play this
security = single("/usr/local/var/zik/fail/vache.ogg")
# Start building the feed with liners
lgt = liners
# Now add some jingles
lgt = random(weights = [1, 3],[lgt, jingles])
# Now add some music
lgt = random(weights = [1, 3],[lgt, music])
# And finally the security
lgt = fallback(track_sensitive = false, [lgt, security])


Maybe I wrote something wrong...
