### ISSUE TITLE
Spelling prefered => preferred

### ISSUE THREAD

**Issue by jooola** [savonet/liquidsoap#1654]
**Describe the bug**

`prefered` should be spelled `preferred`. I found this by running codespell in a project using liquidsoap.

In order to fix this I would suggest adding an alias to this function names or properties, and deprecate the bad spelled name for next major release.

**Comment by smimram** [comment]
Leaving this open to remind us to run codespell on the codebase, quite a few typos apparently.

**Comment by jooola** [comment]
@smimram Does it mean I can already fix this line ?

https://github.com/LibreTime/libretime/blob/master/python_apps/pypo/liquidsoap/1.4/ls_script.liq#L403

I though it was function name, and required a proper deprecation.

**Comment by smimram** [comment]
nope, it will be for 2.0, where the function has been renamed `output` anyway
