### ISSUE TITLE
How to get next song metadata

### ISSUE THREAD

**Issue by sonyarianto** [savonet/liquidsoap#1658]
Hi everyone,
Is there any chance to get the next song metadata in Liquidsoap and I will save it to text file. Thank you in advance.

**Comment by smimram** [comment]
Unfortunately not in general: next song is not known much in advance by default in Liquidsoap. However, if you are using the `playlist` operator you can use register a `check_next` function which will be called to validate the next song. You can abuse this in order to log the next song as follows:
```
def log_next(r)
  m = request.metadata(r)
  file.write(data="#{json_of(m)}", "/tmp/next-song")
  true
end

radio = playlist("~/Music", length=40., check_next=log_next)
```

**Comment by sonyarianto** [comment]
@smimram wow thank you very much, I will test it first and let you know the result.

**Comment by sonyarianto** [comment]
@smimram it works perfectly, here is the example on text file, very detail.
```
{
 "album": "Demi Cintaku", "date": "2019-01-18", "track": "1", "disc": "1",
 "kind": "{audio=2;video=0;midi=0}",
 "artist": "Dian Pramana Poetra;Ikaputri", "decoder": "FFMPEG",
 "isrc": "FR10S1906057", "title": "Demi Cintaku", "bpm": "0",
 "filename": "hahawhawahw.flac",
 "publisher": "Target Pop", "temporary": "false", "source": "songs",
 "tracknumber": "1",
 "initial_uri": "hahawhawahw.flac",
 "length": "267000", "barcode": "3615936556032", "playlist_length": "3633",
 "status": "ready", "discnumber": "1", "albumartist": "Dian Pramana Poetra",
 "rid": "3", "genre": "Pop", "playlist_position": "2",
 "album_artist": "Dian Pramana Poetra;Ikaputri"
}
```

thank you very much

**Comment by smimram** [comment]
Great! :)
