### ISSUE TITLE
Extracted JPG cover art with EXIF data causing libjpeg error

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#1660]
jpg images extracted from ID3 metadata that include prepended EXIF blocks are causing `setting libjpeg error message: ""`

When used as a 'video' input this is causing a crash loop

**Comment by smimram** [comment]
Could you please provide an example mp3 file? (You can send me the link privately if you prefer) Also, how are you using the cover in your script?

**Comment by dhannyz** [comment]
@smimram this image is causing it https://transfer.sh/1uSTLB5/cover1.jpg

Im using `single(fallible=true, filename)` writing to the file after extracting metadata and refreshing it with `skip()`
This was based on an older example I saw, more recently ive seen some newer cover methods with request dynamic though

**Comment by dhannyz** [comment]
Ah good to know its not just me. For now, perhaps I can script up something to remove any EXIF embedded in the jpgs

**Comment by smimram** [comment]
Reported on https://gitlab.com/camlspotter/camlimages/-/issues/2

**Comment by smimram** [comment]
Closing here, since camlimages is the culprit. Also, #1743 might help here.
