### ISSUE TITLE
Remove warning on `unit?`

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#1670]
```
  def f() = if 0 == 1 then () else null() end end
  f()
```
Gets this log:
```
Warning 3: This expression should have type unit.
```

**Comment by smimram** [comment]
Hum, I am not sure we want to ignore this one. The rationale for ignoring unit is that it brings absolutely no information whereas `unit?` has a bit of information (either `()` or `null`). Do you have a more concrete example where you encounter this?

**Comment by toots** [comment]
Agreed actually.
