### ISSUE TITLE
Can't distinguish between playlist and queue in server interface.

### ISSUE THREAD

**Issue by jonathanstowe** [savonet/liquidsoap#1673]
**Describe the bug**

Given a script that defines a `playlist` and `request.queue` both are returned with a type of `request.dynamic.list` with `list` in the server interface, so it isn't possible to distinguish them by "type" alone.  However they do have different "methods" as shown by "help" so they are arguably actually different thing.

**To Reproduce**
Given a script like:

```
#!/usr/bin/env liquidsoap

set("log.file", false)
set("log.stdout", true)
set("server.telnet", true)
set("harbor.bind_addr","127.0.0.1")
set("scheduler.fast_queues",2)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port",9985)
set("init.allow_root",true)


default = playlist(id="default-playlist","t/data/play")

incoming = request.queue(id="incoming")



radio = fallback(track_sensitive=false,[incoming, default, blank()])

output.dummy(id="dummy-output", radio)

```
Then "list" will return : 

```
incoming : request.dynamic.list
switch_33307 : switch
dummy-output : output.dummy
blank_33306 : blank
max_duration_33398 : max_duration
default-playlist : request.dynamic.list
sequence_33399 : sequence
fail_33432 : fail
END
```

And "help" returns:

```
Available commands:
| default-playlist.reload
| default-playlist.skip
| default-playlist.uri [<uri>]
| dummy-output.metadata
| dummy-output.remaining
| dummy-output.skip
| exit
| help [<command>]
| incoming.push <uri>
| incoming.queue
| incoming.skip
| list
| quit
| request.alive
| request.all
| request.metadata <rid>
| request.on_air
| request.resolving
| request.trace <rid>
| uptime
| var.get
| var.list
| var.set <name> = <value>
| version
```
**Expected behavior**

I'm not sure what the behaviour *should* be, but clearly as the `playlist`  and `request.queue` have different capabilities ("methods",) there should be some means to distinguish them from "list" for some integration that uses the type of the object to determine the available methods on the object (without calling "help",)

**Version details**
 - OS: Debian as per the Docker image.
 - Version Liquidsoap 2.0.0-beta1+git@2482a139

**Install method**

Docker image based on the liquidsoap:2.0.0-beta1

**Comment by smimram** [comment]
This should now be mostly corrected. Feel free to report if you see some more operators with incorrect names!

**Comment by jonathanstowe** [comment]
Cheers, I'll check it out later when the 2.0.0 Docker image is updated.
