### ISSUE TITLE
input.http: start/stop/change URL

### ISSUE THREAD

**Issue by martinkirch** [savonet/liquidsoap#1674]
Hello,
`intput.http` has been updated in 2.0.0-beta1 and I miss a great option from 1.4.4 : [autostart=false](https://www.liquidsoap.info/doc-1.4.4/reference.html#input.http).

This allowed me to have only one http source for any stream, even those whose URL appear after Liquidsoap's start : when creating the source with `autostart=false`, I could use telnet `.start` and `.stop` to stream only when needed, and `.url` to stream from somewhere else.

Would it be possible to add those 3 methods to the new implem ?

**Comment by jonathanstowe** [comment]
Actually yes, I was going to bring this one up, for me it creates a small problem with testing an integration which expects the input to be stopped when the test starts, but instead gets a bunch of noise in the logs because the source may or may not be there.

**Comment by toots** [comment]
Yes, I plan on re-writing the `Start_stop` utility and bring this back.

**Comment by toots** [comment]
This was fixed in ac6460ad476e1b4a0a798d95ca4a4e009e56569c
