### ISSUE TITLE
[2.0.0 beta2] Example from documentation gives error!

### ISSUE THREAD

**Issue by dikkedimi** [savonet/liquidsoap#1676]
Hi All!

I have installed liquidsoap on my Raspberry Pi 3B through the instructions on the website, using the opam method. I have written my first recipe and have confirmed it is working as it should.

I backed up my recipe and started work on adding a secondary stream with image to send to youtube. Happily surprised I could find an example in the cookbook (page 184, chapter 7. Video) :

```
key = string.trim(file.contents("youtube-key"))
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
enc = %ffmpeg(format="flv",
   %audio(codec="libmp3lame", samplerate=44100, q=5),
   %video(codec="libx264", width=854, height=480,
      b="800k", g=50, preset="veryfast"))
output.url(fallible=true, url=url, enc, s)
```

I integrated the example in my recipe only to finde out it caused a syntax error. I immediately assumed I was the one to blame. However, upon being unable to fix the error  I started wondering..

So I made a new file: example.liq

```
#!/home/pi/.opam/4.08.0/bin/liquidsoap
ImageSource = video.add_image(width=1280,height=720,
                           x=0,y=0,
                           file="/mnt/PNY/splash.jpg",
                           ImageSource)


key = string.trim(file.contents("/home/pi/key-yt.txt"))
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
enc = %gstreamer(video=h264_omx speed-preset=1",audio="fdk-aac"),
output.url(fallible=true, url=url, enc, ImageSource)

```
result:
```
pi@liquidsoap:~ $ ./liquidsoap/example.liq
At line 5, char 0:
Error 3: Syntax error!
```

you'll notice the only difference is I modified the key location to my situation.
as far as I'm considered there's 2 options:
- the docs are incorrect
- I did a dumb thing?

Either way I'd be so happy if someone could point me in the right direction

for reference here is the file I was originally trying to integrate it into

```
#!/home/pi/.opam/4.08.0/bin/liquidsoap
live    =       input.http("http://localhost:8000")
emergency       =       playlist("/mnt/PNY/emergency")
jukebox =       playlist("/mnt/PNY/jukebox")
jukebox =       crossfade(fade_out=3., fade_in=3., duration=5., jukebox)
AudioStream     =       fallback(track_sensitive=false, [live, jukebox, emergency, blank()])

#video to youtube
keyYT           =       string.trim(file.contents("/home/pi/key-yt.txt"))
YoutubeIntake   =       "rtmp://a.rtmp.youtube.com/live2#{keyYT}"
encoder         =       %ffmpeg(format = "flv",
                                %audio(codec = "libmp3lame", samplerate = 44100, q = 5),
                                %video(codec = "libx264" , width = 854, height = 480, b = "800k", g = 50, preset = "veryfast")
                                )

#output video+audio
output.url(fallible=true,url=YoutubeIntake, encoder, ImageSource)

#output audio only
output.icecast(%vorbis, host="localhost", port=8443, password="hackme", mount="stream", stream)
```

**Comment by dikkedimi** [comment]
Sorry for spamming the issue hub, I thought I had gotten one step closer.

https://www.liquidsoap.info/doc-dev/encoding_formats.html says:

> _"The full syntax is as follows:_
> ```
> %ffmpeg(format=<format>,
>                       # Audio section
>                       %audio(codec=<codec>,<option_name>=<option_value>,..),
>                       # Or:
>                       %audio.raw(codec=<codec>,<option_name>=<option_value>,..),
>                       # Or:
>                       %audio.copy,
>                       # Video section
>                       %video(codec=<codec>,<option_name>=<option_value>,..),
>                       # Or:
>                       %video.raw(codec=<codec>,<option_name>=<option_value>,..),
>                       # Or:
>                       %video.copy,
>                       # Generic options
>                       <option_name>=<option_value>,..
>                     )
> ```
> _Where:
> 
> <format> is either a string value (e.g. "mpegts"), as returned by the ffmpeg -formats command or none. When set to none or simply no specified, the encoder will try to auto-detect it."_

ffmpeg -formats returned
`-bash: ffmpeg: command not found`

so I ran
```
sudo apt-get update
sudo apt-get install -y ffmpeg
ffmpeg -formats
```
and ran my example.liq again after confirming flv was in the list of supported formats.
it still returned a syntax error.

**Comment by nigeyuk** [comment]
I had this problem to so here is the working config for mine which uses "radio" as its audio source.

# Output to Youtube
ImageSource = single("/home/nigel/Radio/YTLogo.png")file="YTLogo.png")
key = string.trim(file.contents("youtube-key"))
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
enc = %ffmpeg(format="flv",
%audio(codec="libmp3lame", samplerate=44100, q=3),
%video(codec="libx264", width=1920, height=1080,
b="2500k", g=50, preset="veryfast"))
output.url(fallible=true, url=url, enc, mux_video(video=ImageSource, radio))

**Comment by toots** [comment]
Hi! What version of liquidsoap are you using? The syntax mentioned above is for the `2.0.0` branch, currently in development.

**Comment by dikkedimi** [comment]
I have no idea which version I am running, but it must be 2.0.0 or above because I followed the instructions on the install page, which are for 2.0.0. Is there a command which prints the version to commandline?

either way, i followed the 2.0.0 documentation.

**Comment by smimram** [comment]
You can obtain the version by typing
```
liquidsoap --version
```

**Comment by dikkedimi** [comment]
Okay, it says liquidsoap 1.4.4

which is unexpected. If liquidsoap is the supported version, why does following the default instructions (using opam) install version 1.4.4?

**Comment by smimram** [comment]
Liquidsoap 2.0 is not released yet but will be soon (it is in beta 2). You can get the doc specific to 1.4.4 at https://www.liquidsoap.info/doc-1.4.4/

**Comment by dikkedimi** [comment]
Ah, that explains some of it. I guess I didn't notice that 2.0 was the bleeding edge version. But ehm,

> I had this problem to so here is the working config for mine which uses "radio" as its audio source.
> 
> ```
> # Output to Youtube
> ImageSource = single("/home/nigel/Radio/YTLogo.png")file="YTLogo.png")
> key = string.trim(file.contents("youtube-key"))
> url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
> enc = %ffmpeg(format="flv",
> %audio(codec="libmp3lame", samplerate=44100, q=3),
> %video(codec="libx264", width=1920, height=1080,
> b="2500k", g=50, preset="veryfast"))
> output.url(fallible=true, url=url, enc, mux_video(video=ImageSource, radio))
> ```

Unfortunately this also causes a syntax error in my case.

(currently on my mac, since the raspberry only seemed capable of 4 fps @1080p with ffmpeg)

```
#!/Users/liquidsoap/.opam/default/bin/liquidsoap
ImageSource = video.add_image(
       width=30,height=30,
       x=10,y=10,
       file="/Users/liquidsoap/assets/Graphics/splash.png")
key = string.trim(file.contents("/Users/liquidsoap/assets/key-yt.txt"))
EndpointURL = "rtmp://a.rtmp.youtube.com/live2/#{key}"
enc = %gstreamer(channels=2, audio="lamemp3enc", has_video=true, video="x264enc", muxer="mpegtsmux", metadata="metadata", log=5)
output.url(fallible=true, url=EndpointURL, enc, ImageSource )
```

no longer produces a syntax error but

```
liquidsoap $ ./example-macos.liq
At line 9, char 0-11:
Error 4: Undefined variable output.url
```

since I seem unable to get what I want to work in 1.4.4 I guess I'll uninstall it and just go to 2.0.0, since it offers more efficient video encoding anyway, and apparently I wrote the script already. Which did not work because I was running 1.4.4. Will close when I succeed.

**Comment by dikkedimi** [comment]
Hm, installing 2.0 on a mac is not as straightforward as I had hoped (who would've guessed, it's mac)

after following the steps and arriving at the 

```
./bootstrap
./configure
```

stage,

it fails producing this:

checking for ocaml standard library path... ./configure: line 6429: no: command not found

```
checking for caml/threads.h... no
./configure: line 6505: no: command not found
./configure: line 6522: no: command not found
./configure: line 6524: no: command not found
checking whether ocamlopt accepts -ffast-math... no
./configure: line 6656: no: command not found
checking for ocamlc version... ..
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
configure: error: version 4.08.0 or greater of the OCaml compiler is required to build liquidsoap
```

even though ocaml 4.12 is installed

```
radio:liquidsoap admin$ brew install ocaml
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 19 formulae.

Warning: ocaml 4.12.0 is already installed and up-to-date.
To reinstall 4.12.0, run:
  brew reinstall ocaml
radio:liquidsoap admin$ brew reinstall ocaml
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://caml.inria.fr/pub/distrib/ocaml-4.12/ocaml-4.12.0.tar.xz
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/30d9898066ac272819ad5ef9778c40d74168d98b23e8937d4773fa710ee87fde--ocaml-4.12.0.tar.xz
==> Reinstalling ocaml 
==> ./configure --prefix=/usr/local --enable-debug-runtime --mandir=/usr/local/Cellar/ocaml/4.12.0/share/man
==> make world.opt
==> make prefix=/usr/local/Cellar/ocaml/4.12.0 install
🍺  /usr/local/Cellar/ocaml/4.12.0: 2,335 files, 374.2MB, built in 8 minutes 25 seconds
```

**Comment by dikkedimi** [comment]
back to 1.4.4
I am having trouble finding output to youtube in the documentation. Also, the "Presentations" page gives a 404, as well as the "OCaml libraries" page and the "Documentation of some internals" page.

Quite annoyed that all the examples found by google seem to lead to the 2.0 documentation!

I am trying to accomplish the shared encoding example from this page, as it is exactly what i want (without a shuffling playlist, but that's something I'll figure out once I get the script working)
[https://www.liquidsoap.info/doc-dev/cookbook.html#](https://www.liquidsoap.info/doc-dev/cookbook.html#)

```
# An audio source
audio = single("/Users/admin/Radio/Playlist")

# Encode it in mp3
audio = ffmpeg.encode.audio(
  %ffmpeg(%audio(codec="libmp3lame")),
  audio)

# Send it to icecast
output.icecast(
  %ffmpeg(format="mp3", %audio.copy),
  host = "10.0.0.3",
  password = "12Receive",
  mount = "/stream",
  audio
)

# A video source, for instance a static image
video = video.add_image(
       width=1920,height=1080,
       x=0,y=0,
       file="/Users/admin/Radio/Graphics/splash.png")

# Encode it in h264 format
video = ffmpeg.encode.video(
  %ffmpeg(%video(codec="libx264")),
  video)

# Mux it with the audio
stream = mux_video(video=video, audio)

# Copy encoder for the rtmp stream
enc = %ffmpeg(
  format="flv",
  %audio.copy,
  %video.copy)

# Send to YouTube
key = string.trim(file.contents("/Users/admin/Radio/key-yt.txt"))
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
output.url(url=url, enc, stream)

# Send to Facebook
# key =
# url = "rtmps://live-api-s.facebook.com:443/rtmp/#{key}"
# output.url(url=url, enc, stream)

```

When consulting the 1.4.4. documentation page, this example is not available in the required syntax.
the script seems to run, but gives a syntax error for the audio input line, which should be correct for 1.4.4!
Example from
[https://www.liquidsoap.info/doc-1.4.4/quick_start.html](https://www.liquidsoap.info/doc-1.4.4/quick_start.html)

```
# If something goes wrong, we'll play this
security = single("~/radio/sounds/default.ogg")
```

Yet still yields the following result:
```
altruistradio:Radio admin$ ./example-multi-encode.liq 
./example-multi-encode.liq: line 2: syntax error near unexpected token `('
./example-multi-encode.liq: line 2: `audio = playlist("~/Radio/Playlist")'
altruistradio:Radio admin$ ./example-multi-encode.liq 
./example-multi-encode.liq: line 2: syntax error near unexpected token `('
./example-multi-encode.liq: line 2: `audio = playlist("~/Radio/Playlist")'
altruistradio:Radio admin$ ./example-multi-encode.liq 
./example-multi-encode.liq: line 2: syntax error near unexpected token `('
./example-multi-encode.liq: line 2: `audio = single("~/Radio/Playlist")'
```

can I say that the very fragmented documentation lacks any usable search functionality? Any search I do (on google) yields results for 2.0.0 which won't work on 1.4.4, and since 2.0.0 is not working and not supported on macos, it's good to know if I'm just wasting time or if this is something that can be done with liquidsoap 1.4.4 or not?

No objections against installing ubuntu on my mac mini, but it must be possible to run it on a mac.

**Comment by dikkedimi** [comment]
Okay, after trying it on linux I am making steady progress. The only thing I can't seem to be able to find a solution to with the existing 1.4.4 docs is that the copy encoder for the rtmp stream still throws an error that I am not able to remedy with any examples from the 1.4.4. documentation. It is however no longer a syntax error, so must be heading in the right direction... Googling also does not yield usable results. The documentation could use a prominently displayed search function imho. As someone who suffers from dyscalculia the reference gives me the jitters.
```
#!/home/user/.opam/4.08.0/bin/liquidsoap

#%include("cfg.liq")
#global vars
baseDir = "/home/user/assets"
jukeboxDir = "{baseDir}/music"
imageDir = "{baseDir}/graphics"
recipeDir = "{baseDir}/recipes"

#youtube stream key
key = string.trim(file.contents("{baseDir}/key-yt.txt"))

# An audio source
audio = single("{jukeboxDir}")

# Encode it in mp3
audio = ffmpeg.encode.audio(%ffmpeg(format="mp3",codec="lame"),audio)
# Send it to icecast
output.icecast(
  %mp3(bitrate=128, samplerate=44100, stereo=true) %audio.copy,
  host = "10.0.0.3", port=8000, password = "hackme",  mount = "/stream",
  audio)

# A video source, for instance a static image
video = video.add_image(
       width=1920,height=1080,
       x=0,y=0,
       file="{imageDir}splash.png")

# Encode it in h264 format
video = ffmpeg.encode.video(
  %ffmpeg(codec="libx264"),
  video)

# Mux it with the audio
stream = mux_video(video=video, audio)

# Copy encoder for the rtmp stream
#enc = %ffmpeg(format="flv", %audio.copy, %video.copy)
enc = %ffmpeg(format="flv" %audio.copy %video.copy)

# Send to YouTube
# key = string.trim(file.contents("/Users/admin/Radio/key-yt.txt"))
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
output.url(url=url, enc, stream)

```

result

```
At line 40, char 25-50:
Error 8: Complex expressions are forbidden in encoding formats
```

if it's not this error, it's an undefined variable error. It's becoming frustrating.

**Comment by dikkedimi** [comment]
Well yay, I guess. 

https://github.com/savonet/liquidsoap/pull/1038#issuecomment-559128035
yielded an encoder setting that produced a NEW error! I love going around in friggin circles SO MUCH! I'll be doing this for the rest of my life.

```
enc =  = %ffmpeg(video_codec="libx264",audio_codec="libmp3lame",
                  format="flv")
```
result
```
At line 17, char 8-28:
Error 4: Undefined variable ffmpeg.encode.audio

```

**Comment by dikkedimi** [comment]
Oh, and I also came to the conclusion that the search function in the 1.4.4. API reference is NON-FUNCTIONAL. It's just a textbox that doesn't do anything.

Can't find ffmpeg.encode or ffmpeg.encode.audio in there, so I am not able to progress currently.

**Comment by dikkedimi** [comment]
so now on 2.0.0 beta2, on ubuntu server 20.04 after some help from a more experienced *nix user

```
#!/home/user/.opam/4.08.0/bin/liquidsoap
#%include("cfg.liq")
#global vars
baseDir = "/home/rutger/assets"
jukeboxDir = "{baseDir}/music"
imageDir = "{baseDir}/graphics"
recipeDir = "{baseDir}/recipes"

#youtube stream key
key = string.trim(file.contents("{baseDir}/key-yt.txt"))


#sources
# An audio source
audio = single("{jukeboxDir}")

# Encode it in mp3
audio = ffmpeg.encode.audio(
  %ffmpeg(%audio(codec="libmp3lame")), audio)

# Send it to icecast
output.icecast(
  %ffmpeg(format="mp3", %audio.copy), 
  host = "10.0.0.3", 
  port = 8443, 
  password = "12Receive", 
  mount = "/stream", audio)

# A video source, for instance a static image
video = video.add_image(
       width=1920, height=1080, 
       x=0, y=0, 
       file="{imageDir}/splash.png", video)

# Encode it in h264 format
video = ffmpeg.encode.video(
  %ffmpeg(%video(codec="libx264")), 
  video)

# Mux it with the audio
stream = mux_video(video=video, audio)

# Copy encoder for the rtmp stream
enc = %ffmpeg(
  format="flv", 
  %audio.copy, 
  %video.copy)

# Send to YouTube
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
output.url(url=url, enc, stream)

```
produces
```

At line 33, char 37-42:
Error 5: this value has type
  unit (inferred at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/ffmpeg.liq, line 38 char 0 - line 61 char 3)
but it should be a subtype of the type of the value at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/video.liq, line 43, char 106
  source(_) (inferred at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/video.liq, line 63, char 8)
```

**Comment by toots** [comment]
This is probably coming from:
```
# A video source, for instance a static image
video = video.add_image(
       width=1920, height=1080, 
       x=0, y=0, 
       file="{imageDir}/splash.png", video)
```
Before this line, `video` is the  video module, which contains all the video-related operators (such as `video.add_image`!). Its type is `unit`, which means that it has no value. 

The type of `video,.add_image` is:
```
(?id : string?, 
 ?width : {int}, 
 ?height : {int},
 ?x : {int},
 ?y : {int}, 
 file : string,
 source(audio=internal('a), video=internal('b), midi=internal('c))) -> 
   source(audio=internal('a), video=internal('b), midi=internal('c))
```
So, it is expecting a source for its last argument. You could either use a `blank()` source:
```
# A video source, for instance a static image
video = video.add_image(
       width=1920, height=1080, 
       x=0, y=0, 
       file="{imageDir}/splash.png", video)
```
Or else, simply decode the image as a single:
```
video = single("{imageDir}/splash.png")
```

**Comment by dikkedimi** [comment]
Thanks toots,

using the blank() method yields
```

```
At line 33 char 0 - line 36 char 45:
Warning 2: This source is unused, maybe it needs to
be connected to an output.
At line 41, char 2-7:
Error 5: this value has type
  unit (inferred at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/ffmpeg.liq, line 38 char 0 - line 61 char 3)
but it should be a subtype of
  source(_)
```

using the single method yields
```

Line 7, char 0:
Warning 4: Unused variable recipeDir
Line 6, char 0:
Warning 4: Unused variable imageDir
Line 5, char 0:
Warning 4: Unused variable jukeboxDir
Line 4, char 0:
Warning 4: Unused variable baseDir
At line 10, char 53, at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/file.liq, line 5 char 0 - line 10 char 54:
Error 14: Uncaught runtime error:
type: file,
message: "The file {baseDir}/key-yt.txt could not be read: Sys_error(\"{baseDir}/key-yt.txt: No such file or directory\")"

```


```

**Comment by dikkedimi** [comment]
ah, think I found part of the problem:
```
video = ffmpeg.encode.video(
  %ffmpeg(%video(codec="libx264")),
  video)
```
should be
```
video = ffmpeg.encode.video(
  %ffmpeg(%video(codec="libx264")),
  blank())
```

still throws an error related to something else:

```
At line 33 char 0 - line 36 char 45:
Warning 2: This source is unused, maybe it needs to
be connected to an output.
Line 7, char 0:
Warning 4: Unused variable recipeDir
Line 6, char 0:
Warning 4: Unused variable imageDir
Line 5, char 0:
Warning 4: Unused variable jukeboxDir
Line 4, char 0:
Warning 4: Unused variable baseDir
At line 10, char 53, at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/file.liq, line 5 char 0 - line 10 char 54:
Error 14: Uncaught runtime error:
type: file,
message: "The file {baseDir}/key-yt.txt could not be read: Sys_error(\"{baseDir}/key-yt.txt: No such file or directory\")"
```

even though
```

user@radio:~/assets$ ls
graphics  key-yt.txt  music  recipes
```

**Comment by dikkedimi** [comment]
to lower the noise I used fixed paths for everything, marked sources as safe (so I wouldn't get infallablity errors)
```
#!/usr/bin/env liquidsoap
#%include("cfg.liq")
#global constants
baseDir = "/home/user/assets"
jukeboxDir = "{baseDir}/music"
imageDir = "{baseDir}/graphics"
recipeDir = "{baseDir}/recipes"

#youtube stream key
key = string.trim(file.contents("/home/rutger/assets/key-yt.txt"))


#sources
# An audio source
audio = single("/home/user/assets/music")
# mksafe(audio)

# Encode it in mp3
audio = ffmpeg.encode.audio(
  %ffmpeg(%audio(codec="libmp3lame")), audio)

# Send it to icecast
output.icecast(
  %ffmpeg(format="mp3", %audio.copy),
  host = "10.0.0.3",
  port = 8443,
  password = "12Receive",
  mount = "/stream", audio)

# A video source, for instance a static image
# video = single("{imageDir}/splash.png")

# video.add_image(
#        width=1920, height=1080,
#        x=0, y=0,
#        file="{imageDir}/splash.png", blank())
video = single("/home/user/assets/graphics/splash.png", fallible=false)
mksafe(video)
# Encode it in h264 format
video = ffmpeg.encode.video(
  %ffmpeg(%video(codec="libx264")),
  video)


# Mux it with the audio
stream = mux_video(video=video, audio)
mksafe(stream)
# Copy encoder for the rtmp stream
enc = %ffmpeg(
  format="flv",
  %audio.copy,
  %video.copy)

# Send to YouTube
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
output.url(url=url, enc, stream)

```
produces
```

Error 5: this value has type
  source(audio=ffmpeg.audio.copy,...) (inferred at line 46, char 9-38)
but it should be a subtype of the type of the value at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/source.liq, line 5, char 24
  source(audio=?internal(?A),...) (inferred at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/source.liq, line 6, char 42-73)
```

**Comment by dikkedimi** [comment]
```
#!/usr/bin/env liquidsoap
#%include("cfg.liq")
#global constants
baseDir = "/home/rutger/assets"
jukeboxDir = "{baseDir}/music"
imageDir = "{baseDir}/graphics"
recipeDir = "{baseDir}/recipes"

#youtube stream key
key = string.trim(file.contents("/home/rutger/assets/key-yt.txt"))


#sources

# reads directory but doesn't play any files.
# audio = single("/home/rutger/assets/music")


#doesn't work, produces:
# At line 20, char 43:
# Error 7: Invalid value:
# That source is fallible
audio = playlist("/home/rutger/assets/music")


# no whining about fallabiltiy
mksafe(audio)

# Encode it in mp3
audio = ffmpeg.encode.audio(
  %ffmpeg(%audio(codec="libmp3lame")), audio)

# Send it to icecast
output.icecast(
  %ffmpeg(format="mp3", %audio.copy),
  host = "10.0.0.3",
  port = 8443,
  password = "12Receive",
  mount = "/stream", audio)

# A video source, for instance a static image
# video = single("{imageDir}/splash.png")



# should work, but causes
# At line 38, char 7-12:
# Error 5: this value has type
#   unit (inferred at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/ffmpeg.liq, line 38 char 0 - line 61 char 3)
# but it should be a subtype of the type of the value at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/source.liq, line 5, char 24
#   source(_) (inferred at /home/rutger/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/source.liq, line 6, char 42-73)

# video.add_image(
#        width=1920, height=1080,
#        x=0, y=0,
#        file="{imageDir}/splash.png", blank())

# works, but still
# throws an exception:
# Available decoders cannot decode "/home/rutger/assets/graphics/splash.png" as {audio=none,video=yuva420p,midi=none}
video = single("/home/rutger/assets/graphics/splash.png")

# no whining about fallabiltiy
mksafe(video)

# Encode video in h264 format
video = ffmpeg.encode.video(
  %ffmpeg(%video(codec="libx264")),
  video)


# Mux it with the audio into stream
stream = mux_video(video=video, audio)
# mksafe(stream)

# Copy encoder settings(?) or coded data(?) for the rtmp stream
enc = %ffmpeg(
  format="flv",
  %audio.copy,
  %video.copy)


# Send to YouTube
url = "rtmp://a.rtmp.youtube.com/live2/#{key}"
output.url(url=url, enc, stream)

```
