### ISSUE TITLE
".next" vs ".skip" on playlist

### ISSUE THREAD

**Issue by jonathanstowe** [savonet/liquidsoap#1678]
**Describe the bug**

It seems that in v2.0.0  (and HEAD,) the `.next` server command on a `playlist` has been replaced by `.skip` - it would be nice if `.next` was available (even as an "alias" for `.skip`) to allow integrations to work with both versions.

**To Reproduce**

Script thus:

```
#!/usr/bin/env liquidsoap

set("log.file", false)
set("log.stdout", true)
set("server.telnet", true)
set("harbor.bind_addr","127.0.0.1")
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port",9985)
set("init.allow_root",true)


default = playlist(id="default-playlist","t/data/play")

radio = fallback(track_sensitive=false,[default, blank()])

output.dummy(id="dummy-output", radio)
```

`help` output on v1.4.4:

```
| default-playlist.next
| default-playlist.reload
| default-playlist.uri [<URI>]
```

`help` output on Liquidsoap 2.0.0+git@54dd901b:

```
| default-playlist.reload
| default-playlist.skip
| default-playlist.uri [<uri>]
```

**Expected behavior**

The `.next` command should be available for at least a transitional period (perhaps with a deprecation warning in the logs,) so existing integrations can continue to work without jumping through too many hoops.  I appreciate  the consistency of using `.skip` wherever it makes sense, but `.next` also makes sense for me in the context of a playlist as that's literally what it does.

**Version details**
 - OS:  Debian Buster as per the docker image
 - Version Liquidsoap 2.0.0+git@54dd901b

**Install method**

Docker image based on the liquidsoap:main

**Comment by smimram** [comment]
First thanks for all your reports, keep them coming, this is really helpful!

You can register a `next` function like this:
```
default = playlist(id="default-playlist","t/data/play")
server.register("next", fun(_) -> begin default.skip(); "OK" end)
```
Do you think that adding this to the documentation somewhere would be enough? (maybe could we start a migration page) Or do you think it's better to add `next` with a warning for now?

**Comment by jonathanstowe** [comment]
So yes, with the v2.0.0 the 

```
server.register("default-playlist.next", fun(_) -> begin default.skip(); "OK" end)
```

Does exactly the right thing, however with v1.4.4 it will get (for obvious reasons,):

```
Error 4: Undefined variable default.skip
```

Which may be a problem if one wasn't sure in advance which version the script was going to be run on.

Is there a way to conditionally add the registration?  Either by determining the running version of LS or checking whether the playlist has the `skip` function for instance?  Or would that even work as the `default.skip` will be referenced anyway (I'm not sure how the language parser works in detail.)

In the case of my code (https://github.com/jonathanstowe/Audio-Liquidsoap ) I can make it do the right thing based on the running LS, but this might not be the case everywhere.

So I would be leaning toward adding back the `.next` as an alias for `.skip` for a transitional period with a warning then remove it again in a later version (even v2.0.1 say)  then all of those things that are going to be treated that way can be documented in one place.

But yes a migration guide would be a useful thing too.

**Comment by jonathanstowe** [comment]
Nice one.
