### ISSUE TITLE
last.fm appears to be broken in 2.0.0 / main

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1680]
I have `main` installed / pinned via opam on Debian Buster. 
A very minimal script with lines of the last.fm code is attached below
When the lines of last.fm code in the script are uncommented, the script won't start.
However, if you comment out those lines, the script runs fine.

[lastfm-enabled.liq.txt](https://github.com/savonet/liquidsoap/files/6615413/lastfm-enabled.liq.txt)

I suspect there have been developments in `main` that aren't accounted for in the code I'm using in my script. Any help is appreciated.

**Comment by toots** [comment]
Hi! 

Could you also send the logs? This script runs fine here:
```
s = blank()

def lastfm.submit(~user,~password,~source="broadcast",~length=false,m) =
  audioscrobbler.submit(
    user=user,password=password,
    source=source,length=length,
    host="post.audioscrobbler.com",port=80,m
  )
end

s.on_metadata(lastfm.submit(user="USERNAME",password="PASSWORD"))

output.dummy(s)
```

**Comment by oranjebloom** [comment]
@toots I installed all dependencies via opam with a compiler version 4.08.0. I then pinned `main` after cloning from GitHub.
Could the installation method is the problem?

**Comment by dhannyz** [comment]
Is this due to the shift to ocurl? I had that issue earlier.

**Comment by toots** [comment]
> Is this due to the shift to ocurl? I had that issue earlier.

Yeah that's probably what it is. @oranjebloom have you installed `ocurl` via `opam`?

**Comment by oranjebloom** [comment]
yep, that was it. Installing ocurl fixed it. Thanks @toots and @dhannyz
