### ISSUE TITLE
How to use  Liquidsoap's docker image

### ISSUE THREAD

**Issue by jonahzheng** [savonet/liquidsoap#1681]
os: ubuntu 18.04
wanted to install version 1.4.3, but could not find the DEB of Ubuntu 18.04.

**Comment by jonathanstowe** [comment]
I run the docker image like:

```
docker run --entrypoint bash -it -p 9985:9985 -v `pwd`:/home/liquidsoap -w /home/liquidsoap --rm savonet/liquidsoap:v1.4.4 -c "liquidsoap test-resources.liq"
```
Obviously you'd need to adjust the port mapping as per your needs, and the name of the script to be run.
