### ISSUE TITLE
Missing start/stop/status on output in server interface for v2.0.0

### ISSUE THREAD

**Issue by jonathanstowe** [savonet/liquidsoap#1686]
**Describe the bug**

It seems that the `.start`, `.stop`, `.status` and `.autostart` commands are missing from the server interface for outputs, I'm guessing this is an oversight as they are quite useful in various integrations.

**To Reproduce**

Given this script (I've put two outputs just to check it isn't specific to one type of output):

```#!/usr/bin/env liquidsoap

set("log.stdout", true)
set("server.telnet", true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port",9985)
set("init.allow_root",true)

outblank = blank(id="blanky")

output.dummy(id="dummy-output", outblank)

output.icecast( %mp3( bitrate=160), mount = "blank", host = "127.0.0.1", port = 8000, password = "hackme", outblank);


```

For `help` in the server interface for v1.4.4 I get:

```
| blank.autostart
| blank.metadata
| blank.remaining
| blank.skip
| blank.start
| blank.status
| blank.stop
| dummy-output.autostart
| dummy-output.metadata
| dummy-output.remaining
| dummy-output.skip
| dummy-output.start
| dummy-output.status
| dummy-output.stop

```
Whereas in the `Liquidsoap 2.0.0+git@39423f8d` I get:

```
| blank.metadata
| blank.remaining
| blank.skip
| dummy-output.metadata
| dummy-output.remaining
| dummy-output.skip
```

**Expected behavior**

server commands on the outputs as v1.4.4 

(sorry about the flurry of these, I'm running my existing tests which worked for v1.4.4 and adding issues as the previous tests pass,)

**Version details**
 - OS:  Debian as per the Docker image
 - Version Liquidsoap 2.0.0+git@39423f8d

**Install method**

Docker image based on `main`

**Comment by toots** [comment]
Working on it!

**Comment by jonathanstowe** [comment]
Cheers I'll take a look when the new `main` docker image drops
