### ISSUE TITLE
Cannot make my OPUS stream play in mono

### ISSUE THREAD

**Issue by ivellios1988** [savonet/liquidsoap#1694]
With reference to: https://github.com/AzuraCast/AzuraCast/issues/4275

**Describe the bug**
I use Liquidsoap as a part of my AzuraCast installation. I have some streams in OPUS format, one of them plays in 24kbps. Everything worked and sounded pretty fine, stream played in mono, until recent update of AzuraCast I made last week, after which I discovered that this particular stream started to play in stereo. As one might expect from such a low bitrate, using stereo mode causes a lot of artifacts. So I decided to somehow force it to play in mono again... but everything I try results in Liquidsoap failing to start and producing error messages.

**To Reproduce**
1) use AzuraCast
2) create an OPUS stream with 32kbps
3) manually edit liquidsoap.liq file - change bitrate to 24kbps and make this file read-only
4) restart Liquidsoap

Aaarghhh, stream starts playing in stereo and sounds like... like... aaaaarghhh...

5) edit liquidsoap.liq, following Liquidsoap's documentation:
- set channels=1
OR
- set stereo="false"
OR
- set mono="true"
6) restart Liquidsoap

**Expected behavior**
Stream should start playing in mono.

**Version details**
 - OS: Ubuntu 18.04
 - Version [e.g. `1.3.4`]

**Install method**
AzuraCast installed using Docker method

**Comment by toots** [comment]
Looks like it's been fixed in AzuraCast.
