### ISSUE TITLE
Cannot clock encoders anymore

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#1699]
I just found out that the recent change concerning active sources has a very unfortunate side effect: we cannot change the clock of an encoder anymore. For instance, the following pattern was quite useful to put an encoder in its own clock and thus use multiple cores:
```
a = single("video.mkv")
b = single("video.mkv")
output.file(%theora, "/tmp/a.ogv", a)
clock(output.file(%theora, "/tmp/b.ogv", b))
```
This does not work anymore because the type of `output.file` is now `unit`. ~~I could use `clock` on `b` here I guess, but~~ do we want to lose the above way of proceeding?

**Comment by toots** [comment]
You can! You just have to assign it to the underlying source:
```
a = single("video.mkv")
b = single("video.mkv")
clock(b)
output.file(%theora, "/tmp/a.ogv", a)
output.file(%theora, "/tmp/b.ogv", b)
```

**Comment by toots** [comment]
Closing, let me know if there's anything more we can do.
