### ISSUE TITLE
Execution of input.http returning error

### ISSUE THREAD

**Issue by 918483** [savonet/liquidsoap#1707]
Execution of `input.http` returning error after using liquidsoap 2.0 beta1
```
funcao_relay = audio_to_stereo(input.http(id="relay_27006", "http://01.painelstreaming.com.br:7062"))
```

**Comment by smimram** [comment]
Could you also show us the error that you have?

**Comment by 918483** [comment]
after using 

funcao_relay = audio_to_stereo(input.http(id="inicia_relay_27006", autostart=false, "http://01.painelstreaming.com.br:7062"))

Returns me the following error observation in 2.0 alpha was normal

Error 5: this value has type
  ((?id : string, ?start : bool, ?on_start : (() -> unit),
    ?on_stop : (() -> unit), ?fallible : bool) ->
   active_source(audio=pcm(?A), video=?B, midi=?C)
   .{
     time : () -> float,
     shutdown : () -> unit,
     fallible : () -> bool,
     skip : () -> unit,
     seek : (float) -> float,
     is_up : () -> bool,
     remaining : () -> float,
     on_track : ((([string * string]) -> unit)) -> unit,
     on_leave : ((() -> unit)) -> unit,
     on_shutdown : ((() -> unit)) -> unit,
     on_metadata : ((([string * string]) -> unit)) -> unit,
     is_ready : () -> bool,
     id : (() -> string)})
  .{
    keyboard : 'a.'b.(?id : string) ->
                     source(audio='a, video='b, midi=midi(channels=1))
                     .{
                       time : () -> float,
                       shutdown : () -> unit,
                       fallible : () -> bool,
                       skip : () -> unit,
                       seek : (float) -> float,
                       is_up : () -> bool,
                       remaining : () -> float,
                       on_track : ((([string * string]) -> unit)) -> unit,
                       on_leave : ((() -> unit)) -> unit,
                       on_shutdown : ((() -> unit)) -> unit,
                       on_metadata : ((([string * string]) -> unit)) -> unit,
                       is_ready : () -> bool,
                       id : (() -> string)},
    oss : 'a.'b.'c.(?id : string, ?clock_safe : bool, ?device : string,
                    ?fallible : bool, ?on_start : (() -> unit),
                    ?on_stop : (() -> unit), ?start : bool) ->
                   active_source(audio=pcm('a), video='b, midi='c)
                   .{
                     time : () -> float,
                     shutdown : () -> unit,
                     fallible : () -> bool,
                     skip : () -> unit,
                     seek : (float) -> float,
                     is_up : () -> bool,
                     remaining : () -> float,
                     on_track : ((([string * string]) -> unit)) -> unit,
                     on_leave : ((() -> unit)) -> unit,
                     on_shutdown : ((() -> unit)) -> unit,
                     on_metadata : ((([string * string]) -> unit)) -> unit,
                     is_ready : () -> bool,
                     id : (() -> string)},
    mplayer : 'a.'b.'c.(?id : string, ?restart : bool,
                        ?restart_on_error : bool, ?buffer : float,
                        ?max : float, string) ->
                       source(audio=pcm('a), video='b, midi='c)
                       .{
                         time : () -> float,
                         shutdown : () -> unit,
                         fallible : () -> bool,
                         skip : () -> unit,
                         seek : (float) -> float,
                         is_up : () -> bool,
                         remaining : () -> float,
                         on_track : ((([string * string]) -> unit)) -> unit,
                         on_leave : ((() -> unit)) -> unit,
                         on_shutdown : ((() -> unit)) -> unit,
                         on_metadata : ((([string * string]) -> unit)) ->
                                       unit,
                         is_ready : () -> bool,
                         id : (() -> string)},
    hls : (?id : string, string) -> source(audio=?D, video=?E, midi=?F)
          .{
            time : () -> float,
            shutdown : () -> unit,
            fallible : () -> bool,
            skip : () -> unit,
            seek : (float) -> float,
            is_up : () -> bool,
            remaining : () -> float,
            on_track : ((([string * string]) -> unit)) -> unit,
            on_leave : ((() -> unit)) -> unit,
            on_shutdown : ((() -> unit)) -> unit,
            on_metadata : ((([string * string]) -> unit)) -> unit,
            is_ready : () -> bool,
            id : (() -> string)},
    external : 'a.'b.'c.((?id : string, ?buffer : float, ?channels : int,
                          ?log_overfull : bool, ?max : float,
                          ?restart : bool, ?restart_on_error : bool,
                          ?samplerate : int) ->
                         (string) -> source(audio=pcm('a), video='b, midi='c)
                         .{
                           time : () -> float,
                           shutdown : () -> unit,
                           fallible : () -> bool,
                           skip : () -> unit,
                           seek : (float) -> float,
                           is_up : () -> bool,
                           remaining : () -> float,
                           on_track : ((([string * string]) -> unit)) -> unit,
                           on_leave : ((() -> unit)) -> unit,
                           on_shutdown : ((() -> unit)) -> unit,
                           on_metadata : ((([string * string]) -> unit)) ->
                                         unit,
                           is_ready : () -> bool,
                           id : (() -> string)})
    .{
      rawaudio : 'd.'e.'f.(?id : string, ?buffer : float, ?channels : int,
                           ?log_overfull : bool, ?max : float,
                           ?restart : bool, ?restart_on_error : bool,
                           ?samplerate : int, string) ->
                          source(audio=pcm('d), video='e, midi='f)
                          .{
                            time : () -> float,
                            shutdown : () -> unit,
                            fallible : () -> bool,
                            skip : () -> unit,
                            seek : (float) -> float,
                            is_up : () -> bool,
                            remaining : () -> float,
                            on_track : ((([string * string]) -> unit)) ->
                                       unit,
                            on_leave : ((() -> unit)) -> unit,
                            on_shutdown : ((() -> unit)) -> unit,
                            on_metadata : ((([string * string]) -> unit)) ->
                                          unit,
                            is_ready : () -> bool,
                            id : (() -> string)},
      wav : 'd.'e.'f.(?id : string, ?buffer : float, ?log_overfull : bool,
                      ?max : float, ?restart : bool,
                      ?restart_on_error : bool, string) ->
                     source(audio=pcm('d), video='e, midi='f)
                     .{
                       time : () -> float,
                       shutdown : () -> unit,
                       fallible : () -> bool,
                       skip : () -> unit,
                       seek : (float) -> float,
                       is_up : () -> bool,
                       remaining : () -> float,
                       on_track : ((([string * string]) -> unit)) -> unit,
                       on_leave : ((() -> unit)) -> unit,
                       on_shutdown : ((() -> unit)) -> unit,
                       on_metadata : ((([string * string]) -> unit)) -> unit,
                       is_ready : () -> bool,
                       id : (() -> string)},
      rawvideo : 'd.'e.'f.(?id : string, ?buffer : float,
                           ?log_overfull : bool, ?max : float,
                           ?restart : bool, ?restart_on_error : bool, string) ->
                          source(audio='d, video=yuva420p('e), midi='f)
                          .{
                            time : () -> float,
                            shutdown : () -> unit,
                            fallible : () -> bool,
                            skip : () -> unit,
                            seek : (float) -> float,
                            is_up : () -> bool,
                            remaining : () -> float,
                            on_track : ((([string * string]) -> unit)) ->
                                       unit,
                            on_leave : ((() -> unit)) -> unit,
                            on_shutdown : ((() -> unit)) -> unit,
                            on_metadata : ((([string * string]) -> unit)) ->
                                          unit,
                            is_ready : () -> bool,
                            id : () -> string,
                            buffer_length : (() -> float * float * float)},
      ffmpeg : 'd.(?id : string, ?show_command : bool, ?restart : bool,
                   ?restart_on_error : bool, ?buffer : float, ?max : float,
                   string) ->
                  source(audio=pcm(stereo), video=yuva420p('d), midi=none),
      avi : 'd.'e.((?id : string, ?buffer : float, ?log_overfull : bool,
                    ?max : float, ?restart : bool, ?restart_on_error : bool,
                    string) ->
                   source(audio=pcm('d), video=yuva420p('e), midi=none)
                   .{
                     time : () -> float,
                     shutdown : () -> unit,
                     fallible : () -> bool,
                     skip : () -> unit,
                     seek : (float) -> float,
                     is_up : () -> bool,
                     remaining : () -> float,
                     on_track : ((([string * string]) -> unit)) -> unit,
                     on_leave : ((() -> unit)) -> unit,
                     on_shutdown : ((() -> unit)) -> unit,
                     on_metadata : ((([string * string]) -> unit)) -> unit,
                     is_ready : () -> bool,
                     id : () -> string,
                     buffer_length : (() -> float * float * float)})
    },
    harbor : 'a.((?id : string,
                  ?auth : ((
                            {
                              password : string,
                              user : string,
                              address : string
                            }) -> bool)?,
                  ?buffer : float, ?debug : bool, ?dumpfile : string?,
                  ?icy : bool, ?icy_metadata_charset : string?,
                  ?log_overfull : bool, ?logfile : string?, ?max : float,
                  ?metadata_charset : string?,
                  ?on_connect : (([string * string]) -> unit),
                  ?on_disconnect : (() -> unit), ?password : string,
                  ?port : int, ?replay_metadata : bool, ?timeout : float,
                  ?user : string, string) -> source('a)
                 .{
                   time : () -> float,
                   shutdown : () -> unit,
                   fallible : () -> bool,
                   skip : () -> unit,
                   seek : (float) -> float,
                   is_up : () -> bool,
                   remaining : () -> float,
                   on_track : ((([string * string]) -> unit)) -> unit,
                   on_leave : ((() -> unit)) -> unit,
                   on_shutdown : ((() -> unit)) -> unit,
                   on_metadata : ((([string * string]) -> unit)) -> unit,
                   is_ready : () -> bool,
                   id : () -> string,
                   buffer_length : () -> float,
                   status : () -> string,
                   connected_client : () -> string?,
                   stop : (() -> unit)})
  } (inferred at line 439 char 0 - line 460 char 3)
but it should be a subtype of the type of the value at line 68, char 31-41

**Comment by 918483** [comment]
after using

funcao_relay = audio_to_stereo (input.http (id = "inicia_relay_27006", autostart = false, " http://01.painelstreaming.com.br:7062 "))

Returns the following observation in 2.0 alpha was normal

At line 68, char 31-36:
Error 5: this value has type
  ((?id : string, ?start : bool, ?on_start : (() -> unit),
    ?on_stop : (() -> unit), ?fallible : bool) ->
   active_source(audio=pcm(?A), video=?B, midi=?C)
   .{
     time : () -> float,
     shutdown : () -> unit,
     fallible : () -> bool,
     skip : () -> unit,
     seek : (float) -> float,
     is_up : () -> bool,
     remaining : () -> float,
     on_track : ((([string * string]) -> unit)) -> unit,
     on_leave : ((() -> unit)) -> unit,
     on_shutdown : ((() -> unit)) -> unit,
     on_metadata : ((([string * string]) -> unit)) -> unit,
     is_ready : () -> bool,
     id : (() -> string)})
  .{
    keyboard : 'a.'b.(?id : string) ->
                     source(audio='a, video='b, midi=midi(channels=1))
                     .{
                       time : () -> float,
                       shutdown : () -> unit,
                       fallible : () -> bool,
                       skip : () -> unit,
                       seek : (float) -> float,
                       is_up : () -> bool,
                       remaining : () -> float,
                       on_track : ((([string * string]) -> unit)) -> unit,
                       on_leave : ((() -> unit)) -> unit,
                       on_shutdown : ((() -> unit)) -> unit,
                       on_metadata : ((([string * string]) -> unit)) -> unit,
                       is_ready : () -> bool,
                       id : (() -> string)},
    oss : 'a.'b.'c.(?id : string, ?clock_safe : bool, ?device : string,
                    ?fallible : bool, ?on_start : (() -> unit),
                    ?on_stop : (() -> unit), ?start : bool) ->
                   active_source(audio=pcm('a), video='b, midi='c)
                   .{
                     time : () -> float,
                     shutdown : () -> unit,
                     fallible : () -> bool,
                     skip : () -> unit,
                     seek : (float) -> float,
                     is_up : () -> bool,
                     remaining : () -> float,
                     on_track : ((([string * string]) -> unit)) -> unit,
                     on_leave : ((() -> unit)) -> unit,
                     on_shutdown : ((() -> unit)) -> unit,
                     on_metadata : ((([string * string]) -> unit)) -> unit,
                     is_ready : () -> bool,
                     id : (() -> string)},
    mplayer : 'a.'b.'c.(?id : string, ?restart : bool,
                        ?restart_on_error : bool, ?buffer : float,
                        ?max : float, string) ->
                       source(audio=pcm('a), video='b, midi='c)
                       .{
                         time : () -> float,
                         shutdown : () -> unit,
                         fallible : () -> bool,
                         skip : () -> unit,
                         seek : (float) -> float,
                         is_up : () -> bool,
                         remaining : () -> float,
                         on_track : ((([string * string]) -> unit)) -> unit,
                         on_leave : ((() -> unit)) -> unit,
                         on_shutdown : ((() -> unit)) -> unit,
                         on_metadata : ((([string * string]) -> unit)) ->
                                       unit,
                         is_ready : () -> bool,
                         id : (() -> string)},
    hls : (?id : string, string) -> source(audio=?D, video=?E, midi=?F)
          .{
            time : () -> float,
            shutdown : () -> unit,
            fallible : () -> bool,
            skip : () -> unit,
            seek : (float) -> float,
            is_up : () -> bool,
            remaining : () -> float,
            on_track : ((([string * string]) -> unit)) -> unit,
            on_leave : ((() -> unit)) -> unit,
            on_shutdown : ((() -> unit)) -> unit,
            on_metadata : ((([string * string]) -> unit)) -> unit,
            is_ready : () -> bool,
            id : (() -> string)},
    external : 'a.'b.'c.((?id : string, ?buffer : float, ?channels : int,
                          ?log_overfull : bool, ?max : float,
                          ?restart : bool, ?restart_on_error : bool,
                          ?samplerate : int) ->
                         (string) -> source(audio=pcm('a), video='b, midi='c)
                         .{
                           time : () -> float,
                           shutdown : () -> unit,
                           fallible : () -> bool,
                           skip : () -> unit,
                           seek : (float) -> float,
                           is_up : () -> bool,
                           remaining : () -> float,
                           on_track : ((([string * string]) -> unit)) -> unit,
                           on_leave : ((() -> unit)) -> unit,
                           on_shutdown : ((() -> unit)) -> unit,
                           on_metadata : ((([string * string]) -> unit)) ->
                                         unit,
                           is_ready : () -> bool,
                           id : (() -> string)})
    .{
      rawaudio : 'd.'e.'f.(?id : string, ?buffer : float, ?channels : int,
                           ?log_overfull : bool, ?max : float,
                           ?restart : bool, ?restart_on_error : bool,
                           ?samplerate : int, string) ->
                          source(audio=pcm('d), video='e, midi='f)
                          .{
                            time : () -> float,
                            shutdown : () -> unit,
                            fallible : () -> bool,
                            skip : () -> unit,
                            seek : (float) -> float,
                            is_up : () -> bool,
                            remaining : () -> float,
                            on_track : ((([string * string]) -> unit)) ->
                                       unit,
                            on_leave : ((() -> unit)) -> unit,
                            on_shutdown : ((() -> unit)) -> unit,
                            on_metadata : ((([string * string]) -> unit)) ->
                                          unit,
                            is_ready : () -> bool,
                            id : (() -> string)},
      wav : 'd.'e.'f.(?id : string, ?buffer : float, ?log_overfull : bool,
                      ?max : float, ?restart : bool,
                      ?restart_on_error : bool, string) ->
                     source(audio=pcm('d), video='e, midi='f)
                     .{
                       time : () -> float,
                       shutdown : () -> unit,
                       fallible : () -> bool,
                       skip : () -> unit,
                       seek : (float) -> float,
                       is_up : () -> bool,
                       remaining : () -> float,
                       on_track : ((([string * string]) -> unit)) -> unit,
                       on_leave : ((() -> unit)) -> unit,
                       on_shutdown : ((() -> unit)) -> unit,
                       on_metadata : ((([string * string]) -> unit)) -> unit,
                       is_ready : () -> bool,
                       id : (() -> string)},
      rawvideo : 'd.'e.'f.(?id : string, ?buffer : float,
                           ?log_overfull : bool, ?max : float,
                           ?restart : bool, ?restart_on_error : bool, string) ->
                          source(audio='d, video=yuva420p('e), midi='f)
                          .{
                            time : () -> float,
                            shutdown : () -> unit,
                            fallible : () -> bool,
                            skip : () -> unit,
                            seek : (float) -> float,
                            is_up : () -> bool,
                            remaining : () -> float,
                            on_track : ((([string * string]) -> unit)) ->
                                       unit,
                            on_leave : ((() -> unit)) -> unit,
                            on_shutdown : ((() -> unit)) -> unit,
                            on_metadata : ((([string * string]) -> unit)) ->
                                          unit,
                            is_ready : () -> bool,
                            id : () -> string,
                            buffer_length : (() -> float * float * float)},
      ffmpeg : 'd.(?id : string, ?show_command : bool, ?restart : bool,
                   ?restart_on_error : bool, ?buffer : float, ?max : float,
                   string) ->
                  source(audio=pcm(stereo), video=yuva420p('d), midi=none),
      avi : 'd.'e.((?id : string, ?buffer : float, ?log_overfull : bool,
                    ?max : float, ?restart : bool, ?restart_on_error : bool,
                    string) ->
                   source(audio=pcm('d), video=yuva420p('e), midi=none)
                   .{
                     time : () -> float,
                     shutdown : () -> unit,
                     fallible : () -> bool,
                     skip : () -> unit,
                     seek : (float) -> float,
                     is_up : () -> bool,
                     remaining : () -> float,
                     on_track : ((([string * string]) -> unit)) -> unit,
                     on_leave : ((() -> unit)) -> unit,
                     on_shutdown : ((() -> unit)) -> unit,
                     on_metadata : ((([string * string]) -> unit)) -> unit,
                     is_ready : () -> bool,
                     id : () -> string,
                     buffer_length : (() -> float * float * float)})
    },
    harbor : 'a.((?id : string,
                  ?auth : ((
                            {
                              password : string,
                              user : string,
                              address : string
                            }) -> bool)?,
                  ?buffer : float, ?debug : bool, ?dumpfile : string?,
                  ?icy : bool, ?icy_metadata_charset : string?,
                  ?log_overfull : bool, ?logfile : string?, ?max : float,
                  ?metadata_charset : string?,
                  ?on_connect : (([string * string]) -> unit),
                  ?on_disconnect : (() -> unit), ?password : string,
                  ?port : int, ?replay_metadata : bool, ?timeout : float,
                  ?user : string, string) -> source('a)
                 .{
                   time : () -> float,
                   shutdown : () -> unit,
                   fallible : () -> bool,
                   skip : () -> unit,
                   seek : (float) -> float,
                   is_up : () -> bool,
                   remaining : () -> float,
                   on_track : ((([string * string]) -> unit)) -> unit,
                   on_leave : ((() -> unit)) -> unit,
                   on_shutdown : ((() -> unit)) -> unit,
                   on_metadata : ((([string * string]) -> unit)) -> unit,
                   is_ready : () -> bool,
                   id : () -> string,
                   buffer_length : () -> float,
                   status : () -> string,
                   connected_client : () -> string?,
                   stop : (() -> unit)})
  } (inferred at line 439 char 0 - line 460 char 3)
but it should be a subtype of the type of the value at line 68, char 31-41

**Comment by smimram** [comment]
This looks like the same bug as in #1693.

**Comment by smimram** [comment]
More precisely, you should install ffmpeg-av. For instance, if you use opam:
```
opam install ffmpeg-av
```

**Comment by 918483** [comment]
all library is installed as below

libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100

but when I run the command

opam install ffmpeg-av

returns the following error

[ffmpeg-av.1.0.0~beta1] found in cache
[ffmpeg-avcodec.1.0.0~beta1] found in cache
[ffmpeg-avutil.1.0.0~beta1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ffmpeg-avutil failed at "/root/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avutil -j 5 @install".

#=== ERROR while compiling ffmpeg-avutil.1.0.0~beta1 ==========================#
# context     2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.0 | https://opam.ocaml.org#2f66dcb5
# path        ~/.opam/4.12.0/.opam-switch/build/ffmpeg-avutil.1.0.0~beta1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avutil -j 5 @install
# exit-code   1
# env-file    ~/.opam/log/ffmpeg-avutil-26998-2dea01.env
# output-file ~/.opam/log/ffmpeg-avutil-26998-2dea01.out
### output ###
#     discover avutil/c_flags,avutil/c_flags.sexp,avutil/c_library_flags.sexp (exit 2)
# (cd _build/default/avutil && config/discover.exe)
# which: pkg-config
# -> found: /usr/bin/pkg-config
# run: /usr/bin/pkg-config --print-errors 'libavutil >= 55.78.100, libavcodec >= 57.107.100'
# -> process exited with code 1
# -> stdout:
# -> stderr:
#  | Requested 'libavutil >= 55.78.100' but version of libavutil is 54.31.100
#  | Requested 'libavcodec >= 57.107.100' but version of libavcodec is 56.60.100
# Fatal error: exception Failure("Requested 'libavutil >= 55.78.100' but version of libavutil is 54.31.100\nRequested 'libavcodec >= 57.107.100' but version of libavcodec is 56.60.100\n")



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ffmpeg-avutil 1.0.0~beta1
└─
╶─ No changes have been performed

**Comment by smimram** [comment]
Basically, your version of FFmpeg libraires are too old. Do you have a way to upgrade them?

@toots would it be possible to fallback on the old in-house version of input.http if FFmpeg is not present?

**Comment by smimram** [comment]
Oh wait. Could you try
```
opam install ocurl
```

**Comment by 918483** [comment]
in this case if i already tried to remove ffmpeg and i wasn't successful i installed ocurl too and i was also unsuccessful but an previous version was using input.http i believe that in beta1 it was removed then?
I used it to relay other ip:port directly on my server I wanted to find a way out so I don't need to go back to the previous version of liquidsoap

**Comment by 918483** [comment]
would have any way to solve this problem or even be able to use the input.http ?

**Comment by 918483** [comment]
@toots Can you help me?

**Comment by toots** [comment]
@918483 what OS are you using to build liquidsoap?

**Comment by 918483** [comment]
centos7 + icecast + shoutcast @toots

**Comment by 918483** [comment]
@toots  Can you help me?

**Comment by toots** [comment]
@918483 How do you install ffmpeg? Centos7 was first released in 2014, that's a pretty old OS. There are instructions here on how to install ffmpeg: https://linuxize.com/post/how-to-install-ffmpeg-on-centos-7/

**Comment by 918483** [comment]
I already have ffmpeg installed and working on my machine what would I like to know and how will I change this line down to ffmpeg?

function_relay = audio_to_stereo (input.http (id = "inicia_relay_27006", autostart = false, " http://01.panelstreaming.com.br:7062 "))

**Comment by toots** [comment]
@918483 I thought that your problem was that your version of ffmpeg was too old? Are you still seeing this:
```
[ffmpeg-av.1.0.0~beta1] found in cache
[ffmpeg-avcodec.1.0.0~beta1] found in cache
[ffmpeg-avutil.1.0.0~beta1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ffmpeg-avutil failed at "/root/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avutil -j 5 @install".

#=== ERROR while compiling ffmpeg-avutil.1.0.0~beta1 ==========================#
# context     2.0.8 | linux/x86_64 | ocaml-base-compiler.4.12.0 | https://opam.ocaml.org#2f66dcb5
# path        ~/.opam/4.12.0/.opam-switch/build/ffmpeg-avutil.1.0.0~beta1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avutil -j 5 @install
# exit-code   1
# env-file    ~/.opam/log/ffmpeg-avutil-26998-2dea01.env
# output-file ~/.opam/log/ffmpeg-avutil-26998-2dea01.out
### output ###
#     discover avutil/c_flags,avutil/c_flags.sexp,avutil/c_library_flags.sexp (exit 2)
# (cd _build/default/avutil && config/discover.exe)
# which: pkg-config
# -> found: /usr/bin/pkg-config
# run: /usr/bin/pkg-config --print-errors 'libavutil >= 55.78.100, libavcodec >= 57.107.100'
# -> process exited with code 1
# -> stdout:
# -> stderr:
#  | Requested 'libavutil >= 55.78.100' but version of libavutil is 54.31.100
#  | Requested 'libavcodec >= 57.107.100' but version of libavcodec is 56.60.100
# Fatal error: exception Failure("Requested 'libavutil >= 55.78.100' but version of libavutil is 54.31.100\nRequested 'libavcodec >= 57.107.100' but version of libavcodec is 56.60.100\n")



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ffmpeg-avutil 1.0.0~beta1
└─
╶─ No changes have been performed
```

**Comment by 918483** [comment]
yes I see this when I run opam install ffmpeg-av but I already have the ffmpeg installed in the hundreds there is no way to use the input.http as in the previous version?

**Comment by 918483** [comment]
that's all it takes to stay as it was in the previous version on my system

**Comment by 918483** [comment]
@toots  if you can tell me something that I can use instead of input.http or even use it in some way, please let me know because I use it to retransmit another stream inside my server starting with telnet commands?

**Comment by toots** [comment]
@918483 Do you need to use the development version? I'd recommend to stick with `1.4.4` for now in your case.

**Comment by 918483** [comment]
ok

**Comment by toots** [comment]
Closing this one, please re-open if needed.

**Comment by 918483** [comment]
How do I use the same code below in version 2.0.4

input.http (id = "inicia_relay_27006", autostart = false, " http://01.panelstreaming.com.br:7062/ ")

I need to broadcast a streaming with a schedule

when i install ffmpeg.1.1.4 it gives the error below


[ERROR] The compilation of ffmpeg-avutil.1.1.4 failed at "dune build -p ffmpeg-avutil -j 1 @install".

#=== ERROR while compiling ffmpeg-avutil.1.1.4 ================================#
# context     2.1.2 | linux/x86_64 | ocaml-base-compiler.4.12.0 | pinned(git+file:///ocaml/ocaml-ffmpeg#main#6ca1aaf1)
# path        ~/.opam/4.12.0/.opam-switch/build/ffmpeg-avutil.1.1.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ffmpeg-avutil -j 1 @install
# exit-code   1
# env-file    ~/.opam/log/ffmpeg-avutil-8404-f9c440.env
# output-file ~/.opam/log/ffmpeg-avutil-8404-f9c440.out
### output ###
# [...]
# avutil_stubs.c:1620:13: error: request for member ‘sw_format’ in something not a structure or union
#    frames_ctx->sw_format = PixelFormat_val(_src_pixel_format);
#              ^
# avutil_stubs.c:1621:13: error: request for member ‘width’ in something not a structure or union
#    frames_ctx->width = Int_val(_width);
#              ^
# avutil_stubs.c:1622:13: error: request for member ‘height’ in something not a structure or union
#    frames_ctx->height = Int_val(_height);
#              ^
# avutil_stubs.c:1625:3: warning: implicit declaration of function ‘av_hwframe_ctx_init’ [-Wimplicit-function-declaration]
#    ret = av_hwframe_ctx_init(hw_frames_ref);
#    ^


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ffmpeg-avutil 1.1.4

**Comment by tyctor** [comment]
hi 
i have same problem 
have you found some solution?

```
soap@124c133e0235:~$ opam install taglib mad lame cry ffmpeg liquidsoap
[NOTE] Package cry is already installed (current version is 0.6.7).
[NOTE] Package lame is already installed (current version is 0.3.6).
[NOTE] Package mad is already installed (current version is 0.5.2).
[NOTE] Package taglib is already installed (current version is 0.3.10).
The following actions will be performed:
  - install ffmpeg-avutil     1.1.6 [required by ffmpeg]
  - install ffmpeg-swscale    1.1.6 [required by ffmpeg]
  - install ffmpeg-avfilter   1.1.6 [required by ffmpeg]
  - install ffmpeg-avcodec    1.1.6 [required by ffmpeg]
  - install ffmpeg-swresample 1.1.6 [required by ffmpeg]
  - install ffmpeg-av         1.1.6 [required by ffmpeg]
  - install ffmpeg-avdevice   1.1.6 [required by ffmpeg]
  - install ffmpeg            1.1.6
  - install liquidsoap        2.1.2
===== 9 to install =====
Do you want to continue? [Y/n] Y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> retrieved ffmpeg.1.1.6  (cached)
-> retrieved ffmpeg-av.1.1.6  (cached)
-> retrieved ffmpeg-avcodec.1.1.6  (cached)
-> retrieved ffmpeg-avdevice.1.1.6  (cached)
-> retrieved ffmpeg-avfilter.1.1.6  (cached)
-> retrieved ffmpeg-avutil.1.1.6  (cached)
-> retrieved ffmpeg-swresample.1.1.6  (cached)
-> retrieved ffmpeg-swscale.1.1.6  (cached)
-> retrieved liquidsoap.2.1.2  (cached)
[ERROR] The compilation of ffmpeg-avutil.1.1.6 failed at "dune build -p ffmpeg-avutil -j 7 --promote-install-files=false @install".

#=== ERROR while compiling ffmpeg-avutil.1.1.6 ================================#
# context     2.1.0 | linux/x86_64 | ocaml.4.14.0 | https://opam.ocaml.org#2b389a2b
# path        ~/.opam/default/.opam-switch/build/ffmpeg-avutil.1.1.6
# command     ~/.opam/default/bin/dune build -p ffmpeg-avutil -j 7 --promote-install-files=false @install
# exit-code   1
# env-file    ~/.opam/log/ffmpeg-avutil-33424-815a53.env
# output-file ~/.opam/log/ffmpeg-avutil-33424-815a53.out
### output ###
# avutil_stubs.c:1589:13: error: request for member 'sw_format' in something not a structure or union
# [...]
#              ^~
# avutil_stubs.c:1590:13: error: request for member 'width' in something not a structure or union
#    frames_ctx->width = Int_val(_width);
#              ^~
# avutil_stubs.c:1591:13: error: request for member 'height' in something not a structure or union
#    frames_ctx->height = Int_val(_height);
#              ^~
# avutil_stubs.c:1594:9: warning: implicit declaration of function 'av_hwframe_ctx_init'; did you mean 'av_frame_clone'? [-Wimplicit-function-declaration]
#    ret = av_hwframe_ctx_init(hw_frames_ref);
#          ^~~~~~~~~~~~~~~~~~~
#          av_frame_clone

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ffmpeg-avutil 1.1.6
+- 
- No changes have been performed
# Run eval $(opam env) to update the current shell environment
```

`ffmpeg` version
```
ffmpeg -version
ffmpeg version 4.4.3-0ubuntu1~18.04.sav1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --prefix=/usr --extra-version='0ubuntu1~18.04.sav1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-crystalhd --enable-libmfx --enable-libsvtav1 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-librav1e --enable-shared
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

**Comment by toots** [comment]
It looks like the ffmpeg _library_ you are compiling against is too old. Have you installed the `ffmpeg` command line and library separately or in a different way?
