### ISSUE TITLE
http.post give this has no method post in ver 2.0 (main)

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1708]
Using this code 
```    ignore(http.post(headers=[("Content-Type","application/json"),("Accept","application/json")],data="#{dt}","#{url}"))```

I'm getting this error
```this value has no method post```

The Docs suggest this method is still active, so guessing this may be a bug ?

version 2.0 git(main)

opam install

Arch linux

**Comment by smimram** [comment]
This is #1693 again (I changed the error message to something more clear, but the error is the same).

**Comment by smimram** [comment]
Not exactly sure though. How did you install Liquidsoap? Do you have `ocurl` library enabled?

PS: for @toots, maybe should we define the method `http.post` with a more relevant error message like "please install ocurl"?

**Comment by smimram** [comment]
Just saw that it was opam. Then
```
opam install ocurl
```
Does it help?

**Comment by Russsgithub** [comment]
Yes, I didn't notice the move to ocurl. thank you.

**Comment by toots** [comment]
> PS: for @toots, maybe should we define the method `http.post` with a more relevant error message like "please install ocurl"?

Let's do that. An exception would be great for this.

**Comment by smimram** [comment]
Let's reopen so that we don't forget.

**Comment by toots** [comment]
Done! :-)
