### ISSUE TITLE
input.http does not fail in 2.0

### ISSUE THREAD

**Issue by lesion** [savonet/liquidsoap#1710]
**Describe the bug**
My main source is an http mp3 stream with `alsa` as fallback, I run my examples **without any network** to test the input.http failure and then toggle twice the network status to check that `fallback` is working correctly:
Liquidsoap 1.4.4 example:
```
source_alsa = input.alsa(id='alsa')
source_http = input.http(id='http',  "http://zeppelin.streampunk.cc/_stream/blackout.mp3")
output.dummy( fallback( id='fallback', track_sensitive=false, [source_http, source_alsa] ) )
```
1.4.4 is working correctly:
```
2021/06/24 14:33:34 [fallback:3] Switch to alsa.
# here I wait some seconds and reattach the network so the input.http is working again
2021/06/24 14:33:50 [decoder:3] Method "MAD" accepted "audio/mpeg". 
2021/06/24 14:33:50 [http:3] Decoding...
2021/06/24 14:33:50 [http:3] New metadata chunk: ? -- .
2021/06/24 14:33:50 [fallback:3] Switch to http with transition.
# I remove the network again, fallback is working good switching to alsa again
2021/06/24 14:34:03 [fallback:3] Switch to alsa with forgetful transition.
```

but with the last version -> Liquidsoap 2.0.0-beta1+git@a180ebd8 with minimal modified script (using clock_safe = false):
```
source_alsa = input.alsa(clock_safe=false, id='alsa')
source_http = input.http(id='http',  clock_safe=false, "http://zeppelin.streampunk.cc/_stream/blackout.mp3")
output.dummy( fallback( id='fallback', track_sensitive=false, [source_http, source_alsa] ) )
```

when toggling network status `input.http` is not failing anymore:
```
2021/06/24 14:20:14 [clock.main:3] Streaming loop starts in auto-sync mode
2021/06/24 14:20:14 [clock.main:3] Delegating synchronisation to active sources
2021/06/24 14:20:14 [fallback:3] Switch to alsa.
[tcp @ 0x7fb3d40088c0] Connection to tcp://zeppelin.streampunk.cc:80 failed: Connection timed out
[tcp @ 0x7fb3b40088c0] Connection to tcp://zeppelin.streampunk.cc:80 failed: Connection timed out
# here I wait some seconds and reattach the network so the input.http is working again
2021/06/24 14:20:32 [http:3] New metadata chunk: ? -- .
2021/06/24 14:20:32 [fallback:3] Switch to http with transition.
# When I remove the network again, fallback is not working and alsa is not used anymore
```
Ps. I'm using `sudo iptables -A INPUT -s zeppelin.streampunk.cc -j DROP` and then with `-D` to test network failures...

**Expected behavior**
`fallback` between `input.http` and `input.alsa` when there is a network failure.

**Version details**
 - OS: Debian
 - Version: Liquidsoap 2.0.0-beta1+git@a180ebd8

**Install method**
opam

thanks!

**Comment by 918483** [comment]
Friend, are you able to use input.http in version 2.0 beta1 ? could put your entire script?

**Comment by lesion** [comment]
Ah, this is not supposed to work yet? Sorry I didn't know.

My entire script is that three lines, and I confirm the following is working as expected in Liquidsoap 2.0.0-beta1+git@a180ebd8

```
source = input.http(id='http', clock_safe=false, "http://zeppelin.streampunk.cc/_stream/blackout.mp3")
output.pulseaudio(mksafe(source))
```

**Comment by 918483** [comment]
so in my case the error I posted elsewhere on the forum see below
and I can't use input.http

https://github.com/savonet/liquidsoap/issues/1707

**Comment by toots** [comment]
@lesion thanks for the report. I am testing here but so far it restarts each time. I am simply disabling the wifi. When you say that also is not used again, do you mean that the source streams blank data? Or that it is stuck?

**Comment by toots** [comment]
I just pushed some commits to `main` that may have solved this issue.

**Comment by lesion** [comment]
Nope :/
I'm on last commit -> Liquidsoap 2.0.0+git@32289852
I'm trying this easier script without fallback neither:
```
source_http = input.http(id='http',  "http://zeppelin.streampunk.cc/_stream/blackout.mp3")
output.file(
        %vorbis,
        "/tmp/test.ogg",
        flush=true,
        drop_metadata(mksafe(source_http)))
```
If i disconnect my network, it stucks: nothing is displayed in logs, the file does no longer grows in size, there is no silence inside it, and if I try to ctrl+c it says `2021/06/25 12:47:07 [main:3] Waiting for main threads to terminate...` forever (or until I reactivate the network).

If network is reactivated:
```
2021/06/25 12:42:06 [clock.main:2] Too much latency! Resetting active sources..
```
or 
```
2021/06/25 12:59:41 [clock.main:2] We must catchup 15.70 seconds!
```
(but that 15 second of silence is nowhere inside the file)

Another hint: when started without network, for each `[tcp @ 0x7f49f40088c0] Connection to tcp://zeppelin.streampunk.cc:80 failed: Connection timed out` a chunk of 3 seconds of silence is written in file at each connection retry.

I hope it helps you :heart:

**Comment by toots** [comment]
Yes, it does, thanks. I fixed some issues yesterday that were introduced earlier this week during a rewrite of some of the internal streaming APIs. This is likely to have created this issue as well. Any chance you could try with the latest `main`? In particular, how's the CPU usage going when the issue happen?

**Comment by lesion** [comment]
Another test with Liquidsoap 2.0.0+git@07b9512c with the last script, this is the log:
```
2021/06/25 21:20:10 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/06/25 21:20:10 [sandbox:3] Sandboxing disabled
2021/06/25 21:20:10 [video.converter:3] Using preferred video converter: ffmpeg.
2021/06/25 21:20:10 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/06/25 21:20:10 [clock.main:3] Streaming loop starts in auto-sync mode
2021/06/25 21:20:10 [clock.main:3] Delegating synchronisation to CPU clock
2021/06/25 21:20:10 [mksafe:3] Switch to safe_blank.
2021/06/25 21:20:10 [mksafe:3] Switch to http with transition.
2021/06/25 21:20:10 [http:3] New metadata chunk: ? -- .
# waited ~ 30sec before killing the connection (nothing happens) and restore it after ~1min....
2021/06/25 21:22:42 [clock.main:2] Too much latency! Resetting active sources...
2021/06/25 21:22:42 [mksafe:3] Switch to safe_blank with forgetful transition.
2021/06/25 21:22:43 [mksafe:3] Switch to http with transition.
```
the switch to safe_blank appears together with the http switch, I think it should switch when http buffer is finished.  
cpu usage is <1%

I'm on debian 11.0, please feel free to ask for any tests or more information

**Comment by toots** [comment]
Ok thanks! I just added back a `timeout` parameter with the last commit to `main`. Would you mind testing with it? You should be able to put a low value, default is `10.`.

**Comment by toots** [comment]
Here: https://github.com/savonet/liquidsoap/commit/39049ca789601d731df751367e72f31d406e32d0

**Comment by lesion** [comment]
and here we go :smile:

```
[mp3float @ 0x7fabd409a740] invalid new backstep -1
2021/06/26 01:57:26 [clock.main:2] We must catchup 10.09 seconds!
2021/06/26 01:57:26 [http:2] Feeding failed: FFmpeg.Avutils.Error(Connection timed out)
2021/06/26 01:57:26 [http:2] Error while fetching metadata: Invalid_argument("option is None")
2021/06/26 01:57:26 [mksafe:3] Switch to safe_blank with forgetful transition.
[tcp @ 0x7fabd001cb80] Connection to tcp://zeppelin.streampunk.cc:80 failed: Connection timed out

```
:pray:  thanks!

**Comment by toots** [comment]
Awesome, thanks for reporting!
