### ISSUE TITLE
The source may control its own latency error with append LS 2.0

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1711]
**Describe the bug**
Both append and source.on_end give 

``` The source may control its own latency and cannot be used with this operator.```

error when used as described in docs.

**To Reproduce**
```
def add_silence(m) =
   blank(duration=3.)
end

s = append(s, add_silence)
```

**Expected behavior**
Track to be appended with 3 seconds of silence

**Version details**
 - OS:  - Arch linux
 - Version - 2.0 (git main)

**Install method**
Opam

**Comment by toots** [comment]
Hi @Russsgithub. Thanks for this report! We are adding new functionalities to better detect when a source can or cannot be used in situations where we need to control the rate with which we pull data. Is that source used in a `crossfade` later? 

I have pushed a commit that should make it work for you now.

**Comment by Russsgithub** [comment]
Ok, thanks.
The source is used in a ```crossfade``` later in the script.
