### ISSUE TITLE
https.get

### ISSUE THREAD

**Issue by UseRadio** [savonet/liquidsoap#1715]
I have problem to use https.get for calling a page/server. Liquidsoap says:
 the variable https.get used here has not been previously defined.
I hope you can help me. thanks

**Comment by smimram** [comment]
Which version are you using? In 2.0, you can simply use `http.get` (which now also handles the secure version).

**Comment by UseRadio** [comment]
Ok, I found a way to call webapi
ignore(get_process_lines(curl url))
