### ISSUE TITLE
Syntax error with %audio

### ISSUE THREAD

**Issue by e2489** [savonet/liquidsoap#1727]
Running liquidsoap 1.4.1 on Ubuntu 20.04.2, with this script:
```
output.icecast(%ffmpeg(format="mp3",%audio(codec="libmp3lame",b="128k")),
        format="audio/mpeg",
        port = 8000,
        host = "192.168.1.162",
        mount = "test1",
        password = "hackme",
        source)
```
But I'm getting this error-
```
At line 5, char 36:
Error 3: Syntax error!
```
Which in the full script is the % in %audio

**Comment by smimram** [comment]
You need a more recent version of Liquidsoap for this (I think even 2.0).

**Comment by e2489** [comment]
The [docs page](https://www.liquidsoap.info/doc-1.4.1/encoding_formats.html) says FFmpeg support was added in 1.4.0, is this not accurate?

**Comment by smimram** [comment]
We are both right :) The FFmpeg support was introduced in 1.4.0 but `%audio` is only supported since 2.0. I guess you can make your example work with something like:
```
%ffmpeg(format="mp3",codec="libmp3lame",b="128k")
```

**Comment by e2489** [comment]
Yep, that worked. I'm guessing it's because 1.4.0 supported audio only and now that 2.0 supports video, you need to use %audio to specify. Anyway, all good now. Thanks!
