### ISSUE TITLE
Opam install error of 2.0.0-beta2

### ISSUE THREAD

**Issue by gammaw** [savonet/liquidsoap#1728]
I'm trying to install Liquidsoap 2.0.0-beta2 (f0ec18b495a576b84dc9dfa74e85ec5d15208dbb) and it gives me an the following error 

```
#15 103.1 [ERROR] The compilation of conf-ffmpeg failed at "/usr/bin/pkg-config --exists libavutil libavformat libavcodec libavdevice libavfilter libswresample libswscale".
```

When I try it with 6fc002dd8c27ea4d6849ac3078662d53fd484106 (2.0.0-beta1), it compiles. 

I'm using the following dependencies for `opam install`:

```
ladspa ffmpeg samplerate taglib mad faad fdkaac lame vorbis cry flac opus duppy ssl liquidsoap
```

Do you have a hint for me? My installation is inside a dockerized ubuntu:focal container, if that helps.  

PS: this issue is a duplicate of https://github.com/savonet/liquidsoap/issues/1693#issuecomment-874314352 which I thought is not the best place for this question in a closed and originally unrelated issue.

**Comment by toots** [comment]
Hi! Have you run `opam depext` to install external dependencies? Looking at your OS, it should have the required ffmpeg packages so hope fully that fixes it.

**Comment by gammaw** [comment]
That's a good hint, thank you! Now the installation is successful but when I try to run Liquidsoap, via `liquidsoap --version`, I get the following error (which I don't have with 2.0.0-beta1):

```
liquidsoap: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory
```

Any idea?

**Comment by toots** [comment]
That seems to indicate something off with your ffmpeg install. How did you install it?

**Comment by toots** [comment]
Also, since you are using docker, have you considered using our pre-built docker images?

**Comment by gammaw** [comment]
> That seems to indicate something off with your ffmpeg install. How did you install it?

I guess I found the problem, it seems to be similar to this issue https://github.com/savonet/liquidsoap/issues/1544#issuecomment-857702163 (dynamic loading of dependencies). The problem was that my Dockerfile first built Liquidsoap in a temporary image, then it copied the binary and the libs and some other files to the final image. When I don't copy files and use the image in which Liquidsoap was built, the problem disappeared. 

> Also, since you are using docker, have you considered using our pre-built docker images?

The reason is that we use Liquidsoap with Azuracast and we customise their Dockerfile to build an image with Liquidsoap and Icecast inside. It's a legacy that we'll try to change and work with Liquidsoap images from the Docker Hub instead of building it on our own, but we don't want to change too much at once (currently we're focussing on migrating to Liquidsoap 2.0.0 and replacing the `once` operator with `delay`). 

Thanks for your help, the issues seems to be resolved.

**Comment by toots** [comment]
Happy to hear!
