### ISSUE TITLE
Flac streams with ffmpeg?

### ISSUE THREAD

**Issue by codeofdusk** [savonet/liquidsoap#1729]
Trying to get a flac stream on 2.0 using Ffmpeg. This fragment generates an unplayable stream:

```
output.icecast(%ffmpeg(format="flac",
  %audio(codec="flac")
),
icy_metadata="false",
...,
source)
```

**Comment by codeofdusk** [comment]
CC @toots.

**Comment by smimram** [comment]
Is is better if you put `format="ogg"`? I am not sure that FLAC can act as a container.

**Comment by codeofdusk** [comment]
Yes, `format="ogg"` does work, but metadata doesn't update.

**Comment by toots** [comment]
The ffmpeg encoder does not support in-stream metadata at the moment, I'll investigate that. Meanwhile, you could try to set `icy_metadata` to `true`, I believe icecast is capable of inserting ogg metadata. Also, you could just use the internal `%ogg(%flac))` encoder.
