### ISSUE TITLE
Uncaught runtime error in playlist.liq (2.0.0-beta2)

### ISSUE THREAD

**Issue by gammaw** [savonet/liquidsoap#1732]
Hi, 

I'm running `v2.0.0-beta2` with a custim `liq` file and I'm having the following runtime error: 

```
At /var/azuracast/.opam/ocaml-system.4.08.1/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/playlist.liq, line 256, char 2-62,
at /var/azuracast/.opam/ocaml-system.4.08.1/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/playlist.liq, line 263 char 31 - line 265 char 28,
at /var/azuracast/.opam/ocaml-system.4.08.1/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/playlist.liq, line 263 char 31 - line 265 char 28,
at /var/azuracast/.opam/ocaml-system.4.08.1/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/playlist.liq, line 263 char 2 - line 265 char 28,
at /var/azuracast/.opam/ocaml-system.4.08.1/lib/liquidsoap/share/liquidsoap/2.0.0-beta2/libs/playlist.liq, line 260 char 45 - line 262 char 42, at line 16, char 213:
Error 14: Uncaught runtime error:
type: not_found, message: none
```

In our `liq` file, we have numerous `playlist` definitions, where some of them may not specify a valid URI (non-existing file), but it wasn't a problem with `v1.4.4`. Do you have any idea what goes wrong?

**Comment by toots** [comment]
Thanks for this report. I'll look at it shortly.

**Comment by toots** [comment]
It was a problem on our side in the playlist's watcher implementation. We should not try to setup a watcher if the playlist's file does not exist.

**Comment by gammaw** [comment]
Thanks! It fixed the error, now our script seems to be running for the first time with 2.0.0! Looking forward to start testing the functionality.

**Comment by toots** [comment]
Great! Don't hesitate to checkout the latest `main` every now and then, we're pushing all new bugfixes there.
