### ISSUE TITLE
Ffmpeg mp3 metadata: make more complete and consistent

### ISSUE THREAD

**Issue by codeofdusk** [savonet/liquidsoap#1733]
On Liquidsoap 2.0 (installed using Opam), encoding an mp3 stream with Ffmpeg causes metadata to be partially incomplete (for instance, album and track number are not transmitted) and the metadata sometimes get out-of-sync with the currently-playing track. Ffmpeg flac metadata appears to be more consistent (i.e. stays synchronized) and is more complete.

**Comment by toots** [comment]
Hi & thanks for the report! Could you give more details about this issue? Are you talking about metadata sent via `output.icecast`? Mp3 metadata are sent out-of-band via a HTTP call so they can indeed get slightly out of sync and also the encoder might not matter too much except perhaps for some internal buffering. Have you tried with a different mp3 encoder?

**Comment by toots** [comment]
Following my response above, I don't believe that this is an issue. Feel free to reopen if needed.
