### ISSUE TITLE
Migrating custom transition to version 2.0.0 using fade.out and fade.in

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#1734]
I'm needing some help migrating from version 1.4.4 to 2.0.0 ... I saw it mentioned in the migration document that fade.initial and fade.final are now deprecated in 2.0.0. 

My custom transition uses `fade.initial` and `fade.final `which works in version 2.0.0 for now, but the logs are giving me messages to replace these with `fade.out` and `fade.in` respectively. When I go ahead and replace these the transition no longer fades out. I'm guessing that the transition below requires more than just those two edits. Any advice would be really great. The current working code is below

```
def trans(old, new) =
    source.skip(new)
    sequence(merge=true,[
    fade.final(duration=10.,old),
    fade.initial(duration=0.,new)
  ])
end

sources = [
  #Tuesday#
  ({10h-22h},source2),

  #Default#
  ({true},source1)
]

transitions = list.map(fun (_) -> trans, sources)

radio = switch(
  track_sensitive=false,
  transition_length=10.,
  transitions=transitions,
  sources)
```

**Comment by dhannyz** [comment]
Hey there @oranjebloom I had a similar issue.
Try using `fade.out(track_sensitive=false,...)` and likewise for fade.in
The description what what track_sensitive does in the docs is a bit vague, but it should work like fade.final & fade.initial used to

**Comment by oranjebloom** [comment]
Hi @dhannyz, thanks a bunch mate. Adding `track_sensitive=false` as you suggested to both the `fade.in` and `fade.out` fixed it for me.
