### ISSUE TITLE
Transitions don't work, and give strange behaviour, after fallback added, to watch a request.queue

### ISSUE THREAD

**Issue by Warblefly** [savonet/liquidsoap#1735]
Without a fallback to insert requests submitted by telnet, the crossfades work.

But adding the line:
```
myplaylist = fallback(track_sensitive=true, transition_length=30.0, [request.queue(id="override"), myplaylist])
```
...causes crossfades to stop happening, though the appropriate audio from the request.queue correctly appears.

But, then, it is followed by what sounds like a repeating frame, for about 30 seconds, followed by music continuing.

This begins at time 21:09:39 in the log

The full script, and the log, are attached, within a ZIP file.

Liquidsoap is running on Debian Linux, kernel 5.10.46-1

Installed from source.
[liquidsoap-diag.zip](https://github.com/savonet/liquidsoap/files/6812008/liquidsoap-diag.zip)

**Comment by toots** [comment]
Thanks for this report, much appreciated. Will look at it shortly.

**Comment by toots** [comment]
I can reproduce, thank you. Hopefully the fix comes quickly as well.

**Comment by toots** [comment]
Hi again! @Warblefly what was the last version that worked for you?

**Comment by toots** [comment]
Hi @Warblefly. This should be fixed with the latest `main` branch. Thanks for the report, that was a tricky one. If you use the `ffmpeg` encoder, you will need to also install the latest `master` branch for it, I cleaned up the seeking API as part of the debugging effort..

**Comment by Warblefly** [comment]
Thank you for looking into this. To answer your question, it was 1.4.4 that last worked properly for me.

While the request queue controlled by Telnet will be welcomed, I hope to switch over to the new, 'liquidsoap' language method of doing these news insertions soon. 

The same goes for the FFmpeg audio processing, as you have implemented filters within the language.

best wishes,
JW

**Comment by Warblefly** [comment]
On Sun, 18 Jul 2021 at 17:55, Romain Beauxis ***@***.***>
wrote:

> Hi @Warblefly <https://github.com/Warblefly>. This should be fixed with
> the latest main branch. Thanks for the report, that was a tricky one. If
> you use the ffmpeg encoder, you will need to also install the latest
> master branch for it, I cleaned up the seeking API as part of the
> debugging effort..
>
Hello Romain,

Thank you for fixing the insertion problem.

The odd noises no longer happen.

The start of the log shows liquidsoap is using the FFmpeg master.

Crossfading isn't taking place, however, between tracks on the playlist.

The outgoing track plays right to its end — even though, in the log, there
are entries such as "[crossfade_0:4] Setting crossfade duration to 5.17s"

If you are already working on this, no worries. But if you would like the
latest logs, please let me know.

I found something I didn't understand regarding the
parameter "override_duration", on line 441 of cross.ml.

My guess is probably completely wrong, but I understood my playlist
annotation "liq_cross_duration" was the crossfade duration, not the track
duration? I set duration in the playlist with the annotation "duration".

( "override_duration",
        Lang.string_t,
        Some (Lang.string "liq_cross_duration"),
        Some
          "Metadata field which, if present and containing a float,
overrides \
           the 'duration' parameter for current track." );

with best wishes,
John
