### ISSUE TITLE
Remove metadata containing dots

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1736]
I'm trying to remove metadata keys containing certain characters ( in this instance a dot (.) to get around mongodb logging issues with json keys containing dots )

I've tried using 
```
s = source of some type

def db_call() = 
  if list.assoc.mem(string.contains(substring="."), m)
    list = list.assoc.remove.all(string.contains(substring="."),m)
  end

  dt = json_of(compact=true, list)

   #### post to api code
end

s.on_track(db_call)
```
but get
```
Error 5: this value has type
  (?prefix : string, ?suffix : string, string) -> bool
but it should be a subtype of the type of the value at /home/russ/.opam/ocaml-base-compiler.4.11.1/lib/liquidsoap/share/liquidsoap/git/ee13f438/libs/list.liq, line 293, char 19
  something that is an orderable type
```
I've also tried using regex expressions to find keys containing "." but get a similar response.

I'm sure I'm just not understanding something, but would love a point in the right direction.

Thanks

**Comment by toots** [comment]
`list.assoc.mem` needs a full string. You are looking for a dynamic check using a callback. Also, I believe that you need to escape the string to make sure it is not interpreted as a regexp:
```
s = source of some type

def db_call() = 
  if list.find(string.contains(substring="\\."), m)
    def filter(s)
      not string.contains(substring="\\.", s)
    end
    list = list.filter(filter,m)
  end

  dt = json_of(compact=true, list)

   #### post to api code
end

s.on_track(db_call)
```
Something like that..

**Comment by Russsgithub** [comment]
Brilliant, I'll give it a try.

Thanks many times to you and Samuel for all the work you're putting into this.

On 15 Jul 2021 18:05, Romain Beauxis ***@***.***> wrote:

list.assoc.mem needs a full string. You are looking for a dynamic check using a callback. Also, I believe that you need to escape the string to make sure it is not interpreted as a regexp:

s = source of some type

def db_call() =
  if list.find(string.contains(substring="\\."), m)
    def filter(s)
      not string.contains(substring="\\.", s)
    end
    list = list.filter(filter,m)
  end

  dt = json_of(compact=true, list)

   #### post to api code
end

s.on_track(db_call)


Something like that..

**Comment by Russsgithub** [comment]
I can't get this code to work . 
I get 
```
Error 5: this value has type
  string (inferred at /home/russ/.opam/ocaml-base-compiler.4.11.1/lib/liquidsoap/share/liquidsoap/git/ee13f438/libs/string.liq, line 11, char 30)
but it should be a subtype of
  bool
```
at list.find

**Comment by toots** [comment]
My bad, you need `list.exists`:
```
  list =
    if list.exists(string.contains(substring="\\."), m) then
      def filter(s)
        not string.contains(substring="\\.", s)
      end
      list.filter(filter,m)
    else
      m
    end

  dt = json_of(compact=true, list)
```
Also, the check can be removed to simplify the logic:
```
  def filter(s)
    not string.contains(substring="\\.", s)
  end

  list = list.filter(filter,m)

  json_of(compact=true, list)
```
I'd recommend to not override `list` as this might have some confusing side-effects.

**Comment by Russsgithub** [comment]
Thanks, but I'm getting error from these too.
The second example give
```
  [_ * _] (inferred at ././defs.liq, line 55, char 7-9)
but it should be a subtype of the type of the value at /home/russ/.opam/ocaml-base-compiler.4.11.1/lib/liquidsoap/share/liquidsoap/git/ee13f438/libs/list.liq, line 153, char 39
  [string] (inferred at /home/russ/.opam/ocaml-base-compiler.4.11.1/lib/liquidsoap/share/liquidsoap/git/ee13f438/libs/list.liq, line 155, char 11)
```
at line
```
list = list.filter(filter,m)
```

The first gives a similar error in a different place I think it was
```
list.exists(string.contains(substring="\\."), m)
```

I'm sending multiple sources through this as a function ie.
```
s = somesource
a = another source

def call(m) =
  def trigger() =
    if something then
      def filter(s)
        not string.contains(substring="\\.", s)
      end
  
      list = list.filter(filter,m)

      json_of(compact=true, list)

      ## api post code for list
    end
  -1.
  end
  thread.run.recurrent(fast=false,trigger)
end

s.on_track(call)
a.on_track(call)
```
But I can't imagine this is causing the errors ... though i may be wrong.

Thanks

**Comment by Russsgithub** [comment]
I seems to have got the script running using
```
def call(m) =
  def trigger() =
    if something then
      def filter(s1,s2)
        not string.contains(substring="\\.", s1)
      end
  
      list = list.assoc.filter(filter,m)

      json_of(compact=true, list)

      ## api post code for list
    end
  -1.
  end
  thread.run.recurrent(fast=false,trigger)
end
```
Testing to see if it delivers the desired effect, I can't see why not.

Thanks

**Comment by Russsgithub** [comment]
No , still passing json keys containing dots to my db.

**Comment by Russsgithub** [comment]
I need this to log to a mongo database which doesn't except dots in JSON keys.

A few music suppliers seem to like adding dotty JSON keys.

I've been logging play out times on the database to then filter out the most recently played files from the list of possible next to play files.

I have just noticed ```playlog()``` which I have used on an on_metadata call to check for repeats.

This removes the need for me to remove JSON keys containing dots from the posted data, so solves my problem. Hopefully (testing).

Thanks

**Comment by toots** [comment]
This function will do, I misunderstood how the regexp thing worked:
```
def remove_dotted_values(l) =
  def filter(m)
    let (_, value) = m
    not string.contains(substring=".", value)
  end

  list.filter(filter, l)
end
```
Do you need to remove both key/values that have dots or just values? Also, in SQL databases, there's a way to prepare a statement and then inserts the variables so you avoid that kind of issue. That does not exist with mongo db? Or, else a way to escape passed values?

**Comment by Russsgithub** [comment]
I need the key .
I guess that mean passing _ to string.contains rather than value.

I'll try.

Thanks Romain

On 17 Jul 2021 16:22, Romain Beauxis ***@***.***> wrote:

This function will do, I misunderstood how the regexp thing worked:

def remove_dotted_values(l) =
  def filter(m)
    let (_, value) = m
    not string.contains(substring=".", value)
  end

  list.filter(filter, l)
end


Do you need to remove both key/values that have dots or just values? Also, in SQL databases, there's a way to prepare a statement and then inserts the variables so you avoid that kind of issue. That does not exist with mongo db? Or, else a way to escape passed values?

**Comment by toots** [comment]
This will filter both key and values with dots:
```
def remove_dotted_values(l) =
  def filter(m)
    let (key, value) = m
    not (string.contains(substring=".", key) or string.contains(substring=".", value))
  end

  list.filter(filter, l)
end
```

**Comment by Russsgithub** [comment]
Brilliant thank you.

On 17 Jul 2021 16:34, Romain Beauxis ***@***.***> wrote:

This will filter both key and values with dots:

def remove_dotted_values(l) =
  def filter(m)
    let (key, value) = m
    not (string.contains(substring=".", key) or string.contains(substring=".", value))
  end

  list.filter(filter, l)
end

**Comment by Russsgithub** [comment]
All working fine. Closing thread.
