### ISSUE TITLE
Soundtouch buffer too big ? - 2.0 (main)

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1744]
I am using soundtouch to beat sync a source to another.

```
s = some source

s = bpm(s)
### send bpm to function that matches bpm to another source if its close enough and sets a ref (sBpm = ref(float)) to a float between 0.9 and 1.1 approx
thread.run(every=1., {bpm_set(s.bpm())})

s = soundtouch(tempo = {!sBpm}, s)

# a bit of processing (compress, ....)
.....
.....
.....
silence = blank()
## switch that drops source s for blank if ref no_s_source if true
s = switch(track_sensitive=false,[({!no_s_source},silence),({true},s)])
s = crossfade(s)
s = mksafe(s)

....
....
....
```
source s constantly pulls in data both with or without the switch changing.

Is it possible to add max buffer size to soundtouch maybe?

Thanks

**Comment by toots** [comment]
Hi! Could you clarify what you mean by pulling data? Thks!

**Comment by Russsgithub** [comment]
Hello, If soundtouch is in the chain the source prepares one track , plays it while immediately preparing the next , then the next etc. Audio plays as it should , as in it doesn't skip to the next track when the next is prepared.

This made me presume (logs print producer / consumer buffers) that the buffer either one or the other or both have infinite or very big buffers and soundtouch is ? Self syncing ?

Without soundtouch in the chain this doesn't happen.

I hope this explains what I'm trying to say.

Thanks

On 20 Jul 2021 17:18, Romain Beauxis ***@***.***> wrote:

Hi! Could you clarify what you mean by pulling data? Thks!

**Comment by toots** [comment]
Hi! I cannot reproduce so far. Here's the script that I have, pretty fun outcome:
```ruby
s = playlist("/tmp/pl")

s = bpm(s)

sBpm = ref(1.)

thread.run(every=1., {s.bpm(); sBpm := random.float(min=0.9, max=1.1)})

s = soundtouch(tempo = {!sBpm}, s)

s = crossfade(s)
```

Would you mind sharing more of your script, the liq version or git tag that you are using and also perhaps some logs? Thanks!

**Comment by Russsgithub** [comment]
I'm stripping my script down to try and reproduce, and haven't managed it yet which suggests I've just written bad code.

I'll spend the day trying to recreate it, and leave open for now, but chances are this is my error.

I apologies if this is the case.

Saying that the minimizing of my script is defiantly teaching me stuff, which is great.

Thanks

**Comment by Russsgithub** [comment]
I'm closing this, messy script with possibly unneeded buffers causing this. ooops
