### ISSUE TITLE
on_track and on_end trigger when track skipped at on_metadata

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#1746]
**Describe the bug**
If I add ```source.skip(s)``` within ```s.on_medadata()``` , ```on_track``` and ```on_end``` are still trggered and metadata is passed to output

**To Reproduce**
```
def next() =
  list.map(fun(item) -> request.create(item),
    process.read.lines("../../../python_scripts/next_track_vocal_fx.py")
  )
end


s = request.dynamic.list(length=70., conservative = false, next)

def onEnd(_,m)
  print("On end triggered")
end

s.on_metadata(fun(m) -> source.skip(s))

s.on_track(fun(m) -> print("on track of skipped track"))

s = source.on_end(s, onEnd)

output.icecast(description="Sound Mirror", icy_metadata="true", format="audio/aac", %fdkaac(channels=2, samplerate=48000, bitrate=320, afterburner=true, transmux="adts", aot="mpeg4_aac_lc", sbr_mode=false), host="ec2-63-34-87-186.eu-west-1.compute.amazonaws.com", port=8000, password="R@d1o5",mount="testv2",mksafe(clock(s)))

```
**Expected behavior**
No `on_track` or `on_end` calls, and no metadata passed to output when track is skipped further up the script.

**Version details**
 - OS: [e.g. Debian, OSX] - Arch
 - Version [e.g. `1.3.4`] - 2.0 - git (main)

**Install method**
OPAM

**Comment by smimram** [comment]
This should be expected with `on_metadata` which is only intended to observe metadata (= it is too late when you skip). In order to achieve what you want I would use `map_metadata`, and change
```
s.on_metadata(fun(m) -> source.skip(s))
```
to something like
```
def mapf(m)
  source.skip(m)
  []
end
s = map_metadata(update=false, mapf, s)
```
I think that you will still get the empty metadata, but this is easily ignored. Does this help?

**Comment by Russsgithub** [comment]
Great thanks.

I'll test, but see your point so imagine it will solve my problem.

Thanks
