### ISSUE TITLE
Error 4: Undefined variable mksafe

### ISSUE THREAD

**Issue by forerosantiago** [savonet/liquidsoap#1747]
Hello! So I am following the quickstart guide [here](https://www.liquidsoap.info/doc-1.4.4/quick_start.html), I am trying to use the function **mksafe()** so my playlist becomes infallible, but I get the following error

`Error 4: Undefined variable mksafe
1 forero@forero:~/music$ nano radio.liq`

Also, this is my radio.liq script:
```#!/usr/bin/liquidsoap
source = mksafe("/home/forero/music/")

output.icecast(%vorbis,
   host = "localhost", port = 8000,
   password = "password", mount = "stream.ogg",
   source)
```

Am I doing something wrong? By the way the **/home/forero/music/** is just a directoy with only mp3 files.

**Comment by Russsgithub** [comment]
Hello, try something like this :-

```
source =mksafe( playlist("/home/forero/music/"))

output.icecast(%vorbis,
   host = "localhost", port = 8000,
   password = "password", mount = "stream.ogg",
   source)
```
I think mksafe is just another way of writing a fallback to silence.

Have fun.

**Comment by Russsgithub** [comment]
I found this really useful

https://www.liquidsoap.info/doc-dev/book.html

**Comment by forerosantiago** [comment]
> Hello, try something like this :-
> 
> ```
> source = mksafe(playlist("/home/forero/music/"))
> 
> output.icecast(%vorbis,
>    host = "localhost", port = 8000,
>    password = "password", mount = "stream.ogg",
>    source)
> ```
> 
> I think mksafe is just another way of writing a fallback to silence.
> 
> Have fun.

Yep, I forgot to use the **playlist()** function, but I'm still getting this error though.
`At line 3, char 9-16:
Error 4: Undefined variable mksafe`

**Comment by millicent-audio-mirror** [comment]
I'm not sure then.
The script works for me .

I'll leave this for someone else to answer, but it may be related to you're install. 

I use opam to install, I think this script would need ocaml-vorbis and maybe ocaml-ogg as well installed. (opam depext -i vorbis ogg) .

**Comment by forerosantiago** [comment]
You may be right, I  installed it using Ubuntu's apt

**Comment by Russsgithub** [comment]
I've not installed through Ubuntu's apt.

If I remember rightly the opam install is something like: -

install opam via apt - 

```
add-apt-repository ppa:avsm/ppa
apt update
apt install opam
```
from opam install page - https://opam.ocaml.org/doc/Install.html

```
opam init
```

then install a switch , i think they are up to ver 4.12.0 ,

```
opam switch create 4.12.0
```

if you need to run
```
eval $(opam env)
```

Then install liquidsoap and anything else you need, depext checks for needed dependencies and installs them if it can.

So from liquidsoap docs

```
opam depext -i taglib mad lame vorbis cry samplerate liquidsoap
```

This will give you mp3, vorbis and icecast output support, though you could replace samplerate for fmpeg.

```
opam depext -i taglib mad lame cry ffmpeg liquidsoap
```
and it should work.

**Comment by forerosantiago** [comment]
All right, I installed it using opam, now the command isn't on my $PATH, how to add it?

**Comment by forerosantiago** [comment]
I mean, I am getting this error:
 ```
Command 'liquidsoap' not found, but can be installed with:

sudo apt install liquidsoap
```

**Comment by Russsgithub** [comment]
OK, I've not had this issue, so not sure.

You might need to run
```
eval $(opam env)
```
to update the switch after you installed stuff.

If you used ffmeg you also need to install ffmpeg , I think.
```
sudo apt install ffmpeg
```
.....

I think eval $(opam env) should get you going , after your last comment

**Comment by forerosantiago** [comment]
Oh yeah, I forgot` eval $(opam env)`, it works perfectly. Thank you.

**Comment by Russsgithub** [comment]
No worries, enjoy. Its an amazing language that you can do a lot with.

On 23 Jul 2021 15:38, Santiago Forero ***@***.***> wrote:

Oh yeah, I forgot eval $(opam env), it works perfectly. Thank you.
