### ISSUE TITLE
Streaming Video from mac osx to icecast

### ISSUE THREAD

**Issue by russellharrower** [savonet/liquidsoap#175]
Maybe I am jumping into deep to quickly, but that was the way i got told to learn, I am having the following issue:

```
T903:liq russellharrower$ liquidsoap test.liq
Invalid value at line 5, char 17-27:
  Could not get a valid media file of kind {audio=2;video=1;midi=0} from "video.avi".
```

the code I am using is below.

```
#!/usr/local/lib/liquidsoap

source = single("video.mp4")

output.icecast(
        %ogg(%theora(quality=25,width=320,height=240),%vorbis),
        host="server.radiobreakout.com.au",
        port=8080,
        password="123456789",
        mount="/videostream",
        source)
```

I am not sure if it is a mac issue or if it is a liquidsoap brew issue as it did not install --with-shout and when i went to install --with-all it threw errors at me saying it could not download the files it needed. - I am not sure why.

**Comment by smimram** [comment]
Yes, you can use `audio_to_stereo` to ensure stereo.

**Comment by smimram** [comment]
This was apparently solved a long time ago, closing. Please reopen if necessary.
