### ISSUE TITLE
Bandpass filter for MP3 streams?

### ISSUE THREAD

**Issue by ivellios1988** [savonet/liquidsoap#1751]
### Discussed in https://github.com/savonet/liquidsoap/discussions/1750

<div type='discussions-op-text'>

<sup>Originally posted by **ivellios1988** July 23, 2021</sup>
In my radio I have a stream which broadcasts in MP3 with 128kbps. I'd like to reduce the amount of audible distortion in stereo signal, by cutting the audio bandwidth to, say, 14kHz or even 13kHz. Is there any way to achieve this in Liquidsoap?</div>

**Comment by toots** [comment]
Hi! Great idea to switch to discussions, I left a comment there!
