### ISSUE TITLE
delay operator issues

### ISSUE THREAD

**Issue by gammaw** [savonet/liquidsoap#1758]
I expect the `delay` operator to start playing the source _immediately_ and to become then unavailable for a specified amount of time (see docs at https://www.liquidsoap.info/doc-dev/reference.html#delay and also in https://github.com/savonet/liquidsoap/issues/1544). Instead, it seems that it starts with a delay before the source becomes available for the first time. 

For example, I have the following statement inside a `switch`: 

`({6w and (15h-15h02m or 15h10m-15h12m)}, delay(70.0,playlist_with_one_audio_file))`

In the log I see this: 

```
2021/07/24 15:00:00 [switch_7:3] Switch to delay_1 with transition.
2021/07/24 15:01:16 [decoder:2] Decoding "/var/stations/radio/media/test.mp3" ended
```

As you can see, it is switched to the playlist on time but the file will start playing after more or less 70 seconds, although this is the very first occurrence of the playlist. I know that there may be an issue with skipping the playlist after the single file in the playlist has been played already (see also https://github.com/savonet/liquidsoap/issues/1544), but this is not the case here. 

Can anybody help? 

PS: I'm on commit 55d5a7e8731ce39e9acb041990d349c88ef3408d.

**Comment by smimram** [comment]
This is strange, I read the code again and it seems fine. Moreover, the test
```
s = fallback(track_sensitive=false, [delay(5., sine(880., duration=5.)), sine(440.)])
output(s)
```
plays a the high-pitched sine directly. Is it also the case on your side?

**Comment by gammaw** [comment]
Thanks. Yeah with your code it seems to play directly but after 5s the low-pitch sine stays forever. Shouldn't the high-pitch one play over and over, i.e., 5s high-pitch, 5s low-pitch, 5s high-pitch, ...? This is how I understand what `delay` does. 

As for my original question, it's still a strange behaviour. I tried with your `sine` source instead of the playlist and if I start the script at a time inside `15h-15h02m` then it play directly, if I start the script before the time range in the predicate, then the sine won't play at `15h` but after some time (which was about a minute, not 5s).

**Comment by toots** [comment]
I'm not sure what could cause your issue but, looking at the code, it looks like some cleanup is needed there:
```ocaml
    val mutable last = if initial then Unix.time () else 0.

    val mutable in_track = false

    method private delay_ok = Unix.time () -. last >= delay

    method is_ready = in_track || (self#delay_ok && source#is_ready)

    method private end_track =
      in_track <- false;
      last <- Unix.time ()

    method private get_frame buf =
      source#get buf;
      in_track <- true;
      (* The current track ends. *)
      if Frame.is_partial buf then self#end_track
``` 
Source can become unavailable (`source#is_ready = false`) between calls to `get_frame` but this code will force `self#is_ready` to return `true` inside a given track regardless of wether `source` is ready or not, which can lead to some trouble.

Comment in `source.mli`:
```ocaml
       (** [get buf] asks the source to fill the buffer [buf] if possible.
           The [get] call is partial when the buffer is not completely filled.
           [get] should never be called with a full buffer,
           and without checking that the source is ready. *)
       method get : Frame.t -> unit
```

Instead, it should delegate `is_ready` to the underlying `source` at all time and deal with `source` becoming unavailable during a track on its own.

I'll look at fixing this. Not sure if that'll fix the originally reported bug but one can hope!

**Comment by gammaw** [comment]
Thanks! I guess I see what you mean. 

```
s = fallback(track_sensitive=false, [delay(5., sine(880., duration=5.)), sine(440.)])
output(s)
```

> Shouldn't the high-pitch one play over and over, i.e., 5s high-pitch, 5s low-pitch, 5s high-pitch, ...? This is how I understand what delay does.

For the time being, can you confirm that this is the expected behavior (the "alternation")? If you run the script, do you also hear what I do (5s high-pitch, then low-pitch forever)?

**Comment by toots** [comment]
I pushed the changes related to the issues I noticed in the code. I don't think that this is likely to change the issue here but it would be nice if you had a minute to test the latest `main` @gammaw !

**Comment by gammaw** [comment]
Thanks @toots!

When I try to compile the new HEAD I get this: 

```
#14 539.8 [ERROR] The compilation of liquidsoap failed at "/usr/bin/make".
#14 539.8 
#14 539.8 #=== ERROR while compiling liquidsoap.2.0.0 ===================================#
#14 539.8 # context              2.0.5 | linux/x86_64 | ocaml-system.4.08.1 | pinned(git+file:///var/azuracast/liquidsoap#HEAD#d8ebbc56)
#14 539.8 # path                 ~/.opam/ocaml-system.4.08.1/.opam-switch/build/liquidsoap.2.0.0
#14 539.8 # command              /usr/bin/make
#14 539.8 # exit-code            2
#14 539.8 # env-file             ~/.opam/log/liquidsoap-7-ad3bdd.env
#14 539.8 # output-file          ~/.opam/log/liquidsoap-7-ad3bdd.out
#14 539.8 ### output ###
#14 539.8 # [...]
#14 539.8 # OCAMLOPT -c decoder/ffmpeg_decoder.ml
#14 539.8 # File "decoder/ffmpeg_decoder.ml", line 528, characters 15-27:
#14 539.8 # 528 |   Av.seek ~fmt:`Millisecond ~min_ts ~max_ts ~ts container;
#14 539.8 #                      ^^^^^^^^^^^^
#14 539.8 # Error: The function applied to this argument has type
#14 539.8 #          Avutil.Time_format.t -> Int64.t -> Av.seek_flag array -> unit
#14 539.8 # This argument cannot be applied with label ~fmt
#14 539.8 # make[2]: *** [../Makefile.rules:127: decoder/ffmpeg_decoder.cmx] Error 2
#14 539.8 # make[2]: Leaving directory '/var/azuracast/.opam/ocaml-system.4.08.1/.opam-switch/build/liquidsoap.2.0.0/src'
#14 539.8 # make[1]: *** [../Makefile.rules:69: all-auto-ocaml-prog] Error 2
#14 539.8 # make[1]: Leaving directory '/var/azuracast/.opam/ocaml-system.4.08.1/.opam-switch/build/liquidsoap.2.0.0/src'
#14 539.8 # make: *** [Makefile.rules:29: all-subdirs] Error 2
```

The gist of my compile script is this: 

```
RUN cd ~/ \
     && git clone --recursive https://github.com/savonet/liquidsoap.git \
    && cd liquidsoap \
    && git checkout d8ebbc56d7308646143bd19df7e2abcf211e8f63 \
    && opam pin add --no-action liquidsoap .

ARG opam_packages="ladspa ffmpeg samplerate taglib mad faad fdkaac lame vorbis cry flac opus duppy ssl liquidsoap"
RUN opam depext -y ${opam_packages}
RUN opam install -y ${opam_packages}
```

I'm sorry to bother you with compile questions, I know we should switch to using your images. At the moment we have a tech stack constraint which prevents us from easily plugging in new Liquidsoap images (instead, we compile it ourselves) but I guess we'll have to work on it because it seems likely that we bump into issues like this.

**Comment by smimram** [comment]
You need to install git version of `ocaml-ffmpeg` first (with `opam pin add .` in `ocaml-ffmpeg` directory).

**Comment by gammaw** [comment]
Thanks! I managed to use your latest image from Docker hub so hopefully I won't need to compile it on our end.  

I tried the new version and it plays the same result of your sine example. Which means that the `delay` indeed returns a source which is available immediately.

I have to now go on testing how can we combine it with `playlist` sources and `switch` predicates. Our dilemma is still the same: how can we schedule playlists with single files over and over (e.g., once per week in the same time slot, or every hour before noon), where we want to play a file (playlist) only once on each occasion. Your proposal with `delay` was promising but I couldn't get it working yet. 

If it's ok with you, we can keep this issue open in case I have further questions on `delay` (I guess I will).

**Comment by gammaw** [comment]
My first experiment on a stripped down example went well. I copy in my example. The show playlist contains a single file (`my_show_test_17_seconds.mp3`) which is now approx. 17s long. As expected, the file plays exactly two times, at `8h37m` and at `8h39m`, and the `delay` operator prevents it from  playing more than once within the 1-minute the time slots. 

There is one thing I noticed. The playback of file starts approx. 10s after the specified times (i.e., at around 8h37m + 10s and 8h39m + 10s). Is it a normal latency in the system? I attach the logs too. There you can see that switching to `delay` occurs precisely at 8h37m and 8h39m, but again, the hearable playback starts a bit later. 

```
set("log.stdout", true)

playlist_my_show = playlist(id="playlist_my_show",mode="randomize",reload_mode="watch","/var/azuracast/stations/lahmacun_radio/playlists/playlist_my_show.m3u")
playlist_my_show = audio_to_stereo(id="stereo_playlist_my_show", playlist_my_show)

playlist_off_air = playlist(id="playlist_off_air",mode="randomize",reload_mode="watch","/var/azuracast/stations/lahmacun_radio/playlists/playlist_off_air.m3u")
playlist_off_air = audio_to_stereo(id="stereo_playlist_off_air", playlist_off_air)

off_air = fallback(id="playlist_off_air_safe", track_sensitive = false, [playlist_off_air, single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")])

radio = switch(track_sensitive=false,
    [({2w and 8h37m-8h38m or 8h39m-8h40m}, delay(60., playlist_my_show)),
    ({true}, off_air) ])

output.harbor(%mp3, mount="my-radio.mp3", radio)
```

```
021/08/10 08:37:00 [playlist_my_show:3] Prepared "/var/azuracast/stations/lahmacun_radio/media/my_show_test_17_seconds.mp3" (RID 4).
2021/08/10 08:37:00 [switch_1:3] Switch to delay_0 with transition.
[mp3 @ 0x7f342c1f0a40] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f342c1f0a40] Estimating duration from bitrate, this may be inaccurate
2021/08/10 08:37:16 [decoder:2] Decoding "/var/azuracast/stations/lahmacun_radio/media/my_show_test_17_seconds.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f3438b244c0] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f3438b244c0] Estimating duration from bitrate, this may be inaccurate
2021/08/10 08:37:17 [playlist_my_show:3] Prepared "/var/azuracast/stations/lahmacun_radio/media/my_show_test_17_seconds.mp3" (RID 6).
2021/08/10 08:37:17 [switch_1:3] Switch to playlist_off_air_safe with forgetful transition.
2021/08/10 08:37:17 [camomile:3] Failed to convert "Girls To The Front (Kapita\197\130) x The Ear Has To Travel (Cashmere)" from auto(UTF-8,ISO-8859-1) to Latin-1 (CamomileLibrary__UChar.Out_of_range)!
2021/08/10 08:39:00 [switch_1:3] Switch to delay_0 with transition.
[mp3 @ 0x7f3434144000] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f3434109800] Estimating duration from bitrate, this may be inaccurate
2021/08/10 08:39:16 [decoder:2] Decoding "/var/azuracast/stations/lahmacun_radio/media/my_show_test_17_seconds.mp3" ended: Ffmpeg_decoder.End_of_file.
```

**Comment by gammaw** [comment]
> There is one thing I noticed. The playback of file starts approx. 10s after the specified times (i.e., at around 8h37m + 10s and 8h39m + 10s). Is it a normal latency in the system? I attach the logs too. There you can see that switching to delay occurs precisely at 8h37m and 8h39m, but again, the hearable playback starts a bit later.

Any idea on this?

**Comment by toots** [comment]
Hi! I'm gonna try and have another pass at this shortly.

**Comment by toots** [comment]
Hi!

Finally looking at this! Let's try to get an update and clear out some of the remarks above.
* The `10s` delay might very well be due to `output.harbor`'s internal buffering. I'd recommend trying different outputs, `output.harbor` is not defined for real-time capabilities.
* What's the status with the underlying delay issue? Your paired down example seems to have worked well. Do you still have the issue in your production system?

If you are still experiencing the issue, any version of your script that we could reproduce locally would help immensely. Usually once we can reproduce a bug, it gets fixed pretty quickly.

Thanks for your patience!

**Comment by gammaw** [comment]
Thanks @toots! Not to use `harbor` seemed to be a good hint! We switched to using an `icecast` output and the transitions are now audible on time. Also, we switched to using the latest Liquidsoap 2.0.0 Docker image, so I can't be 100% sure what fixed the issue, but since we're using Icecast in production too, I don't really care :)

As it's still a minimalistic test with `delay`, we'll continue with adding features to it from our production and hope that we can have a full-fledged configuration with `delay` in it. FYI: in our production system that we have been successfully using since years, we use `once` instead of `delay`, but `once` has limitations and that's why we'd like to switch to `delay`. It's going to be a major upgrade in our setup as we not only plan to replace `once` with `delay`, we'll also upgrade from Liquidsoap 1.4.2 to 2.0.0. Btw, when do you plan to officially release 2.0.0? 

For this GitHub issue, can we keep it open until we validate that `delay` works as expected in our full-fledged configuration?
