### ISSUE TITLE
Streaming Icecast unstable bitrate with mp3 CBR coder 

### ISSUE THREAD

**Issue by nfavrod** [savonet/liquidsoap#179]
I have a problem streaming a playlist with liquidsoap (both in airtime and liquidsoap standalone).

output.icecast(%mp3(bitrate = 256, stereo = true), ... )  stream to an external icecast but the coder is very unstable. It bursts a lot more than 300kbps, and it makes the stream drop some packets and cut very often. I use a professional codec (Barix like) to receive this stream and even with a big buffer, it drops a lot of packets.

When I encode the stream with Darkice, the stream is very stable. I don't have the variations. The CBR coder doesn't variate more than 5kbps. It's much more stable.

I also tried to use VBR ( %mp3.vbr(quality=3) ) and it's a little better but it's not perfect either.

Can you tell me a little more how liquidsoap encodes and check if the processing could be improved?

**Comment by dbaelde** [comment]
I'll close as incomplete due to inactivity. Feel free to reopen.
