### ISSUE TITLE
Attempting to process multiple dynamic requests at the same time fails

### ISSUE THREAD

**Issue by chrism** [savonet/liquidsoap#1797]
**Describe the bug**
Attempting to process multiple dynamic requests at the same time fails.

**To Reproduce**
I have a server endpoint which returns a plain text response for each station in the annotate format including some metadata and the URL of the mp3 track. ie

```
annotate:title=\"Title\",artist=\"Artist\",album=\"Album}\":http://remote-url/tracks/track.mp3
```

In the script is a method which creates a stream for each station

```
def generate_stream(slug)
  def next() =
    url = "http://remote-url/next/"^slug
    cue = http.get(url)
    uri = list.hd(default="",[cue])

    if uri != "" then
      request.create(uri)
    else
      null()
    end
  end

  stream = request.dynamic(next)
  radio = mksafe(stream)

  radio
end

test1 = generate_stream("test1")
```

This works perfectly for a single station, but if I add a second station

```
test1 = generate_stream("test1")
test2 = generate_stream("test2")
```

Then the process fails with this error message

```
liquidsoap_1          | [mp3 @ 0x7f0808004900] Format mp3 detected only with low score of 1, misdetection possible!
liquidsoap_1          | [mp3 @ 0x7f0808004900] Failed to read frame size: Could not seek to 1026.
liquidsoap_1          | 2021/08/05 12:40:57 [decoder:2] Error while checking file's content: FFmpeg.Avutils.Error(Invalid argument)
liquidsoap_1          | 2021/08/05 12:40:57 [decoder:2] Error while checking file's content: Mad.End_of_stream
liquidsoap_1          | 2021/08/05 12:40:57 [decoder:3] Available decoders cannot decode "/tmp/liq-processa4fbac.mp3" as {audio=pcm(stereo),video=none,midi=none}
```

**Expected behavior**
I would expect this to be possible and queue both tracks to process sequentially if necessary.

**Version details**
`liquidsoap:v2.0.0-beta2`

**Install method**
Installed using the Docker image `savonet/liquidsoap:v2.0.0-beta2`

**Comment by chrism** [comment]
Also, I wondered if changing the decoder to mad might help

```
set("decoder.priorities.mad",100)
```

But I ultimately still get the same error

```
liquidsoap_1          | 2021/08/05 19:46:08 [decoder:2] Error while checking file's content: Mad.End_of_stream
liquidsoap_1          | [mp3 @ 0x7fc1ec12a240] Format mp3 detected only with low score of 1, misdetection possible!
liquidsoap_1          | [mp3 @ 0x7fc1ec12a240] Failed to read frame size: Could not seek to 1026.
liquidsoap_1          | 2021/08/05 19:46:08 [decoder:2] Error while checking file's content: FFmpeg.Avutils.Error(Invalid argument)
liquidsoap_1          | 2021/08/05 19:46:08 [decoder:3] Available decoders cannot decode "/tmp/liq-process8b3a17.mp3" as {audio=pcm(stereo),video=none,midi=none}
```

**Comment by toots** [comment]
Thanks for the report. I can confirm and reproduce the bug. The new request resolution implementation is pretty neat but we're not waiting for the streamed download to finish before sending the file down the decoding pipe. Will push a fix as soon as I figure out how to do it properly 🙂

**Comment by chrism** [comment]
Thats great, look forward to it thanks so much @toots !
