### ISSUE TITLE
Opus stream breaks up when playing a playlist

### ISSUE THREAD

**Issue by noer** [savonet/liquidsoap#180]
```
set("log.file.path","/tmp/basic-radio.log")

playlist = mksafe(playlist("playlist.m3u"))

output.icecast(%opus(bitrate=48),
  host = "localhost", port = 8000,
  password = "hackme", mount = "stream.opus",
  playlist)
```

When listening to the stream in Chromium or VLC, the streaming stops when switching to a new track in the playlist.

Icecast `error.log` contains lines like this for every new track

```
[2014-06-13  11:01:15] INFO format-opus/initial_opus_page seen initial opus header
```

This makes for a very bad listener experience.

**Comment by xogium** [comment]
Hi,
I can confirm this is still the case with the latest liquidsoap built with opus support (I used the opam way). Vlc, firefox, audacious, mpv, chromium, they all get disconnected at practically every song change. I think it has to do with ogg chaining that the opus also uses but I can be wrong. It happens also if you read a directory, not just with a playlist. If I capture a sample of the stream with wget and examine the result with opusinfo, then pastebin the result, would that help ?

**Comment by toots** [comment]
Thanks for the report, I'll look at it asap.

**Comment by toots** [comment]
@noer Thanks for those scripts. Sorry this slipped through the cracks. I'm on it now.

**Comment by MinePro120** [comment]
Are we sure this is fixed @toots? MPV reports `[lavf] Linearizing discontinuity` when playing the stream, and there is a small stutter on every track change in VLC. This is the command I use:
```
liquidsoap 'output.icecast(%opus(bitrate = 128, samplerate = 48000, stereo, signal="music", application="audio"), port = 42868, password = "hackme", mount = "stream.opus", mksafe(replaygain(playlist(mode = "randomize", reload = 900, reload_mode = "rounds", prefix = "replaygain:", "/musicDir"))))'
```
