### ISSUE TITLE
Add default value to getenv function

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#1801]
**Is your feature request related to a problem? Please describe.**
I want to assign default value to my env vars.
To do that I have to create my own function that supports default values.

**Describe the solution you'd like**
Function code
```
def getenv(s, default = "")
  list.assoc(default = default, s, environment())
end
```
With this variant I can do things like this
```
DEFAULT_ICECAST_HOST = getenv("LIQUIDSOAP_DEFAULT_ICECAST_HOST", "icecast")
DEFAULT_ICECAST_PORT = int_of_string(getenv("LIQUIDSOAP_DEFAULT_ICECAST_PORT", "8000"))
DEFAULT_ICECAST_USER = getenv("LIQUIDSOAP_DEFAULT_ICECAST_USER", "source")
DEFAULT_ICECAST_PASSWORD = getenv("LIQUIDSOAP_DEFAULT_ICECAST_PASSWORD")
```

**Describe alternatives you've considered**
No alternatives

**Additional context**
I think this function will be backwards compatible.
Also I've found some examples of such functions:
- https://docs.python.org/3/library/os.html#os.getenv
- https://laravel.com/docs/8.x/helpers#method-env

**Comment by smimram** [comment]
Just commited a change where you can write
```
getenv(default="icecast", "LIQUIDSOAP_DEFAULT_ICECAST_HOST")
```

**Comment by vitoyucepi** [comment]
@smimram I didn't seen `null()` before. Will it return empty string as before?
Also I thought that named arguments should be prefixed with `~`. And definition should look like `def getenv(~default=null(), s)`

**Comment by toots** [comment]
> @smimram I didn't seen `null()` before. Will it return empty string as before?
> Also I thought that labeled arguments should be prefixed with `~`. And definition should look like `def getenv(~default=null(), s)`

Yes, both concerns were correct. Code has been updated in `main` to reflect that now. Function takes an optional labelled argument and returns an empty string when given `null()` or no argument for it.

**Comment by vitoyucepi** [comment]
@toots I still not sure if it should be `getenv(~default = null(), s)` instead of
- `getenv(~default = "", s)`
- `getenv(s, default = "")`

Personally I prefer the latest one.

**Comment by smimram** [comment]
Sorry for the too quick fix...

I think that @vitoyucepi is right, we should have `""` as default value to keep backward compatibility (otherwise users will get unexpected exceptions...)

**Comment by toots** [comment]
This is done now!

See:
https://github.com/savonet/liquidsoap/commit/1c6c32730939e32a3e03446552e64f283cd2b1a8

**Comment by vitoyucepi** [comment]
@toots but `default = default ?? ""` is useless, because we can define `default = ""` instead of `default = null()`.
Also maybe `s` is not well named parameter and should be renamed as `key` or `variableName`.
There are a lot of same named function parameters with practically useless names. In sound related functions I think `s` is shorthand for `source` but in other function there should be more self-documented parameters.
