### ISSUE TITLE
No cross-fade after short track/jingle

### ISSUE THREAD

**Issue by cgrozev** [savonet/liquidsoap#181]
Hi. I cannot achieve cross-fade transitions when scheduling short elements (jingles, liners). Assume song A is followed by jingle J (=5 sec), followed by song B, followed by song C.
Cross-fade transitions are perfect between A and J, and between B and C. But J to B simply does not work; it sequences instead of crossfades.
(Btw, I am using cue_cut with annotate: in the playlist)

Any ideas on how to ensure cross-fade transitions AFTER short elements, I would be grateful.

Regards
Christo

**Comment by toots** [comment]
Hi again. Closing this now. Feel free to reopen or submit a new issue.
