### ISSUE TITLE
replaygain extracted by ffmpeg seems invalid on mono tracks

### ISSUE THREAD

**Issue by jooola** [savonet/liquidsoap#1814]
**Describe the bug**
I cannot find a source of truth, to determine whether the value extracted by `extract-replaygain` on mono audio files is valid.

We previously used https://github.com/chaudum/rgain3.
We are moving to ffmpeg filters for our audio file analysis, instead of many different tools.
I tried another tool to have a third opinion, mp3gain.

Here is the result for the following file https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/tests/test_data/44100Hz-16bit-mono.mp3:
`rgain3`: +5.2 dB with +- 0.6 tolerance
`extract-replaygain` (ffmpeg): +8.21 dB
`mp3gain`: +5.690000 

So I don't understand why we have a different result with mono files using ffmpeg.

**To Reproduce**
```sh
wget "https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/tests/test_data/44100Hz-16bit-mono.mp3"

./scripts/extract-replaygain 44100Hz-16bit-mono.mp3

mp3gain 44100Hz-16bit-mono.mp3
```

Another file that can be tested is https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/tests/test_data/44100Hz-16bit-mono.ogg

**Expected behavior**

To have a consistent result across the different tools.

**Version details**
 - OS: Debian 10 or 11 (can only find mp3gain on bullseye)

**Comment by toots** [comment]
Thanks for reporting. I can confirm the discrepancy. 

I wonder if the issue could actually be with the two other tools. If you create a stereo file from the mono file by repeating the single mono channel, `mp3gain` reports:
```
Recommended "Track" dB change: 9.170000
```
Whereas `ffmpeg` reports the same value:
```
track_gain = +8.67 dB
```
There should be no reason for a different value in mono or stereo in this case and the value for stereo from `mp3gain` seems in the same vicinity as `ffmpeg`'s so, yeah, I believe `mp3gain` is, here, not behaving correctly w.r.t to mono data.

**Comment by jooola** [comment]
I just tried again with rgain3, (using GStreamer):
```sh
$ replaygain python_apps/airtime_analyzer/tests/test_data/44100Hz-16bit-mono.mp3 
Checking for Replay Gain information ...
  python_apps/airtime_analyzer/tests/test_data/44100Hz-16bit-mono.mp3:none
Calculating Replay Gain information ...
  python_apps/airtime_analyzer/tests/test_data/44100Hz-16bit-mono.mp3:5.24 dB
  Album gain: 5.24 dB
Writing Replay Gain information to files ...
  python_apps/airtime_analyzer/tests/test_data/44100Hz-16bit-mono.mp3:done
Done
```

So, something is still odd, I still don't understand how this can be false for so 2 other tools and not ffmpeg.

I feel dumb asking for more explanation, I don't understand why "There should be no reason for a different value in mono or stereo in this case and the value for stereo".

**Comment by toots** [comment]
> I feel dumb asking for more explanation, I don't understand why "There should be no reason for a different value in mono or stereo in this case and the value for stereo".

This is because amplification adjustment is based on audio peaks. If the two channels have the same data, the peaks should be the same and the required amplification should be the same. At least that's how I understand it.

> I tried on a real file again, with both mono and stereo:
> 
> ```
> $ replaygain Neverend-stereo.mp3 --force --dry-run
> Calculating Replay Gain information ...
>   Neverend-stereo.mp3:-8.95 dB
>   Album gain: -8.95 dB
> Done
> 
> $ ./extract-replaygain Neverend-stereo.mp3
> -8.90 dB
> 
> $ replaygain Neverend-mono.mp3 --force --dry-run
> Calculating Replay Gain information ...
>   Neverend-mono.mp3:-8.45 dB
>   Album gain: -8.45 dB
> Done
> 
> $ ./extract-replaygain Neverend-mono.mp3        
> -5.36 dB
> ```

Interesting. How did you convert to mono? Here's an example here:
```
% ffmpeg -i stereo.mp3 -filter replaygain -f null /dev/null
...
[Parsed_replaygain_0 @ 0x142717850] track_gain = -4.94 dB

% ffmpeg -i stereo.mp3 -ac 1 mono.mp3
% ffmpeg -i mono.mp3 -filter replaygain -f null /dev/null
...
[Parsed_replaygain_0 @ 0x12a72f3b0] track_gain = -4.48 dB
```
Close enough..

However:
```
% mp3gain stereo.mp3
stereo.mp3
Recommended "Track" dB change: -4.900000

% mp3gain mono.mp3
mono.mp3
Recommended "Track" dB change: -7.450000
```

**Comment by jooola** [comment]
Hey, sorry for this late answer.

I converted the file from stereo to mono using Audacity, which seem to use lame for mp3 files (not sure about that).

FFMPEG and gstreamer seem to rely on the older version 1 of the replaygain specs https://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification.

I'll try to wrap my head around the specs.
But for now I'll simply trust ffmpeg.

Another small question, I know liquidsoap v2 will be able to run ffmpeg filters, does that mean we will be able to use the modern EBU R128 audio normalizer ?

**Comment by Warblefly** [comment]
Just a note about automatic EBU R.128 normalisation. It's not very nice on
music with heavy brass e.g. big band jazz. Because of its sensitivity to
frequency ranges as well as level, it will have the effect of lowering the
volume of loud brassy passages, which is unnatural. R.128 is a standard
designed for manual compliance.

Have you tried the many parameters of dynaudnorm?

You might have done so already, of course.

JW

**Comment by smimram** [comment]
As a side note, we already have LUFS computation native in Liquidsoap. I just added in a1b56b3fdb73d1e59c19a66b22f07eb25537eea4 an option to `normalize` to normalize based on LUFS (set `lufs=true`).
