### ISSUE TITLE
`source.remaining` return value is not look like remaining time of track

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#1817]
**Describe the bug**
Calling `source.remaining(s)` reports not remaining time, but something other.
For example sources can have no remaining time or remaining time will be the same even if source is playing.

**To Reproduce**
1. Create a `sample.ogg`
	For example I downloaded a [song](https://freemusicarchive.org/music/maarten-schellekens/single/dawn-3).
	Then converted it with `ffmpeg -i music.mp3 -c:a libvorbis -b:a 500k sample.ogg`
	And checked `ffprobe -hide_banner sample.ogg`
	```
	Input #0, ogg, from 'sample.ogg':
		Duration: 00:03:16.75, start: 0.000000, bitrate: 322 kb/s
	```
1. Create a command, that reports source info
	```
	def addSourceInfoCommand(~namespace = null(), src)
	  def generateResponse(_)
	    resultRecord = {success = true}

	    let resultRecord.namespace = namespace
	    let resultRecord.isFallible = source.fallible(src)
	    let resultRecord.isReady = source.is_ready(src)
	    let resultRecord.clockTime = source.time(src)

	    remainingTime = source.remaining(src)
	    let resultRecord.remainingTime = (remainingTime != infinity) ? remainingTime : null()

	    json_of(compact = true, resultRecord)
	  end

	  namespace = namespace ?? source.id(src)

	  server.register(
	    namespace = namespace,
	    usage = "info",
	    description = "Get source info",
	    "info",
	    generateResponse
	  )
	end
	```
1. Use it in source code 
	```
	security = single("sample.ogg")
	addSourceInfoCommand(namespace = "Security", security)
	```
1. Start server and execute command `Security.info` several times
1. Get output like 
	```json
	{"remainingTime":197.27399093,"clockTime":362.6,"isReady":true,"isFallible":false,"namespace":"Security","success":true}
	{"remainingTime":197.27399093,"clockTime":633.88,"isReady":true,"isFallible":false,"namespace":"Security","success":true}
	```
	Remaining time is the same every time.

**Expected behavior**
Remaining time will decrease over time.

**Version details**
 - OS: ubuntu:20.04 in docker
 - Version: `1.4.4` and `2.0.0-beta.3`

**Install method**
[Liquidsoap github release deb](https://github.com/savonet/liquidsoap/releases/download/v2.0.0-beta3/liquidsoap-v2.0.0-beta3_2.0.0.beta3-ubuntu-focal-1_amd64.deb)

**Common issues**
N/A

**Comment by toots** [comment]
Thanks for reporting. This is fixed in the latest `main` now.
