### ISSUE TITLE
json.strigify seems to return a list

### ISSUE THREAD

**Issue by millicent-audio-mirror** [savonet/liquidsoap#1840]
Hello,

I've noticed that since the change to json.strigify from json_of that i've been getting a ```some of array items are not an object``` error from my database. ( I'm using json.strigify to send metadata to a logging database).

Looking at the output from
```
 print("#{json.stringify(compact=false, m)}")
```
It seems to be returning a list not json. eg.
```
[
 [ "track_peak", "0.898430" ],
 [ "kind", "{audio=pcm(stereo),video=none,midi=none}" ],
 [ "artist", "unknown" ], [ "decoder", "FFMPEG" ], [ "liq_cue_in", "0" ],
 [ "title", "Ardour - Juanma Salinas Remix" ], [ "type", "music" ],
 [ "filename", "/tmp/liq-processd0172e.mp3\"\"\"" ], [ "temporary", "true" ],
 [ "source", "music" ],
[ "file_id", "60d4e5201c215f458fa3e8b7" ], [ "status", "playing" ],
 [ "mix_type", "Mix" ], [ "lastPlayed", "2021-08-19T12:41:12.000Z" ],
 [ "on_air", "2021/08/21 09:34:30" ],
 [ "rid", "10" ], [ "duration", "464.4" ],
 [ "liq_amplify", "-5.640000 dB" ]
]
```
Is this intended ?

Thanks.

**Comment by millicent-audio-mirror** [comment]
Changing code to 
```
    j = json()

    j.add("title", m['title'])
    j.add("artist", m['artist'])
    j.add("on_air", m['on_air'])
   .... etc

    dt = json.stringify(compact=true, j)

    res = http.post(headers=[("Content-Type","application/json")], data=dt, "API ADDRESS")
```

**Comment by millicent-audio-mirror** [comment]
Looking through my logs it seems that it's only occasionally i get the 
```
some of array items are not an object
```
error.

So it could be some metadata I'm passing through as an annotation that is causing it.

the above works for me and does the job i need it to so I'm not going to dig any deeper unless its useful to you guys.

Thanks

**Comment by vitoyucepi** [comment]
@millicent-audio-mirror 
It seems, that there's no more list of tuples to object conversion because of this https://github.com/savonet/liquidsoap/pull/1824/files#diff-be1a1ab728e3e66741d1ef2b67de01360ddbaa26948413c5aa88cba3cbf89fddL39.
So `[("key1", "value1"), ("key2", "value2")]` will become valid json of arrays.
```json
[
	["key1", "value1"],
	["key2", "value2"]
]
```
not an object
```json
{
	"key1": "value1",
	"key2": "value2"
}
```
like it was previously.

By the way it's possible to do with `list.iterator` over metadata.

```
# m is metadata - list of tuples [("key1", "value1"), ("key2", "value2")]
j = json()
for item = list.iterator(m) do
	let (tag, value) = item # destructuring tuple
	j.add(tag, value)
end
print(json.stringify(j))
```

Maybe it's possible with `list.fold` like this, but I can't make it work this way, because I'm still not a professional of typing.

```
# This code isn't working
def f(acc, item)
	let (tag, value) = item
	acc.add(tag, value)
	acc
end
j = list.fold(f, json(), m)
print(json.stringify(j))
```

Sometimes you would like to use special methods like `metadata.cover(m)` https://github.com/savonet/liquidsoap/blob/bdf718982025fd499bc4a378cdfec83cdaa8f9b4/libs/metadata.liq#L68
```
j = json()
for item = list.iterator(m) do
	let (tag, value) = item
	value = tag == "cover" ? metadata.cover(m) : value
	j.add(tag, value)
end
print(json.stringify(j))
```
Also you could move `value` extraction into another function.

**Comment by toots** [comment]
Thanks for this detailed response @vitoyucepi. We've removed the legacy ad-hoc conversion of `[string * 'a]` lists into objects. This was limited (all values in the object have to be of the same type) and potentially surprising (you would expect an array of pairs like we do for all other type of lists).

I could consider a `legacy` parameter that would optionally revert this back for users having trouble adapting their code to this new API but it would be rather intrusive so I'd like to take a minute to consider it. @millicent-audio-mirror would you let us know if you find @vitoyucepi's answer and the associated code change hard to implement? Thanks!

**Comment by toots** [comment]
> # This code isn't working
> def f(acc, item)
> 	let (tag, value) = item
> 	acc.add(tag, value)
> 	acc
> end
> j = list.fold(f, json(), m)
> print(json.stringify(j))

This looks like a bug in the typing system.

**Comment by millicent-audio-mirror** [comment]
Thank you @vitoyucepi and @toots .

I've managed to implement the code change , so no problems there. Though list folding is new to me so I'll have to research that to help my head understand.
