### ISSUE TITLE
shutdown liquidsoap after playing playlist

### ISSUE THREAD

**Issue by nesale** [savonet/liquidsoap#186]
Hi, tell me please

Task: shutdown liquidsoap after playing playlist

You have configured:

#!/usr/bin/liquidsoap -d
set("init.daemon",true)
set("init.daemon.pidfile",true)
set("init.daemon.pidfile.path", "/tmp/radio.pid")
set("log.file.path","/tmp/radio.log")
set("log.level",3)

source  =  crossfade(start_next=3.,fade_out=5.,fade_in=1.,mksafe(playlist.once("/home/radio/radio.m3u")))

output.icecast(
        %mp3(bitrate = 128,id3v2=false),
        host = "localhost",
        port = 8071,
        password = "radio",
        source
	)

BUT after playing playlist in the stream go silence, liquidsoap have process operating system

HOW TO MAKE: after playing playlist liquidsoap shotdown in work, included in OS and unmount icecast

**Comment by toots** [comment]
You should be able to do that by executing `shutdown` when the `playlist.once` is done: `playlist.once(on_done=shutdown,...)`
