### ISSUE TITLE
Trigger the new song at -12dB

### ISSUE THREAD

**Issue by ArvyRogerio** [savonet/liquidsoap#1869]
Hi, I'm new to LiquidSoap, I'm switching from SAM Broadcaster (Windows). I like the SB overlap method and I am trying to reproduce it in LS.

I want to trigger the new music when the old music reaches the "last -12dB", means, that after that point, no sound goes beyond -12dB, even the old music still has 10 seconds, a long "decay". No fades, just overlap both. But sometimes the song has an abrupt ending, a single "beat" of 0dB to -infinity dB at the very end of the song. In these cases, it will not overlap, it just plays the songs in sequence, as there is no “fading out”.

I've done hours of testing, but I still can't do it. Any idea?

My best result was:

`source = mksafe (crossfade (length = 1.5, width = 10, margin = 1., minimum = 0.5, smart = true, high = -3., medium = -22., fade_in = 0., fade_out = 0. , source)) `

Thanks!

**Comment by Warblefly** [comment]
On Thu, 2 Sept 2021, 18:15 Rogerio Arvy Vitiello, ***@***.***>
wrote:

> Hi, I'm new to LiquidSoap, I'm switching from SAM Broadcaster (Windows). I
> like the SB overlap method and I am trying to reproduce it in LS.
>
> I want to trigger the new music when the old music reaches the "last
> -12dB",
>

For this, I personally prepare the tracks with annotations, automatically.

I haven't fully documented the whole process of merging, annotating tracks
with leading silence cut, tails detected (including allowance for long
tails that must be kept e.g. "Bohemian Rhapsody"), and deduplication using
Chromaprint, but it's pretty reliable and automatic on this system now,
except for human intervention to decide which duplicates or near-duplicates
to weed out.

Volume detection and annotation also takes place.

https://github.com/Warblefly/TrackBoundaries
JW

**Comment by ArvyRogerio** [comment]
Thank you @Warblefly for the information. I'm studying how to do this. Reading this text and doing Google searches, I think I understand how Liquidsoap does the mixing at the end of the "old" song. See if I'm right: what I need is that each MP3 has a metadata called "liq_fade_out" with the position in seconds of the exit point. For example, in a 300 second song, the mix point might be at 297 seconds. Then, when there are 3 seconds left, Liquidsoap will "press play" on the new song to overlap the final 3 seconds. All my songs are edited manually, so I don't need the "liq_fade_in", I just need to know when the next song will play from the first one.

For that I need to insert the field "liq_fade_out" in all my MP3s and use cue_cut() and then crossfade(). My "next song" is dynamically read from a PHP script:

def my_request_function() =
  result = list.hd (default = "", get_process_lines ("/bin/php /home/liquid/generator.php"))
  [request.create (result)]
end

source = request.dynamic.list (my_request_function)

If I'm right, all I need now is to figure out how to detect the -12dB point at the end of each song and write the meta tag. Writing the meta tag via PHP I know how to do. So the question is "how do I discover this value" in each song. This is where I'm stuck. If you can help me, I'm grateful.

**Comment by ArvyRogerio** [comment]
I found a way, using Mixramp: https://bitbucket.org/discofish/mixramp2/src/master/

I get its return, process using a PHP script to find the first position lower than -12 dB, then "ffmpeg" (to convert to WAV), I get the MP3 duration using  "ffprobe" (-show_entries format=duration -v quiet -of csv="p=0"`), and finally I fill the extended tags in the original MP3 using "mid3v2" in a bash script (mid3v2 --TXXX "liq_cue_in:0." --TXXX "liq_cue_out:$Dif" --TXXX "liq_cross_duration:$Pos").

Works fine with LS, I still have some problems (ie, LS is cutting off the last seconds when overlapping, I don't know why), and I have a "gap" when overlapping to a Vorbis/Opus mountpoint in Icecast. Well, still studing. Thanks.
