### ISSUE TITLE
Crossfade with dynamic.request stops working after random time interval

### ISSUE THREAD

**Issue by cgrozev** [savonet/liquidsoap#187]
Dear all,

I am running Liquidsoap 1.1.1+scm (git://github.com/savonet/liquidsoap.git@887833c67a2f559c7d78aa3af8f4dc14250ecdfd:20140709:160051).

I have a problem with crossfade applied on dynamic.request, which is followed by cue_cut.

The mix works absolutely perfectly for a while, sometimes for days, sometimes for minutes after launching. Then it switches to sequencing without crossfading. It is unpredictable and thus unmanageable.
Has anyone experienced this before? Any ideas? Thank you in advance!
Here is the relevant part of the script:

```
# Dynamic playlist, calling php

def my_request_function() = 
  result =
    list.hd(
      get_process_lines("/usr/bin/php /var/www/playlist/get_next_sched.php -- r10_Zom"))
   request.create(result)
end
## Create the source
s = request.dynamic(my_request_function,conservative=true, length=60., timeout=10.)
f = mksafe(playlist(mode="normal","/channels/fallback/zommer.pls"))

s = cue_cut(s)
f = cue_cut(f)
enable_replaygain_metadata ()
s = amplify(1.05,override="replay_gain",s) 
s = crossfade(s)
s = fallback([s, f])

s = ladspa.multibandcompressor( ...etc)
s = limit(attack=1., release=100., threshold=-2., rms_window=0.001, gain=0., s)

s = amplify(1.4, s)
output.icecast(%aac(...etc,s), 
```

P.S. The logs show no issues, obviously.

**Comment by cjbars** [comment]
Has anyone found a solution to this problem?

**Comment by cjbars** [comment]
try this:
add
`s = mksafe(s) before
s = cue_cut(s)` 

Sometimes liquidsoap does not have time to download tracks and begins to accumulate errors.

**Comment by toots** [comment]
Hi,

This is a pretty old version of liquidsoap. Any luck with a more recent one? 

Gonna close this for now, please feel free to reopen or submit a new one.
