### ISSUE TITLE
Serve `metadata.on_air` in seconds instead of `pretty_date`

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#1871]
**Is your feature request related to a problem? Please describe.**
There's no internal method to convert `time` from pretty form as it reported in `on_air` to time in seconds since epoch.
```json
"on_air":"2021/09/03 03:15:15"
```

**Describe the solution you'd like**
Make `on_air` value in seconds.

**Describe alternatives you've considered**
Add function to parse time like `strftime` and `strptime`.
Maybe there's also should be an option to set pretty date format for logs. For example to print date in `ISO8601` format.

**Additional context**
N/A

**Comment by toots** [comment]
Thanks for this report. I have just added `on_air_timestamp` to request's metadata. Should come out with `2.0.0`.
