### ISSUE TITLE
make extract-replaygain regex match case insensitive

### ISSUE THREAD

**Issue by dwcarder** [savonet/liquidsoap#1888]
In using [rgain3](https://github.com/chaudum/rgain3) to precompute replaygain (once, in bulk) and apply it to files before being read by liquidsoap, I noticed rgain3 is using lower case `replaygain_track_gain` in the file metadata vs `REPLAYGAIN_TRACK_GAIN`. 

https://github.com/chaudum/rgain3/blob/1bffd2ea718aa383eed4e0632c788785c0d9fc0c/rgain3/lib/rgio.py#L55

In browsing various other replaygain implementations linked from wikipedia, it does appear that there is some ambiguity and both forms appear common.

If extract-replaygain were to do a case-insensitive match in the sed expression, it could accommodate both flavors.

Thus,

`$FFPROBE "$FILE" 2>&1 | $SED -n -r 's/.* REPLAYGAIN_TRACK_GAIN: ([-+]?[0-9]+\.[0-9]+ dB).*/\1/p'`
would become
`$FFPROBE "$FILE" 2>&1 | $SED -n -r 's/.* REPLAYGAIN_TRACK_GAIN: ([-+]?[0-9]+\.[0-9]+ dB).*/\1/pi'`

<br>

**Version details**
 - savonet/liquidsoap:v2.0.0-rc1 docker image

**Comment by dwcarder** [comment]
In looking at the ffmpeg source, it appears that it might also be doing a case insensitive match.
https://github.com/FFmpeg/FFmpeg/blob/25c8507818d8559a6654a5b30a0f8aae11a48181/libavformat/replaygain.c#L90

**Comment by toots** [comment]
Thanks for this report. This is fixed in the latest `main` and `v2.0.0` branch!
