### ISSUE TITLE
Cannot use some LADSPA plugins

### ISSUE THREAD

**Issue by christopher-mh** [savonet/liquidsoap#191]
Hello,

I was trying to build an AGC by using a sidechain compressor. But I cannot use multiple channels plugins like LADSPA SC2 or SC3 ones (or I misunderstood the use of those plugins).

Actually, I'm trying to build an AGC like that :

    Input → Compressor → Output
    Input → HPF → Sidechain of the compressor

Will the multichannel plugins be supported my Liqudisoap ?

(The normalize plugin and the replay gain don't satisfy me)

**Comment by smimram** [comment]
Hi,

Right now we are only registering the operators with mono or stereo inputs and outputs. The reason for this is that, while Liquidsoap supports more than 1 or 2 channels, there is currently not much support for muxing/demuxing multiple channels and thus plugins which are not stereo would not be really useable. It should not be too hard to add support for LADSPA with multiple audio channels, but we would need to come up with a decent way of using them.

For instance, in SC2 what are the inputs? From what you write there is a stereo audio input and a stereo audio to control the compressor is that right? I guess I could easily implement something which would work like this then:
```
source = playlist(...)
hp = hpf(souce)
output = ladspa.sc2(mux_stereo(source, hp))
```
Would this be ok for you?
