### ISSUE TITLE
add permalinks to the documentation

### ISSUE THREAD

**Issue by mcfiredrill** [savonet/liquidsoap#192]
It would be nice if I could just link someone to the documentation on a specific function like `fallback` immediately.

**Comment by smimram** [comment]
This is actually doable. For instance, the documentation of `output.alsa` is http://liquidsoap.fm/doc-svn/reference.html#output_alsa

**Comment by mcfiredrill** [comment]
Oh nice! I had no idea. :smile: 
Thank you so much.
