### ISSUE TITLE
Stream Switching No Longer Seamless in 1.4.3/1.4.4

### ISSUE THREAD

**Issue by Kerosel** [savonet/liquidsoap#1928]
**Describe the bug**
I was thrilled to find Liquidsoap 1.3.3 would do seamless/gapless playback on files ripped from CDs that had seamless transitions between tracks, i.e. mix CDs broken up into tracks for each song or an album that has tracks that run together. It was _so_ good that the only way you could tell the track changed was from the metadata push.

This behavior is no longer present in 1.4.3 or 1.4.4. There is a hitch at the transition point where the beat seems "short", like the outgoing stream is ending slightly early. How noticeable this is depends a lot on the audio of the transition, but in a mix with a steady beat carried from track to track, it stands out very prominently.

For completeness in eliminating variables, I played the tracks I was testing through Rhythmbox and verified that the original tracks do play back seamlessly.

**To Reproduce**
Create the simplest possible script to stream a playlist and play back adjoining tracks.

```
list = playlist.once("/***/DDR3/megamix.m3u")
output.icecast(%mp3, host = "*", port = *, password = "*", mount = "*", list, fallible=true)
```

I would be happy to supply some FLAC files from a mix CD where the hitch is quite noticeable going between tracks.

**Expected behavior**
I expected 1.4.3/1.4.4 to behave as 1.3.3 did and seamlessly join the outgoing stream with the incoming stream.

**Version details**
Debian 10 "Buster" - Liquidsoap 1.3.3 (expected behavior)
Debian 11 "Bullseye" - Liquidsoap 1.3.3 (expected behavior)
Debian 11 "Bullseye" - Liquidsoap 1.4.3 (unexpected behavior)
Debian 11 "Bullseye" - Liquidsoap 1.4.4 (unexpected behavior)

**Install method**
All Liquidsoap versions installed from Debian repositories _except_ version 1.4.4 package was downloaded from the Liquidsoap distribution page and installed manually.

Please let me know if there's anything else I can do to help out. I know this is a small thing and I'm probably overly-sensitive to timing issues in music, but I'm hoping it's not a difficult fix since it worked back in 1.3.3.

Also thank you everyone for your work on Liquidsoap. It's an amazingly simple yet powerful way to get all sorts of music going out on the internet. I've had so much fun with it since discovering it.

**Comment by toots** [comment]
Hi!

Thanks for this update. Could you try with the latest `v2.0.0-rc1` version? This is the version we are actively developing. You can find bullseye packages for it here: https://github.com/savonet/liquidsoap/releases/tag/v2.0.0-rc1.

I understand that this requires some changes to your script. We have documented most of them here: https://www.liquidsoap.info/doc-dev/migrating.html

**Comment by Kerosel** [comment]
Thanks Toots. I downloaded the DEB for 2.0.0-rc1 and installed it and ran my test script... transitions between tracks are seamless again in 2.0.0-rc1 so I'm going to close this issue. I have some other things that bug me about 2.0.0-rc1, but I'll see if I can open a discussion about them rather than spam issues that might not actually be issues (might be me being overly picky).

Oddly enough, I didn't have too much to retool in my main script, but the migration docs are definitely a big help. Thanks for putting those up.
