### ISSUE TITLE
Support for shoutcast2

### ISSUE THREAD

**Issue by Arsimael** [savonet/liquidsoap#193]
Hello,

Shoutcast got sold from AOL and the new owner discontinues the transcoder. 
I looked into liquidsoap and it has some very nice and neat features, but still doesn't support native SC2 Streaming. 
I read in an old mailinglsit from 2013 that SC2 doesn't get supported because if some gibberish licences/patents. I talked to the SC devs why they are not helping you, since there is absolutely NO alternative for the sc transcoder on linux. 

One of the devs itself said there are no restrictions and stuff left which keeps anyone to implement the sc2 protocol. 

http://forums.winamp.com/showthread.php?t=376646

Is there any chance to use liquidsoap with sc2 or are we still forced to use icecast with Liquidsoap?

Greetings
Arsimael

**Comment by toots** [comment]
See #216

**Comment by toots** [comment]
Fixed in #216
