### ISSUE TITLE
no argument labeled "delay"

### ISSUE THREAD

**Issue by Sakrecoer** [savonet/liquidsoap#1983]
**Describe the bug**
Since upgrade to 2.0.0-rc1. Liquidsoap fails to start. Seems my .liq script is not forward compatible?

**To Reproduce**
run the command `/home/liquidsoap/.opam/4.08.0/bin/liquidsoap /home/liquidsoap/liquidsoap-daemon/script/main.liq-run.liq`
Result: liquidsoap exits with warnings and errors:
```
At /home/liquidsoap/liquidsoap-daemon/script/main.liq, line 55, char 25-28:
Error 6: Cannot apply that parameter because the function at /home/dat/liquidsoap-daemon/script/main.liq, line 55, char 8-19
has no argument labeled "delay"!
```
Removing "delay" fromt that line results in another error:

```
Error 5: this value has type
  unit (inferred at /home/liquidsoap/.opam/4.08.0/lib/liquidsoap/share/liquidsoap/2.0.0-rc1/libs/deprecations.liq, line 221, char 2-25)
but it should be a subtype of
  source(_)
```

**Expected behavior**
liquidsoap starts

**Version details**
 - OS: Ubunty
 - Version 20.04

**Install method**
`opam`

**Comment by smimram** [comment]
It would be very helpful if you could show us at least the incriminated lines (e.g. line 55 of `main.liq`).

**Comment by Sakrecoer** [comment]
thanks for your reply, ans sorry for late response! i'll post those lines here as soon as i get to terminal.

**Comment by Sakrecoer** [comment]
here it is:
```
# Talk over stream using microphone mount.
mic = audio_to_stereo(input.harbor("mic",port=8050,password="wordpass",buffer=1.0))
radio = smooth_add(delay=0.8, p=0.15, normal=radio, special=mic)
```

**Comment by Sakrecoer** [comment]
And in case the discrepancy with the paths in the logs above made anyone tilt: i have a weird habit of editing out the username when pasting logs. So much for that occlusion attempt lol

**Comment by smimram** [comment]
As you can see in [the documentation](https://www.liquidsoap.info/doc-2.0.0/reference-extras.html#smooth_add) the parameter `delay` has been changed to `duration`.

**Comment by Sakrecoer** [comment]
Thank you @smimram ! That explains it! I did look at that documentation, and i did notice the absence of `delay`, but there is nothing in there that explicitly say it has been replaced. Now i know :)
