### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by Creepercdn** [savonet/liquidsoap#1992]
**Describe the solution you'd like**
Add Namespaces, like C/C++.

**Comment by smimram** [comment]
There is already sort of a namespace support: you can prefix function names by the module you would like them to be into. For instance, in the sandard library, we define the `length` functions for lists and strings with
```
def list.length(l)
  ...
end

def string.length(s)
  ...
end
```
which avoids any possible confiusion between the two. Isn't this enough for your needs?

**Comment by Creepercdn** [comment]
I want to define variables in the "namespace"

**Comment by smimram** [comment]
Isn't the definition of `list.length` precisely a definition of `lengh` in the "namesapce" `list`?

**Comment by Creepercdn** [comment]
I mean:
```
my.var = 100
print(my.var)
```

**Comment by smimram** [comment]
You can already write
```
my = ()
let my.var = 100
print(my.var)
```
which is essentially what you want:
- on the first line you declare the namespace `my`
- on the second line you define `my.var` (for ennoying reasons with the syntax you have to use `let` or `def` when declaring field members)

**Comment by Creepercdn** [comment]
Nice, thanks!
