### ISSUE TITLE
LS 2.0.0 crashed when changing to a song

### ISSUE THREAD

**Issue by ArvyRogerio** [savonet/liquidsoap#2015]
**Describe the bug**
LS 2.0 crashed when changing to a song.

**To Reproduce**
Not sure but I can provide the file where the error happened.
I'll try to test if happens in a specific file only.

**Version details**
 - OS: Debian 11
 - Version 2.0.0

**Install method**
Opam

-------------
2021/10/11 18:47:00 [decoder:2] Decoding "/mnt/3035.mp3" ended: Mad.End_of_stream.
2021/10/11 18:47:00 [request.dynamic.list_0:3] Prepared "/mnt/8322.mp3" (RID 2).
2021/10/11 18:47:00 [cue_cut_0:3] Cueing in...
2021/10/11 18:47:00 [crossfade_0:3] Analysis: -42.609094dB / 409.436324dB (3.32s / 3.32s)
2021/10/11 18:47:00 [crossfade_0:3] Simple transition: crossed, fade-in, fade-out.
liquidsoap: quantize.c:1968: ABR_iteration_loop: Assertion `eov->bitrate_index <= cfg->vbr_max_bitrate_index' failed.
Aborted

**Comment by ArvyRogerio** [comment]
Well, testing again. manually inserting the file in the queue, the problem didn't happen again.
Let me know if I can help anyway.

**Comment by toots** [comment]
The priorities work the other way, the decoder with the higher priority is selected first.. 🙂

As for disabling entirely, if you installed via `opam`, just remove the `mad` package!
