### ISSUE TITLE
Soundcard output hangs (starts stutteting) after several hours of playback

### ISSUE THREAD

**Issue by etretien** [savonet/liquidsoap#202]
Hi,

I need to play a randomized playlist during given hours (e.g. from 9:05 to 18:00), with several repeating smoothly added jingles. Jingles cannot play randomly but only at the specific moments (hours/minutes). 

I have a following script for that:

```
set("log.file.path", "liquidsoap.log")
set("log.level", 4)
set("log.stdout", true)
set("init.daemon.pidfile.path", "liquidsoap.pid")

def add_jingles(~delay=0.9,~p=0.0,~normal,~special,~meta)
  d = delay
  q = 1. - p
  c = amplify
  fallback(track_sensitive=false,
           [special,normal],
           transitions=[
             fun(special,normal)->
               add(normalize=true,
                   [c(0.0,meta),
                   c(q,normal),
                   c(q,fade.final(duration=d*1.5,type="sin",special))
                    ]),
             fun(normal,special)->
               add(normalize=false,
                   [c(p,normal),
                    c(q,fade.initial(duration=d*1.5,type="sin",special))
                    ])
           ])
end

def prepend_pause(track_metadata)
    s = blank(duration=1.0)
    map_metadata(fun(m)->track_metadata, s)
end

ch = playlist.safe("playlists/3/")

radio = mksafe(switch(track_sensitive = false, [
                ({ 9h05m0s-18h00m59s }, ch)
        ]))


jingles = empty()

track1 = prepend(merge=true, audio_to_stereo(single("1.mp3")), prepend_pause)
track1_m = switch([({15m0s},track1)])
track1_hm = switch([({9h0m0s-17h59m59s}, track1_m)])
jingles = add([track1_hm, jingles])

track2 = prepend(merge=true, audio_to_stereo(single("2.mp3")), prepend_pause)
track2_m = switch([({48m0s},track2)])
track2_hm = switch([({9h0m0s-17h59m59s}, track2_m)])
jingles = add([track2_hm, jingles])

track3 = prepend(merge=true, audio_to_stereo(single("3.mp3")), prepend_pause)
track3_m = switch([({10m0s},track3),({20m0s},track3),({40m0s},track3),({58m0s},track3)])
track3_hm = switch([({9h0m0s-17h59m59s}, track3_m)])
jingles = add([track3_hm, jingles])

track4 = prepend(merge=true, audio_to_stereo(single("4.mp3")), prepend_pause)
track4_m = switch([({55m0s},track4)])
track4_hm = switch([({9h0m0s-17h59m59s}, track4_m)])
jingles = add([track4_hm, jingles])

radio = add_jingles(delay=0.9,p=0.0,normal=radio,special=jingles,meta=jingles)
on_shutdown(event_shutdown)
radio = on_track(event_metadata, radio)
output.alsa(radio)
```

I tried to use standard smooth_add, but it didn't work:
- (most important) the on_track functions doesn't send me the name of the jingle, just the name of the track
- the music-to-jingle transmission is not that smooth (and if I increase set delay to more than 1 second, I can't hear all or some jingles at all, the main stream fades out and then fades in immediately)

So I tried to rewrite smooth_add in several ways, and the add_jingles() in the above code is its last version.

As for prepend() calls, those have been put there because I need the jingle to wait before the music stream fades out. Unfortunately I couldn't achieve this with sequence/blank operators in transition functions, as recommended in Cookbook (maybe I did it wrong, please advise): jingles don't play, or the jingle starts to play even earlier, etc)

**Anyway, the code above plays fine and sends metadata correctly, except one very bad thing: at some moments the playback hangs and starts stuttering. It hangs on one small piece of a track for several seconds, then advances to the next piece, etc.** 
I've recorded an example of this here: http://vocaroo.com/i/s0CdMLBZwywT

The stream can hang like this for hours. If I restart LS it returns to normal.

I've found some patterns:
1. When it hangs, the playback log continues as usual just as tracks were played normally. LS logs show the same, no errors, no warnings. However, jingles stops to appear in the logs, but not all the jingles! For example, in this script we have 4 jingles, and when it hangs, we can see only one or two of them in the logs (but they appear at the correct times, though). When LS is restarted and playback returns to normal, all jingles are played and appear in the log. I'm attaching here the today's (25/11) log in a file: http://paste.org.ru/?e6zqua. It hanged at ~15:30, and was like this until the stream stopped at 18:00.
2. It doesn't depend on hardware. Currently I have set up 3 different boxes with the same script and they demonstrate the same behaviour. They are all Atom-based, but different, two are quite new (this year), one is ~3y old.
3. It always starts at the same time (on the same script). E.g. today all 3 boxes with LS started at midnight with the same script (but different music content) hanged at the same time (at ~15:30). Sometimes some of them don't hang.
4. When the stream is hanged, I can run any track with mplayer and it plays normally on top of that stuttering stream.

The OS is Debian 7. I've tried to use LS 1.0.1 (from standard debian reps) and LS 1.1.1 from http://apt.sourcefabric.org/ (Airtime builds). In both cases the result is pretty much the same.

I couldn't reproduce this on a virtual machine (but didn't try much).

What else I have already tried:
- setting explicit device name in ~/.asoundrc as pcm.liquidsoap {type plug, slave { pcm "hw:0,0" }}
- changing add() to fallback() to add tracks to 'jingles' source (also hangs, and consumes much more CPU when I add more jingles)
- setting playlist reloading on (mode=rounds) and off

What I haven't tried yet:
- output.ao, etc instead of alsa (but doesn't libao use alsa itself?)
- experimenting with clocks (don't know what can I do here)
- playlist() instead of playlist.safe() - ?
- simplify jingles source construction and add_jingles(), getting rid of prepend(), etc - I need an advice here because I couldn't get it playing well otherwise.
- experimenting with compiling latest LS snapshots
- experimenting with different OS

Clearly, all of these are pretty blind ways to find a workaround, but not to find the root cause and solve the problem. And even if I find one, it can happen again any time in the future when the script or environment are changed. That's why I'm appealing for developers' help here.

**UPD**: today this issue has been reproduced on my local Debian virtual machine. It was running almost the same script, but with 24h playback, and without prepend() calls for jingles...

Thank you in advance,
Alexey.

**Comment by kenrestivo** [comment]
I had the exact same problem several years ago, with liquidsoap, on Ubuntu 10.04, using Airtime.

The problem was never solved. We just hacked around it by having a cron job reboot liquidsoap every few hours.

Ultimately it was assumed that the problem was due to underpowered hardware (single-core 3.5Ghz P4). That particular transmitter is being replaced by a multi-core i3 right now. It'll be interesting to see if it continues to fail, or if the problem was in fact due to CPU issues.
