### ISSUE TITLE
LIQUIDSOAP 2.0 CRASHING

### ISSUE THREAD

**Issue by glenbuck1** [savonet/liquidsoap#2028]
After running for several days, the script stops running; the first time it showed a memory error in the log, the second time, it just stopped without any warning or error message.

I have attached a partial log from both incidents showing script start-up and error message together with the portion of the log when it stopped without warning! I am also attaching the script file and have sent the file causing first failure privately.

A clear and concise description of what the bug is. Add some script and log extract so we can see what is happening. Don't forget to add some context although not necessarily your whole script..

**To Reproduce**
A minimal script to reproduce the issue is the most efficient way to have your bug addressed and fixed very quickly!
n/a
**Expected behavior**
Continue running until stopped manually
E**Version details**
 - OS: [e.g. Debian, OSX]
 - Version [e.g. `1.3.4`]
Ubuntu 21.10 (GNU/Linux 5.13.0-20-generic x86_64)
Icecast 2.4.4
LiquidSoap 2.0

**Install method**
Did you install via `opam`? Using your distribution's packages? From source?
Yes
**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)
[PartialAutoDJ.log](https://github.com/savonet/liquidsoap/files/7402762/PartialAutoDJ.log)
[autodj.txt](https://github.com/savonet/liquidsoap/files/7402767/autodj.txt)

**Comment by toots** [comment]
Have you tried removing `mad` entirely?

**Comment by toots** [comment]
Hi! Any update on this issue?

**Comment by glenbuck1** [comment]
Hi,

 

Sorry for delay in replying...

 

The crashes are still happening but at a much less frequent rate I'm pleased to say.  Generally, there seems to be about nine or ten days between them but, still, when they do occur, there is no error message or warning in the log.  Memory and swap usage is low so that shouldn't be a factor.

 

I am managing the situation by running a cron job to monitor for the liquidsoap process and, if it's not, restarting it – not ideal but a workaround.

 

Thanks

Richard Bartholomew

**Comment by oranjebloom** [comment]
Hi @toots and @glenbuck1 , I would also like to report that I am experiencing the same ... version 2.0.0 crashes on Debian Buster installed via opam. I did a clean install of Liquidsoap without mad and only ffmpeg. With mad it ran for about 7 days before it crashed, but with ffmpeg it only took 1 day. Please let me know what I can provide to help diagnose the problem. I already have the logs set to debug but I don't see anything suspicious. The daemon logs showed this ...

```
Nov 27 07:52:16 systrum systemd[1]: ssr2.liq-liquidsoap.service: Main process exited, code=killed, status=6/ABRT
Nov 27 07:52:16 systrum systemd[1]: ssr2.liq-liquidsoap.service: Failed with result 'signal'.
Nov 27 07:52:16 systrum systemd[1]: ssr2.liq-liquidsoap.service: Service RestartSec=100ms expired, scheduling restart.
Nov 27 07:52:16 systrum systemd[1]: ssr2.liq-liquidsoap.service: Scheduled restart job, restart counter is at 1.
Nov 27 07:52:16 systrum systemd[1]: Stopped ssr2.liq Liquidsoap daemon.
Nov 27 07:52:16 systrum systemd[1]: Starting ssr2.liq Liquidsoap daemon...
Nov 27 07:52:16 systrum liquidsoap[30548]: File /home/db/liquidsoap-daemon/script/ssr2.liq, line 15, char 0:
Nov 27 07:52:16 systrum liquidsoap[30548]: Warning 4: Unused variable metadata
Nov 27 07:52:16 systrum liquidsoap[30548]: File /home/db/liquidsoap-daemon/script/ssr2.liq, line 29, char 0:
Nov 27 07:52:16 systrum liquidsoap[30548]: Warning 4: Unused variable s
Nov 27 07:52:17 systrum systemd[1]: ssr2.liq-liquidsoap.service: Supervising process 30553 which is not our child. We'll most likely not notice when it exits.
Nov 27 07:52:17 systrum systemd[1]: Started ssr2.liq Liquidsoap daemon.
```

**Comment by oranjebloom** [comment]
I should also add that in order to filter out the cover art metadata, I added the following lines to my script.

```
#REMOVE METADATA COVER
#https://github.com/savonet/liquidsoap/issues/1872
#https://github.com/savonet/liquidsoap/issues/1590
#https://github.com/martinkirch/showergel/issues/20
def remove_metadata_cover(metadata) =
  [
    ("cover", ""),
    ("apic", "")
  ]
end
```

as well as the following line after ever source ...

`source  = map_metadata(strip=true, remove_metadata_cover, source)`

This probably explains the warning I get in the daemon logs when I start the liquidsoap service

```
Nov 27 07:52:16 systrum liquidsoap[30548]: File /home/db/liquidsoap-daemon/script/ssr2.liq, line 15, char 0:
Nov 27 07:52:16 systrum liquidsoap[30548]: Warning 4: Unused variable metadata
```

@toots could this be part of the reason for the crashes?

**Comment by oranjebloom** [comment]
Hi and thanks for the reply. I'll enable the core dump and let you know when I have something you can work with.

**Comment by glenbuck1** [comment]
Hi,

 

Since updating to this version from 2.0.0 on 6 December, I seem to be having
a problem with a show which is scheduled to run at 14:00 GMT on a Saturday.


 

On 11 December, the file attempting to be picked up was the previous one in
the *.pls file rather than the current one; then, after a few minutes, the
current file was finally loaded and started playing.

 

Today, 18 December, the file is not being picked up at all and the music
defined up to 14:00 is continuing to be played.  

 

I have attached the script file for info and the relevant entries are those
relating to FlashbackYears.

 

This was running successfully up until 11 December so I am not sure what has
changed and why the problem has started.  If anyone has any ideas, please,
I'd be most grateful.

 

Thanks for any help.

 

Richard Bartholomew

 

 

 


set("log.file.path","/home/radio/logs/autodj.log")
#settings.path.to.key.set(/home/radio/logs/autodj.log)

#playlists
jingles=audio_to_stereo(mksafe(normalize(playlist("/home/radio/jingles"))))
Sixties=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/decades/60s70s80s/1960s"))))
Seventies=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/decades/60s70s80s/1970s"))))
Eighties=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/decades/60s70s80s/1980s"))))
Nineties=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/decades/90s00s10s20s"))))
SixtiesPlus=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/decades/60s70s80s"))))
NinetiesPlus=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/decades/90s00s10s20s"))))
Breakfast=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/BreakfastClub"))))
Christmas=audio_to_stereo(mksafe(normalize(playlist("/home/radio/music/Christmas"))))
MondayPM=audio_to_stereo(mksafe(normalize(playlist(mode="normal", "/home/radio/playlists/MondayPM.pls"))))
WednesdayPM=audio_to_stereo(mksafe(normalize(playlist(mode="normal", "/home/radio/playlists/WednesdayPM.pls"))))
MemoryLane=audio_to_stereo(mksafe(normalize(playlist(mode="normal", "/home/radio/playlists/MemoryLane.pls"))))
GarageRock=audio_to_stereo(mksafe(normalize(playlist(mode="normal", "/home/radio/playlists/GarageRock.pls"))))
FlashbackYears=audio_to_stereo(mksafe(normalize(playlist(mode="normal", "/home/radio/playlists/FlashbackYears.pls"))))
Worship=audio_to_stereo(mksafe(normalize(playlist(mode="normal", "/home/radio/playlists/Worship.pls"))))


#scheduling
Monday=mksafe(switch(track_sensitive=false, [({0h-13h}, SixtiesPlus), ({13h-14h}, MondayPM), ({14h-20h}, SixtiesPlus), ({20h-22h}, NinetiesPlus), ({22h-0h}, SixtiesPlus)]))
Tuesday=mksafe(switch(track_sensitive=false, [({0h-14h}, SixtiesPlus), ({14h-16h}, NinetiesPlus), ({16h-0h}, SixtiesPlus)]))
Wednesday=mksafe(switch(track_sensitive=false, [({0h-3h}, MemoryLane), ({3h-15h}, SixtiesPlus), ({15h-17h}, WednesdayPM), ({17h-20h}, Seventies), ({20h-22h}, Sixties), ({22h-0h}, SixtiesPlus)]))
Thursday=mksafe(switch(track_sensitive=false, [({0h-14h}, SixtiesPlus), ({14h-17h}, Eighties), ({17h-0h}, SixtiesPlus)]))
Friday=mksafe(switch(track_sensitive=false, [({0h-1h}, GarageRock), ({1h-0h}, SixtiesPlus)]))
Saturday=mksafe(switch(track_sensitive=false, [({0h-14h}, SixtiesPlus), ({14h-15h}, FlashbackYears), ({15h-0h}, SixtiesPlus)]))
Sunday=mksafe(switch(track_sensitive=false, [({0h-7h}, SixtiesPlus), ({7h-10h}, Worship), ({10h-0h}, SixtiesPlus)]))

radio=mksafe(switch(track_sensitive=false, [({1w}, Monday), ({2w}, Tuesday), ({3w}, Wednesday), ({4w}, Thursday), ({5w}, Friday), ({6w}, Saturday), ({7w}, Sunday)]))
radio=mksafe(crossfade(smart=true, rotate(weights=[1, 3, 2], [jingles, Christmas, radio])))
output.icecast(%mp3(bitrate=192), name="The Phoenix Radio Record Machine", host="listen.phoenixradio1208.com", password="", port=8020, mount="autodj", radio)

**Comment by glenbuck1** [comment]
Hi, again

 

Further to my earlier message, The FlashbackYears.pls finally started
playing at 14:27:01 rather than 14:00:00 so would still really appreciate
some enlightenment, if possible, please.

 

Thanks

 

Richard Bartholomew

**Comment by oranjebloom** [comment]
Hi @toots, as instructed, I enabled core dumps on my Debian VDS and after 8 days of running version 2.0.0 it crashed. I have a link for you to download the core dump for that instance which I started via the Liquidsoap deamon.

https://systrum.net/core.systrum.zip

**Comment by toots** [comment]
Great thanks so much! The next step is to get a stack trace. I can do it myself if you tell me:
* What OS you are running (debian verison)
* How you installed liquidsoap

Alternatively, you can generate the stack trace by doing:
```
gdb /path/to/liquidsoap /path/to/core/dump
> thread apply all bt
```

I would still like to get the info on your OS/liquidsoap binary since that would also allow me to inspect the trace to get more info on the crash.

**Comment by oranjebloom** [comment]
Hi, I am running Debian 10 (Buster) and I installed via opam

**Comment by oranjebloom** [comment]
Hi @ toots, just a bit more info regarding my install on Debian 10 ... I installed via opam doing ...

```
opam depext taglib ffmpeg lame cry ssl samplerate magic lastfm inotify ocurl liquidsoap

opam install taglib ffmpeg lame cry ssl samplerate magic lastfm inotify ocurl liquidsoap
```

**Comment by toots** [comment]
Awesome, thank you, will report ASAP.

**Comment by toots** [comment]
Ok, unfortunately, I cannot get any info from that at the moment. I'll have to investigate. 

Meanwhile, I'd suggest installing the latest `ocaml-lame` version `0.3.5`. The opam package is pending but you can pin it:
```
git clone https://github.com/savonet/ocaml-lame
cd ocaml-lame
opam install -y .
```
I'd also consider installing the upcoming `v2.0.2`:
```
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap && git checkout v2.0.2-preview
opam install -y .
```
We just fixed a segfault in ocaml-lame that could very well be your issue here.

**Comment by oranjebloom** [comment]
Okay, I'll try your advice and see how it goes. Please let us know if your further investigation yields anything.

**Comment by toots** [comment]
Sounds good, thanks!

**Comment by toots** [comment]
Hi @oranjebloom ! Anything to report here? Hopefully, no news is good news?

**Comment by oranjebloom** [comment]
Hi @toots ... I'm still trying to get Liquidsoap 2.0.2 to install with ffmpeg. Pinning the dev version removes ffmpeg (like below) so I'm left with no decoder. Any advice?

```
The following actions will be performed:
  ⊘ remove  ffmpeg            1.1.0  [uses ffmpeg-avfilter, ffmpeg-av, ffmpeg-avcodec, ffmpeg-avutil]
  ⊘ remove  ffmpeg-swscale    1.1.0  [conflicts with liquidsoap]
  ⊘ remove  ffmpeg-swresample 1.1.0  [conflicts with liquidsoap]
  ⊘ remove  ffmpeg-avfilter   1.1.0  [conflicts with liquidsoap]
  ⊘ remove  ffmpeg-avdevice   1.1.0  [conflicts with liquidsoap]
  ⊘ remove  ffmpeg-av         1.1.0  [conflicts with liquidsoap]
  ⊘ remove  ffmpeg-avcodec    1.1.0  [conflicts with liquidsoap]
  ⊘ remove  ffmpeg-avutil     1.1.0  [conflicts with liquidsoap]
  ∗ install liquidsoap        2.0.2*


```

**Comment by oranjebloom** [comment]
... in the meantime, I'm running version 2.0.1 with the latest ocaml-lame. On average crashes have been happening around the 7 day mark. I'll definitely report back whatever the outcome.

**Comment by toots** [comment]
Awe man I was hoping the latest `ocaml-lame` was the issue. By the latest you mean `0.3.5` right?

As for your `ocaml-ffmpeg` issue, you need to pin it for now until it is released. I want to do it soon but you always find last minute fixes so I want to trigger that as late as possible. Here's the procedure to pin it:
```
git clone https://github.com/savonet/ocaml-ffmpeg.git
cd ocaml-ffmpeg
opam install -y .
```

**Comment by oranjebloom** [comment]
Yes, I'm using ocaml-lame 0.3.5 as recommended. There haven't been any crashes so far, so your fix may have worked, but I'll need to run it longer with Liquidsoap 2.0.1 to know for sure. I'll keep you posted. Thanks for the instructions regarding ffmpeg. I'll set up another instance with Liquidsoap version 2.0.2 and test that also.

**Comment by toots** [comment]
Ha great. Fingers crossed then!

**Comment by oranjebloom** [comment]
hi @toots , I just want to report that I have been running version Liquidsoap 2.0.2 with ocaml-lame 0.3.5 continuously since Jan 1st and there have been no crashes so far. I am going to continue running it for another week and if no crashes occur before then, we can probably assume that the issue has been resolved.

**Comment by toots** [comment]
Glad to hear!

**Comment by oranjebloom** [comment]
Hi @toots, I have been running the new version for 2 weeks without any problems. I think it's safe to assume the issue has been resolved and can be closed.
