### ISSUE TITLE
playlist.reload() dos not reload empty playlist

### ISSUE THREAD

**Issue by giflw** [savonet/liquidsoap#203]
When I create a playlist using a file (playlist.pls) and try to reload an empty playlist, liquidsoap keep playing old files instead of loading the empty playlist. The same applies to directory playlists (#196).

When I make a playlist empty I need that it plays blank until I reload it (if it is the only source) or be skeeped (if it is in a multiple sources configuration, like rotate).

Those are my expected results:

Single source (playlist should play blank when empty:

```
pls = playlist("playlist.pls")
out(pls)
```

Multiple sources (playlist should skipped when empty (or skip its turns)):

```
songs = playlist("songs.m3u")
jingles = playlist("jingles.pls")
s = rotate(weights=[1,3], [jingles, songs])
out(s)
```

In multiple sources configuration, if all playlist are empty, it should play blank.

**Comment by toots** [comment]
So, a fallible playlist should accept empty playlists on reload. See #218 for that. If you need the source to play blank when receiving an empty playlist, you will need use `mksafe()`.

**Comment by dbaelde** [comment]
Note that the playlist is fallible here so the proposed change won't be useful. The usual workaround, if one really wants an empty playlist is to make it non-empty but containing a broken URI, e.g., "/path/to/nowhere.ogg". I admit this is ugly and I am open to discussing a change of behavior, but I wonder if we have the time this deserves before a release.
