### ISSUE TITLE
Uisng reload_mode="watch", loop=false, causes messages to flood logs in version 2.0.0 

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#2040]
I am using `s = playlist(mode="normal", reload_mode="watch", loop=false, "/path/to/files")` in version 2.0.0 installed on Debian 10 via opam.

When this playlist has ended and it falls back to another source, liquidsoap complains that the request queue is empty. This message continues to flood the logs, like below.
```

2021/11/02 21:45:43 [voxpop1:5] Failed to prepare track: no file.
2021/11/02 21:45:43 [voxpop1:5] Queue is empty!
2021/11/02 21:45:43 [voxpop1:5] Failed to prepare track: no file.
2021/11/02 21:45:43 [voxpop1:5] Queue is empty!
2021/11/02 21:45:43 [voxpop1:5] Failed to prepare track: no file.
2021/11/02 21:45:43 [voxpop1:5] Queue is empty!
```

The log level is set to 5, and the message doesn't appear when set to level 3. Is it normal for this message to appear? I recall @smimram coming up with `reload_mode="watch", loop=false`, because of this same issue was occurring with the deprecated playlist.once

**Comment by toots** [comment]
Hi. Yes, I believe that this is normal to have this message and you can just ignore it unless you see any issue with CPU usage. Log level 5 is really designed for debugging so it will show a lot of information that is not necessarily related to issues.

Closing this ticket, please feel free to reopen if needed.
