### ISSUE TITLE
extract-replaygain missing lowercase metadata

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#2044]
**Describe the bug**
ffprobe seems to output metadata for `REPLAYGAIN_TRACK_GAIN` lowercase, which isn't caught by `$SED -n -r 's/.* REPLAYGAIN_TRACK_GAIN: ([-+]?[0-9]+\.[0-9]+ dB).*/\1/p'` in extract-replaygain.

**To Reproduce**
Take a file with replaygain metadata from rgain3 or Quod Libet, use ffprobe, seems like ffprobe spits the metadata full lowercase..

**Expected behavior**
extract-replaygain should catch those metadata, even if lowercase, which might be as simple to fix by adding `/i` to the sed flags

**Version details**
 - OS: Ubuntu 20.04
 - Version 1.4.3 (but 2.x seems to deliver the same script)

**Install method**
Installed using github actions packages for 1.4.3

https://github.com/savonet/liquidsoap/issues/1002 seems to indicate there is a will to remove that external trick..

**Comment by gilou** [comment]
also, there might be no need to call the extract script, if that's metadata is directly readable by liq..

**Comment by smimram** [comment]
Thanks for the report, we'll correct this. A side note: this script is mostly meant to be called if your files are *not* already tagged with RG info. Otherwise, Liquidsoap can already use the standard tags through the `replaygain` operator.

**Comment by smimram** [comment]
Also, it seems that `/i` is already present in the regexp you mention, isn't it?

**Comment by gilou** [comment]
You might have gotten it by email, but I edited my comment on github as I pasted the fixed version in my original message...

You might be right about the script call, I haven't checked what `enable_replaygain_metadata()` actually does under the hood. The use case here is simple, most of the files are rgain3-tagged, but some may not, so we'll allow some ffmpeg magic (or later on, by re-tagging them on the fly for good). But I think it's nice if the script works out of the box in this situation ;)

**Comment by toots** [comment]
It seems to me that the current regexp is case-insensitive:
```
  RG=`$FFPROBE "$FILE" 2>&1 | $SED -n -r 's/.* REPLAYGAIN_TRACK_GAIN: ([-+]?[0-9]+\.[0-9]+ dB).*/\1/pi'`
```

**Comment by smimram** [comment]
(see also #1888)

**Comment by gilou** [comment]
indeed, a dup, and I missed it as it's not that easy to follow the changes, even on "release" branch.. Thanks!
