### ISSUE TITLE
output.file not creating directory when using %ffmpeg format

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#2069]
**Describe the bug**
When I use flac/mp3 format, output.file() will nicely create the directories needed in the path, but if I try to use %ffmpeg, it fails.
For example:

`liquidsoap 'output.file(%ffmpeg(format="mp3", %audio.copy),"MP3/%Y%m%d-%H%M%S.mp3", input.http("http://some.mp3.somewhere/blah.mp3", new_track_on_metadata=false), reopen_on_error=true, reopen_when={20s or 40s}, flush=true, fallible=true)' --debug`

raises:

 `Error when starting MP3/%Y%m%d-%H%M%S.mp3: FFmpeg.Avutils.Error(No such file or directory)!`

**To Reproduce**
Use the script while not having a MP3 directory in the example, it will fail.

**Expected behavior**
Maybe create the directories, or document the issue ;)
If the dir exists: there is no issue at all

**Version details**
 - OS: Ubuntu 20.04
 - Version 2.0

**Install method**
Github Actions release .deb files

**Comment by toots** [comment]
Thanks that's a great one to fix. Took me more time than I thought because of a bug with ffmpeg but it should be fixed as soon as https://github.com/savonet/liquidsoap/pull/2072 passes the CI!

**Comment by toots** [comment]
Fixed in https://github.com/savonet/liquidsoap/commit/8519aaf71c209b54b0c4770d88e1d55d363646d9

**Comment by gilou** [comment]
This works on v2.0.1-preview, but you knew it ;)
