### ISSUE TITLE
truncating log files

### ISSUE THREAD

**Issue by willwh** [savonet/liquidsoap#207]
Hi Folks,

I run liquidsoap on Windows, and I'm wondering about truncating logs.

Here's the relevant snippet from my .liq:

```
set("log.file",true)
set("log.file.path","D:\station1.log")
set("log.stdout",true)
set("log.level",3)
set("server.telnet",true)
set("server.telnet.port",1234)
```

I've been logging since April, and they're now massive, and I'd like to be able to truncate them.

To give a little more context, the stations we run are 24/7, and we restart liquidsoap via telnet, each hour, to do some playlist reloads in a specific way.

Is there any way I could truncate the logs via telnet?

Any other options? Thanks!

**Comment by mcfiredrill** [comment]
Doesn't really seem like something liquidsoap itself should handle, most people use log rotation tools I imagine?

**Comment by toots** [comment]
Yeah, I agree with @mcfiredrill here. You can reopen the logs by sending a `USR1` signal to the liquidsoap process or simply use `logrotate`. There's a `liquidsoap.logrotate` script in the `scripts/` section of the sources that you can look at as well.
