### ISSUE TITLE
output.file (almost) failing to reopen when using %ffmpeg format and %audio.copy

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#2070]
**Describe the bug**
Using %ffmpeg and %audio.copy, it seems output.file is having a hard time when asked to reopen the file, and sometime even failing (noticed on a slow filesystem, but there might be something else at play here). However, whatever happens, it seems that it misses 1s on reopening...

If I reopen like every 30s, I get flooded with:
```
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.
2021/11/22 01:32:00 [MP3/%Y%m%d-%H%M%S.mp3:3] Re-opening output pipe.

```

**To Reproduce**
`liquidsoap 'output.file(%ffmpeg(format="mp3", %audio.copy),"MP3/%Y%m%d-%H%M%S.mp3", input.http("http://some-server/some-mountpoint.mp3", new_track_on_metadata=false), reopen_when={0s or 30s}, flush=true, fallible=true)' --debug`

**Expected behavior**
Not failing / reopening many times, as I suspect it's missing frames while doing that, and possibly crashing in some contexts. I'd say that it's missing less than 1s everytime... 

Maybe it's expected, but if I do something like reopen_when={0s or 10s or 20s or 30s or 40s or 50s}, I assume each file is going to be 10s, long, but I get 9s 38ms files in the end... I tried going for 1 minute for a more realistic usecase, I only get 59 s 36 ms / file...

What gives? Bug ? Bad usage of ffmpeg and audio.copy ?
My goal is to be able to dump an exact copy of what input.http gives me, without re-encoding it in the final file.

**Version details**
 - OS: Ubuntu 20.04
 - Version 2.0.0

**Install method**
github actions .deb release

**Comment by toots** [comment]
Could you try with the latest `v2.0.1-preview`? The fix for https://github.com/savonet/liquidsoap/issues/2069 also included a cleanup of the output code that might have helped with this. Thks!

**Comment by gilou** [comment]
Do you maintain builds for it as .deb, or do I need to build it from source?

**Comment by gilou** [comment]
also,  does it need a fresh ocaml-ffmpeg ?

**Comment by gilou** [comment]
No more errors with v2.0.1-preview on pipe re-opening, files are 1 minute long if I use {0s}, can’t check if the audio is correct until later on, but this looks good.

**Comment by toots** [comment]
Awesome, thanks for testing!
