### ISSUE TITLE
Liquidsoap 1.1.1. FDK-AAC help

### ISSUE THREAD

**Issue by DJAnonimo** [savonet/liquidsoap#208]
Hello,
I just installed the latest "I think" available liquidsoap version and when I try to encode to FDK-AAC I get:
Invalid value at line 7, char 1-124: No encoder found for that format.

How to install FDK-AAC encoder? Is there any simple way?

Thank You
```
liquidsoap --version
Liquidsoap 1.1.1+scm (git://github.com/savonet/liquidsoap.git@616e31bb1c41b3c5424b5395c21d524ea4e61164:20130515:153227)
```

* No LSB modules are available.
* Distributor ID: Debian
* Description:    Debian GNU/Linux 7.8 (wheezy)
* Release:        7.8
* Codename:       wheezy

**Comment by mcfiredrill** [comment]
You can see if you have support for a plugin with `liquidsoap --list-plugins`.

Try
`liquidsoap --list-plugins | grep -i aac`

If you installed from homebrew you should be able to able to pass the `--with-fdkaac` option to install with support for that.

**Comment by mcfiredrill** [comment]
Oh sorry, I guess you are on Debian?

**Comment by DJAnonimo** [comment]
Yes, Debian 7.8 wheezy.  liquidsoap_1.1.1~wheezy~sfo-2_amd64.deb

I tried to install libfdkaac-ocaml_0.2.0-1_amd64.deb with no luck.

What can I do?

 liquidsoap --list-plugins | grep -i aac
 + AAC
  Use libfaad to decode AAC if MIME type or file extension is appropriate.
 + ladspa.sine_faac
 + AAC
 + AAC
 + AAC+/LIBAACPLUS/DYNLINK

**Comment by toots** [comment]
You should try to install `fdk-aac` either from source or using the debian package: https://packages.debian.org/fdk-aac and the compile and install `ocaml-fdkaac` from source: https://github.com/savonet/ocaml-fdkaac hopefully, liquidsoap should pick up the dynamic module at start up once you've run `make install` in `ocaml-fdkaac`

**Comment by toots** [comment]
Hi. I'm gonna close this one as it's not technically and issue in the code. Please refer to the explanations above or the mailing list. All the best with your liquidsoap projects!

**Comment by nuess0r** [comment]
No, liquidsoap does not pick up the dynamic module at start. 

Version 1.1.1 which is included in the debian repos (jessie to sid) is nine days older than the commit "Added dynamically loaded fdkaac encoder." (dfbb7bb3556e8d615cc5692001778878e0fbf454).

The needed libraries (libfdkaac-ocaml-dynlink and libfdk-aac0) are now in the debian package repositories (activate contrib and non-free).

I opened a bug at debian to update the package. I will see if someone has the time to do it.

**Comment by attilagyorffy** [comment]
@nuess0r did you manage to get liquidsoap on debian (well, ubuntu) to pick up the `%fdkaac` encoder?

**Comment by attilagyorffy** [comment]
I'm getting AAC support reported but that specific encoder cannot be found (`No encoder found for that format`):

```
$ liquidsoap --list-plugins | grep -i aac
 + AAC
  Use libfaad to decode AAC if MIME type or file extension is appropriate.
  Enable or disable external FAAD (AAC/AAC+/M4A) decoders. Requires faad binary in the path for audio decoding and metaflac binary for metadata. Does not work on Win32.
   Endoding format. For shoutcast, should be mp3 or AAC(+).
 + AAC
 + AAC
```

I have the following packages installed:

- libfdkaac-ocaml-dynlink
- fdkaac
- libfdk-aac0
- liquidsoap-plugin-faad

**Comment by nuess0r** [comment]
@attilagyorffy Sorry for the long delay, but I had to finish my master thesis :-)

No. As I explained the versions currently in the Debian/Ubuntu repositories are compiled without fdk support. There is no newer version around yet.

If you like, you can comment to the Debian bug, to raise the awareness a bit.

In the meantime you have to follow the instructions to compile it yourself.


Regarding your error report you get: The reported AAC support means that you can use the encoder %aac but not %aacplus or %fdaaac. They would be listed separately.
