### ISSUE TITLE
Can a request contain a playlist? 

### ISSUE THREAD

**Issue by cgrozev** [savonet/liquidsoap#209]
I was trying to feed a pls source to dynamic request, but liquidsoap tries to interpret the playlist file as an audio file. I was expecting that request would also interpret uri's recursively - apparently not.
Is there any other way to feed a mini-playlist of (3-4) tracks with their own metadata via a dynamic call inside liq? If possible, I prefer a single pre-loading event as opposed to sequentially loading them one by one.
Is queue a solution here (i.e. can queue be appended inside the liq script or does it always have to be called via telnet?

thanks for any ideas
Christo

**Comment by dbaelde** [comment]
A media request (as used in request.queue/dynamic(), playlist(), single()...) cannot contain a playlist. If you want to do dynamic stuff, you should use request.queue() or request.dynamic(). As you guessed, the queue allows you to pre-load all your requests in one go. (It makes other things more complex, such as loading new stuff before the queue empties, but that won't matter e.g. if your playlist is to be loaded at a particular time of the day.) Cheers.
