### ISSUE TITLE
Usage Question: Automatic Recording for Each Live DJ Broadcast

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#2090]
Hello everyone!

Currently, we're using a bit of a runaround way of recording live broadcasts:
 - The input harbor has an "onConnect" event that calls a PHP script, which then makes a telnet connection back to Liquidsoap and tells the script to start recording with a new filename
 - The "onDisconnect" event on the harbor calls the same PHP script, which then calls, via telnet, the "stop recording" function.

Part of the reason for the complicated nature of this is because all of the input harbor functions are defined, by necessity, _before_ the recording functions, which means that, at least as far as I've seen, there's no easy way for the harbor onConnect/onDisconnect functions to call the recording start/stop functions, as they necessarily exist "lower" in the code than they do.

Here's an example of how we currently do this from the Liquidsoap side:

```
# DJ Authentication
live_enabled = ref(false)
last_authenticated_dj = ref("")
live_dj = ref("")

def dj_auth(login) =
    user = ref("")
    password = ref("")

    if (login.user == "source" or login.user == "") and (string.match(pattern="(:|,)+", login.password)) then
        auth_string = string.split(separator="(:|,)", login.password)

        user := list.nth(default="", auth_string, 0)
        password := list.nth(default="", auth_string, 2)
    else
        user := login.user
        password := login.password
    end

    log("Authenticating DJ: #{!user}")

    ret = list.hd(process.read.lines(env=[("DJ_USER", !user), ("DJ_PASSWORD", !password), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/auth --form dj-user="$DJ_USER" --form dj-password="$DJ_PASSWORD" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast DJ Auth Response: #{ret}")

    authed = bool_of_string(ret)
    if (authed) then
        last_authenticated_dj := !user
    end

    authed
end

def live_connected(header) =
    dj = !last_authenticated_dj
    log("DJ Source connected! Last authenticated DJ: #{dj} - #{header}")

    live_enabled := true
    live_dj := dj

    ret = list.hd(process.read.lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djon --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Live Connected Response: #{ret}")
end

def live_disconnected() =
    dj = !live_dj

    log("DJ Source disconnected! Current live DJ: #{dj}")

    ret = list.hd(process.read.lines(env=[("DJ_USER", dj), ("API_AUTH", !azuracast_api_auth)], 'curl -s --request POST --url http://web/api/internal/1/djoff --form dj-user="$DJ_USER" --form api_auth="$API_AUTH"'), default="")
    log("AzuraCast Live Disconnected Response: #{ret}")

    live_enabled := false
    last_authenticated_dj := ""
    live_dj := ""
end

# A Pre-DJ source of radio that can be broadcast if needed',
radio_without_live = radio
ignore(radio_without_live)

# Live Broadcasting
live = input.harbor("/", id = "input_streamer", port = 8005, auth = dj_auth, icy = true, icy_metadata_charset = "UTF-8", metadata_charset = "UTF-8", on_connect = live_connected, on_disconnect = live_disconnected, buffer = 5.00, max = 10.00)
ignore(output.dummy(live, fallible=true))

radio = fallback(id="live_fallback", replay_metadata=false, track_sensitive=false, [live, radio])

# Record Live Broadcasts
stop_recording_f = ref (fun () -> ())

def stop_recording() =
    f = !stop_recording_f
    f ()

    stop_recording_f := fun () -> ()
end

def start_recording(path) =
    stop_recording ()

    output_live_recording = output.file(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), fallible=true, reopen_on_metadata=false, "#{path}.tmp", live)
    stop_recording_f := fun() -> begin
        output_live_recording.shutdown()
        process.run("mv #{path}.tmp #{path}")
    end
end

server.register(namespace="recording", description="Start recording.", usage="recording.start filename", "start", fun (s) -> begin start_recording(s) "Done!" end)
server.register(namespace="recording", description="Stop recording.", usage="recording.stop", "stop", fun (s) -> begin stop_recording() "Done!" end)
```

We've recently run into some reliability issues caused by this little game of telnet telephone that we're playing in the existing code, so I would love some assistance in making this entirely function within Liquidsoap.

(To answer any possible questions: it's certainly possible for Liquidsoap to determine the filename to be generated, as it would just be the authenticated DJ username followed by a timestamp, and our own scripts could take advantage of that without needing to control the process the way they currently do)

**Comment by vitoyucepi** [comment]
@SlvrEagle23 here's some ideas

```
def create_harbor(~port, ~mount)
  file_name = ref("")
  stream = ref(source.fail())

  def auth(credentials)
    print("auth")
    print(credentials)
    if not ref.get(stream).is_ready()
      file_name := file.temp("", "")
      true
    else
      false
    end
  end

  def on_connect(headers)
    print("connect")

    print(headers)
    print(!file_name)
    print(ref.get(stream).id())
    ()
  end

  def on_disconnect()
    print("disconnect")
    print(!file_name)
    ()
  end

  def on_close(arg)
    print("close")
    print(arg)
    print(!file_name)
    ()
  end

  stream := input.harbor(
    mount,
    port = port,
    auth = auth,
    on_connect = on_connect,
    on_disconnect = on_disconnect
  )
  output.file(
    %vorbis,
    {!file_name},
    !stream,
    fallible = true,
    on_close = on_close
  )
  !stream
end


# Live Broadcasting
live = create_harbor(port = 8000, mount = "/live")

output.dummy(mksafe(live))
```

1. I create function `create_harbor` to simplify harbor initialization.
   Also I think that it's good not to spam variables all over the global scope.
2. `output.file` will start automatically when `stream` will be ready.
   But the only way to move file after creation is to handle this by `on_close` handler.
3. There's race condition in `auth` function.
   But this is the only place where it's possible to get `login`.
4. `on_connect` function receives stream-specific headers, so it doesn't know `login` or who is streaming at the current time.
5. `on_disconnect` isn't necessary for this script, because there's no need to close `output.file`.
6. In liquidsoap 2.0 `output.file` will no longer return anything.
   So it's not possible to call any of the [methods](https://www.liquidsoap.info/doc-2.0.0/reference.html#output.file) as far as I know.
7. It's possible to generate name once, but I don't know how to protect `auth` from multiple connections at the same time.

Some other thoughts
1. In 2.0 you can utilize `http.*` functions like `http.get` to obtain data.
   JSON can be used as a conversation format.
2. Instead of `telnet` it's possible to use `harbor.http`.
   It's possible to have both `telnet` and `http` APIs with the same commands.
   - `telnet`
     ```
     > api.server.restart
     < {"success": true}
     ```
   - `http`
     ```
     > curl http://liquidsoap/api/server/restart
     < {"success": true}
     ```

**Comment by SlvrEagle23** [comment]
@vitoyucepi That's a lot of really useful information, thank you very much. That gives me quite a lot I can work with in improving the structure of our auto-generated code.

**Comment by SlvrEagle23** [comment]
An update on this: I was able through some of the sample code above to rewrite the broadcast recording mechanism so it was handled entirely on the Liquidsoap side, so basically our application returns a filename it should be recording to, and it then takes over, recording to a temporary file and then moving the file over to its expected location, with no extra telnet commands necessary, and with far, far higher reliability than we've seen before.

The documentation, I'm afraid, is still too sparse for me to feel comfortable using `http.post` in lieu of cURL for internal API calls, and for me to use `harbor.http` in lieu of the Telnet server (especially because it appears to require manual registration of every API command, unlike Telnet). I hear things are set to improve on that front in 2.1.0, so I'm certainly looking forward to that.

**Comment by vitoyucepi** [comment]
@SlvrEagle23 
> especially because it appears to require manual registration of every API command, unlike Telnet

I'm not 100% sure if I understand what do you mean, but here's another sample of code.

```
let api = ()
let http_port = 8000
http_path_prefix = "api/server"
telnet_path_prefix = "api.server"

def api._server_restart()
  restart()
  {success = true}
end

def telnet_response_json(data_json)
  try
    json.stringify(compact = true, data_json)
  catch _error do
    log.severe(label = "telnet", null.get(error.message(_error)))
    ""
  end
end

def http_response_json(data_json)
  try
    http.response(
      code = 200,
      content_type = "application/json; charset=UTF-8",
      data = json.stringify(compact = true, data_json) ^ "\n"
    )
  catch _error do
    log.severe(label = "http", null.get(error.message(_error)))
    http.response(code = 500)
  end
end

def api.server_restart_http(~protocol = _, ~headers = _, ~data = _, _)
  http_response_json(api._server_restart())
end

def api.server_restart_telnet(_)
  telnet_response_json(api._server_restart())
end

def api.register_commands()
  harbor.http.register(
    port = http_port,
    method = "GET",
    "#{http_path_prefix}/restart",
    api.server_restart_http
  )

  server.register(
    namespace = "#{telnet_path_prefix}",
    usage = "restart",
    description = "Restart server",
    "restart",
    api.server_restart_telnet
  )
end
```

1. To register commands I call `api.register_commands()`.
2. Each of the commands I have to register separately.
   For example I want server to `restart`.
   If I want to register `sleep`, then I'll create another `server.register` and `http.http.register`.
3. `api.server_restart_telnet` and `api.server_restart_http` are adapters for private `api._server_restart` function.
4. `http_response_json` and `telnet_response_json` are util functions, so it'll be possible to use them in all adapters

It is also possible to create function, that will return functions
```
def a(~protocol = _, ~headers = _, ~data = _, _)
  http.response(code = 200, data = "I'm http")
end

def b(_)
  "I'm telnet"
end

def c(type)
  if type == "http" then
    a
  elsif type == "telnet" then
    b
  end
end
```
