### ISSUE TITLE
Incorrect position reported for strings

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#2095]
In the code
```
_ = "334" + 2
```
we get the erorr
```
At tes.liq, line 1, char 8:
```
where the position corresponds to the last `"` instead of having the whole token `"334"` colored. It seems that this is due to the use of the `read_string` function in the lexer.

**Comment by smimram** [comment]
Note: it seems that sedlex does not offer any function to set the start position of the current lexeme...

**Comment by toots** [comment]
We do keep the start position of the lexer buffer while parsing the string. However, it seems that the parser only receives a single position information at the end of the lexer buffer. We should see how we can enhance the coordination between lexer and parser at that level.

**Comment by toots** [comment]
Fixed!

<img width="248" alt="Screen Shot 2021-12-11 at 3 18 15 PM" src="https://user-images.githubusercontent.com/871060/145691947-ad105349-b4ee-409d-80f2-44dbb7f6a002.png">

**Comment by smimram** [comment]
Great! How come `"334"` is not colored in your terminal? (it should be in red...)

**Comment by toots** [comment]
It was done through the interactive console!

**Comment by toots** [comment]
<img width="262" alt="Screen Shot 2021-12-12 at 10 31 03 AM" src="https://user-images.githubusercontent.com/871060/145720796-24f59e85-fb98-482f-826f-f0c36304fe5d.png">
 Wow nice!
