### ISSUE TITLE
Question: Liquidsoap in Other Languages?

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#2096]
Edit: Disregard this...looking back at the Liquidshop, I can't find any reference to the possibility for writing Liquidsoap script in other languages and then "transcoding" it. I have no idea where I got that idea, but I could swear it applied to Liquidsoap.

**Comment by toots** [comment]
Hi,

This is not necessarily a bad idea nor something we wouldn't consider. With the changes that @smimram is adding to the core type system and runtime data structures, the language is moving more and more toward being a fully featured language with a semantics/typing system close to scripting languages such as TypeScript.

One of long term goal is to see if we could extract the language and use it to e.g. transpile liquidsoap code to Javascript for instance. If and when this happens, it probably would also be possible to consider the other direction, i.e. Javascript to liquidsoap.

However, one thing to keep in mind is that the complexity of liquidsdoap scripts comes, I believe, more from the _sematics_ of the operators than the language itself. Our operators have complex underlying behavior and, most of the time, issues come from specific subcases of e.g. how metadata are passed, or a switch picks up the next source, how a transition is computed etc.

On this level, we are working extensively toward re-implementing the internals of the language to:
* Move as many functionalities as possible to the scripting level
* Minimize the core OCaml internals to simplify them

The last effort that will start soon will be a rewrite of the streaming model (metadata, media frame, track marks) which allow us to cleanup a lot of the operator's logic and, hopefully, make the whole implementation easier to reason, debug and, eventually, more predictable to use in end-user scripts.
