### ISSUE TITLE
Sudden silence during streaming

### ISSUE THREAD

**Issue by kkacprzak** [savonet/liquidsoap#211]
Hello,

I installed liquidsoap on Ubuntu 14.04 and have some problems running it for longer time. I run the simple script, that randomly plays songs from directory to Icecast server. Everything seems to be ok, but after about 7 hours stream goes silent, that is: songs are still randomly picked, played entirely, but with volume 0. It happens on random song, during play. Only way to fix it is to restart liquidsoap script. 
I have checked the logs, but found nothing interesting.
Also, I used second computer with the same configuration to cross-stream one from another. I turn out that it must be liquidsoap on the first machine, because stream from first died after 7 hours, and from second - not. 
Can you give me a hint, what to check, where to look, in order to investigate for an error.

Best regards.

**Comment by toots** [comment]
Hi. We've have multiple reports of this kind but were unfortunately never able to pin it down. We don't even know if it comes from liquidsoap itself or OCaml or a third party lib.. What we discovered, though, is that the bug didn't seem to happen for 64 bit machines so perhaps that could help you?
