### ISSUE TITLE
buffer overrun using crossfade and request.dynamic.

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#2116]
**Describe the bug**
I have a script that uses ```add``` to mix up to 4 sources (1 request.dynamic - 3 queue.queue) of which 2 have crossfades ( 1 smart 1 not ).

Up to commit 583be814942a0d4a2b0c8435c404187ff715cda2 this caused me minimal problems.

After the above commit I get no errors at log level 3 but log level 4 show many ```generator4: buffer overrun: dropping of 0.04s``` ,  unless I remove both crossfade functions from the script . 

My cpu is showing maybe 5% increase on each core to about 25% each, but is still got plenty of head room (70% on each core).

Thanks.

**To Reproduce**
I can provide if needed

**Expected behavior**
no frame dropping.

**Version details**
 - OS: [e.g. Debian, OSX] - Ubuntu server 20.04
 - Version [e.g. `1.3.4`] - git main- 2.1.0+

**Install method**
OPAM

**Comment by Russsgithub** [comment]
This script for example results in a lot of 
```
[generator:4] Buffer overrun: Dropping 0.04s. Consider increasing the max buffer size!
```
messages in the log and a fast stuttering stream.

```
next_track.py returns annotate:.........:s3://....mp3
```

```
def nextm_mix() =
  result = list.hd(default="", process.read.lines("../python_scripts/next_track.py"))
  request.create(result)
end

mix = request.dynamic(id="music_mix", prefetch=3, nextm_mix)

mix = crossfade(mix)

output.icecast(fallible=true, icy_metadata="true", format="audio/aac", %fdkaac(channels=2, samplerate=48000, bitrate=320, bandwidth=20000,afterburner=true, transmux="adts", aot="mpeg4_aac_lc", sbr_mode=false), host="HOST", port=8000, password="PASS",mount="test",mix)

```

**Comment by toots** [comment]
Thanks for this report. Am I correct to assume that this is with the latest `main`? Do you have the issue with `2.0.1` or `2.0.2`?

**Comment by Russsgithub** [comment]
This seems not to be a problem with the latest code on git hub, so I'll close the issue.

Thanks
