### ISSUE TITLE
track_sensitive = false is not working

### ISSUE THREAD

**Issue by mylselgan** [savonet/liquidsoap#2119]
**Describe the bug**
I want to end the currently playing track immediately with fade and start playing next playlist as per schedule.
But the next playlist starts only after finishing the current track

**To Reproduce**
```
default=fallback(track_sensitive = false, [ switch([({ (4w) and 17h30-17h35}, playlist1),
({ (4w) and 17h35-17h40}, playlist2),
({ (4w) and 17h40-17h45}, playlist3),
({ (4w) and 17h45-17h50}, playlist4),
({ (4w) and 17h50-17h55}, playlist6),
({ (7w) and 16h20-16h50}, playlist7),
({ (4w) and 18h40-18h45}, playlist1),
({ (4w) and 18h45-18h50}, playlist2),
({ (4w) and 18h50-18h55}, playlist3),
({ (4w) and 18h55-19h0}, playlist4),
({ (4w) and 19h0-19h5}, playlist5),
]), playlist6])
default=mksafe(default)
def crossfade(~start_next,~fade_in,~fade_out,s)
fade.in = fade.in(duration=fade_in)
fade.out = fade.out(duration=fade_out)
fader = fun (_,_,_,_,a,b) -> add(normalize=false,[fade.in(b),fade.out(a)])
cross(duration=start_next,fader,s)
end
radio = crossfade(start_next=5.,fade_in=5.,fade_out=5.,default)
s = fallback(track_sensitive=false, [live,radio])
```

**Expected behavior**
End the currently playing track immediately with fade and start the next playlist as per schedule.

**Version details**
Debian GNU/Linux 9 (stretch)
Liquidsoap 1.4.4

**Install method**
Opam

**Common issues**
Next scheduled playlist waits for the current track to finish.

**Comment by betweenus** [comment]
Hi. Try use track_sensitive = false for swirch operator.

`switch(track_sensitive = false, [ ...`

**Comment by mylselgan** [comment]
@betweenus Thnaks, it works now.
