### ISSUE TITLE
LS restarting - seemingly at random

### ISSUE THREAD

**Issue by SpeedyCharly** [savonet/liquidsoap#2125]
As you well know we just finished going through the process of fixing the problem of buffer overruns and CPU overloads but a new weird problem has now surfaced - It seems LS kicks it's head up at random and restarts the stream for no apparent reason.
Here is a portion of log where it kicked me off of a live stream and restarted; 
[Booted off 1.txt](https://github.com/savonet/liquidsoap/files/7777116/Booted.off.1.txt)
And another episode a bit later which unfolded a bit differently:
[Kicker off-Log.txt](https://github.com/savonet/liquidsoap/files/7777117/Kicker.off-Log.txt)

Logs from this morning (26-12) show 3 restarts within minutes of each other during AutoDJ operation;
[12-26 log.txt](https://github.com/savonet/liquidsoap/files/7777120/12-26.log.txt)
Same behavior was observed yesterday morning also...

Slvr Eagle @ Azuracast reports seeing the same in other operator's reports also....

 - OS: Ubuntu
 - Version 20.04 - up to date

**Install method**
Docker [AzuraCast]

**Comment by SpeedyCharly** [comment]
For those interested... further developments on this may be read at https://github.com/AzuraCast/AzuraCast/issues/4922#issuecomment-1001211493

**Comment by toots** [comment]
Any update on this @SpeedyCharly ?

**Comment by toots** [comment]
Closing as per https://github.com/AzuraCast/AzuraCast/issues/4922#issuecomment-1001623831
