### ISSUE TITLE
DJs getting booted from the stream

### ISSUE THREAD

**Issue by SpeedyCharly** [savonet/liquidsoap#2129]
For a few days now [ starting 22-12] we have DJs getting booted from the stream, or having difficulty logging in.  Following is a log snippet from the first occurrence on the 22nd.  Random restart wasn't yet fixed then and one occurred during the problem, which is why I assument the 2 were somehow related;
[22-12 Weird episode.txt](https://github.com/savonet/liquidsoap/files/7782102/22-12.Weird.episode.txt)

I have logs of episodes on the 24th and 26th [none occurred on the 25th] but I'll spare you those. Let's jump to the mess of today;
[27-12 -Multi Occurrences.txt](https://github.com/savonet/liquidsoap/files/7782109/27-12.-Multi.Occurrences.txt)

This is an edited log [1070 lines of text] outlining multiple occurrences during the course of our live streaming.  I've managed to get a screenshot of the SAM Broadcaster event log which shows nothing out of the ordinary during the first recorded incident.  
![SAM log](https://user-images.githubusercontent.com/66107794/147515554-3a3bbba3-63b2-468b-804f-0d723867ea94.jpg)

Here's hoping you'se guys ain't to weary of my constant problem reporting...

Cheers; SPEEDY
     Pls don't hesitate to call on me if further info is required.

 - OS: [UBUNTU]
 - Version [20.04 - up to date]

**Install method**
[Docker - AzuraCAst]

**Comment by SpeedyCharly** [comment]
Difficulty logging in for the first dj this morning; wonder if related to the current problem...
[!st dj login this AM.txt](https://github.com/savonet/liquidsoap/files/7785274/st.dj.login.this.AM.txt)

Also, as seen in AzuraCast, I don't appear to be correctly connected...
![Image1](https://user-images.githubusercontent.com/66107794/147580362-fec9f8b1-d653-4da1-8c6f-20cb974d25bb.jpg)

**Comment by SpeedyCharly** [comment]
29-12 - All went well for most of the day until a couple event hit the last 2 djs.  Here is edited portions on log;
[29-12 log.txt](https://github.com/savonet/liquidsoap/files/7791493/29-12.log.txt)

**Comment by SpeedyCharly** [comment]
Question as an aside; is it normal for the first handshake to happen on port 8006 at dj login since our encoder only invokes 8005?

**Comment by toots** [comment]
Port `8006` should only be used for shoutcast connections. Could some of your live source clients be configured to use the shoutcast protocol?

**Comment by SpeedyCharly** [comment]
all of them are we is operating in Shoutcast environment, not ice....  We all use SAM Broadcaster 4.2 and login on 8005

**Comment by SpeedyCharly** [comment]
Trouble at handover this am;
[Trouble at dj handover.txt](https://github.com/savonet/liquidsoap/files/7794148/Trouble.at.dj.handover.txt)

I get a lot of these;
-----------------------------
2021/12/30 13:02:37 [lang:3] AzuraCast Feedback Response: OK
2021/12/30 13:02:38 [buffer_499:4] Buffer emptied, buffering needed.
2021/12/30 13:02:38 [buffer_498:4] Buffer emptied, buffering needed.
2021/12/30 13:02:38 [crossfade_0:4] Buffering end of track...
2021/12/30 13:02:38 [crossfade_0:4] More buffering will be needed
----------------------------

Does that mean I need to increase my buffer to help prevent these drops??

**Comment by SpeedyCharly** [comment]
Still having issues with DJ's being dropped.  Please have a look at this log ;
[DJ dropped.txt](https://github.com/savonet/liquidsoap/files/7836473/DJ.dropped.txt)

**Comment by SpeedyCharly** [comment]
Cross-reference with https://github.com/AzuraCast/AzuraCast/issues/4983
