### ISSUE TITLE
Help, the port is getting an error after reboot, and it will not connect to liquid Soap

### ISSUE THREAD

**Issue by NeedanXpert** [savonet/liquidsoap#213]
Can someone help me reconnect the port on the server?

Thanks

**Comment by mcfiredrill** [comment]
What is the error message you are seeing?

**Comment by smimram** [comment]
This error is too vague and likely to be an error du to the fact that you did not relaunch Liquidsoap properly. Feel free to reopen and be more precise if you think that this is really an issue in Liquidsoap.
