### ISSUE TITLE
Liquidsoap 2.0.2: SRT 0.2.1 not released to OPAM

### ISSUE THREAD

**Issue by chrko** [savonet/liquidsoap#2139]
**Describe the bug**
Liquidsoap 2.0.2 requires SRT 0.2.1, but this isn't released: https://opam.ocaml.org/packages/srt/ – also the tag is missing.

**To Reproduce**
```
opam install srt liquidsoap
```
yields `liquidsoap=2.0.1` installed.

```
opam install liquidsoap=2.0.2
```
removes `srt=0.2.0`

**Expected behavior**
Recent liquidsoap version installed via OPAM

**Version details**
 - Debian Stable
 - ArchLinux

**Install method**
`opam`

**Comment by toots** [comment]
Just published it and pushed a package to opam: https://github.com/ocaml/opam-repository/pull/20354. Thanks for reporting.
