### ISSUE TITLE
Can't get input.harbour to work correctly...

### ISSUE THREAD

**Issue by nokturnal** [savonet/liquidsoap#215]
First off, let me set the stage with my newb'ness... I am brand new to Icecast and liquidsoap... I fumbled my way through the installations on a fresh ubuntu 14.04 server... I gathered various snippets and ended up with this as my script file:

```
#!/usr/bin/liquidsoap

# Log dir
set("log.file.path","/tmp/some-radio.log")

# Live DJ stuff
#set("harbor.bind_addr","0.0.0.0")
#set("harbor.verbose",true)
#livedj = input.harbor(
#       "live",
#       port=8000,
#       password="********"
#)

# Music
mixes = playlist(mode="randomize",reload=3600,reload_mode="watch","/mnt/nfs/some/path/mixes/blah.m3u")

# Some jingles
jingles = playlist(mode="randomize",reload=3600,reload_mode="watch","/mnt/nfs/some/path/jingles/blah.m3u")

# If something goes wrong, we'll play this
security = single("/mnt/nfs/some/path/security/error.mp3")

# Set rotation
rotation = rotate(weights=[1,2],[jingles,mixes])

# Set Radio
#radio = fallback(track_sensitive = false, [livedj, rotation, security])
radio = fallback(track_sensitive = false, [rotation, security])

# Stream it out
output.icecast(
        %mp3(bitrate=128),
        host = "localhost",
        port = 8000,
        password = "********",
        mount = "master",
        radio
)
```

IT WORKS!...

... until I uncomment all the "livedj" stuff at the top and add "livedj" to the radio = fallback line... I get the following in the log file:

```
2015/05/06 22:23:54 >>> LOG START
2015/05/06 22:23:54 [protocols.external:3] Found "/usr/bin/wget".
2015/05/06 22:23:54 [main:3] Liquidsoap 1.1.1
2015/05/06 22:23:54 [main:3] Using: graphics=[distributed with Ocaml] pcre=7.0.2 dtools=0.3.1 duppy=0.5.1 duppy.syntax=0.5.1 cry=0.2.2 mm=0.2.1 xmlplaylist=0.1.3 lastfm=0.3.0 ogg=0.4.5 vorbis=0.6.1 opus=0.1.0 speex=0.2.0 mad=0.4.4 flac=0.1.1 flac.ogg=0.1.1 dynlink=[distributed with Ocaml] lame=0.3.2 shine=0.1.1 gstreamer=0.2.0 frei0r=0.1.0 voaacenc=0.1.0 theora=0.3.0 schroedinger=0.1.0 gavl=0.1.5 bjack=0.1.4 alsa=0.2.1 ao=0.2.0 samplerate=0.1.2 taglib=0.3.1 magic=0.7.3 camomile=0.8.4 inotify=1.0 faad=0.3.2 soundtouch=0.1.7 portaudio=0.2.0 pulseaudio=0.1.2 ladspa=0.1.4 dssi=0.1.1 sdl=0.9.1 camlimages=4.0.0 lo=0.1.0 yojson=1.1.7 gd=1.0a5
2015/05/06 22:23:54 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2015/05/06 22:23:54 [dynamic.loader:3] Could not find dynamic module for aacplus encoder.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/mad.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/faad.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/taglib.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/ogg.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/lame.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/voaacenc.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/pulseaudio.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/cry.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/vorbis.cmxs.
2015/05/06 22:23:54 [dynamic.loader:2] Loaded plugin file /usr/lib/liquidsoap/1.1.1/plugins/flac_ogg.cmxs.
2015/05/06 22:23:54 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2015/05/06 22:23:54 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2015/05/06 22:23:54 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2015/05/06 22:23:54 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2015/05/06 22:23:54 [decoder:3] Method "MAD" accepted "/mnt/nfs/some/path/security/error.mp3".
2015/05/06 22:23:54 [single:3] "/mnt/nfs/some/path/security/error.mp3" is static, resolving once for all...
2015/05/06 22:23:54 [threads:3] Created thread "generic queue #1".
2015/05/06 22:23:54 [threads:3] Created thread "generic queue #2".
2015/05/06 22:23:54 [clock.wallclock_main:2] Error when starting master: Address already in use in bind()!
2015/05/06 22:23:54 [master:1] Got ill-balanced activations (from master)!
2015/05/06 22:23:54 [clock:2] Error when leaving output master: File "source.ml", line 403, characters 10-16: Assertion failed!
2015/05/06 22:23:54 [main:3] Shutdown started!
2015/05/06 22:23:54 [main:3] Waiting for threads to terminate...
2015/05/06 22:23:54 [main:3] Cleaning downloaded files...
2015/05/06 22:23:54 [main:3] Freeing memory...
2015/05/06 22:23:54 >>> LOG END
```

I would love any advise on this... Like I painfully explained, I am a super newb to all this stuff and have no idea where to begin to try to solve this... thanks :)

**Comment by mcfiredrill** [comment]
Are you running icecast on port 8000?
Check out this errror:
```
2015/05/06 22:23:54 [clock.wallclock_main:2] Error when starting master: Address already in use in bind()!
```

Something on your system is already using port 8000. I usually pick another port like 9000 for the harbor.

**Comment by nokturnal** [comment]
Sorry for being so new to this, I really hope these are not stupid statements... but here goes :)...

Yes, I am running icecast in it's default config and am successfully sending the radio out to port 8000 when I comment out all the harbor stuff.

I have modified my script to have the harbor use port 9000 but still end up with the exact same errors:
```
livedj = input.harbor(
        "live",
        port=9000,
        password="*****"
)
```

Also, I can successfully use BUTT to broadcast to "live" on port 9000 and listen to the mount directly...So I think icecast is working as it should be...

**Comment by mcfiredrill** [comment]
Sorry I'm kind of confused now, you said you get the same errors, but you can broadcast successfully to the "live" mount on port 9000? :question: 

Maybe I'm misunderstanding the question. What exactly is the issue with input.harbor if you can broadcast to it successfully?

**Comment by nokturnal** [comment]
Sorry, I did not explain that very well.  Let's take liquidsoap out of the equation for the explanation...

I can broadcast from a remote system (using BUTT) to Icecast on port 9000 using the mount name of "live".  In turn, I can access the stream via http://serverip:9000/live and play it... I can only assume that means that Icecast is working as expected if that all works...

The issue is when liquidsoap attempts to use the "live" mount as the harbor...

Does that make some more sense?

**Comment by mcfiredrill** [comment]
If that is the case, then it appears icecast is listening on port 9000 as well. Icecast should *not* be listening on the same port as `input.harbor`, or liquidsoap will be unable to use it. What does your icecast configuration look like? In particular, your <listen-socket> elements? That is where you define the ports for source clients in icecast.
```
    <!-- You may have multiple <listener> elements -->                                                                                            
    <listen-socket>                                                                                                                               
        <port>8000</port>                                                                                                                         
        <!-- <bind-address>127.0.0.1</bind-address> -->                                                                                           
        <!-- <shoutcast-mount>/stream</shoutcast-mount> -->                                                                                       
    </listen-socket>                                                                                                                              
```

At least, that sounds like the problem to me so far. I could be wrong.

**Comment by nokturnal** [comment]
ahhhhh... ok. So I think I fundamentally did not understand how input.harbor works... I assumed you had to broadcast to icecast and liquidsoap would connect to that mount and relay it to the output streams.  Instead you broadcast your live stream directly to liquidsoap... Is that correct?

I have modified my script to use port 9001 for the harbor (unused by icecast):

```
livedj = input.harbor(
        "live",
        port=9001,
        password="*****"
)
```

I can now run the script without error!

That said, I can no longer connect BUTT to that system from a remote PC and therefore cannot live stream... The system is on the same internal network and could connect directly to Icecast as previously explained... Any ideas?

**Comment by mcfiredrill** [comment]
Ah I see. Yes you have it right now. You connect directly to liquidsoap through the harbor.

The harbor is likely working fine now.
Sometimes I have issues with BUTT. Do you have any other source clients you could try?
Can you check the log for any errors when connecting with BUTT?

**Comment by nokturnal** [comment]
I have tried BUTT, MIXX, and now NiceCast on a Mac... NiceCast is actually giving me an authentication error whereas the others fail silently.  I guess that's good news hehehe... How do I tackle this new turn of events :)

**Comment by nokturnal** [comment]
OK... I got NiceCast to broadcast!  It seemed to be either the username of "source" and/or the mount point of live that created the issue.  I changed the username to "dj" and the mount to "livedj" and everything worked!

For completeness, BUTT 0.1.14 had a code change that makes it not play well with LS (https://forum.sourcefabric.org/discussion/17237/butt-0-1-14-is-dead-with-airtime-/p1).  Long story short, if you install 0.1.13 everything works as it should :) (http://sourceforge.net/projects/butt/files/butt/butt-0.1.13/)

Cheers and thanks for trying to help out @mcfiredrill

**Comment by mcfiredrill** [comment]
Glad you got it working!
Thanks for sharing that info, I was wondering why so many people report problems with BUTT.
Honestly kind of disappointed at the state of source clients right now. :( All the free solutions seem to have various issues.

At least there's Nicecast, cheers!

**Comment by nokturnal** [comment]
@mcfiredrill and at least there is a working older version of BUTT... Since I can't dictate what OS a client can be using BUTT is the only real answer.  I really should knuckle down and try to write a WebRTC client... there has to be a way to get that to work!

**Comment by mcfiredrill** [comment]
Does this mean liquidsoap doesn't support PUT for source clients? 
Seems like that might be a bug.
