### ISSUE TITLE
run_process error in liquidsoap ≥ 2.0.0

### ISSUE THREAD

**Issue by nikoroxy** [savonet/liquidsoap#2160]
**Describe the bug**
Commands with run_process() throws an "Undefined variable" error.

**To Reproduce**
Install 2.0.0 or greater and run any command containing run_process() method

**Expected behavior**
Successfully execute said method
 
**Version details**
tested on 
 - OS: Manjaro and RapberrypiOS
 - Version 1.4.4, 2.0.0, 2.0.2
 - Installed via opam 
 
**Running example**
```
<><> liquidsoap.1.4.4 installed successfully ><><><><><><><><><><><><><><><><><>
=> Congratulations on installing liquidsoap! 

[nik@thinkpad ~]$ liquidsoap 'print(run_process("echo Hello World!"))'
("Hello World!\n", "", ("exit", "0"))
No output defined, nothing to do.
```

**Error example**
```
<><> liquidsoap.2.0.2 installed successfully ><><><><><><><><><><><><><><><><><>
=> ✨ Congratulations on installing liquidsoap! ✨

[nik@thinkpad ~]$ liquidsoap 'print(run_process("echo Hello World!"))'
At line 0, char 6-18:

Error 4: Undefined variable run_process
```

**Comment by toots** [comment]
`run_process` was removed in favor of `process.run` but we forgot to add a deprecation for it. I'd recommend to update your script to use `process.run` but meanwhile, here's a wrapper you can add to your script to keep using it:
```ruby
def run_process(%argsof(process.run), p) =
  x = process.run(%argsof(process.run), p)
  (x.stdout, x.stderr, ("#{x.status}", x.status.description))
end
```

**Comment by nikoroxy** [comment]
Thanks, i was just poking with It so it isn't a big problem
