### ISSUE TITLE
Liquidsoap github main code not installing with opam

### ISSUE THREAD

**Issue by millicent-audio-mirror** [savonet/liquidsoap#2167]
**Describe the bug**
With most recent gti main code ( 9bbd6d191ab3d44b17b5d66c8441a6aa0721c21a ) pinned to opam I get this error msg at install. My last pull from git was dcf16ee3e1986cf681664adf192db5df71994338, which worked as expected.

```
[liquidsoap.2.1.0] no changes from git+file:///home/ubuntu/liquidsoap#main

Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
```

**Version details**
 - OS: - Ubuntu 20.04
 - Version - 2.1.0

**Install method**
Opam

**Comment by gilou** [comment]
What in you repin it? opam is weird with pinned packages, but I sometimes need to reinstall or re-pin the repos for it to see there was a changed…

**Comment by toots** [comment]
Hi! As part of the ongoing bugfix work the following bindings need to be pinned to their latest `git` version:
* `ocaml-mad`
* `ocaml-mm`
Please note that `2.1.0` is currently  ongoing some deep changes. We encourage early testing and reports but we will prioritize fixing issues on the `2.0.x` dev branch.

**Comment by Russsgithub** [comment]
thanks @toots

**Comment by codeofdusk** [comment]
@toots I've cloned, pinned, and installed savonet/ocaml-mad and ocaml-mm but am still running into the "no solution found" error when attempting to install commit 17c585c56b30c2070eef4409680b5b9f093f2b72.
