### ISSUE TITLE
video.add_text not updating text

### ISSUE THREAD

**Issue by kessenza** [savonet/liquidsoap#2188]
```ruby
def get_time()
"time #{string_of_float(time())}"
end

s = video.add_text(get_time,font="/home/ubuntu/bankgothic.ttf",size=22,y=600,speed=140, s)
```

If I launch this script it doens't change text on screen. But if I use video.add_text.native instead of video.add_text in that case text with increasing time appears correctly on screen

I am using Ubuntu 20, liquidsoap 2.0.2 installed via Opam

**Comment by toots** [comment]
Thanks for this report. Do you have logs of your script? The operator is picked-up at runtime depending on your installation so that would help us figure out which one you are actually using. Thanks!

**Comment by kessenza** [comment]
Yes I inspected the code and I understood that video.add_text.best is got automatically but I can't figure which one.
I am attaching log about the test but also with that log I can't get which method is using. 
My test.liq script is as following

#!/root/.opam/4.10.0/bin/liquidsoap -v
  
settings.init.allow_root.set(true)
settings.frame.video.width.set(1280)
settings.frame.video.height.set(720)
settings.log.file.path.set("/tmp/liquidsoap.log")
settings.log.stdout.set(true)
settings.log.level.set(5)

s = mksafe(playlist(reload_mode="watch",mode="normal","/opt/video/loop640/hplaylist.pls"))
s = fallback([s, blank()])

def get_time()
"time #{string_of_float(time())}"
end

s = video.add_text(
      get_time,font="/home/ubuntu/bankgothic.ttf",size=22,y=600,speed=140, s)

output.icecast(
 %ffmpeg(format="mpegts",
         %audio(codec="ac3",channel_coupling=0),
         %video(codec="libx264",profile="baseline",tune="zerolatency",
                     b="1800k", g=45, preset="veryfast")
        ),
icy_metadata="false",
        host="localhost",
        port=8000,
        password="hackme",
        mount="/test",
s)
[liquidsoap.log](https://github.com/savonet/liquidsoap/files/7973390/liquidsoap.log)

**Comment by toots** [comment]
Looking at the code it was probably the ffmpeg one, which was fixed in a previous commit. SDL compilation was fixed earlier and I just changed it as the new default. This issue should also be fixed now. Thanks for reporting!

**Comment by kessenza** [comment]
This was exactly what I thought.
But the strange thing is look at this code

s = mksafe(playlist(reload_mode="watch",mode="normal","/opt/video/loop640/hplaylist.pls"))
s = fallback([s, blank()])

def get_time()
"time #{string_of_float(time())}"
end

s = video.add_text.ffmpeg(
      get_time(),font="/home/ubuntu/bankgothic.ttf",size=36,y=600,speed=200, s)

output.icecast(
 %ffmpeg(format="mpegts",
         %audio(codec="ac3",channel_coupling=0),
         %video(codec="libx264",profile="baseline",tune="zerolatency",
                     b="1800k", g=150, preset="veryfast")
        ),
fallible=true,
icy_metadata="false",
        host="localhost",
        port=8000,
        password="hackme",
        mount="/test",
s)

this produces screenshot A (see attachment), while if change  video.add_text.ffmpeg to  video.add_text this produce screenshot B. Can you see text difference? Moreover with video.add_text.ffmpeg the movement of the text from right to left is a bit jerky, while with video.add_text is very smooth.
Shouldn't two method be the same thing?

Thanks
![b](https://user-images.githubusercontent.com/19859582/151922267-f704c649-6e83-45ac-b522-be2dc15cf3d0.png)
![a](https://user-images.githubusercontent.com/19859582/151922273-208fc1ae-656e-450f-adbb-ec65e7362e8c.png)
