### ISSUE TITLE
video.transparent method not found

### ISSUE THREAD

**Issue by kessenza** [savonet/liquidsoap#2206]
Hi, here at doc https://www.liquidsoap.info/doc-2.0.2/video.html it's written that's it's possible to use video.transparent
but it seems that transparent it's not a available method

I tried to implement it directly using ffmpeg.filter.colorkey but it doesn't work. I think I am doing something wrong but can't realize what.

Here my code
```
s1 = single("overlay.png")
s2 = single("test.mp4")

def video.transparent(s) =
   v=ffmpeg.raw.encode.video(%ffmpeg(%video.raw), s)
  def mkfilter(graph) =
        v1 = ffmpeg.filter.video.input(graph, v)
        v1= ffmpeg.filter.colorkey(color="blue",graph,v1)
        ffmpeg.filter.video.output(graph,v1)
  end
 ffmpeg.filter.create(mkfilter)
 ffmpeg.raw.decode.video(v)
end

s1 = video.transparent(s1)
s = add([s1,s2])
```
I tried also switching s1 and s2 order like that s = add([s2,s1]) but still doesn't work
Any help would be appreciated

I am using liquidsoap 2.0.2 installed via opam on Ubuntu 20

**Comment by smimram** [comment]
Yes it somehow got lost when converting to YUV420. However, this functionality can easily be obtained with appropriate plugins. For instance, `video.frei0r.bluescreen0r` should mostly do that (you need to install frei0r plugins for this).

**Comment by kessenza** [comment]
Great man! You saved my day. It works perfectly. Just a little suggestion. You should update doc https://www.liquidsoap.info/doc-2.0.2 and add also some info about this extension. I only found some references on LS book but not online. I found also (on the book) that add_text.native doesn't support font (as also stated with the issue #2186 ) but on the online doc font is a parameter supported

video.add_text.native
Display a text.

Type:

(?id : string?, ?color : int, ?cycle : bool,
 ?font : string, ?metadata : string?, ?size : int,
 ?speed : int, ?x : {int}, ?y : {int}, {string},
 source(audio='a, video=yuva420p('b), midi='c)) ->
source(audio='a, video=yuva420p('b), midi='c)

Anyway thanks. You all are doing a great job here

**Comment by smimram** [comment]
Actually, adding back `video.transparent` was easy :): https://github.com/savonet/liquidsoap/pull/2208 

Also @toots added a warning about the font of `video.add_text.native` recently here in ec017d199a8735e06769b7ee6805f6400456b1ca
