### ISSUE TITLE
Add support for youtube HLS output

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#2209]
Youtube apparently supports [HLS ingestion](https://developers.google.com/youtube/v3/live/guides/hls-ingestion). Since we already have support for HLS, I guess it should not be too hard to add a youtube backend in this way !...

**Comment by toots** [comment]
It already is! Unfortunately, it is relying on some recent changes in `http.post` so only available in `main` at the moment.

**Comment by smimram** [comment]
Wow this is so great, I had missed that! For future reference, this is `output.youtube.live.hls`.
