### ISSUE TITLE
Error 4: Undefined variable server.telnet

### ISSUE THREAD

**Issue by theotherjenkutler** [savonet/liquidsoap#2214]
**Describe the bug**
Liquidsoap does not appear to be recognizing server.telnet() function

**To Reproduce**
```
#!/usr/bin/liquidsoap
server.telnet() 

set("log.file",false)
#set("log.file.path", "/home/jenkutler/ls_logs/measures.log")
set("log.stdout",true)
set("log.level",3)
# Music
myPlaylist = playlist(mode='randomize',reload=1,reload_mode="rounds", "/home/jenkutler/audio/")

# Start building the feed with music
radio = myPlaylist

# Stream it out
output.icecast(%mp3,
  host = "localhost", port = 8000,
  password = "measures", mount = "liquidsoaptest.mp3",
  radio,
  fallible = true)
```
**Expected behavior**
"In order to start the server, one should begin by calling the server.telnet function: server.telnet()"

**Version details**
 - OS: Ubuntu 20.04.3
 - Version [e.g. `1.4.1

**Install method**
 opam -- followed the instructions in the book

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by smimram** [comment]
What version of Liquidsoap are you using (you can obtain it with `liquidsoap --version`)?

What makes you think that it does not work? Do you have a particular error message?

**Comment by smimram** [comment]
Also `server.telnet` is basically an alias for
```
settings.server.telnet.set(true)
```
which might work better, but I fear that there are some installation problems: you are mentioning opam in your report, but `/usr/bin/liquidsoap` is not a path where opam would typically install a program (it is rather in `~/.opam/...`). My guess is that you have two versions of liq on your system...

**Comment by theotherjenkutler** [comment]
Yes. Thank you my mistake! I uninstalled the apt package and installed it opam and now it is working great. Thank you very much for the help!
