### ISSUE TITLE
`video.add_image` not respecting alpha channel on png images

### ISSUE THREAD

**Issue by kessenza** [savonet/liquidsoap#2216]
`video.add_image` seems not  respecting alpha channel on png images

I am using liquidsoap 2.0.2 installed via opam on ubuntu 20

**Comment by smimram** [comment]
Fixed by 716f6162cde67cec99fc88b037de45dfdeb21d6c.

**Comment by JoCat** [comment]
Debian 11, Liquidsoap 2.0.6, same problem

**Comment by toots** [comment]
@JoCat Looks like this fix is only in the `2.1.x` branch, you should try this rolling release: https://github.com/savonet/liquidsoap/releases/tag/rolling-release-v2.1.x. We're expecting to do s first release of `2.1.x` in the next week or so.
