### ISSUE TITLE
catch up x.xx secs warning after simple actions like `add_image` and `add_text`

### ISSUE THREAD

**Issue by kessenza** [savonet/liquidsoap#2218]
I have a simple script like this
```
def get_time()
t= time.local()
"#{pad(t.hour)}\:#{pad(t.min)}\:#{pad(t.sec)}"
end

s = blank()

s = video.add_image(file="/home/ubuntu/logo.png",x=1155,y=15,width=100,height=100,s)
s = video.add_image(file="/home/ubuntu/row.png",x=1,y=663,width=1280,height=57,s)
s = video.add_text(
      "some text.",font="/home/ubuntu/bankgothic.ttf",cycle=true,color=0x000000,size=15,y=663, s)
s = video.add_image(file="/home/ubuntu/tg.png",x=1,y=663,width=350,height=57,s)
s = video.add_text.ffmpeg(
     get_time,font="/home/ubuntu/bankgothic.ttf",size=23,speed=0,color=0x000000,x=218,y=684, s)
```
I have immediately  this catchup log and after a while it disconnects
```
2022/02/04 20:15:51 [clock.main:2] We must catchup 1.00 seconds!
2022/02/04 20:15:52 [clock.main:2] We must catchup 1.10 seconds!
2022/02/04 20:15:53 [clock.main:2] We must catchup 1.20 seconds!
2022/02/04 20:15:54 [clock.main:2] We must catchup 1.24 seconds!
2022/02/04 20:15:55 [clock.main:2] We must catchup 1.26 seconds!
2022/02/04 20:15:56 [clock.main:2] We must catchup 1.24 seconds!
```
In attachment complete log
[liquidsoap.log](https://github.com/savonet/liquidsoap/files/8005618/liquidsoap.log)

**Comment by kessenza** [comment]
Hi I did some more tests and it happens also with only add_image methods (without add_text).
It seems that it happens when two or more add_image calls are done on sources.
For instance this code reproduce the issue

settings.init.allow_root.set(true)
settings.frame.video.width.set(1280)
settings.frame.video.height.set(720)
#settings.log.file.path.set("/tmp/liquidsoap.log")
#settings.log.stdout.set(true)
#settings.harbor.verbose.set(true)
#settings.log.level.set(5)
#settings.frame.video.framerate.set(30)


s = playlist(reload_mode="watch",loop=false,mode="normal","/opt/video/test.pls")

s = video.add_image(file="/home/ubuntu/logo.png",x=1155,y=15,width=100,height=100,s)
s = video.add_image(file="/home/ubuntu/row.png",x=1,y=663,width=1280,height=57,s)
s = video.add_image(file="/home/ubuntu/row_red.png",x=1,y=610,width=1280,height=53,s)
s = video.add_image(file="/home/ubuntu/br.png",x=1,y=610,width=356,height=53,s)
s = video.add_image(file="/home/ubuntu/dx_giallo.png",x=1096,y=610,width=184,height=53,s)
s = video.add_image(file="/home/ubuntu/tg.png",x=1,y=663,width=350,height=57,s)

output.icecast(
 %ffmpeg(format="mpegts",
  %audio(codec="ac3",channel_coupling=0),
         %video(codec="libx264",profile="baseline",tune="zerolatency",
                     b="1800k", g=150, preset="veryfast")
        ),
fallible=true,
icy_metadata="false",
        host="localhost",
        port=8000,
        password="hackme",
        mount="/test",
s)

**Comment by toots** [comment]
@smimram Was this improved with the introduction on canvas?

**Comment by smimram** [comment]
It should, at least on small images...

**Comment by kessenza** [comment]
With new versions I never got the catch up message again. I think we can close the issue and reopen in case it happens again

**Comment by toots** [comment]
That's great thank you!
