### ISSUE TITLE
Remove string interpolation

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#2221]
This is outdated and should be replaced by string getters everywhere it is still in use.

**Comment by smimram** [comment]
Yes, nobody know about it / use it. Although, be careful, it's still in use in some scripts...

**Comment by smimram** [comment]
See #2220.

**Comment by smimram** [comment]
Note that `output.file` allows specifying the filename depending on current metadata, which is going to be difficult to reimplement with getters.

**Comment by martinkirch** [comment]
I don't understand the motivation behind this ? being able to write a path as `%Y-%m-%d/%Hh%M_%S.flac` is more simpler and elegant than writing a complete function as in https://github.com/savonet/liquidsoap/discussions/2220#discussioncomment-2125860

**Comment by toots** [comment]
I think that Sam brings up a good point here and @martinkirch is right to follow-up with this. What we need to remove, I believe, is the generic string interpolation: `s % hash` type. We should definitely keep the functionalities around filename in `output.file` but make it specific to this operator.

**Comment by toots** [comment]
This feature is still too useful to remove. Closing!
