### ISSUE TITLE
Output video using an external encoder

### ISSUE THREAD

**Issue by GeekBrony** [savonet/liquidsoap#223]
I'm attempting to run an automated video streamer (streaming to Icecast), selecting random videos according to a playlist, but the encoders that Liquidsoap provides are very intensive, taking up almost 90% of my dual-processor Xeon server, which slows it down a ton. Plus, there are constant pauses in the stream, forcing me to restart the stream.

The thing I'm suggesting is an alternative to `%external()` that supports video sources, providing access to external encoders like ffmpeg and x264 with parameters. I find that it would be very helpful for a lot of video streamers.

Thanks!

**Comment by smimram** [comment]
The problem is that `%external` is currently communicating with programs via the standard input / output. If you know some programs supporting that for video, we'd be glad to add support for those...

**Comment by smimram** [comment]
Actually, it seems that ffmpeg is supporting video in `rawvideo` format (frames in YUV or even RGB) so this should be doable...

@toots what do you think?

**Comment by smimram** [comment]
Some work was done in https://github.com/savonet/liquidsoap/pull/256 to support external encoders. Alternatively, you can [use clocks](http://liquidsoap.fm/doc-svn/clocks.html) to use multiple cores (see the end of the page).
