### ISSUE TITLE
Reference does not adopt the type of the variable that it references with strings

### ISSUE THREAD

**Issue by theotherjenkutler** [savonet/liquidsoap#2233]
**Describe the bug**
References to strings do not adopt the type string. 

**To Reproduce**

```
#!/home/jenkutler/.opam/4.10.0/bin/liquidsoap
settings.init.force_start.set(true) #this will allow LS to start w/o an active source
settings.server.telnet.set(true) #starts telnet server

set("log.file",false)
#set("log.file.path", "/home/jenkutler/ls_logs/measures.log")
set("log.stdout",true)
set("log.level",5)

def on_telconnect(m)
    amotherfuckingstring = ""
    i = ref(amotherfuckingstring)
    i := (m)
    log.debug(i)
end
server.register(usage= "mac <mac>",
                "mac", on_telconnect)
```

**Expected behavior**
That a user can connect to the telnet server and  type the mac command, enter a string and then liquidsoap would print that string to the log. (instead I get errors about how ref is type (_) but it wants a string. We all want a string. A string is all we have ever wanted.

**Version details**
 - OS: Ubuntu 20.04.3 LTS
 - Version 2.0.2

**Install method**
Opam

**Comment by smimram** [comment]
Two things:
1. in order to get the value of a reference you need to prefix it with `!` and thus replace `i` by `!i` in your script
2. the `on_teleconnect` function needs to return a string (which is printed on the telnet once the command succeeds).

Thus, the corrected version is:
```
```

**Comment by theotherjenkutler** [comment]
Thank you for the help! Do i still need the "!" symbol to use the reference in other ways? for example if I wanted the reference to set the mountpoint of a stream? Something like-
`output.icecast(%mp3(samplerate = 44100, internal_quality=1),
  host = "localhost", port = 8000,
  password = "measures", mount = !i,
  radio,
  fallible = true)`
