### ISSUE TITLE
list.add not defined?

### ISSUE THREAD

**Issue by Tasemu** [savonet/liquidsoap#224]
I'm trying to use the list.add() function however it throws an error saying the variable has not been previously defined. Has the function name changed or something?

**Comment by smimram** [comment]
This is strange because `list.add` is a builtin command, which has been there, unchanged, for a while. What is the output of `liquidsoap -h list.add` on your machine?

**Comment by smimram** [comment]
No input from @Tasemu, closing. Please reopen if the problem persists.
