### ISSUE TITLE
request queue.length() not working

### ISSUE THREAD

**Issue by hayden-t** [savonet/liquidsoap#2274]
**Describe the bug**
queue method `length()` only returns 0
also calling `queue.queue()` or `last_metadata()` (maybe others) in `on_track` callback results in

```
2022/03/06 00:22:10 [clock.main:2] Source xxx failed while streaming: (Sys_error "Mutex.lock: Resource deadlock avoided")!
```
(while queue.current() and others work)

**To Reproduce**
```
recorder_queue = request.queue()
test = request.create('/app/media/test.wav')
recorder_queue.add(test)
log.severe("#{recorder_queue.length()}")
log.severe("#{list.length(recorder_queue.queue())}")
```
```
2022/03/06 00:37:54 [lang:2] 0
2022/03/06 00:37:54 [lang:2] 1
```

**Version details**
 - OS: Debian 11
 - Version: Liquidsoap 2.0.3-1 (DOCKER)

**Install method**
DOCKER

**Comment by toots** [comment]
Thanks for this report. Will have a look very soon.

**Comment by toots** [comment]
Thanks for your report. The `length()` method and deadlock issues should be fixed in the `v2.0.4-preview` and `main` branch. Please note that, for `request.queue`, the `push` method should be used instead of `add`. In future releases, `add()` should be removed.

**Comment by hayden-t** [comment]
Thanks, will try this out some time when released main in docker

**Comment by toots** [comment]
Thanks! Please keep in mind that we do not advise the use of `main` in production yet unless you have the time to do the proper testing to make sure that it is stable enough for your use case.

**Comment by hayden-t** [comment]
Sorry, i just randomly picked main as keyword, meant stable release
