### ISSUE TITLE
How to make a dynamic playlist

### ISSUE THREAD

**Issue by fedwa-zarrok** [savonet/liquidsoap#2277]
@toots @smimram  Hi all, Am trying to create a dynamic playlist with an external bash script that output multiple paths to audio files that I wanna play on icecast. So I am using request.dynamic but it streams the first line only. Can anyone please help ASAP please !This is my code : 

```
# !/usr/bin/liquidsoap

set ("log.file.path","/home/admin/radio.log")

def my_request_function() = 
  
  result =
    list.hd(default="", get_process_lines("sh testScript.sh"))

  request.create(result)
end




m = request.dynamic(my_request_function)
m = audio_to_stereo(m)

radio = m


 clock.assign_new(id="/stream",[output.icecast(%vorbis(samplerate=44100, channels=2, quality=0.3),format="audio/ogg", fallible=true, host = "ip address", port = 8080 , password="XXX",  mount = "/test1",radio)])](url)
```

And here is my bash simple script : 

```
#!/bin/bash


now="$(date +'%Y-%m-%d')"
cd Playlist
cd Musique
cat $now*
```

Bash script output : 
```
/home/admin/1.mp3
/home/admin/2.mp3
```

**Comment by rrolla** [comment]
Firstly list.hd return the head (first element) of a list, or default if the list is empty. look here: https://www.liquidsoap.info/doc-2.0.3/reference.html#list.hd

**Comment by rrolla** [comment]
Duplicate: https://github.com/savonet/liquidsoap/discussions/2269
