### ISSUE TITLE
Inactive outputs started on source reset

### ISSUE THREAD

**Issue by icedream** [savonet/liquidsoap#2278]
**Describe the bug**
When setting up an Icecast output with `icecast.output(start=false, fallible=true, …)`, sources should stay offline until brought online by a call to `.start()` or via telnet. Liquidsoap however will decide to connect to the Icecast server anyways if its main clock happens to fall behind far enough (a minute of latency, visible in the log with message `[clock.main:2] Too much latency! Resetting active sources...`). It then sends no data whatsoever and seems to not disconnect until Liquidsoap is shut down.

This is a side effect of another already faulty condition that shouldn't occur and I haven't quite figured out yet, but handling this particular situation gracefully would be better.

**To Reproduce**
Set up any `output.icecast` and run Liquidsoap such that the clock will fall behind eventually (in my case I was deploying it on a NAS, it was unable to keep up for currently unknown reasons). This will trigger the source reset, making the Icecast output react and connect to the streaming server.

**Expected behavior**
Outputs that are stopped should not connect on source reset.

**Version details**
 - OS: Debian (Docker host)
 - Version `2.0.3`

**Install method**
Docker image `savonet/liquidsoap:v2.0.3`

**Comment by toots** [comment]
Thanks for this detailed report. I'll look at it and will fix it for the `2.0.4` release.
