### ISSUE TITLE
Invalid crossfade time (my bug) cascades into stream halting, 100% CPU

### ISSUE THREAD

**Issue by Warblefly** [savonet/liquidsoap#2287]
Thank you for reading this. 

A single playlist line including an invalid annotation `...liq_cross_duration="-0.010"...` triggers a continuous cascade of this:
```
2022/03/09 16:09:26 [ffmpeg.raw.encode.audio.consumer_0:2] Warning: there may be an infinite sequence of empty tracks!
2022/03/09 16:09:26 [ffmpeg.raw.encode.audio.consumer_0:2] Warning: there may be an infinite sequence of empty tracks!
```
...cuts the audio, and eats 100% CPU.

**Obviously, there should NEVER be a negative `liq_cross_duration`!** It's my end-of-track detector program that's gone bad, and I'm fixing it.

But should the consequence be an irretrievable failure? I suppose in `src/operators/cross.ml` around line 470 one could add a 'clamp' to ensure `override_duration` never goes negative but I'm unsure how to do this in OCaml.

Here's the playlist line that causes the problem. There doesn't seem to be anything wrong with the audio file itself, just the cross duration.

`annotate:liq_cue_in="0.000",liq_cross_duration="-0.010",duration="405.590",liq_amplify="-9.000dB":/home/john/src/radio/mez3/Money in the Desert-1299755992.6a64c973577c303dd98a424b19698d41.mka`

The script passes audio to FFmpeg for processing and it is in the wrapper where this error occurs:
```
def audio_process_multi_wrap(s) =
  a = ffmpeg.raw.encode.audio(%ffmpeg(%audio.raw), buffer(s))
  a = audio_process_multi(a)
  ffmpeg.raw.decode.audio(a)
end
```
Platform: Debian Linux 'testing'
Liquidsoap: 2.0.3-1
Installed via self-compilation. FFmpeg also self-compiled (and updated frequently) to include the FDKAAC codec.

**Comment by toots** [comment]
Thanks for the report. This should be fixed now and will come out with the `2.0.4` bugfix release.
