### ISSUE TITLE
Could not find the .cmi file for interface tools/rqueue.mli

### ISSUE THREAD

**Issue by batphil** [savonet/liquidsoap#229]
I just try a fresh new installation on ubuntu 14.04, and with git code i have this error when make running:

CAMLP4O tools/server.camlp4
CAMLP4O tools/harbor.camlp4
OCAMLDEP
File "io/alsa_io.ml", line 114, characters 27-29:
Error: Syntax error: ')' expected
File "io/alsa_io.ml", line 113, characters 31-32:
Error: This '(' might be unmatched
OCAMLOPT -c shutdown.ml
OCAMLOPT -c tools/stdlib.ml
OCAMLOPT -c tools/doc.ml
OCAMLOPT -c tools/utils.ml
OCAMLOPT -c tools/plug.ml
OCAMLOPT -c tools/dyntools.ml
OCAMLOPT -c tools/rqueue.ml
File "tools/rqueue.ml", line 1:
Error: Could not find the .cmi file for interface tools/rqueue.mli.
make[3]: *** [tools/rqueue.cmx] Erreur 2
make[3]: quittant le répertoire « /home/fred/liquidsoap/liquidsoap/src »
make[2]: *** [all-auto-ocaml-prog] Erreur 2
make[2]: quittant le répertoire « /home/fred/liquidsoap/liquidsoap/src »
make[1]: *** [all-subdirs] Erreur 2
make[1]: quittant le répertoire « /home/fred/liquidsoap/liquidsoap »
make: *** [all] Erreur 1
fred@fred-Aspire-5750G:~/liquidsoap$

**Comment by batphil** [comment]
seems that i'm not the only one to having it http://sourceforge.net/p/savonet/mailman/message/34112626/

**Comment by toots** [comment]
I think that this has been fixed in #227

**Comment by batphil** [comment]
but it's the last version from github, the fix is already in code that i have.

**Comment by toots** [comment]
Sorry I just tried with the latest code and I cannot reproduce the issue

**Comment by batphil** [comment]
after reading this tutorial http://dev.radiopiloten.de/dokuwiki/doku.php/liquidsoap:installation ; installation is OK. but already my problem to launch the GUI and the telnet error, in my previous report bug.

**Comment by Cysioland** [comment]
I can reproduce this on newest code

**Comment by ArvyRogerio** [comment]
Cannot compile on Fedora 28 (latest development version)

CAMLP4O tools/server.camlp4
OCAMLOPT -c shutdown.ml
findlib: [WARNING] Interface ogg.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
findlib: [WARNING] Interface ogg_demuxer.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
OCAMLOPT -c tools/stdlib.ml
findlib: [WARNING] Interface ogg.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
findlib: [WARNING] Interface ogg_demuxer.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
OCAMLOPT -c tools/doc.ml
findlib: [WARNING] Interface ogg.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
findlib: [WARNING] Interface ogg_demuxer.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
OCAMLOPT -c tools/utils.ml
findlib: [WARNING] Interface ogg.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
findlib: [WARNING] Interface ogg_demuxer.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
OCAMLOPT -c tools/plug.ml
findlib: [WARNING] Interface ogg.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
findlib: [WARNING] Interface ogg_demuxer.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
OCAMLOPT -c tools/rqueue.ml
findlib: [WARNING] Interface ogg.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
findlib: [WARNING] Interface ogg_demuxer.cmi occurs in several directories: /root/liquidsoap/liquidsoap/../ocaml-ogg/src, /root/.opam/4.05.0/lib/ogg
File "tools/rqueue.ml", line 1:
Error: Could not find the .cmi file for interface tools/rqueue.mli.
make[3]: *** [../Makefile.rules:193: tools/rqueue.cmx] Error 2
make[3]: Leaving directory '/root/liquidsoap/liquidsoap/src'
make[2]: *** [../Makefile.rules:67: all-auto-ocaml-prog] Error 2
make[2]: Leaving directory '/root/liquidsoap/liquidsoap/src'
make[1]: *** [Makefile.rules:27: all-subdirs] Error 2
make[1]: Leaving directory '/root/liquidsoap/liquidsoap'
make: *** [Makefile:11: all] Error 1

**Comment by toots** [comment]
This usually indicates a broken dependency. Would you mind sharing more of your compilation effort like output of ./configure and make. Also, have you tried installing via opam? This is the recommended way to install liquidsoap now, even with the latest code (via the pinning mechanism).
