### ISSUE TITLE
Any way to grab only index 1 to 10 of a list?

### ISSUE THREAD

**Issue by Tasemu** [savonet/liquidsoap#230]
Ive been looking through the docs and haven't found any way to do this yet. I am supplying an endpoint of json which lists previously played songs, however over the course of days, this list get massive. I need to know how to only print index 1 to 10 on the json. :)

**Comment by toots** [comment]
I think what you're looking for is `list.nth`: http://liquidsoap.fm/doc-svn/reference.html#list_nth
