### ISSUE TITLE
Turn off preload

### ISSUE THREAD

**Issue by andersmandersen** [savonet/liquidsoap#232]
Hi 

I have a problem, when I start a stream, it preload my first spot file. 
I have a logging on my spot files. So every time the spot playlist preload a song, it makes a wrong time entry in log file. 

I would like to get the exact play time for a spot file. Is it possible to turn off preload? Or lower the preload to 10 seconds before play time? 

My log is working this way: 

The stream calls php file that first log in a mysql database and then return mp3 file to stream.

**Comment by smimram** [comment]
Unfortunately, there is currently no way to disable preload (and probably there will be none in a near future). The rationale for this is that we need to get ready in advance in order to make sure that the file will be available, read its headers, and not have to handle a failure at the last second...

**Comment by vrtisworks** [comment]
Could you do the logging in on_meta?  I remember reading that on_meta is in the main thread, so you don't want to do a lot.  I don't know of an http request is 'a lot' or not...

But I would think that on_meta would give you a better time for when it is actually played.

**Comment by dbaelde** [comment]
I agree with @vrtisworks : load in advance and log the play time using on_meta, this is the way to go. I believe it solves the issue; please feel free to reopen the ticket otherwise.

**Comment by dbaelde** [comment]
I also realize now that I should add to the answer by @smimram that, while preload is a good and encouraged thing, it is possible to disable it, typically by setting the preload length to 0.

**Comment by smimram** [comment]
Didn't know that! Is it somewhere in the doc?...

**Comment by dbaelde** [comment]
Yes it's here:
https://github.com/savonet/liquidsoap/blob/master/doc/content/request_sources.txt

BTW google does not point to liquidsoap.fm for our doc anymore!

On Tue, Aug 25, 2015 at 2:23 PM, Samuel Mimram <notifications@github.com>
wrote:

> Didn't know that! Is it somewhere in the doc?...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/savonet/liquidsoap/issues/232#issuecomment-134568836>.
>



-- 
David

**Comment by vrtisworks** [comment]
It doesn't say specifically that 0 turns it off, but it does say 
'below', so depending on how the condition is checked (< or <=).

Nick
