### ISSUE TITLE
on_connect/on_disconnect for input.http

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#234]
ditto

**Comment by S54B32** [comment]
I'm trying to write a function for on_connect and on_disconnect for input.http. I have it working, BUT it seems to run the function twice whenever I get a connect/disconnect event. My function is:
# Function On Main Connect
def main_start(start) =
	system("echo $(date) " ^ name ^ " main_input started! >> " ^ connection.log)
	log(name ^ "main_input started!")
end

Any ideas? Thank you

**Comment by S54B32** [comment]
Toots were you able to replicate this? Have you found a remedy?
Thanks

**Comment by smimram** [comment]
As a temporary fix, you can prevent the function from running twice using a reference. Something like:
```
already = ref false

def main_start(start) =
  if not !already then
    already := true
    system("echo $(date) " ^ name ^ " main_input started! >> " ^ connection.log)
    log(name ^ "main_input started!")
  end
end
```

**Comment by toots** [comment]
Quick glance at the code didn't seem to show any obvious cause for this issue. Could you describe us in more details what you are trying to do?

**Comment by dbaelde** [comment]
While we're looking at this I'm noticing typos in the on_disconnect doc: "excecute" should be "execute" and there should be a dot at the end of the doc. I would fix it right now but there's also a strange wording for on_connect and I don't know how to fix it: "Function to execute when a source is connected" is strange because it seems to talk about liquidsoap sources, whereas as far as I understand on_connect is about connecting to an HTTP stream.

**Comment by dbaelde** [comment]
I tried to reproduce the issue with a minimal setup but did not succeed. I ran
```
output.icecast(%vorbis,mount="toto.ogg",mksafe(playlist("~/media/audio")))
```
to create an HTTP stream and then ran
```
output.dummy(fallible=true,input.http("http://localhost:8000/toto.ogg",on_connect=fun(_)->log("XXXXXXXXXXXXXXXXX")))
```
to connect to it, but I saw only one line of XXX... in my logs.

**Comment by dbaelde** [comment]
By the way, what was the initial purpose of this issue? I thought it was a feature request, but we already have the feature. Now it has become a bug report... we should perhaps update the title.

**Comment by toots** [comment]
You right on the initial intent for this ticket. I'll be closing it for now until we have more info on how to reproduce the issue.

**Comment by S54B32** [comment]
Hi dbaelde and toots, I didn't realise you guys had responded! Thanks for the replies.

To clarify, this was a bug report - my code was producing some strange results. Basically, these two functions are run when a HTTP harbour is connected/disconnected. My functions are doing the following when the HTTP harbour disconnects/connects:
Write a line to a log file
Write a 1 or 0 to a second log file
Write a log entry in the liquidsoap log

My code is as follows:

# Function On Main Connect
def main_start(start) =
	system("echo " ^ date.cmd ^ " " ^ name ^ " main_input started! >> " ^ connection.log)
	system("echo [1] > " ^ main.input.status)
	log(name ^ " main_input started!")
end

# Function On Main Disconnect
def main_stop( )=
	system("echo " ^ date.cmd ^ " " ^ name ^ " main_input stopped! >> " ^ connection.log)
	system("echo [0] > " ^ main.input.status)
	log(name ^ " main_input stopped!")
end


My main_start function works as expected. The issue I have is that the disconnect function is run twice and writes two log entries to the connection.log and main.input.status files that I have defined in my script.

Am I missing something in my code?

Thanks again :-)

**Comment by S54B32** [comment]
I have tested the workaround smimram and have found some odd results. The workaround does work but only for the first attempt.

Here is what happens with the harbour and the log result when I start the liq.
Connect to harbour - main_input started!
Disconnect from harbour - main_input stopped!
Connect to harbour - main_input started!
Disconnect - no log entry
Connect to harbour - main_input started!
Disconnect - no log entry
Connect to harbour - main_input started!

and so on. The workaround only works for the first attempt.

Any other ideas are greatly appreciated. Thanks

**Comment by smimram** [comment]
A simple modification of the script will allow for the function to be called once every two rounds:
```
already = ref false

def main_start(start) =
  if not !already then
    already := true
    system("echo $(date) " ^ name ^ " main_input started! >> " ^ connection.log)
    log(name ^ "main_input started!")
  else
    already := false
  end
end
```

**Comment by S54B32** [comment]
Thank you very much for this. Supposed I have four functions, one for when the main harbour starts and stops. And one for when a backup harbour starts and stops. Would I need to add 4 different
 already = ref false 
to the code? Or would just one suffice?

Thanks very much

**Comment by S54B32** [comment]
The fix is working nicely - I have a main harbour and backup habour, each with a on_connect and on_disconnect function. Is there a way to define two functions, one for stop and start and take the value of which harbour has dropped instead of defining a function for each harbour?

**Comment by S54B32** [comment]
I am still having issues with the fix - I have had to define main_already and backup_already for use with the main and backup harbour. Even still, I get some issues where sometimes the stop function isn't run at all. Do you have any ideas?

Thanks

**Comment by S54B32** [comment]
I fixed my code!

All I had to do was remove the space in:
def backup_stop( ) =

so it becomes:
def backup_stop() =


I'm not sure if this is expected behaviour with Liquidsoap or a potential issue...

Thanks for your advice and creating a fantastic utility!

**Comment by toots** [comment]
@S54B32 I think we'd need to see more context from your script to be able to assess the issue further. So far, I'll mark it as not reproducible..
