### ISSUE TITLE
Is it possible to change the harbor server port

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#2359]
**Is your feature request related to a problem? Please describe.**

Related to #2358 ,

I can workaroud this by spawning new liq instances (i think) , but would like to run separate harbor servers on each. I can't find a way of setting the harbor port to bind to ( interactive port would be good to ). If I'm not reading the right part of the doocs i appologies.

**Describe the solution you'd like**
Way of setting the harbor and interactive port numbers.

**Comment by cdgraff** [comment]
I'm not sure if that what you need but input.harbor support PORT params.

`live = input.harbor("test-harbor",port=8080,password="xxx")`

https://www.liquidsoap.info/doc-dev/harbor.html

**Comment by Russsgithub** [comment]
@cdgraff 

I meant the server rather than the input, but thank you anyway.

But i was not being very observant as they are here

https://www.liquidsoap.info/doc-dev/reference.html#interactive.harbor

https://www.liquidsoap.info/doc-dev/harbor_http.html

Thanks for making me think about it better.
