### ISSUE TITLE
Can't start telnet port

### ISSUE THREAD

**Issue by cesarlwhoriginal** [savonet/liquidsoap#2367]
Hi, I'm having problem to start the telnet port, I don't understand why not working and any help is appreciated.

Here is my start code:

```
settings.log.file.path.set("/home/test.log")
settings.init.allow_root.set(true)
settings.server.telnet.set(true)
settings.server.telnet.port.set(8080)
settings.log.level.set(3)
settings.log.stdout.set(true)
settings.harbor.max_connections.set(1)
settings.tag.encodings.set(["UTF-8","ISO-8859-1"])
settings.encoder.metadata.export.set(["artist","title","album","song"])
settings.decoder.file_extensions.taglib.set(["mp3"])
settings.init.daemon.set(false)
settings.scheduler.fast_queues.set(0)
settings.request.grace_time.set(3600.)
settings.harbor.bind_addrs.set(["0.0.0.0"])

streaming = playlist(reload_mode="watch", loop=true, mode=playlist_modo, "/home/playlist.pls")

output.shoutcast(%fdkaac(bitrate=128, samplerate=44100, channels=2, aot="mpeg4_aac_lc"),name="Demo",url="https://google.com", genre="Rock", public=true, icy_reset=true, host=127.0.0.1,port = 8000,password = "123", streaming)
```
Port 8080 is not in use. The liquidsoap is running but only the telnet can't run.

**Comment by toots** [comment]
Hi Cesar. Thanks for reporting. There's an issue with the way the telnet server is started with the latest `2.0.4` point release. I'll have a fix out very shortly. I'm also taking this opportunity to rethink our release workflow so we can get more point releases out for everyone to use as soon as possible. Thanks for your patience!

**Comment by cesarlwhoriginal** [comment]
Thank you for your answer, What version is telnet working on? On 2.0.2 is working?

**Comment by vitoyucepi** [comment]
@cesarlwhoriginal just tested different versions.
Telnet worked fine in:
- `2.0.3`;
- `2.0.4` initial release, currently unavailable;
- `2.0.4` the first rebuild, currently unavailable.

It was broken in `2.0.4` the second rebuild, current version.
You can just wait for the third rebuild, which will be available shortly(I think).

It's also possible to get previous version release artifact from ci pipeline, like [this](https://github.com/savonet/liquidsoap/actions/runs/2239916722). Concretely this linked pipeline has release artifacts similar to `2.0.4` the first rebuild, except this is a git version.

**Comment by toots** [comment]
Yeah new stable build is queued here: https://github.com/savonet/liquidsoap/actions/runs/2254253819

You are correct about the CI. I'm looking at a new release workflow that would leverage this and provide a rolling release that people can use to grab intermediary stable release.

Essentially, with the user base growing and the large set of features we provide, it's becoming impossible to provide a single stable release that won't need an update every couple of weeks. 

But, while might not be able to provide a single release that would work for all people, we can and should definitely provide an intermediary release that incorporates all the ongoing fixes and has the same expected stability as the latest versioned release.

This way, is someone reports a bug on a latest release, we can fix it, push it to the rolling release and point them to this as a viable alternative to the versioned release they reported from.

Additionally, we should start incorporating breaking changes earlier. The current `main` branch has way too many useful things that are currently being held up for a hypothetical major release.

Still thinking about all this. Meanwhile, the release assets are updated now. Gonna push a new `opam` package as well. Hopefully, this is the last time we do this before the new release workflow.

**Comment by vitoyucepi** [comment]
@toots I think that rebuilding already tagged versions is bad practice.
In my vision there should be a branch of `2.0` with bugfixes, periodically tagged as new patch versions: `2.0.0`, `2.0.1`, `2.0.2` and so on. There should be no new features for this branch.
All new features should be packed into another branch, generally `main`. And periodically cut into new branches like `2.1`, `2.2`.
Basically I'd prefer semver.

Nevertheless, as a package maintainer, I personally don't like when release artifacts for existing release change. If this happen, I will not receive any notifications, until some other package will be updated and build pipeline will fail.

**Comment by toots** [comment]
Yes, this is the plan. We're gonna spin up a repository dedicated to release assets and promise to never change the assets there and push a new one for each release/point release.

Also, we try to follow semver whenver possible. Just for us, we look at: <major changes>.<breaking changes>.<potentially backward compatible changes>

I'll document the release process/versioning better as part of this ongoing work.
