### ISSUE TITLE
Error -1: Exception raised: Lang_encoders.Error(_)

### ISSUE THREAD

**Issue by q9f** [savonet/liquidsoap#2375]
**Describe the bug**
Using a variable to configure a codec does result in the following error:

```
Unknown position:

Error -1: Exception raised: Lang_encoders.Error(_)
Raised at Lang_vorbis.make_cbr.(fun) in file "lang_encoders/lang_vorbis.ml", line 53, characters 18-41
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Lang_vorbis.make_cbr in file "lang_encoders/lang_vorbis.ml", line 39, characters 4-816
Called from Parser._menhir_goto_app_opt in file "lang/parser.mly", line 410, characters 23-50
Called from Runtime.from_lexbuf.(fun) in file "lang/runtime.ml", line 245, characters 19-64
Called from Runtime.report in file "lang/runtime.ml", line 227, characters 12-23
```

**To Reproduce**
The following script fails:

```
#!/usr/bin/liquidsoap

foo = 128

ogg = output.icecast(
  %vorbis.cbr(
    bitrate = foo
  )
)
```

However, setting `bitrate = 128` directly works.

**Expected behavior**
You should be able to use variables to define configuration options of the output codecs.

**Version details**
 - OS: Archlinux
 - Version: 2.0.4

**Install method**
via `opam`

**Comment by toots** [comment]
Hi! Thanks for reporting. This is actually fixed in `main` and we're putting in some work to release it soon and also have rolling releases accessible for easy early testing/upgrade. Keep your eyes open, it's coming soon!
