### ISSUE TITLE
creating a file with a daily broadcast

### ISSUE THREAD

**Issue by nesale** [savonet/liquidsoap#238]
Make playlist a daily. Can be generated (sincerity) this playlist to a file, right? Not expecting?

**Comment by TrurlMcByte** [comment]
Just generate it daily and use like
```
... = playlist(mode="normal",reload=86400,"mydailygeneratedplaylist.m3u")
```

**Comment by smimram** [comment]
The solution proposed by @TrurlMcByte is a decent answer. Please reopen if you have a more specific case.
