### ISSUE TITLE
Error reading a file

### ISSUE THREAD

**Issue by 918483** [savonet/liquidsoap#2381]
How to avoid this error and the source turn off automatically in 2.0.4
```
2022/05/05 02:11:06 [cross_0:3] Analysis: -59.021995dB / -14.774403dB (1.96s / 1.96s)
2022/05/05 02:11:06 [crossfade_0:3] Simple transition: crossed, fade-in, fade-out.
2022/05/05 02:11:11 [decoder:2] Decoding "/home/streaming/horacerta/7062/hora_certa.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/05/05 02:11:12 [clock.main:2] Source Radio_Melhor_Mix failed while streaming: Avutil.Error(Invalid argument)!
2022/05/05 02:11:12 [Radio_Melhor_Mix:3] Closing connection...
2022/05/05 02:11:12 [main:3] Shutdown started!
2022/05/05 02:11:12 [main:3] Waiting for main threads to terminate...
2022/05/05 02:11:13 [harbor:3] Removing mountpoint '/' on port 5118
2022/05/05 02:11:13 [harbor:3] Nothing more on port 5118: closing sockets.
2022/05/05 02:11:13 [clock.main:3] Streaming loop stopped.
2022/05/05 02:11:13 [main:3] Main threads terminated.
2022/05/05 02:11:13 [threads:3] Shutting down scheduler...
2022/05/05 02:11:13 [threads:3] Scheduler shut down.
2022/05/05 02:11:13 [server:3] Closing socket.
2022/05/05 02:11:13 [main:3] Cleaning downloaded files...
2022/05/05 02:11:13 [main:3] Freeing memory...
```

**Comment by 918483** [comment]
@toots ???

**Comment by toots** [comment]
Hi,

Could you share more of your script? And also add this to the beginning of it:
```ruby
log.level.set(4)
```
Thanks!

**Comment by 918483** [comment]
I'm reading a .mp3 file that updates every minute in a server directory that will be used to speak the right time and it is delaying and when it doesn't delay it reads along with the moment it is generating the file and gives this error that I said above I'm sweating the following code below


clock = amplify(override="liq_amplify", 1., single("/home/streaming/horacerta/7062/hora_certa.mp3"))
clock = cue_cut(id="cue_horacerta", clock)
toca_hora = delay(600.,clock)
toca_hora = blank.skip(toca_hora)
radio = fallback(id="horacerta", [toca_hora,radio])

**Comment by 918483** [comment]
[mp3float @ 0x7f90b402df80] Could not update timestamps for skipped samples.
2022/05/07 00:44:35 [cue_horacerta:4] Cue points : none / none
2022/05/07 00:44:35 [cue_horacerta:3] Cueing in...
[mp3float @ 0x7f90b402df80] Header missing
2022/05/07 00:44:35 [cross_0:3] Analysis: -47.532617dB / -15.062846dB (1.96s / 1.96s)
Hora Certa - Automatica
2022/05/07 00:44:35 [crossfade_0:4] Before: ("tcom", "FELIPE FERRAZ ")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("album", "FELIPE FERRAZ ")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("composer", "FELIPE FERRAZ ")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("on_air_timestamp", "1651894896.00")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("kind", "{audio=pcm(stereo),video=none,midi=none}")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("artist", "FELIPE FERRAZ ")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("decoder", "FFMPEG")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("title", " AMOR COM DESAPEGO")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("filename", "/home/streaming/musicas/Sertanejo - 1/FELIPE FERRAZ - AMOR COM DESAPEGO.mp3")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("temporary", "false")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("source", "playlist_inicio")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("tcop", "Painel Streaming")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("tsse", "Lavf52.54.0")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("initial_uri", "/home/streaming/musicas/Sertanejo - 1/FELIPE FERRAZ - AMOR COM DESAPEGO.mp3")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("copyright", "Painel Streaming")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("encoder", "Lavf52.54.0")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("status", "playing")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("on_air", "2022/05/07 00:41:36")
2022/05/07 00:44:35 [crossfade_0:4] Before: ("rid", "11")
2022/05/07 00:44:35 [crossfade_0:4] After : ("tcon", "Blues")
2022/05/07 00:44:35 [crossfade_0:4] After : ("album", "                              ")
2022/05/07 00:44:35 [crossfade_0:4] After : ("date", "2020")
2022/05/07 00:44:35 [crossfade_0:4] After : ("on_air_timestamp", "1651895075.00")
2022/05/07 00:44:35 [crossfade_0:4] After : ("kind", "{audio=pcm(stereo),video=none,midi=none}")
2022/05/07 00:44:35 [crossfade_0:4] After : ("year", "2020")
2022/05/07 00:44:35 [crossfade_0:4] After : ("artist", "Hora Certa")
2022/05/07 00:44:35 [crossfade_0:4] After : ("tdrc", "2020")
2022/05/07 00:44:35 [crossfade_0:4] After : ("decoder", "FFMPEG")
2022/05/07 00:44:35 [crossfade_0:4] After : ("title", "Automatica")
2022/05/07 00:44:35 [crossfade_0:4] After : ("filename", "/home/streaming/horacerta/7062/hora_certa.mp3")
2022/05/07 00:44:35 [crossfade_0:4] After : ("temporary", "false")
2022/05/07 00:44:35 [crossfade_0:4] After : ("tsse", "Lavf59.16.100")
2022/05/07 00:44:35 [crossfade_0:4] After : ("tracknumber", "1")
2022/05/07 00:44:35 [crossfade_0:4] After : ("initial_uri", "/home/streaming/horacerta/7062/hora_certa.mp3")
2022/05/07 00:44:35 [crossfade_0:4] After : ("encoder", "Lavf59.16.100")
2022/05/07 00:44:35 [crossfade_0:4] After : ("status", "playing")
2022/05/07 00:44:35 [crossfade_0:4] After : ("on_air", "2022/05/07 00:44:35")
2022/05/07 00:44:35 [crossfade_0:4] After : ("rid", "1")
2022/05/07 00:44:35 [crossfade_0:4] After : ("comment", "                            ")
2022/05/07 00:44:35 [crossfade_0:4] After : ("genre", "Blues")
2022/05/07 00:44:35 [crossfade_0:3] Simple transition: crossed, fade-in, fade-out.
2022/05/07 00:44:35 [source:4] Source add_10 gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [add_10:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source fade.in gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [fade.in:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source fade.in gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [fade.in:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source cross_0_after gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [cross_0_after:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source buffer_17 gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [buffer_17:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source fade.out gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [fade.out:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source fade.out gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [fade.out:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source on_end_8 gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [on_end_8:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source cross_0_before gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [cross_0_before:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [source:4] Source buffer_16 gets up with content kind: {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [buffer_16:4] Content type is {audio=pcm(stereo),video=none,midi=none}.
2022/05/07 00:44:35 [cross_0_after:4] Fading in (type: sin, duration: 1.5s).
2022/05/07 00:44:36 [cross_0_before:4] Fading out with 1.s remaining.
2022/05/07 00:44:37 [buffer_17:4] Buffer emptied, buffering needed.
2022/05/07 00:44:37 [buffer_16:4] Buffer emptied, buffering needed.
2022/05/07 00:44:37 [source:4] Source add_10 gets down.
2022/05/07 00:44:37 [source:4] Source fade.in gets down.
2022/05/07 00:44:37 [source:4] Source fade.in gets down.
2022/05/07 00:44:37 [source:4] Source cross_0_after gets down.
2022/05/07 00:44:37 [source:4] Source buffer_17 gets down.
2022/05/07 00:44:37 [source:4] Source fade.out gets down.
2022/05/07 00:44:37 [source:4] Source fade.out gets down.
2022/05/07 00:44:37 [source:4] Source on_end_8 gets down.
2022/05/07 00:44:37 [source:4] Source cross_0_before gets down.
2022/05/07 00:44:37 [source:4] Source buffer_16 gets down.
2022/05/07 00:44:37 [cross_0:4] Buffering end of track...
2022/05/07 00:44:37 [cross_0:4] More buffering will be needed.
2022/05/07 00:44:37 [decoder:4] Decoding "/home/streaming/horacerta/7062/hora_certa.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/05/07 00:44:37 [decoder:4] Raised at Ffmpeg_decoder.mk_decoder.(fun).f in file "decoder/ffmpeg_decoder.ml", line 691, characters 12-29
2022/05/07 00:44:37 [decoder:4] Called from Decoder.mk_decoder.fill in file "decoder/decoder.ml", line 500, characters 10-31
2022/05/07 00:44:37 [decoder:4]
2022/05/07 00:44:37 [single_0:4] Finished with "/home/streaming/horacerta/7062/hora_certa.mp3".
2022/05/07 00:44:37 [single_0:3] Prepared "/home/streaming/horacerta/7062/hora_certa.mp3" (RID 1).

**Comment by toots** [comment]
Ok thanks. Please post again when this error happens again:
```
2022/05/05 02:11:12 [clock.main:2] Source Radio_Melhor_Mix failed while streaming: Avutil.Error(Invalid argument)!
```
The whole stacktrace should tell us exactly what we need.

**Comment by 918483** [comment]
[autodj-7062.log](https://github.com/savonet/liquidsoap/files/8645724/autodj-7062.log)

**Comment by 918483** [comment]
@toots hello, I left above one of the logs that occurs and automatically shuts down the system and I'm leaving 1 more in the sequence

[autodj-7062.log](https://github.com/savonet/liquidsoap/files/8653747/autodj-7062.log)

**Comment by 918483** [comment]
2022/05/08 06:11:15 [decoder:2] Decoding "/home/streaming/musicas/Sertanejo - 1/DIEGO E ARNALDO - RELOGIO PARADO AO VIVO.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/05/08 06:11:15 [switch_0:3] Switch to Intercalado with forgetful transition.
2022/05/08 06:11:15 [clock.main:2] Source Radio_Melhor_Mix failed while streaming: Avutil.Error(Invalid argument)!
2022/05/08 06:11:15 [Radio_Melhor_Mix:3] Closing connection...
2022/05/08 06:11:16 [main:3] Shutdown started!
2022/05/08 06:11:16 [main:3] Waiting for main threads to terminate...
2022/05/08 06:11:16 [harbor:3] Removing mountpoint '/' on port 5118
2022/05/08 06:11:16 [harbor:3] Nothing more on port 5118: closing sockets.
2022/05/08 06:11:16 [clock.main:3] Streaming loop stopped.
2022/05/08 06:11:16 [main:3] Main threads terminated.
2022/05/08 06:11:16 [threads:3] Shutting down scheduler...
2022/05/08 06:11:16 [threads:3] Scheduler shut down.
2022/05/08 06:11:16 [server:3] Closing socket.
2022/05/08 06:11:16 [main:3] Cleaning downloaded files...
2022/05/08 06:11:16 [main:3] Freeing memory...
2022/05/08 06:11:17 >>> LOG END

**Comment by 918483** [comment]
@toots ??

**Comment by 918483** [comment]
@toots Could help?

**Comment by 918483** [comment]
@smimram  Could help?

**Comment by toots** [comment]
Hi @918483 Unfortunately, there still isn't enough info in those logs. Please add the following to increase verbosity:
```
log.level.set(4)
```
And post again when you see the issue. Thanks!

**Comment by 918483** [comment]
[autodj-7062.log](https://github.com/savonet/liquidsoap/files/8740521/autodj-7062.log)

@toots  Sorry for the delay but here is the log with the information at the time of the error

**Comment by 918483** [comment]
@toots @smimram Could help?

**Comment by toots** [comment]
Thanks for providing the logs. The issue is fixed in the rolling release and `main` branch and will come out very soon with the `2.0.5` release!
