### ISSUE TITLE
Can I use http.get to select a source?

### ISSUE THREAD

**Issue by chrisc97** [savonet/liquidsoap#239]
*Apologies if a GitHub issue isn't the right place to post this*

**Is there any way I can use http.get to affect what source is currently selected?**

I have two ShoutCast servers set up, one for input and one for output. I have Liquidsoap configured to take audio from the input server and send it to output, or to fall back onto a prerecorded track when there's no input being sent.

What I'd like to be able to do is, when the input stream stops/goes down, have Liquidsoap check with an API endpoint whether the show is still supposed to be live. The API is already set up so that it returns 200 OK when the show is supposed to be on, but 404s when the show is supposed to be off-air. Then, I'd like Liquidsoap to play an 'emergency' track (sorry for the technical difficulties, etc.) if the show is supposed to be on air (API 200), or the standard 'off air' track if not (API 404).

I don't want to just fall back to the emergency track all the time because the live show is only a few hours every week or so (i.e. there's no 24/7 live programming), but I want the emergency track to play as the fallback during the show if it goes off-air.

Anyone have any ideas? Thanks in advance :)

**Comment by smimram** [comment]
Yes it can easily be done. The following function returns `true` whenever the answer from google is 200:
```
def status() =
  g = http.get("http://www.google.fr/")
  n = snd(fst(fst(fst(g))))
  print("Status is #{n}")
  n == 200
end
```
You can then easily use this function with a `swich` operator to select a source depending on the result.
