### ISSUE TITLE
Telnet connecting but having Connection timed out.. and not run commands

### ISSUE THREAD

**Issue by cesarlwhoriginal** [savonet/liquidsoap#2394]
Hi everyone.

**Describe the bug**

Only on this server, when I connect to telnet, the connection done successfully but the commands do not execute, it keeps thinking until get times out.

**To Reproduce**

`#telnet localhost 1001`

**The error**

```
# telnet -4 localhost 1001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
help [it takes a while]
Connection closed by foreign host.
```
**Expected behavior**

That run the telnet commands, it's only happening on this server, I tested it on another server with the same configuration and it's working normally

**Version details**

- OS: CentOS 7
- Version 2.0.4-1

**Install method**
With opam

**Comment by cesarlwhoriginal** [comment]
I tested it with netcat too and it didn't work, I had to use curl and it worked:

```
# (echo Web_Radio.remaining;echo quit;echo quit) | curl telnet://localhost:1001
END
16.92
END
Bye!
```
but the ideal would be to use telnet itself, why does this problem occur?

Thanks.

**Comment by toots** [comment]
Is this the same as https://github.com/savonet/liquidsoap/discussions/2399 ? Looks like it is, please reopen if needed.
