### ISSUE TITLE
Precedence of ! over [_]

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#24]
Apparently the precedence of ! over [_] is wrong.

From the ML:

On Fri, Feb 8, 2013 at 4:42 AM, Alexander wrote:

> for !CONFIG["STATION_ID"] call, it gives error:
> 
> > At line 36, char 14:
> >   this value has type
> >     ref(_) (infered at line 32, char 10-15)
> >   but it should be a subtype of
> >     [_]

We worked hard to make errors as understandable as possible, but
there's a point where you have to learn to use those messages. I'll
rephrase it for you: something is a ref but it should have been a
list. What could have caused this error? Well, CONFIG is a ref and we
are trying to lookup an associative list, it must be that liquidsoap
read !(CONFIG["ID"]) instead of (!CONFIG)["ID"]. Solution: make the
parentheses explicit.

In that case I don't think the error could have been much better.
However, it looks like the precedencies between ! and _[_] are not the
most natural ones, I should perhaps go change this. Any opinion on
this?

**Comment by toots** [comment]
I actually disagree on this. I immediately read `!config["label"]` as: `!(config["label"])`
