### ISSUE TITLE
Liquidsoap doesn't reconize file protocol when loading http playlists

### ISSUE THREAD

**Issue by giflw** [savonet/liquidsoap#241]
Liquidsoap 1.1.1 on Ubuntu 14.04.2 LTS loads an http playlist and suppose that links are relative, ignoring file protocol prepended on urls. I tried M3U, PLS and XSPF formats.

Playlist (m3u):
```
file:///home/myuser/music/file.mp3
```

Script:
```
set("log.level", 5)
set("log.stdout", true)
def apply_metadata(m) =
    print(m)
end
s = playlist("http://localhost/playlist.php/playlist.m3u")
s = on_metadata(apply_metadata,s)
out(s)
```

**Comment by smimram** [comment]
I don't really understand your problem. It is working as expected here. With a playlist containing
```
file:///tmp/test.wav
```
the `apply_metadata` prints
```
[("kind","{audio=2;video=0;midi=0}"), ("decoder","WAV"), ("filename","/tmp/test.wav"), ("temporary","false"), ("source","playlist-file(dot)m3u"), ("initial_uri","file:///tmp/test.wav"), ("status","playing"), ("on_air","2015/08/06 19:04:43"), ("rid","1")]
```
where the `initial_uri` is correct (and I can hear the file). What is the problem exactly?

**Comment by thewilli** [comment]
@giflw I had the same problem, it worked after I manually added the mime type as follows:

```
mymusic = playlist(mime_type="application/x-mpegURL","http://localhost:8080/playlist.pls")
```

**Comment by giflw** [comment]
Thanks for the answer.

It's working perfectly!
