### ISSUE TITLE
process.run memory leak?

### ISSUE THREAD

**Issue by Calypso971** [savonet/liquidsoap#2424]
Since the transition to v2 I experience a gradual increasing use of memory by liquidsoap processes as they run (example: starting with 4.4% of use, and after one month it's 35%). After the recent improvements in de v2 series to address memory/CPU leaks, I was hoping it would solve mine too, but it didn't. After installing v2.0.5 this week, I decided to dive into this to see where it was coming from.

After some trying I came to the conclusion it appears to be using process.run; my script without process.run didn't use more memory between starting up (and waiting 10 minutes) and one day later, while the same script with process.run experienced an increased memory use. 

So I decided to create a simple script and see how that performs:

```
set("log.file.path", "/var/log/liquidsoap/test.log")
set("log.level",4)

def f() =
  print("Running test program")
  p = process.run(timeout=2., "sleep 1")
  print("Program status: #{p.status} (#{p.status.code})")
end

thread.run(every=5.,f)

output.dummy(blank())
```

On my 8GByte machine, it used 2.3% of memory after starting. 
After 5 hours, it used 2.8% of memory. When trying the same program without the process.run line, memory consumption doesn't increase.

As said, tested with liquidsoap 2.0.5 on Ubuntu 20.04 (up-to-date), 4CPU's, 8GByte memory, but I experience it since using v2 (I started with v2.0.1)

So my suspicion is that there is a memory leak in process.run. The logfile states that the process is closing correctly:

```
2022/05/28 19:45:19 [stdout:3] Running test program
2022/05/28 19:45:19 [process:4] Closing process's stdin
2022/05/28 19:45:20 [process:4] Process exited with code 0
2022/05/28 19:45:20 [stdout:3] Program status: exit (0)
```

**Comment by smimram** [comment]
I can clearly reproduce (and faster) with the following slight variant:
```
def f() =
  print("Running test program")
  p = process.run(timeout=2., "exit 42")
  print("Program status: #{p.status} (#{p.status.code})")
end

thread.run(every=.1,f)

output.dummy(blank())
```
If I set `timeout` to a negative value, it seems that there is no leak, which means that it should be related to the asynchronous launch of the task. So, I'd look on the side of the scheduler, ie duppy...

**Comment by toots** [comment]
I can confirm the issue & am investigating. Thanks for pointing this out @smimram this is really useful.

**Comment by toots** [comment]
I _think_ that I was able to track it down to an issue with the OCaml gc when running thread: https://github.com/ocaml/ocaml/issues/11289

With the added changes (a manual run of the GC after closing the process), the memory seems to be under control or at least growing at a much slower speed.

There might still be other places where we could optimize memory usage but this one was clearly an issue that should hopefully be fixed now.
