### ISSUE TITLE
Mux kills track information

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#244]
From the ML, confirmed by @dbaelde. Muxing functions should be updated.

**Comment by dbaelde** [comment]
I don't remember talking about this on the mailing list, but okay :) But we shouldn't block the release for this one: I don't think there is an easy and clean way to do a track preserving mux. In short, here is why: when we ask one source to get data it gives as much as possible, stopping only if it ends its track or when the frame is full; if the second muxed source stops earlier than the first one, we cannot "put back" the extra data from the first source. Remaining time information is not solid enough to be used here, and dropped the extra data is ugly. The only solution I see is a finer source protocol, but that not for liquidsoap 1.x.

**Comment by smimram** [comment]
I actually fixed this recently, see #795.
