### ISSUE TITLE
Last fm submission failed

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#2452]
I am running version 2.0.4 installed on Debian Buster via opam. I am noticing that some of my stream's submissions to last fm fail occasionally but I note that the time entry of the log is not in sync with the rest of the log and that this occurs multiple times throughout the log (see attached screen shot of the log).
![Screen Shot 2022-06-13 at 20 53 40](https://user-images.githubusercontent.com/46059094/173340909-20d4b9ba-5c42-41a0-aaf9-db7d28f016ef.png)

The section of my script that I am using for last fm submissions is below. 

```
#LAST.FM SCROBBLING#
def lastfm.submit(~user,~password,~source="broadcast",~length=false,m) =
audioscrobbler.submit(user=user,password=password,
source=source,length=length,
host="post.audioscrobbler.com",port=80,m)
end

radio.on_metadata(lastfm.submit(user="****",password="********"))
```

**Comment by oranjebloom** [comment]
Upon further examination of the logs, it appears that the last submission submission error from days earlier (4th June at 20:31) continues to appear multiple times throughout the current log (15th June). See the screen shot below. Is it normal behaviour for an error that occurred many days earlier to continue to be stamped the current log file?
![Screen Shot 2022-06-15 at 22 17 42](https://user-images.githubusercontent.com/46059094/173825753-0b8b7e8c-7a52-40dd-b29f-a637f6780e1f.png)

**Comment by toots** [comment]
Ha, thanks, that was a funny one. The partial application of the logging function was freezing the timestamp at the time of the partial application.
