### ISSUE TITLE
fallback and request.dynamic combination re-evaluate several times each second

### ISSUE THREAD

**Issue by thewilli** [savonet/liquidsoap#247]
Consider  the following piece of code. I would have expected (at least that is what I want to achieve), that liquidsoap tries to check for a request on the song.txt file, and if that fails, plays the static mp3 file _1.mp3_. Just before the mp3 file finishes playing, it should re-evaluate the command, and check if a valid file URI is provided (this is how I understood the `track_sensitive=true` option of `fallback`).

 While this seemed to work, liquidsoap does not stop trying to execute the command when the static mp3 file is played. So if there is no such text file, or if the file is just empty, I get the following debug messages about 4 times a second:

> 2015/08/15 14:20:11 [request:4] Nonexistent file or ill-formed URI ""!  

Is there any way to get `fallback` to only re-evaluate the command (I do not really want to use `cat`  here, it is just a replacement for a helper tool I want to use later) only when needed - in my example just before 1.mp3 stops playing - and not all the time in the background?

```
dynreqs =
  request.dynamic(
    fun () ->
      request.create(get_process_output("cat song.txt")))

static = single("1.mp3")

final = fallback(track_sensitive=true,[dynreqs,static])

output.alsa(final)
```

**Comment by thewilli** [comment]
I tried to define a custom protocol using `add_protocol`, and it is called even more than in my example above: just before the previous song finishes, I get plenty of calls during just a couple of seconds. Maybe I misunderstand the whole concept. Is there any way to return a "stop processing, no music here" value, so `fallback([alt1,alt2])` won't try the first alternative *alt1* again, until *alt2* was played one time?

**Comment by vrtisworks** [comment]
I ran into the same problem, and spent a few days trying to work around it.  The only solution I found was sort of brutal.  I did a variation of the request_dynamic sample.  After a lot of experimenting, I found that you need to shutdown BOTH the playlist and the output.  That will make LS do one last check for the input file and then quit.

I created a telnet command to start and stop the output when I knew the file was available.  You could probably shutdown the one that isn't working and start up a new one.  

Shutting down just the playlist did not stop the search for the file.  I tried a number of different variations.

Let me know if you have any other ideas.

**Comment by dbaelde** [comment]
This seems to be related to the preloading behavior of request.dynamic. If you set length to 0, it should stop preloading. If you set it to a few seconds, it should preload that many seconds before the end of file. Does this help?

**Comment by vrtisworks** [comment]
I don't remember all the things I tried.  But this is a good suggestion.  I'll have to try it out.

Thanks

**Comment by smimram** [comment]
This bug is mostly superseeded by #784.
