### ISSUE TITLE
OSC on Raspberry Pi

### ISSUE THREAD

**Issue by vrtisworks** [savonet/liquidsoap#248]
I have installed 1.0.1 on the Pi, and it is working.  I installed the LO plugin (which says it is OSC support), and when I start up Liquidsoap, it says the the plugin is loaded (0.1.0).

But, when I try to use any of the osc functions in my code, I get an error..

At line 58, char 18: the variable osc.send_string used here has not been
  previously defined.

It looks like I need to include something, but have not seen anything in any of the examples that I have found which does an include to enable these.

Anybody know what is going on?

Thanks.. Nick

**Comment by dbaelde** [comment]
OSC supports is only enabled if ocaml-lo is detected at configure-time. (And ocaml-lo itself, distributed by us, depends on liblo.) For instance here is what I get when I configure liquidsoap here:
```
 ...
   - lo                : no (requires lo)
 ...
```
As a result, `osc.send_string` is not available on my liquidsoap build. Does this help?

**Comment by dbaelde** [comment]
I confirm the issue on my debian (on a regular intel laptop): I have the liquidsoap and liquidsoap-plugin-lo packets installed but /usr/bin/liquidsoap does not know osc.send_string. Could the lo plugin be broken? I hope that Romain can help, otherwise I'll look into how the plugins are built and loaded.

**Comment by smimram** [comment]
The functions for sending data via OSC have not (yet) been released. You can either build from the git or wait for a new release (which should hopefully happen soon...)
