### ISSUE TITLE
Document log levels

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#249]
We should document log levels somewhere (and probably establish a policy before that and enforce it). I answered the following on the ML, but it should be refined / corrected.

Here is the informal policy (as I see it):
- level 1 : the program won't run because of this error (e.g. wrong arguments to a function)
- level 2 : an important error
- level 3 : a recoverable error / a warning
- level 4 : important debug message
- level 5 : a debug message

**Comment by dbaelde** [comment]
I agree with your description. For level 3 I'd tame it a bit. For me, in short: 1 = error, 2 = warning, 3 = info.

**Comment by smimram** [comment]
Fixed in #801.
