### ISSUE TITLE
metadata.json.stringify - image

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#2491]
**Describe the bug**
I've been passing metadata including cover art, which is recieved by a server as
```
{
...
"cover":"data:image/jpeg;base64: ...... ",
....
}
```
When I pass this on to an web page as ```<img src="data:image/jpeg;base64: ...... ">``` it fails.

If I replace ```data:image/jpeg;base64:``` with ```data:image/jpeg;base64,``` i.e replace the ```;``` after base64 with ```,``` it works. I'm quite happy to replace the character, but thought it was worth mentioning.

**To Reproduce**
```
http.post(headers=[("Content-Type","application/json")],data="#{metadata.json.parse(m)}", "http://127.0.0.1:7001/endpoint")
```
the resulting json is then parsed and the cover art is used in an image tag on a website.

Using version 2.0.6.

**Comment by Russsgithub** [comment]
I see it can use both ; and , in different situation . I'll close this.

**Comment by vitoyucepi** [comment]
@Russsgithub are you sure the this is the correct syntax for data url scheme?
According to [RFC](https://www.rfc-editor.org/rfc/rfc2397#section-2) there should be always `data:` and `,`, not `data:` and `:`

@toots I'm pretty sure there's a bug [here](https://github.com/savonet/liquidsoap/blob/7af6e951eb2bb1e4130e9641d1a0f112be7041f8/src/libs/string.liq#L178-L206).

I tried this code sample and it works
```js
a = new Image();
b = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
a.src = b;
```
but this will not work
```js
a = new Image();
b = 'data:image/gif;base64:R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
a.src = b;
```

And the patch for main
```patch
diff --git a/src/libs/string.liq b/src/libs/string.liq
index ea239bba..38d43c1c 100644
--- a/src/libs/string.liq
+++ b/src/libs/string.liq
@@ -176,20 +176,20 @@ end
 let string.data_uri = ()
 
 # Encode a string using the data uri format,
-# i.e. `"data:<mime>[;base64]:<data>"`.
+# i.e. `"data:<mime>[;base64],<data>"`.
 # @category String
 # @param ~base64 Encode data using the base64 format
 # @param ~mime Data mime type
 def string.data_uri.encode(~base64=true, ~(mime:string), s) =
-  s = base64 ? ";base64:#{string.base64.encode(s)}" : ":#{s}"
+  s = base64 ? ";base64,#{string.base64.encode(s)}" : ",#{s}"
   "data:#{mime}#{s}"
 end
 
 # Decode a string using the data uri format,
-# i.e. `"data:<mime>[;base64]:<data>"`.
+# i.e. `"data:<mime>[;base64],<data>"`.
 # @category String
 def string.data_uri.decode(s) =
-  captured = r/^data:([\/\w]+)(;base64)?:(.+)$/.exec(s)
+  captured = r/^data:([\/\w]+)(;base64)?,(.+)$/.exec(s)
   if list.assoc.mem(1, captured) and list.assoc.mem(3, captured) then
     mime = list.assoc(1, captured)
     data = list.assoc(3, captured)
diff --git a/tests/language/string.liq b/tests/language/string.liq
index e07d9970..aeed7ab3 100755
--- a/tests/language/string.liq
+++ b/tests/language/string.liq
@@ -64,11 +64,11 @@ def f() =
   t(string.annotate.parse("foo=bla,\"foo\"=\"✨✅\",\"gni:gno\"=\"bla\\\"blu:\":😈uri"),
     ([("foo", "bla"), ("foo", "✨✅"), ("gni:gno", "bla\"blu:")], "😈uri"))
 
-  t(string.data_uri.encode(mime="foo/bar", "✨"), "data:foo/bar;base64:4pyo")
-  t(string.data_uri.encode(base64=false, mime="foo/bar", "✨"), "data:foo/bar:✨")
+  t(string.data_uri.encode(mime="foo/bar", "✨"), "data:foo/bar;base64,4pyo")
+  t(string.data_uri.encode(base64=false, mime="foo/bar", "✨"), "data:foo/bar,✨")
 
-  t(string.data_uri.decode("data:foo/bar;base64:4pyo"), null("✨".{mime = "foo/bar"}))
-  t(string.data_uri.decode("data:foo/bar:✨"), null("✨".{mime = "foo/bar"}))
+  t(string.data_uri.decode("data:foo/bar;base64,4pyo"), null("✨".{mime = "foo/bar"}))
+  t(string.data_uri.decode("data:foo/bar,✨"), null("✨".{mime = "foo/bar"}))
   
   if !success then test.pass() else test.fail() end
 end
```

**Comment by Russsgithub** [comment]
@vito

No not at all. I remember finding use cases for  data:image/gif;base64:  but can't seem to find anything in search's that confirm that now.

I'm passing this into CSS , so data:image/gif;base64, is what I would need, ideally.

Russ

On 4 Sep 2022 02:31, Vito ***@***.***> wrote:

@Russsgithub<https://github.com/Russsgithub> are you sure the this is the correct syntax for data url scheme?
According to RFC<https://www.rfc-editor.org/rfc/rfc2397#section-2> there should be always data: and ,, not data: and :

@toots<https://github.com/toots> I'm pretty sure there's a bug here<https://github.com/savonet/liquidsoap/blob/7af6e951eb2bb1e4130e9641d1a0f112be7041f8/src/libs/string.liq#L178-L206>.

I tried this code sample and it works

a = new Image();

b = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';

a.src = b;

but this will not work

a = new Image();

b = 'data:image/gif;base64:R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';

a.src = b;

And the patch for main

diff --git a/src/libs/string.liq b/src/libs/string.liq

index ea239bba..38d43c1c 100644

--- a/src/libs/string.liq

+++ b/src/libs/string.liq

@@ -176,20 +176,20 @@ end

 let string.data_uri = ()



 # Encode a string using the data uri format,

-# i.e. `"data:<mime>[;base64]:<data>"`.

+# i.e. `"data:<mime>[;base64],<data>"`.

 # @category String

 # @param ~base64 Encode data using the base64 format

 # @param ~mime Data mime type

 def string.data_uri.encode(~base64=true, ~(mime:string), s) =

-  s = base64 ? ";base64:#{string.base64.encode(s)}" : ":#{s}"

+  s = base64 ? ";base64,#{string.base64.encode(s)}" : ",#{s}"

   "data:#{mime}#{s}"

 end



 # Decode a string using the data uri format,

-# i.e. `"data:<mime>[;base64]:<data>"`.

+# i.e. `"data:<mime>[;base64],<data>"`.

 # @category String

 def string.data_uri.decode(s) =

-  captured = r/^data:([\/\w]+)(;base64)?:(.+)$/.exec(s)

+  captured = r/^data:([\/\w]+)(;base64)?,(.+)$/.exec(s)

   if list.assoc.mem(1, captured) and list.assoc.mem(3, captured) then

     mime = list.assoc(1, captured)

     data = list.assoc(3, captured)

diff --git a/tests/language/string.liq b/tests/language/string.liq

index e07d9970..aeed7ab3 100755

--- a/tests/language/string.liq

+++ b/tests/language/string.liq

@@ -64,11 +64,11 @@ def f() =

   t(string.annotate.parse("foo=bla,\"foo\"=\"✨✅\",\"gni:gno\"=\"bla\\\"blu:\":😈uri"),

     ([("foo", "bla"), ("foo", "✨✅"), ("gni:gno", "bla\"blu:")], "😈uri"))



-  t(string.data_uri.encode(mime="foo/bar", "✨"), "data:foo/bar;base64:4pyo")

-  t(string.data_uri.encode(base64=false, mime="foo/bar", "✨"), "data:foo/bar:✨")

+  t(string.data_uri.encode(mime="foo/bar", "✨"), "data:foo/bar;base64,4pyo")

+  t(string.data_uri.encode(base64=false, mime="foo/bar", "✨"), "data:foo/bar,✨")



-  t(string.data_uri.decode("data:foo/bar;base64:4pyo"), null("✨".{mime = "foo/bar"}))

-  t(string.data_uri.decode("data:foo/bar:✨"), null("✨".{mime = "foo/bar"}))

+  t(string.data_uri.decode("data:foo/bar;base64,4pyo"), null("✨".{mime = "foo/bar"}))

+  t(string.data_uri.decode("data:foo/bar,✨"), null("✨".{mime = "foo/bar"}))



   if !success then test.pass() else test.fail() end

 end

**Comment by toots** [comment]
Thanks, fixed!
