### ISSUE TITLE
All encoders are running on a single thread

### ISSUE THREAD

**Issue by westjgames** [savonet/liquidsoap#250]
Hiya Guys

Basically, the issue is that I am getting nearly 100% CPU utilisation on single thread with 2 MP3 Encoders and 2 AAC encoders.

Is there any way to thread these out without resorting to external encoders?

Cheers.

**Comment by dbaelde** [comment]
Please look into clocks: http://liquidsoap.fm/doc-svn/clocks.html

On Tue, Aug 25, 2015 at 3:36 PM, westjgames <notifications@github.com>
wrote:

> Hiya Guys
>
> Basically, the issue is that I am getting nearly 100% CPU utilisation on
> single thread with 2 MP3 Encoders and 2 AAC encoders.
>
> Is there any way to thread these out without resorting to external
> encoders?
>
> Cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/savonet/liquidsoap/issues/250>.
>



-- 
David
