### ISSUE TITLE
Fallback source with `max_blank`: `on_track` gets triggered before it actually starts playing

### ISSUE THREAD

**Issue by davidtrattnig** [savonet/liquidsoap#2513]
**Describe the bug**

My fallback source starts playing as expected after the `max_blank` period of 15 seconds.

But the `on_metadata_notification` gets triggered 15 seconds before.

**To Reproduce**

```py
# 1.) Metadata to be called when track starts
def on_metadata_notification(meta) =
    print("TITLE: #{meta['title']}")
    print("ON AIR: #{meta['on_air']}")
end

# 2.) Invalid source to test fallback
empty_source = blank.strip(
        id="invalid_source",
        track_sensitive=false,
        max_blank=15.,
        min_noise=0.,
        threshold=-80.,
        blank()
    )

# 3.) Fallback
fallback_source = playlist(id="fallback_folder", "../audio/fallback", mode="randomize", reload=300, reload_mode="seconds")
fallback_source = source.on_track(id="fallback_folder", fallback_source, on_metadata_notification)
fallback_source = mksafe(fallback_source)

# 4.) Mix and output
main_source = fallback(
    id="fallback-source",
    track_sensitive=false,
    replay_metadata=true,
    [empty_source, fallback_source])
output.alsa(id="lineout", device="default", main_source)
```

**Logs:**

```log
2022/07/14 15:11:43 >>> LOG START
2022/07/14 15:11:41 [main:3] Liquidsoap 2.1.0+git@ac4233e2
...
2022/07/14 15:11:41 [clock:3] Using native (high-precision) implementation for latency control
TITLE: Heart Skipped A Beat
ON AIR: 2022/07/14 15:11:43
```

**Expected behavior**

`on_track` to be triggered when audio actually starts playing from the fallback source.

**Version details**
 - Liquidsoap 2.1.x latest rolling release (Liquidsoap 2.1.0+git@ac4233e2)

**Install method**
deb

**Comment by davidtrattnig** [comment]
After switching from the 2.1 rolling to the final 2.1 release the issue magically disappeared.

When just looking at the effects it appears to have a correlation with [this issue](https://github.com/savonet/liquidsoap/discussions/2544). Though it is working the PulseAudio ALSA plugin too.

**Comment by toots** [comment]
Great. We reverted some early changes on internal content representation that most likely had caused while `2.1.x` was in development. The work has restarted with more caution in `2.2.x`/`main`.

**Comment by davidtrattnig** [comment]
Oh thanks for letting me know. That gives some clarity and peace of mind.
