### ISSUE TITLE
Registering a  seek server function doesn't seem to work

### ISSUE THREAD

**Issue by luigiScarso** [savonet/liquidsoap#2514]
I am trying to implement a server command seek_full, but it fails : it works only for the first iteration of the rotation i.e. at the second iteration of the track1 the log says  "Seek not implemented!".  Registering the function at each track doesn't work too.  I am using the following code:
```
server.telnet()
settings.server.timeout.set(-1.)
set('alsa.alsa_buffer',32768)

s2 = single('track1.mp3')
s1 = single('track2.mp3')
src_RT =  rotate(id='src_RT',weights=[1,1], [s1,s2])

full = switch([
({true}, src_RT),
])

def seek_full(t)
  s = float_of_string(t)
  string_of_float(full.seek(s))
end
server.register("seek_full",seek_full)

##full.on_track(fun(_)-> server.register("seek_full",seek_full))
output.alsa(mksafe(full))
```
liquidsoap 2.0.6 installed via `opam` , ubuntu 20.04.4 ,  x86_64 .

**Comment by toots** [comment]
Thanks for the report. I ended up fixing a lot of places where `seek` wasn't implemented. This should come out with the `2.1.0` release that will be out tomorrow.
