### ISSUE TITLE
libs search path is incorrect on Windows.

### ISSUE THREAD

**Issue by wleader** [savonet/liquidsoap#2519]
In previous versions (1.3.4, 1.4.3) the software would correctly identify the libs(pervasives script libraries) directory. running "liquidsoap.exe --help" in these versions would show the help text:

     --no-pervasives
          Do not load pervasives script libraries (i.e.,
          C:\LiquidSoap\libs/*.liq).

In the latest 2.1.0, running "liquidsoap.exe --help" produces the following:

     --no-stdlib
          Do not load stdlib script libraries (i.e.,
          /home/opam/.opam/4.12.0/lib/liquidsoap/libs/*.liq).

This means that if you simply extract the archive to a folder and run the test.liq, it does not run. "liquidsoap.exe test.liq"

    PS C:\liquidsoap2> .\liquidsoap.exe .\test.liq
    Fatal error: exception Failure("Could not find default stdlib.liq library!")
    Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
    Called from Runtime.load_libs in file "lang/runtime.ml", line 232, characters 6-59
    Called from Main.load_libs.(fun) in file "main.ml", line 90, characters 6-102
    Called from Main.do_eval.eval in file "main.ml", line 110, characters 4-16
    Called from Main.do_eval.force in file "main.ml", line 126, characters 10-16
    Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
    Called from Dtools__Dtools_impl.Init.exec.exec in file "src/dtools_impl.ml", line 455, characters 10-16
    Re-raised at Dtools__Dtools_impl.Init.exec.exec in file "src/dtools_impl.ml", line 466, characters 8-15
    Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
    Called from Dtools__Dtools_impl.Init.exec.exec in file "src/dtools_impl.ml", line 458, characters 10-35
    Re-raised at Dtools__Dtools_impl.Init.exec.exec in file "src/dtools_impl.ml", line 466, characters 8-15
    Called from Main.start in file "main.ml" (inlined), line 572, characters 15-51
    Called from Runner_service in file "runner_service.ml", line 84, characters 15-28

**To Reproduce**
Extract the windows release to a directory and run "liquidsoap.exe test.liq"

**Expected behavior**
The http mp3 stream should play over the local soundcard.

**Version details**
 - OS: Windows
 - Version 2.1.0

**Install method**
Download Zip file and Extract to a folder.

**Comment by toots** [comment]
Thanks for your report! The issue should now be fixed in the asset available at: https://github.com/savonet/liquidsoap/releases/tag/v2.1.0. Feel free to give a try!

**Comment by wleader** [comment]
Confirmed. It does appear to be fixed.

**Comment by toots** [comment]
Build fixed to properly enable ffmpeg: https://github.com/savonet/liquidsoap/releases/download/v2.1.0/liquidsoap-2.1.0-win64.zip
