### ISSUE TITLE
Shine not detected - ARMHF Ubuntu

### ISSUE THREAD

**Issue by westjgames** [savonet/liquidsoap#252]
I installed all the libshine binaries, and made a symlink from /usr/lib/arm-linux-gnueabihf/libshine.so to /usr/bin/libshine.so

Running `liquidsoap 'output.icecast(%mp3.fxp,fallible=true,mount="test",playlist("/tmp/er"))'` results in `Invalid value at line 1, char 16-23: No encoder found for that format.`

I built Liquidsoap from source with Shine and all necessary requirements installed.

**Comment by smimram** [comment]
You need more than simply shine's .so: you also need the [ocaml binding](https://github.com/savonet/ocaml-shine)!

**Comment by westjgames** [comment]
That was built as well.

I ended up installing my distribution's version from their repository, then installing my compiled Liquidsoap over the top of it.

**Comment by dbaelde** [comment]
Please run configure again and check what it says about "MP3 (fixed-point)" in the summary at the end. For me (without shine installed) I have:
```
   - MP3 (fixed-point) : no (requires shine)
```
If you don't get a `yes` there, it's useless to go further in the build process.

**Comment by westjgames** [comment]
Nah, my ./configure result had "yes" for that one. Turns out it was sticking the built file in /usr/bin/, but the previous build I did stuck it in /usr/share/bin, which became default for some reason. My box is screwed.
