### ISSUE TITLE
Type infer error with `output.file`

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#2523]
**Describe the bug**
I got an error if I apply a function that modifies *source*, pass modified *source* into the `output.file` and then try to create a list from unmodified *source* and modified *source*.

**To Reproduce**
```
a = playlist("/a")
b = normalize(a)
output.file(%vorbis, "a.ogg", a, fallible = true)
c = [b, a]
```

**Expected behavior**
No error as in `2.0`

**Version details**
- OS: `ubuntu:20.04` in docker
- Version: `2.1.0`

**Install method**
Debian package for ubuntu focal in the `2.1.0` release.

**Common issues**
N/A

**Comment by toots** [comment]
Looks like a type inference issue:
<img width="629" alt="Screen Shot 2022-07-19 at 12 39 51 AM" src="https://user-images.githubusercontent.com/871060/179673608-6355256f-8e84-47c8-adf6-4dc34f3bd763.png">

**Comment by smimram** [comment]
Hum, "interesting"... A slightly minified version:
```
a = sine()
b = a.{xxx = 5}
output.file(%vorbis, "/tmp/a.ogg", a, fallible = true)
c = [b, a]
```
The strange thing is that if we replace `output.file` by `output.dummy` or `output.pulseaudio` the problem vanishes.

Let's try to understand...

**Comment by smimram** [comment]
Narrowing down: this works with
```
def f(s)
  ignore((s:source))
end
def g(s)
  ignore((s:source(audio=pcm(stereo))))
end

a = sine()
b = a.{xxx = 5}
f(a)
c = [b, a]
```
but not when I replace the call to `f` by a call to `g`.

**Comment by smimram** [comment]
New finding:
- it works if I print the type I we cast to in the penultimate line (yes, heisenbug, printing makes the bug disappear)
- it does not work if I remove the printing of ground types.

Conclusion, this is related to the way ground types are handled now... @toots it seems that the ball is in your camp now :)

**Comment by smimram** [comment]
This is actually more related to printing of formats. I get the error if I disable printing of formats:
```diff
diff --git a/src/lang/repr.ml b/src/lang/repr.ml
index b45064be1..af715e947 100644
--- a/src/lang/repr.ml
+++ b/src/lang/repr.ml
@@ -256,7 +256,7 @@ let print f t =
         Format.fprintf f "none";
         vars
     | `Constr (_, [(_, `Ground (Ground.Format format))]) ->
-        Format.fprintf f "%s" (Content.string_of_format format);
+        (* Format.fprintf f "%s" (Content.string_of_format format); *)
         vars
     | `Constr (name, params) ->
         Format.open_box (1 + String.length name);
```

**Comment by toots** [comment]
Clearly, there's something non standard with the way formats are passed down as type. I'm working on generalizing and cleaning this up in the `main` branch and will address it there.

**Comment by vitoyucepi** [comment]
@toots I've revisited this issue and maybe it's broken because of #2524.
That issue is not backported into `2.1.x` yet.

```
a = playlist("/a")
```
`a` has `remaining()` of `() -> [string]`
```
b = normalize(a)
```
`b` has `remaining()` of `() -> float`

So it's possible that they are actually not type compatible.

The we'll create a list.
```
c = [a, b]
```
And check this two loops.
1. ```
   for i = list.iterator(c) do print(i) end;;
   ```
1. ```
   for i = list.iterator(c) do print(i.remaining()) end;;
   ```

**Comment by smimram** [comment]
I don't think that this is related to #2524: my minimized examples don't use `playlist`.

**Comment by vitoyucepi** [comment]
I can't reproduce this issue in 1a262d49bd2cfb8457439e986c748a1a0317f8d4 and c15ac2ea08f36e49014d8e06e583387d5e11aff5.
Perhaps it should be closed.

**Comment by toots** [comment]
Great thanks for checking
