### ISSUE TITLE
`playlist` has wrong type for `remaining`

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#2524]
**Describe the bug**
`playlist.remaining` has type `fun() -> [string]`, but should be `fun() -> float`.
Ref: ef8e9b1.

**To Reproduce**
```
playlist("/something").remaining()
```

**Expected behavior**
`playlist.remaining` should have the same type as other source-like.

**Version details**
- OS: `ubuntu:20.04` in docker
- Version: `2.1.0`

**Install method**
Debian package for ubuntu focal in the `2.1.0` release.

**Common issues**
N/A

**Comment by toots** [comment]
Thanks @smimram. I'm backporting this to the rolling release for 2.1.x. It'll come out with the next bugfix on that branch.
