### ISSUE TITLE
`\` in interactive mode causes infinite error loop

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#2527]
**Describe the bug**
If I enter command `\`, then interactive session will fall into infinite loop.
```
Error 3: Parse error: 
# At line 1, char 0-0:

Error 3: Parse error: 
# At line 1, char 0-0:

Error 3: Parse error: 
# At line 1, char 0-0:

Error 3: Parse error: 
# At line 1, char 0-0:

Error 3: Parse error: 
# At line 1, char 0-0:

Error 3: Parse error: 
# At line 1, char 0-0:
```

**To Reproduce**
1. `liquidsoap --interactive`
2. `\<enter>`
3. `\;;<enter>`
4. `\single("/");;<enter>`

**Expected behavior**
I think that it should be a single parse error, not an infinite loop of errors.

**Version details**
- OS: `ubuntu:20.04` in docker
- Version: `1.4.4`, `2.0.7`, `2.1.0`

**Install method**
Debian package for ubuntu focal in the `2.1.0` release.

**Common issues**
N/A

**Comment by toots** [comment]
Fixed, thanks for reporting!
