### ISSUE TITLE
BREW install on OS/X 10.9.5

### ISSUE THREAD

**Issue by vrtisworks** [savonet/liquidsoap#253]
I tried to do a brew tap drfill/liquidsoap (which went ok)

Then I did brew install liquidsoap

and got
Error: No available formula for camlp4 (dependency of liquidsoap)
Searching taps...
adminisatorsair:~ administrator$

**Comment by toots** [comment]
I have this here:
```
==> Installing drfill/liquidsoap/liquidsoap dependency: camlp4
==> Downloading https://homebrew.bintray.com/bottles/camlp4-4.02.2+6_1.yosemite.bottle.tar.gz
```

What version of OSX are you running?

BTW, we will no longer maintain homebrew recipes with the next release and switch straight to the [opam](http://opam.ocaml.org/) package manager for OCaml.

**Comment by toots** [comment]
Okay sorry your version was in the title..

According to the [recipe for camlp4](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/camlp4.rb) it should be supported for your version.

I suspect that you have an issue with your homebrew setup, probably an outdated list of recipes. Closing this for now, please re-open if you have more info..
