### ISSUE TITLE
playlist.reloadable reloads just once

### ISSUE THREAD

**Issue by giflw** [savonet/liquidsoap#255]
I'm experimenting playlist.reloadable, and I'm trying to use the reload function returned to reload the playlist when its done, using a callback function on on_done parameter, but the playlist is always reloading just once.

```
Liquidsoap 1.1.1
Ubuntu 14.04.3 LTS
```

```ruby
pls_reload = ref fun(~uri="") -> print(uri)

def reload_pls()
  func = !pls_reload
  func()
end

s = playlist.reloadable( random=true, on_done=reload_pls,
              "http://localhost:8080/playlist.php/random" )
pls_reload := fst(s)

s = snd(s)
out(s)
```

The URI gives a random file URL per request.

**Comment by giflw** [comment]
I've changed some lines on `utils.liq` in my liquidsoap installation and its working now, apparently.

I've create a Gist with the actual utils.liq and my modification (but I really dont know if it add some other bug) (https://gist.github.com/giflw/e665b56ad429af67500a/revisions?diff=unified)

**Comment by smimram** [comment]
It's strange because your diff in `utils.liq` should not change anything... Are you sure it does not work if you revert it?

**Comment by giflw** [comment]
If I revert the changes, it will reload just once and switch to safe blank.

As I can see, on the first time it ends, on_done is called after passing `if not !has_stopped then` on line 527. But has_stopped is set to true on line 530 (`has_stopped := true`), preventing furter access to call on_done again on line 527.

Maybe in another place should have a `has_stopped := false`, but I don't know where.

Another question that came to my mind is: what happens if it loads a empty playlist

**Comment by giflw** [comment]
Another requirement for playlist.reloadable would be call on_done after reading a empty playlist too. This is what is happening with my changes. I can't know if this is the original behaviour, as it reloading just once and switching to safe blank.

**Comment by smimram** [comment]
After looking at your issue more in details, I think I understand it. With your modification, I think that `has_stopped` will never be `false` and thus `on_done` will be called infinitely. Could you try the following?
```
diff --git a/scripts/utils.liq b/scripts/utils.liq
index f7fcbdf..bda83ed 100644
--- a/scripts/utils.liq
+++ b/scripts/utils.liq
@@ -525,9 +525,9 @@ def playlist.reloadable(~id="",~random=false,~on_done={()},uri)
       else
         # Playlist finished
         if not !has_stopped then
+          has_stopped := true
           on_done ()
         end
-        has_stopped := true
         ""
       end
     request.create(file)
```

**Comment by giflw** [comment]
I've made a little simple test and seems to be working as expected.

As soon as I can i'll test with my full script to be sure, but seems OK now.

Thanks

**Comment by giflw** [comment]
It's working

**Comment by smimram** [comment]
Great! Reopening in order to think about comitting the fix.

**Comment by giflw** [comment]
I think it should be commited. I'll make a pacth on my installations for now.
