### ISSUE TITLE
`srt` documentation and installation

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#2556]
**Describe the bug**
I tried to do some experiments with `output.srt`.
I think it has problems.
1. Opam versions of `conf-srt` and `srt` are not maintained. They will fail to install on linux distros.
2. `output.srt(mode='listener')` supports only one simultaneous connection.
3. srt socket restarts after client disconnect.

**To Reproduce**
Run docker images
- `ocaml/opam:ubuntu-20.04-ocaml-4.14` - not fine
- `ocaml/opam:ubuntu-22.04-ocaml-4.14` - not fine
- `ocaml/opam:debian-10-ocaml-4.14` - not fine
- `ocaml/opam:debian-11-ocaml-4.14` - fine

With script
```sh
opam repository set-url default https://opam.ocaml.org/
sudo apt-get update
opam depext srt
opam install srt
```

**Expected behavior**
1. I'd like to see documentation about
   > In "listener" mode, it waits for clients to connect to it to send them the stream.

   I didn't expect that it will allow only one client at a time.
2. `srt` with different distros.

**Version details**
 - OS: *debian:10*, *debian:11*, *ubuntu:20.04*, *ubuntu:22.04*
 - Version: *2.0.7*, *2.1.0*

**Install method**
- opam
- deb from release artifact

**Common issues**
N/A

**Comment by toots** [comment]
Good points, thanks for raising them. The `output` operator was originally only considered for a single output and the listening code mostly comes from the input operator for which restarting the listening socket was an acceptable compromise. Will address both.

**Comment by toots** [comment]
The `opam` depext issues are addressed in https://github.com/ocaml/opam-repository/pull/21987
