### ISSUE TITLE
Liquidsoap not in /etc directory

### ISSUE THREAD

**Issue by daw654** [savonet/liquidsoap#2558]
After installing via apt-get install liquidsoap, there is no folder in /etc? 

How do I find the script to edit liquidsoap?

**Comment by vitoyucepi** [comment]
Hi, @daw654 what linux distribution are you using? What version of liquidsoap have you installed?

**Comment by daw654** [comment]
@vitoyucepi  Ubuntu 22.04 LTS and 2.0.2.

**Comment by vitoyucepi** [comment]
@daw654 there's no configuration directory in ubuntu package.

If I were you, then I will
1. Get `/etc/systemd/system/liquidsoap@.service` from aur https://aur.archlinux.org/cgit/aur.git/plain/liquidsoap.service?h=liquidsoap.
2. Do `systemctl daemon-reload`.
3. Create dir `/etc/liquidsoap`.
4. Write my config in `/etc/liquidsoap/main.liq`.
   `main` is a sample name, any other can be used.
5. Enable + start liquidsoap service with command `systemctl enable --now liquidsoap@main.service`.
   `main` is the same name as in (4).

**Comment by daw654** [comment]
@vitoyucepi I will try that thank you

**Comment by daw654** [comment]
@vitoyucepi How would I do step 1?

**Comment by vitoyucepi** [comment]
@daw654 
`sudo wget 'https://aur.archlinux.org/cgit/aur.git/plain/liquidsoap.service?h=liquidsoap' -O '/etc/systemd/system/liquidsoap@.service'`

**Comment by daw654** [comment]
@vitoyucepi I am able to start it as a service but I don't get an output to Icecast, not sure what the problem is.

**Comment by vitoyucepi** [comment]
@daw654 I do recommend you to read the guideline here https://www.liquidsoap.info/doc-2.0.2/.
And also [the book](http://www.liquidsoap.info/book/book.pdf).
There are a lot of code samples there.
I highly recommend you to read them.

As for your question, you could read files from any path.
```ruby
s = mksafe(playlist("/path/to/your/music"))
output.icecast(
  host="localhost",
  port=8000,
  password="hackme",
  mount="my-radio.mp3",
  %mp3,
  s
)
```

Anyway, would you mind opening a [discussion](https://github.com/savonet/liquidsoap/discussions/new) in *Q&A* category?
If I've answered your original question, then please mark this issue as solved.

**Comment by Matzeee** [comment]
> @daw654 there's no configuration directory in ubuntu package.
> 
> If I were you, then I will
> 
> 1. Get `/etc/systemd/system/liquidsoap@.service` from aur https://aur.archlinux.org/cgit/aur.git/plain/liquidsoap.service?h=liquidsoap.
> 2. Do `systemctl daemon-reload`.
> 3. Create dir `/etc/liquidsoap`.
> 4. Write your config in `/etc/liquidsoap/main.liq`.
>    `main` is a sample name, any other can be used.
> 5. Enable + start liquidsoap service with command `systemctl enable --now liquidsoap@main.service`.
>    `main` is the same name as in (4).

That was really helpful, but it took me some time to find this issue. Works for me on ubuntu.
A hint in the docs would be useful:
https://www.liquidsoap.info/doc-dev/in_production.html


How about that one? Should not be used anymore?
https://github.com/savonet/liquidsoap-daemon
