### ISSUE TITLE
Outdated `set` recommendations

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#2562]
**Describe the bug**
If I run liquidsoap as root, then I'll see
```
init: security exit, root euid & guid (user & group). Override with set("init.allow_root",true)
```

This suggestion comes from here
https://github.com/savonet/liquidsoap/blob/9fc6637461463743ba27e2a5cbbed5ab835d446c/src/bin/main.ml#L583-L586

Maybe also this code will produce same old syntax https://github.com/savonet/liquidsoap/blob/9fc6637461463743ba27e2a5cbbed5ab835d446c/src/bin/main.ml#L523-L528

Should be backported to `2.0` and `2.1`.

**To Reproduce**
1. Become root
1. `echo 'output.dummy(blank())' > 1.liq`
1. `liquidsoap 1.liq`

**Expected behavior**
There should be a settings of new style `settings.init.allow_root.set(true)`.

**Version details**
 - OS: `ubuntu:20.04` in docker
 - Version: *2.0.x*, *2.1.x*, *main*

**Install method**
Debian package for ubuntu focal.

**Common issues**
N/A

**Comment by toots** [comment]
Fixed in `main` and `rolling-release-v2.1.x`, thanks for reporting!

**Comment by vitoyucepi** [comment]
@toots why is it `init.allow_root.set(true)` and not `settings.init.allow_root.set(true)`?

I've checked it and didn't find any notes except `log.level.set`.
Is it an undocumented shortcut to the settings?

**Comment by toots** [comment]
That's a typo! Just pushed a fix, thanks for checkin it!

**Comment by vitoyucepi** [comment]
@toots and what about this piece of code? https://github.com/savonet/liquidsoap/blob/227b6e74cf145f3a61bed67fd41ae18c53cdff17/src/bin/main.ml#L523-L528
I have no idea how to trigger this error.

**Comment by vitoyucepi** [comment]
@toots anyway, would you kindly share a piece of knowledge about this behavior.
Why `init.allow_root.set(true)` works as expected?
Why `log.level.set` is used in the book (pages 65, 109, etc) and in the tests.
https://github.com/savonet/liquidsoap/blob/227b6e74cf145f3a61bed67fd41ae18c53cdff17/tests/streams/request.liq#L3
https://github.com/savonet/liquidsoap/blob/227b6e74cf145f3a61bed67fd41ae18c53cdff17/tests/media/test_video_size.liq#L1-L4

**Comment by toots** [comment]
> @toots anyway, would you kindly share a piece of knowledge about this behavior. Why `init.allow_root.set(true)` works as expected? Why `log.level.set` is used in the book (pages 65, 109, etc) and in the tests.
> 
> https://github.com/savonet/liquidsoap/blob/227b6e74cf145f3a61bed67fd41ae18c53cdff17/tests/streams/request.liq#L3
> 
> 
> https://github.com/savonet/liquidsoap/blob/227b6e74cf145f3a61bed67fd41ae18c53cdff17/tests/media/test_video_size.liq#L1-L4

`log.level.set()` it a shorthand for `settings.log.level.set()` defined in the standard library to make it easier to change this commonly used setting.
