### ISSUE TITLE
Alpine Docker Image Errors On Raspberry PI

### ISSUE THREAD

**Issue by jkossis** [savonet/liquidsoap#2564]
**Describe the bug**
The alpine-based docker image spits out the following error when run on a Raspberry Pi 3b+:

<img width="1410" alt="Screen Shot 2022-08-16 at 3 27 26 PM" src="https://user-images.githubusercontent.com/1247832/184965614-539bb495-1036-4033-b9d4-4972da6e4f40.png">

In comparison, this is the output when run on a Macbook Pro:

<img width="896" alt="Screen Shot 2022-08-16 at 3 27 06 PM" src="https://user-images.githubusercontent.com/1247832/184965785-ae30d8e3-41f6-4e83-a9b7-bbe09e2fea44.png">

**To Reproduce**
Run the following command: `docker run --rm ghcr.io/savonet/liquidsoap-alpine:v2.1.0`

**Expected behavior**
Running the image on the Raspberry Pi should yield the same message: `No output defined, nothing to do.`

**Version details**
 - OS: macOS 11.6.8, Raspbian GNU/Linux 10 (buster)

**Install method**
Docker

**Comment by toots** [comment]
Thanks for reporting this. I've rebuilt the `armhf` image for alpine and the images are being rebuilt here: https://github.com/savonet/liquidsoap/actions/runs/2873032618. Would you mind giving it a try once it completes?

**Comment by jkossis** [comment]
I appreciate you getting back to me so quickly. I gave the new rolling release a go, and it appears we are moving in the right direction (I think). The container now just exits immediately, without printing all the byte-code that we were seeing previously. 

When running in a docker-compose setup (with icecast), it shows the container exiting with code 139. That said, I can't seem to get any logs or info from it (tried running with the `-v` and `--debug` flags).

On a possibly (un)related note, I think a typo might have [snuck into this commit on line 1](https://github.com/savonet/liquidsoap/commit/3b02e9c1e79bf9fe57a810b7b73b5a63b747ebc8).

**Comment by toots** [comment]
Ok, it took me much longer than I expected but the image is now fixed! Also that typo too :-)
