### ISSUE TITLE
Flows service is down

### ISSUE THREAD

**Issue by BreadMaker** [savonet/liquidsoap#257]
I'm getting a 503 error when I'm trying to connect to Flows service.

![captura de pantalla de 2015-09-08 11-39-23](https://cloud.githubusercontent.com/assets/713711/9737707/5517191a-561e-11e5-94c3-77686f01a305.png)

![captura de pantalla de 2015-09-08 11-40-16](https://cloud.githubusercontent.com/assets/713711/9737722/6604a580-561e-11e5-837d-fbb875a0727e.png)

**Comment by toots** [comment]
Yeah. heroku is shutting our free dyno down at times now to "recharge"..

**Comment by BreadMaker** [comment]
Anything we can do to keep that dyno up 24/7 ?

**Comment by toots** [comment]
Donate through our webpage at http://liquidsoap.fm/

We have some money in the account actually, I'll look at upgrading to a hobby dyno as soon as possible.

**Comment by BreadMaker** [comment]
Sure thing! Thanks.

**Comment by bradisbell** [comment]
@toots I might be willing to provide hosting for this service in exchange for a link back to my company's website, http://audiopump.co.  Please contact me at brad@audiopump.co if you have interest in this.
