### ISSUE TITLE
Crash in 2.1.0 when file in playlist doesn't exist

### ISSUE THREAD

**Issue by brenc** [savonet/liquidsoap#2576]
**Describe the bug**
Today I noticed that when a file in a playlist doesn't exist, LS 2.1.0 gets stuck in a loop and crashes. This doesn't happen with 2.0.7.

**To Reproduce**
```
# Load up a playlist:
chipstepnewhigh = playlist(
    '/ngradio/playlists/chipstep_newhigh.m3u',
    mime_type='application/x-mpegURL',
    mode='randomize', 
    reload_mode='watch',
)

# chipstep_newhigh.m3u (this file does not exist):
/mnt/ng_audio_uploads/1110000/1110395_Head-In-The-Clouds.mp33
```

Editing the file causes a reload and some error messages which is expected:

`[request:3] Nonexistent file or ill-formed URI "/mnt/ng_audio_uploads/1110000/1110395_Head-In-The-Clouds.mp33"!`

If I restart LS I get:
```
# 100s of these:
[request:3] Nonexistent file or ill-formed URI "/mnt/ng_audio_uploads/1110000/1110395_Head-In-The-Clouds.mp33"!
# A few of these:
[request:2] There are currently 6500 RIDs, possible request leak! Please check that you don't have a loop on empty/unavailable requests.
# And then finally:
Segmentation fault (core dumped)
```

**Expected behavior**
Log nonexistent errors a few times and stop.

**Version details**
 - OS: Docker
 - Version: savonet/liquidsoap:v2.1.0

**Comment by toots** [comment]
Thanks for reporting! This is fixed in the `rolling-release-v2.1.x` branch which is about to go out!
