### ISSUE TITLE
Not getting cover art with ID3v2.2 tags

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#2581]
**Describe the bug**
I have had a few mp3's with ID3v2.2 tags, and have noticed the images embedded are not getting seen by liq

I need to find an offending mp3 as i converted them all to v2.3 to get around this, but will upload one soon.

**Version details**
 - OS: [e.g. Debian, OSX] - ubuntu 20.04
 - Version [e.g. `1.3.4`] - 2.1

**Install method**
opam

**Comment by Russsgithub** [comment]
I can't edit that post for some reason, but here's a link to the file.

https://drive.google.com/file/d/1kqJlNRnyFgFq3RE15MaFPKgcu-WvH4aA/view?usp=sharing

and here's the script i've been using to test files with.

```
s = single("./Black_Beauty.mp3")
s.on_metadata(fun(m) -> print(m))
output.dummy(fallible = true, s)
```

**Comment by toots** [comment]
This is fixed now, thanks for reporting. Nice track, too!
