### ISSUE TITLE
buffer_length always returns 0.

### ISSUE THREAD

**Issue by ftirej** [savonet/liquidsoap#2604]
**Describe the bug**
buffer_length always returns 0. when trying to get the value in seconds of the input.http or input.harbor inputs.

**To Reproduce**
![image](https://user-images.githubusercontent.com/1999170/188920192-12578fde-4958-4be6-8e62-0e7382c76737.png)

**Expected behavior**
Return the buffer value in seconds.

**Version details**
 - OS: [OSX 12.5.1]

**Install method**
installed via opam

**Comment by toots** [comment]
Thanks for the report. Please, next time send textual code so it's easy to copy/paste.. 🙂

**Comment by toots** [comment]
I can confirm the values but I don't think that there's any issue here. The operator is designed to operate with a minimal buffer. Typically if it is behind a switch pulling from another track. This is also true when the operator is not actively used (for instance when used in a switch), in which case ffmpeg does the buffering internally.

The pre-2.x `input.http` was operating differently with an internal thread and an internal buffer but this was changed when we switched to using `input.ffmpeg` for it.

If you need a buffer, you can always use an explicit `buffer`:
```liquidsoap
s = input.http("...")
s = buffer(buffer=4., s)
```

**Comment by toots** [comment]
I'm gonna keep this tab open for a minute to think about how this issue and https://github.com/savonet/liquidsoap/issues/2615 point to a need to clarify some issues with buffering in these operators.
