### ISSUE TITLE
Lowercase tags are ignored on Opus files with album art

### ISSUE THREAD

**Issue by parnikkapore** [savonet/liquidsoap#2605]
**Describe the bug**
It looks like the title and artist tags from Opus files (Ogg files in general?) are ignored if they are in lowercase according to `ffprobe` and the file has an album art. If the tags are uppercase, LiquidSoap will pick them up.

This file will not have any metadata when played via liquidsoap:
```
Input #0, ogg, from 'test5a.ogg':
  Duration: 00:01:05.25, start: 0.000000, bitrate: 157 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      title           : Test A
      artist          : Ada
  Stream #0:1: Video: png, rgb24(pc), 256x256 [SAR 3780:3780 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)
```
(tagged using Quod Libet)

This file will:
```
Input #0, ogg, from 'test5e.ogg':
  Duration: 00:01:05.25, start: 0.000000, bitrate: 157 kb/s
  Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      TITLE           : Test A
      ARTIST          : Adak
  Stream #0:1: Video: png, rgb24(pc), 256x256 [SAR 3780:3780 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Cover (front)

```
`{ "artist": "Adak", "title": "Test A" }`
(tagged using Picard)

**To Reproduce**
```
def log_song(m)
    print("#{metadata.json.stringify(m)}\n")
end

radio = single("./test/test5a.ogg")
radio.on_track(log_song)
output.dummy(radio)
```

**Expected behavior**
The title and artist tags should be recognized both in uppercase and lowercase, similar to VLC and Quod Libet.

**Version details**
 - OS: KDE Neon
 - Version: 2.1.0

**Install method**
Installed using .deb package from Releases page

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by parnikkapore** [comment]
Issue seems to be misdiagnosed; hold on a sec please

**Comment by parnikkapore** [comment]
There is a distinct possibility of Quod Libet's tags being subtly broken, although the tags work fine in VLC...

**Comment by toots** [comment]
Hi @parnikkapore, thanks for reporting! Could you either attach an example file here or send it to me at toots@rastageeks.org? Thks!

**Comment by parnikkapore** [comment]
Sure! The file and script is in the attached .zip file. (GitHub doesn't support uploading sound files)

[repro.zip](https://github.com/savonet/liquidsoap/files/9542372/repro.zip)

**Comment by smimram** [comment]
I just added support for the native ogg parser, which seems to handle the file correctly: 516cf01be7adfa9d57bdfb584383a5bb6ffc791a.

**Comment by toots** [comment]
Thanks @smimram ! This one was a multiple one:
* We were not pulling enough metadata using `ffmpeg`
* Taglib was (prolly historically) limited to `mp3`
* We had a bug in the opus comment parser.

Woof! This should all be fixed now!
