### ISSUE TITLE
Allow fractional / sub 1s sleep times

### ISSUE THREAD

**Issue by brenc** [savonet/liquidsoap#2610]
**Is your feature request related to a problem? Please describe.**
I'm trying to load a large number of playlists in way that is less impactful to station startup/operation during the first few minutes.

One thing I'm doing is sleeping in a loop that loads each playlist in a dir. I've noticed that `sleep()` takes a float, however, it appears that it rounds whatever is passed to it to an integer. For example, a sleep of 0.4 operates like 0.0 and a sleep of 0.5 operates like 1.0.

**Describe the solution you'd like**
To be able to sleep for fractional time, especially sub-1s. It's confusing that `sleep()` takes a float but rounds the number to an int.

**Describe alternatives you've considered**
This is my workaround:
```
_ = process.test("sleep 0.1")
```

**Comment by toots** [comment]
Thanks for reporting it, that was an interesting one. I'm suspecting this was a pretty old behavior, perhaps even from before we had asynchronous tasks workers. Fixed in `main` and `rolling-release-v2.1.x`.
