### ISSUE TITLE
Support multipart/form-data with http.{post.put}

### ISSUE THREAD

**Issue by cdgraff** [savonet/liquidsoap#2617]
I'll like to avoid use CURL to post form-data audio to external API, and replace them with native `http.post`
```
uploader = process.read.lines("curl -i -X POST https://url.com/ -F \"file=@#{fname}\"")
```
With something more native like:
```
res = http.post(data="file=@file.read(fname)",file_url(path.basename(fname))) 
```

**Comment by smimram** [comment]
Could you try #2640? I am not sure about how to easily test this...

**Comment by cdgraff** [comment]
@smimram Happy to test, just I don't know if I can download some docker or deb with this code branch? or need to download and compile from GIT? can help me with some guidance for testing this feature?

**Comment by toots** [comment]
@cdgraff I'm gonna backport this to `rolling-release-v2.1.x` I believe since it is only adding new functionalities.

**Comment by toots** [comment]
It's been backported. You can now do:
```
http.post.file(file="/path/to/file", "http://...")

**Comment by cdgraff** [comment]
After your latest fixes! works... I was fighting for some hours without understanding what was wrong, and checking read your latest commit with fixes... after the update, it all start to work, thanks!!!

**Comment by cdgraff** [comment]
@toots I found something that I'll like to get your opinion...

Current POST doesn't include a Content-Length header, that was by design?

We saw that our HTTP server response with HTTP 100

```
2022/09/26 11:16:31 [/tmp/streambox/pruebaaudit/%Y/%m/%d/%Hh/1664155942.mp3:3] Re-opening output pipe.
2022/09/26 11:16:31 [pruebaaudit:3] Segment /tmp/streambox/pruebaaudit/2022/09/26/11h/1664190961.mp3 created
2022/09/26 11:16:32 [pruebaaudit:3] Uploader Status: 100 - Continue
```

But before with CURL we get the 200, researching about when is getting the 100 HTTP code we found:

> chunked
> Data is sent in a series of chunks. The Content-Length header is omitted in this case and at the beginning of each chunk you need to add the length of the current chunk in hexadecimal format, followed by '\r\n' and then the chunk itself, followed by another '\r\n'. The terminating chunk is a regular chunk, with the exception that its length is zero. It is followed by the trailer, which consists of a (possibly empty) sequence of header fields.

```
Host: xxxxx.x.pipedream.net
Transfer-Encoding: chunked
user-agent: Liquidsoap/2.1.2+git@8aa9e853 (Unix; OCaml 4.14.0)
accept: */*
content-type: multipart/form-data; boundary=0exK3PPksPTt
```
I don't know if wrong but is not a serie of chunks,  I think the file has a length and are reading full them before post, for that reason is possible to get the Content-Length.

thanks!
Ale

**Comment by toots** [comment]
Yes, this is the intended behavior. The idea is to never load the data in-memory so the file is transferred chunked by chunk. In this case, the HTTP protocol stipulates that no `Content-Length` should be used and to let the chunked transfer determine the total size.

I've just added some changes that allow to revert to `Content-Length` when the whole file is in memory. Though `libcurl` seems to still prefer chunked transfer for `PUT` request, this will work for `http.post.file`:
```
http.post.file(contents=file.contents(filename), filename=filename, ...)
```
But this will load the whole file in memory!

**Comment by toots** [comment]
As for the `100` status, this is also `libcurl` default behavior it seems. Responding with a `200` should work but you won't be able to read the incoming data until you send it. Most webservers handle this transparently.
