### ISSUE TITLE
server.insert_metadata() misparses commas

### ISSUE THREAD

**Issue by nowster** [savonet/liquidsoap#2619]
I use the telnet server to insert metadata into a stream captured from the sound card.

```
settings.server.telnet.set(true)
source = mksafe(input.alsa())
source = server.insert_metadata(id="ID", source)
```

I feed in artist and titles using something similar to this:

```
echo 'ID.insert artist="Artist Name",title="Track Title" ' | nc -w1 127.0.0.1 1234
```

The problem is that if either field contains a comma, the parser fails. If it's in the artist field, the artist name is unset and just the title is sent to the Icecast server. If it's in the title field, the title becomes "Unknown".

If both fields contain commas, an error is returned:

```
Syntax error or no metadata given. Use key1="val1",key2="val2",..
```

This is easy to test:

```
echo 'ID.insert artist="Test Artist",title="Test Track"' | nc -w1 127.0.0.1 1234
echo 'ID.insert artist="Test, Artist",title="Test Track"' | nc -w1 127.0.0.1 1234
echo 'ID.insert artist="Test Artist",title="Test, Track"' | nc -w1 127.0.0.1 1234
echo 'ID.insert artist="Test, Artist",title="Test, Track"' | nc -w1 127.0.0.1 1234
```

**Version details**
 - OS: Debian
 - Version: 2.0.6-1

**Install method**
Installed from Debian package.

**Comment by smimram** [comment]
I guess that [this comment](https://github.com/savonet/liquidsoap/blob/main/src/libs/server.liq#L35) is relevant: :)
```python
    #TODO: we don't split as expected if one string contains a comma, but this
    #is difficult to achieve with regexps
```
Let met try do do something here.

**Comment by nowster** [comment]
Quick hack:

```
35    l = r/",/.split(s)
```
and
```
41     ret = r/([^=]+)\s*=\s*"((?:\"|[^"])*)"?/.exec(x)
```

**Comment by nowster** [comment]
If ocaml supports _perlre_ type lookbehind, then the change is simply:

```
35  l = r/(?<="\s*),/.split(s)
```

**Comment by toots** [comment]
We have a proper parser for this now!
