### ISSUE TITLE
add_text and cycle=true with long text doesn't wait the end of the text

### ISSUE THREAD

**Issue by kessenza** [savonet/liquidsoap#2620]
Hi I am using Liquidsoap 2.1.2+dev on Ubuntu 20 installed via opam
I need to cycle long text using add_text method (it's using camlimages). 
After one hundred chars (more or less) text restarts on the left from the beginning. Changing speed doesn't help and doesn't let to see more text.
Setting cycle to false let to see all text but I don't know how to show it again.

This is my code

```python
#!/root/.opam/ocaml/bin/liquidsoap -v
settings.init.allow_root.set(true)
settings.frame.video.width.set(1280)
settings.frame.video.height.set(720)
settings.log.file.path.set("/tmp/liquidsoap.log")
settings.log.stdout.set(true)
settings.log.level.set(5)

accentText=file.lines("/usr/local/iptv/liquid/accent.txt")
channelText=list.hd(accentText)

schedule= playlist(id="test_playlist",reload_mode="watch",loop=false,mode="normal","/usr/local/iptv/liquid/channel_1/schedule_0.pls")

schedule  = video.add_text(speed=540,
    channelText,font="/usr/local/iptv/assets/bankgothic.ttf",cycle=true,color=0xFFFFFF,size=40,x=1280,y=644, schedule)
```

-----
I'm attaching log. [liquidsoap.log](https://github.com/savonet/liquidsoap/files/9566048/liquidsoap.log)

**Comment by smimram** [comment]
This should have been fixed by b5b95cf2223f13ab61c878730e9ffc2c1111d7db.
