### ISSUE TITLE
ReplayGain extraction fails

### ISSUE THREAD

**Issue by parnikkapore** [savonet/liquidsoap#2624]
**Describe the bug**
ReplayGain extraction is not applied to a file without existing ReplayGain tags.

**To Reproduce**
```ruby
enable_replaygain_metadata()
settings.protocol.youtube_dl.path.set("yt-dlp") # you know why
radio = single("youtube-dl:https://www.youtube.com/watch?v=dQw4w9WgXcQ")
radio = mksafe(replaygain(radio))
output(radio)
```

Run the script with `--debug`. The following will appear:
```plain
[extract.replaygain:4] ReplayGain extraction by /usr/share/liquidsoap/2.1.1/bin/extract-replaygain failed with: /bin/sh: 1: extract_replaygain: not found
```

**Expected behavior**
The script should be run properly and the ReplayGain metadata should be generated.

**Version details**
 - OS: KDE Neon
 - Version: 2.1.1

**Install method**
Installed using .deb package from Releases page

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by smimram** [comment]
We should fix this once and for all by not using an external script for RG, see #1002.
