### ISSUE TITLE
Getting this while compiling: File "tools/file_watcher_inotify.ml", line 52, characters 20-32: Error: Unbound value Inotify.init

### ISSUE THREAD

**Issue by odifek** [savonet/liquidsoap#263]
Always getting this error while running make on liquidsoap-full after successful ./configure.
```
OCAMLOPT -c tools/file_watcher_inotify.ml
File "tools/file_watcher_inotify.ml", line 52, characters 20-32:
Error: Unbound value Inotify.init
make[3]: *** [tools/file_watcher_inotify.cmx] Error 2
```

Don't know how to get out of it!

**Comment by smimram** [comment]
Hi,

This was fixed in 017154e86940f24906096a0fde88f77bd9f7ff14. Please use the git version or wait for the next release.
