### ISSUE TITLE
on_metadata not working ?

### ISSUE THREAD

**Issue by MrChrisCool** [savonet/liquidsoap#2639]
Hi !
Here is my script : 

----------------------------------------------------------------------------------------------------------------------------
enable_replaygain_metadata()
security = single("/usr/local/var/zik/fail/vache.ogg")

def requestTrack() =
  log("Request")
  result = list.hd(default="", process.read.lines("php /var/www/srv/requestTrack.php"))
  log("Got answer: #{result}")
  [request.create(result)]
end

def onmeta(m) =
  artist = m["artist"]
  title = m["title"]
  log("--=== Fire MetaData - #{title} [#{artist}] ===--")
end

lgt = amplify(1.,override="replay_gain", request.dynamic.list(requestTrack))
lgt = fallback(track_sensitive = false, [lgt, security])
lgt = on_metadata(onmeta, lgt)

output.icecast(%vorbis, host = "localhost", port = 8000, mount = "lgt.ogg", name = "La Grosse Tambouille", url = "https://radio-tambouille.net", description = "Web radio éclectique sans pub !", genre = "Eclectique", lgt)
output.icecast(%mp3, host = "localhost", port = 8000, mount = "lgt.mp3", name = "La Grosse Tambouille", url = "https://radio-tambouille.net", description = "Web radio éclectique sans pub !", genre = "Eclectique", lgt)
--------------------------------------------------------------------------------------------------------------------------

When I try to run this script I receive the following error : 

Sep 21 19:19:05 radio-tambouille liquidsoap[6895]: At /home/liquidsoap/liquidsoap-daemon/script/lgt.liq, line 28, char 6-18:
Sep 21 19:19:05 radio-tambouille liquidsoap[6895]: lgt = on_metadata(onmeta, lgt)
Sep 21 19:19:05 radio-tambouille liquidsoap[6895]: Error 4: Undefined variable on_metadata

Liquidsoap 2.1.1 on Ubuntu server 20.04 compiled with opam (Ocaml 4.14.0)

I missed something ? on_metadata is no more available ?

Thanks

**Comment by cdgraff** [comment]
I'm using just check that on_metadata needs to be assigned to some stream

# Check output metadata to set is_playing metric
radio.on_metadata(check_is_playing)
