### ISSUE TITLE
File: Error Could not write data to host.  Broken pipe on Write() . Opus streaming 

### ISSUE THREAD

**Issue by odifek** [savonet/liquidsoap#264]
Have encountered this error on fresh built liquidsoap trying to set up opus streaming on icecast2 server. Have searched everywhere in the Internet, seems no solution.

**Comment by toots** [comment]
Do you have more information about your setup?

**Comment by odifek** [comment]
Oh, I discovered the cause. I was using the default icecast (2.3) provided
by Ubuntu which does not support opus streaming.
Updated to version 2.4 through custom ppa and the problem is now fixed.
I got the ppa from icecast.org
Thanks
