### ISSUE TITLE
Permission denied when trying to write to pid file. 

### ISSUE THREAD

**Issue by dannybit** [savonet/liquidsoap#265]
I am trying to create a service that starts multiple liquidsoap instances so I want to create a different pid for each instance and run liquidsoap as daemon.
Here is what I have in my .ls file: 

```
   set("init.daemon",true)
   set("init.daemon.pidfile.path", "liquidsoap.pid")
```

Here is the error I get when I try to run the script with `liquidsoap -d liquidsoap.ls`:
```
Fatal error: exception Sys_error("liquidsoap.pid: Permission denied")
Raised by primitive operation at file "pervasives.ml", line 239, characters 21-47
Called from file "pervasives.ml", line 242, characters 2-74
```

I have multiple liquidsoap scripts each saved in a separate folder and I want the script to save the PID file in the same folder of the script. 

Thank you.

**Comment by toots** [comment]
What user is liquidsoap running under and does that user have write access to the directory where the pid resides?

(Sorry, gonna close this as I don't think it an issue in the code per-say. Feel free to respond here though)
