### ISSUE TITLE
immediate segmentation fault on ubuntu 15.04

### ISSUE THREAD

**Issue by rhetr** [savonet/liquidsoap#266]
I installed the liquidsoap binary provided in the ubuntu repositories but I can't run it at all, I immediately get a segmentation fault. I also compiled it manually but still received a segmentation fault. even `liquidsoap --help` produces a segmentation fault. Running it in gdb returns this 

    Program received signal SIGSEGV, Segmentation fault.
    0x000000000075e39f in caml_copy_string ()

**Comment by smimram** [comment]
This bug is most likely due to a problem in Ubuntu's build chain. Please report directly to Ubuntu.
