### ISSUE TITLE
Specify a python binary at configure time

### ISSUE THREAD

**Issue by J5lx** [savonet/liquidsoap#267]
Currently liquidsoap expects the python binary to be named strictly `python`. However this binary is Python 3 on my system while liquidsoap seems to expect Python 2 (which is named `python2` on my system). Therefore it would be useful to be able to specify a Python binary at configure time, e.g. something like `./configure --with-python=/usr/bin/python2`.

**Comment by smimram** [comment]
I think that python is only used for `liguidsoap` which can be considered as unmaintained... Is there some other place where we need python?

**Comment by smimram** [comment]
Closing this since liguidsoap is deprecated (it's not even running at the moment).
