### ISSUE TITLE
Missing URL and Song mappings for icecast metadata updates on harbor

### ISSUE THREAD

**Issue by DaneStreeter** [savonet/liquidsoap#2676]
**Describe the bug**
 I’m working on replacing a native icecastKH implementation with and LS harbor. I’ve noted that the metadata update command on the harbor doesnt support all the KH metadata fields, namely ‘song’ and ‘url’.

An example update as so:
```
/admin/metadata?mount=/stream.mp3&mode=updinfo&song=TESTSONG&url=TESTURL
```
I know these arent used too commonly but are a key metadata driver in this instance.
Are you aware these options are missing or not mapped on the harbor?

**To Reproduce**
Sending a manual icy metadata update to the harbor such as: 
```
/admin/metadata?mount=/stream.mp3&mode=updinfo&song=TESTSONG&url=TESTURL
```
Also tested by adding a GET method on a HTTP harbor and adding the option via `settings.encoder.metadata.export.set`

The update is accepted as an option but not passed to the source. 

**Expected behavior**
'song' option to be mapped to 'title' 
'url' option to be mapped to 'metadata_url

**Version details**

- OS: [Debian]
- Version [2.1.2]

**Install method**
opam

**Comment by toots** [comment]
This should be fixed in `main` and `rolling-release-v2.1.x`.
