### ISSUE TITLE
Error 12: Unsupported format: %aacplus(bitrate=32). for windows dist

### ISSUE THREAD

**Issue by svaganov** [savonet/liquidsoap#2690]
Hello. I have problem with latest release for windows platform. 
Error 12: Unsupported format: %aacplus(bitrate=32).
You must be missing an optional dependency. Script works well on 1.4 . what library i should add ?

**Comment by toots** [comment]
Hi @svaganov ! The windows build only has the `%ffmpeg` encoder enabled because of some compilation limitations.

I have just enabled the `fdk-aac` option on ffmpeg on the rolling release windows build here: https://github.com/savonet/liquidsoap/releases/tag/rolling-release-v2.1.x

You should be able to use it this way:
```
%ffmpeg(
  format="adts",
  %audio(codec="libfdk_aac", b="32k")
)
```

**Comment by svaganov** [comment]
Hi. thank you for response. I downloaded new version 2.1.3. 

Use this 
`output.icecast(%ffmpeg(format="adts", %audio(codec="libfdk_aac", b="32k",samplerate=48000)),fallible=true, mount="test_aac", host = "localhost", port = 8000, password = "hackme", s)`

After that i have this

`2022/10/17 11:52:10 [ffmpeg.encoder.internal:2] Cannot find encoder libfdk_aac: The requested ffmpeg encoder was not found, please make sure that ffmpeg was compiled with support for it.
2022/10/17 11:52:10 [clock.main:2] Source test_aac failed while streaming: The requested ffmpeg encoder was not found, please make sure that ffmpeg was compiled with support for it!
2022/10/17 11:52:10 [main:3] Shutdown started!`

**Comment by toots** [comment]
Ha yeah, something was off with the build. It should be activated now, try the latest release: https://github.com/savonet/liquidsoap/releases/tag/rolling-release-v2.1.x

**Comment by svaganov** [comment]
Thank you !!!! It works fine
