### ISSUE TITLE
Album artwork not showing

### ISSUE THREAD

**Issue by matthewunmuted** [savonet/liquidsoap#2697]
**Describe the bug**
One of our client's album artwork is not showing for their uploaded media

**To Reproduce**
Upload any media to affected station

**Expected behavior**
Album artwork to correctly display 

**Version details**
 v0.17.1 Stable

- OS: Debian
- Version  v0.17.1 Stable

**Install method**
Docker

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/#download)

**Comment by toots** [comment]
Hi @matthewunmuted Is this issue related to liquidsoap? The reported version does not match our versions.

**Comment by matthewunmuted** [comment]
Hi toots,

Apologies, this has been submitted in error. I will close this.
