### ISSUE TITLE
smart start and stop

### ISSUE THREAD

**Issue by nesale** [savonet/liquidsoap#272]
I have 3 file of duration 2 minutes. I want to play one by one, but the first to run for 20 seconds and 98 seconds to stop and launch a the second at 15 seconds and finish his play at 105 second run third for 5 seconds and stop 116

playlist
1.mp3, start = 20., stop = 98.
2.mp3, start = 15., stop = 105
3.mp3, start = 5., stop = 116

See the principle https://youtu.be/BY-S54jdHsk

Do I need to use http://liquidsoap.fm/doc-svn/reference.html#cue_cut ? And how to separate or set for different frames (tracks) different begin/end time?

Pic 
![start stop](https://cloud.githubusercontent.com/assets/8306768/11040638/61c9d310-871e-11e5-94df-36b3b1d9844b.png)

**Comment by smimram** [comment]
Yes, the function `cue_cut` is exactly what you need. In your playlist, you can have lines such as
```
annotate:liq_cue_in="5.",liq_cue_out="15.":/path/to/file.mp3
```
and then use a script such as
```
s = playlist("/path/to/playlist")
s = cue_cut(s)
out(s)
```
The above line will play the mp3 file from second 5 to second 15 (thus lasting for 10 sec). Other examples [can be found here](http://liquidsoap.fm/doc-svn/seek.html).

I close the bug, but feel free to reopen if something is not clear or I misunderstood a point.
