### ISSUE TITLE
HLS storage paths automated created, to avoid "target directory does not exist"

### ISSUE THREAD

**Issue by cdgraff** [savonet/liquidsoap#2725]
**Is your feature request related to a problem? Please describe.**
Trying to use `output.file.hls` i got frequently 
```
Error 7: Invalid value:
The target directory does not exist
```

And I need to create them manually, but I'm trying to create subfolders level by hour, to maintain the more clean structure of TS Files

**Describe the solution you'd like**
I'll like the missing folders be create automatically when TS file try to save inside them, that way we can use dynamic paths like:

```
hlspath = ref(getenv("HLSPATH"))
if !hlspath == "" then
  hlspath := "#{storage_dir}/#{station_slug}/%Y/%m/%d/%Hh/"
end
```

**Describe alternatives you've considered**
`output.file` support that, and Originally I'm using them... but the issues with the segmentation inside that output made me force to move to hls segmenter the output files are working well (no audio missing between the files as happened inside output.file segmentation )

**Additional context**
I'm trying to create a long-term Audio Digital Archive using HLS chunks with long retention, and order to avoid recording all inside the same directory is critical.

**Comment by cdgraff** [comment]
Same situations if I try to use the new `time.string` feature

```
# Output to HLS
def segment_name(~position,~extname,stream_name) =
  timestamp = int_of_float(time())
  time.string("%Y/%m/%d/%Hh/#{timestamp}.#{extname}")
end
```
Dynamic paths works perfect, but as folder was not previously created give error:
`Source output_hls failed while streaming: Sys_error("/tmp/hls/2022/11/06/15h/1667747468.ts: No such file or directory")!`

**Comment by toots** [comment]
Fixed, thanks for reporting! It is in `rolling-release-v2.1.x` and will come out with the next stable release.

**Comment by smimram** [comment]
Reopening for a quick question: I see in your patch that you are using `Sys.mkdir`.
