### ISSUE TITLE
Liquidsoap does not close file descriptors before spawning child processes

### ISSUE THREAD

**Issue by asantoni** [savonet/liquidsoap#273]
The bug is as described in 2013 here:
https://www.mail-archive.com/savonet-devl@lists.sourceforge.net/msg01561.html

What was the eventual outcome of that bug ticket? Was it closed, or is this still an issue? 

I have the sneaky suspicion that this is still a problem. I've seen a case where Liqudisoap failed to restart after being terminated because it was unable to bind to its telnet port. It's unclear why the process restarted in the first place, but I know subprocesses are involved.

**Comment by toots** [comment]
Unfortunately, this bug needs to be fixed at the compiler's level and there does not seem to be a consensus over it as of now.. See: http://caml.inria.fr/mantis/view.php?id=5256
