### ISSUE TITLE
Sourceforge win32 zip reported as having trojans 

### ISSUE THREAD

**Issue by infixed** [savonet/liquidsoap#274]
Downloaded the precompiled liquidsoap from sourceforge via

http://skylineservers.dl.sourceforge.net/project/savonet/liquidsoap/1.0.1/liquidsoap-win32-1.0.1.zip

Ran it through virustotal.com and it reports several detentions

https://www.virustotal.com/en/file/b175543108702b3791389e6fe415826bcb09cbdaf7cd8bb274d1856712d290c8/analysis/

Comodo 	TrojWare.Win32.Agent.avef 	20150801
Jiangmin 	Trojan/Agent.btin 	20150731
Panda 	Generic Malware 	20150731
Symantec 	WS.Reputation.1 	20150801

**Comment by infixed** [comment]
The real issue is at the top of files tab on sourceforge page where it says

"Looking for the latest version? Download liquidsoap-win32-1.0.1.zip (13.5 MB) "

That's not the latest version.   There is a V1.1.1 deeper in the repository

But the one in the banner is one that gets detected as having trojans,  Andit's the libtag.dll that seems to be the culprit

**Comment by smimram** [comment]
Thanks for letting us know, I have removed the 1.0.1-win32 version from sf.net. I don't know how sf.net chooses the latest version, but hopefully it will update it.

**Comment by toots** [comment]
Wow. Damn these guys.. Will look at it as soon as possible.
