### ISSUE TITLE
Raspberry Pi: audio glitches when pushing songs through a queue

### ISSUE THREAD

**Issue by itibet** [savonet/liquidsoap#275]
Hi,
I'm testing liquidsoap on the new Raspberry Pi 2 (Raspbian), I've defined a simple script where a live input (an Internet radio) is played through output.ao and there's a queue to be played as soon as a song is pushed into it.
However, when I push a song into the queue, I can sometimes (often but not always) hear a short audio glitch a couple of seconds before the transition from the live input to the pushed song starts. Looking at the logs the glitch corresponds to the moment the decoder starts decoding the pushed song (no matter the audio format I use).
Moreover, if I push more songs into the queue to be played sequentially, the glitch sometimes (often but not always) occurs again a couple of seconds before the transition from a song to the next starts.
Is anybody experiencing something similar with the raspberry pi?
Is there any optimization I can perform?
Thanks

**Comment by vrtisworks** [comment]
I'm not sure which version of Raspbian you are running.  Liquidsoap pushes the Pi 2 pretty hard (typically I see 25%+ CPU just playing a song to alsa).  It sounds like you are either running out of CPU or memory.  If you are running the full GUI raspbian, then there are a lot of other things running, and I don't think Liquidsoap is set up with any kind of priorty.

I run Liquidsoap headless using [http://thethingbox.io/] - The THINGBOX, and it even runs pretty well even on a B+... but I don't have much else running on that system.

Nick

**Comment by itibet** [comment]
Hi,
I'm running the git version and It's not a problem of CPU, I discovered that taglib was causing the glitches: short audio loss when getting audio file id3 tags (this only happens when pushing songs through the queue). I compiled liquidsoap without taglib and the problem disappeared.
Thanks
