### ISSUE TITLE
`http.get` function response on redirect

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#2758]
**Describe the bug**

If `http.get` function will receive a redirect, then
1. the response string will contain the redirect page output;
1. the response record `status_message` property is empty.

**To Reproduce**
1. ```ruby
   a = http.get(headers=[("user-agent", "test")], 'http://ifconfig.me/all.json')
   print("#{a}")
   print(a.status_message)
   ```
1. ```ruby
   a = http.get(headers=[("user-agent", "curl")], 'http://ifconfig.me/all.json')
   print("#{a}")
   print(a.status_message)
   ```
1. ```ruby
   a = http.get('domain.invalid')
   print("#{a}")
   print(a.status_message)
   ```

**Expected behavior**

The output of the command should be

1. ```
   {
     "ip_addr": "1.1.1.1",
     "remote_host": "unavailable",
     "user_agent": "test",
     "port": 12345,
     "method": "GET",
     "mime": "*/*",
     "via": "1.1 google",
     "forwarded": "1.1.1.1, 2.2.2.2"
   }
   OK
   ```
1. ```
   {
     "ip_addr": "1.1.1.1",
     "remote_host": "unavailable",
     "user_agent": "curl",
     "port": 12345,
     "method": "GET",
     "mime": "*/*",
     "via": "1.1 google",
     "forwarded": "1.1.1.1, 2.2.2.2"
   }
   OK
   ```
1. ```
   
   Origin is unreachable
   ```

**Actual behavior**

1. ```
   Found. Redirecting to https://ifconfig.me/all.json{
     "ip_addr": "1.1.1.1",
     "remote_host": "unavailable",
     "user_agent": "test",
     "port": 12345,
     "method": "GET",
     "mime": "*/*",
     "via": "1.1 google",
     "forwarded": "1.1.1.1, 2.2.2.2"
   }
   ```
1. ```
   {
     "ip_addr": "1.1.1.1",
     "remote_host": "unavailable",
     "user_agent": "curl",
     "port": 12345,
     "method": "GET",
     "mime": "*/*",
     "via": "1.1 google",
     "forwarded": "1.1.1.1, 2.2.2.2"
   }
   OK
   ```
1. ```
   
   Origin is unreachable
   ```

**Version details**

- OS: `ubuntu:22.04` in docker
- Version: *2.0.0*-*2.1.2* and 0a3582b

**Install method**
Deb package from liquidsoap releases at github

**Common issues**
N/A

**Comment by toots** [comment]
Thanks for reporting. The body data was indeed not cleared on redirect. This is now fixed. Please note that in the first example, for some reason `libcurl` decides to go with `HTTP/2`, resulting in no `status_message`. If you force `http_version` to `"1.1"` in the call, you do get the proper `status_message`.

**Comment by vitoyucepi** [comment]
@toots, I do know why curl uses `HTTP/2`.
1. Go to http://ifconfig.me/all.json.
2. Get redirect to https://ifconfig.me/all.json.
3. Go to https://ifconfig.me/all.json.
4. Get the info that the server allows `h2` and `http/1.1`.
5. Use `HTTP/2`.

If you set the user-agent to `curl` then there will be no redirect to https.
I think curl didn't even try to use `http/2` for `http://`.
