### ISSUE TITLE
Syntax errors from included files not reported correctly

### ISSUE THREAD

**Issue by xorinzor** [savonet/liquidsoap#2775]
**Describe the bug**
When there is a syntax error in a file included via `%include`, the parser will fail on the `%include` and just say `Parse Error` rather then telling about the syntax error in the nested code.

**To Reproduce**
have 2 files:
**main.liq**
```
%include "test.liq"
-- any other code --
```

**test.liq** (notice the double `.` in the parameter)
```
def test(~test=1..) =
    test
end
```

This will return something along the lines of:
```
At main.liq, line 1, char 0-20:
%include "test.liq"

Error 2: Parse error
```

**Expected behavior**
It should report on the syntax error in `test.liq`

**Additional details**
interestingly enough, if the content of `test.liq` is set to something like:
```
invalid content
```

The parser error will say:
```
At test.liq, line 1, char 0-7:
invalid content

Error 4: Undefined variable invalid
```

**Version details**

- OS: Ubuntu 22.10
- Version 2.1.3 (docker container)

**Install method**
Docker

**Comment by toots** [comment]
Thanks for reporting. I'm happy to report that the upcoming rolling release seems to have this fixed already!
