### ISSUE TITLE
Documentation for error "records" (and deprecation of error.kind())

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#2779]
Doc still mentions using error.kind() instead of using err.kind here: https://www.liquidsoap.info/doc-2.1.2/language.html#cb85-1

Using the code from the doc on 2.1.2 fails: `Error 5: this value has no method `kind`

This is a note to check where doc is written... and update it if someone doesn’t do it before I get to it...

**Comment by toots** [comment]
Thanks for reporting! This should be fixed now.
