### ISSUE TITLE
interactive.bool cannot be switched via telnet since upgrade from 2.0.x to 2.1.x

### ISSUE THREAD

**Issue by origintopleft** [savonet/liquidsoap#2785]
**Describe the bug**
I have this interactive bool that, when set to true, triggers some graceful exit logic: `signoff_requested = interactive.bool("signoff_requested", false)`

This worked without issue in 2.0.x, but since migrating to Fedora 36 I've had a new version of OCaml available, so I moved up to 2.1.2. The issue is still present in 2.1.3.

The variable is, in fact, present via telnet and can even be read:
```
% telnet localhost 7999
... telnet preamble ...
var.list
signoff_requested : bool
END
var.get signoff_requested
false
END
```

However, when attempting to set the variable to true, as done in previous versions, I'm receiving errors:
```
% telnet localhost 7999
... telnet preamble ...
var.set signoff_requested = true
Syntax error or variable not found.
END
var.set signoff_requested = 1
Syntax error or variable not found.
END
var.set signoff_requested = yes
Syntax error or variable not found.
END
var.set signoff_requested = "true"
Syntax error or variable not found.
END
```

**To Reproduce**
`signoff_requested = interactive.bool("signoff_requested", false)`

**Expected behavior**
Expected to be set to true

**Version details**

- OS: Fedora 36
- Version 2.1.3

**Install method**
opam

**Comment by smimram** [comment]
I have just pushed a fix: we weren't removing the whitespaces around the variable and the value. In the meantime, the following should work:
```
var.set signoff_requested=1
```
(note : no space around the `=`).
