### ISSUE TITLE
Is there a way to extract metadata from input.harbor?

### ISSUE THREAD

**Issue by westjgames** [savonet/liquidsoap#279]
Been trying to pull data such as "stream name" and "stream genre" from input.harbor, but can't seem to figure it out, all I get is a (track) title.

The purpose is to output this data as JSON so that we can apply it to our website (make the site change when a live DJ is on air).

**Comment by toots** [comment]
Yes! You should look at this:

```
 * on_connect : ([(string*string)])->unit (default: fun (_) -> ())
     Function to execute when a source is connected. Its receives the list of
     headers, of the form: (<label>,<value>). All labels are lowercase.
```

The headers will contain the information that you are looking for.

**Comment by westjgames** [comment]
How would I use this? I have the idea of using:

    def geticymeta(headers)
      icymeta = json_of(headers)
    end

However, all I can see happening is that these persist after the source has disconnected.

Also, I'm not even sure if `headers` can be directly JSON encoded.
