### ISSUE TITLE
http.post.file use different variable for timeout and different defaults from the others http.post params

### ISSUE THREAD

**Issue by cdgraff** [savonet/liquidsoap#2809]
Inside `http.post` and `http.post.stream`  variable is called `timeout_ms` and has 10000 as the default

`timeout_ms (of type int?, which defaults to 10000): Timeout for network operations in milliseconds.`

Inside`http.post.file` variable is called `timeout` and is NULL as default

`timeout (of type int?, which defaults to null): Timeout in ms.`

Will be good normalize to easy and clean writing

thanks!

**Comment by toots** [comment]
Hi,

That's a great suggestion! Have you ever tried to contribute to the code? This would be an easy one to pick!
