### ISSUE TITLE
Liquidsoap keeps crashing after hours of running. 

### ISSUE THREAD

**Issue by hydrosIII** [savonet/liquidsoap#2828]
**Describe the bug**

Hi. We have a server to catch a stream from the internet and output it to  a radio transmitter. It implements Liquidsoap. It is a simple script with liquidsoap. Today it crashed several times for no apparent reason.  

The Server is Debian Bullseye with the Kernel RealTime.  Liquidsoap 2.1 version installed from package. 

The liquidsoap config: 

````
set("log.file",true)
set("log.file.path","/home/violetaradio/violeta.log")
set("log.stdout",true)
set("log.level",5)
set("frame.audio.size",1881)
set("frame.video.framerate", 0)


radio = input.http( max_buffer=30.0, "https://flujos.mazorca.org/violetaradio.mp3")

#### para detectar los silencios
def handler()
  system("/home/violetaradio/detectar-silencio.sh")
end

###### Detección de silencios en el stream manejados por la función de abajo
radio = blank.detect(handler,radio)

### manda el output a alsa
output.alsa(bufferize=true,id="alsa", mksafe(radio))

````

Liquidsoap is implemented via a sytemd service so it kept getting back up. After a lot of reboots everything began to work again.
Key lines in the logs:

````
[alsa:3] Using ALSA 1.2.4.
9 [alsa:3] channels=2, samplerate=44100Hz, buffer size=262144B, frame size=4B, periods=5826
9 [threads:3] Thread "alsa" aborts with exception Alsa error: Invalid argument!
9 [threads:4] Raised by primitive operation at Alsa in file "src/alsa.ml", line 68, characters 0-1023
9 [threads:4] Called from Alsa_out.output#get_device in file "outputs/alsa_out.ml", line 120, characters 12-37
9 [threads:4] Called from Alsa_out.output#push_block in file "outputs/alsa_out.ml", line 132, characters 16-31
9 [threads:4] Called from IoRing.output#reader in file "tools/ioRing.ml", line 191, characters 10-58
9 [threads:4] Re-raised at IoRing.output#reader in file "tools/ioRing.ml", line 215, characters 12-19
9 [threads:4] Called from Tutils.create.(fun).process in file "tools/tutils.ml", line 164, characters 12-15
9 [main:3] Shutdown started!
9 [lifecycle:5] At stage: "Liquidsoap core shutdown"
9 [main:3] Waiting for main threads to terminate...
9 [threads:4] Waiting for thread clock_alsa to shutdown
9 [input.http_0:5] Activations changed: static=[blank.detect_0:mksafe:alsa:alsa], dynamic=[].
9 [alsa:5] Activations changed: static=[], dynamic=[].
9 [source:4] Source alsa gets down.
9 [mksafe:5] Activations changed: static=[], dynamic=[].
9 [source:4] Source mksafe gets down.
9 [blank.detect_0:5] Activations changed: static=[], dynamic=[].
9 [source:4] Source blank.detect_0 gets down.
9 [input.http_0:5] Activations changed: static=[], dynamic=[].
9 [source:4] Source input.http_0 gets down.
9 [safe_blank:5] Activations changed: static=[mksafe:alsa:alsa], dynamic=[].
9 [safe_blank:5] Activations changed: static=[], dynamic=[].
9 [source:4] Source safe_blank gets down.
9 [clock.alsa:3] Streaming loop stopped.
9 [threads:4] Thread "clock_alsa" terminated (0 remaining).
9 [main:3] Main threads terminated.
9 [lifecycle:5] At stage: "Liquidsoap scheduler shutdown"
9 [threads:3] Shutting down scheduler...
9 [threads:4] Thread "non-blocking queue #1" terminated (3 remaining).
9 [threads:4] Thread "generic queue #2" terminated (2 remaining).
9 [threads:4] Thread "non-blocking queue #2" terminated (1 remaining).
input.http_0:4] Connection failed: Avutil.Error(Immediate exit requested)
4 [threads:4] Thread "generic queue #1" terminated (0 remaining).
4 [threads:3] Scheduler shut down.
4 [lifecycle:5] At stage: "Liquidsoap final cleanup"
4 [main:3] Cleaning downloaded files...
4 [main:3] Freeing memory...
e: Succeeded.
e: Consumed 1.624s CPU time.
e: Scheduled restart job, restart counter is at 2267.

````

This happened a lot of times during an hour

**Comment by hydrosIII** [comment]
Also relevant. I thinks something happens to alsa that it blocks. 
````
 [alsa:2] Trying to recover.
 [threads:3] Thread "alsa" aborts with exception Alsa error: Device or resource busy!
 [threads:4] Raised by primitive operation at Alsa.Pcm.recover in file "src/alsa.ml", line 93, characters 39-73
 [threads:4] Called from IoRing.output#reader in file "tools/ioRing.ml", line 191, characters 10-58
 [threads:4] Re-raised at IoRing.output#reader in file "tools/ioRing.ml", line 215, characters 12-19
 [threads:4] Called from Tutils.create.(fun).process in file "tools/tutils.ml", line 164, characters 12-15
````

**Comment by jkossis** [comment]
I'm seeing this exact same thing as well. For context, here is my config:

```
#!/usr/bin/liquidsoap

output.icecast(
  %mp3(bitrate=320),
  host="living-room-pi",
  port=8000,
  password="JStelers86@!*",
  mount="vinyl-streamer.mp3",
  input.alsa(
    bufferize=true,
    fallible=false,
    device="hw:1,0"
  )
)
```

**Comment by toots** [comment]
I concur. I would suggest to use `output.ao` for the output. As for input, yeah probably pulseaudio. Alsa is not my favorite sound API, it's in dire need of a rewrite.

**Comment by hydrosIII** [comment]
As for pulseaudio, I always thought tha Alsa being low level was less error prone. But ok.

**Comment by toots** [comment]
Ha that could explain the issue with alsa too @hydrosIII. If your `input.http` is from a icecast server, you're gonna run into a synchronization issue potentially.

The icecast server has its own synchronization and your sound card has a different one. Most of the time, for limited listening, you will not see an issue but, overtime, both input and output can accumulate difference in synchronization.

A couple of things that you can try:
* Yes, `output.ao` can output on the soundcard to trying a different operator can help. It's possible different implementation deal with the issue differently.
* Let the `input.http` drive the synchronization. This would be achieved this way:
```
radio = input.http( max_buffer=30.0, "https://flujos.mazorca.org/violetaradio.mp3", self_sync=true)

#### para detectar los silencios
def handler()
  system("/home/violetaradio/detectar-silencio.sh")
end

###### Detección de silencios en el stream manejados por la función de abajo
radio = blank.detect(handler,radio)

### manda el output a alsa
output.pulseaudio( mksafe(radio), clock_safe=false)
```
* Last resort, you can use the `buffer.adaptative`. This buffer will insert or remove audio samples to ensure that input and output keep being in sync:
```
radio = input.http( max_buffer=30.0, "https://flujos.mazorca.org/violetaradio.mp3")

#### para detectar los silencios
def handler()
  system("/home/violetaradio/detectar-silencio.sh")
end

###### Detección de silencios en el stream manejados por la función de abajo
radio = blank.detect(handler,radio)

radio = buffer.adaptative(radio)

### manda el output a alsa
output.pulseaudio( mksafe(radio))
```

**Comment by hydrosIII** [comment]
Well I have changed completely the config, and it is still getting out of sync. Less than a second but still. I am using your recommendations and buffer. 
I do not know if it has something to be with the mksafe function. I am passing it twice, but buffer. adaptative  does not seem to accept a fallible source, and even if a the source is not fallible I get a not fallible output. Also I update to liquidsoap 2.1.3

````
set("log.file",true)
set("log.file.path","/home/violetaradio/violeta.log")
set("log.stdout",true)
set("log.level",5)
set("root.max_latency",30.)


radio = input.http(clock_safe=true,debug=true,max_buffer=60.0, "https://flujos.mazorca.orgvioletaradio.mp3",self_sync=true)

##### dummy output to avoid piling up
output.dummy(id="dummy", fallible=true, radio)
radio = buffer.adaptative(mksafe(radio),max=40.,buffer=20.0)
radio = mksafe(radio)
output.pulseaudio(id="pulse",radio,clock_safe=false)


````

Is there a way to decouple the source  entirely maybe routing the output to a file or to another stream, before sending it to the  sound card?  I would like to pass some volume correction and compression to the stream. But now in this state it will mess up the timing. Also this is not the original bug, so maybe I can open a new issue.

**Comment by toots** [comment]
`output.dummy` should not be needed anymore but it doesn't make a lot of difference either.

`buffer.adaptative` does in fact decouple the two streams. Do you still see issues with it?

**Comment by hydrosIII** [comment]
I still have, the issues are minimal. I mean in the order of less than a second. So maybe is not a issue at all. I wonder what will happen if I add a sound processor.  Well Thanks, you can close this bug. I will open a new one if a new issue arises.

**Comment by hydrosIII** [comment]
One last question how do I use output.ao with my soundcard. Is there a manual for that?

**Comment by hydrosIII** [comment]
I am closing this, our crashes come from disconnections from the streaming server, that make liquidsoap crash in a chain reaction.
