### ISSUE TITLE
Silent failure, no output.pulse and no logs. 

### ISSUE THREAD

**Issue by hydrosIII** [savonet/liquidsoap#2845]
Hi I am running liquidsoap to receive a stream from the internet and send it to a radio transmitter.  Today I experienced a silent failure. I mean liquidsoap logs said everything was working fine. But it wasn't, there was no output and the logs were fine. This was particularly strange since we have had failures before but liquidsoap  either crashed or gave something in the  logs. 

My config. 

````

settings.path.to.key.set("log.file",true)
settings.path.to.key.set("log.file.path","/home/violetaradio/violeta.log")
settings.path.to.key.set("log.stdout",true)
settings.path.to.key.set("log.level",5)


radio = input.http(clock_safe=true,debug=true,max_buffer=60.0, "https://flujos.mazorca.org/violetaradio.mp3",>
##### dummy output to avoid piling up
output.dummy(id="dummy", fallible=true, radio)
radio = buffer.adaptative(mksafe(radio),max=60.,buffer=30.0)
#### çagain mksafe
radio = mksafe(radio)
######### limit
radio = limit(radio)

output.pulseaudio(id="pulse",radio,clock_safe=false)

set("root.max_latency",30.)

````

We got the logs with some warnings from a sincronization problem, but nothing to weird. Also the warnings are there always. 

```
[clock.main:2] We must catchup 1.14 seconds
```

**Comment by hydrosIII** [comment]
We were using output.alsa before it crashed often every hour, but it was not silent.

**Comment by hydrosIII** [comment]
Sorry: liquidsoap version 2.1.3. Debian bullseye kernel rt 6.0.0-0

**Comment by toots** [comment]
Hi,

It is the same error as https://github.com/savonet/liquidsoap/issues/2828 ? Could there be an underlying issue with your sound system that is handled differently with alsa (a crash) and pulseaudio (a silent failure)? Have you tried to reproduce the issue with another tool than liquidsoap?

**Comment by hydrosIII** [comment]
Yes, You were right, there were issues with the streaming server, we got a lot of disconnections. But maybe this should just crash liquidsoap instead of going to a silent failure.

**Comment by hydrosIII** [comment]
I am closing this issue, because I think, that it was not a liquidsoap failure, and I am suspecting a pulseaudio failure or a network error in our stream

**Comment by hydrosIII** [comment]
I have checked hardware it is fine. I have checked the pulseaudio logs at details  and I have rewinds often. So i have switches to output.ao. 

 It is true that we have a lot of network latency, it is 150ms of latency in the ping. However I would expect that liquidsoap resyncs the clocks when the latency overflows the buffers. This happens most if the of time.

But sometimes it just stales and we have to reboot liquidsoap. I am not sure if liquidsoap should be that resilient, or this is a corner case that is to difficult to handle. However, even ir it is a corner case I would expect liquidsoap to fail entirely. It does not, liquidsoap get zombified. No output, no logs, and no failure. 

My liquidsoap is ran by a systemd daemon so if it detects that liquidsoap has failed it reboots it. But if not, we lose the radio signal.

**Comment by toots** [comment]
Have you tried to use a framework better designed to deal with latency issues such as bjack?

**Comment by hydrosIII** [comment]
Closing this bug since I think it is because of this: https://github.com/savonet/liquidsoap/issues/2974 . This is more specific.
