### ISSUE TITLE
Feature request: Ability to parse YAML files

### ISSUE THREAD

**Issue by davidtrattnig** [savonet/liquidsoap#2853]
Currently we configure our play-out [engine](https://gitlab.servus.at/aura/engine-core) using `INI` files. Most other of our services are configured by `YAML` files. For consistency and ease of use we want to do the same with our Liquidsoap repository.

It would be great, if you provide such functionality or point us to an existing way of parsing `YAML` in Liquidsoap.

**Comment by davidtrattnig** [comment]
:scream_cat: wow, that was quick! lotta thanks.

**Comment by toots** [comment]
Nopb! It will have to come out with the next major release, though, so probably some time around spring.

**Comment by davidtrattnig** [comment]
That's soon enough. I will not be able to use it earlier anyway.
