### ISSUE TITLE
Looks like bpm operator is broken

### ISSUE THREAD

**Issue by rrolla** [savonet/liquidsoap#2871]
**Describe the bug**
BPM operator https://www.liquidsoap.info/doc-2.1.3/reference.html#bpm always return `0.`, looks like with some version upgrade this is broken

**To Reproduce**
```ruby

musicSource = playlist(id="musicSource", "/mnt/test/bpm")

musicSourceBpm = bpm(id="bpm", musicSource)

def detectBpm()
    metadata = musicSource.last_metadata() ?? []
    title = "#{metadata['artist']} - #{metadata['title']}"
    bpm = musicSourceBpm.bpm()
    bpmWithTitle = "BPM: #{string_of(int_of_float(bpm))} #{title}"
    print(bpmWithTitle)
end

def startDetectBpm()
    thread.run(delay=20.0, (fun() -> begin detectBpm() {} end))
end

def onMetadataHandler(metadata)
    startDetectBpm()
end

musicSource.on_metadata(onMetadataHandler)
```
returns

```ruby
BPM: 0 Dj Gollum × Empyre One - Supernova (Original Mix)
```

**Expected behavior**
after calling `detectBpm` it should return BPM instead of 0

**Version details**

- OS: Debian
- Version 2.1.3

Also checked plugins on liquidsoap installation, looks ok:
```bash
liquidsoap --list-plugins | grep bpm
 + bpm
  Detect the BPM (number of beats per minute). The returned source has a method `bpm`, which can be called to compute it.
   + bpm
 ?bpm : float?, ?ms : int?, ?hz : float?,
   set timing. (default: 2, possible values: 0 (bpm), 1 (ms), 2 (hz))
  + bpm
 ?bpm : float?, ?ms : int?, ?hz : float?,
   set timing. (default: 2, possible values: 0 (bpm), 1 (ms), 2 (hz))
  + bpm
liquidsoap --list-plugins | grep soundtouch
 + soundtouch
```

**Install method**
Via deb package [2.1.3-debian-bullseye-1_amd64.deb](https://github.com/savonet/liquidsoap/releases/download/v2.1.3/liquidsoap-dbgsym_2.1.3-debian-bullseye-1_amd64.deb)

**Other issue**
If I call bpm directly on `musicSource` instead add to new variable `musicSourceBpm`
eg
```ruby
musicSourceBpm = bpm(id="bpm", musicSource)
# instead musicSourceBpm = bpm(id="bpm", musicSource)
``` 

the metadata is stripped out from `musicSource`

**Comment by toots** [comment]
Hi,

Is the source connected to an output? You need to be actively pulling data from it to generate stats. At the very lease you should add:

```
output.dummy(musicSourceBpm)
```

I just confirmed that the operator is at least working on `main` and added a regression test for it. Please re-open if you still see an issue in your own version with an output added.

**Comment by rrolla** [comment]
> Hi,
> 
> Is the source connected to an output? You need to be actively pulling data from it to generate stats. At the very lease you should add:
> 
> ```
> output.dummy(musicSourceBpm)
> ```
> 
> I just confirmed that the operator is at least working on `main` and added a regression test for it. Please re-open if you still see an issue in your own version with an output added.

Hey @toots yes that source is connected to output, glad that you added tests, so you will suggest to try on [Rolling Release 2.1.x](https://github.com/savonet/liquidsoap/releases/tag/rolling-release-v2.1.x)?

**Comment by toots** [comment]
Confirmed also working on `2.1.x`. The reported BPM is `60.`, which is what the metronome source is set to.

**Comment by toots** [comment]
Could be that the BPM algorithm is failing on your content, tho. It will for instance report `0.` on a sine waveform or noise source.
