### ISSUE TITLE
Artist and title not updated properly when using Stereo Tool in Liquidsoap

### ISSUE THREAD

**Issue by KevanGP** [savonet/liquidsoap#2876]
**Describe the bug**
This doesn't happen all the time, when I have crossfading on it doesn't happen 80% of the time, but without crossfading it always happens. Artist and title are stuck showing the 1st played track upon starting LiquidSoap. Even after more play, the 1st is still shown in VLC and other players. This only happens with Stereo Tool on.
Could it be some sort of buffering issue? StereoTool has about a 5 second delay in audio when compared to streaming without it, not sure if that can be gotten rid of.

**To Reproduce**
```
#!/usr/bin/liquidsoap
#SetPlaylists
music1 = playlist("path to music folder")
announce = playlist("path to announce folder")
#If something goes wrong, we'll play this
security = single("path to error.mp3")
#Schedule announcements every X tracks, finish building automatic playlist
radio = rotate(weights = [1,9],[announce,music1])
#radio = crossfade(smart=true,fade_out=0.50,fade_in=0.00,duration=1.00,radio)
radio = fallback(track_sensitive = false,[(fallback([request.queue(id="request"),radio])),security])
#Add support for live streams.
live = input.harbor("live",port=8080,password="****",buffer=1.0)
auto = input.harbor("auto",port=8080,password="****",buffer=1.0)
full = fallback(track_sensitive=false, [live,auto,radio])
process = pipe(data_length=0, replay_delay=1.5, restart_on_error = true, process='path to stereo_tool_cmd_64 - - -s path to Preset.sts -q', full)
#Stream it out
output.icecast(The stream with the broken artist/title uses the process variable)
...
```

**Expected behavior**
The artist and title should update fine upon every track change.

**Version details**
Ubuntu 22.10
LiquidSoap 2.1.3

**Install method**
Opam

**Comment by toots** [comment]
Have you see this: https://www.liquidsoap.info/blog/2023-03-16-stereotool-shared-library-support/ ? We now support the plugin SDK for stereotool. Should be a much better alternative. Download is available here: https://www.thimeo.com/stereo-tool/download/

**Comment by rrolla** [comment]
> Have you see this: https://www.liquidsoap.info/blog/2023-03-16-stereotool-shared-library-support/ ? We now support the plugin SDK for stereotool. Should be a much better alternative. Download is available here: https://www.thimeo.com/stereo-tool/download/

Wow great news upcoming 🥳
