### ISSUE TITLE
Problem with clocks?

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#288]
I can't seem to manage to have clocks working. I tried almost the example from the cookbook:

```
s = sine()
clock.assign_new(id="PULSE",[output.pulseaudio(mksafe(buffer(s)))])
output.file(%mp3,"/tmp/test.mp3",s)
```

This results in

```
Error when initializing source at line 2, char 47-65: a source cannot
  belong to two clocks (wallclock_pulse[], wallclock_PULSE[]).
```

Incidentally, the `clock` shorthand is difficult to use (for other reasons):

```
s = sine()
clock(id="PULSE",output.pulseaudio(mksafe(buffer(s))))
output.file(%mp3,"/tmp/test.mp3",s)
```

results in

```
At line 2, char 6-54: This term would evaluate to a (passive) source which
  would then be dropped. This is usually the sign of a misunderstanding:
  only active sources are animated on their own; dangling passive sources
  are just dead code.
```

Am I missing anything obvious?

**Comment by dbaelde** [comment]
I guess `clock` was not meant primarily as a shorthand, but as a way to assign clocks other than at toplevel: `s = f(clock(expr))` avoids having to write `x = expr ; clock.assign_new([expr]) ; s = f(expr)`. From this viewpoint the warning is not a problem: you should only use `clock.assign_new` at toplevel. 

(I may be wrong, it's been a long time and I'm only recollecting/inventing without having checked any detail.)

**Comment by dbaelde** [comment]
For the main problem, it could be that the example from the cookbook is outdated. It makes sense only if `output.pulseaudio` does not force a specific clock on itself. This might have been the case at some point, but from what you observe (and by looking at the source code) it is not the case now. You can revert to the old behaviour using `clock_safe=false`.

The conclusion is that the cookbook is outdated.

**Comment by smimram** [comment]
Thanks I now understand... Is there an easy way to see who is using clocks without having to look at the code?

**Comment by dbaelde** [comment]
I must have almost always added a clock_safe parameter to I/O operators
that use clocks, so that's one way to know without reading the source. But
there is no more systematic way that I can think of.

On Fri, Jan 15, 2016 at 10:17 AM, Samuel Mimram <notifications@github.com>
wrote:

> Thanks I now understand... Is there an easy way to see who is using clocks
> without having to look at the code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/savonet/liquidsoap/issues/288#issuecomment-171909507>.
>



-- 
David
