### ISSUE TITLE
Audio-video stream using Liquidsoap

### ISSUE THREAD

**Issue by tinware** [savonet/liquidsoap#289]
Hi, 

I have a problem with audio-video stream to IceCast2 Server using Liquidsoap. 

Using example code with use picture in JPG format - it works!

```
s = single("/mnt/dysk1/all/test.jpg")

output.icecast(
  %ogg(%theora),
  host="localhost",
  port=8000,
  password="*****",
  mount="/test1.ogg",
  name="Test1",
  description="Testing...",
  url=" ",
  s)
```

Example code with example use audio-video in AVI format and audio-video in MP4 format and audio-video in WEBM format- did not work! 

```
s = single("/mnt/dysk1/all/test.avi")

output.icecast(
  %ogg(%theora, %vorbis),
  host="localhost",
  port=8000,
  password="*****",
  mount="/test1.ogg",
  name="Test1",
  description="Testing...",
  url=" ",
  s)
```

You receive the following error message: 

```
Invalid value at line 1, char 12-36: Could not get a valid media file of kind {audio=2;video=1;midi=0} from "/mnt/dysk1/all/test.avi".
```

Example code with example use audio-video in OGV format - did not work! 

```
s = single("/mnt/dysk1/all/test.ogv")

output.icecast(
  %ogg(%theora, %vorbis),
  host="localhost",
  port=8000,
  password="*****",
  mount="/test1.ogg",
  name="Test1",
  description="Testing...",
  url=" ",
  s)
```

You receive the following error message: 

```
notification: Speex header too small
notification: Speex header too small
notification: Speex header too small
notification: Speex header too small
```

My distribution is the Linux Raspbian. 
Liquidsoap installation from the repository

```
apt-get install liquidsoap liquidsoap-plugin-all
```

I apologize for my low level of English proficiency. Please help me.

**Comment by djp9803** [comment]
I am also having trouble on Raspbian/Jessie.  Liquidsoap is unable to detect audio in any format.  When I run "liquidsoap -r <filename>"  I either get this:
kind="{audio=0+;video=0+;midi=0+}" 
or this:
Request resolution failed

I am using version 1.1.1-7.  Any troubleshooting suggestions?

**Comment by smimram** [comment]
Do you have all gstreamer plugins installed?

**Comment by smimram** [comment]
Closing for lack of answer from submitter, please reopen if needed.
