### ISSUE TITLE
Question - harbour on_connect / on_disconnect function - send source variable to function?

### ISSUE THREAD

**Issue by S54B32** [savonet/liquidsoap#290]
Hi all,

I'm having difficulty trying to write a function which can be used for multiple harbor sources. What I would like to send the source name back to the function, so I can use a single function to log when a source connects/disconnects and takes the source name and writes this to a log.

Effectively I'd like this:
```
def source_connect($SOURCE) =
	log($SOURCE ^ " input started!")
end
```

Or, if possible, I'd really like a single function to be used for multiple sources on both disconnect and connect, effectively this:
```
def source_connect($SOURCE, $STATUS) =
	log($SOURCE ^ " input" ^  $STATUS)
end
```

I am struggling to send the source name back to the function, does anyone have any advice with this at all? It would be most gratefully received.

Thanks

**Comment by smimram** [comment]
I am not sure I understand exactly your question by you can define
```
def source_connect(status, source)
  log(source ^ " input" ^ status)
end
```
and then pass `source_connect("started!")` as an argument (notice that you specify status, but source is still and argument for the function).

**Comment by S54B32** [comment]
Thank you very much for this, Samuel.

This just what I needed to get started writing some more advanced functions. Could you please tell me how I can pass  source_connect("started!") as an argument ?

For example in my harbor point I have input.harbor(on_connect=source_connect("started!"), ....) - but I can't figure out how I can pass the arguments back to the function.

Any more advice would be massively appreciated, thanks.

**Comment by S54B32** [comment]
Looking at this further I have managed to get the headers passed back to the function, but I still cannot see how I can either extract or pass the source ID back to the function :-(

**Comment by smimram** [comment]
Could you please copy the relevant parts of your code and explain more precisely what you want to achieve?

**Comment by S54B32** [comment]
Sorry for not making myself clearer in my initial post.

What I would like to achieve is to have a single function, which takes two arguments, the source name or source ID and the source status (if it's connected or disconnected) and then logs these arguments to a log file.

I would like to call this function using input.harbor on_connect and on_disconnect. When the function is called I'd like to write out to a separate log file the source ID and the status. So when a harbor source connects I write to a log:
$SOURCE $STATUS
which could be
harbor1 connected
or perhaps
harbor4 disconnected


This would allow me to drastically simplify my code but I cannot see any method of passing the source name/id and the status(connection/disconnection) back to a function.

Thank you for your time

**Comment by smimram** [comment]
Hi,

In this case, I think the simpler thing to do is something like that:
```
def source_connect(source, status)
  log(source ^ " input " ^ status)
end

def harbor_log(id, mountpoint)
  input.harbor(id=id,
    on_connect=fun (_) -> source_connect(id,"started"),
    on_disconnect=fun () -> source_connect(id,"stopped"),
    mountpoint)
end

s1 = harbor_log("harbor1", "/h1")
s2 = harbor_log("harbor2", "/h2")
output.dummy(s1)
output.dummy(s2)
```
Is it more or less what you expected?

**Comment by S54B32** [comment]
I think this will achieve what I would like, thank you very much.

I haven't had a chance to test this but will spend some time with this over the weekend.

Thank you again, smimram!

**Comment by S54B32** [comment]
Hi Samuel, I have run some basic tests using your code and I am incredibly pleased to say that it works!

This is a very very useful snippet for me as it means I can vastly simplify my code.

Thank you again very much, it is very much appreciated :grinning:

**Comment by smimram** [comment]
My pleasure :)
