### ISSUE TITLE
Documentation navigation bug

### ISSUE THREAD

**Issue by mbalandis** [savonet/liquidsoap#2905]
Hi. This is trivial but annoying when trying to get to latest stable version and have to manually edit the URL. At some point in last 2 weeks it broke. I couldn't find in the repo where the issue is to make a PR to contribute.

**Describe the bug**

- Navigation is broken for 4 versions: 
![Liquidsoap 2023-02-17 at 9 01 17 am](https://user-images.githubusercontent.com/18264973/219600999-52ff4476-b48e-48f3-be27-c71e242e42c9.png)

**To Reproduce**

- Go to URL: https://www.liquidsoap.info/doc-2.1.3/ 
- Click on the navigation button that says 2.1.2 2.1.3 or 2.0.0 2.1.1

**Expected behavior**

See each row with individual versions and when clicking it would go to the version.

**Version details**

- N/A

**Install method**
- N/A

**Common issues**
- N/A

**Comment by toots** [comment]
This is fixed now, thanks for reporting.
