### ISSUE TITLE
Problem fallback

### ISSUE THREAD

**Issue by avideau** [savonet/liquidsoap#291]
Hello, 

I want to liquidsoap switch sources with the title of a file.

For example:

```
If meta ['title'] == "Advert" then
fallback ([advert, s])
end
```

But the problem is that I can not recover the file title, this is a week that I try to find a
solution on the internet and reading the doc but its not working.

Can you help me ?

Thanks

**Comment by smimram** [comment]
You should use the [`on_metadata`](https://www.liquidsoap.info/doc-dev/reference.html#on_metadata) function in order to be informed of metadata, set a reference and then use an appropriate [`switch`](https://www.liquidsoap.info/doc-dev/reference.html#switch).
