### ISSUE TITLE
input.http cuts URL after '?'

### ISSUE THREAD

**Issue by prayerslayer** [savonet/liquidsoap#292]
I’m trying to figure out how I could combine multiple streams from soundcloud into a single liquidsoap/icecast2 stream. Anyways what I noticed is that `input.http` cuts the URL after `?`.

I run this:

    liquidsoap -v --debug 'output.alsa(device="pcm.liquidsoap", input.http("http://ec-media.sndcdn.com/I6pvB8Sdinkn.128.mp3?<long random string>"), fallible=true)'

And in the logs the random string is missing and you get in fact a 403 if you leave it out.

~~~
2016/01/29 23:26:40 [http_6041:4] Connecting to <http://ec-media.sndcdn.com:80/I6pvB8Sdinkn.128.mp3?>...
2016/01/29 23:26:40 [http_6041:4] Content-type "text/html".
2016/01/29 23:26:41 [http_6041:4] Could not get file: Forbidden
2016/01/29 23:26:41 [http_6041:4] Connection failed: Internal http error.
~~~

And also if I use the https URL, I get an invalid URL exception:

~~~
liquidsoap -v --debug 'output.alsa(device="pcm.liquidsoap", input.http("https://google.com"), fallible=true)'
> Invalid value at line 1, char 49-68: invalid URL.
~~~

I’m running `1.1.1` on Raspbian Jessie, so maybe this is fixed in `1.2.0`.

**Comment by smimram** [comment]
I believe that this is fixed in 1.2.0, see bug #262. I tried your script with 1.2.0 and got
```
2016/02/14 20:40:11 [http_7847:4] Connecting to <http://ec-media.sndcdn.com:80/I6pvB8Sdinkn.128.mp3?<long random string>>...
```
