### ISSUE TITLE
Unexpected high peak memory usage when using remote urls in a playlist

### ISSUE THREAD

**Issue by 5chulzi** [savonet/liquidsoap#2935]
**Describe the bug**
Using remote urls in a playlist seems to cause a short high memory usage when a file is being (down-) loaded. A file of size 300 MB causes Liquidsoap to consume around 1 GiB of memory for a short period. Only after some time it drops down to around 100 MiB and slowly rising up to approximately the size of the file (which is expected). For a file of size 60 MB it rises up to around 500 MiB of memory usage.

When the files are read from a local disk instead, the high peak does not occur.

**To Reproduce**
This is the config being used:

```
log.stdout.set(true)
settings.log.level.set(4)
settings.server.telnet.set(true)

s = playlist("/app/playlist.txt", mode="normal", reload_mode="watch")
s = fallback(track_sensitive=false, [s, blank()])


output.icecast(
  %ffmpeg(format="mp3", %audio(codec="libmp3lame", b="128k", samplerate=44100)),
  fallible=true,
  mount="/path/to/mount",
  host="localhost", port=9090, password="source", name="source", url="localhost",
  s)
```

Playlist:

```
annotate:title="Title 1",artist="Artist 1":/app/music/localfile.mp3
annotate:title="Title 1",artist="Artist 1":https://origin/some/remote/file.mp3
```

**Expected behavior**
Expecting the same behavior that occurs when using local files.

**Version details**

- OS: Docker
- Version 2.1.3

**Install method**
Using docker-compose and docker image from https://hub.docker.com/r/savonet/liquidsoap.

**Comment by toots** [comment]
Fixed in 1cb591b934dde2b54e3e1f9214f9c3239c5851b1 and `v2.1.4` thanks!!!
