### ISSUE TITLE
audio.amplify not registered

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#2936]
**Describe the bug**
I've been getting this error on the latest git hub code - 16:10 UTC

```
At /home/ubuntu/.opam/4.14.0/share/liquidsoap-lang/libs/audio.liq, line 17, char 33-60:
def amplify(~id=null("amplify"), %argsof(audio.amplify[!id]), f, s) =

Error 3: Builtin audio.amplify is not registered!
```

**To Reproduce**
```
s = sine(440.)

s = amplify(s)

output.dummy(s)
```

**Version details**

- OS: [e.g. Debian, OSX] - ubuntu 20.04 
- Version [e.g. `1.3.4`] - 2.2.0 - github main (2/3/23)

**Install method**
Did you install via `opam`? Using your distribution's packages? From source? opam

**Comment by smimram** [comment]
It seems that you don't have the latest version of the library... Could you make sure that this is the case?

**Comment by Russsgithub** [comment]
@smimram 

I have run

```
git pull
```
in liquidsoap dir
and 
```
opam reinstall liquidsoap
```
which has recompiled lang, libs, js and liquidsoap.

I can confirm this fixed it. Sorry, I must have done something wrong in updating to the latest code.

Thanks
