### ISSUE TITLE
Use HLS url as source

### ISSUE THREAD

**Issue by maurodelazeri** [savonet/liquidsoap#295]
I have a HLS url with audio from mobile, how can I connect it with the liquidsoap?

**Comment by S54B32** [comment]
This may be of interest if you've not already seen it:
https://github.com/d-a-n/liquidsoap-hls/blob/master/hls.liq

**Comment by smimram** [comment]
The most simple way is to use `gstreamer.hls("http://hls.source.com")`.

**Comment by smimram** [comment]
Client and server HLS is now implemented in trunk.
