### ISSUE TITLE
Implement HLS streaming protocol

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#296]
As client first and as server perhaps..

Protocol specs: https://tools.ietf.org/html/draft-pantos-http-live-streaming-18

**Comment by toots** [comment]
Would fix #295

**Comment by S54B32** [comment]
I'd be really interested to see a HLS implementation in Liquidsoap, particularly the server side and chunking aspect :+1: 

There is a method here that uses FFMpeg:
https://github.com/d-a-n/liquidsoap-hls/blob/master/hls.liq

**Comment by mkpascal** [comment]
Another good implementation of server HLS using avconv: https://github.com/akerbis/shoutcast2hls/blob/master/shoutcast2hls.sh

**Comment by maurodelazeri** [comment]
How should I use ?

https://github.com/savonet/liquidsoap/blob/master/scripts/gstreamer.liq

**Comment by maurodelazeri** [comment]
I have a HLS url, I want to use as source

**Comment by smimram** [comment]
As you would expect:
```
s = gstreamer.hls("http://my.url.com/hls")
output.alsa(s)
```

**Comment by maurodelazeri** [comment]
The problem I have is when I try to use the following:
At line 20, char 20: the variable gstreamer.hls used here has not been

I saw (below) that it is a common problem, but I really did not understand why I should declare a variable if it is a function

http://blog.svnlabs.com/liquidsoap-gstreamer/

what should I do @smimram ?

**Comment by smimram** [comment]
Do you have support for GSteramer? How did you install Liquidsoap? What is your version of Liquidsoap? What is your environment?

The GStreamer-related functions are only enabled if Liquidsoap was compiled with GStreamer support.

**Comment by maurodelazeri** [comment]
you are right @smimram I forgot some packages, but I fix it
I have the last version of liquidsoap

My conf is something like it

s = gstreamer.hls("http://52.27.167.120:5080/live/stream1.m3u8")

security = single("/home/ubuntu/live/fallback.mp3")
radio = fallback(track_sensitive=false, [s,security])

output.icecast(%mp3,
  icy_metadata = "false",
  host = "127.0.0.1", port = 80,
  password = "test", mount = "test",
  radio)

I can play http://52.27.167.120:5080/live/stream1.m3u8 but liquidsoap always is using my fallback

With gstreamer.hls could I use m3u8 sources ?

**Comment by smimram** [comment]
Client and server HLS is now implemented in trunk.
