### ISSUE TITLE
Implement pipe operator

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#297]
Pipe/process data through an external process' `stdin/stdout`

**Comment by toots** [comment]
cc/ @gilou

**Comment by toots** [comment]
I thought you were interested @smimram :-)

**Comment by smimram** [comment]
I am, but I won't decently have time for that in a short future...

**Comment by toots** [comment]
Fixed in b0d28f6

**Comment by attilagyorffy** [comment]
Is there an example somewhere on how to use the new pipe operator? I'd like to pass a harbor input through a stereotool processing before it would reach a shoutcast output. Where can I find an example of this? Thanks for your hard work.

/CC @toots

**Comment by toots** [comment]
Hi!

Would love to help. Can you describe what you are trying to achieve?

**Comment by attilagyorffy** [comment]
@toots Thank you :) I'm trying to achieve server-side DSP using stereo tool. I have an `input.harbor` and an `output.shoutcast` that uses `%fdkaac` encoding. in between i'd like to add the signal processing using stdin and stdout.

This is just a mere guess but I guess I'd need to decode the source stream that reaches `input.harbor` to a raw PCM, then pipe it to a linux process (stereo tool) and then somehow pipe that to the output using `%fdkaac` encoding. I'm looking for an example how to achieve this using the new pipe options, similar to the examples in the [docs](http://liquidsoap.fm/doc-svn/external_encoders.html).

Thanks in advance.

**Comment by toots** [comment]
Hi,

I've seen your email in the mailing list, will respond there.

2017-01-04 19:22 GMT-06:00 Attila Györffy <notifications@github.com>:

**Comment by attilagyorffy** [comment]
@toots Thank you. \o/
