### ISSUE TITLE
Playlist question. Using loop argument.

### ISSUE THREAD

**Issue by exlexv** [savonet/liquidsoap#2986]
Hello there! I'm using the latest version of Liquidsoap. The goal I want to achieve is:

I have a playlist file of 10 tracks (one album). And i want it to be played every day starting at 12am. So all 10 tracks from one to ten and then switch to main source. In my script I have something like this: 

`...`
`onealbum = playlist(mode="normal", reload=43200, reload_mode="seconds", loop=false, "/radio/playlist-onealbum.m3u")`
`onealbumjingle = playlist(mode="normal",  reload=43200, reload_mode="seconds", loop=false, "/radio/jingles/onealbum")`
`onealbum = rotate(weights = [1, 3],[onealbumjingle, onealbum])`

and I put it into my dayshift program:

`dayshift = fallback([ switch([({ 12h-13h15 }, onealbum),dayshift])`

So it plays from 12 till the last track and then dayshift continues. But the loop=false, so it won't play the next day, right? 

If i drop the "loop=false" then the remaining time (12h-13h15) would be filled with repeated songs from the album. If i specify the switch (12h-13h15) to accommodate the duration of the onealbum, it would mess up with other different albums I am going to put into the playlist file.

How to make it play every day starting at 12 from the very first track till the last one and then drop to the main source?  

Thank you

**Comment by oranjebloom** [comment]
I may be wrong about this, but it's my understanding that `loop=false `only works with `reload_mode="watch"`.
I don't think you can use `loop=false` together with `reload_mode="seconds"` like you are trying to do. It won't work. 

I am doing something similar to you. Instead, I use `thread.run`... like like I am doing below and set it to reload the playlist maybe an hour before it is set to play (like 11:00). It will then be reloaded and wait until it is scheduled to play at 12:00.

```
SOURCE1 = playlist(mode="normal", reload_mode="watch", reload=0, loop=false, "path/to/playlist")
thread.run(every=60., fun()-> begin d={11h00m};if (d()) then SOURCE1.reload() end end) 
```

**Comment by exlexv** [comment]
Nice execution. I have waited for `onealbum = playlist(mode="normal", reload=43200, reload_mode="seconds", loop=false, "/radio/playlist-onealbum.m3u")` to take effect for the second run and it worked! But your method seems better: to reload at specific time. I'll try it. Thank you.

My concern was that if I use `loop=false` then regardless of reload options it wouldn't play again like ever))

**Comment by oranjebloom** [comment]
Yeah, I think that's the the whole point of loop=false. It was created as a replacement for the obsolete `playlist_once ` which only played tracks once time. Glad you figured out how to reload the playlist.
