### ISSUE TITLE
Buffer overrun when reconnecting

### ISSUE THREAD

**Issue by ESPONI** [savonet/liquidsoap#299]
```
# Failover
fo = single("_Audio/1.mp3")

# A HTTP input, a Icecast stream
live = input.http("http://radiogestion.com:7005/mount5") 

# fallback
stream = fallback(track_sensitive=false, [ strip_blank(max_blank=5., live), fo ])

# An output to the local soundcard
output.ao(fallible=true, stream)
```

**To reproduce:**
Everything is ok and playing the stream, then force your internet connection to fail, and the fallback plays ok, then turn your connection on again and the sound drops, the Buffer overrun is shown.

**Comment by S54B32** [comment]
Try adding a output.dummy in your script for your HTTP input source. Add:

output.dummy(fallible=true, live)

Or if it's your output.ao that is suffering overruns then try putting the input.http and output.ao in different clocks

**Comment by ESPONI** [comment]
We will try to use different clocks because dummy output overruns too.
Thanks, I will let you know!

**Comment by ESPONI** [comment]
Could you please advise us?

We are trying to asing different clocks, reading API and Cookbook examples and getting this error:
(...) clock.assign_new(sync=false,[source])
Error: A source cannot belong to two clocks (wallclock_ao[], wallclock_output.icecast_4954[]).

**Comment by S54B32** [comment]
One way around this is to apply a buffer operator to the source.
 clock.assign_new(sync=false,[buffer(source)])

You might want to adjust the default values like so (1s with max of 2s buffer, for example):
buffer(buffer=1.0, max=2.0, source)
