### ISSUE TITLE
Source ID does not return ID that was set with map.metadata

### ISSUE THREAD

**Issue by icedream** [savonet/liquidsoap#2996]
**Describe the bug**
When `map.metadata` is called with an explicit ID to set via the `id` parameter for a source `s`, that ID is later not the one returned for `s.id` calls for the same source.

**To Reproduce**
Reproduction repository with script and Dockerfile: https://github.com/icedream/repro-liquidsoap-sourceid
For completeness sake, here's the script as well:

```rb
def setup_http(s) =
    id = s.id()

    def on_http_get(_) =
        http.response(status_code=200)
    end

    harbor.http.register.simple(port=8080, method="GET", "/#{id}/test", on_http_get)

    s
end

# just an example source
s = sine()

def example_meta(_) =
    [
        ("test", "Some test metadata"),
    ]
end

# this should set the new source id for s to main
s = metadata.map(id="main", example_meta, s)

# should set up /main/test but the log says /source_0/test is set up instead
s = setup_http(s)

output.dummy(s)
```

The log output will contain a line like this:

```
2023/04/08 07:15:48 [harbor:3] Adding handler for 'GET ^/source_0/test$' on port 8080
```

**Expected behavior**
The `s.id` call in above code should return `main`, and the above code should as a result of that set up the HTTP handler for `/main/test` instead.

**Version details**
- OS: Debian 11 or Arch Linux, happens on both
- Version rolling-release-v2.2.x

**Install method**
The Docker image `savonet/liquidsoap-ci-build:rolling-release-v2.2.x@sha256:4cee43e436f6dff60e77273a5608686991f0703d2763fae1c6131e7fdb0886ad` was used to run the script above.

**Comment by toots** [comment]
Thanks for this report. The source ID assignment has been overdue for some cleanup in a while, I'll get to it shortly.
