### ISSUE TITLE
High memory usage when delaying a stream

### ISSUE THREAD

**Issue by CGenie** [savonet/liquidsoap#2998]
Hello,

**Describe the bug**

I experience high memory usage when using `buffer` to delay a stream.

**To Reproduce**

My script looks roughly like this:
```liquidsoap
  s = mksafe(input.http(station.url))
  delayed = buffer(buffer=3600., max=4000., s)
  
  # Output
  output.icecast(
      %mp3(),
      host=az.host,
      port=az.port,
      user=az.user,
      password=az.password,
      mount=az.mount,
      mksafe(delayed))
```

**Expected behavior**

I need to delay a stream by 1 hour because of timezone difference. It takes around 5.6 Gb after the script runs for some time.

Even 1 hour of wav file at 44.1kHz and 16-bit 2-chan stereo is only 635 Mb! https://www.colincrawley.com/audio-file-size-calculator/

**Version details**

- OS: Ubuntu 22.04.2 LTS
- Version: 2.1.3

**Install method**

Official Ubuntu packages.

**Comment by ly5y** [comment]
Hey,
I am observing similar memory usage on the delayed for 1 hour live streams using the same method. With two streams, no errors, disconnects, failures of any sort - streams can lock up to 6.2Gb of RAM each. I can see the method used in this thread has been discussed in details here: https://github.com/savonet/liquidsoap/issues/832, however in my case, discussed RAM footprint is significantly higher.
Observed high RAM usage is irrespective of the startup method: tmux or systemd process.

Leaving reasoning behind, in theory and assuming linear RAM requirements, for 12h delayed stream one would need to reserve north of 60 GB of physical RAM.

Is there a better option to handle live streams for targeting different timezones?
Kind Regards,

**Comment by toots** [comment]
Hi all,

This is a pretty new request and one that certainly isn't the intended use of the original operator. I believe that the high memory usage is probably putting the garbage collector under a lot of stress, at least.

I'm thinking of other ways to support this, perhaps with a new operator. Will keep y'all posted.

**Comment by CGenie** [comment]
I understand that this might be a bit of an abuse of the `buffer` operator. However, the comment

https://github.com/savonet/liquidsoap/issues/832#issuecomment-502086922

suggested that it would take around 650 Mb of RAM which I would be in with.

On the other hand, I much prefer delaying in memory than in disk, as keeping temporary streams in files opens a new can of worms (surviving restarts,cleaning the files up, rotating them etc).

**Comment by toots** [comment]
So, the large memory usage is most likely due to the fact that we in fact store data internally using OCaml's native `float`, which is 64 bit integer so you're  looking at ~1.27 Gb in fact.

It is perhaps something to think about for future improvements with our buffers.

The other issue here is that `buffer` is an old operator that was originally introduced to create a buffer between clocks. It's been used a lot recently to do what most people expect, i.e. a buffer in the same clock, but that's not how it's supposed to work.

I am working on a simpler buffer that would be in the same clock and could be used for this kind of purpose. We are planning a rewrite of the clocks with version `2.3.x`  so this new buffer could eventually become the `buffer`. I'll push something when I have tested it more and also found a good name.

Meanwhile, I would suggest to try and keep the data encoded while buffering it. Something like this should suffice:

```liquidsoap
  s = input.http(station.url)
  delayed = buffer(buffer=3600., max=4000., s)

  delayed = ffmpeg.decode.audio(delayed)
  
  # Output
  output.icecast(
      %mp3(),
      host=az.host,
      port=az.port,
      user=az.user,
      password=az.password,
      mount=az.mount,
      mksafe(delayed))
```

**Comment by CGenie** [comment]
Helo, thank you for this suggestions, it seems memory usage droped to around 0.5 GB which is much better!

**Comment by toots** [comment]
Great. I was wrong on memory size, float 64 is actually 8 bytes so, for 3600s in stereo, you get a staggering.. `2.54 GB`.. I'm thinking of ways to remedy that.

**Comment by ly5y** [comment]
Hey,
I just wonder the math here. 3600s buffer of a stereo stream shows 5.2Gb after one hour and has a linear growth until it reaches 6.2Gb in a week or so. How does it translate to mentioned `2.54 GB`? Is it for one channel?
Kind Regards,

**Comment by toots** [comment]
> Hey, I just wonder the math here. 3600s buffer of a stereo stream shows 5.2Gb after one hour and has a linear growth until it reaches 6.2Gb in a week or so. How does it translate to mentioned `2.54 GB`? Is it for one channel? Kind Regards,

That's the basic memory consumption for the data alone, there could be other overhead due to OCaml boxing, the structure that wraps around the buffers etc.

**Comment by ly5y** [comment]
@toots - What would be the best way to build a deb package containing pool request https://github.com/savonet/liquidsoap/pull/3008? Is there a template to follow? The official documentation is a bit too generic w/r to dependencies on newer distro version like Ubuntu 22.04 >.

**Comment by toots** [comment]
The PR has been merged. Will close this one for now, please re-open if the changes do not help. I plan on following up with a longer doc/blog post about memory management in liq.

**Comment by toots** [comment]
Forgot to say: the rolling release build of v2.2x with this should also be coming up soon.

**Comment by toots** [comment]
I think that there's a design issue with the OCaml garbage collection for that kind of use-case. I reported this to them: https://github.com/ocaml/ocaml/issues/12228

I'll be thinking of a workaround if I can find one.

**Comment by ly5y** [comment]
I appreciate the effort and I wonder if there is some roadmap or perhaps planning for this stream delaying thread. For most of the time I'm on the ropes about to throw a towel...

**Comment by toots** [comment]
Hi. I understand. This is a tricky corner for us as well. I've been working on a dedicated operator for this. Any chance you could test it? The PR is here: https://github.com/savonet/liquidsoap/pull/3136

Syntax:

```liquidsoap
  s = mksafe(input.http(station.url))
  
  let { audio = a, ...tracks } = source.tracks(s)
  a = track.audio.defer(delay=3570., a) # optional: overhead=430.

  delayed = source({
    audio = a,
    metadata = track.metadata(a),
    track_marks = track.track_marks(a)
  })
  
  # Output
  output.icecast(
      %ffmpeg(format="mp3", %audio(pcm_s16, codec="libshine")),
      host=az.host,
      port=az.port,
      user=az.user,
      password=az.password,
      mount=az.mount,
      mksafe(delayed))
```

**Comment by ly5y** [comment]
Hey. Using PR #3136 is a massive improvement. For the past 24h, with one hour defer, the stream barely uses CPU and stays for most of the times on 3.9% occasionally shifts to 4.5% and there is not stutter. RAM usage went up to 1.05Gb and also stays at this level. I will test 12h defer and share the result.
Kind Regards

**Comment by toots** [comment]
Great thanks. I'll clean this up and will merge it then.

**Comment by ly5y** [comment]
The 12h deferred stream so has grown to 7.5Gb RAM and CPU stays steady at 31%.
The 1h deferred stream holds it's ground at 1.05Gb RAM and under 4% CPU.
No stutter and both reconnect right away when purposely stopped destination.
This is in all terms remarkable achievement.

Not pushing my luck - when #3136 and dependencies are expected to be pushed to the rolling release?
Kind Regards.

**Comment by toots** [comment]
Great! I'd like to give is a little more time for experimenting with it. Typically, the CPU should be the same with 1 or 12h, I'm gonna investigate that. You can expect it to land fairly soon (a week or so) and be included in the next stable release.

**Comment by ly5y** [comment]
Thanks! Let me know if you need some testing done.
This whole set pcm_xx and defer is asking for an elaborate documentation. Quite an effort went into the the solution.
Kind Regards.

**Comment by toots** [comment]
I haven't forgotten about this, will resume shortly and get it in in time for the imminent release!

**Comment by toots** [comment]
> Thanks! Let me know if you need some testing done. This whole set pcm_xx and defer is asking for an elaborate documentation. Quite an effort went into the the solution. Kind Regards.

The PR is merged now and, yes, I will add some documentation.
