### ISSUE TITLE
strip_blank to start off as blank

### ISSUE THREAD

**Issue by StudentSA** [savonet/liquidsoap#301]
Hi, 

This may be more of a feature request. 
Is it possible to have strip_blank behave in such away that when liquidsoap starts up, the source is considered as "failed"/"blank". 
In this way, connection to output.icecast (for eg) wont occur on script startup if the source is blank and will only connect when noise is detected.

**Comment by cohibo** [comment]
I need this function in my liquidsoap. I've liquidsoap 1.2.2 installed using OPAM, but it tells me that strip_blank function have no start_blank parameter. How can I resolve?
