### ISSUE TITLE
Usage - Apply on_blank or other function only when source is up

### ISSUE THREAD

**Issue by S54B32** [savonet/liquidsoap#302]
I'm trying to apply an `on_blank` function to a harbor which does what I need it to do (basic logging of when a harbor is silent or not)

However, when the source disconnects, I get many errors:

```
2016/02/18 12:43:10 [on_blank_5782:3] Warning: #get called when not #is_ready! This is normal if an operator using this source has been unused while the source has gone unavailable. If unsure about this warning, you are very welcome to report it and ask for clarifications.
```

What I cannot seem to accomplish, is to only apply the function if the harbor is available.

I've tried writing an if statement using source.is_up but it doesn't seem to work for me. So then I tried  the very basics, writing an if statement, basically:

```
if source.is_up(myharbor) then 
log("It's up!")
end
```

But I never seem to get any log entries when the source is up. Am I using source.is_up incorrectly? I cannot see why the simple above statement would not work?

Any advice is gratefully received, thank you.

**Comment by S54B32** [comment]
After further investigation it seems that if I try to apply strip_blank to a source which has on_blank applied I get the error.

If I just use on_blank it's fine. How can I use the two in tandem? If I apply strip_blank before on_blank it means that the on_blank function will never be executed as there won't ever be blank to detect!

Thanks

**Comment by S54B32** [comment]
Does anyone have any advice on this? I still cannot only specify to run the strip_blank on a source which can be removed (harbor)

I've tried adding some basic logging to see if I can even test if the harbor is working but it doesn't seem to produce any log whatsoever.

if source.is_ready(harbor) == true then log("********* READY *********") else log ("************ NOT READY *******") end

if source.is_up(harbor) == true then log("********** UP *********") else log("********* NOT UP *********") end


Neither of the above lines log anything so I'm wondering if I'm missing something?

I've also tried:

source = if source.is_ready(harbor) then strip_blank(track_sensitive=false, max_blank=SILENCE.DURATION, min_noise=NOISE.DURATION, threshold=SILENCE.LEVEL, silence_setup(harbor, MOUNT)) else harbor end


Any advice on how I can possibly only apply strip_blank when the source is available would be appreciated.

Thanks

**Comment by giflw** [comment]
As I can see, that's the expected behaviour. `strip_blank` should "Make the source unavailable when it is streaming blank.", not when it is disconected. What you trying to accomplish?

**Comment by S54B32** [comment]
Thanks for your reply.

I'm trying to write a script with a harbor input and a backup file.

I would like to do some silence detection on the harbor - if the harbor disconnects then the on_blank function I have implemented generates massive amounts of log entries (like 10-30 per second) with the following error:
```
2016/02/18 12:43:10 [on_blank_5782:3] Warning: #get called when not #is_ready! This is normal if an operator using this source has been unused while the source has gone unavailable. If unsure about this warning, you are very welcome to report it and ask for clarifications.
```

If I add a fallback of blank to the harbor, the errors stop but it means that I end up calling my silence function when the harbor disconnects as it falls back to blank().

What I would like to is apply the on_blank to the harbor without generating massive amounts of logs when the harbor disconnects.

I have tried using if statements but I can't seem to even get a basic log entry using source.is_up and source.is_ready:
```
if source.is_up(s) then log("it's up!")
if source.is_ready(s) then log("it's up!")
```

Am I missing something here?

Thanks

**Comment by giflw** [comment]
Have you tried using rotate, switch or fallback? Maybe one of them be more suitable to your needs.

**Comment by giflw** [comment]
About your ifs, have you tried to use `on_(dis)connect` callbacks in `input.harbor`?

**Comment by smimram** [comment]
This issue is quite old and some solutions were proposed. Please reopen if the problem persists.
