### ISSUE TITLE
`%external` encoder fails to start

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3020]
**Describe the bug**

#### 2.0.7
`output.icecast(%external)` starts and works good.
Liquidsoap can't properly terminate the child processes.
Requires *SIGKILL* to terminate.

#### 2.1.4, 2.2.0+git
`output.icecast(%external)` doesn't start and throws exception.
Liquidsoap doesn't start and can't terminate itself.
Requires *SIGKILL* to terminate.

<details>
<summary>Log</summary>

```
2023/04/23 12:09:41 [clock.main:2] Source radio failed while streaming: Invalid_argument("option is None")!
2023/04/23 12:09:41 [clock.main:2] Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
2023/04/23 12:09:41 [clock.main:2] Called from Stdlib__Option.get in file "option.ml" (inlined), line 21, characters 41-69
2023/04/23 12:09:41 [clock.main:2] Called from External_encoder.encoder.encode in file "src/core/encoder/external_encoder.ml", line 115, characters 24-44
2023/04/23 12:09:41 [clock.main:2] Called from Output.encoded#send_frame.output_chunks.f in file "src/core/outputs/output.ml", line 235, characters 21-59
2023/04/23 12:09:41 [clock.main:2] Called from Output.output#output in file "src/core/outputs/output.ml", line 174, characters 10-35
2023/04/23 12:09:41 [clock.main:2] Called from Clock.MkClock.clock#end_tick.(fun) in file "src/core/clock.ml", line 305, characters 16-24
```

</details>

**To Reproduce**

<details>
<summary>Liquidsoap config</summary>

```ruby
encoder = %external(process="lame - -")
output.icecast(
  encoder,
  sine(),
  format = "audio/mpeg",
  host = "icecast",
  port = 8000,
  user = "source",
  password = "hackme",
  mount = "radio"
)
```

</details>

**Expected behavior**

**Version details**
 - OS: `ubuntu:22.04` in docker
 - Version: *2.1.4*, *2.2.0+git@1c17b384a*

**Install method**
Deb package from liquidsoap releases at github

**Common issues**
#3019

**Comment by toots** [comment]
Thanks for reporting. this should be fixed now.
