### ISSUE TITLE
request.dynamic retry_delay value not used

### ISSUE THREAD

**Issue by danbo** [savonet/liquidsoap#3026]
**Describe the bug**
The value I set is not taken into account. This is an issue in both 2.1.4 and 2.2.x

**To Reproduce**
```

def get_request() =
  ...
end

music = request.dynamic(
  id="music", 
  prefetch=1,
  retry_delay=5.,
  get_request
)
```

If liquidsoap throws a runtime error in get_request, ie uncaught json parsing, then get_request is called many times very quickly instead of once every 5 second per the set retry_delay

**Expected behavior**
request.dynamic should respect the retry_delay value set in the script

**Version details**

- Liquidsoap 2.2.0+git@2a3bf62e1
- Docker version 20.10.22, build 3a2c30b
- Image: savonet/liquidsoap:rolling-release-v2.2.x

**Install method**
Docker

**Common issues**
Did not find a related issue

**Comment by toots** [comment]
Thanks for reporting. Do you have more logs and/or a stand alone script to reproduce? This script seems to work fine:

```liquidsoap
def get_request() =
  error.raise(error.not_found, "foo")
end

music = request.dynamic(
  id="music",
  prefetch=1,
  retry_delay=5.,
  get_request
)

output.dummy(fallible=true, music)
```

**Comment by toots** [comment]
Thanks for the detailed explanation! I think I might have found out why, the logic to queue request after a failure has two distinct mechanisms to trigger the next fetch operation.

Any chance you could try the binaries built in this action (when it finishes): https://github.com/savonet/liquidsoap/actions/runs/5140220404
