### ISSUE TITLE
Selecting device to input from?

### ISSUE THREAD

**Issue by ESPONI** [savonet/liquidsoap#303]
Any function to input from other than default device?
As we use "output.ao" to output to any other device, like we have tested with Virtual Cable (id=5) here 

```
output.ao(fallible=true, options=[("id", "5")], outputStream)
```

(Sorry if is not the correct site to post this question)

Thanks!!! & Awesome APP

**Comment by smimram** [comment]
The `output.ao` operator has an `options` parameters which should behave [as described here](https://xiph.org/ao/doc/drivers.html) and should allow choosing the output.
