### ISSUE TITLE
Simple ffmpeg filter with ffmpeg raw causes memory issue (v2.2.x)

### ISSUE THREAD

**Issue by jamesds** [savonet/liquidsoap#3030]
When using an ffmpeg filter as shown below in Liquidsoap 2.2.x, after running the script the process's RAM usage quickly climbs, until the RAM is exceeded and the process is killed. 

**Example Script**
The following is a small script that will reproduce this issue. I've left the `acopy` / `bbox` lines commented out as even though they give the filter a purpose, their inclusion doesn't affect the outcome - it crashes either way.

```
video_playlist = playlist('test/playlist.txt');

def i_will_eat_your_ram(s) =
  def mkfilter(graph) =
    a = source.tracks(s).audio;
    v = source.tracks(s).video;

    a = ffmpeg.filter.audio.input(graph, a);
    v = ffmpeg.filter.video.input(graph, v);

    # a = ffmpeg.filter.acopy(graph, a);
    # v = ffmpeg.filter.bbox(graph, v);

    a = ffmpeg.filter.audio.output(graph, a);
    v = ffmpeg.filter.video.output(graph, v);

    source({ audio=a, video=v })
  end

  ffmpeg.filter.create(mkfilter);
end

video_playlist = i_will_eat_your_ram(video_playlist)

enc = %ffmpeg(format="mpegts", %audio.raw(codec="aac"), %video.raw(codec="libx264"))

output.file.hls(fallible=true, "test/hls/", [("1080", enc)], video_playlist)
```

**Log Output**

The following log output when running this may be of note:

```
[abuffersink_0 @ 0x7f3ab1c19c00] 100 buffers queued in abuffersink_0, something may be wrong.
[abuffersink_0 @ 0x7f3ab1c19c00] 1000 buffers queued in abuffersink_0, something may be wrong.
```

**Version Details**
Running Liquidsoap 2.2.x (latest commit c81e52eba) on Ubuntu 22.04

**Install method**
Installed via opam / git:

```
opam install ssl samplerate taglib mad lame cry tsdl-ttf

git clone https://github.com/savonet/ocaml-ffmpeg.git
cd ocaml-ffmpeg
opam install -y .
cd ..
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam install -y .
```

**Comment by toots** [comment]
Thanks for reporting. I need to do more testing but this branch should have a fix for you: https://github.com/savonet/liquidsoap/pull/3032

**Comment by toots** [comment]
This should be fixed with https://github.com/savonet/liquidsoap/commit/45f579b8f695f5bf94c159c030f0baa3d15d0aa9, will push to `rolling-release-v2.2x` soon.
