### ISSUE TITLE
Enabling replaygain on LS 2.2.0 breaks playback

### ISSUE THREAD

**Issue by Vaalyn** [savonet/liquidsoap#3039]
**Describe the bug**
I'm reporting a bug that we found after upgrading the LS version we include in AzuraCast to 2.2.0.
When enabling replaygain metadata calculation via `enable_replaygain_metadata` LS ignores our playlists and request.dynamic and repeats trying to play the error fallback file.

As soon as I disable the `enable_replaygain_metadata` operator it runs normally. 

**To Reproduce**
Here is the Liquidsoap config we generate as part of AzuraCast in the current version with the 2.2.0 LS version.
<details> 
  <summary>LS Config</summary>

    # WARNING! This file is automatically generated by AzuraCast.
    # Do not update it directly!

    init.daemon.set(false)
    init.daemon.pidfile.path.set("/var/azuracast/stations/azuratest_radio/config/liquidsoap.pid")

    log.stdout.set(true)
    log.file.set(false)

    settings.server.log.level.set(4)

    settings.server.socket.set(true)
    settings.server.socket.permissions.set(0o660)
    settings.server.socket.path.set("/var/azuracast/stations/azuratest_radio/config/liquidsoap.sock")

    settings.harbor.bind_addrs.set(["0.0.0.0"])
    settings.encoder.metadata.export.set(["artist","title","album","song"])

    environment.set("TZ", "UTC")

    autodj_is_loading = ref(true)
    ignore(autodj_is_loading)

    autodj_ping_attempts = ref(0)
    ignore(autodj_ping_attempts)

    # Track live-enabled status.
    live_enabled = ref(false)
    ignore(live_enabled)

    # Track live transition for crossfades.
    to_live = ref(false)
    ignore(to_live)

    azuracast_api_url = "http://127.0.0.1:6010/api/internal/1/liquidsoap"
    azuracast_api_key = "(PASSWORD)"

    def azuracast_api_call(~timeout=2.0, url, payload) =
        full_url = "#{azuracast_api_url}/#{url}"

        log("API #{url} - Sending POST request to '#{full_url}' with body: #{payload}")
        try
            response = http.post(full_url,
                headers=[
                    ("Content-Type", "application/json"),
                    ("User-Agent", "Liquidsoap AzuraCast"),
                    ("X-Liquidsoap-Api-Key", "#{azuracast_api_key}")
                ],
                timeout=timeout,
                data=payload
            )

            log("API #{url} - Response (#{response.status_code}): #{response}")
            "#{response}"
        catch err do
            log("API #{url} - Error: #{error.kind(err)} - #{error.message(err)}")
            "false"
        end
    end

    station_media_dir = "/var/azuracast/stations/azuratest_radio/media"
    def azuracast_media_protocol(~rlog=_,~maxtime=_,arg) =
        ["#{station_media_dir}/#{arg}"]
    end

    protocol.add(
        "media",
        azuracast_media_protocol,
        doc="Pull files from AzuraCast media directory.",
        syntax="media:uri"
    )

    playlist_default = playlist(id="playlist_default",mime_type="audio/x-mpegurl",mode="randomize",reload_mode="watch","/var/azuracast/stations/azuratest_radio/playlists/playlist_default.m3u")
    playlist_default = cue_cut(id="cue_playlist_default", playlist_default)

    # Standard Playlists
    radio = random(id="standard_playlists", weights=[3], [playlist_default])

    # AutoDJ Next Song Script
    def autodj_next_song() =
        response = azuracast_api_call(
            "nextsong",
            ""
        )
        if (response == "") or (response == "false") then
            null()
        else
            r = request.create(response)
            if request.resolve(r) then
                r
            else
                null()
            end
        end
    end

    # Delayed ping for AutoDJ Next Song
    def wait_for_next_song(autodj)
        autodj_ping_attempts.set(autodj_ping_attempts() + 1)

        if source.is_ready(autodj) then
            log("AutoDJ is ready!")
            autodj_is_loading.set(false)
            -1.0
        elsif autodj_ping_attempts() > 200 then
            log("AutoDJ could not be initialized within the specified timeout.")
            autodj_is_loading.set(false)
            -1.0
        else
            0.5
        end
    end

    dynamic = request.dynamic(id="next_song", timeout=20.0, retry_delay=10., autodj_next_song)
    dynamic = cue_cut(id="cue_next_song", dynamic)

    dynamic_startup = fallback(
        id = "dynamic_startup",
        track_sensitive = false,
        [
            dynamic,
            source.available(
                blank(id = "autodj_startup_blank", duration = 120.),
                predicate.activates({autodj_is_loading()})
            )
        ]
    )
    radio = fallback(id="autodj_fallback", track_sensitive = true, [dynamic_startup, radio])

    ref_dynamic = ref(dynamic);
    thread.run.recurrent(delay=0.25, { wait_for_next_song(ref_dynamic()) })

    requests = request.queue(id="requests")
    requests = cue_cut(id="cue_requests", requests)
    radio = fallback(id="requests_fallback", track_sensitive = true, [requests, radio])

    interrupting_queue = request.queue(id="interrupting_requests")
    interrupting_queue = cue_cut(id="cue_interrupting_requests", interrupting_queue)
    radio = fallback(id="interrupting_fallback", track_sensitive = false, [interrupting_queue, radio])

    def add_skip_command(s) =
        def skip(_) =
            source.skip(s)
            "Done!"
        end

        server.register(namespace="radio", usage="skip", description="Skip the current song.", "skip",skip)
    end

    add_skip_command(radio)

    def live_aware_crossfade(old, new) =
        if to_live() then
            # If going to the live show, play a simple sequence
            sequence([fade.out(old.source),fade.in(new.source)])
        else
            # Otherwise, use the smart transition
            cross.simple(old.source, new.source, fade_in=2.00, fade_out=2.00)
        end
    end

    radio = cross(minimum=0., duration=3.00, live_aware_crossfade, radio)

    # Allow for Telnet-driven insertion of custom metadata.
    radio = server.insert_metadata(id="custom_metadata", radio)

    # Apply amplification metadata (if supplied)
    radio = amplify(override="liq_amplify", 1., radio)

    # Replaygain Metadata
    enable_replaygain_metadata()
    radio = replaygain(radio)

    error_file = single(id="error_jingle", "/usr/local/share/icecast/web/error.mp3")

    def tag_error_file(m) =
        ignore(m)
        [("is_error_file", "true")]
    end
    error_file = metadata.map(tag_error_file, error_file)

    radio = fallback(id="safe_fallback", track_sensitive = false, [radio, error_file])

    # Send metadata changes back to AzuraCast
    last_title = ref("")
    last_artist = ref("")

    def metadata_updated(m) =
        def f() =
            if (m["is_error_file"] != "true") then
                if (m["title"] != last_title() or m["artist"] != last_artist()) then
                    last_title.set(m["title"])
                    last_artist.set(m["artist"])

                    j = json()

                    if (m["song_id"] != "") then
                        j.add("song_id", m["song_id"])
                        j.add("media_id", m["media_id"])
                        j.add("playlist_id", m["playlist_id"])
                    else
                        j.add("artist", m["artist"])
                        j.add("title", m["title"])
                    end

                    _ = azuracast_api_call(
                        "feedback",
                        json.stringify(j)
                    )
                end
            end
        end

        thread.run(f)
    end

    radio.on_metadata(metadata_updated)

    # Handle "Jingle Mode" tracks by replaying the previous metadata.
    last_metadata = ref([])
    def handle_jingle_mode(m) =
        if (m["jingle_mode"] == "true") then
            last_metadata()
        else
            last_metadata.set(m)
            m
        end
    end

    radio = metadata.map(update=false, strip=true, handle_jingle_mode, radio)

    # Local Broadcasts
    output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="local_1", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/radio.mp3", name = "KMTS-FM", description = "A test radio station.", genre = "TRK", public = false, encoding = "UTF-8", radio)
    output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=64, id3v2=true), id="local_2", host = "127.0.0.1", port = 8000, password = "(PASSWORD)", mount = "/mobile.mp3", name = "KMTS-FM", description = "A test radio station.", genre = "TRK", public = false, encoding = "UTF-8", radio)

    # Remote Relays
</details>

**Expected behavior**
Enabling replaygain metadata calculation shouldn't break the playback.

**Version details**

- OS: Ubuntu 22.04
- Version: 2.2.0+git@fbff29210

**Install method**
From the .deb file found at:
https://github.com/savonet/liquidsoap-release-assets/releases/tag/rolling-release-v2.2.x

**Logs**
```
2023/04/30 12:15:23 [source.replaygain.compute_152:3] Content type is {audio=pcm(stereo)}.
2023/04/30 12:15:23 [request.once_152:3] Content type is {audio=pcm(stereo)}.
2023/04/30 12:15:23 [decoder.ffmpeg:3] Requested content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/04/30 12:15:23 [decoder.ffmpeg:3] FFmpeg recognizes "/usr/local/share/icecast/web/error.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/04/30 12:15:23 [decoder.ffmpeg:3] Decoded content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/04/30 12:15:23 [dummy:3] Content type is {audio=pcm(stereo)}.
2023/04/30 12:15:23 [source.replaygain.compute_153:3] Content type is {audio=pcm(stereo)}.
2023/04/30 12:15:23 [request.once_153:3] Content type is {audio=pcm(stereo)}.
2023/04/30 12:15:23 [decoder.ffmpeg:3] Requested content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/04/30 12:15:23 [decoder.ffmpeg:3] FFmpeg recognizes "/usr/local/share/icecast/web/error.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/04/30 12:15:23 [decoder.ffmpeg:3] Decoded content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/04/30 12:15:23 [dummy:3] Content type is {audio=pcm(stereo)}.
```

**Comment by Moonbase59** [comment]
Confirming this, also for Liquidsoap 2.2.0+git@81016089f. ReplayGain tag support is rather important for many stations, for instance we use a 160.000 track song library, carefully replaygained using [loudgain](https://github.com/Moonbase59/loudgain).

**Comment by toots** [comment]
Thanks for reporting. Acknowledged and being investigated. Will push a fix shortly.

**Comment by Vaalyn** [comment]
@toots unfortunately I haven't been able to test this earlier and I can still see this happening on version `Liquidsoap 2.2.0+git@81016089f`

Here is the log output:

```
2023/06/05 18:46:34 >>> LOG START
2023/06/05 18:46:30 [main:3] Liquidsoap 2.2.0+git@81016089f
2023/06/05 18:46:30 [main:3] Using: alsa=0.3.0 angstrom=0.15.0 ao=0.2.4 asetmap=0.8.1 astring=0.8.5 base.caml=v0.15.1 base64=3.5.1 bigarray=[distributed with OCaml] bigarray-compat=1.1.0 bigstringaf=0.9.1 bjack=0.1.6 bytes=[distributed with OCaml] camlimages.all_formats=4.2.6 camlimages.core=5.0.4 camlimages.exif=5.0.4 camlimages.gif=5.0.4 camlimages.jpeg=5.0.4 camlimages.png=5.0.4 camlimages.tiff=5.0.4 camlimages.xpm=5.0.4 camlp-streams camomile=d3773ec camomile.lib=d3773ec cohttp=5.1.0 cohttp-lwt=5.1.0 cohttp-lwt-unix=5.1.0 conduit=6.2.0 conduit-lwt=6.2.0 conduit-lwt-unix=6.2.0 cry=0.6.8 ctypes=0.20.2 ctypes.foreign=0.20.2 ctypes.stubs=0.20.2 curl=0.9.2 domain-name=0.4.0 dssi=0.1.5 dtools=0.4.4 dune-build-info=3.7.1 dune-private-libs.dune-section=3.7.1 dune-site=3.7.1 dune-site.private=3.7.1 duppy=0.9.3 faad=0.5.2 fdkaac=0.3.3 ffmpeg-av=1.1.8 ffmpeg-avcodec=1.1.8 ffmpeg-avdevice=1.1.8 ffmpeg-avfilter=1.1.8 ffmpeg-avutil=1.1.8 ffmpeg-swresample=1.1.8 ffmpeg-swscale=1.1.8 fileutils=0.6.4 flac=0.3.2 flac.decoder=0.3.2 flac.ogg=0.3.2 fmt=0.9.0 frei0r=0.1.2 gd=1.0a5 gen=1.1 inotify=2.4.1 integers ipaddr=5.5.0 ipaddr-sexp=5.5.0 ipaddr.unix=5.5.0 irc-client irc-client-unix ladspa=0.2.2 lame=0.3.6 lastfm=0.3.3 lilv=0.1.0 liquidsoap-lang=2.2.0 liquidsoap_alsa=rolling-release-v2.2.x-20-g8101608 liquidsoap_ao=rolling-release-v2.2.x-20-g8101608 liquidsoap_bjack=rolling-release-v2.2.x-20-g8101608 liquidsoap_builtins=rolling-release-v2.2.x-20-g8101608 liquidsoap_camlimages=rolling-release-v2.2.x-20-g8101608 liquidsoap_core=rolling-release-v2.2.x-20-g8101608 liquidsoap_dssi=rolling-release-v2.2.x-20-g8101608 liquidsoap_faad=rolling-release-v2.2.x-20-g8101608 liquidsoap_fdkaac=rolling-release-v2.2.x-20-g8101608 liquidsoap_ffmpeg=rolling-release-v2.2.x-20-g8101608 liquidsoap_flac=rolling-release-v2.2.x-20-g8101608 liquidsoap_frei0r=rolling-release-v2.2.x-20-g8101608 liquidsoap_gd=rolling-release-v2.2.x-20-g8101608 liquidsoap_irc=rolling-release-v2.2.x-20-g8101608 liquidsoap_ladspa=rolling-release-v2.2.x-20-g8101608 liquidsoap_lame=rolling-release-v2.2.x-20-g8101608 liquidsoap_lastfm=rolling-release-v2.2.x-20-g8101608 liquidsoap_lilv=rolling-release-v2.2.x-20-g8101608 liquidsoap_lo=rolling-release-v2.2.x-20-g8101608 liquidsoap_mad=rolling-release-v2.2.x-20-g8101608 liquidsoap_magic=rolling-release-v2.2.x-20-g8101608 liquidsoap_mem_usage=rolling-release-v2.2.x-20-g8101608 liquidsoap_memtrace=rolling-release-v2.2.x-20-g8101608 liquidsoap_ogg=rolling-release-v2.2.x-20-g8101608 liquidsoap_ogg_flac=rolling-release-v2.2.x-20-g8101608 liquidsoap_optionals=rolling-release-v2.2.x-20-g8101608 liquidsoap_opus=rolling-release-v2.2.x-20-g8101608 liquidsoap_osc=rolling-release-v2.2.x-20-g8101608 liquidsoap_oss=rolling-release-v2.2.x-20-g8101608 liquidsoap_portaudio=rolling-release-v2.2.x-20-g8101608 liquidsoap_posix_time=rolling-release-v2.2.x-20-g8101608 liquidsoap_prometheus=rolling-release-v2.2.x-20-g8101608 liquidsoap_pulseaudio=rolling-release-v2.2.x-20-g8101608 liquidsoap_runtime=rolling-release-v2.2.x-20-g8101608 liquidsoap_samplerate=rolling-release-v2.2.x-20-g8101608 liquidsoap_sdl=rolling-release-v2.2.x-20-g8101608 liquidsoap_shine=rolling-release-v2.2.x-20-g8101608 liquidsoap_soundtouch=rolling-release-v2.2.x-20-g8101608 liquidsoap_speex=rolling-release-v2.2.x-20-g8101608 liquidsoap_srt=rolling-release-v2.2.x-20-g8101608 liquidsoap_ssl=rolling-release-v2.2.x-20-g8101608 liquidsoap_stereotool=rolling-release-v2.2.x-20-g8101608 liquidsoap_taglib=rolling-release-v2.2.x-20-g8101608 liquidsoap_theora=rolling-release-v2.2.x-20-g8101608 liquidsoap_vorbis=rolling-release-v2.2.x-20-g8101608 liquidsoap_xmlplaylist=rolling-release-v2.2.x-20-g8101608 liquidsoap_yaml=rolling-release-v2.2.x-20-g8101608 lo=0.2.0 logs=0.7.0 logs.fmt=0.7.0 logs.lwt=0.7.0 lwt=5.6.1 lwt.unix=5.6.1 macaddr=5.5.0 mad=0.5.3 magic=0.7.3 magic-mime=1.3.0 mem_usage=0.0.4 memtrace=0.2.3 menhirLib=20220210 metadata=0.2.0 mm=0.8.3 mm.audio=0.8.3 mm.base=0.8.3 mm.image=0.8.3 mm.midi=0.8.3 mm.video=0.8.3 ocplib-endian ocplib-endian.bigstring ogg=0.7.3 ogg.decoder=0.7.3 opus=0.2.3 opus.decoder=0.2.3 osc osc-unix parsexp=v0.15.0 pcre=7.5.0 portaudio=0.2.3 posix-base=65ec333 posix-socket=65ec333 posix-socket.constants=65ec333 posix-socket.stubs=65ec333 posix-socket.types=65ec333 posix-time2=65ec333 posix-time2.constants=65ec333 posix-time2.stubs=65ec333 posix-time2.types=65ec333 posix-types=65ec333 posix-types.constants=65ec333 ppx_sexp_conv.runtime-lib=v0.15.0 prometheus=1.2 prometheus-app=1.2 pulseaudio=0.1.6 re=1.10.4 result=1.5 samplerate=0.1.6 sedlex=3.1 seq=[distributed with OCaml 4.07 or above] sexplib=v0.15.1 sexplib0=v0.15.0 shine=0.2.3 soundtouch=0.1.9 speex=0.4.1 speex.decoder=0.4.1 srt=0.3.0 srt.constants=0.3.0 srt.stubs=0.3.0 srt.stubs.locked=0.3.0 srt.types=0.3.0 ssl=0.5.13 stdlib-shims=0.3.0 stereotool=rolling-release-v2.2.x-20-g8101608 str=[distributed with OCaml] stringext=1.6.0 taglib=0.3.10 theora=0.4.0 theora.decoder=0.4.0 threads=[distributed with OCaml] threads.posix=[distributed with OCaml] tsdl=v1.0.0 tsdl-image=0.5 tsdl-ttf=0.5 unix=[distributed with OCaml] unix-errno=0.6.2 unix-errno.errno_bindings=0.6.2 unix-errno.errno_types=0.6.2 unix-errno.errno_types_detected=0.6.2 unix-errno.unix=0.6.2 uri=4.2.0 uri-sexp=4.2.0 uri.services=4.2.0 vorbis=0.8.1 vorbis.decoder=0.8.1 xmlm=1.4.0 xmlplaylist=0.1.5 yaml=3.1.0 yaml.bindings=3.1.0 yaml.bindings.types=3.1.0 yaml.c=3.1.0 yaml.ffi=3.1.0 yaml.types=3.1.0
2023/06/05 18:46:30 [clock:3] Using native (high-precision) implementation for latency control
2023/06/05 18:46:34 [main:3] Standard library loaded in 4.09 seconds.
2023/06/05 18:46:34 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2023/06/05 18:46:34 [frame:3] Video frame size set to: 1280x720
2023/06/05 18:46:34 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2023/06/05 18:46:34 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2023/06/05 18:46:34 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2023/06/05 18:46:34 [sandbox:3] Running inside a docker container, disabling sandboxing.
2023/06/05 18:46:34 [startup:3] DSSI plugins registration: 0.00s
2023/06/05 18:46:34 [startup:3] FFmpeg filters registration: 0.02s
2023/06/05 18:46:34 [startup:3] FFmpeg bitstream filters registration: 0.00s
2023/06/05 18:46:34 [startup:3] Lilv plugins registration: 0.00s
2023/06/05 18:46:34 [startup:3] Frei0r plugin registration: 0.00s
2023/06/05 18:46:34 [startup:3] LADSPA plugins registration: 0.04s
2023/06/05 18:46:34 [startup:3] Typechecking: 3.97s
2023/06/05 18:46:34 [startup:3] Evaluation: 0.01s
2023/06/05 18:46:34 [startup:3] Typechecking: 0.02s
2023/06/05 18:46:34 [startup:3] Evaluation: 0.00s
2023/06/05 18:46:34 [startup:3] Typechecking: 0.02s
2023/06/05 18:46:34 [startup:3] Evaluation: 0.15s
2023/06/05 18:46:34 [startup:3] Loaded /var/azuracast/stations/brg/config/liquidsoap.liq: 0.17s
2023/06/05 18:46:34 [video.converter:3] Using preferred video converter: ffmpeg.
2023/06/05 18:46:34 [audio.converter:3] Using samplerate converter: libsamplerate.
2023/06/05 18:46:34 [local_1:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source_4:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [metadata_map:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source_2:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source_1:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [metadata_map:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [insert_metadata_1:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [amplify:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [custom_metadata:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [cross_0:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [cue_next_song:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [next_song:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source.available_0:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [autodj_startup_blank:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [on_track_1:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [cue_playlist_test_123:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [playlist_test_123:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [cue_playlist_nightdj:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [playlist_nightdj:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [on_track_0:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [cue_playlist_daydj:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [playlist_daydj:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [amplify:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [amplify_1:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source_3:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [metadata_map:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [error_jingle:3] "/usr/local/share/icecast/web/error.mp3" is static, resolving once for all...
2023/06/05 18:46:34 [decoder.ffmpeg:3] Requested content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] FFmpeg recognizes "/usr/local/share/icecast/web/error.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] Decoded content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:34 [dummy:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source.replaygain.compute_0:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [request.once_0:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [decoder.ffmpeg:3] Requested content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] FFmpeg recognizes "/usr/local/share/icecast/web/error.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] Decoded content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:34 [dummy:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source.replaygain.compute_1:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [request.once_1:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [decoder.ffmpeg:3] Requested content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] FFmpeg recognizes "/usr/local/share/icecast/web/error.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] Decoded content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:34 [dummy:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [source.replaygain.compute_2:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [request.once_2:3] Content type is {audio=pcm(stereo)}.
2023/06/05 18:46:34 [decoder.ffmpeg:3] Requested content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] FFmpeg recognizes "/usr/local/share/icecast/web/error.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/06/05 18:46:34 [decoder.ffmpeg:3] Decoded content-type for "/usr/local/share/icecast/web/error.mp3": {audio=pcm(stereo)}
2023/06/05 18:46:35 [dummy:3] Content type is {audio=pcm(stereo)}.
...
```

**Comment by toots** [comment]
Hi! If I'm correct this commit is from April 29: https://github.com/savonet/liquidsoap/commit/81016089f this is a little old, there's been a lot of fixes around that part of the code since then. I'd recommend to test again with a recent build. Thanks!
