### ISSUE TITLE
Rolling Release #fbff29210,#81016089f: After about an hour, "We must catchup …" messages appear in LS log, station stutters

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3040]
**Describe the bug**
After about an hour, "We must catchup …" messages appear in LS log, station stutters.

**More info**
- Trying to remedy replaygain bug (https://github.com/savonet/liquidsoap/issues/3039), we tested not only #fbff29210 but also #81016089f.
- **All details, config, logs, etc. at https://github.com/AzuraCast/AzuraCast/issues/6247**

**To Reproduce**
see above

**Expected behavior**
- Much less CPU consumption.
- No "We must catch up…" errors.
- Replaygain bug fixed.

**Version details**

- OS: Ubuntu 22.04-LTS server
- Version: AzuraCast rolling release, running in docker container

**Install method**
AzuraCast. For #81016089f, manual install inside docker container:
```bash
wget https://github.com/savonet/liquidsoap-release-assets/releases/download/rolling-release-v2.2.x/liquidsoap-8101608_2.2.0-ubuntu-jammy-1_amd64.deb
apt remove liquidsoap-fbff292
dpkg -i ./liquidsoap-8101608_2.2.0-ubuntu-jammy-1_amd64.deb
```

**Comment by toots** [comment]
The replaygain bug https://github.com/savonet/liquidsoap/issues/3039 is fixed and about to be pushed with the latest `rolling-release-v2.2.x`. I'd suggest to test again as this bug was in fact causing a high CPU burn live loop.

**Comment by toots** [comment]
The upstream bug seems fixed, closing this, please reopen if needed.
