### ISSUE TITLE
If one output.icecast stream disconnects, all of them disconnect

### ISSUE THREAD

**Issue by asantoni** [savonet/liquidsoap#305]
If you're running Liquidsoap with multiple output streams, and one of them disconnects due to a network issue, then all of the streams will disconnect. The expected behaviour is that only the stream that encountered the problem should disconnect, and the remaining streams should stay connected.

I have attached a simple example script that illustrates the problem. If you connect one stream to an Icecast server running on localhost and the other stream to a remote Icecast server, then disable your ethernet adapter, you will see the following output and both streams will disconnect:

```
2016/02/23 15:55:14 [my_remote_mount:2] Error while sending data: could not write data to host: connection timeout!
2016/02/23 15:55:14 [lang:3] Error - disconnected
2016/02/23 15:55:14 [my_remote_mount:3] Closing connection...
2016/02/23 15:55:14 [my_remote_mount:3] Will try to reconnect in 5.00 seconds.
2016/02/23 15:55:14 [my_local_mount:2] Error while sending data: could not write data to host: Broken pipe in write()!
2016/02/23 15:55:14 [lang:3] Error - disconnected
2016/02/23 15:55:14 [my_local_mount:3] Closing connection...
2016/02/23 15:55:14 [my_local_mount:3] Will try to reconnect in 5.00 seconds.
```

The impact of this bug is that multiple streams cannot be used for redundancy. This is a critical issue affecting anyone who is streaming to multiple servers.

Example script:
```
# The input file,
# any format supported by liquidsoap
input = argv(1)

# A source that plays the file once
source = once(single(input))

# We use a clock with disabled synchronization
clock.assign_new(sync=false,[source])

host = "localhost"
port = 8000
mount_point = "my_local_mount"
pass = "hackme"
url = "xyz"
description = "xyz"
name = "xyz"
genre = "xyz"
user = "source"


def on_error(msg)
    log("Error - disconnected")
    5.
end
def on_connect()
    log("Connected")
end


output.icecast(%mp3, host = host,
            port = port,
            password = pass,
            mount = mount_point,
            fallible = true,
            url = url,
            description = description,
            name = name,
            genre = genre,
            user = user,
            on_error = on_error,
            on_connect = on_connect,
            source)

remote_host = "my_remote_icecast_server"
remote_mount_point = "my_remote_mount"
remote_user = "source"
remote_pass = "XXXXXX"

output.icecast(%mp3, host = remote_host,
            port = port,
            password = remote_pass,
            mount = remote_mount_point,
            fallible = true,
            url = url,
            description = description,
            name = name,
            genre = genre,
            user = remote_user,
            on_error = on_error,
            on_connect = on_connect,
            source)
```

This was tested with Liquidsoap 1.1.1.

Thanks,
Albert

**Comment by toots** [comment]
Hi Albert,

Have you looked at clocks? They have been introduced specially for this kind of situations where the latency of one output impacts the other output.

The documentation is here: http://liquidsoap.fm/doc-1.1.1/clocks.html In particular, you might want to look at the chapter "External clocks: decoupling latencies".

**Comment by asantoni** [comment]
Hi Romain,

If I make two changes to my above script, the problem is fixed. The changes are:

1) Wrap the source in mksafe:
`source = mksafe(once(single(input)))`

2) Assign a new clock to each source, and wrap the sources in buffer:

`clock.assign_new(id="stream1", [output.icecast(%mp3, host = host,
              port = port,
              password = pass,
              mount = mount_point,
              fallible = true,
              url = url,
              description = description,
              name = name,
              genre = genre,
              user = user,
              on_error = on_error,
              on_connect = on_connect,
              buffer(source))])
`

I have confirmed with these changes, the local stream stays up and is uninterrupted when the remote stream goes down. I tested the case of a network dropout of less than 30 seconds, and the case of greater than 30 seconds. When the remote stream comes back online, it remains roughly in sync with the local stream.

However, I measured the CPU usage of Liquidsoap with both scripts, and the latter script uses 25% more CPU usage. Is there a way to reduce the CPU usage while still fixing the problem? (The first script averaged 16.0% usage and the latter script averaged 20.1%.)

Thanks again!
Albert

**Comment by toots** [comment]
Hi Albert,

I am not sure where the increased CPU usage comes from. My guess would be that multiple clocks require multiple threads which is probably where this comes from.

As of now, I have no idea about how to reduce CPU usage. However, multiple clocks should also allow you to take advantage of multiple cores for encoding so, overall, this should reduce or at least optimize your CPU usage more than anything.
