### ISSUE TITLE
Problem with Tracks

### ISSUE THREAD

**Issue by Lenkine** [savonet/liquidsoap#306]
Hello to everybody,

I'm facing two litl issue with LS, and i hope you can help...
I have this LS script with a playlist as a fallback..:

```
source1 = input.http('url_of_stream/1.aac')
source1 = strip_blank(source1, length=5.0)
source2 = input.http('url_of_stream/2.aac')
source2 = strip_blank(source2, length=5.0)

output.alsa(fallback(track_sensitive=true, [source1, source2, playlist.safe(playlist.pls)]))
```

When there is a problem with the source1, it switches to source2, and when there is a problem with source 2 it switches to the playlist. 

The first problem is that when it switches from the source 1 to the source 2 (or the playlist...) it: 
- accelerate the first 3/4 sec of the source 2 (or the first track of the playlist for 3/4 sec)
- When he's playing te playlist, when he finished to play a track and starts playing the next track, there is a kind of croak at the begining of the track for 3 or 8 second depending on track...

PLease help...
Thanks.

**Comment by toots** [comment]
Hi @Lenkine.

I suspect that your problem is due to clock/timing issues and perhaps with the `alsa` plugin as well. Here are a couple of things you can do:
* Post logs around the time of the issues so we can gather more information about it.
* Try using `output.ao`

**Comment by smimram** [comment]
This bug report is quite old, and a solution was proposed without an answer. Closing for now, please reopen if necessary.
