### ISSUE TITLE
avutil_stubs error array type has incomplete element type enum PixelFormat

### ISSUE THREAD

**Issue by 5chdn** [savonet/liquidsoap#307]
Both liquidsoap-1.2.0 and the latest git fail to build:

    ocamlmklib      -L-Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/lib    \
          -o gavl_stubs  gavl_stubs.o -lgavl \
    ocamlc.opt -a -dllib dllgavl_stubs.so       -ccopt -Wl,-O1,--sort-common,--as-needed,-z,relro -ccopt -L/usr/lib  -ccopt -L-Wl,-O1,--sort-common,--as-needed,-z,relro -ccopt -L/usr/lib     \
          -cclib -lgavl_stubs -cclib -lgavl  -o gavl.cma  gavl.cmo
    make[3]: Leaving directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-gavl/src'
    make[3]: Entering directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-gavl/src'
    making ._ncdi/gavl.di from gavl.mli
    make[3]: 'libgavl_stubs.a' is up to date.
    ocamlopt.opt -c -g -w +A@5-7@8@11@12@20-35-44-45 gavl.ml
    File "gavl.ml", line 86, characters 4-156:
    Warning 4: this pattern-matching is fragile.
    It will remain exhaustive when constructors are added to type pixel_format.
    File "gavl.ml", line 86, characters 4-156:
    Warning 4: this pattern-matching is fragile.
    It will remain exhaustive when constructors are added to type pixel_format.
    File "gavl.ml", line 96, characters 4-243:
    Warning 4: this pattern-matching is fragile.
    It will remain exhaustive when constructors are added to type pixel_format.
    File "gavl.ml", line 96, characters 4-243:
    Warning 4: this pattern-matching is fragile.
    It will remain exhaustive when constructors are added to type pixel_format.
    ocamlopt.opt -a        -ccopt -Wl,-O1,--sort-common,--as-needed,-z,relro -ccopt -L/usr/lib  -ccopt -L-Wl,-O1,--sort-common,--as-needed,-z,relro -ccopt -L/usr/lib    -cclib -lgavl_stubs -cclib -lgavl  \
           -o gavl.cmxa gavl.cmx
    make[3]: Leaving directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-gavl/src'
    make[2]: Leaving directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-gavl/src'
    make[1]: Leaving directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-gavl'
    make[1]: Entering directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-ffmpeg'
    make -C src all
    make[2]: Entering directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-ffmpeg/src'
    make[3]: Entering directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-ffmpeg/src'
    ocamldep.opt swscale.ml > ._d/swscale.d
    ocamldep.opt avutil.ml > ._d/avutil.d
    ocamlc.opt -c -cc "gcc" -ccopt "-fPIC -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -I/usr/include   -Wall -DCAML_NAME_SPACE \
          -DPIC -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include    \
              -o avutil_stubs.o " avutil_stubs.c
    avutil_stubs.c:13:31: error: array type has incomplete element type ‘enum PixelFormat’
     static const enum PixelFormat PIXEL_FORMATS[] = {
                                   ^
    avutil_stubs.c:14:3: error: ‘PIX_FMT_YUV420P’ undeclared here (not in a function)
       PIX_FMT_YUV420P,
       ^
    avutil_stubs.c:15:3: error: ‘PIX_FMT_YUYV422’ undeclared here (not in a function)
       PIX_FMT_YUYV422,
       ^
    avutil_stubs.c:16:3: error: ‘PIX_FMT_RGB24’ undeclared here (not in a function)
       PIX_FMT_RGB24,
       ^
    avutil_stubs.c:17:3: error: ‘PIX_FMT_BGR24’ undeclared here (not in a function)
       PIX_FMT_BGR24,
       ^
    avutil_stubs.c:18:3: error: ‘PIX_FMT_YUV422P’ undeclared here (not in a function)
       PIX_FMT_YUV422P,
       ^
    avutil_stubs.c:19:3: error: ‘PIX_FMT_YUV444P’ undeclared here (not in a function)
       PIX_FMT_YUV444P,
       ^
    avutil_stubs.c:20:3: error: ‘PIX_FMT_YUV410P’ undeclared here (not in a function)
       PIX_FMT_YUV410P,
       ^
    avutil_stubs.c:21:3: error: ‘PIX_FMT_YUV411P’ undeclared here (not in a function)
       PIX_FMT_YUV411P,
       ^
    avutil_stubs.c:22:3: error: ‘PIX_FMT_YUVJ422P’ undeclared here (not in a function)
       PIX_FMT_YUVJ422P,
       ^
    avutil_stubs.c:23:3: error: ‘PIX_FMT_YUVJ444P’ undeclared here (not in a function)
       PIX_FMT_YUVJ444P,
       ^
    avutil_stubs.c:24:3: error: ‘PIX_FMT_RGBA’ undeclared here (not in a function)
       PIX_FMT_RGBA,
       ^
    avutil_stubs.c:25:3: error: ‘PIX_FMT_BGRA’ undeclared here (not in a function)
       PIX_FMT_BGRA
       ^
    avutil_stubs.c: In function ‘caml_avutil_bits_per_pixel’:
    avutil_stubs.c:39:32: error: ‘av_pix_fmt_descriptors’ undeclared (first use in this function)
       ans = av_get_bits_per_pixel(&av_pix_fmt_descriptors[p]);
                                    ^
    avutil_stubs.c:39:32: note: each undeclared identifier is reported only once for each function it appears in
    avutil_stubs.c:36:7: warning: variable ‘p’ set but not used [-Wunused-but-set-variable]
       int p = Int_val(pixel);
           ^
    avutil_stubs.c: At top level:
    avutil_stubs.c:13:31: warning: ‘PIXEL_FORMATS’ defined but not used [-Wunused-variable]
     static const enum PixelFormat PIXEL_FORMATS[] = {
                                   ^
    avutil_stubs.c: In function ‘PixelFormat_val’:
    avutil_stubs.c:31:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    OCamlMakefile:1124: recipe for target 'avutil_stubs.o' failed
    make[3]: *** [avutil_stubs.o] Error 2
    make[3]: Leaving directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-ffmpeg/src'
    OCamlMakefile:784: recipe for target 'byte-code-library' failed
    make[2]: *** [byte-code-library] Error 2
    make[2]: Leaving directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-ffmpeg/src'
    Makefile:9: recipe for target 'all' failed
    make[1]: *** [all] Error 2
    make[1]: Leaving directory '/home/usr/aur/liquidsoap-git/src/liquidsoap-git/ocaml-ffmpeg'
    Makefile:11: recipe for target 'all' failed
    make: *** [all] Error 1

ArchLinux kernel 4.0.6-1-ARCH x86_64 GNU/Linux, tried the packages from AUR:

- https://aur.archlinux.org/packages/liquidsoap
- https://aur.archlinux.org/packages/liquidsoap-git

Both fail to build with the same issue.

That said, I already have been able to build and install liquidsoap-1.2.0 earlier last year but I have to rebuild it as links were broken:

    0 ✓ user@chaos ~/aur/liquidsoap-git $ liquidsoap --check
    liquidsoap: error while loading shared libraries: libavutil.so.54: cannot open shared object file: No such file or directory
    127 ✗ user@chaos ~/aur/liquidsoap-git $ ldd `which liquidsoap`
      linux-vdso.so.1 (0x00007fff6a1de000)
      liblo.so.7 => /usr/lib/liblo.so.7 (0x00007fce98b4b000)
      libpulse.so.0 => /usr/lib/libpulse.so.0 (0x00007fce988fa000)
      libpulse-simple.so.0 => /usr/lib/libpulse-simple.so.0 (0x00007fce986f5000)
      libportaudio.so.2 => /usr/lib/libportaudio.so.2 (0x00007fce984c5000)
      libm.so.6 => /usr/lib/libm.so.6 (0x00007fce981c0000)
      libSoundTouch.so.0 => /usr/lib/libSoundTouch.so.0 (0x00007fce97fab000)
      libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fce97c29000)
      libfaad.so.2 => /usr/lib/libfaad.so.2 (0x00007fce979e6000)
      libtag.so.1 => /usr/lib/libtag.so.1 (0x00007fce976d9000)
      libsamplerate.so.0 => /usr/lib/libsamplerate.so.0 (0x00007fce9736d000)
      libao.so.4 => /usr/lib/libao.so.4 (0x00007fce97164000)
      libasound.so.2 => /usr/lib/libasound.so.2 (0x00007fce96e5d000)
      libjack.so.0 => /usr/lib/libjack.so.0 (0x00007fce96c3d000)
      libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fce96a20000)
      libavutil.so.54 => not found
      libswscale.so.3 => not found
      libgavl.so.1 => /usr/lib/libgavl.so.1 (0x00007fce96194000)
      libschroedinger-1.0.so.0 => /usr/lib/libschroedinger-1.0.so.0 (0x00007fce95eb8000)
      libtheoradec.so.1 => /usr/lib/libtheoradec.so.1 (0x00007fce95c9f000)
      libogg.so.0 => /usr/lib/libogg.so.0 (0x00007fce95a98000)
      libtheoraenc.so.1 => /usr/lib/libtheoraenc.so.1 (0x00007fce95857000)
      libfdk-aac.so.1 => /usr/lib/libfdk-aac.so.1 (0x00007fce955a2000)
      libgstreamer-1.0.so.0 => /usr/lib/libgstreamer-1.0.so.0 (0x00007fce95282000)
      libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007fce95030000)
      libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fce94d22000)
      libgstapp-1.0.so.0 => /usr/lib/libgstapp-1.0.so.0 (0x00007fce94b15000)
      libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x00007fce9489e000)
      libFLAC.so.8 => /usr/lib/libFLAC.so.8 (0x00007fce94628000)
      libmad.so.0 => /usr/lib/libmad.so.0 (0x00007fce94408000)
      libspeex.so.1 => /usr/lib/libspeex.so.1 (0x00007fce941ef000)
      libopus.so.0 => /usr/lib/libopus.so.0 (0x00007fce93f9e000)
      libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007fce93d71000)
      libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007fce93abe000)
      libvorbisfile.so.3 => /usr/lib/libvorbisfile.so.3 (0x00007fce938b5000)
      libgd.so.3 => /usr/lib/libgd.so.3 (0x00007fce93647000)
      libSDL-1.2.so.0 => /usr/lib/libSDL-1.2.so.0 (0x00007fce933ae000)
      libSDL_image-1.2.so.0 => /usr/lib/libSDL_image-1.2.so.0 (0x00007fce93191000)
      libSDL_ttf-2.0.so.0 => /usr/lib/libSDL_ttf-2.0.so.0 (0x00007fce92f8a000)
      libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fce92d1a000)
      libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fce929d8000)
      libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fce927d4000)
      libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fce925be000)
      libc.so.6 => /usr/lib/libc.so.6 (0x00007fce9221d000)
      libpulsecommon-8.0.so => /usr/lib/pulseaudio/libpulsecommon-8.0.so (0x00007fce91f9c000)
      libjson-c.so.2 => /usr/lib/libjson-c.so.2 (0x00007fce91d91000)
      libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007fce91b40000)
      librt.so.1 => /usr/lib/librt.so.1 (0x00007fce91938000)
      /lib64/ld-linux-x86-64.so.2 (0x00007fce98d5c000)
      libz.so.1 => /usr/lib/libz.so.1 (0x00007fce91722000)
      libdb-5.3.so => /usr/lib/libdb-5.3.so (0x00007fce91363000)
      liborc-0.4.so.0 => /usr/lib/liborc-0.4.so.0 (0x00007fce910e3000)
      libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x00007fce90edf000)
      libffi.so.6 => /usr/lib/libffi.so.6 (0x00007fce90cd6000)
      libgstbase-1.0.so.0 => /usr/lib/libgstbase-1.0.so.0 (0x00007fce90a73000)
      libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007fce9081a000)
      libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fce905e5000)
      libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fce90325000)
      libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007fce900e6000)
      libXpm.so.4 => /usr/lib/libXpm.so.4 (0x00007fce8fed4000)
      libvpx.so.3 => /usr/lib/libvpx.so.3 (0x00007fce8f970000)
      libtiff.so.5 => /usr/lib/libtiff.so.5 (0x00007fce8f6ec000)
      libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fce8f4dc000)
      libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fce8f27b000)
      libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fce8f058000)
      libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007fce98ecd000)
      libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x00007fce8ede1000)
      libasyncns.so.0 => /usr/lib/libasyncns.so.0 (0x00007fce8ebdb000)
      libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fce8e9b1000)
      liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fce8e78b000)
      libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fce8e560000)
      libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fce8e35c000)
      libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fce8e156000)
      libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fce8df52000)
      libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007fce8dd3b000)
      liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007fce8db29000)
      libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007fce8d847000)
      libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007fce8d633000)
      libnsl.so.1 => /usr/lib/libnsl.so.1 (0x00007fce8d41b000)
    0 ✓ user@chaos ~/aur/liquidsoap-git $ find /usr/lib | grep -E "libavutil|libswscale"
    /usr/lib/pkgconfig/libswscale.pc
    /usr/lib/pkgconfig/libavutil.pc
    /usr/lib/libswscale.so.4.0.100
    /usr/lib/libavutil.so.55
    /usr/lib/libswscale.so.4
    /usr/lib/libswscale.so
    /usr/lib/libavutil.so
    /usr/lib/libavutil.so.55.17.103

Any idea what I can try?

**Comment by 5chdn** [comment]
If you could give me a short hint, that would be really appreciated. Currently the streaming server is in danger as I can not restart the streams. 

I tried symlinking the missing libraries against the new versions, but it still notices the updated versions.

    0 ✓ root@chaos ~ $ liquidsoap --check
    liquidsoap: error while loading shared libraries: libavutil.so.54: cannot open shared object file: No such file or directory
    127 ✗ root@chaos ~ $ ln -s /usr/lib/libavutil.so /usr/lib/libavutil.so.54
    0 ✓ root@chaos ~ $ liquidsoap --check
    liquidsoap: error while loading shared libraries: libswscale.so.3: cannot open shared object file: No such file or directory
    127 ✗ root@chaos ~ $ ln -s /usr/lib/libswscale.so /usr/lib/libswscale.so.3
    0 ✓ root@chaos ~ $ liquidsoap --check
    liquidsoap: /usr/lib/libavutil.so.54: version `LIBAVUTIL_54' not found (required by liquidsoap)
    liquidsoap: /usr/lib/libswscale.so.3: version `LIBSWSCALE_3' not found (required by liquidsoap)

**Comment by smimram** [comment]
Why don't you simply disable gavl in `PACKAGES`? You certainly don't need it since it is for video.

**Comment by 5chdn** [comment]
THANKS ALOT! I disabled all video extensions and the errors are gone. 

    # ============================================================================
    # Video processing
    # ============================================================================

    # GAVL converts from and to many formats,
    # is very efficient and has a quality setting for
    # tweaking load vs. quality of the conversion.
    # It is the recommended module to use with video
    ###ocaml-gavl

    # FFMPEG is currently only used to convert from
    # and to many formats.
    ###ocaml-ffmpeg

    # Frei0r is a minimalistic plugin API for video sources and filters.
    ###ocaml-frei0r

**Comment by hrefhref** [comment]
I'm experiencing the same issue on Debian Stretch. [Here is the logs from the ffmpeg opam compile](https://gist.github.com/hrefhref/f1bbd93a90a2004cbda244ee938b815d).

I'm running ` opam install taglib mad lame vorbis cry samplerate opus fdkaac flac inotify lame ogg samplerate ssl theora ffmpeg liquidsoap` ; and I've installed libavutil-dev and libswscale-dev as instructed by `depext`.
