### ISSUE TITLE
Multiple station id when switching to live content with fade.final

### ISSUE THREAD

**Issue by dl3ebb** [savonet/liquidsoap#308]
Hi @all,

I am trying to get liquidsoap running and have a problem with station-ids between live content and playlist. I stripped down my script to the minimum to demonstrate the effect. 

After start, liquidsoap runs fine and plays out the songs from the playlist. If I connect from an external client (icecast or shoutcast does not change) the stationid is played twice. 

After the source disconnects the stationid ist played only once. 

I do not know if this is a bug or if I am just to blind to see my fault. 

`#!/usr/bin/liquidsoap

set("log.file",false)

def dj_auth(user,password) = 
  true
end

set("harbor.bind_addr","0.0.0.0")
live=input.harbor(port=8010,auth=dj_auth,"/live")

radio = playlist("~/radio/default.lst")

stationid=single("~/radio/jingles/stationid.mp3")

def trans (old,new) =
  old = fade.final(old)
  s = add([stationid,old])
  sequence([s,new])
end

out (fallback(track_sensitive=false,transitions=[trans,trans],[live,radio]))
`

Attached below you'll find the .liq file and the debug file that was written with log level 5. 

[radio_simple.liq.txt](https://github.com/savonet/liquidsoap/files/165931/radio_simple.liq.txt)
[radio_simple.log.txt](https://github.com/savonet/liquidsoap/files/165930/radio_simple.log.txt)

Anyone there, that is able to help me ?

**Comment by dl3ebb** [comment]
Some more details after sleeping a while and some further testing : 

I added another mp3 as station id of only aprox < 1 sec and this was repeated 8 times. Then I changed the duration of the fade.final to 0.5 seconds and the effect was gone (i.e. the jingle was only played once) 

Then I extended the duration to 10 secs and the stationid was repeated >>10 times. 

So my conclusion is, that the jingle is repeated as long as the fade out buffer is filled. (i.e. fade.final.duration / length of jingle). Is this true and if so : Is there a way to avoid it (except setting the duration to 0.5 secs) ?

**Comment by toots** [comment]
Yeah, although confusing, this seems to be the desired behavior. When adding the sources, tracks for `stationid` are gonna be played in repeat until the other one finishes. A simple way to mitigate is to create a `once` source inside your transition. Something like this:

```
def trans (old,new) =
  old = fade.final(old)
  stationid=once("~/radio/jingles/stationid.mp3")
  s = add([stationid,old])
  sequence([s,new])
end
```

I believe that this should work. Closing this issue, let me know if you need further information.
