### ISSUE TITLE
Unexpected length error after resampling in buffer.adaptative with rolling release 2.2

### ISSUE THREAD

**Issue by hydrosIII** [savonet/liquidsoap#3087]
I am getting a lot of logs when my script is running:
````
13:28:31 [buffer.adaptative.producer_0:3] Unexpected length after resampling: 3527 instead of 3528
````
**Version details**
Liquidsoap 2.2.0+git@57d489745
Debian bullseye
Install method: from package.

Minimal script for testing:
````

log.stdout.set(true)
settings.decoder.decoders.set(["FFMPEG"])
settings.init.allow_root.set(true)

radio = input.ffmpeg(max_buffer=240.0,self_sync=true,"http://espora.org:8000/violetaradio.mp3")


radio = buffer.adaptative(radio,max=240.,buffer=5.0,fallible=true,averaging=60., limit=1.1, reset=true)

output.dummy(mksafe(radio))


````

**Comment by hydrosIII** [comment]
I also tested with another stream an receiving the same results.

````
radio = input.ffmpeg(max_buffer=240.0,"http://stream.radioparadise.com/aac-128")
````

**Comment by hydrosIII** [comment]
Hi i have seen that this has to do with the alsa audio.size.set. The buffer.adaptative somehow defines a different length of package so I get this errors.  Defining resample=false stops the error. However I do not think is a permanent or adequate solution.

**Comment by toots** [comment]
Thanks for reporting. As far as I can tell, we are duplicating samples when this happens. The resampler can sometime keep some samples for the next round of resampling. The strict ringbuffer policy on the `buffer.adaptative` should guarantee that we always stay within reasonable bounds, my guess is that every now and then we will duplicate a sample and then drop it later but overall the signal should be fine.

I'm pushing a commit downgrading this log to debug level and closing this issue. If you hear any audio glitches or artifact, please reopen or submit a new issue and we'll have a closer look.

Thanks!
