### ISSUE TITLE
playlist not working in deamon mode

### ISSUE THREAD

**Issue by daslicht** [savonet/liquidsoap#310]
```
/etc/liquidsoap/radio.liq
#!/usr/bin/liquidsoap
input = mksafe(playlist(mode="normal","./ogg/ogg.m3u"))
output.icecast(%vorbis,
     	host = "localhost", 
	    port = 8000, 
     	password = "*", 
	     mount = "stream.ogg", 
     	input)
# Second transcoder : MP3 128 kbps
output.icecast(%mp3(bitrate=128),
	host ="localhost",
	port = 8000,
	password ="*", 
  	mount = "stream.mp3",
  	input)
```
not working:
```/etc/init.d/liquidsoap start```
no error tho
working:
```sudo -u liquidsoap liquidsoap radio.liq ```

icecast displays the mount points but the playlist seams not start
I just get undefined songs

**Comment by TheSeanBrady** [comment]
Please run this in verbose mode, ie "sudo -u liquidsoap liquidsoap -v radio.liq". You can also chmod +x and run it as ./radio.liq.

**Comment by toots** [comment]
I think this is to be expected. The path to your playlist is relative (starts with `./`), this will not work when running as daemon since the current directory will be changed to `/`.
