### ISSUE TITLE
Compressor doesn't work

### ISSUE THREAD

**Issue by Jookia** [savonet/liquidsoap#3100]
**Describe the bug**

When using a compressor it gives no output at all

**To Reproduce**

This script:

```
threshold = interactive.float("compress_threshold", -10.0)
pregain = interactive.float("compress_pregain", 0.0)
postgain = interactive.float("compress_postgain", 0.0)
ratio = interactive.float("compress_ratio", 0.0)
output.pulseaudio(compress(threshold=threshold, pre_gain=pregain, gain=postgain, ratio=ratio, sine()))
```

**Expected behavior**

A sine wave that can have its peaks compressed

**Version details**

- OS: Arch Linux
- Version: Git

**Install method**

Installed from Git

**Comment by vitoyucepi** [comment]
Hi @Jookia,

`ratio = interactive.float("compress_ratio", 0.0)`
Are you sure about this?
I've never seen a compressor ratio less than `1`.
For example, `ffmpeg -f lavfi -i "sine=frequency=1000:duration=5" -af "acompressor=ratio=0" -y test.wav`
> Value 0.000000 for parameter 'ratio' out of range [1 - 20]

<details>
<summary>I think you should redefine <code>ratio</code> like this</summary>

1. `ratio = interactive.float("compress_ratio", 1., min=1., max=20.)`
2. ```ruby
   ratio = interactive.float("compress_ratio", 1.)
   ratio = {min(20., max(1., ratio()))}`
   ```
3. ```ruby
   def clamp(value, min_value, max_value)
     min(max_value, max(min_value, value))
   end

   ratio = interactive.float("compress_ratio", 1.)
   ratio = {clamp(ratio(), 1., 20.)}
   ```

</details>

**Comment by vitoyucepi** [comment]
Hi @toots,
What's happening with `compress` when calling with `ratio=0.`?
Why it breaks once and for all?
Is it possible to limit the `ratio` to a minimum float greater than `0.` or simply `1.`?

**Comment by Jookia** [comment]
Sorry everyone, I made a 'minimal' test case that was wrong, the ratio was 0 and that caused the issue. But the multiband compressor still doesn't work. Here's one that more faithfully reproduces my error:

```
output.pulseaudio(compress.multiband.interactive(sine()))
interactive.harbor()
```

No sine wave can be heard.

**Comment by vitoyucepi** [comment]
There appears to be an issue with the multiband compressor when the number of `bands` is a multiple of 5.
It didn't work even in *2.0.0*.

**Comment by toots** [comment]
Thanks for the patient analysis y'all. Just pushed a commit raising an error when ratio is less than 1. We'll have to get to the other bug. @smimram is the person to reach out for that I believe.

**Comment by vitoyucepi** [comment]
Hi @toots,

> `Should be greater than 1.`

I think this should be rephrased
- `Should be no less than 1.`
- `Must be at least 1.`
- `Should be 1 or higher.`

**Comment by toots** [comment]
Must is good, just did the change.
