### ISSUE TITLE
Liquidsoap LADSPA plugin

### ISSUE THREAD

**Issue by radioman16** [savonet/liquidsoap#311]
Hi Guys,

I am running Debian 7 Wheezy and am new to Linux !!!

I'm hoping someone can help out here I am having install problems installing the liquidsoap-plugin-ladspa that enables me to use ladspa plugins. When I am attempting to do this I am getting dependency errors:

The following packages have unmet dependencies: liquidsoap-plugin-ladspa : Depends: liquidsoap (= 1.0.1+repack1-1.1) but 1.1 wheezy-sfo-2 is to be installed.

What are my options to fix this error?

Any help will be appreciated, I am a newbie to Linux

Thanks

**Comment by toots** [comment]
Hi @radioman16 

There seems to be an inconsistency with your `apt-get` sources. I'd suggest running `apt-get update` and the uninstall and reinstall liquidsoap.

I'm closing this issue here as we try to focus on liquiddoap-only issues. Hope you find a solution to your problem.
