### ISSUE TITLE
LS 2.2.0+git@af6b0a9cd builds up to using 100% CPU over an hour, catchup and station dropouts follow

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3128]
LS 2.2.0+git@8101608 turned out not to handle ReplayGain correctly (immediately 100% CPU), so we tried LS 2.2.0+git@af6b0a9cd with AzuraCast.

Unfortunately, over about an hour of playing time, LS’s CPU usage built up from around 20% to almost 100% all the time, leading to massive amounts of "We must catchup" errors and Icecast going to fallback after 3s of no data arriving.

Running in a 2 CPU, 4 GB RAM Ubuntu 22.04 LTS VM, with AzuraCast. No steal, no I/O waits, and LS 2.1 worked fine withe same setup. Source material is a mixture of 44.1 kHz/16-bit FLAC as well as MP3s ranging from 128 kbit/s to 320 kbit/s. LS has to feed two streams: 128 kbit/s MP3 and 128 kbit/s AAC.

For details, logs, screenshots and LS configuration file please check https://github.com/AzuraCast/AzuraCast/issues/6316.

I wonder if we have a clock or some runaway issue here.

Be glad if you could take a look, since the station is currently unusable, with fallback dropouts multiple times per song…

**Comment by Moonbase59** [comment]
All new results and findings in the AzuraCast issue.

**Comment by toots** [comment]
I believe that this is fixed in https://github.com/savonet/liquidsoap/commit/dd50b0729c5fbfd83328fcf28f2899b9d7e0cb3c, thanks for reporting!
