### ISSUE TITLE
Map metadata Genre from live input to output genro no effekt

### ISSUE THREAD

**Issue by zoschel** [savonet/liquidsoap#313]
Hello Developer
What i will Do,
Code snipes from my radio.liq
......
live = input.http("http://192.168.10.100:8000/live1")

#From live1 "genre" must be ovewrite the output "genre" if live1 is online

s = fallback(track_sensitive=false,[live,s])

output.icecast(%mp3,
mount="/live",
host="192.168.10.100",
port=8000,
name="***",
genre="Misc", <<<---This must be overwrite from live1 if online
description="****",
url="***",

I found nothing solutions für this, what can i do to solve my porblem?

my version is liquidsoap_1.1.1-7.1 on ubuntu 16.04
MfG

**Comment by zoschel** [comment]
No Answer is an Answer.

**Comment by giflw** [comment]
As I know, the genre can be changed only on media files, but not on outputs. If I understood correctly, you want to be able to change the stream genre on icecast. What are you doing is changing the genre tag of played media. I think that's all you can do.

**Comment by zoschel** [comment]
Hello, Thanx for Answer!
That's what I thought

Am 08.04.2016 um 14:40 schrieb Guilherme I F L Weizenmann:

**Comment by toots** [comment]
@giflw is unfortunately right..

**Comment by giflw** [comment]
Maybe using the admin metadata update URL in icecast ( http://icecast.org/docs/icecast-2.4.1/admin-interface.html). To try that you would need to call the icecast URL using `on_metadata`
