### ISSUE TITLE
Dropouts, fallback when using replaygain due to high CPU usage

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3135]
**Describe the bug**
Referring to https://github.com/AzuraCast/AzuraCast/issues/6316#issuecomment-1582658413, let’s make this a separate issue, so it’s easier to follow up.

When using ReplayGain like
```
# Replaygain Metadata
enable_replaygain_metadata()
radio = replaygain(radio)
```
LS 2.2.0+git@dd50b0729 starts out at ~118% CPU, stays a while at around 100%, sometimes the "AzuraCast Ad" plays and "Source failed" messages appear in the LS log. After about 6 minutes, LS returns to a CPU usage of 12–18% (HLS still enabled). Returning to the lower CPU usage is probably due to almost all of my songs having ReplayGain tags, so no extra calculation is needed.

**To Reproduce**
See logs attached:

[AzuraCast LS Config - RG enabled.txt](https://github.com/savonet/liquidsoap/files/11705618/AzuraCast.LS.Config.-.RG.enabled.txt)

[AzuraCast 7d1b987 LS startup - RG enabled.log](https://github.com/savonet/liquidsoap/files/11705619/AzuraCast.7d1b987.LS.startup.-.RG.enabled.log)

**Expected behavior**
Hopefully less CPU usage when having to calculate replaygain. This is probably not an easy job.

**Version details**

- OS: Ubuntu Server 22.04.2 LTS, AzuraCast running in a Docker container

**Install method**
AzuraCast Docker

**Comment by toots** [comment]
Hi.

This fix: https://github.com/savonet/liquidsoap/commit/b68a9d9a7fe5f16b9637224b4513d26449270f5e makes it possible to reuse existing replaygain tags. 

Operationally, this means that we are on-par with `v2.1.x`. In `v2.1.x` we would require that the `ffmpeg` CLI is available and:
1. Check for metadata via the CLI
2. If not, compute it via the CLI

We now do the same on `rolling-release-v2.2.x` except that it's all internal and does not depend on an external command.

Could you try again with this release and report if you see any significant degradation compared to `v2.1.x`? The expected behavior is that CPU usage should not peak unless a file needs to have replaygain metadata computed (i.e. if it does not have it).

Also, be aware that, in `v2.1.x`, you would not see the CPU usage spiking on the `liquidsoap` process as it was using an external process. However, that external process would have consumed about the same amount of CPU resources and the liquidsoap script would have blocked until it returned. 

I think the right way to check for regression here is:
* Is the station using more CPU _overall_, i.e. with all processes included
* Is the station able to handle the same load/number of radios/output etc.

Thanks for your help with all this!

**Comment by Moonbase59** [comment]
Thank _you_ for fixing all this! :-)

I can confirm that in LS 2.2.0+git@b68a9d9a7 the behaviour is as intended: It only tries to recalc RG when no tag found, see also https://github.com/AzuraCast/AzuraCast/issues/6327#issuecomment-1585741755.

I’m not the best test candidate though, I do have ~156k files but only a few jingles might _not_ have ReplayGain tags, so I will almost never run into the case where LS has to actually _perform the RG calculation_.

**Maybe someone with many untagged files could also test this version please?**

**Comment by toots** [comment]
Hi! Any update on this one? Is it still happening with the latest `rolling-release-v2.2.x`?

**Comment by LordHelmchen666** [comment]
Files are all tagged using loudgain. There are only 12 files not tagged because these are download weekly (Syndication Shows).

I use Azuracast rolling version. This never happend before Azuracast Rolling switched to LS 2.2.x. Maybe i can try it an local VM instance to see how it behaves.

**Comment by toots** [comment]
Ok @LordHelmchen666 could you send me one such file? toots@rastageeks.org

**Comment by LordHelmchen666** [comment]
Could it be that Intel CPUs don't spike that much. The screenshot above is a AMD Opteron 3365. My local CPU is a I7-2600 where i don't see that heavy usage.

**Comment by toots** [comment]
> Files are all tagged using loudgain. There are only 12 files not tagged because these are download weekly (Syndication Shows).

I don't see the replaygain info on these files using our tools:

```shell
dune exec examples/meta.exe -- /tmp/upload/soundtrack_deines_lebens_1.mp3
# Metadata for /tmp/upload/soundtrack_deines_lebens_1.mp3

- comment: Syndications4Readio.de - Weitergabe untersagt.
- comment: Syndications4Readio.de - Weite
- title: Der Soundtrack deines Lebens 1
- artist: Robert Roßbach
- title: Der Soundtrack deines Lebens 1
- artist: Robert Roßbach
- comment: Syndications4Readio.de - Weite
- genre: 0
```

Or with `ffprobe`:

```
ffprobe /tmp/upload/soundtrack_deines_lebens_1.mp3
[...]
Input #0, mp3, from '/tmp/upload/soundtrack_deines_lebens_1.mp3':
  Metadata:
    comment         : Syndications4Readio.de - Weitergabe untersagt.
    ID3v1 Comment   : Syndications4Readio.de - Weite
    title           : Der Soundtrack deines Lebens 1
    artist          : Robert Roßbach
  ```

Without these tags, replaygain values are computed each time the file is decoded.

**Comment by LordHelmchen666** [comment]
Sure you can't find replaygain, because These are files without it. I missunderstood you. *shame* I will send you files with replaygain when in am at home.

**Comment by LordHelmchen666** [comment]
I sent you a file with replaygain tags. Looks like this
```
Input #0, mp3, from '/media/START_AD_BREAK.mp3':
  Metadata:
    title           : START_AD_BREAK
    artist          : START_AD_BREAK
    replaygain_track_gain: 4.83 dB
    replaygain_track_peak: 0.285461
    replaygain_album_gain: -9.72 dB
    replaygain_album_peak: 1.248119
    replaygain_reference_loudness: -18.00 LUFS
    replaygain_track_range: 12.00 dB
    replaygain_album_range: 14.14 dB
  Duration: 00:00:09.67, start: 0.000000, bitrate: 256 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 256 kb/s
    Side data:
      replaygain: track gain - 4.830000, track peak - 0.000007, album gain - -9.720000, album peak - 0.000029,
```
So it would be the best to use loudgain to add tags right after auto download in a bash script?

**Comment by toots** [comment]
Ok I did more cleanup:
* Raised log level for replaygain resolution so what's happening is more visible.
* Also made sure `file.replaygain` does not compute replaygain value when metadata is present.

I was also able to confirm that, with your file, the value is fetched from the metadata, not computed.

I guess we should now make sure that you are in fact running the latest `rolling-release-v2.2.x`. The build with the changes is coming up, I'll ping Buster in the channel.

**Comment by Moonbase59** [comment]
> So it would be the best to use loudgain to add tags right after auto download in a bash script?

@LordHelmchen666 That’s what I’d always prefer, if possible, since it effectively decouples getting/preprocessing syndicated content from its actual broadcast.

You can also be sure to use the same setting for replaygaining, since different tools often use different methods (loudgain, with the suggested ["golden" settings](https://github.com/Moonbase59/loudgain#loudgain-makes-it-easy-following-the-gold-standard), uses true-peak (inter-frame-interpolation) and the EBU-recommended 1 dB headroom).

**Comment by LordHelmchen666** [comment]
@Moonbase59 Thanks. I do it now via bash script now right after download.

@toots Now all files are tagged wit replaygain values. There are no more high CPU usage. But what about users without those tags?

**Comment by toots** [comment]
Thanks @LordHelmchen666 my assumption is that the CPU profile in this case was already like that previously except the load was on the external `ffmpeg` process.

**Comment by SpeedyCharly** [comment]
Adding a bit of meat to this stew pot;
https://github.com/AzuraCast/AzuraCast/issues/6751

**Comment by Moonbase59** [comment]
@SpeedyCharly If it’s not too late: You could steal some code from loudgain’s [rgbpm](https://github.com/Moonbase59/loudgain/blob/master/bin/rgbpm) and [rgbpm2](https://github.com/Moonbase59/loudgain/blob/master/bin/rgbpm2) helper scripts.
