### ISSUE TITLE
LS 2.2.0+git@b68a9d9a7: Can’t get `video.add_text()` to work

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3138]
**Describe the bug**
Following the docs at https://www.liquidsoap.info/doc-dev/video.html#scrolling-text, I’m trying to add some text to a video but can’t get it to work. This is in preparation of setting up a video stream for AzuraCast, with overlayed metadata shown.

**To Reproduce**
Minimal script:
```
video = video.testsrc()
radio = playlist("/home/matthias/Musik/Oldies.m3u")

videostream = mux_video(video=video, radio)
videostream = video.add_text("Hi there!", videostream)

set("frame.video.width", 640)
set("frame.video.height", 360)
output.pulseaudio(fallible=true, videostream)
output.sdl(fallible=true, videostream)
```

I get this error:
```
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
At test2.liq, line 6, char 14-19:
videostream = video.add_text("Hi there!", videostream)

Error 5: 
this value has no method `add_text`
  Its type is source(video='B, 'A)
.{
  buffered : () -> [string * float],
  duration : () -> float,
  elapsed : () -> float,
  fallible : bool,
  id : () -> string,
  is_active : () -> bool,
  is_ready : () -> bool,
  is_up : () -> bool,
  last_metadata : () -> [string * string]?,
  log : 
  {level : (() -> int?).{set : (int) -> unit}
  },
  on_metadata : ((([string * string]) -> unit)) -> unit,
  on_shutdown : ((() -> unit)) -> unit,
  on_track : ((([string * string]) -> unit)) -> unit,
  on_wake_up : ((() -> unit)) -> unit,
  remaining : () -> float,
  seek : (float) -> float,
  self_sync : () -> bool,
  skip : () -> unit,
  time : () -> float
}.
```

Using `video.add_text.sdl` instead gives the same error, commenting out the line
```
videostream = video.add_text("Hi there!", videostream)
```
makes it play (without text, of course).

**Expected behavior**
Text overlayed on video.

**Version details**

- OS: Linux Mint 21.1
- LS Version: 2.2.0+git@b68a9d9a7

**Install method**
`.deb` from https://github.com/savonet/liquidsoap-release-assets/releases/download/rolling-release-v2.2.x/liquidsoap-b68a9d9_2.2.0-ubuntu-jammy-1_amd64.deb

---

I also tried @BusterNeece’s script at https://gist.github.com/BusterNeece/5dbfb4dbc1846055c9ab07a7c685899c, to no avail.

**Comment by toots** [comment]
This is fixed in https://github.com/savonet/liquidsoap/pull/3139. Rolling release build: https://github.com/savonet/liquidsoap/actions/runs/5236324382

**Comment by Moonbase59** [comment]
Hm. LS 2.2.0+git@64732ea7a gets me exact the same error. Btw, `video.add_image()` does also not work.

**Comment by smimram** [comment]
The problem here comes from the fact that you are defining a variable named `video` (bound to `video.testsrc`): because of this you don't have access anymore to `video.add_text` which calls the method `add_text` of video. The solution is simple: rename your variable to something else like `v`:
```
v = video.testsrc() # MAIN CHANGE IS HERE!!
#v = single("/home/matthias/media/videostream/video.mp4")
radio = playlist("/home/matthias/Musik/Oldies.m3u")
radio = amplify(1.,override="replaygain_track_gain",radio)

videostream = mux_video(video=v, radio)

# This errors out:
videostream = video.add_text("Hi there!", videostream)

# This errors out:
#videostream = video.add_image(width=30, height=30, x=10, y=10, file="niteradio-cover.png", videostream)

set("frame.video.width", 640)
set("frame.video.height", 360)
#output.pulseaudio(fallible=true, videostream)
#output.sdl(fallible=true, videostream)
output.audio_video(videostream)
```

**Comment by Moonbase59** [comment]
Darn. Thanks for the explanation! I somehow fear I’ll _never_ get my head around OCaml…

**Comment by smimram** [comment]
You'll manage at some point :) And BTW this not OCaml, liquidsoap is an original language! (which happens to be implemented in OCaml)
