### ISSUE TITLE
Flows! service is down again!

### ISSUE THREAD

**Issue by biguenique** [savonet/liquidsoap#314]
I love liquidsoap, and I love Flows! 

But the Flows! service is down again: http://flows.liquidsoap.fm/

I'm pretty sure I'm not the only one operating a webradio that relies on the Flows! API... Not only it's handy, it's also a nice centralized place to show off our liquidsoap stations. How can we collectively make sure that Flows! stays up and running in the future? I guess making donations would help cover the cost of hosting...

Can we still send donations through https://sourceforge.net/donate/index.php?group_id=89802 ?

Thanks for you help!

**Comment by toots** [comment]
Yes, you can still send donations :-)

Flows has been back for about a week now..
