### ISSUE TITLE
Issues with console colors when getting help

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#3140]
When I type
```
liquidsoap -h video.add_text
```
I get
![image](https://github.com/savonet/liquidsoap/assets/2012073/bdce9493-dd08-430b-9a30-605d8237a6ed)

Note that
1. the description of the function is in gray which makes it not particularly readable
2. the beginning of the type is mangled by the description of the function

**Comment by Moonbase59** [comment]
Thanks for taking care of "the little helpers", too! To be honest, without all that (and the docs) the language is still hard to grasp…

**Comment by toots** [comment]
@smimram what happens with `opam`? They use the same bold white color:

<img width="739" alt="Screenshot 2023-06-26 at 6 24 15 PM" src="https://github.com/savonet/liquidsoap/assets/871060/b0279d93-5df0-4d55-a706-fbe70c6efd3f">

**Comment by smimram** [comment]
Much more readable:
![image](https://github.com/savonet/liquidsoap/assets/2012073/9b3d8a54-03cd-4721-a2f7-856c363ad89a)
