### ISSUE TITLE
LS 2.2.0+git@dcf405ff4: Installation from `.deb` works but has errors

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3148]
**Describe the bug**
When installing the LS 2.2.0+git@dcf405ff4 `.deb` from https://github.com/savonet/liquidsoap-release-assets/releases/download/rolling-release-v2.2.x/liquidsoap-dcf405f_2.2.0-ubuntu-jammy-1_amd64.deb, it installs, but shows errors:

```
$ LC_ALL=C sudo apt install ~/Downloads/liquidsoap-dcf405f_2.2.0-ubuntu-jammy-1_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'liquidsoap-dcf405f' instead of '/home/matthias/Downloads/liquidsoap-dcf405f_2.2.0-ubuntu-jammy-1_amd64.deb'
Suggested packages:
  icecast2 awscli
The following NEW packages will be installed:
  liquidsoap-dcf405f
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/11.4 MB of archives.
After this operation, 46.3 MB of additional disk space will be used.
Get:1 /home/matthias/Downloads/liquidsoap-dcf405f_2.2.0-ubuntu-jammy-1_amd64.deb liquidsoap-dcf405f amd64 1:2.2.0-ubuntu-jammy-1 [11.4 MB]
Selecting previously unselected package liquidsoap-dcf405f.
(Reading database ... 630368 files and directories currently installed.)
Preparing to unpack .../liquidsoap-dcf405f_2.2.0-ubuntu-jammy-1_amd64.deb ...
Unpacking liquidsoap-dcf405f (1:2.2.0-ubuntu-jammy-1) ...
Setting up liquidsoap-dcf405f (1:2.2.0-ubuntu-jammy-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for doc-base (0.11.1) ...
Processing 1 added doc-base file...
Error in `/usr/share/doc-base/liquidsoap-dcf405f.liquidsoap', line 9: all `Format' sections are invalid.
Note: `install-docs --verbose --check file_name' may give more details about the above error.
```

I’m a little unsure what might be affected. Since these are used for installation within _AzuraCast_, it’d be nice to have a clean install.

**To Reproduce**
See above.

**Expected behavior**
Clean installation.

**Version details**

- OS: Linux Mint 21.1
- LS Version: 2.2.0+git@dcf405ff4

**Install method**
`.deb` from the release assets, using `apt install` (not `dpkg -i`) because apt will remove older versions automatically and is thus easier to use (I’m lazy).

**Comment by toots** [comment]
The `doc-base` file format has changed. The html doc are still provided by the package. I'm not so sure if we want to ship the HTML doc with the package anymore, we haven't checked on this particular build, if the rendered HTML looks good in a browser and etc.

Some of the debian packages date back from a time with different connectivity assumptions and etc. I believe that, nowadays, most people consume HTML data via a browser pointing to an online website, not local files. 

We keep the doc always updated online and, for these reasons, I'm tempted to make this the main source for HTML documentation, not the binary package local doc.

**Comment by vitoyucepi** [comment]
> The `doc-base` file format has changed.

Are you sure?
```
Document: liquidsoap
Title: Liquidsoap documentation
Author: The Savonet Team
Abstract: Liquidsoap documentation
Section: Network/Communication

Format: HTML
Index: /usr/share/doc/liquidsoap/html/index.html
Files: /usr/share/doc/liquidsoap/html/*
```

Here's a `/usr/share/doc-base/doc-base`
```
Title: Debian doc-base Manual
Author: Christian Schwarz
Abstract: This manual describes what doc-base is and how it can be used to
 manage online manuals on Debian systems.
Section: Debian

Format: text
Files: /usr/share/doc/doc-base/doc-base.txt.gz

Format: HTML
Index: /usr/share/doc/doc-base/doc-base.html/index.html
Files: /usr/share/doc/doc-base/doc-base.html/*.html
```

**Comment by toots** [comment]
Hmm maybe not. At any rate, the underlying situation is that I believe the HTML shouldn't be shipped at all. It's already not shipping by the alpine package and I just removed it from https://github.com/savonet/liquidsoap/pull/3143

**Comment by vitoyucepi** [comment]
Maybe you're right. Because both yelp and khelpcenter doesn't support doc-base.
