### ISSUE TITLE
Alsa error: Invalid argument error on liquidsoap script

### ISSUE THREAD

**Issue by serogrip** [savonet/liquidsoap#315]
Alsa error: Invalid argument error on liquidsoap script
## **1. I made sound config like this at /home/account/.asoundrc**

pcm.left {
type plug
slave.pcm "hw:0"
slave.channels 2
ttable.0.0 1
}

pcm.right {
type plug
slave.pcm "hw:0"
slave.channels 2
ttable.0.1 1
}

---
1. testing speaker-test program
## working find like this

speaker-test 1.0.25

Playback device is plug:left
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 16 to 16384
Period size range from 15 to 16385
Using max buffer size 16384
Periods = 4
was set period_size = 4096
was set buffer_size = 16384
 0 - Front Left
Time per period = 2.524128
 0 - Front Left
1. try with liquidsoap script
## test.liq script
# !/usr/bin/liquidsoap -v

set("log.file.path","/home/user/a.log")
songs = playlist(id="custom", mode='randomize',reload=1, reload_mode="rounds","/home/user/music")
output.alsa(device="plug:left", mksafe(songs))
## error shows

Thread 4 killed on uncaught exception Alsa.Invalid_argument
Raised at file "pcre.ml", line 829, characters 14-76
## log files

016/04/03 13:49:47 [mksafe:3] Switch to custom with transition.
2016/04/03 13:49:47 [alsa_out(plug:left):3] Using ALSA 1.0.25.
2016/04/03 13:49:47 [alsa_out(plug:left):3] Samplefreq=44100Hz, Bufsize=15052B, Frame=4B, Periods=1076
2016/04/03 13:49:47 [threads:1] Thread "alsa_out(plug:left)" aborts with exception Alsa error: Invalid argument!
2016/04/03 13:49:47 [threads:3] Raised by primitive operation at file "", line 0, characters 0-0
2016/04/03 13:49:47 [main:3] Shutdown started!
2016/04/03 13:49:47 [main:3] Waiting for threads to terminate...
2016/04/03 13:49:47 [custom:3] Finished with "/home/user/music/test.mp3".
2016/04/03 13:49:47 [clock.wallclock_alsa:3] Streaming loop stopped.
2016/04/03 13:49:47 [threads:3] Thread "wallclock_alsa" terminated (0 remaining).
2016/04/03 13:49:47 [main:3] Cleaning downloaded files...
2016/04/03 13:49:47 >>> LOG END

**Comment by S54B32** [comment]
Have you tried accessing the device using the hw ID rather than plug:left?

**Comment by serogrip** [comment]
thank you for your comment 
.
hw ID addressing working fine.

but I want make 2 sound play 1 sound card.

I make virtual sound card left and right with .asoundrc file.
-------------------------------------------------------------------------
speaker-test -D left command working file even mpg123

but liquidsoap can't play virtual sound card.

how can I address left speaker for play 1 channel?

**Comment by toots** [comment]
Hi,

If the sample rate for alsa is set to `4800Hz` with no conversion, have you tried to also set liquidsoap to that sampling rate?

`set("frame.audio.samplerate",48000)`

Should do it..
