### ISSUE TITLE
Installation Liquidsoap 2.2.0

### ISSUE THREAD

**Issue by rgriep** [savonet/liquidsoap#3151]
Hi, 

I get an error while installing Liquidsoap 2.2.0 that I can't solve.

The error is : 
The following dependencies couldn't be met:
  - liquidsoap → mm >= 0.8.4
      no matching version

I tried to update but I didn't find the solution.

Please, can someone help me. how to do it?

Rob

**Comment by smimram** [comment]
you need to install it from git: https://github.com/savonet/ocaml-mm (this was not released yet)

**Comment by rgriep** [comment]
Thank you so much for the fast answer and it works well!

I updated a lot, what went well but I  get another error now.

The following dependencies couldn't be met:
  - liquidsoap → liquidsoap-lang
      unknown package

The normal way of installing it via opam doesn't work. Do you have a tip again for me?

Best regards,
Rob

**Comment by toots** [comment]
Hi @rgriep

You should try to pin from git too:

```shell
opam pin -ny git+https://github.com/savonet/liquidsoap
opam install liquidsoap
```

**Comment by rgriep** [comment]
Hi @toots 

Thank you for the answer. I get the next error 

The following actions will be performed:
  ∗ install liquidsoap 2.2.0*

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of liquidsoap failed at "/root/.opam/opam-init/hooks/sandbox.sh build dune build -p liquidsoap -j 3 --promote-install-files=false @install".

#=== ERROR while compiling liquidsoap.2.2.0 ===================================#
# context     2.0.9 | linux/x86_64 |  | pinned(git+https://github.com/savonet/liquidsoap#4cc07515)
# path        ~/.opam/default/.opam-switch/build/liquidsoap.2.2.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p liquidsoap -j 3 --promote-install-files=false @install
# exit-code   1
# env-file    ~/.opam/log/liquidsoap-2728076-d0f245.env
# output-file ~/.opam/log/liquidsoap-2728076-d0f245.out
### output ###
# File "dune", line 1, characters 0-493:
#  1 | (rule
#  2 |  (target liquidsoap.config)
#  3 |  (deps ./src/bin/liquidsoap.exe)
# ....
# 16 |    (with-stdout-to
# 17 |     %{target}
# 18 |     (run ./src/bin/liquidsoap.exe --opam-config)))))
# Error: No rule found for src/bin/liquidsoap.exe



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build liquidsoap 2.2.0
└─
╶─ No changes have been performed

Do you have a solution? Or what do I have to do more?

Best regards,
Rob

**Comment by toots** [comment]
Hi @rgriep. It looks like your `opam` version is too old. Could you try to update to version 2.1?
