### ISSUE TITLE
ID3v2 metadata in HLS streams

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#3153]
### Discussed in https://github.com/savonet/liquidsoap/discussions/3152

<div type='discussions-op-text'>

<sup>Originally posted by **fkane** June 16, 2023</sup>
Hi, I'm trying to integrate my station's HLS stream into Sonos devices. In order to display metadata such as artist, title, and cover art, they require it to be embedded in ID3v2 frames, and have specific requirements on how to embed URL's to the album art.

Is there any existing mechanism for embedding ID3v2 metadata into HLS streams, and any existing hooks I can use to implement the WXXX tag for a URL to the album art in the way they want?

Their requirements are [here](https://developer.sonos.com/build/content-service-add-features/supported-audio-formats/), and pasted below for convenience:

For HLS content, use [ID3v2 frames](http://id3.org/id3v2.3.0#Declared_ID3v2_frames) for metadata, as defined in the [ID3 tag version 2.3.0 documentation](http://id3.org/id3v2.3.0). Sonos players read the following ID3v2 tags:

COMM—comments
PRIV—private frame
TALB—album/move/show
TCMP—iTunes compilation
TCOM—composer
TCON—content type
TIT2—title/song name/content
TPE1—lead performer, soloist
TPE2—band/orchestra
TPOS—part of a set
TRCK—track number
WXXX—user defined url link

Use the WXXX tag if you want your stream to have artwork that changes, like an Internet radio stream that changes artwork for each song. We use this tag to specify the size of the artwork and the URL. To do this, you must separate these strings with a null character, such as \0. The first string should start with “artworkURL_” followed by the width of the image in pixels and “x”. For example, this string will be set to “artworkURL_640x” for an image that is 640 pixels wide. The second string should be the full album art URI (example: http://server/path/art.jpg”). Together, the strings would look like this: “artworkURL_640x\0http://example.com/artwork/1341414.jpg”.</div>

**Comment by Moonbase59** [comment]
I haven’t yet checked what’s possible with HLS, just keep in mind there are people using other formats than MP3 (AAC, OGG, FLAC, …) that use different tagging schemes.

Also, the ID2v2 `WXXX` tags do have some drawbacks, for instance the URL needs to be encoded in ISO-8859-1, and (at least in ID3v2.4) there can be a multitude of `WXXX` tags for different purposes. The above is a _very Sonos-specific_ solution.

From the [_Mutagen_ docs](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#wxxx), since [id3.org](https://id3.org/) has been unavailable for a long time now:

> This frame is intended for URL [URL] links concerning the audio file in a similar way to the other “W”-frames. The frame body consists of a description of the string, represented as a terminated string, followed by the actual URL. The URL is always encoded with ISO-8859-1 [ISO-8859-1]. There may be more than one “WXXX” frame in each tag, but only one with the same description.

```
<Header for 'User defined URL link frame', ID: "WXXX">
Text encoding     $xx
Description       <text string according to encoding> $00 (00)
URL               <text string>
```

**Comment by vitoyucepi** [comment]
It's not clear to me how sonos use id3 tags.
If you'll check the development documentation about [hls](https://developer.sonos.com/build/content-service-add-features/supported-audio-formats/http-live-streaming-hls/), then you should see
> Sonos supports the following for HLS:
> 
> - MIME/media types: application/x-mpegURL, application/vnd.apple.mpegurl, audio/mpegurl
> - Codecs and profiles: AAC-LC, HE-AAC, HEv2-AAC
> - Container format: MPEG-TS, MPEG-4
> - Playlist formats: m3u and m3u8
> - Sample rates: 48 kHz or lower
> ### Not supported
> - Video. If the HLS stream or track has embedded video, the Sonos player attempts to find the audio stream. But audio playback may not work. This could also cause performance issues as the player would have to download the video as well.
> - We do not support AAC SSR, AAC Main, and MP3 under HLS.
Explicit tags on tracks within a stream. You can tag containers, so we recommend tagging any HLS stream that may play explicit content. See [Tag & filter explicit content](https://developer.sonos.com/build/content-service-add-features/tag-filter-explicit-content/) for details.

**Comment by toots** [comment]
The HLS spec actually has a section for ID3 tags, I guess I should have paid more attention: https://datatracker.ietf.org/doc/html/rfc8216#section-3.4

The implementation is almost ready, I need to add more tests and check on stream validity with various players.

**Comment by mojikosu** [comment]
Hi all,

@toots 
Have you figured out a way to achieve the WXXX injection to include coverart, meanwhile?

I have been successful so far as to formulate the coverart successfully as is required by SONOS. However, I cannot wrap my head around how to feed the WXXX tag with the respective url into the stream, so the HLS output shows the coverart on SONOS.

Many thanks in advance and best regards.

**Comment by toots** [comment]
Hi @mojikosu !

Exported metadata are filtered using the `settings.encoder.metadata.export` settings: https://www.liquidsoap.info/doc-2.2.5/settings.html#exported-metadata

`WXXX` frames are mapped internally to the `url` metadata:
```ocaml
let frame_id_of_string = function
  | "comment" -> Some `COMM
  | "album" -> Some `TALB
  | "bpm" -> Some `TBPM
  | "composer" -> Some `TCOM
  | "content" -> Some `TCON
  | "copyright" -> Some `TCOP
  | "date" -> Some `TDAT
  | "encoder" -> Some `TENC
  | "title" -> Some `TIT2
  | "language" -> Some `TLAN
  | "length" -> Some `TLEN
  | "performer" -> Some `TOPE
  | "artist" -> Some `TPE1
  | "band" -> Some `TPE2
  | "publisher" -> Some `TPUB
  | "tracknumber" -> Some `TRCK
  | "year" -> Some `TYER
  | "url" -> Some `WXXX
  | v -> Metadata.ID3v2.frame_id_of_string v
```
However, you should also be able to use `WXXX`, it will be mapped to the correct id3 frame.

So, looks like you can do one of two things:
1. Use `url` and add `"url"` to the list of exported metadata
2. Use `WXXX` and add `"WXXX"` to the list of exported metadata

**Comment by mojikosu** [comment]
Hi @toots ,

Thanks for your quick reply! I'll dig into this!
Best regards!
