### ISSUE TITLE
Where is pervasives.liq in opam install

### ISSUE THREAD

**Issue by vrtisworks** [savonet/liquidsoap#316]
When I install liquidsoap 1.2.0 from opam, where do I need to put the pervasives.liq and other included scripts?

Is there some way to find out where it is looking?  or to set it?

I tried looking at confg-dump, but didn't see anything that looked like a setting for the include library.

Thanks.

**Comment by toots** [comment]
If you look at `liquidsoap -h`, the `--no-pervasives` options should tell you that:

```
  --no-pervasives
	  Do not load pervasives script libraries (i.e.,
	  /Users/toots/.opam/4.02.3/lib/liquidsoap/lib/liquidsoap/1.2.0/*.liq).
``
