### ISSUE TITLE
Allow dynamic file name in `video.add_image` 

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3178]
**Is your feature request related to a problem? Please describe.**
It would be really helpful if the file name in the function `video.add_image` could be set dynamically.

**Describe the solution you'd like**
`video.add_image` is defined as
```
(
  ?id : string?,
  ?width : {int}?,
  ?height : {int}?,
  ?x : {int},
  ?y : {int},
  file : string,
  source(video=canvas('a), 'b)
) -> source(video=canvas('a), 'b)
```
I would like to call it like
```ruby
image = ref("image.png")

s = video.testsrc()
s = video.add_image(x=50, y=50, width=100, height=100, file=image, s)

output.dummy(s)
```
The function should be defined like
```
(
  ?id : string?,
  ?width : {int}?,
  ?height : {int}?,
  ?x : {int},
  ?y : {int},
  file : {string},
  source(video=canvas('a), 'b)
) -> source(video=canvas('a), 'b)
```

**Describe alternatives you've considered**
N/A

**Additional context**
Ref: #3177
https://github.com/savonet/liquidsoap/blob/08d70be8e505b5c2528cda963448364ce961f64e/src/libs/video.liq#L50-L62

**Comment by Moonbase59** [comment]
@toots Should you implement this, could you please build it so it becomes a release-asset, so that I can grab the `.deb` and test it, and @BusterNeece can implement it in AzuraCast?

**Comment by Moonbase59** [comment]
Just a thought: If this isn’t done easily, maybe we could add the `set` method `image` already has?
