### ISSUE TITLE
Black video produced from image

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3194]
**Describe the bug**
Liquidsoap produces black screen instead of image.

**To Reproduce**
```ruby
video = single("image.png")
enc = %ffmpeg(format="mpegts", %video(codec="libx264"))
output.harbor.hls([("test", enc)], video)
```

Image in archive: [image.tar.gz](https://github.com/savonet/liquidsoap/files/11984033/image.tar.gz)
sha256sum: `52456eb824b34669c7d8239046ab036c62a05856afae9d2c985c00dabbad534e  image.png`

**Expected behavior**
Image displayed correctly.

**Version details**

- OS: debian in docker
- Version: *savonet/liquidsoap:rolling-release-v2.2.x-b0db4b0*

**Install method**
container from https://hub.docker.com/r/savonet/liquidsoap

**Common issues**
N/A

**Comment by toots** [comment]
Thanks for reporting! I can confirm that the issues is coming from the `sdl` image decoder. 

Adding this fixes the issue:
```liquidsoap
settings.decoder.image_file_decoders := ["ffmpeg"]
```
Also, the minimal binaries should work fine.

**Comment by vitoyucepi** [comment]
@smimram
> Image in archive: [image.tar.gz](https://github.com/savonet/liquidsoap/files/11984033/image.tar.gz)
> sha256sum: `52456eb824b34669c7d8239046ab036c62a05856afae9d2c985c00dabbad534e  image.png`
