### ISSUE TITLE
Test pattern fix fa5d11f doesn’t work

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3205]
**Describe the bug**
In fa5d11f, more test patterns were added but they don’t work:

```
v = video.testsrc.ffmpeg(pattern="pal75bars")
```

Result:

```
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
At error.liq, line 26, char 2-33:

Error 14: Uncaught runtime error:
type: failure,
message: "invalid pattern for video.testsrc.ffmpeg",
stack: at error.liq, line 26, char 2-33,
at error.liq, line 26, char 2-33,
at ffmpeg.liq, line 171, char 84-136,
at ffmpeg.liq, line 171, char 2-140,
at test4.liq, line 7, char 4-45
```
**To Reproduce**
See above.

**Expected behavior**
All (defined) patterns working.

**Version details**

- OS: Linux Mint 21.1, Ubuntu 22.04.2 LTS Server
- LS Version: 2.2.0+git@0a90fcf99

**Install method**
`.deb` from release-assets

**Comment by toots** [comment]
It's fixed. Also at least for me the whole input wasn't working at all. Should be fixed with the latest builds.
