### ISSUE TITLE
Reopening of `output.file` is messy

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#3206]
I really don't like the new `should_reopen` argument of `output.file`.  The [migration doc](https://www.liquidsoap.info/doc-dev/migrating.html#reopen_-arguments-in-output.file-and-similar) makes it clear. What used to be
```
output.file(%mp3, {time.string("archive/%Y-%m-%d/%H-%M-%S.mp3")}, radio, reopen_when={0m})
```
is now
```
# Use a ref to reload only once on minute 00:
has_reloaded = ref(false)

def should_reload(~metadata, ~restart) =
  if null.defined(metadata) or null.defined(restart) then
    null()
  elsif 00m and not has_reloaded() then
    has_reloaded := true
    0.
  else
    if not 00m then
      # Reset has_reloaded
      has_reloaded := false
    end
    null()
  end
end
output.file(%mp3, {time.string("archive/%Y-%m-%d/%H-%M-%S.mp3")}, radio, should_reopen=should_reload)
```
This is crazy. Can we get back to the old arguments please? Nobody will use that...

Also the migration mentions `should_reload` instead of `should_reopen`.

**Comment by toots** [comment]
I agree. Let's fix this before the release.
