### ISSUE TITLE
Type constraints are not showing in the doc

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#3212]
The type of `sine` is currently
```
(?id : string?, ?amplitude : {float}, ?duration : float?, ?{float}) -> source(audio='a)
```
The target (`source(audio='a)`) makes us think that it can generate audio in any format, including compress, which I don't think it can (and I suspect that I could make the evaluation crash with this...)

**Comment by toots** [comment]
That's intended. The reason it's confusing is b/c type constraints are not displayed in the doc. This is actually `'a where 'a is one of: pcm, pcm_f32 or pcm_s16`. This is because the operator can generate any of these types.

**Comment by toots** [comment]
<img width="639" alt="Screenshot 2023-07-12 at 6 33 40 PM" src="https://github.com/savonet/liquidsoap/assets/871060/1a4949e9-5e1f-44f9-9c8e-8ac5543c0bd7">

**Comment by smimram** [comment]
A slight suggestion: could we come up with a more readable notation like `pcm+` for this kind of constraints (which is going to be quite widespread I think)?
