### ISSUE TITLE
Decode ogg vorbis input harbor

### ISSUE THREAD

**Issue by maurodelazeri** [savonet/liquidsoap#323]
I'm trying to decode ogg on my input harbor, but does not work

**It works well to decode aac**
def test_ffmpeg(file) = -1 end
ffmpeg_p = "/usr/bin/ffmpeg -i - -f wav -"
add_decoder(name="FFMPEG",description="Decode files using the ffmpeg decoder binary",mimes=["audio/aacp"],test=test_ffmpeg,ffmpeg_p)
set("decoder.stream_decoders",["FFMPEG"])

**Does not work to decode ogg**
def test_ffmpeg(file) = -1 end
ffmpeg_p = "/usr/bin/ffmpeg -i - -f ogg -"
add_decoder(name="FFMPEG",description="Decode files using the ffmpeg decoder binary",mimes=["audio/ogg"],test=test_ffmpeg,ffmpeg_p)
set("decoder.stream_decoders",["FFMPEG"])

**My system packges**
root@source:/home/ubuntu/live# dpkg -l | grep libtheora
ii  libtheora-dev:amd64                         1.1.1+dfsg.1-3.2                        amd64        Theora Video Compression Codec (development files)
ii  libtheora0:amd64                            1.1.1+dfsg.1-3.2                        amd64        Theora Video Compression Codec
root@source:/home/ubuntu/live# dpkg -l | grep libvorbis
ii  libvorbis-dev:amd64                         1.3.4-2~trusty1                         amd64        development files for Vorbis General Audio Compression Codec
ii  libvorbis0a:amd64                           1.3.4-2~trusty1                         amd64        decoder library for Vorbis General Audio Compression Codec
ii  libvorbisenc2:amd64                         1.3.4-2~trusty1                         amd64        encoder library for Vorbis General Audio Compression Codec
ii  libvorbisfile3:amd64                        1.3.4-2~trusty1                         amd64        high-level API for Vorbis General Audio Compression Codec

**liquidsoap**
ocaml-ogg
ocaml-vorbis

**Comment by maurodelazeri** [comment]
I got the solution

add_decoder(
	name="FFMPEG",
	description="Decode audio files using the ffmpeg/avconv decoder binary",
	test=fun(file) -> -1,
	"$(which ffmpeg || which avconv) -loglevel panic -i - -f wav -"
)

set("decoder.file_decoders", ["META","WAV","IMAGE","FLAC","MAD","OGG","XMP","FFMPEG","GSTREAMER"])

**Comment by toots** [comment]
Just curious: why do you want to use ffmpeg and not the built in decoders?

**Comment by maurodelazeri** [comment]
@toots I just know how to make it with ffmpeg, can I make it differently?

**Comment by toots** [comment]
Well, liquidsoap should be able to natively decode vorbis and wav files for sure..

**Comment by maurodelazeri** [comment]
You are right @toots, the problem was that I missed some extensions after fix it, works well without use ffmpeg
