### ISSUE TITLE
[v2.2.0] Crashing when using remote playlists

### ISSUE THREAD

**Issue by charles-rc** [savonet/liquidsoap#3239]
**The bug**
First off, thank you very much for liquidsoap. It's an awesome piece of software and I am loving learning how to use it.

I am trying to create a simple script which creates two playlist sources and chooses which to play in a switch statement based on a predicate. The audio is outputted to icecast. The playlists are remote files stored in Cloudflare R2. The files described within the playlists are also remote files stored in R2.

When I run the script with v2.1.4 everything works as expected. When I used a 2.2.0 rolling release then liquidsoap crashes.

The logs show errors like `Source stream_mp3 failed while streaming: Invalid_argument("index out of bounds")!` and `Failed to find a file extension for https://pub-af7f6f17ab9d4cc8809a3c34057da4b1.r2.dev/Gansu.mp3.`.

I am using Supervisord to run icecast and liquidsoap. It attempts to restart liquidsoap when it crashes. It restarts and crashes 3-4 times and then everything seems to be fine. 

I have attached the logs to this issue in case that helps!
[crash.txt](https://github.com/savonet/liquidsoap/files/12079821/crash.txt)

**To Reproduce**
```
#!/usr/bin/env liquidsoap

%include "passwords.liq"

# allow root access (for now)
settings.init.allow_root.set(true)

# Open up harbor server
settings.harbor.bind_addrs.set(["0.0.0.0"])

# Use the telnet server for requests
settings.server.telnet.set(true)

# We fall back to empty noise
emptyNoise = blank()

# A live stream (e.g. via BUTT or Mixxer)
# TODO - auth
live = input.harbor("live",port=9000,password="hackme",user="icecast")

shouldWePlayA = ref(true)

playlistA = playlist(id="playlistA", "https://pub-af7f6f17ab9d4cc8809a3c34057da4b1.r2.dev/test-a.m3u")
playlistB = playlist(id="playlistB", "https://pub-af7f6f17ab9d4cc8809a3c34057da4b1.r2.dev/test-b.m3u")

def transition(a,b) =
  log("transition called...")
  add(
    normalize=false,
    [
      sequence([
        blank(duration=0.01),
        fade.in(duration=0.5, b)
      ]),
      fade.out(duration=0.5, a)
    ]
  )
end

# Switch between the tracks depending on the boolean
s = switch(id="playlistSwitch", track_sensitive=false, transitions=[transition, transition], [(shouldWePlayA, playlistA), ({ true }, playlistB)])

radio = mksafe(fallback(track_sensitive=false,
                 [live, s, emptyNoise]))

output.icecast(
    %mp3(bitrate=32, samplerate=22050, stereo=false),
    host = "localhost", port = 8000,
    password = icecastPassword, mount = "stream.mp3",
    radio
)
```

**Version details**
- OS: Running inside a Docker container built with linux/arm64 ubuntu:jammy
- Version: liquidsoap-5aee24d_2.2.0-ubuntu-jammy-1_arm64.deb (seems to happen with other 2.2 releases I have tried)

**Comment by Russsgithub** [comment]
There's an extra "." on the MP3 path in the playlist, which to me looks why your getting that error.

"https://pub-af7f6f17ab9d4cc8809a3c34057da4b1.r2.dev/Gansu.mp3."

**Comment by toots** [comment]
Thanks for reporting, great timing!

The `.` at the end of the URL was a logging artifact. The real problem was an issue in the layer that connects runtime source and track content with the types computed at typecheck.

This should be fixed with https://github.com/savonet/liquidsoap/pull/3240

**Comment by charles-rc** [comment]
Thank you! You're too quick! It seems to be working with the latest version - `1b8e317`.
