### ISSUE TITLE
Question: change log directory at compile time

### ISSUE THREAD

**Issue by rmens** [savonet/liquidsoap#325]
After compiling liquidsoap with:

``` ./configure --enable-debugging --disable-graphics --with-user=liquidsoap --with-group=liquidsoap --sysconfdir=/etc ```

It seems to create te default logging dir ``` /usr/local/var/log/liquidsoap ``` but i'd like that to be ``` /var/log/liquidsoap ``` and couldn't find a configure parameter to pass. Any idea how to do this?

**Comment by S54B32** [comment]
Creating the /var/log/liquidsoap directory and setting your scripts to log to that directory would accomplish the same thing

Is there a reason you want to do this at compilation rather than after? 
```
set("log.file", true)
set("log.file.path", "/var/log/liquidsoap/<script>.log")
```

**Comment by toots** [comment]
Thks for the explanation @S54B32 !
