### ISSUE TITLE
`%ffmpeg` ignores `q` option

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3267]
**Describe the bug**
In *2.2.0* ffmpeg ignores `q` option and uses default CBR if `b` is not present.

**To Reproduce**
```ruby
MP3_FFMPEG = %ffmpeg(%audio(codec="libmp3lame", q=0), format="mp3")
MP3_SIMPLE = %mp3.vbr(quality=0)

s = sine()

output.harbor(MP3_FFMPEG, s, mount="mp3_ffmpeg")
output.harbor(MP3_SIMPLE, s, mount="mp3_simple")
```

1. `ffprobe http://localhost:8000/mp3_ffmpeg`
2. `ffprobe http://localhost:8000/mp3_simple`

If I use version 2.1.4, then the expected bitrate in both cases will be around 67 Kbit/s.
In 2.2.0 ffmpeg sets bitrate to 128 Kbit/s.

**Expected behavior**
`%ffmpeg` should respect `q` option value for *libmp3lame*.

**Version details**

- OS: *ubuntu:22.04* in docker
- Version: *2.2.0*

**Install method**
Deb package from liquidsoap releases at github

**Common issues**
N/A

**Comment by toots** [comment]
Thanks for reporting! This is fixed in main and `rolling-release-v2.2.x`
