### ISSUE TITLE
Use new OCaml 4.03 features

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#327]
Apparently OCaml 4.03 has [tons of new features](https://linuxfr.org/news/ocaml-4-03) including optimization that we could benefit much from. Maybe could we try to see if we gain any speed with those?

**Comment by toots** [comment]
That's pretty cool although some of the new features presented in the
article aren't new, like `noalloc`, also it's not clear to me if the new
`flambda` is activated or not..

What part do you think we should look at? The optimizations look cool but I
feel like this isn't critical to our case, I'm much more interested by the
multicore GC but that isn't there yet..
