### ISSUE TITLE
VBAN support?

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#3281]
I'm again in the middle of multi-platform setup for broadcast systems… And … after the mumble game, here comes the Voicemeeter game. Voicemeeter is a Windows audio routing software that does a lot of things, including communicating over the network using the [VBAN protocol](https://vb-audio.com/Voicemeeter/VBANProtocol_Specifications.pdf), a rather simple payload transport proto over UDP. It has "native" support for raw (or more likely PCM) Audio, Serial, MIDI, text… 

Since it can be used as input/output, what could be nice to have in liq would be:
- base support for the [VBAN protocol](https://vb-audio.com/Voicemeeter/VBANProtocol_Specifications.pdf)
- input/output for audio
- optionnally… MIDI input/output ? (I'm not sure how this is handled in liq, as I don't use it that way)
- even more optionnaly: Serial/Text for metadata / remote controlling liq (or Voicemeeter).

This could allow fun full duplex setups between liq and Voicemeeter… Either feeding audio to VM through liq, or the other way around, or both with a mix minus situation and what not…

Also I'm guessing it's a great way to showcase liq's flexibility, as even though I'm probably too noob to code it myself, I figure since the protocol is "simple" and basically transports raw data over UDP, with configurable buffer, it'd be rather easy to implement in liq's logic…

Thoughts?

Gilou

**Comment by gilou** [comment]
Just to add some context, it's not out of nowhere, Pipewire just released support for VBAN audio in 0.3.76 ( [sender](https://docs.pipewire.org/page_module_vban_send.html) / [receiver](https://docs.pipewire.org/page_module_vban_recv.html) ) and will enable MIDI once this [commit](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/241066029902cd088c4d6488dbb023a713277c54) is released.

**Comment by toots** [comment]
@gilou I'm all for features but also all for limiting the time spend debugging/supporting users.

If pipewire supports this, are there other paths? Can we support it through pipewire (not supported yet directly but would bring a lot of stuff at once)? Can we support it via ffmpeg?

**Comment by gilou** [comment]
well yup, it's easy to get to it through pipewire indeed, as it provides sources/sinks seen as devices to liq ;)
