### ISSUE TITLE
HLS atomic write as per LS 2.2.1+git@f4af3b763 errors & shuts LS down

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3290]
**Describe the bug**
See https://github.com/AzuraCast/AzuraCast/issues/6470

**Version details**

- OS: Ubuntu 22.04 server
- LS Version: 2.2.1+git@f4af3b763

**Install method**
Ubuntu Jammy from release assets

**Comment by toots** [comment]
Fix is on the way! See: https://github.com/savonet/liquidsoap/pull/3286#issuecomment-1661584311

**Comment by Moonbase59** [comment]
Cheers for caring, will test as soon as @BusterNeece has integrated it in AzuraCast!

**Comment by Moonbase59** [comment]
Looks fine now, using AzuraCast Rolling Release #[4078c70](https://github.com/AzuraCast/AzuraCast/commit/4078c70ee87f7cdbed37fd9d270ffe5e1d8c0170) (2023-08-03 3:37) with Liquidsoap 2.2.1+git@b46726daa.

Did some listening tests as well as a long "curl" run to look for glitches (example):

while true;do curl -s https://example.com/hls/station/aac_hifi.m3u8 | wc -l;done
