### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by FreeInternetRadio** [savonet/liquidsoap#332]
Hi There,

I'm trying to get something done in liquidsoap but......

I know this is not the place to ask this kind off questions but is there somewhere ???????

Tnx
Feiko

**Comment by linuxgeek96** [comment]
Mailing list: https://lists.sourceforge.net/lists/listinfo/savonet-users

**Comment by smimram** [comment]
Yes, the mailing-list savonet-users@lists.sf.net is the right place.
