### ISSUE TITLE
Check_next

### ISSUE THREAD

**Issue by Botanistt** [savonet/liquidsoap#334]
https://github.com/savonet/liquidsoap/issues/333
 
Can anyone give me example for this? I tried different ways and it never worked. What's the correct syntax for it?

**Comment by smimram** [comment]
Please reopen bug #333 instead of creating a new one. Also, please provide what you tried there.

**Comment by Botanistt** [comment]
If I knew how to reopen then I would.

**Comment by smimram** [comment]
There is a button "Reopen and comment" at the bottom of the page.
