### ISSUE TITLE
ogg/flac harbor doesn't reflect metadata

### ISSUE THREAD

**Issue by rmens** [savonet/liquidsoap#335]
When streaming ogg/flac to a harbor input, the metadata is not reflected on re-encoded mount points. When streaming ogg/vorbis the metadata is reflected (tested with Liquidsoap 1.2.0 on Ubuntu 16.04 LTS)

**Comment by toots** [comment]
Hi,

I'm not sure how to reproduce. Here's what I have tried:

Receiving end:
```
% liquidsoap 'output.dummy(fallible=true,on_metadata(print,input.harbor("bla")))'
```

Sending end:
```
% liquidsoap 'output.icecast(mount="bla",port=8005,fallible=true,%ogg(%flac),playlist("~/Music"))'
```

And I get the following logs:
```
2016/06/27 09:38:38 [decoder:3] Method "OGG" accepted "application/ogg".
2016/06/27 09:38:38 [threads:3] Created thread "harbor source feeding" (2 total).
2016/06/27 09:38:38 [harbor_4867:3] Decoding...
[("album","I-Sus"), ("track","5"), ("year","2003"), ("artist","Delroy Washington"), ("title","Freedom Fighters (2002 Digital Remaster)"), ("vendor","reference libFLAC 1.3.1 20141125"), ("comment","0"), ("genre","Reggae")]
```

**Comment by rmens** [comment]
Hi,

I'm doing:

```radio = input.harbor("studio",port=8080,password="---")```

And stream ogg/flac to it with edcast that also sends the metadata. 

And have these outputs:
```
output.icecast(%ogg(%flac)
output.icecast(%mp3(bitrate=192)
output.icecast(%aacplus(bitrate=64)
```

None of them reflect the metadata. If i switch to ogg/vorbis, the metadata is reflected.

**Comment by toots** [comment]
What do you mean by reflected? How do you test it?

**Comment by rmens** [comment]
Reflected = the metadata that the encoder sends to the harbor is also shown in the outputs. 

I'm testing it by simply starting edcast of samcast on Windows and send a stream with metadata to the harbor input. The metadata is not shown on the outputs which are on an icecast2 server if the harbor is receiving an ogg/flac stream.

**Comment by toots** [comment]
Ok. Metadata updates have different protocols. `ogg/vorbis` metadata are embedded in the stream while for `mp3` and `AAC` and, possibly, `ogg/flac`, metadata are sent via a `HTTP GET` call. It is possible that the issue lies with your client or network configuration. Have you tried the two commands I provided above on the same machine?

**Comment by smimram** [comment]
Quite an old bug with a proposed solution and not feedback, closing. Please reopen if the problem persists.
