### ISSUE TITLE
Harbor & shoutcast protocol (v1.2.0)

### ISSUE THREAD

**Issue by Jontyy** [savonet/liquidsoap#337]
Hi all,

I'm having issues connecting to harbor with the shoutcast protocol, icecast2 works fine. I'm seeing this in the logs:

> 2016/06/03 10:14:23 [harbor:4] Header: icy-url, value: http://www.rogueamoeba.com/nicecast/.
> 2016/06/03 10:14:23 [harbor:4] Header: icy-pub, value: 1.
> 2016/06/03 10:14:23 [harbor:4] Header: icy-br, value: 128.
> 2016/06/03 10:14:23 [harbor:4] ICY request on /.
> 2016/06/03 10:14:23 [harbor:4] Adding source on mountpoint "/" with type "audio/mpeg".
> 2016/06/03 10:14:23 [harbor:5] Relaying ICY.
> 2016/06/03 10:14:23 [harbor:4] Returned 500 for '/': File "tools/harbor.ml", line 369, characters 31-37: Assertion failed

I installed liquidsoap from opam with the following packages: `faad fdkaac mad lame vorbis cry aacplus taglib liquidsoap.1.2.0`

Here is a minimum working example for reproducing this issue:

```ruby
set("log.file",true)
set("log.level",6)
set("log.stdout", true)
set("log.file.path","liquidsoap_shoutcast.log")

harbor_port = 1104

icecast_host = "127.0.0.1"
icecast_port = 8000;
icecast_password = "hackme"

def on_harbor_connect (headers) =
  list.iter (fun(h) -> log("header: #{fst(h)}: #{snd(h)}"), headers)
end

def dj_auth (u,p) =
  true
end


live_dj = audio_to_stereo(input.harbor("",id="live_dj",auth=dj_auth, port=harbor_port,buffer=15.0,max=30.0,icy=true,on_connect=on_harbor_connect))

source = mksafe(live_dj)

clock.assign_new(id="output_listen", [output.icecast(%mp3(bitrate=128),id="output_listen",
                                    mount="/live",
                                    host=icecast_host, port=icecast_port, password=icecast_password,
                                    icy_metadata="true",description="",
                                    url="",
                                    mksafe(buffer(source)))])
```

Thanks in advance.

**Comment by Jontyy** [comment]
Looks like this issue is isolated to my opam install, I installed `v1.0.1` today on debian 7 from apt and it was working fine, I cannot use this though as aac+ was limited before fdkaac if I remember correctly?

Here is the output from `v1.0.1`

> 2016/06/07 10:31:14 [harbor:4] New client on port 1105: 192.168.33.1
> 2016/06/07 10:31:15 [lang:3] dj authenticated successfully
> 2016/06/07 10:31:15 [harbor:4] Header: icy-url, value: http://www.rogueamoeba.com/nicecast/.
> 2016/06/07 10:31:15 [harbor:4] Header: icy-pub, value: 1.
> 2016/06/07 10:31:15 [harbor:4] Header: icy-br, value: 128.
> 2016/06/07 10:31:15 [harbor:4] ICY request on /.
> 2016/06/07 10:31:15 [decoder:4] Trying method "WAV" for "audio/mpeg"...
> 2016/06/07 10:31:15 [decoder:4] Trying method "PCM/BASIC" for "audio/mpeg"...
> 2016/06/07 10:31:15 [decoder:4] Trying method "MAD" for "audio/mpeg"...
> 2016/06/07 10:31:15 [decoder:3] Method "MAD" accepted "audio/mpeg".
> 2016/06/07 10:31:15 [lang:3] header: icy-url: http://www.rogueamoeba.com/nicecast/
> 2016/06/07 10:31:15 [lang:3] header: icy-pub: 1
> 2016/06/07 10:31:15 [lang:3] header: icy-br: 128
> 2016/06/07 10:31:15 [lang:3] harbor connect
> 2016/06/07 10:31:16 [threads:3] Created thread "harbor source feeding" (2 total).
> 2016/06/07 10:31:16 [harbor:4] Adding source on mountpoint "/" with type "audio/mpeg".
> 2016/06/07 10:31:16 [live_dj:3] Decoding...
> 2016/06/07 10:31:16 [harbor:4] New client on port 1104: 192.168.33.1
> 2016/06/07 10:31:16 [harbor:4] Header: Content-Length, value: 0.
> 2016/06/07 10:31:16 [harbor:4] Header: User-Agent, value: Shoutcast(Mozilla).
> 2016/06/07 10:31:16 [harbor:4] HTTP GET request on /admin.cgi.
> 2016/06/07 10:31:16 [harbor:4] HTTP Arg: url, value: http://www.rogueamoeba.com/nicecast/.

Any chance anybody could help out in getting this to work on `1.2.0`? I'm assuming its just a missing dependency on my system?

**Comment by SkepticalHippo** [comment]
Adding `Icy` to `match hprotocol` in `harbor.camlp4 line 401` seems to fix this issue.

**Comment by toots** [comment]
Wow. Good find and great debugging, thanks. Looks like this one had been around since at least when chunked transfer was introduced, back in 2013.. Should be fixed in latest git now.

**Comment by Jontyy** [comment]
@toots When will this fix be available in opam?

Or what would be the recommended way to install this patch now considering we already use liquidsoap 1.2 from opam? I tried opam pin but had failed to apply patch issues `"lang_builtins.patch"`.

Thanks in advance.

**Comment by toots** [comment]
I'm looking at doing a quick bug-fix release soon, there's been some important stuff pushed lately. Will get back at you asap.

**Comment by jmulvany** [comment]
It would really be a big help!

**Comment by acorkin** [comment]
@toots just wondering if there is any update for a fix in opam? It's the only thing holding us back at the moment 👍

**Comment by toots** [comment]
Gonna try to do it soon.

**Comment by Jontyy** [comment]
@toots thanks for this :)
