### ISSUE TITLE
Unary minus operation with variables

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3405]
**Describe the bug**
Liquidsoap doesn't support unary minus with variables.

**To Reproduce**
```ruby
a = 1
b = -a
if a == -b then
  print(a+-b)
end
```

**Expected behavior**
Unary minus supported.

**Version details**

- OS: Debian in docker
- Version: 2.2.1, b2a6924f3

**Install method**
savonet/liquidsoap:rolling-release-v2.2.x

**Common issues**
N/A

**Comment by vitoyucepi** [comment]
Also `-nan` and `-infinity`.

**Comment by toots** [comment]
Thanks for reporting this. I revisited the way we do it in https://github.com/savonet/liquidsoap/pull/3399 and it's not satisfactory.

The problem we have is that there is ambiguity in the language. We accept implicit term separation, so for instance you can write:
```liquidsoap
x + 1
(1, 2, 3)
```

Without a `;` separating them like most language do.

(It is worth noting that we also support:
```liquidsoap
x + 1;
(1, 2, 3)
```
but, I guess, nobody every uses that..)

Morally, what we really should mean is that the _line return_ is the term separator. However, for technical reasons, this is not how it's implemented: our current parser does not see line returns at all. 

This creates ambiguity, for instance:
```liquidsoap
# Just x alone
x
# The number -3.14
-3.14
```
is seen the same way as:
```liquidsoap
# x minus 3.14
x - 3.14
```
The current work around is to distinguish between:
1. `<integer, float, variable name or an expression terminated by )> - <anything>`
2. `<anything else> - <integer or float or (expression)>`.

The meaning for each is then:
1. `<integer, float or an expression terminated by )> <minus> <anything>`
2. `<anything else> <integer or float or (expression)>`.

Examples:
```liquidsoap
# 1 minus 2
1 - 2

# x minus 2
x - 2

# application function minus 2
f(x) - 2

# y equals the number -1
y = -1

# This fails because we don't know how to parse it. There is an ambiguity in the grammar
y = -x

# This is the workaround:
y = -(x)
```

This is clearly a hack and we need to do better. We could keep adjusting the workaround but, the best is to add support for line return as term separator, which I will have a look at soon I hope.
