### ISSUE TITLE
interactive.harbor handles does not handle [&<>"'] characters well

### ISSUE THREAD

**Issue by ghostnumber7** [savonet/liquidsoap#3418]
**Describe the bug**
When using `interactive.harbor()` there are a few issues with the `/interactive` form:
* If a field description contains a `<` character it breaks the interfase
* If an `interactive.string()` value contains some combinations of `'<>` if breaks the interfase
* If an `interactive.string()` value contains some combinations of `+&=` the value is not saved correctly

**To Reproduce**
```
interactive.harbor()
metadataTransformRegex = interactive.string(
  description = "Metadata transform regex (Example: StreamTitle='(?<artist>[^~]*?)\\s*~(?<title>[^~]*?)\\s*~ )",
  "metadataTransformRegex", "'>oops"
)
```

Go to `localhost:8000/interactive` and see it broken

**Expected behavior**
HTML entities should be escaped and form should be url encoded when submitting

**Version details**

- Ubuntu
- 2.2.0

**Install method**
opam

**Comment by toots** [comment]
Fixed with 81f4bcae61368d72f306489800d7bbc6565934ba and 113ead700
