### ISSUE TITLE
reloading playlist from within liquidsoap

### ISSUE THREAD

**Issue by chrispolley** [savonet/liquidsoap#342]
Hi,
I am trying to reset a playlist after **fallback** switches away from it, so that it always plays from the top.  I see in playlist.ml [line 88] that the vplaylist class registers the command "reload" to point to the internal reload_playlist method, but this doesn't seem to be accessible except via the [real-time] server commands.  The following code fails to parse unless I remove the `outage_playlist.reload` command.  No joy with `outage_playlist.reload_playlist` either.

Is this possible?  How do I access `playlist`'s `reload` method?

The outage playlist has a short bit of silence, a brief announcement, some bumper music, then a longer announcement and some prerecorded long-format material.

The practical impact is that if  the feeds go down for a while, the outage playlist will play, but then when they come back the position in the playlist is remembered, and at the next outage, the playlist picks up where it left off, which will likely not be in the correct spot.

Here's a code snippet:

```
outage_playlist = playlist(id="outage_playlist",  mode="normal", "/var/audio/outage.m3u" )
net_outage  = mksafe(amplify(0.1,add([sine(),noise()])));

def reset_outage(a,b)
   outage_playlist.reload
   log("Outage playlist reloaded")
    b
end

def default_transition(a,b)
    b
end

radio = fallback(
    track_sensitive=false,
    transitions=[
        reset_outage,
        reset_outage,
        reset_outage,
        reset_outage,
        default_transition
    ],
    [
        audio_to_stereo(request.queue(id="q")),
        audio_to_stereo(feed_main),
        audio_to_stereo(feed_alt1),
        audio_to_stereo(feed_alt2),
        audio_to_stereo(outage_playlist),
        net_outage
    ]
)
```

**Comment by giflw** [comment]
Hi

The problem is that `reload` or `reload_playlist` are not commands of `playlist`. You must use `playlist.reloadable` (http://savonet.sourceforge.net/doc-svn/reference.html#playlist_reloadable) insted of `playlist`. A relodable playlist returns a tuple `(reload_function, source)`. Where yout used the `outage_playlist` you should use `snd(outage_playlist)` and call the function provided by `fst(outage_playlist)`. Try this:

```
pls_reloadable = playlist.reloadable(id="outage_playlist", "o_mapa.pls.xspf")

outage_playlist = snd(pls_reloadable)
playlist_reload = fst(pls_reloadable)

net_outage  = mksafe(amplify(0.1,add([sine(),noise()])));

def reset_outage(a,b)
   playlist_reload()
   log("Outage playlist reloaded")
   b
end

....
```
