### ISSUE TITLE
Builtin metadata.map is not registered when parsing config file

### ISSUE THREAD

**Issue by rmens** [savonet/liquidsoap#3423]
**Describe the bug**
Parsing the config file generates an error in Liquidsoap 2.2.1.

**To Reproduce**
Create an empty `.liq` file and try to parse that:
```
root@liq:/var/log/liquidsoap# touch /tmp/empty.liq
root@liq:/var/log/liquidsoap# liquidsoap -p /tmp/empty.liq 
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
At /usr/share/liquidsoap-lang/libs/extra/deprecations.liq, line 96, char 17-38:
def map_metadata(%argsof(metadata.map), fn, s)

Error 3: Builtin metadata.map is not registered!
```
**Expected behavior**
Parse the file without errors.

**Version details**
- OS: Debian
- Version 22.04 (Liquidsoap 2.2.1)

**Install method**
DEB package

**Comment by vitoyucepi** [comment]
I can confirm this problem.
Liquidsoap in parse-only mode prints an error.

Versions: main, 2.2, 2.1, 2.0.

To reproduce
`echo '' | liquidsoap --parse-only -`

**Comment by toots** [comment]
Thanks for reporting. I have fixed the issue by disabling the deprecated layer when running in parse-only mode.
