### ISSUE TITLE
Liquidsoap Help!!

### ISSUE THREAD

**Issue by lelos09** [savonet/liquidsoap#343]
Hi,
i'm a newbie at liquidsoap and got confused....i need help if somebody can.
I have a Raspberry Pi3 model B with Cirrus Logic Audio card and disabled onboard.
i'm trying to make script for liquidsoap to connect my icecast server. Get music from line in of Cirrus Logic and stream vobris to my icecast server.
Can somebody help me?
Thanks in advance!

**Comment by giflw** [comment]
Hi!

Have you seen this http://liquidsoap.fm/doc-svn/quick_start.html? 

If so, what you have done so far? Do you have some specific question?

Regards

**Comment by jethroweb** [comment]
Hi, 

have you seen this : https://technic2radio.fr/tuto-raspberry-pi-liquidsoap-icecast/
