### ISSUE TITLE
replaygain issue when dB missing from the tag

### ISSUE THREAD

**Issue by camilocerchiari** [savonet/liquidsoap#3435]
hello!
I think there's something that's not right with the replay gain feature.

if you set the metadata tag as in `("replaygain_track_gain", "-16.0 dB")` the replaygain lowers the playback volume as expected.
but if the tag says `("replaygain_track_gain", "-16.0")` (without the dB) the volume is increased, as if the - sign wasn't there.

for my tests I'm setting the metadata with ffmpeg:
`ffmpeg -hide_banner -i  music/music-NORG.opus  -codec copy -metadata REPLAYGAIN_TRACK_GAIN="-16.0" -y music/music-RG-16.opus`

docker image: `savonet/liquidsoap-alpine:rolling-release-v2.2.x`
```
# liquidsoap --version
INFO: Loading Sdl_image, Target = linux
INFO: Loading Sdl_ttf, Target = linux
Liquidsoap 2.2.2+git@c99114d85
Copyright (c) 2003-2023 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.info> for more information.
```

**Comment by vitoyucepi** [comment]
Hi @camilocerchiari,

Each time liquidsoap finds a new track, it calls `replaygain_metadata`.
https://github.com/savonet/liquidsoap/blob/36ec5b189a294075242c1668c9764e838422eb78/src/libs/replaygain.liq#L64-L78
This function will try to extract metadata from tags.
If it doesn't find the tag, then it will try to use the `file.replyagain` function.
The `file.replaygain` function will try to extract from tags, but not in this case, or calculate it.

Eventually, the result of the `replaygain_metadata` function will be one of
1. The value of `REPLAYGAIN_TRACK_GAIN` without any modifications.
   Any garbage could be returned.
1. The calculated replaygain in format `#{float} dB`.
1. `null` if file resolution has failed.

The result will be passed to the `amplify` function.
If the passed value is
1. Garbage or `null` - nothing happens.
1. Number without `dB` suffix - linear amplification, everything will be *n* times louder.
1. Number with `dB` suffix - lin_of_db amplification.

The problems:
1. `file.replaygain` and `replaygain_metadata` implement the same function differently.
   The `replaygain` function also sets the gain value, by the way.
   I'm currently thinking about how to rewrite it properly.
1. I'm not sure if the `replaygain_track_gain` value implies db.

**Comment by vitoyucepi** [comment]
Hi @camilocerchiari,
I am planning to modify the behavior in issue #3438. The change will be merged into the main branch but not applied to version `2.2.x`.

As for now, I can recommend you add the `dB` suffix to your `REPLAYGAIN_TRACK_GAIN` tags.

**Comment by camilocerchiari** [comment]
thank you.
