### ISSUE TITLE
Liquidsoap not working with Icecast on CentOS 7

### ISSUE THREAD

**Issue by antonstorozhilov** [savonet/liquidsoap#344]
When trying to run a test liquid soap script

`set("log.file.path","/tmp/basic-radio.log")`
`source = single("audiofile.ogg")`
`output.icecast(%mp3, host="**.**.***.***",
port=8000, password="****",
source)`

I get the error:
`At line 7, char 15: the variable output.icecast used here has not been
  previously defined.`

I've spent several hours googling this issue, as I am quite new to using CentOS. 

Also, for context, I had a lot of issues installing liquidsoap through opam, I had to install a ton of external packages as dependencies, that were hard to find. I tried opam removing and reinstalling liquidsoap but that didn't change anything.

Update: when I go into opam/packages/liquidsoap/liquidsoap.1.2.1 and open opam I see:
`conflicts: [
  "cry" {< "0.4.0"}
  "taglib" {< "0.3.0"}
]
`

**Comment by antonstorozhilov** [comment]
After many hours of trying everything, with the help of a Russian site and from seeing the conflicts line above, I came to the conclusion that cry was the issue. 

I was finally able to install cry using opam after fiddling with it, at which point liquidsoap reinstalled automatically.

I'm not sure why liquidsoap on installation did not report any conflicts or problems, that was quite misleading.

I will close my own thread and leave it up in case anyone else runs into a similar problem.

**Comment by toots** [comment]
Hi,

Cry is not installed by default so it needs to be installed to provide `output.icecast`. We have documented all this here: http://liquidsoap.fm/download.html

Glad you were able to fix your problem. All the best with your liquidsoap project!
