### ISSUE TITLE
blank.detect threshold with interactive value

### ISSUE THREAD

**Issue by YoannQueret** [savonet/liquidsoap#3444]
Hi,

Is it possible to use interactive value with blank.detect threshold ?

It seem that the new value is not used.

```
blank_threshold = interactive.float("blank_threshold", -40.0)
[...]
source = blank.detect(
    max_blank=10.0,
    min_noise=10.0,
    on_noise=handler_noise,
    threshold=blank_threshold(),
    track_sensitive=false,
    start_blank=false,
    handler_blank,
    source
)
```

If i change from -40 (value at startup) to -0.5, with an input audio level at -20dB blank.detect detect nothing.

Something is wrong in the code ?

Thk for your help.
Yoann

**Comment by toots** [comment]
`threshold` is a float getter in `rolling-release-v2.2.x` and `main`. The next stable release should have it out and should take too long to come out.
