### ISSUE TITLE
Replay Gain causes sound corruption

### ISSUE THREAD

**Issue by RecursiveGreen** [savonet/liquidsoap#345]
I've had an issue with my station for a while where certain songs would play with ear-piercing pops/clicks/screeches. I've finally been able to narrow it down to a common variable in which they are all semi-quiet songs and the replay gain ID3 metadata is high into the positive values. I've seen it occur from songs that report a value as low as +3.00db all the way up to +16.00db.

I usually use Foobar2000's built-in functions to compute the replay gain values and the results play fine on all the players I throw at it--Liquidsoap seems to be the only one causing the noise.

If you need more info, or a sample file, let me know.

Thanks!

**Comment by smimram** [comment]
Hi, I don't recall any mention of such a problem in the past. Could you please send a link to some file which exhibits the problem so that we can reproduce it?

**Comment by RecursiveGreen** [comment]
Here's a FLAC file that exhibits the behavior:
[sample.zip](https://github.com/savonet/liquidsoap/files/416760/sample.zip)

This is my radio config for reference:
[radio.liq](https://gist.github.com/RecursiveGreen/58c710d12e5488b8976288860c72208f)

Also, this was compiled from git source on Ubuntu 16.04 LTS. So if nothing on your end can be found, it might even be a binary from Ubuntu's repositories.

Let me know if you need anything else.

**Comment by smimram** [comment]
Was it related to #749?

**Comment by Yamakaky** [comment]
The norm defines the replaygain_track_peak field which can be used to prevent this problem
