### ISSUE TITLE
Flac encoder terrible bad sound...solution?

### ISSUE THREAD

**Issue by lelos09** [savonet/liquidsoap#346]
Hi,
i have set up a raspberry pi 3 with Cirrus Logic Audio card at 192khz and i'm trying to stream flac into oqq container but my sound is terrible bad....is an empty sound with full of middle frequencies and if i give him bass or tremble from my external equillizer it become more terrible.

my code is : 
```
set("frame.audio.samplerate",192000)
set("frame.audio.channels",2)

output.icecast(%ogg(%flac(samplerate=192000, channels=2)),
  host = "localhost", port = 8000,
  password = "hackme", mount = "radio_flac", input.alsa()
 ) 
```

My audio input is at 192khz and so i want my output.
Any suggestion or wrong at my streming code?

**Comment by lelos09** [comment]
noone? :(

**Comment by toots** [comment]
Wow, 192kHz. That's, hmm, something.

Have you checked what you get with the command line flac encoder? I'm not sure that the algorithm was designed to handle that special case..

**Comment by smimram** [comment]
Old bug which is apparently flac's fault, no answer from the reporter, closing. Feel free to reopen if there is something new.
