### ISSUE TITLE
Besoin d'aide : Raspberry Pi 3 + Liquidsoap + Icecast

### ISSUE THREAD

**Issue by jethroweb** [savonet/liquidsoap#347]
Bonjour,

J'essaye de diffuser un flux audio (capturé par une carte son usb) depuis un raspbeery pi vers un serveur icecast hébergé à l'exterrieur. J'ai installé liquidsoap et les plugins mais je suis un peu perdu sur la marche à suivre. 
J'ai suivi différents tuto, mais quand je veux lancer liquidsoap, j'obtiens l'erreur suivante :
init: exception encountered during start phase:
  Sys_error("/var/log/liquidsoap/radioref.log: Permission denied")

**Comment by jethroweb** [comment]
Pour info, voici mon fichier de config :
#!/usr/bin/liquidsoap
radio = input.alsa(device="plughw:1,0")
output.icecast(%vorbis, 
  host="80.82.229.202",port=8000,password="lafrap",
  mount="graffiti.ogg",radio)

J'ai corrigé mes problèmes de droits avec la commande :
sudo chown -R pi /var/log/liquidsoap

Maintenant, quand je lance liquidsoap, j'arrive à accéder à mon point de montage mais je n'ai pas de son. Que puis-je faire ?

**Comment by jethroweb** [comment]
Pour info, voici mon fichier de config :
#!/usr/bin/liquidsoap
radio = input.alsa(device="plughw:1,0")
output.icecast(%vorbis, 
host="xx.xx.xxx.xxx",port=8000,password="xxxxx",
mount="radio.ogg",radio)

J'ai corrigé mes problèmes de droits avec la commande :
sudo chown -R pi /var/log/liquidsoap

Maintenant, quand je lance liquidsoap, j'arrive à accéder à mon point de montage mais je n'ai pas de son. Que puis-je faire ?

**Comment by jethroweb** [comment]
Problème résolu pour le son, le périphérique USB avait changé. Tout fonctionne après un reboot.
Prochaine étape : Faire en sorte que liquidsoap se lance au démarrage (streaming vers icecast).
Des piste pour l'autostart ?

**Comment by jethroweb** [comment]
Solution trouvée :
https://technic2radio.fr/tuto-raspberry-pi-liquidsoap-icecast/

**Comment by smimram** [comment]
Cool :)
