### ISSUE TITLE
No sound in RTMP stream

### ISSUE THREAD

**Issue by UndeRus** [savonet/liquidsoap#3476]
**Describe the bug**
When I try to stream video(or static image) + audio - I have only video

Also in logs I see this:

``time="2023-10-17T21:15:38Z" level=info msg="Processing video using codec x264 with 2 output qualities configured."
time="2023-10-17T21:16:06Z" level=error msg="[flv @ 0x55ff35f8c480] Could not find codec parameters for stream 0 (Audio: aac, 44100 Hz, mono, 128 kb/s): unspecified sample format"
time="2023-10-17T21:16:06Z" level=error msg="Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options"``

**To Reproduce**

```audio = single("bla.aac")
video = single("bla.png")

video = ffmpeg.encode.video(
    %ffmpeg(%video(
      codec="libx264",
      b="2000k",
      maxrate="2500k",
      bufsize="5000k",
      g=50,
      preset="veryfast",
      pix_fmt="yuv420p",

  )),
    video)

audio = ffmpeg.encode.audio(
  %ffmpeg(%audio(
    codec="aac",
    b="128k",
    ar=48000,
    sample_fmt="s16",
  )), audio)

stream = mux_video(video=video, audio)

enc = %ffmpeg(
  format="flv",
  %audio.copy,
  %video.copy)

key = "STREAM KEY"
url = "STREAM SERVER URL/#{key}"             
output.url(url=url, enc, stream)
```
As stream server I tried to use [Owncast](https://owncast.online/)

When I try make same with ffmpeg command - it works ok
` ffmpeg -stream_loop -1 -re -f image2 -i .\bla.png -i .\bla.mp3 -c:v libx264 -vf scale=400:-2 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ac 2 -ar 44100 -f flv RTMP_STREAM_URL`

**Expected behavior**
Video plays with sound

**Version details**

- OS: Windows 10
- Version 2.2.1

**Install method**
Build from releases page

**Comment by gAlleb** [comment]
I've been able to reproduce as well (liq2.2.1 opam)
`ffmpeg.encode.audio_video` seems to work though. You can try it. But sometimes it messes with audio as well)

**Comment by UndeRus** [comment]
> I've been able to reproduce as well (liq2.2.1 opam) `ffmpeg.encode.audio_video` seems to work though. You can try it. But sometimes it messes with audio as well)
> 
> ```
> video = single("test.jpg")
> stream = source.mux.video(video=video, audio)
> 
> stream = ffmpeg.encode.audio_video(
>   %ffmpeg(
>       %video(
>       codec="libx264",
>       b="2000k",
>       maxrate="2500k",
>       bufsize="5000k",
>       g=50,
>       preset="veryfast",
>       pixel_format="yuv420p",
>       ),
>      %audio(
>       codec="aac",
>       b="128k",
>       ar=48000,
>       sample_fmt="s16",
>       )),
>       stream)
> 
> 
> enc = %ffmpeg(
>   format="flv",
>   %video.copy,
>   %audio.copy,)
> 
> 
> url = "rtmp://localhost/live"
>              
> output.url(url=url, enc, stream)
> ```

This works, but sound is like with wrong speed and with clipping, I don't have this effect with direct ffmpeg call

**Comment by toots** [comment]
I would recommend to use the internal ffmpeg encoder instead of the inline ones. Sending via `rtmp` (aka flash) has some quirks between the container (flash) and the codecs (aac/h264). When encoding inline, the first encoder has no idea that flash/rtmp will be used as container and might not be setting the encoding right.

This should do:
```liquidsoap
video = single("test.jpg")
stream = source.mux.video(video=video, audio)

stream =
  ffmpeg.encode.audio_video(
    %ffmpeg(
      %video(
        codec = "libx264",
        b = "2000k",
        maxrate = "2500k",
        bufsize = "5000k",
        g = 50,
        preset = "veryfast",
        pixel_format = "yuv420p"
      ),
      %audio(codec = "aac", b = "128k", ar = 48000, sample_fmt = "s16")
    ),
    stream
  )

enc = %ffmpeg(format = "flv", %video.copy, %audio.copy)

url = "rtmp://localhost/live"

output.url(url=url, enc, stream)
```

**Comment by UndeRus** [comment]
> I would recommend using the internal ffmpeg encoder instead of the inline ones. Sending via `rtmp` (aka flash) has some quirks between the container (flash) and the codecs (aac/h264). When encoding inline, the first encoder has no idea that flash/rtmp will be used as container and might not be setting the encoding right.
> 
> This should do:
> 
> ```
> video = single("test.jpg")
> stream = source.mux.video(video=video, audio)
> 
> enc =
>   %ffmpeg(
>     format = "flv",
>     %video(
>       codec = "libx264",
>       b = "2000k",
>       maxrate = "2500k",
>       bufsize = "5000k",
>       g = 50,
>       preset = "veryfast",
>       pixel_format = "yuv420p"
>     ),
>     %audio(codec = "aac", b = "128k", ar = 48000, sample_fmt = "s16")
>   )
> 
> url = "rtmp://localhost/live"
> 
> output.url(url=url, enc, stream)
> ```

Thank you, this config works amazing!
