### ISSUE TITLE
`on_track` damages cover art

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3502]
**Describe the bug**
Cover art data is corrupted when extracted from metadata inside the `on_track` function callback.

**To Reproduce**
This file may be corrupted in some way.
[1.mp3.zip](https://github.com/savonet/liquidsoap/files/13259616/1.mp3.zip)

```ruby
def a()
    s = single("1.mp3")
    s.on_track(
        fun(m) -> begin
            c = metadata.cover(m)
            file.write("a.jpg", data=c)
        end
    )
    output.dummy(s)
end

def b()
    m = file.metadata("1.mp3")
    c = metadata.cover(m)
    file.write("b.jpg", data=c)
end

def c()
    c = file.cover("1.mp3")
    file.write("c.jpg", data=c)
end

a()
b()
c()
```

```
a.jpg: data
b.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=16, height=2720, bps=206, PhotometricInterpretation=RGB, manufacturer=Canon, model=Canon EOS 5D Mark II, orientation=upper-left, width=4080], baseline, precision 8, 880x880, components 3
c.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=16, height=2720, bps=206, PhotometricInterpretation=RGB, manufacturer=Canon, model=Canon EOS 5D Mark II, orientation=upper-left, width=4080], baseline, precision 8, 880x880, components 3
```

**Expected behavior**
Cover data should not be corrupted when passed from `on_track`.

**Version details**

- OS: *ubuntu:22.04* in docker
- Version: *2.2.2*

**Install method**
Deb package from liquidsoap releases at github

**Common issues**
https://github.com/savonet/liquidsoap/discussions/3402#discussioncomment-7478411

**Comment by toots** [comment]
Thank you for all the effort putting this together, I'll have a look as soon as possible.

**Comment by DigiBC** [comment]
@vitoyucepi

After a few tests with your MP3 file, I found out the following:
- It's not a general problem, cover art extraction from other MP3 files works without errors.
- In your MP3 file the cover art is embedded with MIME type "image/JPG", usually "image/jpeg" is used.
- I experimentally extracted the cover art from your MP3 file with the "Mp3tag" tool and then embedded it again. The resulting MP3 file (same size) works without errors.
- Somehow the results of the cover art extraction seem to depend on the metadata decoder. The corrupt JPEG file you describe is created when using ID3 or ID3v2, whereas I haven't noticed any problems with other metadata decoders, e.g. ffmpeg, ID3v1, image, taglib.

So, there's a workaround by configuring the relevant metadata settings, for example:
`settings.request.metadata_decoders := ["ffmpeg"]`

**Comment by DigiBC** [comment]
Well, if I understand you correctly, you intentionally used a non-standard MP3 file (with invalid MIME type "image/JPG" and potentially other inconsistencies in its metadata) to challenge Liquidsoap and its default metadata decoder.   :wink:

Do the previous versions of Liquidsoap (< v2.2.2) with ID3v2 (ID3) metadata decoder extract the cover art image of your MP3 file without issues?
(Unfortunately, I can't test this myself right now.)

**Comment by vitoyucepi** [comment]
> if I understand you correctly, you intentionally used a non-standard MP3 file to challenge Liquidsoap and its default metadata decoder.

Not at all, first of all the file is not mine. Second, I'm helping to develop the image extraction feature https://github.com/savonet/liquidsoap/discussions/3402#discussioncomment-7478411.

> Do the previous versions of Liquidsoap

I haven't tested it against 2.1. But I think it's present in 2.2.1. I could do a thorough test of different versions.

**Comment by DigiBC** [comment]
> I'm helping to develop the image extraction feature [#3402 (reply in thread)](https://github.com/savonet/liquidsoap/discussions/3402#discussioncomment-7478411).

That sounds like an exciting feature indeed!   :thumbsup:
Of course, this requires a certain amount of error handling when it comes to poorly tagged audio files. Apart from the issue reported here, it remains to be seen which of the available metadata decoders is best for the job.

**Comment by toots** [comment]
If believe that this was closed with https://github.com/savonet/liquidsoap/commit/a86be5bcd0394b467fc7a7e0967642d0647314b4 and https://github.com/savonet/liquidsoap/commit/fece51da600185da508903d683c65016ba177cdb
