### ISSUE TITLE
Error compiling liquidsoap, unbound module Magic

### ISSUE THREAD

**Issue by geneturnbow** [savonet/liquidsoap#351]
I'm most of the way through solving the trick of compiling on CentOS 6.8, and I've hit a snag. 

While compiling LiquidSoap itself (I've already resolved all the other issues compiling the support libraries) I'm getting this:

make[3]: Entering directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0/src'
OCAMLOPT -c configure.ml
File "configure.ml", line 21, characters 19-31:
Error: Unbound module Magic
make[3]: *** [configure.cmx] Error 2
make[3]: Leaving directory`/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0/src'
make[2]: **\* [all-auto-ocaml-prog] Error 2
make[2]: Leaving directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0/src'
make[1]: *** [all-subdirs] Error 2
make[1]: Leaving directory`/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0'
make: **\* [all] Error 1

I've already successfully compiled and installed ocaml-magic. I don't know ocaml, I'm just trying to work my way through all the make files and get this running. And yes, I know this would be infinitely easier on a Debian based system. I have to use CentOS 6.8, I don't have any options there. 

Any idea what it's stumbling on?

**Comment by geneturnbow** [comment]
It does, and I used it to do that.

I'm ALMOST THERE. having cleared that issue, I now have a new one:

File "tools/sdl_utils.ml", line 54, characters 14-25:
Error: Unbound module Sdlttf
make[3]: *** [tools/sdl_utils.cmx] Error 2
make[3]: Leaving directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0/src'
make[2]: *** [all-auto-ocaml-prog] Error 2
make[2]: Leaving directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0/src'
make[1]: *** [all-subdirs] Error 2
make[1]: Leaving directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0'
make: *** [all] Error 1

I'm guessing there's an ocaml-Sdlttf module out on the internet somewhere, but I'm having trouble finding that.

**Comment by smimram** [comment]
You might have better luck by uninstalling some libraries (for instance, you probably not need SDL which is for video). Another option would be to use opam, see http://liquidsoap.fm/download.html#opam.

**Comment by geneturnbow** [comment]
Actually, I desperately need SDL, because video is precisely what I'm doing with it.

I'll have a look at another look at opam, but I've already tried it once.

**Comment by geneturnbow** [comment]
So I think I've traced it down to ocamlsdl not being installed. Which needs SDL2, SDL2-image, SDL2-ttf, and SDL2-mixer, all of which are installed, but not one of which can be found by the configure file that comes with the ocamlsdl source code.

If I can get 'configure' to find the headers and recognize that the libraries are there, I can compile it and get this hunk of junk in the air. So THAT'S the source of my problems.

**Comment by geneturnbow** [comment]
I've been beating my brains out with a slice of lemon wrapped around a large gold brick on this. Ocamlfind can't find the module Sdlttf and I still don't know why.

File "tools/sdl_utils.ml", line 54, characters 14-25:
Error: Unbound module Sdlttf
make[3]: *** [tools/sdl_utils.cmx] Error 2
make[3]: Leaving directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0/src'
make[2]: *** [all-auto-ocaml-prog] Error 2
make[2]: Leaving directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0/src'
make[1]: *** [all-subdirs] Error 2
make[1]: Leaving directory `/usr/local/src/liquidsoap/liquidsoap-1.2.0-full/liquidsoap-1.2.0'
make: *** [all] Error 1

**Comment by smimram** [comment]
This bug is rather old, and the use of opam should solve most of your issues. Please reopen if it is not the case.
