### ISSUE TITLE
`bpm` throws Error 4: Undefined variable bpm

### ISSUE THREAD

**Issue by Mikulskii** [savonet/liquidsoap#3527]
Took an example from The Liquidsoap Book, but it doesn't work:
```
s = mksafe(playlist("..."))
s = bpm(s)
thread.run(every=1., {print("BPM: #{s.bpm()}")})
output(s)
```
**Output:**
```
At bpm.liq, line 2, char 4-8:
s = bpm(s)

Error 4: Undefined variable bpm
```
`lufs` and `rms` are working properly. Tried on versions `2.1.2` and `2.2.2` - Windows & Ubuntu(via opam)

**Comment by rrolla** [comment]
Hey looks like s object is modified if you call it directly on real source

try like this

```ruby
musicSource = mksafe(playlist(id="musicSource", "/mnt/test/bpm"))

musicSourceBpm = bpm(id="bpm", musicSource)

def detectBpm()
    metadata = musicSource.last_metadata() ?? []
    title = "#{metadata['artist']} - #{metadata['title']}"
    bpm = musicSourceBpm.bpm()
    bpmWithTitle = "BPM: #{string_of(int_of_float(bpm))} #{title}"
    print(bpmWithTitle)
end

def startDetectBpm()
    thread.run(delay=5.0, (fun() -> begin detectBpm() {} end))
end

def onMetadataHandler(metadata)
    startDetectBpm()
end

musicSource.on_metadata(onMetadataHandler)
```

And look whats happened on track change, maybe for you also always return 0 
see https://github.com/savonet/liquidsoap/issues/2871

**Comment by Mikulskii** [comment]
Hey @rrolla !
Strangely, I get the same error
```
musicSourceBpm = bpm(id="bpm", musicSource)

Error 4: Undefined variable bpm
```

**Comment by vitoyucepi** [comment]
Hi @Mikulskii,
Have you installed liquidsoap via opam in windows and ubuntu?
Can you list all installed opam packages with `opam list`?
I think the `bpm` function depends on `soundtouch`.

**Comment by Mikulskii** [comment]
Hi @vitoyucepi! Ah, that's the thing.
I installed `soundtouch` and the case moved forward. Thanks!
`opam` is only on Ubuntu.
