### ISSUE TITLE
`source.drop` prevents liquidsoap from starting

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3542]
**Describe the bug**
I'm testing the `source.drop` command and discovered that in completely stops all output to stdout.

**To Reproduce**
1. Start container
   `docker run -it --entrypoint bash savonet/liquidsoap:v2.2.2 -c "echo 'source.drop(blank())' | liquidsoap -"`
1. See in logs
   ```
   INFO: Loading Sdl_image, Target = linux
   INFO: Loading Sdl_ttf, Target = linux
   ```

**Expected behavior**
`source.drop` should not prevent liquidsoap initialization.

**Version details**

- OS: *Debian* in docker, *Ubuntu:22.04*
- Version: *2.2.2*, ca55f979

**Install method**
- deb package for ubuntu vm from release artifacts
- main build using dune + opam for dependencies in a container
- image from *savonet/liquidsoap*

**Common issues**
N/A

**Comment by toots** [comment]
Thanks for reporting. I also plan on looking at this while rewriting the clock system.

**Comment by vitoyucepi** [comment]
No `source.drop()`, no problem?

**Comment by toots** [comment]
Well `source.drop` will animate the source until it runs out of data. I'm afraid, a `source.drop` of a `blank` would essentially run your CPU at 100% forever..

**Comment by vitoyucepi** [comment]
Hi @toots,
Wasn't the `source.drop()` function removed in #4216, so if there is no `source.drop` then it can't cause a problem?

**Comment by toots** [comment]
Ha. Yes!
