### ISSUE TITLE
blank.strip increases CPU load (>100%)

### ISSUE THREAD

**Issue by yan-sag** [savonet/liquidsoap#3544]
Hi,
I'm trying to fallback a unavalaible source to a playlist one, after a x sec silence of transition between them.
I tried with `blank.strip`, and provokes a huge consumption of CPU.

**Describe the bug**
`blank.strip` operator increases CPU load, from about 6% at startup, increases 1% by percent to more than 100%.
This causes 'must catchup' errors.

**To Reproduce**
```
mic = buffer(input.alsa(device="plughw:1,0"))
mic = blank.strip(max_blank=2., mic)
music = playlist("~/musique")
radio = fallback(track_sensitive=false, [mic, music])

output.alsa(fallible=true, device='plughw:1,0', radio)
```

**Expected behavior**
`music` playlist is played after a 2 seconds silence on `mic`, without any significant CPU load increase.

**Version details**
- bookworm
- liquidsoap 2.2.2

**Install method**
opam build

**Comment by toots** [comment]
Thanks for the report. I'll have a look asap. I suspect, however, that you simply shouldn't use `buffer` in this situation. Something like this:
```liquidsoap
mic = input.alsa(device="plughw:1,0")
mic = blank.strip(max_blank=2., mic)
music = playlist("~/musique")
radio = fallback(track_sensitive=false, [mic, music])

output.alsa(fallible=true, device='plughw:1,0', radio)
```

**Comment by vitoyucepi** [comment]
Hi @toots,
I suspect this is the exact code snippet shown on [page 99 of the book](https://www.liquidsoap.info/book/book.pdf).

**Comment by yan-sag** [comment]
Hi,
same issue without `buffer`.

Indeed, its the example in the book. My script is more complex, I wanted to try with a minimal code.

**Comment by toots** [comment]
Thanks y'all planning on getting to this as soon as possible.

**Comment by toots** [comment]
I believe the changes built here: https://github.com/savonet/liquidsoap/actions/runs/6991394869 are addressing the issue. Any change one of y'all could test them?

**Comment by toots** [comment]
I was able to reproduce and confirm that the changes mentioned above do fix the issue.

**Comment by toots** [comment]
Yes please!
