### ISSUE TITLE
Source.seek always returns 0

### ISSUE THREAD

**Issue by pdyakov** [savonet/liquidsoap#357]
Trying to use source.seek for playlist source according to this documentation:
http://savonet.sourceforge.net/doc-svn/seek.html
but it always returns 0.
Does this feature actually works now?

**Comment by toots** [comment]
It works but only for requests with a decoder that supports it. What format are the files in that playlist?

**Comment by pdyakov** [comment]
There are mp3 files in playlist.

**Comment by toots** [comment]
Hmm. Seek should work on mp3 files. Would you mind sharing more of your script so we can see why it isn't for you? Thanks!

**Comment by smimram** [comment]
This bug is quite old and we are missing input from the reporter, closing. Please reopen if it still applies.
