### ISSUE TITLE
Documentation error 

### ISSUE THREAD

**Issue by ScuttleSE** [savonet/liquidsoap#3580]
At https://www.liquidsoap.info/doc-2.2.2/encoding_formats.html

"Liquidsoap provides operators that can be used to convert sources into a format acceptable for a given encoder. For instance, the mean operator transforms any audio source into a mono source and the audio_to_stereo operator transforms any audio source into a stereo source."

The audio_to_stereo operator has been removed in 2.2.2

**Comment by toots** [comment]
Thanks for reporting! This should be fixed in all the `2.2.x` doc now.
