### ISSUE TITLE
Live source 'Name' as output.file file name?

### ISSUE THREAD

**Issue by masochism** [savonet/liquidsoap#359]
Hi there! I've set up automatic recording of live sources with output.file but I want to use the source's 'Name' as the file name, is this possible? I've tried using (title) and {title} but this doesn't seem to work. Live sources will use the Name value to display their artist/DJ alias so it would be great to name the files this way. Thanks in advance, sorry if this is a massive noob query!!

**Comment by toots** [comment]
Hi, 

Where is the name coming from? Is it fixed at run-time in the code, is it a metadata?

I'm closing the issue here since it is not code-related. Feel free to continue the conversation here or, better, move it to the mailing list at: savonet-users@lists.sourceforge.net

Thanks!
