### ISSUE TITLE
[Harbor] input.harbor with http.transport.tls don't accept connections after some connections

### ISSUE THREAD

**Issue by codeurimpulsif** [savonet/liquidsoap#3598]
**Describe the bug**
I use `input.harbor` with `http.transport.tls` (or `http.transport.ssl`) to input external stream but after multiple connections I can't connect anymore.

Note: This issue seem to be the same as #3067 

**To Reproduce**

- Get liquidsoap package (here `arm64` but you can use another one)
  ```
  wget https://github.com/savonet/liquidsoap/releases/download/v2.2.2/liquidsoap_2.2.2-debian-bookworm-1_arm64.deb
  ```

- Install liquidsoap
  ```
  sudo apt-get install --no-install-recommends ./liquidsoap_2.2.2-debian-bookworm-1_arm64.deb
  ```

- Generate self-signed ssl certificates
  ```
  openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -sha256 -days 365 -subj '/CN=localhost' -nodes
  ```

- Create this script:
  ```ruby
  #!/usr/bin/liquidsoap

  settings.harbor.bind_addrs.set(["127.0.0.1", "::1"])

  tls_radio = http.transport.tls(
    certificate="/path/to/cert.pem",
    key="/path/to/key.pem",
  )

  live = input.harbor(id="live",
    transport=tls_radio,
    buffer=2.,
    max=10.,
    port=8005,
    metadata_charset = "UTF-8",
    "live"
  )

  output.dummy(mksafe(live))
  ```

- Run it: `liquidsoap 1.liq`

- Watch this `ss` command to see liquidsoap connections in `CLOSE-WAIT` and `ESTABLISHED` states:
  ```
  watch 'ss -tapn | grep 8005 | grep -E "CLOSE|ESTAB"'
  ```

- Install `netcat-openbsd`
  ```
  sudo apt-get install netcat-openbsd
  ```

- Then open some terminals (5 terminals works in my case), and in each one run:
  ```
  nc -v localhost 8005
  ```

- You can see connections are `ESTABLISHED`, but the 5th command in the last terminal can't connect.

- Wait (during 30 seconds for me) and close `nc` commands (with a `^c`)

- Then you can't connect anymore to port 8005, with `nc` commands or with [Butt](https://danielnoethen.de/butt/) for example

- All connections in the watch `ss` previously in `ESTABLISHED` state are now in `CLOSE-WAIT` state

The only solution to regain access to Liquidsoap port 8005 seem to be restarting Liquidsoap script to force connections in `CLOSE-WAIT` state to be flushed.

**Expected behavior**

- Connection to the harbor TLS port need to still be possible without restarting Liquidsoap every 4 connections

**Version details**

- OS: Debian 12 (Raspberry Pi 4B, aarch64)
- Version: `2.2.2-debian-bookworm-1`

**Install method**

- Debian package from this Github repository

**Comment by toots** [comment]
Thank you for this detailed report. I'm gonna have a look at it in the coming days.

**Comment by brenc** [comment]
It's possibly we might be hitting this one too or something similar. This causes LS to go completely off-air. LS spits out the following logs:

`2024-01-11T16:26:05.357906-05:00 docker06 ngradio-liquidsoap[1199]: 2024/01/11 21:26:05 [harbor:2] Failed to accept new client: SSL accept() error: error:00:000000:lib(0)::reason(0)`

This seems to happen when someone wants to broadcast over SSL. Sometimes it works but often it causes LS to go off-air. Using v2.2.3 Docker. This happened the other day on v2.2.1 so that prompted me to upgrade. Only fix is to restart LS.
