### ISSUE TITLE
input.http initial disconnect

### ISSUE THREAD

**Issue by StudentSA** [savonet/liquidsoap#360]
Hi,
I'm trying to use liqudsoap as a basic transcoder... unsuccessfully. Im first trying plain mp3 -> mp3 (rate change) then I want to do ogg.opus ->mp3.

I would like to find out if its normal for a input.http() directive to connect then immediately disconnect? 
The second connection attempt then begins the stream correctly. This causes an issue as I need liquidsoap process to quit after the stream is done and have added a "on_stop=shutdown" to the output.icecast. The disconnection thus causes liquidsoap to immediately shutdown.

If I do not add the shutdown option, liquidsoap process remains active in a loop:

2016/11/07 17:37:16 [http_4963:4] Connecting to <http://localhost:8000/streamLive.mp3>...
2016/11/07 17:37:16 [http_4963:4] Content-type "text/html".
2016/11/07 17:37:16 [http_4963:4] Could not get file: File Not Found
2016/11/07 17:37:16 [http_4963:4] Connection failed: Internal http error.
2016/11/07 17:37:18 [http_4963:4] Connecting to <http://localhost:8000/streamLive.mp3>...
2016/11/07 17:37:18 [http_4963:4] Content-type "text/html".
2016/11/07 17:37:18 [http_4963:4] Could not get file: File Not Found
2016/11/07 17:37:18 [http_4963:4] Connection failed: Internal http error.

My liq file:
url = "http://localhost:8000/streamLive.mp3"
ogginput = input.http(url,debug=true,logfile="/home/me/liquidsoap-http-log",force_mime="audio/mpeg")

output.icecast(
  %mp3(bitrate=32, samplerate=44100, mono=true),
  mount="/streamTranscode",
  host="localhost", port=8000, password="hackme",
  fallible=true,
  mean(ogginput)
)

My log:
2016/11/07 21:15:55 [clock.wallclock_main:4] Starting 1 sources...
2016/11/07 21:15:55 [source:4] Source output.icecast_4966 gets up.
2016/11/07 21:15:55 [source:4] Source mean_4965 gets up.
2016/11/07 21:15:55 [mean_4965:4] Content kind is {audio=1;video=0;midi=0}.
2016/11/07 21:15:55 [source:4] Source http_4963 gets up.
2016/11/07 21:15:55 [http_4963:4] Content kind is {audio=2;video=0;midi=0}.
2016/11/07 21:15:55 [threads:3] Created thread "http polling" (1 total).
2016/11/07 21:15:55 [http_4963:4] Connecting to <http://localhost:8000/streamLive.mp3>...
2016/11/07 21:15:55 [http_4963:4] Activations changed: static=[mean_4965:/streamTranscode:/streamTranscode], dynamic=[].
2016/11/07 21:15:55 [mean_4965:4] Activations changed: static=[/streamTranscode:/streamTranscode], dynamic=[].
2016/11/07 21:15:55 [/streamTranscode:4] Activations changed: static=[/streamTranscode], dynamic=[].
2016/11/07 21:15:55 [/streamTranscode:4] Enabling caching mode: active source.
2016/11/07 21:15:55 [/streamTranscode:3] Connecting mount /streamTranscode for source@localhost...
2016/11/07 21:15:55 [/streamTranscode:3] Connection setup was successful.
2016/11/07 21:15:55 [threads:3] Created thread "wallclock_main" (2 total).
2016/11/07 21:15:55 [clock:4] Main phase starts.
2016/11/07 21:15:55 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2016/11/07 21:15:55 [/streamTranscode:3] Source failed (no more tracks) stopping output...
2016/11/07 21:15:55 [/streamTranscode:3] Closing connection...
2016/11/07 21:15:55 [http_4963:4] Content-type "audio/mpeg".
2016/11/07 21:15:55 [http_4963:4] Trying playlist parser for mime audio/mpeg
2016/11/07 21:15:55 [decoder:4] Trying method "WAV" for "audio/mpeg"...
2016/11/07 21:15:55 [decoder:4] Trying method "PCM/BASIC" for "audio/mpeg"...
2016/11/07 21:15:55 [decoder:4] Trying method "AAC" for "audio/mpeg"...
2016/11/07 21:15:55 [decoder:4] Trying method "FLAC" for "audio/mpeg"...
2016/11/07 21:15:55 [decoder:4] Trying method "OGG" for "audio/mpeg"...
2016/11/07 21:15:55 [decoder:4] Trying method "MAD" for "audio/mpeg"...
2016/11/07 21:15:55 [decoder:3] Method "MAD" accepted "audio/mpeg".
2016/11/07 21:15:55 [http_4963:3] Decoding...
2016/11/07 21:15:56 [/streamTranscode:3] Connecting mount /streamTranscode for source@localhost...
2016/11/07 21:15:56 [/streamTranscode:3] Connection setup was successful.

Please can you assist with implementing basic transcoding functionality?

**Comment by toots** [comment]
Hi,

It would seem that your HTTP/streaming endpoint does not return an appropriate mime/content-type value. As you have noticed, using `force_mime` would do the trick although I would advise to fix the issue directly with your streaming endpoint if that is a possibility.

As for shutdown, I think the issue here is to be able to separate proper end-of-stream from temporary network disconnection. Not sure how you could do that too, it'll depend on your origin server as well.
