### ISSUE TITLE
Possible to record live stream including a `.cue` file?

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3608]
For recording DJ live streams, it would be advantageous being able to not only _record_ the live stream, but also get a `.cue` file together with the recording. **Would this be possible?**

I think LS would be the logical place to generate a `.cue` file, since it knows date, time, and all metadata while playing out.

Reasons:
- Easier reporting what was broadcast, and when.
- Seeing (and jumping to) the titles in later playback of the recording.
- Auto-generating a "show" textual representation for station forums, etc. (What was played at which date/time.)

When using [IDJC](https://idjc.sourceforge.io/) as streaming software, we can already have that (generated by IDJC), and it would be great if something like this would be possible in Liquidsoap, too.

IDJC outputs a recording of what was broadcast with a configurable name, and includes the metadata (and start of broadcast) in the corresponding cue file.

**File example:**

```
aufzeichnung.2019-06-24.160520-r01.cue
aufzeichnung.2019-06-24.160520-r01.mp3
```

**`.cue` file content (abbreviated):**

```cue
TITLE "[2019-06-24][16:05:20]"
PERFORMER "Recorded with IDJC"
FILE "aufzeichnung.2019-06-24.160520-r01.mp3" MP3
  TRACK 01 AUDIO
    TITLE "A.C.D.C. (2006)"
    PERFORMER "Joan Jett and the Blackhearts"
    REM ALBUM "Sinner"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "No Metal, all Rock: 13 Jahre - 13 Titel"
    PERFORMER "Moonbase"
    INDEX 01 00:01:07
  TRACK 03 AUDIO
    TITLE "A.C.D.C. (2006)"
    PERFORMER "Joan Jett and the Blackhearts"
    REM ALBUM "Sinner"
    INDEX 01 01:27:58
  TRACK 04 AUDIO
    TITLE "Runnin' Wild (2007)"
    PERFORMER "Airbourne"
    REM ALBUM "Runnin' Wild"
    INDEX 01 04:48:50
```

**Comment by rrolla** [comment]
This would be a nice feature

**Comment by smimram** [comment]
This is certainly possible, let me propose something for this.

**Comment by Moonbase59** [comment]
@smimram @toots Thanks! Would love to test this, but seem to be a bit blocked today… And it’s not yet in the docs.

- Do we have a minimum working example, say, using a playlist, to record a stream to MP3 and write a corresponding cue file?
- Is there a "start date/time" in the `.cue` like in my example? (It’s not nice putting it in the TITLE but since it’s a recording, it might be okay. We _do_ need something to show start date/time of the recording, for further processing… Using above would make it compatible with _IDJC_, but if all else fails, something like `REM DATE YYYY-MM-DDTHH:MM:SS` could probably also be used.)
- I _think_ I saw a hard.coded `FILE … MP3` somewhere in the code. If so, this might be a bad idea—not everybody saves only MP3 files. I’ve seen `WAVE`, `AIFF`, `MP3` and others here like `FLAC` and `OGG` but the latter seem not standard (couldn’t quickly find anything but [this spec](https://github.com/libyal/libodraw/blob/main/documentation/CUE%20sheet%20format.asciidoc#271-file-types)).
