### ISSUE TITLE
HLS Output: Fragments length does not adhere to EXT-X-TARGETDURATION

### ISSUE THREAD

**Issue by RobinvdGriend** [savonet/liquidsoap#3630]
**Describe the bug**
I've been trying to get HLS working, but I've hit upon very poor performance: HLS players constantly stall when they try to access the stream generated by liquidsoap. I think the problem might be related to the following.

The `#EXT-X-TARGETDURATION` can be set by the `segment_duration` argument of `output.file.hls`. The problem is that the generated segments themselves are not created with the correct length. Indeed, as you can see in the example below the `#EXTINF` of each fragment is 20.00 and the generate `.ts` fragments are also 20 seconds when openend in VLC. The HLS Spec says that fragment length should never exceed the `TARGETDURATION` for this can have performance problems.

Generated .m3u8:
```
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXTINF:1.400,
video_high_1.ts
#EXTINF:20.000,
video_high_2.ts
#EXTINF:20.000,
video_high_3.ts
```

**To Reproduce**
Here is the full script:
```
#!/bin/env liquidsoap
settings.init.allow_root := true

# Studio input
studio = input.rtmp("rtmp://0.0.0.0:1935/studio") 
studio = buffer(fallible=true, buffer=5., studio)

# Fallback
pause_animation = single("/assets/pause_animation.mp4")
pause_sound = single("/assets/pause_sound.wav")
pause = source(source.tracks(pause_animation).{audio=source.tracks(pause_sound).audio})

s = fallback(track_sensitive=false,[studio, pause])

# Output formats
video_high = %ffmpeg(format="mpegts",
  %audio.(codec="aac", b="128k"),
  %video.(codec="libx264", b="2000k", preset="faster")
)

video_low = %ffmpeg(format="mpegts",
  %audio.(codec="aac", b="128k"),
  %video(codec="libx264", b="400k", preset="faster")
)

video_formats = [
  ("video_high", video_high),
  ("video_low", video_low),
]

# Video output
output.file.hls(playlist="video.m3u8",
  temp_dir="/output/tmp",
  "/output/hls",
  video_formats,
  s
)
```
The fallback is generated by muxing an animation loop with a sound loop. The main input is gotten from RTMP.

**Expected behavior**
We expect each fragment to be generated with a length that is ideally equal to `segment_duration` but at least should not exceed it.

We expect this to be reflected in the generated m3u8 file by the `#EXTINF` duration not exceeding the `#EXT-X-TARGETDURATION`.

**Version details**
Using docker with image `savonet/liquidsoap:v2.2.3`

**Comment by toots** [comment]
This should be fixed. I'm not super super fan of the implementation, I wonder if this could cause some stress on the ffmpeg encoder (it is flushed on each frame to be able to know what is that breakable point) so I will keep this for the next major release to give us time to test it. 

It should be possible to have a custom build with this backported against the latest stable code though. I would also recommend testing directly with the `main` branch. We're here to fix errors quickly on this branch!

**Comment by RobinvdGriend** [comment]
@toots Thank you for this!

So I've been testing this on the feature branch and comparing the results, but it seems there is something else wrong with the "non-forced" `2.2.4` segmenter.

When using `%video(codec="libx264", b="2000k", preset="faster", r=30, x264opts="keyint=60:min-keyint=60:no-scenecut")` I'm getting a nice 2 second interval between keyframes[^1]:

```
frame,1,0.066667,I,0,H.26[45] User Data Unregistered SEI message
frame,1,2.066667,I,60
frame,1,4.066667,I,120
frame,1,6.066667,I,180
frame,1,8.066667,I,240
```

So we would expect the segmenter to split this stream into nice 2 second long segments, even with the `v2.2.4` version is that right? Problem is that on `2.2.4` I'm still getting 4 second long segments.

I'm a little bit blind here as I can't really read OCaml and I have a hard time grokking the code that is responsible for the segmenting itself, but could this be a problem with either:
1. The frames not starting exactly on timestamp 0?
2. The frames in the stream are not strictly in order.
3. Some other error in the segmenting logic?

I'm sorry this is a bit of a vague description, but I came to this following this article regarding GOP sizes for HLS streams and how to optimize them. It turns out that `min-keyint` is clamped tot half the max keyframe interval in x264. So we need to either disable scenecuts or force keyframes on set timestamps. https://marcinchmiel.com/articles/2020-10/why-you-should-force-fixed-closed-gops-and-how-to-do-it-in-ffmpeg/

[^1]: This output is generated by `ffprobe test.mp4 -select_streams v -show_frames -of csv -show_entries frame=coded_picture_number,key_frame,pict_type,pts_time | grep -e "frame,1" -e "I"`.

**Comment by toots** [comment]
> @toots Thank you for this!
> 
> So I've been testing this on the feature branch and comparing the results, but it seems there is something else wrong with the "non-forced" `2.2.4` segmenter.
> 
> When using `%video(codec="libx264", b="2000k", preset="faster", r=30, x264opts="keyint=60:min-keyint=60:no-scenecut")` I'm getting a nice 2 second interval between keyframes[1](#user-content-fn-1-5aa9888a7e3fc4e508eec8089655b296):
> 
> ```
> frame,1,0.066667,I,0,H.26[45] User Data Unregistered SEI message
> frame,1,2.066667,I,60
> frame,1,4.066667,I,120
> frame,1,6.066667,I,180
> frame,1,8.066667,I,240
> ```
> 
> So we would expect the segmenter to split this stream into nice 2 second long segments, even with the `v2.2.4` version is that right? Problem is that on `2.2.4` I'm still getting 4 second long segments.
> 
> I'm a little bit blind here as I can't really read OCaml and I have a hard time grokking the code that is responsible for the segmenting itself, but could this be a problem with either:
> 
> 1. The frames not starting exactly on timestamp 0?
> 2. The frames in the stream are not strictly in order. There's a difference between the order of the coded frames and the displayed frames. Sometimes the first _displayed_ keyframe comes after a couple of frames in the coded stream. Sometimes when I check the `.ts` segments, I get an error that states some of these frames are not included in the file. This could perhaps explain the performance degradation. Maybe the segmenter is currently segmenting based on frames as they are presented in the coded stream, instead of how they are ordered in the _displayed_ stream?
> 3. Some other error in the segmenting logic?
> 
> I'm sorry this is a bit of a vague description, but I came to this following this article regarding GOP sizes for HLS streams and how to optimize them. It turns out that `min-keyint` is clamped tot half the max keyframe interval in x264. So we need to either disable scenecuts or force keyframes on set timestamps. https://marcinchmiel.com/articles/2020-10/why-you-should-force-fixed-closed-gops-and-how-to-do-it-in-ffmpeg/
> 
> ## Footnotes
> 1. This output is generated by `ffprobe test.mp4 -select_streams v -show_frames -of csv -show_entries frame=coded_picture_number,key_frame,pict_type,pts_time | grep -e "frame,1" -e "I"`. [↩](#user-content-fnref-1-5aa9888a7e3fc4e508eec8089655b296)

The 2.2.x segment will look for the next keyframe _forward_ from the cut point. So, if the next one is picked your segments are 4s. You could try to reduce the keyframe interval to 1s and this should work better?

BTW I cleaned up the new segmentation further more in `main`, I have more confidence into it not overwhelming the encoder. It was tricky to do :-) There's a callback now from the encoder telling us when a keyframe was found, which prevents the constant use of flush. We keep track of position of the last keyframe is the current segment when encoding and simply truncate the segment right before it when it's time to split!
