### ISSUE TITLE
mksafe does not accept id

### ISSUE THREAD

**Issue by chrispolley** [savonet/liquidsoap#366]
As defined in 1.1.1/utils.liq, mksafe does not accept a defined id.  
This differs from the declared behavior at http://savonet.sourceforge.net/doc-svn/reference.html#mksafe

To fix, edit utils.liq to change declaration of mksafe to include id as an optional argument, and use that in the definition: (also, corrected spelling)

```
# Turn a source into an infallible source.
# by adding blank when the source is not available.
# @param s the source to turn infallible
# @param ~id Force the value of the source ID, defaults to "mksafe"
# @category Source / Track Processing
def mksafe(~id="mksafe", s)
  fallback(id=id,track_sensitive=false,[s,blank(id="safe_blank")])
end
```

**Comment by smimram** [comment]
This was changed in 1.2.0 (commit 744c92b544fd3c7a2db3852c962613ad93aba5fe), please update to the latest version!
