### ISSUE TITLE
socket hangs on "<station>.status" if request for URL gets no response from http.input source

### ISSUE THREAD

**Issue by liquidpeter** [savonet/liquidsoap#367]
We are using telnet command `station.url [url]` to dynamically set an HTTP input URL.
Afterwards we use `station.status` to check if the url is polling, matchs to the URL set before, and further checks.
In case a HTTP request to the URL gets no response from audio stream server, the status command in telnet interface will hang and not return. This will result the client in hanging, too.
A workaround at client is to read from liquidsoap telnet interface using a timeout. From user view it would be better if the status command returns after some time, if connection status cannot be received.

**Comment by toots** [comment]
Hi,

Is the `station.status` a custom telnet command? We have asynchronous functionalities that it may be possible to use here..

**Comment by liquidpeter** [comment]
Hi, sorry I did not notice you comment earlier.
source.status is the build in command.
In opposite to .url it does not just contain the string, but also information like "polling" or "connected".
while .url does work, .status is hanging, if the source stream does not repond, as the given example is currently doing (i am not sure how long the example stream will not work)

an example script:

`set("log.stdout", true)
set("log.file", false)

set("server.telnet", true)
set("server.telnet.port", 1234)
set("server.telnet.bind_addr", "127.0.0.1")

radio = input.http(id="station1", "http://127.0.0.1:8000/radio1")
radio = audio_to_stereo(radio)
radio = mksafe(radio)
output.dummy(fallible=true, radio);


$ telnet localhost 1234

station1.status
polling
END

station1.url http://stanontour.ddns.net:8000
Done
END

station1.url
http://stanontour.ddns.net:8000
END

station1.status
... hangs ...`

**Comment by patrykkrz** [comment]
I have the same problem in version 1.3.3.
How to avoid this? Do you have a solution for this?

**Comment by toots** [comment]
Thanks for the report and insisting. I have just pushed a fix that will go with the next `1.3.7` bugfix release.
