### ISSUE TITLE
Some special characters not escaped properly

### ISSUE THREAD

**Issue by chrispolley** [savonet/liquidsoap#368]
In liquidsoap v.1.1.1, Including an actual backslash in a liquidsoap string is difficult.

For a backslash, the simple declaration:
`bs = "\\"`

generates an "Unterminated String" error.  The second backslash appears to be escaping the second quote, which is not what I expected.

similarly, the declaration:

`lf = "\\n"`

does not generate a string containing a backslash-n combination, which is needed, for instance, in constructing a multi-line system call, such as using socat to set another liquidsoap instance's interactive.string variables

The work-around I have been able to come up with is to base64-encode the desired string and assign it using the base64.decode function:
```
lf = base64.decode("XG4=")
bs = base64.decode("XA==")
```
and then including them in other strings using the #{bs} or #{lf} phrase.

**Comment by toots** [comment]
That's a smart workaround! @dbaelde maybe be able to help on this one..

**Comment by toots** [comment]
I closed this one by adding this:
```
# x = "\092";;
x : string = "\\"
```

Also, `\n` can be obtained simply as:
```
# x = "\n";;
x : string = "\n"
```
