### ISSUE TITLE
SHOUTcast Metadata update may have failed

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#369]
My configuration - http://pastebin.com/raw/rz7nPj1i the logs show this error:
> [output(dot)shoutcast:3] Metadata update may have failed with error: bad answer
Why?

My SHOUTcast Server Version is 1.9.8/Linux

**Comment by toots** [comment]
That's a good question heh. Do you have any more logs perhaps from shoutcast itself?

**Comment by desavil** [comment]
The metadata is updated properly. It's just a matter of wrong information in the liquidsoap logs.

**Comment by vrtisworks** [comment]
I have the same problem.  Shoutcast Version 1.9.8/Linux.  Liquidsoap 1.2.1 on a Raspberry Pi installed from OCAML.

The Shoutcast logs do not show any problems, or even mention that they got additional metadata (which is normal).  They do show the correct metadata.

I am broadcasting to Second Life.. and the Second Life client shows the Metadata as it comes in.  So it appears that all the pieces 'work'.. just a confusing message from Liquidsoap.

Here is my simple Liquidsoap testing file

#!/home/liquidsoap/.opam/system/bin/liquidsoap
set("log.file",false)
set("log.stdout",true)
source = single("FirstTest.mp3")

output.icecast(%mp3, host="bigboh.vrtisworks.com",
                     port=5863, password="hackme",
                     protocol="icy",public=false,
                     genre="Rock",icy_metadata="true",
                     source)


If I change icy_metadata="false", no metadata is sent, and there is no error message.







                               [ Read 10 lines ]
^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Page ^K Cut Text  ^C Cur Pos
^X Exit      ^J Justify   ^W Where Is  ^V Next Page ^U UnCut Text^T To Spell

**Comment by desavil** [comment]
My investigation showed that the problem occurs when broadcasting to the old SHOUTcast v1. This problem does not occur on SHOUTcast v2.
