### ISSUE TITLE
prepend / skip causing crash.

### ISSUE THREAD

**Issue by Russsgithub** [savonet/liquidsoap#3696]
**Describe the bug**
If i skip a track in metadata.map that has prepend further down the skip I get #get_frame added too many breaks, then shutdown.

```
2024/02/02 09:01:58 [prepend_0:2] #get_frame added too many breaks!
2024/02/02 09:01:58 [clock.main:2] Source dummy failed while streaming: File "source.ml", line 664, characters 12-18: Assertion failed!
2024/02/02 09:01:58 [clock.main:2] Raised at Source.operator#get in file "source.ml", line 664, characters 12-24
2024/02/02 09:01:58 [clock.main:2] Called from Output.output#output in file "outputs/output.ml", line 166, characters 10-30
2024/02/02 09:01:58 [clock.main:2] Called from Clock.clock#end_tick.(fun) in file "clock.ml", line 300, characters 14-22
```

**To Reproduce**
```
s = sine(440.)

def map(m)
  s.skip()
  []
end

s = metadata.map(update=false, strip = true, map, s)

s = prepend(s, fun(_) -> blank(duration=4.))

output.dummy(s)
```

**Version details**

- OS: [e.g. Debian, OSX] Ubuntu and docker
- Version [e.g. `1.3.4`] 2.2.x rolling-release

**Install method**
opam and docker

**Comment by toots** [comment]
Hi! Thanks for reporting. I can't reproduce with the following script:

```liquidsoap
s = sine(440.)

def map(_)
  s.skip()
  []
end

s = metadata.map(update=false, strip = true, map, s)

s = prepend(s, fun(_) -> blank(duration=4.))

clock.assign_new(sync="none",[s])

output.dummy(s)
```

**Comment by Russsgithub** [comment]
Neither can i now ( with the original script).

I commented the line in my full script to stop the crash, but have un commented it now and run it back up again.

I'll close this for now and re open with more info if it comes back.

Sorry if this was a false flag.

Thanks

**Comment by toots** [comment]
Ok sounds good. Doesn't look like a false flag but rather something tricky to fix.

Good news is, in `2.3.x` we have gotten rid of this specific error!
