### ISSUE TITLE
SHOUTcast 2 add dj argument to updinfo

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#370]
SHOUTcast 2 use dj argument in metadata:
admin.cgi?pass=xxx&mode=updinfo&song=songname&dj=name

I suggest add this function in output.icecast(dj="my nick") and/or output.shoutcast(dj="my nick") or if password is: my nick:xxx:#1

> Changes from 2.0.0 build 29 to 2.2.0 build 107:
> (16th October 2013)
> 
> Added 'Stream DJ' (if known) on the stream admin pages as well as <DJ/> in all statistics for getting the current DJ of the connected source (more formal specification than fiddling the IRC / AIM / ICQ values as used with 1.x DNAS setups)
> 
> Added 'dj' parameter to the 'updinfo' action to allow for scripted updating of the 'DJ' reported for a stream (useful for legacy source software)

**Comment by toots** [comment]
Thanks for the report! Just added an optional `"dj"` parameter for metadata updates. `output.shoutcast` now has a `dj` argument to make use of it. If you set it to return your dj name, it should be included with the next metadata update. 

Any chance you could test it?

**Comment by desavil** [comment]
Error:
> At line 20, char 125-130:
  this value has type
    string
  but it should be a subtype of (the type of the value at /usr/local/lib/liquidsoap/scm/shoutcast.liq, line 28, char 28)
    ()->_ (inferred at /usr/local/lib/liquidsoap/scm/shoutcast.liq, line 28, char 29-32)

**Comment by toots** [comment]
Yeah, it should be `dj={"my nick"}`.  Should be working now with ef6bf6d

**Comment by desavil** [comment]
Now it works fine. 👍
