### ISSUE TITLE
Transition to a short track cuts the next track but one

### ISSUE THREAD

**Issue by RM-FM** [savonet/liquidsoap#3731]
**Describe the bug**
While testing the new `delay` feature for `fade.out` and `fade.in`, I took note of strange cuts at the end the next track but one.

**To Reproduce**
```
def clean_transition(old, new) =

  def safe_float_of_string(str) =
    try
      float_of_string(str)
    catch _ do
      0.
    end
  end

  jingle_transition = new.metadata["jingle_mode"]
  cross_duration = safe_float_of_string(old.metadata["liq_cross_duration"])
  fade_out = ref(safe_float_of_string(old.metadata["liq_fade_out"]))
  cue_in = safe_float_of_string(new.metadata["liq_cue_in"])
  delay = ref(0.)
  fade_in = ref(0.)
  lbl = "clean_transition"

  add = fun (a, b) -> add(normalize=false, [b, a])
  sequence = fun (a, b) -> (sequence([a, b]) : source)
  
  if jingle_transition == "true" then
    if cross_duration > 3.0 then
      delay := cross_duration - 3.0
      fade_out := 3.
      fade_in := 0.
    end
  end
  
  fade_out := max(fade_out(), 0.1)
  if cue_in >= 0.1 then fade_in := 0.1 end

  let fade.out = fun (s) -> fade.out(type="exp", duration=fade_out(), delay=delay(), s)
  let fade.in = fun (s) -> fade.in(type="log", duration=fade_in(), delay=delay(), s)

  if cross_duration > 0. then
    if jingle_transition == "true" then
      log(label=lbl,"Jingle transition")
    end
    log(label=lbl,"Crossfade. Duration: #{cross_duration}. Fade out: #{fade_out()}. Fade in: #{fade_in()}. Delay: #{delay()}")
    if fade_out() > 0. and (fade_in() > 0. or jingle_transition == "true") then 
      add(fade.out(old.source), fade.in(new.source))
    elsif fade_out() > 0. and fade_in() <= 0. and jingle_transition != "true" then 
      add(fade.out(old.source), new.source)
    elsif fade_out() <= 0. and (fade_in() > 0. or jingle_transition == "true") then 
      add(old.source, fade.in(new.source))
    else
      add(old.source, new.source)
    end
  else
    log(label=lbl,"Sequence. Fade out: #{fade_out}. Fade in: #{fade_in}.")
    if fade_out() > 0. and fade_in() > 0. then 
      sequence(fade.out(old.source), fade.in(new.source))
    elsif fade_out() > 0. and fade_in() <= 0. then 
      sequence(fade.out(old.source), new.source)
    elsif fade_out() <= 0. and fade_in() > 0. then 
      sequence(old.source, fade.in(new.source))
    else
      sequence(old.source, new.source)
    end
  end

end

radio = cross(clean_transition,radio)
```

**Expected behavior**
Tracks should be fully played but not cut too early.

**Version details**

- Debian 22.04 LTS
- 2.2.4 [(Hotfix)](https://github.com/savonet/liquidsoap/commit/2e210880571e750607150d40721e3fbfe5fe8715)

**Install method**
Azuracast Rolling Release https://github.com/AzuraCast/AzuraCast/commit/ab9b626103a134ba74b9c8de0898303123c1ff00

**Comment by RM-FM** [comment]
This issue has been resolved. I could no longer reproduce it, or rather, I believe it is related to how "Skip Song" is implemented in AzuraCast.

**Comment by RM-FM** [comment]
@toots The issue is not delay related. It seems to be caused by short tracks where old.source crossfade duration is longer than new.source total duration.

I tried to avoid the overlap entirely by using sequence instead, but the issue persists.

**Comment by RM-FM** [comment]
@toots You should be able to reproduce it with `sequence`as soon as `new.source` is shorter than buffer/crossfade duration. Sometime the jingle is even repeating.

According to Release Notes of 2.2.4 `sequence` is the correct way to handle short tracks like jingles.

```
let fade.out = fun (s) -> fade.out(type="exp", duration=2., s)
sequence([fade.out(old.source), new.source])
```

**Comment by RM-FM** [comment]
As a workaround, I have added 10 seconds of silence at the end of our jingles and removed `cue_out`. Instead I set crossfade duration only to make sure there is enough buffer data.

**Comment by RM-FM** [comment]
@toots This issue was also mentioned in Azuracast Discussion https://github.com/AzuraCast/AzuraCast/discussions/6252

**Comment by toots** [comment]
@RM-FM can this be closed?
