### ISSUE TITLE
Please migrate away from Pcre

### ISSUE THREAD

**Issue by paddatrapper** [savonet/liquidsoap#3750]
**Describe the bug**
Pcre has been removed from Debian, causing liquidsoap to fail to build. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064128 for the build output

**To Reproduce**
Build Liquidsoap without ocaml-pcre available. 

**Expected behavior**
Liquidsoap should build

**Version details**

- OS: Debian unstable
- Version 2.2.3

**Install method**
Debian package

**Comment by paddatrapper** [comment]
Fixed in https://github.com/savonet/liquidsoap/pull/2085 and https://github.com/savonet/liquidsoap/pull/3613, released in 2.2.4

**Comment by paddatrapper** [comment]
Seems that this was not fixed in 2.2.4, as at least some of the move was reverted in https://github.com/savonet/liquidsoap/commit/854d1e7ce9d413601c880185506f3edcba28caeb

**Comment by paddatrapper** [comment]
The revert seems just to have happened for 2.2.4? It looks like the `main` branch still carries the fixes, but 2.2.4 does not. @toots do you know what is happening?

**Comment by toots** [comment]
Yes, the migration will be effective when `2.3.0` comes out. This is too large of a migration to be applied in the stable release cycle.

We are planning on starting a `2.3.0` release soon.

**Comment by toots** [comment]
I'll try to make a patch for you to be able to update debian tho.

**Comment by paddatrapper** [comment]
Thanks! That would be greatly appreciated

**Comment by toots** [comment]
@paddatrapper we're talking about build for the next stable debian release correct? The changes are too invasive for `2.2.x` I'm afraid but the `2.3.x` release should happen in the next couple of months and will definitely be without `pcre`.

**Comment by paddatrapper** [comment]
I had hoped to get this fixed for Ubuntu 24.04, but I was about a month too late for that, so targeting 24.10, which will have Debian import freeze around August

**Comment by toots** [comment]
Cool. Yeah I'd love to have `2.2.x` on it as it's clearly getting super stable now but the changes to switch are really invasive and I'm not very confident. I'll have another pass nonetheless.

**Comment by toots** [comment]
This is done in `2.3.x` which will be the next release.

**Comment by paddatrapper** [comment]
Thanks a lot!
