### ISSUE TITLE
More predictable release file names

### ISSUE THREAD

**Issue by rmens** [savonet/liquidsoap#3755]
The 2.2.3 release was named `liquidsoap_2.2.3-debian-bookworm-1_arm64.deb` while the 2.2.4 release had a 2 in the filename `liquidsoap_2.2.4-debian-bookworm-2_arm64.deb`

This lead me to bang my head against the wall about why my installation script was 404'ing while I did update the version number. Took me a while to figure out the 1 was replaced by a 2.

It's a nitpicky detail, but can the file names for release be made more predictable in this way too? Thanks!

**Comment by rmens** [comment]
Ah I wasn’t aware that the ‘2’ was caused by a hofix re-release. Makes sense. Unfortunately that still breaks basic scripting with the version number as variable on the release assets repo. But maybe it is what it is and my implementation is too basic.

**Comment by toots** [comment]
I have taken notice of the general opposition to hotfix releases.
