### ISSUE TITLE
when using buffered() on input.http it always returns 0.

### ISSUE THREAD

**Issue by mooseh** [savonet/liquidsoap#3778]
**Describe the bug**
i have an input.http which i have set the max_buffer to 10.0 and i have a prometheus metric monitoring this
but when running the buffered() method it is always 0, im not sure this is normal behaviour.

additionally to this buffer_length() is in the api docs against input.http but does not actually exist anymore.

**To Reproduce**
here is a scfript to simply print the buffer value
```
        def get_input_buffer(source) =
            def callback() =
                bufferItem = list.nth(source.buffered(), 0)
                bufferValue = snd(bufferItem)
                print("the buffer is #{bufferValue} on #{source.url()}")
            end
            callback
        end

        url = "https://direct.sharp-stream.com/ssradioprem.mp3"
        source = input.http(
            id="#{url}",
            timeout=10.0,
            poll_delay=2.0,
            max_buffer=10.0,
        url)
        
        thread.run(every=1., get_input_buffer(source))
```

**Expected behavior**
I expect the buffer value to sit near to 10 and fluctuate slightly 

**Version details**
docker v2.2.3

**Install method**
FROM savonet/liquidsoap-alpine:v2.2.3

**Comment by vitoyucepi** [comment]
Hi @mooseh,
I can't confirm this behavior, but maybe I'm doing something wrong, for example, my reproduction script is oversimplified.
```ruby
url = "http://icecast/stream.mp3"
s = input.http(
    id="#{url}",
    max_buffer=10.0,
    url,
)

def get_input_buffer(s) =
    print(s.buffered())
    print(s.buffer_length())
end

thread.run(every=1., {get_input_buffer(s)})
output.dummy(s, fallible=true)
```

```
[("audio", 0.00764172335601)]
0.00764172335601
[("audio", 0.0156462585034)]
0.0156462585034
[("audio", 0.0396371882086)]
0.0396371882086
```

**Comment by mooseh** [comment]
thanks for this, turns out wrapping an input.http removed these methods and then causes it to constantly report 0.
@vitoyucepi thanks for all your help :+1:
