### ISSUE TITLE
Percent encoding in URLs with http functions

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3789]
**Describe the bug**
When I try to use percent-encoded entities in the url of the `http.get()` it decodes them, thus breaking the url.

**To Reproduce**
1. Start the http server.
1. Start Wireshark.
1. `http.get("http://192.168.0.1/%2f")` -> `GET //`.
   `http.get("http://192.168.0.1/\%2f")` -> `GET /%5C%2F`.
   `http.get("http://192.168.0.1/%2e")` -> `GET /`.
1. `curl http://192.168.0.1/%2f` -> `GET /%2F`.
   `curl http://192.168.0.1/\%2f` -> `GET /\%2F`.
   `curl http://localhost:8000/%2e` -> `GET /%2e`.

**Expected behavior**
Percent-encoded entities should be left as they are.

**Version details**

- OS: *debian:12* in docker
- Version: *2.2.4-1*

**Install method**
*savonet/liquidsoap:v2.2.4*

**Common issues**
https://github.com/savonet/liquidsoap/discussions/3782#discussioncomment-8693869

**Comment by toots** [comment]
The issue was introduced while trying to fix https://github.com/savonet/liquidsoap/issues/2551
