### ISSUE TITLE
input.harbor - SHOUTcast no: icy-name

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#380]
My configuration:
> def on_harbor_connect (headers) =
  list.iter (fun(h) -> log("header: #{fst(h)}: #{snd(h)}"), headers)
end
live = input.harbor("/",port=8000,password="hackme",icy=true,on_connect=on_harbor_connect)

Logs:
> 2017/01/10 00:40:02 [lang:3] header: icy-genre: R&B and Urban
2017/01/10 00:40:02 [lang:3] header: icy-url: http://www.test.com
2017/01/10 00:40:02 [lang:3] header: icy-irc: N/A
2017/01/10 00:40:02 [lang:3] header: icy-icq: 0
2017/01/10 00:40:02 [lang:3] header: icy-aim: N/A
2017/01/10 00:40:02 [lang:3] header: icy-pub: 1
2017/01/10 00:40:02 [lang:3] header: icy-br: 128
2017/01/10 00:40:02 [lang:3] header: content-type: audio/mpeg

There is no "Name" (icy-name) - https://i.snag.gy/ClUVNA.jpg

**Comment by toots** [comment]
Have you checked what is effectively passed by the client? `set("log.level",4)` should help..

**Comment by desavil** [comment]
> 2017/01/10 10:51:44 [harbor:4] New client on port 8001: x.x.x.x
2017/01/10 10:51:44 [harbor:4] Header: icy-genre, value: R&B and Urban.
2017/01/10 10:51:44 [harbor:4] Header: icy-url, value: http://www.test.com.
2017/01/10 10:51:44 [harbor:4] Header: icy-irc, value: N/A.
2017/01/10 10:51:44 [harbor:4] Header: icy-icq, value: 0.
2017/01/10 10:51:44 [harbor:4] Header: icy-aim, value: N/A.
2017/01/10 10:51:44 [harbor:4] Header: icy-pub, value: 1.
2017/01/10 10:51:44 [harbor:4] Header: icy-br, value: 128.
2017/01/10 10:51:44 [harbor:4] Header: content-type, value: audio/mpeg.
2017/01/10 10:51:44 [harbor:4] ICY request on /.
2017/01/10 10:51:44 [harbor:4] Adding source on mountpoint "/" with type "audio/mpeg".
2017/01/10 10:51:44 [decoder:4] Trying method "WAV" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:4] Trying method "AIFF" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:4] Trying method "PCM/BASIC" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:4] Trying method "RAW AUDIO" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:4] Trying method "FLAC" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:4] Trying method "AAC" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:4] Trying method "OGG" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:4] Trying method "MAD" for "audio/mpeg"...
2017/01/10 10:51:44 [decoder:3] Method "MAD" accepted "audio/mpeg".
2017/01/10 10:51:44 [lang:3] header: icy-genre: R&B and Urban
2017/01/10 10:51:44 [lang:3] header: icy-url: http://www.test.com
2017/01/10 10:51:44 [lang:3] header: icy-irc: N/A
2017/01/10 10:51:44 [lang:3] header: icy-icq: 0
2017/01/10 10:51:44 [lang:3] header: icy-aim: N/A
2017/01/10 10:51:44 [lang:3] header: icy-pub: 1
2017/01/10 10:51:44 [lang:3] header: icy-br: 128
2017/01/10 10:51:44 [lang:3] header: content-type: audio/mpeg

**Comment by toots** [comment]
So, no `icy-name` is passed down to `input.harbor`, which explains why you do not see it..

**Comment by desavil** [comment]
Please look this (yellow) - https://i.snag.gy/3MPGHV.jpg
Tcpdump log from server with liquidsoap.

**Comment by toots** [comment]
Interesting, thanks. Could you attach a ASCII dump of it?

**Comment by desavil** [comment]
I sent you an e-mail.

**Comment by toots** [comment]
Well, that was another stupid one.. Thanks for the report, fixed in 04c28e0
