### ISSUE TITLE
Help - rewrite_metadata for icy value from input.harbor

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#381]
Hi,

My provisional configuration:
> live = input.harbor("/",port=8000,password="hackme",icy=true)
live = rewrite_metadata([("dj","Name: icy-name, Genre: icy-genre")], live)

How to dynamic change "icy-name" and "icy-genre" to value from harbor client?

I would greatly appreciate to someone help me do it.
Thanks!

**Comment by toots** [comment]
Hi,

You should do something like this:

```
headers = ref []

def on_connect(new_headers) =
  headers := new_headers
end

live = input.harbor("/",port=8000,password="hackme",icy=true,on_connect=on_connect)

def add_dj_metadata(metadata) =
  headers = !headers then

  if headers["icy-name"] != "" && headers["icy-genre"] != "" then
    list.add(("dj", "Name: #{icy-name}, Genre: #{icy-genre}"), metadata)
  else
    metadata
  end
end

live = map_metadata(add_dj_metadata, live)
```

Haven't tested it but that's the idea.

I'm closing here since this is not related to the current code. Feel free to bring the discussion over to the mailing list!

**Comment by desavil** [comment]
It works. Thank you very much for help.

Of course, I sign up for the mailing list.

**Comment by toots** [comment]
Sweet!
