### ISSUE TITLE
HLS with ADTS muxing doesn't represnt transportStreamTimestamp correctly

### ISSUE THREAD

**Issue by JonathanThorpe** [savonet/liquidsoap#3817]
**Describe the bug**
When creating an HLS stream using either %ffmpeg or %fdkaac encoders with the ADTS transmux, as per https://datatracker.ietf.org/doc/html/rfc8216#section-3.4 there's a requirement to include a "com.apple.streaming.transportStreamTimestamp" tag which LS attempts to do.

Using ffprobe, this metadata appears as `id3v2_priv.?com.apple.streaming.transportStreamTimestamp`. Note the erroneous `?` which might be coming from an empty byte in the frame (removing this with a hex editor shows the correct result).

**To Reproduce**

```
config_aac_lofi = %fdkaac(channels=2, samplerate=48000, bandwidth="auto", vbr=1, afterburner=false, aot="mpeg4_he_aac", transmux="adts", sbr_mode=false).{
                      id3_version = 4,
                      replay_id3 = true}

output.file.hls(playlist="test.m3u8",
                  hls_segments_directory,
                  temp_dir=temp_dir,
                  persist_at="#{persist_dir}/persist.config",
                  segment_duration=10.,
                  segments=7,
                  segments_overhead=10,
                  segment_name=segment_name,
                  [("hifi", config_aac_hifi)],
                  hls_source)
```

**Expected behavior**

Using `ffprobe -i test.m3u8`, `id3v2_priv.com.apple.streaming.transportStreamTimestamp` is expected to show correctly.

**Version details**

2.2.4

**Install method**
Official Docker container.

**Comment by toots** [comment]
Thanks for reporting. This should be fixed in the latest `rolling-release-v2.2.x` and `main`.
