### ISSUE TITLE
Cannot run a simple script from the doc

### ISSUE THREAD

**Issue by mtrabelsi** [savonet/liquidsoap#382]
**What's your LS version ?**

```
marwen@lalala:~$ liquidsoap --version
Liquidsoap 1.2.1+scm (git://github.com/savonet/liquidsoap.git@be69c091d54d407d94ca02d9070cf870c98851b1:20170112:023730)
Copyright (c) 2003-2016 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.fm> for more information.

```
**What about your tree folders and files ?**
.
├── music
│   ├── 3910.mp3
│   └── Canon.mp3
├── myscript.liq
└── playlist.m3u

**What script are you running?** 
The same script taken from the doc, myscript.liq :

```
liquidsoap 
  'output.icecast(%vorbis,
     host = "localhost", port = 8000, \
     password = "hackme", mount = "liq.ogg", \
     mksafe(playlist("playlist.m3u")))'

```

**What about M3U file ? :** 

```
marwen@vps311337:~$ cat playlist.m3u 
/home/marwen/music/3910.mp3
/home/marwen/music/Canon.mp3

```

Running either :
./myscript.liq
or 
liquidsoap myscript.liq

**Error I get :** 

> At line 2 char 12 - line 3 char 0: the variable liquidsoap used here
>   has not been previously defined.

**Comment by hairmare** [comment]
You .liq script contains a shell one-liner and not the liquidsoap code. What you want, is to only have the actual liquidsoap code in the file:

```
output.icecast(%vorbis,
     host = "localhost", port = 8000,
     password = "hackme", mount = "liq.ogg",
     mksafe(playlist("playlist.m3u")))
```

You can then run it using `liquidsoap myscript.liq`. If you want to run it directly you need to tell the shell by adding a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) on the first line like so:

```
#!/usr/bin/liquidsoap

output.icecast(%vorbis,
     host = "localhost", port = 8000,
     password = "hackme", mount = "liq.ogg",
     mksafe(playlist("playlist.m3u")))
```

You can get the path to actual liquidsoap binary by running `which liquidsoap`. And you need to make the file executable with `chmod +x myscript.liq` for this to work.

**Comment by mtrabelsi** [comment]
@hairmare : Thanks for your clarifications!
Unfortunately, this still reproduced with one-liner command : 
```

marwen@vpsblablaba:~$ liquidsoap 'output.icecast(%vorbis,
     host = "localhost", port = 8000, \
     password = "hackme", mount = "liq.ogg", \
     mksafe(playlist("playlist.m3u")))'
Line 2, char 39: Empty token!

```

**Comment by mtrabelsi** [comment]
Am gonna close this as I get the server running, but my previous comment is still open, looking forward for some explanations :-)

**Comment by hairmare** [comment]
The issue with the one liner is the backticks. They are not needed since the shell already expects an open string to wrap multiple lines.

```
liquidsoap 'output.icecast(%vorbis,
     host = "localhost", port = 8000, 
     password = "hackme", mount = "liq.ogg", 
     mksafe(playlist("playlist.m3u")))'
```

**Comment by mtrabelsi** [comment]
Thanks for the commit! @hairmare
