### ISSUE TITLE
Playlist mode='random' - Play unique

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#386]
When I set playlist mode to random then I often see that one track play e.g. 3x drubbing and other track do not play ever.

Can it be changed?

For example, when playlist start then track randomizes in the playlist, after playing all track the action is repeated (randomize track in the playlist).

**Comment by StudentSA** [comment]
Im just a user so I may be wrong. but I suggest you try adding the following to your playlist command:
mode="randomize",reload=1,reload_mode="rounds"

**Comment by desavil** [comment]
It works, thank you!
