### ISSUE TITLE
2.3.0 - check_next doesn't read metadata

### ISSUE THREAD

**Issue by gAlleb** [savonet/liquidsoap#3864]
I'm trying to make `check_next` work in 2.3.0. It works ok with default `filename` (with no extra parameters specified). But if I want to reject tracks by title/artist/etc... - it starts looping because metadata always returns empty. Log:

```ruby
  [
  "",
  1712487606.54
]
```

In 2.2.5 - All is good.

Reproduction (every 2.3.0 version - packages and opam):

```ruby
def hash_artist(m)
      metadata.artist(m)
end

l = playlog(persistency="check.log", duration=10000., hash=hash_artist)
def check(r)
      m = request.metadata(r)
  if l.last(m) < 7000. then
      log(level=3,"#{m['artist']} has played #{l.last(m)}s ago. Rejecting...")
      false
  else
      l.add(m)
      true
  end
end
```

**Comment by vitoyucepi** [comment]
Hi @gAlleb,
I'd like to point out that `check_next` is called before the request is resolved. So there will be no metadata until the request is resolved.
Ref: #3625.
I don't remember exactly why I created this issue, but it seems I have a lot of garbage in the music directory and want to discard files before decoding.

**Comment by gAlleb** [comment]
I've tried something like this (and a bunch of different iterations) but result is the same.
```ruby
def check(r)
      
  if request.resolve(r) then
	m = request.metadata(r)
        if l.last(m) < 7000. then
	   log(level=3,"Rejecting")
	   false
        else
	  l.add(m)
	  true
        end
  else
  false
  end

end
```

What am I doing wrong?

**Comment by toots** [comment]
Could be another regression. I'll have a look shortly, thanks for reporting.

**Comment by vitoyucepi** [comment]
Ref: 28cceeccee26a1b170528857e8c0503069f75e03, 03f65e8f57676388a6068461aae679e70a0f6152, 25e7189ce5a34f5ff7697ccc4800396568dd54e2, #3874, d2a38cf31aa3ed999a45e5443f11c56008ee3c51

**Comment by gAlleb** [comment]
Many thanks!
