### ISSUE TITLE
SHOUTcast 2 add "next" (song) argument to updinfo

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#388]
SHOUTcast 2 have "next" argument in metadata:
admin.cgi?pass=xxx&mode=updinfo&song=songname&next=next-songname

Could you add it to take as a title of the next song?

**Comment by desavil** [comment]
How to use this?

**Comment by toots** [comment]
You need to provide a `next` metadata. You can use `annotate:...` on a request or a custom `map_metadata` operator.

**Comment by desavil** [comment]
I do not understand.
Could you give me an example configuration?

**Comment by toots** [comment]
Well, it depends on how you fetch files in your liquidsoap install. Can you
tell us more about your script? :-)

2017-03-18 14:14 GMT-05:00 desavil <notifications@github.com>:

**Comment by desavil** [comment]
I will return to this application.

Maybe you would consider adding to output.shoutcast parameter, e.g `shoutcast2_moreupd=true/false` (default `false`) and that would send the name of the next song?

Well, you already know the configuration. :)
```
set("log.stdout",false)
set("init.daemon",true)
set("init.daemon.pidfile.path","/home/liquid/liquidsoap.pid")
set("log.file",true)
set("log.file.path","/home/liquid/liquidsoap.log")
def update_songtitle(m) =
if m["title"] == "" then
[("title",list.hd(default="",string.split(separator="\.mp3",(list.hd(default="",list.rev(string.split(separator="/",m["filename"])))))))]
else
[("title",m["title"])]
end
end
radio = mksafe(audio_to_stereo(playlist(mode="normal","/home/liquid/playlist.m3u")))

radio = map_metadata(update_songtitle,radio)
output.shoutcast(%fdkaac(bitrate=96,samplerate=44100,channels=2),name="Name",genre="Genre",url="http://website.tld",public=true,host="localhost",port=8000,password="pass",on_error=(fun (_) -> 10.),radio)
```

**Comment by MattMski** [comment]
I would like to know how to do this, I get the logic of what needs to be done but i'd need to know how to code it in liquidsoap
