### ISSUE TITLE
Build with dev informations without Git dependency

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3899]
**Is your feature request related to a problem? Please describe.**
I would like to be able to build without having a direct dependency on git.

**Describe the solution you'd like**
1. If `git` exists, and the git repository was found, and the exit code of the `git` command is 0, then use the result of the `git` command.
2. Otherwise, if an environment variable such as `VERSION_HASH`, `COMMIT_ID` or `GIT_COMMIT` is set, then use it.
3. Otherwise, use an empty string or literally *unknown*. *(none)* is also fine, I guess.

**Describe alternatives you've considered**
Maybe it would be great to integrate with `IS_SNAPSHOT` somehow.

**Additional context**
If the project is built from github source archives like `https://github.com/savonet/liquidsoap/archive/$_commit.tar.gz`, then the git repository will not be available, but the commit could easily be set using the environment variable.

In addition, it would be great to explain all build time environment variables in the build manual.

**Comment by vitoyucepi** [comment]
The alpine *APKBUILD* I use has no support for sourcing git repositories, unlike archlinux *PKGBUILD* which has support for something like `git+https://github.com/savonet/liquidsoap.git#commit=$_commit`.
So I have to rely on the archive tarball to build from the rolling release and main branches.

**Comment by toots** [comment]
@vitoyucepi this should be addressed in https://github.com/savonet/liquidsoap/pull/4032 with two override env variables.

We should probably start adding a `dune` build guide to our doc. Is that something that you'd be interested to write? I know that you already have an excellent tutorial in the discussions section..

**Comment by vitoyucepi** [comment]
Hi @toots,
I can write the dune build guide, but I'll need you to proofread it since I know very little about it.

**Comment by toots** [comment]
Definitely!
