### ISSUE TITLE
HLS stream will not change audio quality

### ISSUE THREAD

**Issue by K1oma** [savonet/liquidsoap#3908]
**Describe the bug**

I've made an HLS stream that streams audio quality in 320kbps, 192kbps, 96kbps. When I play the stream in VLC or SMPlayer the stream starts at 96kbps for 3-4 seconds and then goes to 320kpbs, which is great. Then I throttle my network to test if it will go to the lower quality with one question in mind, what if someone that listens to my radio station and then their internet got worse? I want their stream to go down from 320kbps to 192kbps or 96kpbs. But in the reality, when I throttle my network, the stream stops instead of going down in quality. I tried numerous players that support ABR either on PC and iPhone, and they all give the same results. 

**To Reproduce**

`settings.log.file.set(false)`
`enable_replaygain_metadata()`

`input = cue_cut(cue_in_metadata="liq_cue_in",playlist(mode="normal",reload=1,reload_mode="rounds","plejlista-processed.m3u8"))`
`input = crossfade(fade_out=0.01, fade_in=0., default=(fun(a,b)->add(normalize=false,([b, a]))), conservative=true, input)`
`aac_lofi = %ffmpeg(format="mpegts",
                    %audio(
                      codec="aac",
                      channels=2,
                      ar=44100,
                      b="96k"
                    ))`
`aac_midfi = %ffmpeg(format="mpegts",
                    %audio(
                      codec="aac",
                      channels=2,
                      ar=44100,
                      b="192k"
                    ))` 
`aac_hifi = %ffmpeg(format="mpegts",
                   %audio(
                     codec="aac",
                     channels=2,
                     ar=44100,
                     b="320k"
                   ))` 
`streams = [("aac_lofi",aac_lofi),
           ("aac_midfi", aac_midfi),
           ("aac_hifi", aac_hifi)]` 

`def segment_name(~position,~extname,stream_name) =
  timestamp = int_of_float(time())
  duration = 2
  "#{stream_name}_#{duration}_#{timestamp}_#{position}.#{extname}"
end` 

`input = mksafe(normalize(input, gain_max = 3.0, gain_min = 1., target = -13.0, threshold = -65.0))
output.harbor.hls(port=8088, path="stream/",segment_duration=6.,segments=10, streams, input)` 

**Expected behavior**

I expect my stream to go from 320kbps to 192kbps/96kbps without interruption if the client has bad internet or internet stoppage. Also, the stream needs to be without any pauses, silence or anything like that.

**Version details**

- OS: [Debian]
- Liquidsoap version: [v2.1.4]

**Install method**
1. Did you install via `opam`? Yes
2. Using your distribution's packages? Yes
3. From source? Yes

**Comment by gAlleb** [comment]
Hi! I think it's not LS issue at all. Such players as `VLC` should work great with HLS - some don't. 
`iOS` specifically has very interesting problem: it starts from `lo-fi` and never goes up ;) so I had to set quality of the streams explicitly. Also I've tested LS HLS streams on latest Android and VLC - they work normally. 

To sum up: it all depends on the software you are using to listen to HLS streams.

**Comment by K1oma** [comment]
Thanks for the tips, gAlleb!

I have updated it on 2.2.5+dev
Now I have a different problem with config. It seems I cant find a new config on thei internet, do you have any links or configs laying around for HLS?

The problem:

At liquid.conf, line 30 char 11 - line 36 char 22:
aac_lofi = %ffmpeg(format="mpegts",
                    %audio(
...
                      b="96k"
                    ))

Error 12: Unsupported encoder: %ffmpeg(format="mpegts", %audio(codec="aac", channels=2, ar=44100, b="96k")).
You must be missing an optional dependency.

**Comment by gAlleb** [comment]
Don't forget to upgrade/install `ffmpeg`. It should have been upgraded automatically.

You could also add `{id3_version = 4}` something like this - `opam install ffmpeg` %ffmpeg(format="mpegts",%audio( codec="aac",channels=2, ar=44100,b="96k")).{id3_version = 4}

HLS now supports metadata so you can see it in your player (usually http protocol only).

Normal setup could be with `ocaml compiler 4.14.2`

**Comment by K1oma** [comment]
Thank you gAlleb, I really can't thank you enough. Thank you for your time and efforts!
