### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#392]
Hight resource usage (especially RAM, next CPU) for two liquidsoap instances - https://i.snag.gy/MG9WmY.jpg

I noticed that this happens, as the SHOUTcast server is turned off but liquidsoap running (broadcasting).

1. Last 100 lines of log file - http://pastebin.com/raw/iJt0YjJx
2. Last 100 lines of log file - http://pastebin.com/raw/HF1PGyPn
Why liquidsoap preparing files? SHOUTcast Server is turned off so should do reconnect every x seconds (as above in 1).

Resource usage after kill the two liquidsoap instances - https://i.snag.gy/BEft3i.jpg (save 920 MB of RAM usage).

**Comment by toots** [comment]
Could you share more of your script?

Thanks!

**Comment by desavil** [comment]
Yes.

1. http://pastebin.com/raw/2qQQp13R
2. http://pastebin.com/raw/AwJVy1h7

**Comment by desavil** [comment]
Unfortunately not. :(
It seemed to me that I not set an expiry for my paste on pastebin.

The problem no longer appeared. Details about this problem you have also on your e-mail.
As I see again, I report in this issue.

**Comment by toots** [comment]
Ok, thanks.
