### ISSUE TITLE
Feature request: packages for Ubuntu 24.04

### ISSUE THREAD

**Issue by rmens** [savonet/liquidsoap#3933]
I'd like to update to Ubuntu 24.04. Liquidsoap is the only package holding it back. Are there plans to build for Ubuntu Noble too? Merci!

**Comment by vitoyucepi** [comment]
Hi @rmens,
The build for `ubuntu:24.04` will be available in the `2.3` release. Ref: #3903.
At the moment you can use liquidsoap 2.2.4 from the ubuntu repository.

**Comment by rmens** [comment]
Thanks for the update @vitoyucepi!
