### ISSUE TITLE
Metadata not updated when switching (fallback) between 2 input.http sources

### ISSUE THREAD

**Issue by Calypso971** [savonet/liquidsoap#3943]
I have a liquidsoapscript that has 2 input.http sources with both metadata in them. Both are in a fallback scenario, so when one is unavailable, the other is used for output.

Simplified:

```
source1 = input.http("http://url1.com/bla", id="first")
source1 = blank.strip(max_blank=20., source1)
source2 = input.http("http://url2.com/blu",id="second")
source2 = blank.strip(max_blank=20., source2)

stream = fallback(transitions=[switch1, switch2], [source1,source2])

```
"stream" has the correct metadata from source1 when it is available. However, when for some reason that source isn't avaible, Liquidsoap tries to connect; the status of source1 becomes "starting" and "stream" will get "source2" for it's stream/audio. That works. However, the metadata that "stream" has is still the (old) metadata of "source1", even if during playing the metadata of "source2" is updated by the source.  I've added the "blank.strip" (because it's in my script), but it doesn't seem to make any difference if it's in there or not.

When I use this scenario with source1 as an input.harbor it works correctly - so it appears that the status of source1 ("starting") is preventing to switch to the correct metadata.

OS: Debian Bookworm
LS Version: 2.2.5 (Debian package from github)

**Comment by vitoyucepi** [comment]
Hi @Calypso971,

Could you check if the metadata is propagated correctly through the fallback when `source2` changes it and `source1` is unavailable. I think fallback doesn't care about `source2` metadata when switching from one source to another because there is no metadata frame at that moment.

Display metadata like this
```ruby
stream = fallback(transitions=[switch1, switch2], [source1,source2])
stream.on_metadata(print)
```

**Comment by Calypso971** [comment]
The printing of the metadata is already in my (more elaborate) code that I've been testing with - for the sake of simplicity I've removed those parts from the sample code. I've been looking at metadata of "source1", "source2" and "stream". 

As said, "even if during playing the metadata of "source2" is updated by the source" - maybe my wording wasn't clear enough, but this is the scenario that normally I'd expect that (in the end) the metadata of "stream" would have been updated with that of "source2":

Source1 is available - Source2 is available: Stream has output of Source1, Metadata of Source1, Change of metadata of Source1 is reflected in Stream

Source1 is unavailable ("starting") - Source2 is available: Stream has output of Source2, Metadata of Source1, Change of metadata of Source2 is not reflected in Stream

When I use a input.harbor as Source1, things are working as expected, even with non-changing metadata on Source2 it is reflected after the fallback taken place. 

Last night I was thinking it may be Debian Bookworm related - I've had issues with metadata on the Debian package with older versions (those were fixed and are working in 2.2.5) - while those were working on Ubuntu. I've not got a 2.2.5 Ubuntu machine available right now but will check this weekend what happens on those.

**Comment by vitoyucepi** [comment]
Well, I can't reproduce this behavior at all, so I set up an icecast server and two instances of liquidsoap, using the `savonet/liquidsoap:v2.2.5` container image.
The first one produces two streams and has an `interactive.harbor()` to control them.

<details>
<summary>First config</summary>

```ruby
p1 = playlist('/tmp/test/music1')
p2 = playlist('/tmp/test/music2')
interactive.harbor()
b1 = interactive.bool("p1", true)
b2 = interactive.bool("p2", true)
thread.when(predicate.changes(b1), {print("b1 changed")})
thread.when(predicate.changes(b2), {print("b2 changed")})

p1 = switch(track_sensitive=false, [(b1, p1)])
p2 = switch(track_sensitive=false, [(b2, p2)])

enc = %ffmpeg(%audio(codec="libmp3lame", b="192k"), format="mp3")
output.icecast(enc, p1, host='icecast', mount='p1', fallible=true)
output.icecast(enc, p2, host='icecast', mount='p2', fallible=true)
```

</details>

The second liquidsoap instance consumes both of the icecast mounts using `input.http` just like yours.

<details>
<summary>Second config</summary>

```ruby
source1 = input.http("http://icecast:8000/p1")
source2 = input.http("http://icecast:8000/p2")

stream = fallback([source1,source2])
stream.on_metadata(print)

enc = %ffmpeg(%audio(codec="libmp3lame", b="192k"), format="mp3")
output.icecast(enc, stream, host='icecast', mount='p3', fallible=true)
```

</details>

<details>
<summary>Log</summary>

```
liquidsoap1-1  | 2024/05/31 08:37:55 [p1:3] Source failed (no more tracks) stopping output...
icecast-1      | [2024-05-31  08:37:55] INFO source/get_next_buffer End of Stream /p1
icecast-1      | [2024-05-31  08:37:55] INFO source/source_shutdown Source from 172.18.0.2 at "/p1" exiting
icecast-1      | [2024-05-31  08:37:55] INFO source/source_clear_source 1 active listeners on /p1 released
icecast-1      | 172.18.0.2 - - [31/May/2024:08:37:55 +0000] "SOURCE /p1 HTTP/1.0" 200 19 "-" "Liquidsoap/2.2.5 (Unix; OCaml 4.14.1)" 14
icecast-1      | 172.18.0.4 - - [31/May/2024:08:37:55 +0000] "GET /p1 HTTP/1.1" 200 343414 "-" "Liquidsoap/2.2.5 (Unix; OCaml 4.14.1)" 13
liquidsoap1-1  | 2024/05/31 08:37:55 [p1:3] Closing connection...
liquidsoap2-1  | [http @ 0x7ca3fd027100] Stream ends prematurely at 343053, should be 18446744073709551615
liquidsoap2-1  | [mp3float @ 0x7ca3fc41c000] invalid new backstep -1
liquidsoap2-1  | 2024/05/31 08:37:55 [input.http:2] Feeding failed: Avutil.Error(Input/output error)
liquidsoap2-1  | 2024/05/31 08:37:55 [switch:3] Switch to input.http.2 with forgetful transition.
liquidsoap2-1  | 2024/05/31 08:37:55 [replay_metadata:3] Content type is {audio=pcm(stereo)}.
liquidsoap2-1  | [("icy-br", "192"), ("icy-pub", "1"), ("title", "music2_6"), ("icy-name", "p2")]
icecast-1      | [2024-05-31  08:37:55] INFO fserve/fserve_client_create checking for file /p1 (/usr/share/icecast/web/p1)
icecast-1      | [2024-05-31  08:37:55] WARN fserve/fserve_client_create req for file "/usr/share/icecast/web/p1" No such file or directory
icecast-1      | [2024-05-31  08:37:55] INFO admin/admin_handle_request Received admin command metadata on mount "/p3"
icecast-1      | [2024-05-31  08:37:55] INFO util/util_conv_string converting metadata from UTF-8 to UTF-8
icecast-1      | [2024-05-31  08:37:55] INFO admin/command_metadata Metadata on mountpoint /p3 changed to "music2_6"
liquidsoap1-1  | b1 changed
```

</details>


Did I miss something?

**Comment by Calypso971** [comment]
> Did I miss something?

Yes and no. Did some extensive testing with different versions. On Ubuntu all work as expected (tested Liquidsoap versions: 2.2.4, 2.2.5 and 2.3). On Debian 12 Liquidsoup 2.2.5 appears to act a bit differently and does not work as expected when using a transition (even if the transition is only a logentry that the transition is taking place). On Debian v2.2.4 and v2.3 it works as expected - and it's reproducable in my setup. All Debian/Ubuntu setups are minimal setups with latest updates and required packages installed by the same Ansible script. Very strange, but it seems "specific build related". I'll let it rest for now (and decide if I'll go with 2.3, 2.2.4 or go the Ubuntu route) or maybe try out if another package for 2.2.5 has the same. 

Thanks for looking into it.

**Comment by Calypso971** [comment]
Closing it - there is a workaround

**Comment by Calypso971** [comment]
Closing the issue - there is a workaround
