### ISSUE TITLE
Issues while trying to use FDK AAC's AAC-ELD (Enhanced Low Delay) AOT

### ISSUE THREAD

**Issue by AlReem** [savonet/liquidsoap#396]
I was trying to use the aot for AAC-ELD (Enhanced Low Delay) AOT while using FDK AAC and cannot successfully get it to work.  Please find below the config and the logs.
```
output.icecast(
  %fdkaac(bitrate=32, samplerate=32000, channels=2, afterburner=false,
        aot="mpeg4_aac_ld", transmux="adts", sbr_mode=true),
  mount="/low",
  genre="Talk",
  input)
```
While starting liquidsoap, I get the following error
```
2017/02/10 16:25:15 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2017/02/10 16:25:15 [mksafe:3] Switch to safe_blank.
2017/02/10 16:25:15 [clock.wallclock_main:2] Source /low failed while streaming: Transport library initialization error!
2017/02/10 16:25:15 [clock.wallclock_main:3] Raised by primitive operation at file "fdkaac.ml", line 243, characters 4-30
2017/02/10 16:25:15 [clock.wallclock_main:3] Called from file "encoder/fdkaac_encoder.ml", line 135, characters 12-48
2017/02/10 16:25:15 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 256, characters 10-46
2017/02/10 16:25:15 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 264, characters 35-47
2017/02/10 16:25:15 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 180, characters 6-27
2017/02/10 16:25:15 [clock.wallclock_main:3] Called from file "clock.ml", line 160, characters 17-25
2017/02/10 16:25:15 [/low:3] Closing connection...
```
From the above, it seems like it is an issue with the encoder.  Can you please let me know how I can debug this? Any possible solutions? I have used opam to install fdkaac as mentioned in your guides.

I was using the `mpeg4_he_aac` aot before but I was getting delays about 3 minutes between live and broadcast stream on my internet radio.

**--Update--**
Corrected config script above as

```
output.icecast(
  %fdkaac(bitrate=32, samplerate=32000, channels=2, afterburner=false,
        aot="mpeg4_aac_eld", transmux="adts", sbr_mode=true),
  mount="/low",
  genre="Talk",
  input)
```
However using both `mpeg4_aac_eld` and `mpeg4_aac_ld` seems to raise the same error.

**Comment by toots** [comment]
Are you using `mpeg4_aac_eld` or `mpeg4_aac_ld`? You mention ELD but quoted script says `mpeg4_aac_ld`..

**Comment by AlReem** [comment]
I have tried both and both gives the same error.

**Comment by toots** [comment]
Ok, reading from the sources, `adts` transport will raise an error when used in conjunction with `LD` or `ELD`. Setting it to `latm` or `loas` makes it work but the resulting stream does not seem to be readable for either `ffmpeg`, `VLC` or `mplayer`.

Configuration errors are the same with the example `aac-enc` provided by `fdk-aac` so I'm closing this issue since it is not liquidsoap-related. I'd be curious to know if you can make it work or find a player that supports this format.

**Comment by AlReem** [comment]
Thank you, I successfully got it to work but yes, it is not readable by any player.  I was going through the documentation and found this AOT to be "Low Delay" and wanted to try it in an effort to reduce the AAC+ stream processing delay for my station.
