### ISSUE TITLE
LS 2.2.5: Commit with Stefan’s PR (missing RegEx global "g") didn’t pass CI

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#3964]
**Describe the bug**
Stefan’s RegEx PR (missing global "g") didn’t go through the CI—no Bookworm and Jammy `.deb`, and others missing, too.

**To Reproduce**
Check https://github.com/savonet/liquidsoap/commit/8440adc06bbc19b3f886d4c5206f0aeb08869cbb

**Expected behavior**
`deb.` build for all architectures, so AzuraCast and some of us could pick it up.

**Comment by toots** [comment]
I'm working on this.
