### ISSUE TITLE
Query liquidsoap current status

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#397]
My goal is to make a webradio. I need to broadcast lives with songs played during the pauses. For that, I need to monitor and control liquidsoap from a web interface, with display of which song is playing, how much time before the end of the song (very important for the live manager), which input is currently playing and what will be the next one... I think I get the control part, with queues and interactive variables, but I have trouble on the monitoring part. How could I do that? There are the `on_*` functions, but it seems to only work on metadata of the current song and not the exact state of liquidsoap, like knowing how much time there is before the next song.

**Comment by toots** [comment]
Have you looked at: http://liquidsoap.fm/doc-latest/harbor_http.html ?

**Comment by toots** [comment]
Hehe. That's right :-) Feel free to let us know how you've done it, perhaps we can add this to the standard library!

**Comment by Yamakaky** [comment]
The basic idea is to use `on_end` to request the next song using HTTP. That way, there is only the current song and the next (if near the end of the current) in liquidsoap. The entire state is maintained externally in my backend, so it's easy to manipulate. An internal id is added to the metadata and sent with HTTP using `on_track` for tracking of the current song. At least that's the plan, I'm still doing it ^^
BTW, I use the [HTTP bridge of crossbar](http://crossbar.io/docs/HTTP-Bridge/), so that's why you see me asking about json ;)

**Comment by Yamakaky** [comment]
In fact, I still need a better solution. My current setup is this:

```
def on_e(time_left, m) =
    def run()
        meta = "{\"time_left\": " ^ json_of(time_left) ^ ", " ^
               " \"id\": " ^ m["id"] ^ "}"
        data = "{\"topic\": \"internal.on_end\", \"kwargs\": " ^ meta ^ "}"
        log(data)
        ignore(http.post(headers=[("Content-Type","application/json; charset=utf-8")],
                         data=data,
                         "http://localhost:60012/pub"))
        (-1.0)
    end
    add_timeout(fast=false, 0., run)
end

queue = on_end(on_e, queue)
queue = on_end(on_e, queue, delay=0.)
```

The time to end of the current track is synced at -5s and -0s. It works well, at least until I `switch([false, queue])` to pause the music. I can't find a way in the doc to query the time to end of the current track in a playlist. A solution would be to add `on_end` callbacks every 5s, but that's not very scalable.
