### ISSUE TITLE
Cache path in packages

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3970]
**Describe the bug**
By default, the Ubuntu package sets the home directory for the liquidsoap user to `/usr/share/liquidsoap`, but the `liquidsoap` user does not have write access to the home directory, so it generates `Error while loading cache: Sys_error("/usr/share/liquidsoap/.cache: Permission denied")` error.

**To Reproduce**
1. Install liquidsoap on ubuntu:22.04 using ubuntu package from ci pipeline artifacts.
1. `/tmp/main.liq`
   ```ruby
   output.dummy(blank())
   ```
1. `sudo -u liquidsoap liquidsoap /tmp/main.liq`

**Expected behavior**
1. Probably the cache directory should be set to `/var/cache/liquidsoap` with owner `liquidsoap:liquidsoap` and permissions `0755`.
1. Add build config option for custom cache path.
1. Add the stdlib cache to the package. Probably replace stdlib completely with cache.
1. Check if cache is writable/readable only once.
1. Fail silently like python.

**Version details**

- OS: *ubuntu:22.04*
- Version: c46726b64

**Install method**
Package from the github ci pipeline artifacts.

**Common issues**
#3949

**Comment by Moonbase59** [comment]
Good catch. I’m also voting for `/var`.

**Comment by vitoyucepi** [comment]
But that's only for liquidsoap user, all other users should use their own home dir.

I'm currently experimenting with the following set of changes:
1. ```diff
   --- a/src/lang/term/term_cache.ml
   +++ b/src/lang/term/term_cache.ml
   @@ -25,10 +25,7 @@
                  Sys.chdir cwd;
                  Some (Filename.concat dir ".cache")
              | _ ->
   -              Some
   -                (Filename.concat
   -                   (Filename.concat (Unix.getenv "HOME") ".cache")
   -                   "liquidsoap")
   +              Some "/var/cache/liquidsoap"
          with Not_found -> None)

    let cache_dir () =
   ```
1. ```sh
   pkgusers="liquidsoap"
   pkggroups="liquidsoap"

   # cut
   
   install -dm0755 -o liquidsoap -g liquidsoap "$pkgdir/var/cache/liquidsoap"
   ```
1. ```containerfile
   VOLUME [ "/var/cache/liquidsoap" ]
   ```

**Comment by toots** [comment]
Thanks for reporting. I initially used https://github.com/ocamlpro/directories but then switched to `$HOME` for simplicity and to prevent having another external dependency.

The code for cache dir, though, is:
```ocaml
  (** $XDG_CACHE_HOME or $HOME/.cache *)
  let cache_dir =
    match getenvdir "XDG_CACHE_HOME" with
    | None -> option_map (fun dir -> dir / ".cache") home_dir
    | Some _dir as dir -> dir
  ```
So, not much help either.

I think that the right logic shouold be to include the cache dir in the posix build target the same way we do for other paths. For those builds, we expect a system-wide install and will use `/var/cache/liquidsoap`

**Comment by vitoyucepi** [comment]
If the user is not `liquidsoap` and the build type is `posix`, then the cache path should be set to
1. `$LIQ_CACHE_DIR`, if it's set.
1. `$XDG_CACHE_DIR/liquidsoap` if `$XDG_CACHE_DIR` is set.
1. `$HOME/.cache/liquidsoap`.

I think debian and ubuntu packages should have a prebuilt stdlib cache, but I'm not sure about the alpine package. I'd prefer a separate package with cache, like it's done with python packages in alpine official repos.

**Comment by toots** [comment]
Yes, there are two caches indeed, on for stdlib that should be shared and one for user scripts. I'll work on cleaning that up. Also, feel free to expand for the PR I started if you want.
