### ISSUE TITLE
Ubuntu / Debian packages are v1.1.1

### ISSUE THREAD

**Issue by NTShop** [savonet/liquidsoap#398]
Ubuntu and Debian packages are v1.1.1, I believe those need to be updated to v1.2.x, the websocket connection for harbor doesn't work in v1.1.1 as discussed in Issue 276: #276

https://github.com/savonet/liquidsoap/issues/276

**Comment by NTShop** [comment]
Trying to get the webcaster demo running, finally realized that liquidsoap was throwing a 404, thus the reference of issue #276 and a need for an updated Ubuntu package since I can't build from source.

**Comment by hairmare** [comment]
For understandable reasons the savonet project has decided to focus on the opam distribution of liquidsoap.

I am maintaining the [RaBe Liquidsoap Distribution (RaBe LSD)](https://build.opensuse.org/project/show/home:radiorabe:liquidsoap) which runs fine on CentOS and similar distros.

LibreTime is tracking this issue at https://github.com/LibreTime/libretime/issues/192. It looks like we are all still looking for someone to take over the Debian packaging efforts.

Having an easy way to update to 1.3.1 would help with lots of issues we are seeing, thus the LibreTime community would be very thankful if someone were to take over maintainership of liquidsoap on Debian. We'd be happy to help out testing and promoting any official/semi-official packages.

**Comment by paddatrapper** [comment]
I have taken over Debian maintainer-ship and am busy packaging the new version at the moment. It's slow going because there are a bunch of dependencies that need updating first

**Comment by toots** [comment]
Hi @paddatrapper. Still interested by this? I'm available to mentor.

**Comment by paddatrapper** [comment]
@toots thanks for the offer. I'm waiting for Jonathan Carter to upload new dependecy versions that I have updated. Once they hit unstable, I will be able to continue on updating liquidsoap packaging. If I run into issues I will definitely give you a shout

**Comment by toots** [comment]
I haven't done work on debian package for a while, would you mind sharing the code you're working on?

Another thing I forgot to add: I would strongly suggest to get rid of the plugin packages and just build one liquidsoap package with all available features enabled. That's how `ffmpeg` is built for instance

The plugin system is a bit too hackish & was put together solely for the debian packages. It's been deprecated by `opam` optional dependencies & I'm hoping to get rid of it at some point in the future.

**Comment by paddatrapper** [comment]
Sorry I've taken so long to get back to you - I have been ill. My packaging is on [salsa](https://salsa.debian.org/paddatrapper-guest/liquidsoap). I have dropped all the plugins. I am busy converting the `debian/rules` file to use `dh`. It is currently not building, but I will only be able to work on it again probably at the weekend

**Comment by toots** [comment]
Thanks! I'll try to test it soon. Glad you're feeling better.

**Comment by toots** [comment]
Here are my notes:
- `dh_autoreconf` gave me grief. `./bootstrap` worked great, tho.
- `dh_auto_test` failed, git repo is missing the test dirs (`src/test` and `scripts/test` at least). I would disable it anyways.
- Had to modify `dh_autoinstall`.
- Had to modify `liquidsoap.install`. Not sure if everything is correct, haven't checked the standard practices there in a long while..
- I would suggest simply dropping liguidsoap. It hasn't been maintained in ages.

Other that, it looks great and all available options in `main` compile. That's a lot of ground work to push all these update, hats off!

Final diff:
```
diff --git a/debian/liguidsoap.install b/debian/liguidsoap.install
index 1fde12d..eb4cfe4 100644
--- a/debian/liguidsoap.install
+++ b/debian/liguidsoap.install
@@ -1,4 +1,4 @@
 debian/tmp/usr/bin/liguidsoap
-debian/tmp/usr/lib/python*/site-packages/liquidsoap/* var/lib/liguidsoap
+debian/tmp/usr/lib/*/python*/site-packages/liquidsoap/* var/lib/liguidsoap
 debian/icons/* usr/share/pixmaps
 debian/liguidsoap.desktop usr/share/applications
diff --git a/debian/liquidsoap.install b/debian/liquidsoap.install
index fada731..a1625dc 100644
--- a/debian/liquidsoap.install
+++ b/debian/liquidsoap.install
@@ -1,5 +1,6 @@
 debian/tmp/usr/bin/liquidsoap
-debian/tmp/usr/lib/liquidsoap
+debian/tmp/usr/lib/*/liquidsoap
 debian/tmp/etc/logrotate.d/liquidsoap
-examples/radio.liq               etc/liquidsoap
-NODYN: debian/tmp/@OCamlStdlibDir@/liquidsoap/dllliquidsoap.so @OCamlDllDir@
+debian/tmp/usr/share/doc/liquidsoap-* usr/share/doc/liquidsoap
+debian/tmp/usr/share/man/man1
+debian/tmp/etc/liquidsoap/radio.liq.example usr/share/doc/liquidsoap
diff --git a/debian/rules b/debian/rules
index 1033a80..50ee0f5 100755
--- a/debian/rules
+++ b/debian/rules
@@ -2,18 +2,26 @@

 include /usr/share/ocaml/ocamlvars.mk

-DESTDIR := $(CURDIR)/debian/tmp/$(OCAML_STDLIB_DIR)
+DESTDIR := $(CURDIR)/debian/tmp

 %:
        dh $@

+
+override_dh_autoreconf:
+       ./bootstrap
+
 override_dh_auto_build:
        [ -f debian/autoreconf.before ] || dh_autoreconf
        $(MAKE) all doc

+override_dh_auto_test:
+
 override_dh_auto_install:
        mkdir -p $(DESTDIR)
-       $(MAKE) install OCAMLFIND_DESTDIR=$(DESTDIR) OCAMLFIND_LDCONF=ignore
+       $(MAKE) install DESTDIR=$(DESTDIR) OCAMLFIND_DESTDIR=$(DESTDIR)/$(OCAML_STDLIB_DIR) \
+               prefix=$(DESTDIR)/usr sysconfdir=$(DESTDIR)/etc \
+               INSTALL_DAEMON=no OCAMLFIND_LDCONF=ignore
        dh_install --fail-missing

 override_dh_auto_clean:
```

**Comment by paddatrapper** [comment]
Thanks a lot! I'll spend some time updating it probably either tomorrow or early next week.

**Comment by paddatrapper** [comment]
Good news! I have finished updating the package. I will push it to mentors tomorrow and hopefully it should make it into unstable some time next week

**Comment by paddatrapper** [comment]
Version 1.3.3 is now in Debian unstable \o/

**Comment by toots** [comment]
![giphy](https://user-images.githubusercontent.com/871060/44100548-f164a886-9faa-11e8-919a-e861443e3e08.gif)

**Comment by toots** [comment]
Thank you so much, so many users that are gonna be so happy about that!

**Comment by toots** [comment]
Hi! Liquidsoap `1.3.4` is out if you're interested in updating the package! There are a couple of new bindings as well. I think the list is:
```
ocaml-dtools
ocaml-mm
ocaml-vorbis
ocaml-ffmpeg
ocaml-gstreamer
ocaml-lastfm
ocaml-duppy
ocaml-faad
ocaml-cry
```

**Comment by paddatrapper** [comment]
Thanks! I have already updated most of that list. I will do Liquidsoap once the current pending upload is sponsored and I can confirm it fixes the builds on mips*
