### ISSUE TITLE
Shutdown doesn't disconnect Icecast connections

### ISSUE THREAD

**Issue by NTShop** [savonet/liquidsoap#399]
When I start liquidsoap from the command line where its configured to connect to an Icecast server, using Ctrl-C to stop liquidsoap doesn't close the connections to Icecast (as seen in the Icecast Admin screen, source_client_connections ) - so repeated testing results in a large number of connections.

**Comment by StudentSA** [comment]
Please make reference to the icecast documentation 

[icecast server stats](http://icecast.org/docs/icecast-2.4.1/server-stats.html)

```
source_client_connections
Source client connections are the number of times (cumulative since start-up, not just currently connected) a source client has connected to Icecast.
This is an accumulating counter.
```

**Comment by smimram** [comment]
Thanks @StudentSA for clarification. @NTShop please reopen if there is really a problem.
