### ISSUE TITLE
Error when i want to Install liquidsoap

### ISSUE THREAD

**Issue by JipeLie** [savonet/liquidsoap#403]
Hey,

When i want to install liquidsoap and launch the command : ./configure
I have this error:
checking whether pkg-config knows about shine >= 0.1.0... configure: error: shine.pc not found.. Do you need to set PKG_CONFIG_PATH?

What i need to do ??

**Comment by toots** [comment]
Hi,

You need to install the `libshine` library. On debian and ubuntu, you should install the `libshine-dev` package.
