### ISSUE TITLE
Problem with displaying special unicode characters in liquidsoap log files

### ISSUE THREAD

**Issue by al-t** [savonet/liquidsoap#404]
I have a problem regarding the wrong output of some unicode characters in liquidsoap log files.

The name of the files with special unicode characters are not shown correctly in the log.
For example, the name of the file: "Space - Back To The Future (Touch Édit).mp3"  is shown in the LiquidSoap log line as:
2017/03/03 13:57:36 [reserve(dot)txt:3] Prepared "/var/www/html/data/0/chanel Mix/All/Space - Back To The Future (Touch \195\137dit).mp3" (RID 1).
(the character É is replaced by the corresponding UTF-8 code "\195\137")
I am using the log output for displaying some information in the web-interface of the radio, so I need the names appear correctly in the log. 
Is it possible to fix the correct output to the log of such characters, by means of some liquidsoap settings?

Here is my liquidsoap init script:

    #!/usr/bin/liquidsoap
    # Log dir
    set("log.file.path","/var/www/radio-logs/reserve.log")

    # Music
    playlist_file = "/var/www/playlists/reserve.txt"
    enable_replaygain_metadata ()
    myplaylist = playlist(mode="normal",playlist_file,reload_mode="rounds",reload=1)
    myplaylist = amplify(1.,override="replay_gain",myplaylist)
    myplaylist = on_track(apply_metadata,myplaylist)
    myplaylist = mksafe(myplaylist)
    myplaylist = crossfade(start_next=6., fade_out=4., fade_in=6., myplaylist)

    output.icecast(%mp3, host = "localhost", port = 8000, password = "...", mount = "reserve.mp3", mksafe(myplaylist))

**Comment by toots** [comment]
Hi

I don't think that this is possible. We use OCaml's native string escaping to print out this string and this is the format that it returns.

I wouldn't recommend using the logs to display informations, though. Have you considered using `on_metadata` for instance?
