### ISSUE TITLE
[protocols.external:3] Didn't find "curl".

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#409]
I have installed curl on my server (Linux Debian 8) but I see this information in log file always:
> [protocols.external:3] Didn't find "curl".

> curl -V
> curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
> Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

Btw. Can I remove this informations from log file?:
> 2017/03/18 21:16:11 [main:2] 
> 2017/03/18 21:16:11 [main:2] We hope you enjoy this snapshot build of Liquidsoap!
> 2017/03/18 21:16:11 [main:2] 
> 2017/03/18 21:16:11 [main:2] at <https://github.com/savonet/liquidsoap/issues>.
> 2017/03/18 21:16:11 [main:2] Please send any bug report or feature request
> 2017/03/18 21:16:11 [main:2] 
> 2017/03/18 21:16:11 [main:2] or to join the #savonet IRC channel on Freenode.
> 2017/03/18 21:16:11 [main:2] drop us a mail at <savonet-devl@lists.sf.net>
> 2017/03/18 21:16:11 [main:2] the development of Liquidsoap, feel free to
> 2017/03/18 21:16:11 [main:2] If you are interested in collaborating to
> 2017/03/18 21:16:11 [main:2] 
> 2017/03/18 21:16:11 [main:2] issues as soon as possible.
> 2017/03/18 21:16:11 [main:2] about our development code and committed to fix
> 2017/03/18 21:16:11 [main:2] We are, however, very interested in any feedback
> 2017/03/18 21:16:11 [main:2] 
> 2017/03/18 21:16:11 [main:2] unless you know what you are doing!
> 2017/03/18 21:16:11 [main:2] As such, it should not be used in production
> 2017/03/18 21:16:11 [main:2] compiled from a snapshot of the development code.
> 2017/03/18 21:16:11 [main:2] DISCLAIMER: This version of Liquidsoap has been
> 2017/03/18 21:16:11 [main:2] 
> 2017/03/18 21:16:11 [main:3] Using: graphics=[distributed with Ocaml] bytes=[OCaml strictly before 4.02] pcre=7.2.3 dtools=0.3.3 duppy=0.6.0 duppy.syntax=0.6.0 cry=0.5.0 mm=0.3.0 xmlplaylist=0.1.4 lastfm=0.3.1 ogg=0.5.1 vorbis=0.6.2 mad=0.4.5 flac=0.1.2 flac.ogg=0.1.2 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 ao=0.2.1 samplerate=0.1.4 taglib=0.3.3 ssl=0.5.3 magic=0.7.3 camomile=0.8.5
> 2017/03/18 21:16:11 [main:3] Liquidsoap 1.2.1+scm (git://github.com/savonet/liquidsoap.git@ad9faca995a04318254757acd53ecee3b75dc2aa:20170318:211223)

**Comment by toots** [comment]
Where is `curl` installed?

**Comment by desavil** [comment]
`/usr/bin/curl`

**Comment by toots** [comment]
How do you start liquidsoap? Liquidsoap will look at your `$PATH` env variable to determine the list of directory to search for `curl`. Thus, `/usr/bin` must be in the `$PATH` env variable.

**Comment by desavil** [comment]
`echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`

Start liquidsoap: `liquidsoap config.liq`

**Comment by toots** [comment]
That's odd.What do you get with: `liquiddoap 'print(getenv("PATH"))'` ?

**Comment by desavil** [comment]
> /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
> No output defined, nothing to do.

**Comment by desavil** [comment]
I see that you corrected something (fbe1e0b4dc66d4985b34323e20d3985fd7432c09), but it still does not solve the problem.

**Comment by toots** [comment]
Well, then what does `liquidsoap 'print(which("curl"))'` say?

**Comment by desavil** [comment]
> liquidsoap@ap:~/autopilot/10403$ liquidsoap 'print(which("curl"))'
> /usr/bin/curl
> No output defined, nothing to do.
> liquidsoap@ap:~/autopilot/10403$ /usr/bin/curl
> curl: try 'curl --help' or 'curl --manual' for more information

**Comment by toots** [comment]
Well, I don't get it. `which("curl")` is the exact code that is executed to find `curl` in the external protocol. Are you sure that you start your script the same way that you've executed this command?

**Comment by desavil** [comment]
I'm sorry my mistake.

Normally, I'm running liquidsoap via PHP. I made a few tests, because curl is available through PHP:
<?php
exec('echo $PATH >> /home/test.txt');
exec('which curl >> /home/test.txt');
exec('curl -V >> /home/test.txt');

exec('liquidsoap \'print(getenv("PATH"))\' >> /home/test.txt');
exec('liquidsoap \'print(which("curl"))\' >> /home/test.txt');

Output (test.txt):
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> /usr/bin/curl
> curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
> Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
> 
> No output defined, nothing to do.
> 
> No output defined, nothing to do.

**Comment by toots** [comment]
Hey,

I have completely reworked the download protocol. With the latest `master` you should be able to set the path to curl using this setting:
```
set("protocol.external.curl","curl")
```
