### ISSUE TITLE
Crossfade between playlist when track_sensitive=false

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#410]
Crossfade not working correctly between playlists switching when `track_sensitive=false`.
As it sets to `true` all works well.

The problem only with the `fade_out` - ignored.
`start_next` and `fade_in` works properly.

My configuration:
> radio = switch(track_sensitive=false,[
>                                       ({23h05-23h30},mksafe(audio_to_stereo(playlist(mode="randomize", "/home/time1.pls")))),
>                                       ({23h30-23h50},mksafe(audio_to_stereo(playlist(mode="randomize", "/home/time2.pls")))),
>                                       ({true},mksafe(audio_to_stereo(playlist(mode="randomize","/home/default.pls"))))
>                                     ])
> radio = crossfade(start_next=3.,fade_out=6.,fade_in=6.,radio)

**Comment by toots** [comment]
Try passing `conservative=true` to `crossfade()`

**Comment by toots** [comment]
I'm changing the default to `true` in the next release.
