### ISSUE TITLE
Docs: dead link to Kube on sidebar

### ISSUE THREAD

**Issue by IcedQuinn** [savonet/liquidsoap#4103]
### Description

The sidebar under "user scripts" contains dead links. Those are not particularly helpful.

### Steps to reproduce

- Go to https://www.liquidsoap.info/doc-dev/
- Click `Kube`

### Expected behavior

Something other than a 404 page.

### Liquidsoap version

```text
N/A
```

### Liquidsoap build config

```text
N/A
```

### Installation method

From source/self-built

**Comment by toots** [comment]
Thanks for reporting!
