### ISSUE TITLE
How can I output to sound card?

### ISSUE THREAD

**Issue by serogrip** [savonet/liquidsoap#412]
Hi all.

I want to make sound out to sound card on pc.
but `out.alsa`, `out.pulseaudio`, not working.

Test Code
```
output.alsa(radio)
output.pulseaudio(radio)
output.alsa(fallible=true,device="pcm.pulse",radio)
output.alsa(bufferize=false,device="hw:0,1", mksafe(radio))
```
all code not working error show in liquidsoap log
```
Thread "alsa_out(pcm(dot)pulse)" aborts with exception Alsa error: Connection refused!
```

Thanks for advice

**Comment by hairmare** [comment]
Isn't #414 a dupe of this?

**Comment by smimram** [comment]
I think so. I am closing it for now. Please reopen (or better go to the mailing-list) if it is not the case.
