### ISSUE TITLE
liquidsoap alsa script error when start as service

### ISSUE THREAD

**Issue by serogrip** [savonet/liquidsoap#414]
I found alsa error when liquidsoap script run via service.
os: ubuntu

sample.liq
```
#!/usr/bin/liquidsoap
radio = playlist("/home/user/music/");
output.alsa(id="alsa", mksafe(radio))
```
[case A  : run as user level => working fine]
user:> liquidsoap sample.liq

[case B : run as system service => alsa error]
root:> service liquidsoap start   <== sample.liq file located /etc/liquidsoap/sample.liq

start sample.liq with liquidsoap service.

log file
```
2017/03/26 23:36:04 [alsa:3] Using ALSA 1.1.0.
2017/03/26 23:36:04 [threads:1] Thread **"alsa" aborts with exception Alsa error: No such file or directory!**
2017/03/26 23:36:04 [stderr:3] Home directory not accessible: Permission denied
2017/03/26 23:36:04 [main:3] Shutdown started!
```

thanks any advice !!

**Comment by hairmare** [comment]
On modern systems the users accessing ALSA usually needs to be in the `audio` group. The `liquidsoap` user is probably not in the group.

You can test this with `id liquidsoap` and looking if `audio` is in the output.

To fix it you can assign the `audio` group to the `liquidsoap` user with `usermod -a -G audio liquidsoap`.

**Comment by serogrip** [comment]
Wow!!
it's working perfectly.

Thanks hairmare.

Very usefull

**Comment by smimram** [comment]
The mailing-list would be more suitable for such problems.
