### ISSUE TITLE
Inappropriate dependencies for debian bookworm on 2.3.0-rc1

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#4147]
### Description

Dependencies don't seem to match packages that are available on debian bookworm…

Would install using dependencies available in Debian 12 / bookworm… instead:

```
root@test-liqv2:~# apt install ./liquidsoap_2.3.0-debian-bookworm-1_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 liquidsoap : Depends: libavcodec60 (>= 10:6.0.1) but it is not installable
              Depends: libavdevice60 (>= 10:6.0.1) but it is not installable
              Depends: libavfilter9 (>= 10:6.0.1) but it is not installable
              Depends: libavformat60 (>= 10:6.0.1) but it is not installable
              Depends: libavutil58 (>= 10:6.0.1) but it is not installable
              Depends: libfdk-aac2 (>= 1:2.0.2) but 2.0.2-1 is installed
              Depends: libmp3lame0 (>= 1:3.100) but 3.100-6 is installed
              Depends: libswresample4 (>= 10:6.0.1) but 7:5.1.4-0+deb12u1 is installed
              Depends: libswscale7 (>= 10:6.0.1) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

### Steps to reproduce

On an up to date debian 12:
```
wget https://github.com/savonet/liquidsoap/releases/download/v2.3.0-rc1/liquidsoap_2.3.0-debian-bookworm-1_amd64.deb
apt install ./liquidsoap_2.3.0-debian-bookworm-1_amd64.deb
```

### Expected behavior

Would depend on libavcodec59 and so on…

### Liquidsoap version

```text
Liquidsoap v2.3.0-rc1
```

### Liquidsoap build config

```text
Not applicable
```

### Installation method

From official packages in the release artifacts

**Comment by gAlleb** [comment]
Hi, @gilou. 

Thing is that LS 2.3.0 requires `ffmpeg 6` or higher. You should install by yourself:

`sudo apt remove ffmpeg`

###Install ffmpeg6:

`sudo nano /etc/apt/sources.list.d/deb-multimedia.sources`

Paste the text below into the file and save: 

```
Types: deb
URIs: https://www.deb-multimedia.org
Suites: stable
Components: main non-free
Signed-By: /etc/apt/trusted.gpg.d/deb-multimedia-keyring.gpg
```
`contol + x` and `Y`.

`sudo wget https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb`

`sudo apt install ./deb-multimedia-keyring_2016.8.1_all.deb`

`sudo nano /etc/apt/preferences.d/99deb-multimedia`

Paste the text below into the file and save: 

```
Package: *
Pin: origin www.deb-multimedia.org
Pin-Priority: 1
```
`contol + x` and `Y`.

`sudo apt update`

`sudo apt install -t 'o=Unofficial Multimedia Packages' ffmpeg`

**Comment by gilou** [comment]
Ah, I removed debian multimedia when liq only depended again on main… OK, will do that.
