### ISSUE TITLE
Heterogeneous json generation

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#416]
I have to encode the following json:
```
{
  "procedure": "set_current",
  "kwargs": {..}
}
```
with `kwargs` an object. The trouble is that `json_of` don't seem to allow it. I tried to first encode `kwargs`, but then it would be a string and not an object. I can't change the API. Is there a solution?

**Comment by toots** [comment]
Interestingly, the solution has been implemented very recently. You can now do multiple parsing calls. It's still annoying but at least it's possible. See the bottom of: http://liquidsoap.fm/doc-latest/json.html

We'll be release this shortly..

**Comment by Yamakaky** [comment]
I'm trying to encode, not decode. But thanks for the tip!

**Comment by Yamakaky** [comment]
I manage to do what I want by concatenating strings. Not ideal though ^^

**Comment by toots** [comment]
I'm sure it's not. I'm gonna keep this one open. I know that this is a real pain in the ass to not be able to generate mixed-type json but, alas, this is a fundamental restriction of the language type system and I don't think that there is an easy fix/hack here..

**Comment by Yamakaky** [comment]
Yeah, I know...

**Comment by smimram** [comment]
I have just added parsing of JSON data as records in c71b6231e9ff411ab9cad75efdfe4a28c7b2d050 which should provide a decent solution to this heterogeneous data parsing problem. In your case:
```
of_json(default={procedure="", kwargs={...}}, data)
```

**Comment by toots** [comment]
This is dope, thanks @smimram. We should make sure that this is documented.
