### ISSUE TITLE
Append a request to a queue from the script

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#417]
I would like to be able to send a file name + id via harbor, create a request, add the id as metadata (I need it for my backend) and push it to the queue. The trouble is that it doesn't seem possible since appending to a queue can only be done by a server command.
A possible hack I thought of is to use `server.execute` to add the filename to the queue, get the rid and modify it's metadata, but there again it doesn't seem possible.
Is there a way to add some metadata to a song pushed to a queue?

**Comment by toots** [comment]
Yes. It's done through the `annotate:..` protocol. I've added a list of supported protocols here: http://liquidsoap.fm/doc-latest/protocols.html and I'm planning on writing a more detailed documentation on how to make the best of them for the next release.

**Comment by Yamakaky** [comment]
Cool, thanks!
TIL `youtube-dl` is a valid protocol XD
