### ISSUE TITLE
metadata not sent? (vorbis stream)

### ISSUE THREAD

**Issue by CyberDomovoy** [savonet/liquidsoap#418]
I use map_metadata to set a bunch of metadata on my stream, but they don't get to the client.
You can test the stream at http://stream.ondecourte.fr:8000/test.ogg

code:
```
def print_meta(m) =
	def log_meta(label, m) =
		rl = "local_meta.#{label}"
		
		def f(data) =
			"Name: #{fst(data)}, Value: #{snd(data)}"
		end
		
		log(label=rl, "---- METADATA: #{label} ----")
		
		list.iter(log(label=rl), list.map(f, m))
	end
	
	if config.debug then
		log_meta("to_icecast", m)
	end
end

output.icecast(%vorbis,
    host=icecast_host,
    password=icecast_pass,
	id=radio_id,
	mount=radio_mount,
    public=config.public,
    name=radio_name,
    description=radio_desc,
    genre=radio_genre,
    url=radio_url,
    on_metadata(print_meta, radio))
```

output:
> 2017/03/29 02:02:06 [local_meta.to_icecast:3] ---- METADATA: to_icecast ----
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: opus, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: part, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: composer, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: album, Value: Unknown Album
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: date, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: disctotal, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: conductor, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: artist, Value: Unknown Artist
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: isrc, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: title, Value: [Les_Detectives_Sauvages]_My_Turtle_[Les_Sauvages_Detections]_[Licence_Art_Libre]_[www.dogmazic.net]
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: organization, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: sourcemedia, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: location, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: tracknumber, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: license, Value: Unknown License
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: copyright, Value: Unknown Copyright
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: version, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: author, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: partnumber, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: arranger, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: metadata_block_picture, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: lyricist, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: encoder, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: discnumber, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: description, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: productnumber, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: contact, Value: http://ondecourte.fr
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: performer, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: ensemble, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: tracktotal, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: grouping, Value: Failsafe
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: comment, Value: none
2017/03/29 02:02:06 [local_meta.to_icecast:3] Name: genre, Value: Misc

The client is quodlibet, i patched it to print some infos about gstreamer supported tags and tags received:

> D: 1.772: GStreamerPlayer._fill_stream: GROUPING EXISTS
D: 1.772: GStreamerPlayer._fill_stream: (tag) artist=Unknown Artist
D: 1.772: GStreamerPlayer._fill_stream: (tag) title=[Les_Detectives_Sauvages]_My_Turtle_[Les_Sauvages_Detections]_[Licence_Art_Libre]_[www.dogmazic.net]
D: 1.772: GStreamerPlayer._fill_stream: (tag) album=Unknown Album
D: 1.772: GStreamerPlayer._fill_stream: (tag) genre=Misc
D: 1.772: GStreamerPlayer._fill_stream: (tag) comment=none
D: 1.772: GStreamerPlayer._fill_stream: (tag) application-name=Liquidsoap/1.1.1 (Unix; OCaml 4.01.0)
D: 1.772: GStreamerPlayer._fill_stream: (tag) encoder=Xiph.Org libVorbis I 20140122 (Turpakäräjiin)
D: 1.772: GStreamerPlayer._fill_stream: (tag) encoder-version=0
D: 1.773: GStreamerPlayer._fill_stream: (tag) audio-codec=Vorbis
D: 1.773: GStreamerPlayer._fill_stream: (tag) nominal-bitrate=112000
D: 1.773: GStreamerPlayer._fill_stream: (tag) bitrate=112000

As you can see, a lot is missing, and particularly "grouping", which i'd like to use as the radio program name.
I tried with and without taglib.

**Comment by toots** [comment]
Hi,

Exported metadata are filtered, essentially to avoid potential leaks of internal values such as `original_uri` which may contain a password etc.

You can change the list of exported metadata through this setting:
```
set("encoder.encoder.export",["artist","title","album","genre","date","tracknumber","comment","track","year","dj","next"])
```

**Comment by CyberDomovoy** [comment]
Well, maybe i'm missing something, but it doesn't seem to work.
Added code:
```
allowed = list.append(
	list.map(fst, metadata.mandatory),
	metadata.extra
)
list.iter(log(label="ALLOWED TAG"), allowed)
# Allowed tags
set("encoder.encoder.export", allowed)
```

Output:
> 2017/03/29 15:58:19 [ALLOWED TAG:3] album
2017/03/29 15:58:19 [ALLOWED TAG:3] artist
2017/03/29 15:58:19 [ALLOWED TAG:3] contact
2017/03/29 15:58:19 [ALLOWED TAG:3] copyright
2017/03/29 15:58:19 [ALLOWED TAG:3] genre
2017/03/29 15:58:19 [ALLOWED TAG:3] license
2017/03/29 15:58:19 [ALLOWED TAG:3] title
2017/03/29 15:58:19 [ALLOWED TAG:3] show-name
2017/03/29 15:58:19 [ALLOWED TAG:3] author
2017/03/29 15:58:19 [ALLOWED TAG:3] date
2017/03/29 15:58:19 [ALLOWED TAG:3] arranger
2017/03/29 15:58:19 [ALLOWED TAG:3] conductor
2017/03/29 15:58:19 [ALLOWED TAG:3] comment
2017/03/29 15:58:19 [ALLOWED TAG:3] composer
2017/03/29 15:58:19 [ALLOWED TAG:3] description
2017/03/29 15:58:19 [ALLOWED TAG:3] discnumber
2017/03/29 15:58:19 [ALLOWED TAG:3] disctotal
2017/03/29 15:58:19 [ALLOWED TAG:3] ensemble
2017/03/29 15:58:19 [ALLOWED TAG:3] encoder
2017/03/29 15:58:19 [ALLOWED TAG:3] isrc
2017/03/29 15:58:19 [ALLOWED TAG:3] location
2017/03/29 15:58:19 [ALLOWED TAG:3] lyricist
2017/03/29 15:58:19 [ALLOWED TAG:3] metadata_block_picture
2017/03/29 15:58:19 [ALLOWED TAG:3] opus
2017/03/29 15:58:19 [ALLOWED TAG:3] organization
2017/03/29 15:58:19 [ALLOWED TAG:3] part
2017/03/29 15:58:19 [ALLOWED TAG:3] partnumber
2017/03/29 15:58:19 [ALLOWED TAG:3] performer
2017/03/29 15:58:19 [ALLOWED TAG:3] productnumber
2017/03/29 15:58:19 [ALLOWED TAG:3] sourcemedia
2017/03/29 15:58:19 [ALLOWED TAG:3] tracknumber
2017/03/29 15:58:19 [ALLOWED TAG:3] tracktotal
2017/03/29 15:58:19 [ALLOWED TAG:3] version
2017/03/29 16:01:36 [local_meta.to_icecast:3] ---- METADATA: to_icecast ----
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: album, Value: Matin du Nevada
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: date, Value: 2001
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: show-name, Value: Archive Dogmazik
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: artist, Value: A_dontigny D_turgeon K_wong
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: title, Value: Difficultés de câblage
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: tracknumber, Value: 1/4
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: license, Value: Unknown License
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: copyright, Value: Unknown Copyright
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: contact, Value: http://ondecourte.fr
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: comment, Value: NT 052 / www.notype.com
2017/03/29 16:01:36 [local_meta.to_icecast:3] Name: genre, Value: Electronic

Quodlibet output:
> D: 30.446: GStreamerPlayer._fill_stream: show-name EXISTS
D: 30.447: GStreamerPlayer._fill_stream: (tag) artist=A_dontigny D_turgeon K_wong
D: 30.447: GStreamerPlayer._fill_stream: (tag) title=Difficultés de câblage
D: 30.447: GStreamerPlayer._fill_stream: (tag) album=Matin du Nevada
D: 30.447: GStreamerPlayer._fill_stream: (tag) genre=Electronic
D: 30.448: GStreamerPlayer._fill_stream: (tag) datetime=<GstDateTime at 0x7fe8c8004590>
D: 30.448: GStreamerPlayer._fill_stream: (tag) comment=NT 052 / www.notype.com
D: 30.448: GStreamerPlayer._fill_stream: (tag) application-name=Liquidsoap/1.1.1 (Unix; OCaml 4.01.0)
D: 30.448: GStreamerPlayer._fill_stream: (tag) encoder=Xiph.Org libVorbis I 20140122 (Turpakäräjiin)
D: 30.449: GStreamerPlayer._fill_stream: (tag) encoder-version=0
D: 30.449: GStreamerPlayer._fill_stream: (tag) audio-codec=Vorbis
D: 30.449: GStreamerPlayer._fill_stream: (tag) nominal-bitrate=112000
D: 30.449: GStreamerPlayer._fill_stream: (tag) bitrate=112000

**Comment by toots** [comment]
I'll re-visit that. Have you checked that those metadata aren't filtered some place else? You should able to dump the resulting stream and investigate using `oggz` and the like..

**Comment by CyberDomovoy** [comment]
I added 'dumpfile="out.ogg"' to output.icecast.

LS output:
> 2017/03/29 17:07:05 [local_meta.to_icecast:3] ---- METADATA: to_icecast ----
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: album, Value: Hypercubal EP
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: date, Value: 1999
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: show-name, Value: Archive Dogmazik
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: artist, Value: Darck
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: title, Value: Relax v.1.3
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: tracknumber, Value: 3/12
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: license, Value: Unknown License
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: copyright, Value: Unknown Copyright
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: contact, Value: http://ondecourte.fr
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: comment, Value: NT 008 / www.notype.com
2017/03/29 17:07:05 [local_meta.to_icecast:3] Name: genre, Value: Electronic

LC_ALL=C ogginfo out.ogg:
> New logical stream (#2, serial: 086df219): type vorbis
Vorbis headers parsed for stream 2, information follows...
Version: 0
Vendor: Xiph.Org libVorbis I 20140122 (Turpakäräjiin)
Channels: 2
Rate: 44100

Nominal bitrate: 112.000000 kb/s
Upper bitrate not set
Lower bitrate not set
User comments section follows...
	ARTIST=Darck
	TITLE=Relax v.1.3
	ALBUM=Hypercubal EP
	GENRE=Electronic
	DATE=1999
	COMMENT=NT 008 / www.notype.com
	ENCODER=Liquidsoap/1.1.1 (Unix; OCaml 4.01.0)

**Comment by CyberDomovoy** [comment]
I tried to compile master but it seems debian stable just can't do it (not without getting a bunch of other stuff not in packages).
First i had to mess with autoconf, and when i managed to get a working ./configure, it told me it couldn't find ocaml bytes, which seems to be in ocaml>=4.02 (debian stable has 4.01).

So i won't be able to check if this is still an issue in current code, sorry.

**Comment by CyberDomovoy** [comment]
Found the culprits (i think):
https://github.com/savonet/liquidsoap/blob/liquidsoap-1.1.1/src/ogg_formats/vorbis_encoder.ml#L129
https://github.com/savonet/ocaml-vorbis/blob/master/src/vorbis.ml#L132

So i guess in order to get my tags working on debian stable, i'll have to compile my own version of those... right?

Strange that nobody fell on this before...

**Comment by CyberDomovoy** [comment]
Ok, two patches that fixes it for me:

For ocaml-vorbis, tag "ocaml-vorbis-0.6.1":
[0001-tags-allows-any-tag.txt](https://github.com/savonet/liquidsoap/files/880893/0001-tags-allows-any-tag.txt)

For liquidsoap, tag "liquidsoap-1.1.1":
[0001-use-list-version-of-Vorbis.tags.txt](https://github.com/savonet/liquidsoap/files/880889/0001-use-list-version-of-Vorbis.tags.txt)

Both compile and works on my system, had to mess a bit with autoconf for ocaml-vorbis:
`libtoolize -fvi; rm m4; ln -s ../liquidsoap/m4 ./; autoreconf -fvi -I m4`

I don't know if it's ok for you, if it is, you're welcome to use those patches in any way you see fit.
And thanks for liquidsoap, i enjoy it very much!

**Comment by gilou** [comment]
Hi,
Maybe you could try to patch it against 1.3.0 though this seems to not have changed much, and issue a pull request directly for this issue?
Also, in your patch, you don't define a default list of allowed tags, is it because it relies on another filter somewhere else? (I'm not too familiar with this part).

**Comment by CyberDomovoy** [comment]
Hi, i'd gladly patch against master, but unfortunately i really don't have the time at the moment. I'll admit my (selfish) goal was just to get it working on my setup.
But rest assured that as soon as i find the time, i'll do it.

> Also, in your patch, you don't define a default list of allowed tags

For ocaml-vorbis, i believe it is not its task to do any filtering, so it just sets all the found tags.

For liquidsoap, my patch only makes the vorbis encoder use the patched version of ocaml-vorbis, using all the tags available to it (instead of a static list specifically for the vorbis encoder). The filtering is done before (using "encoder.encoder.export"), and is not dependent of a particular encoder (if i recall well, and i believe i do).

Before that, the process was:
- Filter using "encoder.encoder.export"
- Send to vorbis encoder
- vorbis encoder use ocaml-vorbis, filtering again using a static list of tags (title, artist, genre, date, album, tracknumber, comment). So allowing any other in "encoder.encoder.export" is like a no-op.

With the patch:
- Filter using "encoder.encoder.export"
- Send to vorbis encoder
- vorbis encoder use ocaml-vorbis, without any additional filtering

I may be able to come back at coding in a few weeks, but until then, i won't be able to patch against master. Sorry for the inconvenience.

**Comment by toots** [comment]
Thanks for these patches, I've committed them and they'll go out with the next bugfix release shortly.

**Comment by CyberDomovoy** [comment]
You're very welcome.
And thanks for committing those even though they were not against master.
Now let's hope ocaml-vorbis 0.7.0 makes it to debian stable soon, so that i can get back to an "unpatched server" :)

**Comment by 808y** [comment]
hello
i am using Liquidsoap 2.0.3-1 opam on rpi 3B

is it possible with this version to bypass the filtering of metadatas ?

i'd  need to show the 'composer' metadata, and a bunch of others...

**Comment by toots** [comment]
> hello i am using Liquidsoap 2.0.3-1 opam on rpi 3B
> 
> is it possible with this version to bypass the filtering of metadatas ?
> 
> i'd need to show the 'composer' metadata, and a bunch of others...

You should look at the `settings.encoder.metadata.export` setting.
