### ISSUE TITLE
"Unable to decode" on playback of mono-coded mp3-files

### ISSUE THREAD

**Issue by ALuserX** [savonet/liquidsoap#42]
Hello fellas,

after you helped us in February everything seemed to work fine except some files simply were not playing. As I mentioned it last time we have a bunch of oldschool 8-bit/chiptune crap that makes out like 2-3% of the content on our radio station. Those files are mostly being offered for free download by the artists and unfortunately some of them are mono-coded. I think that's the reason why Liquidsoup is unable to decode these files.

Is it a bug or a feature?
Is there a way to play these files except of manually transcoding them to stereo?

Example file:
http://tools.42fm.ru/Thunder_Carnival_%282005%29.zip

Log-Output

<pre>
2013/03/15 19:13:25 [decoder.mad:3] File "/home/radio/content/music/8-bit/Circles/Thunder_Carnival_(2005).mp3" has an incompatible number of channels.
2013/03/15 19:13:25 [decoder:3] Unable to decode "/home/radio/content/music/8-bit/Circles/Thunder_Carnival_(2005).mp3" as {audio=2;video=0;midi=0}!
</pre>

Our version is:

<pre>
 Liquidsoap 1.0.1+scm (  git://github.com/savonet/liquidsoap.gi@7a959fb6befcbb79b4e848e540a5ecccfd021f9a:20130225:162212  )
</pre>

**Comment by Blazedallup** [comment]
so i am new to Azuracast and also github so i apologize before i start.
so i have azuracast setup and running my problem is i have a lot of podcasts in mono that azuracast wont play at first i thought it was the size of the file 53mb so i changed that to 90mb  but i took the same file and converted it to stereo and it now plays fine. how do i get liquid soap or azura to play my mono files in stereo? and i dont understand this s = audio_to_stereo(playlist("...")) where do i change this or add this? i would hate to have to manually transcode 60gb of files into stereo. Thanks for you're time.
