### ISSUE TITLE
Queue non-blocking queue #1 crashed with exception Invalid argument in select()

### ISSUE THREAD

**Issue by mcfiredrill** [savonet/liquidsoap#420]
First liquidsoap crash I've seen. :)
Is there anyway I can get a stacktrace or more info? current log level is 3.

Using liquidsoap from git at `fb680c806e36159bcf2e8e2fcaf60b99813e18a6`.
I will recompile with HEAD soon.

````
2017/03/31 04:10:32 [lang:3] annotate_line: annotate:liq_fade_in=0,liq_fade_out=0,liq_cue_in=0:https://dongles.streampusher-relay.club/Pride365/EdSheeran-ShapeOfYouGalantisRemix.mp3?1489196459
2017/03/31 04:10:33 [threads:2] Queue non-blocking queue #1 crashed with exception Invalid argument in select()
2017/03/31 04:10:33 [threads:2] Re-raised at file "duppy.ml", line 199, characters 17-18
Called from file "duppy.ml", line 201, characters 4-8
Called from file "duppy.ml", line 295, characters 12-25
Called from file "tools/tutils.ml", line 208, characters 13-61

2017/03/31 04:10:33 [threads:1] PANIC: Liquidsoap has crashed, exiting..
2017/03/31 04:10:33 [threads:1] Please report at: savonet-users@lists.sf.net
```

**Comment by toots** [comment]
Hi. Thanks for reporting. I've been working on some important (and exciting!) changes and the risk with those is always stability. That being said, I did notice and fix duppy queue crashes very recently so it'd be nice it you could indeed confirm that you still see the bug on a recent `HEAD`. Thanks!

**Comment by mcfiredrill** [comment]
Thanks @toots ! I'll have a go with the latest HEAD and reopen if I see the crash again.
