### ISSUE TITLE
Conditional source creation

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#421]
I'm trying to do
```
mic = if getenv("JACK") != "" then
    input.jack()
else
    in()
end
```
but it outputs that `input.jack()` is not an active source. How could I do that?

BTW, the documentation for the conditionals is very limited ^^

**Comment by toots** [comment]
Hi.

Active sources have their own clocks. There's another issue related to your problem here: #419 

What input would you use if jack isn't enabled?

**Comment by Yamakaky** [comment]
It's mainly for easier development, where I use pulseaudio for the input.

**Comment by toots** [comment]
Ok, thanks. For now, I'd suggest simply commenting out some parts in the code. I'll see if I can fix this typing issue, `active_source` and `source` should actually work together nicely.

**Comment by Yamakaky** [comment]
I think I'll end up including a `input.local.liq` ignored by git, that should do the job.

**Comment by smimram** [comment]
The `active_source` type was removed, I guess we can close this now.
