### ISSUE TITLE
Passing metadata to/evaluating result of a function

### ISSUE THREAD

**Issue by haydenryan** [savonet/liquidsoap#422]
Hi,
I am trying to run a conditional on my stream to check for metadata. If the function apply_metadata returns 1, an ad is playing on the stream (because the album name is AD30), so play another local ad - otherwise relay the stream.

Ideally I'd like to be able to update a variable from my apply_metadata function, but it looks like liquidsoap can't read that from outside the function (if I define a variable in a function and then print that variable outside it, I get the error ```This term would evaluate to a function which
  would then be dropped.```)

Here's my current code:
```
# Input Stream
stream = input.http("http://127.0.0.1:8000/main.ogg.m3u")
radio = stream
# Some jingles
jingles = playlist("jingles2.m3u")
# If something goes wrong, we'll play this
#security = single("~/radio/sounds/default.ogg")

def apply_metadata(m) =
  title = m["title"]
  artist = m["artist"]
  album = m["album"]
  if album == "AD30" then
    #radio = jingles
    print("This is an ad")
    1
  else
    #radio = stream
    print("Now playing: #{title} by #{artist} from #{album}")
    0
  end
end

radio = if on_metadata(apply_metadata,stream) == 1 then radio = jingles else radio = stream end
radio = on_metadata(apply_metadata,radio)

out = output.icecast(%vorbis,host="localhost", port=8000, password="4me2cnow", mount="second.ogg", fallible=true, radio)
```
which returns the error:
```
At line 24, char 38:
  this value has type
    (...)->int (inferred at line 9 char 1 - line 22 char 3)
  but it should be a subtype of
    (...)->unit
```

(Note: I understand I shouldn't be calling apply_metadata with on_metadata on line 24 - however I can't work out a way to pass the metadata directly to the function without it)

So, a couple of questions:
- How can I set a variable in my apply_metadata function which can be evaluated outside it?
- How can I pass the album name directly to the function?
Or, is there a better way to do this?

Thanks

**Comment by smimram** [comment]
The way out consists in using a reference. Then `apply_metadata` can simply modify it, without returning a value. To use it, you can use `switch` which makes a source available only when a condition is satisfied (here, the variable). So, I would do something like this (not tested):
```
# Input Stream
stream = input.http("http://127.0.0.1:8000/main.ogg.m3u")
# Some jingles
jingles = playlist("jingles2.m3u")
# If something goes wrong, we'll play this
#security = single("~/radio/sounds/default.ogg")

ad = ref false

def apply_metadata(m) =
  title = m["title"]
  artist = m["artist"]
  album = m["album"]
  if album == "AD30" then
    #radio = jingles
    print("This is an ad")
    ad := true
  else
    #radio = stream
    print("Now playing: #{title} by #{artist} from #{album}")
    ad := false
  end
end

stream = on_metadata(apply_metadata,stream)
jingles = switch([({!ad}, jingles)])

radio = fallback([jingles, stream])

out = output.icecast(%vorbis,host="localhost", port=8000, password="4me2cnow", mount="second.ogg", fallible=true, radio)
```
