### ISSUE TITLE
cue_file NameError: name 'ffmpeg' is not defined

### ISSUE THREAD

**Issue by LordHelmchen666** [savonet/liquidsoap#4229]
### Description

cue_file throws error _NameError: name 'ffmpeg' is not defined_ when writing tags is enabled.
```
Traceback (most recent call last):
  File "/usr/local/bin/cue_file", line 1261, in <module>
    write_tags(args.file, result, args.replaygain)
  File "/usr/local/bin/cue_file", line 995, in write_tags
    ffmpeg,
    ^^^^^^
NameError: name 'ffmpeg' is not defined
```

[Line 995](https://github.com/savonet/liquidsoap/blob/aab0fd84681d1f6f76738971d3f2274e7005b172/scripts/cue_file)
i guess needs to be `FFMPEG` .

### Steps to reproduce

Try `cue_file -w /my.mp3`

### Expected behavior

Throw no error and write tags to file.

### Liquidsoap version

```text
no version. pull request
```

### Liquidsoap build config

```text
no version
```

### Installation method

From source/self-built

**Comment by gAlleb** [comment]
Yeah, our ffmpeg binary is a preset in the begining: `# Default presets: FFMPEG = "ffmpeg"`

You can do that or add `ffmpeg=FFMPEG` to the `write` function.

```python
def write_tags(filename, tags={}, replaygain=False, ffmpeg=FFMPEG):
```

**Comment by toots** [comment]
I'm not sure that this an error with liquidsoap!

**Comment by toots** [comment]
Ha. yes, of course thanks for noticing. I'm not sure yet if we'll go that route.
