### ISSUE TITLE
rms.stereo decimal places

### ISSUE THREAD

**Issue by Johnson120** [savonet/liquidsoap#423]
Hello!

We've just upgraded Liquidsoap across our station from a git clone from around August to the latest one, and noticed that our volume meters have suddenly lost precision because Liquidsoap is only giving us volume to 1 decimal place now. Is this a deliberate change? Anything we can do to get 2 decimal places again?

Here's the kind of thing we do to get separate left/right levels:

```
rmsaudio = rms.stereo(duration=rms_sample_length,mksafe(hardware_input))
rms = fst(rmsaudio)
hardware_input = snd(rmsaudio)

def rms_left(_) = "#{fst(rms())}" end
def rms_right(_) = "#{snd(rms())}" end
server.register("rms_left",rms_left)
server.register("rms_right",rms_right)
```

**Comment by toots** [comment]
Thanks for reporting this. Should be fixed with the latest `master` now.
