### ISSUE TITLE
Unknown protocol "process"

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#424]
```
Unknown protocol "process" in URI "process:x,sqlite3"!
```
Does it need to be activated?
(It's not the complete command, I cut it to `sqlite3` for the issue)

**Comment by toots** [comment]
Hmm interesting. How did you get to this point?

**Comment by Yamakaky** [comment]
I'm on archlinux https://aur.archlinux.org/packages/liquidsoap/ (build script: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=liquidsoap)

**Comment by toots** [comment]
Protocols like `process` are a very recent and yet unreleased feature of liquidsoap. I don't think you would encounter that issue using the archlinux package..

**Comment by Yamakaky** [comment]
So it's for the next release?

Maybe then make that http://liquidsoap.fm/doc-latest points to the latest release and not `master`.

**Comment by toots** [comment]
I've renamed it `doc-dev` to make it clear.

**Comment by Yamakaky** [comment]
Can't make the 1.2.1 doc the default one?
