### ISSUE TITLE
Loading two scripts in sequence fails with 2.2.5 (but works with 2.3.0) on macOS

### ISSUE THREAD

**Issue by floholl** [savonet/liquidsoap#4255]
### Description

See discussion #4254, which revealed the following bug: On Liquidsoap v2.25 under macOS installed via opam, loading multiple `.liq` scripts in a single Liquidsoap command does not work [as expected](https://www.liquidsoap.info/doc-2.2.5/script_loading.html), but the same works fine in v2.3.0.

### Steps to reproduce

The following plays the expected sine wave:

```
$ cat sine_portaudio.liq
src = sine()
output.portaudio(src)
$ liquidsoap sine_portaudio.liq
```

However, if I split the two lines from the previous `.liq` script into two separate scripts and load both, I get an error under v2.2.5 on macOS (Liquidsoap retrieved via `opam`):

```
$ cat sine.liq
src = sine()
$ cat portaudio.liq
output.portaudio(src)
$ liquidsoap sine.liq portaudio.liq
Unknown position:

Error -1: Exception raised: File "src/core/stream/frame_settings.ml", line 123, characters 6-12: Assertion failed
...
```

But it works just fine when upgrading Liquidsoap to 2.3.0 via `opam` on the same machine.

### Expected behavior

Playing a sine wave on the local sound card.

### Liquidsoap version

```text
Liquidsoap 2.2.5 under macOS, retrieved via `opam`
```

### Liquidsoap build config

```text
I am afraid I cannot reproduce this after already having upgraded Liquidsoap to v2.3.0.
```

### Installation method

From OPAM

**Comment by toots** [comment]
Thanks for reporting. This was never really meant to work before `2.3.0` and is working now due to the work on concatenating script before running them to implementing script cache.

**Comment by toots** [comment]
Ho my bad I see the doc now.
