### ISSUE TITLE
Error: Unbound module Configure

### ISSUE THREAD

**Issue by mcfiredrill** [savonet/liquidsoap#428]
I get this error on some of my machines compiling liquidsoap, but not all the time. I suppose I just have one of my ocaml dependencies configured incorrectly. Any tips would be appreciated. :)

```
make[2]: Circular tools/dyntools.cmx <- configure.cmx dependency dropped.
OCAMLOPT -c tools/dyntools.ml
File "tools/dyntools.ml", line 144, characters 2-19:
Error: Unbound module Configure
make[2]: *** [tools/dyntools.cmx] Error 2
make[1]: *** [all-auto-ocaml-prog] Error 2
make: *** [all-subdirs] Error 2
```

**Comment by toots** [comment]
Hi.

This could be indicative of many issues, including a missing source file.. Could you post more logs from the configure/make process? Thanks!

**Comment by mcfiredrill** [comment]
Sorry, will open with more detail if I have this problem again! 😅
