### ISSUE TITLE
Installing the new liquidsoap_2.3.0-debian-trixie-1_amd64.deb problems

### ISSUE THREAD

**Issue by etherwvlf** [savonet/liquidsoap#4283]
### Description

I have difficulties installing the latest 2.3.0 version on a Debian testing machine compared to previous versions with which I've never had any problems.
After some time fooling around myself with the problems to no avail, I found a suggestion on here that one should add the deb-multimedia.org repo to install successfully which I did and surely enough was able to install the package.

The thing is adding third party repos is against the best practices of using Debian.
I have had many instances where deb-multimedia packages broke the system (libraries didn't play well together) and/or some software no longer worked properly.

I just don't want having to deal with core libraries getting replaced with third-party versions. Also dealing with the nightmare of managing the packages (which are deb-multimedia and which are Debian) as well as it making upgrades troublesome (often apt would try to remove large amounts of software/packages to satisfy a dependency conflict).

The deb-multimedia repository maintainer builds packages with the same names as Debian packages, but built in ways that are not always compatible with Debian packages. That repository absolutely can and will break Debian if you allow it to blindly upgrade over Debian packages. 

What are my options and is that a permanent thing now ? There surely must be a way to install without third-party packages as the situation was with the previous versions.
Thanks the dev team for all their hard work on this beautiful software.

### Steps to reproduce

Try to install liquidsoap_2.3.0-debian-trixie-1_amd64.deb on Debian Trixie without adding deb-multimedia.org repo

### Expected behavior

Ability to install liquidsoap_2.3.0-debian-trixie-1_amd64.deb on Debian Trixie without adding deb-multimedia.org repo as was with the previous versions.

### Liquidsoap version

```text
liquidsoap 2.3.0
```

### Liquidsoap build config

```text
Non relevant
```

### Installation method

From official packages in the release artifacts

**Comment by gAlleb** [comment]
You need `deb-multimedia` only because of `ffmpeg7`. Not sure if that can become a nightmare or be unsafe.

Alternatively you can use Liquidsoap in a Docker container https://hub.docker.com/u/savonet/

**Comment by vitoyucepi** [comment]
Hi @etherwvlf,
`ffmpeg` from deb-multimedia is a hard dependency of the package because of `fdkaac`, if I remember correctly. It is not free, so debian builds `ffmpeg` without it.
You can either use containers or build from opam.

**Comment by etherwvlf** [comment]
> You need `deb-multimedia` only because of `ffmpeg7`. Not sure if that can become a nightmare or be unsafe.
> 
> Alternatively you can use Liquidsoap in a Docker container https://hub.docker.com/u/savonet/

Is there a chance this version to find it's way into testing ?
Meaning could I just wait on it using liquidsoap 2.2.5 until this ffmpeg get upgraded eventually ?
Docker containers are no option for me on that machine.

**Comment by etherwvlf** [comment]
> Hi @etherwvlf, `ffmpeg` from deb-multimedia is a hard dependency of the package because of `fdkaac`, if I remember correctly. It is not free, so debian builds `ffmpeg` without it. You can either use containers or build from opam.
Yes, but what changed ?
How come the previous version was installable without deb-multimedia but not this one ?
Containers are no option for me and if I cannot just wait on it using liquidsoap 2.2.5 until ffmpeg gets upgraded(if that is even a possibility) I may be left with the only option of compiling this myself unfortunately...

**Comment by vitoyucepi** [comment]
> How come the previous version was installable without deb-multimedia but not this one ?

I think the reason for using *deb-multimedia* is the broadest codec support. I don't fully agree with the decision, but I bet `fdkaac` is one of the most requested features.

> Containers are no option for me

May I have a bit of clarification on your position?

> I may be left with the only option of compiling this myself unfortunately

That's the best option you have if you want to customize the installation for your own needs.

**Comment by Warblefly** [comment]
On Tue, 24 Dec 2024, 09:12 Vito, ***@***.***> wrote:

> How come the previous version was installable without deb-multimedia but
> not this one ?
>
> I think the reason for using *deb-multimedia* is the broadest codec
> support. I don't fully agree with the decision, but I bet fdkaac is one
> of the most requested features.
>
Certainly, fdkaac is my "must have". HE-AACv2 down at the lowest variable
rate (-vbr 1), around 28-32kbit/s, at 32kHz sampling rate, is my reason for
compiling FFmpeg myself.

One must be careful to use the right encapsulation, to prevent a huge
amount of padding.

Example 28-32kbit/s stream for test/evaluation:
http://warblefly.sytes.net:8000/live.m3u8

With best wishes,
John

>

**Comment by etherwvlf** [comment]
> > Containers are no option for me
> 
> May I have a bit of clarification on your position?

Very finicky client who is quite adamant on what does he wants installed on this particular machine.
Mad about efficiency, minimalism, unencumbered with useless (his description) software startup speeds etc...
Long story...
I really gotta make that work without containers lol

**Comment by etherwvlf** [comment]
I just need one more question answered which everyone seemed to overlook.

Is there any chance this required ffmpeg version to find it's way into testing ?
Meaning could I just wait on it using liquidsoap 2.2.5 until this ffmpeg get upgraded eventually ?

Thank you all for your answers and Merry Christmas !

**Comment by vitoyucepi** [comment]
Hi @etherwvlf,
I can't recommend you to install liquidsoap 2.2.5 unless it's from debian repo and wait until ffmpeg is updated. The binary interface of some libraries may change and everything will be broken.
I can recommend you to make your client happy by installing opam, ocaml compiler, development packages and produce 500 MBs of various build artifacts.
If you're not a fan of creating a mess on the production system, then
1. use a package from the Debian repository;
2. use a package from release artifacts;
3. use a container image
4. build locally;
5. build on CI, e.g. GitHub actions.

**Comment by etherwvlf** [comment]
> Hi @etherwvlf, I can't recommend you to install liquidsoap 2.2.5 unless it's from debian repo and wait until ffmpeg is updated. The binary interface of some libraries may change and everything will be broken. I can recommend you to make your client happy by installing opam, ocaml compiler, development packages and produce 500 MBs of various build artifacts. If you're not a fan of creating a mess on the production system, then
> 
>     1. use a package from the Debian repository;
> 
>     2. use a package from release artifacts;
> 
>     3. use a container image
> 
>     4. build locally;
> 
>     5. build on CI, e.g. GitHub actions.

2.2.5 is currently installed and purring flawlessly along hence my question.
It was installed from the releases section here.
My problems only began when trying to install the latest 2.3.0 which seems to have this exotic form of ffmpeg's dependencies.

1. liquidsoap is with status REMOVED from testing since 2023-08-30
2. I was trying to install the latest package to no avail
3. Not applicable in my case
4. I am considering building on another machine or in a virtual machine as more and more it seems like I have no other option.
5. I currently don't posses the knowledge to do that. Should research further.

Thank you.

**Comment by toots** [comment]
Our own build use the ffmpeg from https://www.deb-multimedia.org/ because they provide ffmpeg with fdk-aac with AAC+ support.

If you install the sources from there, you should be able to install and run our own builds without issues.

**Comment by etherwvlf** [comment]
> Our own build use the ffmpeg from https://www.deb-multimedia.org/ because they provide ffmpeg with fdk-aac with AAC+ support.
> 
> If you install the sources from there, you should be able to install and run our own builds without issues.

Not wanting to come off as rude, ignorant or something. I am just assessing my options here. Seems like I am the minority not wanting to create this Frankendebian here, adding third party repo and potentially creating more problems for myself in the long run.

**Comment by toots** [comment]
> > Our own build use the ffmpeg from https://www.deb-multimedia.org/ because they provide ffmpeg with fdk-aac with AAC+ support.
> > If you install the sources from there, you should be able to install and run our own builds without issues.
> 
> Not wanting to come off as rude, ignorant or something. I am just assessing my options here. Seems like I am the minority not wanting to create this Frankendebian here, adding third party repo and potentially creating more problems for myself in the long run.

I understand the anxiety but AAC+ support out of the box is a big plus for most of our users.

deb-multimedia has been around for decades, it's a pretty standard source to add.

**Comment by etherwvlf** [comment]
> > > Our own build use the ffmpeg from https://www.deb-multimedia.org/ because they provide ffmpeg with fdk-aac with AAC+ support.
> > > If you install the sources from there, you should be able to install and run our own builds without issues.
> > 
> > 
> > Not wanting to come off as rude, ignorant or something. I am just assessing my options here. Seems like I am the minority not wanting to create this Frankendebian here, adding third party repo and potentially creating more problems for myself in the long run.
> 
> I understand the anxiety but AAC+ support out of the box is a big plus for most of our users.
> 
> deb-multimedia has been around for decades, it's a pretty standard source to add.

Thanks for your time.
I'll figure something out.
You can close this.
