### ISSUE TITLE
Shoutcast v2 source

### ISSUE THREAD

**Issue by lrfsh** [savonet/liquidsoap#430]
Hello,

First of all, thank you for this open source streaming app.

Secondly, I need to stream to a Shoutcast Server DNAS 2.5.1.724 with source V2, i managed to stream with AAC 2 but the Shoutcast server says that the source is V1 and not V2 so I can't use the monetize program

Here is my script: 
```
#!/usr/bin/liquidsoap

# Enable logging
set("log.file.path","/home/radio/<script>.log")

# AAC Stream
shout = output.shoutcast(%fdkaac(channels=2, samplerate=44100, bitrate=64, afterburner=false, aot="mpeg2_he_aac_v2", transmux="adts", sbr_mode=false), host="127.0.0.1",port=8005,
# MP3 Stream
#shout = output.shoutcast(%mp3, host="127.0.0.1",port=8005,
  password="W4Nt6FvYvJbla",genre="",url="",
  name="",
  public=false,irc="")


musiclist = playlist(reload=21600,"/home/radio/lista.m3u")
musiclist = mksafe(musiclist)
musiclist = normalize(musiclist)
musiclist = smart_crossfade(musiclist)
musiclist = skip_blank(musiclist)


shout(musiclist)
```
Is possible to stream with v2 source? 

Thank you

**Comment by neralex** [comment]
Liquidsoap doesn't support the the SHOUTcast v2 protocoll!

**Comment by norecords** [comment]
Hi there, is this still the case ?

**Comment by smimram** [comment]
@norecords I don't think that there is any progress on this for now.

Closing this bug report, since it was already reported as #389.
