### ISSUE TITLE
QUESTION: say_metadata() @ the beginning of the track

### ISSUE THREAD

**Issue by count00zero** [savonet/liquidsoap#431]
Dear liquidsoap developers :)

I recently started to use liquidsoap with my private radiostream (@home).
Everything went very well, but the function say_metadata doesn't work as I think it should do (or maybe I'm using it wrong).
It always "says" the metadata when the track ends and before the next one begins. BUT shouldn't it be triggered at the beginning of the new track?
And if not, how could one (I) configure it to say the metadata at the beginning of the track?

THANKS and best regards,
count

**Comment by toots** [comment]
Hi,

Sorry, I only see this now.

How do you use the functionality? Can you share some script? Thanks!

**Comment by count00zero** [comment]
Hi,

I'm using it in this simple manner:
`radio = say_metadata(radio)`

Thanks in advance.

**Comment by smimram** [comment]
The function `say_metadata` is [defined here](https://github.com/savonet/liquidsoap/blob/master/lib/utils.liq#L171):
```
def say_metadata
  p = 'say:$(if $(artist),"It was $(artist)$(if $(title),\\", $(title)\\").")'
  fun (s,~pattern=p) ->
    append(s,fun (m) -> request.queue(queue=[request.create(pattern % m)],
                                      interactive=false))
end
```
If you change `append` to `prepend` it should behave as desired.
