### ISSUE TITLE
Ubuntu 16.10: build/make not possible (taglib)

### ISSUE THREAD

**Issue by count00zero** [savonet/liquidsoap#433]
Hi again,

I've got an issue when building liquidsoap from source (full).
As soon as I'm at stage "make" I cannot move on because of some problems withe the compilation of ocaml-taglib.

The following error occurs: `/usr/bin/ld: /usr/local/lib/libtag.a(mpegfile.cpp.o): relocation R_X86_64_PC32 against symbol "_ZTVN6TagLib4MPEG4FileE" can not be used when making a shared object; recompile with -fPIC`

Do you mayhaps know any solution for that problem?

THANKS in advance and BR,
count

**Comment by toots** [comment]
Hi,

This is a weird bug. It looks like you compiled taglib yourself. Have you tried using the packages provided by your distribution?

More generally, do you need to compile from source explicitly or could you try to use `opam` pinning? `opam` pinning should help you by re-using automated support for building liquidsoap such as external packages dependencies.

**Comment by toots** [comment]
See: http://liquidsoap.fm/download.html#opam

**Comment by count00zero** [comment]
Hi there,

thanks for your answer!
I once built taglib myself (newer version was needed for my install of gerbera [https://github.com/v00d00/gerbera].
I'll check out opam pinning!

Thanks again and best regards,
count

**Comment by toots** [comment]
Ok. Make sure that you compile taglib with the `-fPIC` option if you compile it on your own. I'm pretty sure that this is where your issue comes from.

Gonna close this issue. Please, feel free to re-open if you're having more trouble.

**Comment by count00zero** [comment]
Hello again,

thanks for your help.  The taglib part went well this time :)
Unfortunately, the following happend:```

OCAMLOPT -c lang/lang_builtins.ml
File "lang/lang_builtins.ml", line 103, characters 17-40:
Error: Unbound value String.capitalize_ascii
```

Maybe you know a solution for this too?

Best Regards,
count

**Comment by toots** [comment]
You should update your sources, I think this has been fixed now.

**Comment by count00zero** [comment]
AND ....... THANKS AGAIN!
Did a complete cleanup, pull, init and so on and built everything successfully!!!

THANKS!

Best regards,
count
