### ISSUE TITLE
Error decoding WAV files

### ISSUE THREAD

**Issue by Tokyx** [savonet/liquidsoap#436]
Hi everyone,

I have some issues when I try to decode WAV (PCM) file, I've got an error : 
> Could not get a valid media file of kind {audio=2;video=0;midi=0} from "/home/dechire.wav"

But, liquidsoap seems to support it (liquidsoap --conf-descr | grep wav)

>\# Default: ["wav"]
>set("decoder.file_extensions.wav",["wav"])
>\# Default: ["audio/vnd.wave","audio/wav","audio/wave","audio/x-wav"]
>set("decoder.mime_types.wav",["audio/vnd.wave","audio/wav","audio/wave","audio/x-wav"])
>\# Default: ["audio/mpeg","audio/aacp","audio/aac","audio/x-aac","audio/wav","audio/wave","audio/x-flac"]
>set("harbor.icy_formats",["audio/mpeg","audio/aacp","audio/aac","audio/x-aac","audio/wav","audio/wave","audio/x-flac"])

Do you have some idea of what happen ?

I use liquidsoap 1.1.1 on Debian 8.

> music = single("/home/dechire.wav")

**Exemple WAV :** 
> Audio
> Format                      : PCM
> Format settings, Endianness : Little
> Format settings, Sign       : Signed
> Codec ID                    : 1
> Duration                    : 4 min
> Bit rate mode               : Constant
> Bit rate                    : 1 411.2 kb/s
> Channel(s)                  : 2 channels
> Sampling rate               : 44.1 kHz
> Bit depth                   : 16 bits
> Stream size                 : 47.1 MiB (100%)

Thanks !

**Comment by toots** [comment]
Any chance you could try with liquidsoap `1.3.0`? `1.1.1` is a rather old version..

**Comment by toots** [comment]
Or else, feel free to send me the file at toots@rastageeks.org.

**Comment by smimram** [comment]
Wav files are now handled by ffmpeg by default, which should help on strange files. If you still have the bug, please reopen and provide a test case.
