### ISSUE TITLE
get_process_lines Regression in Liquidsoap 1.3.0 (no output)

### ISSUE THREAD

**Issue by dtcooper** [savonet/liquidsoap#439]
I installed liquidsoap 1.3.0 on Ubuntu 16.04 LTS using opam, and I observe that `get_process_lines(...)` returns no output

```
$ liquidsoap 'print(get_process_lines("whoami"))'
[]
No output defined, nothing to do.
```

Running the same command with liquidsoap 1.2.1 works,

```
$ liquidsoap 'print(get_process_lines("whoami"))'
["liquidsoap"]
No output defined, nothing to do.
```

(Note `get_process_output` also is broken)

Thanks,

David

---

Here's the opam install script (`install_liquidsoap_opam.sh`)

```
#!/bin/sh

LIQUIDSOAP_OPAM_DEPS="taglib mad lame vorbis cry alsa"

# Install opam and minimal ocaml
sudo apt-get install -y build-essential
sudo apt-get install -y --no-install-recommends opam m4 ocaml-nox

# Add a liquidsoap user
sudo adduser --system --disabled-password --shell=/bin/bash --group liquidsoap
sudo adduser liquidsoap audio

# Init opam + install depext
sudo -iu liquidsoap opam init -ya
sudo -iu liquidsoap opam install depext

# Compute dependencies
DEPS=$(sudo -iu liquidsoap opam depext -l $LIQUIDSOAP_OPAM_DEPS)

# Install dependencies
DEPS=$(echo "$DEPS" | grep '^#  - ' | sed 's/^#  - //')
sudo apt-get -y install $DEPS

# Install opam packages including liquidsoap
# Change "liquidsoap" => "liquidsoap.1.2.1" for a different version
sudo -iu liquidsoap opam install -y $LIQUIDSOAP_OPAM_DEPS liquidsoap
```

**Comment by dtcooper** [comment]
Strangely not observed on macOS El Capitan (10.11.6)

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1421
$ liquidsoap --version
Liquidsoap 1.3.0
Copyright (c) 2003-2017 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.fm> for more information.
$ liquidsoap 'print(get_process_lines("whoami"))'
["david"]
No output defined, nothing to do.
```

**Comment by toots** [comment]
I can confirm this one. Same as #437 Interestingly, it doesn't show up inside a docker container.

**Comment by toots** [comment]
This is a bug in the OCaml compiler. See: https://caml.inria.fr/mantis/view.php?id=7136

I'll commit a fix in the code and close this issue. I don't think we need to re-releasing, the issue has been fixed in OCaml 4.03 and above so I would recommend to upgrade your compiler for the time being.

Thanks for reporting.

**Comment by toots** [comment]
Actually, looking at default compiler versions in Debian and Ubuntu, I think that we're gonna have to release a bugfix version soon, unfortunately..

**Comment by dtcooper** [comment]
@toots Makes sense. +1 on a bugfix. Thanks for confirming what was causing the bug so I can fix locally.

Best,

David

**Comment by mcfiredrill** [comment]
Is there a bugfix release for this yet? Or an easy way to upgrade the compiler? 🤔

**Comment by dtcooper** [comment]
I just patched the 1.3.0 with the fix and compiled.

**Comment by hairmare** [comment]
I installed from opam using the instructions from http://liquidsoap.fm/download.html (or from https://github.com/savonet/liquidsoap/issues/402#issuecomment-287561420). Upgrading the compiler is probably not a quick fix, opening a bug with your distro might make sense.

**Comment by toots** [comment]
Yes, I plan on pushing a release in the next week or so. Just waiting a little bit to see if anything else shakes up..

**Comment by toots** [comment]
Also pushing a patch through opam right now.

**Comment by mcfiredrill** [comment]
I’m still seeing strange behavior with this running liquidsoap in a docker container.
Specifically I'm trying to run Ruby. I don't see any output at all.

```
liquidsoap@f42fe715cb60:~$ liquidsoap --version
Liquidsoap 1.3.0+scm (git://github.com/savonet/liquidsoap.git@522e0e1957bf98ba35720a19ce4a23f574b45941:20170518:002928)
Copyright (c) 2003-2017 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.fm> for more information.
liquidsoap@f42fe715cb60:~$ liquidsoap 'print(get_process_lines("date"))'
["Thu May 18 04:09:47 UTC 2017"]
No output defined, nothing to do.
liquidsoap@f42fe715cb60:~$ liquidsoap 'print(get_process_lines("ruby -v"))'
[]
No output defined, nothing to do.
liquidsoap@f42fe715cb60:~$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
liquidsoap@f42fe715cb60:~$ liquidsoap 'print(get_process_lines(“python --version"))'
[]
No output defined, nothing to do.
liquidsoap@f42fe715cb60:~$ python --version
Python 2.7.6
```
On my Ubuntu system outside of the container it works fine.

Does it seem like this could be related?

**Comment by toots** [comment]
Interesting. Thanks for reporting. What do you see if you use `run_process` instead?

**Comment by hairmare** [comment]
Python prints it's version to stderr. To get around that you can redirect stderr to stdout.

```
liquidsoap 'print(get_process_lines("python --version 2>&1"))'
```
```
["Python 2.7.5"]
```

Or you can access the stderr part directly through `run_process`.

```
liquidsoap 'print(string.split(separator="\\n",snd(fst(run_process("python --version")))))'
```
```
["Python 2.7.5"]
```

It doesn't make much sense that the same wouldn't work with ruby.. I was pretty sure I was reproducing the issue until I realized that I had simply forgotten to install ruby in my container.

**Comment by mcfiredrill** [comment]
@hairmare Thanks for trying to help, I tried using stderr and it seems I have a different path when running commands through `get_process_lines` in liquidsoap.
```
liquidsoap@f42fe715cb60:~$ liquidsoap 'print(get_process_lines("ruby -v 2>&1"))'
["/bin/sh: 1: ruby: not found"]
No output defined, nothing to do.
```

**Comment by toots** [comment]
@mcfiredrill Starting with `1.3.0`, `get_process_lines` and others takes an `env` parameter. If you use env-based ruby wrappers such as `rvm` and the like, this is probably where you will need to adjust.

**Comment by mcfiredrill** [comment]
@toots Yes I noticed that. 

Before those changes were made, `get_process_lines` and others seemed to inherit the whole environment from the liquidsoap process.  That doesn't seem to be the case anymore. 

I have to admit the previous behavior was more convenient for my needs as I rely on quite a few environment variables, but I'll see what I can do.

**Comment by mcfiredrill** [comment]
@toots Going to see if I can just pass the whole environment to `get_process_lines` with `environment()`.

http://savonet.sourceforge.net/doc-svn/reference.html#environment

**Comment by toots** [comment]
I might reverse that in the next release as well.

**Comment by toots** [comment]
Ok, reversed in latest `master`. Expect a release some time next week.

**Comment by toots** [comment]
Also, I've made the type for `env` to match the returned type of `environment` for convenience..

**Comment by itibet** [comment]
Hi, I've compiled liquidsoap with OCaml 4.04, but now I've got this weird behaviour:
- if I launch liquidsoap as a service `sudo service liquidsoap start`, then `get_process_lines` gives no output
- if I launch in a shell with `liquidsoap run.liq` then `get_process_lines` works fine but liquidsoap fails to decode streams of type "audio/aacp".
In both cases the liquidsoap process runs with the same user.
Thank you

**Comment by toots** [comment]
Hi @itibet,

For `audio/aacp`, you might need to install the `faad` module:

```
% opam depext faad
% opam install faad
```

For the `get_process_lines` issue, could you tell me more about what/how you are calling it?

Thanks!

**Comment by itibet** [comment]
Hi @toots,
as for `audio/aacp` I'm using aacplus module, strangely it works if I run liquidsoap as a service, while if I launch the same script with `liquidsoap myscript.liq` then liquidsoap fails to decode aacp.

As for `get_process_lines`, in my script I get the list of files in a folder with `get_process_lines("ls path/to/folder")` starting with version 1.3.0 I get no output when running liquidsoap as a service, while the following works fine: `liquidsoap 'print( get_process_lines("ls") )'` (i.e. not launching as a service).

Could these problems be related somehow?
Thank you

**Comment by toots** [comment]
@itibet Most likely yes. It sounds like the service isn't running the same liquidsoap binary. If you switch compiler in `opam` and reinstall `liquidsoap` with it, you will end-up with two different binaries in different path. You might want to compare:
```
which liquidsoap
```
With the path used in your service script.

**Comment by itibet** [comment]
Thank you @toots,
you are perfectly right, now it works.
I've also installed `faad` package and `audio/aacp` decoding is working as well. Does this package replace `aacplus` package?
Thanks for you help!

**Comment by toots** [comment]
@itibet Excellent! `aacplus` was only for decoding, it's been deprecated in favor of `fdkaac` with `1.3.0`

**Comment by mcfiredrill** [comment]
Just wanted to say thanks for the fix @toots 
https://github.com/savonet/liquidsoap/commit/11f8247fe5226e468180781e58adad7181b8f167
