### ISSUE TITLE
Pulseaudio output

### ISSUE THREAD

**Issue by vrtisworks** [savonet/liquidsoap#444]
I have managed to install Liquidsoap 1.3 on a Raspberry Pi (I have a set of notes I need to polish up and I will add them to the mailing list) - it works fine, and I didn't have any problems with the install.

BUT.. I am having problems getting sound through Pulseaudio to the onboard audio.  I know it works, because I can use MPG321 to play an MP3 through Pulse to the speakers. 

When I try to output it through Liquidsoap, I do not get any sound.  It looks like Liquidsoap is sending stuff to Pulse, and Pulse is seeing Liquidsoap talking to it.

I have a simple pls file, with one file listed, and I run Liquidsoap from a single inline command (the command and the output is below).

I have also included a log from "pacmd" which shows that Pulse is up and sees that Liquidsoap is connected.  It also shows that the output is not muted, and does have the volume up.

One other strange thing.  If I hit Control+C, Liquidsoap starts to shut down, but then sort of hangs.  It will hang until I shutdown Pulse via the "pacmd" exit command.  Once I do that, Liquidsoap finishes the shutdown (I added some **** where I hit the Control+C, and also where I shut down Pulse in a different session.
```
liquidsoap@audiobox:~/audiobox $ liquidsoap 'output.pulseaudio(mksafe(playlist("testing.pls")))'
2017/05/12 14:47:59 >>> LOG START
2017/05/12 14:47:57 [main:3] Liquidsoap 1.3.0
2017/05/12 14:47:57 [main:3] Using: bytes=[OCaml strictly before 4.02] pcre=7.2.3 dtools=0.3.3 duppy=0.6.0 duppy.syntax=0.6.0 cry=0.5.0 mm=0.3.0 mad=0.4.5 dynlink=[distributed with Ocaml] lame=0.3.3 alsa=0.2.3 taglib=0.3.3 camomile=0.8.5 pulseaudio=0.1.3
2017/05/12 14:47:57 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2017/05/12 14:47:59 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2017/05/12 14:47:59 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2017/05/12 14:47:59 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2017/05/12 14:47:59 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2017/05/12 14:47:59 [threads:3] Created thread "generic queue #1".
2017/05/12 14:47:59 [threads:3] Created thread "generic queue #2".
2017/05/12 14:47:59 [threads:3] Created thread "non-blocking queue #1".
2017/05/12 14:47:59 [threads:3] Created thread "non-blocking queue #2".
2017/05/12 14:47:59 [testing(dot)pls:3] Loading playlist...
2017/05/12 14:47:59 [testing(dot)pls:3] No mime type specified, trying autodetection.
2017/05/12 14:47:59 [testing(dot)pls:3] Playlist treated as format application/x-mpegURL
2017/05/12 14:47:59 [testing(dot)pls:3] Successfully loaded a playlist of 1 tracks.
2017/05/12 14:47:59 [threads:3] Created thread "wallclock_pulse" (1 total).
2017/05/12 14:47:59 [clock.wallclock_pulse:3] Streaming loop starts, synchronized by active sources.
2017/05/12 14:47:59 [mksafe:3] Switch to safe_blank.
2017/05/12 14:47:59 [decoder:3] Method "MAD" accepted "/home/liquidsoap/testing_venus.mp3".
2017/05/12 14:47:59 [testing(dot)pls:3] Prepared "/home/liquidsoap/testing_venus.mp3" (RID 1).
2017/05/12 14:47:59 [mksafe:3] Switch to testing(dot)pls with transition.
********************************** Here is where I hit the Control+C
^C2017/05/12 14:50:29 [main:3] Shutdown started!
2017/05/12 14:50:29 [main:3] Waiting for threads to terminate...
 ********************************* Here is where I told Pulse to shutdown.
2017/05/12 14:50:45 [clock.wallclock_pulse:2] Source pulse_out(liquidsoap:) failed while streaming: Pulseaudio error: Connection terminated!
2017/05/12 14:50:45 [clock.wallclock_pulse:3] Called from file "outputs/output.ml", line 180, characters 6-27
2017/05/12 14:50:45 [clock.wallclock_pulse:3] Called from file "clock.ml", line 160, characters 17-25
2017/05/12 14:50:45 [testing(dot)pls:3] Finished with "/home/liquidsoap/testing_venus.mp3".
2017/05/12 14:50:45 [clock.wallclock_pulse:3] Streaming loop stopped.
2017/05/12 14:50:45 [threads:3] Thread "wallclock_pulse" terminated (0 remaining).
2017/05/12 14:50:45 [main:3] Threads terminated.
2017/05/12 14:50:45 [threads:3] Shutting down scheduler...
2017/05/12 14:50:45 [threads:3] Thread "non-blocking queue #1" terminated.
2017/05/12 14:50:45 [threads:3] Scheduler shut down.
2017/05/12 14:50:45 [main:3] Cleaning downloaded files...
2017/05/12 14:50:45 [main:3] Freeing memory...
2017/05/12 14:50:45 >>> LOG END
liquidsoap@audiobox:~/audiobox $ 
liquidsoap@audiobox:~/audiobox $ 

liquidsoap@audiobox:~ $ pacmd
Welcome to PulseAudio 5.0! Use "help" for usage information.
>>> list-sink-inputs
1 sink input(s) available.
    index: 3
	driver: <protocol-native.c>
	flags: 
	state: RUNNING
	sink: 0 <alsa_output.platform-soc_audio.analog-stereo>
	volume: front-left: 42902 /  65% / -11.04 dB,   front-right: 42902 /  65% / -11.04 dB
	        balance 0.00
	muted: no
	current latency: 131.70 ms
	requested latency: 105.00 ms
	sample spec: float32le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	resample method: copy
	module: 11
	client: 6 <liquidsoap>
	properties:
		media.name = "pulse_out(liquidsoap:)"
		application.name = "liquidsoap"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "29"
		application.process.id = "1627"
		application.process.user = "liquidsoap"
		application.process.host = "audiobox"
		application.process.binary = "liquidsoap"
		application.language = "C"
		application.process.machine_id = "52ee0a3228b449d58ef83c53a12495f3"
		application.process.session_id = "c2"
		module-stream-restore.id = "sink-input-by-application-name:liquidsoap"
>>> exit
>>> liquidsoap@audiobox:~ $ 
```

**Comment by vrtisworks** [comment]
I tried running pulseaudio with extra logging (-vvvv).  Here is the log from that, in case it can provide any additional information.

`
I: [pulseaudio] client.c: Created 3 "Native client (UNIX socket client)"
D: [pulseaudio] protocol-native.c: Protocol version: remote 29, local 29
I: [pulseaudio] protocol-native.c: Got credentials: uid=1001 gid=1001 success=1
D: [pulseaudio] protocol-native.c: SHM possible: yes
D: [pulseaudio] protocol-native.c: Negotiated SHM: yes
D: [pulseaudio] module-augment-properties.c: Looking for .desktop file for liquidsoap
D: [pulseaudio] module-intended-roles.c: Not setting device for stream pulse_out(liquidsoap:), because it lacks role.
D: [pulseaudio] sink-input.c: Negotiated format: pcm, format.sample_format = "\"float32le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
I: [pulseaudio] sink-input.c: Trying to change sample rate
I: [pulseaudio] sink-input.c: Rate changed to 44100 Hz
D: [pulseaudio] module-suspend-on-idle.c: Sink alsa_output.platform-soc_audio.analog-stereo becomes busy, resuming.
D: [pulseaudio] sink.c: Suspend cause of sink alsa_output.platform-soc_audio.analog-stereo is 0x0000, resuming
D: [pulseaudio] reserve-wrap.c: Unable to contact D-Bus session bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Trying resume...
I: [alsa-sink-bcm2835 ALSA] alsa-util.c: cannot disable ALSA period wakeups
D: [alsa-sink-bcm2835 ALSA] alsa-util.c: Maximum hw buffer size is 743 ms
D: [alsa-sink-bcm2835 ALSA] alsa-util.c: Set buffer size first (to 32768 samples), period size second (to 32768 samples).
I: [alsa-sink-bcm2835 ALSA] alsa-util.c: ALSA period wakeups were not disabled
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: hwbuf_unused=0
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: setting avail_min=31886
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Time scheduling watermark is 20.00ms
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Resumed successfully...
D: [pulseaudio] module-suspend-on-idle.c: Sink alsa_output.platform-soc_audio.analog-stereo becomes idle, timeout in 5 seconds.
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Starting playback.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Cutting sleep time for the initial iterations by half.
D: [pulseaudio] module-suspend-on-idle.c: Sink alsa_output.platform-soc_audio.analog-stereo becomes idle, timeout in 5 seconds.
I: [pulseaudio] resampler.c: Forcing resampler 'copy', because of fixed, identical sample rates.
D: [pulseaudio] resampler.c: Resampler:
D: [pulseaudio] resampler.c:   rate 44100 -> 44100 (method copy)
D: [pulseaudio] resampler.c:   format float32le -> s16le (intermediate s16le)
D: [pulseaudio] resampler.c:   channels 2 -> 2 (resampling 2)
D: [pulseaudio] memblockq.c: memblockq requested: maxlength=33554432, tlength=0, base=4, prebuf=0, minreq=1 maxrewind=0
D: [pulseaudio] memblockq.c: memblockq sanitized: maxlength=33554432, tlength=33554432, base=4, prebuf=0, minreq=4 maxrewind=0
I: [pulseaudio] sink-input.c: Created input 0 "pulse_out(liquidsoap:)" on alsa_output.platform-soc_audio.analog-stereo with sample spec float32le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] sink-input.c:     media.name = "pulse_out(liquidsoap:)"
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Cutting sleep time for the initial iterations by half.
I: [pulseaudio] sink-input.c:     application.name = "liquidsoap"
I: [pulseaudio] sink-input.c:     native-protocol.peer = "UNIX socket client"
I: [pulseaudio] sink-input.c:     native-protocol.version = "29"
I: [pulseaudio] sink-input.c:     application.process.id = "8620"
I: [pulseaudio] sink-input.c:     application.process.user = "liquidsoap"
I: [pulseaudio] sink-input.c:     application.process.host = "audiobox"
I: [pulseaudio] sink-input.c:     application.process.binary = "liquidsoap"
I: [pulseaudio] sink-input.c:     application.language = "C"
I: [pulseaudio] sink-input.c:     application.process.machine_id = "52ee0a3228b449d58ef83c53a12495f3"
I: [pulseaudio] sink-input.c:     application.process.session_id = "c5"
I: [pulseaudio] sink-input.c:     module-stream-restore.id = "sink-input-by-application-name:liquidsoap"
I: [pulseaudio] protocol-native.c: Requested tlength=250.00 ms, minreq=20.00 ms
D: [pulseaudio] protocol-native.c: Adjust latency mode enabled, configuring sink latency to half of overall latency.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Cutting sleep time for the initial iterations by half.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Cutting sleep time for the initial iterations by half.
D: [pulseaudio] protocol-native.c: Requested latency=105.00 ms, Received latency=105.00 ms
D: [pulseaudio] memblockq.c: memblockq requested: maxlength=4194304, tlength=51160, base=8, prebuf=44112, minreq=7056 maxrewind=0
D: [pulseaudio] memblockq.c: memblockq sanitized: maxlength=4194304, tlength=51160, base=8, prebuf=44112, minreq=7056 maxrewind=0
I: [pulseaudio] protocol-native.c: Final latency 250.01 ms = 105.01 ms + 2*20.00 ms + 105.00 ms
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Cutting sleep time for the initial iterations by half.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Latency set to 105.00ms
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: hwbuf_unused=112552
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: setting avail_min=31887
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Requesting rewind due to latency change.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Requested volume: front-left: 42902 /  65% / -11.04 dB,   front-right: 42902 /  65% / -11.04 dB
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Got hardware volume: front-left: 42902 /  65% / -11.04 dB,   front-right: 42902 /  65% / -11.04 dB
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Calculated software volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB (accurate-enough=yes)
D: [alsa-sink-bcm2835 ALSA] sink.c: Volume not changing
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Requested to rewind 131072 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Limited to 123764 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: before: 30941
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: after: 30941
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Rewound 123764 bytes.
D: [alsa-sink-bcm2835 ALSA] sink.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] sink.c: latency = 0
D: [alsa-sink-bcm2835 ALSA] sink-input.c: Have to rewind 123764 bytes on render memblockq.
D: [alsa-sink-bcm2835 ALSA] source.c: Processing rewind...
D: [pulseaudio] core-subscribe.c: Dropped redundant event due to change event.
D: [alsa-sink-bcm2835 ALSA] protocol-native.c: Requesting rewind due to end of underrun.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Requested to rewind 131072 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Limited to 12972 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: before: 3243
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: after: 3243
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Rewound 12972 bytes.
D: [alsa-sink-bcm2835 ALSA] sink.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] sink.c: latency = 0
D: [alsa-sink-bcm2835 ALSA] sink-input.c: Have to rewind 12972 bytes on render memblockq.
D: [alsa-sink-bcm2835 ALSA] source.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] protocol-native.c: Implicit underrun of 'pulse_out(liquidsoap:)'
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4156 bytes ago (12600 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4156 bytes ago (10836 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4156 bytes ago (10836 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4156 bytes ago (9076 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4156 bytes ago (9076 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 14736 bytes ago (3784 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 14736 bytes ago (3784 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 14736 bytes ago (2020 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 14736 bytes ago (2020 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 14736 bytes ago (260 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 14736 bytes ago (260 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] protocol-native.c: Requesting rewind due to end of underrun.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Requested to rewind 23564 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Limited to 18264 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: before: 4566
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: after: 4189
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Rewound 16756 bytes.
D: [alsa-sink-bcm2835 ALSA] sink.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] sink.c: latency = 0
D: [alsa-sink-bcm2835 ALSA] sink-input.c: Have to rewind 16756 bytes on render memblockq.
D: [alsa-sink-bcm2835 ALSA] source.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] protocol-native.c: Implicit underrun of 'pulse_out(liquidsoap:)'
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4400 bytes ago (12356 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4400 bytes ago (10592 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 4400 bytes ago (8784 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 13276 bytes ago (5244 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 13276 bytes ago (3352 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] protocol-native.c: Requesting rewind due to end of underrun.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Requested to rewind 60848 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Limited to 12972 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: before: 3243
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: after: 3243
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Rewound 12972 bytes.
D: [alsa-sink-bcm2835 ALSA] sink.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] sink.c: latency = 0
D: [alsa-sink-bcm2835 ALSA] sink-input.c: Have to rewind 12972 bytes on render memblockq.
D: [alsa-sink-bcm2835 ALSA] source.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] protocol-native.c: Implicit underrun of 'pulse_out(liquidsoap:)'
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 632 bytes ago (14364 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 632 bytes ago (14364 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 632 bytes ago (12556 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 632 bytes ago (12556 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 632 bytes ago (10776 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 11208 bytes ago (7312 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 11208 bytes ago (7312 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 11208 bytes ago (244 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] sink.c: Found underrun 11208 bytes ago (244 bytes ahead in playback buffer)
D: [alsa-sink-bcm2835 ALSA] protocol-native.c: Requesting rewind due to end of underrun.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Requested to rewind 58840 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Limited to 12968 bytes.
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: before: 3242
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: after: 3242
D: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Rewound 12968 bytes.
D: [alsa-sink-bcm2835 ALSA] sink.c: Processing rewind...
D: [alsa-sink-bcm2835 ALSA] sink.c: latency = 11
D: [alsa-sink-bcm2835 ALSA] sink-input.c: Have to rewind 12968 bytes on render memblockq.
D: [alsa-sink-bcm2835 ALSA] source.c: Processing rewind...
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Decreasing wakeup watermark to 15.01 ms
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Decreasing wakeup watermark to 10.02 ms
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Decreasing wakeup watermark to 5.03 ms
I: [alsa-sink-bcm2835 ALSA] alsa-sink.c: Decreasing wakeup watermark to 3.99 ms
`
Here is the corresponding Liquidsoap log.
`
liquidsoap@audiobox:~ $ liquidsoap 'output.pulseaudio(mksafe(single("testing_venus.mp3")))'
2017/05/21 15:08:52 >>> LOG START
2017/05/21 15:08:50 [main:3] Liquidsoap 1.3.0
2017/05/21 15:08:50 [main:3] Using: bytes=[OCaml strictly before 4.02] pcre=7.2.3 dtools=0.3.3 duppy=0.6.0 duppy.syntax=0.6.0 cry=0.5.0 mm=0.3.0 mad=0.4.5 dynlink=[distributed with Ocaml] lame=0.3.3 alsa=0.2.3 taglib=0.3.3 camomile=0.8.5 pulseaudio=0.1.3
2017/05/21 15:08:50 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2017/05/21 15:08:52 [decoder:3] Method "MAD" accepted "testing_venus.mp3".
2017/05/21 15:08:52 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2017/05/21 15:08:52 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2017/05/21 15:08:52 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2017/05/21 15:08:52 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2017/05/21 15:08:52 [threads:3] Created thread "generic queue #1".
2017/05/21 15:08:52 [threads:3] Created thread "generic queue #2".
2017/05/21 15:08:52 [threads:3] Created thread "non-blocking queue #1".
2017/05/21 15:08:52 [threads:3] Created thread "non-blocking queue #2".
2017/05/21 15:08:52 [single_5777:3] "testing_venus.mp3" is static, resolving once for all...
2017/05/21 15:08:52 [single_5777:3] Prepared "testing_venus.mp3" (RID 0).
2017/05/21 15:08:52 [threads:3] Created thread "wallclock_pulse" (1 total).
2017/05/21 15:08:52 [clock.wallclock_pulse:3] Streaming loop starts, synchronized by active sources.
2017/05/21 15:08:52 [mksafe:3] Switch to single_5777.
^C2017/05/21 15:15:38 [main:3] Shutdown started!
2017/05/21 15:15:38 [main:3] Waiting for threads to terminate...
2017/05/21 15:16:00 [clock.wallclock_pulse:2] Source pulse_out(liquidsoap:) failed while streaming: Pulseaudio error: Connection terminated!
2017/05/21 15:16:00 [clock.wallclock_pulse:3] Called from file "outputs/output.ml", line 180, characters 6-27
2017/05/21 15:16:00 [clock.wallclock_pulse:3] Called from file "clock.ml", line 160, characters 17-25
2017/05/21 15:16:00 [single_5777:3] Finished with "testing_venus.mp3".
2017/05/21 15:16:00 [clock.wallclock_pulse:3] Streaming loop stopped.
2017/05/21 15:16:00 [threads:3] Thread "wallclock_pulse" terminated (0 remaining).
2017/05/21 15:16:00 [main:3] Threads terminated.
2017/05/21 15:16:00 [threads:3] Shutting down scheduler...
2017/05/21 15:16:00 [threads:3] Thread "generic queue #1" terminated.
2017/05/21 15:16:00 [threads:3] Scheduler shut down.
2017/05/21 15:16:00 [main:3] Cleaning downloaded files...
2017/05/21 15:16:00 [main:3] Freeing memory...
2017/05/21 15:16:01 >>> LOG END
liquidsoap@audiobox:~ $ 

`

**Comment by toots** [comment]
Hi!

Thanks for the report. Do you have any script that I could use to reproduce the issue?

**Comment by vrtisworks** [comment]
I didn't even use a 'script'.  Just a simple commandline.

`
liquidsoap 'output.pulseaudio(mksafe(single("testing_venus.mp3")))'

where testing_venus.mp3 is a local file. (I had to retype, so there might be a misspelling or syntax)

`

**Comment by toots** [comment]
Hi,

I just tested here but I cannot reproduce...

What device parameter are you using? Have you tried other values that the default there?

**Comment by vrtisworks** [comment]
Hi,

Thank you for checking.  Apparently there must be a problem with my current configuration.  I am using all the default values.  I will need to do some additional research and see if I can collect additional information.  I will not be able to do much for a few weeks, so if you want, you can close this, and I will reopen a problem when I get additional information.  Or you can just leave it open and I will post the new information when I get a chance.

**Comment by vrtisworks** [comment]
toots, Is liquidsoap actually producing float32le?  is there some way to get it to produce 16le?

Not sure I am even asking correctly.  Just trying to figure out more things to test.

Thanks.

**Comment by toots** [comment]
Hi @vrtisworks.

Yes, liquidsoap is sending float data to pulse audio. This is the internal format for us so it makes it more efficient to not have to convert back to s16le.

One thing you could try to isolate the problem further is try the simple noise example in the `ocaml-pulseaudio` binding: https://github.com/savonet/ocaml-pulseaudio/tree/master/examples/noise

**Comment by vrtisworks** [comment]
Hi @toots 

I tried liquidsoap 'output.pulseaudio(noise(duration=20.0))' and I get noise for as long as I want.

I tried a different mp3 file, and got the same results.  It plays about 4 seconds, and just hangs.  I cannot 'control-c' liquidsoap until I shut down pulseaudio.
liquidsoap 'output.pulseaudio(mksafe(single("testing_name.mp3")))' 

When I tried this without the mksafe, It plays about twice as long.  I do hear one or two 'clicks' or 'pauses' when it does play the extra music.  But I do not see anything in the liquidsoap log that said liquidsoap had a problem.
liquidsoap 'output.pulseaudio(single("testing_venus.mp3"))' 

I ran "TOP" while I was testing, and the CPU was only at about 30-50% while music was playing.  It dropped down to almost nothing when the music stopped.

**Comment by toots** [comment]
Hey!

Sorry, only getting back to this.

The fact that it works with `noise` but not a mp3 file seems quite suspicious. Once the file is decoded, there shouldn't be any difference between the noise audio data and the file's data.. 

Have you tried with a different audio format? And a different output, perhaps `output.alsa`?

**Comment by vrtisworks** [comment]
I guess we can close this.  The latest release of Raspian upgraded to Stretch, and eliminated pulseaudio.

We I am back to using ALSA to get to the Bluetooth headset.  That is a new set of problems, and I will open something about that in another thread.
