### ISSUE TITLE
Liquidsoap 1.3.0: the variable output.ao used here has not been previously defined.

### ISSUE THREAD

**Issue by itibet** [savonet/liquidsoap#445]
After updating to 1.3.0 my script issues the following error: `the variable output.ao used here has not been previously defined`.
However package `libao-dev` is installed in the system and `opam info ao` is successful as well (see below).
Does anybody have a solution?
Thank you

$ opam info ao
             package: ao
             version: 0.2.1
          repository: default
        upstream-url: https://github.com/savonet/ocaml-ao/releases/download/0.2.1/ocaml-ao-0.2.1.tar.gz
       upstream-kind: http
   upstream-checksum: 7f763e8c47e8369274ee400c640532d4
            homepage: https://github.com/savonet
              author: The Savonet Team <savonet-users@lists.sourceforge.net>
             depends: ocamlfind
   installed-version: 
  available-versions: 0.2.0, 0.2.1
         description: Bindings for the AO library which provides high-level functions for using soundcards

**Comment by gilou** [comment]
Did you recompile liquidsoap after installing ao ?
opam install liquidsoap will probably do it on its own if ao was updated/added though

**Comment by itibet** [comment]
Hi, yes! `opam install liquidsoap` recompiled liquidsoap with ao support.
Thanks!
