### ISSUE TITLE
List.hd odd behavior

### ISSUE THREAD

**Issue by naircl** [savonet/liquidsoap#448]
Hi;
I've been successfully running liquid soap+icecast2 on both an RPi2 and RPi3. Up until liquid soap 1.2.1, this code worked as expected:
 Idx = int_of_string(list.hd(get_process_lines("date +%-k")))
This correctly stores the current hour in idx as an int. As of 1.3.0, the return value is "\<fun\>" which I have no idea what it is and obviously is not what I expect. Qu'est çe qui se passe?

**Comment by vrtisworks** [comment]
Yes.  In 1.3, list.hd (and some of the other list. functions) have a default value that needs to be specified.  See the change log at [https://github.com/savonet/liquidsoap/releases/tag/1.3.0](url)

**Comment by hairmare** [comment]
FWIW, passing a default to `list.hd` for 1.3.0 would look as follows.
```
Idx = int_of_string(list.hd(default="",get_process_lines("date +%-k")))
```
The additional `default=""` in the `list.hd` call tells liquidsoap that this instance of the list function will return a string. That string can then be converted by `int_of_string`. Before 1.3.0 the list functions only worked on lists of strings, hence this change.

**Comment by smimram** [comment]
Thanks for explaining the problem!

**Comment by naircl** [comment]
No problem, I´ve already punished myself for not reading the changelog...

Nelson Saavedra Pinos
------------------------------------------------
nair.cl
gatoencerrado.cl
lagata.cl
imaginariocolectivo.info
------------------------------------------------
e: saavedra.nelson@gmail.com
c: +56 9 69074027
