### ISSUE TITLE
Liquidsoap 1.3.0: get_process_lines/get_process_output return empty result

### ISSUE THREAD

**Issue by itibet** [savonet/liquidsoap#449]
Hi,
in my script I get the list of files in a folder with `get_process_lines("ls path/to/folder")`, but with version 1.3.0 the returned list is always empty (the folder is not), also the following return empty strings: `get_process_output("ls")` and `get_process_output("cat path/to/file")`.
Are these apis broken in v1.3.0? Any workaround?
Thank you

**Comment by Jontyy** [comment]
https://github.com/savonet/liquidsoap/issues/439

**Comment by toots** [comment]
Yeah, this is fixed in `master` and also with the latest `1.3.0` in `opam`. Will push a bugfix release tomorrow.
