### ISSUE TITLE
less strict mp3 mime types?

### ISSUE THREAD

**Issue by mcfiredrill** [savonet/liquidsoap#451]
Hi I was wondering if there is a rationale to the only mime type for mp3 being "audio/mpeg".
https://github.com/savonet/liquidsoap/blob/11f8247fe5226e468180781e58adad7181b8f167/scripts/protocols.liq#L156

I often have files with mime type "audio/mp3", simply because its detected as such in Chrome and then uploaded to my server, then played in Liquidsoap.

I don't really know about the history of this choice or what the proper mime type is really supposed to be. If there is a preferred approach to this I'd like to hear it.

**Comment by mcfiredrill** [comment]
Maybe this is a bug in chrome... 🐛 
https://bugs.chromium.org/p/chromium/issues/detail?id=227004

**Comment by toots** [comment]
I don't think that it's a big deal to change it on our side. Just pushed the change.

**Comment by mcfiredrill** [comment]
Awesome!
