### ISSUE TITLE
ERROR while installing ogg.0.5.1

### ISSUE THREAD

**Issue by itibet** [savonet/liquidsoap#452]
Hi,
I'm trying to install liquidsoap on a Raspberry Pi 2 through opam, but it fails because the required package ogg fails to compile.
I've installed required dependencies throught depext, moreover I've got a Raspeberry Pi 3 where liquidsoap installed smoothly through opam.
Does anybody have any idea?
Thank you

`#=== ERROR while installing ogg.0.5.1 =========================================#`
`# opam-version 1.2.0`
`# os           linux`
`# command      make`
`# path         /home/pi/.opam/4.03.0/build/ogg.0.5.1`
`# compiler     4.03.0`
`# exit-code    2`
`# env-file     /home/pi/.opam/4.03.0/build/ogg.0.5.1/ogg-628-ad6566.env`
`# stdout-file  /home/pi/.opam/4.03.0/build/ogg.0.5.1/ogg-628-ad6566.out`
`# stderr-file  /home/pi/.opam/4.03.0/build/ogg.0.5.1/ogg-628-ad6566.err`
`### stdout ###`
`# ...[truncated]`
`# ocamlc.opt -c -g -w +A-4@5-7@8@11@12@20-35-44-45-50 -I /home/pi/.opam/4.03.0/lib/bytes` `ogg_demuxer.mli`
`# ocamlc.opt -c -g -w +A-4@5-7@8@11@12@20-35-44-45-50 -I /home/pi/.opam/4.03.0/lib/bytes` `ogg_demuxer.ml`
`# ocamlmklib    -I /home/pi/.opam/4.03.0/lib/bytes  -L/home/pi/.opam/4.03.0/lib   \`
`# 			-o ogg_stubs  ogg_stubs.o -logg  \`
`# 			`
`# OCamlMakefile:908: recipe for target 'dllogg_stubs.so' failed`
`# make[2]: Leaving directory '/home/pi/.opam/4.03.0/build/ogg.0.5.1/src'`
`# OCamlMakefile:736: recipe for target 'byte-code-library' failed`
`# make[1]: Leaving directory '/home/pi/.opam/4.03.0/build/ogg.0.5.1/src'`
`# Makefile:11: recipe for target 'all' failed`
`### stderr ###`
`# /usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libogg.so: file not recognized: File` `format not recognized`
`# collect2: error: ld returned 1 exit status`
`# make[2]: *** [dllogg_stubs.so] Error 2`
`# make[1]: *** [byte-code-library] Error 2`
`# make: *** [all] Error 2`

**Comment by toots** [comment]
Hmm. Thanks for the report. What do you see in debug:
```
opam install vorbis --verbose
```

**Comment by itibet** [comment]
The error has gone after switching to opam 4.04.1, I don't know what caused the error.
Thank you!
