### ISSUE TITLE
Variable source samplerate and output

### ISSUE THREAD

**Issue by austinsavage** [savonet/liquidsoap#455]
When sources are at a lower samplerate (22050Hz) than the icecast output (44100Hz), the audio is poor and clicking artifacts can be heard on the stream.

Outputting at a lower samplerate corrects this issue and the artifacts cannot be heard. How can I output 44100Hz with variable samplerate input sources?

**Comment by austinsavage** [comment]
I am normalizing sample rates by re-encoding the files using ffmpeg to work around this limitation.

**Comment by smimram** [comment]
I'm glad you found a way to fix this, but actually Liquidsoap should properly take care of this. I'm reopening so that we can investigate.

**Comment by toots** [comment]
Hi @austinsavage !

Did you install the `samplerate` binding?
```
opam install samplerate
```

Once installed, liquidsoap should be using this library for up and down sampling. Furthermore, you can use the settings to adjust which resampling method/algorithm is being used:
> Libsamplerate conversion settings
> 
> Resampling quality
> Default: "fast"
> 
> set("audio.converter.samplerate.libsamplerate.quality","fast")
>
> Resampling quality, one of: “best”, “medium”, “fast”, “zero_order”, “linear”. Refer to ocaml-samplerate for details.

**Comment by toots** [comment]
I'm closing this one as I believe it should be working with `libsamplerate`. Please re-open if needed. Thanks!

**Comment by austinsavage** [comment]
@toots you were right, this running `opam install samplerate` does fix the symptoms I was having.

**Comment by toots** [comment]
Cool, thanks for letting us know. I've added `samplerate` in the OPAM install instructions.
