### ISSUE TITLE
Handle mime-type arguments

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#456]
Per `savonet-users`:

> The following error occurs several times in the log when I try to connect to an input.harbor in Liquidsoap:
> 2017/06/14 23:49:08 [decoder:3] Unable to decode stream of type "audio/ogg; codecs=opus"!

**Comment by codeofdusk** [comment]
Thanks for fixing! When can we see this in a released version?

**Comment by toots** [comment]
Will probably do another small release in the next months or so.
