### ISSUE TITLE
Opus fails to decode

### ISSUE THREAD

**Issue by codeofdusk** [savonet/liquidsoap#457]
>>
[testing.opus.zip](https://github.com/savonet/liquidsoap/files/1082265/testing.opus.zip)

 2017/06/17 02:52:39 [decoder:3] Method "OGG" accepted "audio/ogg; codecs=opus".
>> 2017/06/17 02:52:39 [threads:3] Created thread "harbor source feeding" (3 total).
>> 2017/06/17 02:52:39 [input(dot)harbor_6175:3] Decoding...
>> 2017/06/17 02:52:40 [input(dot)harbor_6175:2] Feeding stopped: Failure("Ogg stream does not contain required data").
>> 2017/06/17 02:52:40 [threads:3] Thread "harbor source feeding" terminated (2 remaining).
>> 2017/06/17 02:52:41 [decoder:3] Method "OGG" accepted "audio/ogg; codecs=opus".
>> 2017/06/17 02:52:41 [threads:3] Created thread "harbor source feeding" (3 total).
>> 2017/06/17 02:52:41 [input(dot)harbor_6175:3] Decoding...
>> 2017/06/17 02:52:42 [input(dot)harbor_6175:2] Feeding stopped: Ogg_demuxer.Invalid_stream.
>> 2017/06/17 02:52:42 [threads:3] Thread "harbor source feeding" terminated (2 remaining).
>> 2017/06/17 02:52:43 [decoder:3] Method "OGG" accepted "audio/ogg; codecs=opus".
>> 2017/06/17 02:52:43 [threads:3] Created thread "harbor source feeding" (3 total).
>> 2017/06/17 02:52:43 [input(dot)harbor_6175:3] Decoding...
>> 2017/06/17 02:52:44 [input(dot)harbor_6175:2] Feeding stopped: Ogg_demuxer.Invalid_stream.
>> 2017/06/17 02:52:44 [threads:3] Thread "harbor source feeding" terminated (2 remaining).
>> 2017/06/17 02:52:45 [decoder:3] Method "OGG" accepted "audio/ogg; codecs=opus".
>> 2017/06/17 02:52:45 [threads:3] Created thread "harbor source feeding" (3 total).
>> 2017/06/17 02:52:45 [input(dot)harbor_6175:3] Decoding...
>> 2017/06/17 02:52:46 [input(dot)harbor_6175:2] Feeding stopped: Ogg_demuxer.Invalid_stream.
>> 2017/06/17 02:52:46 [threads:3] Thread "harbor source feeding" terminated (2 remaining).
>> 2017/06/17 02:52:48 [decoder:3] Method "OGG" accepted "audio/ogg; codecs=opus".
>> 2017/06/17 02:52:48 [threads:3] Created thread "harbor source feeding" (3 total).
>> 2017/06/17 02:52:48 [input(dot)harbor_6175:3] Decoding...
>> 2017/06/17 02:52:49 [input(dot)harbor_6175:2] Feeding stopped: Ogg_demuxer.Invalid_stream.
>> 2017/06/17 02:52:49 [threads:3] Thread "harbor source feeding" terminated (2 remaining).

I've attached a test stream generated by the client. It's Ladiocast running on MacOS.

**Comment by toots** [comment]
Did you install the `opus` binding:
```
opam install opus
```
?

**Comment by codeofdusk** [comment]
Yes.

Bill

**Comment by toots** [comment]
Ok. Any change you'd have a longer stream to share? The one you attached only has the first two packets..

**Comment by codeofdusk** [comment]
Hmmm, that’s strange.

Bill

**Comment by toots** [comment]
```
% oggz-dump -x testing.opus
00:00:00.000: serialno 18446744072095340169, granulepos 0, packetno 0 *** bos: 19 bytes
    0000: 6050 6294 ff7f 0000 0000 00c2 0000 0000  `Pb.............
    0010: 0000 00                                  ...

00:00:00.000: serialno 18446744072095340169, granulepos 0, packetno 1: 110 bytes
    0000: 4f70 7573 5461 6773 1000 0000 4c61 6469  OpusTags....Ladi
    0010: 6f43 6173 7420 302e 3132 2e30 0400 0000  oCast 0.12.0....
    0020: 1200 0000 5449 544c 453d 4e36 204f 7075  ....TITLE=N6 Opu
    0030: 7320 5465 7374 0c00 0000 4745 4e52 453d  s Test ...GENRE=
    0040: 286e 756c 6c29 1200 0000 4445 5343 5249  (null)....DESCRI
    0050: 5054 494f 4e3d 286e 756c 6c29 0e00 0000  PTION=(null)....
    0060: 434f 4e54 4143 543d 286e 756c 6c29       CONTACT=(null)
```

**Comment by toots** [comment]
```
% oggz-info testing.opus
Content-Duration: 00:00:00.000

Unknown: serialno 18446744072095340169
	2 packets in 216 pages, 0.0 packets/page, 1.216% Ogg overhead
```

**Comment by toots** [comment]
Any news on this one?

**Comment by codeofdusk** [comment]
Something's definitely up with the client, as attempting to play the resulting stream with VLC doesn't seem to work either. If anyone else wants to test this, it's Ladiocast for Mac (available in the appStore). I'm capturing the stream with wget to post here.

**Comment by toots** [comment]
Ok, thanks. I'm closing this one for now, please re-open when needed!
