### ISSUE TITLE
Strange error "Error while processing request: Http.Unix_transport.Socket"

### ISSUE THREAD

**Issue by albertosgr** [savonet/liquidsoap#458]
Hi all.

I have this code:

```
def requestTracks() =
	lines = http.get( headers=[], config.apiUrl ^ "/getNextTrackForLS" )
	body = snd(lines)
	log(level=1,"Got answer: #{body}")
        request.create(body)
end
```
the response is something like this:

`annotate:length="349.83",title="Title",artist="Artist":/somePath/track_3061.mp3`

in plain text. this part is working fine, but after a couple of days I get this error that I cant find anything related to it.

**Error while processing request: Http.Unix_transport.Socket**

after this, all requests all failing with the same error. LS is 1.3.1 from opam repos.

Does anyone can guide me on how to resolve this?

**Comment by toots** [comment]
Hi,

My first instinct would be to look for a FD leak. Could you see the list of sockets opened by liquidsoap when that happens? You can do:
```
lsof | grep liquidsoap
```

**Comment by toots** [comment]
Any news on this one?

**Comment by albertosgr** [comment]
Hi toots.

No I switched to command fetch (using curl) and I also compiled against the latest version (I think 4.04) and everything seems fine. Cant replicate this for now, but I will try it again some time in the future.

**Comment by toots** [comment]
Cool, thanks for the feedback! I'm gonna close this one for now, please re-open or fill a new one if you see errors in the future.
