### ISSUE TITLE
can't use single() to play most video extensions

### ISSUE THREAD

**Issue by xorinzor** [savonet/liquidsoap#459]
I can't use `single()` to play most video extensions (such as avi, webm, mp4, mov, etc). (It however does work with `ogv`).

Whereas using `input.gstreamer.video(pipeline='filesrc location="myvideo.avi" ! decodebin ! videoconvert')` does work.

Perhaps also worth noting, adding `! videosink` to the end of the pipeline causes these errors to appear:

```
GST_PIPELINE grammar.y:642:gst_parse_perform_link: could not link autovideosink0 to decodebin0
GST_PIPELINE grammar.y:642:gst_parse_perform_link: could not link autovideosink1 to decodebin1
GST_PIPELINE grammar.y:642:gst_parse_perform_link: could not link autovideosink2 to decodebin2
GST_PIPELINE grammar.y:642:gst_parse_perform_link: could not link autovideosink3 to decodebin3
etc.
```

What is preventing me here from using `single()` ?

Running Ubuntu 17.04 with gstreamer-1.0

**Comment by toots** [comment]
I think you need to install more `gstreamer` plugins.
