### ISSUE TITLE
[clock.wallclock_main:2] Too much latency! Resetting active sources...

### ISSUE THREAD

**Issue by crmb** [savonet/liquidsoap#463]
Hello

I am using liquidsoap and icecast (administred by "Centovacast" CP) with 5 mount points.
Liquidsoap is randomly reseting (every 14-24 hours). Here is the log:
(CPU usage is around 50-60%. I didn't notice anything unusual during the problem)
```
10:21:33 [replaygain:3] Overriding amplification: 0.882064.
10:21:33 [source:4] Garbage collected add_13836.
10:21:33 [source:4] Garbage collected buffer_13835.
10:21:48 [output_streammp3--priv_autodj:3] Metadata update may have failed with error: could not read data from host: Connection reset by peer in read()
(...)
10:22:48 [output_stream-AAC-Chill_autodj:3] Metadata update may have failed with error: could not read data from host: Connection reset by peer in read()
10:22:48 [clock.wallclock_main:2] Too much latency! Resetting active sources...
10:22:48 [output_streammp3--priv_autodj:3] Closing connection...
10:22:48 [output_streammp3--priv_autodj:3] Connecting mount streammp3--priv_autodj for source@149.202.XXX.XXX...
10:22:48 [output_streammp3--priv_autodj:3] Connection setup was successful.
(...)
10:22:48 [output_stream-AAC-Chill_autodj:3] Closing connection...
10:22:48 [output_stream-AAC-Chill_autodj:3] Connecting mount stream-AAC-Chill_autodj for source@149.202.XXX.XXX...
10:22:48 [output_stream-AAC-Chill_autodj:3] Connection setup was successful.
10:22:53 [buffer_13849:4] End of track.
10:22:53 [buffer_13849:4] Buffer emptied, buffering needed.
10:22:54 [normal_crossfade:4] Buffering end of track...
10:22:54 [normal_crossfade:4] More buffering will be needed.
10:26:58 [lang:3] #### fetching http://127.0.0.1:2199/nextsong.php?username=chillout&secret=8a6b7e8afd3908fa76526cb41f23ebc8
10:26:58 [http.get:4] No network activity for 1.00 second(s).
10:26:59 [lang:3] #### nextsong: got code 200
```
I though it may be related to issue #377 and applied patch https://github.com/savonet/liquidsoap/commit/e58ab2ded2fadafee3e1131ec128f2f885eac3b8 on my 1.2.1

But no change.
I don't understand the "Connection reset y peer" from icecast

**Comment by crmb** [comment]
I have tried changing the various icecast timeout settings, and message is now : 

05:20:36 [output_streammp3--priv_autodj:3] Metadata update may have failed with error: Cry.Timeout
05:21:07 [output_stream64k-AAC-Deep_autodj:3] Metadata update may have failed with error: Cry.Timeout
05:21:37 [output_stream--priv_autodj:3] Metadata update may have failed with error: Cry.Timeout
05:22:07 [output_stream-mp3-Deep_autodj:3] Metadata update may have failed with error: Cry.Timeout
05:22:37 [output_stream-AAC-Deep_autodj:3] Metadata update may have failed with error: Cry.Timeout
05:22:37 [clock.wallclock_main:2] Too much latency! Resetting active sources...

**Comment by toots** [comment]
Hi,

There could be many reasons for this issue. One that seems quite possible is a network reset somewhere in your setup. Do you have a dynamic IP or a static IP? Both messages seem to be related to temporary network failures, all happening at the same time..

**Comment by crmb** [comment]
I have others liquidsoap+icecast process running (the server run several radio stations) but they won't encounter the issue at the same time. 

For exemple, one got the issue few hours ago. But another one is running OK since 3 days. (But will most likely encounter the issue at some point).

Server (everything run on the same server) is cloud server with static IP. ("ovh public cloud")

**Comment by toots** [comment]
These errors can be tricky and also possibly come from the server.

One thing you might want to try to mitigate is to isolate the `output.icecast` outputs from the main clock so the whole streaming doesn't reset when one such output is stuck.

The documentation has some information about it here: http://liquidsoap.fm/doc-1.3.1/clocks.html

Looks like this:
```
icecast_outouts = [output_1, output_2, ...]

clock.assign_new(id="icecast",icecast_outouts)
```
Depending on how complex your script is, this may or may not help or be needed but if, for instance, you use live audio input or file output, this would definitely help.

**Comment by crmb** [comment]
Thank you.
I think the script is quite complicated (generated by Centova Cast). I will talk to them about it but it seems we are the only client encoutering the issue.
I made a new installation on another server (a physical server, not a VM) and the same thing happen.

**Comment by scysys** [comment]
@crmb Did you solved it? Same problem on some installations

**Comment by crmb** [comment]
**Regarding this specific issue :** (Cry Timeout / metadata update issue)
I had the same problem trying on a physical server, so it was not some kind of network/socket lag on the cloud instance.
CentovaCast team said bogus mp3 could cause issues. My client retagged all his mp3 (and maybe re-encoded some) and his stations run (almost) flawlessly since. (with around 3000 listeners on several streams for this server). Total CPU usage is around 60% average.

**Another issue :** 
However, another person has a station with very huge/fast variations of listeners (not sure what he is doing exactly) and the station (and others stations on the same server) were restarting and restarting.. connection timeout / reset by peer / We must catchup XX seconds (we've been late for 100 rounds) .... 
in liquidsoap logs. Despite the server beeing quite powerfull.
Yet again this is another cloud server from another hosting company and i will try to switch at some point.
I don't see how liquidsoap/icecast can be laggy if there is still like 50% cpu available

First thing is check if you see the same track coming during the various timeout, and to try retag/rencode it.
