### ISSUE TITLE
Handle URI scheme in case-insensitive way

### ISSUE THREAD

**Issue by mpbraendli** [savonet/liquidsoap#464]
Dear Liquidsoap devs,

HTTP URLs are matched against a regex in a case sensitive way in the file
https://github.com/savonet/liquidsoap/blob/master/src/sources/http_source.ml#L147

According to https://tools.ietf.org/html/rfc3986#section-3.1 this should also accept HTTP and other capitalisation:

>  Although schemes are case-
>    insensitive, the canonical form is lowercase and documents that
>    specify schemes must do so with lowercase letters.  An implementation
>    should accept uppercase letters as equivalent to lowercase in scheme
>    names (e.g., allow "HTTP" as well as "http") for the sake of
>    robustness but should only produce lowercase scheme names for
>    consistency.

With my rudimentary OCaml knowledge, it seems that using `Str.regexp_case_fold` instead of `Str.regexp` would suffice. Otherwise
`let url_expr = Str.regexp "^[Hh][Tt][Tt][Pp]://\\([^/]+\\)\\(/.*\\)?$"`
would do it.

Thanks,
mpb

**Comment by toots** [comment]
Thanks for reporting!
