### ISSUE TITLE
Manually update metadata on song change

### ISSUE THREAD

**Issue by kernelpanic3** [savonet/liquidsoap#468]
Hi,

I have a bit of an interesting niche case here. I'm trying to set up a simple automated station (no need to go live or anything fancy like that), but with a twist: before it goes to Icecast, the stream runs through one of these guys:

![Vintage Emergency Alert System encoder.](https://upload.wikimedia.org/wikipedia/en/2/2b/Sage_EAS_Endec.jpg)

This necessitates outputting over ALSA so I can run the audio to the machine's input - but at the end of the chain, I still have an Icecast stream that needs metadata, which needless to say the device can't pass through. I've run through the documentation a few times but I haven't found anything that could help, so I figured I'd ask here - is there some way I might be able to manually update the metadata of a _separate_ Icecast stream when the song changes?

Thanks in advance!

**Comment by hairmare** [comment]
Icecast has an [endpoint for updating the metadata](http://icecast.org/docs/icecast-2.4.1/admin-interface.html#metadata-update) over HTTP. I think you can call that directly using [`http.get`](http://savonet.sourceforge.net/doc-svn/reference.html#http_get) to send metadata directly to the stream.

**Comment by kernelpanic3** [comment]
@hairmare That sounds like it would solve half of my problem, but how would I pass the metadata unaltered? I don't need to rewrite the string at all, just pass it along. (Sorry if I sound utterly clueless, I know my way around scripting but this is my first time with Liquidsoap...)

**Comment by toots** [comment]
This is a tricky thing to do. We've added a `pipe` operator recently that might be able to help. Using it, you can pipe audio data through an external program. Metadata is synchronized with the output stream from the program this way: at each metadata, the external program is stopped, all remaining data is flushed out and the metadata is then added. That's the only way to deal with the necessary buffering that happens.

In your case, you might be able to use `pipe` with an external program that writes and reads to a sound card. And that external program can actually be written using liquidsoap. Something along these lines:
```
#!/usr/bin/env liquidsoap

# Fetch audio from stdin
s = input.external("cat")
# Send to sound card
output.alsa(s)

# Fetch from sound card
s = input.alsa(...)
# Send to stdout
output.external("cat",s)
```

**Comment by toots** [comment]
A fully functional script maybe a bit more tricky to write, though. You could also just write your own using a different language. I'll get back to this.

**Comment by smimram** [comment]
It seems that this was answered by @toots, closing. Feel free to reopen if there are further questions.
