### ISSUE TITLE
Issue with creating a playlist with annotate inside

### ISSUE THREAD

**Issue by stlpedro** [savonet/liquidsoap#470]
Guys,
 
This must it have been asked a million times but I’m looking for a way to load a playlist that would have start time and end time of each clip something like.
 
Playlist.txt (this is the file inside of ./playout)
annotate:liq_cue_in=10.,liq_cue_out=45:content/vid1.mp4
 
My script is…
 
# Standard settings
 
set("log.file",true)
set("log.file.path","/data/logs/liquidsoap.log")
#set("init.daemon",true)
#set("init.daemon.change_user",true)
#set("init.daemon.change_user.group","audio")
#set("init.daemon.change_user.user","liquidsoap")
#set("init.daemon.pidfile",true)
#set("init.daemon.pidfile.path","/data/run/liquidsoap.pid")
 
set("log.level",4)
 
 
set("frame.video.width",                 1280)
set("frame.video.height",                                720)
set("frame.video.samplerate",       25)
set("gstreamer.add_borders",       false)
 
s = playlist.safe("playout/pl1.txt",reload_mode="watch", mode="normal")
 
s = cue_cut(s)
 
s = fallback([s, blank()])
 
def log_arg(x) =
     label = fst(x)
     value = snd(x)
     log(level=4,"  #{label}: #{value}")
end
 
def append_title(m) =
  # Grab the current title
  title = m["title"]
 
  list.iter(log_arg,m)
 
  # Return a new title metadata
  [("title","#{title} - www.station.com")]
end
 
s = map_metadata(append_title, s)
 
  output.gstreamer.audio_video(
  video_pipeline=
    "videoconvert ! x264enc bitrate=2000 ! video/x-h264,profile=baseline ! queue ! mux.",
  audio_pipeline=
    "audioconvert ! voaacenc bitrate=128000 ! queue ! mux.",
  pipeline=
    "flvmux name=mux ! rtmpsink location=\"rtmp://localhost:1935/mytv/live live=1\"",
  s)
 
This does not work since it tells me that the playlist is empty or invalid.
 
Is there a way to note the start and end time of a video clip in the playlist?
 
Please help!

**Comment by toots** [comment]
Hey,

Do you have logs? My guess is that you should use `playlist` instead of `playlist.safe`. `annotate` URIs are not considered `static` so the playlist wouldn't be considered infallible..
