### ISSUE TITLE
High CPU Usage after upgrade to 1.3.1

### ISSUE THREAD

**Issue by jdbuys** [savonet/liquidsoap#475]
Hi,

I recently upgraded from 1.2.1 to 1.3.1. 
The problem is that the cpu % for the Liquidsoap process went from 2% to 180%. 
This specifically happens when a song uses an external decoder like ffmpeg or faad.

Here's my script, which is a very simple script just streaming to an icecast server with a cusom ffmpeg decoder.

To reproduce: 

- Run the script with 1.3.1 and put a file in the playlist that will be decoded by the custom ffmpeg decoder

``` #!/usr/local/bin/liquidsoap
set("log.file.path","radio.log")
set("log.stdout", true)
set("server.telnet",false)
set("server.socket",true)
set("server.socket.path","lsoap.sock")
set("server.socket.permissions",511)
set("server.timeout",20.)
set("log.level",8)

#Add ffmpeg
def test_ffmpeg(file) = -1 end
ffmpeg_p = "/usr/local/bin/ffmpeg -i - -f wav -"
add_decoder(name="FFMPEG",description="Decode files using the ffmpeg decoder binary",mimes=["video/x-ms-asf","audio/aacp","application/octet-stream","audio/x-wav"],test=test_ffmpeg,ffmpeg_p)

source=fallback(track_sensitive=false,[playlist("/tmp/playlist.pls"),request.queue(id="queue",length=10.0),request.equeue(id="equeue")])
source=mksafe(source)
add_skip_command(source)
source=audio_to_stereo(id="source",source)


output.icecast(%mp3(stereo=true,bitrate=64,samplerate=44100),id="icecast",host="127.0.0.1",port=80,user="source",password="hackme",fallible=true,name="ffmpegtest",mount="ffmpegtest",source)
```
Any help would be appreciated.

**Comment by toots** [comment]
Thanks for the report. I'll investigate ASAP.

**Comment by toots** [comment]
Ok, it should be fixed. Glad you pointed out to this issue. The component responsible for it is pretty important so I'm gonna wait a couple of days to see if anything else is reported but you can expect a release with this fix pretty soon.

**Comment by jdbuys** [comment]
Thank you very much! 
I will make a new build from source and test it.
