### ISSUE TITLE
User merge_tracks to play instant jingles

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#476]
I would like to be able to play some tracks at any time, like https://www.youtube.com/watch?v=6zXDo4dL7SU. I tried `merge_tracks(request.queue(id="instant_tracks"))`, but it seems to play them sequentially. What did I do wrong?

**Comment by toots** [comment]
Hi

Not sure I follow what you are trying to do :-)

**Comment by Yamakaky** [comment]
I want to be able to start multiple tracks at any time, like https://www.youtube.com/watch?v=6zXDo4dL7SU.

**Comment by chrispolley** [comment]
Do you mean you want to merge audio sources onto another, using real-time commands, mimicking pushing buttons on a soundboard to insert sound effects (e.g. https://www.youtube.com/watch?v=KLANLzerfa0)?

Or do you want to overlay another track on a scheduled basis?  For that, I would do:
`# insert station IDs at xx:59:45 over then-playing content
normal_ids  = audio_to_stereo( id="id_normal", playlist (id="id_playlist", mode="random", reload_mode="watch", "/var/audio/IDs/"))

feed_main = audio_to_stereo(## your main input.source e.g. input.http, playlist, etc ##)

combined_out  = smooth_add(
        normal=feed_main,
        p=0.30,
        special=switch([
        ( { 59m45s }, normal_ids )
        ])
)
`
This ducks your `feed_main` source to 30% and overlays the ID/jingle at the specified time.

**Comment by Yamakaky** [comment]
Yes, exactly like in your video!

**Comment by tekaymedia** [comment]
Hey @chrispolley – do you have an idea how to instantly overlay a track (not on a scheduled basis)? Would love to do the same like @Yamakaky intended to achieve! Thank you!

**Comment by chrispolley** [comment]
I guess what I would try is to set up a request queue as in the cookbook
at  https://www.liquidsoap.info/doc-1.4.0/request_sources.html.

Then I would smooth_add them together. You may want to look at tuning the
delay and p arguments to your liking.

I think the hard part would be triggering the sfx in a low-latency way,
since you need to send the queue request, and liquidsoap then needs to
queue it and then play it.

**Comment by smimram** [comment]
I have just added `request.player` which plays requests immediately (and multiple ones can be played so that you avoid the `request.queue` problem).

**Comment by rrolla** [comment]
@smimram you added on commit https://github.com/savonet/liquidsoap/commit/e6ceb477b31aa8e63f318c7bf815997b6d94043c example:

A source which plays requests immediately. For instance

```
s = request.player()
def note()
  r = "synth:frequency=#{random.float(min=200.,max=800.)},duration=#{random.float(min=2.,max=6.)}"
  log.important("Playing #{r}")
  r
end
thread.run(every={random.float(min=0.,max=2.)}, {s.play(request.create(note()))})
output(s)
```

But in this above example is just one source, my question is it possible to do like this
```
source               [=================]
request.player         [===]      [==]
```

eg play over source immediately when i call `request.player().play()`

**Comment by smimram** [comment]
You should simply add the two, something like this:
```
s = source...
r = request.player()
o = add(normalize=false, [r,s])

output(o)
```

**Comment by rrolla** [comment]
> You should simply add the two, something like this:
> 
> ```
> s = source...
> r = request.player()
> o = add(normalize=false, [r,s])
> 
> output(o)
> ```

Thanks will try
