### ISSUE TITLE
Segfault in audio_to_stereo of playlist

### ISSUE THREAD

**Issue by chrispolley** [savonet/liquidsoap#477]
Hi,
I am using  the debain/stretch dist of liquidsoap (package version 1.1.1-7.2 containing liquidsoap 1.1.1; libogg0 package version 1.3.2-1 containing libogg.so.0.8.2) 

Folder /var/audio/ID-15 contains a collection of mono MP3s.  In isolating this issue I converted these to wav and put them in the folder /var/audio/ID-15-wav

When I run the following test file, it generates a segfault:
`segfault at 4004f20 ip 00007f091ccaa049 sp 00007f0912f4e9d8 error 6 in libogg.so.0.8.2[7f091ccaa000+7000]`

```
#!/usr/bin/liquidsoap

pl =  audio_to_stereo(playlist (mode="random", reload_mode="watch", "/var/audio/ID-15"))
output.dummy(fallible=true, pl)

```

however the following file runs fine

```
#!/usr/bin/liquidsoap


pl =  audio_to_stereo(playlist (mode="random", reload_mode="watch", "/var/audio/ID-15-wav"))
output.dummy(fallible=true, pl)
```
The only difference is that the playlist contents are in one case mono mp3 and in the other mono wav files.

Using the playlist without audio_to_stereo works OK, but I need these as stereo sources in my actual application.

I can workaround with these short (15-second) files, but for longer-format material the wav files' size would quickly add up.

Thanks for any help!

**Comment by toots** [comment]
Hi @chrispolley 

Any chance you could try this issue with a recent release? `1.1.1` is very old now and I'm not sure that it'll be possible to track this bug across such code-change..

**Comment by toots** [comment]
I'm closing this as a mean to keep track of pending issues on the current code. Please, re-open if you can confirm it with a recent version, I'd be glad to look at it.

**Comment by chrispolley** [comment]
Thanks. Is a more recent release in the debian distribution or packaged
somewhere?

**Comment by toots** [comment]
You would have to use `opam` or compile by hand. `opam` has a small learning curve but once you're familiar with it, it makes it very convenient to install `liquidsoap` and its dependencies.
