### ISSUE TITLE
Fade duration via metadata issue

### ISSUE THREAD

**Issue by jdbuys** [savonet/liquidsoap#480]
Hi,
I saw that you guys did work on the fade component and I just want to find out what the correct / expected behaviour is. Specifically with regards to the duration meta override.

Before my upgrade from LS 1.2.1 to 1.3.2 the metadata override had to be set after each track if I wanted to change the fade duration. 
But now if I set the fade duration via the metadata it is retained for every song.

Is this the way it should work? 
If it is, is there a setting to disable that or do I just have to redesign the fade duration override on my end?

Thanks

**Comment by toots** [comment]
Hi @jdbuys,

I wasn't aware of this behavior before rewriting those operators. The behavior now is: metadata override are permanent until another metadata comes along.

A quick way to get the old behavior back could be to use the `on_metadata` operator. Something like this:
```
def default_fade_values(m) =
  # Set default fade_in if not present
  m =
    if m["liq_fade_in"] == "" then
      list.add(("liq_fade_in",<default value>),m)
    else
      m
   end
   # Same for duration override
end

source = map_metadata(default_fade_values,source)
```

**Comment by jdbuys** [comment]
Thanks!!

**Comment by walterdevos** [comment]
Doesn't work:
list.add(("liq_fade_in",1.0),m)
this value has type
 [(_*string)] (inferred at line 85, char 9)
but it should be a subtype of
 [(_*float)]

changing the line to 
list.add(("liq_fade_in","1.0"),m)
this value has type
 (...)->unit (inferred at line 82 char 1 - line 91 char 3)
but it should be a subtype of
(...)->[_]


**context:**
security = single("/var/radio/muziek/hr-id/00353-.mp3")

radio = fallback(track_sensitive = false, [radio, security])

def default_fade_values(m) =
  # Set default fade_in if not present
  m =
    if m["liq_start_next"] == "" then
      list.add(("liq_start_next","2.5"),m)
    else
      m
    end
   # Same for duration override
end

radio = map_metadata(default_fade_values,radio)

radio = crossfade(start_next=2.5,fade_out=1.0,fade_in=0.5,radio)

**Comment by walterdevos** [comment]
That won't work. It returns a empty value (unit)

You need to return the metadata.

`def default_fade_values(m) =
  # Set default fade_in if not present
  m =
    if m["liq_start_next"] == "" then
      log(level=4,"fade start next was empty")
      list.add(("liq_start_next",**<default value FLOAT notation in "quotes" ex."2.5">**),m)
    else
      value = m["liq_start_next"]
      log(level=4,"fade start next has a value #{value}")
      m
    end
   **m**
end`

That's still a bit flaky, but it works.
