### ISSUE TITLE
Playlist by day of month or expand hour time interval

### ISSUE THREAD

**Issue by amavarick** [savonet/liquidsoap#481]
**Please expand your time interval to include d = day.**

I have a station that I need to play a certain thing each day of the month.  Calling an external function within the liq script exceeds my capabilities.

**If adding d = day to the time interval is too involved, would you consider instead expanding h from the 23 hour limit to 744 hours?**

This would allow me to create a script that can run monthly and define them within each 24 hour day.  I can then use a cron job to stop and start the script once a month.

Thank you for your time...

**Comment by toots** [comment]
That's an interesting feat. will look at it!

**Comment by amavarick** [comment]
Awesome!  That would be exciting if it is able to be integrated.

**Comment by toots** [comment]
Ok, so it was a little too tricky. I don't think we should change the time predicates at this point. However, I've added a lil something that should help you. See this:
```
# Returns true if current time is 12th of April:
def april_12() =
  localtime(time(), fun (~sec,~min,~hour,~mday,~mon,~year,~wday,~yday,~isdst) ->
    mday == 12 and mon == 3) # These are POSIX standards, mon: month of year [0,11]
end
```
