### ISSUE TITLE
During live streaming - Harbor, the stream is interrupted by the playlist.

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#486]
I connect using harbor to live broadcast. Unfortunately, it is very common for liquidsoap to break the harbor connection for a few seconds and play a song from the playlist.

This is not a problem with the server and the internet connection.

Please see how it looks in the logs (last lines) - look at 22:01:17:

> 2017/09/29 22:25:27 [clock.wallclock_main:2] We must catchup 2.24 seconds!
> 2017/09/29 22:25:25 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 22:25:24 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 22:25:24 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 22:25:23 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 22:20:44 [clock.wallclock_main:2] We must catchup 2.39 seconds!
> 2017/09/29 22:20:06 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 22:20:05 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 22:20:05 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 22:20:04 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 22:15:22 [clock.wallclock_main:2] We must catchup 1.50 seconds!
> 2017/09/29 22:14:25 [clock.wallclock_main:2] We must catchup 1.32 seconds!
> 2017/09/29 22:10:25 [clock.wallclock_main:2] We must catchup 1.96 seconds!
> 2017/09/29 22:09:48 [clock.wallclock_main:2] We must catchup 1.94 seconds!
> 2017/09/29 22:09:46 [clock.wallclock_main:2] We must catchup 1.02 seconds!
> 2017/09/29 22:06:22 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 22:06:21 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 22:06:21 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 22:06:19 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 22:06:17 [clock.wallclock_main:2] We must catchup 1.66 seconds!
> 2017/09/29 22:04:45 [clock.wallclock_main:2] We must catchup 1.03 seconds!
> 2017/09/29 22:04:11 [clock.wallclock_main:2] We must catchup 1.62 seconds!
> 2017/09/29 22:04:03 [clock.wallclock_main:2] We must catchup 2.87 seconds!
> 2017/09/29 22:04:02 [clock.wallclock_main:2] We must catchup 3.07 seconds!
> 2017/09/29 22:02:58 [clock.wallclock_main:2] We must catchup 1.10 seconds!
> 2017/09/29 22:02:08 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 22:02:07 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 22:02:07 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 22:02:06 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 22:01:20 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 22:01:19 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 22:01:19 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 22:01:17 [input(dot)harbor_6110:3] Decoding...
> 2017/09/29 22:01:17 [threads:3] Created thread "harbor source feeding" (2 total).
> 2017/09/29 22:01:17 [decoder:3] Method "MAD" accepted "audio/mpeg".
> 2017/09/29 22:01:17 [threads:3] Thread "harbor source feeding" terminated (1 remaining).
> 2017/09/29 22:01:17 [input(dot)harbor_6110:2] Feeding stopped: Mad.End_of_stream.
> 2017/09/29 22:01:16 [mksafe:3] Switch to audio_to_stereo_6127.
> 2017/09/29 22:01:16 [switch_6134:3] Switch to mksafe with transition.
> 2017/09/29 22:01:16 [90743(dot)m3u:3] Prepared "/home/liquidsoap/mp3/Luis_Fonsi-Despacito.mp3" (RID 8).
> 2017/09/29 22:01:16 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 21:58:55 [clock.wallclock_main:2] We must catchup 1.92 seconds!
> 2017/09/29 21:58:13 [clock.wallclock_main:2] We must catchup 1.09 seconds!
> 2017/09/29 21:57:37 [input(dot)harbor_6110:3] New metadata chunk ? -- Adele - Hello
> 2017/09/29 21:57:12 [clock.wallclock_main:2] We must catchup 1.51 seconds!
> 2017/09/29 21:53:26 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 21:53:25 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 21:53:24 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 21:53:22 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 21:52:06 [clock.wallclock_main:2] We must catchup 2.06 seconds!

Another logs - about play one-two seconds playlist file when I live stream by harbor (look: 23:50:26, 23:42:34):

> 2017/09/29 23:53:34 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:53:33 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:53:33 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:53:32 [clock.wallclock_main:2] We must catchup 2.14 seconds!
> 2017/09/29 23:53:30 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:50:26 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:50:26 [90743(dot)m3u:3] Prepared "/home/liquidsoap/mp3/ClubDance/Bruno Mars - Locked Out Of Heaven (Sultan & Ned Shepard Remix).mp3" (RID 0).
> 2017/09/29 23:50:26 [90743(dot)m3u:3] Finished with "/home/liquidsoap/mp3/jingles/1.mp3".
> 2017/09/29 23:50:25 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:50:25 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:50:24 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:50:21 [clock.wallclock_main:2] We must catchup 2.19 seconds!
> 2017/09/29 23:46:17 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:46:16 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:46:15 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:46:14 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:46:11 [clock.wallclock_main:2] We must catchup 1.23 seconds!
> 2017/09/29 23:44:01 [clock.wallclock_main:2] We must catchup 1.29 seconds!
> 2017/09/29 23:43:29 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:43:28 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:43:28 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:43:27 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:42:34 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:42:34 [decoder:3] Method "MAD" accepted "/home/liquidsoap/mp3/ClubDance/Bruno Mars - Locked Out Of Heaven (Sultan & Ned Shepard Remix).mp3".
> 2017/09/29 23:42:33 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:42:33 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:42:32 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:42:25 [clock.wallclock_main:2] We must catchup 1.04 seconds!
> 2017/09/29 23:41:32 [clock.wallclock_main:2] We must catchup 2.76 seconds!
> 2017/09/29 23:41:22 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:41:22 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:41:21 [clock.wallclock_main:2] We must catchup 1.50 seconds!
> 2017/09/29 23:41:20 [fallback_6145:3] Switch to map_metadata_6143 with transition.
> 2017/09/29 23:41:16 [clock.wallclock_main:2] We must catchup 2.16 seconds!
> 2017/09/29 23:41:13 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:41:12 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:41:12 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:41:11 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:41:05 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:41:04 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:41:03 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:41:02 [clock.wallclock_main:2] We must catchup 1.58 seconds!
> 2017/09/29 23:41:01 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:40:53 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:40:53 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:40:53 [clock.wallclock_main:2] We must catchup 1.64 seconds!
> 2017/09/29 23:40:53 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:40:51 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:40:40 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:40:39 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:40:39 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:40:37 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:40:22 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:40:21 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:40:21 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:40:20 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:39:52 [clock.wallclock_main:2] We must catchup 1.25 seconds!
> 2017/09/29 23:39:50 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:39:50 [clock.wallclock_main:2] We must catchup 1.79 seconds!
> 2017/09/29 23:39:47 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:39:47 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:39:47 [clock.wallclock_main:2] We must catchup 1.43 seconds!
> 2017/09/29 23:39:46 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:38:19 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:38:18 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:38:18 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:38:17 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:35:40 [clock.wallclock_main:2] We must catchup 1.35 seconds!
> 2017/09/29 23:35:08 [clock.wallclock_main:2] We must catchup 1.41 seconds!
> 2017/09/29 23:35:05 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:35:04 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:35:04 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:35:03 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:32:10 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:32:09 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:32:09 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:32:07 [fallback_6145:3] Switch to map_metadata_6143 with forgetful transition.
> 2017/09/29 23:28:23 [map_metadata_6112:3] Inserting missing metadata.
> 2017/09/29 23:28:22 [map_metadata_6147:3] Inserting missing metadata.
> 2017/09/29 23:28:22 [fallback_6145:3] Switch to map_metadata_6112 with transition.
> 2017/09/29 23:28:19 [input(dot)harbor_6110:3] Decoding...
> 2017/09/29 23:28:19 [threads:3] Created thread "harbor source feeding" (2 total).
> 2017/09/29 23:28:19 [decoder:3] Method "MAD" accepted "audio/mpeg".
> 2017/09/29 23:28:12 [mksafe:3] Switch to audio_to_stereo_6127.
> 2017/09/29 23:28:12 [switch_6134:3] Switch to mksafe.
> 2017/09/29 23:28:12 [fallback_6145:3] Switch to map_metadata_6143.
> 2017/09/29 23:28:12 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
> 2017/09/29 23:28:12 [threads:3] Created thread "wallclock_main" (1 total).
> 2017/09/29 23:28:12 [output(dot)shoutcast:3] Connection setup was successful.
> 2017/09/29 23:28:12 [decoder:3] Method "MAD" accepted "/home/liquidsoap/mp3/jingles/1.mp3".
> 2017/09/29 23:28:12 [output(dot)shoutcast:3] Connecting mount sid#1 for @y.y.y.y...
> 2017/09/29 23:28:12 [90743(dot)m3u:3] Prepared "/home/liquidsoap/mp3/jingles/1.mp3" (RID 8).
> 2017/09/29 23:28:12 [91320(dot)m3u:3] Successfully loaded a playlist of 156 tracks.
> 2017/09/29 23:28:12 [91320(dot)m3u:3] Playlist treated as format application/x-mpegURL
> 2017/09/29 23:28:12 [91320(dot)m3u:3] No mime type specified, trying autodetection.
> 2017/09/29 23:28:12 [decoder:3] Method "MAD" accepted "/home/liquidsoap/mp3/jingles/1.mp3".
> 2017/09/29 23:28:12 [91320(dot)m3u:3] Loading playlist...
> 2017/09/29 23:28:12 [90743(dot)m3u:3] Successfully loaded a playlist of 123 tracks.
> 2017/09/29 23:28:12 [90743(dot)m3u:3] Playlist treated as format application/x-mpegURL
> 2017/09/29 23:28:12 [90743(dot)m3u:3] No mime type specified, trying autodetection.

Config file:
```
set("log.stdout",false)
set("init.daemon",true)
set("init.daemon.pidfile.path","/home/liquidsoap/liquidsoap.pid")
set("log.file.path","/home/liquidsoap/liquidsoap.log")
set("harbor.bind_addr","0.0.0.0")
headers = ref []

def on_connect(new_headers) =
headers := new_headers
end

def add_dj_metadata(metadata) =
list.add(("dj","#{!headers}"),metadata)
end


def crossfade_dj(a,b)
add(normalize=false,
[ sequence([ blank(duration=1.00),
fade.initial(duration=2.,b) ]),
fade.final(duration=2.,a) ])
end
def crossfade_dj2(a,b)
add(normalize=false,
[ sequence([fade.initial(duration=2.,b) ]),
fade.final(duration=0.,a) ])
end


live = input.harbor("/",port=8000,password="hackme",icy=true,on_connect=on_connect)
live = map_metadata(add_dj_metadata,live)
radio = switch(track_sensitive=false,[({00h00m00s-03h59m00s},mksafe(audio_to_stereo(playlist(mode="normal", "/home/liquidsoap/playlist1.m3u")))),({04h00m00s-05h59m00s},mksafe(audio_to_stereo(playlist(mode="normal", "/home/liquidsoap/playlist2.m3u")))),({18h00m00s-21h59m00s},mksafe(audio_to_stereo(playlist(mode="normal", "/home/liquidsoap/playlist3.m3u")))),({22h00m00s-23h59m00s},mksafe(audio_to_stereo(playlist(mode="normal", "/home/liquidsoap/playlist4.m3u")))),({true},mksafe(audio_to_stereo(playlist(mode="normal","/home/liquidsoap/playlist5.m3u"))))])
radio = crossfade(start_next=1.00,fade_out=2.,fade_in=2.,radio)
radio = map_metadata((fun (_) -> [("title","")]),radio)
radio = fallback(track_sensitive=false,transitions=[crossfade_dj,crossfade_dj2],[live,radio])
output.shoutcast(%mp3(bitrate=96,samplerate=44100,internal_quality=7),name="Music 24h",genre="POP",url="http://website.com",public=true,host="y.y.y.y",port=8004,password="hackme",on_error=(fun (_) -> 5.),radio)
```

How can I solve this problem? This is very annoying.

Liquidsoap 1.3.2 (installed via opam).

**Comment by toots** [comment]
Your logs show a lot of catchup messages. This means that liquidsoap is having trouble processing your stream in real time. You should probably start by looking at that. 

Looking at your script, it doesn't seem to be overly CPU intensive. What kind of machine is running it?

**Comment by SkillenUK** [comment]
Sorry if im taking this slightly off topic! I have a similar issue but I think it is attributed to the Internet connection of the person streaming in my case (which i can live with as it doesn't happen too often). I've been trying to configure a script which falls back to a blank silence for a few seconds before the playlist kicks in. I've tried using the blank command in the fallback but it seems to run indefinitely regardless of the duration that I put in. I've also been trying a transition that would play a jingle except I'm giving am MP3 which has a few seconds of silence as the jingle. I've experimented a lot but not successfully managed to do this. Is there a feature I can use to achieve it or could i request something?  Thanks,

Chris.

**Comment by rihani** [comment]
Hi, I have the same issue as you do and as SkillenUK. any solutions you found pease?

**Comment by desavil** [comment]
@rihani look for this - http://freedrool.us/blog/all-about-buffers

Please try add `buffer=15.0,max=30.0` in `input.harbor()`

`buffer.adaptative()` it does not work at all @toots could you check it out in the latest version of liquidsoap?
