### ISSUE TITLE
Unable to decode stream of type "audio/aacp"!

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#488]
Input.harbor error:
`[decoder:3] Unable to decode stream of type "audio/aacp"!`

This error is in versions from larger than commit a3161cc82f9291894a1f8c0ec621bbfc72bbb690

**Comment by toots** [comment]
Have you compiled with `faad` support enabled?

**Comment by desavil** [comment]
Yes.
The problem occurs both with manual compilation and by opam installation.

**Comment by toots** [comment]
I'm not sure that I can reproduce. Here's a log I got testing:
```
2017/10/06 09:50:05 [harbor:4] Adding source on mountpoint "/bla" with type "audio/aacp".
2017/10/06 09:50:05 [decoder:4] Trying method "WAV" for "audio/aacp"...
2017/10/06 09:50:05 [decoder:4] Trying method "AIFF" for "audio/aacp"...
2017/10/06 09:50:05 [decoder:4] Trying method "PCM/BASIC" for "audio/aacp"...
2017/10/06 09:50:05 [decoder:4] Trying method "RAW AUDIO" for "audio/aacp"...
2017/10/06 09:50:05 [decoder:4] Trying method "FLAC" for "audio/aacp"...
2017/10/06 09:50:05 [decoder:4] Trying method "AAC" for "audio/aacp"...
2017/10/06 09:50:05 [decoder:3] Method "AAC" accepted "audio/aacp".
```

Do you have more logs of your issue? Make sure you do `set("log.level",4)`

**Comment by desavil** [comment]
Ok, I'll check it out again and let you know.
