### ISSUE TITLE
High memory usage when input/output has bad host

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#490]
High memory usage when input/output has bad host.
Liquidsoap 1.3.1 (installed via Opam, Debian 8).

Memory usage: 1,5 GB! - https://i.snag.gy/CTlMn6.jpg

Config:
```
set("log.stdout",false)
set("init.daemon",true)
set("init.daemon.pidfile.path","/home/83/liquidsoap.pid")
set("log.file.path","/home/83/liquidsoap.log")
set("harbor.bind_addr","0.0.0.0")

headers = ref []

def on_connect(new_headers) =
headers := new_headers
end

def add_dj_metadata(metadata) =
list.add(("dj","#{!headers}"),metadata)
end

def crossfade_dj(a,b)
add(normalize=false,
[ sequence([ blank(duration=5.00),
fade.initial(duration=10.,b) ]),
fade.final(duration=10.,a) ])
end
def crossfade_dj2(a,b)
add(normalize=false,
[ sequence([fade.initial(duration=10.,b) ]),
fade.final(duration=0.,a) ])
end

live = input.harbor("/",port=8000,password="hackme",icy=true,on_connect=on_connect)
live = map_metadata(add_dj_metadata,live)
radio = mksafe(input.http("http://www.bad-url.com"))radio = fallback(track_sensitive=false,transitions=[crossfade_dj,crossfade_dj2],[live,radio])
output.shoutcast(%mp3(bitrate=48,samplerate=44100,internal_quality=7),name="",genre="",url="http://",public=true,host="http://www.bad-url.com",port=0,password="hackme",on_error=(fun (_) -> 5.),radio)
output.shoutcast(%mp3(bitrate=48,samplerate=44100,internal_quality=7),name="",genre="",url="http://",public=true,host="",port=0,password="",on_error=(fun (_) -> 5.),radio)
output.shoutcast(%mp3(bitrate=48,samplerate=44100,internal_quality=7),name="",genre="",url="http://",public=true,host="",port=0,password="",on_error=(fun (_) -> 5.),radio)
output.shoutcast(%mp3(bitrate=48,samplerate=44100,internal_quality=7),name="",genre="",url="http://",public=true,host="",port=0,password="",on_error=(fun (_) -> 5.),radio)
```

Logs:

> 2017/10/04 10:44:03 [output(dot)shoutcast:3] Connecting mount sid#1 for @http://www.bad-url.com...
> 2017/10/04 10:44:03 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:03 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:03 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:03 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:04 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:04 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:04 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:04 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:04 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:04 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:04 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:04 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:04 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:04 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:04 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:04 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:04 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:04 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:04 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:09 [output(dot)shoutcast:3] Connecting mount sid#1 for @http://www.bad-url.com...
> 2017/10/04 10:44:09 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:09 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:09 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:09 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:10 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:10 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:10 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:10 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:10 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:10 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:10 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:10 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:10 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:10 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:10 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:10 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:10 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:10 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:10 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:15 [output(dot)shoutcast:3] Connecting mount sid#1 for @http://www.bad-url.com...
> 2017/10/04 10:44:15 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:15 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:15 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:15 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:16 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:16 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:16 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:16 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:16 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:16 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:16 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:16 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:16 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:16 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:16 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:16 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:16 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:16 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:16 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:21 [output(dot)shoutcast:3] Connecting mount sid#1 for @http://www.bad-url.com...
> 2017/10/04 10:44:21 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:21 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:21 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:21 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:22 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:22 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:22 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:22 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:22 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:22 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:22 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:22 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:22 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:22 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:22 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:22 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:22 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:22 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:22 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:27 [output(dot)shoutcast:3] Connecting mount sid#1 for @http://www.bad-url.com...
> 2017/10/04 10:44:27 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:27 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:27 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:27 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:28 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:28 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:28 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:28 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:28 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:28 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:28 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:28 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:28 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:28 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:28 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:28 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:28 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:28 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:28 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:33 [output(dot)shoutcast:3] Connecting mount sid#1 for @http://www.bad-url.com...
> 2017/10/04 10:44:33 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:33 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:33 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:33 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:34 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:34 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:34 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:34 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:34 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:34 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:34 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:34 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:34 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:34 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:34 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:34 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:34 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:34 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:34 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:39 [output(dot)shoutcast:3] Connecting mount sid#1 for @http://www.bad-url.com...
> 2017/10/04 10:44:39 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:39 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:39 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:39 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:40 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:40 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:40 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:40 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:40 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:40 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:40 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:40 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:40 [output(dot)shoutcast:3] Connecting mount sid#1 for @...
> 2017/10/04 10:44:40 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:40 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:40 [output(dot)shoutcast:2] Connection failed: Not_found
> 2017/10/04 10:44:40 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/04 10:44:40 [stderr:3] strange error flushing buffer ...
> 2017/10/04 10:44:40 [stderr:3] strange error flushing buffer ...

**Comment by toots** [comment]
Thanks. Interesting bug indeed.

I've committed what should be a fix for it. Any chance you could try? Should be fairly easy, by pinning liquidsoap in `opam`:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add liquidsoap .
```

Thanks!

**Comment by toots** [comment]
Hey! I'm gonna assume that this is fixed. Please reopen if it isn't!
