### ISSUE TITLE
Problem with liquidsoap when updating playlist file

### ISSUE THREAD

**Issue by pthanasis** [savonet/liquidsoap#492]
Hi,

I have a simple playlist.txt file and liquisoap plays all the tracks sequentially. From time to time I make some changes in that file by deleting or adding new tracks, but after a while and during the playback, liquidsoap starts to play the first track of the playlist. Is this a normal behavior or do I have to change something in the .liq file? 

Thank you in advance

OS: Debian 8.9
Source: liquidsoap (1.1.1-7)
Version: 1.1.1-7+b1 (Debian package)

**Script**
#!/usr/bin/liquidsoap

world = playlist.safe("/home/test/mp3/playlist.txt",mode="normal",reload_mode="watch")
radioworld = crossfade(start_next=8.,fade_in=3.,fade_out=3.,world)

output.icecast(%mp3(bitrate=128),
host="localhost",
port=8000,
password="pass",
mount="test",
name="test",
description="test",
genre="Misc",
url="http://127.0.0.1",
radioworld)

**Comment by pthanasis** [comment]
Hello,

Does anyone know what I can do about it?

Thank you!

**Comment by toots** [comment]
Hi!

Not sure what the problem is. Is the playlist has exhausted its tracks, it will loop back and start over with the first file.

**Comment by mylselgan** [comment]
What I understand is when he add more tracks to the active playlist it is not automatically reloaded but plays the old playlist instead.

ie. reload_mode="watch" is not working

**Comment by neralex** [comment]
Finally some pointed this issue, which I found months ago and why I can't use 1.3.x....

https://github.com/savonet/liquidsoap/issues/441

**Comment by mylselgan** [comment]
Hi neralex, Have you found any solution in mailing list.? Could you please post the mailing list link here. Or do you have any fix?

**Comment by pthanasis** [comment]
Hello,

For example, I have a playlist of 100 tracks and track number "20" is being played. I make a change in the playlist (adding or removing tracks in the playlist) and then after a while, when track "20" or the next one finish, liquidsoap restarts by playing again track number "1" without finishing the entire playlist. In other words, liquidsoap restarts the playlist when a single change is made in the playlist.

Thank you all

**Comment by toots** [comment]
Ok, I get it now. Let me look at it.

**Comment by toots** [comment]
Ok, I think I have found the issue. Could you try to add this to your script:
```
set("scheduler.fast_queues",1)
```
Let me know if that works for you.

**Comment by pthanasis** [comment]
Still no luck. Once liquidsoap understands that the playlist file has changes (track addition/removal) then it reloads the playlist as I understand from the log file and then prepares again the 1st track of the playlist.

2017/11/20 19:27:15 [pl-world(dot)txt:3] Finished with "/home/test/mp3/01-1389301-Evgeny Teilor-Haunted Shores.mp3".
2017/11/20 19:27:15 [decoder:3] Method "MAD" accepted "/home/test/mp3/03-1389298-Evgeny Teilor-Beta Decay.mp3".
2017/11/20 19:27:15 [pl-world(dot)txt:3] Prepared "/home/test/mp3/03-1389298-Evgeny Teilor-Beta Decay.mp3" (RID 9).
**(A change is made in the playlist.txt file. I deleted the last track and then liquidsoap reloaded the playlist)**
2017/11/20 19:28:57 [pl-world(dot)txt:3] Loading playlist...
2017/11/20 19:28:57 [pl-world(dot)txt:3] No mime type specified, trying autodetection.
2017/11/20 19:28:57 [pl-world(dot)txt:3] Playlist treated as format application/x-mpegURL
2017/11/20 19:28:57 [decoder:3] Method "MAD" accepted "/home/test/mp3/01-1389301-Evgeny Teilor-Haunted Shores.mp3".
2017/11/20 19:28:57 [decoder:3] Method "MAD" accepted "/home/test/mp3/03-1389298-Evgeny Teilor-Beta Decay.mp3".
2017/11/20 19:28:57 [decoder:3] Method "MAD" accepted "/home/test/mp3/04-1389299-Evgeny Teilor-Uncertainty.mp3".
2017/11/20 19:28:57 [decoder:3] Method "MAD" accepted "/home/test/mp3/05-1389303-Evgeny Teilor-Chrome.mp3".
2017/11/20 19:28:57 [decoder:3] Method "MAD" accepted "/home/test/mp3/06-1389300-Evgeny Teilor-Reversable.mp3".
2017/11/20 19:28:57 [decoder:3] Method "MAD" accepted "/home/test/mp3/07-1389306-Evgeny Teilor-Landscape.mp3".
2017/11/20 19:28:57 [decoder:3] Method "MAD" accepted "/home/test/mp3/08-1389304-Evgeny Teilor-Te Henga.mp3".
2017/11/20 19:28:57 [pl-world(dot)txt:3] Successfully loaded a playlist of 7 tracks.
**(Finishes with track No3 and start from the beginning with track No1.)**
2017/11/20 19:31:07 [pl-world(dot)txt:3] Finished with "/home/test/mp3/03-1389298-Evgeny Teilor-Beta Decay.mp3".
2017/11/20 19:31:07 [decoder:3] Method "MAD" accepted "/home/test/mp3/01-1389301-Evgeny Teilor-Haunted Shores.mp3".
2017/11/20 19:31:07 [pl-world(dot)txt:3] Prepared "/home/test/mp3/01-1389301-Evgeny Teilor-Haunted Shores.mp3" (RID 1).

It should continue with track No4...right?

**Comment by toots** [comment]
Ha. No, that's the way it's supposed to work. If you need finer-grained control over the playlist's content, you should consider using a plain `m3u` file. Then you can update the playlist's content and make sure that the first song in the new playlist is the one you expect to be played next.
