### ISSUE TITLE
Way to play certain tracks always together, in order

### ISSUE THREAD

**Issue by FreeSlave** [savonet/liquidsoap#493]
I'm new to liquidsoap, so this might be a silly question.

There are songs that consist of two tracks (e.g. intro and main theme) or even more (e.g. conceptual albums where every track 'flows' into the next without a pause).
Is there any nice way to define such pairs and play them always one by another treating them like one track and keeping the random uniform?

**Comment by toots** [comment]
Hi,

There can be many ways to achieve this. One could be a custom scheduler used via `request.dynamic`.

I'm gonna close this here as it is not related to code development. Please feel free to follow-up on the mailing list at: savonet-users@lists.sourceforge.net
