### ISSUE TITLE
Liquidsoap 1.3.3: the variable output.icecast has not been previously defined

### ISSUE THREAD

**Issue by codeofdusk** [savonet/liquidsoap#494]
I see this error on the latest 1.3.3. 1.3.2 as well as a development version of 1.3.3 work perfectly fine. What's going on?

**Comment by codeofdusk** [comment]
More specifically, it seems that commit 301d11b59bb71fbb8526ebbb15a47f1b325db0e3 breaks my config.

**Comment by codeofdusk** [comment]
I fixed my install by installing [ocaml-cry](http://github.com/savonet/ocaml-cry) from GIt (the latest commit is the 0.6.0 version required by the `configure` script). This should fail more gracefully to avoid confusing users!

**Comment by toots** [comment]
How do you install liquidsoap to begin with? Closing this now but feel free to comment further.

**Comment by codeofdusk** [comment]
I installed it from git, using Opam.

**Comment by toots** [comment]
Ok. You mean you used `opam` pinning mechanism on `git` repositories? By default `opam` fetches released source tarballs.

**Comment by codeofdusk** [comment]
Yes

**Comment by toots** [comment]
Ha I see. Then, yes, I'd recommend unpinning before installing released versions. `opam` should know how to handle versioned dependencies but `git`-pinned packages only have `dev` for their version. Hope that helps.
