### ISSUE TITLE
Error compile with enable: ocaml-flac

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#495]
From latest sources.

Look this:

> make[3]: Opuszczenie katalogu '/home/liquidsoap/liquidsoap-full/ocaml-faad/src'
> make[2]: Opuszczenie katalogu '/home/liquidsoap/liquidsoap-full/ocaml-faad/src'
> make[1]: Opuszczenie katalogu '/home/liquidsoap/liquidsoap-full/ocaml-faad'
> make[1]: Wejście do katalogu '/home/liquidsoap/liquidsoap-full/ocaml-flac'
> make -C src all
> make[2]: Wejście do katalogu '/home/liquidsoap/liquidsoap-full/ocaml-flac/src'
> make[3]: Wejście do katalogu '/home/liquidsoap/liquidsoap-full/ocaml-flac/src'
> making ._bcdi/ogg_demuxer_flac_decoder.di from ogg_demuxer_flac_decoder.mli
> making ._bcdi/ogg_flac.di from ogg_flac.mli
> making ._bcdi/flac.di from flac.mli
> making ._d/ogg_demuxer_flac_decoder.d from ogg_demuxer_flac_decoder.ml
> making ._d/ogg_flac.d from ogg_flac.ml
> making ._d/flac.d from flac.ml
> ocamlc -c -cc "gcc" -ccopt "-fPIC -I .. -Wall -DCAML_NAME_SPACE \
>                         -DPIC -fPIC   \
>                           -I/home/liquidsoap/.opam/system/lib/bytes -I/home/liquidsoap/liquidsoap-full/ocaml-flac/../ocaml-ogg/src  -o flac_stubs.o " flac_stubs.c
> ocamlc -c -cc "gcc" -ccopt "-fPIC -I .. -Wall -DCAML_NAME_SPACE \
>                         -DPIC -fPIC   \
>                           -I/home/liquidsoap/.opam/system/lib/bytes -I/home/liquidsoap/liquidsoap-full/ocaml-flac/../ocaml-ogg/src  -o ogg_flac_stubs.o " ogg_flac_stubs.c
> ar rcs libflac_stubs.a  flac_stubs.o ogg_flac_stubs.o
> ocamlc -c -g -w +A-4@5-7@8-9@11@12@20-35-44-45-50 -I /home/liquidsoap/.opam/system/lib/bytes -I /home/liquidsoap/liquidsoap-full/ocaml-flac/../ocaml-ogg/src flac.mli
> File "flac.mli", line 299, characters 15-20:
> Error: Unbound type constructor bytes
> OCamlMakefile:934: polecenia dla obiektu 'flac.cmi' nie powiodły się
> make[3]: *** [flac.cmi] Błąd 2
> make[3]: Opuszczenie katalogu '/home/liquidsoap/liquidsoap-full/ocaml-flac/src'
> OCamlMakefile:717: polecenia dla obiektu 'byte-code-library' nie powiodły się
> make[2]: *** [byte-code-library] Błąd 2
> make[2]: Opuszczenie katalogu '/home/liquidsoap/liquidsoap-full/ocaml-flac/src'
> Makefile:12: polecenia dla obiektu 'all' nie powiodły się
> make[1]: *** [all] Błąd 2
> make[1]: Opuszczenie katalogu '/home/liquidsoap/liquidsoap-full/ocaml-flac'
> Makefile:11: polecenia dla obiektu 'all' nie powiodły się
> make: *** [all] Błąd 1

This is probably the reason:
> File "flac.mli", line 299, characters 15-20:

**Comment by smimram** [comment]
The problem is actually in ocaml-flac, see https://github.com/savonet/ocaml-flac/pull/3.
