### ISSUE TITLE
Liquidsoap 1.3.3 - Connection failed: Failure("inet_addr_of_string")

### ISSUE THREAD

**Issue by desavil** [savonet/liquidsoap#496]
Liquidsoap 1.3.3 bug (installed from sources).

When I use: host="my-server.com":
> 2017/10/16 17:02:22 [output(dot)shoutcast:3] Connecting mount sid#1 for @my-server.com...
> 2017/10/16 17:02:22 [output(dot)shoutcast:2] Connection failed: Failure("inet_addr_of_string")
> 2017/10/16 17:02:22 [output(dot)shoutcast:3] Will try again in 5.00 sec.
> 2017/10/16 17:02:22 [stderr:3] strange error flushing buffer ...
> 2017/10/16 17:02:22 [stderr:3] strange error flushing buffer ...

When I use: host="x.x.x.x" works well.

In earlier versions I have not noticed this problem.
Maybe it has something to do with the introduction of IPv6.

**Comment by davehayes** [comment]
I'll second this bug. I just encountered it as well. The fix is to use a dotted IP address.

**Comment by noahnu** [comment]
I just upgraded from 1.2.1 to 1.3.3 yesterday and ran into the same issue. I came across [this doc](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Unix.html#VALinet_addr_of_string) which describes the function as

> Conversion from the printable representation of an Internet address to its internal representation. The argument string consists of 4 numbers separated by periods (XXX.YYY.ZZZ.TTT) for IPv4 addresses, and up to 8 numbers separated by colons for IPv6 addresses. __Raises Failure when given a string that does not match these formats.__

I was using "localhost" as the mount point. Changing it to 127.0.0.1 per @davehayes comment fixed it.

**Comment by Yamakaky** [comment]
Same for me, `host=127.0.0.1` works.

**Comment by desavil** [comment]
IP address works, but domains not.
This is not a solution to the problem, just a workaround.

**Comment by toots** [comment]
Shit. Yes, it's coming from the `IPv6` changes. Will get on this asap.

**Comment by toots** [comment]
Ok, I've pushed a fix to `ocaml-cry`. Woud you guys mind giving it a try? Should be relatively easy with opam:
```
% git clone --recursive https://github.com/savonet/ocaml-cry.git
% cd ocaml-cry
% opam pin add cry .
```

Thanks!

**Comment by toots** [comment]
Ok, I'll release this tomorrow.

**Comment by toots** [comment]
This should be fixed with the latest `0.6.1` release of `ocaml-cry`. Updated `opam` package has been submitted and should hopefully be coming pretty soon. Please re-open if you still see the issue with that version.

**Comment by deadseankennedy** [comment]
Hey there!

Any chance this change will be getting pushed to the docker image as well?  It seems to suffer from the same bug.

Thanks for all of your awesome work keep it up!

Sean

**Comment by toots** [comment]
Just did it, thanks for reminding me!

**Comment by dtcooper** [comment]
Would an updated "full" build for this? (ie a second version of `liquidsoap-1.3.3-full.tar.gz`)?

**Comment by xogium** [comment]
I second what @dtcooper said, it would be really nice to have a tarball fixing this (or even replacing the existing one), for distro that package liquidsoap... We have that in arch but it must be built from sources. Using opam on arch is a nightmare, as is for npm, perl package manager, that's why we use it only in fakeroot environment.

**Comment by toots** [comment]
Good point. I'll make on ASAP.

**Comment by toots** [comment]
Done! :-)

**Comment by xogium** [comment]
Hi,
it appeares that the liquidsoap-1.3.3-full.tar.gz is no longer available, the url gives a 404. I think something went wrong when you uploaded it :)

**Comment by toots** [comment]
I can see it here: https://github.com/savonet/liquidsoap/releases/tag/1.3.3

**Comment by xogium** [comment]
Hi,
for me,
https://github.com/savonet/liquidsoap/releases/download/1.3.3/liquidsoap-1.3.3-full.tar.gz
is returning a 404 error, but
https://github.com/savonet/liquidsoap/releases/download/1.3.3/liquidsoap-1.3.3-full.tar.bz2
seems to be still there. Was it the bz2 that was rebuilt in order to vix the bug ?

**Comment by toots** [comment]
Huh. Duh ok, thanks for your perspicacity! As a side note: the `bz2` archive is half the size of the `gz` archive, I think next release I'll just use `bz2`..
