### ISSUE TITLE
Liquidsoap not outputting any audio

### ISSUE THREAD

**Issue by LithianCoth** [savonet/liquidsoap#497]
I'm not sure where else to put this, I cant seem to leave a thread on the mailing-list on source forged, nor do I see any thread with this issue.

OS: rasbian
Linux 3.10.25+ armv6l

Liquidsoap Version: 1.0.1
I've done the following install Liquid soap
apt-get update
apt-get install liquidsoap
apt-get install liquidsoap-plugin-all

The plugin's one resolved the: a problem with this line: output.alsa(filesource)

however, currently I am not even able to get liquid soap to do the following
test.liq
out(sine())

And running that with: /etc/init.d/liquidsoap start
of course, the test.liq is the only .liq file in the /etc/liquidsoap/ directory

I've even tried to add logging, but that also didnt work(by that i mean whether i created the log file before hand or not, there was nothing printed to that file), I've given the script 777 permissions,

The script give me the following: Starting liquidsoap channels: test.liq OK

But no sound. Now some might say, oh its your sound card, or you dont have speakers plugged in. I've used the following to test.

mpg123 music-test.mp3

and music does play.

So I am stuck, not sure what to do. I am not looking to use icecast, because this isnt supposed to be a streaming device, simply it only needs to output audio to the speakers, from there i would build onto it. making it output audio to the left and right speakers, two different songs.

Any help would be appreciated!
---
EDIT
So after desavil's kind instructions, I've removed liquidsoap, and had to download the package from github using the following:

wget "https://github.com/savonet/liquidsoap/releases/download/1.3.3/liquidsoap-1.3.3-full.tar.gz"

I've extracted it as follows

tar -xf liquidsoap-1.3.3-full.tar.gz

and followed the INSTALL file until, i got to the make commands.
I had attempted (I was in the directory with the make file in it)
make
and
make -f Makefile

I got the following Error:
for i in ocaml-cry-0.6.0 ocaml-ao-0.2.1 ocaml-portaudio-0.2.1 ocaml-alsa-0.2.3 ocaml-pulseaudio-0.1.3 ocaml-bjack-0.1.5 ocaml-gstreamer-0.2.3 ocaml-mad-0.4.5 ocaml-taglib-0.3.3 ocaml-lame-0.3.3 ocaml-shine-0.2.1 ocaml-ogg-0.5.2 ocaml-vorbis-0.7.0 ocaml-speex-0.2.1 ocaml-theora-0.3.1 ocaml-opus-0.1.2 ocaml-fdkaac-0.2.1 ocaml-faad-0.3.3 ocaml-flac-0.1.3 ocaml-ladspa-0.1.5 ocaml-soundtouch-0.1.8 ocaml-samplerate-0.1.4 ocaml-gavl-0.1.6 ocaml-ffmpeg-0.1.2 ocaml-frei0r-0.1.1 ocaml-dssi-0.1.2 ocaml-xmlplaylist-0.1.4 ocaml-lastfm-0.3.1 ocaml-lo-0.1.1 ocaml-dtools-0.3.4 ocaml-duppy-0.6.1 ocaml-mm-0.3.0 liquidsoap-1.3.3; do make -C $i || exit 1; done
make[1]: Entering directory `/path/to/liquidsoap-1.3.3-full/ocaml-cry-0.6.0'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/path/to/liquidsoap-1.3.3-full/ocaml-cry-0.6.0'
make: *** [all] Error 1

I've looked around for a solution for the makefile but have not been successful, so far 1.0.1 has been the closest to working, and the only available repository.

If someone could provide a working makefile that would be most helpful, otherwise any assistance is appreciated!

**Comment by desavil** [comment]
You're doing it wrong.
Liquidsoap 1.0.1 is outdated and has a lot of bugs.

Install the latest version by opam or compile.

**Comment by toots** [comment]
Hey @LithianCoth.

@desavil is right, it would be better to try a more recent version. I really recommend installing via `opam` too, instead of compiling from sources. Have you visited the instructions page here: http://liquidsoap.fm/download.html

As per your problem, it would be nice to have some logs to see. Maybe add `set("log.level",4)` to make it more verbose, too.

**Comment by toots** [comment]
Hi,

I'm gonna close this one as I'm trying to focus on releasing `1.3.4`. Feel free to test with a recent version and report/reopen if the bug still occurs.

Good luck with your projects.
