### ISSUE TITLE
handle authentication when listener connects

### ISSUE THREAD

**Issue by simahawk** [savonet/liquidsoap#499]
icecast supports some hooks as `listener_add` / `listener_remove` that you can use to authenticate users.
Basically it calls your callbacks passing IP of the user and other params.

Unfortunately this works only with named mount points that you declare in xml config AFAIK.

I'm creating streams on the fly - using liquidsoap - so the question is: is there a way to pass extra mount-specific arguments (such as `listener_*`,  `max-listeners`) to icecast?

If not, is there another way w/ pure liquidsoap to provide a callback to be called when a user start listening? I spotted "on_connect" but I don't know if you can use it for this purpose and if you can gather all the metadata you need to handle authentication properly.

**Comment by toots** [comment]
Liquidsoap is pretty agnostic with regard to icecast listeners. It will see nothing coming from them. As for the custom icecast mount-specific arguments, I don't think that it exists as of now so you might have to circle back to them for this. If/when those are added, you might be able to use them in liquidsoap via, for instance, the `headers` argument in `output.icecast`.

I'm closing this for now but feel free to re-open if new development happen.

**Comment by simahawk** [comment]
What do you mean here?
> I don't think that it exists as of now so you might have to circle back to them for this.

Maybe you can help me to understand how this works under the hood. As I get it, correct me if I'm wrong, [here](https://github.com/savonet/liquidsoap/blob/e4c6ffc2f6a1c09ca58b41dd3e1dd427883cfb4b/src/outputs/icecast2.ml#L155) is where you define icecast params. Later on they are prepared for "send". 

I wonder how they are sent and if placing an arg more in there is going to make it land in data that is sent (which I guess happens [here](https://github.com/savonet/liquidsoap/blob/537d338593b680c708e3ff54e7701e947af4c53c/src/lang/builtins_cry.ml#L31)).

Thanks in advance for your support.
