### ISSUE TITLE
Catchup warnings when using run_process or get_process_output

### ISSUE THREAD

**Issue by AlReem** [savonet/liquidsoap#501]
I am trying to get an 'm4a' container format version of saved files (HE-AAC encoded) with the following code which uses fdkaac via a shell command when the file is closed by output.file.  Everything works fine except for the catchup warnings after every shell execution.  I want to know if I am doing anything wrong.  Does liquidsoap execute run_process synchronously?  What might be the best way to address this requirement.

By the way, I am doing this to provide a playable file for our listeners who missed hearing it live.

```
def closed_recording ( filename )
    filenameAac = string.replace(pattern='(.wav)', fun(_) -> "", basename(filename)) ^ ".aac"
    filenameAac = string.replace(pattern=' ', fun(_) -> "\ " , filenameAac)
    filename = string.replace(pattern=' ', fun(_) -> "\ " , filename)
    print('Processing file...')
    execShell = 'fdkaac --profile 29 --bitrate 32000 --bitrate-mode 3 --afterburner 1 --lowdelay-sbr 1 --raw -o #{saveFolder}#{filenameAac} #{filename} > /dev/null 2>&1'
    print( run_process(execShell) )
end

output.file( %wav( stereo=true, channels=2, samplesize=16, header=false),
on_start=started_recording, on_close=closed_recording, 
on_stop=stopped_recording, reopen_on_metadata=true, fallible=false, 
"#{tmpFolder}%Y_%m_%d_%H_%M_%S^$(title).wav", s )
```
Catch up messages show up like this...
`2017/10/27 09:52:57 [clock.wallclock_main:2] We must catchup 3.73 seconds!`
Interestingly though, these are not shown when I comment out the `run_process`or `get_process_output` command in the script.

**Comment by toots** [comment]
Hi @AlReem 

I think that the `on_close` callback is executed in the main streaming loop, which will thus be blocked until the file is encoded, which will cause the delays you are experiencing. 

Instead, you should send the execution to the tasks threads this way:
```
def closed_recording ( filename )
    def exec () =
      filenameAac = string.replace(pattern='(.wav)', fun(_) -> "", basename(filename)) ^ ".aac"
      filenameAac = string.replace(pattern=' ', fun(_) -> "\ " , filenameAac)
      filename = string.replace(pattern=' ', fun(_) -> "\ " , filename)
      print('Processing file...')
      execShell = 'fdkaac --profile 29 --bitrate 32000 --bitrate-mode 3 --afterburner 1 --lowdelay-sbr 1 --raw -o #{saveFolder}#{filenameAac} #{filename} > /dev/null 2>&1'
      print( run_process(execShell) )
      (-1.)
    end
    add_timeout(fast=false,0.,exec)
end
```
