### ISSUE TITLE
Transcode with LiquidSoap

### ISSUE THREAD

**Issue by Recentes** [savonet/liquidsoap#503]
Hi,

I´m tryiing to transcode a livestream to a lower sample/bitrate to another server, but I cannot get it to work... Keep getting "the variable restart used here has not been prevously defined"
Can someone help me ? maybe with a working script ?

Regards,

**Comment by toots** [comment]
Hey @Recentes 

Would you mind sharing your script? Thanks!

**Comment by Recentes** [comment]
Hi toots,

Yes, my scipt is:
url = "URL for stream feed"
inut = mksafe(input.http(url))

output.icecast(
  %mp3(bitrate=8, samplerate=22050, stereo=false),
  mount=/mount-name.mp3"
  host="my ICECAST server ip adress", port=8000, password="my ADMIN password",
  mean(input))

Thats it, but I do not know if it is the right one...
I need a script so I can transcode in another bitrate and samplerate and my live stream feed :)

Regards,

**Comment by toots** [comment]
This looks cool, except that `8` for `mp3` bitrate seems too low. You can find the combination of supported `bitrate`/`samplerate` for mp3 here: https://en.wikipedia.org/wiki/MP3

**Comment by Recentes** [comment]
And if I want to transcode in AAC ? do you have an ide how I could do that ? :)

**Comment by Recentes** [comment]
btw, the error I am getting in this script, is:
"At line 9, char 15: the variable output.icecast used here har not been previously defined"
A on line 9, char 15 is output.icecast**"("**

**Comment by E46-S54** [comment]
If that's your script in it's entirety then you've got

**inut** = mksafe(input.http(url))

yet you're using **mean(input)** .  - missing P

**Comment by Recentes** [comment]
Yeah, that was a mistype, when typing here :)

**Comment by toots** [comment]
@Recentes you need to install `ocaml-cry` if you want to enable `output.icecast`. When using opam it should be as simple as:
```
opam install cry
```

**Comment by Recentes** [comment]
Hi @toots 
Now I am getting a many lines of "Strange error flushing buffer..."

**Comment by Recentes** [comment]
Found my problem :)
