### ISSUE TITLE
http.get what I am doing wrong

### ISSUE THREAD

**Issue by Sveeeeeen** [savonet/liquidsoap#504]
Hi,

I just try to add http request always when a track starts/ends,

`playlist = playlist.once(
        reload_mode="watch",
        on_done=track_end(),
        "playlist.txt"
)
`

I have created the function track_end
`
def track_end()
        log("Sending track end to webserver...")
        ignore( http.get( " URL is here" ))
        log("Done!")
end
`

But this does not work. 

`
At line 21, char 19-20:
  this value has type
    unit (inferred at line 12, char 5-13)
  but it should be a subtype of (the type of the value at /usr/lib/liquidsoap/1.1.1/utils.liq, line 601, char 48)
    ()->_ (inferred at /usr/lib/liquidsoap/1.1.1/utils.liq, line 601, char 49-52)
`

Would someone please help me with this?

**Comment by toots** [comment]
Hi! 

You are executing the function before passing it! Here: `on_done=track_end(),`. Try this instead:
```
playlist = playlist.once( reload_mode="watch", on_done=track_end, "playlist.txt" )
```

**Comment by Sveeeeeen** [comment]
Wow thanks.
