### ISSUE TITLE
Problem with encoding of data passed to system method

### ISSUE THREAD

**Issue by Evreke** [savonet/liquidsoap#506]
Liquidsoap is running in docker container (using my own image with Ubuntu:16.04 and regular apt install liquidsoap) 
I am trying to make feature for my web radio that will show last N played tracks in frontend.
Decision is to use Python script which will take 2 arguments, then write\append them to json file...

I am using this part of code 

```
def new_track(m) =
	artist = m["artist"]
	title = m["title"]
	system("python3 ./scripts/last_10_songs.py \"#{artist}\" \"#{title}\"")
end
```

My python script fails to write **Cyrillic** strings to json but no problem with **Latin** characters.

One guy from community told me to get bytes of passed string from liquidsoap to determine output encoding, but i have no success to determine encoding of bytes array.

Is there anyway to determine what type of encoding variables `artist` and `title` have.

**Comment by toots** [comment]
Hi @Evreke,

You might want to try the `string.recode` method:
```
Convert a string. Effective only if Camomile is enabled.
Type: (?in_enc:string,?out_enc:string,string)->string
Category: String
Parameters:
 * in_enc : string (default: "")
     Input encoding. Autodetected if empty.
 * out_enc : string (default: "UTF-8")
     Output encoding.
 * (unlabeled) : string (default: None)
```

For, if you want to convert a string to `ECMA-CYRILLIC` you would do:
```
s = string.recode(out_enc="ECMA-CYRILLIC",s)
```

Hope that helps, feel free to re-open if you have more questions or if the problem still occurs.

**Comment by toots** [comment]
Although, you might want to double check on which encoding to use. I believe that the `json` standard expectes `UTF8` strings only.
