### ISSUE TITLE
Missing liquidtts

### ISSUE THREAD

**Issue by wizbox** [savonet/liquidsoap#507]
I noticed the following is missing from the latest version docs 1.3.3:

set("say.program","/usr/local/lib/liquidsoap/scm/liquidtts")

does that mean i cannot use my own tts script anymore?  

and only sox and festival is supported :-(

**Comment by wizbox** [comment]
I got around the issue by creating my own text2wave script rather than using festival version:

#!/bin/bash
read param
googletts-cli.pl -s 1.3 -t "$param" -o "$param".tmp.wav
cat "$param".tmp.wav
rm "$param"*.wav

**Comment by toots** [comment]
Hi @wizbox!

No, not at all :-) Support for `say` has been rewritten in a more elegant and composable way using support for script-defined protocols introduced in `1.3.0`.  Thus, `liquidtts` is no longer provided and instead you should just provide the `sox` binary in the `PATH` or specify where to find it using:
```
set("protocol.say.sox_path","sox")
```

Closing now, please re-open if you have further issues.

**Comment by toots** [comment]
Sorry, I forgot to add: you should also now be able to implement your own speech synthesis protocol. For instance, here's the definition of the `polly` protocol, using `AWS`'s speech synthesis services:
```
register(name="AWS protocols settings","protocol.aws",())
register(name="Profile",descr="Use a specific profile from your credential file.",
         "protocol.aws.profile","")
register(name="Region",descr="AWS Region",
         "protocol.aws.region","")
register(name="Binary",descr="Path to aws CLI binary",
         "protocol.aws.path","aws")
register(name="Polly protocol settings","protocol.aws.polly",())
register(name="Format",descr="Output format",
         "protocol.aws.polly.format","mp3")
register(name="Voice",descr="Voice ID",
         "protocol.aws.polly.voice","Joanna")

# Build a aws base call
# @flag hidden
def aws_base() =
  aws = get(default="aws","protocol.aws.path")

  region = get(default="","protocol.aws.region")

  aws =
    if region !="" then
      "#{aws} --region #{region}"
    else
      aws
    end

  profile = get(default="","protocol.aws.profile")

  if profile !="" then
    "#{aws} --profile #{quote(profile)}"
  else
    aws
  end
end

# Register the polly: protocol using AWS Polly
# speech synthesis services. Syntax: polly:<text>
# @flag hidden
def polly_protocol(~rlog,~maxtime,text) =
  aws = aws_base()

  format = get(default="mp3","protocol.aws.polly.format")

  extname =
    if format == "mp3" then
      "mp3"
    elsif format == "ogg_vorbis" then
      "ogg"
    else
      "wav"
    end

  aws = "#{aws} polly synthesize-speech --output-format #{format}"

  voice_id = get(default="Joanna","protocol.aws.polly.voice")

  cmd = "#{aws} --text #{quote(text)} --voice-id #{quote(voice_id)} $(output)"

  [process_uri(extname=extname,cmd)]
end
add_protocol(static=true,"polly",polly_protocol,
             doc="Generate speech synthesis using AWS polly service. \
                  Result might be mono, needs aws binary in the path.",
             syntax="polly:Text to read")
```

Protocols code is located here: [https://github.com/savonet/liquidsoap/blob/master/scripts/protocols.liq[(https://github.com/savonet/liquidsoap/blob/master/scripts/protocols.liq). Let me know if you need more explanations on how to write your own one.
