### ISSUE TITLE
Strange error flushing buffer... after 3 hours livestream

### ISSUE THREAD

**Issue by Recentes** [savonet/liquidsoap#508]
Hi,
I´m getting an error code "Strange error flushing buffer..." after 3 hours streaming with 18 instances...
The server is very slow as well... Does anyone have an idea why ?

**Comment by toots** [comment]
Hi @Recentes,

Do you have more logs of your issue? What are the consequences of this error? It's not clear to me what's going on :-)

**Comment by toots** [comment]
Hi,

Closing this one, please reopen if it still applies!
