### ISSUE TITLE
Flac Jingles Freeze

### ISSUE THREAD

**Issue by wizbox** [savonet/liquidsoap#514]
When using FLAC format for jingles, Liquidsoap 1.3.3 freezes after about 3+ hours, there isn't much in the log apart from a smartcrossfade on a jingle FLAC file. When i switch jingles to WAV format, Liquidsoap stays rock solid stable?

I use jingles like this:

```
jingle_radio1=single("/home/media/radio/jingles/jingle.flac")
jingle_radio2=single("/home/media/radio/jingles/jingle2.flac")
jingle_stream_rotate=rotate(weights=[1,4,1,4],[jingle_radio1,radio,jingle_radio2,radio])
```

**Comment by wizbox** [comment]
Problem is now fixed, i did the following things, not sure what one solved it:

1) tested small amount of music on playlists to start with, then checked and corrected all the music for errors.

2) used the following setting: set("tag.encodings",["UTF-8"]) + also, added this to output.icecast: encoding="UTF-8"

3) used the following for playlists:
music=playlist("/home/media/music/music.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")


Liquidsoap is running rock solid now, so this can be marked as [SOLVED]

**Comment by toots** [comment]
Ok, good to hear!
