### ISSUE TITLE
massive memory leak

### ISSUE THREAD

**Issue by mrdevis** [savonet/liquidsoap#516]
To achieve a mixdown of four audio channels (two from live input, two from stock video), I ran into the following (admittedly ugly, but functioning - at least for a while) solution:

```
    liveIn = nrj(input.jack(id="liquidIn", buffer_size=1))
    v_src = playlist.once(reload_mode="watch", "/VIDEOS/play_now.pls")

    footage = fallback(track_sensitive=true, [v_src, single("/VIDEOS/break.mp4")] )
    footage_audio = drop_video(footage)
    footage_video = drop_audio(footage)

    liveOut = add(normalize=true, [footage_audio, liveIn])
    liveOut = mux_video(video=footage_video, liveOut)

    // liveOut sent to output.gstreamer.audio_video(clock_safe=false, ...
```

This produces a

`[mux_6831:4] Copy-avoiding optimization isn't working!`

Error/Warning (?), and has a massive memory leak causing liquidsoap to bail out after about 10 minutes (when the available 16G has been eaten).

**Comment by toots** [comment]
Hey,

Could you try with the latest `ocaml-gstreamer`? I've made some fixes that could very well solve this issue..

**Comment by toots** [comment]
This should be fixed now!
