### ISSUE TITLE
Skip input.http if on_blank

### ISSUE THREAD

**Issue by mickaelmonsieur** [savonet/liquidsoap#517]
Hi,
I'm looking for how to switch to the 2nd source (pointer "fallback") if a blank is detected on the input.http (pointer program).
And that input.http (re)starts again as soon as there is no more blank.
How to do?
my script:

```
def send_alert() =
  system("python /home/pi/alert.py")
  log("Alert!")
end

url = "http://127.0.0.1:8000/test.mp3"
program = input.http(url)

playlist = playlist(reload_mode="watch","/home/pi/playlist/")
energie = nrj(playlist)
#fallback = strip_blank(energie,max_blank=2., threshold=-50.)

program = on_blank(send_alert,program)

#radio = fallback.skip(input=program,fallback)
radio = fallback(track_sensitive=false, [program, energie])

radio=mksafe(radio)

output.alsa(radio)
```

**Comment by toots** [comment]
I believe that `strip_blank` should work for that. You might need to wrap your source in a `output.dummy` before applying it to make sure that it is being pulled:
```
output.ao(program)
program = strip_blank(program)
```
