### ISSUE TITLE
How do I replace metadata handling?

### ISSUE THREAD

**Issue by davehayes** [savonet/liquidsoap#518]
As I understand how liquidsoap works, media file decoders are run
twice. The first time, this is to find and remember metadata. The
second time actually decodes the media.

How can I intercept the first time this happens and provide my own
metadata?

I ask this because a bug in gstreamer prevents me from playing wma files and it was asserted that the bug is in the metadata handling. So given that I can provide my own metadata (from my database) per file it makes sense to actually do that as a bug workaround.

**Comment by toots** [comment]
Hi,

You should be able to use `map_metadata` for this. If you want to entirely replace the metadata you should set `update=false`:
```
def make_my_own_metadata(m) =
  # Do something with m
  [("title",title),...]
end

s = map_metadata(update=false,make_my_own_metadata,s)
```
If metadata aren't present at all you can also set `insert_missing=true` on this operator.
