### ISSUE TITLE
http.post is blocking

### ISSUE THREAD

**Issue by Sveeeeeen** [savonet/liquidsoap#521]
Hello,

Do you have any way to avoid a http.post is blocking the whole application due to a "overloaded" webserver? I added a sleep to a PHP script an I received "must catch up xxx seconds" error in LS.

Unfortunately, I need the output of the request. If possible I would like to avoid to write a separate script which runs in a different thread.

**Comment by cryptiksouls** [comment]
If you add a sleep to your PHP script then you are delaying execution further, that's not going to help matters as the POST request is waiting for a response. There are many ways you can work around this, depending upon what exactly you are trying to do and on what server you are trying to do it.

Why are you reluctant to write another script? It would propbably make your life easier...
Do you have to use PHP? If so what does your PHP script code look like?
Could you use a socket connection instead?
Could you fork a curl process to obtain the response and register a harbor.http handler which it could post back to?
Could you redirect all output from the PHP script to a file and register a file.watch handler for liquidsoap to retrieve the output?
etc etc..

**Comment by toots** [comment]
If you need the output of the request in real time for your stream then I'm afraid that there's nothing that could be done. Otherwise, you can use `add_timeout` to run the function as a task which will free the main streaming thread and avoid the catchup issues.
