### ISSUE TITLE
Error installing liquidsoap with sdl support: Unbound module Sdlttf

### ISSUE THREAD

**Issue by itibet** [savonet/liquidsoap#522]
Hi,
I'm trying to add SDL support to liquidsoap (on Ubuntu 17.10).
I've first run
$ opam depext ocamlsdl
which resulted in installing libsdl1.2-dev.
Then ocamlsdl was succesfully installed, but recompilation of liquidsoap failed with the logs below.
Could anybody help?
Thank you
`
$ opam install ocamlsdl liquidsoap
[NOTE] Package ocamlsdl is already installed (current version is 0.9.1).
The following actions will be performed:
  ∗  install liquidsoap 1.3.3
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[liquidsoap] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

The following actions will be performed:
  ∗  install liquidsoap 1.3.3

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[liquidsoap] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of liquidsoap failed at "make".
Processing  1/1: [liquidsoap: rm]
=== ERROR while installing liquidsoap.1.3.3 ==================================#
 opam-version 1.2.2
 os           linux
 command      make
 path         /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3
 compiler     4.04.1
 exit-code    2
 env-file     /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/liquidsoap-19193-d2c37b.env
 stdout-file  /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/liquidsoap-19193-d2c37b.out
 stderr-file  /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/liquidsoap-19193-d2c37b.err
stdout
 [...]
 OCAMLOPT -c encoder_formats/ogg_format.ml
 OCAMLOPT -c encoder_formats/wav_format.ml
 OCAMLOPT -c encoder.ml
 OCAMLOPT -c tools/server_builtins.ml
 OCAMLOPT -c tools/sdl_utils.ml
 ../Makefile.rules:192: recipe for target 'tools/sdl_utils.cmx' failed
 make[2]: Leaving directory '/home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/src'
 ../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
 make[1]: Leaving directory '/home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/src'
 Makefile.rules:27: recipe for target 'all-subdirs' failed
stderr
 File "tools/sdl_utils.ml", line 54, characters 14-25:
 Error: Unbound module Sdlttf
 make[2]: *** [tools/sdl_utils.cmx] Error 2
 make[1]: *** [all-auto-ocaml-prog] Error 2
 make: *** [all-subdirs] Error 2

[ERROR] The compilation of liquidsoap failed at "make".
Processing  1/1: [liquidsoap: rm]
=== ERROR while installing liquidsoap.1.3.3 ==================================#
 opam-version 1.2.2
 os           linux
 command      make
 path         /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3
 compiler     4.04.1
 exit-code    2
 env-file     /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/liquidsoap-20815-d2c37b.env
 stdout-file  /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/liquidsoap-20815-d2c37b.out
 stderr-file  /home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/liquidsoap-20815-d2c37b.err
stdout
 [...]
 OCAMLOPT -c encoder_formats/ogg_format.ml
 OCAMLOPT -c encoder_formats/wav_format.ml
 OCAMLOPT -c encoder.ml
 OCAMLOPT -c tools/server_builtins.ml
 OCAMLOPT -c tools/sdl_utils.ml
 ../Makefile.rules:192: recipe for target 'tools/sdl_utils.cmx' failed
 make[2]: Leaving directory '/home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/src'
 ../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
 make[1]: Leaving directory '/home/mauro/.opam/4.04.1/build/liquidsoap.1.3.3/src'
 Makefile.rules:27: recipe for target 'all-subdirs' failed
stderr
 File "tools/sdl_utils.ml", line 54, characters 14-25:
 Error: Unbound module Sdlttf
 make[2]: *** [tools/sdl_utils.cmx] Error 2
 make[1]: *** [all-auto-ocaml-prog] Error 2
 make: *** [all-subdirs] Error 2

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install liquidsoap 1.3.3
No changes have been performed
`

**Comment by itibet** [comment]
Solved by running the following commands:
$ opam depext conf-sdl-mixer conf-sdl-image conf-sdl-ttf ocamlsdl liquidsoap
$ opam install conf-sdl-mixer conf-sdl-image conf-sdl-ttf ocamlsdl liquidsoap

**Comment by Infernion** [comment]
Would be good to add to documentation
