### ISSUE TITLE
REPORT: liquidsoap 1.3.3 on Ubuntu 16.04 (Orange Pi)

### ISSUE THREAD

**Issue by DJAnonimo** [savonet/liquidsoap#523]
Hello,

I've just installed Ubuntu 16.04. with a newer kernel than the on of the official site. With the official image I compiled liquidsoap without errors. 
And now with newer kernel...

```
git clone https://github.com/savonet/liquidsoap-full.git liquidsoap
cd liquidsoap
make init
make update
make clean
make
```
Error:
```
File "tools/rqueue.ml", line 1:
Error: Could not find the .cmi file for interface tools/rqueue.mli.
../Makefile.rules:192: recipe for target 'tools/rqueue.cmx' failed
make[3]: *** [tools/rqueue.cmx] Error 2
make[3]: Leaving directory '/home/orangepi/liquidsoap/liquidsoap/src'
../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
make[2]: *** [all-auto-ocaml-prog] Error 2
make[2]: Leaving directory '/home/orangepi/liquidsoap/liquidsoap/src'
Makefile.rules:27: recipe for target 'all-subdirs' failed
make[1]: *** [all-subdirs] Error 2
make[1]: Leaving directory '/home/orangepi/liquidsoap/liquidsoap'
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1

```

Anyway with tarball https://github.com/savonet/liquidsoap/releases/download/1.3.3/liquidsoap-1.3.3-full.tar.gz installed without error.

Btw I have a question... Do I need resample if im transcoding AAC 192 stream to aac+ 64. All streams are 44100Hz

Thank You

**Comment by toots** [comment]
Hi,

Not sure what the first issue is. You are probably missing some dev dependencies but I would need to see more logs.

As for resampling, liquidsoap will do it for you when needed!

Gonna close this for now, please re-open if you have more issues. All the best with your projects!
