### ISSUE TITLE
SSL Read error

### ISSUE THREAD

**Issue by nicktgr15** [savonet/liquidsoap#527]
Hi,

I'm running a `webcaster -> liquidsoap -> icecast` chain in docker containers and the setup was working fine for some time. I haven't changed anything in the chain but now when webcaster tries to connect to liquidsoap I get the following:
```
2018/02/09 14:18:15 [harbor:4] New client on port 8083: 172.17.0.1
2018/02/09 14:18:15 [harbor:4] Ssl.Read_error(1)
```
Any idea what `Ssl.Read_error(1)` is related to? I get this with chrome and firefox. With chrome the error is 
```
[harbor:4] Ssl.Read_error(5)
```
Mainly looking for directions on how to debug this.

Cheers,
Nik

**Comment by toots** [comment]
Hi,

Not sure about this at all. Have you checked your SSL certificates? Maybe some have expired?
