### ISSUE TITLE
Creating a handler for liquidsoap fallback

### ISSUE THREAD

**Issue by rihani** [savonet/liquidsoap#528]
I would like to know when liquidsoap has fallback to the emergency_playlist so that I can initiate a system script. perhaps there is a handler that can do this similar to on_blank(handler,radio),

here is my code,

```
#!/home/ubuntu/.opam/system/bin/liquidsoap
myplaylist = playlist("~/backup_playlist/playlist/Emergency-list.m3u",mode="normal")
backup_playlist = audio_to_stereo(myplaylist) 
liveset = input.http("http://listen.qkradio.com.au:8382/main_test.mp3")
radio = fallback(track_sensitive=false,
         [strip_blank(max_blank=120.,liveset), backup_playlist])
radio = on_blank(handler,radio)

 # Stream it out
output.icecast(
%mp3(bitrate=64),
host="localhost", port=8382, password="xxxxxxxx", 
mount="test.mp3",  radio)
```

**Update:**

the following code below does execute a system script however only when the script starts up, I would like however this to be executed every time a fallback is initiated

```
def fall()
   system("./scripts/pushover.py")
   backup_playlist
end

radio = fallback(track_sensitive=false,
         [strip_blank(max_blank=10.,liveset), fall() , security])
```

**Comment by toots** [comment]
Your solution isn't gonna work, `fall()` is called once and for all when creating the source. Instead, you should use a transition:
```
backup_playlist = audio_to_stereo(id="backup_playlist", myplaylist) 

def transition(old,new) = 
  if source.id(new) == "backup_playlist" then
    system("./scripts/pushover.py")
  end

  sequence([old,new])
end

radio = fallback(track_sensitive=false,
         transitions=[transition,transition,transition],
         [strip_blank(max_blank=120.,liveset), backup_playlist])
```

Gonna close here, feel free to follow-up on savonet-users@lists.sourceforge.net

**Comment by dtcooper** [comment]
@toots I'm noting my fallback sources, for example arg `new` in a `transition` function as being called `replay_metadata_NNNN` unless I call `fallback()` with `replay_metadata=false`, which I don't want to do. To make matters worse, if I abruptly disconnect from a harbor the `old` arg has a value as `empty_NNNN`.

I'm noting the log for the `fallback` is correct. Is there a way to actually get the names of the tracks transitioning, or otherwise not which source is actually playing in a `fallback`? Thanks!

**Comment by dtcooper** [comment]
Bump on this, a callback that has the new/old source without their names being chomped would be helpful. Currently, I'm using `source.is_active()` to infer this.

**Comment by toots** [comment]
Hey. Just seeing this. I see your issue, let me look at it.

**Comment by dtcooper** [comment]
@toots, while this an issue. I have a workaround that I'll post soon on this thread, so it's not urgent. :) thanks for looking, however!

**Comment by toots** [comment]
Cool. After looking at it I think that my initial solution was too weak. Relying on source IDs is not a good idea for many reasons. For instance, if you assign an ID to a source which is already used, then this ID will be changed to make sure source IDs are always unique at all time.

A most robust solution would probably require to monitor metadata being passed down and catch a particular one marking the backup source.
