### ISSUE TITLE
Liquidsoap freezes with some files - only when in daemon mode

### ISSUE THREAD

**Issue by mkonecny** [savonet/liquidsoap#53]
The script:

```
path = "/home/martin/tmp"
set("log.file.path", string.concat([path, "hang.log"]))
set("server.telnet", true)
set("server.telnet.port", 1234)
set("init.daemon.pidfile.path", string.concat([path, "hang.pid"]))

queue = request.equeue(id="queue")
output.pulseaudio(fallible=true, queue)
```

The file:
https://dl.dropbox.com/u/256410/airtime/rayj.mp3

Instructions:
## Part 1: Run as regular process

Run 

```
$ liquidsoap hang.liq
```

Telnet in and do

```
queue.push rayj.mp3
```

Notice music is playing.
## Part 2: Run as daemon

Run 

```
$ liquidsoap -d hang.liq
```

Telnet in and do

```
queue.push rayj.mp3
```

Liquidsoap process compiled from 36f750a is now frozen

**Comment by toots** [comment]
Hi,

Unfurtunately, this issue is so old that I don't think we'll be able to reproduce and/or fix in the current codebase. Closing here now..
