### ISSUE TITLE
MP3 Decoding problems

### ISSUE THREAD

**Issue by Power2All** [savonet/liquidsoap#531]
Hey,

I've been messing around a lot, and noticed, MP3 decoding with MAD is problematic.

> 2018/03/05 10:04:42 [lang:3] timeout --signal=KILL 45 pyponotify --connect --stream-id=1 --time=1520244282.72 &
> 2018/03/05 10:04:42 [threads:3] Created thread "wallclock_main" (2 total).
> 2018/03/05 10:04:42 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
> 2018/03/05 10:04:42 [decoder:3] Method "MAD" accepted "/music_nfs/stream2/Kawaii Loli Attack 4/DJ Sailor Moon - Kawaii Loli Attack 4.mp3".
> 2018/03/05 10:04:43 >>> LOG START

This stops restarting, when it hits a OGG file.
MP3 decoding is borked, tried Liquidsoap 1.1.1 and 1.3.3, both giving the same issues.

Anybody else know how to patch this ?

**Comment by toots** [comment]
Hi,

Could you explain more about your issue? Do you have a script (minimal if possible) to reproduce with `1.3.3`? Thanks!

**Comment by smimram** [comment]
This is bug report is getting old and lacking information, closing. Please reopen if the bug still applies.
