### ISSUE TITLE
AirTime/LiquidSoap not updating metadata on Icecast ?

### ISSUE THREAD

**Issue by Power2All** [savonet/liquidsoap#532]
Hi,

The IceCast server is not updating somehow.
When I force it through Icecast itself, it updates metadata, but through Airtime or forcing liquidsoap to sent metadata, it doesn't do anything.

**Comment by Power2All** [comment]
As example:

> 2018/03/05 15:43:47 [lang:3] Title: Back to the Moon (Psy-Trance-Goa)
> 2018/03/05 15:43:47 [lang:3] Artist: (Japan AniMix 2) Takedown

Here I make it show the Title and Artist:

I use the following to force update, and playing offline content:

> music = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/music_nfs/stream2"))
> security = single("/music_nfs/stream2/fallback.ogg")
> v = random(weights=[1],[music])
> default = fallback(track_sensitive=false, [v, security])
> 
> def update_meta(m) =
>     title = m["title"]
>     log("Title: #{title}")
>     artist = m["artist"]
>     log("Artist: #{artist}")
>     [("title","#{title}"),("artist","#{artist}")]
> end
> 
> default = map_metadata(update_meta, default)

This "worked" when I used normal Airtime 2.5.x series, but with Libretime I have some issues.
Anybody could point me out why Icecast is ignoring the meta update ?

**Comment by toots** [comment]
Hi,

I'm not sure if your bug applies to liquidsoap. It seems to be related to libretime instead. I'll close here for now, please re-open if that is indeed a bug with us.

Good luck with your projects.
