### ISSUE TITLE
lin_of_dB + interactive.float

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#536]
`out(amplify(lin_of_dB(interactive.float("test", 0.0), in())))`

```
At line 1, char 40-52:
  this value has type
    ()->_
  but it should be a subtype of
    float
```

I would expect that to succeed

**Comment by toots** [comment]
Hi,

Yes, that is a limitation of the (outdated) `interactive.float`. I'm gonna see what I can do about it.

Meanwhile, you can either compute `lin_of_dB` before setting the value through the server command or write your own server command that does it for you. Something like this:

```
def set_interactive_value(v) =
  v = lin_of_dB(float_of_string(default=0.,v))
  ret = server.execute("var.set test = #{v}")
  string.concat(separator="\n",ret)
end
```

**Comment by Yamakaky** [comment]
I ended up doing the dB -> lin conversion in the calling part, not in liquidsoap ^^

**Comment by smimram** [comment]
I don't think we can do much about this. Here is the way I would do that:
```
f = interactive.float("test", 0.0)
f = {lin_of_dB(f())}
s = amplify(f, in())
out(s)
```
