### ISSUE TITLE
Liquidsoap Gstreamer MPEG-TS Pipeline

### ISSUE THREAD

**Issue by abhilashkrishnan** [savonet/liquidsoap#540]
Can anybody please help me with Gstreamer MPEG-TS Audio and Video pipeline for UDP streaming?

**Comment by toots** [comment]
Hi,

Please redirect this to our mailing list at: savonet-users@lists.sourceforge.net. Hopefully someone should be able to help you there..

**Comment by Infernion** [comment]
@abhilashkrishnan have you figured out how to manage it?
