### ISSUE TITLE
Stuttering stream, CPU greater than 100% with video stream

### ISSUE THREAD

**Issue by comiconomenclaturist** [savonet/liquidsoap#542]
I am running Liquidsoap with the gstreamer output to nginx rtmp server. The output settings are as follows:

```
output.gstreamer.audio_video(
  video_pipeline=
    "videoconvert ! x264enc bitrate=2000 ! video/x-h264,profile=baseline ! queue ! mux.",
  audio_pipeline=
    "audioconvert ! voaacenc bitrate=128000 ! queue ! mux.",
  pipeline=
    "flvmux name=mux ! rtmpsink location=\"rtmp://127.0.0.1:1935/example/live live=1\"",
  s)
```
When I play this back, there is buffering/stuttering. The machine is a Quad-Core Intel Core i7 2.93 GHz and the GPU is NVIDIA Corporation G92 [GeForce GTS 240], although I'm not sure if Liquidsoap uses the explicitly uses the GPU for processing..

In any case, is there a way to get a smooth stream with this spec machine?

**Comment by toots** [comment]
Hi,

I'm not sure. Does this work smoothly when ran outside of liquidsoap, for instance using `gst-launch`?

**Comment by toots** [comment]
Hi,

There's been extensive work done on gstreamer recently. Are you able to test with the latest code? Let me know if you need instructions on how to do so.
