### ISSUE TITLE
Allow printing to a server connection

### ISSUE THREAD

**Issue by davehayes** [savonet/liquidsoap#544]
I was unable to find any print command that prints arbitrary text to a unix domain socket server connection. Thus I am unable to use the ```on_end``` callback to print a message to the server when the song is about to change. This forces my other software to poll the server repeatedly rather than wait for an IO event. 

Is it possible to add a command that will print text to a server connection?

**Comment by toots** [comment]
Hi,

Would you mind describing the functionality a bit more? Are you talking about an existing server connection or a connection you would also open and close?

**Comment by davehayes** [comment]
So here's the basicis of the script I'm using:
```
set("log.file.path","liquidstream.log")
set("log.stdout", true)
set("server.socket", true)
set("server.socket.path", "/tmp/liquidserver")
set("server.socket.permissions",0o660);

defaultsource = blank(duration=15.0)
serverqueue = request.queue(id="mainreq")
serverqueue= amplify(1., override="REPLAYGAIN_TRACK_GAIN", serverqueue)
content = fallback([ serverqueue, defaultsource ])
crossplay = smart_crossfade(content)
output.icecast(
  %vorbis(channels=2, quality=0.3),
  ...
)
```

So I have an external program that opens the unix domain socket that this script created. Right now, in this external program, I push commands to it and read responses using a simplistic model (no select multiplexing yet, etc.). At the moment, due to this simple model, I poll liquidsoap through this socket to see how big the song queue is and how long the current song has left to play. 

What I'd like to accomplish is to move to an event driven model. To do that, I have to somehow get the `on_end` callback to send a message to my external program everytime the currently playing song ends. To do that, I have to have a way to print arbitrary text to the unix domain socket from within that callback. Then I can move away from polling liquidsoap and become purely event driven. 

Does this help?

**Comment by toots** [comment]
Done now! See: http://www.liquidsoap.info/doc-dev/server.html

**Comment by davehayes** [comment]
Awesome! I like the condition variable stuff too. Thank you!
