### ISSUE TITLE
fdkaac encoder produces strange audio on ARM

### ISSUE THREAD

**Issue by XorgMC** [savonet/liquidsoap#556]
When using the FDKAAC encoder on ARM Linux, the generated audio (stream) sounds really horrible, you can hear it here: https://youtu.be/iUUqTKpv5vI
I've tried it on an Odroid XU4 and on an Odroid U3 - both produce the same horrible audio. I've installed LiquidSoap from OPAM on both devices (XU4 1.3.3; U3 1.3.1). The CPU isn't overloaded, so that should not be the cause. The XU4 uses Ubuntu 16.04, the U3 uses Debian Jessie.
If I run LiquidSoap on an x86 computer (also installed from OPAM, also 1.3.3), the generated audio/stream sounds totally fine.

Script used:
```
set("init.daemon",false)
set("log.stdout",true)
set("log.file",false)
set("log.level",4)

eins = "http://webstream.radioeins.com/radio-eins.mp3"

inputa = mksafe(input.http(eins))
inputb = mksafe(input.http("http://webstream.galaxy-oberfranken.de/galaxy-oberfranken.mp3"))

one = ladspa.bass_treble(drop_metadata(inputa), amplifier=1.0, bass=0.4, treble=1.8)
two = ladspa.bass_treble(drop_metadata(inputb), amplifier=1.0, bass=0.4, treble=1.8)

output.icecast(%opus(channels=2, samplerate=48000, bitrate=56, signal="music"), mount="/galaxy", host="192.168.178.187", port=8080, password="...", two)
output.icecast(%fdkaac(channels=2, samplerate=44100, bitrate=48, afterburner=true, aot="mpeg4_he_aac_v2", sbr_mode=true), mount="/eins", host="192.168.178.187", port=8080, password="...", one)
```

The opus stream sounds fine on both ARM and x86.

**Comment by toots** [comment]
Hi @XorgMC,

Unfortunately, there might not be much that we can do here. We use an external library for FDK-AAC. 

I suggest that you report the issue with `fdk-aac`. Meanwhile, I'll close our issue here.

Good luck,
Romain
