### ISSUE TITLE
Long delay when applying special with smooth_add

### ISSUE THREAD

**Issue by ajitam** [savonet/liquidsoap#557]
Hello,

**What I would like to do:**
I would like to have stream (which is actually a silence) and ability to push specific audio file at specific time on top of that stream. So basically I want to have simple device in my home on which I can "push" specific audio at specific time.

**What I did**
This is my `liq` script so far

```
#!/usr/bin/liquidsoap

set("server.telnet", true)

special = request.queue(id="special")

# The file source
s = playlist("/path/to/silence/ogg", conservative=true)
s = smooth_add(normal=s,special=special)

output.icecast(%vorbis,
		id="icecast",
               	fallible=true,
		mount="static.ogg",
               	host="localhost",
		password="xxx",
               	s)
```

so `/path/to/silence/ogg` is folder with 3 `ogg` files which a just very quite static

then I `telnet 127.0.0.1 1234` and I execute command `special.push /path/to/audio.ogg`

This works but delay between command execute and audio being played is about ~15sec. In log I can see that file is accepted immediately.

I noticed that if I stream music instead of static the delay is not that long (~5sec).

**Questions**
**Q1:** How can I "remove" this delay?
**Q2:** (maybe even more important) Is there a better way of accomplish this task with liquidsoap?

**Comment by toots** [comment]
Hi,

I believe that the `delay` parameter in `smooth__add` should help:
```
# @param ~delay   Delay before starting the special source.
```

I'm gonna close this issue since it's not related to the code. Feel free to follow-up at savonet-users@lists.sourceforge.net  and all the best with your projects!
