### ISSUE TITLE
I need assistance with live cut-ins

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#558]
Liquidsoap creates a source from a playlist I have defined, this is called "radio"
I also have another http input which is actually 24/7 called "newsinput"
The final source is called "final"

So basically when the times reaches 12:00 I would like "final" to switch to "newsinput" as the source and then at 12:15 I want it to switch back to "radio" until the next day.

Now this sounds easier enough but I have not been able to accomplish because the 24/7 stream is    (as suggested) 24/7 so I have tried using switch() to make the audio stream from "newsinput" blank when the time is not 12:00-12:15

I would also like track_sensitive=false if this is possible (in this scenario)

Any help would be much appreciated!
Thanks

**Comment by Niall7459** [comment]
bump

**Comment by Niall7459** [comment]
help my boss will disipline me

**Comment by 5chdn** [comment]
What have you tried so far? switch would be my first idea.

**Comment by Niall7459** [comment]
I have tried with switch and fallback. Both of which did not do the job. Because they WAIT for the stream to finish before switching. So it never switches because the stream is always on. Unless switch() has track_sensitive but I could not find this

**Comment by 5chdn** [comment]
Ah okay. What I did in such a case was listening for a live mount point in icecast to pop up and switch over immediately. like:

```
# some output
ogg = output.icecast(
  %vorbis.cbr(
    samplerate=44100,
    channels=2,
    bitrate=128
  ),
  host="127.0.0.1",
  port=8000,
  public=true,
  password="asdf",
  mount="station"
)

# some playlist
musiclist = smart_crossfade(
  normalize(
    mksafe(
      playlist(
        reload=21600,
        reload_mode="seconds",
        mode="random",
        "/path/to/playlist.m3u"
      )
    )
  )
)

# listen for news
news = input.http(
  "http://localhost:8000/news",
  buffer=9.9,
)

radio = fallback(
  track_sensitive=false,
  [
    news,
    musiclist
  ]
)

# stream it
ogg(radio)
```

**Comment by autonarcosis** [comment]
Here is an example of a fallback switch with track sensitive false and timed shows.  The key part would be to set the news for 12h-12h15 (minutes).  What this does is; play any requests pushed to the request queue immediately, for any of the specified times immediately switch to that playlist (don't wait for the current track to end) then once the specified time ends immediately fallback to the rotating playlist (don't wait for the current track to end), play a spot over the currently playing track on the top of the hour and some seconds.

`scheduler=add([fallback(track_sensitive=false,[

	#Play Requests
	request.queue(id="request"),

	#Start Rotation Of Playlists
	switch(track_sensitive=false,[
	
	#Play Show1
	({ 0h-1h }, show1),

	#Play Show2
	({ 1h-4h }, show2),

	#Crevice Memorial Show
	({ 7w and 16h20-17h55 }, show4),

	#Play Show3
	({ 14h-17h }, show3),

	]),
	#Play Normal Mix
	(rotating
	),
	]),
	#Add Spots on the hour over current track.
	switch([({ 0m and 0s-5s },delay(5.,spots))])])	
`

**Comment by toots** [comment]
What's the status on this issue?

**Comment by Niall7459** [comment]
Solved with switch and track_sensitive=false parameter.

**Comment by toots** [comment]
Awesome, thanks!
