### ISSUE TITLE
Mp3 supplied into liquidsoap not playing

### ISSUE THREAD

**Issue by SoFresher** [savonet/liquidsoap#564]
the mp3 files supplied to the .liq file are not playing ...
here is the content of the .liq file
//!/usr/bin/liquidsoap

//Log dir
 set("log.file.path","/home/dir/shoutcast/log/liquidsoap.log")

//enable daemon mode
set("init.daemon",true)

// do not create a pid file
set("init.daemon.pidfile",false)

//Music
myplaylist = mksafe(playlist("/home/dir/shoutcast/mp3s"))

//Start building the feed with music
radio = myplaylist

output.shoutcast(%mp3,
        host = "localhost",
        port = 8130,
        name = "test test",
        password = "password3",
        radio
)`
when I started the server, i tried to test, the player was moving (i.e the playing time was increasing) but no sound/audio was heared
Any applicable solution to this?
Thanks

**Comment by StormdragonDesigns** [comment]
What's the output of `liquidsoap --list-plugins`?

**Comment by toots** [comment]
I think what @StormdragonDesigns was alluding to is wether you have `mp3` decoding enabled via `libmad`. How did you install liquidsoap?

**Comment by toots** [comment]
Hi! I really think you're just missing the `mp3` decoder. Gonna close this one, let me know if you need more info.
