### ISSUE TITLE
Force playlist restart after updating

### ISSUE THREAD

**Issue by Raifeg** [savonet/liquidsoap#565]
Hi.
I have a playlist, which fully renews sometimes.
What I need: if playlist was changed, immediately restart playing from beginning of playlist.
playlist.once (reload_mode = "watch") almost do this, but it have not "track_sensitive" parameter, so playing new playlist happened only after current track ends.

How can I realize this behavior?

Thanks in advance,
Pavel.

**Comment by toots** [comment]
Hi,

That's an interesting feature. I'm gonna look at implementing a `on_load` function for playlists then you could use it to execute `source.skip` on the playlist. Hopefully for the next release.

**Comment by smimram** [comment]
`on_reload` is present in current implementation of `playlist`.
