### ISSUE TITLE
can liquidsoap stream the audio output?

### ISSUE THREAD

**Issue by Oliviercreativ** [savonet/liquidsoap#566]
Hello,
I use liquidsoap on a raspberry Pi with a mini USB sound card.
I can use my microphone without problem but I would rather that the stream takes the audio output instead of the microphone input. So for the moment I mean the microphone and not the music at all. If you have an idea ? Thank you

Best regards
Olivier

**Comment by StormdragonDesigns** [comment]
You can make an ALSA loopback device that will allow you to capture audio sent to it. You can also play that back into your regular output.
https://unix.stackexchange.com/questions/127567/recording-audio-from-web-based-audio-player-using-alsa-loop-device
http://alsa-project.org/main/index.php/Matrix:Module-aloop

**Comment by Oliviercreativ** [comment]
Hello, sorry for my late response, I will try the tutorials you have proposed.

Thank you

**Comment by toots** [comment]
Or you can plug a jack from the output do the input ;-)

Gonna close this since this isn't a bug. Don't hesitate for forward the conversation to savonet-users@lists.sourceforge.net
