### ISSUE TITLE
Make playlist not pick the same file until it reloads

### ISSUE THREAD

**Issue by Parradox27** [savonet/liquidsoap#567]
Hello there, I am trying to create a playlist that would play all files randomly, but without any of them repeating until the playlist starts all over again. I have tried playlist.once, which plays all files, it does pick them randomly, but it doesnt restart the playlist once its done. Classic playlist isnt ideal because it doesnt "care" about what it played already and some songs may repeat (i saw check_next, however that one also isnt ideal). I am sorry if this has been already answered, I havent found anyone with this issue. Is this even possible?

**Comment by toots** [comment]
Unless I've missed something, the `"randomize"` mode does exactly what you describe and is the default:
```
     shuffle the playlist each time it is loaded, and play it in this order
     for a whole round ("randomize" mode)
```
