### ISSUE TITLE
CentOS 7 Compilation Issue

### ISSUE THREAD

**Issue by Aniruddh-J** [savonet/liquidsoap#573]
Hello,

I am trying to compile liquidsoap-1.3.3 on CentOS 7 and I am getting following error:

```
[root@test liquidsoap-1.3.3]# make
which: no gsed in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
for i in ; do make -C $i || exit 1; done
```

gsed is already installed in the system.

**Comment by toots** [comment]
Hi,

Have you tried installing via `opam`? This is our recommended way of doing it now.

**Comment by smimram** [comment]
Quite old bug lacking feedback, and `opam` is the standard way of installing, closing. Please reopen if you still have problems.
