### ISSUE TITLE
pass and retrieve custom arguments to liquidsoap script

### ISSUE THREAD

**Issue by TheFrankman** [savonet/liquidsoap#574]
I have read the documentation with regards to getopts but it's been no help. I'm sure the answer is very simple.

I'm trying to do something like this : 

`liquidsoap -ta foo -tb bar test.liq`

```
#test.liq
triggerA = getopt('-ta')

if triggerA == 'foo' then
  print("trigger A")
end
```

But this gives error : 
```
liquidsoap: unknown option '-ta'.
```

If i use an option that does exist, let's say `-t` I have have the following issue 

`liquidsoap -t foo test.liq`

```
triggerA = getopt('-t')

if triggerA == 'foo' then
  print("trigger A")
end
```
Result : 

```
At line 1, char 4-3: the variable foo used here has not been previously
  defined.
```
No idea what's going on. How's that documentation re-write coming along ?

**Comment by toots** [comment]
You should pass your arguments after the `--` marker. Otherwise liquidsoap thinks those applies to the `liquidsoap` binary. Try:
```
liquidsoap test.liq -- -ta foo -tb bar
```

**Comment by TheFrankman** [comment]
thanks @toots
