### ISSUE TITLE
Could not find the .cmi file for interface tools/rqueue.mli (compile/source)

### ISSUE THREAD

**Issue by ArvyRogerio** [savonet/liquidsoap#576]
Note: I've tried everything using Opam, so I decided to compile from source. 

I'm trying to install LiquidSoap from source because I need AAC+ support (fdk-aac). I did tests with Ubuntu 18.04, Debian 9 and CentOS 7.5, all giving the same error.

After ./configure (that runs ok), when I run "make":

File "tools/rqueue.ml", line 1:
Error: Could not find the .cmi file for interface tools/rqueue.mli.
../Makefile.rules:192: recipe for target 'tools/rqueue.cmx' failed
make[3]: *** [tools/rqueue.cmx] Error 2
make[3]: Leaving directory '/root/liquidsoap/liquidsoap/src'
../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
make[2]: *** [all-auto-ocaml-prog] Error 2
make[2]: Leaving directory '/root/liquidsoap/liquidsoap/src'
Makefile.rules:27: recipe for target 'all-subdirs' failed
make[1]: *** [all-subdirs] Error 2
make[1]: Leaving directory '/root/liquidsoap/liquidsoap'
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1

I'm stuck here. I did everything possible, installed all libs (apt-get) and ocaml packages. I'm sure that nothing is missing. What can I do? Thank you.

**Comment by toots** [comment]
Hi,

Sorry that you're having troubles. We always and strongly recommend using `opam` but let's try to debug your issue.

What steps have you followed when installing from source?

**Comment by ArvyRogerio** [comment]
I just did http://www.liquidsoap.info/doc-dev/build.html

No dependencies problems. but the error
"Error: Could not find the .cmi file for interface tools/rqueue.mli."
Looks like a file missing somewhere on the source, because the same error occurs on CentOS, Ubuntu and Debian.

**Comment by rngnrs** [comment]
The same problem appears on Debian Sid. I followed the instruction that was mentioned above.
This error appears after "making" all dependencies and `OCAMLOPT -c` some liquidsoap code.

**Comment by toots** [comment]
I've compile liquidsoap on a lot of platforms lately. Something must be missing the y'all steps. Can you guys write down each step one by one so we can review them? Thks!
