### ISSUE TITLE
mono to stereo azuracast

### ISSUE THREAD

**Issue by Blazedallup** [savonet/liquidsoap#577]
hi i am new to github and azuracast , so i will apologize now.
i cant get my mono files to play. i have looked up audio_to_stereo but i have no idea where to change this 
everywhere i look refers to it but noone explains what file or location it is in PLEASE HELP!
Thank you for you're time.

**Comment by SlvrEagle23** [comment]
@Blazedallup Just happened to be visiting the Liquidsoap repository when I noticed your issue. It looks like your question is specifically about AzuraCast, which indeed uses Liquidsoap under the hood, but is an independent project with its own repository.

Feel free to [create a new issue](https://github.com/AzuraCast/AzuraCast/issues/new/choose) on the AzuraCast repository, and I'd be happy to instruct you further on where to find the custom Liquidsoap configuration inside the web interface.
