### ISSUE TITLE
[URGENT] ERROR: RTMP_Connect0, failed to create socket. Error: 24

### ISSUE THREAD

**Issue by GBraga23** [savonet/liquidsoap#579]
```
ERROR: RTMP_Connect0, failed to create socket. Error: 24
```

What is the problem???

**Comment by toots** [comment]
Hi,

Could you share more details:
- Liquidsoap version and how you installed it
- Script extract
- Log extract

Thanks!

**Comment by toots** [comment]
Hi,

We've been doing extensive work on gstreamer lately and it appears to work fine now. Please test with the latest code and gstreamer `1.14.2` or above and re-open if needed. Thanks!
