### ISSUE TITLE
Script is down if http.input have not stream

### ISSUE THREAD

**Issue by dekardkrr** [savonet/liquidsoap#585]
i have a script:
set("harbor.bind_addr","0.0.0.0")
file= single("/home/pi/m/some_file.mp3")
all_in_for_operator = mksafe(
                        audio_to_stereo(
                                input.http(
                                id="local_operator_in",
                                debug=false,
                                "http://192.168.1.100:8002/live1"
)))
security=blank()
all_in = amplify(3.0,all_in_for_operator)
radio = fallback(track_sensitive = false,
                [all_in, file, security])
output.alsa(
        fallible = true,
        device="pcm.out2",
        buffer(radio)
)

If http.input source is active on remote server then alsa send data "all_in".
If http.input source is down on remote server then source "file" not play. And log contain:
[source:4] Garbage collected empty_6020.
[local_operator_in:4] Connecting to <http://192.168.1.100:8002/live1>...
 [local_operator_in:4] Connection failed: Http.Unix_transport.Socket
 [local_operator_in:4] Connecting to <http://192.168.1.100:8002/live1>...
 [local_operator_in:4] Connection failed: Http.Unix_transport.Socket
 [local_operator_in:4] Connecting to <http://192.168.1.100:8002/live1>...
 [local_operator_in:4] Connection failed: Http.Unix_transport.Socket
 [local_operator_in:4] Connecting to <http://192.168.1.100:8002/live1>...
 [local_operator_in:4] Connection failed: Http.Unix_transport.Socket

**Comment by toots** [comment]
You should not use `mksafe` on the `all_in_for_operator` source. That makes the source infallible so the `fallback` never switches away from it..
