### ISSUE TITLE
Firefox Quantum doesn't like FDK_AAC streams

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#587]
Stream plays fine in chrome, however in firefox it hangs on a metadata error related to this 
https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1448762

**Comment by toots** [comment]
> I understand your concerns, however those files are technically invalid. Rejecting them is the right thing to do.

Oh my, Jean-Yves haha, you have no idea how many people you might have infuriated with this haha.

I'm not sure that there's much we can do here, though. This bug would be better reported to `fdk-aac` I believe..
