### ISSUE TITLE
Add support for HTTP Live Streaming (HLS)

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#59]
We should add support for HTTP Live Streaming, ie make the following work:

```
s = input.http("http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8")
output.pulseaudio(s)
```

Basically, these are simply m3u playlists of small segments of the stream, so it should work out of the box, but it doesn't :)
- A simple example can be found here: http://www.longtailvideo.com/html5/
- Apple has lots of resources about the subject: https://developer.apple.com/resources/http-streaming/
- The RFC: http://tools.ietf.org/html/draft-pantos-http-live-streaming-10

Ideally, we should also be able to generate such streams.

**Comment by mylselgan** [comment]
Hi, please check the following link, It's a 100% working audio-only link but not working with gstreamer.hls
http://airlive.nic.in/hls-live/livepkgr/_definst_/raagam/raagam.m3u8
