### ISSUE TITLE
Restart Playlist on Harbor Disconnect

### ISSUE THREAD

**Issue by Pelican104** [savonet/liquidsoap#590]
Really enjoying using Liquidsoap. I have a set up where we are relaying a number of external sources via harbor inputs. 
When the harbor source disconnects the default playlist kicks back in, but it restarts from wherever it had last got up to. Is there  a way of making it restart from the first item in the playlist?

Thanks

**Comment by smimram** [comment]
Yes you should be able to reload the playlist (`playlist.reloadable`) with the `on_connect` function of `input.harbor`.
