### ISSUE TITLE
Problem with using the file.watch() function

### ISSUE THREAD

**Issue by Ruben1836** [savonet/liquidsoap#592]
Hello,
i want to make my liquidsoap sript reacting to a Change on a specific file to change the source its streaming from. But i have a problem with the file watch function, because it returns a "--> unit" and i cant find "unit" in the documentation. 

What is "unit" and how can i use the file.watch() function to change the source its streaming from?

Thanks

**Comment by gilou** [comment]
Hi,
You may want to share a bit of your script if you need help. unit is the "void" of OCaml, meaning it doesn't return anything or so.

**Comment by smimram** [comment]
This bug is a request for help and lacks feedback. Closing.
