### ISSUE TITLE
Is there a function to normalize the audio volume.

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#595]
Some songs are louder/quieter than others.

I've used code but it hasn't worked for me.
![screen shot 2018-08-13 at 16 59 34](https://user-images.githubusercontent.com/9781846/44043262-4bf9547c-9f1a-11e8-8b0e-4916ff67cc48.png)
This does not seem to keep tracks at the same level for me

**Comment by wnolfm** [comment]
http://tap-plugins.sourceforge.net/ladspa/limiter.html

Might help you. When I get near my config I can post what I'm using. 

@toots do you have any insight on this one?

**Comment by toots** [comment]
The standard method in liquidsoap is described here: http://www.liquidsoap.info/doc-1.3.3/replay_gain.html

Feel free to follow-up on savonet-users@lists.sourceforge.net if y'all need more information!

**Comment by Niall7459** [comment]
Update on this. It does not seem to be working, Should be apply the replay gain before any crossfades. A lot of songs still seem to have different volumes.

Regards

**Comment by toots** [comment]
Are you able to test with the most recent `master` or `1.4.0-beta1`?

**Comment by Niall7459** [comment]
I believe I’m running the latest version from opam package manager. I can try with a newer version, should the amplify be placed before or after any crossfades?

**Comment by toots** [comment]
Ok! The only difference is that with the recent `master`, the replay gain information is extracted using only one binary, `ffmpeg`. 

Yes, amplification adjustments should be applied before crossfades. I believe that also recent `master` should have a log to check that amplification has been applied.

**Comment by Niall7459** [comment]
Alrighty, I will try moving the amplify and see if that makes an improvement.

**Comment by Niall7459** [comment]
I have moved the amplify before the cross fade statements, it is still after any switch statements though. I don’t believe there’s been an improvement. Is it possible to install the 1.4.0 version using Opam? 

Thanks.

**Comment by toots** [comment]
Yes:

```
git clone https://github.com/savonet/liquidsoap.git
cd liquidsoap
opam pin add .
```

You might also need other packages if they have a pending release. At least `ocaml-flac` if you are using it. Same procedure as above applies.

Let us know how it works for you. Also, make sure you enable replay gain across the board:
```
enable_replaygain_metadata()
```

**Comment by smimram** [comment]
No answer for a long time with a solution, closing. Feel free to reopen if needed.
