### ISSUE TITLE
Dynamically loaded fdk-aac encoder doesn't work.

### ISSUE THREAD

**Issue by tzumbrunnen** [savonet/liquidsoap#598]
I just did some first tests with the new 1.3.3 unstable package. after the announcement in #398 ( kudos to @paddatrapper )

Using fdkaac as encoder gives me the "No encoder found for that format" message.
Did I missed something during the installation or is this encoder removed for some reason I dont remember.

cheers
tom

**Comment by paddatrapper** [comment]
Unfortunately the fdk-aac encoder is licenced under a non-free license and thus is in the Debian non-free repo (https://tracker.debian.org/pkg/fdk-aac). As such, I can't include it in the liquidsoap package without placing liquidsoap in contrib. As I prefer to keep liquidsoap in main, fdk-aac encoder support is not built into the package.

I will document that in the Debian package for the next release

**Comment by toots** [comment]
I haven't tested it in a while but the `libfdkaac-ocaml-dynlink` should actually provide a dynamically loaded `fdk-aac` encoder for `liquidsoap`. As far as I can remember it was designed so that just installing it would enable the encoder in liquidsoap. Anyone care to test and report? Thks!

**Comment by toots** [comment]
So, it looks like the only thing that's missing to make it work is an update of `ocaml-fdkaac` in Debian. Once this is done, `liquidsoap` should be able to pick it up. Gonna close here, @paddatrapper feel free to re-open if that doesn't fix the issue.

**Comment by paddatrapper** [comment]
@toots - does `liquidsoap` need rebuilding with some option/dependency to use `libfdkaac-ocaml-dynlink` or does `ocaml-fdkaac` (updating and moved to contrib) sort that out automatically?

**Comment by toots** [comment]
No rebuild needed for `liquidsoap`. It will look into `/usr/lib/ocaml/fdkaac/` for the dynlink module. It's currently failing because the `ABI` is incompatible.

**Comment by paddatrapper** [comment]
Ah ok cool. I shall update that in the next week or so then

**Comment by paddatrapper** [comment]
New version is uploaded into unstable

**Comment by toots** [comment]
It works!
```
2018/08/16 16:11:01 [dynamic.loader:3] Loaded dynamic fdkaac encoder from /usr/lib/ocaml/fdkaac
```
Awesome guys!

**Comment by anisakharov** [comment]
2019/03/24 04:33:53 [dynamic.loader:3] Error while loading dynamic fdkaac encoder at /usr/lib/ocaml/fdkaac
Liquidsoap 1.3.6
install of OPAM
What version should I put to make fdkaac? For almost a week I can not configure anything

**Comment by toots** [comment]
Hi,

If you are installing via `opam` you should be able to enable built-in fdkaac support via:
```
opam install fdkaac
```

**Comment by kmahelona** [comment]
Hello,

I'm getting these errors on Ubuntu 19.10,
```
[dynamic.loader:3] Error while loading dynamic fdkaac encoder at /usr/lib/ocaml/fdkaac
[dynamic.loader:3] error loading shared library: /usr/lib/ocaml/fdkaac/fdkaac.cmxs: undefined symbol: aacEncoder_GetParam
[dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
```

The problem is `/usr/lib/ocaml/fdkaac/fdkaac.cmxs: undefined symbol: aacEncoder_GetParam` and I'm wondering if that's an incompatible versions problem?

**Comment by toots** [comment]
Hi @kmahelona! In order to help I think I'd need a little more context:
- How are you installing liquidsoap?

**Comment by mailinglists35** [comment]
getting this on ubuntu 22.04

what packages am I missing?

````
$ dpkg -l | egrep 'liquid|opam|fdk'
ii  fdkaac                               1.0.0-1build1                           amd64        command line encoder frontend for libfdk-aac
ii  libfdk-aac2:amd64                    2.0.2-1                                 amd64        Fraunhofer FDK AAC Codec Library - runtime files
ii  libfdkaac-ocaml                      0.3.2-1build2                           amd64        OCaml interface to the fdkaac library -- runtime files
ii  libfdkaac-ocaml-dynlink              0.3.2-1build2                           amd64        OCaml interface to the fdkaac library -- dynamically load
ii  liquidsoap                           2.0.2-1build2                           amd64        audio streaming language

````

**Comment by KevGP** [comment]
I can't get it to work either.
Liquidsoap says the fdkaac encoder is available when I enter "info liquidsoap", but fails to start and complains about unsupported format when I enter "liquidsoap <script file>".



If I run apt-get remove liquidsoap, the daemon stops working. But I did install via Opam. I think I have Liquidsoap on my system twice?

**Comment by rmens** [comment]
> getting this on ubuntu 22.04
> 
> what packages am I missing?
> 
> ```
> $ dpkg -l | egrep 'liquid|opam|fdk'
> ii  fdkaac                               1.0.0-1build1                           amd64        command line encoder frontend for libfdk-aac
> ii  libfdk-aac2:amd64                    2.0.2-1                                 amd64        Fraunhofer FDK AAC Codec Library - runtime files
> ii  libfdkaac-ocaml                      0.3.2-1build2                           amd64        OCaml interface to the fdkaac library -- runtime files
> ii  libfdkaac-ocaml-dynlink              0.3.2-1build2                           amd64        OCaml interface to the fdkaac library -- dynamically load
> ii  liquidsoap                           2.0.2-1build2                           amd64        audio streaming language
> ```

I have the exact same problem. I prefer not to self-compile software and use the packages from the OS vendor. Liquidsoap doesn't seem to pick up fdkaac on Ubuntu 22.04 or Debian 11. Is there something wrong with the packages provided by these OS'es or are we doing something wrong? (cc @toots).

**Comment by paddatrapper** [comment]
Dynamic linking was disabled in ocalm-fdkaac, so the Debian and Ubuntu packages can no longer be linked at runtime. See https://github.com/savonet/ocaml-fdkaac/issues/5

**Comment by rmens** [comment]
For who lands here from Google (like I did). Installing the `.deb` package from Savonet Github seems to work with fdkaac. The package that ships with Debian and Ubuntu does not.

This is with the package from Savonet Github (the encoder works):
```
$ dpkg -l | egrep 'liquid|opam|fdk'
ii  fdkaac                         1.0.0-1                        amd64        command line encoder frontend for libfdk-aac
ii  libfdk-aac2:amd64              2.0.1-1                        amd64        Fraunhofer FDK AAC Codec Library - runtime files
ii  libfdkaac-ocaml                0.3.2-1                        amd64        OCaml interface to the fdkaac library -- runtime files
ii  libfdkaac-ocaml-dynlink        0.3.2-1                        amd64        OCaml interface to the fdkaac library -- dynamically load
ii  liquidsoap                     1:2.1.1-debian-bullseye-1      amd64        audio and video streaming language
``` 

```
$ liquidsoap --list-plugins | grep -i FDKAAC
 + AAC/FDKAAC/BUILTIN
```

This is with the package from Ubuntu 22.04 (the encoder is not enabled):

```
$dpkg -l | egrep 'liquid|opam|fdk'
ii  fdkaac                               1.0.0-1build1                           amd64        command line encoder frontend for libfdk-aac
ii  libfdk-aac2:amd64                    2.0.2-1                                 amd64        Fraunhofer FDK AAC Codec Library - runtime files
ii  libfdkaac-ocaml                      0.3.2-1build2                           amd64        OCaml interface to the fdkaac library -- runtime files
ii  libfdkaac-ocaml-dynlink              0.3.2-1build2                           amd64        OCaml interface to the fdkaac library -- dynamically load
ii  liquidsoap                           2.0.2-1build2                           amd64        audio streaming language
```

```
$ liquidsoap --list-plugins | grep -i FDKAAC
   Audio encoder. Can be one of: "fdkaacenc", "voaacenc"
    "fdkaacenc"
```

**Comment by paddatrapper** [comment]
It works because it links to fdkacc at build time, which isn't allowed within Debian and Ubuntu due to licensing. The workaround was to link at runtime, but that was disabled and no longer works

**Comment by rmens** [comment]
Thanks for the clear explanation @paddatrapper

**Comment by toots** [comment]
Hi all,

Thanks for the investigation and updates. From our perspective, dynamic loading was an interesting solution back in the days where we didn't have `opam` and CI-built packages. It provided an easy solution to work around the linking limitations offered by debian and other distributions.

Fast forward to nowadays, our primarily means of installing `liquidsoap` are:
* `opam` installation
* `docker` images
* Custom-built packages for a wide variety of distributions

These choices are meant to provide the widest array of installation options while minimizing the work on our end. Both @smimram and myself have been active debian developers/packagers in the past and we have nothing but appreciation for the project. However, in order to optimize our available time, the dynamically loaded encoder was disabled in the code at some point in the past.

If there is a loud need for it, we would certainly reconsider that option but, for now, this is where it is at.

I'm about to look at re-enabling the dynamic module in `ocaml-fdkaac`, though, in case that can be helpful. c.f. https://github.com/savonet/ocaml-fdkaac/issues/5
