### ISSUE TITLE
Random playlists

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#600]
Okay this is genuinely annoying although coincidence.

I have a playlist of around 200 songs at the moment, yet at the same time i can have the same song play withing three songs such as:

1. Song 1
2. Song 2
3. Song 1

etc.

Sometimes the same songs are more common. Can we get a system to check if the song was played and not play the same ones if all the songs have not been played during a cycle.

Thnaks

**Comment by gilou** [comment]
You can use the randomize mode to avoid this, or check_next to disallow tracks, I'm working on such a feature based on filename, but you can implement whatever you want with check_next

**Comment by Niall7459** [comment]
How can I use check_next I can’t find documentation for its use. Thanks.

**Comment by gilou** [comment]
it's just a parameter to playlist(), it must return a boolean telling liq if it can let the track be played or skip it. I started writing one here: https://gist.github.com/gilou/43133d2619202791e153211471aff6a1#file-functions-liq-L26-L97 that might be interesting.

**Comment by Niall7459** [comment]
Okay thanks
