### ISSUE TITLE
Confused about Liquidsoap

### ISSUE THREAD

**Issue by alexnya** [savonet/liquidsoap#602]
I'm a little confused about using liquidsoap. Can anyone explain to me how to use it to stream video to my Icecast server? Also is there a web interface for Liquidsoap?

Thank you.

**Comment by gilou** [comment]
Hi,
There is a bit of documentation explaining the video part of liq here: http://www.liquidsoap.info/doc-1.3.3/video.html
Liq is a scripting language allowing you to describe what you want it to do. There are a few web front-ends for liq, but I don't know of any focusing on the video part.

**Comment by alexnya** [comment]
So do I have to put those commands in a script and then run it or could I run each line directly on terminal?

**Comment by gilou** [comment]
You write a .liq file with the commands in it, and start it using `liquidsoap xxx.liq` (or use a hashbang, and start the script directly)

**Comment by alexnya** [comment]
Ok here is my test.liq file

source = single("test.avi")

output.icecast(
        %ogg(%theora(quality=25,width=320,height=240),%vorbis),
        host="localhost",
        port=8000,
        password="hackme",
        mount="/videostream",
        source)

When I trying running it using liquidsoap test.liq I get a message saying 
Invalid value at line 1, char 17-26:
  Could not get a valid media file of kind {audio=2;video=1;midi=0} from "test.avi".

I uploaded a test.avi video to the same directory as test.liq (etc/liquidsoap). Is that the correct directory or should the video be in a different directory?

**Comment by gilou** [comment]
If you have a relative path like test.avi, it looks for it in the directory you run liquidsoap from, not necessarily the one where the script is. Also make sure the video is in a supported format.

**Comment by alexnya** [comment]
Ok I changed the first line in test.liq  to source = single("/etc/liquidsoap/test.avi") and now I'm getting this message:

At line 1, char 9-8: the variable test.liq used here has not been previously
  defined.

**Comment by sumpfralle** [comment]
> At line 1, char 9-8: the variable test.liq used here has not been previously defined.

This error message does not seem to correspond to the script, that you posted above, since your example script does not contain the string `test.liq`.

Anyway: you need to be aware, that liquidsoap is more or less a *programming language* for media processing. Thus you will need to work through examples in order to try to grasp the language.
The error message above does certainly *not* indicate a failure of liquidsoap, but an error in your script. Thus you will need to dig down to the source of the problem between your keyboard and your chair :)
Enjoy the ride!

**Comment by gilou** [comment]
you can try the mailing list as mentionned on http://www.liquidsoap.info/doc-1.3.3/help.html  or IRC #savonet on freenode, or through https://webchat.freenode.net/?channels=#savonet

**Comment by autonarcosis** [comment]
> Ok I changed the first line in test.liq to source = single("/etc/liquidsoap/test.avi") and now I'm getting this message:
> 
> At line 1, char 9-8: the variable test.liq used here has not been previously
> defined.

This error is essentially FILE NOT FOUND.  You are attempting to launch liquidsoap where it cannot find the test.liq file. Either give liquidsoap the fuill path to the .liq file or change directory to where the .liq resides and launch liquidsoap from there.

**Comment by smimram** [comment]
Quite old bug which is really a request for help getting started, closing.
