### ISSUE TITLE
Impossible dependencies?

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#603]
Hi,
Because probably of: https://github.com/savonet/liquidsoap/blob/master/liquidsoap.opam#L24
opam is looking for ocaml-mm 0.4.0 which wasn't released, as far as I can tell (0.3.1 at most)..
And then:
because of https://github.com/savonet/liquidsoap/blob/master/configure.ac#L319
 configure expects dtools 0.4.0... Since this unrelated(?) commit?
https://github.com/savonet/liquidsoap/commit/3d7e036756ed03132eef51df3a08207180de5e0a#diff-67e997bcfdac55191033d57a16d1408a

This happened while working around #596

**Comment by gilou** [comment]
workaround is to compile / pin the dev version from git for both, but it's rather unconvenient.

**Comment by toots** [comment]
Yup. I promise it'll all be fixed soon!
