### ISSUE TITLE
is pipe() broken in master?

### ISSUE THREAD

**Issue by gilou** [savonet/liquidsoap#607]
Here is the script:

```
s = playlist("list.m3u")
# sox - - for stdin/out
ps = pipe(process="sox - -t wav - flanger", mksafe(s))
output.icecast(%mp3, mount="test", mksafe(ps))
```

I get:
```
[source:4] Source pipe_8899 gets up.
[pipe_8899:4] Starting process
...
[pipe_8899:4] Closing process's stdin
...
[mksafe:3] Switch to safe_blank.
```
And of course it's streaming blank. I tried to use `tee` to see pipe()'s output, but I only get a truncated wav header. And the liq process uses 100% of the cpu...

It works if I do it using the named pipe trick:
```
s = playlist("list.m3u")
ps = input.external("cat my_pipe")
# sox - output for stdin
output.external(%wav, "sox - -t wav my_pipe flanger", s)
output.icecast(%mp3, mount="test", mksafe(ps))
```

Any idea?

**Comment by toots** [comment]
Ok, this should be fixed now. Please not that the process needs to restart on each new metadata so you might want to `drop_metadata` before if you don't care about them, that avoids some audio glitches when the process restarts. Also, `sox` is not really well behaved as a process, in particular it doesn't respond to `SIGTERM`.. :-)

**Comment by gilou** [comment]
sox does return with a 0 code when it's happy.. anyway, sox is not my final tool, I was using it merely to test with a noticeable modification. Maybe we could have a way to debug stderr or the return code?

I don't really understand why the behavior is that different using a named pipe and output.external or stdout and pipe(), but I'll assume it's more about the tool at the other end than liq...

Dropping metadata means I'm going to have to inject them later on, but that's doable.. however, I think if I don't want to handle an error code (I need to treat errors as such, in case something actually fails..) the only road is to also merge_tracks...

**Comment by gilou** [comment]
yeah, stderr can be redirected, but a hint about the return code could be nice ;)

**Comment by gilou** [comment]
OK.. it still seems that output.external(%wav) is cleaner than pipe() (but màybe some programs behave better than others in this regard). Also, I was wrong, I can't easily re-inject metadata if I use pipe as I can't easily get a function to do so... Falling back to output.external on a named pipe although makes liq barf at some point, so I'll just drop pipe() and investigate this... with merged tracks it might work out...

My goal is, as you may have guessed from my annoying reports, to easily pipe liq through a dsp like Stereotool, which doesn't need/want to have separate tracks, and works better with a continuous stream.

This worked flawlessly on 1.2.0 using the external output to a named pipe feeded back to liq, but freezes sometimes on 1.3.3... so I'm back to investigate this further... thanks for the clarification anyway.

**Comment by toots** [comment]
Thanks. Appreciate the reports as well. Release is coming soon, would love to clean out more of these before pulling the trigger!

**Comment by griffon56** [comment]
Hi,
I am experiencing the same issue using liquidsoap 1.3.3 on debian sid and wanting to interface stereotool with pipe(). The stereotool process start again on every track. even when using drop_metadata. This restart produces an annoying audio glitch.

`output = mksafe(pipe(restart_on_error = true, process='/process/stereo_tool_cmd_64 - - -s /process/preset.sts', drop_metadata(radio)))`

The only workaround I found is to have a separate liq file that drop_medatata and use input_http on the liq file where pipes feeds stereotool.liq. But then the metadata needs to be retrieved...

Is there anything that been working besides fifo which is painfull to manage ?

Le bonjour chez vous !

**Comment by toots** [comment]
@griffon56 any chance you'd be able to test it with the latest code? I'd love to see if this is fixed for the upcoming release.

**Comment by griffon56** [comment]
Hi toots, i just tested with the package from the sid repository and same issue (external process restarts every song) happens.

**Comment by toots** [comment]
I found the source of your issue. The process restart is part of the design of `pipe()`. The audio glitches are because I forgot to consume the initial WAV header.. Will push a fix soon.

**Comment by griffon56** [comment]
Great news ! Just to be complete about the bug and not miss anything in the upcoming fix :  I also found out that the audio of the file preceding the audio glitch (= end of previous track) was missing for 0,5sec or so

**Comment by toots** [comment]
I'll look at it. However, I'm pretty strict on reading all the data returned by the piping process (which is why it is being stopped on each metadata/track mark)
