### ISSUE TITLE
Telnet is not working properly

### ISSUE THREAD

**Issue by EntityinArray** [savonet/liquidsoap#610]
Liquidsoap 1.3.3+scm running on Windows 8.1 x64

I was trying to make station interactable through Telnet server, but after i execute a command it says that no such command exists (even if i type "help" command that 100% exists) and then my connection to Telnet server times out.

Here's my station code:

    set("server.telnet",true)

    vol = interactive.float("volume",1.0)

    source = amplify(vol,mksafe(playlist("playlist.m3u")))

    output.icecast(%mp3,
        host = "coolgoga.hldns.ru", port = 8000,
        password = "xxx", mount = "entity",
        name="cool music", genre="cool", description="hmm",
        source
    )`

And here is what happens when i try to interact through PuTTY telnet client:

https://i.imgur.com/PupBzyH.png
https://i.imgur.com/phgnbvl.png

**Comment by dromer** [comment]
Try this:

```
set("server.telnet.bind_addr", "127.0.0.1")
set("server.telnet.port", 1234)
set("server.telnet", true)
```

**Comment by EntityinArray** [comment]
@dromer 
> Try this:
>
>set("server.telnet.bind_addr", "127.0.0.1")
>set("server.telnet.port", 1234)
>set("server.telnet", true)
>And use these address and port settings for your telnet client.

Didn't help, everything is same.

**Comment by dromer** [comment]
Are you trying to connect from the same machine or a different machine?

**Comment by EntityinArray** [comment]
@dromer 
> Are you trying to connect from the same machine or a different machine?

it's same machine

**Comment by toots** [comment]
We've had weird reports on the `win32` build. I'm honestly completely at lost with what's going on. It's failing in ways that are beyond the mere semantics of the language. I know that @gilou has tested liquidsoap on windows. Maybe he's got more feedback.

**Comment by toots** [comment]
BTW, working on a new windows build for the upcoming release. Hopefully it should behave better..

**Comment by savonet-users** [comment]
Just to add some information.. I had a problem when trying to connect a
node based telenet client to Liquidsoap.  This was on a Raspberry Pi, so it
was completely Linux.  I seem to remember that it had something to do with
the initial handshake and line endings, and/or the initial prompt.  I hope
I left some trails to where I modified the node client to get it to work.

I didn't have any problems connecting to it from a Windows machine running
PUTTY.. but that's a pretty forgiving program.

Nick

**Comment by toots** [comment]
Good news! I've added a new windows build for the coming `1.3.4` release. Would y'all mind testing it? It's available here: https://github.com/savonet/liquidsoap/releases/tag/1.3.4-win32

**Comment by toots** [comment]
It's an issue in the OCaml compiler: https://caml.inria.fr/mantis/view.php?id=7665 Not sure what I can do to work around it. Will see about it.

**Comment by toots** [comment]
I've uploaded a 4th beta build that should have the fix for this issue. Would you mind trying it? It's here: https://github.com/savonet/liquidsoap/releases/download/1.3.4-win32/liquidsoap-1.3.4-win64-beta4.zip

**Comment by savonet-users** [comment]
das ist fantastisch, Romain!
telnet is now working properly.
i'm letting it run!

i remember i had some issues with long wav or mp3 files with older releases 
(when it approaches 7 hours), will check how they behave in coming week.

champagne and kudos,
p

-----Original Message----- 
From: Romain Beauxis
Date: 2018 m. rugsėjo 2 d. 20:34
To: savonet/liquidsoap
Cc: savonet-users ; Comment
Subject: Re: [Savonet-users] [savonet/liquidsoap] Telnet is not working 
properly (#610)



I've uploaded a 4th beta build that should have the fix for this issue. 
Would you mind trying it? It's here: 
https://github.com/savonet/liquidsoap/releases/download/1.3.4-win32/liquidsoap-1.3.4-win64-beta4.zip
