### ISSUE TITLE
Process hangs while decoding

### ISSUE THREAD

**Issue by jdbuys** [savonet/liquidsoap#611]
Hi,

Liquidsoap correctly uses the ffmpeg decoder, but then hangs and doesn't actually stream or give an error, and you can't terminate the process because it seems like it can't close ffmpeg.
Attached are the files that cause the issue. I can't replicate it with any other files so far.
Any help would be appreciated.

I have compiled the latest version from source on Ubuntu 18.04.
Liquidsoap 1.3.3+scm (git://github.com/savonet/liquidsoap.git@a1602f7193774d874d188cd94a2080d56afbbc80:20180822:100724)

And here is my script:

```
#!/usr/local/bin/liquidsoap
set("log.file.path","error.log")
set("log.stdout", true)
set("server.telnet",false)
set("server.socket",true)
set("server.socket.path","lsoap.sock")
set("server.socket.permissions",511)
set("server.timeout",20.)
set("scheduler.generic_queues",2)
set("scheduler.non_blocking_queues",2)
set("scheduler.fast_queues",0)
set("scheduler.log",true)
set("init.catch_exn",true)
set("log.level",8)


#Add ffmpeg
def test_ffmpeg(file) = -1 end
ffmpeg_p = "/tmp/ffmpeg/ffmpeg -i - -f wav -"
add_decoder(name="FFMPEG",description="Decode files using the ffmpeg decoder binary",mimes=["audio/aacp","application/octet-stream","audio/x-wav"],test=test_ffmpeg,ffmpeg_p)


source=fallback(track_sensitive=false,[playlist("/tmp/playlist.pls"),request.queue(id="queue",length=10.0),request.equeue(id="equeue")])
source=audio_to_stereo(id="source",source)
source=mksafe(source)


output.icecast(%mp3(stereo=true,bitrate=64,samplerate=44100),id="icecast",host="127.0.0.1",port=80,user="source",password="hackme",fallible=true,name="GreenMonkey",description="Green Monkeys Unite!!",mount="idGreenMonkeyUnited",url="http://green-monkey.com",source)
```

[music.zip](https://github.com/savonet/liquidsoap/files/2309821/music.zip)

**Comment by gilou** [comment]
Ha! Now I'm not the only one... though your issue is with decoding, mine with outputs (#609).. but common ground: process handling in liq...

**Comment by jdbuys** [comment]
Yep 4.05.0, which I installed through opam.

**Comment by toots** [comment]
Thanks for this report, much appreciated. I'll look at it ASAP.

Meanwhile, if that is production critical, you can look at the new build-in `FFMPEG` decode, which should not have these hang ups (haha)

**Comment by jdbuys** [comment]
Cool, thanks. I tested it with the built-in FFMPEG decoder and it works like a charm.

**Comment by toots** [comment]
I found the issue but it's a tricky one. Will see what I can do.
