### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by dromer** [savonet/liquidsoap#612]
in my liq I have:
```
set("log.file.path", "/media/logs/playvideo.log")
set("log.level",5)
```

But this file is not created/used

**Comment by desavil** [comment]
Try add `set("log.file",true)`
It worked without it before. For some time this is required.

**Comment by toots** [comment]
Thanks for reporting this. I've just pushed a change which should make `log.file` default to `true` when setting `log.file.path` to any value so you shouldn't have to set `log.file` to `true` in the above configuration.
