### ISSUE TITLE
Remove character from Metatag

### ISSUE THREAD

**Issue by preterive** [savonet/liquidsoap#615]
Hello,
i search a way to remove the ; from the meta tag, because my streaming software don't support this character.

**Comment by toots** [comment]
Hi,

You should be able to achieve that by using the `map_metadata` operator. It is described here: http://www.liquidsoap.info/doc-1.3.3/metadata.html

**Comment by preterive** [comment]
I already test it:
```
At line 17, char 17-43: This term would evaluate to a (passive) source which
  would then be dropped. This is usually the sign of a misunderstanding:
  only active sources are animated on their own; dangling passive sources
  are just dead code.

```
could you give a more simple example?

**Comment by toots** [comment]
You can try this:
```
def remove_colon(m) =
  def f(pair) =
    lbl = fst(pair)
    val = snd(pair)
    replace = fun (_) -> ""
    (lbl,string.replace(pattern=":",replace,lbl)
  end
  list.map(f,m)
end

s = map_metadata(remove_colon,s)
```

(Code untried)

You could also be more specific by only rewriting some specific parts:

```
def remove_colon(m) =
  def strip(s) =
    replace = fun (_) -> ""
    string.replace(pattern=":",replace,s)
  end

  updated_meta = []
  updated_meta =
    if m["title"] then
      list.add(("title",string.replace(m["title"]),updated_meta)
    else
      updated_meta
    end

  # Repeat for other labels.

  updated_meta
end

s = map_metadata(remove_colon,s)
```

**Comment by preterive** [comment]
Thanks, it don't work but now i edit them.

**Comment by preterive** [comment]
Both examples don't work. i simple change s to source3.

**Comment by preterive** [comment]
Line 24, char 6 before "end": Parse error!

**Comment by gilou** [comment]
paste your full script so we can help... and opening another issue for this is quite rude in my opinion...

**Comment by preterive** [comment]
no problem: https://pastebin.com/csKaWUUu

**Comment by gilou** [comment]
You didn't include the metadata rewriting there?
