### ISSUE TITLE
Switch between live streams

### ISSUE THREAD

**Issue by anitta-paul** [savonet/liquidsoap#619]
HI, I have new problem that I'm facing while working with `liquidsoap`.
I have a system where `liquidsoap` reads the system audio and inputs to the `icecast` server. This works fine. But, I cannot start a live broadcasting from another broadcasting software while the system audio is being broadcasted by `liquidsoap` unless and until `liquidsoap` is terminated. 

Is there any possibility that I could have a common streaming url which by default streams the system audio using `liquidsoap` and whenever a live broadcast happens `liquidsoap` stops and streams live broadcasting. Also when live broadcast stops the system fallbacks to the system audio broadcasting.

ie. Give more priority to the live broadcasting and keep the system audio as a default playback.

**Comment by autonarcosis** [comment]
Look here;

http://www.liquidsoap.info/doc-1.3.3/cookbook.html

Under 'Dynamic Input With Harbor' and 'Switch Based Transitions'.
