### ISSUE TITLE
Source failed (no more tracks)

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#622]
I'm getting this error after executing a couple of .skip over telnet.
![screen shot 2018-09-08 at 15 35 15](https://user-images.githubusercontent.com/9781846/45255680-040ecf80-b382-11e8-83cd-98e6269b3746.png)
This seemed to only happen on the Windows XP machine, not on my raspberry pi.
```#!/usr/bin/liquidsoap

set("log.stdout", true)
set("log.level", 3)
set("log.file.path", "tests.log")

set("server.telnet", true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port",1717)
set("server.telnet.reverse_dns",true)

hit_music = random([playlist("C:\Documents and Settings\NagarGroup\Desktop\Music",mode="randomize",reload=1,reload_mode="rounds")])
radio = crossfade(hit_music)

radio = amplify(1.,override="replay_gain",radio)

def transitionToLive(old,new) = 
  old = fade.final(old)
  new = fade.in(new)
  add([old,new])
end

def transitionToAuto(old,new) =
  old = fade.final(old)
  new = fade.in(new) 
  add([old,new])
end

vover = input.http("http://listen.nagar.eu:8000/livevover.ogg")
radio = add([radio,vover])
full = fallback(track_sensitive=false,transitions=[transitionToLive,transitionToAuto], [input.http("http://listen.nagar.eu:8000/liveinput.ogg"), radio]) 


output.icecast(%mp3(bitrate=128), 
  host="listen.nagar.eu",name="Nagar FM",description="Playing the latest and greatest music until 6 PM. Join us at 6 PM for party and rap music.",port=8000,password="****",
  mount="autodj.mp3",fallible=true,full)
```
Thanks

**Comment by toots** [comment]
Yes, this is bound it happen if the underlying source doesn't prepare a request fast enough. You should either wrap the top-level source in a `mksafe()` call or use a failsafe `single()` at the root of the source tree.

Now that we're here, I have a question: do you see any memory leak on windows when using the telnet commands?

**Comment by Niall7459** [comment]
Hi Thanks! how would I able to detect a memory leak? My memory usage is relatively low at all times.

**Comment by toots** [comment]
Wait and see if memory usage grows over time :-)

**Comment by Niall7459** [comment]
Il keep an eye on it

**Comment by Niall7459** [comment]
For 3 days memory usage has not increased and stayed reputable the same.

**Comment by toots** [comment]
Thank you!
