### ISSUE TITLE
youtube-dl webm decoding issues

### ISSUE THREAD

**Issue by dali99** [savonet/liquidsoap#623]
I have a request source set up like this:
`requests = audio_to_stereo(drop_video(request.queue(id="request")))`

This allows the request queue to download youtube videos which are downloaded in mp4 and play them as audio. But the vast majority fails because liquidsoap cant find a suitable decoder for webm. Even though I thought gstreamer was able to do this.

My enviroment:
```
RUN apt-get -q update && \
    apt-get install -qq -yy python festival sox && \
    apt-get clean

RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && \
    chmod a+rx /usr/local/bin/youtube-dl

USER opam

RUN opam switch 4.05.0 && \
    opam depext cry faad flac gstreamer lame liquidsoap mad opus samplerate ssl taglib vorbis && \
    opam install cry faad flac gstreamer lame liquidsoap mad opus samplerate ssl taglib vorbis
```

As a workaround I'm going to reimplement the youtube-dl protocol in my script to extract audio. But getting webm decoding working would probably be good for other things too.

Or maybe chaining of protocols should work in requests too? That way one could request ffmpeg2wav:youtube-dl:someurl

**Comment by toots** [comment]
As for the gstreamer decode, yes it should work. You would need to check the file's extension against the configured list:
```
set("decoder.file_extensions.gstreamer",["wma","wmv","avi","mp4","3gp","webm","mkv"])
```
I'll try to give it a try.

**Comment by toots** [comment]
Just pushed changes to the `youtube-dl` protocol so that this now works as well:
```
"ffmpeg2wav:youtube-dl:-IYXYB0r-Ww"
```

**Comment by dali99** [comment]
Wow quick response!
I did try set the gstreamer file extensions but that failed on my install.

Good to know that chaining is supposed to work! unfortunantly even with:

`echo request.push 'ffmpeg2wav:youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU' | nc 127.0.0.1 5000`

This is the result

```
main_1       | 2018/09/09 20:10:42 [protocol.process:4] Processing wav,ffmpeg -y -i $(input) -ac 2 $(output):youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU
main_1       | 2018/09/09 20:10:42 [lang.run_process:4] Starting process
main_1       | 2018/09/09 20:10:42 [lang.run_process:4] Closing process's stdin
main_1       | 2018/09/09 20:10:43 [lang.run_process:4] Process exited
main_1       | 2018/09/09 20:10:43 [lang.run_process:4] Cleaning up process
main_1       | 2018/09/09 20:10:43 [protocol.process:4] Processing ,rm -f $(output) && youtube-dl -q -f best --no-playlist -o $(output) "https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU"
main_1       | 2018/09/09 20:10:43 [protocol.process:4] Executing rm -f "/tmp/liq-process2a5623." && youtube-dl -q -f best --no-playlist -o "/tmp/liq-process2a5623." "https://www.youtube.com/watch?v=gSkocU5YsHU"
main_1       | 2018/09/09 20:10:43 [lang.run_process:4] Starting process
main_1       | 2018/09/09 20:10:43 [lang.run_process:4] Closing process's stdin
main_1       | 2018/09/09 20:10:46 [lang.run_process:4] Process exited
main_1       | 2018/09/09 20:10:46 [lang.run_process:4] Cleaning up process
main_1       | 2018/09/09 20:10:46 [protocol.process:4] Executing ffmpeg -y -i "/tmp/liq-process2a5623." -ac 2 "/tmp/liq-processf2487d.wav"
main_1       | 2018/09/09 20:10:46 [lang.run_process:4] Starting process
main_1       | 2018/09/09 20:10:46 [lang.run_process:4] Closing process's stdin
main_1       | 2018/09/09 20:10:46 [lang.run_process:4] Process exited
main_1       | 2018/09/09 20:10:46 [lang.run_process:4] Cleaning up process
main_1       | 2018/09/09 20:10:46 [protocol.process:3] Failed to execute ffmpeg -y -i "/tmp/liq-process2a5623." -ac 2 "/tmp/liq-processf2487d.wav": ("exit","127")
main_1       | 2018/09/09 20:10:46 [request:4] Failed to resolve "process:wav,ffmpeg -y -i $(input) -ac 2 $(output):youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU"! For more info, see server command 'trace 0'.
```

```
[2018/09/09 20:10:42] Pushed ["ffmpeg2wav:youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU";...].
[2018/09/09 20:10:42] "ffmpeg2wav:youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU" entered the secondary queue : position #1.
[2018/09/09 20:10:42] Entering the primary queue.
[2018/09/09 20:10:42] Resolving "ffmpeg2wav:youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU" (timeout 20s)...
[2018/09/09 20:10:42] Pushed ["process:wav,ffmpeg -y -i $(input) -ac 2 $(output):youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU";...].
[2018/09/09 20:10:42] Resolving "process:wav,ffmpeg -y -i $(input) -ac 2 $(output):youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU" (timeout 20s)...
[2018/09/09 20:10:42] Processing wav,ffmpeg -y -i $(input) -ac 2 $(output):youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU
[2018/09/09 20:10:46] Executing ffmpeg -y -i "/tmp/liq-process2a5623." -ac 2 "/tmp/liq-processf2487d.wav"
[2018/09/09 20:10:46] Failed to execute ffmpeg -y -i "/tmp/liq-process2a5623." -ac 2 "/tmp/liq-processf2487d.wav": ("exit","127")
[2018/09/09 20:10:46] Every possibility failed!
[2018/09/09 20:10:46] Request finished.
```

I also tried to install master by cloning the repo and pinning but liquidsoap wants 0.4.0 of mm. But pinning that lead to this error:

```
mm is now path-pinned to /home/opam/ocaml-mm

[WARNING] Rsync partially failed:
          symlink has no referent:
          "/home/opam/ocaml-mm/bootstrap"
          rsync error: some files/attrs were not
          transferred (see previous errors) (code
          23) at
          main.c(1183) [sender=3.1.1]

[mm] /home/opam/ocaml-mm/ synchronized
[mm] Installing new package description from
/home/opam/ocaml-mm

mm needs to be reinstalled.
The following actions will be performed:
  - upgrade   mm         0.3.1 to dev*
  - recompile liquidsoap 1.3.3                          [uses mm]
===== 1 to recompile | 1 to upgrade =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[WARNING] Rsync partially failed:
          symlink has no referent:
          "/home/opam/ocaml-mm/bootstrap"
          rsync error: some files/attrs were not
          transferred (see previous errors) (code
          23) at
          main.c(1183) [sender=3.1.1]

[mm.dev] /home/opam/ocaml-mm/ synchronized

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> removed   liquidsoap.1.3.3
-> removed   mm.0.3.1
[ERROR] The compilation of mm failed at
        "./bootstrap".
Processing  3/4: [mm: ocamlfind remove]
#=== ERROR while installing mm.dev ============================================#
# opam-version 1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os           linux
# command      ./bootstrap
# path         /home/opam/.opam/4.05.0/build/mm.dev
# compiler     4.05.0
# exit-code    127
# env-file     /home/opam/.opam/4.05.0/build/mm.dev/mm-84-ad8886.env
# stdout-file  /home/opam/.opam/4.05.0/build/mm.dev/mm-84-ad8886.out
# stderr-file  /home/opam/.opam/4.05.0/build/mm.dev/mm-84-ad8886.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  - install liquidsoap 1.3.3
The following actions failed
  - install mm dev
The following changes have been performed
  - remove liquidsoap 1.3.3
  - remove mm         0.3.1
[NOTE] Pinning command successful, but your
       installed packages may be out of sync.

The former state can be restored with:
    opam switch import
"~/.opam/4.05.0/backup/state-20180809181615.export"
```

So I still haven't gotten it to work sadly :confused:

**Comment by dali99** [comment]
Oh installing ffmpeg through opam doesn't install ffmpeg with apt...
ffmpeg2wav works now sorry about that!

**Comment by toots** [comment]
Added :-)

**Comment by MattMski** [comment]
Getting the same errors, would love some help

**Comment by toots** [comment]
@MattMski do you have `ffmpeg` installed?

**Comment by MattMski** [comment]
yes i compiled ffmpeg with liquidsoap

**Comment by toots** [comment]
Ok. So what are you trying to do and what error message are you getting?

**Comment by MattMski** [comment]
Play a youtube video with a request, and I get the same errors as he did. I typed
`request.push ffmpeg2wav:youtube-dl:https$(colon)//www.youtube.com/watch?v=gSkocU5YsHU`

`2019/02/21 14:03:51 [request:2] Time limit exceeded by 2.31 secs!
2019/02/21 14:03:51 [request:2] Time limit exceeded by 2.51 secs!
2019/02/21 14:03:51 [protocol.ffmpeg2wav:3] Failed to resolve process:wav,ffmpeg -y -i $(input) -ac 2 "/tmp/liq-processdcd93a.wav":/tmp/liq-process90316d.
2019/02/21 14:03:51 [request:2] Time limit exceeded by 2.00 secs!`

**Comment by toots** [comment]
How long is the video? If it's a long one you will need to extend the request resolution `timeout`.

**Comment by toots** [comment]
Hmm okay the video looks short. You might have a case of bug #691. Are you using the `opam` package? If so you might be able to try the fix for this bug:

```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
git checkout workaround-691
opam pin add .
```

**Comment by MattMski** [comment]
Yes I am using opam, I ran your steps and got to the 3rd only to get error: pathspec 'workaround-691' did not match any file(s) known to git. (I'm still fairly new sorry, haha). What would I do from here? Was I supposed to install from github using opam?

**Comment by savonet-users** [comment]
Hi Matthew,

Regarding the workaround, I guess Romain forgot that he already merged it
into master : https://github.com/savonet/liquidsoap/pull/703 :-) So all you
need to do is probably opam update && opam upgrade

Regarding your issue, I stumble on the same one with Debian, while the
youtube requests work perfectly on MacOS.

Xavier.

**Comment by MattMski** [comment]
Well I am on Debian 9 and there are no updates available on opam latest it gave me 1.3.4 which is what I am on

**Comment by savonet-users** [comment]
Hi Matthew,

I'm not sure that the version number is the reason why the youtube-dl
protocol doesn't work : it has worked since 1.3.4 on my MacOS. But you
probably should update opam to 2.0.3 if you want to be able to upgrade the
newest liquidsoap versions. This might require getting rid of the opam
package distributed with Debian and instead installing from here:
https://opam.ocaml.org/doc/Install.html

Anyway, the issue remains, so Romain, if you are ready to look at it, I'm
willing to report the result of any command you want on my Debian 9, opam
2.02, liquidsoap 1.3.6.

Cheers,
-- Xavier Cazin

**Comment by MattMski** [comment]
Thanks I upgraded my opam to the latest 2., and am on liquidsoap 1.3.6 now, but when i run the command i am now getting.
`2019/02/23 12:37:05 [protocol.ffmpeg2wav:3] Failed to resolve process:wav,ffmpeg -y -i $(input) -ac 2 "/tmp/liq-process909a63.wav":/tmp/liq-process466c63.`

**Comment by toots** [comment]
Hey y'all.

The first has been merged indeed but the current `master` shouldn't be considered safe for production, it's currently in alpha stage, pending more work and testing.

Meanwhile, the work around should be safe-ish to use instead and is based on the latest `stable` release. I deleted that branch by mistake, just put it back:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
git checkout workaround-691
opam pin add .
```
You will indeed need opam 2 for this to work.

Please let me know if that fixes the issue, otherwise I'm happy to look further into it.
