### ISSUE TITLE
ON_METADATA not called when live show is broadcast.

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#624]
Hi, Ive noticed ON_METADATA function is not called when a live stream interrupts,

However, when a new song is played on the live stream, the function is called (just not on the first song when switching)

Thanks

Heres my script:
```#!/usr/bin/liquidsoap

set("log.stdout", true)
set("log.level", 3)
set("log.file.path", "tests.log")


set("server.telnet", true)
set("server.timeout",-1.0)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port",1717)
set("server.telnet.reverse_dns",true)

def transitionToLive(old,new) = 
  old = fade.final(old)
  new = fade.in(new)
  add([old,new])
end

def transitionToAuto(old,new) =
  old = fade.final(old)
  new = fade.in(new) 
  add([old,new])
end

def send_meta(m) =
ignore(http.get("http://listen.nagar.eu/ctl/post_track.php" ^ "?artist=" ^ url.encode(m["artist"]) ^ "&title=" ^ url.encode(m["title"]) ^ ""))
end

hit_music = random([playlist("C:\Documents and Settings\Appletec\Desktop\Music",mode="randomize",reload=1,reload_mode="rounds")])
requests = request.queue(id="queue")

radio = fallback(track_sensitive=false,transitions=[transitionToLive,transitionToAuto],[requests, hit_music])

radio = smart_crossfade(radio)
radio = amplify(1.,override="replay_gain",radio)



vover = input.http("http://listen.nagar.eu:8000/livevover.ogg")
radio = add([radio,vover])
full = fallback(track_sensitive=false,transitions=[transitionToLive,transitionToAuto], [input.http("http://listen.nagar.eu:8000/liveinput.ogg"), radio]) 

full = on_metadata(send_meta, full)

output.icecast(%mp3(bitrate=128), 
  host="listen.nagar.eu",name="Nagar FM",description="Playing the latest and greatest music until 6 PM. Join us at 6 PM for party and rap music.",port=8000,password="*****",
  mount="autodj.mp3",fallible=true,full)
```

**Comment by Niall7459** [comment]
@toots So basically when the source is switched to a live input on_metadata is not called until the second song is played on the live stream

Would it be possible to call on_metadata directly on the fallback. e.g in the functions toLive and toAuto?

**Comment by Niall7459** [comment]
I mean I can easily call send_meta() I just don’t know where to get the metadata object from directly.

**Comment by Niall7459** [comment]
@toots any update on this?

**Comment by Niall7459** [comment]
Metadata is also not updated when pushing a song to the queue over TELNET
![screen shot 2018-09-16 at 10 30 59](https://user-images.githubusercontent.com/9781846/45594958-a985fc80-b99b-11e8-8bd0-7cb1b34e2485.png)

![screen shot 2018-09-16 at 10 31 30](https://user-images.githubusercontent.com/9781846/45594963-b6a2eb80-b99b-11e8-9c97-0d05a0afad64.png)

**Comment by daniel-j** [comment]
I have a similar issue with Liquidsoap 1.3.4 where `on_metadata` and `map_metadata` doesn't always get called after a `smart_crossfade`. I tested this by running skip multiple times. [code](https://github.com/daniel-j/parasprite-radio/blob/ebddb2fd275249056026d6f681b6a939c1a48cb4/liq/radio.liq)

I can solve it by moving the smart_crossfade after the metadata hooks (unsure how this will affect my live sources, needs more testing) or removing it completely.

**Comment by Niall7459** [comment]
Hi any update on this?

**Comment by dhannyz** [comment]
@daniel-j I have this exact issue with smart_crossfade as well, likewise I dont think moving the crossfade after my live sources would be a good idea, did you get anywhere with this?
