### ISSUE TITLE
Metadata bug

### ISSUE THREAD

**Issue by Euguar** [savonet/liquidsoap#625]
I found some bugs with metadata tag parsing:
1. The _Artist_ field has _Title_ field, and the _Title_ field has _Artist_ field (ex.: "Pink - Aerosmith". It must be "Aerosmith - Pink"). Temporarily solution is map_metadata function using to replace fields.
2. If the field _Artist_ or _Title_ contains comma, this field will be cropped before (ex.: ABBA - Knowing Me, Knowing You. In this case _Title_ filed will be cropped " Knowing You" with space before.
3. If the field _Artist_ or _Title_ contains dash, this filed duplicated twice (ex.: A-Ha - The Bandstand. In this case Atrist field will be "A-Ha - A-Ha".

**Comment by toots** [comment]
Hi,

I'm not sure what context you are referring. Could elaborate a bit more? Thks!

**Comment by Euguar** [comment]
OK, my simple config on Windows 

is:

```
#Liquidsoap 1.3.4 x64
set("log.file",false)
set("log.file.path","logs/liquidsoap.log")
set("log.stdout",true)
set("log.level",3)

playlistpath=playlist(mime_type="audio/x-mpegurl",mode="randomize",reload=86400,reload_mode="seconds","D:\Music\music.m3u")

live=mksafe(playlistpath)

output.icecast(%ogg(%vorbis(channels=2,quality=0.2,samplerate=48000)),
mount="/live.ogg",
format="application/ogg",
host="192.168.0.4",
port=8000,
password="hackme",
public=false,
live)
```

Playlist M3U file contains into:

```
#EXTM3U
#EXTINF:177,ABBA - Money, Money, Money
D:\Music\ABBA - Money Money Money.mp3
#EXTINF:233,Aerosmith - Pink
D:\Music\Aerosmith - Pink.mp3
#EXTINF:160,Blink-182 - California
D:\FMFND\Luxury\Music\Blink-182 - California.mp3
```

Now, connecting to stream:

**Case #1:**
When playing file from playlist with simple metadata: 'Aerosmith - Pink'.
Liquidsoap send inversed metadata fields _Artist_ & _Title_ (see pic. 1): Media player displays _Artist_: '**Pink**', _Title_: 'Aerosmith'.
Local MP3 file metadata tags are: _Artist_: '**Aerosmith**', _Title_: 'Pink'.

**Case #2:**
When playing file from playlist with dash symbol in the _Artist_ field metadata: '**Blink-182** - California'.
Liquidsoap send _Artist_ field to _Title_ (see pic. 2): Media player displays _Artist_: 'Blink-182', _Title_: '**Blink-182 -** California'.
Local MP3 file metadata tags are: _Artist_: 'Blink-182', _Title_: '**California**'.

**Case #3:**
When playing file from playlist with comma symbol in the _Title_ field metadata: 'ABBA - **Money, Money, Money**'.
Liquidsoap send cropped metadata after last comma symbol, and _Artist_ field with space symbol before (see pic. 3): Media player displays _Artist_: ' **Money**', _Title_: 'ABBA'.
Local MP3 file metadata tags are: _Artist_: 'ABBA', _Title_: '**Money, Money, Money**'.

![metadatabug](https://user-images.githubusercontent.com/43269281/45746089-1652fe00-bc0b-11e8-8d18-1bb7fef2422e.png)

**Comment by toots** [comment]
Have you checked the file's metadata?

**Comment by toots** [comment]
Ok, my bad, I hadn't looked at this code for a long time. Yes, liquidsoap parses metadata from the `m3u` playlist and it follows this pattern:
```
#EXTINF<anything>,<artist>-<title>
```
So, your case indeed exhibits the two ambiguous cases, where `<artist>` or `<title>` contains a dash `-` or a comma `,`.

For the comma, there's an easy fix, which is to consider only the first comma in the string. However, for the dash, I'm not sure. Artist and title may both contain a dash, in which case there's no way to know in advance what's the right way. Think about this:
```
#EXTINF:233,My hot artist - feat. DJ. fancy pants - I looked for you at the store -- but you weren't there
D:\Music\song.mp3
```
