### ISSUE TITLE
input.gstreamer.video is never defined, despite gstreamer being installed

### ISSUE THREAD

**Issue by MCOfficer** [savonet/liquidsoap#629]
I spent the last 2 hours trying to use `output.youtube.live`, and always fail with a "not defined" error.
 I installed Liquidsoup and it's dependencies via OPAM, as described [here](https://www.liquidsoap.info/download.html). After the installation, i realized i needed gstreamer, so i installed that, too:
```
$ opam depext gstreamer
$ opam install gstreamer
```
(Edit: later, i also installed `libgstreamer-ocaml-dev` from the repo and repeated the whole process, just to be sure)

and since i still couldn't use `output.youtube.live`, i checked whether gstreamer.liq gets included in the first place. it does, but aparently it doesn't get past the `%ifdef input.gstreamer.video`, because when i comment that line, i get an error that `input.gstreamer.video` is not defined. i checked with grep, and indeed it doesn't seem to be anywhere:

```
$ grep -nRw .opam/ -e "input.gstreamer.video"
  .opam/system/lib/liquidsoap/lib/liquidsoap/1.3.4/gstreamer.liq:1:%ifdef input.gstreamer.video
  .opam/system/lib/liquidsoap/lib/liquidsoap/1.3.4/gstreamer.liq:9:  input.gstreamer.video(id=id, pipeline=pipeline)
```

Edit 2: i tried one of the pre-built windows binaries, and did not have that issue there, however the same grep yielded the same result. with my limited knowledge, i assume that this dubious `input.gstreamer.video` is defined in the binary itself - but then recompiling (or rather, `opam reinstall`ing) should have fixed it.

**what i tried**:
* check if liquidsoup is the latest version (1.3.4 - it is)
* check if i have any other liquidsoup installations interfering (i don't)
* check wether i include the correct pervasives.liq (i do)
* reinstall liquidsoup via OPAM

i'm out of ideas. any help?

**Comment by MCOfficer** [comment]
i wiped my entire opam and everything it had installed, then reinstalled everything. this time, it worked.

**Comment by toots** [comment]
Glad to know it's fixed!
