### ISSUE TITLE
Support playing .m4a or .aac audio files (aac+)

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [savonet/liquidsoap#631]
Good day,
The Liquidsoap supports playing files in the AAC+codec in playlists?
I want to store all the music in aac+ format (32 kbit) for less space on the hard drive, and then broadcast it in AAC+ 32 kbit format

**Comment by toots** [comment]
Absolutely. You need to compile liquidsoap with `faad` for AAC decoding and everything should be fine!
