### ISSUE TITLE
Liquidsoap support multiple radio stations at once?

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [savonet/liquidsoap#632]
Want to make music folders separated by genre, and that Liquidsoap was broadcast them all at once on different mountpoint icecast
(each folder is a separate radio)

**Comment by Euguar** [comment]
The simple config is:
```
#PATHS
popmusic=playlist(mode="randomize","/path/to/pop/playlist.m3u")
rockmusic=playlist(mode="randomize","/path/to/rock/playlist.m3u")
classicmusic=playlist(mode="randomize","/path/to/classic/playlist.m3u")

popbroadcasting=mksafe(popbroadcasting)
rockbroadcasting=mksafe(rockbroadcasting)
classicbroadcasting=mksafe(classicbroadcasting)

#OUTPUT POP LIVE
output.icecast(%ogg(%vorbis(channels=2,quality=0.2,samplerate=48000)),
mount="/pop.ogg",
format="application/ogg",
host="192.168.0.1",
port=8000,
password="hackme",
public=false,
genre="Pop",
url="http://mypopstation.com/",
description="Pop music radio station.",
name="Pop Radio",
popbroadcasting)

#OUTPUT ROCK LIVE
output.icecast(%ogg(%vorbis(channels=2,quality=0.2,samplerate=48000)),
mount="/rock.ogg",
format="application/ogg",
host="192.168.0.1",
port=8000,
password="hackme",
public=false,
genre="Pop",
url="http://myrockstation.com/",
description="Rock music radio station.",
name="Rock Radio",
rockbroadcasting)

#OUTPUT CLASSIC LIVE
output.icecast(%ogg(%vorbis(channels=2,quality=0.2,samplerate=48000)),
mount="/classic.ogg",
format="application/ogg",
host="192.168.0.1",
port=8000,
password="hackme",
public=false,
genre="Classic",
url="http://myclassicstation.com/",
description="Classic music radio station.",
name="Classic Radio",
classicbroadcasting)
```

**Comment by strelkovandreyvalerievich** [comment]
Thank you, that's what I wanted to see!

**Comment by toots** [comment]
Thanks @Euguar !

**Comment by Abdallahsamy1** [comment]
> The simple config is:
> 
> ```
> #PATHS
> popmusic=playlist(mode="randomize","/path/to/pop/playlist.m3u")
> rockmusic=playlist(mode="randomize","/path/to/rock/playlist.m3u")
> classicmusic=playlist(mode="randomize","/path/to/classic/playlist.m3u")
> 
> popbroadcasting=mksafe(popbroadcasting)
> rockbroadcasting=mksafe(rockbroadcasting)
> classicbroadcasting=mksafe(classicbroadcasting)
> 
> #OUTPUT POP LIVE
> output.icecast(%ogg(%vorbis(channels=2,quality=0.2,samplerate=48000)),
> mount="/pop.ogg",
> format="application/ogg",
> host="192.168.0.1",
> port=8000,
> password="hackme",
> public=false,
> genre="Pop",
> url="http://mypopstation.com/",
> description="Pop music radio station.",
> name="Pop Radio",
> popbroadcasting)
> 
> #OUTPUT ROCK LIVE
> output.icecast(%ogg(%vorbis(channels=2,quality=0.2,samplerate=48000)),
> mount="/rock.ogg",
> format="application/ogg",
> host="192.168.0.1",
> port=8000,
> password="hackme",
> public=false,
> genre="Pop",
> url="http://myrockstation.com/",
> description="Rock music radio station.",
> name="Rock Radio",
> rockbroadcasting)
> 
> #OUTPUT CLASSIC LIVE
> output.icecast(%ogg(%vorbis(channels=2,quality=0.2,samplerate=48000)),
> mount="/classic.ogg",
> format="application/ogg",
> host="192.168.0.1",
> port=8000,
> password="hackme",
> public=false,
> genre="Classic",
> url="http://myclassicstation.com/",
> description="Classic music radio station.",
> name="Classic Radio",
> classicbroadcasting)
> ```

Thanks for your reply it really helps,

but if I use an icecast inputs from multiple sources and transcode them to another formats in different mount points how can I achieve this as simple as you have illustrated ?
Thanks
