### ISSUE TITLE
AAC+ broadcast in Windows platform problem

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [savonet/liquidsoap#633]
Good day, I installed ICECAST and made a minimum of settings, namely created TEST mountpoint
Next I installed liquidsoap also making the minimum settings, and it was uncomment in the standard config at the end of several lines

```
# An icecast output in AAC+ format
output.icecast(%aacplus(bitrate=32),
              fallible=true,
              mount="test",
              s)
```

But when I run it, I get an error

`Line 23, char 17 before "%": Parse error!`

I assume that I have a problem at least that, the AAC decoder needs to be installed separately on Windows from out of the box it does not go to liquidsoap. If so, please tell me where it can be taken and where to put it to liquidsoap could use it
Thanks!

**Comment by KruegerDead** [comment]
You need use `%fdkaac` instead `%aacplus`
[Encoding formats docs](https://www.liquidsoap.info/doc-1.3.4/encoding_formats.html)
`%fdkaac(channels=2, samplerate=44100, bitrate=64, afterburner=false, aot="mpeg2_he_aac_v2", transmux="adts", sbr_mode=false)`

**Comment by strelkovandreyvalerievich** [comment]
Thanks for fast answer!!! Works!

Please tell me, if I understand correctly, if I'm in the playlist I put audio files in the AAC+ format with bitrate of 48 kbps and broadcast them with the same settings 48 kbps, what is the probability that liquidsoap will them immediately without conversion in the air to throw?

Rather, the question is even, for example, how much will liquidsoap be easier to work with, if for example it has 20 radio stations on the air, with 20 different playlists. And let's say in the first case in 20 playlists there will be MP3 files with bit rate of 320 kbit and in the second AAC + 48 kbit. In this case, the broadcast is configured so that you need to broadcast AAC+ 48 kbit. I. e. correctly I understand that it will be heavy to it with MP3 since it needs to be converted at first before broadcast to AAC+

**Comment by toots** [comment]
Thanks for the explanations @KruegerDead !
