### ISSUE TITLE
Unknown protocol "text2wav" in URI

### ISSUE THREAD

**Issue by Niall7459** [savonet/liquidsoap#637]
![screen shot 2018-09-29 at 09 46 53](https://user-images.githubusercontent.com/9781846/46243477-a5f76a00-c3cc-11e8-8448-066cc4afa27e.png)
![screen shot 2018-09-29 at 09 46 49](https://user-images.githubusercontent.com/9781846/46243478-a7289700-c3cc-11e8-8780-eeadc326dc00.png)

This is happening with youtube-dl, polly as well:
https://www.liquidsoap.info/doc-dev/protocols.html

Thanks

**Comment by Niall7459** [comment]
This is on windows by the way.

**Comment by toots** [comment]
Ok, this one is a typo. The protocol is actually `text2wave`. Updating the website to reflect it. 

Note: to make this work on windows, you will have to install the `text2wave` binary and set its path using `set("protocol.text2wave.path",<path to binary>)`
