### ISSUE TITLE
Liquidsoap problem

### ISSUE THREAD

**Issue by nickolasnick** [savonet/liquidsoap#638]
Hi all,
i have a raspberry pi 3 model b which runs liquidsoap as streamer out(%ogg(%flac(samplerate=192000, with a cirrus logic audio card for input and one raspberry pi 3 model b for receiver with hifiberry dac+ light which works perfect....i wanted to change receiver raspberry with a pi3 model b plus using again the hifiberry dac+ light,here comes the problem liquidsoap starts without any error but without also any sound. Setup is exactly the same and the model b but here there is not any sound.
Any suggestion? I'm not an expert but i'm trying myself some projects so could somebody help?

**Comment by savonet-users** [comment]
Hi Nicholas,

I believe that on the PI, the default for all the audio is muted.  I have
not used the higiberry, so cannot help with that.  My first suggestion is
to make sure you can play audio through that card.  Without liquidsoap
involved.  There should be some pretty good documentation on the PI site to
troubleshoot that.

The other possibility is that the device name changed.  When you moved to
the b plus, did you end up upgrading the OS?

Nick

**Comment by nickolasnick** [comment]
Hi again and thanks for your reply, from the same streaming works the pi 3 model b at the same time and this works perfect, same setup same audio card and the model b plus does not have sound so it could not be the streaming, could it be a driver problem at the new raspberry? Streaming at 44100 works perfect, at 192000 no sound. But get in mind that same streaming at 192000 can be listened and be decoded from the other raspberry model b and from a pc but not from the model b plus.

**Comment by toots** [comment]
Hi. I'm not sure if the scope of your problem falls within the liquidsoap project. If I'm correct, liquidsoap creates a stream which appears to be correct since a normal PC can decode it but one of the pi model cannot decode it. Is the faulty pi decoder also running liquidsoap?

**Comment by smimram** [comment]
Does not really look like a Liquidsoap bug, closing. Please reopen if it is not the case.
