### ISSUE TITLE
Get Mp3 at specific time

### ISSUE THREAD

**Issue by Alias1975** [savonet/liquidsoap#641]
Hi folks,
I'm running liq 1.3.4.
I need to transmit a file with a dynamic name based on the time.

My script:
```
...omissis...

**#Routine for calculate actually Hour**
def  cal_ora() =
  ora = get_process_output("date +%H")
  ors ="/home/videoserver/Scaricati/tm/donna/ora/#{ora}.mp3"
  ors = string.replace(pattern="\n",fun (_) -> "",ors)
  print(ors)
  audio_to_stereo(single(ors))
end

**#Routine for calculate actually Minute**
def  cal_min() =
  minuti = get_process_output("date +%M")
  mis ="/home/videoserver/Scaricati/tm/donna/minuti/#{minuti}.mp3"
  mis = string.replace(pattern="\n",fun (_) -> "",mis)
  print(mis)
  audio_to_stereo(single(mis))
end

**#Routine for Switch calculated time**
def at(pred,s)
	switch([(pred,s)])
end
def crossfade(a,b)
  add(normalize=false,
      [ sequence([ blank(duration=5.),
                   fade.initial(duration=10.,b) ]),
        fade.final(duration=10.,a) ])
end

mattina =    playlist(mode='randomize',reload=1,reload_mode="rounds", "/home/videoserver/Scaricati/bossacover/bossa.m3u")
pomeriggio =  playlist(mode='randomize',reload=1,reload_mode="rounds", "/home/videoserver/Scaricati/bossacover/bossa.m3u")
sera =         playlist(mode='randomize',reload=1,reload_mode="rounds", "/home/videoserver/Scaricati/bossacover/bossa.m3u")

# Schedulazione playlist su fascia oraria
schedule = switch(track_sensitive=false,
        [
                ({20h-8h}, sera),
                ({8h-12h}, mattina),
                ({12h-20h}, pomeriggio),
                ({ true }, sera)
        ])

s1 = at({10h48-10h54},cal_ora())
s2 = at({10h48-10h54},cal_min())

rotation =  rotate(weights=[1,1,1],[s1,s2,schedule])
radio  = on_metadata(r_metadata,rotation)
radio = fallback([radio,security])

...omissis...
```

Example:
if the song (sensitive=true) end in this range [10h48-10h54] the system will have to calculate the exact time --> 10:51 so i can get the file 10.mp3 and 51.mp3

Where i wrong?
actually (with this script) the outputs routine (cal_ora and cal_min)   returns me the time of  the script was started.

**Comment by Alias1975** [comment]
update:
i insert this function

ref myh = ""
def cal_ora() =
ora = get_process_output("date +%H")
ors ="/home/videoserver/Scaricati/tm/donna/ora/#{ora}.mp3"
ors = string.replace(pattern="\n",fun (_) -> "",ors)
print(ors)
myh := audio_to_stereo(single(ors))
1.0
end

add_timeout(fast=false,20.,cal_ora)
rotation =  rotate(weights=[1,1,1],[spot,{myh},radio])  #line 65


but the response error is:
this value has type
    **float
  but it should be a subtype of
    int (inferred at line 65)**

can i setting REF as source(_) ????

**Comment by gilou** [comment]
use the code blocks (```) so we can read your code properly.. but your ref is a string at the beginning, not a source, and I don't understand the `{ }` syntax here... You probably should use a dynamic source here.

**Comment by Alias1975** [comment]
TY for your reply.
i'm apology in advance for my poor english.
is there a way to set REF into source?

the `{!#variable_name}` should call a value in the DEF routine.
I read the reference and I think the syntax is correct

**Comment by gilou** [comment]
You can set it to a single() something as a fallback, but the type error is probably not related to this.

I would set your source as a dynamic one as I said.. See https://www.liquidsoap.info/doc-dev/request_sources.html

**Comment by Alias1975** [comment]
ok ok, now i understand what you said.

if i set timeout on dynamic_request it should work...
thanks a lot, i'll try code nexy monday.
If work i'll post the entire code.

**Comment by gilou** [comment]
why bother with add_timeout at all? Just set up a dynamic request that will always set the proper source?

**Comment by Alias1975** [comment]
no it does not work I had already tried time ago, after the first tier the name of the m3 remains static.

eg.  
```
def time_hour()
result =
    list.hd(get_process_lines("php_hour_calculate"))
  request.create(result)
end
s = request.dynamic(time_hour)

rotation =  rotate(weights=[1,1,1],[spot,s,radio])  
```

the **s** after the first loop it does not change anymore, so if the 1° calculate is 10-30.mp3 after new loop of rotare it remaing 10-30.mp3
the def is no longer referred to in practice

**Comment by gilou** [comment]
What does `php_hour_calculate` do? using request.dynamic, the function is called everytime the source is activated.

**Comment by Alias1975** [comment]
so i try this script
```
spot =       playlist(mode='randomize',reload=1,reload_mode="rounds", "/var/www/html/admin/spot.m3u")

# Schedulazione playlist su fascia oraria

def orer() = 
  # Get the first line of my external process
  result = list.hd(default="", get_process_lines("php -q ore.php"))
  # Create and return a request using this result
  request.create(result)
  
end

# Create the source
s = request.dynamic(orer)

rotation =  rotate(weights=[1,1],[spot,s])
radio = fallback([rotation,security])
```

ore.php is:

```
<?php 
$h = date('H') .".mp3"; 
echo 'audio_to_stereo(single("ORARIO/ore/'.$h."))'
?>
```

all path are correct but the rotation play only "spot", where i wrong?

**Comment by gilou** [comment]
your php script seems wrong..
`echo 'audio_to_stereo(single("ORARIO/ore/'.$h.'"))'`
shuold be better ?

**Comment by Alias1975** [comment]
yes  there was an error, but the situation has not changed.
i set full path too:

```
<?php 
$h = date('H') .".mp3"; 
echo 'audio_to_stereo(single("/var/www/html/ORARIO/ore/'.$h.'"))'
?>
```

but the spot playlist is only that work. 

i read the log:

Nonexistent file or ill-formed URI "audio_to_stereo(single(\"/var/www/html/sangiorgio/ORARIO/ore/14.mp3\"))"!

I think the error is in formatting the PHP string

**Comment by gilou** [comment]
yeah, you must deliver a source using a known protocol, so just "/var/www/html/sangiorgio/ORARIO/ore/14.mp3", you can call audio_to_stereo(s) later on. single is not really required, it will be selected as such anyway.

**Comment by Alias1975** [comment]
WELL NOW IT WORK
this is the full code for community:

```
security = audio_to_stereo(single("/var/www/html/admin/FLASH.mp3"))

spot = playlist(mode='randomize',reload=1,reload_mode="rounds", "/var/www/html/admin/spot.m3u")

# Def for call PHP script for real-time hour
def orer() = 
  resulth = list.hd(default="", get_process_lines("php -q /var/www/html/sangiorgio/ore.php"))
  request.create(resulth)
end

# Def for call PHP script for real-time minute
def minr() = 
  resultm = list.hd(default="", get_process_lines("php -q /var/www/html/sangiorgio/min.php"))
  request.create(resultm)
end
# call dynamic Hour value
s = request.dynamic(orer)
# call dynamic minute value
sm = request.dynamic(minr)
# set hour and minute as source
s1 = audio_to_stereo(s)
s2 = audio_to_stereo(sm)
#insert in rotation
rotation =  rotate(weights=[1,1,1],[spot,s1,s2])
#fallback
radio = fallback([rotation,security])
```
PHP Files:
```
<?php 
// hour
echo "/var/www/html/sangiorgio/ORARIO/ore/".date('H') .".mp3";  \\ full server path of file is recommended
?>
<?php 
// minute
echo "/var/www/html/sangiorgio/ORARIO/minuti/".date('i') .".mp3"; 
?>
```

Thanks lot to [gilou](https://github.com/gilou)

**Comment by gilou** [comment]
Don't forget to close the issue! Glad you worked it out! :+1:
