### ISSUE TITLE
How play audio files in directory (not playlist)

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [savonet/liquidsoap#642]
Good afternoon, I saw in the possibilities that liquidsoap can 

> Playing from files, playlists, **directories** or script playlists (plays the file chosen by an external program)

But I can not find how to do it, ie playlist turns out to do, and I realized that you can just specify the directory and liquidsoap will be able to take all the audio files from there to your playlist (most likely even recursively be able to enter the folders)

**Comment by Alias1975** [comment]
hi,
dir1 = playlist(mode='randomize',reload=1,reload_mode="rounds", "/your/path/dir/")

This command work same as playlist file (m3u) and reload index folder every 1 minute.
So if add a new file in the folder LiquidSoap read the added file.

**Comment by takenp** [comment]
@Alias1975 

could you confirm that 'reload=1' means reloading every 1 minute, 'coz  on [liquidsoap.info](https://www.liquidsoap.info/doc-1.3.3/cookbook.html)
they say:

> # can be reloaded every 10 minutes.
> playlist(reload=600,"http://my/playlist.txt")

**Comment by smimram** [comment]
The unit of time in reload is seconds, so `reload=1` means reload every 1 second.
