### ISSUE TITLE
Unknown protocol "C" in URI "C:\\RADIO\\MUSIC\reggae"

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [savonet/liquidsoap#646]
Good day, Strange behavior noticed on similar folders
Both folders present, both folders contain files, path correct
But why folder **reggae** doesn't found?

[radio.liq.txt](https://github.com/savonet/liquidsoap/files/2512451/radio.liq.txt)
[radio.log](https://github.com/savonet/liquidsoap/files/2512443/radio.log)

**Comment by gilou** [comment]
Because you got lucky over the escaping I'd say ... Doesn't "/" work on Windows? Otherwise, just escape your string: "C:\\RADIO\\MUSIC\\reggae" (as the others seem to be escaped since the second char isn't an escape sequence?).

**Comment by strelkovandreyvalerievich** [comment]
Hmm, I try change path to **"C:\\RADIO\\MUSIC\\reggae"** but the same result :(

**Comment by gilou** [comment]
It is because \r is an escape sequence, same would probably happen with a `n`, or a `t` e.g. ;) see https://en.wikipedia.org/wiki/Escape_sequences_in_C for reference.

**Comment by smimram** [comment]
Since it seems to only be an escaping problem, I'm closing this for now. Thanks @gilou for answering.

**Comment by strelkovandreyvalerievich** [comment]
> It is because \r is an escape sequence, same would probably happen with a `n`, or a `t` e.g. ;) see https://en.wikipedia.org/wiki/Escape_sequences_in_C for reference.

Thanks, that's clear now. I did not know about this behavior `\r`
