### ISSUE TITLE
Automatically creating audio "snippets" based on blank / sound detection.

### ISSUE THREAD

**Issue by virtualfunction** [savonet/liquidsoap#651]
Hi toots and co, not sure if this is the right place to ask (could see if you have a Slack channel or similar). Anyhow think it's probably worth asking here because I'm sure others might need similar functionality so might be worth documenting it here or officially. 

Basically, we have an audio line that is quite often silent, but occasionally has broadcasts. I want to be able to record this, but rather than record all of the silence as well I just want to record the bits where a sound is detected. The file name should reflect when the audio started e.g. `2018-11-08h_07m-22s.opus`

I'm not totally sure how to do this. I gather `output.file` has reopen_when but I can't see a clone_when option for when the line input triggers blank. Likewise I'm not entirely sure how you get it to trigger when there is audio (I'm, guessing using the `on_noise` option of `on_blank`?). I'm sure you'll be able to mock up an example on here pretty quickly when you have a moment to illustrate this.

**Comment by gilou** [comment]
use a fallible output ?

**Comment by toots** [comment]
Yes. I believe a fallible `oupput.file` just before you apply whatever solution you have to add blank (prolly `mksafe`) would do the the trick. I'm trying to keep things only about issues and feature requests so I'm gonna close it but don't hesitate to follow-up on the mailing list.

PS: a slack channel would be nice. I personally wouldn't have time to participate but if the community wants to set one up I'd be happy to include it on the website.

**Comment by virtualfunction** [comment]
OK, thanks, I think I've managed to achieve what's needed. 

Here's what I'm using, in case anyone is reading this issue looking for the same functionality. I'm using JACK audio here just because I can control what I pip into it better than the pulse / ALSA mic input.

Only downside to this is that I do have a trailing 5 sec of silence. If there's an easy way to get rid of this that would be handy. For now I have another background task that picks up the FLAC file and converts it to OPUS (because the Liquidsoap 1.1.1 has a bug with OPUS in Debian distros i think) and takes off the silence with FFMPEG
```
set('log.file.path', '/tmp/audio.log')
set('log.stdout', true)
sound = input.jack(id = 'input_audio', buffer_size = 2)
output.file(
  %ogg(%flac(channels = 1, samplerate = 48000)), %opus(mono, samplerate = 16000, vbr = "unconstrained") # Does not work on 1.1.1
  'snippets/%Y-%m-%d_%H-%M-%S.flac.ogg',
  reopen_delay = 1.0,
  fallible = true,
  flush = true,
  strip_blank(max_blank = 5.0, sound)
)
```
