### ISSUE TITLE
Liquidsoap 1.3.4 not working with custom crossfade

### ISSUE THREAD

**Issue by wizbox** [savonet/liquidsoap#652]
I am using the following code for a custom crossfade what supports jingles:

```
def my_crossfade(s) =
  def f(_,_, old_m, new_m, old, new) =
    if old_m["genre"] != "myradio" and new_m["genre"] != "myradio" then
      add([fade.initial(new), fade.final(old)])
    else
      log("Old or new file is a jingle: sequenced transition.")
      sequence([old,new])
    end
 end
 smart_cross(f,s)
end
```

This works perfectly on liquidsoap 1.3.3, however, on liquidsoap 1.3.4, the jingles are detected in the logs but when they are played, silence happens instead?

**Comment by toots** [comment]
First test script fails to reproduce:

```
def my_crossfade(s) =
  def f(_,_, old_m, new_m, old, new) =
    if old_m["genre"] != "myradio" and new_m["genre"] != "myradio" then
      add([fade.initial(new), fade.final(old)])
    else
      log("Old or new file is a jingle: sequenced transition.")
      sequence([old,new])
    end
 end
 smart_cross(f,s)
end

myradio = playlist(prefix="annotate:genre=\"myradio\":","~/music")
jingles = playlist(prefix="annotate:genre=\"jingles\":","~/music")

s = rotate([myradio,jingles])

s = my_crossfade(s)

output.ao(fallible=true,s)
```

Could you share more from your script? Thks!

**Comment by toots** [comment]
And also log snippets would help.

**Comment by wizbox** [comment]
Here is a stripped down version of my script which it fails to play jingles on 1.3.4:

`# --Settings--

# Settings Log
set("log.file",true)
set("log.file.path","/var/log/liquidsoap/myradio.log")
set("log.stdout",false)
set("log.level",3)

# Settings Telnet
set("server.telnet",true)
set("server.telnet.bind_addr","127.0.0.1")
set("server.telnet.port",3033)
set("server.timeout",3600.)

# Settings Various
set("init.daemon.pidfile.path","/var/run/liquidsoap/myradio.pid")


# --Define--

def strip_jingle_meta(m) =
if m["genre"] == "myradio" then
  []
else
    m
  end
end

# Define Custom Crossfade
def my_crossfade(s) = 
  def f(_,_, old_m, new_m, old, new) = 
    if old_m["genre"] != "myradio" and new_m["genre"] != "myradio" then
      add([fade.initial(new), fade.final(old)])
    else
      log("Old or new file is a jingle: sequenced transition.")
      sequence([old,new])
    end
 end
 smart_cross(f,s)
end

# --Jingles--

# Jingles Playlist music_1
jingle_music_1=playlist("/home/media/myradio/playlists/jingle_music_1.pls",
  conservative=true,mode="normal")

# Jingles Playlist music_2
jingle_music_2=playlist("/home/media/myradio/playlists/jingle_music_2.pls",
  conservative=true,mode="normal")

# Jingles Playlist music_3
jingle_music_3=playlist("/home/media/myradio/playlists/jingle_music_3.pls",
  conservative=true,mode="normal")

# Jingles Playlist music_4
jingle_music_4=playlist("/home/media/myradio/playlists/jingle_music_4.pls",
  conservative=true,mode="normal")

# --Playlists--

# Playlists music_1
music_1=playlist("/home/media/myradio/playlists/music_1.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

# Playlists music_2
music_2=playlist("/home/media/myradio/playlists/music_2.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

# Playlists music_3
music_3=playlist("/home/media/myradio/playlists/music_3.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

# Playlists music_4
music_4=playlist("/home/media/myradio/playlists/music_4.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

# --Schedule--

# Schedule Rotate Jingles
radio_music_1=rotate(weights=[1,2],[jingle_music_1,music_1])
radio_music_2=rotate(weights=[1,2],[jingle_music_2,music_2])
radio_music_3=rotate(weights=[1,2],[jingle_music_3,music_3])
radio_music_4=rotate(weights=[1,2],[jingle_music_4,music_4])

# Schedule Playlists
radio=switch(track_sensitive=true,[
  ({4h-7h},radio_music_1),
  ({7h-16h},radio_music_2),
  ({16h-19h},radio_music_3),
  ({19h-4h},radio_music_4)])

# Schedule Crossfade
radio=my_crossfade(radio)

# Schedule Radio
source=radio

# Strip Jingle Metadata
source=map_metadata(strip=true,update=false,insert_missing=false,strip_jingle_meta,source)

# --Output--

# Output Icecast MP3
clock.assign_new(id="icecast",[
output.icecast(%mp3.vbr(quality=5,internal_quality=0,samplerate=44100),
  encoding="UTF-8",timeout=90.0,connection_timeout=90.0,host="ice.myradio.net",port=80,
  password="password",mount="radio.mp3",icy_metadata="true",name="myradio",
  description="My Radio",genre="electronic",url="https://www.myradio.com",fallible=true,
  source),
output.icecast(%vorbis(samplerate=44100,quality=0.4),
  encoding="UTF-8",timeout=90.0,connection_timeout=90.0,host="ice.myradio.net",port=80,
  password="password",mount="radio.ogg",icy_metadata="false",name="myradio",
  description="My Radio",genre="electronic",url="https://www.myradio.com",fallible=true,
  source)
])`

**Comment by wizbox** [comment]
Here is a stripped down version of my script which jingles fail to play on 1.3.4:

set("log.file",true)
set("log.file.path","/var/log/liquidsoap/myradio.log")
set("log.stdout",false)
set("log.level",3)

set("server.telnet",true)
set("server.telnet.bind_addr","127.0.0.1")
set("server.telnet.port",3033)
set("server.timeout",3600.)
set("init.daemon.pidfile.path","/var/run/liquidsoap/myradio.pid")

def strip_jingle_meta(m) =
if m["genre"] == "myradio" then
  []
else
    m
  end
end

def my_crossfade(s) = 
  def f(_,_, old_m, new_m, old, new) = 
    if old_m["genre"] != "myradio" and new_m["genre"] != "myradio" then
      add([fade.initial(new), fade.final(old)])
    else
      log("Old or new file is a jingle: sequenced transition.")
      sequence([old,new])
    end
 end
 smart_cross(f,s)
end

jingle_music_1=playlist("/home/media/myradio/playlists/jingle_music_1.pls",
  conservative=true,mode="normal")

jingle_music_2=playlist("/home/media/myradio/playlists/jingle_music_2.pls",
  conservative=true,mode="normal")

jingle_music_3=playlist("/home/media/myradio/playlists/jingle_music_3.pls",
  conservative=true,mode="normal")

jingle_music_4=playlist("/home/media/myradio/playlists/jingle_music_4.pls",
  conservative=true,mode="normal")

music_1=playlist("/home/media/myradio/playlists/music_1.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

music_2=playlist("/home/media/myradio/playlists/music_2.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

music_3=playlist("/home/media/myradio/playlists/music_3.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

music_4=playlist("/home/media/myradio/playlists/music_4.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

radio_music_1=rotate(weights=[1,2],[jingle_music_1,music_1])
radio_music_2=rotate(weights=[1,2],[jingle_music_2,music_2])
radio_music_3=rotate(weights=[1,2],[jingle_music_3,music_3])
radio_music_4=rotate(weights=[1,2],[jingle_music_4,music_4])

radio=switch(track_sensitive=true,[
  ({4h-7h},radio_music_1),
  ({7h-16h},radio_music_2),
  ({16h-19h},radio_music_3),
  ({19h-4h},radio_music_4)])

radio=my_crossfade(radio)

source=radio

source=map_metadata(strip=true,update=false,insert_missing=false,strip_jingle_meta,source)

clock.assign_new(id="icecast",[
output.icecast(%mp3.vbr(quality=5,internal_quality=0,samplerate=44100),
  encoding="UTF-8",timeout=90.0,connection_timeout=90.0,host="ice.myradio.net",port=80,
  password="password",mount="radio.mp3",icy_metadata="true",name="myradio",
  description="My radio",genre="electronic",url="https://www.myradio.com",fallible=true,
  source),
output.icecast(%vorbis(samplerate=44100,quality=0.4),
  encoding="UTF-8",timeout=90.0,connection_timeout=90.0,host="ice.myradio.net",port=80,
  password="password",mount="radio.ogg",icy_metadata="false",name="myradio",
  description="My radio",genre="electronic",url="https://www.myradio.com",fallible=true,
  source)
])

**Comment by wizbox** [comment]
The log says:

2018/11/09 22:57:44 [decoder:3] Method "FLAC" accepted "/home/media/myradio/jingles/jingle.flac".
2018/11/09 22:57:44 [smart_cross_9857:3] Analysis: -19.315977dB / -205.826879dB (5.00s / 5.00s)
2018/11/09 22:57:44 [lang:3] Old or new file is a jingle: sequenced transition.
2018/11/09 22:57:49 [jingle_trance(dot)pls:3] Finished with "/home/media/myradio/jingles/trance.flac".
2018/11/09 22:57:49 [jingle_trance(dot)pls:3] Prepared "/home/media/myradio/jingles/jingle.flac" (RID 25).

Looks ok, but when the jingle is meant to play, silence is played instead?

**Comment by toots** [comment]
Yeah that all looks fine to me. Could you try with jingles in another format than flac? The flac decoder is tricky and could be the issue here.

**Comment by wizbox** [comment]
I am now using this:

jingle_music_1=playlist(prefix="annotate:genre=\"myradio\":","/home/media/myradio/playlists/jingle_music_1.pls",conservative=true,mode="normal")

I added .wavs to the playlist, again the jingle gets detected, but only silence is played.
I have also tested with a different .wav sample from a difference source, silence only.

I have these libs installed:

base-bigarray   base
base-bytes      base        Bytes library distributed with the OCaml compiler
base-threads    base
base-unix       base
camomile        1.0.1       A Unicode library
conf-libpcre    1           Virtual package relying on a libpcre system installation
conf-m4         1           Virtual package relying on m4
conf-pkg-config 1.1         Virtual package relying on pkg-config installation
cppo            1.6.5       Equivalent of the C preprocessor for OCaml programs
dtools          0.4.1       Library providing various helper functions to make daemons
dune            1.4.0       Fast, portable and opinionated build system
jbuilder        transition  This is a transition package, jbuilder is now named dune. Use the dune
magic           0.7.3       Bindings for libmagic (to determine the type of files)
mm              0.4.0       The mm library contains high-level to create and manipulate multimedia streams (audio, video, MIDI)
ocaml           4.03.0      The OCaml compiler (virtual package)
ocaml-config    1           OCaml Switch Configuration
ocaml-system    4.03.0      The OCaml compiler (system version, from outside of opam)
ocamlbuild      0.12.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlfind       1.8.0       A library manager for OCaml
pcre            7.2.3       pcre-ocaml - bindings to the Perl Compatibility Regular Expressions library

**Comment by toots** [comment]
Ok thanks. Let's try to break this down one step at a time.

First, I don't think that you need the `clock.assign_new`. Does it work without it?

Also, does it stream blank in both icecast output?

**Comment by wizbox** [comment]
Ok, i've created a ultra simple script what doesn't play jingles on 1.3.4 wav or flac:

set("log.file",true)
set("log.file.path","/var/log/liquidsoap/myradio.log")
set("log.stdout",false)
set("log.level",3)
set("server.telnet",true)
set("server.telnet.bind_addr","127.0.0.1")
set("server.telnet.port",3033)
set("server.timeout",3600.)
set("init.daemon.pidfile.path","/var/run/liquidsoap/myradio.pid")

def strip_jingle_meta(m) =
if m["genre"] == "myradio" then
  []
else
    m
  end
end

def my_crossfade(s) = 
  def f(_,_, old_m, new_m, old, new) = 
    if old_m["genre"] != "myradio" and new_m["genre"] != "myradio" then
      add([fade.initial(new), fade.final(old)])
    else
      log("Old or new file is a jingle: sequenced transition.")
      sequence([old,new])
    end
 end
 smart_cross(f,s)
end

jingle=playlist(prefix="annotate:genre=\"myradio\":","/home/media/myradio/playlists/jingles.pls",conservative=true)

trance=playlist("/home/media/myradio/playlists/trance.pls",
  conservative=true,mode="randomize",reload=1,reload_mode="rounds")

radio=rotate([jingle,trance])

source=my_crossfade(radio)

output.icecast(%mp3.vbr(quality=5,internal_quality=0,samplerate=44100),
  encoding="UTF-8",timeout=90.0,connection_timeout=90.0,host="ice.myradio.net",port=80,
  password="password",mount="radio.mp3",icy_metadata="true",name="myradio",
  description="My radio",genre="electronic",url="https://www.myradio.com",
  source,fallible=true)

output.icecast(%vorbis(samplerate=44100,quality=0.4),
  encoding="UTF-8",timeout=90.0,connection_timeout=90.0,host="ice.myradio.net",port=80,
  password="password",mount="radio.ogg",icy_metadata="false",name="myradio",
  description="My radio",genre="electronic",url="https://www.myradio.com",
  source,fallible=true)


If this works on your setup, maybe there is something wrong with my install or im missing something when I compiled Liquidsoap?

**Comment by wizbox** [comment]
Also, the jingle plays when the script is first launched, but then after that it goes silent when its meant to play?

**Comment by wizbox** [comment]
I just had a break through! I converted wavs to mp3s, now they are playing! some kind of problem with .wav and .flac when they are played as jingles through a custom crossfade?

**Comment by wizbox** [comment]
arghhhhhh there is something wrong with my jingle samples, i just tested with a mp3 test audio file and now they are played and are detected as jingles. Maybe liquidsoap 1.3.4 is more fussy about the length or bitrate?

**Comment by wizbox** [comment]
Yes, Icecast streams blank on both outputs when jingle is meant to be played.

**Comment by toots** [comment]
Thanks for trying this. Let's break it down even more if you don't mind. If seems that with a rotate like that the transition will always be the jingles one. Thus, let's cut down the smart cross:
```
def my_crossfade(s) =
  def f(_,_, old_m, new_m, old, new) =
    sequence([old,new])
 end
 smart_cross(f,s)
end
```

Also, could you try with only one `output.icecast`? Thks!

**Comment by toots** [comment]
Ha sorry just saw the last message. Yeah that could be it. Any chance you could send me one of these jingles at toots@rastageeks.org?

**Comment by toots** [comment]
I don't think I received the audio.. Would you mind sending them again? Also give the email title in case I have to search in the spam folder.. Thks!

**Comment by toots** [comment]
Hey! Any update on this? Still haven't received the files..

**Comment by wizbox** [comment]
I sent email with .zip attachment with subject line: 
Liquidsoap 1.3.4 not working with custom crossfade (#652)

**Comment by toots** [comment]
Sorry but I really cannot find this email. If the tracks can be shared in public maybe you could upload them somewhere and send a link here? Would love to fix this one in the context of #664..

**Comment by dhannyz** [comment]
I also had crashes recently with the crossfade / smart_crossfade helper when combined with a fallback().
I had a live harbor stream with a fallback to to a crossfaded playlist. Upon the connection of a DJ (mixxx) the live connection would crash instantly

**Comment by savonet-users** [comment]
oh guys, i don't know what to do. at times this new version looked like it 
was doing okay, it even seemed that it solved some old issues (and it did, 
in a way), but it's really mysterious and full of surprise bugs. memory 
leaks, crashes, not doing what told to do, and out of a sudden pretending to 
and actually working normally.

as i understand this new version was built some other way than the old ones, 
using some new 'easier' pathway for cross compiling. maybe that makes it a 
disaster, i don't know.

i have two options now: go back to the last 32bit version when it was kind 
of predictable and leak free, or try to build a new 64bit one myself.
also, what about cygwin? maybe a cygwin version would be less work for 
developers and then at least it would have the same bugs as linux version? 
or should i try cygwin path myself?

are there any runtimes or other external things in windows that it depends 
on? i dont' know where to start, even the debugger is broken in that thing, 
it's a complete mess that's working by a miracle... and sometimes i find it 
having eaten 24GB of RAM, or crashed out of the blue, not decoding things it 
apparently supports, even playing playlists at wrong times! [the config 
hasn't changed for years, just some expressions were adapted to the new 
syntax]

it's really weird.

regards,
p

**Comment by toots** [comment]
@dhannyz would you mind filling a bug report at https://github.com/savonet/liquidsoap/issues/new?template=bug_report.md ? Thanks

**Comment by toots** [comment]
Oh okay, I see the issue I think. Yeah, crossfade consumes data faster that real time and live source can only stream real time and not faster (because they're live..) so using them inside a crossfade will trigger a clock failure, which is expected.
