### ISSUE TITLE
Sometimes Liquidsoap streams silence

### ISSUE THREAD

**Issue by mkonecny** [savonet/liquidsoap#66]
We have two users that have mentioned their stream goes silent during the night.

http://forum.sourcefabric.org/discussion/15111/airtime-audio-fails-daily/p1
http://forum.sourcefabric.org/discussion/15412/unidentified-problem/p1

I've done some extensive analysis into what could be causing this problem - It appears it may be Liquidsoap related because I can see in the logs that Liquidsoap's queue did have tracks in it. It's only after Liquidsoap is restarted that audible output is heard.

Another user has mentioned that connecting to Liquidsoap via input.harbor "awakens" it.

```
s = queue(...)

s = if slave_enabled then
    slave_live = mksafe(
        audio_to_stereo(
            input.harbor(...)))

    ignore(output.dummy(slave_live, fallible=true))

    switch(id="show_schedule_noise_switch",
            track_sensitive=false,
            transitions=[transition, transition],
            [({!live_slave_enabled}, slave_live), ({true}, s)]
        )
else
    s
end

s = if master_enabled then
    master_live = mksafe(
        audio_to_stereo(
            input.harbor(...)))

    ignore(output.dummy(master_live, fallible=true))

    switch(id="show_schedule_noise_switch",
            track_sensitive=false,
            transitions=[transition, transition],
            [({!live_master_enabled}, master_live), ({true}, s)]
        )
else
    s
end

out(s)
```

One user gave me ssh access, and I could **not** get the output started unless restarting liquidsoap. I was able to see that tracks were in the queue, and I tried changing `live_slave_enabled` and `live_master_enabled` on/off via telnet to no effect.

The one lead I have right now is the user connecting to input.harbor and disconnecting again - any ideas how I should approach narrowing this down further?

**Comment by toots** [comment]
Hi,

Unfortunately, this issue is so old that I don't think we'll ever be able to fix it in the current codebase. Closing now.. :-/
