### ISSUE TITLE
Help with crossfade

### ISSUE THREAD

**Issue by ArvyRogerio** [savonet/liquidsoap#662]
Hello,

I'm fighting with smart_crossfade for several hours. I'm trying to trigger the new song when the old song reaches -9dB in last 2-3 seconds of it, and I just want to overlap them, no fade in/out. All songs already has a small fade out on them (in general, last 3 seconds of fade out, from 0 dB to -inf dB).

`source = smart_crossfade(start_next=3.,fade_in=0.,fade_out=0.,high=-9.,medium=-12.,margin=0.,width=3.,source)`

I don't understand the concept of "high" and "medium"... I mostly receive "No transition: using default". And, sometimes, the new song enters with a small cut in the beggining (rarely) and sometimes the crossfade works...

Is possible to create a function that "monitors" the last seconds of the actual song and trigger the new one when the signal/power is below -9dB, for example?

Any ideias are really appreciated!

**Comment by toots** [comment]
Hi,

The `smart_crossfade` is defined in `utils.liq`: https://github.com/savonet/liquidsoap/blob/master/scripts/utils.liq#L419

If you look at the code there you should be able to understand what its doing and also write your own version of it..
