### ISSUE TITLE
Cannot read WMA files

### ISSUE THREAD

**Issue by ArvyRogerio** [savonet/liquidsoap#663]
**Describe the bug**
Error when reading WMA files (decode)

**Version details**
 - OS: Ubuntu
 - Version: 18.10
- Liquidsoap: 1.3.4

**Install method**
Opam with Gstreamer

------

2018/11/27 15:18:53 [decoder:3] Unable to decode "/var/www/html/arquivos/programas/8/1543337553638.wma" as {audio=2;video=0;midi=0}!

(Liquidsoap:9904): GStreamer-CRITICAL **: 15:18:53.161:
Trying to dispose element fakesink0, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.

* 5 same errors with: fakesink0, pipeline0, audioresample0, audioconvert0, filesrc0

**Comment by ArvyRogerio** [comment]
Same error occurs with MP4 files too... but, in the end, it plays.

MP4 erros with: fakesink0,  pipeline0, filesrc0

**Comment by toots** [comment]
Hi,

You should make sure that you have the right `gstreamer` plugins installed.

In the next future, we will recommend using `ffmpeg` for these formats. With the latest release what you should do is:
- Install the `ffmpeg` `opam` package.
- Add this line to your script:
```
 set("decoder.file_extensions.ffmpeg",["mp3","mp4","m4a","wav","flac","ogg","wma"])
```

**Comment by toots** [comment]
Awesome, thanks.
