### ISSUE TITLE
Question: Approximate Liquidsoap Package Build with OPAM

### ISSUE THREAD

**Issue by BusterNeece** [savonet/liquidsoap#665]
I'm in the process of trying to build a base Docker image that has Liquidsoap built from source using OPAM 2, but that follows the general expectations of locating the binary, logs, config, etc. in the same normal spots that it would put them in a packaged build.

The closest approximation I can come to this is to have OPAM generate a "switch" in a folder dedicated for Liquidsoap.

Any recommendations for best practices on this? It would be very handy if I could build out a Docker image for Liquidsoap that other people can use out of the box (and that I can use as the upstream for my own containers)!

**Comment by toots** [comment]
The Dockerfile for the windows build is here: https://github.com/savonet/liquidsoap-full/blob/master/docker/Dockerfile.win32

The step that is important is copying the camomile definitions into the stand alone local folder:
```
cp -rf `ocamlfind -toolchain windows ocamlc -where`/../../share/camomile .
```

**Comment by SlvrEagle23** [comment]
@toots Ah, didn't even realize Liquidsoap itself has Docker build files already in its repos. Thanks for pointing me in that direction!

**Comment by toots** [comment]
Hmm. Sorry I might have responded too quickly 🙂 Looking back at your message I believe all you'd need is a normal build. Yeah, just check out our own Docker image. Also, the `savonet/liquidsoap-full` docker image should have the latest build most of the time.

**Comment by SlvrEagle23** [comment]
@toots The liquidsoap-full dockerfiles are definitely a good start and I can probably work backwards from there, but my question was whether it's possible to use the OPAM-based installation (i.e. installing all of the LS dependencies and LS itself via OPAM 2) to produce an installation that "looks and feels" like one of the packaged builds, i.e. the binary is in `/usr/bin/liquidsoap`, it's looking for `/etc/liquidsoap.conf`, that kind of stuff.

I currently have a Docker build based on OPAM 2 that works just fine in my environment, but it contains all of Liquidsoap inside a folder alongside OPAM itself, and it doesn't seem to be possible to separate the two.

This could definitely just be a limitation of the recommended OPAM installation method, but it would be nice to take advantage of OPAM's flexibility and built-in dependency resolving while producing something that others can use downstream without much confusion.

**Comment by toots** [comment]
@SlvrEagle23 If you change the `prefix` here: https://github.com/savonet/liquidsoap/blob/master/liquidsoap.opam you can have a `opam` package definition that installs anywhere you want, including in `/usr/local/bin`. For installing in other locations, you might have to also add `sudo` to the install command, though.

I'd recommend creating a custom named package like `liquidsoap-global` and using the `opam` pinning system, that should work pretty nicely.
