### ISSUE TITLE
Metadata update liquidsoap from external stream

### ISSUE THREAD

**Issue by rafkos5889** [savonet/liquidsoap#667]
Welcome I have such a problem with the application streaming liquidsoap He wants the Stream Name: and Stream genere to change when the DJ plays live with the shoutcast server.

Progressive internet radio and my rds are still showing auto DJ content even when an external stream is broadcasting.

Statistics screenshot

http://prntscr.com/lp6jl4

I use Centovacast software version 3

requests for assistance

**Comment by TheRealMattLear** [comment]
Hi, hate to reopen an older issue however i just wanted to clarify if this is an issue only with the shoutcast v1 protocol and if this is alleviated with the v2 protocol? (where an enhancement exists separately at #430)

**Comment by toots** [comment]
It is an issue with the `v1` protocol. We currently have no plans to implement the `v2` but we could change our mind if the needs arises and licensing terms have been cleared.
