### ISSUE TITLE
Change of semantics for the add() operator

### ISSUE THREAD

**Issue by toots** [savonet/liquidsoap#668]
I was working on the scripted fade operators the other day and ran into an issue with add using this code:
```
add(normalize=false,[s,blank(duration=5.)])
```
My intuitive idea was to add a blank source to `s` in order to make sure that the resulting source would run for at least 5s even if `s` ended earlier.

However, this didn't work as expected. `add` actually pumps as much data as it can and removes all track marks.

I also experienced a freeze in the streaming thread while experimenting with it, mostly likely because `add` does not currently ticks its child's sources while pumping more than once.

I suggest that we should change and simplify `add` behavior the following way:
- `add` gets data from each source only once per clock cycle. The furthest break is kept. If that is a partial fill (track mark) then let it be.
- `add` keeps metadata from all sources. Let the user decide if he/she wants to silence a source by dropping all metadata on it.

**Comment by toots** [comment]
I think this is too late for the coming release.

**Comment by smimram** [comment]
Is it improved by #1012?

**Comment by toots** [comment]
Ok, just getting back to this.

First problem: `blank` is marked as `is_ready` even past its duration.. Fixed now..

**Comment by toots** [comment]
I merged the other branch. Only thing that wasn't implemented is the changes in metadata. It's documented that only the metadata from the first source are passed and it is not a bug so I left it this way.
