### ISSUE TITLE
Compilation error Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by TorchwoodPL** [savonet/liquidsoap#675]
**Describe the bug**
When I try to compile liquidsoap I always get:

> OCAMLOPT -o liquidsoap
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x35d): undefined reference to `SSL_library_init'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x362): undefined reference to `SSL_load_error_strings'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x381): undefined reference to `CRYPTO_num_locks'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x3c9): undefined reference to `CRYPTO_num_locks'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x3d9): undefined reference to `CRYPTO_set_locking_callback'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x3e5): undefined reference to `CRYPTO_set_id_callback'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x3f1): undefined reference to `CRYPTO_set_dynlock_create_callback'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x3fd): undefined reference to `CRYPTO_set_dynlock_lock_callback'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_init':
> (.text+0x409): undefined reference to `CRYPTO_set_dynlock_destroy_callback'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_create_context':
> (.text+0x543): undefined reference to `SSLv23_client_method'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_create_context':
> (.text+0x631): undefined reference to `SSLv23_server_method'
> /usr/lib/ocaml/ssl/libssl_threads_stubs.a(ssl_stubs.o): In function `ocaml_ssl_create_context':
> (.text+0x681): undefined reference to `SSLv23_method'
> collect2: error: ld returned 1 exit status
> File "caml_startup", line 1:
> Error: Error during linking
> ../Makefile.rules:109: recipe for target 'liquidsoap' failed
> make[3]: *** [liquidsoap] Error 2
> make[3]: Leaving directory '/home/ubuntu/liquidsoap-build/liquidsoap-1.2.1-full/liquidsoap-1.2.1/src'
> ../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
> make[2]: *** [all-auto-ocaml-prog] Error 2
> make[2]: Leaving directory '/home/ubuntu/liquidsoap-build/liquidsoap-1.2.1-full/liquidsoap-1.2.1/src'
> Makefile.rules:27: recipe for target 'all-subdirs' failed
> make[1]: *** [all-subdirs] Error 2
> make[1]: Leaving directory '/home/ubuntu/liquidsoap-build/liquidsoap-1.2.1-full/liquidsoap-1.2.1'
> Makefile:11: recipe for target 'all' failed
> make: *** [all] Error 1

**To Reproduce**
This is a script for version 1.2.1, I also tied on 1.3.0, newest one and latest commit:

```
#!/bin/sh

sudo apt-get install -y build-essential git automake

mkdir -p "$HOME/liquidsoap-build"
cd "$HOME/liquidsoap-build"

wget https://github.com/savonet/liquidsoap/releases/download/1.2.1/liquidsoap-1.2.1-full.tar.gz
tar xvzf liquidsoap-1.2.1-full.tar.gz

cd liquidsoap-1.2.1-full

# Pick most the audio packages
cat > PACKAGES <<EOF
ocaml-cry
ocaml-ao
ocaml-alsa
ocaml-mad
ocaml-taglib
ocaml-lame
ocaml-shine
ocaml-ogg
ocaml-vorbis
ocaml-speex
ocaml-theora
ocaml-opus
ocaml-fdkaac
ocaml-faad
ocaml-flac
ocaml-soundtouch
ocaml-samplerate
ocaml-xmlplaylist
ocaml-lastfm
ocaml-lo
ocaml-dtools
ocaml-duppy
ocaml-mm
liquidsoap
EOF

sudo apt-get -y install \
    checkinstall \
    ocaml-nox \
    pkg-config \
    libpcre-ocaml-dev \
    libcamomile-ocaml-dev \
    libxmlm-ocaml-dev \
    libmagic-ocaml-dev \
    libssl-ocaml-dev \
    libyojson-ocaml-dev \
    libao-dev \
    libasound2-dev \
    libmad0-dev \
    libtag1-dev \
    libmp3lame-dev \
    libogg-dev \
    libvorbis-dev \
    libfdk-aac-dev \
    libfaad-dev \
    libflac-dev \
    libsamplerate0-dev \
    libshine-dev \
    libspeex-dev \
    libtheora-dev \
    libopus-dev \
    libsoundtouch-dev \
    liblo-dev || exit 1

if [ ! -f "/usr/local/lib/ocaml/$(ocaml -vnum)/inotify/META" ]
then
    echo "Installing requirement ocaml-inotify"

    wget -O ocaml-inotify-2.3.tar.gz https://github.com/whitequark/ocaml-inotify/archive/v2.3.tar.gz
    tar xvzf ocaml-inotify-2.3.tar.gz

    cd ocaml-inotify-2.3
    ./configure || exit 1
    make || exit 1
    sudo make install || exit 1

    cd ..
else
    echo "ocaml-inotify-$(grep '^version' /usr/local/lib/ocaml/$(ocaml -vnum)/inotify/META | sed -e 's/.*"\([^"]*\)".*/\1/') already installed"
fi

sudo adduser --system --disabled-password --group liquidsoap
sudo adduser liquidsoap audio

./configure \
    --disable-gui \
    --disable-graphics \
    --localstatedir=/var \
    --sysconfdir=/etc \
    || exit 1

make || exit 1

sudo dpkg -r liquidsoap

LIQUIDSOAP_PKG_VER="1.3.0~dtcooper~$LIQUIDSOAP_GIT_REV"
sudo checkinstall \
    --pkgname=liquidsoap --pkgversion="$LIQUIDSOAP_PKG_VER" \
    --fstrans=no --backup=no --deldoc=yes -y

cd ../..
sudo rm -rf "$HOME/liquidsoap-build"

echo "--------------"
echo
echo "Liquidsoap-$LIQUIDSOAP_PKG_VER installed, use \`dpkg -r liquidsoap\` to remove"

```

**Expected behavior**
Compile, install and work

**Version details**
 - Ubuntu 16.04 LTS

**Install method**
Source

**Comment by toots** [comment]
Any reason for not using `opam` to install? `opam` also handles required external packages.

**Comment by TorchwoodPL** [comment]
I had no idea how :P
