### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by MBoberski** [savonet/liquidsoap#676]
**Describe the bug**
When I try to load my playlist I get a lots of:
2018/12/12 01:52:31 [decoder:3] Unable to decode "/home/disk/obs/Trailers/Transference - Launch Trailer (480p_30fps_H264-128kbit_AAC).mp4" as {audio=2;video=1;midi=0}!

**To Reproduce**
```
Runtime script:

set("frame.video.width", 1280)
set("frame.video.height", 720)
set("frame.video.samplerate", 25)
set("gstreamer.add_borders", false)

s = playlist.safe("shuffle.m3u",reload_mode="watch")
s = fallback([s, blank()])
s = video.add_image(
       width=300,height=100,
       x=10,y=10,
       file="logo_alfa.png",
       s)
       
  output.gstreamer.audio_video(
  video_pipeline=
    "videoconvert ! x264enc bitrate=2000 ! video/x-h264,profile=baseline ! queue ! mux.",
  audio_pipeline=
    "audioconvert ! voaacenc bitrate=44100 ! queue ! mux.",
  pipeline=
    "flvmux name=mux ! rtmpsink location=\"rtmp://live-ams.twitch.tv/app/[KEY] live=1\"",
  s)
```

**Expected behavior**
It was working before, I onlu reinstal linux isntance and install gstreamer and liquidsoap from apt

**Version details**
 - Ubuntu 16.04

**Install method**
apt

**Comment by TorchwoodPL** [comment]
any idea?

**Comment by toots** [comment]
Hi,

What version of liquidsoap are you using? Also, what gstreamer plugin packages do you have installed?

**Comment by TorchwoodPL** [comment]
> root@h-y:~# liquidsoap --version
> Liquidsoap 1.1.1
> Copyright (c) 2003-2013 Savonet team
> Liquidsoap is open-source software, released under GNU General Public License.
> See <http://liquidsoap.fm> for more information.

and

> root@h-y:~# gst-launch-1.0 --gst-version
> GStreamer Core Library version 1.14.2

I had problem with gstreamer plugin when I compiled liquidsoap from source, maybe you can help me with how to obtain one...

TIA

**Comment by toots** [comment]
Ok. `1.1.1` is definitely too old I believe. I'd recommend trying with `1.3.4`. You might need to install via `opam` in this case. See: https://www.liquidsoap.info/download.html

**Comment by TorchwoodPL** [comment]
I get:

> [ERROR] The compilation of liquidsoap failed at "make".
> Processing 56/56: [liquidsoap: rm]
> #=== ERROR while installing liquidsoap.1.3.3-1 ================================#
> # opam-version 1.2.2
> # os           linux
> # command      make
> # path         /home/ubuntu/.opam/system/build/liquidsoap.1.3.3-1
> # compiler     system (4.02.3)
> # exit-code    2
> # env-file     /home/ubuntu/.opam/system/build/liquidsoap.1.3.3-1/liquidsoap-30808-2cc945.env
> # stdout-file  /home/ubuntu/.opam/system/build/liquidsoap.1.3.3-1/liquidsoap-30808-2cc945.out
> # stderr-file  /home/ubuntu/.opam/system/build/liquidsoap.1.3.3-1/liquidsoap-30808-2cc945.err
> ### stdout ###
> # [...]
> # OCAMLOPT -c decoder/vorbisduration.ml
> # OCAMLOPT -c decoder/flacduration.ml
> # OCAMLOPT -c decoder/ogg_flac_duration.ml
> # OCAMLOPT -c decoder/taglib_plug.ml
> # OCAMLOPT -c decoder/gstreamer_decoder.ml
> # ../Makefile.rules:192: recipe for target 'decoder/gstreamer_decoder.cmx' failed
> # make[2]: Leaving directory '/home/ubuntu/.opam/system/build/liquidsoap.1.3.3-1/src'
> # ../Makefile.rules:67: recipe for target 'all-auto-ocaml-prog' failed
> # make[1]: Leaving directory '/home/ubuntu/.opam/system/build/liquidsoap.1.3.3-1/src'
> # Makefile.rules:27: recipe for target 'all-subdirs' failed
> ### stderr ###
> # File "outputs/alsa_out.ml", line 26, characters 0-11:
> # Warning 33: unused open Dtools.
> # File "synth/dssi_op.ml", line 228, characters 14-29:
> # Warning 48: implicit elimination of optional argument ?log_errors
> # File "decoder/gstreamer_decoder.ml", line 122, characters 8-44:
> # Error: Unbound value Gstreamer.App_src.push_buffer_string
> # make[2]: *** [decoder/gstreamer_decoder.cmx] Error 2
> # make[1]: *** [all-auto-ocaml-prog] Error 2
> # make: *** [all-subdirs] Error 2
> 
> 
> 
> =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> The following actions failed
>   ∗  install liquidsoap 1.3.3-1

**Comment by toots** [comment]
I believe you should switch to a more recent OCaml compiler:
```
% opam switch 4.07.0
% eval `opam config env`
```
Then you can proceed with the regular install. Don't forget to also install the optional plugins you need. For instance:
```
% opam depext taglib mad lame vorbis cry samplerate gstreamer liquidsoap
% opam depext taglib mad lame vorbis cry samplerate gstreamer liquidsoap
```

**Comment by TorchwoodPL** [comment]
Ok everything compies properly but after I run my script I get:

> (Liquidsoap:30115): GStreamer-CRITICAL **:
> Trying to dispose element fakesink199, but it is in READY instead of the NULL state.
> You need to explicitly set elements to the NULL state before
> dropping the final reference, to allow them to clean up.
> This problem may also be caused by a refcounting bug in the
> application or some element.
> 
> 
> (Liquidsoap:30115): GStreamer-CRITICAL **:
> Trying to dispose element pipeline199, but it is in READY instead of the NULL state.
> You need to explicitly set elements to the NULL state before
> dropping the final reference, to allow them to clean up.
> This problem may also be caused by a refcounting bug in the
> application or some element.
> 
> 
> (Liquidsoap:30115): GStreamer-CRITICAL **:
> Trying to dispose element audioresample199, but it is in PAUSED instead of the NULL state.
> You need to explicitly set elements to the NULL state before
> dropping the final reference, to allow them to clean up.
> This problem may also be caused by a refcounting bug in the
> application or some element.
> 
> 
> (Liquidsoap:30115): GStreamer-CRITICAL **:
> Trying to dispose element audioconvert199, but it is in PAUSED instead of the NULL state.
> You need to explicitly set elements to the NULL state before
> dropping the final reference, to allow them to clean up.
> This problem may also be caused by a refcounting bug in the
> application or some element.
> 
> 
> (Liquidsoap:30115): GStreamer-CRITICAL **:
> Trying to dispose element filesrc199, but it is in PAUSED instead of the NULL state.
> You need to explicitly set elements to the NULL state before
> dropping the final reference, to allow them to clean up.
> This problem may also be caused by a refcounting bug in the
> application or some element.

my script is:

```
set("frame.video.width", 1280)
set("frame.video.height", 720)
set("frame.video.samplerate", 25)
set("gstreamer.add_borders", false)

s = playlist.safe("shuffle.m3u",reload_mode="watch")
s = fallback([s, blank()])
       
  output.gstreamer.audio_video(
  video_pipeline=
    "videoconvert ! x264enc bitrate=2000 ! video/x-h264,profile=baseline ! queue ! mux.",
  audio_pipeline=
    "audioconvert ! voaacenc bitrate=44100 ! queue ! mux.",
  pipeline=
    "flvmux name=mux ! rtmpsink location=\"rtmp://live-ams.twitch.tv/app/live_138237184_tygleRgXiKHiAziN2sqtIGMGF1QMtU live=1\"",
  s)
```

**Comment by TorchwoodPL** [comment]
I buid gstreamef from source nad now I get many:

> 2018/12/17 23:07:31 [decoder:3] Unable to decode "/home/disk/obs/Trailers/Captain Toad_ Treasure Tracker - Co-op Trailer (480p_30fps_H264-128kbit_AAC).mp4" as {audio=2;video=1;midi=0}!

**Comment by TorchwoodPL** [comment]
Strange thing is that is was working before, and then I decided to update both systems....

**Comment by toots** [comment]
The ffmpeg decoder only works for audio files so you shouldn't use it for video files. It seems to me that you are missing some gstreamer plugins. What gstreamer plugins do you have installed?

**Comment by TorchwoodPL** [comment]
Now to check it?

**Comment by toots** [comment]
You can check if gstreamer can play your file this way:
```
gst-launch-1.0 playbin uri=file:///path/to/file.mp4
```

**Comment by TorchwoodPL** [comment]
```
root@h-y:~# gst-launch-1.0 playbin uri=/home/disk/obs/Trailers/Azure\ Reflections\ -\ Nintendo\ Switch\ Launch\ Trailer\ \(480p_30fps_H264-128kbit_AAC\).mp4
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstURIDecodeBin:uridecodebin0: Invalid URI "/home/disk/obs/Trailers/Azure Reflections - Nintendo Switch Launch Trailer (480p_30fps_H264-128kbit_AAC).mp4".
Additional debug info:
gsturidecodebin.c(1384): gen_source_element (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0
Setting pipeline to NULL ...
Freeing pipeline ...
root@h-y:~#
```

**Comment by toots** [comment]
This is the correct syntax:
```
# gst-launch-1.0 playbin uri=file:///home/disk/obs/Trailers/Azure\ Reflections\ -\ Nintendo\ Switch\ Launch\ Trailer\ \(480p_30fps_H264-128kbit_AAC\).mp4
```

**Comment by TorchwoodPL** [comment]
```
root@h-y:~# gst-launch-1.0 playbin uri=file:///home/disk/obs/Trailers/Azure\ Reflections\ -\ Nintendo\ Switch\ Launch\ Trailer\ \(480p_30fps_H264-128kbit_AAC\).mp4
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Missing element: H.264 (Main Profile) decoder
WARNING: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: No decoder available for type 'video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)3.1, profile=(string)main, codec_data=(buffer)014d401fffe1001d674d401fe8806c1ef3780b50101014000003000400000300f03c60c44801000468ebaf20, width=(int)854, height=(int)480, framerate=(fraction)30/1, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true'.
Additional debug info:
gsturidecodebin.c(921): unknown_type_cb (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
```

**Comment by toots** [comment]
Yeah so that's what I was suspecting: your gstreamer install is missing the right decoder, here H 264. 

If I'm reading the gstreamer online documentation well, you need to have open h264 installed before compiling and install `gst-plugins-bad`. There should be a package for open h264 in your distribution.

**Comment by TorchwoodPL** [comment]
Ok some progress, error has change:

```
2018/12/26 00:38:05 [output(dot)gstreamer:3] Restarting pipeline
2018/12/26 00:38:05 [output(dot)gstreamer:3] Error while processing output data: Gstreamer.Failed
2018/12/26 00:38:05 [output(dot)gstreamer:3] Restarting pipeline
2018/12/26 00:38:06 [output(dot)gstreamer:2] [audio_src] Error: Internal data stream error.
2018/12/26 00:38:06 [output(dot)gstreamer:3] Error while processing output data: Internal data stream error.
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:06 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png"!
2018/12/26 00:38:08 [decoder:3] Unable to decode "/home/disk/obs/logo_alfa.png" as {audio=0;video=1;midi=0}!

```

**Comment by TorchwoodPL** [comment]
What about output(dot)gstreamer part of log?

**Comment by TorchwoodPL** [comment]
And how to isntall plugins you provided?

**Comment by TorchwoodPL** [comment]
and?

**Comment by toots** [comment]
We should fix the source being fed into the `gstreamer` input first. I've just updated the `opam` packages to add all the video deps. Let's try with camlimages and gd first:
```
opam update
opam depext gd camlimages
opam install gd camlimages
```

These are all the deps. If one fails feel free to try without it, it might

**Comment by TorchwoodPL** [comment]
```
ubuntu@h-y:~$ opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org/1.2.2
ubuntu@h-y:~$ opam depext gd camlimages
# Detecting depexts using flags: x86_64 linux ubuntu
[ERROR] No package named gd found.
[ERROR] No package named gd found.
# No extra OS packages requirements found.
# All required OS packages found.
```

**Comment by TorchwoodPL** [comment]
Error still the same.

**Comment by TorchwoodPL** [comment]
PING

**Comment by toots** [comment]
Hey. I believe you should start by installing `opam` `2.0`. See here: http://opam.ocaml.org/doc/Install.html

**Comment by TorchwoodPL** [comment]
I reinstall everything with opam 2, the error have changed:

```
2019/02/12 23:39:15 [output(dot)gstreamer:3] Error while processing output data: Gstreamer.Failed
2019/02/12 23:39:15 [output(dot)gstreamer:2] [audio_src] Error: Internal data stream error.
2019/02/12 23:39:15 [output(dot)gstreamer:3] Error while processing output data: Internal data stream error.
2019/02/12 23:39:15 [output(dot)gstreamer:3] Restarting pipeline
```

I have also done some modification to liquidsoap.liq:

```
set("frame.video.width", 1280)
set("frame.video.height", 720)
set("frame.video.samplerate", 25)
set("gstreamer.add_borders", false)

s = playlist.safe("shuffle.m3u",reload_mode="watch")
s = fallback([s, blank()])

output.gstreamer.audio_video(
  video_pipeline=
    "videoconvert ! x264enc bitrate=2000 ! video/x-h264,profile=baseline ! queue ! mux.",
  audio_pipeline=
    "audioconvert ! voaacenc bitrate=44100 ! queue ! mux.",
  pipeline=
    "flvmux name=mux ! rtmpsink location=\"rtmp://live-waw.twitch.tv/app/[KEY] live=1\"",
s)
```

**Comment by TorchwoodPL** [comment]
I have also found, when I tried yo use different script, pure gstreamer:
https://github.com/joanrieu/gst-live

I get:

```
root@h-y:/home/obs/gst-live# cat config.sh | ./streamer.sh
0:00:00.039237698  3037      0x16ec590 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:gst_element_factory_make: no such element factory "rtmpsink"!
0:00:00.039565427  3037      0x16ec590 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "rtmpsink"
0:00:00.039818533  3037      0x16ec590 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no sink [source=@0x16e04a0]
```

Maybe this will help to find solution...

**Comment by toots** [comment]
Yeah it looks like you are missing the `rtmp` plugin. How did you install `gstreamer`?

**Comment by TorchwoodPL** [comment]
Using: https://gstreamer.freedesktop.org/documentation/installing/on-linux.html and 
[build-gstreamer.sh.txt](https://github.com/savonet/liquidsoap/files/2861675/build-gstreamer.sh.txt) script before that. Every time I remove every gstreamer package.

**Comment by TorchwoodPL** [comment]
Also I reinstall everything and now I for sure have rtmp. But error is still the same:

```
2019/02/14 11:11:33 [output(dot)gstreamer:2] [audio_src] Error: Internal data stream error.
2019/02/14 11:11:33 [output(dot)gstreamer:3] Error while processing output data: Internal data stream error.
2019/02/14 11:11:36 [output(dot)gstreamer:3] Restarting pipeline
2019/02/14 11:11:36 [output(dot)gstreamer:3] Error while processing output data: Gstreamer.Failed
```

**Comment by toots** [comment]
Ok so the gst-live script works? Any chance you could post its full pipeline? You should be able to do that by printing out the `$PIPELINE` variable in that script.

**Comment by TorchwoodPL** [comment]
No it is not working either... I gave up and took advantage of ffmpeg, it's in no mean perfect but it is working :)
