### ISSUE TITLE
reload_mode = watch

### ISSUE THREAD

**Issue by oranjebloom** [savonet/liquidsoap#677]
Hi,

I'm running liquidsoap 1.3.3 on Debian9 installed via Opam.
I'm trying to determine whether the behaviour I'm experiencing with reload_mode = watch in my script is a bug or by design (or a product of my environment).

After repeated testing, the logs show that my playlists reload when new files are uploaded to the directories on the server. However, no reload/refreshing occurs when music files are deleted or shifted between the directories. opam list shows that inotify 2.3 is installed.

A the fundamental parts of my script are below. 

#-----PLAYLIST PARTS-----#
interludes = playlist(mode="randomize", reload_mode = "watch", "/ssr/ssr2/interludes")
fresh = playlist(mode="randomize", reload_mode = "watch", "/ssr/ssr2/fresh")
general = playlist(mode="randomize", reload_mode = "watch", "/ssr/ssr2/general")

#-----TRACK ROTATION-----#
SSR2 = rotate(weights = [1,1,1,1,1],
[interludes,fresh,general,fresh,general])

radio = SSR2

#-----FALLIBILITY-----#
radio = mksafe(radio)

**Comment by toots** [comment]
Good catch on this one, thanks! The inotify code was missing some directory-specific events. It's fixed in the latest code and I'll consider a release shortly. You might be able to backport the path at b0bf3d to `1.3.3`. I don't think that the code has changed much there since that release.
