### ISSUE TITLE
Unable to decode .m4a, faad installed

### ISSUE THREAD

**Issue by rufinus2** [savonet/liquidsoap#680]
**Describe the bug**
Directory containes .mp3 and .m4a files. Mp3's playing ok, while by .m4a are skipped with following error in log:

[decoder:3] Unable to decode "/media/music/filename_here.m4a" as {audio=2;video=0;midi=0}!
 
Liquidsoap was first installed without faad, then faad was added (liquid soap automatically recompiled). All done with opam.

**Version details**
 - OS: Ubuntu 18.04
 - Liquidsoap Version: 1.3.4

**Install method**
Did you install via `opam`? --> Yes

**Comment by toots** [comment]
`faad` should indeed enable `m4a` decoding. Are you files mono? You might want to try `audio_to_stereo` to see if that fixes the problem.

**Comment by rufinus2** [comment]
No, the files are stereo. But i think they are m4a lossless, because average file size is about 30MB. Could that be an issue?

**Comment by rufinus2** [comment]
Confirmed, those files are actually encoded with ALAC. AAC m4a's are playing fine, thank you!
