### ISSUE TITLE
Release tarball contains src/operators/fade.ml

### ISSUE THREAD

**Issue by hairmare** [savonet/liquidsoap#682]
**Describe the bug**
The release tarball seems to contain a file that I cannot find in the git repo. The file surfaced  thanks to the fsf-address check from my Fedora builds.

**To Reproduce**
I'm grabbing the tarball like so
```
curl -L -O https://github.com/savonet/liquidsoap/releases/download/1.3.5/liquidsoap-1.3.5.tar.bz2
tar tvf liquidsoap-1.3.5.tar.bz2  | grep fade
```
and it contains these files matching "fade"
```
-rw-r--r-- root/root      9453 2018-12-25 22:46 liquidsoap-1.3.5/src/operators/fade.ml
-rw-r--r-- root/root     11392 2018-12-25 22:46 liquidsoap-1.3.5/src/operators/video_fade.ml
-rw-r--r-- root/root      3601 2018-12-25 22:46 liquidsoap-1.3.5/doc/content/smartcrossfade.txt
```
The fade.ml file exists in the release tarball but doesn't seem to be in the git repo [here](https://github.com/savonet/liquidsoap/tree/6335ed56917f7a41f1831fa803a960cf59d0d321/src/operators).

At first I though this looks like it could be an artifact from building the release tarball. If I remove the file (by running `rm src/operators/fade.ml` before configure) liquidsoap fails to build properly with the following error.
```
File "tools/rqueue.ml", line 1:
Error: Could not find the .cmi file for interface tools/rqueue.mli.
``` 
Considering my limited ocaml know how this doesn't really make sense. Maybe something is generating fade.ml with the "Temple Place" address.

**Expected behavior**
The release tarball should not contain files that are not in the git repo.

**Version details**
 - OS: Fedora
 - Version rawhide

**Install method**
RPM

Sorry about bugging you with these issues... I can work around them during packaging so having them fixed isn't urgent at all. Do you have an idea where fade.ml is from?

Thanks for all your hard work and for dropping 1.3.5!

**Comment by hairmare** [comment]
FWIW I just noticed that `src/operators/fade.ml` was deleted in 655771e3f282e50dbec2f36f652a0cd21786b242. I can't tell why the removal didn't make it into the release tarball. IMO the rqueue error in my issue is probably not related.

**Comment by toots** [comment]
Hi! That files was intended to be in the tarball. `1.3.5` is a bugfix releases and does not have the `fade` rewrite for that reason. I missed this when backporting the FSF address patch, tho. I suppose you will have to manually fix it if you need to, sorry about that.

**Comment by hairmare** [comment]
No problem at all, the packages still build fine they just fail linting after the fact which isn't much of an issue.
