### ISSUE TITLE
Crossfade error in Liquidsoap 1.3.4 whit Duppy 0.8.0

### ISSUE THREAD

**Issue by alerickert** [savonet/liquidsoap#683]
After updating to Liquidsoap 1.3.4 with duppy 0.8.0 (obligatorily since the previous version has faults with the autodj), now I present another problem.

1) Crossfade does not work in the same way as it did before. Cut the songs at the beginning and end (like erasing the file for a few seconds and not listening to those seconds), and does not work well with files of short duration (before this did not happen).

2) Metadata is not updated correctly. For example, SONG ONE can sound, and then follow SONGED TWO and SONG THREE, but the metadata continues to show as if SONG ONE is playing when the reality is that another different song is already playing.

3) If in the Crossfade options, I deactivate by setting a 0 "crossfade length", problem 2 is solved immediately. But I run out of Crossfade, which I need to work well.

4) Scheduled lists do not work correctly. For example, I have a list of the interval type programmed, which should sound 1 song on the list, every 1 item on the general rotation list.

and it sounds sometimes every 2 songs, then every 3 songs. Also a single file should sound from the list interval, and sometimes sound 3 together, one after the other and not just one as programmed.

**Version details**
 - OS: CENTOS 7.5

**Install method**
CENTOVACAST
[logs.zip](https://github.com/savonet/liquidsoap/files/2715926/logs.zip)
[newsource.zip](https://github.com/savonet/liquidsoap/files/2715927/newsource.zip)

**Comment by alerickert** [comment]
any ideas?

**Comment by alerickert** [comment]
help please?

**Comment by toots** [comment]
Hi. It seems that problem #4 is unrelated to crossfade. As for 1, 2 and 3, I'm gonna try to have a look at them asap. However, the description of the issue still doesn't give me enough information to reproduce it on my end. Would you have a simple scenario that I could test, possibly with sample liq code? I know that you're using a UI on top of liquidsoap so that might not be possible.

**Comment by alerickert** [comment]
Of course, I can give you access to the account so you can test for yourself what I say.
Do you have an email where we can share sensitive information?

**Comment by alerickert** [comment]
What does this version refer to? X and Z ()

- Reimplemented `fade. {In, initial, out, end}` as scripted operators. (# 664)

Is the crossfade problem solved?

**Comment by toots** [comment]
@alerickert not sure if that means it's closed, I have to test :-) Would love to have access to your system. My personal email is: toots@rastageeks.org. Thks!

**Comment by alerickert** [comment]
i send email.

**Comment by alerickert** [comment]
I send you mail but you do not answer.

**Comment by toots** [comment]
Ok, after following up with our conversation on email here are the two outcomes:

- Use `1.3.3` for now in production to be safe wrt to crossfades
- I'd like to know if the bug still occurs in the current dev code. The fade operators have been completely rewritten there.

I'm down to help installing the dev version on your server if needed.

Also, I'm still missing enough information to reproduce the case myself. What I would need is a simple example of a failure with crossfade, for instance two files which didn't crossfade properly so I can test locally.

Thanks.

**Comment by alerickert** [comment]
Now what I did was pay centovacast to install liquid 1.3.3 and see if it is compatible with duppy 0.8, then I inform the results.


________________________________

**Comment by toots** [comment]
Sounds good. When you get a chance, please try with the latest dev code as well and let me know if the issue still occurs there, that would be really helpful. Again, I'm down to help with the server side for that.

**Comment by alerickert** [comment]
If you want to install the latest code I have no problems, but to do so, you must access remotely by team viewer on my pc, for which to coordinate the moment I need you to write to my cell phone, send my number by mail, send me a message by Whatsapp.

________________________________
De: Romain Beauxis <notifications@github.com>
Enviado: miércoles, 9 de enero de 2019 19:53
Para: savonet/liquidsoap
Cc: alerickert; Mention
Asunto: Re: [savonet/liquidsoap] Crossfade error in Liquidsoap 1.3.4 whit Duppy 0.8.0 (#683)


Sounds good. When you get a chance, please try with the latest dev code as well and let me know if the issue still occurs there, that would be really helpful. Again, I'm down to help with the server side for that.
