### ISSUE TITLE
Centos 7 / LiquidSoap 1.3.3 / Centovacast

### ISSUE THREAD

**Issue by audiobras** [savonet/liquidsoap#688]
**Describe the bug**
Hello, as I see in that forum seems to have an issue in installations with Centos 7 with the default centovacast installer that install the 1.3.3 liquidsoap [683](https://github.com/savonet/liquidsoap/issues/683). But really I don't have any good tutorial to solve the issue. I try to install via OPAM and seems not have good results. I try other ways and happens errors. I will attach here the install log that I find in centovacast directories.
[centova-build.log](https://github.com/savonet/liquidsoap/files/2749937/centova-build.log)

**To Reproduce**

**Expected behavior**
Some tutorial or more detailed instructions to manual update LiquidSoap in centovacast instalatios with Centos 7

**Version details**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - Version 1.3.3

**Install method**
From Centovacast 3.2.11 Installer

**Common issues**

**Comment by toots** [comment]
Hi,

Unfortunately, we do not provide the Centovacast service so we cannot really help with this part. It looks like the install is using the `liquidsoap-full` tarball. 

You might want to look at: https://www.liquidsoap.info/doc-1.3.5/build.html Following these instructions, you should be able to build the latest dev code from https://github.com/savonet/liquidsoap-full the same way that centovacast builds from the tarball.
