### ISSUE TITLE
Install LiquidSoap 1.3.5 via source on centos 7

### ISSUE THREAD

**Issue by audiobras** [savonet/liquidsoap#689]
**Describe the bug**
Why happens that error while executing configure?

checking for ocaml dtools module >= 0.4.0... configure: error: cannot find version from META file.

**To Reproduce**
./configure --disable-camlp4 --with-cry-dir=../ocaml-cry-0.6.2/src --with-mad-dir=../ocaml-mad-0.4.5/src --with-taglib-dir=../ocaml-taglib-0.3.4/src --with-lame-dir=../ocaml-lame-0.3.3/src --with-ogg-dir=../ocaml-ogg-0.5.2/src --with-vorbis-dir=../ocaml-vorbis-0.7.1/src --with-speex-dir=../ocaml-speex-0.2.1/src --with-opus-dir=../ocaml-opus-0.1.2/src --with-fdkaac-dir=../ocaml-fdkaac-0.2.1/src --with-faad-dir=../ocaml-faad-0.4.0/src --with-ladspa-dir=../ocaml-ladspa-0.1.5/src --with-samplerate-dir=../ocaml-samplerate-0.1.4/src --with-dtools-dir=../ocaml-dtools-0.4.0/src --with-duppy-dir=../ocaml-duppy-0.7.4/src --with-mm-dir=../ocaml-mm-0.4.0/src --prefix=/usr/local/centovacast/liquidsoap --disable-graphics

**Expected behavior**
Install LiquidSoap 1.3.5

**Version details**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - Version 1.3.5

**Install method**
from source, following the centovacast install steps

**Common issues**

**Comment by audiobras** [comment]
[root@s1 liquidsoap-1.3.5-full]# ls
bootstrap         ocaml-alsa-0.2.3    ocaml-duppy-0.7.4   ocaml-gavl-0.1.6       ocaml-mad-0.4.5         ocaml-samplerate-0.1.4  ocaml-vorbis-0.7.1
configure         ocaml-ao-0.2.1      ocaml-faad-0.4.0    ocaml-gstreamer-0.3.0  ocaml-mm-0.4.0          ocaml-shine-0.2.1       ocaml-xmlplaylist-0.1.4
INSTALL           ocaml-bjack-0.1.5   ocaml-fdkaac-0.2.1  ocaml-ladspa-0.1.5     ocaml-ogg-0.5.2         ocaml-soundtouch-0.1.8  PACKAGES
LICENSE           ocaml-cry-0.6.2     ocaml-ffmpeg-0.2.0  ocaml-lame-0.3.3       ocaml-opus-0.1.2        ocaml-speex-0.2.1       PACKAGES.default
liquidsoap-1.3.5  ocaml-dssi-0.1.2    ocaml-flac-0.1.3    ocaml-lastfm-0.3.2     ocaml-portaudio-0.2.1   ocaml-taglib-0.3.4      PACKAGES.minimal
Makefile          ocaml-dtools-0.4.0  ocaml-frei0r-0.1.1  ocaml-lo-0.1.1         ocaml-pulseaudio-0.1.3  ocaml-theora-0.3.1      README

**Comment by audiobras** [comment]
reopen

**Comment by audiobras** [comment]
Could you only explain why do you close that without any explantion? The related error is too simple to you or do you believe that this type of installation is not your problem?

**Comment by toots** [comment]
Ho sorry I confused this issue with another one.

I need more context to help you. Can you show more install steps you did? Thks!

**Comment by audiobras** [comment]
The objective was follow the steps that I see in Centova Log, but inside the liquidsoap-1.3.5-full directory with the versions. I am not shure why, but seems that centovacast use the configure several times and repeating comands. I try tu use because it seems that the are the steps used by centovacast, and even you do not support it, I believe the steps can be used by a manual instalation too.

[centova-build.log](https://github.com/savonet/liquidsoap/files/2751348/centova-build.log)

**Comment by toots** [comment]
You need to follow the full steps:

```
cd /usr/local/src/liquidsoap
wget https://github.com/savonet/liquidsoap/releases/download/1.3.5/liquidsoap-1.3.5-full.tar.gz
 tar -xjvf liquidsoap-1.3.5-full.tar.bz2
cd liquidsoap-1.3.5-full
cp PACKAGES.minimal PACKAGES
<edit PACKAGES file, comment out what you want/do no want>
./configure
make
```
Then, finally, as root:
```
make install
```
Will install the binary. Careful as it will overwrite any existing one.

Optionally, you might be able to copy the `PACKAGES` file from another build to use the same configuration.

**Comment by audiobras** [comment]
[root@s1 liquidsoap1]# tar -xjvf liquidsoap-1.3.5-full.tar.bz2
tar (child): liquidsoap-1.3.5-full.tar.bz2: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by audiobras** [comment]
cd /usr/local/src/liquidsoap
mkdir liquidsoap1
cd liquidsoap1
wget https://github.com/savonet/liquidsoap/releases/download/1.3.5/liquidsoap-1.3.5-full.tar.gz
tar -xvf liquidsoap-1.3.5-full.tar.gz
cd liquidsoap-1.3.5-full
cp PACKAGES.default PACKAGES
./configure

It stops here:

****** Configuring ocaml-ao-0.2.1

./configure --with-cry-dir=../ocaml-cry-0.6.2/src --with-ao-dir=../ocaml-ao-0.2.1/src
configure: WARNING: unrecognized options: --with-cry-dir, --with-ao-dir
configuring ocaml-ao 0.2.1
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking that calling user is not root... configure: error: configure script must not be run with root user!

**Comment by smimram** [comment]
As indicated, the `configure` should not be run as root...

**Comment by mrdevis** [comment]
@audiobras I ran into this problem as well, configuring stopping, and noticed that there is in the standard configure one period to much in the `--with-cry-dir=../ocaml-cry-0.6.2/src`. So if you configure like this:

`./configure --with-cry-dir=./ocaml-cry-0.6.2/src --with-ao-dir=./ocaml-ao-0.2.1/src`
it will configure fine

note that `..` is looking one directory up, and `.` is looking in the current directory.
In the end you probably will get a notification about fonts, but that is easily solved as well. On ubuntu 18.04 LTS, the configure line is like this:
`./configure --with-cry-dir=./ocaml-cry-0.6.2 --with-ao-dir=./ocaml-ao-0.2.1 --with-default-font=/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf`
good luck!

@toots: I could not figure out where the extra period was buried, maybe this could be easily fixed?

**Comment by toots** [comment]
I think the problem here is that the user is trying to install as `root`. I would recommend installing under a different user or switching to `opam`. Feel free to follow-up on the mailing list and good luck!
