### ISSUE TITLE
runtime liblo error 

### ISSUE THREAD

**Issue by mrdevis** [savonet/liquidsoap#692]
Would be extremely grateful for some reaction, comment, maybe even help etc on this.

Expected behavior: working LS script after porting from debian (ls1.3.3) to ubuntu 18.04 (ls1.3.5)

having freshly installed gstreamer like this::
```
sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base
gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc
gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl
```
and liquidsoap like this::
```
opam depext pcre dtools duppy cry mm xmlplaylist ogg vorbis lame
gstreamer frei0r fdkaac gavl ffmpeg bjack alsa ao samplerate taglib
magic camomile yojson faad soundtouch ladspa dssi lo camlimages gd
conf-sdl2-mixer conf-sdl2-net conf-sdl2-tt liquidsoap
```
(pulls in gstreamer-devs)
```
opam install  pcre dtools duppy cry mm xmlplaylist ogg vorbis lame
gstreamer frei0r fdkaac gavl ffmpeg bjack alsa ao samplerate taglib
magic camomile yojson faad soundtouch ladspa dssi lo camlimages gd
conf-sdl2 conf-sdl2-image conf-sdl2-mixer conf-sdl2-net conf-sdl2-ttf
liquidsoap
```
when starting a relatively simple script like this::
```
set("log.file.path","/home/jeroen/liquidsoap/log/liqsoap.log")
set("log.level",5)
set("log.stdout",false)

set("frame.audio.samplerate",48000)
set("frame.video.width", 640)
set("frame.video.height", 360)
set("frame.video.samplerate", 25)
set("osc.port",8000)
set("gstreamer.add_borders", false)

# function for OSC parsing
def on_command(m) =
  if ( fst(m) == "command" ) then
      if ( snd(m) == "reset" ) then
        log("Reset received - resetting LiquidSoap ")
        execShell = run_process('/bin/echo "" > /VIDEOS/play_now.pls')
        garbage_collect()

      elsif( snd(m) == "one" ) then
        log("One received - playing video one")
        osc.send_string(host="hh.cs", port=57120, "/played", "1")
        execShell = run_process('/bin/cat /VIDEOS/play_one.pls >
/VIDEOS/play_now.pls')
        garbage_collect()
    end
end

# make source
# liveOut = playlist.safe("/VIDEOS/Mercato.mp4")

liveOut = playlist.once(reload_mode="watch", "/VIDEOS/play_now.pls")
liveOut = fallback(track_sensitive=false, [liveOut,
single("/VIDEOS/Intermissions_long_AV.mp4")] )

# Call the above handler when we have a pair of strings on /metadata
osc.on_string_pair("/metadata",on_command)    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< if commented out then no liblo error
(but also still no output from gstreamer)

# Output to Gstreamer
log("Starting Stream...")
output.gstreamer.audio_video(
        video_pipeline=
          "videoconvert ! x264enc bitrate=1000 speed-preset=ultrafast !
video/x-h264,profile=baseline ! queue ! mux.",
        audio_pipeline=
          "audioconvert ! fdkaacenc bitrate=68000 ! queue ! mux.",
        pipeline=
          "flvmux streamable=1 name=mux ! rtmpsink
location=\"rtmp://hh.cs:1935/live/livestream live=1\" ",
          liveOut)
```

I get after a fresh reboot (so ports should not be occupied) :
```
liblo server error 9904 in path (null): cannot find free port
Line 72, char 1: Unknown error!
Fatal error: exception LO.Error
Raised by primitive operation at file "LO.ml", line 76, characters 19-45
Called from file "lang/builtins_lo.ml", line 70, characters 12-33
Called from file "lang/builtins_lo.ml", line 106, characters 6-21
Called from file "lang/lang_values.ml", line 971, characters 14-20
Called from file "lang/lang_values.ml", line 1053, characters 16-44
Called from file "lang/lang_values.ml", line 1049, characters 19-34
Called from file "lang/lang.ml", line 650, characters 14-38
Called from file "tools/tutils.ml", line 85, characters 14-18
Re-raised at file "tools/tutils.ml", line 85, characters 48-55
Called from file "lang/lang.ml", line 676, characters 8-12
Re-raised at file "lang/lang.ml", line 785, characters 43-50
```
doesn't look like any port is occupied::
```
sudo netstat -anltp | grep 8000
## returns nothing
```

Thanks for any help

ubuntu 18.04LTS

gstreamer 1.14.1

alsa                0.2.3      
ao                  0.2.1      
base                v0.11.1    
base-bigarray       base
base-bytes          base       
base-threads        base
base-unix           base
biniou              1.2.0      
bjack               0.1.5      
camlimages          5.0.1      
camomile            1.0.1      
conf-gd             1          
conf-libpcre        1          
conf-m4             1          
conf-pkg-config     1.1        
conf-sdl2-mixer     1          
conf-sdl2-net       1          
conf-sdl2-ttf       1          
conf-which          1          
configurator        v0.11.0    
cppo                1.6.5      
cry                 0.6.2      
dssi                0.1.2      
dtools              0.4.1      
dune                1.6.3      
duppy               0.8.0      
easy-format         1.3.1      
faad                0.4.0      
fdkaac              0.2.1      
ffmpeg              0.2.1      
frei0r              0.1.1      
gavl                0.1.6      
gd                  1.0a5      
graphics            1.0        
gstreamer           0.3.0      
jbuilder            transition 
ladspa              0.1.5      
lame                0.3.3      
liquidsoap          1.3.5      
lo                  0.1.1      
mad                 0.4.5      
magic               0.7.3      
mm                  0.4.0      
ocaml               4.07.1     
ocaml-base-compiler 4.07.1     
ocaml-config        1          
ocamlbuild          0.12.0     
ocamlfind           1.8.0      
ocamlsdl            0.9.1      
ogg                 0.5.2      
opam-depext         1.1.2      
pcre                7.3.5      
result              1.3        
samplerate          0.1.4      
sexplib0            v0.11.0    
soundtouch          0.1.8      
stdio               v0.11.0    
taglib              0.3.3      
topkg               1.0.0      
vorbis              0.7.1      
xmlm                1.3.0      
xmlplaylist         0.1.4      
yojson              1.5.0

**Comment by mrdevis** [comment]
Ok installation of libgstreamer-plugins-bad1.0-dev fixed the liblo error

Then I ran into a couple of GStreamer-CRITICAL **: 12:01:46.641 errors:

> dispose element fakesink0 pipeline0 audioresample0 audioconvert0 filesrc0 fakesink1 pipeline1 audioresample1 audioconvert1 filesrc1 errors complaining about not being "to the NULL state"

fixed that by adding (as per @toots suggestion in #663):

set("decoder.file_extensions.ffmpeg",["mp3","mp4","m4a","wav","flac","ogg","wma"])

to the script. 
But now I am back to square one, the log complaining about:
```
[single_7269:3] "/VIDEOS/Intermissions_long_AV.mp4" is static, resolving once for all...
2019/01/17 13:22:58 [clock.wallclock_gstreamer:2] Error when starting output(dot)gstreamer: Req_simple.Invalid_URI!
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Raised at file "sources/req_simple.ml", line 37, characters 6-23
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Called from file "source.ml", line 388, characters 6-18
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Called from file "operators/switch.ml", line 105, characters 9-20
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Called from file "list.ml", line 106, characters 12-15
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Called from file "source.ml", line 388, characters 6-18
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Called from file "outputs/output.ml", line 130, characters 4-20
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Called from file "source.ml", line 388, characters 6-18
2019/01/17 13:22:58 [clock.wallclock_gstreamer:3] Called from file "clock.ml", line 221, characters 15-26
2019/01/17 13:22:58 [output(dot)gstreamer:1] Got ill-balanced activations (from output(dot)gstreamer)!


```

**Comment by mrdevis** [comment]
oops, the script was handled a bit messy, sorry about that!

**Comment by mrdevis** [comment]
Anybody??

**Comment by toots** [comment]
Hi. It looks like your output url is invalid. Perhaps it should be: `location=\"rtmp://hh.cs:1935/live/livestream?live=1\"`

**Comment by mrdevis** [comment]
Just a reinstall
 `opem reinstall liquidsoap` 
without touching anything else brought back the 
`GStreamer-CRITICAL **: 22:01:29.871: error`
with the same series as mentioned before.

**Comment by mrdevis** [comment]
@toots: thanks for chiming in! Did that syntax change between 1.3.3 and 1.3.5? (I copied the script from a working machine...).

I first have to get rid of the GStreamer error I mentioned before, then I'll give that a go immediately!

**Comment by mrdevis** [comment]
A complete reinstall by opam got rid of half the GStreamer ERROR's. Only having mentions of fakesink0 pipeline0 audioresample0 audioconvert0 filesrc0, not their nr1 suffixed counterparts.

**Comment by mrdevis** [comment]
Ok, I forgot I had an instance already running, doh.

but the change in the script  still gives this error::
```
2019/01/17 22:24:28 [single_7269:3] "/VIDEOS/Intermissions_long_AV.mp4" is static, resolving once for all...
2019/01/17 22:24:28 [clock.wallclock_gstreamer:2] Error when starting output(dot)gstreamer: Req_simple.Invalid_URI!
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Raised at file "sources/req_simple.ml", line 37, characters 6-23
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Called from file "source.ml", line 388, characters 6-18
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Called from file "operators/switch.ml", line 105, characters 9-20
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Called from file "list.ml", line 106, characters 12-15
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Called from file "source.ml", line 388, characters 6-18
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Called from file "outputs/output.ml", line 130, characters 4-20
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Called from file "source.ml", line 388, characters 6-18
2019/01/17 22:24:28 [clock.wallclock_gstreamer:3] Called from file "clock.ml", line 221, characters 15-26
2019/01/17 22:24:28 [output(dot)gstreamer:1] Got ill-balanced activations (from output(dot)gstreamer)!
2019/01/17 22:24:28 [clock:2] Error when leaving output output(dot)gstreamer: File "source.ml", line 414, characters 10-16: Assertion failed!
2019/01/17 22:24:28 [clock:3] Raised at file "source.ml", line 414, characters 10-22
2019/01/17 22:24:28 [clock:3] Called from file "source.ml", line 421, characters 30-58
2019/01/17 22:24:28 [clock:3] Called from file "clock.ml", line 79, characters 6-13
2019/01/17 22:24:28 [clock:4] Main phase starts.
```

**Comment by mrdevis** [comment]
Now without changing anything (well, only the fdkaacenc to voaacenc in the script) but a reboot I get the Gstreamer Errors back again. version0 and version1. 
Changing the encoder back does solve it

**Comment by mrdevis** [comment]
one step further, finding that quicktime was missing , so after installing gstreamer-plugins::
`sudo apt install gstreamer1.0-rtsp gstreamer1.0-plugins-bad-videoparsers gstreamer1.0-opencv gstreamer1.0-libav gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-qt5`
things are looking better
the` Req_simple.Invalid_URI!` error disappeared, the script keeps running. but still no ts files written in the `www/live` directory, nor the m3u8 is being updated. As LS seems to do it-s job now it seems that somethings missing downstream.

**Comment by mrdevis** [comment]
This is getting away from the original issue so closing this

**Comment by Infernion** [comment]
I recently discovered this bug both with OPAM and repo installation. The solution with installing missing packages works only for OPAM. When I install all this packages with `liquidsoap` I'm getting segmentation fault:

```
$ liquidsoap serve.liq

ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```

This is the command: `sudo apt install liquidsoap-1.4.0 gstreamer1.0-rtsp gstreamer1.0-plugins-bad-videoparsers gstreamer1.0-opencv gstreamer1.0-libav gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad gstreamer1.0-qt5`

As far as I see the issue with `gstreamer1.0-libav. Maybe there some conflict with repo build. @toots could you look at it here?

**Comment by toots** [comment]
Hmm. The `.deb` repo is using its own build of `libav`/`ffmpeg`, which could potentially carry that sort of issues.

Couple of things you can do:
1. Remove all of our own debian sources, install gstreamer via the packages and liquidsoap via opam
2. Rebuild `gstreamer` against our own `ffmpeg`/`libav` packages.

I might have a look at #2 but I cannot guarantee a timeline. My recommendation would be to try #1.

**Comment by toots** [comment]
Ok, that was actually easier than I thought. Just updated the debian repositories with a rebuild of `gstreamer-libav`. Would you mind trying it?

**Comment by Infernion** [comment]
@toots I've checked. Seems it doesn't crash now. Thank you!

**Comment by Infernion** [comment]
@toots I've re-checked. Actually it's still failing. So I'll take one of option that you've proposed. Thanks :)
