### ISSUE TITLE
output.gstreamer.audio_video not working

### ISSUE THREAD

**Issue by mrdevis** [savonet/liquidsoap#693]
opam install 1.3.5 ubuntu 18.04

installed srs (2.0release) streaming server works, tested with external obs
installed gstreamer, works with test script:
```
gst-launch-1.0 \
  filesrc location="/VIDEOS/Intermissions_long_AV.mp4" ! decodebin name=t \
  t. ! videoconvert ! x264enc bitrate=1000 speed-preset=ultrafast tune=zerolatency ! "video/x-h264,profile=baseline" ! queue ! flvmux name=mux \
  t. ! audioconvert ! voaacenc bitrate=128000 ! queue ! mux. \
  mux. ! rtmpsink location="rtmp://hh.cs:1935/live/livestream live=1"
```
last place to look is the connection with liquidsoap, connecting part::
```
output.gstreamer.audio_video(
        video_pipeline= 
          "videoconvert ! x264enc bitrate=1000 speed-preset=ultrafast ! video/x-h264,profile=baseline ! queue ! mux.",
        audio_pipeline=
          "audioconvert ! fdkaacenc bitrate=68000 ! queue ! mux.",
        pipeline=
          "flvmux streamable=1 name=mux ! rtmpsink location=\"rtmp://hh.cs:1935/live/livestream live=1\" ",
          liveOut)
```
This does not work, according to the log all is ok:
https://pastebin.com/ut9pEdh1

Maybe @toots could shine a light? That would be awesome. Thanks!

**Comment by toots** [comment]
The log does show an error:
```
2019/01/18 13:19:24 [output(dot)gstreamer:3] Error while processing output data: Internal data stream error.
2019/01/18 13:19:24 [output(dot)gstreamer:4] Stacktrace: Raised at file "io/gstreamer_io.ml", line 269, characters 53-79
Called from file "tools/gstreamer_utils.ml", line 145, characters 20-46
Called from file "io/gstreamer_io.ml", line 269, characters 8-87
```

And later:
```
2019/01/18 13:19:27 [output(dot)gstreamer:3] Error while processing output data: Gstreamer.Failed
2019/01/18 13:19:27 [output(dot)gstreamer:4] Stacktrace: Raised by primitive operation at file "gstreamer.ml", line 389, characters 4-65
Called from file "io/gstreamer_io.ml", line 258, characters 12-129
```

I'm not certain what causes that. Could you share the script and files with me at toots@rastageeks.org? Thks!

**Comment by mrdevis** [comment]
I could not figure out if this was corrected later in the log

**Comment by mrdevis** [comment]
@toots did you get the files I sent to you by email?

**Comment by toots** [comment]
Hey. No, I didn't. What email is it coming from?

**Comment by mrdevis** [comment]
sent it from `mrdevis@121234.net` to `toots@rastageeks.org` subject `files #693`
please check, I would need this for an exhibition opening next week

**Comment by toots** [comment]
Hi. Yeah, I've got a lot of stuff to deal with outside of liq work these days. I never received your files on that email. I tried sending you an email from another account. Title was: "Liquidsoap files"

**Comment by mrdevis** [comment]
Hi, yes, I got that and immediately send it to your other address two days ago::

Romain Beauxis <romain.beauxis@gmail.com>
with subject `files bug #693`

in there a link with the files. Check your spambox!!

**Comment by toots** [comment]
Locally testing showed that it worked except for the `rtmpsink` which is most likely a configuration issue. I'll close this one, please re-open if I missed anything.

**Comment by toots** [comment]
Final word on this bug:
> I eventually managed to get 1.3.5 working with gstreamer 1.12.1. It seems so that 1.3.5 is working in respect to this bug. Eventually I made it work by compiling a fresh gstreamer libav. And register the gstreamer lib in /etc/ld.conf.d/gstlib.conf. Didn't try with gstreamer 1.14 though, but I guess that would work as well.

Closing for good now!

**Comment by savonet-users** [comment]
hiyaaa!
i got one more nail to the new-gen's coffin:

strip_blank doesn't work anymore. it used to work some years ago for sure.
i noticed long silent sausages being recorded after parties are over, but 
didn't pay a lot of attention - wasted disk space is not as tangible as 
wasted ram ;)

this does nothing: sausagesource = strip_blank(max_blank=90., 
threshold=-32., sausagesource)
i calculated RMS in wavelab - it's below -32dB yet still gets recorded.

is it that synthax has changed or ways to do it have changed?.. or yet 
another new bug?
sausagesource is an input.harbor and strip_blank is the second line for it.. 
to get rid of emtpy broadcasts.

that's it folks for this time ;)

regards,
p
