### ISSUE TITLE
How to use offical Liquidsoap Dockerfile

### ISSUE THREAD

**Issue by jovadeza** [savonet/liquidsoap#694]
Hi all,

Is there any info on the offical Liquidsoap Dockerfile  ([https://github.com/savonet/liquidsoap-full](https://github.com/savonet/liquidsoap-full))?

To build an container from the Dockerfile you have to pass some variables (I suppose), like the .liq file location for example.

I am not able to find any information or examples on this.

Thanks in advance!

**Comment by toots** [comment]
Hi,

The `savonet/liquidsoap-full` image is mostly intended to use in our CI pipeline. It's basically a build of liquidsoap on debian testing with all features enabled.

The image is a snapshot of the state just after calling `make install`. It has a fully-featured working liquidsoap binary at `/usr/local/bin/liquisoap`.

One way to use it is to write your own `Dockerfile`:
```
FROM savonet/liquidsoap-full

ADD my-script.liq /tmp/my-script.liq
```

Then you can execute your script from within that image for instance.

**Comment by rrolla** [comment]
typo binary located in `/usr/local/bin/liquidsoap` not `/usr/local/bin/liquisoap`

**Comment by toots** [comment]
Fixed in comment, thanks!

**Comment by rrolla** [comment]
@toots There is also a typo 
![Screenshot from 2019-05-25 13-54-31](https://user-images.githubusercontent.com/3932546/58368366-c2648b80-7ef4-11e9-9185-0eed8bca64d0.png)

There is no such a branch/tag 1.4.0-beta2

**Comment by toots** [comment]
Fixed, thanks!
