### ISSUE TITLE
Old urls in flows.liq

### ISSUE THREAD

**Issue by Groschi** [savonet/liquidsoap#696]
Hi.
It seems the urls in flows.liq are outdated. I got flows working for my stream by changing them like this:

```
  # If the server is "", we get the server from sf.net
  server =
    if server == "" then
      server = http.get("http://liquidsoap.info/flows_server")
      html_status = snd(fst(fst(fst(server))))
      if html_status == 200 then
        snd(server)
      else
        # If sf is down, we use the hardcoded server
        "http://savonet-flows.herokuapp.com/"
      end
    else
      server
    end
```
Not sure if that's the correct way to do it. Just works for me.

**Comment by savonet-users** [comment]
heya!

i've been a bleeding-edge adopter of all new x64 windows builds and all of 
them had been leaking memory in huge amounts and sometimes locking up at 
maximum cpu usage. in the run, you've been able to fix dead telnet and it 
kind of approached old versions in usability, also having some other bugs 
fixed (randomly locking up harbor on incoming flac streams and a few other 
glitches), but all in all current windows situation is terrible and seems 
this is the end as even debugger is not working. that can be not a problem 
of liquidsoap code, but perhaps shitty new compilers or buggy build systems 
(i've heard you're using new way to build it and it's been shit :(

anyway my radio has been on the edge of being sued for piracy so i changed 
the music to one no one cares about and that combined with unstable 
underlying infrastructure almost no one listens to it lately, but it still 
bugs my server with memory bloat.

is anyone else using windows build? does anyone care to use old build 
methods for a new version? me on my own - i don't think i'd build it from 
scratch on windows. still, something has to be done.. so i'm thinking how to 
contribute if i can. i've already posted whole config, parts of config, so 
there is a way to reproduce what's happening, but perhaps just making a 
build in the old way can fix everything?..

regardssssss,
p

**Comment by savonet-users** [comment]
hi again,

i have a recipe for an easy leak!

start the process, let it run for while playing some playlist.. for an hour 
or so...
then connect via telnet to your liquidsoap and watch the process tickling up 
your RAM!


cheers!
p

**Comment by savonet-users** [comment]
Hi,


Le mar. 22 janv. 2019 à 07:13, p g <pranza@gmail.com> a écrit :
> i have a recipe for an easy leak!
>
> start the process, let it run for while playing some playlist.. for an
hour
> or so...
> then connect via telnet to your liquidsoap and watch the process tickling
up
> your RAM!

Unfortunately, this still isn't enough for me to start working on this. I
also need the script that you are using. Moreover, it would help if that
could be a minimal script. For instance, do you see the issue with this
script:

set("server.telnet",true)

output.dummy(blank())

**Comment by toots** [comment]
Hi,

Thanks for the report. This needs to be updated indeed. More generally, we need to decide what to do with Flows. I'll start a discussion soon.

**Comment by smimram** [comment]
We need to settle the flows future for 1.4.0.

**Comment by toots** [comment]
Yes. I'm afraid we might have to shut it down unless someone from the community wants to take it over.

**Comment by smimram** [comment]
What do you need exactly? Just a server running some docker image?

**Comment by toots** [comment]
Someone to rewrite it! It's using a very outdated stack..

**Comment by smimram** [comment]
If you're ok starting again from the old OCaml code I could help!

**Comment by toots** [comment]
The OCaml code for web? Did we ever have that?
