### ISSUE TITLE
Annotate issue with UTF-8/non-ASCII characters

### ISSUE THREAD

**Issue by RecursiveGreen** [savonet/liquidsoap#697]
**Describe the bug**
Using a Python 3 script to make calls to an API and return an "annotate" string for Liquidsoap to process. If the string contains any non-ASCII characters, it will silently fail and choose the default (""). If all characters are "normal", the line is accepted with no issues.

Here's an example of the log output:

> [lang:3] "annotate:req_id=\"5\",type=\"S\",artist=\"Masato Koda, Satoshi Ise, Tetsuya Shibata\",title=\"Please Kill Me\",game=\"Devil May Cry 2\":/xxxxxxxxxx/Devil May Cry 2/Disc 2/12 Masato Koda, Tetsuya Shibata & Satoshi Ise - Please Kill Me.flac"
[decoder:3] Method "FFMPEG" accepted "/xxxxxxxxxx/Devil May Cry 2/Disc 2/12 Masato Koda, Tetsuya Shibata & Satoshi Ise - Please Kill Me.flac".
[main:3] Prepared "/xxxxxxxxxx/Devil May Cry 2/Disc 2/12 Masato Koda, Tetsuya Shibata & Satoshi Ise - Please Kill Me.flac" (RID 1).
[fallback_7369:3] Switch to main with transition.
[smart_cross_7377:3] Analysis: -27.445053dB / -infdB (5.00s / 5.00s)
[mycross:3] Transition: crossed, fade-in, fade-out.
[lang:3] "annotate:req_id=\"6\",type=\"S\",artist=\"Keiki Kobayashi\",title=\"The Journey Home\",game=\"Ace Combat 5: The Unsung War\":/xxxxxxxxxx/Ace Combat 5 - The Unsung War/Disc 3/14 Keiki Kobayashi - The Journey Home.flac"
[decoder:3] Method "FFMPEG" accepted "/xxxxxxxxxx/Ace Combat 5 - The Unsung War/Disc 3/14 Keiki Kobayashi - The Journey Home.flac".                                                                                                          
[main:3] Finished with "/xxxxxxxxxx/Devil May Cry 2/Disc 2/12 Masato Koda, Tetsuya Shibata & Satoshi Ise - Please Kill Me.flac".                                                                                                             
[main:3] Prepared "/xxxxxxxxxx/Ace Combat 5 - The Unsung War/Disc 3/14 Keiki Kobayashi - The Journey Home.flac" (RID 2).                                                                                                                     
[smart_cross_7377:3] Analysis: -18.808448dB / -34.477153dB (4.96s / 4.96s)
[mycross:3] Transition: crossed, fade-in, fade-out.
[lang:3] ""
[lang:3] ""
[lang:3] ""
[lang:3] ""
[lang:3] ""
[lang:3] ""
[lang:3] ""
[lang:3] ""
[lang:3] ""
[lang:3] ""

**To Reproduce**
Put something like this as your annotate line:

> annotate:req_id="7",type="S",artist="Olivier Derivière",title="Our Parents",game="Remember Me":/xxxxxxxxxx/Remember Me Original Soundtrack/10 Olivier Derivière - Our Parents.flac

Note the "è" character.

**Expected behavior**
When I used a much older version of Liquidsoap (I believe it was version 1.1.1), I had no issues reading non-ASCII characters from the annotate line.

**Version details**
 - OS: Ubuntu 18.04.1 LTS
 - Version: 1.3.4

**Install method**
opam 4.05

**Comment by RecursiveGreen** [comment]
I should clarify that I installed using OPAM, and the OCaml compiler version is 4.05.0.

Just to get it out of the way, I tried with OCaml 4.07.0 and I get the same results.

**Comment by toots** [comment]
Hi! Thanks for the report. How are these urls fed into liquidsoap?

**Comment by RecursiveGreen** [comment]
Hey!

I have a Python 3 script that pulls the API data from the site and it forms an annotate string like the ones mentioned above. I have verified that it works fine from the console so Python seems to be okay.

From Liquidsoap, I followed one of the code examples which has worked wonders for years. Here's the line of code in question:

`def spreq () =`
`     ret = list.hd(default="",get_process_lines("python3 /spradio/djcontrol.py next"))`
`     log(""^quote(ret))`
`     request.create(ret)`
`end`

The log call there is what I used to troubleshoot the issue. That's why the annotate lines are shown in the example above. I suspect the "get_process_lines" doesn't like the different characters and uses the default blank string instead--thus the flood of "".

**Comment by RecursiveGreen** [comment]
Argh! I hate it when that happens! ; )

I'm going through OPAM hell right now and somehow messed up my install when I tried to upgrade to OCaml 4.07.0. I'm in the process of re-installing Liquidsoap to see if I can do what you did to reproduce the issue and see if it's a strange Linux/Locale setting issue.

If you don't mind me asking, what OS environment did you try on?  Also, is there any other specific details that would help you along with this?

**Comment by RecursiveGreen** [comment]
So I copied/pasted the output from the Python script into a text file and changed it as in your example.

test.txt:

> annotate:req_id="7",type="S",artist="Olivier Derivière",title="Our Parents",game="Remember Me":/xxxxxxxxxx/Remember Me Original Soundtrack/10 Olivier Derivière - Our Parents.flac

radio.liq:

> ret = list.hd(default="",get_process_lines("cat /home/liquidsoap/test.txt"))

Lo and behold, it took this time! I'm not entirely certain why the output from "cat" is different from the output from Python. I can see from the logs that the characters are decoded to their unicode numbers respectively.

> [lang:3] "annotate:req_id=\"7\",type=\"S\",artist=\"Olivier Derivière\",title=\"Our Parents\",game=\"Remember Me\":/xxxxxxxxxx/Remember Me Original Soundtrack/10 Olivier Derivière - Our Parents.flac"
[decoder:3] Method "FFMPEG" accepted "/xxxxxxxxxx/Remember Me Original Soundtrack/10 Olivier Derivi\195\168re - Our Parents.flac".
[main:3] Finished with "/xxxxxxxxxx/Remember Me Original Soundtrack/10 Olivier Derivi\195\168re - Our Parents.flac".
[main:3] Prepared "/xxxxxxxxxx/Remember Me Original Soundtrack/10 Olivier Derivi\195\168re - Our Parents.flac" (RID 2).

I'm going to change my Python code to output the decoded, non-latinized (I think that's how you say it?) letters instead and see if it takes. I'll let you know what I find.

**Comment by toots** [comment]
Ok, sorry about that. One thing you can try is using the `tee` command line to say the output from your python script:
```
def spreq () =
ret = list.hd(default="",get_process_lines("python3 /spradio/djcontrol.py next | tee /tmp/python-scrip.log"))
log(""^quote(ret))
request.create(ret)
end
```
Then we can see what comes out of that pipe and test it with `cat` also.

**Comment by RecursiveGreen** [comment]
After taking the majority of Friday evening to get things back into order, I was finally able to get things working by changing my command line to the following:

> PYTHONIOENCODING=utf-8 python3 /spradio/djcontrol.py next

https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING

Strangely, it looks fine when ran from the Linux command line, but without forcing the issue with that environment variable, it must have been defaulting to plain ASCII encoding when running from within Liquidsoap.

That said, I apologize for all the confusion. Just when I think I have a handle on Unicode issues, something always springs up to prove me wrong. I appreciate the help, @toots!!

**Comment by toots** [comment]
No problem. Glad it's fixed. My understanding is that python was trying to convert the utf8 string into ascii and failing, thus returning an empty string. To further investigate, the script should inherit its environment variables from lquidsoap so I'd check what locale (`LANG` variable) and other environment variables it was running under.

I think we can close the bug here..
