### ISSUE TITLE
Intro possible?

### ISSUE THREAD

**Issue by webtent** [savonet/liquidsoap#704]
I really like Liquidsoap, have tried with playlists as well as our live on-air using alsa.input. I've tried to add an intro using Icecast to our stream but an issue with mobile devices having their stream repeat to the point they first started listening when they are interrupted on the phone. When a text or call comes in, the intro replays as I would expect from the reconnect, but the stream repeats from the start instead of going back to live stream or at least the point the interruption occurred.

I'm assuming Liquidsoap, being a source like Darkice, it really isn't possible to serve an intro to Icecast on each connection. But if there is a solution to this issue, either from experienced Icecast users or that LS can handle, I'd love to hear about it...

Liquidsoap 1.3.3
Icecast 2.4.4

**Comment by webtent** [comment]
Yes, it is a live stream. When I say the stream repeats from the start, I mean the start of when you start listening. Yes, like it is being buffered and starts again where that buffer started when you reconnect after an interruption like a text or call on the phone. I wouldn't say it happens 100% of the time, but I can definitely duplicate the issue without trying many times. It seems the longer I wait before sending the interruption, the less it repeats, perhaps the buffer reaches its limit forcing it to go to the live stream. I'm just guessing here. I have enabled the intro on one of our streams if you wanna try. You can use our WMNF Player app in the iOS app store or Android play store to play our HD4 channel. I just did it now and it happens like this: 1) start the stream 2) after the next song starts or some point you can remember, call the phone and hang up forcing it to disconnect and connect again 3) the song playing when you first connected to the stream is playing again after the intro plays again.

I can write a perl or php script to keep track of users to redirect, just not sure how I would get this between the listener and icecast? It was suggested on another forum to just do away with the intro and handle at our app or website player, but we would like the intro no matter the location you connect from, like TuneIn or NPR.org.

**Comment by savonet-users** [comment]
Hi,


Le lun. 4 févr. 2019 à 06:44, webtent <notifications@github.com> a écrit :
>
> Yes, it is a live stream. When I say the stream repeats from the start, I
mean the start of when you start listening. Yes, like it is being buffered
and starts again where that buffer started when you reconnect after an
interruption like a text or call on the phone. I wouldn't say it happens
100% of the time, but I can definitely duplicate the issue without trying
many times. It seems the longer I wait before sending the interruption, the
less it repeats, perhaps the buffer reaches its limit forcing it to go to
the live stream. I'm just guessing here. I have enabled the intro on one of
our streams if you wanna try. You can use our WMNF Player app in the iOS
app store or Android play store to play our HD4 channel. I just did it now
and it happens like this: 1) start the stream 2) after the next song starts
or some point you can remember, call the phone and hang up forcing it to
disconnect and connect again 3) the song playing when you first connected
to the stream is playing again after the intro plays again.
>
> I can write a perl or php script to keep track of users to redirect, just
not sure how I would get this between the listener and icecast? It was
suggested on another forum to just do away with the intro and handle at our
app or website player, but we would like the intro no matter the location
you connect from, like TuneIn or NPR.org.

I believe that this may, unfortunately, be a bug from the client's
listening software. Liquidsoap is indeed just a source and, mostly, icecast
acts as a proxy between one source and many listening clients.

There are several parameters you might want to test, for instance the burst
of data that icecast sends initially to the listeners. Maybe more would
help? Maybe less. Also, you could see about trying different formats, maybe
the listening software behaves differently with mp3 or opus?

Good luck!
Romain

**Comment by webtent** [comment]
Thanks for the feedback, yes, I've already tried a different format and playing with Icecast queue and burst settings up and down and none at all, same result. The players on both the app and website were setup using jplayer I believe, not by me. Guess I'll start debugging with a simple player setup of my own.

**Comment by toots** [comment]
Hi again,

Sorry to hear about these issues. Unfortunately, I don't think that we can do much about them here, thus closing this ticket.

Hope you find a good solution!
