### ISSUE TITLE
Troubles with displaying unicode texts

### ISSUE THREAD

**Issue by StarveTheEgo** [savonet/liquidsoap#712]
Hello! :) I am having some troubles about text rendering! :-)

https://i.imgur.com/LJc9zPD.png

Here is the screenshot
First one is _video.add_text.gd()_, second one is _video.add_text.sdl()_

As i see, SDL looks stylish for me, but does not support Unicode
While GD looks badly and cuts up/down, but supports Unicode

How do i get at least one working option? Maybe there is something about my system, eh
I already tried to google about GD / SDL / liquidsoap configuration, no viable results yet
Tried various unicode-supporting fonts also

As about _video.add_text.gstreamer()_ - it displays nothing in my case

Ubuntu 18.04

Thanks!

**Comment by StarveTheEgo** [comment]
There is a mistype in my screenshot.
Second line is SDL, not GD

**Comment by smimram** [comment]
Hi, utf8 support with SDL should work now.

For GStreamer it's weird it's working here. Did you explicitly specify a font ?

**Comment by StarveTheEgo** [comment]
@smimram Thanks, SDL works great now!

About GStreamer - yea, i did; And it is somehow fixed too after recompilling;
