### ISSUE TITLE
How to decode single() file only once?

### ISSUE THREAD

**Issue by StarveTheEgo** [savonet/liquidsoap#714]
Hello! How can i decode video file only once, if this is possible, without re-decoding it again? Or something similar
Maybe some kind of cache or dunno
I am having video (image+text) + audio stream (mp3/flac)
And would like to add animated background, which is mp4 file
Part of my code is:
```
# VIDEO BASE
video = empty()

# IMAGE
video = video.add_image(x=600,y=0,file='some_image.jpg',video)

# BOTTOM BACKGROUND
bottom_background = single('background_bottom.mp4')
#bottom_background = video.scale(xscale=1.0, yscale=0.5,x=0,y=500,bottom_background)
video = add([video, bottom_background])

# ... then mux audio

#.. then output via gstreamer to restreamer.io
```
And when i run liquidsoap with --debug, i constantly see:
```2019/02/16 16:19:55 [decoder:4] Decoding "background_bottom.mp4" ended: Gstreamer.End_of_stream.
2019/02/16 16:19:56 [single_7599:3] Finished with "background_bottom.mp4".
2019/02/16 16:19:56 [decoder.gstreamer:4] Using GStreamer 1.15.1.
2019/02/16 16:19:57 [single_7599:3] Prepared "background_bottom.mp4" (RID 0).
2019/02/16 16:20:06 [decoder:4] Decoding "background_bottom.mp4" ended: Gstreamer.End_of_stream.
2019/02/16 16:20:07 [single_7599:3] Finished with "background_bottom.mp4".
2019/02/16 16:20:07 [decoder.gstreamer:4] Using GStreamer 1.15.1.
2019/02/16 16:20:07 [single_7599:3] Prepared "background_bottom.mp4" (RID 0).
2019/02/16 16:20:15 [decoder:4] Decoding "background_bottom.mp4" ended: Gstreamer.End_of_stream.
2019/02/16 16:20:15 [single_7599:3] Finished with "background_bottom.mp4".
2019/02/16 16:20:15 [decoder.gstreamer:4] Using GStreamer 1.15.1.
2019/02/16 16:20:15 [single_7599:3] Prepared "background_bottom.mp4" (RID 0).
2019/02/16 16:20:24 [decoder:4] Decoding "background_bottom.mp4" ended: Gstreamer.End_of_stream.
2019/02/16 16:20:24 [single_7599:3] Finished with "background_bottom.mp4".
2019/02/16 16:20:24 [decoder.gstreamer:4] Using GStreamer 1.15.1.
2019/02/16 16:20:25 [single_7599:3] Prepared "background_bottom.mp4" (RID 0).
```
And my stream has freezes always in these moments when Gstreamer decodes my mp4
I would like to loop the file playback somehow

Also, when i run my script as a daemon, it does not work all and i am not able to stop service untill i killall (reminds me of #483). But i hope i will fix it myself or this is another kind of issue mby
My script is working fine as daemon without this video tho

Link to mp4 file is: https://ufile.io/39q7h
Initially it was some hi-res video without audio (https://pixabay.com/en/videos/northern-lights-aurora-borealis-2267/)
I used converter and added some silence stereo sound to make things work

**Comment by StarveTheEgo** [comment]
I tried to use buffer already, but probably in the wrong way, because i still have no idea when and how should i use buffer and when i should not

**Comment by StarveTheEgo** [comment]
Or maybe there can be some workaround with two same video files
Like, while one is playing, another is decoding
gotta try

**Comment by toots** [comment]
Hey. I'm not sure that you can do anything better at the moment. Initializing the decode process with Gstreamer requires some work and this is what is causing the lag that you are seeing. While it possible in the gstreamer framework to rewind a file, it's not obvious how to make use of that in liquidsoap.

One thing you might be able to do is to use `request.dynamic`. This source uses a callback operator which returns requests. You can then send the next request to be prepared in the asynchronous event queue, which should behave better with the streaming thread. Here's an example:

```
r = ref request.create("background_bottom.mp4")

def prepare_request() =
  def fn() =
    ignore(request.resolve(!r))
    (-1.)
  end
  add_timeout(fast=false,0.,fn)
end

def get_request() =
  res = !r
  r := request.create("background_bottom.mp4")
  prepare_request()
  res
end

s = request.dynamic(get_request)
```

I'm gonna close the issue here. Feel free to follow-up here or on the mailing list.

**Comment by StarveTheEgo** [comment]
Thank you!
