### ISSUE TITLE
Probleme with liveMeta

### ISSUE THREAD

**Issue by 10kes** [savonet/liquidsoap#715]
Hi,
I come back here cause I've got I've found a sample of configuration to update metadata from input.harbor but I've got an error and I don't understant why...

Here is the part of my liq file: 
```
def liveStart(headers)
    log("[LIVE-START]: live source goes up! Switching from playlist...")
    title = headers["ice-name"]
    ignore(server.execute("liveMeta.insert title=\"#{title}\""))
end
     liveset = input.harbor("live",port=****,password="****",on_connect=liveStart)

liveset = insert_metadata(id="liveMeta",liveset) 
radio = smooth_add(delay=0.8, p=0.15, normal=radio, special=microphone)

# Add the ability to relay live shows
full = fallback(track_sensitive=false,[liveset,radio])
```

and here is the error message:
```
At line 102, char 53:
  this value has type
    source(_) (inferred at line 63 char 11 - line 87 char 13)
  but it should be a subtype of (the type of the value at line 102, char 47)
    (_*_) (inferred at line 98, char 26-48)``

line 102 is: full = fallback(track_sensitive=false,[liveset,radio])
```

Regards,
Manu

**Comment by mylselgan** [comment]
Updating custom metadata on live connect at harbor can be done using this script

live= input.harbor(icy=true,icy_metadata_charset="UTF-8","live",port=,password="")
    def append_title(m) = [("title","Live DJ Connected")]end live = map_metadata(append_title, live)

**Comment by mylselgan** [comment]
for your understanding,
here "live" is the mount point
it will update the title field to "Live DJ Connected" whenever live connected

**Comment by 10kes** [comment]
That's work fine but how can I change this title with this headers["ice-name"] ?

**Comment by 10kes** [comment]
because the idea is that a lot of dj different can connect and I wish that their name is displayed at the time of their connection in the title.

**Comment by toots** [comment]
Hi,

You can certainly do that as well but it requires a little more work:

```
last_ice_name = ref ""

def on_connect(m) =
  last_ice_name := m["ice-name"]
end

live= input.harbor(on_connect=on_connect,icy=true,"test")

def append_title(m) =
  if !last_ice_name != "" then
    [("title","Live DJ Connected: #{!last_ice_name}")]
  else
    []
  end
end

live = map_metadata(append_title, live)
```

**Comment by 10kes** [comment]
thanks a lot!
