### ISSUE TITLE
Playlists with multiple root directories

### ISSUE THREAD

**Issue by PhasecoreX** [savonet/liquidsoap#718]
I have a couple of directories filled with music:

    /root
      /dir1 (100 songs)
      /dir2 (500 songs)
      /dir3 ( 12 songs)

`playlist()` has support for reading a directory:

    radio = playlist(reload = 1, reload_mode = "rounds", "/root/dir1")

Is it possible to make a playlist that can support multiple directories? In this case, I would like to have one playlist that pulls songs from both `/root/dir1` and `/root/dir2`, but not `/root/dir3`. It would have to get all the songs across both folders, and then randomly pick songs from that whole group.

I've tried using `random([playlist_dir1, playlist_dir2])` but it seems that if one playlist is much smaller than the other, you'll hear repeats from the smaller playlist more often. I assume this is because random picks one of the ready sources and plays it, not taking into account how many songs are in each playlist. Perhaps setting weights equal to how many songs are in the playlists would make it more uniform, but I would need this to be dynamic as well.

`rotate([playlist_dir1, playlist_dir2])` seems to be the same as above, but worse in my case. You'll hear the contents of playlist_dir1 multiple times before playlist_dir2 restarts.

Another thing I tried is having a text file with the above two paths in it, one per line, hoping liquidsoap would see that they were paths instead of songs in a playlist. This didn't work.

Any ideas on making this work? I suppose if it isn't possible at this time, I'll have to reorganize my music into a single folder, or perhaps use docker volumes to mount my music in multiple locations.

**Comment by Euguar** [comment]
Hi!
You may to use this config: `radio = playlist(reload = 1, reload_mode = "rounds", "/root")`.
Liquidsoap will be upload files from subdirectories.

Or you may to create playlist file (ex. `m3u` or `pls`):
```
#EXTM3U
#EXTINF:0,Artist - Title
/root/dir1/song1.mp3
#EXTINF:0,Artist - Title
/root/dir1/song2.mp3
…
#EXTINF:0,Artist - Title
/root/dir1/song100.mp3
#EXTINF:0,Artist - Title
/root/dir2/song1.mp3
…
#EXTINF:0,Artist - Title
/root/dir2/song500.mp3
#EXTINF:0,Artist - Title
/root/dir3/song1.mp3
…
#EXTINF:0,Artist - Title
/root/dir3/song12.mp3
```
and then use this config: `radio = playlist(reload = 1, reload_mode = "rounds", "/root/playlist.m3u")`
Liquidsoap will be upload all files from playlist.

Good luck!

**Comment by PhasecoreX** [comment]
Hello!

I do know that playlist() will traverse subdirectories, so the top option could work, except that I want to exclude /root/dir3. Simply creating a playlist on /root would include all three directories, instead of just the first two that I want.

For the second option, that would also work (leaving out the /root/dir3 files), however generating the playlist file itself wouldn't be dynamic. I'd have to get a cron job or something to update that playlist file. Unless liquidsoap has some sort of functionality to run a script at a given time? That script could be a simple find command that generates the playlist.

The ease of use that is playlist(), in my opinion, is the fact you can give it a directory and it will generate a list of songs from it, optionally updating when it sees changes. If you could pass it multiple paths somehow, that would be perfect.

**Comment by toots** [comment]
Hey! You can filter whatever file is being picked by the playlist using the check next argument. Something along these lines:

```
def check_next(r) =
  dirname(request.filename(r)) != "/root/dir3"
end

s = playlist(check_next=check_next,...)
```

I'm closing the ticket but feel free to follow up here or on the mailing list.
