### ISSUE TITLE
Question the Config file i have thru azuracast

### ISSUE THREAD

**Issue by gothicdude1044** [savonet/liquidsoap#720]
I have used both centovacast and Azuracast both with liquidsoap however the centovacast allows to stream to a shoutcast v2  port with a dj account why with azuracast they are telling me only shoutcast v1 logins are supported when i have logged in using sam broadcaster before and shoutcast v2 which is the dnas i have with a shoutcast v2 login?

**Comment by smimram** [comment]
Shoutcast v2 is not supported for now, see #430.
