### ISSUE TITLE
how to install liquidsoup on my ubuntu step by step ? i cant find it ? please help

### ISSUE THREAD

**Issue by khanfar** [savonet/liquidsoap#723]
**Describe the bug**
A clear and concise description of what the bug is. Add some script and log extract so we can see what is happening. Don't forget to add some context although not necessarily your whole script..

**To Reproduce**
A minimal script to reproduce the issue is the most efficient way to have your bug addressed and fixed very quickly!

**Expected behavior**

**Version details**
 - OS: [e.g. Debian, OSX]
 - Version [e.g. `1.3.4`]

**Install method**
Did you install via `opam`? Using your distribution's packages? From source?

**Common issues**
Can't decode or encode in some audio format? Check if you have [installed the correct dependencies](https://www.liquidsoap.info/download.html)

**Comment by khanfar** [comment]
i try to use installation .sh from this link : https://gist.github.com/dtcooper/a1a9d6b1b96a01191514cfbb425e5f35
but in final installation on my ubuntu 18.04 i got this error : 
W: Not_found
W: Not_found
E: Cannot find external tool 'ocamlbuild'
E: Failure("1 configuration error")

help please

**Comment by khanfar** [comment]
i try install liquid soup from terminal like this : 
sudo apt-get update
sudo apt-get install liquidsoap
but now whats next step ???? how to run it and make it record audio ??

**Comment by smimram** [comment]
There is a tutorial for getting started here: https://www.liquidsoap.info/doc-1.3.6/quick_start.html

**Comment by toots** [comment]
The recommended way to install is via `opam`. You will need `opam 2.0`. The install link above is way too complex. Here's a quick run down. 

As root:
```
# cd /tmp
# wget curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh
# chmod +x install.sh
# ./install.sh
```

As normal user:
```
% opam init --compiler=4.07.0
% opam depext taglib mad lame vorbis cry samplerate liquidsoap
% opam install taglib mad lame vorbis cry samplerate liquidsoap
```

That should give you the last `liquidsoap` with a reasonable set of features. If you need more features, checkout:
```
opam info liquidsoap
```
and install the extra package(s)

I'm closing this ticket, feel free to follow-up on here  or on the mailing list.

**Comment by khanfar** [comment]
How to record any voice come from specific app ??

**Comment by hakao32** [comment]
Is there any way to upgrade apt-get installed liquidsoap? I install it with apt-get install and version of it is 1.1.1. Now I want to upgrade it and use as a service as before. When I install it with OPAM, liquid dont be a service like apt-get installed.

**Comment by toots** [comment]
@hakao32 Looks like liquidsoap `1.4.1` is available in debian unstable now!

**Comment by bastianhilton** [comment]
> ```
> opam info liquidsoap
> ```

Thank you so much, sometimes we as techies make things to complicated for no reason lol

**Comment by KevanGP** [comment]
I keep getting an error about a missing dependency. Not sure what happened because before I started trying to stream to a server it was fine.
