### ISSUE TITLE
Where to find pre-built binaries?

### ISSUE THREAD

**Issue by akovalev** [savonet/liquidsoap#724]
Unfortuantely it's not feasible for me to build liquidsoap from the source code (as some OCaml packages are missing even when I try to build it from `liquidsoap-1.3.6-full.tar.gz` tarball which is a bit strange because I've got an impression that the main purpose of this tarball is to provide all OCaml packages that liquidsoap depends on out of the box). 

`ocamlc` is pre-installed on my machine but due to limited rights I'm not able to install other missing components required to build Liquidsoap from the source code.

So my question: Is there any way to obtain a pre-compiled binary of liquidsoap for Linux/Gentoo?

thanks in advance and my apologies if I choose an inappropriate channel to ask this kind of question

**Comment by toots** [comment]
Unfortunately, we do not provide universal binaries. I have worked on building a static binary based on `alpine` linux but alas too many of the libraries we need do not have a static version there. Some distributions with binary packaging do have pre-built binaries but gentoo isn't one of them.

**Comment by toots** [comment]
What you could do is built a liquidsoap binary on a gentoo virtual image, for instance via `docker` and then copy the result to your server/machine.

**Comment by akovalev** [comment]
Thanks for your answer and I like your idea to build a liquidsoap on a virtual machine
