### ISSUE TITLE
Stuck on default single

### ISSUE THREAD

**Issue by jeliotj** [savonet/liquidsoap#725]
I have a script for our overnight stream that is supposed to play station id's for our station on some days as well as the id for another station who shares our stream on the remaining days of the week.  On Sunday and Thursday at midnight, it starts playing the default single for 24 hours straight, then switches back to expected behavior.

Here is my script:

```
#!/home/liquid/.opam/system/bin/liquidsoap

##### Set the logfile location and also send it to standard out
set("log.file.path","/var/log/liquidsoap/liquidsoap-over.log")

##### Set the station ID location
stationid = mksafe(playlist("/home/local/STATION IDs"))
kfgmID = mksafe(playlist("/home/local/KFGM/Station IDs"))

##### Default Single Track
default = single("/home/gm/fallback-single.mp3")

##### Loading the Overnight Playlist
over = mksafe(playlist("/home/gm/overnight"))

##### Overnight for Sun - Wed
earlyweek = smooth_add(normal=over, special=switch([({0m0s},stationid)]))

##### Overnight for Thu - Sat to include KFGM ID's
lateweek = smooth_add(normal=over, special=switch([({0m0s}, stationid), ({1m0s}, kfgmID)]))

##### Puttin' the overnight together.
overnight = fallback([switch([({ 1w-5w }, earlyweek), ({ 6w-7w }, lateweek)]), default])

##### Output overnight to Icecast mount /overnight
output.icecast(%mp3(bitrate=128, samplerate=44100, stereo=true),host="localhost", port = 9999, password = "********", mount = "overnight", overnight)
```

Here is a pertinent section of the log:

```
2019/03/01 08:22:30 [decoder:3] Method "MAD" accepted "/home/gm/fallback-single.mp3".
2019/03/01 08:22:30 [threads:3] Created thread "generic queue #1".
2019/03/01 08:22:30 [threads:3] Created thread "generic queue #2".
2019/03/01 08:22:30 [threads:3] Created thread "non-blocking queue #1".
2019/03/01 08:22:30 [threads:3] Created thread "non-blocking queue #2".
2019/03/01 08:22:30 [STATION_IDs:3] Loading playlist...
2019/03/01 08:22:30 [STATION_IDs:3] Playlist is a directory.
2019/03/01 08:22:30 [STATION_IDs:3] Successfully loaded a playlist of 69 tracks.
2019/03/01 08:22:30 [overnight:3] Loading playlist...
2019/03/01 08:22:30 [overnight:3] Playlist is a directory.
2019/03/01 08:22:30 [decoder:3] Method "MAD" accepted "/home/local/STATION IDs/Conscious 2.mp3".
2019/03/01 08:22:30 [overnight:3] Successfully loaded a playlist of 9691 tracks.
2019/03/01 08:22:30 [Station_IDs:3] Loading playlist...
2019/03/01 08:22:30 [Station_IDs:3] Playlist is a directory.
2019/03/01 08:22:31 [decoder:3] Method "MAD" accepted "/home/gm/overnight/Lionel Hampton/Lionel Hampton - The Ultimate Jazz Archive, Big Bands-Lionel Hampton/10-Lionel Hampton-Punch and Judy.mp3".
2019/03/01 08:22:31 [Station_IDs:3] Successfully loaded a playlist of 5 tracks.
2019/03/01 08:22:31 [single_6435:3] "/home/gm/fallback-single.mp3" is static, resolving once for all...
2019/03/01 08:22:31 [single_6435:3] Prepared "/home/gm/fallback-single.mp3" (RID 0).
2019/03/01 08:22:31 [overnight(dot)1:3] Connecting mount overnight for source@localhost...
2019/03/01 08:22:31 [decoder:3] Method "MAD" accepted "/home/local/KFGM/Station IDs/Butte ID.mp3".
2019/03/01 08:22:31 [overnight(dot)1:3] Connection setup was successful.
2019/03/01 08:22:31 [threads:3] Created thread "wallclock_main" (1 total).
2019/03/01 08:22:31 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2019/03/01 08:22:31 [fallback_6448:3] Switch to single_6435.
2019/03/01 08:22:54 [single_6435:3] Finished with "/home/gm/fallback-single.mp3".
2019/03/01 08:22:54 [single_6435:3] Prepared "/home/gm/fallback-single.mp3" (RID 0).
2019/03/01 08:23:16 [single_6435:3] Finished with "/home/gm/fallback-single.mp3".
2019/03/01 08:23:16 [single_6435:3] Prepared "/home/gm/fallback-single.mp3" (RID 0).
2019/03/01 08:23:25 [main:3] Shutdown started!
```

Any suggestions would be appreciated.

**Comment by toots** [comment]
I think you've got the days wrong. Here: https://www.liquidsoap.info/doc-1.3.6/language.html

> w stands for weekday, ranging from 0 to 7, where 1 is monday, and sunday is both 0 and 7.

**Comment by toots** [comment]
That does not explain the behavior you're seeing, though, just why it fails on those day, which is the days where it switches from one overnight spec to the other one.

I say you should try to broaden the conditions on the the `smooth_add` switch. Something like: `0m0s-0m15s` perhaps, just to make sure that is the jingle source isn't immediately available the source does not fail immediately. I would also test without `smooth_add` to see if the issue is tied to this operator.

Let us know!

**Comment by jeliotj** [comment]
Thanks @toots ,

Fiddling with the timing in smooth_add seems to have helped.  I didn't realize you could have a range of time there.

Thanks also for the note about the days; I recently edited them and put in incorrect values.

**Comment by jeliotj** [comment]
I thought that changing the times in smooth_add was a fix but it was not.  Instead, it then prepares more than one file from the directory pointed to for jingles, overlapping them if the range is too short.

The solution was a simple one.  The range of days had me confused.  I needed:

  `fallback([switch([({ 0w-5w }, earlyweek), ({ 5w-7w }, lateweek)]), default])`

because the range is inclusive of the first day but up to and not including the second day.  I was unaware of that particular usage and thus was not including Thursday and Sunday when I set it to 0-4 and 5-6 or some such range.  That is why it played the default single for 24 hours and then stopped.

Thanks again for your help.

**Comment by toots** [comment]
Glad to hear that it's fixed!
