### ISSUE TITLE
Read metadata from wav stream

### ISSUE THREAD

**Issue by KruegerDead** [savonet/liquidsoap#727]
I have a MPD with always on playing music, streamed in WAVE format. I try to restream it with Liquidsoap, but metadata is missing in output of liquidsoap streams. If i play source of MPD wav with any player, metadata is ok. Any chance to add metadata reading from wav option in liquidsoap?
Maybe this is due to this issue: https://github.com/savonet/liquidsoap/issues/173
OS: Windows 7 x64
Liquidsoap version: 1.4.0-alpha1 (and previous)
cfg:
```
set("log.file",true)
set("log.stdout",true)
set("log.level",4)

s = input.http("http://localhost:6800")
s = mksafe(s)

# MY OUTPUTS
# ...
```

**Comment by toots** [comment]
Hi!

There's no common standard for WAV metadata. Could you share some of these files so I can have a look at them?

**Comment by KruegerDead** [comment]
http://78.29.12.41:6800/ it maybe laggy. Because its wav stream.

**Comment by toots** [comment]
First glance doesn't seem to show metadata. Are they passed on song change?

**Comment by toots** [comment]
Nevermind got it. I see now, they are passed as ICY metadata, very interesting.

**Comment by chrispolley** [comment]
Sample wav file file tagged using the BSI "InfoEdit" utility:(http://www.bsiusa.com/software/info_edit/info_editor.php) 

[metadataSample.zip](https://github.com/savonet/liquidsoap/files/2920510/metadataSample.zip)

**Comment by toots** [comment]
It's fixed in `master`. I'm gonna let it sit there and be rolled with the next major release as this might need further testing to make sure it doesn't break other use cases.

**Comment by chrispolley** [comment]
Looking at that wave file, the info I added is at the very end; there is additional metadata in XML format before that from the stock service I obtained the item from.
