### ISSUE TITLE
Strange error flushing buffer because of input.harbor

### ISSUE THREAD

**Issue by aliv** [savonet/liquidsoap#728]
**Describe the bug**
hi
i have liquidsoap 1,3,4 on ubuntu 18.04.
i have two .liq files and there is a line like this in both .liq files:
//only icecast mount is differnet for two files
```
live = input.harbor(id="harbor",  "harbor.mp3", password="xyz")
final = add([final, live])
output.icecast(..., final)
```

i can run first liq file without problem but for second .liq file there is a error like 
`strange error flushing buffer ...`
if i change harbor port for second liq file to another port like '8007' there is no problem. 

- i want to know if this a correct behavior? 
- so when we want to send one unique live event to two multiple stations -which run with different liq files and get live with input.harbor-, we need two different instance of Butt -with different port configs- to send stream to this stations?

**Version details**
 - OS: [ubuntu 18.04]
 - Version [`1.3.4`]

**Install method**
opam

**Comment by toots** [comment]
Hmm. I'm surprised changing the port makes a difference. As far as I remember, this is a log message coming from one of the libraries -- the lame encoder I believe, and you should be able to safely ignore it..

**Comment by aliv** [comment]
@toots besides mentioned error, I can't hear second  stream ran by liquidsoap liq2.file.  Only if those input harbor have different port, there is no error and both of them stream correctly. I hope I describe the situation clearly.

**Comment by aliv** [comment]
i updated to 1.3.6 and i receive this warning (strange error flushing buffer) without any output with this version too.

**Comment by makeworld-the-better-one** [comment]
@toots Just noticed this error occurring for me too, with the latest version 1.4.2. That's all the log output will show, again and again. Can you reopen this.

**Comment by makeworld-the-better-one** [comment]
Thanks. Any idea what's causing it?

**Comment by toots** [comment]
Hi there. I want to revisit this. @makeworld-the-better-one what exactly is the error here for you? Just the log or do you also see some other issues?
