### ISSUE TITLE
Icecast 1

### ISSUE THREAD

**Issue by alcir** [savonet/liquidsoap#729]
Hello, and sorry. Maybe this is the wrong place to ask this question.
I'm able to configure icecast 2 input
`live=audio_to_stereo(input.harbor("live",port=2081,user="source",password="foo"))
`
And southcast input
`live_dj = audio_to_stereo(input.harbor(icy=true,"/",port=2082,password="bar")`

How to configure input for icecast 1?

**Comment by toots** [comment]
Hi,

Icecast 1 protocol should be supported although it has never really been tested extensively. Even at the time the harbor input was implemented (which puts us more than 10 years in the past wow!), icecast 1 was largely gone and even more for source clients using that protocol.

Do you have source clients sending this format still?

**Comment by alcir** [comment]
Thanks for the answer. 
I was not configuring the client in the right way.
