### ISSUE TITLE
Add ability to limit area of scrolling text. Scrolling enhance

### ISSUE THREAD

**Issue by StarveTheEgo** [savonet/liquidsoap#730]
**Is your feature request related to a problem? Please describe.**
I would like to add scrolling text via **video.add_text** function (this is currently possible)
I would like to have this text to scroll on some limited area. Like, i can dedicate some part of screen for this and scroll text only in that small part of screen. Currently text is scrolling on the full width of frame, so the thing i want to achieve is impossible currently

**Describe the solution you'd like**
Probably add arguments:
**width** - scrolling width / text area width. Default value is frame width
**height** - scrolling height / text area height. Default value is... font size? Not sure tho

And maybe replace **speed** with:
**x_speed** - scrolling speed on X axis. Default value is 0
**y_speed** - scrolling speed on Y axis. Default value is 0
^ In order to allow vertical scrolling too

**Additional context**

I think if you guys are overloaded i can try to learn this OCaml and join to help, since i am programmer
But not sure yet  :D

And, sorry for unrelated question: when will be next version released? I am not familiar with conventions of this project. Like, maybe you release every [xx] features or months or... is there public roadmap? Thanks forward!

**Comment by smimram** [comment]
I think that an even better solution would be to have functions so that the user can specify pretty much any dynamic placement of text. I'll try to have a look at it.

**Comment by aliv** [comment]
@smimram is it possible to have a feature to update or remove text via telnet by id too?

**Comment by smimram** [comment]
Ok, so you can now do:
```
y = ref(0)

def ty () =
  y := !y-1;
  if !y <= -100 then y := 0 end;
  !y
end

s = single("test.avi")
s = video.add_text(x=0, y=ty, speed=0, size=40, "Hello world!", s)
s = mksafe(s)

output.sdl(s)
```
which allows you to program whatever function for `x` and `y`. For the text it was already the case, you can use a similar logic with references to update it!

**Comment by StarveTheEgo** [comment]
Nice! So i can improve Deer Radio now!

**Comment by toots** [comment]
Thanks @sam! Would you mind adding a Changelog entry for it?
