### ISSUE TITLE
vide.add_image wont work

### ISSUE THREAD

**Issue by aliv** [savonet/liquidsoap#731]
**Describe the bug**
i would like to add logo to my videos by video.add_image but at final streamed result i can't see logo.
although text added by video.add_text.sdl(...) is shown.

**To Reproduce**

```
playlist=playlist(...)

playlist=video.add_text.sdl(
         ...
        "text", playlist
)

playlist = video.add_image(
       width=100,
      height=100,
       x=10,y=10,
       file="logo.jpg",
       playlist)

output.icecast(
        format = "video/ogg",
        icy_metadata="false",
        fallible=true, 
		%gstreamer(
                ...
                ),
        host="127.0.0.1",
        password="xx",
        mount="video",
        playlist
)
```

at log, i can see
 
```
[decoder:3] Method "SDL/IMAGE" accepted ...
[decoder:3] Method "IMAGE" accepted ....
[img:3] Prepared "logo.jpg" (RID 2)
```

and there is no error but i don't know why image is not appeared in final stream.

**Version details**
 - OS: [e.g. ubuntu 18.04]
 - Version [e.g. `1.3.6`]

**Install method**
opam

**Comment by smimram** [comment]
I can confirm that. @toots any change related to `add` recently?

**Comment by smimram** [comment]
For info, it was working in 1.3.3 but various changes in configure and libraries make bisection difficult.

**Comment by autonarcosis** [comment]
Convert the image file to a PPM image file and see if that works.  Had same issue and the ppm file worked.

**Comment by aliv** [comment]
@autonarcosis thanks for suggestion but it doesn't work too. also it seems there is support for other common formats after https://github.com/savonet/liquidsoap/pull/33.

**Comment by toots** [comment]
@smimram not much change on `add()` since `1.3.3`. I haven't touched much of the video layer for a while either. Let me know if y'all can bisect to a good point.

**Comment by autonarcosis** [comment]
The PPM image file needs to be in RGB24.

$ffprobe -i logo.ppm

Stream #0:0: Video: ppm, rgb24, 2407x2022, 25 tbr, 25 tbn, 25 tbc

The article you refer to is from 2013. Consider that to be outdated and a 'it maybe kinda supports those files but probably not'.

**Comment by aliv** [comment]
@autonarcosis also ppm doesn't work. output of ffprobe is :
```
Input #0, ppm_pipe, from 'pic.ppm':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: ppm, rgb24, 70x31, 25 tbr, 25 tbn, 25 tbc
```
