### ISSUE TITLE
Stream http directly 

### ISSUE THREAD

**Issue by cdkey22** [savonet/liquidsoap#733]
Hello thanks for all your work,

The problem I have is the following, when I push an http file in my queue (queue.push http://{url_of_mp3_file} i have to wait the file to be completly download before starting.

I tried to use gstreamer or ffmpeg via external but it has to be defined in the liq file and I can't provide them into the queue (or i don't know how)

Is there a way to resolve my problem,

Thanks in advance,

**Comment by toots** [comment]
Hi,

If the `http` resource you are trying to stream takes too long to pre-process, you should switch to `input.http` instead. This will stream the resource as it is being fetched.

However, the draw back here is that it is not easy to change the `url` used for the source. One thing you can do, however, is to point the source to a playlist, for instance `m3u` format. Then the source will simply pick up a track from it and play it. Once the track has finished, it will pull the playlist again, and that's where you can specify a new song (or none).

**Comment by cdkey22** [comment]
I tried to put the http url of mu m3u file (or directly for testing the mp3 file url) directly in input.http (
main_queue = input.http("http://armb2.saooti.net:8888/armb/media?path=Efficace%2FSummer+Of+Love+-+U2.mp3"). It doesn't works and buffer indicate that it was full.
I set an important buffer (for testing)
main_queue = input.http(max=3000.,"http://armb2.saooti.net:8888/armb/media?path=Efficace%2FSummer+Of+Love+-+U2.mp3"). No error log anymore (except [http_10577:2] Feeding stopped: end of track looping) but no sound

Did i do the right thing (I'm not sure) ? 
Is it supposed to work like that ? 
Can I put a m3u url instead of a file url ?

**Comment by toots** [comment]
It seems that the audio is mono. You will need to convert it using `audio_to_stereo(input.http(...))`. You indeed need a buffer that can contain the whole file potentially, since the download will happen faster than real time rate.
