### ISSUE TITLE
[Question/Feature Request] List/print sources informations

### ISSUE THREAD

**Issue by silverkorn** [savonet/liquidsoap#734]
Hi,

I'm new with liquidsoap and I did not find anything about this in the documentation, examples and in GitHub but is there a way to list the available sources by name, ID and their different attributes (number of input/output, etc.) so we can select the proper one in a script?

If there is a way to list them directly with liquidsoap's API, let me know.
Otherwise, an additional switch could be really useful, maybe something like `--list-devices=TYPE`, where "TYPE" could be `portaudio`, `pulseaudio`, `jack`, etc.
The listing directly from liquidsoap would be more viable for both needing only the application itself and not an additional one but also to avoid unavailable devices or ID assignation clash due to different compiled libraries between them (e.g.: Portaudio built with VS without ASIO)

Thank you!

**Comment by toots** [comment]
Hi!

Welcome!

Have you tried this link: https://www.liquidsoap.info/doc-1.3.6/reference.html

**Comment by silverkorn** [comment]
> I did not find anything about this in the **documentation**, examples and in GitHub

:stuck_out_tongue_winking_eye: 

---

I'm trying to gather some information like the name associated to the input ID just like how Portaudio has it in this example: http://portaudio.com/docs/v19-doxydocs/pa__devs_8c_source.html

This returns something like this:
```
Number of devices = 16
--------------------------------------- device #0
Name                        = Mappeur de sons Microsoft - Input
Host API                    = MME
Max inputs = 2, Max outputs = 0
Default low input latency   =   0.0900
Default low output latency  =   0.0900
Default high input latency  =   0.1800
Default high output latency =   0.1800
Default sample rate         = 44100.00
Supported standard sample rates
 for half-duplex 16 bit 2 channel input =
         8000.00,  9600.00, 11025.00, 12000.00,
        16000.00, 22050.00, 24000.00, 32000.00,
        44100.00, 48000.00, 88200.00, 96000.00,
        192000.00
--------------------------------------- device #1
[ Default Input ]
Name                        = Microphone sur casque (Plantron
Host API                    = MME
Max inputs = 2, Max outputs = 0
Default low input latency   =   0.0900
Default low output latency  =   0.0900
Default high input latency  =   0.1800
Default high output latency =   0.1800
Default sample rate         = 44100.00
Supported standard sample rates
 for half-duplex 16 bit 2 channel input =
         8000.00,  9600.00, 11025.00, 12000.00,
        16000.00, 22050.00, 24000.00, 32000.00,
        44100.00, 48000.00, 88200.00, 96000.00,
        192000.00

[…]
```

---

I've tried with this:
```
setenv("PA_RECOMMENDED_INPUT_DEVICE","1")
sourceInput = input.portaudio()
log(source.id(sourceInput))
shutdown()
```
But it returns an unrepresentative name:
```
[…]
2019/03/14 11:28:51 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/03/14 11:28:51 [lang:3] portaudio_6708
2019/03/14 11:28:51 [threads:3] Created thread "gstreamer_main_loop" (1 total).
[…]
```

Just so you know, the `sourceInput` in the test does receive data and outputting in a file works properly.

Thanks!

**Comment by silverkorn** [comment]
@toots, any guidelines/updates?
Thanks!

**Comment by silverkorn** [comment]
If #857 is done, this part could probably be done in a similar way?

**Comment by silverkorn** [comment]
@toots , is this something that will be done?
