### ISSUE TITLE
Curl timeout when requesting a media

### ISSUE THREAD

**Issue by cdkey22** [savonet/liquidsoap#736]
**Describe the bug**
I moved to liquidsoap 1.3.6 installed via opam. Previously i was building LS using the makefile. In my new version of liquidsoap, each time a request is done via http (using curl) it fail and logs indicate a timeout. I tried to delete the curl binray and get the same result (instead of immediate error). I also tried to use the 
set("protocol.external.curl","/usr/bin/curl") line in my liquidsoap file and it does the same.
I don't understand what am I doing wrong

**To Reproduce**
Here a sample script to execute
``
#!/bin/liquidsoap

set("log.level",4)
set("log.stdout", true)
set("log.file",false)
set("tag.encodings",["UTF-8"])
set("protocol.external.curl","/usr/bin/curl")

telnet_port = 12345

log(level=2,"Using telnet port : #{telnet_port}")
set("server.telnet", true)
set("server.telnet.bind_addr", "127.0.0.1")
set("server.telnet.port", int_of_string("#{telnet_port}"))

main_queue = playlist("http://corse.saooti.com:8888/ambiance/services/playlist/4.m3u?duration=100")

return = output.dummy(id="return", mksafe(main_queue))
``

**Expected behavior**
I would like the playlist to be downloaded in the coresponding file. The curl doesn't seem to work.

**Version details**
 - OS: Ubuntu 16.04
 - Version: 1.3.6

**Install method**
Installed via opam (opam installed from binaries)

** Additionnal information **
* I tried to put a mp3 in input.queue and i have the same problem
* I tried to make a docker container to run into to be the simpliest and i have the same problem (Dockerfile bellow)
``
#Docker file for creating the builder
FROM ubuntu:18.04

#Updating and upgrading
RUN apt update && apt upgrade -qy
#Installing all packaging and building tools
RUN apt -y install autoconf pkg-config sudo wget yasm unzip python3 build-essential libtool curl
#Installing ocaml to version 4.06
RUN wget http://caml.inria.fr/pub/distrib/ocaml-4.06/ocaml-4.06.0.tar.gz && tar xvf ocaml-4.06.0.tar.gz && cd ocaml-4.06.0 && ./configure &&  make world.opt && make install
#Installing opam to version 2.03
RUN wget https://github.com/ocaml/opam/releases/download/2.0.3/opam-2.0.3-x86_64-linux && cp opam-2.0.3-x86_64-linux /usr/local/bin/opam && sudo chmod a+x /usr/local/bin/opam
#Installing all needed binaries
RUN apt -y install faad fdkaac lame
#Installing all needed libraries
RUN apt -y install libfdk-aac-dev libmad0-dev libmp3lame-dev libpcre3-dev libssl-dev
#Creating liquidsoap user
RUN useradd liquidsoap  && mkdir /home/liquidsoap && chown -R liquidsoap:liquidsoap /home/liquidsoap
#Initializing opam repository
RUN su liquidsoap -c "opam init --disable-sandboxing -y"
#Install liquidsoap
RUN su liquidsoap -c "opam install ssl -y"
RUN su liquidsoap -c "opam install fdkaac -y"
RUN su liquidsoap -c "opam install lame -y"
RUN su liquidsoap -c "opam install mad -y"
RUN su liquidsoap -c "opam install liquidsoap -y"
RUN cp /home/liquidsoap/.opam/default/bin/liquidsoap /bin/liquidsoap && sudo chmod uga+x /bin/liquidsoap
#Have to add the file and mange output ...
``

**Comment by toots** [comment]
Thanks for your report. There's an known issue (#691) that is most likely you issue as well. The fix has been in the `master` branch for a while but was only scheduled for a major release due to the amount of code needed for it.

I realized now that it really needs to be fast tracked. I have just pushed the fix to the `1.3.7` bugfix branch and will make a call for testing in the next days. Meanwhile you should be to test the following way:
```
git clone --recursive https://github.com/savonet/liquidsoap.git
cd liquidsoap
git checkout 1.3.7
opam pin add .
```
Let us know if the fix works for you!
