### ISSUE TITLE
encoding="ISO-8859-1"

### ISSUE THREAD

**Issue by hmorneau** [savonet/liquidsoap#737]
I'm running liquidsoap 1.3.3 (debian) installed from apt and when I add in output.icecast the option encoding="ISO-8859-1", it doesn't work. On a different server running an older version of liquidsoap it works fine (1.1.1) and the charset show correctly. It's needed to connect to icecast KH11.

On a side note I tried installing 1.3.6 but everything I have tried have failed so far. From source there is tons of lib missing, from opam it install 1.3.3-1 (and I'm not sure where the package get installed, it's not in /usr/bin/liquidsoap. If I try to install from source with 
```
# opam:opam pin add liquidsoap .
liquidsoap is now path-pinned to /home/liquidsoap/liquidsoap

[liquidsoap] /home/liquidsoap/liquidsoap/ synchronized
[ERROR] File "/home/liquidsoap/.opam/system/packages.dev/liquidsoap/liquidsoap.opam", line 110, character 9-10: parse error.
[WARNING] Errors in opam file from liquidsoap source, ignored (fix with 'opam pin edit')

liquidsoap needs to be installed.
[ERROR] liquidsoap.1.3.4 is not available because your system doesn't comply with ocaml-version >= "4.03".
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```
Seems like there is no easy way to install liquidsoap at the moment.

**Comment by rafaelbaiolim** [comment]
Liquidsoap 1.3.6 requires `opam 2.x` to be installed, if you already have `opam 1.x` you could try this: 

``` 
$ curl https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh -o /home/streaming/install.sh && chmod +x /home/streaming/install.sh && echo '' | sh /home/streaming/install.sh --fresh 
```

And after that: 

```
$ opam update && opam pin add liquidsoap 1.3.6 -y && opam upgrade -y
```

If everything goes wrong, I suggest you to `uninstall opam` and removes all from `~/.opam` folder. Reinstall with `opam 2.x ` and all packages you're using.  

I set my current liquid script for encoding="ISO-8859-1" and works fine here with liquidsoap v1.3.6.

**Comment by smimram** [comment]
A solution was already posted (thanks @rafaelbaiolim) and no feedback, closing. Feel free to reopen if you still have problem compiling.
