### ISSUE TITLE
Ability to suppress metadata being sent to Icecast/SHOUTcast/etc?

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#738]
Hello Liquidsoap team! AzuraCast dev here with a quick question.

A number of my users have requested the addition of a feature that is basically "jingle mode", where a given track plays in the regular rotation, but it doesn't trigger a metadata update to the broadcast frontends (Icecast/SHOUTcast/etc), so listeners continue to see the song that was playing prior to it while the jingle/commercial/etc. rolls.

Currently, I've implemented that on the software side in a bit of a "hacky" way: since my software tracks the song history for the station, it knows the title/artist of the song previous to the jingle, so when Liquidsoap requests the next song, it simply provides the jingle's filename but the previously played file's metadata. To listeners (and to my software) this is akin to just extending the previous song, but it makes sure the jingle gets played too.

This is possible as long as users have AzuraCast set so that it provides the "next" song to Liquidsoap itself, but in a lot of cases they don't want to do this (i.e. so that LS can cut off playlists strictly on schedules or do other more advanced config), and despite some searching I couldn't find any way to tell Liquidsoap _not_ to send a metadata update to its broadcast frontends when the song changed.

Any pointers on whether this is possible, and what this would look like in the .liq file?

Thanks as always. Much love from me and the AzuraCast team. <3

**Comment by Euguar** [comment]
Hello! Maybe **drop_metadata** function helps you:
```
music=playlist("/path/to/your/music")
jingles=playlist("/path/to/your/jingles")
jingles=drop_metadata(jingles)
```
See https://www.liquidsoap.info/doc-1.3.6/reference.html#drop_metadata

**Comment by toots** [comment]
I believe @Euguar's response should be what you need. You can be even more finer-grained in when to send metadata or not by implementing your own function. For reference you can see the code for `drop_metadata`:

```
# Removes all metadata coming from a source.
# @category Source / Track Processing
def drop_metadata(s)
  map_metadata(fun(_)->[],update=false,strip=true,insert_missing=false,s)
end
```

**Comment by SlvrEagle23** [comment]
@toots What would be the logistics of handling this in an on_metadata function? As far as I know, the on_metadata function only receives the updated metadata as an argument and can't manipulate the metadata on the fly.

Basically, I'm looking for something akin to:

```
def handle_jingle_mode(m) = 
  if (m["jingle_mode"] == "") then
    log("Jingle mode; stripping metadata...")
    []
  end
  m
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)
```

...but the above throws this error:

```
At line 57 char 31 - line 59 char 6:
  this value has type
    (...)->[_]
  but it should be a subtype of
    (...)->unit
```

**Comment by SlvrEagle23** [comment]
@toots Any idea what I'm doing wrong with the function above? I like to think I'm rather familiar with the Liquidsoap scripting model but it's got me stumped. Thanks for your help :)

**Comment by toots** [comment]
@SlvrEagle23 yeah, you need to provide a return value in a functional fashion:

```
def handle_jingle_mode(m) = 
  if (m["jingle_mode"] == "true") then
    log("Jingle mode; stripping metadata...")
    []
  else
    m
  end
end
radio = map_metadata(handle_jingle_mode,update=false,strip=true,insert_missing=false,radio)
```

That should work.

**Comment by SlvrEagle23** [comment]
@toots Works like a charm. I don't know why it didn't occur to me to try that, since it's so similar to my existing code, but years of working in PHP has drilled into me the micro-optimization of avoiding "else"s on conditionals that return.

Thanks for your help!
