### ISSUE TITLE
Need help with cutting a live stream

### ISSUE THREAD

**Issue by CGenie** [savonet/liquidsoap#739]
Hello,

I have a live stream with

```
s = input.http('...')
```

I want to play only 30 minutes of it, then cut it. I found the `cue_cut` which I think could work, however it needs some metadata set (`liq_cue_in` and `liq_cue_out`) however I'm not sure I know how to set it (examples on the website are for playlist and apparently `input.http` is something different).

Thanks in advance.

**Comment by Euguar** [comment]
Hello!
If you're broadcasting via Icecast try to use `<max-listener-duration>` value on server config for mountpoint. This value which will set the length of time in seconds a listener will stay connected to the stream.

**Comment by toots** [comment]
Hi all,

@Euguar's solution has some merit for sure! `cue_cut` is for file-based source so it won't work here.

If you need to do it in the script you'll need a little more work but it's definitely possible. One question first: what should happen after the initial 30s?

**Comment by CGenie** [comment]
I basically have a radio station schedule base on libretime. I have an external script which is called once a day to re-stream an MP3 stream from some internal source, it always takes 30 minutes. Currently I have a systemd service which starts and then kills the `oneshot` service, but I thought that liquidsoap could at least cut the stream after those 30 minutes. Also I want to insert some jingle just before and after the stream, so the systemd stopping functionality becomes problematic now.

**Comment by CGenie** [comment]
Any thoughts on this? I still can't find how to solve the problem apart from hacking with systemd timers :)

**Comment by smimram** [comment]
The [`chop`](https://www.liquidsoap.info/doc-dev/reference.html#chop) operator will insert tracks at regular intervals. To have a new track every 30 min you can do something like
```
s = chop(duration = 30.*60., input.http(...))
```
and then use a `switch` over that to change track.

**Comment by smimram** [comment]
As an example, here is how I would make the source `s` unavailable after 3 seconds:
```
s = single("test.mp3")
a = ref.make(true)
s = available({!a}, s)
add_timeout(3., {ref.set(a,false); -1.})
out(s)
```
(the `available` operator is brand new, but easily coded with `switch`).
