### ISSUE TITLE
 This term would evaluate to a function   which would then be dropped. This is usually the sign of an unintended   partial application: some arguments may be missing.

### ISSUE THREAD

**Issue by DJIronic** [savonet/liquidsoap#740]
Hello, I just started with liquidsoap and I am unable to pass this issue even when starting with the quickstart guide.

What my plan is?

I have two streams: My studio and cloud with always running automation software. What I want is to let the **cloud automation** play and once the **studio** gets connected to the liquidsoap (probably bot of the will be harbor). It will make a crossfade transition between them with playing a jingle in it. Of coruse, I want a playlist that will be a total backup  when both of my souirces will go down. That config can be hard and I am unsure how to build it. But when I tried, I ended up on this error: 

```
 This term would evaluate to a function
  which would then be dropped. This is usually the sign of an unintended
  partial application: some arguments may be missing.
```
So I decided to start slowly with the basic radio setup on the quickstart page of your documentation, but I ended on the same error again.

**To Reproduce**

This is my first to to build the script to achieve my goal:

```
#!/usr/bin/liquidsoap
# Log dir
set("log.file.path","/home/ls.log")

set("harbor.bind_addr","0.0.0.0")

playit = mksafe(input.harbor("playit",port=8080,password="UsdfsdffsdVCeJQp"))

studio = input.harbor("studio",port=8080,password="TMjPfsfsdfssd4fM")

jingle = single("/home/jingles/prechod.flac")

radio = fallback(track_sensitive=false,
	     transitions=[ crossfade, transition(jingle) ],
	     [studio,playit]))

output.icecast(
        %ogg(%flac),
        host = "HIDDEN",
        port = HIDDEN,
        password = "password",
        mount = "stream",
)

```

And this is the simplest radio one that ends on the same error:
```
#!/usr/bin/liquidsoap
# Log dir


# Music
myplaylist = playlist(mode='randomize',reload=1,reload_mode="rounds", "/home/songs/")
# Some jingles
jingles = playlist(mode='randomize',reload=1,reload_mode="rounds", "/home/songs/")
# If something goes wrong, we'll play this
security = single("/home/jingles/prechod.flac")

# Start building the feed with music
radio = myplaylist
# Now add some jingles
radio = random(weights = [1, 4],[jingles, radio])
# And finally the security
radio = fallback(track_sensitive = false, [radio, security])

 # Stream it out
output.icecast(
        %ogg(%flac),
        host = "SERVER",
        port = PORT,
        password = "PASS",
        mount = "stream",
)
```

**Expected behavior**

**Version details**
 - OS: [Ubuntu server 18.04]
 - Version [newest one from the repository]

**Install method**
Used Ubuntu apt-get

I am trying my best to solve it, but still no idea whats going on. Can you please help make my idea work and start using liquidsoap. The reason for doing this that I want to run the station with FLAC (and then copy the script for MP3 version, as I can't transmit meta tags with FLAC). And I need to broadcast the result to a icecast server as this is th eonly way how to get it properly licensed.

Thank you very much!

**Comment by savonet-users** [comment]
You do not have the radio as a source for the icecast output.
output.icecast(
        %ogg(%flac),
        host = "SERVER",
        port = PORT,
        password = "PASS",
        mount = "stream", radio
)

**Comment by DJIronic** [comment]
So if I will fix that, even the frist script will work?

**Comment by toots** [comment]
Hi,

@DJIronic, yes, you need to apply all required parameters to the `output.icecast` operator. If you pass it a source, it should be able to execute. Closing here but feel free to continue the discussion.
