### ISSUE TITLE
Support external decoders on Windows

### ISSUE THREAD

**Issue by mjb2010** [savonet/liquidsoap#742]
On Windows, I would like to be able to stream from a playlist which has many FLAC files in it.

[The documentation](https://www.liquidsoap.info/doc-dev/external_decoders.html) mentions that external decoders are not available on Windows. This prevents FLAC sources from being used.

This feature request is a humble plea to remedy this situation, at least for FLAC, if not all external decoders.

**Comment by toots** [comment]
Hi, 

Flac support was mistakenly removed from the windows build. I have uploaded an updated 1.3.7-beta1 windows build with flac support here: https://github.com/savonet/liquidsoap/releases/tag/1.3.7-beta1

I'm keeping this open as I want to re-assess external decoders on windows in the future.

**Comment by mjb2010** [comment]
Thanks! The new build is working well for me.
