### ISSUE TITLE
smart_crossfade documentation needs update

### ISSUE THREAD

**Issue by mjb2010** [savonet/liquidsoap#743]
The smart_crossfade() documentation does not have all the current parameters explained.

This can be remedied by updating doc/content/smartcrossfade.txt to include the current code from scripts/utils.liq

**Comment by toots** [comment]
Thanks for this report. I am currently working on a rewrite of the `smart_crossfade` function. I'll make sure to address this report as well.

**Comment by toots** [comment]
It looks like the parameters are all documented in the rewrite PR. This should close this issue when the PR is merged.
