### ISSUE TITLE
Fixing the replaygain madness

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#749]
```
$ sox -n rp.mp3 synth 3 sine 500
$ ffmpeg -i rp.mp3 rp.ogg
$ ffmpeg -i rp.mp3 rp.m4a
$ mp3gain -s i rp.mp3
$ vorbisgain rp.ogg
$ aacgain rp.m4a
$ ffprobe rp.mp3
Input #0, mp3, from 'rp-i.mp3':
  Metadata:
    replaygain_reference_loudness: 89.0 dB
    replaygain_track_gain: -4.220000 dB
    replaygain_track_peak: 0.307712
    MP3GAIN_MINMAX  : 134,177
  Duration: 00:00:03.02, start: 0.000000, bitrate: 69 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, mono, fltp, 64 kb/s
    Side data:
      replaygain: track gain - -4.220000, track peak - 0.000007, album gain - unknown, album peak - unknown,
$ ffprobe rp.ogg
Input #0, ogg, from 'rp.ogg':
  Duration: 00:00:03.02, start: 0.000000, bitrate: 26 kb/s
    Stream #0:0: Audio: vorbis, 48000 Hz, mono, fltp, 80 kb/s
    Metadata:
      ENCODER         : Lavc58.35.100 libvorbis
      REPLAYGAIN_TRACK_PEAK: 0.31471366
      REPLAYGAIN_TRACK_GAIN: -4.28 dB
    Side data:
      replaygain: track gain - -4.280000, track peak - 0.000007, album gain - unknown, album peak - unknown,
$ ffprobe rp.m4a
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'rp.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 512
    compatible_brands: isomiso2
    encoder         : Lavf58.20.100
    replaygain_track_peak: 0.31
    replaygain_track_gain: -4.22
    replaygain_track_minmax: 117,148
  Duration: 00:00:03.05, start: 0.000000, bitrate: 56 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 52 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Side data:
      replaygain: track gain - -4.220000, track peak - 0.000007, album gain - unknown, album peak - unknown,
```
Seems like vorbisgain is the only one who read [the doc](https://wiki.hydrogenaud.io/index.php?title=ReplayGain_specification):
- the metadata must be in upper case
- mp3 files should use ID3v2 (it's ape by default with mp3gain)
- the gain must be with a "dB" prefix

Additionally, [`liquidsoap` seem to require a leading space in the metadata value](https://github.com/savonet/liquidsoap/blob/3350999c9efe447d8a226d59ffc061ce55004580/src/operators/amplify.ml#L47), in contradiction with [the doc](https://www.liquidsoap.info/doc-dev/reference.html#amplify).

The only way I see out of this madness, outside from fixing these tools/finding spec-compliant ones, would be to make the ` dB` prefix optional and the metadata name case insensitive. Since this is specific to `replaygain`, a new `replaygain` operator could be created as a `amplify` wrapper.

Bonus point if this operator supports preamp and clipping prevention as required by the spec. It could also be added as a note to use `amplify` in the doc.

What do you think?

**Comment by toots** [comment]
Hi,

The leading space should not matter:
```
# Scanf.sscanf "0.23 dB" " %f dB" (fun x -> Printf.printf "%f\n%!" x);;
0.230000
```

Are you aware of the `extract-replaygain` script that is distributed with `liquidsoap`: https://github.com/savonet/liquidsoap/blob/3350999c9efe447d8a226d59ffc061ce55004580/scripts/extract-replaygain ? It does exactly what you are describing, I believe.

**Comment by savonet-users** [comment]
Hi Romain,

Apologies for crashing this thread. I have been trying to get replay gain to work on my Debian setup without any luck. The last post to my ongoing thread (https://sourceforge.net/p/savonet/mailman/message/36622880/) went unanswered. I ran the test as suggested by Romain without luck but then again, I’m still learning about LS. I hope that someone can get me on the right track to get replaygain to work on my system.

Damian

**Comment by Yamakaky** [comment]
This script works if the corresponding binaries are installed. If instead the mp3 files use ID3v2, the values are present in the Metadata, which are easier to manipulate in liquidsoap and doesn't require any extra binary. It does however require the preprocessing to be done ahead of time.

**Comment by savonet-users** [comment]
Is there any documentation that clearly outlines which binaries to install and from where? Obviously, the reason why it’s not working for me is because I haven’t set this up correctly.

**Comment by Yamakaky** [comment]
I'm writing a script for that, please wait a few more hours ;)

**Comment by Yamakaky** [comment]
Here it is: https://gist.github.com/Yamakaky/0f0546ea0aeb4ed220caa82d814b7d68. This will create the REPLAYGAIN_TRACK_PEAK and GAIN (-a is not implemented). It should support any codec supported by ffmpeg. It must be run one time ahead of time.
In liquidsoap, a basic support is to use `amplify(1.0, override = "REPLAYGAIN_TRACK_PEAK", source)`. It however doesn't support pre-amp or clipping.
BTW, do you know why https://wiki.hydrogenaud.io/index.php?title=ReplayGain_specification#Reduced_gain uses a factor of 20? I thought 3dB = x2 amp, but with this formula it's more around 7dB.

**Comment by Yamakaky** [comment]
In fact, I was thinking of the power level ration of the signal with the amplitude ratio, which is used here.
https://en.wikipedia.org/wiki/Decibel

**Comment by Yamakaky** [comment]
@toots how would you implement the amp factor calculation? I was thinking about using on_metadata + a global ref per source, but that's not very clean and we may use an incorrect amp factor for a few frames at the beginning of the file. We also have to deal with overlapping sources, which may break this setup.

I was thinking of a modified amplify operator, something like `apply_replaygain(preamp: () -> float, limit_peak: bool = false)`. Would that play nice with sources transitions?

**Comment by savonet-users** [comment]
Hi, can i clarify, does this script provide the necessary binaries for the extract replaygain script that comes with liquidsoap? Also, will it provide me with what I need to apply gain to mp3 files?

**Comment by Yamakaky** [comment]
It replaces mp3gain and friends with only ffmpeg which you still need to install. Running the script will check if ffmpeg is present.

**Comment by savonet-users** [comment]
Why would I need ffmpeg instead of mp3gain? The extract-replaygain script seems to specifically require either mp3gain or replaygain for it to work. I can’t see any reference to ffmpeg



if (($file =~ /\.mp3$/i) || (test_mime() =~ /audio\/mpeg/))  {

  if (`which mp3gain`) {

    my $out = `mp3gain -q "$file" 2> /dev/null` ;
    $out =~ /Recommended "Track" dB change: (.*)$/m || die ;
    print "$1 dB\n" ;

  } elsif (`which replaygain`) {
    use_replaygain()
  } else {

    print STDERR "Cannot find mp3gain nor replaygain binaries!\n";

**Comment by Yamakaky** [comment]
Please reply from github, you will see my message edited ^^

**Comment by toots** [comment]
This script looks great @Yamakaky. I'm gonna reuse this work to simplify replaygain. Thanks!

**Comment by Yamakaky** [comment]
Thanks!

How would you implement the RG in .liq? If we do `amplify(1.0, "REPLAYGAIN_TRACK_GAIN", playlist(...)) `, would each track be amplified with its own factor? What it we add transitions between the tracks?

**Comment by toots** [comment]
I need to think about it. There are two possibilities:
- Replace the existing script with one based on your `ffmpeg` work
- Add a protocol which processes the track in the decoding stack and produces a pre-amplified track.

The second solution seems more useful as you wouldn't need to even have to think of using the `amplify` operator and etc. So I'll prolly go that direction.

**Comment by Yamakaky** [comment]
The only problem that may occur is that we should be able to configure if we want per album or per track (can be static), how we handle amplitude limiting (idem) and pre-amp (dynamic). Not sure if we can do the pregain with a protocol?

**Comment by toots** [comment]
Considering that the underlying architecture of liquidsoap is track-based, I believe that the best solution is a standard, per-track, implementation of the replay gain specifications. It should be only optionally enabled and anything beyond that would require the user to specify what they intent to do. Of course, it can and should be made as easy as possible to go beyond the simple standard.

**Comment by Yamakaky** [comment]
Some bugs I discovered with my scripts :
- wav doesn't have Metadata so it doesn't work
- ffmpeg can't write m4a Metadata
- the script doesn't handle covers (fixed in a newer version)
I think I will endup converting wav, m4a files to flac. Will release when the script will be more battle tested.
