### ISSUE TITLE
Add a noise gate operator

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#751]
https://en.wikipedia.org/wiki/Noise_gate

Since `compress` exists, this should not be to hard to implement.

**Comment by toots** [comment]
Sure thing. Looks like @smimram is in for it. You could also look at coding it if you're interested to learn how liquidsoap works under the hood..!

**Comment by autonarcosis** [comment]
Don't forget ladspa plugin abilities. There appears to be several ladspa gate plugins.

**Comment by gilou** [comment]
Indeed, I do have several places where I use it, such as
`ladspa.gate(s, threshold = -20.0, attack = 0.15, hold = 1.0, decay = 200.0, range = -25.0)`

**Comment by Yamakaky** [comment]
Could you provide the url for this plug-in? The doc doesn't mention it.

**Comment by gilou** [comment]
Sorry, it's an external one indeed from the famous [Steve Harris plugins](http://plugin.org.uk/ladspa-swh/docs/ladspa-swh.html) (swh-plugins package) :
```
$ liquidsoap -h ladspa.gate

Gate by Steve Harris <steve(at)plugin.org.uk>.

Type: (?id:string,?attack:'a,?decay:'b,?hf_key_filter:'c,
 ?hold:'d,?lf_key_filter:'e,?output_select:int,?range:'f,
 ?threshold:'g,source(audio='#h,video='#i,midi='#j))->
source(audio='#h,video='#i,midi='#j)
where
  'a, 'b, 'c, 'd, 'e, 'f, 'g is either float or ()->float

Category: Source / Sound Processing

Parameters:

 * id : string (default: "")
     Force the value of the source ID.

 * attack : anything that is either float or ()->float (default: 250.007507324)
     Attack (ms) (0.01 <= <code>attack</code> <= 1000).

 * decay : anything that is either float or ()->float (default: 2001.)
     Decay (ms) (2 <= <code>decay</code> <= 4000).

 * hf_key_filter : anything that is either float or ()->float (default: 21609.)
     HF key filter (Hz) (220.5 <= <code>hf_key_filter</code> <= 21609).

 * hold : anything that is either float or ()->float (default: 1500.5)
     Hold (ms) (2 <= <code>hold</code> <= 2000).

 * lf_key_filter : anything that is either float or ()->float (default: 30.8699989319)
     LF key filter (Hz) (30.87 <= <code>lf_key_filter</code> <= 4410).

 * output_select : int (default: 0)
     Output select (-1 = key listen, 0 = gate, 1 = bypass) (-1 <=
     <code>output_select</code> <= 1).

 * range : anything that is either float or ()->float (default: -90.)
     Range (dB) (-90 <= <code>range</code> <= 0).

 * threshold : anything that is either float or ()->float (default: -70.)
     Threshold (dB) (-70 <= <code>threshold</code> <= 20).

 * (unlabeled) : source(audio='#h,video='#i,midi='#j) (default: None)

```

**Comment by autonarcosis** [comment]
To further expand on the ladspa plugin feature.  This isn't by default. In opam you need to install the ladspa plugin feature for LS. You'll want to install the system ladspa and ladspa-devel packages, then opam install ladspa.  Opam wlll install the ladspa plugin and prompt to re-compile LS.  For my Fedora (and most likely RedHat type distros) the plugins are located in /usr/lib64/ladspa.

You'll know it's installed if LS responds positive with a liquidsoap --list-plugins | grep ladspa

To expand more on Yamakaky's recent posts. There is an automatic gain control ladspa plugin called vlevel.  I tested it out for about an hour and it appears to work.  The only thing I am not sure on is the placement of it in the audio path as I noticed the smartcross was acting differently (always default).

Forked version
https://github.com/radiocicletta/vlevel

Original version
http://vlevel.sourceforge.net/about/

**Comment by smimram** [comment]
Unstale.

**Comment by toots** [comment]
One file was missing from the commit..
