### ISSUE TITLE
Add "Question" template to Github Issues for liquidsoap

### ISSUE THREAD

**Issue by crackhd** [savonet/liquidsoap#752]
**Is your feature request related to a problem? Please describe.**
I cannot find a way to ask community a question regarding liquidsoap.

**Describe the solution you'd like**
Maybe it will be better to add Question type to allowed Github issue types on creation.

**Describe alternatives you've considered**
The other option is to directly ask random people.

**Additional context**
I expect this to be supported and [implemented by repository owner](https://help.github.com/en/articles/creating-issue-templates-for-your-repository). 

Casues:
- lack of "official community"
- "i am not a user, i am potential contributor if i will be able to blend in"

**Comment by toots** [comment]
Hi,

Thanks for this report. It's an interesting idea. There is a mailing list for for a while its use has blended with the use of github issues for support requests indeed. For that reason, github issues have been forwarded to the mailing list for a couple of months now.

Before implementing your idea I'd like to have a quick review of other potential tools to achieve the same goal. A chat channel is personally not an option. Are you or anybody reading this aware of other tools we could use to ove away from the sourceforge mailing list?

**Comment by crackhd** [comment]
Mixing questions/support style of communication with development communication _may be_ wrong idea. However, they are only option to make content indexed by Google.

Alternatives i can think of: 
- Slack workspace
- Discord server

They are similar and convenient messaging apps, but very different in user base. You can easily create sort of #support or #questions channel there as admin and anyone will be able to join and communicate.

**Comment by savonet-users** [comment]
The mailing list of my choice is groups.io for its ease of use and accessibility to screen readers.
Humberto

**Comment by toots** [comment]
Hey! We have a slack channel now! Click [here](https://join.slack.com/t/liquidsoapworkspace/shared_invite/enQtNjQyODQ1Mzg3NzY2LWMwYTYxZDVkMjNkMjQ4NzMzMTEzNDhkZmEyODEyMmYzZjc4ZWI2NzBlYWY4MDlmNzM5NGY5ZjAyZmY3OGI0ZGY) to join.
