### ISSUE TITLE
Distortion in ALL Opus streams

### ISSUE THREAD

**Issue by ivellios1988** [savonet/liquidsoap#759]
I already reported this issue to the AzuraCast developers (https://github.com/AzuraCast/AzuraCast/issues/1459) but after some investigation, their project manager told me that probably there's something wrong in Liquidsoap so I should report the issue here.

On my VPS, I'm using AzuraCast suite and running a couple of radio stations, currently mainly for the purposes of testing and checking out what AzuraCast has to offer. All of my stations use Liquidsoap and ALMOST all audio formats work very well, except OPUS.

I noticed a strange problem with OPUS streams. There appears a distortion which makes them sound like they were badly resampled from 44100 Hz to 48000 Hz without proper filtering. I recorded a sample to illustrate the issue:

left channel: OPUS 192kbps, 48000 Hz
right channel: MP3 128kbps, 44100 Hz

In the left channel, the distortion is very clearly audible, especially with sibilants.

[Untitled.Session.2_mixdown (1).zip](https://github.com/savonet/liquidsoap/files/3109743/Untitled.Session.2_mixdown.1.zip)

I also did a couple of other tests, among others, I was experimenting with changing sample rate in liquidsoap.liq. I changed samplerate from 48000 to 24000, then I changed permissions in order to prevent the file from being overwritten when Liquidsoap is restarted, and I restarted Liquidsoap. Audio bandwidth was cut to 24000 Hz, of course, but the distortion was still there.

Another test included creating two streams, one in OGG and the other in OPUS:

OGG: https://s.paranormalium.pl/radio/8020/ogg
OPUS: https://s.paranormalium.pl/radio/8020/opus

Audio bandwidth of the file being played by AutoDJ is 8000 Hz. In OGG stream the sound is clear, whereas in OPUS stream a heavy distortion is clearly audible.

I also tried playing files with sample rate of 48000, however, no success, the distortion was still present.

The distortion is present all the time in all OPUS streams I create.

**Comment by toots** [comment]
Hi,

Thanks for your report.

This quick test:
```
liquidsoap 'output.icecast(fallible=true,mount="bla.ogg",%ogg(%opus),playlist("~/music"))'
```
doesn't show any distortion on the audio. Could you share more about your script? A way to reproduce would be great.

**Comment by ivellios1988** [comment]
My settings in liquidsoap.liq look like this:

[code]output.icecast(%opus(samplerate=48000, bitrate=192, vbr="none", application="audio", channels=2, signal="music", complexity=10, max_bandwidth="full_band"), id="do_zabawy_local_1", host = "127.0.0.1", port = 8020, password = "REMOVED", mount = "/opus", name = "do zabawy", description = "", genre = "", public = false, encoding = "UTF-8", radio)

output.icecast(%vorbis.cbr(samplerate=44100, channels=2, bitrate=192), id="do_zabawy_local_2", host = "127.0.0.1", port = 8020, password = "REMOVED", mount = "/ogg", name = "do zabawy", description = "", genre = "", public = false, encoding = "UTF-8", radio)[/code]

**Comment by ivellios1988** [comment]
Steps to reproduce:

1) Login to AuraCast panel via https://s.paranormalium.pl/

email: radio-passreset@paranormalium.pl
password: Z7kaAi4sDqqtCUr

2) create a mountpoint with OPUS and another one in OGG/AAC/MP3 (already done)

3) create an playlist and put some audio file in it (already done)
You may also start broadcasting to the server, using credentials given on homepage after you log in.

4) start Icecast and Liquidsoap, listen to both streams and check if the distortion in OPUS stream is present

The distortion in OPUS is clearly audible regardless of settings.

**Comment by autonarcosis** [comment]
Opus is way different from the encoders of the past.  Opus outputs to 48khz samplerate only. The max_bandwidth setting sets 'effective' sample rates for the decoder. The samplerate configuration in LS is for the input audio source and not the output. I'd recommend keeping the default (I think it's 24000) or setting it to 48000.  The 'wideband' setting is an effective samplerate of about 16khz as per the Opus RFC specs.
What operating system is the VPS? What version of LS are you using. What versions of the libsamplerate and libopus is the VPS using?  The most recent libopus version 1.3.1 was released earlier this month.  The most recent version of LS is v1.3.6.

**Comment by ivellios1988** [comment]
System: Ubuntu 18.04.2 LTS

libopus: not sure but I found "libopus.so.0.5.2"

libsamplerate: couldn't find exact version, I only found a file named "libsamplerate_converter.ml"

**Comment by autonarcosis** [comment]
From searching google you can issue to see the package versions;
`$ apt-cache policy <package-name>`

It appears for v18.04.2 that libopus is v1.1.2. and Liquidsoap package is v1.1.1.

These are quite old versions. I highly recommend to install the latest Liquidsoap via opam to start with.

**Comment by ivellios1988** [comment]
Even though AzuraCast makes use of Liquidsoap, "apt-cache policy liquidsoap" gives me information that LS is not installed. Apparently AzuraCast uses some non-standard locations for libraries.

apt-cache policy couldn't find libsamplerate and libopus as well.

**Comment by autonarcosis** [comment]
This is a bit beyond the scope of what I can provide. It appears that you maybe using the Docker version of AzuraCast.  I'd recommend installing Liquidsoap via opam independently on the VPS and test it with a simple script to see if you get the same results. If you are using the Docker install version, I'd recommend trying the Ubuntu bare-metal install of AzuraCast.

**Comment by Vaalyn** [comment]
Hey, I'm one of the maintainers of AzuraCast and wanted to provide some informations about our LS setup here. This is how we install LS and the other components for it in our Docker container:

```
ARG opam_packages="taglib.0.3.3 mad.0.4.5 faad.0.4.0 fdkaac.0.2.1 lame.0.3.3 vorbis.0.7.1 cry.0.6.1 flac.0.1.4 opus.0.1.2 duppy.0.8.0 ssl liquidsoap.1.3.7"

RUN opam init --disable-sandboxing -a \
    && opam install -y ${opam_packages}

...

RUN ln -s /var/azuracast/.opam/default/bin/liquidsoap /usr/local/bin/liquidsoap
```

**Comment by toots** [comment]
Hi,

I still cannot reproduce with your settings. I'm using `libopus` version `1.3` here. My first recommendation would be to upgrade your `libopus`. `liquidsoap` has very few knowledge of what `opus` does so it's very likely that your bug is with the library and not us.

**Comment by toots** [comment]
Hi @Vaalyn! Good to hear from one of y'all! I'll keep your contact handy in case we need to reach out!

**Comment by Vaalyn** [comment]
@toots Would probably be the best first step to make sure we have the newest version of libopus then. I'll get to that and maybe @ivellios1988 you could test if an update to that fixed the problem then. I'll let both of you know when we've updated that lib.

**Comment by ivellios1988** [comment]
Ok, I'm looking forward for the update.

**Comment by ivellios1988** [comment]
By the way, this is what 'apt-cache policy libopus-dev' returns on my VPS:

libopus-dev:
  Installed: (none)
  Candidate:   1.1.2-1ubuntu1
  Version table:
     1.1.2-1ubuntu1 500
        500 http://nova.clouds.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Comment by Vaalyn** [comment]
@ivellios1988 That's probably because you are using our Docker installation and you are executing the `apt-cache policy libopus-dev` in the ssh session of your host VPS not from inside the `azuracast_stations` container, which is where LS is installed.

**Comment by ivellios1988** [comment]
Ok, I finally started learning how to use Docker containers:

docker exec -it azuracast_stations apt-cache policy libopus-dev
libopus-dev:
  Installed: 1.1.2-1ubuntu1
  Candidate: 1.1.2-1ubuntu1
  Version table:
 *** 1.1.2-1ubuntu1 100
        100 /var/lib/dpkg/status

**Comment by Vaalyn** [comment]
@toots After upgrading to libopus 1.3.1 (together with liquidsoap 1.3.7) the problem still persists. I've also created a small re-encoding script on my local dev installation docker container to see if there is anything in our application that could be effecting the process. The distortion issue is still happening with that script.

```
apt-cache policy libopus-dev
libopus-dev:
  Installed: 1.3-1
  Candidate: 1.3-1
  Version table:
 *** 1.3-1 990
         10 http://archive.ubuntu.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.2-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

Here is the script that I used for my local tests:
```
input = "/var/azuracast/stations/azuratest_radio/media/.mp3"

output = "/var/azuracast/stations/azuratest_radio/media/output.ogg"

source = once(single(input))

clock.assign_new(sync=false, [source])

output.file(
    %opus(
        samplerate=48000,
        bitrate=96,
        vbr="none",
        application="audio",
        channels=2,
        signal="music",
        complexity=10,
        max_bandwidth="full_band"
    ),
    output,
    fallible=true,
    on_stop=shutdown,
    source
)
```

I have tried using just `%opus` without any configuration and with the config above. Both producing the same distorted output. The source I used is a 44100 encoded 128kbps mp3 file. I've also tried if there is any difference when using a 48000 source but that results in no change in the output quality.

To make sure that this problem is not coming from the file itself I tried a random generic mp3 re-encoder I found on the web and the opus file from that sounds much better with the same configs.

I'll add a .zip file with my test source and output files for you.

Here is the log produced by executing the script:
```
2019/05/03 09:32:06 >>> LOG START
2019/05/03 09:32:06 [main:3] Liquidsoap 1.3.7
2019/05/03 09:32:06 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.4.1 dtools=0.4.1 duppy=0.8.0 cry=0.6.1 mm=0.4.0 ogg=0.5.2 vorbis=0.7.1 opus=0.1.2 mad=0.4.5 flac=0.1.4 flac.ogg=0.1.4 dynlink=[distributed with Ocaml] lame=0.3.3 fdkaac=0.2.1 taglib=0.3.3 ssl=0.5.7 camomile=1.0.1 faad=0.4.0
2019/05/03 09:32:06 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/azuratest_radio/media/03_-_time_to_be_awesome.mp3".
2019/05/03 09:32:06 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.
2019/05/03 09:32:06 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2019/05/03 09:32:06 [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2019/05/03 09:32:06 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2019/05/03 09:32:06 [threads:3] Created thread "generic queue #1".
2019/05/03 09:32:06 [threads:3] Created thread "generic queue #2".
2019/05/03 09:32:06 [threads:3] Created thread "non-blocking queue #1".
2019/05/03 09:32:06 [threads:3] Created thread "non-blocking queue #2".
2019/05/03 09:32:06 [single_6389:3] "/var/azuracast/stations/azuratest_radio/media/03_-_time_to_be_awesome.mp3" is static, resolving once for all...
2019/05/03 09:32:06 [threads:3] Created thread "wallclock_sequence_6391" (1 total).
2019/05/03 09:32:06 [clock.wallclock_sequence_6391:3] Streaming loop starts, synchronized by active sources.
2019/05/03 09:32:06 [single_6389:3] Prepared "/var/azuracast/stations/azuratest_radio/media/03_-_time_to_be_awesome.mp3" (RID 0).
2019/05/03 09:32:09 [single_6389:3] Finished with "/var/azuracast/stations/azuratest_radio/media/03_-_time_to_be_awesome.mp3".
2019/05/03 09:32:09 [/var/azuracast/stations/azuratest_radio/media/output(dot)ogg:3] Source failed (no more tracks) stopping output...
2019/05/03 09:32:09 [main:3] Shutdown started!
2019/05/03 09:32:09 [main:3] Waiting for threads to terminate...
2019/05/03 09:32:09 [threads:3] Shuting down thread wallclock_sequence_6391
2019/05/03 09:32:09 [clock.wallclock_sequence_6391:3] Streaming loop stopped.
2019/05/03 09:32:09 [threads:3] Thread "wallclock_sequence_6391" terminated (0 remaining).
2019/05/03 09:32:09 [main:3] Threads terminated.
2019/05/03 09:32:09 [threads:3] Shutting down scheduler...
2019/05/03 09:32:09 [threads:3] Scheduler shut down.
2019/05/03 09:32:09 [threads:3] Shutting down queues...
2019/05/03 09:32:09 [threads:3] Thread "generic queue #1" terminated.
2019/05/03 09:32:09 [threads:3] Thread "generic queue #2" terminated.
2019/05/03 09:32:09 [threads:3] Thread "non-blocking queue #2" terminated.
2019/05/03 09:32:09 [threads:3] Thread "non-blocking queue #1" terminated.
2019/05/03 09:32:09 [threads:3] Queues shut down
2019/05/03 09:32:09 [main:3] Cleaning downloaded files...
2019/05/03 09:32:09 [main:3] Freeing memory...
2019/05/03 09:32:09 >>> LOG END
```

**Comment by ivellios1988** [comment]
@SlvrEagle23 suggests that there may be something wrong with the ocaml audio connector or with the OPUS encoder itself.

https://github.com/AzuraCast/AzuraCast/issues/1459

**Comment by toots** [comment]
I listened to your files. There's a clear audio degradation on the `48k_source_output.ogg`. The `41k_source_output.ogg` does not appear to have a comparably obvious distorsion.

Could you explain what I should be listening for more specifically?

I tested with the `savonet/liquidsoap-full` docker container. Here's a link to the generated file: https://www.dropbox.com/s/0bqs71iuot00cpq/toots.ogg?dl=0

How does my file test for you? It sounds fine to me.

**Comment by ivellios1988** [comment]
@toots For some reason I can't download your file - it says "File is uploading..."

**Comment by toots** [comment]
Try this one: https://www.dropbox.com/s/9h3sg5rv8krl399/toots.ogg?dl=0

**Comment by ivellios1988** [comment]
Anyway, in `41k_source_output.ogg` the degradation may not be as clearly audible - but the distortion is clearly present. It becomes more audible when we compare both files in audio editor.

In this attachment: left channel is OPUS (with noticeable hiss), right channel is the original file. 
[distortion_comparison.zip](https://github.com/savonet/liquidsoap/files/3142656/distortion_comparison.zip)

And this is what can be seen when we open `41k_source_output.ogg` in editor and switch to spectral frequency display: 
![41_distortion](https://user-images.githubusercontent.com/13646017/57150055-80509a00-6dcd-11e9-81bf-744e1eedaf43.png)

For comparison, this is the spectral view of the original file: 
![original](https://user-images.githubusercontent.com/13646017/57150102-a4ac7680-6dcd-11e9-89cf-d7b99f48d6fc.png)

Just listened to your file @toots - it sounds (and looks) fine: 
![toots](https://user-images.githubusercontent.com/13646017/57150228-010f9600-6dce-11e9-91b0-40290d99459c.png)

**Comment by toots** [comment]
Ok. Then I believe the next step is to double check what version of the `libopus` your liquidsoap binary is linked with. Here's mine:
```
% ldd /usr/local/bin/liquidsoap
...
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f4f3ee58000)
....
```
Then, on a debian system, you can do:
```
% dpkg -L libopus0
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libopus.so.0.6.1
/usr/share
/usr/share/doc
/usr/share/doc/libopus0
/usr/share/doc/libopus0/changelog.Debian.gz
/usr/share/doc/libopus0/copyright
/usr/lib/x86_64-linux-gnu/libopus.so.0
```
So we're effectively using the debian packaged `libopus`. Finally:
```
% apt-cache show libopus0
Package: libopus0
Source: opus
Version: 1.3-1
Installed-Size: 383
Maintainer: Ron Lee <ron@debian.org>
Architecture: amd64
Depends: libc6 (>= 2.14)
Suggests: opus-tools
Description: Opus codec runtime library
Description-md5: 1155b70f2f801c41248e2e9c555bc1df
Multi-Arch: same
Homepage: http://www.opus-codec.org
Tag: role::shared-lib
Section: libs
Priority: optional
Filename: pool/main/o/opus/libopus0_1.3-1_amd64.deb
Size: 191080
MD5sum: 1feb55101b70f008e3b1968fb2005dca
SHA256: 78d2d72932f9749012cf356e8699f5f56c4a707eeb1f18c44b59928af7ac5876
```
Which gives us the version used for `libopus`.

**Comment by Vaalyn** [comment]
@toots @ivellios1988 The first test where I created the files were done with the stations container from AzuraCast (see other posts for version numbers).

I also tested this on the `savonet/liquidsoap-full` docker container that you mentioned and there the resulting opus file does not have that distortion in it: [output.ogg.zip](https://github.com/savonet/liquidsoap/files/3142713/output.ogg.zip)

The image uses Liquidsoap 1.3.4 and libopus 1.3~beta+20180518-1 so this is most likely a problem with our setup then. Here is the list of opam packages that we install:
```
taglib.0.3.3 mad.0.4.5 faad.0.4.0 fdkaac.0.2.1 lame.0.3.3 vorbis.0.7.1 cry.0.6.1 flac.0.1.4 opus.0.1.2 duppy.0.8.0 ssl liquidsoap.1.3.7
```

[Here](https://github.com/AzuraCast/docker-azuracast-radio/blob/master/Dockerfile) the link to our dockerfile so you can see the whole environment we use.

-------

Additional debug output:

```
ldd /usr/local/bin/liquidsoap
	linux-vdso.so.1 (0x00007ffe1d757000)
	libfaad.so.2 => /usr/lib/x86_64-linux-gnu/libfaad.so.2 (0x00007f376ebde000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f376e840000)
	libtag.so.1 => /usr/lib/x86_64-linux-gnu/libtag.so.1 (0x00007f376e56a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f376e1e1000)
	libfdk-aac.so.1 => /usr/lib/x86_64-linux-gnu/libfdk-aac.so.1 (0x00007f376df29000)
	libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f376dcb2000)
	libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f376da3b000)
	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f376d832000)
	libmad.so.0 => /usr/lib/x86_64-linux-gnu/libmad.so.0 (0x00007f376d612000)
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f376f9fe000)
	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f376d3e7000)
	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f376d13e000)
	libvorbisfile.so.3 => /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007f376cf36000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f376cccc000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f376c854000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f376c5e2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f376c3c3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f376c1bf000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f376bfa7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f376bbb6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f376f83c000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f376b7ff000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f376b5e2000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f3769a39000)
```

```
dpkg -L libopus0
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libopus.so.0.7.0
/usr/share
/usr/share/doc
/usr/share/doc/libopus0
/usr/share/doc/libopus0/changelog.Debian.gz
/usr/share/doc/libopus0/copyright
/usr/lib/x86_64-linux-gnu/libopus.so.0
```

```
apt-cache show libopus0
Package: libopus0
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 383
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: opus
Version: 1.3-1
Depends: libc6 (>= 2.14)
Suggests: opus-tools
```

**Comment by toots** [comment]
The ogg encoder in liquidsoap will resample its data if needed. Have your installed `libsamplerate`? If not that could be the source of the issue here.

**Comment by Vaalyn** [comment]
@toots That lib is indeed not installed in our container. I'm currently rebuilding it locally and will then test again.

**Comment by autonarcosis** [comment]
I want to chime in here and say again. There is no such thing as a 44.1khz opus file. The encoder does not support that sample rate. The DECODER will resample to the best available samplerate that the hardware supports. The information stored in the file is the SOURCE sample rate.

libsamplerate should probably be a requirement for the Opus codec within LS.

To further note, your Tests.zip files. The external opus file is in fact a Vorbis audio codec file.

**Comment by toots** [comment]
Thanks for these remarks. Liquidsoap will issue an error if `samplerate` is not one of the support one for the `%opus` encoder:
```ocaml
          | ("samplerate",({ term = Int i; _} as t)) ->
              let samplerates = [8000;12000;16000;24000;48000] in
              if not (List.mem i samplerates) then
                raise (Error (t,"Opus samplerate should be one of \
                                 8000, 12000, 16000, 24000 or 48000"));
              { f with Opus_format.samplerate = i }
```

**Comment by Vaalyn** [comment]
@autonarcosis I didn't mean to imply that the output was 44.1 just the input file, to see if there is any difference if the source is different.

Thank you for the info about the external file, I didn't double check the file that the online encoder produced as there was just an opus button. Will look for a different online encoder to check that again.

@toots I installed `libsamplerate` now in our container and re-encoded the original again, it seems better but there is still something off with the voice: [output.ogg.zip](https://github.com/savonet/liquidsoap/files/3142887/output.ogg.zip)

**Comment by ivellios1988** [comment]
@Vaalyn actually there's still a lot of distortion there

![Bez tytułu](https://user-images.githubusercontent.com/13646017/57155936-fc9ea980-6ddc-11e9-93f0-4f450d3e7b85.png)

**Comment by SlvrEagle23** [comment]
@toots Hello! Other AzuraCast dev here. You already have my contact information but I just wanted to drop in and note I'm keeping an eye on this issue as well. Thank you for helping us work out this issue.

Is the source `Dockerfile` for the `savonet/liquidsoap-full` image available anywhere that we could see? I want to make sure we're as close to parity on that as we can be, but I don't want to directly inherit from that image, as it's not tagged with individual LS versions but instead just uses a "latest" tag that would introduce some unpredictability into our build process.

We can definitely add `libsamplerate` and should, especially since our users are clamoring for us to support new and exciting sample rates that aren't 44.1 (or, for OPUS, 48) kHz. I'm not sure what else differentiates our setup from the main `full` image, though.

**Comment by SlvrEagle23** [comment]
@toots Never mind, I found it: https://github.com/savonet/liquidsoap-full/blob/master/docker/Dockerfile.full

We won't be able to update anything today on account of the Docker Hub going "read-only" all day to deal with their little security incident from earlier, but we'll dig into it and do a better comparison between the two shortly.

**Comment by toots** [comment]
Hi @SlvrEagle23! I wouldn't recommend doing exactly the same as the `full` image as this image is intended to have every single optional module enabled.. I do believe, however, that `libsamplerate` is the solution to this issue.

**Comment by SlvrEagle23** [comment]
@toots Myself and @Vaalyn played with things a little further and realized that when we originally included `libsamplerate` we didn't also include the corresponding OCaml connector for it. Once that was included as well, it appears the issue has gone away. As soon as we can, we'll get updated Docker images up that include the fix. Thanks again for your help! :)

**Comment by toots** [comment]
Very happy to hear that!

**Comment by ivellios1988** [comment]
Great! Can't wait for the update :)
