### ISSUE TITLE
Dynamic getters for settings

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#760]
`get(default, setting_name)` returns a float, is there a reason for not it being a `float | ()->float`? I plan to use them for dynamic settings like the limiter parameters, since `dynamic.float` requires the use of `server.execute("var.set <key> = <val>")`.

**Comment by toots** [comment]
Hi!

For such use, you should go with variable reference:
```
x = ref 10.0

print("Value of x: #{!x}")

x := 20.

print("value of x: #{!x}")
```

**Comment by toots** [comment]
You can make a callback with it if that fits your use better:
```
cb = fun () -> !x
```

**Comment by Yamakaky** [comment]
I'm hesitant to use references since I have 10+ variables, so I would have to create 10+ harbor endpoints... 

If I want to use a dynamic amplify factor, should I use raw dereference or a callback?

The ! operator isn't mentioned in the language reference?

**Comment by smimram** [comment]
Right! `!` is now  mentioned: https://github.com/savonet/liquidsoap/commit/ea6dcbae23f3bada5d83b796bb302b76dd169f55
