### ISSUE TITLE
[Question/Feature request] Pull YouTube Playlist as input

### ISSUE THREAD

**Issue by nemesis64** [savonet/liquidsoap#761]
Is there a way to pull a youtube playlist as an input source in liquidsoap? right now i have to use youtube-dl and bash to check for new videos and download them in a directory,. So is there a way to pull a youtube playlist automatically and sync it within liquidsoap?

**Comment by smimram** [comment]
`youtube-dl -g http://youtube/playlist` gives a list of urls of the videos in the playlist, which you should be able to use as a regular playlist.

**Comment by savonet-users** [comment]
On Sun, 28 Apr 2019, 22:37 Samuel Mimram, <notifications@github.com> wrote:

> youtube-dl -g http://youtube/playlist gives a list of urls of the videos
> in the playlist, which you should be able to use as a regular playlist
>
I regularly package youtube-dl; and its authors do a good job of tracking a
moving target. For example, something in YouTube's pages changed only a day
or so ago.
JW

>

**Comment by toots** [comment]
I believe you can try:
```
s = playlist("youtube-dl:http://youtube/playlist")
```

It might even work with just:
```
s = playlist("youtube-dl:<playlistID>")
```

**Comment by nemesis64** [comment]
Thank you so much!
Is there a way to sync the playlist without using an external program/script though? that's another one of my concerns

**Comment by nemesis64** [comment]
When i put ``playlist("youtube-dl:http://path/to/youtube/playlist")`` It gets processed but the stream is dead silent.

**Comment by nemesis64** [comment]
followed @smimram 's answer, cant't get it to work, throws a ``SSL: rejecting connection - error=20``

here's a full log of it:

```
2019/04/29 03:29:06 [procol.external:4] Request response: (((("Internal error",999),"Internal error"),[]),"Error while processing request: Timed out after waiting for 19.99 sec.")
2019/04/29 03:29:06 [procol.external:3] No known file extension for mime: 
2019/04/29 03:29:06 [procol.external:4] Fetching https head for <path to raw youtube stream>
Certificate[1] subject=/C=US/O=Google Trust Services/CN=Google Internet Authority G3
Certificate[1] issuer =/OU=GlobalSign Root CA - R2/O=GlobalSign/CN=GlobalSign
SSL: rejecting connection - error=20

```

**Comment by toots** [comment]
Yeah I talked too quickly. I wanted to add support for this back when `youtube-dl:` protocol was added but dropped it. I believe it was too annoying at the moment. I'll have another look at it.

**Comment by toots** [comment]
Done! 🎉

**Comment by toots** [comment]
`playlist("youtube-pl:RD1zWlnzFXcKY")` should work with the latest `master` now! Note: `youtube-pl`, not `youtube-dl`!
