### ISSUE TITLE
[Question/Need help] exit function

### ISSUE THREAD

**Issue by alexandre1985** [savonet/liquidsoap#763]
I want to exit a function when certain condition is met.

That function is returning an audio source so, I don't know, maybe if that condition is met I should return a null audio source.

Can someone tell me if I'm thinking right and how I can do this?

And does LiquidSoap scripts accept OCaml language commands inside the scripts?

Thank you, keep it up!

**Comment by toots** [comment]
Hi,

Since liquidsoap is functional and statically typed, each branch of your conditional executions need to return a value of the same type.

If you show us some code we might be able to help further.

I'm closing the issue but we can continue the discussion here or on the mailing list.

**Comment by alexandre1985** [comment]
Here is my code:
```
def rec youtube_live(ytid) =

	json = get_process_output("youtube-dl -j https://youtu.be/#{ytid}")

	is_live = bool_of_string(string.trim(get_process_output("echo '#{json}' | jq '.is_live'")))

	if is_live == false then
		msg = "ERROR: The youtube id '#{ytid}' is not a live stream."
		log(msg)
		print(msg)
		# I want to exit this function here - dont know how to
	end

	url = string.trim(get_process_output("echo '#{json}' | jq '.formats | .[] | select(.format_id == \"93\") | .url'"))
	title = string.trim(get_process_output("echo '#{json}' | jq -r '.fulltitle'"))
	uploader = string.trim(get_process_output("echo '#{json}' | jq -r '.uploader'"))

	
	def add_title(m)
		[("title","[YouTube] #{title}"),("artist","#{uploader}")]
	end
	
	video_source = gstreamer.hls(url)
	
	audio_source = drop_video(video_source)
	
	audio_source = map_metadata(strip=true, add_title, audio_source)
	
	fallback(track_sensitive=false, [audio_source, youtube_live(ytid)])
end

```

**Comment by toots** [comment]
How is the function used? (Also: do you need the recursion on it?)

**Comment by alexandre1985** [comment]
this function is used as a way to return an audio source.
For example you could use `youtube_live("hHW1oY26kxQ")` and it would return an audio source from youtube live for you to use in liquidsoap.

The recursion is needed because the `url` variable (that is fetched using `youtube-dl` command) is a `.m3u8` URL that expires after 6 hours. It seems that youtube does give an expiration time for it's `.m3u8` URLs.
What happens is that, after 6 hours, I get a Forbidden HTTP status (I believe is a 403) error.
Recursion is a way to fetch a new youtube `.m3u8` URL.

I have posted the gstreamer Forbidden status issue in here https://github.com/savonet/liquidsoap/issues/762

**Comment by toots** [comment]
Yeah, you would need to think about how you will structure your script in the case when the source cannot be created. Is that a source created dynamically on-demand?

**Comment by alexandre1985** [comment]
@toots yes, the source is created by receiving one `.m3u8` URL from `youtube-dl`.

Can you help me improve this function in case the source cannot be created?
If not, what would I need to do?
