### ISSUE TITLE
Documentation for compress.exponential

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#766]
I can't find any mention of exponential compression out of liquidsoap. Where does it come from and what are its weak and strong points compared to a regular compressor? 

From what I understand, you lose on configurability of the response curve (all the curve is modified instead of after threshold + knee) , but it seems more smooth and responsive during the "attack phase". Combined with amplify, it could provide a reliable limiter.

**Comment by Yamakaky** [comment]
Also, I assume the samples are in a -1 < x < 1 format, so a data point with max amplitude isn't modified?

**Comment by smimram** [comment]
It is quite different from a regular compressor: a compressor changes the volume depending on the past mean volume. This `compressor.exponential` roughly changes a sample `x` (between -1 and 1) into `1-(1-x)^n` where `n` is typically 2. This means that the sample has a tendency to get pushed toward 1 (or -1 if it was negative). For instance, with n=2, you get
```
0.2 -> 0.36
0.4 -> 0.64
0.6 -> 0.84
0.8 -> 0.96
```
The higher the n is the higher the effect is (n=1 means no effect). So, intuitively, it acts as a compressor which makes the sound take the full range for samples. However, the function being non-linear, there is also a distortion in the spectrum, so I would do some testing before using it :)

**Comment by Yamakaky** [comment]
OK, thanks, will do!

Does it come from somewhere else or was it invented here?
