### ISSUE TITLE
scrobbler lastfm

### ISSUE THREAD

**Issue by cheleentano** [savonet/liquidsoap#772]
Hi, everybody. Sorry for my bad English. Who has a working lastfm Scrobbler. Share please.

**Comment by smimram** [comment]
There are functions such as `lastfm.submit` in the [standard library](https://github.com/savonet/liquidsoap/blob/master/lib/lastfm.liq).

**Comment by cheleentano** [comment]
> There are functions such as `lastfm.submit` in the [standard library](https://github.com/savonet/liquidsoap/blob/master/lib/lastfm.liq).

Я не пойму как ей пользоваться. Есть мануал какой нибудь по использованию?

**Comment by savonet-users** [comment]
This works for me. In the last line, add your username and password for lastfm.


def lastfm.submit(~user,~password,~source="broadcast",~length=false,m) =
audioscrobbler.submit(user=user,password=password,
source=source,length=length,
host="post.audioscrobbler.com",port=80,
m)
end

radio = on_metadata(lastfm.submit(user=“ADD_USER_NAME_HERE",password=“ADD_PASSWORD_HERE"), radio)

**Comment by cheleentano** [comment]
Thank you very much, everything works

**Comment by savonet-users** [comment]
Glad to help
