### ISSUE TITLE
FDK-AAC Cutoff (Low pass) Frequency Too Low (14kHz)

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#773]
It seems in CBR mode the cutoff frequency is being fixed to the library default of 14k? (Should be 17k)
With vbr=5 this cutoff is not imposed (as per the spec) however there is no ability to set a cutoff within liquidsoap's encoder settings to force the lowpass value. So even very high bitrates like 320kbps have very low cut-offs.
Is it possible to get a new encoding parameter to force the position of this lowpass?

**Comment by autonarcosis** [comment]
Do you have an example configuration? What version of the fdk-aac library are you using? The latest version commonly used in Linux is v2.0. I am currently using v1.6 and not having any obvious cut off issues using ffplay or VLC players.  I did have problems with older versions.

https://github.com/mstorsjo/fdk-aac

From what I interpret there are no defaults to the cutoff frequency. It's based on the bit rate that is set or the VBR mode that is set.  For CBR it states 96kbps and above is 17000Hz.  From what I understand  this cut off is dependent on SBR being enabled to reproduce the higher frequencies. This is dependent on the decoder side as well. You'll want afterburner and sbr set to true in liquidsoap (I believe SBR is set to true by default).
Unless you are doing multiple channels like 5.1/7.1, AAC 320kbps is kind of moot point and you should look towards FLAC.

**Comment by toots** [comment]
I agree with @autonarcosis here. However, since the `bandwidth` parameter was missing I added it. You'll need both the latest `liquidsoap` and `ocaml-fdkaac` master.

**Comment by dhannyz** [comment]
Yes i understand it should be 17k by default. I had reports from a listener of there looking like a cutoff at 15k (this was likely the source file)

Not sure why you would suggest using SBR (AAC+/HE-AAC) however. Seems like a bunch of extra steps to achieve a similar goal as just setting the bandwidth parameter correctly. As SBR will first encode in LC at 1/2 sample rate (thus max frequency info will be 1/4 real samplerate, 48kHz -> 12kHz) then use SBR bits on the decoder side to 'reconstruct' the higher frequency info, useful for low bitrate stuff, sure... However more intensive for the decoder and as I do choose to transmit in 320k I can afford to raise the bandwidth cutoff.
Interesting if SBR is indeed enabled by default, and would be news to me, It is disabled in ffmpeg by default.

I do not see the point in streaming in ogg/flac, at least doubling the required bandwidth with no apparent quality difference to fdk_aac (or any other encoder at 320k tbh) with a correctly set bandwidth parameter...

The choice of fdkaac over vorbis (and other ogg encapsulated encodings) was due to bugs/issues in how browsers decode chained ogg, in particular when piped into the webaudio api (i seem to get timestamp desyncs). 

The main reason for wanting to set it higher is that there is a noticeable difference between my fdkaac streams and my equivalent ogg/vorbis streams, and also to mirror my settings in my DASH configuration.

```
-c:a:0 libfdk_aac -cutoff 20000 -b:a:0 320k \
-c:a:1 libfdk_aac -cutoff 19000 -b:a:1 256k \
-c:a:2 libfdk_aac -cutoff 18000 -b:a:2 192k \
-c:a:3 libfdk_aac -cutoff 18000 -b:a:3 128k \
-c:a:4 libfdk_aac -cutoff 17000 -b:a:4 96k \
```
Now at low bitrate dash options there is a valid reason to use HE / SBR and I shall look into that.

@toots thanks for making that parameter available, i will look into building from master, however i did have issues a couple days ago due to something to do with an incorrect return type in sedlexing_compat
I was using an opam pin, is there some other dependency i also need to pin for this to build successfully?

**Comment by toots** [comment]
@dhannyz Not sure. The `configure` script should tell you what version are required for dependencies now. If that version hasn't been released then it's most certainly a pin. `sedlex` isn't pinned though.
