### ISSUE TITLE
about removing of cross/crossfade operators in 1.4.2 - alpha 2

### ISSUE THREAD

**Issue by aliv** [savonet/liquidsoap#774]
**Is your feature request related to a problem? Please describe.**
currently i'm using cross and i specify liq_start_next in metatag based on genre, type and duration of **current and next** track to have smooth cross -and maybe no cross- and i don't find smart_cross on some cases smooth to use it. 

actually my question is:
- why cross and crossfade functions are removed? i think this is good idea to control cross duration per track.

**Describe the solution you'd like**
also i found minimum parameter in smart_cross and it is useful but it seems it only consider duration of current track. so what if next track is short and we don't want cross between current and next track.?

i think this is good idea to have a meta per track like -do_smart_cross=0 or 1- to decide if there should be a cross with next track or not.

**Comment by toots** [comment]
Hi,

The old `cross`/`crossfade` operators are superseeded by `smart_cross`/`smart_crossdade`. Most of the functionalities of the old operators should be replicable with the new one.

In particular, the `liq_start_next` functionality has been added to the `smart_cross` operators but renamed `liq_cross_duration`

You should be able to write your own crossfading function and decide in it what kind of transition you want to apply using metadata and etc.

**Comment by savonet-users** [comment]
On Sun, 12 May 2019, 23:00 Romain Beauxis, <notifications@github.com> wrote:

> Hi,
>
> The old cross/crossfade operators are superseeded by smart_cross/
> smart_crossdade. Most of the functionalities of the old operators should
> be replicable with the new one.
>
> In particular, the liq_start_next functionality has been added to the
> smart_cross operators but renamed liq_cross_duration
>
> You should be able to write your own crossfading function
>
Exactly this form of use has been running on my server continuously for
some weeks now.
JW

>
