### ISSUE TITLE
AutoDJ stops at random times and needs to be restarted

### ISSUE THREAD

**Issue by bp7000** [savonet/liquidsoap#776]
Greetings,

As the title states, my AutoDJ keeps stopping at random times. I am running Liquidsoap 1.3.3 which was bundled with the latest version of Centova Cast. I tried following the steps in post [#678](https://github.com/savonet/liquidsoap/issues/678), but hitting a wall when getting to the ./bootstrap part. I keep getting this error: which: no gsed in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/user/.lo
cal/bin:/home/user/bin). Seems to be the same exact issue as discussed in the mentioned post above, and looks like I just need to update the liquidsoap portion of my centova cast without affecting the whole program. Am I missing something simple here? I'd like to fix this on my own, and maybe you can guide me with a simpler solution to do so. Anyways, thanks in advance and hopefully I'll get this resolved some day. FYI, the OS this is running on is Centos 7.

**Comment by autonarcosis** [comment]
Install it using opam and not the tar source package.

https://www.liquidsoap.info/doc-1.3.6/install.html

I recommend adding to the basic install fdkaac, flac and opus. So it'd be something like; 

opam depext taglib mad lame vorbis cry samplerate fdkaac flac opus liquidsoap
opam install taglib mad lame vorbis cry samplerate fdkaac flac opus liquidsoap

If you need other dependencies later, you can just use open install <dependency> and opam will recompile liquidsoap.
