### ISSUE TITLE
Failing to compile fdkaac_encoder.ml

### ISSUE THREAD

**Issue by RecursiveGreen** [savonet/liquidsoap#777]
**Describe the bug**
I'm attempting to compile the latest liquidsoap from git using opam. I'm getting an error with fdkaac:
```
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(git+file:///home/josh/Development/liquidsoap-dev#add-aws-endpoint-url#f88c2e61)
# path        ~/.opam/default/.opam-switch/build/liquidsoap.dev
# command     /usr/bin/make
# exit-code   2
# env-file    ~/.opam/log/liquidsoap-30313-2dea01.env
# output-file ~/.opam/log/liquidsoap-30313-2dea01.out
### output ###
# Error: Signature mismatch:
# [...]
#              | `Samplerate of int
#              | `Sbr_mode of bool
#              | `Transmux of transmux ]
#        File "encoder/fdkaac_encoder.ml", line 54, characters 8-327:
#          Expected declaration
#        File "fdkaac.mli", line 101, characters 2-278: Actual declaration
# make[2]: *** [../Makefile.rules:125: encoder/fdkaac_encoder_builtin.cmx] Error 2
# make[2]: Leaving directory '/home/josh/.opam/default/.opam-switch/build/liquidsoap.dev/src'
# make[1]: *** [../Makefile.rules:67: all-auto-ocaml-prog] Error 2
# make[1]: Leaving directory '/home/josh/.opam/default/.opam-switch/build/liquidsoap.dev/src'
# make: *** [Makefile.rules:27: all-subdirs] Error 2
```

I suspect this might be related to commit de9e739 , but my current record for "gut feelings" on here is pretty abysmal. 😉

**Version details**
 - OS: Ubuntu 19.04
 - Version: git commit 55869c1

**Install method**
opam + git

**Comment by toots** [comment]
Hi,

You are correct! You need the latest `ocaml-fdkaac` to compile that encoder in `master`:
```
git clone --recursive https://github.com/savonet/ocaml-fdkaac.git
cd ocaml-fdkaac
opam pin add .
```

**Comment by savonet-users** [comment]
hya!
it's about latest windows build that has flac enabled.
Liquidsoap 1.3.5+scm 
(https://github.com/savonet/liquidsoap.git@0c97657a840bcceb
6e44944ef328745fbc3b422e:20190201:170433)
Copyright (c) 2003-2019 Savonet team



how do you think, why the thing breaks in recent builds? every morning it 
should switch from nightly to daily but it shuts down instead:

2019/05/16 08:01:50 [switch_7141:3] Switch to dieninis with forgetful 
transition.
2019/05/16 08:01:50 [clock.wallclock_main:2] Source 
radio(dot)audiomastering(dot)lt(dot)3 failed while streaming: 
Lang.Clock_conflict(_)!
2019/05/16 08:01:50 [clock.wallclock_main:3] Raised at file "lang/lang.ml", 
line 421, characters 10-46
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"lang/lang_values.ml", line 971, characters 14-20
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"lang/lang_values.ml", line 971, characters 14-20
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"tools/tutils.ml", line 85, characters 14-18
2019/05/16 08:01:50 [clock.wallclock_main:3] Re-raised at file 
"tools/tutils.ml", line 85, characters 48-55
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/switch.ml", line 167, characters 22-185
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"tools/tutils.ml", line 85, characters 14-18
2019/05/16 08:01:50 [clock.wallclock_main:3] Re-raised at file 
"tools/tutils.ml", line 85, characters 48-55
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/switch.ml", line 204, characters 10-15
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/smartcross.ml", line 223, characters 15-25
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/smartcross.ml", line 185, characters 10-24
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/insert_metadata.ml", line 46, characters 6-16
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/on_metadata.ml", line 35, characters 6-11
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/add.ml", line 123, characters 15-20
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "list.ml", 
line 117, characters 24-34
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/add.ml", line 109, characters 6-1023
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/noblank.ml", line 88, characters 6-16
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/switch.ml", line 204, characters 10-15
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 536, characters 12-26
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/compress.ml", line 45, characters 4-14
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 522, characters 8-22
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"operators/compress.ml", line 45, characters 4-14
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "source.ml", 
line 536, characters 12-26
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file 
"outputs/output.ml", line 174, characters 8-18
2019/05/16 08:01:50 [clock.wallclock_main:3] Called from file "clock.ml", 
line 160, characters 17-25
2019/05/16 08:01:50 [radio(dot)audiomastering(dot)lt(dot)3:3] Closing 
connection...


fallback is as follows:
radio = fallback(track_sensitive=false,
                 [pageidavimai, mm, lunmute, lawx, tiesiogiai, 
switch(track_sensitive=true, transitions=[ chik(dzinglas) ],[
            ({ 1w and 13h-15h }, lietmuz),
            ({ 4w and 22h-23h59 }, ske),
            ({ 6w and 13h-15h00 }, ske)]),
            laida, traktorius, lopageidavimai, lovebar, 
switch(track_sensitive=true, transitions=[ chik(dzinglas) ],[
            ({ 2w and 10h }, minmon),
            ({ 2w and 21h-23h59 }, red1),
            ({ 3w and 15h-17h }, maumai),
            ({ 4w and 20h-21h59 }, coldtear),
            ({ 5w and 19h-23h }, mano),
            ({ 6w and 20h-22h00 }, beatz),
            ({ 7w and 14h}, lovekart)]),
            switch(track_sensitive=true, transitions=[ chik(dzinglas) ],[
            ({ 8h-0h }, dieninis),
            ({ 0h-7h59 }, naktinis)])])


also, to remind, windows release is plagued by memleak + casual freezes of 
process when flac is enabled;
neither does it play long mp3s or wavs (never did, including 32bit builds). 
test with 7 hours file and you'll witness the track ending within first 
hour.
also, new builds seem to handle strip_blank in a weir way - even when 
silence, server ends up with many chunks of silence. it used to be OK 
before...
input.harbor(id="mm", buffer=30.,max=90.,"mm"....
strip_blank(max_blank=90., threshold=-28., mm)

regards,
p

**Comment by RecursiveGreen** [comment]
Thanks, @toots. That worked.
