### ISSUE TITLE
Question: Queue song when set to play at time instead of checking the exact minute

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#779]
I strongly suspect there's already a `Liquidsoapy` solution for this problem, but I'm not aware of what it is, so I figured I'd ask on here:

Currently, when users indicate that they'd like a song to play once per day at a specified time (or once per hour), the Liquidsoap config we're writing is basically:

```
radio = switch(track_sensitive=true, [ ({ 2h58m }, once(playlist_interrupting_cow_moo)), ({true}, radio) ])
```

However, this is having the effect of only playing the song specified if the "next song" is calculated exactly at the 2:58 minute. Of course, when track_sensitive is set to `false` this isn't a problem, and it just directly interrupts the existing stream.

However, with track_sensitive set to `true`, what our users are actually looking for is that when the time the track is due to play comes up, the song gets queued up as the next-playing song and then right as the current track finishes, even if the specific minute when the song should've played is up, it goes ahead and plays through anyway.

I'm not sure how to do this in Liquidsoap. We could always just have the web application do a minute-by-minute check of songs that are due to play at that minute and push to the "requests" queue, but of course I'd like to avoid this if at all possible.

Thanks as always for your help and continued development. <3

**Comment by savonet-users** [comment]
On Fri, 17 May 2019, 09:38 SlvrEagle23, <notifications@github.com> wrote:

> I strongly suspect there's already a Liquidsoapy solution for this
> problem, but I'm not aware of what it is, so I figured I'd ask on here:
>
> Currently, when users indicate that they'd like a song to play once per
> day at a specified time (or once per hour), the Liquidsoap config we're
> writing is basically:
>
> radio = switch(track_sensitive=true, [ ({ 2h58m }, once(playlist_interrupting_cow_moo)), ({true}, radio) ])
>
> However, this is having the effect of only playing the song specified if
> the "next song" is calculated exactly at the 2:58 minute. Of course, when
> track_sensitive is set to false this isn't a problem, and it just
> directly interrupts the existing stream.
>
> However, with track_sensitive set to true, what our users are actually
> looking for is that when the time the track is due to play comes up, the
> song gets queued up as the next-playing song and then right as the current
> track finishes, even if the specific minute when the song should've played
> is up, it goes ahead and plays through anyway.
>
> I'm not sure how to do this in Liquidsoap. We could always just have the
> web application do a minute-by-minute check of songs that are due to play
> at that minute and push to the "requests" queue, but of course I'd like to
> avoid this if at all possible.
>
> I don't know LS way of doing this so I set up a queue then use an 'expect'
script via telnet to drop an item into the queue which overrides the
playlist.

Super system, anyway.

JW

>
>

**Comment by Robbt** [comment]
Yeah you may want to look into how the LibreTime airtime-playout python module interacts with liquidsoap scheduling via telnet for some inspiration. I believe that we are doing it similar to the suggestion above but since I didn't write that part of the code and haven't spent the time refactoring it to python 3 I can't say for sure.

**Comment by toots** [comment]
John's solution is pretty much on point. If you want to keep things inside the liquidsoap code, you could use a `add_timeout` polling to queue the song at the right time. I might work on some easier library functions to do this.

**Comment by SlvrEagle23** [comment]
@toots I'm curious what that would look like and where to begin on that front.

I can definitely have the web application itself handle the schedule triggering for these types of playlists, but the problem is that it introduces a kind of bizarre set of pathways in the code. It would basically mean writing to LS directly for most playlist scenarios, and then checking specifically for a track-sensitive scheduled item and instead using the request queue.

I'm also worried that the request queue method wouldn't preserve other settings applied to the playlist, i.e. if it was merged into a single track, I'm not aware of a way to say, via Telnet, "play from this playlist" rather than just "play this specific song".

**Comment by SlvrEagle23** [comment]
Any insight on this issue that anyone can share? It seems completely reasonable to me that people would want this scheduling method (i.e. at 2pm, cue a song to play from this playlist after the current song, just without interrupting it) but if it means we have to write a manual handler for that, it won't let us take advantage of other built-in Liquidsoap functions (i.e. only play playlist once, merge playlist, etc).

**Comment by toots** [comment]
Gonna add something in the standard library for this.

**Comment by SlvrEagle23** [comment]
@toots Thank you :D

**Comment by savonet-users** [comment]
On Wed, May 29, 2019 at 4:14 PM Romain Beauxis <notifications@github.com>
> wrote:
> Gonna add something in the standard library for this.


Thanks! The telnet/expect system worked for me, though it felt
un-liquidsoap to do it quite like that. Still, mustn't neglect to learn
OCaml properly now.

System still running, weeks and weeks now, with the new crossfade code.

with best wishes,
JW

**Comment by tmladek** [comment]
Hey! Not to poke you unnecessarily, but I'd really like a lot if this type of scheduling could be done within liquidsoap only; it's the only thing that I'd have to keep an external script running for!

So just a sanity check, using the `add_timeout` function, would it make sense to have a function that runs every minute, checking against a `{ 13h30 }` time spec, queueing when it returns true? Or would a dynamic queue which is only available at a certain time be possible / better?

Thank you kindly, liquidsoap is blowing my mind!

**Comment by toots** [comment]
Hi,

I've been thinking about this one and how to do it properly. Hopefully this will come to fruition soon!

The polling idea you outlined should indeed work. Make sur you don't end up queueing twice during the time where the predicate is `true`.

Thank you for your support!

**Comment by smimram** [comment]
What about putting the file in a request queue at a specific time?

**Comment by Yamakaky** [comment]
That's what I do, using harbor and server.execute.

**Comment by toots** [comment]
Yeah that's the idea but with a nice API.

**Comment by Yamakaky** [comment]
Yeah, being able to fully interact with queue in liquidscript would be very nice

**Comment by toots** [comment]
Hi all,

I'm moving this for the next major cycle. I want work on something comprehensive, which is more than what we've got left in the current release cycle..

**Comment by SlvrEagle23** [comment]
@toots Thanks for keeping us updated on this one. For my project, our switch back to having our application control much of the "playing next" control has resolved the issue for a majority of users.

**Comment by smimram** [comment]
We now have
- `request.queue.pushable` which allows pushing into queue
- `thread.when` which allows running a task at a particular time
Your problem should be easy to solve with these two!

**Comment by SlvrEagle23** [comment]
@smimram I'm not seeing these documented in the API reference on the Liquidsoap site. Care to share any insight into how this could actually be implemented in an example script?

**Comment by smimram** [comment]
They are in the API reference: [`requestion.queue.pushable`](https://www.liquidsoap.info/doc-dev/reference.html#request.queue.pushable) and [`thread.when`](https://www.liquidsoap.info/doc-dev/reference.html#thread.when).

**Comment by RadioChecheresOk** [comment]
Hello, thank you in advance and I am infinitely grateful for your work and offering to the world of radio and much more. I ask: where do I find the menu or area for "Advanced Liquidsoap"? I couldn't find it and I have the automatic updater. Thank you so much

**Comment by gAlleb** [comment]
@RadioChecheresOk, wrong thread and place. But I got you.

If you want `azuracast` assistance go to https://github.com/AzuraCast/AzuraCast/discussions

Meanwhile I think you can find your answer here https://github.com/AzuraCast/AzuraCast/issues/6899

**Comment by RadioChecheresOk** [comment]
Infinitas gracias por su inmensa cordialidad, voy a intentarlo cómo me
indicas, en serio te digo que infinitas gracias.
