### ISSUE TITLE
`peak` and `rms` units

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#781]
What are the units of `peak()` and `rms()`? From testing I assume it's the amplitude between 0 and 1, but I sometime get >1 values for peak (max I saw was 1.003).
I think I will take some time to improve the doc XD

**Comment by smimram** [comment]
Samples are (usually) between -1 and 1 as usual in floating point representation. `peak` is the maximal absolute value and `rms` is [what it is](https://en.wikipedia.org/wiki/Root_mean_square). This is satisfied for input files, but some operators (e.g. a compressor, replaygain, etc.) might produce value greater than 1, and Liquidsoap does nothing to enforce this (unless you use the `clip` operator) but most outputs correctly handle this by clipping anyway.
