### ISSUE TITLE
Queue with per-track amplify factor

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#782]
I want to have a queue of tracks with proper replaygain support. I assume that the use of the replaygain protocol + `amplify(queue.dynamic...)` would give incorrect results when using transition, since you need to amplify each track before and not after the transition mix. (is that correct?). I tried to do the following:
```
def get_next_track(type)
    req = request.create("var/permanent//EarthBound_Piano_Meets_Girl_OC_ReMix.mp3")
    m = request.metadata(req)

    gain_m = list.assoc("replaygain_track_gain", m, default = "0 dB")
    matches = string.extract(pattern = "([+-]?[0-9.]+) *dB", gain_m)
    gain_dB = snd(list.hd(matches, default = ("0", "0.0")))
    gain = lin_of_dB(float_of_string(gain_dB, default = 0.0))

    peak_m = list.assoc("replaygain_track_peak", m, default = "1.0")
    peak = float_of_string(peak_m, default = 1.0)

    amp_factor = min(gain, 1. / peak)

    amplify(amp_factor, req)
end

permanent = request.dynamic(id="permanent", {get_next_track("permanent")})
```
but `req` is a request and not a source, so `amplify` doesn't work. I could `annotate` the url, but I would be back to square one since I would have to apply the factor to the `request.dynamic`, so after the mix. Do you see a way to do that?

Also, [according to the spec](http://wiki.hydrogenaud.io/index.php?title=ReplayGain_specification#Reduced_gain), the user-controlled gain must be applied before the `min`, so `gain = gain * !pregain_linear` with `pregain_linear` being a variable reference, so using the `annotate` method would not be appropriate.

Bonus point: I also use `request.queue` in a different part of the script for user-controlled breaks during the shows, so I would like to do replaygain + preamp there also.

See https://github.com/savonet/liquidsoap/issues/749 and https://github.com/savonet/liquidsoap/issues/345

**Comment by Yamakaky** [comment]
Idea: pass a function to `request.*()` which is applied to each track.

**Comment by toots** [comment]
You can already do that following the liquidsoap architecture:

```
def get_next_track(type)
    url = "var/permanent//EarthBound_Piano_Meets_Girl_OC_ReMix.mp3"

    # Extract metadata
    req = request.create(url)
    request.resolve(req)
    m = request.metadata(req)

    gain_m = list.assoc("replaygain_track_gain", m, default = "0 dB")
    matches = string.extract(pattern = "([+-]?[0-9.]+) *dB", gain_m)
    gain_dB = snd(list.hd(matches, default = ("0", "0.0")))
    gain = lin_of_dB(float_of_string(gain_dB, default = 0.0))

    peak_m = list.assoc("replaygain_track_peak", m, default = "1.0")
    peak = float_of_string(peak_m, default = 1.0)

    amp_factor = min(gain, 1. / peak)

    request.create("annotate:liq_amplify=\"#{amp_factor}\":#{url}")
end

permanent = amplify(1., request.dynamic(id="permanent", {get_next_track("permanent")}))
```

The `lid_amplify` metadata is passed down with the final request and overrides the amplify value. 

Another way to do it with the current `master` is to use a function for the `amplify` value:

```
amp_factor = ref 1.

def get_next_track(type)
    url = "var/permanent//EarthBound_Piano_Meets_Girl_OC_ReMix.mp3"

    # Extract metadata
    req = request.create(url)
    request.resolve(req)
    m = request.metadata(req)

    gain_m = list.assoc("replaygain_track_gain", m, default = "0 dB")
    matches = string.extract(pattern = "([+-]?[0-9.]+) *dB", gain_m)
    gain_dB = snd(list.hd(matches, default = ("0", "0.0")))
    gain = lin_of_dB(float_of_string(gain_dB, default = 0.0))

    peak_m = list.assoc("replaygain_track_peak", m, default = "1.0")
    peak = float_of_string(peak_m, default = 1.0)

    amp_factor  := min(gain, 1. / peak)

    req
end

permanent = amplify({amp_factor}, request.dynamic(id="permanent", {get_next_track("permanent")}))
```

**Comment by toots** [comment]
Also, we have an automated support for replay gain. Here's an example with the current master:

```
def get_next_track(type)
    url = "var/permanent//EarthBound_Piano_Meets_Girl_OC_ReMix.mp3"
    request.create("replay_gain:#{url}")
end

permanent = amplify(override="replay_gain", 1., request.dynamic(id="permanent", {get_next_track("permanent")}))
```

See: https://github.com/savonet/liquidsoap/blob/master/lib/protocols.liq#L8

**Comment by Yamakaky** [comment]
Two issues with your solution :
- the pre amp must account for the per-track amplitude max, so you can't apply it on the final mix I think
- I think your last example will not play nice with transitions? The transitions should apply to tracks with replaygain already applied, correct?

**Comment by toots** [comment]
You can pass whatever value you want for pre-amp. It is per-track but you can also use the per-album value if you want.

For transitions, yes, you should probably apply the amplification correction before the transition, which would be the case in the example code if `amplify` is applied as early as possible in the source chain.
