### ISSUE TITLE
Video Playlist + Audio Playlist with Muxed Video Transitions ?

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#795]
I'm having issues with getting transitions between two video sources in a rotate() or random()

With code like the following:
```
music_videos = playlist("/music_videos")
videos = playlist("/stock_videos")
music = playlist("/music")

music_mux = mux_video(
    video=videos,
    music
)
rotate([music_videos, music_mux])
```
This will work to play the first music video, and transitions to the muxed video stream, but never returns to the music videos. The idea would be that the end of the audio track triggers rotate to change sources, as would be the case for 2 audio only sources.

I've had intermittent success utilising `clock(...)`, and `source.skip(...)`, `drop_metadata(videos)`, `merge_tracks(videos)` of the muxed videos playlist. 
However I cant find particularly stable configuration.

Some guidance would be appreciated,
Regards

**Comment by dhannyz** [comment]
Doing the following however, triggers rotate correctly (?)
```
add_skip_command(music)
telnet > music.skip
```

**Comment by dhannyz** [comment]
So I had a read through https://github.com/savonet/liquidsoap/blob/master/src/conversions/mux.ml
It believe the type of muxing I require isn't yet supported.
I would need the mode = Master, to preserve the audio stream track information, where it seems only Symmetric is currently implemented.
```
  * There are several possible modes for muxing:
  *  - Master: the auxiliary source should be infallible, and has to
  *    fill in exactly the data zone that the master produces.
  *    Track information for the aux source is lost.
  *    In the future we might want to require exclusivity on the auxiliary
  *    source because this mode requires doing tricks to it, and sharing
  *    would have funny effects.
  *  - Auxiliary: same with exchanged roles.
  *  - Symmetric: The sources have a symmetric role, we loose all track
  *    information, filling as much as possible. If one of the sources
  *    is not ready anymore, extra data from the other is dropped. *)
```
@toots Checking the history here, it seems this particular 'TODO' is many years old.
What are the prospects of getting this muxing mode functional?

**Comment by smimram** [comment]
Just implemented the preservation of the master tracks (= audio tracks in your case). Does this work for you?

**Comment by toots** [comment]
Thanks @smimram !

**Comment by dhannyz** [comment]
Thanks heaps @smimram I can confirm that this is now working as expected :+1:

**Comment by dhannyz** [comment]
@smimram is there are risk here of Audio/Video de-synchronising in one of the sources ? I seem to have a little bit of that going on

**Comment by smimram** [comment]
@dhannyz yes it's expected, is it a problem for you? I can come up with something fancier

**Comment by dhannyz** [comment]
@smimram what I am doing is transitioning between a playlist of music-videos  (I need this in sync) and a 2nd source, that is a more complex arrangement of an audio only source random([weights,...], [playlists,...]), which is more of a traditional radio, that has some stock video applied via the mux.
I'm noticing that in my rotation between these two sources, the music-video's audio tends to come in some noticeable period before the corresponding video transitions. Even from the first occurance of the music-video.
You can imagine when there are video elements timed with audio that this can become quite off-putting

Thanks for what you are doing, if I had the faintest clue about ocaml I'd attempt contribute as well (I'm a developer professionally, but quite time poor atm).
I may be pushing liquidsoap a little, this is what i currently have running 'in production'  https://www.youtube.com/watch?v=mNSTeO0Y_3M
And this is what I'm trying to turn into some kind of radio/music video TV stream hybrid :P

**Comment by dhannyz** [comment]
I actually might have solved this elsewhere.
I _think_ this was being caused by fallible=true on output.external() feeding ffmpeg,,, i also added a -async 1 option to my ffmpeg call.
I will test over some period and report back

**Comment by dhannyz** [comment]
Update: Although it improved things initially, it does slowly desync as mentioned

**Comment by autonarcosis** [comment]
What I have found for video, is that all videos in the playlist must be the same frame rate or you will get desyncronized audio.

**Comment by smimram** [comment]
Ok, so you could try the following. The idea is to mux without propagating tracks and then to re-insert tracks when there is one in the audio track. Here is the code that I have:
```
video = drop_audio(single("test.avi"))

audio = single("test.mp3")
audio = chop(duration=2., audio) # simulate track boundaries

s = mux_video(mode="none", video=video, audio)
is = insert_track(s)
insert = fst(is)
s = snd(is)

def track(m) =
  print("re-inserting track\n\n")
  insert(m)
end
audio = on_track(track, audio)
output.dummy(audio)

def f(_) =
  print("new track!!\n\n\n")
end
s = on_track(f,s)

output.sdl(drop_audio(s))
out(s)
```
You should remove the `chop` line (it is to simulate tracks to test). You can see that when there is a track on `audio` a track is inserted on `s`. Tracks should thus be propagated, without losing sync. the `mode="none"` in mux is the original mode you used at the beginning of this bug report.

**Comment by dhannyz** [comment]
@smimram this does not work for me, the resulting muxed video has silent audio
Also wouldnt the dummy consume the audio stream while im playing the music-video playlist, and ruin transitions between that and this muxed one?

**Comment by dhannyz** [comment]
In fact, the recent changes have broken my working setup

**Comment by smimram** [comment]
Can you try to be more specific and pin down the commit which is breaking you setup? `mux(mode="none",...)` should be the same as what you had before...

Also could you first try my exact script first (giving it again since the syntax changed a bit):
```
video = drop_audio(single("test.avi"))
audio = single("test.mp3")
audio = chop(duration=2., audio) # simulate track boundaries

s = mux_video(mode="none", video=video, audio)
is = insert_metadata(s)
insert = fst(is)
s = snd(is)

def track(m) =
  print("re-inserting track\n\n")
  insert(new_track=true, m)
end
audio = on_track(track, audio)
output.dummy(audio)

def f(_) =
  print("new track!!\n\n")
end
s = on_track(f,s)

output.sdl(drop_audio(s))
out(s)
```
Without changing anything (excepting from the audio and video file), don't you get audio? (I do)

Liquidsoap supports streams shared between sources, so that the audio stream does not get eaten by `output.dummy`.

**Comment by dhannyz** [comment]
@smimram thanks for your work on this earlier, my subsequent issues were unrelated.
My most recent one was the new sandboxing causing a particular system call i used to return 0's
This was counting a playlist folder's number of tracks, to set the weights=[] for random(). And I was ending up with `weights=[0,0,0,0,0]`  Which stops random() from ever becoming active
