### ISSUE TITLE
Passing custom track duration when using request.dynamic

### ISSUE THREAD

**Issue by mrcatman** [savonet/liquidsoap#798]
I'm using request.dynamic to generate a radio playlist from my external script. Is there a way to pass custom duration of a track for trimming it? Tried to pass it through annotate (like _'annotate:title="Title 1",duration=30,artist="Artist 1":_), but it doesn't work.

**Comment by smimram** [comment]
Yes, the [`cue_cut` operator](https://www.liquidsoap.info/doc-dev/reference.html#cue_cut) is precisely meant for that, and you can use the `liq_cue_out` metadata to specify the end point.
