### ISSUE TITLE
Log levels

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#800]
I can't find a listing for the possible values for `log()` and the setting `log.level`. By testing, I assume 1 is the highest level, but what is the lowest?
Additionally, we can add more builtins like `log.debug` and such.

**Comment by smimram** [comment]
yes, we have meant to document the log levels for some time. I would say
- 1: critical
- 2: important
- 3: normal
- 4: information
- 5: debug

I'll think about making this more clear in the code.

**Comment by smimram** [comment]
Started implementing this in #801.
