### ISSUE TITLE
Fallback being triggered by lots of things

### ISSUE THREAD

**Issue by SlvrEagle23** [savonet/liquidsoap#803]
Hello! AzuraCast dev here again, and I've been noticing a fairly frequent issue with how Liquidsoap handles fallbacks.

Currently, this is my most barebones setup for handling this fallback in case there's nothing playing:

```
error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="azuratest_radio_requests"))
radio = fallback(id="azuratest_radio_autodj_fallback", track_sensitive = true, [requests, radio, error_song])
```

The idea is that should Liquidsoap need to "fall back" to `error_song` briefly (i.e. after skipping a song, when cueing-out, or other situations that cause fallbacks to trigger, intentionally or not) it would play the 5 seconds of silence, detect that the "higher level" radio source is live again and switch back to it.

Instead, it seems to be playing the error jingle basically every time any of these fallback events happens.

My first question here is why does skipping a song (internally via telnet we're calling `source.skip` where `source` is the first output source) trigger fallback, and why would cue_cut be setting it off either? Secondly, what am I doing wrong with this formatting and how do I get it to fall back to silence in these scenarios, but still play the error message if there genuinely is no live source for an extended period of time?

Thanks again! :)

**Comment by SlvrEagle23** [comment]
Just for ease of diagnosis, here's the full configuration file as generated by the software:

```
set("init.daemon", false)
set("init.daemon.pidfile.path","/var/azuracast/stations/azuratest_radio/config/liquidsoap.pid")
set("log.stdout", true)
set("log.file", false)
set("server.telnet",true)
set("server.telnet.bind_addr","0.0.0.0")
set("server.telnet.port", 8004)
set("harbor.bind_addrs",["0.0.0.0"])

set("tag.encodings",["UTF-8","ISO-8859-1"])
set("encoder.encoder.export",["artist","title","album","song"])

setenv("TZ", "UTC")

playlist_default = audio_to_stereo(playlist(id="playlist_default",mode="randomize",reload_mode="watch","/var/azuracast/stations/azuratest_radio/playlists/playlist_default.m3u"))

# Standard Playlists
radio = random(weights=[3], [playlist_default])

error_song = sequence([blank(duration=5.), single("/usr/local/share/icecast/web/error.mp3")])
requests = audio_to_stereo(request.queue(id="azuratest_radio_requests"))
radio = fallback(id="azuratest_radio_autodj_fallback", track_sensitive = true, [requests, radio, error_song])

radio = cue_cut(id="azuratest_radio_radio_cue", radio)

# Allow for Telnet-driven insertion of custom metadata.
radio = server.insert_metadata(id="custom_metadata", radio)

# Apply amplification metadata (if supplied)
radio = amplify(1., radio)

radio = crossfade(start_next=3.,fade_out=2.,fade_in=2.,radio)

# Send metadata changes back to AzuraCast
def metadata_updated(m) =
  if (m["song_id"] != "") then
    ret = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/feedback --form song="^quote(m["song_id"])^" --form media="^quote(m["media_id"])^" --form playlist="^quote(m["playlist_id"])^" --form api_auth="^quote("")^""), default="")
    log("AzuraCast Feedback Response: #{ret}")
  end
end

radio = on_metadata(metadata_updated,radio)

# Local Broadcasts
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=128, id3v2=true), id="azuratest_radio_local_1", host = "127.0.0.1", port = 8000, password = "", mount = "/radio.mp3", name = "AzuraTest Radio", description = "A test radio station.", genre = "", public = false, encoding = "UTF-8", radio)
output.icecast(%mp3(samplerate=44100, stereo=true, bitrate=64, id3v2=true), id="azuratest_radio_local_2", host = "127.0.0.1", port = 8000, password = "", mount = "/mobile.mp3", name = "AzuraTest Radio", description = "A test radio station.", genre = "", public = false, encoding = "UTF-8", radio)
```

**Comment by SlvrEagle23** [comment]
So far, we have three scenarios that reliably, in almost all of our tests, will briefly mark the entire set of playlists as an inactive source and trigger falling all the way back to the fallback silence (or error MP3):

 - Restarting the station triggers it immediately after restart
 - Skipping a song (which internally is calling `.skip` on the output source or, as of our latest update, the `radio` variable itself)
 - A song with cue metadata reaching the end of its cue and being regularly "cued out".

I know this is a little forward and may not be possible given you all are busy folks, but given there are thousands of AzuraCast users and yet we seem to always be plagued with these issues that really cause problems for all of our station operators, it may be worthwhile if we could donate to one of your team members in order to pay for some developer time to perform a full "audit" of how we're generating Liquidsoap code, identifying any obvious things we're doing wrong and helping us create a more reliable experience for our listeners. It would really help us out.

**Comment by toots** [comment]
I think that this comes from a misuse of `track_sensitive`. When it is `true`, the fallback will wait until a track has been fully played before trying to switch away. The first order of business here is to split your `fallback` into one that is `track_sensitive` to switch between your real sources and then one that is not `track_sensitive` to switch to the error source only when absolutely required and switch away as soon as possible:
```
radio = fallback(id="azuratest_radio_autodj_fallback", track_sensitive = true, [requests, radio])
radio = fallback(id="azuratest_radio_autodj_safe_fallback", track_sensitive = false, [radio, error_song])
```

The second issue that you describe is linked to how your sources prepare new requests. If a new request is ready whenever a track ends then there shouldn't be any down time or switch. With things such as `skip` and `cue_cut`, it can happen that the source is caught empty handed when the track ends and has to go down briefly to prepare a new one.

One way to mitigate that is to make sure that it queues at least one track in advance. This can be done using the `default_duration` and `length`.

To save on computation time, each new track is assumed to be `default_duration` when queued, which is `30.` seconds. As the track is played, this value is estimated and gets closer to the actual remaining time when it gets to the end.

However, when a track has just been queued, liquidsoap assumes it is `30.` sec long. Also, liquidsoap wants to make sure that it has at least `length` seconds queued up. By default it is `10.` seconds, so once one track is queued up, it won't try to queue another track until remaining time has dropped below `10.` sec.

Thus, if, for instance, you set `default_duration` to `10.` and `length to `20.` then you should have at all time at least two track queued up in the system.

I'm closing this here. We're trying to move all user-related discussions such as this one to our slack channel now. Let's continue the conversation there!
