### ISSUE TITLE
Fade Skip

### ISSUE THREAD

**Issue by jdbuys** [savonet/liquidsoap#804]
Would it be possible to create a function that when it is called will fade out the song for x amount of seconds and then when it is done it calls skip?

It just makes the transition between track sound better than just an abrupt stop when you call skip.

Thanks.

**Comment by Yamakaky** [comment]
I could use that ^^

**Comment by smimram** [comment]
Fading is already almost entirely coded in liq: https://github.com/savonet/liquidsoap/blob/master/lib/fades.liq

It should not be too hard to adapt that in order to achieve what you want. I'll give it a show some day soon if you don't do it before me.
