### ISSUE TITLE
Assertion failed in duppy.ml

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#806]
Just noticed this crash in my production log on 1.3.7, not sure how to reproduce... I have a jack input and output, a icecast output, file.output and multiple request.queue.

```
2019/05/27 17:00:59 [main:3] Shutdown started!
2019/05/27 17:00:59 [main:3] Waiting for threads to terminate...
2019/05/27 17:00:59 [threads:3] Shuting down thread radiokawaii
2019/05/27 17:00:59 [threads:3] Thread "retour-plateau" terminated (3 remaining).
2019/05/27 17:00:59 [icecast(dot)mp3:3] Closing connection...
2019/05/27 17:00:59 [jingles:3] Finished with "var/jingles//Virgule_Short_Smooth_Femme.flac".
Queue generic queue #1 crashed with exception File "duppy.ml", line 269, characters 4-10: Assertion failed
Raised at file "duppy.ml", line 269, characters 4-42
Called from file "duppy.ml", line 313, characters 7-24
Called from file "duppy.ml", line 350, characters 9-15
Called from file "duppy.ml", line 356, characters 5-9
Called from file "tools/tutils.ml", line 216, characters 19-55
```

**Comment by toots** [comment]
Thanks. I'll look it up.

**Comment by toots** [comment]
I've looked at this one and it's tricky. Here's the relevant code:
```
    Mutex.lock s.ready_m ;
    log (Printf.sprintf "There are %d ready tasks." (List.length s.ready)) ;
    if exec s priorities then raise Queue_processed;
```
And:
```
let exec s (priorities:'a->bool) =
  (* This assertion does not work on
   * win32 because a thread can double-lock
   * the same mutex.. *)
  if Sys.os_type <> "Win32" then
    assert(not (Mutex.try_lock s.ready_m)) ;
```
I can see very little reason why the mutex should be unlocked immediately after locking them. Two reasons that come to mind:
* A general stack corruption.
* A library that allows for double locking

What is your OS? It seems to me that you're using `alpine`, which is based on `musl`. Perhaps their implementation has a double locking issue?

Please try to add the usual information from the template next time, that always helps.. 🙂

**Comment by Yamakaky** [comment]
Sorry: it's the same docker as in https://github.com/savonet/liquidsoap/issues/810.

**Comment by toots** [comment]
No pb. Do you have a reliable way to reproduce the issue?

**Comment by Yamakaky** [comment]
No, I'll see if I get this error again.

**Comment by toots** [comment]
Any new occurence of this one?

**Comment by Yamakaky** [comment]
No, will update if I do...

**Comment by toots** [comment]
Hi. I'm gonna close this one. Please reopen if you have more info about it..
