### ISSUE TITLE
input.external.avi eating RAM

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#812]
I'x experimenting with live rtmp input, as a video source that comes in over the top of my video-radio stream.
```
live_video = clock(input.external.avi(
restart_on_error=true,
"ffmpeg -v 16 -listen 1 -i rtmp://#{IP}:#{port}/#{mount} \
-f avi -vf format=rgb24 -vcodec rawvideo -r 25 -s 1280x720 \
-acodec pcm_s16le -ar 44100 \
pipe:1"
))
```

This actually works and I am able to use OBS to livestream through liquidsoap to youtube (wow)
A few caveats:
Firstly, I need to assign a new clock for this input, otherwise the whole application waits for ffmpeg, and doesnt even parse the rest of the script. This makes some sense. So I use a fallible buffer to use the source in a fallback(). However it would be nice if this had behaviour similar to input.harbor (maybe an input.external.live_video)

Secondly, On connection, ffmpeg complains with an error that causes it to restart, but then subsequently works fine.
`[avi @ 0x55af80542e00] rgb24 rawvideo cannot be written to avi, output file will be unreadable`

And lastly, the big one, this is eating RAM at a rate that looks like the entire input stream goes directly there, and never gets freed. even after disconnection and the restarting of `input.external.avi` a few minutes of live video and my 64GB is completely used.

**Comment by smimram** [comment]
I can confirm and reproduce with the following slightly simpler script:
```
cmd = "ffmpeg -i test.avi -f avi -vf format=rgb24 -vcodec rawvideo -r #{get(default=0,\"frame.video.samplerate\")} -s #{get(default=0,\"frame.video.width\")}x#{get(default=0,\"frame.video.height\")} -an pipe:1"
print(cmd)
s = input.external.avi(restart_on_error=true, cmd)
s = mksafe(s)
output.sdl(s)
```

**Comment by dhannyz** [comment]
Further more, it seems to break my server's standard output, and fails to close the external thread on exit

**Comment by smimram** [comment]
Could you try with the latest commit? It has solved the memory leak problem here. Other issues are minor and could easily be solved.

**Comment by smimram** [comment]
@dhannyz can you confirm that it helps?

**Comment by dhannyz** [comment]
Continued in #830

**Comment by smimram** [comment]
Thanks for closing. Sorry, I did not remember that we already had this bug open.
