### ISSUE TITLE
Convert duppy to lwt

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#814]
Since we don't have so much manpower, it might be a good idea to ditch our internal libraries when standard ones are available. For duppy, it might be a good idea to switch to lwt.

@toots What do you think about it?

**Comment by toots** [comment]
While a totally agree on removing dependencies duppy is my baby and I wouldn't remove that part first.. 😅

More seriously, here are a couple of reasons not to:
* Duppy follows an architecture with multiple pooled threads picking up tasks. This is much more close to the node/libev architecture than to Lwt. Lwt is a monothread architecture that would require changing all our code. I'm not even sure it would fit all our use cases.
* Duppy is actively maintained, by myself!

I'm gonna close this for these reasons. However, please note that I am 100% ready to cut through dependencies.

The number one that I have in mind is a total rewrite of the file decoders. We should just use ffmpeg bindings for audio and video content. For audio content we could even decide everything down to wave format in the protocol stack. That would remove a ton of external dependencies.

**Comment by toots** [comment]
Ha also, let's do that after the 1.4 release.. 🙂

**Comment by smimram** [comment]
Fair enough, I thought that duppy was more or less superseeded by lwt. If it's not the case then let's keep things this way. Concerning the library for decoders, I am not completely sure, let's discuss this. In the past having multiple bindings has allowed us to switch easily when there was a problem.
