### ISSUE TITLE
[1.3.7] ffmpeg 0.2.1 from opam doesn't contain swresample on debian 8

### ISSUE THREAD

**Issue by r4sas** [savonet/liquidsoap#816]
**Describe the bug**
Building liquidsoap 1.3.7 fails:
```
make[3]: вход в каталог «/usr/src/liquidsoap-1.3.7-full/liquidsoap-1.3.7/src»
OCAMLOPT -c decoder/ffmpeg_decoder.ml
File "decoder/ffmpeg_decoder.ml", line 40, characters 47-70:
Error: Unbound module FFmpeg.Swresample
../Makefile.rules:196: ошибка выполнения рецепта для цели «decoder/ffmpeg_decoder.cmx»
```
**To Reproduce**
`PACKAGES` list:
```
ocaml-cry
ocaml-mad
ocaml-taglib
ocaml-lame
ocaml-shine
ocaml-ogg
ocaml-vorbis
ocaml-speex
ocaml-theora
ocaml-opus
ocaml-fdkaac
ocaml-faad
ocaml-flac
ocaml-ladspa
ocaml-soundtouch
ocaml-samplerate
ocaml-dtools
ocaml-duppy
ocaml-mm
liquidsoap
```

Accoding to post on stackoverflow, swresample is not available on debian (as I see, till deb 9), and avresample is not compatible: https://stackoverflow.com/a/14618056

**Expected behavior**
Build without problems. I really don't know why ffmpeg is used at first, since it not included in `PACKAGES`

**Version details**
 - OS: Debian 8
 - Version 1.3.7

**Install method**
Used Debian 8 with latest opam binary.
All needed packages installed via opam, ocaml version 4.07.1.

`ffmpeg` installed via `opam`:
> [NOTE] Package ffmpeg is already installed (current version is 0.2.1).

Libraries, requested by ocaml packages at configuration step installed from apt.

**Comment by smimram** [comment]
Why don't you install Liquidsoap with opam too ?

**Comment by r4sas** [comment]
Because it returns same error.

**Comment by smimram** [comment]
Do you by any chance have a local installation of ocaml-ffmpeg ?

**Comment by r4sas** [comment]
```
# dpkg -l | grep ffmpeg
ii  ffmpeg 10:2.6.9-dmo1+deb8u2 amd64 audio/video encoder, streaming server & audio/video file converter
```

**Comment by smimram** [comment]
What about
```
ocamlfind query duppy
```
?

**Comment by smimram** [comment]
I meant
```
ocamlfind query ffmpeg
```

**Comment by r4sas** [comment]
$ ocamlfind query ffmpeg
/srv/transcoder/.opam/4.07.1/lib/ffmpeg

It will be that anyway, because of eval ``` `opam env` ```

**Comment by r4sas** [comment]
Just for note: latest version I've successfully built on same machine was 1.33.
Since that version I haven't updated liquidsoap until now.

**Comment by smimram** [comment]
@r4sas in this case
```
opam remove ffmpeg && opam install liquidsoap
```
should work for you. I'll tighten the configure check on ffmpeg.

**Comment by r4sas** [comment]
Yup, now liquidsoap builded.
Close issue if here no more things to do.

**Comment by smimram** [comment]
Great, I'll leave it open for now so that we can think of tightening the checks on ffmpeg.
