### ISSUE TITLE
Webcaster Connection

### ISSUE THREAD

**Issue by Pelican104** [savonet/liquidsoap#817]
Hi, I'm trying to test the webcaster functionality which looks like a fantastic feature.
However I cant get the test client to connect, it doesn't seem to respect the connection string I enter in the stream destination uri field.
My server is liquidsoap 1.1.1. I'm running the client in firefox using the HTTP version as my server isn't yet running SSL
The firefox log shows the client trying to connect to a localhost address rather than the uri I have entered.
Any thoughts much appreciated.
![image](https://user-images.githubusercontent.com/42071538
![webcaster issue](https://user-images.githubusercontent.com/42071538/58890413-78dd2300-86e2-11e9-9f67-708a75260f78.png)
/58890245-2c91e300-86e2-11e9-864d-67788b9161db.png)

**Comment by toots** [comment]
Have you tried with a `ssl` connection? Most recent web browsers do require `ssl` connections to work. You would use: `wss://...` and also will have to install a `ssl` certificate with liquidsoap (and thus use a liquidsoap with `ssl` available and enabled. `1.3.7` is recommended)

**Comment by Pelican104** [comment]
Ok thanks for the advice, I will try upgrading my liquidoap and then figuring out the SSL stuff. I'll let you know how I get on. Thanks for taking the time to reply.

**Comment by Pelican104** [comment]
Well, I've got to admit I've hit multiple brick walls trying to get this to work. This is probably down to a lack of knowledge/understanding on my part but, if I can offer some feedback/user insight, I have to say I find the whole OPAM install process a complete nightmare. It's taken me a week to get Liquidsoap installed on a new ubuntu 1804 machine, I've ended up with files all over the place and still can't get deamonization to work.

I have previously installed liquidsoap 1.1.1 on ubuntu via apt. That took me one evening and has been successfully running three radio stations for well over a year (www.yorkshirecoastradio.com/extra) 

I'd love to get the latest version running, there are some great features in there that I'd like to use but the OPAM install process is not clear, the files end up buried somewhere in  ~/.opam but most of the documentation talks about /etc/liquidsoap, /etc/init.d/liquidsoap and /var/log/liquidsoap. It's all very difficult to fathom.

Maybe the end user the project is targeting is someone more technical than me, if so that's fine. I will happily carry on using the apt version, it works well, it's stable and reliable. 

I'll have a go at building from source and see if I have any more joy with that.

Thanks for taking the time to read this, I hope the feedback is useful. I'm not trying to be critical, just offering the observation that a fairly technical guy with decades of broadcast technology experience can't make this work via OPAM.

**Comment by toots** [comment]
Hey! I'm sorry that you're having a hard time installing the software. Feel free to drop by our slack channel to get some help: https://savonet-slack-auto-invite.herokuapp.com/

Also, you might be happy to learn that we recently re-introduced testing packages for various debian-based distributions. See here: https://www.liquidsoap.info/doc-dev/install.html#debianubuntu

**Comment by smimram** [comment]
Also, I would be curious about which parts specifically gave you hard time so that we can improve the installation process or, at least, the documentation...

**Comment by Pelican104** [comment]
The testing package method worked first time, that was much easier. Thanks.
