### ISSUE TITLE
Error message when telnet port is already taken

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#829]
When the telnet port is already taken we get
```
2019/06/09 09:58:05 >>> LOG START
init: exception encountered during start phase:
  Address already in use in bind()
```
It took me some time to realize that it was because of the telnet, the error message should be improved.

To reproduce simply launch two instances of Liquidsoap with telnet enabled.

**Comment by toots** [comment]
I agree that this message is a bit cryptic. I'm not yet sure what to do, though. The error message comes staight from [strerror](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strerror.html) via `Unix.error_message`. I can see many reason why we wouldn't want to override this, like localization of the message or restricting its meaning to e.g. only sockets while it might pop in other contexts and etc.

I might tackle it sideways by catching multiple socket open on the same address in the server code itself and raising a custom exception there/then.
