### ISSUE TITLE
Memory leak with external

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#830]
This was reported by @dhannyz on slack, copying this here so that I don't forget. The following script listens to rtmp:

```
set("frame.video.width",1280)
set("frame.video.height",720)
set("frame.video.samplerate",25)

in_cmd = "ffmpeg -v 16 -listen 1 -i rtmp://localhost:12345/live/test -f avi -vf format=rgb24 -vcodec rawvideo -r #{video.frame.rate()} -s #{video.frame.width()}x#{video.frame.height()} -acodec pcm_s16le -ar 44100 pipe:1"
out_cmd = "ffmpeg -i pipe:0 -f null /dev/null"

s = input.external.avi(restart_on_error=true, in_cmd)

output.external(fallible=true, %avi, out_cmd, s)
```

When a client connects, which can be simulated with

```
ffmpeg -re -f lavfi -i testsrc -f lavfi -i anullsrc -vf scale=1280:720 -c:v libx264 -profile:v baseline -pix_fmt yuv420p -c:a libfdk_aac -b:a 128k -bsf:a aac_adtstoasc -f flv rtmp://localhost:12345/live/test
```

The memory consumption grows linearly (and quite fast at 1280x720).

**Comment by smimram** [comment]
Crazy thing: I cannot reproduce with `input.external.avi` **or** `output.external` only...

**Comment by smimram** [comment]
Simplified version:

```
set("frame.video.width",1280)
set("frame.video.height",720)
set("frame.video.samplerate",25)

s = input.external.avi(id="in", restart_on_error=true, "ffmpeg -v 16 -i test.avi -f avi -vf format=rgb24 -vcodec rawvideo -r #{video.frame.rate()} -s #{video.frame.width()}x#{video.frame.height()} -acodec pcm_s16le -ar 44100 pipe:1")

s = mksafe(s)
out(s)
output.sdl(drop_audio(s))
```

It works with standard file input (no need for rtmp) and no `output.external`.

**Comment by smimram** [comment]
My current diagnostic is that
- the video frames created by `input.external.avi` are never freed (which means that they must remain rechable for some reasons)
- the generator's size remains roughly constant (once the maximum buffer size has been reached)
This means that someone along the line must keep a pointer on the video frames, but I don't have any idea of who could do that...

@toots I'm quite lost on this, any help welcome.

**Comment by dhannyz** [comment]
Does this still happen with `input.external.rawvideo` ?
Could maybe narrow down where it's occurring, if specific to AVI or not

**Comment by smimram** [comment]
Yes, the following also exhibits the leak:
```
set("frame.video.width",1280)
set("frame.video.height",720)
set("frame.video.samplerate",25)

s = input.external.rawvideo(id="in", restart_on_error=true, max=2., "ffmpeg -v 16 -f lavfi -i testsrc -f rawvideo -vf format=rgb24 -r #{video.frame.rate()} -s #{video.frame.width()}x#{video.frame.height()} pipe:1")
s = mksafe(s)
output.sdl(s)
```

**Comment by smimram** [comment]
Fixed in https://github.com/savonet/ocaml-mm/commit/51992d7dee785c0a27b0df6b5897b13a533f5116 (finally). You need the most recent version of ocaml-mm.

**Comment by toots** [comment]
Super happy to see this, thanks for chasing this one down @smimram!

**Comment by dhannyz** [comment]
Aha! I suspected something to do with Img, given it appeared in both the .avi and .rawvideo functions.
Awesome to see this fixed!
