### ISSUE TITLE
HLS issues

### ISSUE THREAD

**Issue by mkpascal** [savonet/liquidsoap#831]
**Describe the bug**
I’ve been experimenting with HLS in Liquidsoap recently and I haven’t been able to make it work.

I currently have two issues:
- HLS AAC encoding is crashing after a few minutes
- HLS stream is unreadable on various devices

For the first issue, I’m getting the same unlink issue with both output.file.hls and output.harbor.hls using fdkaac as the encoder. This is raising an error and stopping encoding in HLS after a few minutes (doesn't fail right away).

`2019/06/04 15:08:11 [clock.wallclock_main:2] Source stream(dot)m3u8 failed while streaming: No such file or directory in unlink(/tmp/hls2e975e/aac_64_1.aac)!
2019/06/04 15:08:11 [clock.wallclock_main:3] Raised by primitive operation at file "outputs/hls_output.ml", line 177, characters 28-73`

The last issue is that I’m not able to listen to the HLS stream on a browser and also on an iOS device. This happens on both AAC & MP3 HLS encoding. This is also happening with both output.file.hls & output.harbor.hls. (And I have no issue when I try with another tool -- HLS encoded with FFMPEG).

I tried with an HLS validator and there’s a mention of mismatch of codec/extension, not sure if it’s entirely the issue but I wanted to mention this.

**To Reproduce**
Here’s what I’m using in my scripts.

`output.file.hls("/home/c9/www/stream/hls", [("aac_64",%fdkaac(channels=2, samplerate=44100, bitrate=64, afterburner=true, aot="mpeg4_he_aac", transmux="adts", sbr_mode=true)), ("aac_32", %fdkaac(channels=2, samplerate=44100, bitrate=32, afterburner=true, aot="mpeg4_he_aac", transmux="adts", sbr_mode=true))], source)`

OR

`output.harbor.hls(port=8088, [("aac_64",%fdkaac(channels=2, samplerate=44100, bitrate=64, afterburner=true, aot="mpeg4_he_aac", transmux="adts", sbr_mode=true)), ("aac_32", %fdkaac(channels=2, samplerate=44100, bitrate=32, afterburner=true, aot="mpeg4_he_aac", transmux="adts", sbr_mode=true))], source)`

**Expected behavior**
- Able to listen to an HLS stream on devices

**Version details**
 - OS: Debian 9
 - Version: 1.4.0-beta1

**Install method**
Using opam

Thanks!

**Comment by smimram** [comment]
When trying the example, I get
```
2019/06/12 15:55:42 [clock.wallclock_main:2] Source stream(dot)m3u8 failed while streaming: Parameter not available!
2019/06/12 15:55:42 [clock.wallclock_main:3] Raised by primitive operation at file "fdkaac.ml", line 251, characters 30-45
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "encoder/fdkaac_encoder.ml", line 151, characters 10-36
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "outputs/hls_output.ml", line 241, characters 20-66
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "list.ml", line 88, characters 20-23
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "outputs/hls_output.ml", line 240, characters 8-165
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "outputs/hls_output.ml", line 267, characters 10-26
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 264, characters 35-47
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "outputs/output.ml", line 180, characters 6-22
2019/06/12 15:55:42 [clock.wallclock_main:3] Called from file "clock.ml", line 160, characters 17-25
```

**Comment by toots** [comment]
This should be fixed now. @smimram you should check the version of `fdk-aac` that you are using.

**Comment by toots** [comment]
And thanks for reporting!

**Comment by smimram** [comment]
Yes, it seems to be working now!
