### ISSUE TITLE
How can I delay a live stream?

### ISSUE THREAD

**Issue by CGenie** [savonet/liquidsoap#832]
I have a live stream that I need to stream delayed by 1 hour, how can I proceed with that?

**Comment by smimram** [comment]
I would do something like
```
delayed = buffer(buffer=3600., max=4000., source)
```
(not tested).

**Comment by CGenie** [comment]
Thank you. However I pass this to icecast like this:

```
output.icecast(
    %mp3(bitrate=128),
    host="xxx",
    port=8000,
    user="xx",
    password="xxx",
    mount="/",
    mksafe(delayed))
```

Thing is the output stream immediately takes over so I have a long silence before the buffered stream kicks in. How to prevent sending the output stream until it is fully buffered? I tried the `start=false` param (https://www.liquidsoap.info/doc-dev/reference.html#buffer) however it doesn't work.

**Comment by smimram** [comment]
No I don't think that it is possible to delay the output stream. If you really want that I'd suggest dumping the stream in a file and start playing it 1 hour later.

**Comment by CGenie** [comment]
The stream I need to transmit is altogether 3 hours long, however I need to delay it by 1 hour. Would it work to save it to a file and then play afterwards while it's being saved?

**Comment by dhannyz** [comment]
@CGenie unlikely this would work.

I believe the buffer option is your best option, however it may consume some considerable amount of RAM. 1hr of wav at 16bit 44100Hz stereo is I believe ~ 600MB of RAM for that buffer.

The trick is your icecast output should be fallible. Try something like this
```
output.icecast(
    %mp3(bitrate=128),
    host="xxx",
    port=8000,
    user="xx",
    password="xxx",
    mount="/",
    fallible=true,
    buffer(
        fallible=true,
        buffer=3600.,
        max=3700., 
        delayed_live_source
    )
)
```

This way the buffer should not be 'available' until it has pre-buffered 1hr worth of audio, and should then continue playing until it has exhausted?
@smimram I think this should work? However I do recall times where, even though there is data yet to be read out of the buffer, that the source switched before it was completely exhausted.

**Comment by CGenie** [comment]
I have 2 GB RAM free at the moment, I guess 600MB is not that much, though I'm importing an mp3 so I don't know whether it uncompresses it to wav to buffer into RAM or holds MP3 still? In case of MP3 it's negligible, in case of wav tolerable :) I'll try the `fallible` option, thanks!

**Comment by dhannyz** [comment]
With liquidsoap, everything is converted to wav (16 bit PCM LittleEndian, 44100Hz by default) for internal processing

**Comment by smimram** [comment]
Solutions have been proposed, please reopen if there are some more problems.

**Comment by RoyWiggins** [comment]
A followup:

I've had _some_ success by just dumping the stream to a file, waiting the delay time, and then reading it again from the beginning. That this works at all is probably coincidence and may depend on the decoder/encoder, but with %mp3 on 1.4.1 and Windows, this does basically work:

```
buf_file = "buffer.mp3"
s = input.http("...")

output.file(%mp3,buf_file,fallible=true,s)

delay_buffer = single(buf_file)
delayed_source = sequence([blank(duration=(3600.0*5.0)),delay_buffer])
```

However, I want to delay an ongoing live stream, and this buffer.mp3 obviously keeps growing without bound, so I want to split this file into pieces and then output those. I got as far as splitting by hour and keeping a list of the pieces, but I don't know how to build a source that will follow that list as it grows. Is there a good way to do this? 

```
s = input.http("...")
dyn_sources = ref([])

def complete (filename)
	dyn_sources := list.append( !dyn_sources, [ single(filename) ] )
end

file_name = "archive/%Y-%m-%d/%Y-%m-%d-%H_%M_%S.mp3"
output.file(%mp3,file_name,on_close=complete,reopen_when={0m0s},fallible=true, s)
```

**Comment by RoyWiggins** [comment]
Aha, I believe this works, though I haven't rigorously tested it yet. Probably not optimal, but I think this is a viable approach: 

```
lownoise = fun (d) -> amplify(0.05,noise(duration=d))
radio_stream = input.http("...")
safe_stream = fallback([radio_stream,lownoise(0.1)])

dyn_buffer_list = ref([])

def complete (filename)
	dyn_buffer_list := list.append( !dyn_buffer_list, [ filename ] )
	print(dyn_buffer_list)
end

file_name = "archive/%Y-%m-%d/%Y-%m-%d-%H_%M_%S.mp3"
output.file(%mp3,file_name,on_close=complete,reopen_when={0m0s},safe_stream)

def next_file() 
	head = list.hd(default="",!dyn_buffer_list) # get the oldest buffer file
	if head == "" then # must not have any buffer files yet
		[] 
	else # pop this off the list and return it
		dyn_buffer_list := list.tl(!dyn_buffer_list)
		[request.create(head)]
	end
end 

buffer_source = request.dynamic.list(next_file)
delayed_source = sequence([lownoise(3600.0*5.0),buffer_source])
```

**Comment by mylselgan** [comment]
> Aha, I believe this works, though I haven't rigorously tested it yet. Probably not optimal, but I think this is a viable approach:
> 
> ```
> lownoise = fun (d) -> amplify(0.05,noise(duration=d))
> radio_stream = input.http("...")
> safe_stream = fallback([radio_stream,lownoise(0.1)])
> 
> dyn_buffer_list = ref([])
> dyn_old_files = ref([])
> 
> def complete (filename)
> 	dyn_buffer_list := list.append( !dyn_buffer_list, [ filename ] )
> 	print(!dyn_buffer_list)
> end
> 
> file_name = "archive/%Y-%m-%d/%Y-%m-%d-%H_%M_%S.mp3"
> output.file(%mp3,file_name,on_close=complete,reopen_when={0m0s},safe_stream)
> 
> def next_file() 
> 	head = list.hd(default="",!dyn_buffer_list) # get the oldest unplayed buffer file
> 	if head == "" then # must not have any buffer files yet
> 		[] 
> 	else # pop this off the list and return it
> 		dyn_buffer_list := list.tl(!dyn_buffer_list)
> 		dyn_old_files := list.append( !dyn_old_files, [ head ] )
> 		if list.length( !dyn_old_files ) > 3 then # delete the oldest buffer file that's already been played
> 			oldest = list.hd(default="", !dyn_old_files )
> 			file.unlink(oldest)
> 			dyn_old_files := list.tl(!dyn_old_files)
> 		end
> 		[request.create(head)]
> 	end
> end 
> 
> buffer_source = request.dynamic.list(next_file)
> delayed_source = sequence([lownoise(3600.0*5.0),buffer_source])
> ```

Hi @RoyWiggins I tested your script, it plays hissing sound for few hours then plays the buffered audio for couple of hours then switches to hissing sound again at the start of the hour. I don't know why it is not playing continually I want to delay the live streaming for 11 hours and 30 minutes. Could you please share your updated script?

**Comment by mylselgan** [comment]
Hi @RoyWiggins The hissing sound in between is because of source failure. I still waiting for your response to delay the source for 11 hours and 30 minutes.

**Comment by mylselgan** [comment]
It is working as expected thanks
