### ISSUE TITLE
Input External Not Restarting correctly

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#833]
Reconnecting to input.external.avi is currently not working. 

The first connection works as expected, but ending this connection, and attempting to connect again does not work, the ffmpeg process is not re-spawned.

It seems the ffmpeg process that gets set up the first time, via a /bin/sh call works as expected, but on disconnect of the streaming client the ffmpeg process ends. but the parent shell call does not.

Liquidsoap doesn't get triggered to restart the command, as i can still find the parent shell process, but without the required ffmpeg child.

Using the same test as used for the memory leak one.
```
set("frame.video.width",1280)
set("frame.video.height",720)
set("frame.video.samplerate",25)

in_cmd = "ffmpeg -v 16 -listen 1 -i rtmp://localhost:12345/live/test -f avi -vf format=rgb24 -vcodec rawvideo -r #{video.frame.rate()} -s #{video.frame.width()}x#{video.frame.height()} -acodec pcm_s16le -ar 44100 pipe:1"
out_cmd = "ffmpeg -i pipe:0 -f null /dev/null"

s = input.external.avi(restart_on_error=true, in_cmd)

output.external(fallible=true, %avi, out_cmd, s)
```
Connect with this, stop it, then try to run it again
```
ffmpeg -re -f lavfi -i testsrc -f lavfi -i anullsrc -vf scale=1280:720 -c:v libx264 -profile:v baseline -pix_fmt yuv420p -c:a libfdk_aac -b:a 128k -bsf:a aac_adtstoasc -f flv rtmp://localhost:12345/live/test
```

**Comment by smimram** [comment]
Even simpler script:
```
cmd = "sleep 2"
s = input.external.rawvideo(restart_on_error=true, cmd)
s = mksafe(s)
output.sdl(s)
```

@toots it seems that duppy does not call the `process` function when the pipe is closed...
