### ISSUE TITLE
How to append or prepend to selected tracks only?

### ISSUE THREAD

**Issue by tmladek** [savonet/liquidsoap#835]
Is there a way to prepend or append not to all tracks in a source, but only to tracks based on their metadata - or better, a function?

I'd like to only preface tracks with a specific artist or tracks longer than some duration with a "jingle" or an announcement.

I have a feeling there may be some functional programming magic possible - i.e. filter out the references to tracks from a playlist, but as playlists are relatively "inaccessible" sources, I don't see a way how to.

Thanks in advance!

**Comment by dhannyz** [comment]
@tmladek you could probably set up 2 playlist with the same source directory, with different `check_next` methods that filter your playlists into a source to apply the jingle to, and one not to. Then you could recombined those playlists with something like a `random()` or `rotate()`

**Comment by smimram** [comment]
@dhannyz solution is nice. Another option would be to have a
- `fallback(track_sensitive=false, jingles, main)` where `jingle` is a `request.queue`
- you use `on_metadata` to call a function when there is a metadata on `main`
- when the metadata is right you push a jingle in the `jingle` queue

**Comment by smimram** [comment]
Some solutions were proposed. Also `prepend` takes as argument a function which takes the metadata of the current track in account: if, based on the metadata, you don't want to prepend anything, this function can return `source.fail`.
