### ISSUE TITLE
Buffer empty during track transition

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#836]
**Describe the bug**
Sometimes, when a buffered source transits between tracks, the buffer is briefly empty, even if the source uses local files which can't fail.

**To Reproduce**
`liquidsoap 'output.dummy(mksafe(buffer(mksafe(request.dynamic({request.create("/backup.mp3")})))))'`

```
2019/06/17 17:38:53 [request.dynamic_6919:3] Prepared "/backup.mp3" (RID 6).
2019/06/17 17:38:53 [decoder:3] Method "FFMPEG" accepted "/backup.mp3".
2019/06/17 17:38:55 [warp_prod_6923:3] Buffer emptied, start buffering...
2019/06/17 17:38:55 [mksafe:3] Switch to safe_blank with forgetful transition.
2019/06/17 17:38:55 [mksafe:3] Switch to warp_prod_6923 with transition.
2019/06/17 17:38:56 [request.dynamic_6919:3] Finished with "/backup.mp3".
2019/06/17 17:38:56 [request.dynamic_6919:3] Prepared "/backup.mp3" (RID 7).
2019/06/17 17:38:56 [decoder:3] Method "FFMPEG" accepted "/backup.mp3".
2019/06/17 17:38:58 [warp_prod_6923:3] Buffer emptied, start buffering...
2019/06/17 17:38:58 [mksafe:3] Switch to safe_blank with forgetful transition.
2019/06/17 17:38:58 [mksafe:3] Switch to warp_prod_6923 with transition.
```

**Expected behavior**
The transition between the tracks should be without switching to `safe_blank`.

**Version details**
 - OS alpine
 - Version 1.4.0-beta1+scm

**Comment by toots** [comment]
Hmm. Why are using a `buffer` here?

**Comment by toots** [comment]
I'm gonna close this for now. I believe that it stems from an incorrect use or understanding of what `buffer` does.

`buffer` creates an asynchronous, buffered interface between the original source, via a `producer`, and the buffered source, via a` consumer`. It was mainly added to create an interface for sources with different clocks.

There are various things to consider when using it outside of the different clock context. If I understand the code well, if used in within the same clock, the whole operation is synchronous, leading to a buffer that contains just one frame in advance, which would explain what you are seeing.

Thus, coming back to my original question: why a `buffer` here? :-)

**Comment by toots** [comment]
Ok, my bad, you did point to something legit. The buffer was entering buffering mode between track change, which does not make sense. Fixed now, thanks!

**Comment by Yamakaky** [comment]
Naisu!

**Comment by Yamakaky** [comment]
SGTM on beta2
