### ISSUE TITLE
How to export Metadata to text file?

### ISSUE THREAD

**Issue by Euguar** [savonet/liquidsoap#837]
Hi!
Is there a function that create a playlist log file?
How can I export each Metadata value of played files to text file?

Ex: Last played songs in `playlist.txt`:
```
Artist - Title
Second Artist - Second Title
Third Artist - Third Title
Another Artist - Another Title
Yet Another Atrist - Yet Another Title
...
and etc.
```

Thanks much! And have a nice day!

**Comment by Yamakaky** [comment]
You can use `on_track` to detect new tracks. I don't think you can write to arbitrary files, so you could use `log.info` and grep the log file as a hack.
I personally use `http.post` and do all the processing in a python controller.

**Comment by smimram** [comment]
In fact, you can write to arbitrary files with `file.write`. I would do something like
```
def write(m) =
  ignore(file.write(data="#{m[\"artist\"]} - #{m[\"title\"]}\n", append=true, "playlist.txt"))
end

s = playlist(...)
s = on_metadata(write, s)
output.icecast(..., s)
```

**Comment by Yamakaky** [comment]
Nice!

**Comment by Euguar** [comment]
Hot! 💣 THX so much!!!
