### ISSUE TITLE
Reconsider the pretty printing of getters

### ISSUE THREAD

**Issue by dbaelde** [savonet/liquidsoap#841]
Currently the following two types are both printed as `({float})->{float}`:
```
1. ('a)->'b where 'a and 'b are either float or ()->float
2. ('a)->'a where 'a and 'b are either float or ()->float
```
Also, the next two are both printed as '()->{float}':
```
3. ()->'a where 'a is float or ()->float
4. ()->?a where ?a is float or ()->float
```
What do we want for these examples? Here's a proposition:
```
1. ({float})->{float}
2. ('a)->'a where 'a is {float}
3. ()->{float}
4. ()->?{float}
```
I'm not completely comfortable with the notation {float} which does not insist on the disjunction, but this may be the price to pay to make things look simple for simple uses.

**Comment by smimram** [comment]
I like your proposal!

**Comment by smimram** [comment]
Experience seems to indicate that the current situation is fine for users (which don't want to be cluttered with details) and the proposal is not so easy to implement. Closing for now.
