### ISSUE TITLE
Any working HLS video output configuration

### ISSUE THREAD

**Issue by mrcatman** [savonet/liquidsoap#844]
Is it possible now to make a HLS video stream (which can be played in browser) using Liquidsoap? Could not make it to work now.

**Comment by toots** [comment]
For now, HLS is only limited to audio. @smimram, do you have plans to extend to video?

**Comment by smimram** [comment]
Yes, let's put that on my TODO-list :)

**Comment by smimram** [comment]
We are now accepting virtually any encoder. I have been able to `ffplay` raw avi video, more complex encoders should also work.

**Comment by smimram** [comment]
For info, my configuration is
```
s = single("test.ogv")
s = mksafe(s)
output.file.hls("/tmp/hls", [("avi",%avi)], s)
```
but of course more interesting encoders than `%avi` should be more widely supported.
