### ISSUE TITLE
lo 0.1.2 missing

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#849]
https://github.com/savonet/liquidsoap/commit/6a1874f26054bfcf775a9176761b22666ea50ba0 requires `lo` 0.1.2, but only 0.1.1 exists https://opam.ocaml.org/packages/lo/. You seem to forget to publish the version.

**Comment by smimram** [comment]
Yes, ocaml-lo was not released yet. You can `opam pin add .` in `ocaml-lo` at the moment.

**Comment by Yamakaky** [comment]
When do you plan to release it?

**Comment by smimram** [comment]
This should be there soon: https://github.com/ocaml/opam-repository/pull/14380
