### ISSUE TITLE
Seeking in mp3 files

### ISSUE THREAD

**Issue by jovadeza** [savonet/liquidsoap#853]
**Describe the bug**
I am trying to use liq_cue_in, but I get "Seek not implemented!" as result.

**To Reproduce**
radio.liq
```
radio = mksafe(playlist("music/playlist.txt"))
radio = cue_cut(radio)

output.icecast(%mp3, host="",port=8000,password="", mount="mp3", name="", description="", radio)
```

playlist.txt
```
annotate:title="Remedy",artist="Alesso",liq_cue_in="4.",liq_cue_out="20.":/music/mp3/alesso_-_remedy.mp3
```

**Expected behavior**
Let the .mp3 file start at 4 seconds from the beginning of the file.

**Version details**
 - OS: Ubuntu 18.04
 - Version: 1.3.7

**Install method**
I am using a Docker installation, with the following image: https://github.com/PhasecoreX/docker-liquidsoap

**Comment by toots** [comment]
Thanks for the report. I have just fixed it. However, you should always use `cue_cut` as close as possible to your file source, if possible right above it. Otherwise, some operators won't be able to seek properly, for instance when adding multiple sources.
