### ISSUE TITLE
Too many open files in pipe()

### ISSUE THREAD

**Issue by RecursiveGreen** [savonet/liquidsoap#865]
**Describe the bug**
It appears that Liquidsoap is not closing pipes cleanly after a song is finished playing. After ~500 songs being played, the radio crashes with the following error:
`[threads:2] Queue generic queue #5 crashed with exception Too many open files in pipe()`

If I run an `lsof -a -p <LIQUIDSOAP_PID> | wc -l`, I can get a total number of file descriptors open. Every time a new song is queued, the number goes up by two. Since Ubuntu's default limit on file descriptors is 1024, this would align with the crash every 500 songs or so.

To confirm, a listing from `lsof` shows the following:
```
[...]
liquidsoa 13126 liquidsoap   19r  FIFO    0,12      0t0 1175655 pipe
liquidsoa 13126 liquidsoap   21r  FIFO    0,12      0t0 1174420 pipe
liquidsoa 13126 liquidsoap   22r  FIFO    0,12      0t0 1176665 pipe
liquidsoa 13126 liquidsoap   23r  FIFO    0,12      0t0 1175657 pipe
liquidsoa 13126 liquidsoap   24r  FIFO    0,12      0t0 1177727 pipe
liquidsoa 13126 liquidsoap   25r  FIFO    0,12      0t0 1175949 pipe
liquidsoa 13126 liquidsoap   26r  FIFO    0,12      0t0 1174422 pipe
liquidsoa 13126 liquidsoap   27r  FIFO    0,12      0t0 1176066 pipe
liquidsoa 13126 liquidsoap   28r  FIFO    0,12      0t0 1176667 pipe
liquidsoa 13126 liquidsoap   29r  FIFO    0,12      0t0 1178101 pipe
liquidsoa 13126 liquidsoap   30r  FIFO    0,12      0t0 1177729 pipe
liquidsoa 13126 liquidsoap   31r  FIFO    0,12      0t0 1178180 pipe
liquidsoa 13126 liquidsoap   32r  FIFO    0,12      0t0 1175951 pipe
liquidsoa 13126 liquidsoap   33r  FIFO    0,12      0t0 1178306 pipe
liquidsoa 13126 liquidsoap   34r  FIFO    0,12      0t0 1176068 pipe
liquidsoa 13126 liquidsoap   35r  FIFO    0,12      0t0 1178390 pipe
liquidsoa 13126 liquidsoap   36r  FIFO    0,12      0t0 1178103 pipe
liquidsoa 13126 liquidsoap   37r  FIFO    0,12      0t0 1178495 pipe
liquidsoa 13126 liquidsoap   38r  FIFO    0,12      0t0 1178182 pipe
liquidsoa 13126 liquidsoap   39r  FIFO    0,12      0t0 1177433 pipe
[...]
```

I searched previous issues, and this is very similar to #150 , but instead of the files themselves, this appears to be pipes. 

**To Reproduce**
I'm not sure what the easiest way to try and reproduce the problem for you guys might be as my radio uses a couple of external tools to make a request.

The radio runs an external command (python script) to grab the next annotate string and another external command (python script) to report back when a song has been played. The primary data protocol in the annotate string is `s3://` since I copied my playlist to the cloud.

These might be good starting points to investigate, but I must confess that I'm not that familiar with OCaml to pin down the area of suspicion. 

**Expected behavior**
After a song is played, the proper pipes in use are closed and the radio plays uninterrupted. 

**Version details**
 - OS: Ubuntu 18.04.2 LTS
 - Version: git-current (1.4.0 beta)

**Install method**
opam + git source

**Comment by smimram** [comment]
Do you have external encoders?

**Comment by RecursiveGreen** [comment]
@smimram: I have one MP3 and two OGG [Vorbis] streams encoding to an icecast2 instance, but I'm assuming that's all done with whatever default tool Liquidsoap uses.

**Comment by smimram** [comment]
Ok, thanks! Also, a somewhat simplified version of your liquidsoap script would be helpful (without necessarily the external scripts).

**Comment by RecursiveGreen** [comment]
Here's the entirety of my script with redactions:

```
set("protocol.aws.endpoint","https://*****")
set("protocol.aws.region","*****")

# TODO: figure out calling external scripts in sandbox mode
set("sandbox.tool","disabled")

set("server.telnet",false)

set("scheduler.generic_queues",5)
set("scheduler.fast_queues",3)
set("scheduler.non_blocking_queues",3)

set("audio.converter.samplerate.libsamplerate.quality","best")

enable_replaygain_metadata ()

security = single(id="default","/home/liquidsoap/beach.ogg")

# Tweaked custom crossfade to deal with jingles..
def sprcross(~start_next=5.,~fade_in=3.,~fade_out=3.,
             ~default=(fun (a,b) -> sequence([a, b])),
             ~high=-15., ~medium=-32., ~margin=4.,
             ~width=2.,~conservative=false,s)
  fade.out = fade.out(type="sin",duration=fade_out)
  fade.in  = fade.in(type="sin",duration=fade_in)
  add = fun (a,b) -> add(normalize=false,[b, a])
  log = log(label="sprcross")

  def transition(a,b,ma,mb,sa,sb)

    list.iter(fun(x)-> log(level=4,"Before: #{x}"),ma)
    list.iter(fun(x)-> log(level=4,"After : #{x}"),mb)

    if ma["type"] == "J" or mb["type"] == "J" then
      log("Old or new file is a jingle: sequenced transition.")
      sequence([sa, sb])
    elsif
      # Do not fade if it's already very low.
      b >= a + margin and a <= medium and b <= high
    then
      log("new >= old + margin, old <= medium and new <= high.")
      log("Do not fade if it's already very low.")
      log("Transition: crossed, no fade.")
      add(sa,sb)

    # What to do with a loud end and a quiet beginning ?
    # A good idea is to use a jingle to separate the two tracks,
    # but that's another story.

    else
      # Otherwise, A and B are just too loud to overlap nicely,
      # or the difference between them is too large and overlapping would
      # completely mask one of them.
      # log("No transition: using default.")
      # default(sa, sb)
      log("Transition: crossed, fade-in, fade-out.")
      add(fade.out(sa),fade.in(sb))
    end
  end

  cross(width=width, duration=start_next, conservative=conservative,
              transition,s)
end

def spreq () =
  ret = list.hd(default="",get_process_lines("PYTHONIOENCODING=utf-8 python3 /home/liquidsoap/dj/djcontrol.py next"))
  log(""^quote(ret))
  request.create(ret)
end

def change_meta(m) =
  artist = m["artist"]
  game = m["game"]
  title = m["title"]

  log("Request ID: "^quote(m["req_id"]))
  log("Info: #{artist} #{game} #{title}")

  [("artist","#{artist}"),("title","#{title} [#{game}]")]
end

radio = request.dynamic(id="main",spreq,timeout=60.)
radio = fallback(track_sensitive = false, [radio, security])
radio = amplify(1.,override="replay_gain",radio)
radio = map_metadata(change_meta, radio)
radio = on_metadata(id="main", fun (meta) -> system("python3 /home/liquidsoap/dj/djcontrol.py played "^quote(meta["req_id"])), radio)
radio = sprcross(radio)

radio = register_flow(
  radio="Save Point Radio",
  website="http://savepointradio.net/",
  description="A softer side to video game music.",
  genre="game",
  streams=[("mp3/128k","http://stream.savepointradio.net:8000/")],
  radio)

output.icecast(%mp3,
  encoding="UTF-8", protocol="http", name="Save Point Radio",
  description="Save Point Radio - A Softer Side to Video Game Music", genre="Game Soundtrack",
  url="http://savepointradio.net/",
  host="127.0.0.1", port=8001,
  password="*****", mount="stream128.mp3",
  radio)
output.icecast(%vorbis(samplerate=44100, channels=2, quality=0.4),
  encoding="UTF-8", protocol="http", name="Save Point Radio",
  description="Save Point Radio - A Softer Side to Video Game Music", genre="Game Soundtrack",
  url="http://savepointradio.net/",
  host="127.0.0.1", port=8001,
  password="*****", mount="stream128.ogg",
  radio)
output.icecast(%vorbis(samplerate=44100, channels=2, quality=0.0),
  encoding="UTF-8", protocol="http", name="Save Point Radio",
  description="Save Point Radio - A Softer Side to Video Game Music", genre="Game Soundtrack",
  url="http://savepointradio.net/",
  host="127.0.0.1", port=8001,
  password="*****", mount="stream64.ogg",
  radio)
```

**Comment by smimram** [comment]
Side note. Unfortunately, the following simplified version of your script does not exhibit any pipe leak:
```
def spreq() =
  req = list.hd(default="",get_process_lines("echo /home/smimram/prog/savonet/liquidsoap/src/test.mp3"))
  req = "annotate:liq_cue_out=2.:#{req}"
  print("REQUEST: #{req}")
  request.create(req)
end

s = request.dynamic(id="main",spreq,timeout=60.)
s = cue_cut(s)
s = on_metadata(fun (m) -> system("echo Got metadata! My PID is #{getpid()}."), s)
out(s)
```

**Comment by smimram** [comment]
It would be very helpful if you could manage to reduce down your script to a small one such as the above one (and remove everything superfluous). As you can see above, I use `cue_cue` in order to skip tracks after 2 secs in order to accelerate the leak (but I can observe no leak here)...

**Comment by smimram** [comment]
Another hint: I could not test aws, but it might very well be that...

**Comment by RecursiveGreen** [comment]
@smimram that would make sense as I just recently converted my playlist from local files to the cloud. When I was pulling from local files, there were no issues.

I'll see if I can play with the `aws` command that `s3://` uses. If need be, I can see about making a separate protocol to pull from an s3 python library as a workaround.

**Comment by smimram** [comment]
On a side note, aws is implemented in the standard library [at the end of utils.liq](https://github.com/savonet/liquidsoap/blob/master/libs/protocols.liq#L417), it should not be too difficult for you to play with it.

**Comment by RecursiveGreen** [comment]
After attempting to remove as many variables from the issue, the simplest I can make the script to reproduce the problem is as follows:

```
set("scheduler.generic_queues",5)
set("scheduler.fast_queues",3)
set("scheduler.non_blocking_queues",3)

set("audio.converter.samplerate.libsamplerate.quality","best")

set("protocol.aws.endpoint","https://*****")

set("sandbox.tool","disabled")

out(playlist("s3.pls"))
```

With the `s3.pls` file having ten `s3://` protocol strings pointing to nothing but short jingles.

I can confirm that the issue seems to be centered around the `aws` command line application. The debug output from liquidsoap is saying that things are cleaning up nicely:
```
[...]
2019/07/09 14:52:09 [protocol.process:4] Processing .flac,aws --endpoint-url "https$(colon)//*****" s3 cp s3$(colon)//*****.flac $(output)
2019/07/09 14:52:09 [protocol.process:4] Executing aws --endpoint-url "https://*****" s3 cp s3://*****.flac "/tmp/liq-process632898..flac"
2019/07/09 14:52:09 [lang.run_process:4] Starting process
2019/07/09 14:52:09 [lang.run_process:4] Closing process's stdin
2019/07/09 14:52:12 [lang.run_process:4] Process exited with code 0
2019/07/09 14:52:12 [lang.run_process:4] Cleaning up process
2019/07/09 14:52:12 [decoder:4] Trying method "META" for "/tmp/liq-process632898..flac"...
[...]
```
However, after each `run_process` call, two pipes are being created and then abandoned.

I'm continuing to look deeper into this, but I'm curious to know if this could have been affected by the recent sandbox implementation in #785 ? I disabled it in my example script as I'm not 100% certain how to properly configure it to allow the aws call (or any other local calls).

**Comment by RecursiveGreen** [comment]
I can duplicate the results with the curl-based protocols (HTTP/HTTPS/FTP/etc).

Here's my sample script:
```
s = playlist("curl.pls")
s = map_metadata(fun (_) -> [("liq_cue_out","2.")], s)
s = cue_cut(s)
out(s)
```

and the `curl.pls`:

```
http://www.hochmuth.com/mp3/Haydn_Cello_Concerto_D-1.mp3
http://www.hochmuth.com/mp3/Tchaikovsky_Rococo_Var_orch.mp3
http://www.hochmuth.com/mp3/Vivaldi_Sonata_eminor_.mp3
http://www.hochmuth.com/mp3/Tchaikovsky_Nocturne__orch.mp3
http://www.hochmuth.com/mp3/Haydn_Adagio.mp3
```

Since this happens with the protocols making an external call, I'm going to see if I can simultaneously find the leak and learn OCaml. 😉

**Comment by toots** [comment]
Thanks for the minimal report, it helped so much! The bug should be fixed now.

**Comment by RecursiveGreen** [comment]
I pulled/recompiled this morning and confirmed the pipes are no longer leaking.

Thanks @toots and @smimram !
