### ISSUE TITLE
Add lookahead for `compress`

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#869]
**Is your feature request related to a problem? Please describe.**
Limiters in particular use it a lot to prevent clipping.

**Describe the solution you'd like**
Add a `{float}` parameter to `compress`. The compressor keeps N ms of audio in memory and use that to trigger the negative gain before the peak and not after, which is mostly useful for limiters.

**Describe alternatives you've considered**

**Comment by smimram** [comment]
This was added in 308c483367f73f4a5004e73297f13d840ef5c014.
