### ISSUE TITLE
Incorrect samplerate in wav header

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#870]
**Describe the bug**
The wav header contains incorrect samplerate info.

**To Reproduce**
`liquidsoap 'set("frame.audio.samplerate", 48000); output.file(%wav, "out.wav", blank())'`

**Expected behavior**
`ffmpeg out.wav` shows 44100Hz, not 48000Hz.

**Version details**
 - OS alpine
 - Version 1.4.0 rc2

**Install method**
opam

**Comment by toots** [comment]
The `%wav` encoder defaults to `44100`:
```
% liquidsoap 'print(%wav)'
%wav(samplerate=44100,channels=2,samplesize=16,header=true)
```
I have to think about this for a second. Your suggestion seems reasonable but it would introduce a variation in that a script may behave differently depending on settings not necessarily super easy or explicit for the user..

**Comment by Yamakaky** [comment]
Oh OK, I thought it worked that way.

**Comment by Yamakaky** [comment]
Yeah : `samplerate` is not documented for wav.

**Comment by smimram** [comment]
FWIW I'd be in favor of using the Liquidsoap internal samplerate for %wav by default, this seems the most sensible default value and avoids potential resampling.

**Comment by toots** [comment]
Looks like there's a consensus to change it here so I'll go ahead and implement the changes.
