### ISSUE TITLE
bandwidth parameter for @fdkaac encoder?

### ISSUE THREAD

**Issue by mantistob** [savonet/liquidsoap#873]
The docs (and example) show a bandwidth parameter, is this still supported?  It's considered invalid syntax for my LiquidSoap 1.3.7 build.  Does it require a compile module?

**Comment by dhannyz** [comment]
@mantistob yeah you will probably need to be on the master, as well as pinning the ocaml-fdkaac repo.
Bandwidth was only recently added

**Comment by smimram** [comment]
Yes, this was introduced in commit de9e7397573d0c7ec955e6926e255c45d90a5237.
