### ISSUE TITLE
Empty output file created when source starts failling

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#876]
**Describe the bug**
When created, a `output.file(fallible=true)` creates the output file even if the output starts as failing. The file is created empty. It's especially visible on my local dev env, where I can start/stop my setup without using the input, which creates a lot of empty files.

**To Reproduce**
`liquidsoap 'output.file(fallible=true, %wav, "out.wav", fail())'; ls out.wav`

**Expected behavior**
The file should be created when the source first starts outputting.

**Version details**
 - OS: alpine
 - Version beta2

**Install method**
opam

**Comment by toots** [comment]
Fixed, thanks for reporting, that was a good one!

**Comment by Yamakaky** [comment]
Naisu, thanks for the fix, that was a good one!
