### ISSUE TITLE
Can't compile current dev git

### ISSUE THREAD

**Issue by autonarcosis** [savonet/liquidsoap#882]
[geoff@penny liquidsoap]$ opam pin add liquidsoap .
[liquidsoap.1.3.7] synchronised from git+file:///home/geoff/Work/liquidsoap#master
liquidsoap is now pinned to git+file:///home/geoff/Work/liquidsoap#master (version 1.4.0)

Sorry, no solution found: there seems to be a problem with your request.

[NOTE] Pinning command successful, but your installed packages may be out of sync.

**Comment by smimram** [comment]
You should do first:
```
cd ocaml-mm
opam pin add .
```
(this will also pin ocaml-mm to the latest version, which is required by the dev Liquidosap)

**Comment by autonarcosis** [comment]
Works. Thanks.
