### ISSUE TITLE
Default parameters for encoders

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#89]
From the ML:

> Hello,
> 
> What are the default for each encoding format ?
> 
> For example %aac+ without specification has a bitrate of 64

Thanks for asking. Another user brought this recently and I still plan
on updating the doc to be more explicit.

Meanwhile, you can always print a long version of any encoder,
containing default values this way:

```
~ liquidsoap 'print(%aac+)'
  %aac+(channels=2,samplerate=44100,bitrate=64)
```

**Comment by toots** [comment]
Not RC..
