### ISSUE TITLE
on_metadata being called twice

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#903]
The following script prints title lines two by two, whereas there is no good reason for this. The bug is either in `chop` or `on_metadata`...:

```
s = sine()
s = chop(duration=2., metadata=[("title", "The Title")], s)
def f(m) =
  print(m["title"])
end
s = on_metadata(f, s)
output.dummy(s)
```

**Comment by dhannyz** [comment]
A small chance this might be related to an issue ive been having. Where on_metadata and map_metadata are triggered repeatedly, as fast as possible for a short duration during the transition between source playlists. Im yet to document this, it causes no perceivable side effect in the stream, just a spammy log
