### ISSUE TITLE
input.hls unable to read locally from output.harbor.hls

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#911]
It seems there's a stray "\r" at the end of the url and a local 
`in = input.hls("http://localhost:8000/test.m3u8")` 
fails with errors similar to
`Nonexistent file or ill-formed URI "aac_64.m3u8\r"!`

Meanwhile remote access via VLC plays fine

**Comment by smimram** [comment]
I just tried and managed to successfully play the resulting HLS stream. Was there some recent changes regarding this?

The server
```
s = playlist("~/Music/misc")
s = mksafe(s)
output.harbor.hls([("music", %mp3)], s)
```
the player
```
out(input.hls("http://localhost:8000/music.m3u8"))
```

**Comment by dhannyz** [comment]
Add more than one encoding to the HLS adaption, so their is a sub-playlist.

Also there was another, related issue, with not prepending the full domain to the playlist entries (usually they are relative URI's to the main manifest and do not reference the FQDN)

This was causing liquidsoap to look in its working directory, with the wrong protocol
I had a play at fixing this a bit, and got it working more generally.
I the regex matching also needs to account for \n  \r\n  and even  \r  (old macs?)
