### ISSUE TITLE
HLS: In-Band Timed Metadata?

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#914]
It would be amazing if liquidsoap could output in-band metadata as a data track in HLS.
I believe there is a spec floating around, and streaming services like wowza offer this.

This would be said spec https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/2/2.html#//apple_ref/doc/uid/TP40010435-CH2-DontLinkElementID_1
Apple seems to have OSX tools for inserting this type of metadata. But i havent been able to find any public tools

**Comment by dhannyz** [comment]
This would be said spec https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/2/2.html#//apple_ref/doc/uid/TP40010435-CH2-DontLinkElementID_1
Apple seems to have OSX tools for inserting this type of metadata. But i havent been able to find anything open source

**Comment by toots** [comment]
This is implemented now! See: https://github.com/savonet/liquidsoap/pull/3154
