### ISSUE TITLE
Playlist rotation

### ISSUE THREAD

**Issue by dbeiner** [savonet/liquidsoap#919]
Hello Liquidsoap team!

I would like to know if it's possible to do a playlist rotation ?

By example :
1. Fresh hits
2. Top Hits
3. Jingle
4. Classics
5. [repeat]

I'm using Liquidsoap via AzuraCast.

Thank you & BR.

**Comment by smimram** [comment]
Yes, the [rotate](https://www.liquidsoap.info/doc-dev/reference.html#rotate) operator is doing exactly that!

**Comment by dbeiner** [comment]
Yes! Found the doc on Liquidsoap website!

Thank you!

**Comment by sonyarianto** [comment]
@smimram 
I have script like this.

```
set("log.level", 5)

songs = crossfade(playlist(mode="randomize", reload=10, reload_mode="watch", "media-files"))
jingles = playlist(mode="randomize", reload=10, reload_mode="watch", "id-files")

radio = rotate(weights=[1, 2], [jingles, songs])

output.alsa(fallible=true, radio)
```

My expectation is the random jingle will appear after 2 songs, but actually jingle only play in the beginning start of the script after that never played again.

How to make it like my expectation.

Thanks in advance.
