### ISSUE TITLE
Behavior of list.remove

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#922]
Currently, the doc of `list.remove` says
```
Remove a value from a list.
```
but we only remove the first occurrence of a value, i.e.,
```
list.remove(1, [1,2,1,1]) = [2,1,1]
```
is this really what we want: either the doc should make this clear or the implementation should be changed to remove all occurrences.

**Comment by smimram** [comment]
PS: I would be in favor of removing all occurrences...

**Comment by smimram** [comment]
and even worse, `list.remove` is reversing the list....

**Comment by StarveTheEgo** [comment]
I believe `list.remove` must remove element **by index**, while `list.filter` can handle removing by values.
This is how its done in many languages and this is what i personally expect from function named `list.remove`

**Comment by smimram** [comment]
For now, I have specified that this removes the first occurrence since, as you notice, `list.filter` can be used otherwise. And this has the advantage of not breaking anything.

As you do, I still find this function weird and not doing the expected thing. I would simply remove it from the standard library, unless someone is actually using it...

**Comment by StarveTheEgo** [comment]
I just googled some references,
- in Python it removes only first occurence
- in C++ it seems to remove all the occurences
- In PHP / Javascript / LUA you have to remove it by index only, there is no remove() functionality

Anyway, i do not use `list.remove` here, thus cannot bring any use cases too :(

**Comment by smimram** [comment]
I guess this is ok for now. Closing.
