### ISSUE TITLE
[HLS] BANDWIDTH parameter in master playlist is not conform to RFC

### ISSUE THREAD

**Issue by mbugeia** [savonet/liquidsoap#925]
**Describe the bug**
 
https://tools.ietf.org/html/rfc8216#section-4.3.4.2

" If all the Media Segments in a Variant Stream have already been
      created, the BANDWIDTH value MUST be the largest sum of peak
      segment bit rates that is produced by any playable combination of
      Renditions."
"  If the Master Playlist is to be made available before all Media
      Segments in the presentation have been encoded, the BANDWIDTH
      value SHOULD be the BANDWIDTH value of a representative period of
      similar content, encoded using the same settings."

For now AVERAGE-BANDWIDTH and BANDWIDTH are set to the same value which is the exact bitrate. Most players are fine with this but it cause issue with some Apple device. A simple resolution would be to add some margin to theses number. The AVERAGE-BANDWIDTH is fine but optionnal.
In practice theses values are fine 
32000 -> 40000
96000 -> 110000
192000 -> 220000

**To Reproduce**

Start a HLS stream with 3 aac variant , 32k, 96k, 192k.
Master playlist is:
```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=32000,BANDWIDTH=32000,CODECS="mp4a.40.29"
fip_aac_lofi.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=96000,BANDWIDTH=96000,CODECS="mp4a.40.5"
fip_aac_midfi.m3u8
#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=192000,BANDWIDTH=192000,CODECS="mp4a.40.2"
fip_aac_hifi.m3u8
```

**Expected behavior**

```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=40000,CODECS="mp4a.40.29"
fip_aac_lofi.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=110000,CODECS="mp4a.40.5"
fip_aac_midfi.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=220000,CODECS="mp4a.40.2"
fip_aac_hifi.m3u8
```

**Version details**
 - Debian
 - Version master

**Install method**
debian package

**Comment by toots** [comment]
Hi @mbugeia. I'm not sure yet how to properly fix that. Fixed audio bitrate should be the exact bandwidth, I'm not too comfortable adding magic numbers there. I'm pushing the removal of AVERAGE, though, since it's optional.

**Comment by toots** [comment]
I'm marking this one as fixed. Users can override the parameter to set whatever works.

**Comment by mbugeia** [comment]
I agree, for reference it can be set with streams_info parameter of output.file.hls.

**Comment by frant1** [comment]
Hello ! Since the version 2 of Liquidsoap, the "streams_info" was deleted of "output.file.hls" and the bandwidth are still wrong..
For exemple, a 64kbps stream (HE-AACv2) give me a "Variant bitrate" of 70400 and that in the main playlist :

#EXT-X-STREAM-INF:BANDWIDTH=70400,(...)

Would you have a tips to fix it ? I would like to have my streams setted in a clean way.

Best regards,
Antoine

**Comment by frant1** [comment]
Thanks a lot, it works !

Best regards
