### ISSUE TITLE
set("frame.audio.samplerate",48000) not respected

### ISSUE THREAD

**Issue by dhannyz** [savonet/liquidsoap#933]
Previous version not impacted `Liquidsoap 1.4.0+git@da2bd635`
Between then and now, something has caused the setting to be ignored and default to 44100

**Comment by smimram** [comment]
What do you mean exactly by ignored? The following indeed does print 48000:

```
set("frame.audio.samplerate",48000)
print(get(default=0,"frame.audio.samplerate"))
```

**Comment by dhannyz** [comment]
@smimram 
I get `2019/08/26 15:44:59 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz master.`
at the beginning of logs.
ffmpeg via output.external is detecting 44100. and my crazy high CPU usage is all pointing to this setting not being respected.
As mentioned, a previous version at that git commit above does not exhibit this behaviour and correctly sets 48k, and CPU usage is much lower (about 1/10th).
I would not trust that above print as a test

**Comment by smimram** [comment]
This is not necessarily relevant: this might be printed before the change of configuration is evaluated.

**Comment by dhannyz** [comment]
Why then is there such a verry large difference in my CPU usage using the exact same configuration on the same hardware, between that previous commit and the current master. combined with the result shown in ffmpeg it seems resampling is occuring where it is not need. The cases where im seeing this i have a source input stream at 48k, being transcoded to multiple output formats, also in 48k.

**Comment by dhannyz** [comment]
@smimram i just backed 48000 in as the default in the frame.ml source, and achieved a CPU usage drop from 100% on both cores, to 20% on each

**Comment by smimram** [comment]
OK let's try this:
```
set("frame.audio.samplerate",48000)
print(get(default=0,"frame.audio.samplerate"))
output.dummy(blank())
```
From what I understand, the instantiation of the source `blank` is forcing the evaluation of the frame at https://github.com/savonet/liquidsoap/blob/master/src/source.ml#L488 at least the memo is not taking the `set` values in account...

**Comment by smimram** [comment]
Are you use it used to work well? If so it would be quite helpful if you could bissect...

**Comment by dhannyz** [comment]
I have 4 frontends running, 2 with other code running, at the `da2bd635` commit. and 2 with a recent master. The comparison is as i've explained, running the exact same scripts. In fact i had to disable some output formats (ogg vorbis) as the CPU was no longer capable, due to the resampling. Heading to bed now but can look at bisecting later.

**Comment by smimram** [comment]
Ok, so this is quite subtle. The [culprit is here](https://github.com/savonet/liquidsoap/blob/master/libs/video.liq#L100): when parsing `%avi`, we make an avi encoder which triggers the evaluation of the audio rate...

If you comment this line, everything is fine...

**Comment by smimram** [comment]
I have proposed a reasonable PR,  but we will inevitably face the problem again...

**Comment by dhannyz** [comment]
@smimram something to note. I had this behaviour both when using AVI, and when using pure audio decoders/encoders.
I shall of course test my scripts again now on the updated master.

**Comment by dhannyz** [comment]
@toots could you re-open this. It has not fixed the problem in general
