### ISSUE TITLE
Documentation contains severely broken markdown

### ISSUE THREAD

**Issue by Nirei** [savonet/liquidsoap#948]
**Describe the bug**
The page https://www.liquidsoap.info/doc-1.3.7/harbor_http.html contains many broken markdown sections that make it very difficult to read.

**To Reproduce**
Browse said documentation page.

**Expected behavior**
The page is adequately formatted and readable.

**Version details**
 - OS: Firefox 60.8.0esr from Debian 9 GNU/Linux
 - Version: 1.3.7

**Install method**
N/A

**Comment by Nirei** [comment]
Apparently this is fixed in the master branch. I'll just read it from there.

**Comment by smimram** [comment]
I have fixed this page but, yes, there are other broken ones which should be all fixed in the dev version.
