### ISSUE TITLE
Export currently playing song metadata to JSON

### ISSUE THREAD

**Issue by MaddyCrowle** [savonet/liquidsoap#954]
Hello, guys! Your product is amazing, but however, I didn't find answer on my question in the documentation.

Is it possible to write JSON file with audio metadata (artist, title, album, cover art! - important) each time next song starts?

**Comment by smimram** [comment]
Yes, you should use `on_metadata` to have a function called every time a metadata is received and then convert metadata to JSON with `json_of` and write it to a file with `file.write`.

**Comment by MaddyCrowle** [comment]
Could you please point to a full documentation where I can read about language syntax and all it's functions. I didn't manage to find any information about `on_metadata` via Google.

**Comment by smimram** [comment]
All the functions are documented here: https://www.liquidsoap.info/doc-dev/reference.html

For instance [on_metadata is here](https://www.liquidsoap.info/doc-dev/reference.html#on_metadata).

**Comment by MaddyCrowle** [comment]
Oh, it seems I needed to pick "dev" in dropdown list, thanks!
By using `file.write` error appears: "the variable file.write used here has not been previously defined". Why might it be?

**Comment by MaddyCrowle** [comment]
`is_file_saved = file.write(data="123", append=false, perms=420, "/path-to-file/test.txt")`

and nothing happens... no file, no errors. What am I doing wrong?

**Comment by smimram** [comment]
In a shell:
```
$ liquidsoap 'print(file.write(data="123\n", append=false, perms=420, "/tmp/test"))'
true
No output defined, nothing to do.
$ cat /tmp/test 
123
```
What do you get?

**Comment by smimram** [comment]
Yes, not that I print the result:
```
print(file.write(data="123\n", append=false, perms=420, "/tmp/metatest"))
```
you could also ignore it:
```
ignore(file.write(data="123\n", append=false, perms=420, "/tmp/metatest"))
```
or assign it to a variable:
```
b = file.write(data="123\n", append=false, perms=420, "/tmp/metatest")
```

**Comment by MaddyCrowle** [comment]
`b = file.write(data="123\n", append=false, perms=420, "/tmp/metatest")`

now I've got

```
Line 115, char 0:
Warning 4: Unused variable b
No output defined, nothing to do.
$ cat /tmp/metatest
cat: /tmp/metatest: No such file or directory
```

**Comment by smimram** [comment]
The problem here is that Liquidsoap detects that you store the result in `b` but do not use it. Add `print(b)` afterward or use `ignore` as above.

**Comment by MaddyCrowle** [comment]
Yes, it works, now file is created. So Warnings blocks any further code execution?

**Comment by smimram** [comment]
Yes, before running the program, Liquidsoap performs some sanity checks.

**Comment by MaddyCrowle** [comment]
Alright, now metadata itself.
I've wrote this code:
```
def apply_metadata(m) =
  title = m["title"]
  artist = m["artist"]
  "#{artist} - #{title}"
end

#Work around metadata of currently playing song
mymeta = on_metadata(apply_metadata, airtime)
mymeta = json_of(mymeta)
```
But I've got error:
```
At line 112, char 21-35:
Error 5: this value has type
  (...) -> string (inferred at line 1 char 0 - line 5 char 3)
but it should be a subtype of
  (...) -> unit
```

What am I doing wrong here and what is the **unit** type?

**Comment by smimram** [comment]
The unit type is "nothing": function `apply_metadata` is supposed to return nothing, whereas here it returns a string.

**Comment by MaddyCrowle** [comment]
oh, unit is void, ok I understand. And how to write it in right way, could you help please?

if I remove `"#{artist} - #{title}"` it says:
```
Line 3, char 2:
Warning 4: Unused variable artist
```

**Comment by smimram** [comment]
yes, because you define the variable `artist` without using it :)

**Comment by smimram** [comment]
Here you go for the solution:
```
s = mksafe(playlist("~/Music"))

def f(m)
  print("got metadata!")
  data = json_of(m)^"\n"
  ignore(file.write(data=data, append=false, perms=420, "/tmp/metatest"))
end

s = on_metadata(f, s)
out(s)
```

**Comment by MaddyCrowle** [comment]
> yes, because you define the variable `artist` without using it :)

I understand that :) I just couldn't figure out how to write it then if I shall return void but I need to form an array to convert it to json. Now, having studied your code, I got it. Thanks a lot for help and example! Now it works as I needed.
