### ISSUE TITLE
Bad file descriptor in select()

### ISSUE THREAD

**Issue by AzatGaliev** [savonet/liquidsoap#96]
Hi everyone!
I have a trouble with my liquidsoap: after some minutes from starting liquidsoap falls with that message in logs: "Queue generic queue #1 crashed with exception Bad file descriptor in select()". Such bug there is on last code from repo and on the latest bin package from ubuntu repository (1.0.0). Please help me! It's very important for me!
Thank you, guys!

**Comment by smimram** [comment]
The problem is not clear, please reopen if you want to provide more information.
