### ISSUE TITLE
Tools for binary data

### ISSUE THREAD

**Issue by MaddyCrowle** [savonet/liquidsoap#960]
As I mentioned [here](https://github.com/savonet/liquidsoap/issues/958), `metadata_block_picture` is base64 encoded binary data. So if someone need to extract picture and it's parameters from this metatag, after base64 decoding one need to work with it according to [xipth.org flac standards](https://xiph.org/flac/format.html#metadata_block_picture).

I found base64 encoding/decoding functions, but does Liquidsoap has tools for working with binary data? Like unpack("N*", ...) or something.

Actually, i already managed to extract data with another language outside of liq app, but it would be better and more convinient to do all stuff in one place with Liquidsoap.

**Comment by smimram** [comment]
Good idea! I'll try to add that soon.

**Comment by smimram** [comment]
@MaddyCrowle You now have `string.sub` and `string.binary.to_int`. Do you need more than that?

**Comment by MaddyCrowle** [comment]
@smimram Sounds fantastic, thanks a lot! I'll check and report here

**Comment by smimram** [comment]
I even merged functions to parse APIC in #987 , I guess we can safely close this now.

**Comment by MaddyCrowle** [comment]
Sorry for my super long delay, I was totally busy on another project. Now I came back and stuck: liquidsoap 1.5.0 requires duppy 0.8.1, but I didn't manage to find this version anywhere, it says that 0.8.0 is the latest. Could you tell me please where I should get it?

**Comment by smimram** [comment]
The most simple thing to do is to use liquidsoap-full as indicated [at the end of this page](https://www.liquidsoap.info/doc-dev/install.html#latest-development-version):
```
git clone https://github.com/savonet/liquidsoap-full.git liquidsoap
cd liquidsoap
make init
cp PACKAGES.minimal PACKAGES
./bootstrap
./configure
make
```
It will download all our packages (including Liquidsoap) and build them all.

**Comment by MaddyCrowle** [comment]
on the `./configure` stage I faced couple of errors, like:

```
****** Configuring ocaml-mm

./configure: line 47: cd: ocaml-mm: No such file or directory
./configure: line 52: cd: ocaml-mm: No such file or directory

****** Configuring liquidsoap

./configure: line 41: liquidsoap/configure-with-options: No such file or directory
./configure: line 42: cd: liquidsoap: No such file or directory
```
I checked these paths manually, they exists.

`./make` has failed.

**Comment by MaddyCrowle** [comment]
could you please add 2 more functions:
1. from binary to NUL-padded string
2. from binary to unsigned long (always 32 bit, big endian byte order)

Many thanks!

**Comment by smimram** [comment]
null-terminating a string is easy, I just added:
``
def string.null_terminated(s)
  s ^ "\000"
end
```

**Comment by smimram** [comment]
For 2, you can use
```
string.binary.to_int(little_endian=false, binary)
```

**Comment by MaddyCrowle** [comment]
reporting my result: everything works as expected. Thanks a lot!
