### ISSUE TITLE
How to uninstall old versions?

### ISSUE THREAD

**Issue by Moonbase59** [savonet/liquidsoap#967]
**Describe the bug**
I installed Liquidsoap 1.3.7 on Ubuntu 14.04 using opam and _then_ realized I already had version 1.1.1 (Ubuntu package) and 1.2.1 (labelled [system] by opam) installed—years and years ago.

So I removed 1.1.1 using Synaptic but opam still shows me "1.2.1 [system]". Apparently I had built that from source in 2015-2016 and cannot for the life of me find out how to cleanly remove it.

The old makefiles don’t apparently offer an "uninstall" target.
Any ideas how I can safely get rid of the old version 1.2.1? Unfortunately 1.2.1 seems to get called when using `liquidsoap --daemon some-script.liq` but I need post-1.3.1 features in my script.

When I try to start via the script
```bash
./start-liquidsoap.sh
```
I get:
```
no more csLADSPA plugins
At line 10, char 25-26: cannot apply that parameter because the function
  (at line 10, char 16) has no argument labeled "default"!
```
(Line 10 of `test-02.liq` contains a `list.hd(default="", lines)` which I believe has been changed in 1.3.1 or so to require the `default` param.)

The commands from the `start-liquidsoap.sh` script run fine when I enter them in the bash:
```bash
cd ~/Musik/liquidsoap/
liquidsoap --daemon test-02.liq
```

**Expected behavior**
A clear and concise description of how to remove old versions that were manually compiled.

**Version details**
 - OS: Ubuntu Studio
 - Version 14.04.5

**Install method**
1st install: Ubuntu package (1.1.1)
2nd install (on top): manual compile around 2015-2016 (1.2.1)
3rd install (on top, accidentally): opam (1.3.7)

Thanks for your help! (And please don’t bash me because I still _have_ to use this one old machine …)

**Comment by Moonbase59** [comment]
Found half a solution, but would still like help for removing the old 1.2.1 version:

1. `opam uninstall liquidsoap`
2. `eval $(opam env)`
3. `opam install liquidsoap`
4. `eval $(opam env)`

seems to help, but only until I close and reopen the terminal. Can these things be made permanent?

**Comment by smimram** [comment]
The opam settings can be made permanent by running `opam init` (again) and answering yes when it asks to add some stuff in `.bash_profile`.

**Comment by Moonbase59** [comment]
Ah, good news, thanks!
