### ISSUE TITLE
output %fdkaac lead to Error 12: Unsupported format!

### ISSUE THREAD

**Issue by tzumbrunnen** [savonet/liquidsoap#973]
**Describe the bug**
transcoding a high bit mp3 stream to `output.icecast(%fdkaac(channels=2,bitrate=64)` lead to the following Error in Windows CMD

```
At line 32, char 15-45:
Error 12: Unsupported format!
You must be missing an optional dependency.
```

**To Reproduce**
transcode a a high bit mp3 stream to `output.icecast(%fdkaac(channels=2,bitrate=64)`
Line 32, char 15-45 : `output.icecast(%fdkaac(channels=2,bitrate=64)`

**Expected behavior**
a working output as it worked before in Version `1.3.7`

**Version details**
 - OS: Window 10 64bit
 - Version `1.4.0`

**Install method**
from the currently released `1.4.0`. zip File

**Common issues**
n/a

**Comment by toots** [comment]
Thanks for the report. The fdkaac encoder must have been missed when building the image, I'll look into it.

**Comment by toots** [comment]
Ok, I've uploaded fixed builds. Also happy to confirm that fdkaac encoding is working again!

**Comment by KruegerDead** [comment]
with %opus output same problem on win64 release.
```
Error 12: Unsupported format!
You must be missing an optional dependency.
```

**Comment by toots** [comment]
Yeah looks like I forgot to update the `%opus` binding on windows as well.. Rebuilding..

**Comment by krangm** [comment]
@toots most likely its related too #977 
can you please fix
thank you

**Comment by toots** [comment]
Builds updated, thanks for reporting.
