### ISSUE TITLE
fdkaac not working anymore

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#975]
I did some work on fdkaac, and now the minimal example is working again (see <https://github.com/savonet/ocaml-fdkaac/issues/4>), but it seems that Liquidsoap is still not working.

**Comment by smimram** [comment]
My test script:
```
s = playlist("~/Music")
output.file(fallible=true,flush=true,%fdkaac(channels=2,bitrate=64),"/tmp/x.aac",s)
```

**Comment by smimram** [comment]
@toots even with your latest fix on ocaml-fdkaac the above script is not working for me, is it for you?

**Comment by toots** [comment]
It is here.. Are you sure you're running against the right version of the binding?

**Comment by autonarcosis** [comment]
Working for me here using the latest git from the ocaml-fdkaac.

**Comment by toots** [comment]
Good to know, thks!
