### ISSUE TITLE
output.icecast %mp3.vbr gives Error 12: Unsupported format!

### ISSUE THREAD

**Issue by krangm** [savonet/liquidsoap#977]
**Describe the bug**
im using `liquidsoap-master` package from debian repo and after recent update stream is not working anymore.
`output.icecast(%mp3.vbr ... )` gives an error:
```At line 18, char 1-9:
Error 12: Unsupported format!
You must be missing an optional dependency.
```

**To Reproduce**
install `liquidsoap-master` package from debian repo
try to stream with `output.icecast(%mp3.vbr ... )`

**Expected behavior**
last package update from apt logs is
`1:1.4.0-2072~testing` -> `1:1.5.0-2101~testing`

**Version details**
 - OS: Debian
 - Version `5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux`

**Install method**
this guide
https://www.liquidsoap.info/doc-dev/install.html#debianubuntu

**Common issues**
everything was working stable for months. i was updating w/o problems

**Comment by toots** [comment]
Hi,

I'm gonna look at it but, meanwhile, I'd recommend to  install the `1.4.0` package. Work has just started on `1.5.0` and it's bound to break in many ways.

Try this:
```
apt-get install liquidsoap-1.4.0
```

**Comment by toots** [comment]
This should be fixed now!
