### ISSUE TITLE
[ERROR] The sources of the following couldn't be obtained, aborting:    - sedlex.2.1

### ISSUE THREAD

**Issue by snblitz** [savonet/liquidsoap#978]
**Describe the bug**
opam install taglib mad lame vorbis cry samplerate liquidsoap
[ERROR] The sources of the following couldn't be obtained, aborting:
          - sedlex.2.1

**To Reproduce**
opam depext taglib mad lame vorbis cry samplerate liquidsoap
opam install taglib mad lame vorbis cry samplerate liquidsoap
[ERROR] The sources of the following couldn't be obtained, aborting:
          - sedlex.2.1

**Expected behavior**

Does not error out on missing sedlex 2.1 source

**Version details**
 - OS: debian stretch
 - Version 9

**Install method**
opam, opam was install via opam curl method

**Common issues**
won't build

**Comment by smimram** [comment]
Hi, this does not really look like a but on our side but rather a mirror problem or so on opam side. Could you please try to
```
opam update
opam install taglib mad lame vorbis cry samplerate liquidsoap
```
again?

**Comment by snblitz** [comment]
Running the above commands resulted in a built liquidsoap.
So perhaps the package management system was broken at the time as you suggest.
