### ISSUE TITLE
Startup time

### ISSUE THREAD

**Issue by smimram** [savonet/liquidsoap#982]
Is there a good reason why getting the version for Liquidsoap takes almost one second?
```
$ time liquidsoap --version
Liquidsoap 1.4.0
Copyright (c) 2003-2019 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.info> for more information.

real	0m0,914s
user	0m0,862s
sys	0m0,052s
```
We should try to improve startup time...

**Comment by smimram** [comment]
It looks like a good deal of time is spent registering frei0r plugins...

Any idea about how to properly do that in background?

**Comment by toots** [comment]
I'll have to think about it. Plugins need to be registered before parsing the script..
