### ISSUE TITLE
Undefined variable https.post

### ISSUE THREAD

**Issue by mcfiredrill** [savonet/liquidsoap#997]
**Describe the bug**
Trying to use https.post, I get the error `Undefined variable https.post`.

**To Reproduce**
```
  url = "https://liquidsoap.fm"
  let (status, headers, data) = https.post(url)
  log("status: #{status}");
  log("data: #{data}");
  log("headers: #{headers}");
(reverse-i-search)`liq ': cat test_https.liq 
```

**Expected behavior**
I should be able to use https.post just like I can use http.post.

**Comment by smimram** [comment]
Which version of Liquidsoap are you using? How did you install it?

**Comment by smimram** [comment]
In particular, the https functions are compiled only if `ocaml-ssl` is detected during configure... So
```
opam install ssl
```
should help here.

**Comment by mcfiredrill** [comment]
> Which version of Liquidsoap are you using? How did you install it?

Sorry, I'm on latest git.

**Comment by mcfiredrill** [comment]
> In particular, the https functions are compiled only if ocaml-ssl is detected during configure... So

Ah gotcha...sorry maybe I should've asked on slack first. :)

**Comment by mcfiredrill** [comment]
I've got it to work after installing ocaml-ssl, thanks.
