### ISSUE TITLE
Bad handling of opam install --destdir

### ISSUE THREAD

**Issue by Yamakaky** [savonet/liquidsoap#998]
**Describe the bug**
When building liquidsoap from opam with the `--destdir` flag, the binary keeps reference to the local opam install.

**To Reproduce**
```
# opam install --destdir=/tmp/liquidsoap liquidsoap
# grep opam /tmp/liquidsoap/bin/liquidsoap
/home/opam/.opam/4.09/lib/ocaml/caml
/home/opam/.opam/4.09/.opam-switch/build/biniou.1.2.1/_build/default
/home/opam/.opam/4.09/.opam-switch/build/bjack.0.1.5/src
/home/opam/.opam/4.09/.opam-switch/build/...
/home/opam/.opam/4.09/lib
/home/opam/.opam/4.09/lib/liquidsoap/share/liquidsoap/1.4.0/bin
/home/opam/.opam/4.09/lib/liquidsoap/share/liquidsoap/1.4.0/libs
/home/opam/.opam/4.09/lib/liquidsoap/var/log/liquidsoap
/home/opam/.opam/4.09/lib/liquidsoap/var/run/liquidsoap
/home/opam/.opam/4.09/lib/ocaml
/home/opam/.opam/4.09/lib/ocaml/caml
/home/opam/.opam/4.09/lib/ogg
/home/opam/.opam/4.09/share/camomile
```

**Expected behavior**
The package in destdir should be self contained and not keep reference to the opam local install. At least that how I understand it. I'm not very familliar to opam so no idea how to fix it.

My usecase is that I use a opam docker image as first stage then copy the files from destdir in the final image. Currently, I have to also copy `.opam/4.09`, which should not be needed and adds a lot to the final image size.

**Version details**
 - OS: alpine
 - Version: opam 1.4.0

**Comment by smimram** [comment]
After discussion with @toots this is the intended behavior: destdir specifies only the installation directory, not the hardcoded paths. You should still be able to run `liquidsoap --no-pervasives /path/to/pervasives.liq`. Please reopen if this is not the case.

**Comment by Yamakaky** [comment]
Hum, what should I do then for my use case?
